Analysis Software: RICHParticleID Class Reference
RICHParticleID Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/RICHParticleID.h>
Public Member Functions
RICHParticleID (std::string richname, std::string tracksname)
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_refractive_index (float newidx)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
Private Attributes
bool _verbose
int _ievent
std::string _detector
std::string _trackmap_name
std::string _richhits_name
std::string _pidinfo_node_name
float _refractive_index
PidInfoContainer * _pidinfos
TrackProjectorPid * _trackproj
SetupDualRICHAnalyzer * _acquire
PIDProbabilities * _particleid
float _radius
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file RICHParticleID.h.
Constructor & Destructor Documentation
RICHParticleID::RICHParticleID (std::string richname, std::string tracksname)
Definition at line 38 of file RICHParticleID.C.
References _detector, _pidinfo_node_name, and _richhits_name.
Member Function Documentation
void RICHParticleID::CreateNodes (PHCompositeNode * topNode) private
Definition at line 272 of file RICHParticleID.C.
References _detector, _pidinfo_node_name, _pidinfos, PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int RICHParticleID::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 267 of file RICHParticleID.C.
int RICHParticleID::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 56 of file RICHParticleID.C.
References _ievent, _particleid, _refractive_index, _verbose, and PHWHERE.
int RICHParticleID::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 73 of file RICHParticleID.C.
References _acquire, _trackproj, CreateNodes(), and PHWHERE.
int RICHParticleID::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 97 of file RICHParticleID.C.
References _acquire, _ievent, _particleid, _pidinfos, _radius, _refractive_index, _richhits_name, _trackmap_name, _trackproj, Fun4AllReturnCodes::ABORTEVENT, PidInfoContainer::AddPidInfo(), SetupDualRICHAnalyzer::calculate_emission_angle(), PidInfo::CHARGEDKAON, PidInfo::CHARGEDPION, PidInfo::ELECTRON, SetupDualRICHAnalyzer::get_emission_momentum(), SvtxTrack::get_id(), TrackProjectorPid::get_projected_momentum(), TrackProjectorPid::get_projected_position(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), SetupDualRICHAnalyzer::get_true_momentum(), SvtxTrack::get_truth_track_id(), PHG4TruthInfoContainer::GetParticle(), PidInfoContainer::getPidInfo(), TrackProjectorPid::is_in_RICH(), PIDProbabilities::particle_probs(), PHWHERE, PidInfo::PROTON, PidInfo::set_likelihood(), and TrackProjectorPid::SPHERE.
void RICHParticleID::set_refractive_index (float newidx) inline
Definition at line 40 of file RICHParticleID.h.
References _refractive_index.
Referenced by Fun4All_RICHReco().
Member Data Documentation
SetupDualRICHAnalyzer* RICHParticleID::_acquire private
Definition at line 75 of file RICHParticleID.h.
Referenced by InitRun(), and process_event().
std::string RICHParticleID::_detector private
Definition at line 54 of file RICHParticleID.h.
Referenced by CreateNodes(), and RICHParticleID().
int RICHParticleID::_ievent private
Definition at line 51 of file RICHParticleID.h.
Referenced by Init(), and process_event().
PIDProbabilities* RICHParticleID::_particleid private
Definition at line 78 of file RICHParticleID.h.
Referenced by Init(), and process_event().
std::string RICHParticleID::_pidinfo_node_name private
Definition at line 63 of file RICHParticleID.h.
Referenced by CreateNodes(), and RICHParticleID().
PidInfoContainer* RICHParticleID::_pidinfos private
Definition at line 69 of file RICHParticleID.h.
Referenced by CreateNodes(), and process_event().
float RICHParticleID::_radius private
Definition at line 81 of file RICHParticleID.h.
Referenced by process_event().
float RICHParticleID::_refractive_index private
Definition at line 66 of file RICHParticleID.h.
Referenced by Init(), process_event(), and set_refractive_index().
std::string RICHParticleID::_richhits_name private
Definition at line 60 of file RICHParticleID.h.
Referenced by process_event(), and RICHParticleID().
std::string RICHParticleID::_trackmap_name private
Definition at line 57 of file RICHParticleID.h.
Referenced by process_event().
TrackProjectorPid* RICHParticleID::_trackproj private
Definition at line 72 of file RICHParticleID.h.
Referenced by InitRun(), and process_event().
bool RICHParticleID::_verbose private
Definition at line 49 of file RICHParticleID.h.
Referenced by Init().
The documentation for this class was generated from the following files:
analysis/blob/master/ParticleID/RICHAnalysis/RICHParticleID.h
analysis/blob/master/ParticleID/RICHAnalysis/RICHParticleID.C