Analysis Software: online_distribution/blob/master/newbasic/Cframe.h File Reference
Cframe.h File Reference
#include <stdio.h>
#include "phenixOnline.h"
#include "framePublic.h"
#include "formatError.h"
#include "frameHdr.h"
Macros
#define _FRAMES_
Functions
INLINE_P VALUE_ret getFrameHdrLength (FRAME_ptr)
INLINE_P VALUE_ret getFrameHdrVersion (FRAME_ptr)
INLINE_P VALUE_ret getFrameLength (FRAME_ptr)
INLINE_P VALUE_ret getFrameMark (FRAME_ptr)
INLINE_P LOGIC_ret setFrameHdrLength (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameHdrVersion (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameLength (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameMark (FRAME_ptr, UINT)
VALUE_ret checkFrameHdrVersion (FRAME_ptr)
INLINE_P LOGIC_ret validFrameHdr (FRAME_ptr)
INLINE_P LOGIC_ret currentFrameHdr (FRAME_ptr)
INLINE_P LOGIC_ret validFrameMark (FRAME_ptr)
INLINE_P LOGIC_ret emptyFrame (FRAME_ptr)
VALUE_ret checkFrameEndianism (FRAME_ptr frame_ptr)
INLINE_P void byteSwapFrame (FRAME_ptr frame_ptr)
PTR_ret findFrameEnd (FRAME_ptr)
PTR_ret findFrameDataStart (FRAME_ptr)
PTR_ret findFrameDataEnd (FRAME_ptr)
VALUE_ret adjustFrameLength (FRAME_ptr, UINT, UINT, LOGIC_ret)
VALUE_ret removeFramePadding (FRAME_ptr)
VALUE_ret makeFrameHdr (FRAME_ptr, UINT, UINT, UINT, UINT)
VALUE_ret getFrameDataLength (FRAME_ptr)
VALUE_ret getFrameHistoryLength (FRAME_ptr)
VALUE_ret getFrameErrorLength (FRAME_ptr)
VALUE_ret getFrameAlignLength (FRAME_ptr)
VALUE_ret getFrameSourceId (FRAME_ptr)
VALUE_ret getFrameDataType (FRAME_ptr)
VALUE_ret getFrameType (FRAME_ptr)
VALUE_ret getFrameStatus (FRAME_ptr)
VALUE_ret getFramePadding (FRAME_ptr)
VALUE_ret setFramePadding (FRAME_ptr, UINT)
VALUE_ret adjustFrameDataLength (FRAME_ptr, UINT)
VALUE_ret adjustFrameHistoryLength (FRAME_ptr, UINT)
VALUE_ret adjustFrameErrorLength (FRAME_ptr, UINT)
VALUE_ret orFrameStatus (FRAME_ptr, UINT)
LOGIC_ret setDataType (FRAME_ptr, UINT)
LOGIC_ret setFrameType (FRAME_ptr, UINT)
LOGIC_ret setSourceId (FRAME_ptr, UINT)
LOGIC_ret setFrameHistoryLength (FRAME_ptr, UINT)
LOGIC_ret setFrameErrorLength (FRAME_ptr, UINT)
LOGIC_ret setFrameAlignLength (FRAME_ptr, UINT)
LOGIC_ret setFrameStatus (FRAME_ptr, UINT)
PTR_ret findFrameAlignBlock (FRAME_ptr)
PTR_ret findFrameErrorStart (FRAME_ptr)
PTR_ret findFrameHistoryStart (FRAME_ptr)
VALUE_ret getAlignBlock (FRAME_ptr, PHDWORD *, UINT)
LOGIC_ret setAlignBlock (FRAME_ptr, PHDWORD *, UINT)
VALUE_ret getHistoryEntry (FRAME_ptr, UINT)
VALUE_ret getHistoryStage (FRAME_ptr, UINT)
VALUE_ret getHistorySourceIndex (FRAME_ptr, UINT)
VALUE_ret getHistoryStatus (FRAME_ptr, UINT)
PTR_ret findNextError (FRAME_ptr, FRAME_ptr)
Macro Definition Documentation
#define _FRAMES_
Definition at line 117 of file Cframe.h.
Function Documentation
VALUE_ret adjustFrameDataLength (FRAME_ptr , UINT)
Definition at line 414 of file Cframe.C.
References adjustFrameDataLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by extendFrameData(), and extendFrameDataNopad().
VALUE_ret adjustFrameErrorLength (FRAME_ptr , UINT)
Definition at line 433 of file Cframe.C.
References adjustFrameErrorLengthV, getFrameHdrVersion(), and valueFailure.
VALUE_ret adjustFrameHistoryLength (FRAME_ptr , UINT)
Definition at line 424 of file Cframe.C.
References adjustFrameHistoryLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by extendFrameHistory(), and extendFrameHistoryNopad().
VALUE_ret adjustFrameLength (FRAME_ptr , UINT , UINT , LOGIC_ret)
Definition at line 122 of file Cframe.C.
References currentFrameQuantum, dwordClear, FORMAT_ERR_BUFFER_OVERFLOW, FORMAT_ERR_LENGTH_OVERFLOW, getFrameLength(), maxDwordValue, removeFramePadding(), setFrameError(), setFrameLength(), setFramePadding(), validFrameHdr(), and valueFailure.
Referenced by oEvent::addPacket(), oEvent::addUnstructPacketData(), extendFrameData(), extendFrameDataNopad(), extendFrameHistory(), and extendFrameHistoryNopad().
INLINE_D void byteSwapFrame (FRAME_ptr frame_ptr)
Definition at line 382 of file Cframe.h.
References dwordByteSwap(), and singleDwordByteSwap().
Referenced by main().
VALUE_ret checkFrameEndianism (FRAME_ptr frame_ptr)
Definition at line 107 of file Cframe.C.
References dwordByteSwap(), maxFrameHdrLength, validFrameHdr(), and valueFailure.
Referenced by main().
VALUE_ret checkFrameHdrVersion (FRAME_ptr)
Definition at line 64 of file Cframe.C.
References FORMAT_ERR_INVALID_FRAMEMARK, frameHdrLengthV, frameMarkV, getFrameHdrLength(), getFrameHdrVersion(), getFrameMark(), setFrameError(), setFrameSuccess(), and valueFailure.
Referenced by validFrameHdr().
INLINE_D LOGIC_ret currentFrameHdr (FRAME_ptr frame_ptr)
Definition at line 353 of file Cframe.h.
References currentFrameHdrVersion, and getFrameHdrVersion().
Referenced by storeFrameData(), and storeFrameHistory().
INLINE_D LOGIC_ret emptyFrame (FRAME_ptr frame_ptr)
Definition at line 372 of file Cframe.h.
References getFrameHdrLength(), and getFrameLength().
Referenced by storeFrameData().
PTR_ret findFrameAlignBlock (FRAME_ptr)
Definition at line 355 of file Cframe.C.
References findFrameAlignBlockV, getFrameHdrVersion(), ptrFailure, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
PTR_ret findFrameDataEnd (FRAME_ptr)
Definition at line 49 of file Cframe.C.
References findFrameDataStart(), getFrameDataLength(), ptrFailure, and valueFailure.
Referenced by oEvent::addPacket(), oEvent::addUnstructPacketData(), and findNextFramePacket().
PTR_ret findFrameDataStart (FRAME_ptr)
Definition at line 40 of file Cframe.C.
References getFrameHdrLength(), ptrFailure, and validFrameHdr().
Referenced by appendEmptyFramePacket(), dumpFrame(), findFrameDataEnd(), findFramePacketId(), findFramePacketIndex(), findNextFramePacket(), and storeFrameData().
PTR_ret findFrameEnd (FRAME_ptr)
Definition at line 87 of file Cframe.C.
References getFrameLength(), ptrFailure, setFrameSuccess(), validFrameHdr(), and valueFailure.
Referenced by fakeFrame(), and findNextErrorV1().
PTR_ret findFrameErrorStart (FRAME_ptr)
Definition at line 375 of file Cframe.C.
References findFrameErrorStartV, getFrameHdrVersion(), ptrFailure, and valueFailure.
Referenced by A_Event::dumpErrorBlock(), findNextErrorV1(), and A_Event::listError().
PTR_ret findFrameHistoryStart (FRAME_ptr)
Definition at line 365 of file Cframe.C.
References findFrameHistoryStartV, getFrameHdrVersion(), ptrFailure, and valueFailure.
Referenced by getHistoryEntryV1(), A_Event::listHistory(), and storeFrameHistory().
PTR_ret findNextError (FRAME_ptr , FRAME_ptr)
Definition at line 568 of file Cframe.C.
References findNextErrorV, getFrameHdrVersion(), ptrFailure, and valueFailure.
VALUE_ret getAlignBlock (FRAME_ptr , PHDWORD * , UINT)
Definition at line 514 of file Cframe.C.
References getAlignBlockV, getFrameHdrVersion(), and valueFailure.
VALUE_ret getFrameAlignLength (FRAME_ptr)
Definition at line 345 of file Cframe.C.
References getFrameAlignLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), getAlignBlockV1(), A_Event::getFrameValue(), and setAlignBlockV1().
VALUE_ret getFrameDataLength (FRAME_ptr)
Definition at line 315 of file Cframe.C.
References getFrameDataLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by dumpFrame(), fakeFrame(), and findFrameDataEnd().
VALUE_ret getFrameDataType (FRAME_ptr)
Definition at line 305 of file Cframe.C.
References getFrameDataTypeV, getFrameHdrVersion(), and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getFrameErrorLength (FRAME_ptr)
Definition at line 335 of file Cframe.C.
References getFrameErrorLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by A_Event::dumpErrorBlock(), A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::listError().
INLINE_D VALUE_ret getFrameHdrLength (FRAME_ptr frame_ptr)
Definition at line 246 of file Cframe.h.
References FORMAT_ERR_INVALID_HDRLENGTH, FRAME_HDR_LENGTH_MASK, FRAME_HDR_LENGTH_OFFSET_IN_DWORD, FRAME_HDR_LENGTH_OFFSET_OF_DWORD, getBitsMACRO, getFrameLength(), setFrameError(), and valueFailure.
Referenced by checkFrameHdrVersion(), A_Event::dumpFrame(), dumpFrameHdr(), emptyFrame(), emptyFrameV1(), findFrameDataStart(), getFrameDataLengthV1(), A_Event::getFrameValue(), and validFrameHdrV1().
INLINE_D VALUE_ret getFrameHdrVersion (FRAME_ptr frame_ptr)
Definition at line 264 of file Cframe.h.
References FORMAT_ERR_INVALID_HDRVERSION, FRAME_HDR_VERSION_MASK, FRAME_HDR_VERSION_OFFSET_IN_DWORD, FRAME_HDR_VERSION_OFFSET_OF_DWORD, getBitsMACRO, numFrameVersions, setFrameError(), and valueFailure.
Referenced by adjustFrameDataLength(), adjustFrameErrorLength(), adjustFrameHistoryLength(), checkFrameHdrVersion(), currentFrameHdr(), A_Event::dumpFrame(), dumpFrameHdr(), findFrameAlignBlock(), findFrameErrorStart(), findFrameHistoryStart(), findNextError(), getAlignBlock(), getFrameAlignLength(), getFrameDataLength(), getFrameDataType(), getFrameErrorLength(), getFrameHistoryLength(), getFramePadding(), getFrameSourceId(), getFrameStatus(), getFrameType(), A_Event::getFrameValue(), getHistoryEntry(), getHistorySourceIndex(), getHistoryStage(), getHistoryStatus(), orFrameStatus(), setAlignBlock(), setDataType(), setFrameAlignLength(), setFrameErrorLength(), setFrameHistoryLength(), setFramePadding(), setFrameStatus(), setFrameType(), setSourceId(), and validFrameMark().
VALUE_ret getFrameHistoryLength (FRAME_ptr)
Definition at line 325 of file Cframe.C.
References getFrameHdrVersion(), getFrameHistoryLengthV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), getHistoryEntryV1(), A_Event::listHistory(), and storeFrameHistory().
INLINE_D VALUE_ret getFrameLength (FRAME_ptr frame_ptr)
Definition at line 283 of file Cframe.h.
References FORMAT_ERR_LENGTH_OVERFLOW, FRAME_LENGTH_OFFSET_OF_DWORD, getWordMACRO, setFrameError(), and valueFailure.
Referenced by oEvent::addFrame(), adjustFrameLength(), prdfBuffer::buffer_swap(), A_Event::dumpFrame(), dumpFrameHdr(), emptyFrame(), emptyFrameV1(), fakeFrame(), findFrameEnd(), findFrameErrorStartV1(), findFrameHistoryStartV1(), getFrameDataLengthV1(), getFrameHdrLength(), A_Event::getFrameValue(), removeFramePadding(), and A_Event::updateFramelist().
INLINE_D VALUE_ret getFrameMark (FRAME_ptr frame_ptr)
Definition at line 298 of file Cframe.h.
References FRAME_MARK_OFFSET_OF_DWORD, and getWordMACRO.
Referenced by checkFrameHdrVersion(), A_Event::dumpFrame(), dumpFrameHdr(), A_Event::getFrameValue(), and validFrameMark().
VALUE_ret getFramePadding (FRAME_ptr)
Definition at line 395 of file Cframe.C.
References getFrameHdrVersion(), getFramePaddingV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), findFrameErrorStartV1(), findFrameHistoryStartV1(), and removeFramePadding().
VALUE_ret getFrameSourceId (FRAME_ptr)
Definition at line 295 of file Cframe.C.
References getFrameHdrVersion(), getFrameSourceIdV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getFrameStatus (FRAME_ptr)
Definition at line 276 of file Cframe.C.
References getFrameHdrVersion(), getFrameStatusV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getFrameType (FRAME_ptr)
Definition at line 285 of file Cframe.C.
References getFrameHdrVersion(), getFrameTypeV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getHistoryEntry (FRAME_ptr , UINT)
Definition at line 532 of file Cframe.C.
References getFrameHdrVersion(), getHistoryEntryV, index, and valueFailure.
VALUE_ret getHistorySourceIndex (FRAME_ptr , UINT)
Definition at line 550 of file Cframe.C.
References getFrameHdrVersion(), getHistorySourceIndexV, index, and valueFailure.
VALUE_ret getHistoryStage (FRAME_ptr , UINT)
Definition at line 541 of file Cframe.C.
References getFrameHdrVersion(), getHistoryStageV, index, and valueFailure.
VALUE_ret getHistoryStatus (FRAME_ptr , UINT)
Definition at line 559 of file Cframe.C.
References getFrameHdrVersion(), getHistoryStatusV, index, and valueFailure.
VALUE_ret makeFrameHdr (FRAME_ptr , UINT , UINT , UINT , UINT)
Definition at line 407 of file Cframe.C.
References currentFrameHdrVersion, and makeFrameHdrV.
Referenced by oEvent::addPacket(), oEvent::addUnstructPacketData(), and fakeFrame().
VALUE_ret orFrameStatus (FRAME_ptr , UINT)
Definition at line 385 of file Cframe.C.
References getFrameHdrVersion(), orFrameStatusV, and valueFailure.
VALUE_ret removeFramePadding (FRAME_ptr)
Definition at line 186 of file Cframe.C.
References getFrameLength(), getFramePadding(), setFrameLength(), and setFramePadding().
Referenced by adjustFrameLength(), storeFrameData(), and storeFrameHistory().
LOGIC_ret setAlignBlock (FRAME_ptr , PHDWORD * , UINT)
Definition at line 523 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setAlignBlockV, and valueFailure.
Referenced by fakeFrame().
LOGIC_ret setDataType (FRAME_ptr , UINT)
Definition at line 451 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setDataTypeV, and valueFailure.
Referenced by makeFrameHdrV1().
LOGIC_ret setFrameAlignLength (FRAME_ptr , UINT)
Definition at line 496 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameAlignLengthV, and valueFailure.
Referenced by makeFrameHdrV1().
LOGIC_ret setFrameErrorLength (FRAME_ptr , UINT)
Definition at line 487 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameErrorLengthV, and valueFailure.
INLINE_D LOGIC_ret setFrameHdrLength (FRAME_ptr frame_ptr, UINT hdrLength)
Definition at line 306 of file Cframe.h.
References FRAME_HDR_LENGTH_MASK, FRAME_HDR_LENGTH_OFFSET_IN_DWORD, FRAME_HDR_LENGTH_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
Referenced by makeFrameHdrV1().
INLINE_D LOGIC_ret setFrameHdrVersion (FRAME_ptr frame_ptr, UINT hdrVersion)
Definition at line 316 of file Cframe.h.
References FRAME_HDR_VERSION_MASK, FRAME_HDR_VERSION_OFFSET_IN_DWORD, FRAME_HDR_VERSION_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
Referenced by makeFrameHdrV1().
LOGIC_ret setFrameHistoryLength (FRAME_ptr , UINT)
Definition at line 478 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameHistoryLengthV, and valueFailure.
INLINE_D LOGIC_ret setFrameLength (FRAME_ptr frame_ptr, UINT length)
Definition at line 326 of file Cframe.h.
References FRAME_LENGTH_OFFSET_OF_DWORD, setWordMACRO, and TRUE.
Referenced by adjustFrameLength(), makeFrameHdrV1(), and removeFramePadding().
INLINE_D LOGIC_ret setFrameMark (FRAME_ptr frame_ptr, UINT frameMark)
Definition at line 335 of file Cframe.h.
References FRAME_MARK_OFFSET_OF_DWORD, setWordMACRO, and TRUE.
Referenced by makeFrameHdrV1().
VALUE_ret setFramePadding (FRAME_ptr , UINT)
Definition at line 442 of file Cframe.C.
References getFrameHdrVersion(), setFramePaddingV, and valueFailure.
Referenced by adjustFrameLength(), and removeFramePadding().
LOGIC_ret setFrameStatus (FRAME_ptr , UINT)
Definition at line 505 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameStatusV, and valueFailure.
LOGIC_ret setFrameType (FRAME_ptr , UINT)
Definition at line 460 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameTypeV, and valueFailure.
Referenced by makeFrameHdrV1().
LOGIC_ret setSourceId (FRAME_ptr , UINT)
Definition at line 469 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setSourceIdV, and valueFailure.
Referenced by makeFrameHdrV1(), and TruthConversionEval::process_event().
INLINE_D LOGIC_ret validFrameHdr (FRAME_ptr frame_ptr)
Definition at line 346 of file Cframe.h.
References checkFrameHdrVersion(), and valueFailure.
Referenced by adjustFrameLength(), appendEmptyFramePacket(), checkFrameEndianism(), dumpFrameHdr(), findFrameDataStart(), findFrameEnd(), findFramePacketId(), findFramePacketIndex(), isLastFramePacket(), storeFrameHistory(), and A_Event::updateFramelist().
INLINE_D LOGIC_ret validFrameMark (FRAME_ptr frame_ptr)
Definition at line 361 of file Cframe.h.
References FALSE, frameMarkV, getFrameHdrVersion(), getFrameMark(), and valueFailure.