Analysis Software: coresoftware/blob/master/offline/packages/HelixHough/helix_hough/HelixHough_findHelices.cpp File Reference
HelixHough_findHelices.cpp File Reference
#include "HelixHough.h"
#include "HelixRange.h"
#include "SimpleHit3D.h"
#include "SimpleTrack3D.h"
#include <algorithm>
#include <cstddef>
#include <cmath>
#include <iostream>
#include <memory>
#include <sys/time.h>
#include <utility>
#include <vector>
Classes
class floatBin
Functions
static void in_place_counting_sort_unique (vector< unsigned int > &A, vector< unsigned int > &C, unsigned int MAX)
static void in_place_counting_unique (vector< unsigned int > &A, vector< unsigned int > &C)
static void setClusterRange (HelixRange &range1, HelixRange &range2, ParRange &prange, unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0)
static bool mergeClusters (ParameterCluster &clus1, ParameterCluster const &clus2, unsigned int MAX, float overlap_cut)
static int seed_bin (vector< floatBin > &bins, float val)
Function Documentation
static void in_place_counting_sort_unique (vector< unsigned int > & A, vector< unsigned int > & C, unsigned int MAX) inline static
Definition at line 17 of file HelixHough_findHelices.cpp.
References i.
static void in_place_counting_unique (vector< unsigned int > & A, vector< unsigned int > & C) inline static
Definition at line 32 of file HelixHough_findHelices.cpp.
References i.
Referenced by HelixHough::attemptClusterMerge(), and mergeClusters().
static bool mergeClusters (ParameterCluster & clus1, ParameterCluster const & clus2, unsigned int MAX, float overlap_cut) static
Definition at line 194 of file HelixHough_findHelices.cpp.
References C, ParameterCluster::hit_indexes, i, in_place_counting_unique(), ParRange::mergeRange(), and ParameterCluster::range.
Referenced by HelixHough::makeClusters().
static int seed_bin (vector< floatBin > & bins, float val) static
Definition at line 779 of file HelixHough_findHelices.cpp.
Referenced by HelixHough::findSeededHelices().
static void setClusterRange (HelixRange & range1, HelixRange & range2, ParRange & prange, unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0) inline static
Definition at line 75 of file HelixHough_findHelices.cpp.
References HelixRange::max_d, ParRange::max_d, HelixRange::max_dzdl, ParRange::max_dzdl, HelixRange::max_k, ParRange::max_k, HelixRange::max_phi, ParRange::max_phi, HelixRange::max_z0, ParRange::max_z0, HelixRange::min_d, ParRange::min_d, HelixRange::min_dzdl, ParRange::min_dzdl, HelixRange::min_k, ParRange::min_k, HelixRange::min_phi, ParRange::min_phi, HelixRange::min_z0, and ParRange::min_z0.
Referenced by HelixHough::findHelices().