Analysis Software: twrs Class Reference
twrs Class Reference
Public Member Functions
twrs (RawTower *)
virtual ~twrs ()
bool is_adjacent (twrs &)
void set_id (const int i)
int get_id () const
void set_maxphibin (const int i)
int get_maxphibin () const
int get_bineta () const
int get_binphi () const
Protected Attributes
int bineta
int binphi
int maxphibin
RawTowerDefs::keytype id
Detailed Description
Definition at line 41 of file RawClusterBuilderGraph.cc.
Constructor & Destructor Documentation
twrs::twrs (RawTower * rt)
Definition at line 79 of file RawClusterBuilderGraph.cc.
References bineta, binphi, RawTower::get_bineta(), and RawTower::get_binphi().
virtual twrs::~twrs () inline virtual
Definition at line 45 of file RawClusterBuilderGraph.cc.
Member Function Documentation
int twrs::get_bineta () const inline
Definition at line 63 of file RawClusterBuilderGraph.cc.
Referenced by is_adjacent(), and operator<().
int twrs::get_binphi () const inline
Definition at line 67 of file RawClusterBuilderGraph.cc.
Referenced by is_adjacent(), and operator<().
int twrs::get_id () const inline
Definition at line 51 of file RawClusterBuilderGraph.cc.
Referenced by RawClusterBuilderGraph::process_event().
int twrs::get_maxphibin () const inline
Definition at line 59 of file RawClusterBuilderGraph.cc.
bool twrs::is_adjacent (twrs & tower)
Definition at line 87 of file RawClusterBuilderGraph.cc.
References bineta, binphi, get_bineta(), get_binphi(), and maxphibin.
void twrs::set_id (const int i) inline
Definition at line 47 of file RawClusterBuilderGraph.cc.
References i.
Referenced by RawClusterBuilderGraph::process_event().
void twrs::set_maxphibin (const int i) inline
Definition at line 55 of file RawClusterBuilderGraph.cc.
References i.
Referenced by RawClusterBuilderGraph::process_event().
Member Data Documentation
int twrs::bineta protected
Definition at line 73 of file RawClusterBuilderGraph.cc.
Referenced by is_adjacent(), and twrs().
int twrs::binphi protected
Definition at line 74 of file RawClusterBuilderGraph.cc.
Referenced by is_adjacent(), and twrs().
RawTowerDefs::keytype twrs::id protected
Definition at line 76 of file RawClusterBuilderGraph.cc.
int twrs::maxphibin protected
Definition at line 75 of file RawClusterBuilderGraph.cc.
Referenced by is_adjacent().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderGraph.cc