Analysis Software: online_distribution/blob/master/newbasic/PHmd5Utils.cc File Reference
PHmd5Utils.cc File Reference
#include "stdio.h"
#include "PHmd5Utils.h"
#include "md5.h"
Macros
#define BLOCKSIZE 4096
Functions
int PHmd5File (const char *filename, unsigned char *digest, int *filesize)
int PHmd5Stream (FILE *stream, unsigned char *digest, int *filesize)
Macro Definition Documentation
#define BLOCKSIZE 4096
Referenced by PHmd5Stream().
Function Documentation
int PHmd5File (const char * filename, unsigned char * digest, int * filesize)
Definition at line 7 of file PHmd5Utils.cc.
References fclose(), and PHmd5Stream().
Referenced by PHmd5Value::PHmd5Value(), and PHmd5Value::setFileMD5().
int PHmd5Stream (FILE * stream, unsigned char * digest, int * filesize)
Definition at line 21 of file PHmd5Utils.cc.
References BLOCKSIZE, md5_append(), md5_finish(), md5_init(), n, and sum().
Referenced by PHmd5File(), and PHmd5Value::PHmd5Value().