Analysis Software: CaloEvaluator Class Reference
CaloEvaluator Class Reference
Compares reconstructed showers to truth particles.
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvaluator.h>
Public Member Functions
CaloEvaluator (const std::string &name="CALOEVALUATOR", const std::string &caloname="CEMC", const std::string &filename="g4eval_cemc.root")
virtual ~CaloEvaluator ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_strict (bool b)
void add_truth_tracing_embed_flag (int flag)
void set_truth_tracing_energy_threshold (float thresh)
void set_reco_tracing_energy_threshold (float thresh)
void set_do_gpoint_eval (bool b)
void set_do_gshower_eval (bool b)
void set_do_tower_eval (bool b)
void set_do_cluster_eval (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
std::string _caloname
unsigned int _ievent
std::set< int > _truth_trace_embed_flags
float _truth_e_threshold
float _reco_e_threshold
CaloEvalStack * _caloevalstack
bool _strict
bool _do_gpoint_eval
bool _do_gshower_eval
bool _do_tower_eval
bool _do_cluster_eval
TNtuple * _ntp_gpoint
TNtuple * _ntp_gshower
TNtuple * _ntp_tower
TNtuple * _ntp_cluster
std::string _filename
TFile * _tfile
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Compares reconstructed showers to truth particles.
Plan: This module will trace the reconstructed clusters back to the greatest contributor Monte Carlo particle and then test one against the other.
Definition at line 28 of file CaloEvaluator.h.
Constructor & Destructor Documentation
CaloEvaluator::CaloEvaluator (const std::string & name = "CALOEVALUATOR", const std::string & caloname = "CEMC", const std::string & filename = "g4eval_cemc.root")
Definition at line 44 of file CaloEvaluator.cc.
virtual CaloEvaluator::~CaloEvaluator () inline virtual
Definition at line 34 of file CaloEvaluator.h.
Member Function Documentation
void CaloEvaluator::add_truth_tracing_embed_flag (int flag) inline
Definition at line 49 of file CaloEvaluator.h.
References _truth_trace_embed_flags.
int CaloEvaluator::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 136 of file CaloEvaluator.cc.
References _caloevalstack, _do_cluster_eval, _do_gpoint_eval, _do_gshower_eval, _do_tower_eval, _filename, _ievent, _ntp_cluster, _ntp_gpoint, _ntp_gshower, _ntp_tower, _tfile, Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
void CaloEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 351 of file CaloEvaluator.cc.
References _caloevalstack, _caloname, _do_cluster_eval, _do_gpoint_eval, _do_tower_eval, _ievent, _ntp_cluster, _ntp_gpoint, _ntp_gshower, _ntp_tower, _reco_e_threshold, _truth_e_threshold, _truth_trace_embed_flags, GlobalVertexMap::begin(), CaloRawClusterEval::best_cluster_from(), GlobalVertexMap::empty(), RawTower::get_bineta(), RawTower::get_binphi(), CaloTruthEval::get_caloid(), PHG4Particle::get_e(), CaloTruthEval::get_embed(), RawCluster::get_energy(), RawTower::get_energy(), CaloRawClusterEval::get_energy_contribution(), CaloRawTowerEval::get_energy_contribution(), RawTowerGeom::get_eta(), RawTower::get_id(), RawCluster::get_id(), PHG4Shower::get_nhits(), RawCluster::get_phi(), RawTowerGeom::get_phi(), PHG4Particle::get_pid(), CaloTruthEval::get_primary_shower(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), CaloEvalStack::get_rawcluster_eval(), CaloEvalStack::get_rawtower_eval(), CaloTruthEval::get_shower_energy_deposit(), RawTowerGeomContainer::get_tower_geometry(), PHG4Particle::get_track_id(), CaloEvalStack::get_truth_eval(), CaloTruthEval::get_vertex(), PHG4VtxPoint::get_x(), GlobalVertex::get_x(), PHG4VtxPoint::get_y(), GlobalVertex::get_y(), PHG4VtxPoint::get_z(), GlobalVertex::get_z(), RawCluster::get_z(), RawClusterContainer::getClustersMap(), RawCluster::getNTowers(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), RawClusterUtility::GetPseudorapidity(), RawTowerContainer::getTowers(), RawTower::identify(), CaloRawTowerEval::max_truth_primary_particle_by_energy(), CaloRawClusterEval::max_truth_primary_particle_by_energy(), Fun4AllBase::Name(), phi, PHWHERE, Fun4AllBase::Verbosity(), and z.
Referenced by process_event().
int CaloEvaluator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 68 of file CaloEvaluator.cc.
References _do_cluster_eval, _do_gpoint_eval, _do_gshower_eval, _do_tower_eval, _filename, _ievent, _ntp_cluster, _ntp_gpoint, _ntp_gshower, _ntp_tower, _tfile, and Fun4AllReturnCodes::EVENT_OK.
void CaloEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 161 of file CaloEvaluator.cc.
References _ievent, PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4TruthInfoContainer::GetParticleRange(), Fun4AllBase::Name(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by process_event().
void CaloEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 198 of file CaloEvaluator.cc.
References _caloevalstack, _ievent, CaloRawClusterEval::all_clusters_from(), GlobalVertexMap::begin(), GlobalVertexMap::empty(), PHG4Particle::get_e(), CaloTruthEval::get_embed(), RawCluster::get_energy(), CaloRawClusterEval::get_energy_contribution(), RawCluster::get_id(), RawCluster::get_phi(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), CaloEvalStack::get_rawcluster_eval(), CaloTruthEval::get_shower_energy_deposit(), PHG4Particle::get_track_id(), CaloEvalStack::get_truth_eval(), CaloTruthEval::get_vertex(), PHG4VtxPoint::get_x(), GlobalVertex::get_x(), PHG4VtxPoint::get_y(), GlobalVertex::get_y(), PHG4VtxPoint::get_z(), GlobalVertex::get_z(), RawCluster::get_z(), RawCluster::getNTowers(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), phi, PHWHERE, Fun4AllBase::Verbosity(), and z.
Referenced by process_event().
int CaloEvaluator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 100 of file CaloEvaluator.cc.
References _caloevalstack, _caloname, _ievent, _strict, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), CaloEvalStack::next_event(), printInputInfo(), printOutputInfo(), CaloEvalStack::set_strict(), CaloEvalStack::set_verbosity(), and Fun4AllBase::Verbosity().
void CaloEvaluator::set_do_cluster_eval (bool b) inline
Definition at line 77 of file CaloEvaluator.h.
References _do_cluster_eval.
void CaloEvaluator::set_do_gpoint_eval (bool b) inline
Definition at line 74 of file CaloEvaluator.h.
References _do_gpoint_eval.
void CaloEvaluator::set_do_gshower_eval (bool b) inline
Definition at line 75 of file CaloEvaluator.h.
References _do_gshower_eval.
void CaloEvaluator::set_do_tower_eval (bool b) inline
Definition at line 76 of file CaloEvaluator.h.
References _do_tower_eval.
void CaloEvaluator::set_reco_tracing_energy_threshold (float thresh) inline
Definition at line 66 of file CaloEvaluator.h.
References _reco_e_threshold.
void CaloEvaluator::set_strict (bool b) inline
Definition at line 40 of file CaloEvaluator.h.
References _strict.
void CaloEvaluator::set_truth_tracing_energy_threshold (float thresh) inline
Definition at line 58 of file CaloEvaluator.h.
References _truth_e_threshold.
Member Data Documentation
CaloEvalStack* CaloEvaluator::_caloevalstack private
Definition at line 88 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), printOutputInfo(), and process_event().
std::string CaloEvaluator::_caloname private
Definition at line 80 of file CaloEvaluator.h.
Referenced by fillOutputNtuples(), and process_event().
bool CaloEvaluator::_do_cluster_eval private
Definition at line 98 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), and set_do_cluster_eval().
bool CaloEvaluator::_do_gpoint_eval private
Definition at line 95 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), and set_do_gpoint_eval().
bool CaloEvaluator::_do_gshower_eval private
Definition at line 96 of file CaloEvaluator.h.
Referenced by End(), Init(), and set_do_gshower_eval().
bool CaloEvaluator::_do_tower_eval private
Definition at line 97 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), and set_do_tower_eval().
std::string CaloEvaluator::_filename private
Definition at line 106 of file CaloEvaluator.h.
Referenced by End(), and Init().
unsigned int CaloEvaluator::_ievent private
Definition at line 82 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), printInputInfo(), printOutputInfo(), and process_event().
TNtuple* CaloEvaluator::_ntp_cluster private
Definition at line 103 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* CaloEvaluator::_ntp_gpoint private
Definition at line 100 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* CaloEvaluator::_ntp_gshower private
Definition at line 101 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* CaloEvaluator::_ntp_tower private
Definition at line 102 of file CaloEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
float CaloEvaluator::_reco_e_threshold private
Definition at line 86 of file CaloEvaluator.h.
Referenced by fillOutputNtuples(), and set_reco_tracing_energy_threshold().
bool CaloEvaluator::_strict private
Definition at line 93 of file CaloEvaluator.h.
Referenced by process_event(), and set_strict().
TFile* CaloEvaluator::_tfile private
Definition at line 107 of file CaloEvaluator.h.
Referenced by End(), and Init().
float CaloEvaluator::_truth_e_threshold private
Definition at line 85 of file CaloEvaluator.h.
Referenced by fillOutputNtuples(), and set_truth_tracing_energy_threshold().
std::set<int> CaloEvaluator::_truth_trace_embed_flags private
Definition at line 84 of file CaloEvaluator.h.
Referenced by add_truth_tracing_embed_flag(), and fillOutputNtuples().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvaluator.cc