Analysis Software: PHG4ForwardEcalSubsystem Class Reference
PHG4ForwardEcalSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.h>
Public Member Functions
PHG4ForwardEcalSubsystem (const std::string &name="FORWARD_ECAL_DEFAULT", const int layer=0)
virtual ~PHG4ForwardEcalSubsystem ()
int InitRunSubsystem (PHCompositeNode *)
int process_event (PHCompositeNode *)
PHG4Detector * GetDetector () const
PHG4SteppingAction * GetSteppingAction () const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void SetEICDetector ()
void SetfsPHENIXDetector ()
void SetTowerMappingFile (const std::string &filename)
Public Member Functions inherited from PHG4DetectorSubsystem
virtual ~PHG4DetectorSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams () const
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters ()
Private Attributes
PHG4ForwardEcalDetector * m_Detector
PHG4SteppingAction * m_SteppingAction
PHG4DisplayAction * m_DisplayAction
display attribute setting
int m_EICDetectorFlag
Additional Inherited Members
Public Types inherited from PHG4DetectorSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Protected Member Functions inherited from PHG4DetectorSubsystem
PHG4DetectorSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
int BeginRunExecuted () const
Detailed Description
Definition at line 16 of file PHG4ForwardEcalSubsystem.h.
Constructor & Destructor Documentation
PHG4ForwardEcalSubsystem::PHG4ForwardEcalSubsystem (const std::string & name = "FORWARD_ECAL_DEFAULT", const int layer = 0)
Constructor
Definition at line 30 of file PHG4ForwardEcalSubsystem.cc.
References PHG4DetectorSubsystem::InitializeParameters().
PHG4ForwardEcalSubsystem::~PHG4ForwardEcalSubsystem () virtual
Destructor
Definition at line 41 of file PHG4ForwardEcalSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
PHG4Detector * PHG4ForwardEcalSubsystem::GetDetector (void) const virtual
Accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 132 of file PHG4ForwardEcalSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4ForwardEcalSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 43 of file PHG4ForwardEcalSubsystem.h.
References m_DisplayAction.
PHG4SteppingAction* PHG4ForwardEcalSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 41 of file PHG4ForwardEcalSubsystem.h.
References m_SteppingAction.
int PHG4ForwardEcalSubsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
Creates the m_Detector object and place it on the node tree, under "DETECTORS" node (or whatever) Creates the stepping action and place it on the node tree, under "ACTIONS" node Creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorSubsystem.
Definition at line 47 of file PHG4ForwardEcalSubsystem.cc.
References PHCompositeNode::addNode(), PHG4DetectorSubsystem::CheckOverlap(), PHNodeIterator::findFirst(), PHParameters::get_int_param(), PHG4DetectorSubsystem::get_int_param(), PHG4DetectorSubsystem::GetParams(), m_Detector, m_DisplayAction, m_EICDetectorFlag, m_SteppingAction, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHG4DetectorSubsystem::SuperDetector(), PHG4ForwardEcalDetector::SuperDetector(), PHG4Detector::topNode(), PHG4Detector::Verbosity(), and Fun4AllBase::Verbosity().
int PHG4ForwardEcalSubsystem::process_event (PHCompositeNode * topNode) virtual
Event processing
Reimplemented from SubsysReco.
Definition at line 120 of file PHG4ForwardEcalSubsystem.cc.
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4ForwardEcalSubsystem::SetDefaultParameters () private virtual
Implements PHG4DetectorSubsystem.
Definition at line 137 of file PHG4ForwardEcalSubsystem.cc.
References PHG4Utils::md5sum(), and PHG4DetectorSubsystem::set_default_string_param().
void PHG4ForwardEcalSubsystem::SetEICDetector () inline
Definition at line 45 of file PHG4ForwardEcalSubsystem.h.
References m_EICDetectorFlag.
Referenced by FEMCSetup().
void PHG4ForwardEcalSubsystem::SetfsPHENIXDetector () inline
Definition at line 46 of file PHG4ForwardEcalSubsystem.h.
References m_EICDetectorFlag.
Referenced by FEMCSetup().
void PHG4ForwardEcalSubsystem::SetTowerMappingFile (const std::string & filename)
Definition at line 151 of file PHG4ForwardEcalSubsystem.cc.
References PHG4DetectorSubsystem::get_string_param(), PHG4Utils::md5sum(), and PHG4DetectorSubsystem::set_string_param().
Referenced by FEMCSetup().
Member Data Documentation
PHG4ForwardEcalDetector* PHG4ForwardEcalSubsystem::m_Detector private
Pointer to the Geant4 implementation of the detector
Definition at line 54 of file PHG4ForwardEcalSubsystem.h.
Referenced by GetDetector(), and InitRunSubsystem().
PHG4DisplayAction* PHG4ForwardEcalSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 62 of file PHG4ForwardEcalSubsystem.h.
Referenced by GetDisplayAction(), InitRunSubsystem(), and ~PHG4ForwardEcalSubsystem().
int PHG4ForwardEcalSubsystem::m_EICDetectorFlag private
Definition at line 64 of file PHG4ForwardEcalSubsystem.h.
Referenced by InitRunSubsystem(), SetEICDetector(), and SetfsPHENIXDetector().
PHG4SteppingAction* PHG4ForwardEcalSubsystem::m_SteppingAction private
Stepping action
Definition at line 58 of file PHG4ForwardEcalSubsystem.h.
Referenced by GetSteppingAction(), InitRunSubsystem(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.cc