Analysis Software: PHG4CellDefs Namespace Reference
PHG4CellDefs Namespace Reference
Namespaces
namespace EtaPhiBinning
namespace EtaXsizeBinning
namespace MVTXBinning
namespace ScintillatorSlatBinning
namespace SizeBinning
namespace SpacalBinning
namespace TPCBinning
Typedefs
typedef uint64_t keytype
Enumerations
enum CellBinning {
undefined = 0, sizebinning = 1, etaphibinning = 2, etaslatbinning = 3,
spacalbinning = 4, scintillatorslatbinning = 5, etaxsizebinning = 6, mvtxbinning = 7,
tpcbinning = 8
}
Functions
static unsigned int bitshift_layer __attribute__ ((unused)) = bitshift_layer - 16
bool has_binning (PHG4CellDefs::keytype key, PHG4CellDefs::CellBinning binning)
short get_binning (const PHG4CellDefs::keytype key)
short int get_detid (const PHG4CellDefs::keytype key)
Typedef Documentation
typedef uint64_t PHG4CellDefs::keytype
Definition at line 18 of file PHG4CellDefs.h.
Enumeration Type Documentation
enum PHG4CellDefs::CellBinning
Enumerator:
undefined
sizebinning
etaphibinning
etaslatbinning
spacalbinning
scintillatorslatbinning
etaxsizebinning
mvtxbinning
tpcbinning
Definition at line 42 of file PHG4CellDefs.h.
Function Documentation
static unsigned int bitshift_phi PHG4CellDefs::__attribute__ ((unused)) = bitshift_layer - 16 static
short PHG4CellDefs::get_binning (const PHG4CellDefs::keytype key)
Definition at line 187 of file PHG4CellDefs.cc.
References i.
Referenced by RawTowerBuilder::process_event(), CaloAna::process_g4cells(), and DumpPHG4CellContainer::process_Node().
short int PHG4CellDefs::get_detid (const PHG4CellDefs::keytype key)
Definition at line 195 of file PHG4CellDefs.cc.
Referenced by PHG4CellContainer::AddCell(), PHG4Cellv2::get_detid(), PHG4Cellv1::get_detid(), and DumpPHG4CellContainer::process_Node().
bool PHG4CellDefs::has_binning (PHG4CellDefs::keytype key, PHG4CellDefs::CellBinning binning)
Definition at line 176 of file PHG4CellDefs.cc.
Referenced by PHG4Cellv2::has_binning(), and PHG4Cellv1::has_binning().