Analysis Software: coresoftware/blob/master/generators/JEWEL/pythia6425mod.f File Reference
pythia6425mod.f File Reference
Functions/Subroutines
subroutine pyckbd
subroutine pytest (MTEST)
subroutine pyhepc (MCONV)
subroutine pyinit (FRAME, BEAM, TARGET, WIN)
subroutine pyevnt
subroutine pyevnw
subroutine pystat (MSTAT)
subroutine pyupev
subroutine pyupin
subroutine pylhef
subroutine pyinre
subroutine pyinbm (CHFRAM, CHBEAM, CHTARG, WIN)
subroutine pyinki (MODKI)
subroutine pyinpr
subroutine pyxtot
subroutine pymaxi
subroutine pypile (MPILE)
subroutine pysave (ISAVE, IGA)
subroutine pygaga (IGAGA, WTGAGA)
subroutine pyrand
subroutine pyscat
subroutine pyevol (MODE, PT2MAX, PT2MIN)
subroutine pysspa (IPU1, IPU2)
subroutine pyptis (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
subroutine pymemx (MECOR, WTFF, WTGF, WTFG, WTGG)
subroutine pymewt (MECOR, IFLCB, Q2, Z, PHIBR, WTME)
subroutine pyptmi (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
double precision function pyfcmp (XC, XS, NPOW)
double precision function pypcmp (XS, NPOW)
subroutine pyupre
subroutine pyadsh (NFIN)
subroutine pyveto (IVETO)
subroutine pyresd (IRES)
subroutine pymult (MMUL)
subroutine pyremn (IPU1, IPU2)
subroutine pymign (MMUL)
subroutine pymihk
subroutine pycttr (I, KCS, IEND)
subroutine pymihg (JCP1, JCG1, JCP2, JCG2)
subroutine pymirm
subroutine pyfscr (IP)
subroutine pydiff
subroutine pydisg
subroutine pydocu
subroutine pyfram (IFRAME)
subroutine pywidt (KFLR, SH, WDTP, WDTE)
subroutine pyofsh (MOFSH, KFMO, KFD1, KFD2, PMMO, RET1, RET2)
subroutine pyreco (IW1, IW2, NSD1, NAFT1)
subroutine pyklim (ILIM)
subroutine pykmap (IVAR, MVAR, VVAR)
subroutine pysigh (NCHN, SIGS)
subroutine pysgqc (NCHN, SIGS)
subroutine pysghf (NCHN, SIGS)
subroutine pysgwz (NCHN, SIGS)
subroutine pysghg (NCHN, SIGS)
subroutine pysgsu (NCHN, SIGS)
subroutine pysgtc (NCHN, SIGS)
subroutine pysgex (NCHN, SIGS)
subroutine pypdfu (KF, X, Q2, XPQ)
subroutine pypdfl (KF, X, Q2, XPQ)
subroutine pypdel (KFA, X, Q2, XPEL)
subroutine pypdga (X, Q2, XPGA)
subroutine pyggam (ISET, X, Q2, P2, IP2, F2GM, XPDFGM)
subroutine pygvmd (ISET, KF, X, Q2, P2, ALAM, XPGA, VXPGA)
subroutine pygano (KF, X, Q2, P2, ALAM, XPGA, VXPGA)
subroutine pygbeh (KF, X, Q2, P2, PM2, XPBH)
subroutine pygdir (X, Q2, P2, Q02, XPGA)
subroutine pypdpi (X, Q2, XPPI)
subroutine pypdpr (X, Q2, XPPR)
function pycteq (ISET, IPRT, X, Q)
subroutine pygrvl (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
subroutine pygrvm (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
subroutine pygrvd (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
function pygrvv (X, N, AK, BK, A, B, C, D)
function pygrvw (X, S, AL, BE, AK, BK, A, B, C, D, E, ES)
function pygrvs (X, S, STH, AL, BE, AK, AG, B, D, E, ES)
function pyct5l (IFL, X, Q)
function pyct5m (IFL, X, Q)
subroutine pypdpo (X, Q2, XPPR)
function pyhfth (SH, SQM, FRATT)
subroutine pyspli (KF, KFLIN, KFLCH, KFLSP)
function pygamm (X)
subroutine pywaux (IAUX, EPS, WRE, WIM)
subroutine pyi3au (EPS, RAT, Y3RE, Y3IM)
function pyspen (XREIN, XIMIN, IREIM)
subroutine pyqqbh (WTQQBH)
subroutine pystbh (WTTBH)
subroutine pytbhb (MT, MB, MHP, BR, GAMT)
subroutine pytbhg (Q1, Q2, P1, P2, P3, MT, MB, RMB, MHP, AMP2)
subroutine pytbhq (Q1, Q2, P1, P2, P3, MT, MB, RMB, MHP, AMP2)
DOUBLE PRECISION function pytbhs (A, B)
subroutine pymsin
subroutine pyslha (MUPDA, KFORIG, IRETRN)
subroutine pyapps
subroutine pysugi
subroutine pyfeyn (IERR)
function pyrnmq (ID, DTERM)
subroutine pythrg
subroutine pyinom
function pyrnm3 (RGUT)
subroutine pyeig4 (A, W, Z)
subroutine pyhggm (ALPHA)
subroutine pysubh (XMA, TANB, XMQ, XMUR, XMTOP, AU, AD, XMU, XMH, XHM, XMHCH, SA, CA, TANBA)
subroutine pypole (IHIGGS, XMC, XMA, TANB, XMQ, XMUR, XMDR, XMT, AT, AB, XMU, XMH, XMHP, HM, HMP, AMP, SA, CA, STOP1, STOP2, SBOT1, SBOT2, TANBA, XMG, DT, DB)
subroutine pyrghm (MCHI, MA, TANB, MQ, MUR, MD, MTOP, AU, AD, MU, MHP, HMP, MCH, SA, CA, SAB, CAB, TANBA, MGLU, DELTAMT, DELTAMB)
subroutine pygfxx (MA, TANB, MQ, MUR, MD, MTOP, AT, AB, XMU, XMGL, VH, STOP1, STOP2, SBOT1, SBOT2, DELTAMT, DELTAMB)
function pyfint (A, B, C)
function pyfisb (X)
subroutine pysfdc (KFIN, XLAM, IDLAM, IKNT)
subroutine pyglui (KFIN, XLAM, IDLAM, IKNT)
subroutine pytbbn (I, NN, E, XMGLU, GAM)
subroutine pytbbc (I, NN, XMGLU, GAM)
subroutine pynjdc (KFIN, XLAM, IDLAM, IKNT)
subroutine pycjdc (KFIN, XLAM, IDLAM, IKNT)
double precision function pyxxz6 (X)
double precision function pyxxga (C0, XM1, XM2, XMTR, XMTL)
double precision function pyx2xg (C1, XM1, XM2, XM3, GX2, GLR)
double precision function pyx2xh (C1, XM1, XM2, XM3, GX2, GLR)
subroutine pyhext (KFIN, XLAM, IDLAM, IKNT)
double precision function pyh2xx (C1, XM1, XM2, XM3, GX2, GLR)
function pygaus (F, A, B, EPS)
function pygau2 (F, A, B, EPS)
function pysimp (Y, X0, X1, N)
double precision function pylamf (X, Y, Z)
subroutine pytbdy (IDIN)
subroutine pytecm (SMIN, SMOU, WIDO, IOPT)
subroutine pyxdin
subroutine pyuedc
subroutine pyxued (NCHN, SIGS)
subroutine pygram (IN)
DOUBLE PRECISION function pygraw (YIN)
DOUBLE PRECISION function pywdkk (X)
subroutine pyeicg (NM, N, AR, AI, WR, WI, MATZ, ZR, ZI, FV1, FV2, FV3, IERR)
subroutine pycmqr (NM, N, LOW, IGH, HR, HI, WR, WI, IERR)
subroutine pycmq2 (NM, N, LOW, IGH, ORTR, ORTI, HR, HI, WR, WI, ZR, ZI, IERR)
subroutine pycdiv (AR, AI, BR, BI, CR, CI)
subroutine pycsrt (XR, XI, YR, YI)
DOUBLE PRECISION function pythag (A, B)
subroutine pycbal (NM, N, AR, AI, LOW, IGH, SCALE)
subroutine pycba2 (NM, N, LOW, IGH, SCALE, M, ZR, ZI)
subroutine pycrth (NM, N, LOW, IGH, AR, AI, ORTR, ORTI)
subroutine pyldcm (A, N, NP, INDX, D)
subroutine pybksb (A, N, NP, INDX, B)
subroutine pywidx (KFLR, SH, WDTP, WDTE)
subroutine pyrvsf (KFIN, XLAM, IDLAM, LKNT)
subroutine pyrvne (KFIN, XLAM, IDLAM, LKNT)
subroutine pyrvch (KFIN, XLAM, IDLAM, LKNT)
subroutine pyrvgl (KFIN, XLAM, IDLAM, LKNT)
function pyrvsb (KFIN, ID1, ID2, RM2, MODE)
subroutine pyrvgw (KFIN, ID1, ID2, ID3, XLAM)
double precision function pyrvi1 (ID1, ID2, ID3)
double precision function pyrvi2 (ID1, ID2, ID3)
double precision function pyrvi3 (ID1, ID2, ID3)
double precision function pyrvg1 (X)
double precision function pyrvg2 (X)
double precision function pyrvg3 (X)
double precision function pyrvg4 (Y)
double precision function pyrvr (Mab2, RM, RW)
double precision function pyrvs (X, Y, M1, W1, M2, W2)
subroutine py1ent (IP, KF, PE, THE, PHI)
subroutine py2ent (IP, KF1, KF2, PECM)
subroutine py3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
subroutine py4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
subroutine py2frm (IRAD, ITAU, ICOM)
subroutine py4frm (ATOTSQ, A1SQ, A2SQ, ISTRAT, IRAD, ITAU, ICOM)
subroutine py6frm (P12, P13, P21, P23, P31, P32, PTOP, IRAD, ITAU, ICOM)
subroutine py4jet (PMAX, IRAD, ICOM)
function py4jtw (IA1, IA2, IA3, IA4)
subroutine py4jts (IA1, IA2, IA3, IA4, IA5, QMAX)
subroutine pyjoin (NJOIN, IJOIN)
subroutine pygive (CHIN)
subroutine pyonof (CHIN)
subroutine pytune (ITUNE)
subroutine pyexec
subroutine pyprep (IP)
subroutine pystrf (IP)
subroutine pyjurf (PJU, VJU)
subroutine pyindf (IP)
subroutine pydecy (IP)
subroutine pydcyk (KFL1, KFL2, KFL3, KF)
subroutine pykfdi (KFL1, KFL2, KFL3, KF)
subroutine pynmes (KFDIQ)
subroutine pykfin
subroutine pyptdi (KFL, PX, PY)
subroutine pyzdis (KFL1, KFL2, PR, Z)
subroutine pyshow (IP1, IP2, QMAX)
subroutine pyptfs (MODE, PTMAX, PTMIN, PTGEN)
function pymael (NI, X1, X2, R1, R2, ALPHA)
subroutine pyboei (NSAV)
subroutine pybesq (I1, I2, NI, Q2OLD, Q2NEW)
function pymass (KF)
function pymrun (KF, Q2)
subroutine pyname (KF, CHAU)
integer function pychge (KF)
integer function pycomp (KF)
subroutine pyerrm (MERR, CHMESS)
function pyalem (Q2)
function pyalps (Q2)
function pyangl (X, Y)
function pyr (IDUMMY)
subroutine pyrget (LFN, MOVE)
subroutine pyrset (LFN, MOVE)
subroutine pyrobo (IMI, IMA, THE, PHI, BEX, BEY, BEZ)
subroutine pyedit (MEDIT)
subroutine pylist (MLIST)
subroutine pylogo
subroutine pyupda (MUPDA, LFN)
integer function pyk (I, J)
function pyp (I, J)
subroutine pysphe (SPH, APL)
subroutine pythru (THR, OBL)
subroutine pyclus (NJET)
subroutine pycell (NJET)
subroutine pyjmas (PMH, PML)
subroutine pyfowo (H10, H20, H30, H40)
subroutine pytabu (MTABU)
subroutine pyeevt (KFL, ECM)
subroutine pyxtee (KFL, ECM, XTOT)
subroutine pyradk (ECM, MK, PAK, THEK, PHIK, ALPK)
subroutine pyxkfl (KFL, ECM, ECMC, KFLC)
subroutine pyxjet (ECM, NJET, CUT)
subroutine pyx3jt (NJET, CUT, KFL, ECM, X1, X2)
subroutine pyx4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
subroutine pyxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
subroutine pyonia (KFL, ECM)
subroutine pybook (ID, TITLE, NX, XL, XU)
subroutine pyfill (ID, X, W)
subroutine pyfact (ID, F)
subroutine pyoper (ID1, OPER, ID2, ID3, F1, F2)
subroutine pyhist
subroutine pyplot (ID)
subroutine pynull (ID)
subroutine pydump (MDUMP, LFN, NHI, IHI)
subroutine pystop (MCOD)
subroutine pykcut (MCUT)
subroutine pyevwt (WTXS)
subroutine upinit
subroutine upevnt
subroutine upveto (IVETO)
subroutine sugra (MZERO, MHLF, AZERO, TANB, SGNMU, MTOP, IMODL)
character *40 function visaje ()
subroutine ssmssm (RDUM1, RDUM2, RDUM3, RDUM4, RDUM5, RDUM6, RDUM7, RDUM8, RDUM9, RDUM10, RDUM11, RDUM12, RDUM13, RDUM14, RDUM15, RDUM16, RDUM17, RDUM18, RDUM19, RDUM20, RDUM21, RDUM22, RDUM23, RDUM24, RDUM25, IDUM1, IDUM2)
subroutine fhsetflags (IERR, IMSP, IFR, ITBR, IHMX, IP2A, ILP, ITR, IBR)
subroutine fhsetpara (IER, SCF, DMT, DMB, DMW, DMZ, DTANB, DMA, DMH, DM3L, DM3E, DM3Q, DM3U, DM3D, DM2L, DM2E, DM2Q, DM2U, DM2D, DM1L, DM1E, DM1Q, DM1U, DM1D, DMU, AE33, AU33, AD33, AE22, AU22, AD22, AE11, AU11, AD11, DM1, DM2, DM3, RLT, RLB, QTAU, QT, QB)
subroutine fhhiggscorr (IERR, RMHIGG, SAEFF, UHIGGS)
subroutine pytaud (ITAU, IORIG, KFORIG, NDECAY)
subroutine pytime (IDATI)
Function/Subroutine Documentation
subroutine fhhiggscorr (IERR, double precision, dimension(4) RMHIGG, double complex SAEFF, double complex, dimension(3,3) UHIGGS)
Definition at line 80770 of file pythia6425mod.f.
References pydat1, pystop(), and x.
Referenced by pyfeyn().
subroutine fhsetflags (IERR, IMSP, IFR, ITBR, IHMX, IP2A, ILP, ITR, IBR)
Definition at line 80706 of file pythia6425mod.f.
References pydat1, pystop(), and x.
Referenced by pyfeyn().
subroutine fhsetpara (IER, SCF, DMT, DMB, DMW, DMZ, DTANB, DMA, DMH, DM3L, DM3E, DM3Q, DM3U, DM3D, DM2L, DM2E, DM2Q, DM2U, DM2D, DM1L, DM1E, DM1Q, DM1U, DM1D, double complex DMU, double complex AE33, double complex AU33, double complex AD33, double complex AE22, double complex AU22, double complex AD22, double complex AE11, double complex AU11, double complex AD11, double complex DM1, double complex DM2, double complex DM3, RLT, RLB, QTAU, QT, QB)
Definition at line 80738 of file pythia6425mod.f.
References pydat1, pystop(), and x.
Referenced by pyfeyn().
subroutine py1ent (IP, KF, PE, THE, PHI)
Definition at line 59229 of file pythia6425mod.f.
References j, k, max, n, phi, pycomp, pydat1, pyerrm(), pyexec(), pyjets, pylist(), pymass(), and v.
subroutine py2ent (IP, KF1, KF2, PECM)
Definition at line 59284 of file pythia6425mod.f.
References i, j, k, max, n, pycomp, pydat1, pyerrm(), pyexec(), pyjets, pylist(), pymass(), and v.
Referenced by pyeevt(), pyonia(), pyresd(), and pytest().
subroutine py2frm (IRAD, ITAU, ICOM)
Definition at line 59665 of file pythia6425mod.f.
References i, k, max, n, pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyshow(), and v.
subroutine py3ent (IP, KF1, KF2, KF3, PECM, X1, X3)
Definition at line 59376 of file pythia6425mod.f.
References d, i, j, k, max, min, n, pycomp, pydat1, pyerrm(), pyexec(), pyjets, pylist(), pymass(), v, and x3.
Referenced by pyeevt(), pyonia(), pyresd(), and pytest().
subroutine py4ent (IP, KF1, KF2, KF3, KF4, PECM, X1, X2, X4, X12, X14)
Definition at line 59498 of file pythia6425mod.f.
References d, i, j, k, max, min, n, pycomp, pydat1, pyerrm(), pyexec(), pyjets, pylist(), pymass(), pyr(), v, and x2.
Referenced by pyeevt(), pyresd(), and pytest().
subroutine py4frm (ATOTSQ, A1SQ, A2SQ, ISTRAT, IRAD, ITAU, ICOM)
Definition at line 59774 of file pythia6425mod.f.
References i, j, k, max, n, pychge(), pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyr(), pyreco(), pyshow(), and v.
subroutine py4jet (PMAX, IRAD, ICOM)
Definition at line 60366 of file pythia6425mod.f.
References i, j, k, max, n, phi, py4jts(), py4jtw(), pyangl(), pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyr(), pyrobo(), pyshow(), and v.
subroutine py4jts (IA1, IA2, IA3, IA4, IA5, QMAX)
Definition at line 60642 of file pythia6425mod.f.
References i, j, k, max, min, n, pyjets, and v.
Referenced by py4jet().
function py4jtw (IA1, IA2, IA3, IA4)
Definition at line 60574 of file pythia6425mod.f.
References j, k, max, n, pyjets, v, z1, and z2.
Referenced by py4jet().
subroutine py6frm (P12, P13, P21, P23, P31, P32, PTOP, IRAD, ITAU, ICOM)
Definition at line 60002 of file pythia6425mod.f.
References i, it, j, k, max, n, pychge(), pydat1, pyerrm(), pyexec(), pyhepc(), pyjets, pyjoin(), pyr(), pyrobo(), pyshow(), and v.
subroutine pyadsh (NFIN)
Definition at line 16804 of file pythia6425mod.f.
References i, j, k, max, min, n, npart(), pydat1, pyerrm(), pyjets, pyptfs(), pyrobo(), pyshow(), and v.
Referenced by pyevnt(), and pyevnw().
function pyalem (Q2)
Definition at line 74312 of file pythia6425mod.f.
References d, and pydat1.
Referenced by pycjdc(), pyglui(), pyhext(), pyinom(), pymaxi(), pynjdc(), pypdel(), pysfdc(), pysigh(), pysubh(), pytbbc(), pytbbn(), pytecm(), pywidt(), and pywidx().
function pyalps (Q2)
Definition at line 74358 of file pythia6425mod.f.
References b1, max, min, and pydat1.
Referenced by pycjdc(), pyevol(), pyglui(), pyhfth(), pyinom(), pymign(), pymrun(), pynjdc(), pyonia(), pyrnm3(), pyrnmq(), pyrvgl(), pysfdc(), pysgqc(), pysgtc(), pysgwz(), pysigh(), pysspa(), pysubh(), pytbbc(), pytbbn(), pyuedc(), pywidt(), pywidx(), pyxjet(), pyxtee(), and pyxued().
function pyangl (X, Y)
Definition at line 74438 of file pythia6425mod.f.
References d, pydat1, r, sign(), x, and y.
Referenced by py4jet(), pybesq(), pycell(), pydecy(), pydiff(), pydocu(), pyedit(), pygaga(), pyindf(), pyinki(), pymirm(), pyp(), pyprep(), pyptfs(), pyptis(), pyradk(), pyremn(), pyresd(), pyscat(), pyshow(), pysspa(), pytabu(), and pythru().
subroutine pyapps ()
Definition at line 47588 of file pythia6425mod.f.
References boost::array< T, N >::at(), d, i, pycomp, pydat1, pymrun(), pyrnmq(), pystop(), and sign().
Referenced by pymsin().
subroutine pybesq (I1, I2, NI, Q2OLD, Q2NEW)
Definition at line 73937 of file pythia6425mod.f.
References j, k, max, n, ni, phi, pyangl(), pydat1, pyjets, pyrobo(), s, and v.
Referenced by pyboei().
subroutine pybksb (complex*16, dimension(np,np) A, integer N, integer NP, integer, dimension(n) INDX, complex*16, dimension(n) B)
Definition at line 57298 of file pythia6425mod.f.
References i, j, n, and sum().
Referenced by pysgtc().
subroutine pyboei (NSAV)
Definition at line 73432 of file pythia6425mod.f.
References d, dx, i, j, k, max, min, n, nbin, pybesq(), pydat1, pyerrm(), pyjets, pymass(), pyp(), pyr(), pyrobo(), v, and sHelix::w().
Referenced by pyexec().
subroutine pybook (ID, character, dimension(*) TITLE, NX, XL, XU)
Definition at line 79471 of file pythia6425mod.f.
References it, pyerrm(), pynull(), and title.
Referenced by pydump().
subroutine pycba2 (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5) SCALE, integer M, double precision, dimension(5,5) ZR, double precision, dimension(5,5) ZI)
Definition at line 57043 of file pythia6425mod.f.
References i, j, k, n, and s.
Referenced by pyeicg().
subroutine pycbal (integer NM, integer N, double precision, dimension(5,5) AR, double precision, dimension(5,5) AI, integer LOW, integer IGH, double precision, dimension(5) SCALE)
Definition at line 56872 of file pythia6425mod.f.
References c, false, g, i, j, k, n, r, radix, s, and true.
Referenced by pyeicg().
subroutine pycdiv (double precision AR, double precision AI, double precision BR, double precision BI, double precision CR, double precision CI)
Definition at line 56749 of file pythia6425mod.f.
References ci, and s.
Referenced by pycmq2(), and pycmqr().
subroutine pycell (NJET)
Definition at line 76885 of file pythia6425mod.f.
References d, i, j, k, max, min, n, HiMain1::np(), phi, HiStrng::pt(), pyangl(), pychge(), pycomp, pydat1, pyerrm(), pyjets, pyr(), sign(), and v.
integer function pychge (KF)
Definition at line 74145 of file pythia6425mod.f.
References pycomp.
Referenced by py4frm(), py6frm(), pycell(), pyclus(), pyedit(), pyexec(), pyfowo(), pyjmas(), pyk(), pyp(), pyscat(), pyslha(), pysphe(), pytabu(), pythru(), and pyupda().
subroutine pycjdc (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 53061 of file pythia6425mod.f.
References d, ei(), i, j, pi, pyalem(), pyalps(), pycomp, pydat1, pygaus(), pylamf(), pyrvch(), pyx2xg(), pyx2xh(), pyxxz6(), and sign().
Referenced by pymsin().
subroutine pyckbd ()
Definition at line 2236 of file pythia6425mod.f.
References k, n, pydat1, pydat3, pyjets, pystop(), and v.
Referenced by pyinit().
subroutine pyclus (NJET)
Definition at line 76507 of file pythia6425mod.f.
References d, i, j, k, max, min, n, HiMain1::np(), ps(), pychge(), pycomp, pydat1, pyerrm(), pyjets, r2, and v.
subroutine pycmq2 (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5) ORTR, double precision, dimension(5) ORTI, double precision, dimension(5,5) HR, double precision, dimension(5,5) HI, double precision, dimension(5) WR, double precision, dimension(5) WI, double precision, dimension(5,5) ZR, double precision, dimension(5,5) ZI, integer IERR)
Definition at line 56402 of file pythia6425mod.f.
References i, j, k, n, norm, pycdiv(), pycsrt(), pythag(), and x.
Referenced by pyeicg().
subroutine pycmqr (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5,5) HR, double precision, dimension(5,5) HI, double precision, dimension(5) WR, double precision, dimension(5) WI, integer IERR)
Definition at line 56158 of file pythia6425mod.f.
References i, j, n, norm, pycdiv(), pycsrt(), pythag(), and x.
Referenced by pyeicg().
integer function pycomp (KF)
Definition at line 74169 of file pythia6425mod.f.
References i, pycomp, and pydat1.
subroutine pycrth (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(5,5) AR, double precision, dimension(5,5) AI, double precision, dimension(5) ORTR, double precision, dimension(5) ORTI)
Definition at line 57135 of file pythia6425mod.f.
References g, i, j, n, and pythag().
Referenced by pyeicg().
subroutine pycsrt (double precision XR, double precision XI, double precision YR, double precision YI)
Definition at line 56774 of file pythia6425mod.f.
References pythag(), and s.
Referenced by pycmq2(), and pycmqr().
function pyct5l (IFL, X, Q)
Definition at line 41854 of file pythia6425mod.f.
References i, k, sHelix::u(), x, and y.
Referenced by pypdpr().
function pyct5m (IFL, X, Q)
Definition at line 42109 of file pythia6425mod.f.
References i, k, sHelix::u(), x, and y.
Referenced by pypdpr().
function pycteq (ISET, IPRT, X, Q)
Definition at line 41119 of file pythia6425mod.f.
References d, i, max, and x.
Referenced by pypdpr().
subroutine pycttr (I, KCS, IEND)
Definition at line 22991 of file pythia6425mod.f.
References i, k, n, pycomp, pydat1, pyerrm(), pyjets, pylist(), and v.
Referenced by pyevnw(), pyfscr(), pymihk(), pyprep(), pyptfs(), pyptis(), and pyptmi().
subroutine pydcyk (KFL1, KFL2, KFL3, KF)
Definition at line 68723 of file pythia6425mod.f.
References g, min, pycomp, pydat1, pykfdi(), pymass(), pyptdi(), pyr(), pyzdis(), x, and z.
Referenced by pydecy(), and pyprep().
subroutine pydecy (IP)
Definition at line 67901 of file pythia6425mod.f.
References c, d, four, simpleRandom::gauss(), i, j, k, max, min, n, HiMain1::np(), ntry, phi, ps(), pyangl(), pycomp, pydat1, pydat3, pydcyk(), pyerrm(), pyjets, pykfdi(), pymass(), pyr(), pyrobo(), pytaud(), and v.
Referenced by pydiff(), and pyexec().
subroutine pydiff ()
Definition at line 24282 of file pythia6425mod.f.
References i, j, k, max, n, ntry, phi, pyangl(), pydat1, pydecy(), pyjets, pykfdi(), pymass(), pyr(), pyrobo(), pyspli(), and v.
Referenced by pyevnt(), pyevnw(), and pyupev().
subroutine pydisg ()
Definition at line 24508 of file pythia6425mod.f.
References d, i, j, k, max, min, n, ntry, phi, HiStrng::pt(), pycomp, pydat1, pyjets, pymass(), pyptdi(), pyr(), pyrobo(), pyshow(), pyspli(), pyzdis(), and v.
Referenced by pyevnt(), pyevnw(), and pyupev().
subroutine pydocu ()
Definition at line 24815 of file pythia6425mod.f.
References d, i, j, k, max, min, n, HiStrng::pt(), pyangl(), pydat1, pyjets, pysave(), sign(), and v.
Referenced by pyevnt(), pyevnw(), and pyupev().
subroutine pydump (MDUMP, LFN, NHI, dimension(*) IHI)
Definition at line 79888 of file pythia6425mod.f.
References boost::array< T, N >::end(), msg_buffer::format(), it, pybook(), pyerrm(), title, and x.
subroutine pyedit (MEDIT)
Definition at line 74740 of file pythia6425mod.f.
References d, i, j, k, max, n, pyangl(), pychge(), pycomp, pydat1, pyerrm(), pyjets, pyrobo(), sign(), and v.
Referenced by pyevnt(), pyevnw(), and pymihk().
subroutine pyeevt (KFL, ECM)
Definition at line 78130 of file pythia6425mod.f.
References k, max, min, n, ntry, phi, py1ent, py2ent(), py3ent(), py4ent(), pydat1, pyerrm(), pyexec(), pyjets, pylist(), pyprep(), pyradk(), pyrobo(), pyshow(), pyx3jt(), pyx4jt(), pyxdif(), pyxjet(), pyxkfl(), pyxtee(), v, x2, and x3.
Referenced by pytest().
subroutine pyeicg (integer NM, integer N, double precision, dimension(5,5) AR, double precision, dimension(5,5) AI, double precision, dimension(5) WR, double precision, dimension(5) WI, integer MATZ, double precision, dimension(5,5) ZR, double precision, dimension(5,5) ZI, double precision, dimension(5) FV1, double precision, dimension(5) FV2, double precision, dimension(5) FV3, integer IERR)
Definition at line 56076 of file pythia6425mod.f.
References n, pycba2(), pycbal(), pycmq2(), pycmqr(), pycrth(), and x.
Referenced by pyinom(), and pytecm().
subroutine pyeig4 (dimension(4,4) A, dimension(4) W, dimension(4,4) Z)
Definition at line 49193 of file pythia6425mod.f.
References b1, c2, d, i, j, pyr(), s1, sHelix::u(), sHelix::w(), x, and z.
subroutine pyerrm (MERR, character, dimension(*) CHMESS)
Definition at line 74254 of file pythia6425mod.f.
References k, n, pydat1, pyjets, pylist(), pystop(), v, and x.
Referenced by py1ent(), py2ent(), py2frm(), py3ent(), py4ent(), py4frm(), py4jet(), py6frm(), pyadsh(), pyboei(), pybook(), pycell(), pyclus(), pycttr(), pydecy(), pydump(), pyedit(), pyeevt(), pyevnt(), pyevnw(), pyevol(), pyexec(), pyfact(), pyfeyn(), pyfill(), pyfowo(), pyfscr(), pygau2(), pygaus(), pygive(), pyhepc(), pyhggm(), pyindf(), pyinki(), pyinom(), pyinpr(), pyjmas(), pyjoin(), pykfdi(), pykfin(), pyldcm(), pymael(), pymaxi(), pymign(), pymihg(), pymihk(), pymirm(), pymult(), pynmes(), pyofsh(), pyonia(), pyonof(), pyoper(), pypdfu(), pyprep(), pyptfs(), pyptis(), pyptmi(), pyrand(), pyresd(), pyrget(), pyrobo(), pyrset(), pyscat(), pysghg(), pyshow(), pyslha(), pysphe(), pyspli(), pysspa(), pystrf(), pysugi(), pytabu(), pythrg(), pythru(), pytune(), pyupda(), pyupre(), pyxjet(), pyxkfl(), and pyxtot().
subroutine pyevnt ()
Definition at line 3195 of file pythia6425mod.f.
References d, i, j, k, max, min, n, npart(), pyadsh(), pycomp, pydat1, pydat3, pydiff(), pydisg(), pydocu(), pyedit(), pyerrm(), pyevnw(), pyexec(), pyfram(), pyfscr(), pygaga(), pyinki(), pyjets, pymign(), pymihk(), pymirm(), pymult(), pypile(), pyprep(), pyptfs(), pyr(), pyrand(), pyremn(), pyresd(), pysave(), pyscat(), pyshow(), pysspa(), pystop(), pyveto(), pyxtot(), v, and x.
Referenced by genevent(), and pytest().
subroutine pyevnw ()
Definition at line 3569 of file pythia6425mod.f.
References d, i, j, k, max, min, n, npart(), pyadsh(), pycomp, pycttr(), pydat1, pydat3, pydiff(), pydisg(), pydocu(), pyedit(), pyerrm(), pyevol(), pyexec(), pyfram(), pyfscr(), pygaga(), pyinki(), pyjets, pymihk(), pymirm(), pypile(), pyprep(), pyptfs(), pyr(), pyrand(), pyremn(), pyresd(), pysave(), pyscat(), pystop(), pyveto(), pyxtot(), v, and x.
Referenced by pyevnt().
subroutine pyevol (MODE, PT2MAX, PT2MIN)
Definition at line 13594 of file pythia6425mod.f.
References d, i, j, k, max, n, npart(), pyalps(), pydat1, pyerrm(), pyjets, pyptis(), pyptmi(), and v.
Referenced by pyevnw().
subroutine pyevwt (WTXS)
Definition at line 80198 of file pythia6425mod.f.
References pydat1.
Referenced by pymaxi(), and pyrand().
subroutine pyexec ()
Definition at line 64187 of file pythia6425mod.f.
References i, j, k, max, min, n, ps(), pyboei(), pychge(), pycomp, pydat1, pydat3, pydecy(), pyerrm(), pyindf(), pyjets, pylist(), pyprep(), pyresd(), pyshow(), pystrf(), and v.
Referenced by genevent(), py1ent(), py2ent(), py2frm(), py3ent(), py4ent(), py4frm(), py4jet(), py6frm(), pyeevt(), pyevnt(), pyevnw(), pyonia(), and pytest().
subroutine pyfact (ID, F)
Definition at line 79554 of file pythia6425mod.f.
References pyerrm().
double precision function pyfcmp (double precision XC, double precision XS, integer NPOW)
Definition at line 16619 of file pythia6425mod.f.
References y.
Referenced by pypdfu(), and pyptis().
subroutine pyfeyn (IERR)
Definition at line 48247 of file pythia6425mod.f.
References fhhiggscorr(), fhsetflags(), fhsetpara(), pydat1, pyerrm(), and r.
Referenced by pyslha(), and pysugi().
subroutine pyfill (ID, X, W)
Definition at line 79517 of file pythia6425mod.f.
References max, min, pyerrm(), sHelix::w(), and x.
function pyfint (A, B, C)
Definition at line 50639 of file pythia6425mod.f.
References c, d, pyfisb(), pygaus(), xhi, and xlo.
Referenced by pypole().
function pyfisb (X)
Definition at line 50668 of file pythia6425mod.f.
References x.
Referenced by pyfint().
subroutine pyfowo (H10, H20, H30, H40)
Definition at line 77284 of file pythia6425mod.f.
References i, j, k, n, HiMain1::np(), pychge(), pycomp, pydat1, pyerrm(), pyjets, and v.
subroutine pyfram (IFRAME)
Definition at line 25003 of file pythia6425mod.f.
References pydat1, pyrobo(), and x.
Referenced by pyevnt(), pyevnw(), and pyupev().
subroutine pyfscr (IP)
Definition at line 23830 of file pythia6425mod.f.
References four, i, it, j, k, max, min, n, pycomp, pycttr(), pydat1, pyerrm(), pyjets, pyr(), pystop(), pythru(), and v.
Referenced by pyevnt(), and pyevnw().
subroutine pygaga (IGAGA, WTGAGA)
Definition at line 8777 of file pythia6425mod.f.
References d, i, j, k, max, min, n, phi, HiStrng::pt(), pyangl(), pycomp, pydat1, pyjets, pyr(), pyrobo(), pyxtot(), sign(), v, x, y, and ymax.
Referenced by pyevnt(), pyevnw(), pyinit(), pymaxi(), pyrand(), and pyupev().
function pygamm (X)
Definition at line 43104 of file pythia6425mod.f.
References dx, i, and x.
Referenced by pygraw(), pypdel(), pypdpi(), and pypdpo().
subroutine pygano (KF, X, Q2, P2, ALAM, dimension(-6:6) XPGA, dimension(-6:6) VXPGA)
Definition at line 40529 of file pythia6425mod.f.
References max, HiStrng::nfp(), s, and x.
Referenced by pyggam(), and pypdfu().
function pygau2 (double precision, external F, A, B, EPS)
Definition at line 54551 of file pythia6425mod.f.
References c2, d, i, pyerrm(), sHelix::u(), sHelix::w(), and x.
Referenced by pyrvg3().
function pygaus (double precision, external F, A, B, EPS)
Definition at line 54483 of file pythia6425mod.f.
References c2, d, i, pyerrm(), sHelix::u(), sHelix::w(), and x.
Referenced by pycjdc(), pyfint(), pyglui(), pygram(), pynjdc(), pyrvi1(), pyrvi2(), and pyrvi3().
subroutine pygbeh (KF, X, Q2, P2, PM2, XPBH)
Definition at line 40692 of file pythia6425mod.f.
References d, and x.
Referenced by pyggam().
subroutine pygdir (X, Q2, P2, Q02, dimension(-6:6) XPGA)
Definition at line 40759 of file pythia6425mod.f.
References x.
Referenced by pyggam().
subroutine pygfxx (MA, TANB, MQ, MUR, MD, MTOP, AT, AB, XMU, XMGL, dimension(2,2) VH, STOP1, STOP2, SBOT1, SBOT2, DELTAMT, DELTAMB)
Definition at line 50317 of file pythia6425mod.f.
References boost::array< T, N >::at(), g, h1b, h2b, i, j, pi, pydat1, pymrun(), t, t1, t2, v, x, y, and z.
Referenced by pyrghm().
subroutine pyggam (ISET, X, Q2, P2, IP2, F2GM, dimension(-6:6) XPDFGM)
Definition at line 40109 of file pythia6425mod.f.
References d, max, min, pygano(), pygbeh(), pygdir(), pygvmd(), and x.
Referenced by pypdel(), and pypdfu().
subroutine pygive (character, dimension(*) CHIN)
Definition at line 60846 of file pythia6425mod.f.
References i, j, k, n, pycomp, pydat1, pydat3, pyerrm(), pyjets, pylist(), pyonof(), v, and x.
Referenced by pymirm(), pyptfs(), and pyxdin().
subroutine pyglui (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 51342 of file pythia6425mod.f.
References d, ei(), i, min, pi, pyalem(), pyalps(), pycomp, pydat1, pygaus(), pylamf(), pyrvgl(), pytbbc(), pytbbn(), pyxxz6(), and sign().
Referenced by pymsin().
subroutine pygram (IN)
Definition at line 55810 of file pythia6425mod.f.
References d, i, in, min, pi, pydat1, pygaus(), pygraw(), pyr(), pystop(), x, y, and ymax.
Referenced by pyresd(), and pyxdin().
DOUBLE PRECISION function pygraw (YIN)
Definition at line 55945 of file pythia6425mod.f.
References d, i, n, pi, pydat1, pygamm(), pywdkk(), and ymax.
Referenced by pygram().
subroutine pygrvd (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
Definition at line 41625 of file pythia6425mod.f.
References cd(), dx, pygrvs(), pygrvv(), pygrvw(), s, and x.
Referenced by pypdpr().
subroutine pygrvl (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
Definition at line 41392 of file pythia6425mod.f.
References cd(), dx, pygrvs(), pygrvv(), pygrvw(), s, and x.
Referenced by pypdpr().
subroutine pygrvm (X, Q2, UV, DV, DEL, UDB, SB, CHM, BOT, GL)
Definition at line 41509 of file pythia6425mod.f.
References cd(), dx, pygrvs(), pygrvv(), pygrvw(), s, and x.
Referenced by pypdpr().
function pygrvs (X, S, STH, AL, BE, AK, AG, B, D, E, ES)
Definition at line 41781 of file pythia6425mod.f.
References d, dx, s, and x.
Referenced by pygrvd(), pygrvl(), and pygrvm().
function pygrvv (X, N, AK, BK, A, B, C, D)
Definition at line 41741 of file pythia6425mod.f.
References bk(), c, d, dx, n, and x.
Referenced by pygrvd(), pygrvl(), and pygrvm().
function pygrvw (X, S, AL, BE, AK, BK, A, B, C, D, E, ES)
Definition at line 41761 of file pythia6425mod.f.
References bk(), c, d, s, and x.
Referenced by pygrvd(), pygrvl(), and pygrvm().
subroutine pygvmd (ISET, KF, X, Q2, P2, ALAM, dimension(-6:6) XPGA, dimension(-6:6) VXPGA)
Definition at line 40310 of file pythia6425mod.f.
References max, HiStrng::nfp(), s, and x.
Referenced by pyggam(), and pypdfu().
double precision function pyh2xx (double precision C1, double precision XM1, double precision XM2, double precision XM3, GX2, GLR)
Definition at line 54449 of file pythia6425mod.f.
References pydat1, and pylamf().
Referenced by pyhext().
subroutine pyhepc (MCONV)
Definition at line 2699 of file pythia6425mod.f.
References i, j, k, min, n, pycomp, pydat1, pyerrm(), pyjets, and v.
Referenced by py2frm(), py4frm(), py4jet(), and py6frm().
subroutine pyhext (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 53984 of file pythia6425mod.f.
References d, ei(), gr, i, j, min, pyalem(), pycomp, pydat1, pyh2xx(), and pylamf().
Referenced by pymsin().
function pyhfth (SH, SQM, FRATT)
Definition at line 42864 of file pythia6425mod.f.
References d, max, min, pyalps(), and pydat1.
Referenced by pysghf(), pysgtc(), pywidt(), and pywidx().
subroutine pyhggm (double precision ALPHA)
Definition at line 49351 of file pythia6425mod.f.
References boost::array< T, N >::at(), d, pycomp, pydat1, pyerrm(), pypole(), and pysubh().
Referenced by pymsin().
subroutine pyhist ()
Definition at line 79681 of file pythia6425mod.f.
References pynull(), and pyplot().
subroutine pyi3au (EPS, RAT, Y3RE, Y3IM)
Definition at line 43180 of file pythia6425mod.f.
References d, max, min, phi, pydat1, pyspen(), and r.
Referenced by pysghg(), and pysgqc().
subroutine pyinbm (character CHFRAM, character CHBEAM, character CHTARG, WIN)
Definition at line 5533 of file pythia6425mod.f.
References i, j, k, max, n, pydat1, pyjets, pymass(), pyname(), pystop(), s, sign(), v, and x.
Referenced by pyinit().
subroutine pyindf (IP)
Definition at line 67429 of file pythia6425mod.f.
References d, i, j, k, max, min, n, ntry, phi, pyangl(), pycomp, pydat1, pyerrm(), pyjets, pykfdi(), pymass(), pyptdi(), pyr(), pyrobo(), pyzdis(), v, sHelix::w(), and z.
Referenced by pyexec().
subroutine pyinit (character*(*) FRAME, character*(*) BEAM, character*(*) TARGET, WIN)
Definition at line 2870 of file pythia6425mod.f.
References i, j, min, pyckbd(), pydat1, pydat3, pygaga(), pyinbm(), pyinki(), pyinpr(), pyinre(), pykfin(), pylist(), pymaxi(), pymign(), pymsin(), pymult(), pypile(), pysave(), pystop(), pytune, pyxdin(), pyxtot(), upinit(), value, and x.
Referenced by initpythia(), and pytest().
subroutine pyinki (MODKI)
Definition at line 5812 of file pythia6425mod.f.
References i, j, k, max, n, pyangl(), pydat1, pyerrm(), pyjets, pyrobo(), s, sign(), and v.
Referenced by pyevnt(), pyevnw(), pyinit(), and pyupev().
subroutine pyinom ()
Definition at line 48703 of file pythia6425mod.f.
References boost::array< T, N >::at(), d, i, index, j, k, pyalem(), pyalps(), pycomp, pydat1, pyeicg(), pyerrm(), pyrnm3(), pystop(), s, sign(), and x0.
Referenced by pymsin().
subroutine pyinpr ()
Definition at line 6010 of file pythia6425mod.f.
References i, j, max, min, pycomp, pydat1, pydat3, and pyerrm().
Referenced by pyinit().
subroutine pyinre ()
Definition at line 5218 of file pythia6425mod.f.
References i, j, min, pycomp, pydat1, pydat3, pystop(), pywidt(), and x.
Referenced by pyinit().
subroutine pyjmas (PMH, PML)
Definition at line 77103 of file pythia6425mod.f.
References d, i, j, k, max, min, n, HiMain1::np(), ps(), pychge(), pycomp, pydat1, pyerrm(), pyjets, and v.
subroutine pyjoin (NJOIN, dimension(*) IJOIN)
Definition at line 60786 of file pythia6425mod.f.
References i, in, k, n, pycomp, pydat1, pyerrm(), pyjets, pyr(), and v.
Referenced by py2frm(), py4frm(), py4jet(), py6frm(), and pyreco().
subroutine pyjurf (dimension(3,5) PJU, dimension(5) VJU)
Definition at line 67221 of file pythia6425mod.f.
References d, i, j, k, max, and twopi.
Referenced by pyprep(), and pystrf().
integer function pyk (I, J)
Definition at line 75939 of file pythia6425mod.f.
References i, j, k, max, n, pychge(), pycomp, pydat1, pyjets, and v.
Referenced by pyptfs().
subroutine pykcut (MCUT)
Definition at line 80068 of file pythia6425mod.f.
References max, pydat1, pystop(), tau, x, and x2.
Referenced by pyrand().
subroutine pykfdi (KFL1, KFL2, KFL3, KF)
Definition at line 68861 of file pythia6425mod.f.
References max, min, pycomp, pydat1, pyerrm(), pykfin(), pynmes(), and pyr().
Referenced by pydcyk(), pydecy(), pydiff(), pyindf(), pymihk(), pyprep(), pyspli(), and pystrf().
subroutine pykfin ()
Definition at line 69355 of file pythia6425mod.f.
References d, i, max, min, pycomp, pydat1, pyerrm(), and pymass().
Referenced by pyinit(), and pykfdi().
subroutine pyklim (ILIM)
Definition at line 29026 of file pythia6425mod.f.
References d, k, max, min, n, pydat1, pydat3, pyjets, sign(), tau, v, x2, and y3.
Referenced by pymaxi(), pymign(), pymult(), pyptmi(), and pyrand().
subroutine pykmap (IVAR, MVAR, VVAR)
Definition at line 29442 of file pythia6425mod.f.
References d, max, min, pydat1, pyr(), tau, and y3.
Referenced by pymaxi(), pymign(), pymult(), pyptmi(), and pyrand().
double precision function pylamf (double precision X, double precision Y, double precision Z)
Definition at line 54643 of file pythia6425mod.f.
References x, y, and z.
Referenced by pycjdc(), pyglui(), pyh2xx(), pyhext(), pynjdc(), pysfdc(), pytbbc(), pytbbn(), pyx2xg(), and pyx2xh().
subroutine pyldcm (complex*16, dimension(np,np) A, integer N, integer NP, integer, dimension(n) INDX, real*8 D)
Definition at line 57231 of file pythia6425mod.f.
References d, i, j, k, n, pyerrm(), and sum().
Referenced by pysgtc().
subroutine pylhef ()
Definition at line 5098 of file pythia6425mod.f.
References boost::array< T, N >::end(), i, and tileHelper::status().
subroutine pylist (MLIST)
Definition at line 75039 of file pythia6425mod.f.
References i, j, k, max, min, n, ps(), pycomp, pydat1, pydat3, pyjets, pylogo(), pyname(), pyp(), v, and x.
Referenced by makesplitting(), pevrec(), py1ent(), py2ent(), py3ent(), py4ent(), pycttr(), pyeevt(), pyerrm(), pyexec(), pygive(), pyinit(), pymihk(), pyonia(), pyprep(), pyptfs(), pyrand(), pytest(), pyupda(), and upveto().
subroutine pylogo ()
Definition at line 75393 of file pythia6425mod.f.
References j, line, max, min, pydat1, pystop(), and pytime().
Referenced by pylist().
function pymael (NI, X1, X2, R1, R2, ALPHA)
Definition at line 72774 of file pythia6425mod.f.
References max, min, ni, ps(), pyerrm(), r1, r2, and x2.
Referenced by pyptfs(), and pyshow().
function pymass (KF)
Definition at line 74014 of file pythia6425mod.f.
References d, max, pycomp, pydat1, and pyr().
Referenced by py1ent(), py2ent(), py3ent(), py4ent(), pyboei(), pydcyk(), pydecy(), pydiff(), pydisg(), pyinbm(), pyindf(), pykfin(), pymign(), pymihk(), pymrun(), pyp(), pyprep(), pyptis(), pyptmi(), pyradk(), pyrand(), pyremn(), pyresd(), pyscat(), pyshow(), pysigh(), pysspa(), pystrf(), pytabu(), pytest(), pyx3jt(), pyx4jt(), pyxdif(), pyxkfl(), and pyxtee().
subroutine pymaxi ()
Definition at line 7316 of file pythia6425mod.f.
References d, false, i, j, max, min, nbin, ntry, pyalem(), pycomp, pydat1, pydat3, pyerrm(), pyevwt(), pygaga(), pyklim(), pykmap(), pyofsh(), pysigh(), pystop(), pytecm(), s1, tau, true, and x.
Referenced by pyinit().
subroutine pymemx (MECOR, WTFF, WTGF, WTFG, WTGG)
Definition at line 15936 of file pythia6425mod.f.
References k, n, pydat1, pyjets, and v.
Referenced by pyptis(), and pysspa().
subroutine pymewt (MECOR, IFLCB, Q2, Z, PHIBR, WTME)
Definition at line 15983 of file pythia6425mod.f.
References k, n, pydat1, pyjets, v, and z.
Referenced by pyptis(), and pysspa().
subroutine pymign (MMUL)
Definition at line 20896 of file pythia6425mod.f.
References d, i, j, k, max, min, n, phi, HiStrng::pt(), pyalps(), pydat1, pydat3, pyerrm(), pyjets, pyklim(), pykmap(), pymass(), pypdfu(), pyr(), pyrobo(), pysigh(), pysspa(), pywidt(), tau, v, and x.
Referenced by pyevnt(), pyinit(), and pyrand().
subroutine pymihg (JCP1, JCG1, JCP2, JCG2)
Definition at line 23113 of file pythia6425mod.f.
References i, k, max, min, n, pyerrm(), pyjets, and v.
Referenced by pymihk().
subroutine pymihk ()
Definition at line 21878 of file pythia6425mod.f.
References four, i, j, k, max, min, n, ntry, pycomp, pycttr(), pydat1, pyedit(), pyerrm(), pyjets, pykfdi(), pylist(), pymass(), pymihg(), pyr(), pyrobo(), pyspli(), and v.
Referenced by pyevnt(), and pyevnw().
subroutine pymirm ()
Definition at line 23257 of file pythia6425mod.f.
References c, d, four, i, in, j, k, max, min, n, ntry, phi, HiStrng::pt(), pyangl(), pydat1, pyerrm(), pygive(), pyjets, pyr(), pyrobo(), pyzdis(), r1, r2, t1, v, sHelix::w(), and x.
Referenced by pyevnt(), and pyevnw().
function pymrun (KF, Q2)
Definition at line 74079 of file pythia6425mod.f.
References max, pyalps(), pydat1, and pymass().
Referenced by pyapps(), pygfxx(), pypole(), pyrghm(), pyrvch(), pyrvgw(), pyrvne(), pysfdc(), pysghg(), pystbh(), pysubh(), pytbbc(), pytbbn(), pythrg(), and pywidt().
subroutine pymsin ()
Definition at line 45447 of file pythia6425mod.f.
References d, dx, dy, i, init(), j, k1, min, pyapps(), pycjdc(), pycomp, pydat1, pydat3, pyglui(), pyhext(), pyhggm(), pyinom(), pynjdc(), pysfdc(), pyslha(), pystop(), pysugi(), pythrg(), pywidt(), r, and sign().
Referenced by pyinit().
subroutine pymult (MMUL)
Definition at line 19547 of file pythia6425mod.f.
References d, Conversion::dist(), i, j, k, max, min, n, phi, HiStrng::pt(), pycomp, pydat1, pyerrm(), pyjets, pyklim(), pykmap(), pyr(), pyshow(), pysigh(), tau, v, and x.
Referenced by pyevnt(), pyinit(), and pyrand().
subroutine pyname (KF, character CHAU)
Definition at line 74116 of file pythia6425mod.f.
References pycomp, and pydat1.
Referenced by pyinbm(), pylist(), pystat(), and pytabu().
subroutine pynjdc (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 52162 of file pythia6425mod.f.
References d, ei(), fid, i, j, pi, pyalem(), pyalps(), pycomp, pydat1, pygaus(), pylamf(), pyrvne(), pyx2xg(), pyx2xh(), pyxxga(), pyxxz6(), and sign().
Referenced by pymsin().
subroutine pynmes (KFDIQ)
Definition at line 69293 of file pythia6425mod.f.
References d, pydat1, pyerrm(), and pyr().
Referenced by pykfdi().
subroutine pynull (ID)
Definition at line 79863 of file pythia6425mod.f.
Referenced by pybook(), and pyhist().
subroutine pyofsh (MOFSH, KFMO, KFD1, KFD2, PMMO, RET1, RET2)
Definition at line 28077 of file pythia6425mod.f.
References d, f2(), i, max, min, pycomp, pydat1, pydat3, pyerrm(), and pyr().
Referenced by pymaxi(), pyrand(), pyresd(), and pywidt().
subroutine pyonia (KFL, ECM)
Definition at line 79312 of file pythia6425mod.f.
References k, max, n, ntry, phi, py1ent, py2ent(), py3ent(), pyalps(), pydat1, pyerrm(), pyexec(), pyjets, pylist(), pyprep(), pyr(), pyrobo(), pyshow(), v, x2, and x3.
Referenced by pytest().
subroutine pyonof (character, dimension(*) CHIN)
Definition at line 61344 of file pythia6425mod.f.
References pycomp, pydat1, pydat3, and pyerrm().
Referenced by pygive().
subroutine pyoper (ID1, character, dimension(*) OPER, ID2, ID3, F1, F2)
Definition at line 79581 of file pythia6425mod.f.
References d, f2(), max, min, and pyerrm().
function pyp (I, J)
Definition at line 76078 of file pythia6425mod.f.
References d, i, j, k, max, min, n, pyangl(), pychge(), pydat1, pyjets, pymass(), sign(), and v.
Referenced by dofistatescat(), doinstatescat(), dokinematics(), genevent(), getqvec(), hijhrd(), lustrf(), makebranch(), makeinsplit(), makestrings_minl(), pyboei(), pylist(), pystrf(), and pytest().
double precision function pypcmp (double precision XS, integer NPOW)
Definition at line 16655 of file pythia6425mod.f.
Referenced by pypdfu().
subroutine pypdel (KFA, X, Q2, dimension(-25:25) XPEL)
Definition at line 39806 of file pythia6425mod.f.
References d, max, min, pyalem(), pydat1, pygamm(), pyggam(), pypdga(), value, and x.
Referenced by pypdfu().
subroutine pypdfl (KF, X, Q2, dimension(-25:25) XPQ)
Definition at line 39563 of file pythia6425mod.f.
References max, pydat1, pypdfu(), and x.
Referenced by pyrand(), pysigh(), and pysspa().
subroutine pypdfu (KF, X, Q2, dimension(-25:25) XPQ)
Definition at line 38872 of file pythia6425mod.f.
References d, k, max, min, n, pydat1, pyerrm(), pyfcmp(), pygano(), pyggam(), pygvmd(), pyjets, pypcmp(), pypdel(), pypdga(), pypdpi(), pypdpr(), pyr(), v, value, x, and y.
Referenced by pymign(), pypdfl(), pyptis(), pyptmi(), pyrand(), pysigh(), and pysspa().
subroutine pypdga (X, Q2, dimension(-6:6) XPGA)
Definition at line 39989 of file pythia6425mod.f.
References d, max, min, pydat1, t, and x.
Referenced by pypdel(), and pypdfu().
subroutine pypdpi (X, Q2, dimension(-6:6) XPPI)
Definition at line 40797 of file pythia6425mod.f.
References d, max, min, pydat1, pygamm(), x, and y.
Referenced by pypdfu().
subroutine pypdpo (X, Q2, dimension(-6:6) XPPR)
Definition at line 42365 of file pythia6425mod.f.
References d, it, max, min, pydat1, pygamm(), t, x, and y.
Referenced by pypdpr().
subroutine pypdpr (X, Q2, dimension(-6:6) XPPR)
Definition at line 40969 of file pythia6425mod.f.
References d, i, max, min, pyct5l(), pyct5m(), pycteq(), pydat1, pygrvd(), pygrvl(), pygrvm(), pypdpo(), and x.
Referenced by pypdfu().
subroutine pypile (MPILE)
Definition at line 8520 of file pythia6425mod.f.
References d, i, max, min, pydat1, pyr(), and x.
Referenced by pyevnt(), pyevnw(), and pyinit().
subroutine pyplot (ID)
Definition at line 79707 of file pythia6425mod.f.
References d, dy, it, j, max, pydat1, pytime(), sign(), title, x, and ymax.
Referenced by pyhist().
subroutine pypole (IHIGGS, XMC, XMA, TANB, XMQ, XMUR, XMDR, XMT, AT, AB, XMU, XMH, XMHP, HM, HMP, AMP, SA, CA, STOP1, STOP2, SBOT1, SBOT2, TANBA, XMG, DT, DB)
Definition at line 49733 of file pythia6425mod.f.
References boost::array< T, N >::at(), d, deriv(), i, j, pi, prun(), pydat1, pyfint(), pymrun(), pyrghm(), pystop(), t, and v.
Referenced by pyhggm().
subroutine pyprep (IP)
Definition at line 64361 of file pythia6425mod.f.
References d, four, i, it, j, k, k1, max, min, n, HiMain1::np(), ntry, phi, pyangl(), pycomp, pycttr(), pydat1, pydat3, pydcyk(), pyerrm(), pyjets, pyjurf(), pykfdi(), pylist(), pymass(), pyr(), pyrobo(), t, and v.
Referenced by pyeevt(), pyevnt(), pyevnw(), pyexec(), pyonia(), and pyreco().
subroutine pyptdi (KFL, PX, PY)
Definition at line 69673 of file pythia6425mod.f.
References d, max, phi, HiStrng::pt(), pydat1, and pyr().
Referenced by pydcyk(), pydisg(), pyindf(), pyremn(), and pystrf().
subroutine pyptfs (MODE, PTMAX, PTMIN, PTGEN)
Definition at line 71390 of file pythia6425mod.f.
References d, ei(), i, j, k, max, min, n, npart(), phi, print(), pyangl(), pycomp, pycttr(), pydat1, pyerrm(), pygive(), pyjets, pyk(), pylist(), pymael(), pyr(), pyrobo(), sign(), v, x2, x3, and z.
Referenced by pyadsh(), pyevnt(), pyevnw(), pyresd(), and pyshow().
subroutine pyptis (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
Definition at line 14828 of file pythia6425mod.f.
References d, i, it, j, k, max, min, n, npart(), ntry, phi, print(), pyangl(), pycomp, pycttr(), pydat1, pyerrm(), pyfcmp(), pyjets, pymass(), pymemx(), pymewt(), pypdfu(), pyptmi(), pyr(), pyrobo(), v, Fun4AllFileOutStream::xb(), y, and z.
Referenced by pyevol().
subroutine pyptmi (MODE, PT2NOW, PT2CUT, PT2, IFAIL)
Definition at line 16051 of file pythia6425mod.f.
References d, i, j, k, max, min, n, npart(), ntry, phi, pycomp, pycttr(), pydat1, pydat3, pyerrm(), pyjets, pyklim(), pykmap(), pymass(), pypdfu(), pyr(), pyrobo(), pysigh(), pywidt(), tau, v, and x.
Referenced by pyevol(), and pyptis().
subroutine pyqqbh (WTQQBH)
Definition at line 43386 of file pythia6425mod.f.
References dx, i, j, k1, k2, max, HiStrng::pp(), HiStrng::pt(), pycomp, pydat1, x2, and x3.
Referenced by pysghg().
function pyr (IDUMMY)
Definition at line 74471 of file pythia6425mod.f.
References i, j, k, s, and t.
Referenced by dofistatescat(), doinstatescat(), dokinematics(), generatez(), genevent(), getdeltat(), getmass(), getnewmass(), getqvec(), getscatterer(), gett(), init(), makeinsplit(), makesplitting(), makestrings_minl(), mednextevt(), pickvtx(), poissonian(), py4ent(), py4frm(), py4jet(), py6frm(), pyboei(), pycell(), pydcyk(), pydecy(), pydiff(), pydisg(), pyeig4(), pyevnt(), pyevnw(), pyfscr(), pygaga(), pygram(), pyindf(), pyjoin(), pykfdi(), pykmap(), pymass(), pymign(), pymihk(), pymirm(), pymult(), pynmes(), pyofsh(), pyonia(), pypdfu(), pypile(), pyprep(), pyptdi(), pyptfs(), pyptis(), pyptmi(), pyradk(), pyrand(), pyreco(), pyremn(), pyresd(), pysave(), pyscat(), pysgex(), pyshow(), pysphe(), pyspli(), pysspa(), pystrf(), pytbdy(), pytest(), pythru(), pyx3jt(), pyx4jt(), pyxdif(), pyxjet(), pyxkfl(), pyxued(), and pyzdis().
subroutine pyradk (ECM, MK, PAK, THEK, PHIK, ALPK)
Definition at line 78450 of file pythia6425mod.f.
References d, max, min, pyangl(), pydat1, pymass(), and pyr().
Referenced by pyeevt().
subroutine pyrand ()
Definition at line 9196 of file pythia6425mod.f.
References d, i, max, min, ps(), pycomp, pydat1, pydat3, pyerrm(), pyevwt(), pygaga(), pykcut(), pyklim(), pykmap(), pylist(), pymass(), pymign(), pymult(), pyofsh(), pypdfl(), pypdfu(), pyr(), pysave(), pysigh(), pyspli(), pystop(), pyupre(), sign(), upevnt(), and x.
Referenced by pyevnt(), pyevnw(), and pyupev().
subroutine pyreco (IW1, IW2, NSD1, NAFT1)
Definition at line 28489 of file pythia6425mod.f.
References d, Poisson::fact(), four, i, iap, j, k, max, n, phi, pi, pydat1, pyjets, pyjoin(), pyprep(), pyr(), pyrobo(), pyshow(), r, sum(), t, v, v1, v2, x, Fun4AllFileOutStream::xb(), y, and z.
Referenced by py4frm(), and pyresd().
subroutine pyremn (IPU1, IPU2)
Definition at line 20217 of file pythia6425mod.f.
References d, i, j, k, max, min, n, ntry, phi, HiStrng::pt(), pyangl(), pycomp, pydat1, pyjets, pymass(), pyptdi(), pyr(), pyrobo(), pyspli(), pyzdis(), sign(), and v.
Referenced by pyevnt(), and pyevnw().
subroutine pyresd (IRES)
Definition at line 17211 of file pythia6425mod.f.
References c, d, ei(), i, j, k, max, min, n, HiMain1::n0(), HiMain1::np(), npart(), phi, ps(), py2ent(), py3ent(), py4ent(), pyangl(), pycomp, pydat1, pydat3, pyerrm(), pygram(), pyjets, pymass(), pyofsh(), pyptfs(), pyr(), pyreco(), pyrobo(), pyshow(), pytbdy(), pywidt(), pyx3jt(), pyx4jt(), pyxdif(), pyxjet(), sign(), v, x2, and x3.
Referenced by pyevnt(), pyevnw(), pyexec(), and pyupev().
subroutine pyrget (LFN, MOVE)
Definition at line 74551 of file pythia6425mod.f.
References min, and pyerrm().
subroutine pyrghm (MCHI, MA, TANB, MQ, MUR, MD, MTOP, AU, AD, MU, MHP, HMP, MCH, SA, CA, SAB, CAB, TANBA, MGLU, DELTAMT, DELTAMB)
Definition at line 50098 of file pythia6425mod.f.
References i, j, pi, pydat1, pygfxx(), pymrun(), and v.
Referenced by pypole().
function pyrnm3 (RGUT)
Definition at line 49124 of file pythia6425mod.f.
References c, f2(), max, min, pyalps(), r, x0, x2, and x3.
Referenced by pyinom().
function pyrnmq (ID, DTERM)
Definition at line 48357 of file pythia6425mod.f.
References c, ci, f2(), max, min, pi, pyalps(), r, x0, x2, and x3.
Referenced by pyapps().
subroutine pyrobo (IMI, IMA, THE, PHI, BEX, BEY, BEZ)
Definition at line 74635 of file pythia6425mod.f.
References d, i, j, k, min, n, phi, pydat1, pyerrm(), pyjets, and v.
Referenced by dokinematics(), genevent(), getqvec(), makebranch(), makeinsplit(), py4jet(), py6frm(), pyadsh(), pybesq(), pyboei(), pydecy(), pydiff(), pydisg(), pyedit(), pyeevt(), pyfram(), pygaga(), pyindf(), pyinki(), pymign(), pymihk(), pymirm(), pyonia(), pyprep(), pyptfs(), pyptis(), pyptmi(), pyreco(), pyremn(), pyresd(), pyscat(), pyshow(), pysspa(), pystrf(), pythru(), and pyupev().
subroutine pyrset (LFN, MOVE)
Definition at line 74592 of file pythia6425mod.f.
References max, min, and pyerrm().
subroutine pyrvch (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 58045 of file pythia6425mod.f.
References c2, d, false, i, j, pycomp, pydat1, pymrun(), pyrvgw(), rms(), and true.
Referenced by pycjdc().
double precision function pyrvg1 (double precision X)
Definition at line 59072 of file pythia6425mod.f.
References max, pyrvr(), and x.
Referenced by pyrvi1().
double precision function pyrvg2 (double precision X)
Definition at line 59105 of file pythia6425mod.f.
References max, pyrvs(), and x.
Referenced by pyrvi2().
double precision function pyrvg3 (double precision X)
Definition at line 59138 of file pythia6425mod.f.
References d, max, pygau2(), pyrvg4(), x, and ymax.
Referenced by pyrvi3().
double precision function pyrvg4 (double precision Y)
Definition at line 59176 of file pythia6425mod.f.
References pyrvs(), x, and y.
Referenced by pyrvg3().
subroutine pyrvgl (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 58522 of file pythia6425mod.f.
References d, false, i, pyalps(), pycomp, pydat1, pyrvgw(), rms(), and true.
Referenced by pyglui().
subroutine pyrvgw (KFIN, ID1, ID2, ID3, XLAM)
Definition at line 58792 of file pythia6425mod.f.
References d, false, i, j, n, pycomp, pymrun(), pyrvi1(), pyrvi2(), pyrvi3(), rms(), true, and xlim.
Referenced by pyrvch(), pyrvgl(), and pyrvne().
double precision function pyrvi1 (integer ID1, integer ID2, integer ID3)
Definition at line 58956 of file pythia6425mod.f.
References d, pygaus(), pyrvg1(), and rms().
Referenced by pyrvgw().
double precision function pyrvi2 (integer ID1, integer ID2, integer ID3)
Definition at line 58992 of file pythia6425mod.f.
References d, pygaus(), pyrvg2(), and rms().
Referenced by pyrvgw().
double precision function pyrvi3 (integer ID1, integer ID2, integer ID3)
Definition at line 59032 of file pythia6425mod.f.
References d, pygaus(), pyrvg3(), and rms().
Referenced by pyrvgw().
subroutine pyrvne (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 57778 of file pythia6425mod.f.
References c2, d, false, i, j, pycomp, pydat1, pymrun(), pyrvgw(), rms(), and true.
Referenced by pynjdc().
double precision function pyrvr (double precision Mab2, double precision RM, double precision RW)
Definition at line 59202 of file pythia6425mod.f.
Referenced by pyrvg1(), and pyrvs().
double precision function pyrvs (double precision X, double precision Y, double precision M1, double precision W1, double precision M2, double precision W2)
Definition at line 59215 of file pythia6425mod.f.
References pyrvr(), x, and y.
Referenced by pyrvg2(), and pyrvg4().
function pyrvsb (KFIN, ID1, ID2, RM2, MODE)
Definition at line 58751 of file pythia6425mod.f.
References i, max, n, pycomp, and pydat1.
Referenced by pyrvsf().
subroutine pyrvsf (KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, LKNT)
Definition at line 57474 of file pythia6425mod.f.
References i, j, k, pycomp, and pyrvsb().
Referenced by pysfdc().
subroutine pysave (ISAVE, IGA)
Definition at line 8609 of file pythia6425mod.f.
References i, j, and pyr().
Referenced by pydocu(), pyevnt(), pyevnw(), pyinit(), pyrand(), pystat(), and pyupev().
subroutine pyscat ()
Definition at line 10573 of file pythia6425mod.f.
References c2, d, i, in, j, k, max, min, n, npart(), phi, HiStrng::pt(), pyangl(), pychge(), pycomp, pydat1, pydat3, pyerrm(), pyjets, pymass(), pyr(), pyrobo(), pystop(), pywidt(), sign(), v, z, z1, and z2.
Referenced by pyevnt(), pyevnw(), and pyupev().
subroutine pysfdc (integer KFIN, double precision, dimension(0:400) XLAM, integer, dimension(400,3) IDLAM, integer IKNT)
Definition at line 50689 of file pythia6425mod.f.
References boost::array< T, N >::at(), d, ei(), i, j, pi, pyalem(), pyalps(), pycomp, pydat1, pylamf(), pymrun(), pyrvsf(), and sign().
Referenced by pymsin().
subroutine pysgex (NCHN, SIGS)
Definition at line 37978 of file pythia6425mod.f.
References ei(), Poisson::fact(), i, j, pycomp, pydat1, pydat3, pyr(), pywidt(), sign(), and x.
Referenced by pysigh().
subroutine pysghf (NCHN, SIGS)
Definition at line 31540 of file pythia6425mod.f.
References c2, i, j, pycomp, pydat1, pyhfth(), and x.
Referenced by pysigh().
subroutine pysghg (NCHN, SIGS)
Definition at line 34011 of file pythia6425mod.f.
References d, ei(), i, j, max, pydat1, pydat3, pyerrm(), pyi3au(), pymrun(), pyqqbh(), pystbh(), pystop(), pywaux(), pywidt(), sign(), and x.
Referenced by pysigh().
subroutine pysgqc (NCHN, SIGS)
Definition at line 30624 of file pythia6425mod.f.
References d, ei(), i, j, max, min, pyalps(), pycomp, pydat1, pydat3, pyi3au(), pywaux(), pywidt(), sign(), and x.
Referenced by pysigh().
subroutine pysgsu (NCHN, SIGS)
Definition at line 35388 of file pythia6425mod.f.
References d, ei(), i, j, pycomp, pydat1, pywidt(), sign(), and x.
Referenced by pysigh().
subroutine pysgtc (NCHN, SIGS)
Definition at line 36660 of file pythia6425mod.f.
References d, ei(), i, j, max, pyalps(), pybksb(), pycomp, pydat1, pydat3, pyhfth(), pyldcm(), pywidt(), sign(), and x.
Referenced by pysigh().
subroutine pysgwz (NCHN, SIGS)
Definition at line 33201 of file pythia6425mod.f.
References d, ei(), i, j, max, min, pyalps(), pydat1, pydat3, pywidt(), sign(), and x.
Referenced by pysigh().
subroutine pyshow (IP1, IP2, QMAX)
Definition at line 69825 of file pythia6425mod.f.
References d, ei(), i, j, k, max, min, n, npart(), phi, ps(), HiStrng::pt(), pyangl(), pycomp, pydat1, pyerrm(), pyjets, pymael(), pymass(), pyptfs(), pyr(), pyrobo(), sign(), v, x2, x3, and z.
Referenced by py2frm(), py4frm(), py4jet(), py6frm(), pyadsh(), pydisg(), pyeevt(), pyevnt(), pyexec(), pymult(), pyonia(), pyreco(), pyresd(), and pysspa().
subroutine pysigh (NCHN, SIGS)
Definition at line 29825 of file pythia6425mod.f.
References d, h1, h2, i, j, k, max, min, n, pyalem(), pyalps(), pycomp, pydat1, pydat3, pyjets, pymass(), pypdfl(), pypdfu(), pysgex(), pysghf(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pyxued(), tau, v, and x.
Referenced by pymaxi(), pymign(), pymult(), pyptmi(), and pyrand().
function pysimp (double precision, dimension(0:n) Y, double precision X0, double precision X1, N)
Definition at line 54617 of file pythia6425mod.f.
References i, n, s, x0, and y.
Referenced by pytbbc(), and pytbbn().
subroutine pyslha (MUPDA, KFORIG, IRETRN)
Definition at line 46165 of file pythia6425mod.f.
References ATrack::check(), d, boost::array< T, N >::end(), i, it, j, k, max, min, pychge(), pycomp, pydat1, pydat3, pyerrm(), pyfeyn(), pystop(), sign(), visaje(), hcalUtil::width(), and x.
Referenced by pymsin().
function pyspen (XREIN, XIMIN, IREIM)
Definition at line 43289 of file pythia6425mod.f.
References d, i, max, pydat1, and sign().
Referenced by pyi3au().
subroutine pysphe (SPH, APL)
Definition at line 76161 of file pythia6425mod.f.
References d, i, j, k, max, min, n, HiMain1::np(), ps(), pychge(), pycomp, pydat1, pyerrm(), pyjets, pyr(), and v.
subroutine pyspli (KF, KFLIN, KFLCH, KFLSP)
Definition at line 42905 of file pythia6425mod.f.
References j, ntry, pydat1, pyerrm(), pykfdi(), and pyr().
Referenced by pydiff(), pydisg(), pymihk(), pyrand(), and pyremn().
subroutine pysspa (IPU1, IPU2)
Definition at line 13911 of file pythia6425mod.f.
References d, i, it, j, k, max, min, n, npart(), ntry, ps(), pyalps(), pyangl(), pycomp, pydat1, pyerrm(), pyjets, pymass(), pymemx(), pymewt(), pypdfl(), pypdfu(), pyr(), pyrobo(), pyshow(), v, Fun4AllFileOutStream::xb(), and z.
Referenced by pyevnt(), and pymign().
subroutine pystat (MSTAT)
Definition at line 4046 of file pythia6425mod.f.
References d, i, j, max, pycomp, pydat1, pydat3, pyname(), pysave(), pywidt(), and x.
Referenced by pytest().
subroutine pystbh (WTTBH)
Definition at line 43794 of file pythia6425mod.f.
References alphas(), i, max, HiStrng::pp(), HiStrng::pt(), pydat1, pymrun(), pytbhg(), pytbhq(), v, and x.
Referenced by pysghg().
subroutine pystop (MCOD)
Definition at line 80038 of file pythia6425mod.f.
References pydat1, PHTimer::stop(), and x.
Referenced by fhhiggscorr(), fhsetflags(), fhsetpara(), pyapps(), pyckbd(), pyerrm(), pyevnt(), pyevnw(), pyfscr(), pygram(), pyinbm(), pyinit(), pyinom(), pyinre(), pykcut(), pylogo(), pymaxi(), pymsin(), pypole(), pyrand(), pyscat(), pysghg(), pyslha(), pysugi(), pytaud(), pytest(), pythrg(), pyuedc(), ssmssm(), sugra(), upinit(), and visaje().
subroutine pystrf (IP)
Definition at line 65821 of file pythia6425mod.f.
References d, fd, four, i, in, it, j, k, line, max, min, n, HiMain1::np(), ntry, HijJet4::pdr(), pycomp, pydat1, pyerrm(), pyjets, pyjurf(), pykfdi(), pymass(), pyp(), pyptdi(), pyr(), pyrobo(), pyzdis(), sign(), v, and z.
Referenced by pyexec().
subroutine pysubh (double precision XMA, double precision TANB, double precision XMQ, double precision XMUR, double precision XMTOP, double precision AU, double precision AD, double precision XMU, double precision XMH, double precision XHM, double precision XMHCH, double precision SA, double precision CA, double precision TANBA)
Definition at line 49498 of file pythia6425mod.f.
References pi, pyalem(), pyalps(), pydat1, pymrun(), t, and v.
Referenced by pyhggm().
subroutine pysugi ()
Definition at line 47720 of file pythia6425mod.f.
References i, in, j, k1, k2, max, pycomp, pydat1, pyerrm(), pyfeyn(), pystop(), ssmssm(), sugra(), v, visaje(), and x.
Referenced by pymsin().
subroutine pytabu (MTABU)
Definition at line 77376 of file pythia6425mod.f.
References d, i, j, k, max, min, n, HiMain1::np(), phi, pyangl(), pychge(), pycomp, pydat1, pydat3, pyerrm(), pyjets, pymass(), pyname(), sign(), v, and x.
Referenced by pytest().
subroutine pytaud (ITAU, IORIG, KFORIG, NDECAY)
Definition at line 80817 of file pythia6425mod.f.
References k, n, pydat1, pyjets, pystop(), v, and x.
Referenced by pydecy().
subroutine pytbbc (integer I, integer NN, double precision XMGLU, double precision GAM)
Definition at line 51923 of file pythia6425mod.f.
References alphas(), false, i, j, pyalem(), pyalps(), pycomp, pydat1, pylamf(), pymrun(), pysimp(), true, and sHelix::w().
Referenced by pyglui().
subroutine pytbbn (I, integer NN, double precision E, double precision XMGLU, double precision GAM)
Definition at line 51701 of file pythia6425mod.f.
References alphas(), b1, false, g, i, j, pyalem(), pyalps(), pycomp, pydat1, pylamf(), pymrun(), pysimp(), true, and sHelix::w().
Referenced by pyglui().
subroutine pytbdy (IDIN)
Definition at line 54664 of file pythia6425mod.f.
References c, d, ei(), f2(), i, k, max, n, print(), pycomp, pydat1, pyjets, pyr(), r, sign(), v, x0, x2, and x3.
Referenced by pyresd().
subroutine pytbhb (double precision MT, double precision MB, double precision MHP, BR, GAMT)
Definition at line 43880 of file pythia6425mod.f.
References alphas(), v, and Fun4AllFileOutStream::xb().
Referenced by pytbhg(), and pytbhq().
subroutine pytbhg (dimension(4) Q1, dimension(4) Q2, dimension(4) P1, dimension(4) P2, dimension(4) P3, double precision MT, double precision MB, RMB, double precision MHP, AMP2)
Definition at line 43928 of file pythia6425mod.f.
References alphas(), Poisson::fact(), pi, ps(), pydat1, pytbhb(), pytbhs(), s, and v.
Referenced by pystbh().
subroutine pytbhq (dimension(4) Q1, dimension(4) Q2, dimension(4) P1, dimension(4) P2, dimension(4) P3, double precision MT, double precision MB, RMB, double precision MHP, AMP2)
Definition at line 45263 of file pythia6425mod.f.
References alphas(), Poisson::fact(), pi, ps(), pydat1, pytbhb(), pytbhs(), s, and v.
Referenced by pystbh().
DOUBLE PRECISION function pytbhs (dimension(4) A, dimension(4) B)
Definition at line 45427 of file pythia6425mod.f.
Referenced by pytbhg(), and pytbhq().
subroutine pytecm (SMIN, SMOU, WIDO, IOPT)
Definition at line 55071 of file pythia6425mod.f.
References boost::array< T, N >::at(), i, j, min, pyalem(), pycomp, pydat1, pyeicg(), pywidt(), r1, r2, and s1.
Referenced by pymaxi().
subroutine pytest (MTEST)
Definition at line 2270 of file pythia6425mod.f.
References d, i, j, k, max, min, n, phi, py1ent, py2ent(), py3ent(), py4ent(), pycomp, pydat1, pydat3, pyeevt(), pyevnt(), pyexec(), pyinit(), pyjets, pylist(), pymass(), pyonia(), pyp(), pyr(), pystat(), pystop(), pytabu(), sign(), v, and x.
DOUBLE PRECISION function pythag (double precision A, double precision B)
Definition at line 56790 of file pythia6425mod.f.
References r, s, t, and sHelix::u().
Referenced by pycmq2(), pycmqr(), pycrth(), and pycsrt().
subroutine pythrg ()
Definition at line 48444 of file pythia6425mod.f.
References d, i, if(), it, j, max, pycomp, pydat1, pyerrm(), pymrun(), pystop(), sign(), and true.
Referenced by pymsin().
subroutine pythru (THR, OBL)
Definition at line 76315 of file pythia6425mod.f.
References d, i, j, k, min, n, HiMain1::np(), phi, ps(), pyangl(), pychge(), pycomp, pydat1, pyerrm(), pyjets, pyr(), pyrobo(), sign(), and v.
Referenced by pyfscr().
subroutine pytime (integer, dimension(6) IDATI)
Definition at line 80851 of file pythia6425mod.f.
References j.
Referenced by pylogo(), and pyplot().
subroutine pytune (ITUNE)
Definition at line 61520 of file pythia6425mod.f.
References i, pydat1, pyerrm(), and x.
subroutine pyuedc ()
Definition at line 55286 of file pythia6425mod.f.
References c, d, i, pi, pyalps(), pydat1, pydat3, pystop(), and pywidt().
Referenced by pyxdin().
subroutine pyupda (MUPDA, LFN)
Definition at line 75580 of file pythia6425mod.f.
References boost::array< T, N >::end(), i, j, max, min, pychge(), pycomp, pydat1, pydat3, pyerrm(), pylist(), and x.
subroutine pyupev ()
Definition at line 4759 of file pythia6425mod.f.
References i, j, k, n, pycomp, pydat1, pydat3, pydiff(), pydisg(), pydocu(), pyfram(), pygaga(), pyinki(), pyjets, pyrand(), pyresd(), pyrobo(), pysave(), pyscat(), pyxtot(), PHTimer::stop(), v, and x.
subroutine pyupin ()
Definition at line 5027 of file pythia6425mod.f.
References k, max, n, pyjets, and v.
subroutine pyupre ()
Definition at line 16693 of file pythia6425mod.f.
References i, j, and pyerrm().
Referenced by pyrand().
subroutine pyveto (IVETO)
Definition at line 17048 of file pythia6425mod.f.
References i, k, max, n, pydat1, pyjets, upveto(), and v.
Referenced by pyevnt(), and pyevnw().
subroutine pywaux (IAUX, EPS, WRE, WIM)
Definition at line 43142 of file pythia6425mod.f.
References pydat1, and x.
Referenced by pysghg(), and pysgqc().
DOUBLE PRECISION function pywdkk (X)
Definition at line 56001 of file pythia6425mod.f.
References i, n, pi, pydat1, and x.
Referenced by pygraw().
subroutine pywidt (KFLR, SH, dimension(0:400) WDTP, dimension(0:400,0:5) WDTE)
Definition at line 25063 of file pythia6425mod.f.
References ATrack::check(), d, ei(), i, j, max, min, pyalem(), pyalps(), pycomp, pydat1, pydat3, pyhfth(), pymrun(), pyofsh(), pywidx(), root, sign(), t1, x, and y.
Referenced by pyinre(), pymign(), pymsin(), pyptmi(), pyresd(), pyscat(), pysgex(), pysghg(), pysgqc(), pysgsu(), pysgtc(), pysgwz(), pystat(), pytecm(), and pyuedc().
subroutine pywidx (KFLR, SH, dimension(0:400) WDTP, dimension(0:400,0:5) WDTE)
Definition at line 57335 of file pythia6425mod.f.
References i, max, pyalem(), pyalps(), pycomp, pydat1, pydat3, pyhfth(), and sign().
Referenced by pywidt().
double precision function pyx2xg (double precision C1, double precision XM1, double precision XM2, double precision XM3, double precision GX2, double precision GLR)
Definition at line 53922 of file pythia6425mod.f.
References pylamf().
Referenced by pycjdc(), and pynjdc().
double precision function pyx2xh (double precision C1, double precision XM1, double precision XM2, double precision XM3, GX2, GLR)
Definition at line 53951 of file pythia6425mod.f.
References pylamf().
Referenced by pycjdc(), and pynjdc().
subroutine pyx3jt (NJET, CUT, KFL, ECM, X1, X2)
Definition at line 78781 of file pythia6425mod.f.
References max, min, pydat1, pymass(), pyr(), sign(), x, x2, and x3.
Referenced by pyeevt(), and pyresd().
subroutine pyx4jt (NJET, CUT, KFL, ECM, KFLN, X1, X2, X4, X12, X14)
Definition at line 78948 of file pythia6425mod.f.
References it, max, min, pydat1, pymass(), pyr(), and x2.
Referenced by pyeevt(), and pyresd().
subroutine pyxdif (NC, NJET, KFL, ECM, CHI, THE, PHI)
Definition at line 79172 of file pythia6425mod.f.
References k, max, n, phi, pydat1, pyjets, pymass(), pyr(), sign(), v, x2, and x3.
Referenced by pyeevt(), and pyresd().
subroutine pyxdin ()
Definition at line 55198 of file pythia6425mod.f.
References pydat1, pydat3, pygive(), pygram(), and pyuedc().
Referenced by pyinit().
subroutine pyxjet (ECM, NJET, CUT)
Definition at line 78601 of file pythia6425mod.f.
References max, min, pyalps(), pydat1, pyerrm(), and pyr().
Referenced by pyeevt(), and pyresd().
subroutine pyxkfl (KFL, ECM, ECMC, KFLC)
Definition at line 78527 of file pythia6425mod.f.
References max, min, ntry, pydat1, pyerrm(), pymass(), pyr(), and sign().
Referenced by pyeevt().
subroutine pyxtee (KFL, ECM, XTOT)
Definition at line 78287 of file pythia6425mod.f.
References max, min, pyalps(), pydat1, pymass(), and sign().
Referenced by pyeevt().
subroutine pyxtot ()
Definition at line 6931 of file pythia6425mod.f.
References d, i, j, max, pydat1, pyerrm(), and s.
Referenced by pyevnt(), pyevnw(), pygaga(), pyinit(), and pyupev().
subroutine pyxued (integer NCHN, double precision SIGS)
Definition at line 55531 of file pythia6425mod.f.
References alphas(), i, j, pi, pyalps(), pyr(), and x.
Referenced by pysigh().
double precision function pyxxga (double precision C0, double precision XM1, double precision XM2, double precision XMTR, double precision XMTL)
Definition at line 53898 of file pythia6425mod.f.
References f2().
Referenced by pynjdc().
double precision function pyxxz6 (double precision X)
Definition at line 53759 of file pythia6425mod.f.
References c, i, pydat1, s, x, and y.
Referenced by pycjdc(), pyglui(), and pynjdc().
subroutine pyzdis (KFL1, KFL2, PR, Z)
Definition at line 69701 of file pythia6425mod.f.
References fc, max, min, pydat1, pyr(), and z.
Referenced by pydcyk(), pydisg(), pyindf(), pymirm(), pyremn(), and pystrf().
subroutine ssmssm (real RDUM1, real RDUM2, real RDUM3, real RDUM4, real RDUM5, real RDUM6, real RDUM7, real RDUM8, real RDUM9, real RDUM10, real RDUM11, real RDUM12, real RDUM13, real RDUM14, real RDUM15, real RDUM16, real RDUM17, real RDUM18, real RDUM19, real RDUM20, real RDUM21, real RDUM22, real RDUM23, real RDUM24, real RDUM25, IDUM1, IDUM2)
Definition at line 80677 of file pythia6425mod.f.
References pydat1, pystop(), and x.
Referenced by pysugi().
subroutine sugra (real MZERO, real MHLF, real AZERO, real TANB, real SGNMU, real MTOP, integer IMODL)
Definition at line 80622 of file pythia6425mod.f.
References pydat1, pystop(), and x.
Referenced by pysugi().
subroutine upevnt ()
Definition at line 80348 of file pythia6425mod.f.
References boost::array< T, N >::end(), i, and j.
Referenced by pyrand().
subroutine upinit ()
Definition at line 80228 of file pythia6425mod.f.
References boost::array< T, N >::end(), and pystop().
Referenced by pyinit().
subroutine upveto (IVETO)
Definition at line 80479 of file pythia6425mod.f.
References pylist().
Referenced by pyveto().
character*40 function visaje ()
Definition at line 80648 of file pythia6425mod.f.
References pydat1, pystop(), and x.
Referenced by pyslha(), and pysugi().