Analysis Software: analysis/blob/master/PhotonConversion/ana/photonEff.C File Reference
photonEff.C File Reference
#include <iostream>
#include <fstream>
#include "TFile.h"
#include "Scalar.h"
#include "TTree.h"
#include "TChain.h"
#include "TLegend.h"
#include "math.h"
#include "TH1.h"
#include "TH2.h"
#include "TEfficiency.h"
#include "TLine.h"
#include "TGraphAsymmErrors.h"
Functions
TChain * handleFile (string name, string extension, string treename, unsigned int filecount)
void makephotonM (TChain *ttree, TChain *back, TFile *out_file)
void makeVtxR (TChain *ttree, TTree *vtxTree, TFile *out_file)
void makeVtxRes (TChain *ttree, TFile *out_file)
void makeVtxEff (TChain *ttree, TFile *out_file)
void makepTRes (TChain *ttree)
TEfficiency * makepTDist (TChain *ttree, TTree *allTree, TFile *out_file)
void compareDeta (TTree *signalTree, TTree *background)
void testCuts (TChain *ttree, TFile *out_file)
void makeRefitDist (TChain *ttree, TFile *out_file)
void makepTCaloGraph (string filename, TFile *outfile)
TH1F * makePythiaSpec (TChain *ttree, TFile *out_file, string type="")
TH1F removeFirstBin (TH1F h)
double ADtoP (double ad)
float smartChi2 (TH1F hard, TH1F soft)
void chopHard (TH1F hard, TH1F soft)
void calculateConversionRate (TEfficiency *rate, TH1F *pythia, TFile *out_file)
double hardWeightFactor (TH1F *hard, TH1F *soft, unsigned matchBin, double *error)
TH1F * addSpec (TH1F *soft, TH1F *hard, TFile *file)
void photonEff ()
Function Documentation
TH1F* addSpec (TH1F * soft, TH1F * hard, TFile * file)
Definition at line 463 of file photonEff.C.
References hardWeightFactor(), and i.
Referenced by photonEff().
double ADtoP (double ad)
Definition at line 414 of file photonEff.C.
References r.
Referenced by chopHard().
void calculateConversionRate (TEfficiency * rate, TH1F * pythia, TFile * out_file)
Definition at line 444 of file photonEff.C.
void chopHard (TH1F hard, TH1F soft)
Definition at line 431 of file photonEff.C.
References ADtoP(), bins, removeFirstBin(), and smartChi2().
void compareDeta (TTree * signalTree, TTree * background)
Definition at line 227 of file photonEff.C.
References i.
Referenced by photonEff2().
TChain* handleFile (string name, string extension, string treename, unsigned int filecount)
Definition at line 21 of file photonEff.C.
References i, and s.
double hardWeightFactor (TH1F * hard, TH1F * soft, unsigned matchBin, double * error)
Definition at line 453 of file photonEff.C.
References r.
Referenced by addSpec().
void makephotonM (TChain * ttree, TChain * back, TFile * out_file)
Definition at line 35 of file photonEff.C.
References i.
Referenced by photonEff2().
void makepTCaloGraph (string filename, TFile * outfile)
Definition at line 349 of file photonEff.C.
References s, x, and y.
Referenced by photonEff2().
TEfficiency* makepTDist (TChain * ttree, TTree * allTree, TFile * out_file)
Definition at line 182 of file photonEff.C.
References i.
void makepTRes (TChain * ttree)
Definition at line 165 of file photonEff.C.
TH1F* makePythiaSpec (TChain * ttree, TFile * out_file, string type = "")
Definition at line 373 of file photonEff.C.
References i, and title.
Referenced by photonEff().
void makeRefitDist (TChain * ttree, TFile * out_file)
Definition at line 318 of file photonEff.C.
void makeVtxEff (TChain * ttree, TFile * out_file)
Definition at line 140 of file photonEff.C.
References r.
Referenced by photonEff2().
void makeVtxR (TChain * ttree, TTree * vtxTree, TFile * out_file)
Definition at line 77 of file photonEff.C.
References i.
void makeVtxRes (TChain * ttree, TFile * out_file)
Definition at line 118 of file photonEff.C.
References r.
Referenced by photonEff2().
void photonEff ()
Definition at line 482 of file photonEff.C.
References addSpec(), and makePythiaSpec().
TH1F removeFirstBin (TH1F h)
Definition at line 397 of file photonEff.C.
References SVM_v1::h, i, and r.
Referenced by chopHard().
float smartChi2 (TH1F hard, TH1F soft)
Definition at line 425 of file photonEff.C.
Referenced by chopHard().
void testCuts (TChain * ttree, TFile * out_file)
Definition at line 252 of file photonEff.C.