Analysis Software: EventInfoSummary Class Reference
EventInfoSummary Class Reference
#include <prototype/blob/master/offline/packages/Prototype3/EventInfoSummary.h>
Classes
class channel_info
Public Member Functions
EventInfoSummary ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const std::string &name, const int packet_id, const unsigned int offset, const double calibration_const=+1)
add stuff to be unpacked
EventInfoSummary ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const std::string &name, const int packet_id, const unsigned int offset, const double calibration_const=+1)
add stuff to be unpacked
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
typedef std::map< std::string,
channel_info > typ_channel_map
list of channel name -> channel info
typedef std::map< std::string,
channel_info > typ_channel_map
list of channel name -> channel info
Private Attributes
typ_channel_map channel_map
std::string eventinfo_node_name
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file EventInfoSummary.h.
Member Typedef Documentation
typedef std::map<std::string, channel_info> EventInfoSummary::typ_channel_map private
list of channel name -> channel info
Definition at line 50 of file EventInfoSummary.h.
typedef std::map<std::string, channel_info> EventInfoSummary::typ_channel_map private
list of channel name -> channel info
Definition at line 50 of file EventInfoSummary.h.
Constructor & Destructor Documentation
EventInfoSummary::EventInfoSummary ()
Definition at line 40 of file EventInfoSummary.cc.
EventInfoSummary::EventInfoSummary ()
Member Function Documentation
void EventInfoSummary::add_channel (const std::string & name, const int packet_id, const unsigned int offset, const double calibration_const = +1)
add stuff to be unpacked
Parameters
packet_id name of the channel
offset packet id
calibration_const offset in packet data conversion constant from integer to meaningful value
Definition at line 278 of file EventInfoSummary.cc.
References channel_map.
void EventInfoSummary::add_channel (const std::string & name, const int packet_id, const unsigned int offset, const double calibration_const = +1)
add stuff to be unpacked
Parameters
packet_id name of the channel
offset packet id
calibration_const offset in packet data conversion constant from integer to meaningful value
void EventInfoSummary::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 253 of file EventInfoSummary.cc.
References PHCompositeNode::addNode(), eventinfo_node_name, and PHNodeIterator::findFirst().
Referenced by InitRun().
void EventInfoSummary::CreateNodeTree (PHCompositeNode * topNode)
int EventInfoSummary::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int EventInfoSummary::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 47 of file EventInfoSummary.cc.
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
int EventInfoSummary::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int EventInfoSummary::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 54 of file EventInfoSummary.cc.
References assert, EventInfoSummary::channel_info::calibration_const, channel_map, col, DATAEVENT, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, eventinfo_node_name, RawTower::get_bineta(), RawTower::get_binphi(), RawTower::get_energy(), RawTower_Prototype3::get_signal_samples(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), i, it, Packet::iValue(), name, RawTower_Prototype3::NSAMPLES, EventInfoSummary::channel_info::offset, EventInfoSummary::channel_info::packet_id, PHParameters::Print(), PHParameters::SaveToNodeTree(), PHParameters::set_double_param(), PHParameters::set_int_param(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Member Data Documentation
typ_channel_map EventInfoSummary::channel_map private
Definition at line 52 of file EventInfoSummary.h.
Referenced by add_channel(), and process_event().
std::string EventInfoSummary::eventinfo_node_name private
Definition at line 54 of file EventInfoSummary.h.
Referenced by CreateNodeTree(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype3/EventInfoSummary.h
prototype/blob/master/offline/packages/Prototype4/EventInfoSummary.h
prototype/blob/master/offline/packages/Prototype3/EventInfoSummary.cc
prototype/blob/master/offline/packages/Prototype4/EventInfoSummary.cc