Analysis Software: PHNodeDump Class Reference
PHNodeDump Class Reference
#include <coresoftware/blob/master/offline/packages/NodeDump/PHNodeDump.h>
Public Member Functions
PHNodeDump ()
virtual ~PHNodeDump ()
int CloseOutputFiles ()
int GetGlobalVars (PHCompositeNode *topNode)
int RunNumber ()
int EvtSequence ()
int AddIgnore (const std::string &name)
int Select (const std::string &name)
int SetOutDir (const std::string &dirname)
void SetPrecision (const int digits)
Public Member Functions inherited from PHNodeOperation
PHNodeOperation ()
virtual ~PHNodeOperation ()
void operator() (PHNode &o)
void operator() (PHNode *o)
virtual void Verbosity (const int i)
virtual int Verbosity () const
Protected Member Functions
virtual void perform (PHNode *)
int AddDumpObject (const std::string &NodeName, PHNode *node)
Protected Attributes
std::map< std::string,
DumpObject * > dumpthis
std::set< std::string > ignore
std::set< std::string > exclusive
int runnumber
int evtsequence
int fp_precision
std::string outdir
Protected Attributes inherited from PHNodeOperation
int verbosity
Detailed Description
Definition at line 14 of file PHNodeDump.h.
Constructor & Destructor Documentation
PHNodeDump::PHNodeDump ()
Definition at line 49 of file PHNodeDump.cc.
PHNodeDump::~PHNodeDump () virtual
Definition at line 57 of file PHNodeDump.cc.
References dumpthis, exclusive, and ignore.
Member Function Documentation
int PHNodeDump::AddDumpObject (const std::string & NodeName, PHNode * node) protected
Definition at line 145 of file PHNodeDump.cc.
References dumpthis, exclusive, fp_precision, PHNode::getType(), ignore, DumpObject::Init(), DumpObject::NoOutput(), outdir, DumpObject::SetOutDir(), DumpObject::SetParentNodeDump(), and DumpObject::SetPrecision().
Referenced by perform().
int PHNodeDump::AddIgnore (const std::string & name)
Definition at line 69 of file PHNodeDump.cc.
References ignore, and PHWHERE.
Referenced by Dumper::AddIgnore().
int PHNodeDump::CloseOutputFiles ()
Definition at line 135 of file PHNodeDump.cc.
References dumpthis.
Referenced by Dumper::End().
int PHNodeDump::EvtSequence () inline
Definition at line 23 of file PHNodeDump.h.
References evtsequence.
Referenced by DumpObject::process_event().
int PHNodeDump::GetGlobalVars (PHCompositeNode * topNode)
Definition at line 93 of file PHNodeDump.cc.
References RunHeader::get_RunNumber(), and runnumber.
Referenced by Dumper::process_event().
void PHNodeDump::perform (PHNode * node) protected virtual
Implements PHNodeOperation.
Definition at line 103 of file PHNodeDump.cc.
References AddDumpObject(), dumpthis, PHNode::getName(), and PHNode::getType().
int PHNodeDump::RunNumber () inline
Definition at line 22 of file PHNodeDump.h.
References runnumber.
Referenced by DumpObject::process_event().
int PHNodeDump::Select (const std::string & name)
Definition at line 81 of file PHNodeDump.cc.
References exclusive, and PHWHERE.
Referenced by Dumper::Select().
int PHNodeDump::SetOutDir (const std::string & dirname)
Definition at line 310 of file PHNodeDump.cc.
References outdir.
Referenced by Dumper::SetOutDir().
void PHNodeDump::SetPrecision (const int digits) inline
Definition at line 28 of file PHNodeDump.h.
References digits, and fp_precision.
Referenced by Dumper::SetPrecision().
Member Data Documentation
std::map<std::string, DumpObject *> PHNodeDump::dumpthis protected
Definition at line 33 of file PHNodeDump.h.
Referenced by AddDumpObject(), CloseOutputFiles(), perform(), and ~PHNodeDump().
int PHNodeDump::evtsequence protected
Definition at line 37 of file PHNodeDump.h.
Referenced by EvtSequence().
std::set<std::string> PHNodeDump::exclusive protected
Definition at line 35 of file PHNodeDump.h.
Referenced by AddDumpObject(), Select(), and ~PHNodeDump().
int PHNodeDump::fp_precision protected
Definition at line 38 of file PHNodeDump.h.
Referenced by AddDumpObject(), and SetPrecision().
std::set<std::string> PHNodeDump::ignore protected
Definition at line 34 of file PHNodeDump.h.
Referenced by AddDumpObject(), AddIgnore(), and ~PHNodeDump().
std::string PHNodeDump::outdir protected
Definition at line 39 of file PHNodeDump.h.
Referenced by AddDumpObject(), and SetOutDir().
int PHNodeDump::runnumber protected
Definition at line 36 of file PHNodeDump.h.
Referenced by GetGlobalVars(), and RunNumber().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/NodeDump/PHNodeDump.h
coresoftware/blob/master/offline/packages/NodeDump/PHNodeDump.cc