Analysis Software: SvtxClusterMap_v1 Class Reference
SvtxClusterMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxClusterMap_v1.h>
Public Member Functions
SvtxClusterMap_v1 ()
SvtxClusterMap_v1 (const SvtxClusterMap_v1 &clustermap)
SvtxClusterMap_v1 & operator= (const SvtxClusterMap_v1 &clustermap)
virtual ~SvtxClusterMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const SvtxCluster * get (unsigned int idkey) const
SvtxCluster * get (unsigned int idkey)
SvtxCluster * insert (const SvtxCluster *cluster)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SvtxClusterMap
virtual ~SvtxClusterMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (SvtxClusterMap_v1, 1)
Private Attributes
ClusterMap _map
Additional Inherited Members
Public Types inherited from SvtxClusterMap
typedef std::map< unsigned int,
SvtxCluster * > ClusterMap
typedef std::map< unsigned int,
SvtxCluster * >
::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxCluster * >::iterator Iter
Protected Member Functions inherited from SvtxClusterMap
SvtxClusterMap ()
Detailed Description
Definition at line 10 of file SvtxClusterMap_v1.h.
Constructor & Destructor Documentation
SvtxClusterMap_v1::SvtxClusterMap_v1 ()
Definition at line 14 of file SvtxClusterMap_v1.cc.
Referenced by CloneMe().
SvtxClusterMap_v1::SvtxClusterMap_v1 (const SvtxClusterMap_v1 & clustermap)
Definition at line 19 of file SvtxClusterMap_v1.cc.
References _map, assert, begin(), end(), and SvtxCluster::get_id().
SvtxClusterMap_v1::~SvtxClusterMap_v1 () virtual
Definition at line 46 of file SvtxClusterMap_v1.cc.
References Reset().
Member Function Documentation
ConstIter SvtxClusterMap_v1::begin () const inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 37 of file SvtxClusterMap_v1.h.
References _map.
Referenced by operator=(), and SvtxClusterMap_v1().
Iter SvtxClusterMap_v1::begin () inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 41 of file SvtxClusterMap_v1.h.
References _map.
SvtxClusterMap_v1::ClassDef (SvtxClusterMap_v1 , 1) private
void SvtxClusterMap_v1::clear () inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 26 of file SvtxClusterMap_v1.h.
References Reset().
PHObject* SvtxClusterMap_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxClusterMap.
Definition at line 21 of file SvtxClusterMap_v1.h.
References SvtxClusterMap_v1().
size_t SvtxClusterMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 25 of file SvtxClusterMap_v1.h.
References _map.
bool SvtxClusterMap_v1::empty () const inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 23 of file SvtxClusterMap_v1.h.
References _map.
ConstIter SvtxClusterMap_v1::end () const inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 39 of file SvtxClusterMap_v1.h.
References _map.
Referenced by operator=(), and SvtxClusterMap_v1().
Iter SvtxClusterMap_v1::end () inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 43 of file SvtxClusterMap_v1.h.
References _map.
size_t SvtxClusterMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 31 of file SvtxClusterMap_v1.h.
References _map.
ConstIter SvtxClusterMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 38 of file SvtxClusterMap_v1.h.
References _map.
Iter SvtxClusterMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 42 of file SvtxClusterMap_v1.h.
References _map.
const SvtxCluster * SvtxClusterMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SvtxClusterMap.
Definition at line 69 of file SvtxClusterMap_v1.cc.
References _map.
SvtxCluster * SvtxClusterMap_v1::get (unsigned int idkey) virtual
Reimplemented from SvtxClusterMap.
Definition at line 76 of file SvtxClusterMap_v1.cc.
References _map.
void SvtxClusterMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxClusterMap.
Definition at line 63 of file SvtxClusterMap_v1.cc.
References _map.
SvtxCluster * SvtxClusterMap_v1::insert (const SvtxCluster * cluster) virtual
Reimplemented from SvtxClusterMap.
Definition at line 83 of file SvtxClusterMap_v1.cc.
References _map, SvtxCluster::CloneMe(), and index.
int SvtxClusterMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxClusterMap.
Definition at line 20 of file SvtxClusterMap_v1.h.
SvtxClusterMap_v1 & SvtxClusterMap_v1::operator= (const SvtxClusterMap_v1 & clustermap)
Definition at line 32 of file SvtxClusterMap_v1.cc.
References _map, assert, begin(), end(), SvtxCluster::get_id(), and Reset().
void SvtxClusterMap_v1::Reset () virtual
Clear Event.
Reimplemented from SvtxClusterMap.
Definition at line 51 of file SvtxClusterMap_v1.cc.
References _map.
Referenced by clear(), operator=(), and ~SvtxClusterMap_v1().
size_t SvtxClusterMap_v1::size (void) const inline virtual
Reimplemented from SvtxClusterMap.
Definition at line 24 of file SvtxClusterMap_v1.h.
References _map.
Member Data Documentation
ClusterMap SvtxClusterMap_v1::_map private
Definition at line 46 of file SvtxClusterMap_v1.h.
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and SvtxClusterMap_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxClusterMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxClusterMap_v1.cc