Analysis Software: analysis/blob/master/TPC/TrackingPerformance/plot.C File Reference
plot.C File Reference
Functions
void NormByBinWidth (TH1F *inh)
TH1F * getHist (TString nom, TFile *fi, const char *na, int co, int mk=20, float mks=1)
TH2F * getHist2 (TString nom, TFile *fi, const char *na)
TCanvas * MakeEfficiency (TFile *fa, TString ti, float c0=0.01250, float c1=0.001858, bool plotOld=false)
TCanvas * MakeEfficiencyFast (TFile *fa, TString ti, TString hw, bool plotOld=false)
TCanvas * MakePtResolution (TFile *fa, TString ti, bool showBoth=false)
TCanvas * MakeDCA2DResolution (TFile *fa, TString ti)
TCanvas * MakeTH1F (TFile *fa, TString ti, TString wh, TString hw, bool norm=true, bool bw=false, bool log=false)
void plot ()
Function Documentation
TH1F* getHist (TString nom, TFile * fi, const char * na, int co, int mk = 20, float mks = 1)
Definition at line 11 of file plot.C.
Referenced by MakeEfficiency(), MakeEfficiencyFast(), and MakeTH1F().
TH2F* getHist2 (TString nom, TFile * fi, const char * na)
Definition at line 22 of file plot.C.
Referenced by MakeDCA2DResolution(), MakeEfficiency(), and MakePtResolution().
TCanvas* MakeDCA2DResolution (TFile * fa, TString ti)
Definition at line 204 of file plot.C.
References getHist2(), and leg.
Referenced by plot().
TCanvas* MakeEfficiency (TFile * fa, TString ti, float c0 = 0.01250, float c1 = 0.001858, bool plotOld = false)
Definition at line 29 of file plot.C.
References getHist(), getHist2(), leg, and x.
Referenced by plot().
TCanvas* MakeEfficiencyFast (TFile * fa, TString ti, TString hw, bool plotOld = false)
Definition at line 79 of file plot.C.
References getHist().
Referenced by plot().
TCanvas* MakePtResolution (TFile * fa, TString ti, bool showBoth = false)
Definition at line 108 of file plot.C.
References getHist2(), and leg.
Referenced by plot().
TCanvas* MakeTH1F (TFile * fa, TString ti, TString wh, TString hw, bool norm = true, bool bw = false, bool log = false)
Definition at line 259 of file plot.C.
References c2, getHist(), leg, norm, and NormByBinWidth().
Referenced by plot().
void NormByBinWidth (TH1F * inh)
Definition at line 1 of file plot.C.
References i.
Referenced by MakeTH1F().
void plot ()
Definition at line 297 of file plot.C.
References AtoB, cd(), cs_all, cs_off, Draw(), file, fs_off, MakeDCA2DResolution(), MakeEfficiency(), MakeEfficiencyFast(), MakePtResolution(), MakeTH1F(), SetLineColor(), SetLineWidth(), SetMaximum(), SetOptStat(), tcsn, tDQ(), tfsn, and tMap().