Analysis Software: RunInfoUnpackPRDF Class Reference
RunInfoUnpackPRDF Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/RunInfoUnpackPRDF.h>
Classes
class channel_info
Public Member Functions
RunInfoUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const std::string &name, const int packet_id, const unsigned int offset, const double calibration_const=+1)
add stuff to be unpacked
RunInfoUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const std::string &name, const int packet_id, const unsigned int offset, const double calibration_const=+1)
add stuff to be unpacked
RunInfoUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const std::string &name, const int packet_id, const unsigned int offset, const double calibration_const=+1)
add stuff to be unpacked
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
typedef std::map< std::string,
channel_info > typ_channel_map
list of channel name -> channel info
typedef std::map< std::string,
channel_info > typ_channel_map
list of channel name -> channel info
typedef std::map< std::string,
channel_info > typ_channel_map
list of channel name -> channel info
Private Attributes
typ_channel_map channel_map
std::string runinfo_node_name
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file RunInfoUnpackPRDF.h.
Member Typedef Documentation
typedef std::map<std::string, channel_info> RunInfoUnpackPRDF::typ_channel_map private
list of channel name -> channel info
Definition at line 50 of file RunInfoUnpackPRDF.h.
typedef std::map<std::string, channel_info> RunInfoUnpackPRDF::typ_channel_map private
list of channel name -> channel info
Definition at line 50 of file RunInfoUnpackPRDF.h.
typedef std::map<std::string, channel_info> RunInfoUnpackPRDF::typ_channel_map private
list of channel name -> channel info
Definition at line 50 of file RunInfoUnpackPRDF.h.
Constructor & Destructor Documentation
RunInfoUnpackPRDF::RunInfoUnpackPRDF ()
Definition at line 34 of file RunInfoUnpackPRDF.cc.
RunInfoUnpackPRDF::RunInfoUnpackPRDF ()
RunInfoUnpackPRDF::RunInfoUnpackPRDF ()
Member Function Documentation
void RunInfoUnpackPRDF::add_channel (const std::string & name, const int packet_id, const unsigned int offset, const double calibration_const = +1)
add stuff to be unpacked
Parameters
packet_id name of the channel
offset packet id
calibration_const offset in packet data conversion constant from integer to meaningful value
Definition at line 182 of file RunInfoUnpackPRDF.cc.
References channel_map.
Referenced by Fun4All_TestBeam().
void RunInfoUnpackPRDF::add_channel (const std::string & name, const int packet_id, const unsigned int offset, const double calibration_const = +1)
add stuff to be unpacked
Parameters
packet_id name of the channel
offset packet id
calibration_const offset in packet data conversion constant from integer to meaningful value
void RunInfoUnpackPRDF::add_channel (const std::string & name, const int packet_id, const unsigned int offset, const double calibration_const = +1)
add stuff to be unpacked
Parameters
packet_id name of the channel
offset packet id
calibration_const offset in packet data conversion constant from integer to meaningful value
void RunInfoUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 145 of file RunInfoUnpackPRDF.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and runinfo_node_name.
Referenced by InitRun().
void RunInfoUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
void RunInfoUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
int RunInfoUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file RunInfoUnpackPRDF.cc.
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
int RunInfoUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int RunInfoUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int RunInfoUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int RunInfoUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int RunInfoUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 48 of file RunInfoUnpackPRDF.cc.
References BEGRUNEVENT, RunInfoUnpackPRDF::channel_info::calibration_const, channel_map, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, EventHeaderv1::identify(), it, Packet::iValue(), name, RunInfoUnpackPRDF::channel_info::offset, RunInfoUnpackPRDF::channel_info::packet_id, PHParameters::Print(), runinfo_node_name, PHParameters::SaveToNodeTree(), PHParameters::set_double_param(), EventHeaderv1::set_EvtSequence(), EventHeaderv1::set_EvtType(), EventHeaderv1::set_RunNumber(), EventHeaderv1::set_TimeStamp(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Member Data Documentation
typ_channel_map RunInfoUnpackPRDF::channel_map private
Definition at line 52 of file RunInfoUnpackPRDF.h.
Referenced by add_channel(), and process_event().
std::string RunInfoUnpackPRDF::runinfo_node_name private
Definition at line 54 of file RunInfoUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/RunInfoUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype3/RunInfoUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype4/RunInfoUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype2/RunInfoUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype3/RunInfoUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype4/RunInfoUnpackPRDF.cc