Analysis Software: RecoInfoExport Class Reference
RecoInfoExport Class Reference
#include <analysis/blob/master/Test/RecoInfoExport/RecoInfoExport.h>
Public Member Functions
RecoInfoExport (const std::string &name="RecoInfoExport")
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_file_prefix (const std::string &s)
double get_pT_threshold () const
void set_pT_threshold (double tThreshold)
double get_tower_threshold () const
void set_tower_threshold (double towerThreshold)
double get_min_track_hit_dist () const
void set_min_track_hit_dist (double minTrackHitDist)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
int _event
std::string _file_prefix
std::vector< std::string > _calo_names
double _tower_threshold
double _pT_threshold
double _min_track_hit_dist
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 12 of file RecoInfoExport.h.
Constructor & Destructor Documentation
RecoInfoExport::RecoInfoExport (const std::string & name = "RecoInfoExport") explicit
Definition at line 44 of file RecoInfoExport.C.
Member Function Documentation
int RecoInfoExport::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 267 of file RecoInfoExport.C.
double RecoInfoExport::get_min_track_hit_dist () const inline
Definition at line 58 of file RecoInfoExport.h.
References _min_track_hit_dist.
double RecoInfoExport::get_pT_threshold () const inline
Definition at line 34 of file RecoInfoExport.h.
References _pT_threshold.
double RecoInfoExport::get_tower_threshold () const inline
Definition at line 46 of file RecoInfoExport.h.
References _tower_threshold.
int RecoInfoExport::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 52 of file RecoInfoExport.C.
int RecoInfoExport::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 59 of file RecoInfoExport.C.
References _min_track_hit_dist(), _pT_threshold(), _tower_threshold(), Fun4AllReturnCodes::ABORTRUN, SvtxTruthEval::all_truth_hits(), assert, c, RawTower::get_energy(), RawTowerGeomContainer::get_etacenter(), RawTowerGeomContainer::get_phicenter(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), SvtxEvalStack::get_truth_eval(), findNode::getClass(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTowers(), phi, PHWHERE, pos, and t.
void RecoInfoExport::set_file_prefix (const std::string & s) inline
Definition at line 28 of file RecoInfoExport.h.
References _file_prefix, and s.
void RecoInfoExport::set_min_track_hit_dist (double minTrackHitDist) inline
Definition at line 64 of file RecoInfoExport.h.
References _min_track_hit_dist.
void RecoInfoExport::set_pT_threshold (double tThreshold) inline
Definition at line 40 of file RecoInfoExport.h.
References _pT_threshold.
void RecoInfoExport::set_tower_threshold (double towerThreshold) inline
Definition at line 52 of file RecoInfoExport.h.
References _tower_threshold.
Member Data Documentation
std::vector<std::string> RecoInfoExport::_calo_names private
Definition at line 73 of file RecoInfoExport.h.
int RecoInfoExport::_event private
Definition at line 70 of file RecoInfoExport.h.
std::string RecoInfoExport::_file_prefix private
Definition at line 71 of file RecoInfoExport.h.
Referenced by set_file_prefix().
double RecoInfoExport::_min_track_hit_dist private
Definition at line 77 of file RecoInfoExport.h.
Referenced by get_min_track_hit_dist(), and set_min_track_hit_dist().
double RecoInfoExport::_pT_threshold private
Definition at line 76 of file RecoInfoExport.h.
Referenced by get_pT_threshold(), and set_pT_threshold().
double RecoInfoExport::_tower_threshold private
Definition at line 75 of file RecoInfoExport.h.
Referenced by get_tower_threshold(), and set_tower_threshold().
The documentation for this class was generated from the following files:
analysis/blob/master/Test/RecoInfoExport/RecoInfoExport.h
analysis/blob/master/Test/RecoInfoExport/RecoInfoExport.C