Analysis Software: PHG4HcalDetector Class Reference
PHG4HcalDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4HcalDetector.h>
Public Member Functions
PHG4HcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4HcalDetector (void)
destructor
void ConstructMe (G4LogicalVolume *world)
construct
void SetRadius (const G4double dbl)
void SetLength (const G4double dbl)
void SetPosition (const G4double x, const G4double y, const G4double z)
void SetTilt (const double tilt)
void SetScintWidth (const double wid)
void SetNumScint (const int num)
void SetScintPhi0 (const G4double phi0)
void SetThickness (const G4double dbl)
void SetMaterial (const std::string &mat)
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetDetectorType (const std::string &typ)
int IsInCylinderActive (const G4VPhysicalVolume *)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
G4UserSteppingAction * GetSteppingAction ()
void Print (const std::string &what="ALL") const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Static Public Attributes
static int INACTIVE = -100
Private Member Functions
double GetLength (const double phi) const
Private Attributes
G4Material * TrackerMaterial
G4double TrackerThickness
G4LogicalVolume * cylinder_logic
G4VPhysicalVolume * cylinder_physi
std::map< const
G4VPhysicalVolume *, int > box_vol
G4double radius
G4double length
G4double xpos
G4double ypos
G4double zpos
G4double _sciTilt
G4double _sciWidth
G4int _sciNum
G4double _sciPhi0
G4Region * _region
std::string material
int active
int absorberactive
int layer
std::string detector_type
std::string superdetector
Detailed Description
Definition at line 22 of file PHG4HcalDetector.h.
Constructor & Destructor Documentation
PHG4HcalDetector::PHG4HcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam, const int layer = 0)
constructor
Definition at line 51 of file PHG4HcalDetector.cc.
virtual PHG4HcalDetector::~PHG4HcalDetector (void) inline virtual
destructor
Definition at line 29 of file PHG4HcalDetector.h.
Member Function Documentation
void PHG4HcalDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 90 of file PHG4HcalDetector.cc.
References _sciNum, _sciPhi0, _sciTilt, _sciWidth, A, active, PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), box_vol, C, cylinder_logic, cylinder_physi, detector_type, PHNodeIterator::findFirst(), PHG4Utils::GetLengthForRapidityCoverage(), PHG4Detector::GetName(), i, layer, length, M_PI, material, PHG4Detector::OverlapCheck(), phi, r1, r2, radius, PHG4Utils::SetColour(), superdetector, PHG4Detector::topNode(), TrackerMaterial, TrackerThickness, twopi, v1, v2, v3, v4, x2, x3, xpos, y3, ypos, zero, and zpos.
int PHG4HcalDetector::get_Layer () const inline
Definition at line 58 of file PHG4HcalDetector.h.
References layer.
Referenced by PHG4HcalSteppingAction::UserSteppingAction().
double PHG4HcalDetector::GetLength (const double phi) const private
Definition at line 266 of file PHG4HcalDetector.cc.
References c, M_PI, phi, radius, and TrackerThickness.
G4UserSteppingAction* PHG4HcalDetector::GetSteppingAction (void) inline virtual
Reimplemented from PHG4Detector.
Definition at line 59 of file PHG4HcalDetector.h.
References _region.
int PHG4HcalDetector::IsInCylinderActive (const G4VPhysicalVolume * volume)
Definition at line 75 of file PHG4HcalDetector.cc.
References absorberactive, active, box_vol, cylinder_physi, and INACTIVE.
Referenced by PHG4HcalSteppingAction::UserSteppingAction().
void PHG4HcalDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 277 of file PHG4HcalDetector.cc.
References radius.
Referenced by PHG4HcalSubsystem::Print().
void PHG4HcalDetector::SetAbsorberActive (const int i = 1) inline
Definition at line 53 of file PHG4HcalDetector.h.
References absorberactive, and i.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetActive (const int i = 1) inline
Definition at line 52 of file PHG4HcalDetector.h.
References active, and i.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetDetectorType (const std::string & typ) inline
Definition at line 54 of file PHG4HcalDetector.h.
References detector_type.
void PHG4HcalDetector::SetLength (const G4double dbl) inline
Definition at line 37 of file PHG4HcalDetector.h.
References length.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetMaterial (const std::string & mat) inline
Definition at line 51 of file PHG4HcalDetector.h.
References material.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetNumScint (const int num) inline
Definition at line 47 of file PHG4HcalDetector.h.
References _sciNum, and num.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetPosition (const G4double x, const G4double y, const G4double z) inline
Definition at line 38 of file PHG4HcalDetector.h.
References xpos, ypos, and zpos.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetRadius (const G4double dbl) inline
Definition at line 36 of file PHG4HcalDetector.h.
References radius.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetScintPhi0 (const G4double phi0) inline
Definition at line 48 of file PHG4HcalDetector.h.
References _sciPhi0.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetScintWidth (const double wid) inline
Definition at line 46 of file PHG4HcalDetector.h.
References _sciWidth.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetThickness (const G4double dbl) inline
Definition at line 50 of file PHG4HcalDetector.h.
References TrackerThickness.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SetTilt (const double tilt) inline
Definition at line 45 of file PHG4HcalDetector.h.
References _sciTilt.
Referenced by PHG4HcalSubsystem::InitRun().
void PHG4HcalDetector::SuperDetector (const std::string & name) inline
Definition at line 56 of file PHG4HcalDetector.h.
References name, and superdetector.
Referenced by PHG4HcalSubsystem::InitRun(), and PHG4HcalSteppingAction::SetInterfacePointers().
const std::string PHG4HcalDetector::SuperDetector () const inline
Definition at line 57 of file PHG4HcalDetector.h.
References superdetector.
Member Data Documentation
G4Region* PHG4HcalDetector::_region private
Definition at line 87 of file PHG4HcalDetector.h.
Referenced by GetSteppingAction().
G4int PHG4HcalDetector::_sciNum private
Definition at line 85 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetNumScint().
G4double PHG4HcalDetector::_sciPhi0 private
Definition at line 86 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetScintPhi0().
G4double PHG4HcalDetector::_sciTilt private
Definition at line 83 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetTilt().
G4double PHG4HcalDetector::_sciWidth private
Definition at line 84 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetScintWidth().
int PHG4HcalDetector::absorberactive private
Definition at line 90 of file PHG4HcalDetector.h.
Referenced by IsInCylinderActive(), and SetAbsorberActive().
int PHG4HcalDetector::active private
Definition at line 89 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), IsInCylinderActive(), and SetActive().
std::map<const G4VPhysicalVolume*, int> PHG4HcalDetector::box_vol private
Definition at line 78 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and IsInCylinderActive().
G4LogicalVolume* PHG4HcalDetector::cylinder_logic private
Definition at line 76 of file PHG4HcalDetector.h.
Referenced by ConstructMe().
G4VPhysicalVolume* PHG4HcalDetector::cylinder_physi private
Definition at line 77 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and IsInCylinderActive().
std::string PHG4HcalDetector::detector_type private
Definition at line 92 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetDetectorType().
int PHG4HcalDetector::INACTIVE = -100 static
Definition at line 69 of file PHG4HcalDetector.h.
Referenced by IsInCylinderActive(), and PHG4HcalSteppingAction::UserSteppingAction().
int PHG4HcalDetector::layer private
Definition at line 91 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and get_Layer().
G4double PHG4HcalDetector::length private
Definition at line 81 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetLength().
std::string PHG4HcalDetector::material private
Definition at line 88 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetMaterial().
G4double PHG4HcalDetector::radius private
Definition at line 80 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), GetLength(), Print(), and SetRadius().
std::string PHG4HcalDetector::superdetector private
Definition at line 93 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SuperDetector().
G4Material* PHG4HcalDetector::TrackerMaterial private
Definition at line 73 of file PHG4HcalDetector.h.
Referenced by ConstructMe().
G4double PHG4HcalDetector::TrackerThickness private
Definition at line 74 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), GetLength(), and SetThickness().
G4double PHG4HcalDetector::xpos private
Definition at line 82 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetPosition().
G4double PHG4HcalDetector::ypos private
Definition at line 82 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetPosition().
G4double PHG4HcalDetector::zpos private
Definition at line 82 of file PHG4HcalDetector.h.
Referenced by ConstructMe(), and SetPosition().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4HcalDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4HcalDetector.cc