Analysis Software: PHG4CrystalCalorimeterSubsystem Class Reference
PHG4CrystalCalorimeterSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h>
Public Member Functions
PHG4CrystalCalorimeterSubsystem (const std::string &name="CRYSTAL_DEFAULT", const int layer=0)
virtual ~PHG4CrystalCalorimeterSubsystem ()
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
PHG4Detector * GetDetector (void) const
PHG4SteppingAction * GetSteppingAction () const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void SetTowerMappingFile (const std::string &filename)
void SetProjectiveGeometry (const std::string &filename1, const std::string &filename2)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4CrystalCalorimeterDetector * m_Detector
PHG4SteppingAction * m_SteppingAction
PHG4DisplayAction * m_DisplayAction
display attribute setting
int active
std::string detector_type
std::string mappingfile_
std::string mappingfile_4x4_construct_
bool projective_
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file PHG4CrystalCalorimeterSubsystem.h.
Constructor & Destructor Documentation
PHG4CrystalCalorimeterSubsystem::PHG4CrystalCalorimeterSubsystem (const std::string & name = "CRYSTAL_DEFAULT", const int layer = 0)
Constructor
Definition at line 27 of file PHG4CrystalCalorimeterSubsystem.cc.
PHG4CrystalCalorimeterSubsystem::~PHG4CrystalCalorimeterSubsystem () virtual
Destructor
Definition at line 41 of file PHG4CrystalCalorimeterSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
PHG4Detector * PHG4CrystalCalorimeterSubsystem::GetDetector (void) const virtual
Accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 117 of file PHG4CrystalCalorimeterSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4CrystalCalorimeterSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 42 of file PHG4CrystalCalorimeterSubsystem.h.
References m_DisplayAction.
PHG4SteppingAction* PHG4CrystalCalorimeterSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 41 of file PHG4CrystalCalorimeterSubsystem.h.
References m_SteppingAction.
int PHG4CrystalCalorimeterSubsystem::Init (PHCompositeNode * topNode) virtual
Creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) Creates the stepping action and place it on the node tree, under "ACTIONS" node Creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 47 of file PHG4CrystalCalorimeterSubsystem.cc.
References active, PHCompositeNode::addNode(), PHG4Subsystem::CheckOverlap(), detector_type, PHNodeIterator::findFirst(), m_Detector, m_DisplayAction, m_SteppingAction, mappingfile_, mappingfile_4x4_construct_, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), projective_, PHG4CrystalCalorimeterDetector::SetAbsorberActive(), PHG4CrystalCalorimeterDetector::SetActive(), PHG4CrystalCalorimeterDetector::SetSupermoduleGeometry(), PHG4CrystalCalorimeterDetector::SetTowerMappingFile(), and PHG4Detector::topNode().
int PHG4CrystalCalorimeterSubsystem::process_event (PHCompositeNode * topNode) virtual
Event processing
Reimplemented from SubsysReco.
Definition at line 105 of file PHG4CrystalCalorimeterSubsystem.cc.
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4CrystalCalorimeterSubsystem::SetProjectiveGeometry (const std::string & filename1, const std::string & filename2) inline
Select projective geometry for calorimeter
Definition at line 53 of file PHG4CrystalCalorimeterSubsystem.h.
References mappingfile_, mappingfile_4x4_construct_, and projective_.
Referenced by EEMCSetup().
void PHG4CrystalCalorimeterSubsystem::SetTowerMappingFile (const std::string & filename) inline
Set mapping file for calorimeter towers
Definition at line 46 of file PHG4CrystalCalorimeterSubsystem.h.
References filename, and mappingfile_.
Referenced by EEMCSetup().
Member Data Documentation
int PHG4CrystalCalorimeterSubsystem::active private
Definition at line 82 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by Init().
std::string PHG4CrystalCalorimeterSubsystem::detector_type private
Definition at line 84 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by Init().
PHG4CrystalCalorimeterDetector* PHG4CrystalCalorimeterSubsystem::m_Detector private
Enum for different geometry configurationsPointer to the Geant4 implementation of the detector
Definition at line 73 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by GetDetector(), and Init().
PHG4DisplayAction* PHG4CrystalCalorimeterSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 80 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by GetDisplayAction(), Init(), and ~PHG4CrystalCalorimeterSubsystem().
PHG4SteppingAction* PHG4CrystalCalorimeterSubsystem::m_SteppingAction private
Stepping action
Definition at line 77 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
std::string PHG4CrystalCalorimeterSubsystem::mappingfile_ private
Definition at line 85 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by Init(), SetProjectiveGeometry(), and SetTowerMappingFile().
std::string PHG4CrystalCalorimeterSubsystem::mappingfile_4x4_construct_ private
Definition at line 86 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by Init(), and SetProjectiveGeometry().
bool PHG4CrystalCalorimeterSubsystem::projective_ private
Definition at line 88 of file PHG4CrystalCalorimeterSubsystem.h.
Referenced by Init(), and SetProjectiveGeometry().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc