Analysis Software: SvtxTrack_FastSim Class Reference
SvtxTrack_FastSim Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim.h>
Public Member Functions
SvtxTrack_FastSim ()
virtual ~SvtxTrack_FastSim ()
unsigned int get_truth_track_id () const
void set_truth_track_id (unsigned int truthTrackId)
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
void set_num_measurements (int nmeas)
unsigned int get_num_measurements ()
Public Member Functions inherited from SvtxTrack_v1
SvtxTrack_v1 ()
SvtxTrack_v1 (const SvtxTrack_v1 &track)
SvtxTrack_v1 & operator= (const SvtxTrack_v1 &track)
virtual ~SvtxTrack_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
unsigned int get_vertex_id () const
void set_vertex_id (unsigned int id)
bool get_positive_charge () const
void set_positive_charge (bool ispos)
int get_charge () const
void set_charge (int charge)
float get_chisq () const
void set_chisq (float chisq)
unsigned int get_ndf () const
void set_ndf (int ndf)
float get_quality () const
float get_dca () const
void set_dca (float dca)
float get_dca_error () const
void set_dca_error (float dca_error)
float get_dca2d () const
void set_dca2d (float dca2d)
float get_dca2d_error () const
void set_dca2d_error (float error)
float get_dca3d_xy () const
void set_dca3d_xy (float dcaxy)
float get_dca3d_xy_error () const
void set_dca3d_xy_error (float error)
float get_dca3d_z () const
void set_dca3d_z (float dcaz)
float get_dca3d_z_error () const
void set_dca3d_z_error (float error)
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
float get_pos (unsigned int i) const
float get_px () const
void set_px (float px)
float get_py () const
void set_py (float py)
float get_pz () const
void set_pz (float pz)
float get_mom (unsigned int i) const
float get_p () const
float get_pt () const
float get_eta () const
float get_phi () const
float get_error (int i, int j) const
void set_error (int i, int j, float value)
bool empty_states () const
size_t size_states () const
size_t count_states (float pathlength) const
void clear_states ()
const SvtxTrackState * get_state (float pathlength) const
SvtxTrackState * get_state (float pathlength)
SvtxTrackState * insert_state (const SvtxTrackState *state)
size_t erase_state (float pathlength)
ConstStateIter begin_states () const
ConstStateIter find_state (float pathlength) const
ConstStateIter end_states () const
StateIter begin_states ()
StateIter find_state (float pathlength)
StateIter end_states ()
void clear_clusters ()
bool empty_clusters () const
size_t size_clusters () const
void insert_cluster (unsigned int clusterid)
size_t erase_cluster (unsigned int clusterid)
ConstClusterIter begin_clusters () const
ConstClusterIter find_cluster (unsigned int clusterid) const
ConstClusterIter end_clusters () const
ClusterIter find_cluster (unsigned int clusterid)
ClusterIter begin_clusters ()
ClusterIter end_clusters ()
void clear_cluster_keys ()
bool empty_cluster_keys () const
size_t size_cluster_keys () const
void insert_cluster_key (TrkrDefs::cluskey clusterid)
size_t erase_cluster_key (TrkrDefs::cluskey clusterid)
ConstClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid) const
ConstClusterKeyIter begin_cluster_keys () const
ConstClusterKeyIter end_cluster_keys () const
ClusterKeyIter find_cluster_key (TrkrDefs::cluskey clusterid)
ClusterKeyIter begin_cluster_keys ()
ClusterKeyIter end_cluster_keys ()
float get_cal_dphi (CAL_LAYER layer) const
void set_cal_dphi (CAL_LAYER layer, float dphi)
float get_cal_deta (CAL_LAYER layer) const
void set_cal_deta (CAL_LAYER layer, float deta)
float get_cal_energy_3x3 (CAL_LAYER layer) const
void set_cal_energy_3x3 (CAL_LAYER layer, float energy_3x3)
float get_cal_energy_5x5 (CAL_LAYER layer) const
void set_cal_energy_5x5 (CAL_LAYER layer, float energy_5x5)
unsigned int get_cal_cluster_id (CAL_LAYER layer) const
void set_cal_cluster_id (CAL_LAYER layer, unsigned int id)
TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER layer) const
void set_cal_cluster_key (CAL_LAYER layer, TrkrDefs::cluskey id)
float get_cal_cluster_e (CAL_LAYER layer) const
void set_cal_cluster_e (CAL_LAYER layer, float e)
Public Member Functions inherited from SvtxTrack
virtual ~SvtxTrack ()
virtual ClusterKeyIter find_cluster_keys (unsigned int clusterid)
virtual float get_cal_dphi (CAL_LAYER layer) const
virtual void set_cal_dphi (CAL_LAYER layer, float dphi)
virtual float get_cal_deta (CAL_LAYER layer) const
virtual void set_cal_deta (CAL_LAYER layer, float deta)
virtual float get_cal_energy_3x3 (CAL_LAYER layer) const
virtual void set_cal_energy_3x3 (CAL_LAYER layer, float energy_3x3)
virtual float get_cal_energy_5x5 (CAL_LAYER layer) const
virtual void set_cal_energy_5x5 (CAL_LAYER layer, float energy_5x5)
virtual unsigned int get_cal_cluster_id (CAL_LAYER layer) const
virtual void set_cal_cluster_id (CAL_LAYER layer, unsigned int id)
virtual TrkrDefs::cluskey get_cal_cluster_key (CAL_LAYER layer) const
virtual void set_cal_cluster_key (CAL_LAYER layer, TrkrDefs::cluskey key)
virtual float get_cal_cluster_e (CAL_LAYER layer) const
virtual void set_cal_cluster_e (CAL_LAYER layer, float e)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
unsigned int _truth_track_id
unsigned int _nmeas
Additional Inherited Members
Public Types inherited from SvtxTrack
enum CAL_LAYER { PRES = 0, CEMC = 1, HCALIN = 2, HCALOUT = 3 }
typedef std::map< float,
SvtxTrackState * > StateMap
typedef StateMap::const_iterator ConstStateIter
typedef StateMap::iterator StateIter
typedef std::set< unsigned int > ClusterSet
typedef ClusterSet::const_iterator ConstClusterIter
typedef ClusterSet::iterator ClusterIter
typedef std::set
< TrkrDefs::cluskey > ClusterKeySet
typedef
ClusterKeySet::const_iterator ConstClusterKeyIter
typedef ClusterKeySet::iterator ClusterKeyIter
Protected Member Functions inherited from SvtxTrack
SvtxTrack ()
ClassDef (SvtxTrack, 1)
Detailed Description
Definition at line 15 of file SvtxTrack_FastSim.h.
Constructor & Destructor Documentation
SvtxTrack_FastSim::SvtxTrack_FastSim ()
Definition at line 18 of file SvtxTrack_FastSim.cc.
Referenced by CloneMe(), and Reset().
SvtxTrack_FastSim::~SvtxTrack_FastSim () virtual
Definition at line 24 of file SvtxTrack_FastSim.cc.
Member Function Documentation
PHObject* SvtxTrack_FastSim::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxTrack.
Definition at line 35 of file SvtxTrack_FastSim.h.
References SvtxTrack_FastSim().
unsigned int SvtxTrack_FastSim::get_num_measurements () inline
Definition at line 38 of file SvtxTrack_FastSim.h.
References _nmeas.
unsigned int SvtxTrack_FastSim::get_truth_track_id () const inline virtual
Reimplemented from SvtxTrack.
Definition at line 21 of file SvtxTrack_FastSim.h.
References _truth_track_id.
Referenced by PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), and identify().
void SvtxTrack_FastSim::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrack.
Definition at line 28 of file SvtxTrack_FastSim.cc.
References SvtxTrack_v1::begin_clusters(), SvtxTrack_v1::empty_clusters(), SvtxTrack_v1::end_clusters(), SvtxTrack_v1::get_charge(), SvtxTrack_v1::get_chisq(), SvtxTrack_v1::get_id(), SvtxTrack_v1::get_ndf(), SvtxTrack_v1::get_px(), SvtxTrack_v1::get_py(), SvtxTrack_v1::get_pz(), get_truth_track_id(), SvtxTrack_v1::get_x(), SvtxTrack_v1::get_y(), and SvtxTrack_v1::get_z().
int SvtxTrack_FastSim::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrack.
Definition at line 60 of file SvtxTrack_FastSim.cc.
void SvtxTrack_FastSim::Reset () inline virtual
Clear Event.
Reimplemented from SvtxTrack.
Definition at line 33 of file SvtxTrack_FastSim.h.
References SvtxTrack_FastSim().
void SvtxTrack_FastSim::set_num_measurements (int nmeas) inline
Definition at line 37 of file SvtxTrack_FastSim.h.
References _nmeas.
Referenced by PHG4TrackFastSim::MakeSvtxTrack().
void SvtxTrack_FastSim::set_truth_track_id (unsigned int truthTrackId) inline virtual
Reimplemented from SvtxTrack.
Definition at line 26 of file SvtxTrack_FastSim.h.
References _truth_track_id.
Referenced by PHG4TrackFastSim::MakeSvtxTrack(), and PHTruthTrackSeeding::Process().
Member Data Documentation
unsigned int SvtxTrack_FastSim::_nmeas private
Definition at line 42 of file SvtxTrack_FastSim.h.
Referenced by get_num_measurements(), and set_num_measurements().
unsigned int SvtxTrack_FastSim::_truth_track_id private
Definition at line 41 of file SvtxTrack_FastSim.h.
Referenced by get_truth_track_id(), and set_truth_track_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrack_FastSim.cc