Analysis Software: analysis/blob/master/TPC/TrackingPerformance/Fun.C File Reference
Fun.C File Reference
Functions
void ConfigureInput (TString inputFile)
void RandomSeed ()
void ConfigureDetectors ()
void Libraries ()
int Fun (const int nEvents=1, const int nFile=0)
Function Documentation
void ConfigureDetectors ()
Definition at line 54 of file Fun.C.
References Bbc_Reco(), BbcInit(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_Towers(), G4Init(), G4Setup(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), Jet_Eval(), Jet_Reco(), kAll, ShowerCompress(), Svtx_Cells(), Svtx_Eval(), and Svtx_Reco().
Referenced by Fun().
void ConfigureInput (TString inputFile)
Definition at line 1 of file Fun.C.
References PHG4SimpleEventGenerator::add_particles(), PHG4ParticleGeneratorBase::Embed(), Fun4AllInputManager::fileopen(), hijing(), in, Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHG4SimpleEventGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_pt_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
Referenced by Fun().
int Fun (const int nEvents = 1, const int nFile = 0)
Definition at line 143 of file Fun.C.
References ConfigureDetectors(), ConfigureInput(), Fun4AllServer::dumpHistos(), Fun4AllServer::End(), Fun4AllServer::instance(), Libraries(), nEvents, RandomSeed(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), TrackingPerformanceCheck::SetFairClustersContribution(), TrackingPerformanceCheck::SetGoodTrackChi2NDF(), TrackingPerformanceCheck::SetGoodTrackTPCClusters(), TrackingPerformanceCheck::SetLayerTPCBegins(), TrackingPerformanceCheck::SetReconstructableTPCHits(), and Fun4AllBase::Verbosity().
void Libraries ()
Definition at line 131 of file Fun.C.
Referenced by Fun().
void RandomSeed ()
Definition at line 41 of file Fun.C.
References recoConsts::instance().
Referenced by Fun().