Analysis Software: analysis/blob/master/PhotonConversion/ana/conversionRate.C File Reference
conversionRate.C File Reference
Functions
TChain * handleFile (string name, string extension, string treename, unsigned int filecount)
TEfficiency * makepTRes (TFile *out_file, TChain *ttree=NULL, TTree *allTree=NULL)
unsigned totalMB (string path, string extension, string hardname, string softname)
TH1F * calculateRate (TEfficiency *rate, TFile *file, unsigned nMB)
void derivitvePlot (TH1F *finalrate)
void conversionRate ()
Function Documentation
TH1F* calculateRate (TEfficiency * rate, TFile * file, unsigned nMB)
Parameters
rate the uniform conversion rate
file file to get the pythia pT spectra from
Returns
the pT dependent conversion rate
Definition at line 97 of file conversionRate.C.
Referenced by conversionRate().
void conversionRate ()
Definition at line 121 of file conversionRate.C.
References calculateRate(), derivitvePlot(), handleFile(), makepTRes(), and totalMB().
void derivitvePlot (TH1F * finalrate)
Definition at line 110 of file conversionRate.C.
References i.
Referenced by conversionRate().
TChain* handleFile (string name, string extension, string treename, unsigned int filecount)
Definition at line 2 of file conversionRate.C.
References i, and s.
Referenced by conversionRate(), mapper(), minBiasRecoAna(), photonEff2(), trackpT(), train(), vtxPredictionTraining(), and vtxRS().
TEfficiency* makepTRes (TFile * out_file, TChain * ttree = NULL, TTree * allTree = NULL)
makes a TEff holding the hists for a uniform conversion rate
Parameters
out_file file data is saved to this is used for read and write needs converted and truth pT spectra to be inside these are created by photonEff if the pT spectra are not inside the file
ttree and
allTree will be used to calculate these spectra
ttree tree for converted data
allTree tree for nonconverted data
Returns
NULL if the spectra are not in the existing data and the passes trees are not valid
Definition at line 22 of file conversionRate.C.
References i.
Referenced by conversionRate(), and photonEff2().
unsigned totalMB (string path, string extension, string hardname, string softname)
Definition at line 82 of file conversionRate.C.
References name, and r.
Referenced by conversionRate().