Analysis Software: AnaSvtxTracksForGenFit Class Reference
AnaSvtxTracksForGenFit Class Reference
#include <analysis/blob/master/Tracking/GenFitTest/AnaSvtxTracksForGenFit/AnaSvtxTracksForGenFit.h>
Public Types
enum Flag { NONE = 0 }
Public Member Functions
AnaSvtxTracksForGenFit (const std::string &name="AnaSvtxTracksForGenFit")
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_filename (const char *file)
void set_flag (const Flag &flag, const bool &value)
void fill_tree (PHCompositeNode *)
void reset_variables ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void GetNodes (PHCompositeNode *)
Private Attributes
std::string _outfile
int _event
unsigned int _flags
TTree * _tracks
int event
int gtrackID
int gflavor
float gpx
float gpy
float gpz
float gvx
float gvy
float gvz
int trackID
int charge
int nhits
float px
float py
float pz
float dca2d
int clusterID [7]
int layer [7]
float x [7]
float y [7]
float z [7]
float size_dphi [7]
float size_dz [7]
PHG4TruthInfoContainer * _truth_container
SvtxClusterMap * _clustermap
SvtxEvalStack * _svtxevalstack
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file AnaSvtxTracksForGenFit.h.
Member Enumeration Documentation
enum AnaSvtxTracksForGenFit::Flag
Enumerator:
NONE
Definition at line 37 of file AnaSvtxTracksForGenFit.h.
Constructor & Destructor Documentation
AnaSvtxTracksForGenFit::AnaSvtxTracksForGenFit (const std::string & name = "AnaSvtxTracksForGenFit")
Definition at line 52 of file AnaSvtxTracksForGenFit.cc.
References _event, and _outfile.
Member Function Documentation
int AnaSvtxTracksForGenFit::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 133 of file AnaSvtxTracksForGenFit.cc.
References _outfile, _svtxevalstack, _tracks, PHTFileServer::cd(), and PHTFileServer::get().
void AnaSvtxTracksForGenFit::fill_tree (PHCompositeNode * topNode)
Definition at line 150 of file AnaSvtxTracksForGenFit.cc.
References _clustermap, _svtxevalstack, _tracks, _truth_container, SvtxTrack::begin_clusters(), SvtxTrackEval::best_track_from(), charge, clusterID, dca2d, SvtxTrack::end_clusters(), SvtxClusterMap::get(), SvtxTrack::get_charge(), SvtxTrack::get_dca2d(), SvtxTrack::get_id(), SvtxCluster::get_layer(), SvtxCluster::get_phi_size(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_pz(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), SvtxEvalStack::get_truth_eval(), SvtxTruthEval::get_vertex(), PHG4VtxPoint::get_x(), SvtxCluster::get_x(), PHG4VtxPoint::get_y(), SvtxCluster::get_y(), PHG4VtxPoint::get_z(), SvtxCluster::get_z(), SvtxCluster::get_z_size(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), gflavor, gpx, gpy, gpz, gtrackID, gvx, gvy, gvz, layer, nhits, px, py, pz, reset_variables(), SvtxTrack::size_clusters(), size_dphi, size_dz, trackID, x, y, and z.
Referenced by process_event().
void AnaSvtxTracksForGenFit::GetNodes (PHCompositeNode * topNode) private
Definition at line 271 of file AnaSvtxTracksForGenFit.cc.
References _clustermap, _event, _truth_container, and PHWHERE.
Referenced by process_event().
int AnaSvtxTracksForGenFit::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 67 of file AnaSvtxTracksForGenFit.cc.
References _outfile, _tracks, charge, clusterID, dca2d, event, PHTFileServer::get(), gflavor, gpx, gpy, gpz, gtrackID, gvx, gvy, gvz, layer, nhits, PHTFileServer::open(), PHWHERE, px, py, pz, size_dphi, size_dz, trackID, x, y, and z.
int AnaSvtxTracksForGenFit::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 108 of file AnaSvtxTracksForGenFit.cc.
References _event, _svtxevalstack, fill_tree(), GetNodes(), SvtxEvalStack::next_event(), PHWHERE, SvtxEvalStack::set_strict(), SvtxEvalStack::set_verbosity(), and verbosity.
void AnaSvtxTracksForGenFit::reset_variables ()
Definition at line 230 of file AnaSvtxTracksForGenFit.cc.
References charge, clusterID, dca2d, gflavor, gpx, gpy, gpz, gtrackID, gvx, gvy, gvz, i, layer, nhits, px, py, pz, size_dphi, size_dz, trackID, x, y, and z.
Referenced by fill_tree().
void AnaSvtxTracksForGenFit::set_filename (const char * file) inline
Definition at line 33 of file AnaSvtxTracksForGenFit.h.
References _outfile, and file.
Referenced by Fun4All_G4_sPHENIX_AnaGenFit().
void AnaSvtxTracksForGenFit::set_flag (const Flag & flag, const bool & value) inline
Definition at line 45 of file AnaSvtxTracksForGenFit.h.
References _flags.
Member Data Documentation
SvtxClusterMap* AnaSvtxTracksForGenFit::_clustermap private
Definition at line 99 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), and GetNodes().
int AnaSvtxTracksForGenFit::_event private
Definition at line 60 of file AnaSvtxTracksForGenFit.h.
Referenced by AnaSvtxTracksForGenFit(), GetNodes(), and process_event().
unsigned int AnaSvtxTracksForGenFit::_flags private
Definition at line 66 of file AnaSvtxTracksForGenFit.h.
Referenced by set_flag().
std::string AnaSvtxTracksForGenFit::_outfile private
Definition at line 57 of file AnaSvtxTracksForGenFit.h.
Referenced by AnaSvtxTracksForGenFit(), End(), Init(), and set_filename().
SvtxEvalStack* AnaSvtxTracksForGenFit::_svtxevalstack private
Definition at line 102 of file AnaSvtxTracksForGenFit.h.
Referenced by End(), fill_tree(), and process_event().
TTree* AnaSvtxTracksForGenFit::_tracks private
Definition at line 69 of file AnaSvtxTracksForGenFit.h.
Referenced by End(), fill_tree(), and Init().
PHG4TruthInfoContainer* AnaSvtxTracksForGenFit::_truth_container private
Definition at line 98 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), and GetNodes().
int AnaSvtxTracksForGenFit::charge private
Definition at line 82 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
int AnaSvtxTracksForGenFit::clusterID[7] private
Definition at line 89 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::dca2d private
Definition at line 87 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
int AnaSvtxTracksForGenFit::event private
Definition at line 70 of file AnaSvtxTracksForGenFit.h.
Referenced by Init().
int AnaSvtxTracksForGenFit::gflavor private
Definition at line 73 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::gpx private
Definition at line 74 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::gpy private
Definition at line 75 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::gpz private
Definition at line 76 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
int AnaSvtxTracksForGenFit::gtrackID private
Definition at line 72 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::gvx private
Definition at line 77 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::gvy private
Definition at line 78 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::gvz private
Definition at line 79 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
int AnaSvtxTracksForGenFit::layer[7] private
Definition at line 90 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
int AnaSvtxTracksForGenFit::nhits private
Definition at line 83 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::px private
Definition at line 84 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::py private
Definition at line 85 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::pz private
Definition at line 86 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::size_dphi[7] private
Definition at line 94 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::size_dz[7] private
Definition at line 95 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
int AnaSvtxTracksForGenFit::trackID private
Definition at line 81 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::x[7] private
Definition at line 91 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::y[7] private
Definition at line 92 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
float AnaSvtxTracksForGenFit::z[7] private
Definition at line 93 of file AnaSvtxTracksForGenFit.h.
Referenced by fill_tree(), Init(), and reset_variables().
The documentation for this class was generated from the following files:
analysis/blob/master/Tracking/GenFitTest/AnaSvtxTracksForGenFit/AnaSvtxTracksForGenFit.h
analysis/blob/master/Tracking/GenFitTest/AnaSvtxTracksForGenFit/AnaSvtxTracksForGenFit.cc