Analysis Software: PHG4EnvelopeSteppingAction Class Reference
PHG4EnvelopeSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.h>
Public Member Functions
PHG4EnvelopeSteppingAction (PHG4EnvelopeDetector *)
virtual ~PHG4EnvelopeSteppingAction ()
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action. This defines processing of a single step in a given volume
virtual void SetInterfacePointers (PHCompositeNode *)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4EnvelopeDetector * detector_
PHG4HitContainer * hits_
PHG4Hit * hit
Detailed Description
Definition at line 14 of file PHG4EnvelopeSteppingAction.h.
Constructor & Destructor Documentation
PHG4EnvelopeSteppingAction::PHG4EnvelopeSteppingAction (PHG4EnvelopeDetector * detector)
Definition at line 38 of file PHG4EnvelopeSteppingAction.cc.
virtual PHG4EnvelopeSteppingAction::~PHG4EnvelopeSteppingAction () inline virtual
Definition at line 21 of file PHG4EnvelopeSteppingAction.h.
Member Function Documentation
void PHG4EnvelopeSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
Reimplemented from PHG4SteppingAction.
Definition at line 187 of file PHG4EnvelopeSteppingAction.cc.
References detector_, PHG4Detector::GetName(), hits_, and PHG4EnvelopeDetector::SuperDetector().
Referenced by PHG4EnvelopeSubsystem::process_event().
bool PHG4EnvelopeSteppingAction::UserSteppingAction (const G4Step * step, bool was_used) virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used,: true if the hit was already used by a previously registered subsystem
Implements PHG4SteppingAction.
Definition at line 47 of file PHG4EnvelopeSteppingAction.cc.
References PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4EnvelopeDetector::get_Layer(), PHG4HitContainer::GetID(), hit, hits_, PHG4EnvelopeDetector::IsActive(), PHG4EnvelopeDetector::IsInEnvelope(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_index_j(), PHG4Hit::set_index_k(), PHG4Hit::set_index_l(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4EnvelopeDetector* PHG4EnvelopeSteppingAction::detector_ private
Definition at line 33 of file PHG4EnvelopeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4EnvelopeSteppingAction::hit private
Definition at line 37 of file PHG4EnvelopeSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4EnvelopeSteppingAction::hits_ private
Definition at line 36 of file PHG4EnvelopeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.cc