Analysis Software: prototype/blob/master/macros/tpc2019/DrawTpcPrototypeGenFitTrkFitter.C File Reference
DrawTpcPrototypeGenFitTrkFitter.C File Reference
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
#include <TChain.h>
#include <TCut.h>
#include <TEfficiency.h>
#include <TF1.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TH2.h>
#include <TH3.h>
#include <TPolyLine.h>
#include <TTree.h>
#include <TFile.h>
#include <TColor.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TStyle.h>
#include <TDirectory.h>
#include <TMath.h>
#include <TPad.h>
#include <TString.h>
#include <TVirtualFitter.h>
#include <cmath>
#include <iostream>
Macros
#define assert(exp)
Functions
void useLogBins (TAxis *axis)
utility function to
TGraphErrors * FitProfile (const TH2 *h2)
TTree * T (nullptr)
void Resolution (const TCut &cut="Iteration$ >= 5 && Iteration$ <= 10 && TPCTrack.nCluster>=12 && TPCTrack.clusterSizePhi > 3.5", const double phi_start=-2.905, const double phi_end=-2.885)
void TrackQA ()
void Track3D ()
void TrackDistortion (const TCut &cut="TPCTrack.nCluster>=10")
Double_t langaufun (Double_t *x, Double_t *par)
TF1 * langaufit (TH1 *his, const vector< double > &fitrange, const vector< double > &startvalues, const vector< double > &parlimitslo, const vector< double > &parlimitshi)
void TrackClusterEnergy (const TCut &cut="TPCTrack.nCluster>=10")
void DrawTpcPrototypeGenFitTrkFitter (const TString infile="data/tpc_beam/tpc_beam_00000292-0000.evt_TpcPrototypeGenFitTrkFitter.root", const TString desc="Run 292")
Variables
TFile * _file0 = NULL
TString description
Macro Definition Documentation
#define assert (exp)
Value:
{                                                                                             \
    if (!(exp))                                                                                 \
    {                                                                                           \
      cout << "Assert (" << #exp << ") failed at " << __FILE__ << " line " << __LINE__ << endl; \
      exit(1);                                                                                  \
    }                                                                                           \
  }
Definition at line 39 of file DrawTpcPrototypeGenFitTrkFitter.C.
Function Documentation
void DrawTpcPrototypeGenFitTrkFitter (const TString infile = "data/tpc_beam/tpc_beam_00000292-0000.evt_TpcPrototypeGenFitTrkFitter.root", const TString desc = "Run 292")
Definition at line 518 of file DrawTpcPrototypeGenFitTrkFitter.C.
References _file0, assert, description, n, Resolution(), SetsPhenixStyle(), T, t, Track3D(), TrackClusterEnergy(), TrackDistortion(), and TrackQA().
TGraphErrors* FitProfile (const TH2 * h2)
Definition at line 70 of file DrawTpcPrototypeGenFitTrkFitter.C.
References f2(), h1, i, n, x, and y.
TF1* langaufit (TH1 * his, const vector< double > & fitrange, const vector< double > & startvalues, const vector< double > & parlimitslo, const vector< double > & parlimitshi)
Definition at line 427 of file DrawTpcPrototypeGenFitTrkFitter.C.
References i, and langaufun().
Referenced by TrackClusterEnergy().
Double_t langaufun (Double_t * x, Double_t * par)
Definition at line 373 of file DrawTpcPrototypeGenFitTrkFitter.C.
References i, step, and sum().
void Resolution (const TCut & cut = "Iteration$ >= 5 && Iteration$ <= 10 && TPCTrack.nCluster>=12 && TPCTrack.clusterSizePhi > 3.5", const double phi_start = -2.905, const double phi_end = -2.885)
Definition at line 137 of file DrawTpcPrototypeGenFitTrkFitter.C.
References _file0, description, FitProfile(), leg, SaveCanvas(), sum(), T, value, x, and y.
Referenced by DrawTpcPrototypeGenFitTrkFitter().
TTree* T (nullptr)
void Track3D ()
Definition at line 304 of file DrawTpcPrototypeGenFitTrkFitter.C.
References _file0, description, leg, SaveCanvas(), and T.
Referenced by DrawTpcPrototypeGenFitTrkFitter().
void TrackClusterEnergy (const TCut & cut = "TPCTrack.nCluster>=10")
Definition at line 482 of file DrawTpcPrototypeGenFitTrkFitter.C.
References _file0, description, double(), fit(), langaufit(), leg, SaveCanvas(), and T.
Referenced by DrawTpcPrototypeGenFitTrkFitter().
void TrackDistortion (const TCut & cut = "TPCTrack.nCluster>=10")
Definition at line 344 of file DrawTpcPrototypeGenFitTrkFitter.C.
References _file0, FitProfile(), SaveCanvas(), and T.
Referenced by DrawTpcPrototypeGenFitTrkFitter().
void TrackQA ()
Definition at line 255 of file DrawTpcPrototypeGenFitTrkFitter.C.
References _file0, SaveCanvas(), and T.
Referenced by DrawTpcPrototypeGenFitTrkFitter().
void useLogBins (TAxis * axis)
utility function to
Definition at line 49 of file DrawTpcPrototypeGenFitTrkFitter.C.
References assert, bins, and i.
Variable Documentation
TFile* _file0 = NULL
Definition at line 133 of file DrawTpcPrototypeGenFitTrkFitter.C.
TString description
Definition at line 134 of file DrawTpcPrototypeGenFitTrkFitter.C.