Analysis Software: HelixDCAFunc Class Reference
HelixDCAFunc Class Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/helix_hough/VertexFitFunc.h>
Public Member Functions
HelixDCAFunc ()
~HelixDCAFunc ()
bool calcValGradHessian (const Eigen::VectorXd &x, double &val, Eigen::VectorXd &grad, Eigen::MatrixXd &hessian)
FitNewton::FunctionGradHessian * Clone () const
double getTangent (unsigned int coor)
double getPoint (unsigned int coor)
Eigen::Matrix< float, 3, 3 > getPointCovariance ()
void setCovariance (Eigen::Matrix< float, 5, 5 > const &cov)
Public Member Functions inherited from FitNewton::FunctionGradHessian
FunctionGradHessian (unsigned int nparams=1, unsigned int nfixedparams=1)
virtual ~FunctionGradHessian ()
virtual bool calcValGrad (const Eigen::VectorXd &x, double &val, Eigen::VectorXd &grad)
unsigned int nPars ()
unsigned int nFixedPars ()
std::vector< double > getFixedPars ()
void setFixedPar (unsigned int coor, double val)
virtual void computeCovariance (const double &val, const Eigen::MatrixXd &hessian)
virtual void rescaleMove (const Eigen::VectorXd &pars, Eigen::VectorXd &move)
Private Attributes
Eigen::Matrix< float, 5, 5 > covariance
std::vector< double > tangent
std::vector< double > point
Eigen::Matrix< float, 3, 3 > point_covariance
Additional Inherited Members
Protected Attributes inherited from FitNewton::FunctionGradHessian
unsigned int npars
unsigned int nfixedpars
std::vector< double > fixedpars
Detailed Description
Definition at line 12 of file VertexFitFunc.h.
Constructor & Destructor Documentation
HelixDCAFunc::HelixDCAFunc ()
Definition at line 14 of file VertexFitFunc.cpp.
References point, and tangent.
Referenced by Clone().
HelixDCAFunc::~HelixDCAFunc ()
Definition at line 21 of file VertexFitFunc.cpp.
Member Function Documentation
bool HelixDCAFunc::calcValGradHessian (const Eigen::VectorXd & x, double & val, Eigen::VectorXd & grad, Eigen::MatrixXd & hessian) virtual
Implements FitNewton::FunctionGradHessian.
Definition at line 27 of file VertexFitFunc.cpp.
References covariance, d, dx, dy, dzdl, FitNewton::FunctionGradHessian::fixedpars, i, k, M_PI, phi, point, point_covariance, s, tangent, ux, uy, and x.
Referenced by VertexFitFunc::calcValGradHessian().
FitNewton::FunctionGradHessian* HelixDCAFunc::Clone () const inline virtual
Implements FitNewton::FunctionGradHessian.
Definition at line 20 of file VertexFitFunc.h.
References HelixDCAFunc().
double HelixDCAFunc::getPoint (unsigned int coor) inline
Definition at line 23 of file VertexFitFunc.h.
References point.
Referenced by VertexFitFunc::calcValGradHessian().
Eigen::Matrix<float,3,3> HelixDCAFunc::getPointCovariance () inline
Definition at line 24 of file VertexFitFunc.h.
References point_covariance.
Referenced by VertexFitFunc::calcValGradHessian().
double HelixDCAFunc::getTangent (unsigned int coor) inline
Definition at line 22 of file VertexFitFunc.h.
References tangent.
Referenced by VertexFitFunc::calcValGradHessian().
void HelixDCAFunc::setCovariance (Eigen::Matrix< float, 5, 5 > const & cov) inline
Definition at line 25 of file VertexFitFunc.h.
References covariance.
Referenced by VertexFitFunc::calcValGradHessian().
Member Data Documentation
Eigen::Matrix<float,5,5> HelixDCAFunc::covariance private
Definition at line 28 of file VertexFitFunc.h.
Referenced by calcValGradHessian(), and setCovariance().
std::vector<double> HelixDCAFunc::point private
Definition at line 30 of file VertexFitFunc.h.
Referenced by calcValGradHessian(), getPoint(), and HelixDCAFunc().
Eigen::Matrix<float,3,3> HelixDCAFunc::point_covariance private
Definition at line 31 of file VertexFitFunc.h.
Referenced by calcValGradHessian(), and getPointCovariance().
std::vector<double> HelixDCAFunc::tangent private
Definition at line 29 of file VertexFitFunc.h.
Referenced by calcValGradHessian(), getTangent(), and HelixDCAFunc().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/VertexFitFunc.h
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/VertexFitFunc.cpp