Analysis Software: online_distribution/blob/master/pmonitor/pmonitor.h File Reference
pmonitor.h File Reference
#include <TVirtualPad.h>
#include <TThread.h>
#include <Event/Event.h>
#include <Event/EventTypes.h>
Functions
int pstatus ()
int ptestopen ()
int poncsopen (const char *filename)
int rcdaqopen (const char *ip=0)
int pfileopen (const char *filename)
int plistopen (const char *filename)
int pstart (const int nevents)
void prun ()
void prun (const int nevents)
int pstart ()
int pstop ()
int pclose ()
int pidentify (const int n)
int pidentify ()
int pclearidentify ()
int pcontrol ()
int pcontrol (const int seconds)
int pwait ()
int plock ()
int prelease ()
const char * pname ()
int pexitstatus ()
int pinit ()
int process_event (Event *e)
int phsave (const char *filename="histos.root")
void phelp ()
void pupdate (TVirtualPad *pad, const unsigned int refresh=5)
void pend_update (TVirtualPad *pad=0)
Function Documentation
int pclearidentify ()
Definition at line 227 of file pmonitor.cc.
References pmonstate::setIdentifyFlag().
int pclose ()
Definition at line 382 of file pmonitor.cc.
References pmonstate::clearOpened(), pmonstate::isRunning(), pmonstate::streamOpened(), and theIterator.
Referenced by pprocess(), and prun().
int pcontrol ()
int pcontrol (const int seconds)
void pend_update (TVirtualPad * pad = 0)
Definition at line 679 of file pmonitor.cc.
References pad_to_stop, and stop_update.
int pexitstatus ()
Definition at line 57 of file pmonitor.cc.
References pmonstate::getloopStatus().
int pfileopen (const char * filename)
Definition at line 83 of file pmonitor.cc.
References FROG::location(), pmonstate::setFileOpened(), pmonstate::streamOpened(), and theIterator.
void phelp ()
Definition at line 550 of file pmonitor.cc.
int phsave (const char * filename = "histos.root")
int pidentify (const int n)
Definition at line 201 of file pmonitor.cc.
References pmonstate::setIdentifyFlag().
int pidentify ()
Definition at line 221 of file pmonitor.cc.
References pmonstate::setIdentifyFlag().
int pinit ()
Definition at line 81 of file MyFavoriteMartin.C.
References h1a, h1a_D, h1b, h1b_D, h1c, h1c_D, h1d, h1d_D, h2a, h2a_D, h2b, h2b_D, h2c, h2c_D, h2d, h2d_D, h3a, h3a_D, h3b, h3b_D, h3c, h3c_D, h3d, h3d_D, h4a, h4a_D, h4b, h4b_D, h4c, h4c_D, h4d, h4d_D, groot::instance(), scope0, scope1, scope2, and scope3.
Referenced by pmonstate::pmonstate().
int plistopen (const char * filename)
Definition at line 179 of file pmonitor.cc.
References pmonstate::setFileOpened(), pmonstate::streamOpened(), and theIterator.
int plock ()
Definition at line 406 of file pmonitor.cc.
References mylock, and pmonmutex.
const char* pname ()
Referenced by PHParameterContainerInterface::PHParameterContainerInterface().
int poncsopen (const char * filename)
Definition at line 113 of file pmonitor.cc.
References pmonstate::setFileOpened(), pmonstate::streamOpened(), and theIterator.
Referenced by groot100().
int prelease ()
Definition at line 422 of file pmonitor.cc.
References mylock, and pmonmutex.
int process_event (Event * e)
Definition at line 141 of file MyFavoriteMartin.C.
References prdfoStream::addEvent(), Quiver::AnalyzeScope, Quiver::AnalyzeSRS, AZigzag::ApplyCalibration(), CHhybrid, groot::ClearTheDetector(), AZigzag::DetermineCommonMode(), double(), groot::event, FillBlobHist(), FindBlobs(), first_event_nr, Event::getEvtSequence(), Event::getEvtType(), Event::getPacket(), Event::getRunNumber(), h1a, h1a_D, h1b, h1b_D, h1c, h1c_D, h1d, h1d_D, h2a, h2a_D, h2b, h2b_D, h2c, h2c_D, h2d, h2d_D, h3a, h3a_D, h3b, h3b_D, h3c, h3c_D, h3d, h3d_D, h4a, h4a_D, h4b, h4b_D, h4c, h4c_D, h4d, h4d_D, i, groot::instance(), Packet::iValue(), j, min, Nhybrid, AZigzag::Raw, Quiver::RunNumber, Packet::rValue(), samples, scope0, scope1, scope2, scope3, groot::theTraces, groot::theTracks, and groot::theZigzags.
Referenced by pprocess(), and prun().
void prun ()
Definition at line 319 of file pmonitor.cc.
References prun().
Referenced by groot100(), and prun().
void prun (const int nevents)
Definition at line 324 of file pmonitor.cc.
References pmonstate::clearNoevt(), pmonstate::clearRunning(), Eventiterator::getNextEvent(), Event::identify(), pmonstate::incrementNoevt(), pmonstate::isIdentifyFlag(), pclose(), process_event(), return(), pmonstate::setloopStatus(), pmonstate::setRunning(), stopcondition, and pmonstate::streamOpened().
int pstart (const int nevents)
Definition at line 292 of file pmonitor.cc.
References pmonstate::isRunning(), main_thread, nevents(), pprocess(), pmonstate::streamOpened(), and totalevents.
Referenced by pstart().
int pstart ()
Definition at line 314 of file pmonitor.cc.
References pstart().
int pstatus ()
Definition at line 44 of file pmonitor.cc.
References Eventiterator::identify(), and theState.
int pstop ()
Definition at line 366 of file pmonitor.cc.
References pmonstate::isRunning(), and stopcondition.
int ptestopen ()
Definition at line 65 of file pmonitor.cc.
References pmonstate::setTestOpened(), and pmonstate::streamOpened().
void pupdate (TVirtualPad * pad, const unsigned int refresh = 5)
Definition at line 657 of file pmonitor.cc.
References mon_thread, pad_to_stop, threadargument::refreshinterval, stop_update, threadargument::thePad, and update_process().
int pwait ()
Definition at line 437 of file pmonitor.cc.
References pMutex::Lock(), and pMutex::Release().
int rcdaqopen (const char * ip = 0)
Definition at line 137 of file pmonitor.cc.
References pmonstate::setRCDAQOpened(), pmonstate::streamOpened(), and theIterator.