Analysis Software: PHTrackSetMerging Class Reference
PHTrackSetMerging Class Reference abstract
Base class for track seeding.
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackSetMerging.h>
Public Member Functions
PHTrackSetMerging (const std::string &name="PHTrackSetMerging")
virtual ~PHTrackSetMerging ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_track_map_name_in1 (const std::string &map_name)
void set_track_map_name_in2 (const std::string &map_name)
void set_track_map_name_out (const std::string &map_name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int Setup (PHCompositeNode *topNode)
virtual int Process ()=0
virtual int End ()=0
Called in SubsysReco::End.
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map_in1
SvtxTrackMap * _track_map_in2
SvtxTrackMap * _track_map_out
AssocInfoContainer * _assoc_container
std::string _track_map_name_in1
std::string _track_map_name_in2
std::string _track_map_name_out
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
create new node output pointers
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Base class for track seeding.
Definition at line 29 of file PHTrackSetMerging.h.
Constructor & Destructor Documentation
PHTrackSetMerging::PHTrackSetMerging (const std::string & name = "PHTrackSetMerging")
Definition at line 26 of file PHTrackSetMerging.cc.
virtual PHTrackSetMerging::~PHTrackSetMerging () inline virtual
Definition at line 33 of file PHTrackSetMerging.h.
Member Function Documentation
int PHTrackSetMerging::CreateNodes (PHCompositeNode * topNode) private
create new node output pointers
Definition at line 68 of file PHTrackSetMerging.cc.
References _assoc_container, _track_map_out, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Setup().
int PHTrackSetMerging::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 52 of file PHTrackSetMerging.cc.
References End().
virtual int PHTrackSetMerging::End () protected pure virtual
Called in SubsysReco::End.
Referenced by End().
int PHTrackSetMerging::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 116 of file PHTrackSetMerging.cc.
References _assoc_container, _cluster_map, _track_map_in1, _track_map_in2, _track_map_name_in1, _track_map_name_in2, _track_map_name_out, _track_map_out, _vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHTrackSetMerging::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 37 of file PHTrackSetMerging.cc.
References Fun4AllReturnCodes::EVENT_OK.
int PHTrackSetMerging::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 42 of file PHTrackSetMerging.cc.
References Setup().
virtual int PHTrackSetMerging::Process () protected pure virtual
process event interface for trackers, called in process_event. implemented in derived classes
Referenced by process_event().
int PHTrackSetMerging::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 47 of file PHTrackSetMerging.cc.
References Process().
void PHTrackSetMerging::set_track_map_name_in1 (const std::string & map_name) inline
Definition at line 40 of file PHTrackSetMerging.h.
References _track_map_name_in1.
void PHTrackSetMerging::set_track_map_name_in2 (const std::string & map_name) inline
Definition at line 41 of file PHTrackSetMerging.h.
References _track_map_name_in2.
void PHTrackSetMerging::set_track_map_name_out (const std::string & map_name) inline
Definition at line 42 of file PHTrackSetMerging.h.
References _track_map_name_out.
int PHTrackSetMerging::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Definition at line 57 of file PHTrackSetMerging.cc.
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, and GetNodes().
Referenced by InitRun().
Member Data Documentation
AssocInfoContainer* PHTrackSetMerging::_assoc_container protected
Definition at line 62 of file PHTrackSetMerging.h.
Referenced by CreateNodes(), and GetNodes().
TrkrClusterContainer* PHTrackSetMerging::_cluster_map protected
Definition at line 57 of file PHTrackSetMerging.h.
Referenced by GetNodes().
SvtxTrackMap* PHTrackSetMerging::_track_map_in1 protected
Definition at line 59 of file PHTrackSetMerging.h.
Referenced by GetNodes().
SvtxTrackMap* PHTrackSetMerging::_track_map_in2 protected
Definition at line 60 of file PHTrackSetMerging.h.
Referenced by GetNodes().
std::string PHTrackSetMerging::_track_map_name_in1 protected
Definition at line 64 of file PHTrackSetMerging.h.
Referenced by GetNodes(), and set_track_map_name_in1().
std::string PHTrackSetMerging::_track_map_name_in2 protected
Definition at line 65 of file PHTrackSetMerging.h.
Referenced by GetNodes(), and set_track_map_name_in2().
std::string PHTrackSetMerging::_track_map_name_out protected
Definition at line 66 of file PHTrackSetMerging.h.
Referenced by GetNodes(), and set_track_map_name_out().
SvtxTrackMap* PHTrackSetMerging::_track_map_out protected
Definition at line 61 of file PHTrackSetMerging.h.
Referenced by CreateNodes(), and GetNodes().
SvtxVertexMap* PHTrackSetMerging::_vertex_map protected
Definition at line 58 of file PHTrackSetMerging.h.
Referenced by GetNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackSetMerging.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackSetMerging.cc