Analysis Software: online_distribution/blob/master/newbasic/dataBlock.C File Reference
dataBlock.C File Reference
#include "dataBlock.h"
Functions
VALUE_ret getUnstructPacketDataLengthBytes (PACKET_ptr packet_ptr)
VALUE_ret getUnstructPacketDataLengthWords (PACKET_ptr packet_ptr)
VALUE_ret extendUnstructPacketDataBlock (PACKET_ptr packet_ptr, UINT addWords)
Function Documentation
VALUE_ret extendUnstructPacketDataBlock (PACKET_ptr packet_ptr, UINT addWords)
Definition at line 64 of file dataBlock.C.
References DWORD_SIZE, getUnstructPacketDataLengthWords(), getUnstructPacketWordSize(), setUnstructPacketDataPadding(), and valueFailure.
Referenced by finishUnstructDataWrite(), startUnstructDataWrite(), and storePacketHits().
VALUE_ret getUnstructPacketDataLengthBytes (PACKET_ptr packet_ptr)
Definition at line 30 of file dataBlock.C.
References DWORD_SIZE, getPacketDataLength(), getUnstructPacketDataPadding(), and valueFailure.
Referenced by getUnstructPacketDataLengthWords().
VALUE_ret getUnstructPacketDataLengthWords (PACKET_ptr packet_ptr)
Definition at line 46 of file dataBlock.C.
References FORMAT_ERR_DATA_INCONSISTENCY, getUnstructPacketDataLengthBytes(), getUnstructPacketWordSize(), setPacketError(), and valueFailure.
Referenced by dumpPacket(), extendUnstructPacketDataBlock(), fetchPacketHits(), and finishUnstructDataWrite().