Analysis Software: TPCFEETestRecov1 Class Reference
TPCFEETestRecov1 Class Reference
#include <coresoftware/blob/master/offline/packages/tpcdaq/TPCFEETestRecov1.h>
Classes
class ChannelHeader
simple channel header class for ROOT file IO
class ClusterData
buffer for a cluster's data
class EventHeader
simple event header class for ROOT file IO
class PadPlaneData
buffer for full event data
Public Member Functions
TPCFEETestRecov1 (const std::string &outputfilename="TPCFEETestRecov1.root")
virtual ~TPCFEETestRecov1 ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void setClusteringZeroSuppression (int threshold)
void setNPostSample (int nPostSample)
void setNPreSample (int nPreSample)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
Fun4AllHistoManager * getHistoManager ()
void Clustering (void)
Clustering then prepare IOs.
void get_motor_loc (Event *evt)
Static Private Member Functions
static std::pair< int, int > roughZeroSuppression (std::vector< int > &data)
Private Attributes
std::string m_outputFileName
TTree * m_eventT
EventHeader m_eventHeader
EventHeader * m_peventHeader
int m_nClusters
->m_eventHeader, for filling TTree
TClonesArray * m_IOClusters
TTree * m_chanT
ChannelHeader m_chanHeader
ChannelHeader * m_pchanHeader
std::vector< uint32_t > m_chanData
->m_chanHeader, for filling TTree
PadPlaneData m_padPlaneData
std::map< int, ClusterData > m_clusters
int m_clusteringZeroSuppression
int m_nPreSample
int m_nPostSample
int m_XRayLocationX
int m_XRayLocationY
TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp_PDFMaker * m_pdfMaker
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 36 of file TPCFEETestRecov1.h.
Constructor & Destructor Documentation
TPCFEETestRecov1::TPCFEETestRecov1 (const std::string & outputfilename = "TPCFEETestRecov1.root")
Definition at line 65 of file TPCFEETestRecov1.cc.
TPCFEETestRecov1::~TPCFEETestRecov1 () virtual
Definition at line 84 of file TPCFEETestRecov1.cc.
References m_IOClusters, and m_pdfMaker.
Member Function Documentation
void TPCFEETestRecov1::Clustering (void) private
Clustering then prepare IOs.
Definition at line 369 of file TPCFEETestRecov1.cc.
References assert, TPCFEETestRecov1::ClusterData::avg_padx, TPCFEETestRecov1::ClusterData::avg_pady, TPCFEETestRecov1::PadPlaneData::Clustering(), TPCFEETestRecov1::EventHeader::event, TPCFEETestRecov1::PadPlaneData::getGroups(), TPCFEETestRecov1::PadPlaneData::getPad(), i, TPCFEETestRecov1::PadPlaneData::IsValidPad(), TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_clusteringZeroSuppression, m_clusters, m_eventHeader, m_IOClusters, m_nClusters, m_nPostSample, m_nPreSample, m_padPlaneData, m_pdfMaker, TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp_PDFMaker::MakeSectionPage(), max, TPCFEETestRecov1::ClusterData::max_sample, min, TPCFEETestRecov1::ClusterData::min_sample, TPCFEETestRecov1::ClusterData::padx_peaks, TPCFEETestRecov1::ClusterData::padx_samples, TPCFEETestRecov1::ClusterData::padxs, TPCFEETestRecov1::ClusterData::pady_peaks, TPCFEETestRecov1::ClusterData::pady_samples, TPCFEETestRecov1::ClusterData::padys, TPCFEETestRecov1::ClusterData::peak, TPCFEETestRecov1::ClusterData::peak_sample, TPCFEETestRecov1::ClusterData::pedstal, TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), TPCFEETestRecov1::ClusterData::samples, TPCFEETestRecov1::ClusterData::size_pad_x, TPCFEETestRecov1::ClusterData::size_pad_y, TPCFEETestRecov1::ClusterData::sum_samples, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by process_event().
int TPCFEETestRecov1::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 187 of file TPCFEETestRecov1.cc.
References assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllHistoManager::getHisto(), getHistoManager(), i, m_chanT, m_eventT, m_outputFileName, m_pdfMaker, Fun4AllHistoManager::nHistos(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void TPCFEETestRecov1::get_motor_loc (Event * evt) private
Definition at line 695 of file TPCFEETestRecov1.cc.
References assert, Packet::getLength(), Event::getPacket(), i, IDCSTR, Packet::iValue(), m_XRayLocationX, m_XRayLocationY, and Fun4AllBase::Verbosity().
Referenced by process_event().
Fun4AllHistoManager * TPCFEETestRecov1::getHistoManager () private
Definition at line 674 of file TPCFEETestRecov1.cc.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), InitRun(), and process_event().
int TPCFEETestRecov1::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 112 of file TPCFEETestRecov1.cc.
References Fun4AllReturnCodes::EVENT_OK.
int TPCFEETestRecov1::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 117 of file TPCFEETestRecov1.cc.
References assert, TPCFEETestRecov1::EventHeader::event, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), getHistoManager(), SVM_v1::h, i, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_chanData, m_chanT, m_eventHeader, m_eventT, m_IOClusters, m_nClusters, m_outputFileName, m_pchanHeader, m_pdfMaker, m_peventHeader, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int TPCFEETestRecov1::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 216 of file TPCFEETestRecov1.cc.
References assert, BEGRUNEVENT, TPCFEETestRecov1::EventHeader::bx_counter, TPCFEETestRecov1::ChannelHeader::bx_counter, TPCFEETestRecov1::EventHeader::bx_counter_consistent, channel(), Clustering(), DATAEVENT, Fun4AllReturnCodes::DISCARDEVENT, Packet::dump(), TPCFEETestRecov1::EventHeader::event, Fun4AllReturnCodes::EVENT_OK, TPCFEETestRecov1::ChannelHeader::fee_channel, get_motor_loc(), Fun4AllHistoManager::getHisto(), getHistoManager(), TPCFEETestRecov1::PadPlaneData::getPad(), ID4EVT, Packet::identify(), TPCFEETestRecov1::PadPlaneData::IsValidPad(), Packet::iValue(), TPCDaqDefs::FEEv1::kN_CHANNELS, TPCDaqDefs::FEEv1::kPACKET_ID, TPCDaqDefs::FEEv1::kPACKET_LENGTH, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, m_chanData, m_chanHeader, m_chanT, m_eventHeader, m_eventT, m_padPlaneData, m_pdfMaker, m_XRayLocationX, m_XRayLocationY, TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp_PDFMaker::MakeSectionPage(), TPCFEETestRecov1::ChannelHeader::max, TPCFEETestRecov1::ChannelHeader::packet_type, TPCFEETestRecov1::ChannelHeader::pad_x, TPCFEETestRecov1::ChannelHeader::pad_y, TPCFEETestRecov1::ChannelHeader::pedestal, printf(), roughZeroSuppression(), TPCFEETestRecov1::EventHeader::run, TPCFEETestRecov1::ChannelHeader::sampa_address, TPCFEETestRecov1::ChannelHeader::sampa_channel, TPCDaqDefs::FEEv1::SAMPAChan2PadXY(), TPCFEETestRecov1::ChannelHeader::size, value, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, Fun4AllBase::VERBOSITY_SOME, TPCFEETestRecov1::EventHeader::xray_x, and TPCFEETestRecov1::EventHeader::xray_y.
int TPCFEETestRecov1::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 98 of file TPCFEETestRecov1.cc.
References assert, Fun4AllReturnCodes::EVENT_OK, m_chanHeader, m_clusters, m_eventHeader, m_IOClusters, m_nClusters, m_padPlaneData, and TPCFEETestRecov1::PadPlaneData::Reset().
std::pair< int, int > TPCFEETestRecov1::roughZeroSuppression (std::vector< int > & data) static private
rough zero suppression by subtracting sample medium value
Returns
pair of pedestal and max
Definition at line 557 of file TPCFEETestRecov1.cc.
References d, max, and pedestal().
Referenced by process_event().
void TPCFEETestRecov1::setClusteringZeroSuppression (int threshold) inline
Definition at line 49 of file TPCFEETestRecov1.h.
References m_clusteringZeroSuppression.
void TPCFEETestRecov1::setNPostSample (int nPostSample) inline
Definition at line 54 of file TPCFEETestRecov1.h.
References m_nPostSample.
void TPCFEETestRecov1::setNPreSample (int nPreSample) inline
Definition at line 59 of file TPCFEETestRecov1.h.
References m_nPreSample.
Member Data Documentation
std::vector<uint32_t> TPCFEETestRecov1::m_chanData private
->m_chanHeader, for filling TTree
Definition at line 248 of file TPCFEETestRecov1.h.
Referenced by InitRun(), and process_event().
ChannelHeader TPCFEETestRecov1::m_chanHeader private
Definition at line 246 of file TPCFEETestRecov1.h.
Referenced by process_event(), and ResetEvent().
TTree* TPCFEETestRecov1::m_chanT private
Definition at line 244 of file TPCFEETestRecov1.h.
Referenced by End(), InitRun(), and process_event().
int TPCFEETestRecov1::m_clusteringZeroSuppression private
Definition at line 263 of file TPCFEETestRecov1.h.
Referenced by Clustering(), and setClusteringZeroSuppression().
std::map<int, ClusterData> TPCFEETestRecov1::m_clusters private
Definition at line 252 of file TPCFEETestRecov1.h.
Referenced by Clustering(), and ResetEvent().
EventHeader TPCFEETestRecov1::m_eventHeader private
Definition at line 238 of file TPCFEETestRecov1.h.
Referenced by Clustering(), InitRun(), process_event(), and ResetEvent().
TTree* TPCFEETestRecov1::m_eventT private
Definition at line 236 of file TPCFEETestRecov1.h.
Referenced by End(), InitRun(), and process_event().
TClonesArray* TPCFEETestRecov1::m_IOClusters private
Definition at line 242 of file TPCFEETestRecov1.h.
Referenced by Clustering(), InitRun(), ResetEvent(), and ~TPCFEETestRecov1().
int TPCFEETestRecov1::m_nClusters private
->m_eventHeader, for filling TTree
Definition at line 241 of file TPCFEETestRecov1.h.
Referenced by Clustering(), InitRun(), and ResetEvent().
int TPCFEETestRecov1::m_nPostSample private
Definition at line 265 of file TPCFEETestRecov1.h.
Referenced by Clustering(), and setNPostSample().
int TPCFEETestRecov1::m_nPreSample private
Definition at line 264 of file TPCFEETestRecov1.h.
Referenced by Clustering(), and setNPreSample().
std::string TPCFEETestRecov1::m_outputFileName private
Definition at line 234 of file TPCFEETestRecov1.h.
Referenced by End(), and InitRun().
PadPlaneData TPCFEETestRecov1::m_padPlaneData private
Definition at line 251 of file TPCFEETestRecov1.h.
Referenced by Clustering(), process_event(), and ResetEvent().
ChannelHeader* TPCFEETestRecov1::m_pchanHeader private
Definition at line 247 of file TPCFEETestRecov1.h.
Referenced by InitRun().
TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp_PDFMaker* TPCFEETestRecov1::m_pdfMaker private
Definition at line 272 of file TPCFEETestRecov1.h.
Referenced by Clustering(), End(), InitRun(), process_event(), and ~TPCFEETestRecov1().
EventHeader* TPCFEETestRecov1::m_peventHeader private
Definition at line 239 of file TPCFEETestRecov1.h.
Referenced by InitRun().
int TPCFEETestRecov1::m_XRayLocationX private
Definition at line 269 of file TPCFEETestRecov1.h.
Referenced by get_motor_loc(), and process_event().
int TPCFEETestRecov1::m_XRayLocationY private
Definition at line 270 of file TPCFEETestRecov1.h.
Referenced by get_motor_loc(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpcdaq/TPCFEETestRecov1.h
coresoftware/blob/master/offline/packages/tpcdaq/TPCFEETestRecov1.cc