Analysis Software: hcal Class Reference
hcal Class Reference
#include <analysis/blob/master/Prototype2/HCAL/HighBayCode/hcal.h>
Public Member Functions
hcal ()
~hcal ()
void Initialize ()
int evLoop (int nevt)
int GetNextEvent ()
int collect (int)
void setPrdf (TString &fin)
void setPrdflist (TString &fin)
void set_display (bool b)
void Display ()
int Clear ()
void SetCableMap (int _nch, int *_index)
TGraph * getSignal (int ch)
void fitShape (int)
void Save (char *)
void set_positive_polarity (bool b)
void set_verbosity (bool b)
void set_plot_max (float max)
void set_plot_min (float min)
void FitDisplay ()
void setCalibration ()
Int_t getStackTiming ()
Int_t update (Int_t displayMode=3, Bool_t fitShapes=kFALSE)
Int_t collectTrPrimitives ()
void displayRaw (Int_t mode=0)
void displaySummary (Int_t mode=0)
void clean ()
Static Public Member Functions
static double SignalShape (double *x, double *par)
static double SignalShapeNegative (double *x, double *par)
Public Attributes
int runnumber
int nevents
TString prdfName
int NCH
int NSAMPLES
int PEDESTAL
bool display
Eventiterator * it
Event * evt
TGraph * gpulse [100]
std::vector< int > channel_index
TF1 * fits [100]
bool fit_analysis
TH2F * h2_fit_shape [100]
TH1F * h_PulsePeaks [100]
TH1F * h_PulseInt [100]
TH2F * h2_Pulse_H_Int [100]
TH2F * h_hilo [100]
TH1F * h_gain [100]
TH1F * h_tres [100]
TH1F * h_ped_res [100]
TH1F * h_saturation_rates
TH1F * h_info
TGraph * rate
TCanvas * c
float plot_max
float plot_min
TFile * fout
bool polarity_positive
bool verbosity
std::map< int, float > saturation_map
Int_t rejectEvent
Bool_t readyForEvent
Int_t maxStacks
Int_t activeStacks
Int_t activeCalStacks
Bool_t * alive
Int_t * kinds
stack ** stacks
Double_t amplTotal
Double_t eTotal
Double_t calLCG
Double_t scintLCG
TH1 * totalamp
TH1 * totale
TH1 * totallcg
TH1 * scintlcg
Private Member Functions
hcal ()
~hcal ()
Friends
class hcalHelper
Detailed Description
Definition at line 17 of file hcal.h.
Constructor & Destructor Documentation
hcal::hcal ()
Definition at line 22 of file hcal.C.
References PEDESTAL, and verbosity.
hcal::~hcal () inline
Definition at line 21 of file hcal.h.
hcal::hcal () private
hcal::~hcal () private
Member Function Documentation
void hcal::clean ()
Definition at line 544 of file hcalHelper.C.
References amplTotal, calLCG, CALSTACKS, stack::clean(), eTotal, readyForEvent, rejectEvent, scintLCG, and stacks.
Referenced by hcalHelper::evLoop().
int hcal::Clear ()
Definition at line 167 of file hcal.C.
References gpulse, NCH, and verbosity.
int hcal::collect (int ich)
Definition at line 290 of file hcal.C.
References max, min, nevents(), and verbosity.
Int_t hcal::collectTrPrimitives ()
Definition at line 406 of file hcalHelper.C.
References CALOR, CALSTACKS, stack::getTrigger(), and stacks.
Referenced by hcalHelper::evLoop().
void hcal::Display ()
Definition at line 337 of file hcal.C.
References c, gpulse, NCH, nevents(), verbosity, and x.
void hcal::displayRaw (Int_t mode = 0)
Definition at line 458 of file hcalHelper.C.
References CALOR, CALSTACKS, stack::displayADCSum(), stack::displayEvent(), and stacks.
Referenced by hcalHelper::evLoop().
void hcal::displaySummary (Int_t mode = 0)
Definition at line 474 of file hcalHelper.C.
References alive, CALOR, CALSTACKS, cd(), hLabHelper::cDirectory, stack::displayStackSummary(), stack::displayTowerSummary(), Draw(), hLabHelper::getInstance(), hcalHelper::getInstance(), hcalHelper::runnumber, stack::satProb, scintlcg, stacks, totalamp, totale, and totallcg.
Referenced by hcalHelper::evLoop().
int hcal::evLoop (int nevt = 0)
Definition at line 121 of file hcal.C.
References double(), it, NCH, nevents(), rate, and verbosity.
Referenced by analyze().
void hcal::FitDisplay ()
void hcal::fitShape (int ich)
Definition at line 242 of file hcal.C.
References gpulse, NSAMPLES, and pedestal().
int hcal::GetNextEvent ()
Definition at line 179 of file hcal.C.
References fitShape(), Eventiterator::getNextEvent(), gpulse, it, Packet_hbd_fpgashort::iValue(), NCH, nevents(), NSAMPLES, Packet_hbd_fpgashort::setNumSamples(), and verbosity.
TGraph* hcal::getSignal (int ch) inline
Definition at line 38 of file hcal.h.
References gpulse.
Int_t hcal::getStackTiming ()
Definition at line 394 of file hcalHelper.C.
References CALOR, CALSTACKS, stack::getStackTime(), kinds, rejectEvent, and stacks.
Referenced by hcalHelper::evLoop().
void hcal::Initialize ()
Definition at line 35 of file hcal.C.
References gpulse, max, name, NCH, NSAMPLES, rate, SignalShape(), and SignalShapeNegative().
void hcal::Save (char * filename)
Definition at line 403 of file hcal.C.
References fixGDML::fout, NCH, and rate.
Referenced by analyze().
void hcal::set_display (bool b) inline
Definition at line 29 of file hcal.h.
References display.
Referenced by analyze().
void hcal::set_plot_max (float max) inline
Definition at line 48 of file hcal.h.
References max, and plot_max.
void hcal::set_plot_min (float min) inline
Definition at line 50 of file hcal.h.
References min, and plot_min.
void hcal::set_positive_polarity (bool b) inline
Definition at line 44 of file hcal.h.
References polarity_positive.
Referenced by analyze().
void hcal::set_verbosity (bool b) inline
Definition at line 46 of file hcal.h.
References verbosity.
Referenced by analyze().
void hcal::SetCableMap (int _nch, int * _index) inline
Definition at line 34 of file hcal.h.
References channel_index, and NCH.
Referenced by analyze().
void hcal::setCalibration ()
Definition at line 366 of file hcalHelper.C.
References alive, CALOR, CALSTACKS, stack::stackECalib, stack::stackId, stacks, and stECalib.
Referenced by hcalHelper::hcalHelper().
void hcal::setPrdf (TString & fin) inline
Definition at line 26 of file hcal.h.
References prdfName.
Referenced by analyze().
void hcal::setPrdflist (TString & fin)
double hcal::SignalShape (double * x, double * par) static
Definition at line 383 of file hcal.C.
References pedestal(), and signal().
Referenced by Initialize().
double hcal::SignalShapeNegative (double * x, double * par) static
Definition at line 393 of file hcal.C.
References pedestal(), and signal().
Referenced by Initialize().
Int_t hcal::update (Int_t displayMode = 3, Bool_t fitShapes = kFALSE)
Definition at line 424 of file hcalHelper.C.
References alive, amplTotal, calLCG, CALOR, CALSTACKS, tower::campl, stack::E, eTotal, rejectEvent, SCINT, scintLCG, scintlcg, stacks, stAScale, totalamp, totale, totallcg, stack::totCorAmpl, stack::towers, and stack::update().
Referenced by hcalHelper::evLoop().
Friends And Related Function Documentation
friend class hcalHelper friend
Definition at line 257 of file hcalUtil.h.
Member Data Documentation
Int_t hcal::activeCalStacks
Definition at line 264 of file hcalUtil.h.
Int_t hcal::activeStacks
Definition at line 263 of file hcalUtil.h.
Bool_t* hcal::alive
Definition at line 265 of file hcalUtil.h.
Referenced by displaySummary(), hcalHelper::evLoop(), hcalHelper::hcalHelper(), setCalibration(), hcalHelper::setRunKind(), and update().
Double_t hcal::amplTotal
Definition at line 277 of file hcalUtil.h.
Referenced by clean(), hcalTree::hcalTree(), and update().
TCanvas* hcal::c
Definition at line 78 of file hcal.h.
Double_t hcal::calLCG
Definition at line 279 of file hcalUtil.h.
Referenced by clean(), hcalTree::hcalTree(), and update().
std::vector<int> hcal::channel_index
Definition at line 64 of file hcal.h.
Referenced by SetCableMap().
bool hcal::display
Definition at line 60 of file hcal.h.
Referenced by set_display().
Double_t hcal::eTotal
Definition at line 278 of file hcalUtil.h.
Referenced by clean(), hcalTree::hcalTree(), and update().
Event* hcal::evt
Definition at line 62 of file hcal.h.
bool hcal::fit_analysis
Definition at line 66 of file hcal.h.
TF1* hcal::fits[100]
Definition at line 65 of file hcal.h.
TFile* hcal::fout
Definition at line 81 of file hcal.h.
TGraph* hcal::gpulse[100]
Definition at line 63 of file hcal.h.
Referenced by getSignal().
TH2F* hcal::h2_fit_shape[100]
Definition at line 67 of file hcal.h.
TH2F* hcal::h2_Pulse_H_Int[100]
Definition at line 70 of file hcal.h.
TH1F* hcal::h_gain[100]
Definition at line 72 of file hcal.h.
TH2F* hcal::h_hilo[100]
Definition at line 71 of file hcal.h.
TH1F* hcal::h_info
Definition at line 76 of file hcal.h.
TH1F* hcal::h_ped_res[100]
Definition at line 74 of file hcal.h.
TH1F* hcal::h_PulseInt[100]
Definition at line 69 of file hcal.h.
TH1F* hcal::h_PulsePeaks[100]
Definition at line 68 of file hcal.h.
TH1F* hcal::h_saturation_rates
Definition at line 75 of file hcal.h.
TH1F* hcal::h_tres[100]
Definition at line 73 of file hcal.h.
Eventiterator* hcal::it
Definition at line 61 of file hcal.h.
Int_t* hcal::kinds
Definition at line 266 of file hcalUtil.h.
Referenced by getStackTiming().
Int_t hcal::maxStacks
Definition at line 262 of file hcalUtil.h.
int hcal::NCH
Definition at line 57 of file hcal.h.
Referenced by SetCableMap().
int hcal::nevents
Definition at line 55 of file hcal.h.
int hcal::NSAMPLES
Definition at line 58 of file hcal.h.
int hcal::PEDESTAL
Definition at line 59 of file hcal.h.
float hcal::plot_max
Definition at line 79 of file hcal.h.
Referenced by set_plot_max().
float hcal::plot_min
Definition at line 80 of file hcal.h.
Referenced by set_plot_min().
bool hcal::polarity_positive
Definition at line 82 of file hcal.h.
Referenced by set_positive_polarity().
TString hcal::prdfName
Definition at line 56 of file hcal.h.
Referenced by setPrdf().
TGraph* hcal::rate
Definition at line 77 of file hcal.h.
Bool_t hcal::readyForEvent
Definition at line 261 of file hcalUtil.h.
Referenced by clean().
Int_t hcal::rejectEvent
Definition at line 260 of file hcalUtil.h.
Referenced by clean(), getStackTiming(), and update().
int hcal::runnumber
Definition at line 54 of file hcal.h.
std::map<int,float> hcal::saturation_map
Definition at line 84 of file hcal.h.
Double_t hcal::scintLCG
Definition at line 280 of file hcalUtil.h.
Referenced by clean(), hcalTree::hcalTree(), and update().
TH1 * hcal::scintlcg
Definition at line 281 of file hcalUtil.h.
Referenced by displaySummary(), and update().
stack** hcal::stacks
Definition at line 268 of file hcalUtil.h.
Referenced by clean(), hcalHelper::collectRaw(), collectTrPrimitives(), displayRaw(), displaySummary(), hcalHelper::evLoop(), getStackTiming(), hcalHelper::hcalHelper(), setCalibration(), hcalHelper::setRunKind(), and update().
TH1* hcal::totalamp
Definition at line 281 of file hcalUtil.h.
Referenced by displaySummary(), and update().
TH1 * hcal::totale
Definition at line 281 of file hcalUtil.h.
Referenced by displaySummary(), and update().
TH1 * hcal::totallcg
Definition at line 281 of file hcalUtil.h.
Referenced by displaySummary(), and update().
bool hcal::verbosity
Definition at line 83 of file hcal.h.
Referenced by set_verbosity().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype2/HCAL/HighBayCode/hcal.h
analysis/blob/master/Prototype2/hcalLab/hcalUtil.h
analysis/blob/master/Prototype2/HCAL/HighBayCode/hcal.C
analysis/blob/master/Prototype2/hcalLab/hcalHelper.C