Analysis Software: online_distribution/blob/master/newbasic/Cpacket.C File Reference
Cpacket.C File Reference
#include "phenixOnline.h"
#include "packetPublic.h"
#include "packetHdr.h"
#include "Cpacket.h"
#include "CpacketV1.h"
Macros
#define NULLACCESSPFUNC 0
#define NULLPTRACCESSPFUNC 0
#define NULLCHECKPFUNC 0
#define NULLMODIFYPFUNC 0
#define NULLADJUSTPFUNC 0
#define NULLADJUSTDATAPFUNC 0
#define NULLORPFUNC 0
Typedefs
typedef LOGIC_ret CHECKPFUNC (PACKET_ptr)
typedef VALUE_ret ACCESSPFUNC (PACKET_ptr)
typedef VALUE_ret ADJUSTPFUNC (PACKET_ptr, int)
typedef VALUE_ret ORPFUNC (PACKET_ptr, UINT)
typedef PTR_ret PTRACCESSPFUNC (PACKET_ptr)
typedef LOGIC_ret MODIFYPFUNC (PACKET_ptr, UINT)
typedef ACCESSPFUNC * ACCESSPFUNCPTR_arr [NUM_PACKET_VERSIONS]
typedef PTRACCESSPFUNC * PTRACCESSPFUNCPTR_arr [NUM_PACKET_VERSIONS]
typedef CHECKPFUNC * CHECKPFUNCPTR_arr [NUM_PACKET_VERSIONS]
typedef MODIFYPFUNC * MODIFYPFUNCPTR_arr [NUM_PACKET_VERSIONS]
typedef ADJUSTPFUNC * ADJUSTPFUNCPTR_arr [NUM_PACKET_VERSIONS]
typedef ORPFUNC * ORPFUNCPTR_arr [NUM_PACKET_VERSIONS]
Functions
PTR_ret findPacketEnd (PACKET_ptr packet_ptr)
PTR_ret findPacketDataStart (PACKET_ptr packet_ptr)
VALUE_ret extendPacketDataBlock (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
VALUE_ret extendPacketDebugBlock (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
VALUE_ret extendPacketErrorBlock (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
VALUE_ret extendPacketLength (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
LOGIC_ret removePacketPadding (PACKET_ptr packet_ptr)
VALUE_ret makePacketHdr (const PACKET_ptr packet_ptr, UINT maxPacketLength)
VALUE_ret getPacketStatus (PACKET_ptr packet_ptr)
VALUE_ret orPacketStatus (PACKET_ptr packet_ptr, UINT inBits)
VALUE_ret getPacketDataLength (const PACKET_ptr packet_ptr)
VALUE_ret getPacketErrorLength (const PACKET_ptr packet_ptr)
VALUE_ret getPacketDebugLength (const PACKET_ptr packet_ptr)
VALUE_ret getPacketNumErrors (const PACKET_ptr packet_ptr)
VALUE_ret getPacketId (const PACKET_ptr packet_ptr)
VALUE_ret getPacketStructure (const PACKET_ptr packet_ptr)
VALUE_ret getPacketEndianism (const PACKET_ptr packet_ptr)
VALUE_ret getPacketPadding (const PACKET_ptr packet_ptr)
VALUE_ret getPacketDataDescrLength (const PACKET_ptr packet_ptr)
LOGIC_ret setPacketDebugLenth (PACKET_ptr packet_ptr, UINT inLength)
LOGIC_ret setPacketId (PACKET_ptr packet_ptr, UINT inId)
LOGIC_ret setPacketStructure (PACKET_ptr packet_ptr, UINT structure)
LOGIC_ret setPacketEndianism (PACKET_ptr packet_ptr, UINT endianism)
LOGIC_ret setPacketPadding (PACKET_ptr packet_ptr, UINT padding)
LOGIC_ret setPacketStatus (PACKET_ptr packet_ptr, UINT status)
LOGIC_ret setPacketErrorLength (PACKET_ptr packet_ptr, UINT errorLength)
LOGIC_ret setPacketDataDescrLength (PACKET_ptr packet_ptr, UINT descrLength)
PTR_ret findPacketDataEnd (PACKET_ptr packet_ptr)
PTR_ret findPacketDebugStart (PACKET_ptr packet_ptr)
PTR_ret findPacketErrorStart (PACKET_ptr packet_ptr)
PTR_ret findPacketDataDescr (PACKET_ptr packet_ptr)
LOGIC_ret validPacketHdr (PACKET_ptr packet_ptr)
LOGIC_ret emptyPacket (PACKET_ptr packet_ptr)
VALUE_ret adjustPacketDataLength (PACKET_ptr packet_ptr, int addDwords)
VALUE_ret adjustPacketDebugLength (PACKET_ptr packet_ptr, int addLength)
VALUE_ret adjustPacketErrorLength (PACKET_ptr packet_ptr, int addLength)
Variables
ACCESSPFUNCPTR_arr CONSTANT getPacketDataLengthV = {NULLACCESSPFUNC, &getPacketV1DataLength}
ACCESSPFUNCPTR_arr CONSTANT getPacketDebugLengthV = {NULLACCESSPFUNC, &getPacketV1DebugLength}
ACCESSPFUNCPTR_arr CONSTANT getPacketErrorLengthV = {NULLACCESSPFUNC, &getPacketV1ErrorLength}
ACCESSPFUNCPTR_arr CONSTANT getPacketNumErrorsV = {NULLACCESSPFUNC, &getPacketV1NumErrors}
ACCESSPFUNCPTR_arr CONSTANT getPacketEndianismV = {NULLACCESSPFUNC, &getPacketV1Endianism}
ACCESSPFUNCPTR_arr CONSTANT getPacketIdV = {NULLACCESSPFUNC, &getPacketV1Id}
ACCESSPFUNCPTR_arr CONSTANT getPacketPaddingV = {NULLACCESSPFUNC, &getPacketV1Padding}
ACCESSPFUNCPTR_arr CONSTANT getPacketStructureV = {NULLACCESSPFUNC, &getPacketV1Structure}
ACCESSPFUNCPTR_arr CONSTANT getPacketStatusV = {NULLACCESSPFUNC, &getPacketV1Status}
ACCESSPFUNCPTR_arr CONSTANT getPacketDataDescrLengthV = {NULLACCESSPFUNC, &getPacketV1DataDescrLength}
ORPFUNCPTR_arr CONSTANT orPacketStatusV = {NULLORPFUNC, &orPacketV1Status}
ADJUSTPFUNCPTR_arr CONSTANT adjustPacketDataLengthV
ADJUSTPFUNCPTR_arr CONSTANT adjustPacketDebugLengthV
ADJUSTPFUNCPTR_arr CONSTANT adjustPacketErrorLengthV
ORPFUNCPTR_arr CONSTANT makePacketHdrV = {NULLORPFUNC, &makePacketV1Hdr}
MODIFYPFUNCPTR_arr CONSTANT setPacketDebugLengthV = {NULLMODIFYPFUNC, &setPacketV1DebugLength}
MODIFYPFUNCPTR_arr CONSTANT setPacketDataDescrLengthV
MODIFYPFUNCPTR_arr CONSTANT setPacketEndianismV = {NULLMODIFYPFUNC, &setPacketV1Endianism}
MODIFYPFUNCPTR_arr CONSTANT setPacketIdV = {NULLMODIFYPFUNC, &setPacketV1Id}
MODIFYPFUNCPTR_arr CONSTANT setPacketPaddingV = {NULLMODIFYPFUNC, &setPacketV1Padding}
MODIFYPFUNCPTR_arr CONSTANT setPacketErrorLengthV = {NULLMODIFYPFUNC, &setPacketV1ErrorLength}
MODIFYPFUNCPTR_arr CONSTANT setPacketStructureV = {NULLMODIFYPFUNC, &setPacketV1Structure}
MODIFYPFUNCPTR_arr CONSTANT setPacketStatusV = {NULLMODIFYPFUNC, &setPacketV1Status}
PTRACCESSPFUNCPTR_arr CONSTANT findPacketErrorStartV
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDebugStartV
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDataStartV
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDataEndV = {NULLPTRACCESSPFUNC, &findPacketV1DataEnd}
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDataDescrV
CHECKPFUNCPTR_arr CONSTANT validPacketHdrV = {NULLCHECKPFUNC, &validPacketV1Hdr}
CHECKPFUNCPTR_arr CONSTANT emptyPacketV = {NULLCHECKPFUNC, &emptyPacketV1}
Macro Definition Documentation
#define NULLACCESSPFUNC 0
Definition at line 251 of file Cpacket.C.
#define NULLADJUSTDATAPFUNC 0
Definition at line 256 of file Cpacket.C.
#define NULLADJUSTPFUNC 0
Definition at line 255 of file Cpacket.C.
#define NULLCHECKPFUNC 0
Definition at line 253 of file Cpacket.C.
#define NULLMODIFYPFUNC 0
Definition at line 254 of file Cpacket.C.
#define NULLORPFUNC 0
Definition at line 257 of file Cpacket.C.
#define NULLPTRACCESSPFUNC 0
Definition at line 252 of file Cpacket.C.
Typedef Documentation
typedef VALUE_ret ACCESSPFUNC(PACKET_ptr)
Definition at line 225 of file Cpacket.C.
typedef ACCESSPFUNC* ACCESSPFUNCPTR_arr[NUM_PACKET_VERSIONS]
Definition at line 232 of file Cpacket.C.
typedef VALUE_ret ADJUSTPFUNC(PACKET_ptr, int)
Definition at line 226 of file Cpacket.C.
typedef ADJUSTPFUNC* ADJUSTPFUNCPTR_arr[NUM_PACKET_VERSIONS]
Definition at line 236 of file Cpacket.C.
typedef LOGIC_ret CHECKPFUNC(PACKET_ptr)
Definition at line 224 of file Cpacket.C.
typedef CHECKPFUNC* CHECKPFUNCPTR_arr[NUM_PACKET_VERSIONS]
Definition at line 234 of file Cpacket.C.
typedef LOGIC_ret MODIFYPFUNC(PACKET_ptr, UINT)
Definition at line 229 of file Cpacket.C.
typedef MODIFYPFUNC* MODIFYPFUNCPTR_arr[NUM_PACKET_VERSIONS]
Definition at line 235 of file Cpacket.C.
typedef VALUE_ret ORPFUNC(PACKET_ptr, UINT)
Definition at line 227 of file Cpacket.C.
typedef ORPFUNC* ORPFUNCPTR_arr[NUM_PACKET_VERSIONS]
Definition at line 237 of file Cpacket.C.
typedef PTR_ret PTRACCESSPFUNC(PACKET_ptr)
Definition at line 228 of file Cpacket.C.
typedef PTRACCESSPFUNC* PTRACCESSPFUNCPTR_arr[NUM_PACKET_VERSIONS]
Definition at line 233 of file Cpacket.C.
Function Documentation
VALUE_ret adjustPacketDataLength (PACKET_ptr packet_ptr, int addDwords)
Definition at line 563 of file Cpacket.C.
References adjustPacketDataLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by extendPacketDataBlock().
VALUE_ret adjustPacketDebugLength (PACKET_ptr packet_ptr, int addLength)
Definition at line 572 of file Cpacket.C.
References adjustPacketDebugLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by extendPacketDebugBlock().
VALUE_ret adjustPacketErrorLength (PACKET_ptr packet_ptr, int addLength)
Definition at line 581 of file Cpacket.C.
References adjustPacketErrorLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by extendPacketErrorBlock().
LOGIC_ret emptyPacket (PACKET_ptr packet_ptr)
Definition at line 554 of file Cpacket.C.
References emptyPacketV, getPacketHdrVersion(), logicFailure, and valueFailure.
Referenced by startUnstructDataWrite(), and storePacketHits().
VALUE_ret extendPacketDataBlock (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
Definition at line 67 of file Cpacket.C.
References adjustPacketDataLength(), extendPacketLength(), and valueFailure.
Referenced by startUnstructDataWrite(), and storePacketHits().
VALUE_ret extendPacketDebugBlock (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
Definition at line 90 of file Cpacket.C.
References adjustPacketDebugLength(), extendPacketLength(), and valueFailure.
Referenced by reservePacketDebugData().
VALUE_ret extendPacketErrorBlock (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
Definition at line 113 of file Cpacket.C.
References adjustPacketErrorLength(), extendPacketLength(), and valueFailure.
Referenced by appendPacketError().
VALUE_ret extendPacketLength (const PACKET_ptr packet_ptr, UINT maxPacketLength, int addDwords)
Definition at line 136 of file Cpacket.C.
References FORMAT_ERR_BUFFER_OVERFLOW, getPacketLength(), packetQuantum, removePacketPadding(), setPacketError(), setPacketLength(), setPacketPadding(), and valueFailure.
Referenced by extendPacketDataBlock(), extendPacketDebugBlock(), and extendPacketErrorBlock().
PTR_ret findPacketDataDescr (PACKET_ptr packet_ptr)
Definition at line 535 of file Cpacket.C.
References findPacketDataDescrV, getPacketHdrVersion(), ptrFailure, and valueFailure.
Referenced by getUnstructPacketDataPadding(), getUnstructPacketHitFormat(), getUnstructPacketWordSize(), makeUnstructPacketDataDescr(), setUnstructPacketDataPadding(), setUnstructPacketHitFormat(), and setUnstructPacketWordSize().
PTR_ret findPacketDataEnd (PACKET_ptr packet_ptr)
Definition at line 508 of file Cpacket.C.
References findPacketDataEndV, getPacketHdrVersion(), ptrFailure, and valueFailure.
PTR_ret findPacketDataStart (PACKET_ptr packet_ptr)
Definition at line 53 of file Cpacket.C.
References getPacketDataDescrLength(), getPacketHdrLength(), ptrFailure, and validPacketHdr().
Referenced by Packet_fvtx_dcm0::calculate_parity(), Packet_id2evt::decode(), Packet_id4evt::decode(), Packet_iddigitizerv2::decode(), Packet_gl1psum::decode(), Packet_gl1_evclocks::decode(), Packet_idcstr::decode(), Packet_cdevir::decode(), Packet_idcdevdescr::decode(), Packet_starscaler::decode(), Packet_cdevwcm::decode(), Packet_cdevmadch::decode(), Packet_cdevbpm::decode(), Packet_cdevdvm::decode(), Packet_cdevpoltarget::decode(), Packet_hbd_fpgashort::decode(), Packet_hbd_fpga::decode(), Packet_cdevbuckets::decode(), Packet_cdevring::decode(), Packet_fvtx_dcm0::decode(), Packet_cdevringnopol::decode(), Packet_gl1p::decode(), Packet_id4scaler::decode(), Packet_cdevpolarimeter::decode(), Packet_gl1::decode(), Packet_fvtx_dcm0::decode_misc(), Packet_gl1p::demangle(), Packet_gl1::demangle(), Packet_gl1_evclocks::dump(), Packet_idcdevdescr::dump(), Packet_gl1p::dump(), Packet_id4scaler::dump(), Packet_gl1::dump(), dumpPacket(), fetchPacketHits(), Packet_w1::gdump(), Packet_w2::gdump(), Packet_w4::gdump(), Packet_gl1_evclocks::iValue(), Packet_id4scaler::iValue(), Packet_id4scaler::lValue(), Packet_A::standardIntArray(), startUnstructDataWrite(), and storePacketHits().
PTR_ret findPacketDebugStart (PACKET_ptr packet_ptr)
Definition at line 517 of file Cpacket.C.
References findPacketDebugStartV, getPacketHdrVersion(), ptrFailure, and valueFailure.
Referenced by Packet_A::dumpDebugBlock(), and reservePacketDebugData().
PTR_ret findPacketEnd (PACKET_ptr packet_ptr)
Definition at line 35 of file Cpacket.C.
References getPacketLength(), logicFailure, ptrFailure, setPacketError(), setPacketSuccess(), validPacketHdr(), and valueFailure.
Referenced by findNextFramePacket(), finishUnstructDataWrite(), makeEmptyPacket(), and makeUnstructPacket().
PTR_ret findPacketErrorStart (PACKET_ptr packet_ptr)
Definition at line 526 of file Cpacket.C.
References findPacketErrorStartV, getPacketHdrVersion(), ptrFailure, and valueFailure.
Referenced by appendPacketError(), and Packet_A::dumpErrorBlock().
VALUE_ret getPacketDataDescrLength (const PACKET_ptr packet_ptr)
Definition at line 412 of file Cpacket.C.
References getPacketDataDescrLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by findPacketDataStart(), and Packet_A::fullIdentify().
VALUE_ret getPacketDataLength (const PACKET_ptr packet_ptr)
Definition at line 339 of file Cpacket.C.
References getPacketDataLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by Packet_A::getDataLength(), and getUnstructPacketDataLengthBytes().
VALUE_ret getPacketDebugLength (const PACKET_ptr packet_ptr)
Definition at line 359 of file Cpacket.C.
References getPacketDebugLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by dumpPacket(), Packet_A::fullIdentify(), Packet_A::getDebugLength(), and getPacketV1DataLength().
VALUE_ret getPacketEndianism (const PACKET_ptr packet_ptr)
Definition at line 394 of file Cpacket.C.
References getPacketEndianismV, getPacketHdrVersion(), and valueFailure.
Referenced by dumpPacket(), and Packet_A::fullIdentify().
VALUE_ret getPacketErrorLength (const PACKET_ptr packet_ptr)
Definition at line 349 of file Cpacket.C.
References getPacketErrorLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by appendPacketError(), dumpPacket(), Packet_A::fullIdentify(), Packet_A::getErrorLength(), getPacketV1DataLength(), and reservePacketDebugData().
VALUE_ret getPacketId (const PACKET_ptr packet_ptr)
Definition at line 377 of file Cpacket.C.
References getPacketHdrVersion(), getPacketIdV, and valueFailure.
Referenced by A_Event::createMap(), dumpPacket(), findFramePacketId(), findNextFramePacketId(), Packet_A::fullIdentify(), and Packet_A::getIdentifier().
VALUE_ret getPacketNumErrors (const PACKET_ptr packet_ptr)
Definition at line 368 of file Cpacket.C.
References getPacketHdrVersion(), getPacketNumErrorsV, and valueFailure.
VALUE_ret getPacketPadding (const PACKET_ptr packet_ptr)
Definition at line 403 of file Cpacket.C.
References getPacketHdrVersion(), getPacketPaddingV, and valueFailure.
Referenced by dumpPacket(), Packet_A::fullIdentify(), getPacketV1DataLength(), Packet_A::getPadding(), and removePacketPadding().
VALUE_ret getPacketStatus (PACKET_ptr packet_ptr)
Definition at line 321 of file Cpacket.C.
References getPacketHdrVersion(), getPacketStatusV, and valueFailure.
Referenced by dumpPacket(), and Packet_A::fullIdentify().
VALUE_ret getPacketStructure (const PACKET_ptr packet_ptr)
Definition at line 386 of file Cpacket.C.
References getPacketHdrVersion(), getPacketStructureV, and valueFailure.
Referenced by X_Event::change_hf(), dumpPacket(), fetchPacketHits(), A_Event::getPacketList(), getPacketV1DataLength(), Packet_A::getStructure(), A_Event::makePacket(), startUnstructDataWrite(), and storePacketHits().
VALUE_ret makePacketHdr (const PACKET_ptr packet_ptr, UINT maxPacketLength)
Definition at line 311 of file Cpacket.C.
References currentPacketHdrVersion, makePacketHdrV, and valueFailure.
Referenced by makeEmptyPacket(), and makeUnstructPacket().
VALUE_ret orPacketStatus (PACKET_ptr packet_ptr, UINT inBits)
Definition at line 330 of file Cpacket.C.
References getPacketHdrVersion(), orPacketStatusV, and valueFailure.
LOGIC_ret removePacketPadding (PACKET_ptr packet_ptr)
Definition at line 183 of file Cpacket.C.
References FORMAT_ERR_HDR_INCONSISTENCY, getPacketLength(), getPacketPadding(), logicFailure, logicSuccess, packetV1HdrLength, setPacketError(), setPacketLength(), and setPacketPadding().
Referenced by extendPacketLength().
LOGIC_ret setPacketDataDescrLength (PACKET_ptr packet_ptr, UINT descrLength)
Definition at line 499 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketDataDescrLengthV, and valueFailure.
Referenced by makeUnstructPacketDataDescr().
LOGIC_ret setPacketDebugLenth (PACKET_ptr packet_ptr, UINT inLength)
Definition at line 422 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketDebugLengthV, and valueFailure.
LOGIC_ret setPacketEndianism (PACKET_ptr packet_ptr, UINT endianism)
Definition at line 463 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketEndianismV, and valueFailure.
Referenced by makePacketV1Hdr().
LOGIC_ret setPacketErrorLength (PACKET_ptr packet_ptr, UINT errorLength)
Definition at line 490 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketErrorLengthV, and valueFailure.
LOGIC_ret setPacketId (PACKET_ptr packet_ptr, UINT inId)
Definition at line 445 of file Cpacket.C.
References getPacketHdrVersion(), setPacketIdV, and valueFailure.
Referenced by X_Event::change_id(), makeEmptyPacket(), and makeUnstructPacket().
LOGIC_ret setPacketPadding (PACKET_ptr packet_ptr, UINT padding)
Definition at line 472 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketPaddingV, and valueFailure.
Referenced by extendPacketLength(), and removePacketPadding().
LOGIC_ret setPacketStatus (PACKET_ptr packet_ptr, UINT status)
Definition at line 481 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketStatusV, and valueFailure.
LOGIC_ret setPacketStructure (PACKET_ptr packet_ptr, UINT structure)
Definition at line 454 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketStructureV, and valueFailure.
Referenced by makeUnstructPacket(), and setPacketUnstructured().
LOGIC_ret validPacketHdr (PACKET_ptr packet_ptr)
Definition at line 545 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, NUM_PACKET_VERSIONS, and validPacketHdrV.
Referenced by dumpPacket(), fetchPacketHits(), findFramePacketIndex(), findPacketDataStart(), findPacketEnd(), isLastFramePacket(), and storePacketHits().
Variable Documentation
ADJUSTPFUNCPTR_arr CONSTANT adjustPacketDataLengthV
Initial value:
= {NULLADJUSTPFUNC,
                                                       &adjustPacketV1DataLength}
Definition at line 273 of file Cpacket.C.
Referenced by adjustPacketDataLength().
ADJUSTPFUNCPTR_arr CONSTANT adjustPacketDebugLengthV
Initial value:
= {NULLADJUSTPFUNC,
                                                        &adjustPacketV1DebugLength}
Definition at line 275 of file Cpacket.C.
Referenced by adjustPacketDebugLength().
ADJUSTPFUNCPTR_arr CONSTANT adjustPacketErrorLengthV
Initial value:
= {NULLADJUSTPFUNC,
                                                        &adjustPacketV1ErrorLength}
Definition at line 277 of file Cpacket.C.
Referenced by adjustPacketErrorLength().
CHECKPFUNCPTR_arr CONSTANT emptyPacketV = {NULLCHECKPFUNC, &emptyPacketV1}
Definition at line 304 of file Cpacket.C.
Referenced by emptyPacket().
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDataDescrV
Initial value:
= {NULLPTRACCESSPFUNC,
                                                       &findPacketV1DataDescr}
Definition at line 300 of file Cpacket.C.
Referenced by findPacketDataDescr().
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDataEndV = {NULLPTRACCESSPFUNC, &findPacketV1DataEnd}
Definition at line 299 of file Cpacket.C.
Referenced by findPacketDataEnd().
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDataStartV
Initial value:
= {NULLPTRACCESSPFUNC,
                                                       &findPacketV1DataStart}
Definition at line 297 of file Cpacket.C.
PTRACCESSPFUNCPTR_arr CONSTANT findPacketDebugStartV
Initial value:
= {NULLPTRACCESSPFUNC,
                                                        &findPacketV1DebugStart}
Definition at line 295 of file Cpacket.C.
Referenced by findPacketDebugStart().
PTRACCESSPFUNCPTR_arr CONSTANT findPacketErrorStartV
Initial value:
= {NULLPTRACCESSPFUNC,
                                                        &findPacketV1ErrorStart}
Definition at line 293 of file Cpacket.C.
Referenced by findPacketErrorStart().
ACCESSPFUNCPTR_arr CONSTANT getPacketDataDescrLengthV = {NULLACCESSPFUNC, &getPacketV1DataDescrLength}
Definition at line 270 of file Cpacket.C.
Referenced by getPacketDataDescrLength().
ACCESSPFUNCPTR_arr CONSTANT getPacketDataLengthV = {NULLACCESSPFUNC, &getPacketV1DataLength}
Definition at line 261 of file Cpacket.C.
Referenced by getPacketDataLength().
ACCESSPFUNCPTR_arr CONSTANT getPacketDebugLengthV = {NULLACCESSPFUNC, &getPacketV1DebugLength}
Definition at line 262 of file Cpacket.C.
Referenced by getPacketDebugLength().
ACCESSPFUNCPTR_arr CONSTANT getPacketEndianismV = {NULLACCESSPFUNC, &getPacketV1Endianism}
Definition at line 265 of file Cpacket.C.
Referenced by getPacketEndianism().
ACCESSPFUNCPTR_arr CONSTANT getPacketErrorLengthV = {NULLACCESSPFUNC, &getPacketV1ErrorLength}
Definition at line 263 of file Cpacket.C.
Referenced by getPacketErrorLength().
ACCESSPFUNCPTR_arr CONSTANT getPacketIdV = {NULLACCESSPFUNC, &getPacketV1Id}
Definition at line 266 of file Cpacket.C.
Referenced by getPacketId().
ACCESSPFUNCPTR_arr CONSTANT getPacketNumErrorsV = {NULLACCESSPFUNC, &getPacketV1NumErrors}
Definition at line 264 of file Cpacket.C.
Referenced by getPacketNumErrors().
ACCESSPFUNCPTR_arr CONSTANT getPacketPaddingV = {NULLACCESSPFUNC, &getPacketV1Padding}
Definition at line 267 of file Cpacket.C.
Referenced by getPacketPadding().
ACCESSPFUNCPTR_arr CONSTANT getPacketStatusV = {NULLACCESSPFUNC, &getPacketV1Status}
Definition at line 269 of file Cpacket.C.
Referenced by getPacketStatus().
ACCESSPFUNCPTR_arr CONSTANT getPacketStructureV = {NULLACCESSPFUNC, &getPacketV1Structure}
Definition at line 268 of file Cpacket.C.
Referenced by getPacketStructure().
ORPFUNCPTR_arr CONSTANT makePacketHdrV = {NULLORPFUNC, &makePacketV1Hdr}
Definition at line 280 of file Cpacket.C.
Referenced by makePacketHdr().
ORPFUNCPTR_arr CONSTANT orPacketStatusV = {NULLORPFUNC, &orPacketV1Status}
Definition at line 272 of file Cpacket.C.
Referenced by orPacketStatus().
MODIFYPFUNCPTR_arr CONSTANT setPacketDataDescrLengthV
Initial value:
= {NULLMODIFYPFUNC,
                                                         &setPacketV1DataDescrLength}
Definition at line 283 of file Cpacket.C.
Referenced by setPacketDataDescrLength().
MODIFYPFUNCPTR_arr CONSTANT setPacketDebugLengthV = {NULLMODIFYPFUNC, &setPacketV1DebugLength}
Definition at line 282 of file Cpacket.C.
Referenced by setPacketDebugLenth().
MODIFYPFUNCPTR_arr CONSTANT setPacketEndianismV = {NULLMODIFYPFUNC, &setPacketV1Endianism}
Definition at line 286 of file Cpacket.C.
Referenced by setPacketEndianism().
MODIFYPFUNCPTR_arr CONSTANT setPacketErrorLengthV = {NULLMODIFYPFUNC, &setPacketV1ErrorLength}
Definition at line 289 of file Cpacket.C.
Referenced by setPacketErrorLength().
MODIFYPFUNCPTR_arr CONSTANT setPacketIdV = {NULLMODIFYPFUNC, &setPacketV1Id}
Definition at line 287 of file Cpacket.C.
Referenced by setPacketId().
MODIFYPFUNCPTR_arr CONSTANT setPacketPaddingV = {NULLMODIFYPFUNC, &setPacketV1Padding}
Definition at line 288 of file Cpacket.C.
Referenced by setPacketPadding().
MODIFYPFUNCPTR_arr CONSTANT setPacketStatusV = {NULLMODIFYPFUNC, &setPacketV1Status}
Definition at line 291 of file Cpacket.C.
Referenced by setPacketStatus().
MODIFYPFUNCPTR_arr CONSTANT setPacketStructureV = {NULLMODIFYPFUNC, &setPacketV1Structure}
Definition at line 290 of file Cpacket.C.
Referenced by setPacketStructure().
CHECKPFUNCPTR_arr CONSTANT validPacketHdrV = {NULLCHECKPFUNC, &validPacketV1Hdr}
Definition at line 303 of file Cpacket.C.
Referenced by validPacketHdr().