Analysis Software: TowerTiming Class Reference
TowerTiming Class Reference
#include <analysis/blob/master/AntiSigma/src/TowerTiming.h>
Public Member Functions
TowerTiming (const std::string &name="TowerTiming", const std::string &filename="TowerTiming.root")
constructor
virtual ~TowerTiming ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
void AddNode (const std::string &name, const int detid=0)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
int nblocks
Fun4AllHistoManager * hm
std::vector< TH1 * > nhits
std::vector< TH1 * > eloss
std::string _filename
std::set< std::string > _node_postfix
std::map< std::string, int > _detid
TNtuple * ntuptwr
TNtuple * ntupe
TFile * outfile
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file TowerTiming.h.
Constructor & Destructor Documentation
TowerTiming::TowerTiming (const std::string & name = "TowerTiming", const std::string & filename = "TowerTiming.root")
constructor
Definition at line 24 of file TowerTiming.cc.
TowerTiming::~TowerTiming () virtual
destructor
Definition at line 33 of file TowerTiming.cc.
References hm.
Member Function Documentation
void TowerTiming::AddNode (const std::string & name, const int detid = 0)
Definition at line 157 of file TowerTiming.cc.
References _detid, _node_postfix, and name.
int TowerTiming::End (PHCompositeNode * topNode) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 143 of file TowerTiming.cc.
References _filename, Fun4AllHistoManager::dumpHistos(), hm, ntupe, ntuptwr, and outfile.
int TowerTiming::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 41 of file TowerTiming.cc.
References _filename, hm, Fun4AllBase::Name(), ntupe, ntuptwr, and outfile.
int TowerTiming::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 52 of file TowerTiming.cc.
References energy, PHG4Particle::get_e(), RawTowerGeomContainer::get_etacenter(), RawTowerGeomContainer::get_phicenter(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTowers(), j, ntupe, ntuptwr, and phi.
Member Data Documentation
std::map<std::string, int> TowerTiming::_detid protected
Definition at line 47 of file TowerTiming.h.
Referenced by AddNode().
std::string TowerTiming::_filename protected
Definition at line 45 of file TowerTiming.h.
Referenced by End(), and Init().
std::set<std::string> TowerTiming::_node_postfix protected
Definition at line 46 of file TowerTiming.h.
Referenced by AddNode().
std::vector<TH1 *> TowerTiming::eloss protected
Definition at line 43 of file TowerTiming.h.
Fun4AllHistoManager* TowerTiming::hm protected
Definition at line 41 of file TowerTiming.h.
Referenced by End(), Init(), and ~TowerTiming().
int TowerTiming::nblocks protected
Definition at line 40 of file TowerTiming.h.
std::vector<TH1 *> TowerTiming::nhits protected
Definition at line 42 of file TowerTiming.h.
TNtuple* TowerTiming::ntupe protected
Definition at line 49 of file TowerTiming.h.
Referenced by End(), Init(), and process_event().
TNtuple* TowerTiming::ntuptwr protected
Definition at line 48 of file TowerTiming.h.
Referenced by End(), Init(), and process_event().
TFile* TowerTiming::outfile protected
Definition at line 50 of file TowerTiming.h.
Referenced by End(), and Init().
The documentation for this class was generated from the following files:
analysis/blob/master/AntiSigma/src/TowerTiming.h
analysis/blob/master/AntiSigma/src/TowerTiming.cc