Analysis Software: HiMain1 Class Reference
HiMain1 Class Reference
Class definition for HiMain1, which is used to modify the Hijing HIMAIN1 common.
#include <coresoftware/blob/master/generators/sHijing/HiMain1.h>
Classes
struct HIMAIN1
Public Member Functions
HiMain1 ()
~HiMain1 ()
int & natt (void)
float & eatt (void)
int & jatt (void)
int & nt (void)
int & np (void)
int & n0 (void)
int & n01 (void)
int & n10 (void)
int & n11 (void)
int & ierrstat (void)
void init (void)
Static Private Attributes
static HIMAIN1 * _himain1 =0
Friends
struct HIMAIN1
Detailed Description
Class definition for HiMain1, which is used to modify the Hijing HIMAIN1 common.
Definition at line 13 of file HiMain1.h.
Constructor & Destructor Documentation
HiMain1::HiMain1 () inline
Definition at line 75 of file HiMain1.h.
HiMain1::~HiMain1 () inline
Definition at line 80 of file HiMain1.h.
Member Function Documentation
float & HiMain1::eatt (void) inline
Definition at line 91 of file HiMain1.h.
References _himain1, HiMain1::HIMAIN1::eatt, and init().
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), and hijing().
int & HiMain1::ierrstat (void) inline
Definition at line 147 of file HiMain1.h.
References _himain1, HiMain1::HIMAIN1::ierrstat, and init().
Referenced by hijing(), and main().
void HiMain1::init (void) inline
Definition at line 70 of file HiMain1.h.
References _himain1, and himain1_address_().
Referenced by eatt(), ierrstat(), jatt(), n0(), n01(), n10(), n11(), natt(), np(), and nt().
int & HiMain1::jatt (void) inline
Definition at line 98 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::jatt.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), and hijing().
int & HiMain1::n0 (void) inline
Definition at line 119 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::n0.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), calcta(), calcxsection(), fillEvent(), getltimemax(), getmdmin(), getnatmdmin(), getneff(), getneffmax(), getscatterer(), gettemp(), gettempmax(), hijing(), medderiv(), medinit(), mednextevt(), npart(), nthick(), and pyresd().
int & HiMain1::n01 (void) inline
Definition at line 126 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::n01.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
int & HiMain1::n10 (void) inline
Definition at line 133 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::n10.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
int & HiMain1::n11 (void) inline
Definition at line 140 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::n11.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
int & HiMain1::natt (void) inline
Definition at line 84 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::natt.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
int & HiMain1::np (void) inline
Definition at line 112 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::np.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), hijing(), init(), jewel(), lucell(), luclus(), ludecy(), lufowo(), lujmas(), luprep(), lusphe(), lustrf(), lutabu(), luthru(), pycell(), pyclus(), pydecy(), pyfowo(), pyhiresd(), pyjmas(), pyprep(), pyresd(), pysphe(), pystrf(), pytabu(), and pythru().
int & HiMain1::nt (void) inline
Definition at line 105 of file HiMain1.h.
References _himain1, init(), and HiMain1::HIMAIN1::nt.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
Friends And Related Function Documentation
friend struct HIMAIN1 friend
Definition at line 39 of file HiMain1.h.
Member Data Documentation
HiMain1::HIMAIN1 * HiMain1::_himain1 =0 static private
Definition at line 63 of file HiMain1.h.
Referenced by eatt(), ierrstat(), init(), jatt(), n0(), n01(), n10(), n11(), natt(), np(), and nt().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HiMain1.h