Analysis Software: RawTowerv1 Class Reference
RawTowerv1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerv1.h>
Public Member Functions
RawTowerv1 ()
RawTowerv1 (const RawTower &tower)
RawTowerv1 (RawTowerDefs::keytype id)
RawTowerv1 (const unsigned int ieta, const unsigned int iphi)
RawTowerv1 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual ~RawTowerv1 ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
void set_id (RawTowerDefs::keytype id)
RawTowerDefs::keytype get_id () const
int get_bineta () const
int get_binphi () const
double get_energy () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e)
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t)
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
bool empty_g4cells () const
size_t size_g4cells () const
RawTower::CellConstRange get_g4cells () const
RawTower::CellIterator find_g4cell (CellKeyType id)
RawTower::CellConstIterator find_g4cell (CellKeyType id) const
void add_ecell (const CellKeyType g4cellid, const float ecell)
void clear_g4cells ()
bool empty_g4showers () const
size_t size_g4showers () const
RawTower::ShowerConstRange get_g4showers () const
RawTower::ShowerIterator find_g4shower (int id)
RawTower::ShowerConstIterator find_g4shower (int id) const
void add_eshower (const int g4showerid, const float eshower)
void clear_g4showers ()
Public Member Functions inherited from RawTower
virtual ~RawTower ()
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual int get_column () const
virtual int get_row () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid
double energy
float time
CellMap ecells
ShowerMap eshowers
Additional Inherited Members
Public Types inherited from RawTower
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Protected Member Functions inherited from RawTower
RawTower ()
Detailed Description
Definition at line 13 of file RawTowerv1.h.
Constructor & Destructor Documentation
RawTowerv1::RawTowerv1 ()
Definition at line 8 of file RawTowerv1.cc.
RawTowerv1::RawTowerv1 (const RawTower & tower)
Definition at line 16 of file RawTowerv1.cc.
References add_ecell(), add_eshower(), energy, RawTower::get_energy(), RawTower::get_g4cells(), RawTower::get_g4showers(), RawTower::get_id(), RawTower::get_time(), time, and towerid.
RawTowerv1::RawTowerv1 (RawTowerDefs::keytype id)
Definition at line 39 of file RawTowerv1.cc.
RawTowerv1::RawTowerv1 (const unsigned int ieta, const unsigned int iphi)
Definition at line 46 of file RawTowerv1.cc.
References RawTowerDefs::encode_towerid(), RawTowerDefs::NONE, and towerid.
RawTowerv1::RawTowerv1 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 54 of file RawTowerv1.cc.
References RawTowerDefs::encode_towerid(), and towerid.
virtual RawTowerv1::~RawTowerv1 () inline virtual
Definition at line 22 of file RawTowerv1.h.
Member Function Documentation
void RawTowerv1::add_ecell (const CellKeyType g4cellid, const float ecell) virtual
Reimplemented from RawTower.
Definition at line 82 of file RawTowerv1.cc.
References ecells.
Referenced by RawTowerv1().
void RawTowerv1::add_eshower (const int g4showerid, const float eshower) virtual
Reimplemented from RawTower.
Definition at line 95 of file RawTowerv1.cc.
References eshowers.
Referenced by RawTowerv1().
void RawTowerv1::clear_g4cells () inline virtual
Reimplemented from RawTower.
Definition at line 49 of file RawTowerv1.h.
References ecells.
void RawTowerv1::clear_g4showers () inline virtual
Reimplemented from RawTower.
Definition at line 62 of file RawTowerv1.h.
References eshowers.
bool RawTowerv1::empty_g4cells () const inline virtual
Reimplemented from RawTower.
Definition at line 39 of file RawTowerv1.h.
References ecells.
bool RawTowerv1::empty_g4showers () const inline virtual
Reimplemented from RawTower.
Definition at line 53 of file RawTowerv1.h.
References eshowers.
RawTower::CellIterator RawTowerv1::find_g4cell (CellKeyType id) inline virtual
Reimplemented from RawTower.
Definition at line 45 of file RawTowerv1.h.
References ecells.
RawTower::CellConstIterator RawTowerv1::find_g4cell (CellKeyType id) const inline virtual
Reimplemented from RawTower.
Definition at line 46 of file RawTowerv1.h.
References ecells.
RawTower::ShowerIterator RawTowerv1::find_g4shower (int id) inline virtual
Reimplemented from RawTower.
Definition at line 59 of file RawTowerv1.h.
References eshowers.
RawTower::ShowerConstIterator RawTowerv1::find_g4shower (int id) const inline virtual
Reimplemented from RawTower.
Definition at line 60 of file RawTowerv1.h.
References eshowers.
int RawTowerv1::get_bineta () const inline virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTowerv1.h.
References RawTowerDefs::decode_index1(), and towerid.
Referenced by identify().
int RawTowerv1::get_binphi () const inline virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTowerv1.h.
References RawTowerDefs::decode_index2(), and towerid.
Referenced by identify().
double RawTowerv1::get_energy () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 32 of file RawTowerv1.h.
References energy.
Referenced by identify(), isValid(), and PHG4DSTReader::process_event().
RawTower::CellConstRange RawTowerv1::get_g4cells () const inline virtual
Reimplemented from RawTower.
Definition at line 41 of file RawTowerv1.h.
References ecells.
RawTower::ShowerConstRange RawTowerv1::get_g4showers () const inline virtual
Reimplemented from RawTower.
Definition at line 55 of file RawTowerv1.h.
References eshowers.
RawTowerDefs::keytype RawTowerv1::get_id () const inline virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTowerv1.h.
References towerid.
float RawTowerv1::get_time () const inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 34 of file RawTowerv1.h.
References time.
void RawTowerv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
Definition at line 76 of file RawTowerv1.cc.
References get_bineta(), get_binphi(), and get_energy().
int RawTowerv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 71 of file RawTowerv1.cc.
References get_energy().
void RawTowerv1::Reset () virtual
Clear Event.
Reimplemented from RawTower.
Definition at line 63 of file RawTowerv1.cc.
References ecells, energy, eshowers, and time.
void RawTowerv1::set_energy (const double) inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 33 of file RawTowerv1.h.
References energy.
void RawTowerv1::set_id (RawTowerDefs::keytype id) inline virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTowerv1.h.
References towerid.
void RawTowerv1::set_time (const float) inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 35 of file RawTowerv1.h.
References t, and time.
size_t RawTowerv1::size_g4cells () const inline virtual
Reimplemented from RawTower.
Definition at line 40 of file RawTowerv1.h.
References ecells.
size_t RawTowerv1::size_g4showers () const inline virtual
Reimplemented from RawTower.
Definition at line 54 of file RawTowerv1.h.
References eshowers.
Member Data Documentation
CellMap RawTowerv1::ecells protected
Definition at line 74 of file RawTowerv1.h.
Referenced by add_ecell(), clear_g4cells(), empty_g4cells(), find_g4cell(), get_g4cells(), Reset(), and size_g4cells().
double RawTowerv1::energy protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 69 of file RawTowerv1.h.
Referenced by get_energy(), RawTowerv1(), Reset(), and set_energy().
ShowerMap RawTowerv1::eshowers protected
Definition at line 75 of file RawTowerv1.h.
Referenced by add_eshower(), clear_g4showers(), empty_g4showers(), find_g4shower(), get_g4showers(), Reset(), and size_g4showers().
float RawTowerv1::time protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 72 of file RawTowerv1.h.
Referenced by get_time(), RawTowerv1(), Reset(), and set_time().
RawTowerDefs::keytype RawTowerv1::towerid protected
Definition at line 65 of file RawTowerv1.h.
Referenced by get_bineta(), get_binphi(), get_id(), RawTowerv1(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerv1.cc