Analysis Software: online_distribution/blob/master/newbasic/dataBlock.h File Reference
dataBlock.h File Reference
#include "phenixOnline.h"
#include "packetPublic.h"
#include "Cpacket.h"
#include "formatError.h"
Macros
#define UNSTRUCT_DATA_PADDING_OFFSET_OF_DWORD 0
#define UNSTRUCT_DATA_PADDING_OFFSET_IN_DWORD 24
#define UNSTRUCT_DATA_PADDING_NUM_BITS 8
#define UNSTRUCT_DATA_PADDING_MASK 0xff000000
#define UNSTRUCT_WORD_SIZE_OFFSET_OF_DWORD 0
#define UNSTRUCT_WORD_SIZE_OFFSET_IN_DWORD 16
#define UNSTRUCT_WORD_SIZE_NUM_BITS 8
#define UNSTRUCT_WORD_SIZE_MASK 0x00ff0000
#define UNSTRUCT_HIT_FORMAT_OFFSET_OF_DWORD 0
#define UNSTRUCT_HIT_FORMAT_OFFSET_IN_DWORD 0
#define UNSTRUCT_HIT_FORMAT_NUM_BITS 16
#define UNSTRUCT_HIT_FORMAT_MASK 0x0000ffff
Functions
INLINE_P LOGIC_ret makeUnstructPacketDataDescr (PACKET_ptr, UINT, UINT)
INLINE_P VALUE_ret getUnstructPacketWordSize (PACKET_ptr)
INLINE_P VALUE_ret getUnstructPacketDataPadding (PACKET_ptr)
INLINE_P VALUE_ret getUnstructPacketHitFormat (PACKET_ptr)
INLINE_P LOGIC_ret setUnstructPacketWordSize (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setUnstructPacketDataPadding (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setUnstructPacketHitFormat (PACKET_ptr, UINT)
VALUE_ret getUnstructPacketDataLengthBytes (PACKET_ptr)
VALUE_ret getUnstructPacketDataLengthWords (PACKET_ptr)
VALUE_ret extendUnstructPacketDataBlock (PACKET_ptr, UINT)
INLINE_P LOGIC_ret makeUnstructDataDescr (PHDWORD *, UINT, UINT)
INLINE_P LOGIC_ret setUnstructDescrWordSize (PHDWORD *, UINT)
INLINE_P LOGIC_ret setUnstructDescrDataPadding (PHDWORD *, UINT)
INLINE_P LOGIC_ret setUnstructDescrHitFormat (PHDWORD *, UINT)
INLINE_P VALUE_ret getUnstructDescrWordSize (PHDWORD *)
INLINE_P VALUE_ret getUnstructDescrDataPadding (PHDWORD *)
INLINE_P VALUE_ret getUnstructDescrHitFormat (PHDWORD *)
Variables
CONSTANT PHDWORD UnstructDataDescrLength = 1
Macro Definition Documentation
#define UNSTRUCT_DATA_PADDING_MASK 0xff000000
Definition at line 62 of file dataBlock.h.
Referenced by getUnstructDescrDataPadding(), and setUnstructDescrDataPadding().
#define UNSTRUCT_DATA_PADDING_NUM_BITS 8
Definition at line 61 of file dataBlock.h.
#define UNSTRUCT_DATA_PADDING_OFFSET_IN_DWORD 24
Definition at line 60 of file dataBlock.h.
Referenced by getUnstructDescrDataPadding(), and setUnstructDescrDataPadding().
#define UNSTRUCT_DATA_PADDING_OFFSET_OF_DWORD 0
Definition at line 59 of file dataBlock.h.
Referenced by getUnstructDescrDataPadding(), and setUnstructDescrDataPadding().
#define UNSTRUCT_HIT_FORMAT_MASK 0x0000ffff
Definition at line 72 of file dataBlock.h.
Referenced by getUnstructDescrHitFormat(), and setUnstructDescrHitFormat().
#define UNSTRUCT_HIT_FORMAT_NUM_BITS 16
Definition at line 71 of file dataBlock.h.
#define UNSTRUCT_HIT_FORMAT_OFFSET_IN_DWORD 0
Definition at line 70 of file dataBlock.h.
Referenced by getUnstructDescrHitFormat(), and setUnstructDescrHitFormat().
#define UNSTRUCT_HIT_FORMAT_OFFSET_OF_DWORD 0
Definition at line 69 of file dataBlock.h.
Referenced by getUnstructDescrHitFormat(), and setUnstructDescrHitFormat().
#define UNSTRUCT_WORD_SIZE_MASK 0x00ff0000
Definition at line 67 of file dataBlock.h.
Referenced by getUnstructDescrWordSize(), and setUnstructDescrWordSize().
#define UNSTRUCT_WORD_SIZE_NUM_BITS 8
Definition at line 66 of file dataBlock.h.
#define UNSTRUCT_WORD_SIZE_OFFSET_IN_DWORD 16
Definition at line 65 of file dataBlock.h.
Referenced by getUnstructDescrWordSize(), and setUnstructDescrWordSize().
#define UNSTRUCT_WORD_SIZE_OFFSET_OF_DWORD 0
Definition at line 64 of file dataBlock.h.
Referenced by getUnstructDescrWordSize(), and setUnstructDescrWordSize().
Function Documentation
VALUE_ret extendUnstructPacketDataBlock (PACKET_ptr , UINT)
Definition at line 64 of file dataBlock.C.
References DWORD_SIZE, getUnstructPacketDataLengthWords(), getUnstructPacketWordSize(), setUnstructPacketDataPadding(), and valueFailure.
Referenced by finishUnstructDataWrite(), startUnstructDataWrite(), and storePacketHits().
INLINE_D VALUE_ret getUnstructDescrDataPadding (PHDWORD * descr_ptr)
Definition at line 214 of file dataBlock.h.
References getBitsMACRO, UNSTRUCT_DATA_PADDING_MASK, UNSTRUCT_DATA_PADDING_OFFSET_IN_DWORD, and UNSTRUCT_DATA_PADDING_OFFSET_OF_DWORD.
Referenced by getUnstructPacketDataPadding().
INLINE_D VALUE_ret getUnstructDescrHitFormat (PHDWORD * descr_ptr)
Definition at line 205 of file dataBlock.h.
References getBitsMACRO, UNSTRUCT_HIT_FORMAT_MASK, UNSTRUCT_HIT_FORMAT_OFFSET_IN_DWORD, and UNSTRUCT_HIT_FORMAT_OFFSET_OF_DWORD.
Referenced by getUnstructPacketHitFormat().
INLINE_D VALUE_ret getUnstructDescrWordSize (PHDWORD * descr_ptr)
Definition at line 196 of file dataBlock.h.
References getBitsMACRO, UNSTRUCT_WORD_SIZE_MASK, UNSTRUCT_WORD_SIZE_OFFSET_IN_DWORD, and UNSTRUCT_WORD_SIZE_OFFSET_OF_DWORD.
Referenced by getUnstructPacketWordSize().
VALUE_ret getUnstructPacketDataLengthBytes (PACKET_ptr)
Definition at line 30 of file dataBlock.C.
References DWORD_SIZE, getPacketDataLength(), getUnstructPacketDataPadding(), and valueFailure.
Referenced by getUnstructPacketDataLengthWords().
VALUE_ret getUnstructPacketDataLengthWords (PACKET_ptr)
Definition at line 46 of file dataBlock.C.
References FORMAT_ERR_DATA_INCONSISTENCY, getUnstructPacketDataLengthBytes(), getUnstructPacketWordSize(), setPacketError(), and valueFailure.
Referenced by dumpPacket(), extendUnstructPacketDataBlock(), fetchPacketHits(), and finishUnstructDataWrite().
INLINE_D VALUE_ret getUnstructPacketDataPadding (PACKET_ptr packet_ptr)
Definition at line 144 of file dataBlock.h.
References findPacketDataDescr(), getUnstructDescrDataPadding(), ptrFailure, and valueFailure.
Referenced by getUnstructPacketDataLengthBytes(), and storePacketHits().
INLINE_D VALUE_ret getUnstructPacketHitFormat (PACKET_ptr packet_ptr)
Definition at line 137 of file dataBlock.h.
References findPacketDataDescr(), getUnstructDescrHitFormat(), ptrFailure, and valueFailure.
Referenced by X_Event::change_hf(), dumpPacket(), Packet_A::getHitFormat(), and A_Event::makePacket().
INLINE_D VALUE_ret getUnstructPacketWordSize (PACKET_ptr packet_ptr)
Definition at line 130 of file dataBlock.h.
References findPacketDataDescr(), getUnstructDescrWordSize(), ptrFailure, and valueFailure.
Referenced by dumpPacket(), extendUnstructPacketDataBlock(), fetchPacketHits(), getPacketV1DataLength(), getUnstructPacketDataLengthWords(), A_Event::makePacket(), and storePacketHits().
INLINE_D LOGIC_ret makeUnstructDataDescr (PHDWORD * dataDescr_ptr, UINT inWordSize, UINT inHitFormat)
Definition at line 184 of file dataBlock.h.
References logicSuccess, setUnstructDescrHitFormat(), and setUnstructDescrWordSize().
Referenced by makeUnstructPacketDataDescr().
INLINE_D LOGIC_ret makeUnstructPacketDataDescr (PACKET_ptr packet_ptr, UINT inWordSize, UINT inHitFormat)
Definition at line 114 of file dataBlock.h.
References findPacketDataDescr(), logicFailure, makeUnstructDataDescr(), ptrFailure, and setPacketDataDescrLength().
Referenced by makeUnstructPacket(), and setPacketUnstructured().
INLINE_D LOGIC_ret setUnstructDescrDataPadding (PHDWORD * descr_ptr, UINT paddingBytes)
Definition at line 243 of file dataBlock.h.
References setBitsMACRO, TRUE, UNSTRUCT_DATA_PADDING_MASK, UNSTRUCT_DATA_PADDING_OFFSET_IN_DWORD, and UNSTRUCT_DATA_PADDING_OFFSET_OF_DWORD.
Referenced by setUnstructPacketDataPadding().
INLINE_D LOGIC_ret setUnstructDescrHitFormat (PHDWORD * descr_ptr, UINT hitFormat)
Definition at line 233 of file dataBlock.h.
References setBitsMACRO, TRUE, UNSTRUCT_HIT_FORMAT_MASK, UNSTRUCT_HIT_FORMAT_OFFSET_IN_DWORD, and UNSTRUCT_HIT_FORMAT_OFFSET_OF_DWORD.
Referenced by makeUnstructDataDescr(), and setUnstructPacketHitFormat().
INLINE_D LOGIC_ret setUnstructDescrWordSize (PHDWORD * descr_ptr, UINT wordSize)
Definition at line 223 of file dataBlock.h.
References setBitsMACRO, TRUE, UNSTRUCT_WORD_SIZE_MASK, UNSTRUCT_WORD_SIZE_OFFSET_IN_DWORD, and UNSTRUCT_WORD_SIZE_OFFSET_OF_DWORD.
Referenced by makeUnstructDataDescr(), and setUnstructPacketWordSize().
INLINE_D LOGIC_ret setUnstructPacketDataPadding (PACKET_ptr packet_ptr, UINT paddingBytes)
Definition at line 169 of file dataBlock.h.
References findPacketDataDescr(), ptrFailure, setUnstructDescrDataPadding(), and valueFailure.
Referenced by extendUnstructPacketDataBlock().
INLINE_D LOGIC_ret setUnstructPacketHitFormat (PACKET_ptr packet_ptr, UINT unHitFormat)
Definition at line 151 of file dataBlock.h.
References findPacketDataDescr(), ptrFailure, setUnstructDescrHitFormat(), and valueFailure.
Referenced by X_Event::change_hf().
INLINE_D LOGIC_ret setUnstructPacketWordSize (PACKET_ptr packet_ptr, UINT unWordSize)
Definition at line 160 of file dataBlock.h.
References findPacketDataDescr(), ptrFailure, setUnstructDescrWordSize(), and valueFailure.
Variable Documentation
CONSTANT PHDWORD UnstructDataDescrLength = 1
Definition at line 74 of file dataBlock.h.