Analysis Software: PHHepMCGenHelper Class Reference
PHHepMCGenHelper Class Reference
PHHepMCGenHelper provides service of DST upload of HepMC subevent, vertex assignment and random generator.
#include <coresoftware/blob/master/generators/phhepmc/PHHepMCGenHelper.h>
Public Types
enum VTXFUNC { Uniform, Gaus }
supported function distributions
Public Member Functions
PHHepMCGenHelper ()
virtual ~PHHepMCGenHelper ()
void set_vertex_distribution_function (VTXFUNC x, VTXFUNC y, VTXFUNC z, VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
int get_embedding_id () const
void set_embedding_id (int id)
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int create_node_tree (PHCompositeNode *topNode)
init interface nodes
PHHepMCGenEvent * insert_event (HepMC::GenEvent *evt)
send HepMC::GenEvent to DST tree. This function takes ownership of evt
void move_vertex (PHHepMCGenEvent *genevent)
move vertex according to vertex settings
const PHHepMCGenEventMap * get_geneventmap () const
PHHepMCGenEventMap * get_geneventmap ()
gsl_rng * get_random_generator ()
void set_geneventmap (PHHepMCGenEventMap *geneventmap)
Protected Member Functions
double smear (const double position, const double width, VTXFUNC dist) const
Protected Attributes
gsl_rng * RandomGenerator
Private Attributes
VTXFUNC _vertex_func_x
VTXFUNC _vertex_func_y
VTXFUNC _vertex_func_z
VTXFUNC _vertex_func_t
double _vertex_x
double _vertex_y
double _vertex_z
double _vertex_t
double _vertex_width_x
double _vertex_width_y
double _vertex_width_z
double _vertex_width_t
int _embedding_id
bool _reuse_vertex
whether reuse vertex from another PHHepMCGenEvent
int _reuse_vertex_embedding_id
if reuse_vertex, which embedding_id provide the source vertex. Additional smearing and shift possible with set_vertex_distribution*()
PHHepMCGenEventMap * _geneventmap
pointer to the output container
Detailed Description
PHHepMCGenHelper provides service of DST upload of HepMC subevent, vertex assignment and random generator.
Definition at line 30 of file PHHepMCGenHelper.h.
Member Enumeration Documentation
enum PHHepMCGenHelper::VTXFUNC
supported function distributions
Enumerator:
Uniform
uniform distribution with half width set via set_vertex_distribution_width()
Gaus
normal distribution with sigma width set via set_vertex_distribution_width()
Definition at line 37 of file PHHepMCGenHelper.h.
Constructor & Destructor Documentation
PHHepMCGenHelper::PHHepMCGenHelper ()
Definition at line 39 of file PHHepMCGenHelper.cc.
References RandomGenerator, and TauVsDIS_MachineLearning_Differentiation::seed.
PHHepMCGenHelper::~PHHepMCGenHelper () virtual
Definition at line 62 of file PHHepMCGenHelper.cc.
References RandomGenerator.
Member Function Documentation
int PHHepMCGenHelper::create_node_tree (PHCompositeNode * topNode)
init interface nodes
Definition at line 68 of file PHHepMCGenHelper.cc.
References _geneventmap, Fun4AllReturnCodes::ABORTRUN, assert, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by PHSartre::create_node_tree(), sHEPGen::create_node_tree(), PHPythia8::create_node_tree(), ReadEICFiles::CreateNodeTree(), and PHPythia6::CreateNodeTree().
int PHHepMCGenHelper::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 58 of file PHHepMCGenHelper.h.
References _embedding_id.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), PHPythia8::create_node_tree(), ReadEICFiles::get_embedding_id(), Fun4AllOscarInputManager::get_embedding_id(), Fun4AllHepMCInputManager::get_embedding_id(), PHPythia6::get_embedding_id(), sHEPGen::get_embedding_id(), PHSartre::get_embedding_id(), PHPythia8::get_embedding_id(), Fun4AllHepMCPileupInputManager::run(), and Fun4AllHepMCInputManager::run().
const PHHepMCGenEventMap* PHHepMCGenHelper::get_geneventmap () const inline
Definition at line 83 of file PHHepMCGenHelper.h.
References _geneventmap.
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), Fun4AllHepMCPileupInputManager::run(), and Fun4AllHepMCInputManager::run().
PHHepMCGenEventMap* PHHepMCGenHelper::get_geneventmap () inline
Definition at line 88 of file PHHepMCGenHelper.h.
References _geneventmap.
gsl_rng* PHHepMCGenHelper::get_random_generator () inline
Definition at line 94 of file PHHepMCGenHelper.h.
References RandomGenerator.
Referenced by PHSartre::randomlyReverseBeams().
PHHepMCGenEvent * PHHepMCGenHelper::insert_event (HepMC::GenEvent * evt)
send HepMC::GenEvent to DST tree. This function takes ownership of evt
Definition at line 92 of file PHHepMCGenHelper.cc.
References _embedding_id, _geneventmap, PHHepMCGenEvent::addEvent(), assert, genevent(), PHHepMCGenEventMap::insert_event(), and move_vertex().
Referenced by Fun4AllOscarInputManager::ConvertFromOscar(), PHPythia6::process_event(), PHSartre::process_event(), PHPythia8::process_event(), and Fun4AllHepMCInputManager::run().
void PHHepMCGenHelper::move_vertex (PHHepMCGenEvent * genevent)
move vertex according to vertex settings
Definition at line 105 of file PHHepMCGenHelper.cc.
References _geneventmap, _reuse_vertex, _reuse_vertex_embedding_id, _vertex_func_t, _vertex_func_x, _vertex_func_y, _vertex_func_z, _vertex_t, _vertex_width_t, _vertex_width_x, _vertex_width_y, _vertex_width_z, _vertex_x, _vertex_y, _vertex_z, assert, PHHepMCGenEventMap::get(), PHHepMCGenEvent::get_collision_vertex(), PHHepMCGenEventMap::identify(), PHHepMCGenEvent::moveVertex(), and smear().
Referenced by insert_event(), and Fun4AllHepMCPileupInputManager::run().
void PHHepMCGenHelper::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 64 of file PHHepMCGenHelper.h.
References _embedding_id.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), PHPythia6::PHPythia6(), PHPythia8::PHPythia8(), ReadEICFiles::ReadEICFiles(), ReadEICFiles::set_embedding_id(), Fun4AllOscarInputManager::set_embedding_id(), Fun4AllHepMCInputManager::set_embedding_id(), PHPythia6::set_embedding_id(), sHEPGen::set_embedding_id(), PHSartre::set_embedding_id(), PHPythia8::set_embedding_id(), and sHEPGen::sHEPGen().
void PHHepMCGenHelper::set_geneventmap (PHHepMCGenEventMap * geneventmap) inline
Definition at line 100 of file PHHepMCGenHelper.h.
References _geneventmap.
Referenced by Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), and Fun4AllOscarInputManager::Fun4AllOscarInputManager().
void PHHepMCGenHelper::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 67 of file PHHepMCGenHelper.h.
References _reuse_vertex, and _reuse_vertex_embedding_id.
Referenced by ReadEICFiles::set_reuse_vertex(), Fun4AllOscarInputManager::set_reuse_vertex(), Fun4AllHepMCInputManager::set_reuse_vertex(), PHPythia6::set_reuse_vertex(), sHEPGen::set_reuse_vertex(), PHSartre::set_reuse_vertex(), and PHPythia8::set_reuse_vertex().
void PHHepMCGenHelper::set_vertex_distribution_function (VTXFUNC x, VTXFUNC y, VTXFUNC z, VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 140 of file PHHepMCGenHelper.cc.
References _vertex_func_t, _vertex_func_x, _vertex_func_y, _vertex_func_z, t, x, y, and z.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), ReadEICFiles::set_vertex_distribution_function(), Fun4AllOscarInputManager::set_vertex_distribution_function(), Fun4AllHepMCInputManager::set_vertex_distribution_function(), PHPythia6::set_vertex_distribution_function(), sHEPGen::set_vertex_distribution_function(), PHSartre::set_vertex_distribution_function(), and PHPythia8::set_vertex_distribution_function().
void PHHepMCGenHelper::set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 149 of file PHHepMCGenHelper.cc.
References _vertex_t, _vertex_x, _vertex_y, _vertex_z, t, x, y, and z.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), ReadEICFiles::set_vertex_distribution_mean(), Fun4AllOscarInputManager::set_vertex_distribution_mean(), Fun4AllHepMCInputManager::set_vertex_distribution_mean(), PHPythia6::set_vertex_distribution_mean(), sHEPGen::set_vertex_distribution_mean(), PHSartre::set_vertex_distribution_mean(), and PHPythia8::set_vertex_distribution_mean().
void PHHepMCGenHelper::set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 158 of file PHHepMCGenHelper.cc.
References _vertex_width_t, _vertex_width_x, _vertex_width_y, _vertex_width_z, t, x, y, and z.
Referenced by Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), ReadEICFiles::set_vertex_distribution_width(), Fun4AllOscarInputManager::set_vertex_distribution_width(), Fun4AllHepMCInputManager::set_vertex_distribution_width(), PHPythia6::set_vertex_distribution_width(), sHEPGen::set_vertex_distribution_width(), PHSartre::set_vertex_distribution_width(), and PHPythia8::set_vertex_distribution_width().
double PHHepMCGenHelper::smear (const double position, const double width, VTXFUNC dist) const protected
Definition at line 167 of file PHHepMCGenHelper.cc.
References assert, Gaus, position, RandomGenerator, and Uniform.
Referenced by move_vertex().
Member Data Documentation
int PHHepMCGenHelper::_embedding_id private
positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 131 of file PHHepMCGenHelper.h.
Referenced by get_embedding_id(), insert_event(), and set_embedding_id().
PHHepMCGenEventMap* PHHepMCGenHelper::_geneventmap private
pointer to the output container
Definition at line 140 of file PHHepMCGenHelper.h.
Referenced by create_node_tree(), get_geneventmap(), insert_event(), move_vertex(), and set_geneventmap().
bool PHHepMCGenHelper::_reuse_vertex private
whether reuse vertex from another PHHepMCGenEvent
Definition at line 134 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_reuse_vertex().
int PHHepMCGenHelper::_reuse_vertex_embedding_id private
if reuse_vertex, which embedding_id provide the source vertex. Additional smearing and shift possible with set_vertex_distribution*()
Definition at line 137 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_reuse_vertex().
VTXFUNC PHHepMCGenHelper::_vertex_func_t private
Definition at line 116 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
VTXFUNC PHHepMCGenHelper::_vertex_func_x private
Definition at line 113 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
VTXFUNC PHHepMCGenHelper::_vertex_func_y private
Definition at line 114 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
VTXFUNC PHHepMCGenHelper::_vertex_func_z private
Definition at line 115 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_function().
double PHHepMCGenHelper::_vertex_t private
Definition at line 121 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
double PHHepMCGenHelper::_vertex_width_t private
Definition at line 126 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
double PHHepMCGenHelper::_vertex_width_x private
Definition at line 123 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
double PHHepMCGenHelper::_vertex_width_y private
Definition at line 124 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
double PHHepMCGenHelper::_vertex_width_z private
Definition at line 125 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_width().
double PHHepMCGenHelper::_vertex_x private
Definition at line 118 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
double PHHepMCGenHelper::_vertex_y private
Definition at line 119 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
double PHHepMCGenHelper::_vertex_z private
Definition at line 120 of file PHHepMCGenHelper.h.
Referenced by move_vertex(), and set_vertex_distribution_mean().
gsl_rng* PHHepMCGenHelper::RandomGenerator protected
Definition at line 107 of file PHHepMCGenHelper.h.
Referenced by get_random_generator(), PHHepMCGenHelper(), smear(), and ~PHHepMCGenHelper().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHHepMCGenHelper.h
coresoftware/blob/master/generators/phhepmc/PHHepMCGenHelper.cc