Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/Fun4All_G4_EICDetector_LQ.C File Reference
Fun4All_G4_EICDetector_LQ.C File Reference
Functions
int Fun4All_G4_EICDetector_LQ (string n="1000", string ebeam="20", string pbeam="250", string seed="1", string type="3pion")
Function Documentation
int Fun4All_G4_EICDetector_LQ (string n = "1000", string ebeam = "20", string pbeam = "250", string seed = "1", string type = "3pion")
Definition at line 1 of file Fun4All_G4_EICDetector_LQ.C.
References PHG4ParticleGeneratorVectorMeson::add_decay_particles(), PHG4SimpleEventGenerator::add_particles(), PHSartreParticleTrigger::AddParticles(), Bbc_Reco(), BbcInit(), CaloTrigger_Sim(), CEMC_Cells(), CEMC_Clusters(), CEMC_Towers(), DstCompress(), EEMC_Cells(), EEMC_Clusters(), EEMC_Towers(), EGEM_FastSim_Reco(), PHG4ParticleGeneratorBase::Embed(), Fun4AllServer::End(), FEMC_Cells(), FEMC_Clusters(), FEMC_Towers(), FGEM_FastSim_Reco(), FHCAL_Cells(), FHCAL_Clusters(), FHCAL_Towers(), Fun4AllInputManager::fileopen(), Fun4AllServer::fileopen(), G4DSTreader_EICDetector(), G4Init(), G4Setup(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Towers(), in, recoConsts::instance(), Fun4AllServer::instance(), kAll, n, Fun4AllBase::Name(), nEvents, ReadEICFiles::OpenInputFile(), particles, PHSartreParticleTrigger::PrintConfig(), PHSartre::register_trigger(), PHPythia6::register_trigger(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), TauVsDIS_MachineLearning_Differentiation::seed, PHPythia6::set_config_file(), PHSartre::set_config_file(), PHPythia8::set_config_file(), sHEPGen::set_datacard_file(), PHG4ParticleGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHG4ParticleGeneratorVectorMeson::set_mass(), PHG4ParticleGenerator::set_mom_range(), sHEPGen::set_momentum_electron(), sHEPGen::set_momentum_hadron(), PHG4ParticleGeneratorBase::set_name(), PHG4SimpleEventGenerator::set_p_range(), PHG4ParticleGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4ParticleGeneratorVectorMeson::set_pt_range(), PHG4SimpleEventGenerator::set_pt_range(), PHG4ParticleGeneratorVectorMeson::set_rapidity_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorVectorMeson::set_width(), PHG4ParticleGenerator::set_z_range(), PHSartreParticleTrigger::SetEtaHighLow(), PHPy6ParticleTrigger::SetQ2Min(), ShowerCompress(), Svtx_Cells(), Svtx_Reco(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().