Analysis Software: coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CellDefs.cc File Reference
PHG4CellDefs.cc File Reference
#include "PHG4CellDefs.h"
#include <phool/phool.h>
#include <cstdlib>
#include <iostream>
Functions
unsigned short generic_lower_16bit_key (const PHG4CellDefs::keytype key, const PHG4CellDefs::CellBinning binning)
unsigned short generic_upper_16bit_key (const PHG4CellDefs::keytype key, const PHG4CellDefs::CellBinning binning)
unsigned int generic_32bit_key (const PHG4CellDefs::keytype key, const PHG4CellDefs::CellBinning binning)
PHG4CellDefs::keytype generic_16bit_genkey (const unsigned short detid, const PHG4CellDefs::CellBinning binning, const unsigned short upper16bits, const unsigned short lower16bits)
PHG4CellDefs::keytype generic_32bit_genkey (const unsigned short detid, const PHG4CellDefs::CellBinning binning, const unsigned int bit32)
Function Documentation
PHG4CellDefs::keytype generic_16bit_genkey (const unsigned short detid, const PHG4CellDefs::CellBinning binning, const unsigned short upper16bits, const unsigned short lower16bits)
Definition at line 251 of file PHG4CellDefs.cc.
Referenced by PHG4CellDefs::SizeBinning::genkey(), PHG4CellDefs::EtaPhiBinning::genkey(), PHG4CellDefs::SpacalBinning::genkey(), PHG4CellDefs::ScintillatorSlatBinning::genkey(), PHG4CellDefs::EtaXsizeBinning::genkey(), and PHG4CellDefs::TPCBinning::genkey().
PHG4CellDefs::keytype generic_32bit_genkey (const unsigned short detid, const PHG4CellDefs::CellBinning binning, const unsigned int bit32)
Definition at line 265 of file PHG4CellDefs.cc.
Referenced by PHG4CellDefs::MVTXBinning::genkey().
unsigned int generic_32bit_key (const PHG4CellDefs::keytype key, const PHG4CellDefs::CellBinning binning)
Definition at line 235 of file PHG4CellDefs.cc.
References PHWHERE.
Referenced by PHG4CellDefs::MVTXBinning::get_index().
unsigned short generic_lower_16bit_key (const PHG4CellDefs::keytype key, const PHG4CellDefs::CellBinning binning)
Definition at line 202 of file PHG4CellDefs.cc.
References PHWHERE.
Referenced by PHG4CellDefs::EtaPhiBinning::get_etabin(), PHG4CellDefs::EtaXsizeBinning::get_etabin(), PHG4CellDefs::SpacalBinning::get_fiberid(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CellDefs::TPCBinning::get_radbin(), and PHG4CellDefs::ScintillatorSlatBinning::get_row().
unsigned short generic_upper_16bit_key (const PHG4CellDefs::keytype key, const PHG4CellDefs::CellBinning binning)
Definition at line 219 of file PHG4CellDefs.cc.
References PHWHERE.
Referenced by PHG4CellDefs::ScintillatorSlatBinning::get_column(), PHG4CellDefs::EtaPhiBinning::get_phibin(), PHG4CellDefs::SpacalBinning::get_phibin(), PHG4CellDefs::TPCBinning::get_phibin(), PHG4CellDefs::EtaXsizeBinning::get_xsizebin(), and PHG4CellDefs::SizeBinning::get_zbin().