Analysis Software: Fun4AllServer Class Reference
Fun4AllServer Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllServer.h>
Public Member Functions
virtual ~Fun4AllServer ()
virtual bool registerHisto (const char *hname, TNamed *h1d, const int replace=0)
virtual bool registerHisto (TNamed *h1d, const int replace=0)
template<typename T >
T * makeHisto (T *t)
virtual int isHistoRegistered (const std::string &name) const
int registerSubsystem (SubsysReco *subsystem, const std::string &topnodename="TOP")
int unregisterSubsystem (SubsysReco *subsystem)
SubsysReco * getSubsysReco (const std::string &name)
int registerOutputManager (Fun4AllOutputManager *manager)
Fun4AllOutputManager * getOutputManager (const std::string &name)
int registerHistoManager (Fun4AllHistoManager *manager)
Fun4AllHistoManager * getHistoManager (const std::string &name)
TNamed * getHisto (const std::string &hname) const
TNamed * getHisto (const unsigned int ihisto) const
const char * getHistoName (const unsigned int ihisto) const
virtual void Print (const std::string &what="ALL") const
void InitAll ()
int BeginRunTimeStamp (PHTimeStamp &TimeStp)
int dumpHistos (const std::string &filename="", const std::string &openmode="RECREATE")
int process_event (PHCompositeNode *topNode)
int Reset ()
virtual int BeginRun (const int runno)
virtual int EndRun (const int runno=0)
virtual int End ()
PHCompositeNode * topNode () const
PHCompositeNode * topNode (const std::string &name)
int outfileclose ()
virtual int process_event ()
PHCompositeNode * getNode (const std::string &name, const std::string &topnodename="TOP")
int AddTopNode (const std::string &name)
int MakeNodesTransient (PHCompositeNode *startNode)
int MakeNodesPersistent (PHCompositeNode *startNode)
int AddComplaint (const std::string &complaint, const std::string &remedy)
int registerInputManager (Fun4AllInputManager *InManager)
Fun4AllInputManager * getInputManager (const char *name)
int PrdfEvents () const
int DstEvents () const
int run (const int nevnts=0, const bool require_nevents=false)
run n events (0 means up to end of file)
int skip (const int nevnts=0)
skip n events (0 means up to the end of file). Skip means read, don't process.
int fileopen (const char *managername="NONE", const char *filename="NONE")
int fileclose (const std::string &managername="")
int SegmentNumber ()
int ResetNodeTree ()
int BranchSelect (const char *managername, const char *branch, int iflag)
int BranchSelect (const char *branch, int iflag)
int setBranches (const char *managername)
int setBranches ()
virtual int DisconnectDB ()
virtual void identify (std::ostream &out=std::cout) const
unsigned GetTopNodes (std::vector< std::string > &names) const
void GetInputFullFileList (std::vector< std::string > &fnames) const
void GetOutputManagerList (std::vector< std::string > &names) const
void GetModuleList (std::vector< std::string > &names) const
Fun4AllSyncManager * getSyncManager (const std::string &name="DefaultSyncManager")
int registerSyncManager (Fun4AllSyncManager *newmaster)
int retcodestats (const int iret)
void EventNumber (const int evtno)
void NodeIdentify (const std::string &name)
void KeepDBConnection (const int i=1)
void PrintTimer (const std::string &name="")
void PrintMemoryTracker (const std::string &name="") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Member Functions
static Fun4AllServer * instance ()
Protected Member Functions
Fun4AllServer (const std::string &name="Fun4AllServer")
int InitNodeTree (PHCompositeNode *topNode)
int CountOutNodes (PHCompositeNode *startNode)
int CountOutNodesRecursive (PHCompositeNode *startNode, const int icount)
int UpdateEventSelector (Fun4AllOutputManager *manager)
int unregisterSubsystemsNow ()
int setRun (const int runnumber)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TH1 * FrameWorkVars
Fun4AllMemoryTracker * ffamemtracker
Fun4AllHistoManager * ServerHistoManager
PHTimeStamp * beginruntimestamp
PHCompositeNode * TopNode
Fun4AllSyncManager * defaultSyncManager
int OutNodeCount
int bortime_override
int ScreamEveryEvent
int unregistersubsystem
int runnumber
int eventnumber
int keep_db_connected
std::vector< std::string > ComplaintList
std::vector< std::pair
< SubsysReco
*, PHCompositeNode * > > Subsystems
std::vector< std::pair
< SubsysReco
*, PHCompositeNode * > > DeleteSubsystems
std::vector< int > RetCodes
std::vector
< Fun4AllOutputManager * > OutputManager
std::vector< TDirectory * > TDirCollection
std::vector
< Fun4AllHistoManager * > HistoManager
std::map< std::string,
PHCompositeNode * > topnodemap
std::string default_Tdirectory
std::vector< Fun4AllSyncManager * > SyncManagers
std::map< int, int > retcodesmap
std::map< const std::string,
PHTimer > timer_map
Static Protected Attributes
static Fun4AllServer * __instance = nullptr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 29 of file Fun4AllServer.h.
Constructor & Destructor Documentation
Fun4AllServer::~Fun4AllServer () virtual
Definition at line 70 of file Fun4AllServer.cc.
References __instance, beginruntimestamp, ffamemtracker, HistoManager, recoConsts::instance(), OutputManager, Reset(), Subsystems, SyncManagers, TDirCollection, topnodemap, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Fun4AllServer::Fun4AllServer (const std::string & name = "Fun4AllServer") protected
Definition at line 54 of file Fun4AllServer.cc.
References InitAll().
Member Function Documentation
int Fun4AllServer::AddComplaint (const std::string & complaint, const std::string & remedy)
Definition at line 349 of file Fun4AllServer.cc.
References ComplaintList, and ScreamEveryEvent.
int Fun4AllServer::AddTopNode (const std::string & name)
Definition at line 1264 of file Fun4AllServer.cc.
References name, and topnodemap.
Referenced by topNode().
int Fun4AllServer::BeginRun (const int runno) virtual
Definition at line 784 of file Fun4AllServer.cc.
References Fun4AllReturnCodes::ABORTRUN, beginruntimestamp, bortime_override, default_Tdirectory, DisconnectDB(), Fun4AllReturnCodes::EVENT_OK, ffamemtracker, keep_db_connected, PHWHERE, PHTimeStamp::print(), Print(), Fun4AllMemoryTracker::Snapshot(), Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Subsystems, unregistersubsystem, unregisterSubsystemsNow(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by run().
int Fun4AllServer::BeginRunTimeStamp (PHTimeStamp & TimeStp)
Definition at line 774 of file Fun4AllServer.cc.
References beginruntimestamp, bortime_override, and PHTimeStamp::print().
int Fun4AllServer::BranchSelect (const char * managername, const char * branch, int iflag)
Definition at line 1504 of file Fun4AllServer.cc.
References SyncManagers.
int Fun4AllServer::BranchSelect (const char * branch, int iflag)
Definition at line 1515 of file Fun4AllServer.cc.
References SyncManagers.
int Fun4AllServer::CountOutNodes (PHCompositeNode * startNode) protected
Definition at line 901 of file Fun4AllServer.cc.
References CountOutNodesRecursive().
Referenced by process_event().
int Fun4AllServer::CountOutNodesRecursive (PHCompositeNode * startNode, const int icount) protected
Definition at line 908 of file Fun4AllServer.cc.
References PHNodeIterator::ls(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by CountOutNodes().
int Fun4AllServer::DisconnectDB () virtual
Definition at line 1571 of file Fun4AllServer.cc.
Referenced by BeginRun().
int Fun4AllServer::DstEvents () const
Definition at line 1315 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::TotalEvents().
int Fun4AllServer::dumpHistos (const std::string & filename = "", const std::string & openmode = "RECREATE")
Definition at line 152 of file Fun4AllServer.cc.
References HistoManager, ServerHistoManager, and Fun4AllHistoManager::setOutfileName().
Referenced by AnalyzeTree(), Fun(), RunBoth(), and Wrapper().
int Fun4AllServer::End () virtual
Definition at line 1021 of file Fun4AllServer.cc.
References ComplaintList, default_Tdirectory, EndRun(), PHNodeIterator::findFirst(), PHFlag::get_IntFlag(), i, recoConsts::instance(), outfileclose(), OutputManager, PHWHERE, ScreamEveryEvent, Subsystems, TopNode, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_SOME.
Referenced by AnalyzeTree(), Fun(), Fun4All_Ana(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_CaloAna(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCalLikelihood(), Fun4All_ExportGeom(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_HCALAnalysis(), Fun4All_ImportGeom(), Fun4All_JetAna(), Fun4All_MCEventGen(), Fun4All_Pythia6(), Fun4All_RICHReco(), Fun4All_single_particle(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), G4TTree(), generate_hepmc_bjet(), Jin_BJet(), MakeEdepNtuple(), MakeShowerSize(), MakeTree(), MyHitTTree(), ReadClustersRunTracking(), run_dump(), run_macro(), run_macro_2(), RunBDiJetModule(), RunBJetModule(), RunBoth(), RunGenFitTrackProp(), and Wrapper().
int Fun4AllServer::EndRun (const int runno = 0) virtual
Definition at line 970 of file Fun4AllServer.cc.
References default_Tdirectory, PHWHERE, Subsystems, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by End(), and run().
void Fun4AllServer::EventNumber (const int evtno) inline
Definition at line 107 of file Fun4AllServer.h.
References eventnumber.
Referenced by Fun4AllSyncManager::CurrentEvent().
int Fun4AllServer::fileclose (const std::string & managername = "")
Definition at line 1548 of file Fun4AllServer.cc.
References SyncManagers.
int Fun4AllServer::fileopen (const char * managername = "NONE", const char * filename = "NONE")
Definition at line 1493 of file Fun4AllServer.cc.
References SyncManagers.
Referenced by AnalyzeTree(), Fun4All_Ana(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_single_particle(), Jin_BJet(), and run_dump().
TNamed * Fun4AllServer::getHisto (const std::string & hname) const
Definition at line 498 of file Fun4AllServer.cc.
References Fun4AllHistoManager::getHisto(), and ServerHistoManager.
Referenced by PHG4OuterHcalSteppingAction::FieldChecker().
TNamed * Fun4AllServer::getHisto (const unsigned int ihisto) const
Definition at line 487 of file Fun4AllServer.cc.
References Fun4AllHistoManager::getHisto(), and ServerHistoManager.
Fun4AllHistoManager * Fun4AllServer::getHistoManager (const std::string & name)
Definition at line 446 of file Fun4AllServer.cc.
References HistoManager, name, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by PHAna::create_histos(), PHAna::End(), PHAna::fill_histos(), EMCalLikelihood::get_HistoManager(), Proto4SampleFrac::get_HistoManager(), EMCalAna::get_HistoManager(), EMCalCalib::get_HistoManager(), EMCalCalib_TestBeam::get_HistoManager(), Proto4ShowerCalib::get_HistoManager(), Proto2ShowerCalib::get_HistoManager(), Proto3ShowerCalib::get_HistoManager(), Proto4TowerCalib::get_HistoManager(), ExampleAnalysisModule::get_HistoManager(), QAHistManagerDef::getHistoManager(), TPCIntegratedCharge::getHistoManager(), TPCDataStreamEmulator::getHistoManager(), PHG4ScoringManager::getHistoManager(), JetHepMCLoader::getHistoManager(), TPCMLDataInterface::getHistoManager(), SoftLeptonTaggingTruth::getHistoManager(), TPCFEETestRecov1::getHistoManager(), and TpcPrototypeUnpacker::getHistoManager().
const char * Fun4AllServer::getHistoName (const unsigned int ihisto) const
Definition at line 493 of file Fun4AllServer.cc.
References Fun4AllHistoManager::getHistoName(), and ServerHistoManager.
void Fun4AllServer::GetInputFullFileList (std::vector< std::string > & fnames) const
Definition at line 1565 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::GetInputFullFileList().
Fun4AllInputManager * Fun4AllServer::getInputManager (const char * name)
Definition at line 1296 of file Fun4AllServer.cc.
References SyncManagers.
void Fun4AllServer::GetModuleList (std::vector< std::string > & names) const
Definition at line 1598 of file Fun4AllServer.cc.
References Subsystems.
PHCompositeNode * Fun4AllServer::getNode (const std::string & name, const std::string & topnodename = "TOP")
Definition at line 1277 of file Fun4AllServer.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and topNode().
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), and Fun4AllOscarInputManager::Fun4AllOscarInputManager().
Fun4AllOutputManager * Fun4AllServer::getOutputManager (const std::string & name)
Definition at line 427 of file Fun4AllServer.cc.
References OutputManager, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
void Fun4AllServer::GetOutputManagerList (std::vector< std::string > & names) const
Definition at line 1587 of file Fun4AllServer.cc.
References OutputManager.
SubsysReco * Fun4AllServer::getSubsysReco (const std::string & name)
Definition at line 331 of file Fun4AllServer.cc.
References name, Subsystems, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by DisplayOn(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), G4Cmd(), get_gen(), get_gun(), getgun(), matscan(), and QTGui().
Fun4AllSyncManager * Fun4AllServer::getSyncManager (const std::string & name = "DefaultSyncManager")
Definition at line 1629 of file Fun4AllServer.cc.
References defaultSyncManager, name, and SyncManagers.
unsigned Fun4AllServer::GetTopNodes (std::vector< std::string > & names) const
Definition at line 1577 of file Fun4AllServer.cc.
References topnodemap.
void Fun4AllServer::identify (std::ostream & out = std::cout) const virtual
Definition at line 1205 of file Fun4AllServer.cc.
References Fun4AllBase::Name().
void Fun4AllServer::InitAll ()
Definition at line 128 of file Fun4AllServer.cc.
References default_Tdirectory, defaultSyncManager, FrameWorkVars, i, InitNodeTree(), Fun4AllBase::Name(), NFRAMEWORKBINS, registerHisto(), registerHistoManager(), ServerHistoManager, SyncManagers, TopNode, and topnodemap.
Referenced by Fun4AllServer().
int Fun4AllServer::InitNodeTree (PHCompositeNode * topNode) protected
Definition at line 1227 of file Fun4AllServer.cc.
References PHCompositeNode::addNode().
Referenced by InitAll(), and topNode().
Fun4AllServer * Fun4AllServer::instance () static
Definition at line 44 of file Fun4AllServer.cc.
Referenced by AnalyzeTree(), Bbc_Reco(), CaloTrigger_Sim(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_Towers(), ConfigureInput(), ConstructGeometry(), PHAna::create_histos(), Fun4AllSyncManager::CurrentEvent(), DisplayOn(), PHG4GDMLUtility::Dump_GDML(), EEMC_Cells(), EEMC_Clusters(), EEMC_Eval(), EEMC_Towers(), EGEM_FastSim_Reco(), PHAna::End(), FastSim_Reco_EIC(), FEMC_Cells(), FEMC_Clusters(), FEMC_Eval(), FEMC_Towers(), FEMCSetup(), FGEM_FastSim_Eval(), FGEM_FastSim_Reco(), FHCAL_Cells(), FHCAL_Clusters(), FHCAL_Eval(), FHCAL_Towers(), FHCALSetup(), PHG4OuterHcalSteppingAction::FieldChecker(), Fun4AllDstInputManager::fileopen(), PHAna::fill_histos(), Fun(), Fun4All_Ana(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_CaloAna(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCalLikelihood(), Fun4All_ExportGeom(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_ImportGeom(), Fun4All_JetAna(), Fun4All_MCEventGen(), Fun4All_Pythia6(), Fun4All_RICHReco(), Fun4All_single_particle(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), G4_Lepto(), G4Cmd(), G4DSTreader(), G4DSTreader_EICDetector(), G4DSTreader_EICIR(), G4DSTreader_fsPHENIX(), G4Setup(), G4TTree(), generate_hepmc_bjet(), get_gen(), get_gun(), EMCalLikelihood::get_HistoManager(), Proto4SampleFrac::get_HistoManager(), EMCalAna::get_HistoManager(), EMCalCalib::get_HistoManager(), EMCalCalib_TestBeam::get_HistoManager(), Proto4ShowerCalib::get_HistoManager(), Proto2ShowerCalib::get_HistoManager(), Proto3ShowerCalib::get_HistoManager(), Proto4TowerCalib::get_HistoManager(), ExampleAnalysisModule::get_HistoManager(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), getgun(), QAHistManagerDef::getHistoManager(), TPCIntegratedCharge::getHistoManager(), TPCDataStreamEmulator::getHistoManager(), PHG4ScoringManager::getHistoManager(), JetHepMCLoader::getHistoManager(), TPCMLDataInterface::getHistoManager(), SoftLeptonTaggingTruth::getHistoManager(), TPCFEETestRecov1::getHistoManager(), TpcPrototypeUnpacker::getHistoManager(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), HIJetReco(), SvtxSimPerformanceCheckReco::Init(), AnalyzeSimpleTree::Init(), TrackingPerformanceCheck::Init(), SimpleTrackingAnalysis::Init(), STACalorimeterCharacterization::Init(), PHAJMaker::Init(), Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), PHG4TpcElectronDrift::InitRun(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_Reco(), Jin_BJet(), PHG4FullProjSpacalCellReco::LightCollectionModel::LightCollectionModel(), MakeEdepNtuple(), MakeShowerSize(), MakeTree(), matscan(), MyHitTTree(), PHGeom_DSTInspection(), QTGui(), ReadClustersRunTracking(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), HcalRawTowerBuilder::ReadParamsFromNodeTree(), registerSubsystem(), Fun4AllInputManager::registerSubsystem(), Fun4AllInputManager::RejectEvent(), run_dump(), run_macro(), run_macro_2(), RunBDiJetModule(), RunBJetModule(), RunBoth(), RunGenFitTrackProp(), ShowerCompress(), Svtx_Cells(), Svtx_Clustering(), Svtx_Eval(), Svtx_Reco(), Svtx_Tracking(), TopoClusterReco(), Tracking_Cells(), Tracking_Clus(), Tracking_Eval(), Tracking_Reco(), Wrapper(), Fun4AllEventOutputManager::Write(), Fun4AllDstOutputManager::Write(), Fun4AllFileOutStream::WriteEventOut(), and Fun4AllDstOutputManager::WriteNode().
int Fun4AllServer::isHistoRegistered (const std::string & name) const virtual
Definition at line 178 of file Fun4AllServer.cc.
References Fun4AllHistoManager::isHistoRegistered(), and ServerHistoManager.
Referenced by PHG4OuterHcalSteppingAction::FieldChecker().
void Fun4AllServer::KeepDBConnection (const int i = 1) inline
Definition at line 109 of file Fun4AllServer.h.
References i, and keep_db_connected.
template<typename T > T* Fun4AllServer::makeHisto (T * t) inline
Definition at line 38 of file Fun4AllServer.h.
References Fun4AllHistoManager::makeHisto(), and ServerHistoManager.
int Fun4AllServer::MakeNodesPersistent (PHCompositeNode * startNode)
Definition at line 951 of file Fun4AllServer.cc.
References PHNodeIterator::ls().
Referenced by Fun4AllDstOutputManager::Write(), and Fun4AllDstOutputManager::WriteNode().
int Fun4AllServer::MakeNodesTransient (PHCompositeNode * startNode)
Definition at line 932 of file Fun4AllServer.cc.
References PHNodeIterator::ls().
Referenced by process_event(), and Fun4AllDstOutputManager::Write().
void Fun4AllServer::NodeIdentify (const std::string & name)
Definition at line 1666 of file Fun4AllServer.cc.
References PHObject::identify(), name, and TopNode.
int Fun4AllServer::outfileclose ()
Definition at line 1211 of file Fun4AllServer.cc.
References Fun4AllBase::Name(), OutputManager, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by End().
int Fun4AllServer::PrdfEvents () const
Definition at line 1310 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::PrdfEvents().
void Fun4AllServer::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllBase.
Definition at line 1112 of file Fun4AllServer.cc.
References HistoManager, Fun4AllBase::Name(), OutputManager, pos, Fun4AllHistoManager::Print(), Fun4AllOutputManager::Print(), PHNodeIterator::print(), Fun4AllSyncManager::Print(), Subsystems, SyncManagers, and topnodemap.
Referenced by BeginRun(), Prototype2RawTowerBuilder::InitRun(), PHG4Prototype2HcalCellReco::InitRun(), Prototype2RawTowerBuilder::ReadParamsFromNodeTree(), and HcalRawTowerBuilder::ReadParamsFromNodeTree().
void Fun4AllServer::PrintMemoryTracker (const std::string & name = "") const
Definition at line 1711 of file Fun4AllServer.cc.
References ffamemtracker, and Fun4AllMemoryTracker::PrintMemoryTracker().
void Fun4AllServer::PrintTimer (const std::string & name = "")
Definition at line 1681 of file Fun4AllServer.cc.
References timer_map.
Referenced by ReadClustersRunTracking().
int Fun4AllServer::process_event (PHCompositeNode * topNode)
Definition at line 503 of file Fun4AllServer.cc.
References process_event().
int Fun4AllServer::process_event () virtual
Definition at line 509 of file Fun4AllServer.cc.
References Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, ComplaintList, CountOutNodes(), default_Tdirectory, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, ffamemtracker, PHNodeIterator::findFirst(), MakeNodesTransient(), Fun4AllBase::Name(), OutNodeCount, OutputManager, PHWHERE, PHNodeIterator::print(), Fun4AllSyncManager::ResetEvent(), ResetNodeTree(), RetCodes, retcodesmap, ScreamEveryEvent, Fun4AllMemoryTracker::Snapshot(), Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Subsystems, SyncManagers, timer_map, TopNode, unregistersubsystem, unregisterSubsystemsNow(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_EVEN_MORE, and Fun4AllBase::VERBOSITY_MORE.
Referenced by process_event(), and run().
bool Fun4AllServer::registerHisto (const char * hname, TNamed * h1d, const int replace = 0) virtual
Definition at line 173 of file Fun4AllServer.cc.
References Fun4AllHistoManager::registerHisto(), and ServerHistoManager.
Referenced by PHG4OuterHcalSteppingAction::FieldChecker(), SvtxSimPerformanceCheckReco::Init(), TrackingPerformanceCheck::Init(), STACalorimeterCharacterization::Init(), SimpleTrackingAnalysis::Init(), InitAll(), PHG4TpcElectronDrift::InitRun(), and PHG4FullProjSpacalCellReco::LightCollectionModel::LightCollectionModel().
bool Fun4AllServer::registerHisto (TNamed * h1d, const int replace = 0) virtual
Definition at line 168 of file Fun4AllServer.cc.
References Fun4AllHistoManager::registerHisto(), and ServerHistoManager.
int Fun4AllServer::registerHistoManager (Fun4AllHistoManager * manager)
Definition at line 467 of file Fun4AllServer.cc.
References HistoManager, Fun4AllBase::Name(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by PHAna::create_histos(), EMCalLikelihood::get_HistoManager(), Proto4SampleFrac::get_HistoManager(), EMCalAna::get_HistoManager(), EMCalCalib::get_HistoManager(), EMCalCalib_TestBeam::get_HistoManager(), Proto4ShowerCalib::get_HistoManager(), Proto2ShowerCalib::get_HistoManager(), Proto3ShowerCalib::get_HistoManager(), Proto4TowerCalib::get_HistoManager(), ExampleAnalysisModule::get_HistoManager(), QAHistManagerDef::getHistoManager(), TPCIntegratedCharge::getHistoManager(), TPCDataStreamEmulator::getHistoManager(), PHG4ScoringManager::getHistoManager(), JetHepMCLoader::getHistoManager(), TPCMLDataInterface::getHistoManager(), SoftLeptonTaggingTruth::getHistoManager(), TPCFEETestRecov1::getHistoManager(), TpcPrototypeUnpacker::getHistoManager(), AnalyzeSimpleTree::Init(), PHAJMaker::Init(), and InitAll().
int Fun4AllServer::registerInputManager (Fun4AllInputManager * InManager)
Definition at line 1289 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::registerInputManager().
Referenced by AnalyzeTree(), ConfigureInput(), ConstructGeometry(), Fun4All_Ana(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_CaloAna(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCalLikelihood(), Fun4All_ExportGeom(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_ImportGeom(), Fun4All_JetAna(), Fun4All_RICHReco(), Fun4All_single_particle(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), G4TTree(), generate_hepmc_bjet(), Jin_BJet(), MakeEdepNtuple(), MakeShowerSize(), MakeTree(), MyHitTTree(), PHGeom_DSTInspection(), ReadClustersRunTracking(), run_dump(), run_macro(), run_macro_2(), RunBDiJetModule(), RunBJetModule(), RunBoth(), RunGenFitTrackProp(), and Wrapper().
int Fun4AllServer::registerOutputManager (Fun4AllOutputManager * manager)
Definition at line 366 of file Fun4AllServer.cc.
References Fun4AllBase::Name(), OutputManager, UpdateEventSelector(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EMCalLikelihood(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_IonGun(), Fun4All_G4_Momentum(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_ImportGeom(), Fun4All_MCEventGen(), Fun4All_Pythia6(), Fun4All_single_particle(), Fun4All_TestBeam(), Fun4All_TestBeam_TPC(), G4TTree(), generate_hepmc_bjet(), Jin_BJet(), MakeTree(), and MyHitTTree().
int Fun4AllServer::registerSubsystem (SubsysReco * subsystem, const std::string & topnodename = "TOP")
Definition at line 184 of file Fun4AllServer.cc.
References default_Tdirectory, Fun4AllReturnCodes::DONOTREGISTERSUBSYSTEM, ffamemtracker, SubsysReco::Init(), instance(), Fun4AllBase::Name(), PHWHERE, RetCodes, Fun4AllMemoryTracker::Start(), Fun4AllMemoryTracker::Stop(), Subsystems, TDirCollection, timer_map, topNode(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by AnalyzeTree(), Bbc_Reco(), CaloTrigger_Sim(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_Towers(), ConfigureInput(), ConstructGeometry(), EEMC_Cells(), EEMC_Clusters(), EEMC_Eval(), EEMC_Towers(), EGEM_FastSim_Reco(), FastSim_Reco_EIC(), FEMC_Cells(), FEMC_Clusters(), FEMC_Eval(), FEMC_Towers(), FGEM_FastSim_Eval(), FGEM_FastSim_Reco(), FHCAL_Cells(), FHCAL_Clusters(), FHCAL_Eval(), FHCAL_Towers(), Fun(), Fun4All_Ana(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_CaloAna(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCalLikelihood(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_ImportGeom(), Fun4All_JetAna(), Fun4All_MCEventGen(), Fun4All_Pythia6(), Fun4All_RICHReco(), Fun4All_single_particle(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), G4_Lepto(), G4DSTreader(), G4DSTreader_EICDetector(), G4DSTreader_EICIR(), G4DSTreader_fsPHENIX(), G4Setup(), G4TTree(), generate_hepmc_bjet(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), HIJetReco(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_Reco(), Jin_BJet(), MakeEdepNtuple(), MakeShowerSize(), MakeTree(), MyHitTTree(), ReadClustersRunTracking(), run_dump(), run_macro(), run_macro_2(), RunBDiJetModule(), RunBJetModule(), RunBoth(), RunGenFitTrackProp(), ShowerCompress(), Svtx_Cells(), Svtx_Clustering(), Svtx_Eval(), Svtx_Reco(), Svtx_Tracking(), TopoClusterReco(), Tracking_Cells(), Tracking_Clus(), Tracking_Eval(), Tracking_Reco(), and Wrapper().
int Fun4AllServer::registerSyncManager (Fun4AllSyncManager * newmaster)
Definition at line 1609 of file Fun4AllServer.cc.
References Fun4AllBase::Name(), SyncManagers, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
int Fun4AllServer::Reset ()
Definition at line 754 of file Fun4AllServer.cc.
References HistoManager, i, Subsystems, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by ~Fun4AllServer().
int Fun4AllServer::ResetNodeTree ()
Definition at line 731 of file Fun4AllServer.cc.
References PHNodeIterator::cd(), PHNodeIterator::forEach(), topnodemap, PHNodeOperation::Verbosity(), and Fun4AllBase::Verbosity().
Referenced by process_event(), and run().
int Fun4AllServer::retcodestats (const int iret) inline
Definition at line 106 of file Fun4AllServer.h.
References retcodesmap.
int Fun4AllServer::run (const int nevnts = 0, const bool require_nevents = false)
run n events (0 means up to end of file)
Definition at line 1321 of file Fun4AllServer.cc.
References Fun4AllReturnCodes::ABORTEVENT, BeginRun(), EndRun(), PHFlag::FlagExist(), PHFlag::get_IntFlag(), recoConsts::instance(), process_event(), ResetNodeTree(), RetCodes, runnumber, setRun(), SyncManagers, Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, Fun4AllBase::VERBOSITY_QUIET, and Fun4AllBase::VERBOSITY_SOME.
Referenced by AnalyzeTree(), ConstructGeometry(), Fun(), Fun4All_Ana(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_CaloAna(), Fun4All_EICAnalysis_DIS(), Fun4All_EICAnalysis_DISReco(), Fun4All_EICAnalysis_DVCS(), Fun4All_EICAnalysis_Exclusive(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_EICAnalysis_Quarkonia(), Fun4All_EICAnalysis_TrackEval(), Fun4All_EMCalLikelihood(), Fun4All_ExportGeom(), Fun4All_G4_block(), Fun4All_G4_Clusters(), Fun4All_G4_Cylinder(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_IonGun(), Fun4All_G4_LeadBrick(), Fun4All_G4_Momentum(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_HCALAnalysis(), Fun4All_ImportGeom(), Fun4All_JetAna(), Fun4All_MCEventGen(), Fun4All_Pythia6(), Fun4All_RICHReco(), Fun4All_single_particle(), Fun4All_TestBeam(), Fun4All_TestBeam_Ana(), Fun4All_TestBeam_ExampleAnalysisModule(), Fun4All_TestBeam_HCAL_SampleFrac(), Fun4All_TestBeam_HCAL_ShowerCalib(), Fun4All_TestBeam_HCAL_TowerCalib(), Fun4All_TestBeam_ShowerCalib(), Fun4All_TestBeam_TPC(), G4TTree(), generate_hepmc_bjet(), Jin_BJet(), MakeEdepNtuple(), MakeShowerSize(), MakeTree(), MyHitTTree(), PHGeom_DSTInspection(), ReadClustersRunTracking(), run_dump(), run_macro(), run_macro_2(), RunBDiJetModule(), RunBJetModule(), RunBoth(), RunGenFitTrackProp(), Fun4AllMessenger::SetNewValue(), and Wrapper().
int Fun4AllServer::SegmentNumber ()
Definition at line 1559 of file Fun4AllServer.cc.
References defaultSyncManager, and Fun4AllSyncManager::SegmentNumber().
Referenced by Fun4AllFileOutStream::WriteEventOut().
int Fun4AllServer::setBranches (const char * managername)
Definition at line 1526 of file Fun4AllServer.cc.
References SyncManagers.
int Fun4AllServer::setBranches ()
Definition at line 1537 of file Fun4AllServer.cc.
References SyncManagers.
int Fun4AllServer::setRun (const int runnumber) protected
Definition at line 1648 of file Fun4AllServer.cc.
References FrameWorkVars, recoConsts::instance(), PHTimeStamp::print(), RUNNUMBERBIN, and PHFlag::set_IntFlag().
Referenced by run().
int Fun4AllServer::skip (const int nevnts = 0)
skip n events (0 means up to the end of file). Skip means read, don't process.
Definition at line 1481 of file Fun4AllServer.cc.
References SyncManagers.
Referenced by Fun4All_TestBeam_TPC().
PHCompositeNode* Fun4AllServer::topNode () const inline
Definition at line 64 of file Fun4AllServer.h.
References TopNode.
Referenced by ConstructGeometry(), DisplayOn(), PHG4GDMLUtility::Dump_GDML(), Fun4All_ExportGeom(), Fun4All_Generator_Display(), Fun4All_ImportGeom(), Fun4AllHepMCInputManager::Fun4AllHepMCInputManager(), Fun4AllOscarInputManager::Fun4AllOscarInputManager(), Fun4AllPrdfInputManager::Fun4AllPrdfInputManager(), PHFieldUtility::GetFieldConfigNode(), PHFieldUtility::GetFieldMapNode(), getNode(), matscan(), PHGeom_DSTInspection(), QTGui(), registerSubsystem(), Fun4AllInputManager::registerSubsystem(), Fun4AllInputManager::RejectEvent(), and Fun4AllEventOutputManager::Write().
PHCompositeNode * Fun4AllServer::topNode (const std::string & name)
Definition at line 1240 of file Fun4AllServer.cc.
References AddTopNode(), InitNodeTree(), PHWHERE, and topnodemap.
int Fun4AllServer::unregisterSubsystem (SubsysReco * subsystem)
Definition at line 276 of file Fun4AllServer.cc.
References DeleteSubsystems, and unregistersubsystem.
int Fun4AllServer::unregisterSubsystemsNow () protected
Definition at line 284 of file Fun4AllServer.cc.
References DeleteSubsystems, index, OutputManager, RetCodes, Subsystems, unregistersubsystem, UpdateEventSelector(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by BeginRun(), and process_event().
int Fun4AllServer::UpdateEventSelector (Fun4AllOutputManager * manager) protected
Definition at line 386 of file Fun4AllServer.cc.
References Fun4AllOutputManager::EventSelector(), index, PHWHERE, Fun4AllOutputManager::RecoModuleIndex(), Subsystems, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_EVEN_MORE.
Referenced by registerOutputManager(), and unregisterSubsystemsNow().
Member Data Documentation
Fun4AllServer * Fun4AllServer::__instance = nullptr static protected
Definition at line 121 of file Fun4AllServer.h.
Referenced by ~Fun4AllServer().
PHTimeStamp* Fun4AllServer::beginruntimestamp protected
Definition at line 125 of file Fun4AllServer.h.
Referenced by BeginRun(), BeginRunTimeStamp(), and ~Fun4AllServer().
int Fun4AllServer::bortime_override protected
Definition at line 130 of file Fun4AllServer.h.
Referenced by BeginRun(), and BeginRunTimeStamp().
std::vector<std::string> Fun4AllServer::ComplaintList protected
Definition at line 137 of file Fun4AllServer.h.
Referenced by AddComplaint(), End(), and process_event().
std::string Fun4AllServer::default_Tdirectory protected
Definition at line 145 of file Fun4AllServer.h.
Referenced by BeginRun(), End(), EndRun(), InitAll(), process_event(), and registerSubsystem().
Fun4AllSyncManager* Fun4AllServer::defaultSyncManager protected
Definition at line 127 of file Fun4AllServer.h.
Referenced by DstEvents(), GetInputFullFileList(), getSyncManager(), InitAll(), PrdfEvents(), registerInputManager(), and SegmentNumber().
std::vector<std::pair<SubsysReco *, PHCompositeNode *> > Fun4AllServer::DeleteSubsystems protected
Definition at line 139 of file Fun4AllServer.h.
Referenced by unregisterSubsystem(), and unregisterSubsystemsNow().
int Fun4AllServer::eventnumber protected
Definition at line 134 of file Fun4AllServer.h.
Referenced by EventNumber().
Fun4AllMemoryTracker* Fun4AllServer::ffamemtracker protected
Definition at line 123 of file Fun4AllServer.h.
Referenced by BeginRun(), PrintMemoryTracker(), process_event(), registerSubsystem(), and ~Fun4AllServer().
TH1* Fun4AllServer::FrameWorkVars protected
Definition at line 122 of file Fun4AllServer.h.
Referenced by InitAll(), and setRun().
std::vector<Fun4AllHistoManager *> Fun4AllServer::HistoManager protected
Definition at line 143 of file Fun4AllServer.h.
Referenced by dumpHistos(), getHistoManager(), Print(), registerHistoManager(), Reset(), and ~Fun4AllServer().
int Fun4AllServer::keep_db_connected protected
Definition at line 135 of file Fun4AllServer.h.
Referenced by BeginRun(), and KeepDBConnection().
int Fun4AllServer::OutNodeCount protected
Definition at line 129 of file Fun4AllServer.h.
Referenced by process_event().
std::vector<Fun4AllOutputManager *> Fun4AllServer::OutputManager protected
Definition at line 141 of file Fun4AllServer.h.
Referenced by End(), getOutputManager(), GetOutputManagerList(), outfileclose(), Print(), process_event(), registerOutputManager(), unregisterSubsystemsNow(), and ~Fun4AllServer().
std::vector<int> Fun4AllServer::RetCodes protected
Definition at line 140 of file Fun4AllServer.h.
Referenced by process_event(), registerSubsystem(), run(), and unregisterSubsystemsNow().
std::map<int, int> Fun4AllServer::retcodesmap protected
Definition at line 147 of file Fun4AllServer.h.
Referenced by process_event(), and retcodestats().
int Fun4AllServer::runnumber protected
Definition at line 133 of file Fun4AllServer.h.
Referenced by run().
int Fun4AllServer::ScreamEveryEvent protected
Definition at line 131 of file Fun4AllServer.h.
Referenced by AddComplaint(), End(), and process_event().
Fun4AllHistoManager* Fun4AllServer::ServerHistoManager protected
Definition at line 124 of file Fun4AllServer.h.
Referenced by dumpHistos(), getHisto(), getHistoName(), InitAll(), isHistoRegistered(), makeHisto(), and registerHisto().
std::vector<std::pair<SubsysReco *, PHCompositeNode *> > Fun4AllServer::Subsystems protected
Definition at line 138 of file Fun4AllServer.h.
Referenced by BeginRun(), End(), EndRun(), GetModuleList(), getSubsysReco(), Print(), process_event(), registerSubsystem(), Reset(), unregisterSubsystemsNow(), UpdateEventSelector(), and ~Fun4AllServer().
std::vector<Fun4AllSyncManager *> Fun4AllServer::SyncManagers protected
Definition at line 146 of file Fun4AllServer.h.
Referenced by BranchSelect(), fileclose(), fileopen(), getInputManager(), getSyncManager(), InitAll(), Print(), process_event(), registerSyncManager(), run(), setBranches(), skip(), and ~Fun4AllServer().
std::vector<TDirectory *> Fun4AllServer::TDirCollection protected
Definition at line 142 of file Fun4AllServer.h.
Referenced by registerSubsystem(), and ~Fun4AllServer().
std::map<const std::string, PHTimer> Fun4AllServer::timer_map protected
Definition at line 148 of file Fun4AllServer.h.
Referenced by PrintTimer(), process_event(), and registerSubsystem().
PHCompositeNode* Fun4AllServer::TopNode protected
Definition at line 126 of file Fun4AllServer.h.
Referenced by End(), InitAll(), NodeIdentify(), process_event(), and topNode().
std::map<std::string, PHCompositeNode *> Fun4AllServer::topnodemap protected
Definition at line 144 of file Fun4AllServer.h.
Referenced by AddTopNode(), GetTopNodes(), InitAll(), Print(), ResetNodeTree(), topNode(), and ~Fun4AllServer().
int Fun4AllServer::unregistersubsystem protected
Definition at line 132 of file Fun4AllServer.h.
Referenced by BeginRun(), process_event(), unregisterSubsystem(), and unregisterSubsystemsNow().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllServer.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllServer.cc