Analysis Software: Jet Class Reference
Jet Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/Jet.h>
Public Types
enum ALGO { NONE = 0, ANTIKT = 1, KT = 2, CAMBRIDGE = 3 }
enum SRC {
VOID = 0, PARTICLE = 1, TRACK = 2, CEMC_TOWER = 3,
CEMC_CLUSTER = 4, HCALIN_TOWER = 5, HCALIN_CLUSTER = 6, HCALOUT_TOWER = 7,
HCALOUT_CLUSTER = 8, FEMC_TOWER = 9, FEMC_CLUSTER = 10, FHCAL_TOWER = 11,
FHCAL_CLUSTER = 12, CEMC_TOWER_RETOWER = 13, CEMC_TOWER_SUB1 = 14, HCALIN_TOWER_SUB1 = 15,
HCALOUT_TOWER_SUB1 = 16, CEMC_TOWER_SUB1CS = 17, HCALIN_TOWER_SUB1CS = 18, HCALOUT_TOWER_SUB1CS = 19,
HEPMC_IMPORT = 20
}
enum PROPERTY { prop_JetCharge = 1, prop_BFrac = 2, prop_SeedD = 3, prop_SeedItr = 4 }
typedef std::multimap
< Jet::SRC, unsigned int > typ_comp_ids
typedef
typ_comp_ids::const_iterator ConstIter
typedef typ_comp_ids::iterator Iter
Public Member Functions
Jet ()
virtual ~Jet ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual float get_px () const
virtual void set_px (float px)
virtual float get_py () const
virtual void set_py (float py)
virtual float get_pz () const
virtual void set_pz (float pz)
virtual float get_e () const
virtual void set_e (float e)
virtual float get_p () const
virtual float get_pt () const
virtual float get_et () const
virtual float get_eta () const
virtual float get_phi () const
virtual float get_mass () const
virtual float get_mass2 () const
virtual bool has_property (Jet::PROPERTY prop_id) const
virtual float get_property (Jet::PROPERTY prop_id) const
virtual void set_property (Jet::PROPERTY prop_id, float value)
virtual void print_property (std::ostream &os) const
virtual bool empty_comp () const
virtual size_t size_comp () const
virtual size_t count_comp (Jet::SRC source) const
virtual void clear_comp ()
virtual void insert_comp (Jet::SRC source, unsigned int compid)
virtual size_t erase_comp (Jet::SRC source)
virtual void erase_comp (Iter iter)
virtual void erase_comp (Iter first, Iter last)
virtual ConstIter begin_comp () const
virtual ConstIter lower_bound_comp (Jet::SRC source) const
virtual ConstIter upper_bound_comp (Jet::SRC source) const
virtual ConstIter find (Jet::SRC source) const
virtual ConstIter end_comp () const
virtual Iter begin_comp ()
virtual Iter lower_bound_comp (Jet::SRC source)
virtual Iter upper_bound_comp (Jet::SRC source)
virtual Iter find (Jet::SRC source)
virtual Iter end_comp ()
ClassDef (Jet, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 11 of file Jet.h.
Member Enumeration Documentation
enum Jet::ALGO
Enumerator:
NONE
ANTIKT
KT
CAMBRIDGE
Definition at line 16 of file Jet.h.
enum Jet::PROPERTY
Enumerator:
prop_JetCharge
jet charge
prop_BFrac
b-jet fraction
prop_SeedD
discriminator D = max tower E / average E , used to identify seeds in 1st iteration of UE determination
prop_SeedItr
used to tag as seed jet in 1st or 2nd iteration of UE determination
Definition at line 49 of file Jet.h.
enum Jet::SRC
Enumerator:
VOID
PARTICLE
TRACK
CEMC_TOWER
CEMC_CLUSTER
HCALIN_TOWER
HCALIN_CLUSTER
HCALOUT_TOWER
HCALOUT_CLUSTER
FEMC_TOWER
FEMC_CLUSTER
FHCAL_TOWER
FHCAL_CLUSTER
CEMC_TOWER_RETOWER
CEMC_TOWER_SUB1
HCALIN_TOWER_SUB1
HCALOUT_TOWER_SUB1
CEMC_TOWER_SUB1CS
HCALIN_TOWER_SUB1CS
HCALOUT_TOWER_SUB1CS
HEPMC_IMPORT
Definition at line 24 of file Jet.h.
Constructor & Destructor Documentation
Jet::Jet () inline
Definition at line 67 of file Jet.h.
virtual Jet::~Jet () inline virtual
Definition at line 68 of file Jet.h.
Member Function Documentation
virtual PHObject* Jet::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in Jetv1.
Definition at line 73 of file Jet.h.
virtual float Jet::get_e () const inline virtual
Reimplemented in Jetv1.
Definition at line 89 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), CopyAndSubtractJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), MyJetAnalysis::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual float Jet::get_et () const inline virtual
Reimplemented in Jetv1.
Definition at line 94 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), JetHepMCLoader::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual float Jet::get_eta () const inline virtual
Reimplemented in Jetv1.
Definition at line 95 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), HFJetTruthTrigger::hadron_tagging(), QAG4SimulationJet::jet_acceptance_cut(), SoftLeptonTaggingTruth::jet_acceptance_cut(), HFJetTruthTrigger::parton_tagging(), BJetModule::process_event(), HFJetTruthTrigger::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), PHG4DSTReader::process_event(), MyJetAnalysis::process_event(), JetHepMCLoader::process_event(), BDiJetModule::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual unsigned int Jet::get_id () const inline virtual
Reimplemented in Jetv1.
Definition at line 77 of file Jet.h.
Referenced by JetRecoEval::all_jets_from(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), JetMapv1::JetMapv1(), JetMapv1::operator=(), PhotonJet::process_event(), MyJetAnalysis::process_event(), BDiJetModule::process_event(), JetRecoEval::unique_reco_jet_from_truth(), and JetRecoEval::unique_truth_jet_from_reco().
virtual float Jet::get_mass () const inline virtual
Reimplemented in Jetv1.
Definition at line 97 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TruthPhotonJet::process_event(), PhotonJet::process_event(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual float Jet::get_mass2 () const inline virtual
Reimplemented in Jetv1.
Definition at line 98 of file Jet.h.
virtual float Jet::get_p () const inline virtual
Reimplemented in Jetv1.
Definition at line 92 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), TruthPhotonJet::process_event(), and PhotonJet::process_event().
virtual float Jet::get_phi () const inline virtual
Reimplemented in Jetv1.
Definition at line 96 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), HFJetTruthTrigger::hadron_tagging(), HFJetTruthTrigger::parton_tagging(), BJetModule::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), TruthPhotonJet::process_event(), PHG4DSTReader::process_event(), PhotonJet::process_event(), MyJetAnalysis::process_event(), BDiJetModule::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual float Jet::get_property (Jet::PROPERTY prop_id) const inline virtual
Reimplemented in Jetv1.
Definition at line 103 of file Jet.h.
Referenced by BJetModule::process_event(), and BDiJetModule::process_event().
virtual float Jet::get_pt () const inline virtual
Reimplemented in Jetv1.
Definition at line 93 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), TreeMaker::CopyAndMakeJets(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), TreeMaker::GetRecoJets(), AnaTutorial::getReconstructedJets(), TreeMaker::GetTruthJets(), AnaTutorial::getTruthJets(), HFJetTruthTrigger::hadron_tagging(), HFJetTruthTrigger::parton_tagging(), HFJetTruthTrigger::process_event(), BJetModule::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), TruthPhotonJet::process_event(), PHG4DSTReader::process_event(), PhotonJet::process_event(), MyJetAnalysis::process_event(), and BDiJetModule::process_event().
virtual float Jet::get_px () const inline virtual
Reimplemented in Jetv1.
Definition at line 80 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), CopyAndSubtractJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual float Jet::get_py () const inline virtual
Reimplemented in Jetv1.
Definition at line 83 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), CopyAndSubtractJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual float Jet::get_pz () const inline virtual
Reimplemented in Jetv1.
Definition at line 86 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), FastJetAlgoSub::get_jets(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), AnaTutorial::getReconstructedJets(), AnaTutorial::getTruthJets(), CopyAndSubtractJets::process_event(), TruthPhotonJet::process_event(), PhotonJet::process_event(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual bool Jet::has_property (Jet::PROPERTY prop_id) const inline virtual
Reimplemented in Jetv1.
Definition at line 102 of file Jet.h.
Referenced by BDiJetModule::process_event().
void Jet::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in Jetv1.
Definition at line 7 of file Jet.cc.
Referenced by HFJetTruthTrigger::process_event(), MyJetAnalysis::process_event(), QAG4SimulationJet::process_Spectrum(), SoftLeptonTaggingTruth::process_Spectrum(), and QAG4SimulationJet::process_TruthMatching().
virtual int Jet::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in Jetv1.
Definition at line 72 of file Jet.h.
virtual void Jet::print_property (std::ostream & os) const inline virtual
Reimplemented in Jetv1.
Definition at line 105 of file Jet.h.
virtual void Jet::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in Jetv1.
Definition at line 71 of file Jet.h.
virtual void Jet::set_e (float e) inline virtual
Reimplemented in Jetv1.
Definition at line 90 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), CopyAndSubtractJets::process_event(), and JetHepMCLoader::process_event().
virtual void Jet::set_id (unsigned int id) inline virtual
Reimplemented in Jetv1.
Definition at line 78 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), and CopyAndSubtractJets::process_event().
virtual void Jet::set_property (Jet::PROPERTY prop_id, float value) inline virtual
Reimplemented in Jetv1.
Definition at line 104 of file Jet.h.
Referenced by HFJetTruthTrigger::hadron_tagging(), HFJetTruthTrigger::parton_tagging(), and DetermineTowerBackground::process_event().
virtual void Jet::set_px (float px) inline virtual
Reimplemented in Jetv1.
Definition at line 81 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), CopyAndSubtractJets::process_event(), and JetHepMCLoader::process_event().
virtual void Jet::set_py (float py) inline virtual
Reimplemented in Jetv1.
Definition at line 84 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), CopyAndSubtractJets::process_event(), and JetHepMCLoader::process_event().
virtual void Jet::set_pz (float pz) inline virtual
Reimplemented in Jetv1.
Definition at line 87 of file Jet.h.
Referenced by TreeMaker::CopyAndMakeJets(), TrackJetInput::get_input(), TowerJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), CopyAndSubtractJets::process_event(), and JetHepMCLoader::process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/Jet.h
coresoftware/blob/master/simulation/g4simulation/g4jets/Jet.cc