Analysis Software: MyTClonesArray Class Reference
MyTClonesArray Class Reference
#include <tutorials/blob/master/MyOwnTTree/src/MyTClonesArray.h>
Public Member Functions
MyTClonesArray ()
virtual ~MyTClonesArray ()
void Reset ()
Clear Event.
MySimpleTree * GetNewItem ()
MySimpleTree * GetItem (const unsigned int i) const
int Entries ()
void MyEventInt (const int i)
int MyEventInt () const
void MyEventFloat (const float f)
float MyEventFloat () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int myeventint
float myeventfloat
TClonesArray * MyTCArray
Detailed Description
Definition at line 15 of file MyTClonesArray.h.
Constructor & Destructor Documentation
MyTClonesArray::MyTClonesArray ()
Definition at line 25 of file MyTClonesArray.cc.
MyTClonesArray::~MyTClonesArray () virtual
Definition at line 33 of file MyTClonesArray.cc.
References MyTCArray, and return().
Member Function Documentation
int MyTClonesArray::Entries ()
Definition at line 95 of file MyTClonesArray.cc.
References MyTCArray.
Referenced by AnalyzeSimpleTree::process_event().
MySimpleTree * MyTClonesArray::GetItem (const unsigned int i) const
Definition at line 81 of file MyTClonesArray.cc.
References MyTCArray, and PHWHERE.
Referenced by AnalyzeSimpleTree::process_event().
MySimpleTree * MyTClonesArray::GetNewItem ()
Definition at line 64 of file MyTClonesArray.cc.
References DEFAULTSIZE, and MyTCArray.
Referenced by MakeSimpleTree::process_event().
void MyTClonesArray::MyEventFloat (const float f) inline
Definition at line 27 of file MyTClonesArray.h.
References myeventfloat.
Referenced by MakeSimpleTree::process_event().
float MyTClonesArray::MyEventFloat () const inline
Definition at line 28 of file MyTClonesArray.h.
References myeventfloat.
void MyTClonesArray::MyEventInt (const int i) inline
Definition at line 25 of file MyTClonesArray.h.
References i, and myeventint.
Referenced by MakeSimpleTree::process_event().
int MyTClonesArray::MyEventInt () const inline
Definition at line 26 of file MyTClonesArray.h.
References myeventint.
void MyTClonesArray::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 45 of file MyTClonesArray.cc.
References DEFAULTSIZE, myeventfloat, myeventint, MyTCArray, and return().
Member Data Documentation
float MyTClonesArray::myeventfloat protected
Definition at line 32 of file MyTClonesArray.h.
Referenced by MyEventFloat(), and Reset().
int MyTClonesArray::myeventint protected
Definition at line 31 of file MyTClonesArray.h.
Referenced by MyEventInt(), and Reset().
TClonesArray* MyTClonesArray::MyTCArray protected
Definition at line 33 of file MyTClonesArray.h.
Referenced by Entries(), GetItem(), GetNewItem(), Reset(), and ~MyTClonesArray().
The documentation for this class was generated from the following files:
tutorials/blob/master/MyOwnTTree/src/MyTClonesArray.h
tutorials/blob/master/MyOwnTTree/src/MyTClonesArray.cc