Analysis Software: TrkrHit Class Reference
TrkrHit Class Reference
Base class for hit object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHit.h>
Public Member Functions
TrkrHit ()
ctor
virtual ~TrkrHit ()
dtor
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
void addEnergy (const double edep)
double getEnergy ()
void setAdc (const unsigned int adc)
unsigned int getAdc ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
ClassDef (TrkrHit, 1)
Protected Attributes
double m_edep
unsigned int m_adc
Detailed Description
Base class for hit object.
This is the empyt virtual base class for a hit object. Each subsystem should implement an inherited version which contains the actual storage information.
Definition at line 21 of file TrkrHit.h.
Constructor & Destructor Documentation
TrkrHit::TrkrHit ()
ctor
Definition at line 3 of file TrkrHit.cc.
virtual TrkrHit::~TrkrHit () inline virtual
dtor
Definition at line 28 of file TrkrHit.h.
Member Function Documentation
void TrkrHit::addEnergy (const double edep) inline
Definition at line 37 of file TrkrHit.h.
References m_edep.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4MvtxHitReco::process_event(), PHG4InttHitReco::process_event(), and PHG4TpcElectronDrift::process_event().
TrkrHit::ClassDef (TrkrHit , 1) protected
unsigned int TrkrHit::getAdc () inline
Definition at line 40 of file TrkrHit.h.
References m_adc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), SvtxEvaluator::fillOutputNtuples(), PHG4TpcElectronDrift::process_event(), and DumpTrkrHitSetContainer::process_Node().
double TrkrHit::getEnergy () inline
Definition at line 38 of file TrkrHit.h.
References m_edep.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), SvtxEvaluator::fillOutputNtuples(), PHG4TpcElectronDrift::process_event(), and DumpTrkrHitSetContainer::process_Node().
virtual void TrkrHit::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in InttHit, MvtxHit, and TpcHit.
Definition at line 30 of file TrkrHit.h.
References os.
Referenced by PHG4InttDigitizer::DigitizeLadderCells().
virtual int TrkrHit::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in InttHit, MvtxHit, and TpcHit.
Definition at line 35 of file TrkrHit.h.
virtual void TrkrHit::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in InttHit, MvtxHit, and TpcHit.
Definition at line 34 of file TrkrHit.h.
Referenced by InttHit::Reset(), TpcHit::Reset(), and MvtxHit::Reset().
void TrkrHit::setAdc (const unsigned int adc) inline
Definition at line 39 of file TrkrHit.h.
References m_adc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), and PHG4MvtxDigitizer::DigitizeMvtxLadderCells().
Member Data Documentation
unsigned int TrkrHit::m_adc protected
Definition at line 44 of file TrkrHit.h.
Referenced by getAdc(), and setAdc().
double TrkrHit::m_edep protected
Definition at line 43 of file TrkrHit.h.
Referenced by addEnergy(), and getEnergy().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHit.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHit.cc