Analysis Software: GenFitTrackProp Class Reference
GenFitTrackProp Class Reference
#include <analysis/blob/master/Tracking/GenFitTrackProp/GenFitTrackProp.h>
Public Member Functions
GenFitTrackProp (const std::string &name="GenFitTrackProp", const int pid_guess=211)
Default constructor.
int Init (PHCompositeNode *)
Initialization, called for initialization.
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
Process Event, called for each event.
int End (PHCompositeNode *)
End, write and close files.
void set_filename (const char *file)
Change output filename.
int get_pid_guess () const
void set_pid_guess (int pidGuess)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *)
Get all the nodes.
void fill_tree (PHCompositeNode *)
void reset_variables ()
Private Attributes
PHG4TruthInfoContainer * _truth_container
Node pointers.
SvtxTrackMap * _trackmap
int _event
event processed
SvtxEvalStack * _svtxevalstack
PHGenFit::Fitter * _fitter
Needed to initialize genfit::FieldManager and genfit::MaterialEffect.
std::string _track_fitting_alg_name
bool _do_evt_display
int _pid_guess
std::string _outfile_name
output filename
TTree * _eval_tree_tracks
Eval TTrees.
int event
int gtrackID
truth track info
int gflavor
double gpx
double gpy
double gpz
double gpt
double geta
double gvx
double gvy
double gvz
int trackID
reco info
int charge
int nhits
double px
double py
double pz
double pt
double dca2d
double radius80
double pathlength80
double pathlength85
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 40 of file GenFitTrackProp.h.
Constructor & Destructor Documentation
GenFitTrackProp::GenFitTrackProp (const std::string & name = "GenFitTrackProp", const int pid_guess = 211)
Default constructor.
Definition at line 61 of file GenFitTrackProp.cc.
References _event.
Member Function Documentation
int GenFitTrackProp::End (PHCompositeNode * topNode) virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 117 of file GenFitTrackProp.cc.
References _eval_tree_tracks, _fitter, _outfile_name, _svtxevalstack, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, and PHTFileServer::get().
void GenFitTrackProp::fill_tree (PHCompositeNode * topNode) private
Fill the trees with truth, track fit, and cluster information
Truth information
Definition at line 174 of file GenFitTrackProp.cc.
References _eval_tree_tracks, _event, _pid_guess, _svtxevalstack, _trackmap, _truth_container, SvtxTrackMap::begin(), charge, dca2d, SvtxTrackMap::end(), SvtxTrack::end_states(), SvtxTrack::get_charge(), SvtxTrack::get_dca2d(), SvtxTrackState::get_error(), SvtxTrack::get_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrackState::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrackState::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrackState::get_pz(), SvtxTrack::get_pz(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), gflavor, gpt, gpx, gpy, gpz, gtrackID, i, j, LogError, SvtxTrackEval::max_truth_particle_by_nclusters(), nhits, pathlength80, pathlength85, pos, pt, px, py, pz, radius80, reset_variables(), SvtxTrack::size_clusters(), and trackID.
Referenced by process_event().
int GenFitTrackProp::get_pid_guess () const inline
Definition at line 61 of file GenFitTrackProp.h.
References _pid_guess.
int GenFitTrackProp::GetNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 317 of file GenFitTrackProp.cc.
References _event, _trackmap, _truth_container, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
int GenFitTrackProp::Init (PHCompositeNode * topNode) virtual
Initialization, called for initialization.
Reimplemented from SubsysReco.
Definition at line 78 of file GenFitTrackProp.cc.
References _eval_tree_tracks, _outfile_name, charge, dca2d, event, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), gflavor, gpt, gpx, gpy, gpz, gtrackID, gvx, gvy, gvz, nhits, PHTFileServer::open(), pathlength80, pathlength85, PHWHERE, pt, px, py, pz, radius80, and trackID.
int GenFitTrackProp::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 132 of file GenFitTrackProp.cc.
References _do_evt_display, _fitter, _track_fitting_alg_name, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), PHWHERE, PHGenFit::Fitter::set_verbosity(), and verbosity.
int GenFitTrackProp::process_event (PHCompositeNode * topNode) virtual
Process Event, called for each event.
Reimplemented from SubsysReco.
Definition at line 151 of file GenFitTrackProp.cc.
References _event, _svtxevalstack, Fun4AllReturnCodes::EVENT_OK, fill_tree(), GetNodes(), SvtxEvalStack::next_event(), PHWHERE, SvtxEvalStack::set_verbosity(), and verbosity.
void GenFitTrackProp::reset_variables () private
Reset all the tree variables to their default values. Needs to be called at the start of every event
Definition at line 294 of file GenFitTrackProp.cc.
References charge, dca2d, gflavor, gpx, gpy, gpz, gtrackID, gvx, gvy, gvz, nhits, px, py, pz, and trackID.
Referenced by fill_tree().
void GenFitTrackProp::set_filename (const char * file) inline
Change output filename.
Definition at line 58 of file GenFitTrackProp.h.
References _outfile_name, and file.
void GenFitTrackProp::set_pid_guess (int pidGuess) inline
Definition at line 65 of file GenFitTrackProp.h.
References _pid_guess.
Member Data Documentation
bool GenFitTrackProp::_do_evt_display private
Definition at line 103 of file GenFitTrackProp.h.
Referenced by InitRun().
TTree* GenFitTrackProp::_eval_tree_tracks private
Eval TTrees.
Definition at line 116 of file GenFitTrackProp.h.
Referenced by End(), fill_tree(), and Init().
int GenFitTrackProp::_event private
event processed
Processing
Definition at line 92 of file GenFitTrackProp.h.
Referenced by fill_tree(), GenFitTrackProp(), GetNodes(), and process_event().
PHGenFit::Fitter* GenFitTrackProp::_fitter private
Needed to initialize genfit::FieldManager and genfit::MaterialEffect.
Definition at line 99 of file GenFitTrackProp.h.
Referenced by End(), and InitRun().
std::string GenFitTrackProp::_outfile_name private
output filename
Output
Definition at line 113 of file GenFitTrackProp.h.
Referenced by End(), Init(), and set_filename().
int GenFitTrackProp::_pid_guess private
Definition at line 106 of file GenFitTrackProp.h.
Referenced by fill_tree(), get_pid_guess(), and set_pid_guess().
SvtxEvalStack* GenFitTrackProp::_svtxevalstack private
Definition at line 96 of file GenFitTrackProp.h.
Referenced by End(), fill_tree(), and process_event().
std::string GenFitTrackProp::_track_fitting_alg_name private
Definition at line 101 of file GenFitTrackProp.h.
Referenced by InitRun().
SvtxTrackMap* GenFitTrackProp::_trackmap private
Definition at line 85 of file GenFitTrackProp.h.
Referenced by fill_tree(), and GetNodes().
PHG4TruthInfoContainer* GenFitTrackProp::_truth_container private
Node pointers.
Input
Definition at line 84 of file GenFitTrackProp.h.
Referenced by fill_tree(), and GetNodes().
int GenFitTrackProp::charge private
Definition at line 137 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::dca2d private
Definition at line 145 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
int GenFitTrackProp::event private
Definition at line 118 of file GenFitTrackProp.h.
Referenced by Init().
double GenFitTrackProp::geta private
Definition at line 129 of file GenFitTrackProp.h.
int GenFitTrackProp::gflavor private
Definition at line 122 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::gpt private
Definition at line 128 of file GenFitTrackProp.h.
Referenced by fill_tree(), and Init().
double GenFitTrackProp::gpx private
Definition at line 124 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::gpy private
Definition at line 125 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::gpz private
Definition at line 126 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
int GenFitTrackProp::gtrackID private
truth track info
Definition at line 121 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::gvx private
Definition at line 131 of file GenFitTrackProp.h.
Referenced by Init(), and reset_variables().
double GenFitTrackProp::gvy private
Definition at line 132 of file GenFitTrackProp.h.
Referenced by Init(), and reset_variables().
double GenFitTrackProp::gvz private
Definition at line 133 of file GenFitTrackProp.h.
Referenced by Init(), and reset_variables().
int GenFitTrackProp::nhits private
Definition at line 138 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::pathlength80 private
Definition at line 148 of file GenFitTrackProp.h.
Referenced by fill_tree(), and Init().
double GenFitTrackProp::pathlength85 private
Definition at line 149 of file GenFitTrackProp.h.
Referenced by fill_tree(), and Init().
double GenFitTrackProp::pt private
Definition at line 143 of file GenFitTrackProp.h.
Referenced by fill_tree(), and Init().
double GenFitTrackProp::px private
Definition at line 140 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::py private
Definition at line 141 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::pz private
Definition at line 142 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
double GenFitTrackProp::radius80 private
Definition at line 147 of file GenFitTrackProp.h.
Referenced by fill_tree(), and Init().
int GenFitTrackProp::trackID private
reco info
Definition at line 136 of file GenFitTrackProp.h.
Referenced by fill_tree(), Init(), and reset_variables().
The documentation for this class was generated from the following files:
analysis/blob/master/Tracking/GenFitTrackProp/GenFitTrackProp.h
analysis/blob/master/Tracking/GenFitTrackProp/GenFitTrackProp.cc