Analysis Software: sChargeMap Class Reference
sChargeMap Class Reference
#include <analysis/blob/master/TPC/SCDCorrections/sChargeMap.h>
Public Member Functions
sChargeMap (int, float, float, int, float, float, int, float, float, float)
virtual ~sChargeMap ()
void Fill (float, float, float, float)
void Propagate (float)
void ScreenShot (char *, char *, int)
void SaveIonMap (char *)
void SaveRho (char *, int, int, int)
Protected Attributes
TH3D * fI
TH3D * fE
float fEcmperus
float fIcmperms
Detailed Description
Definition at line 9 of file sChargeMap.h.
Constructor & Destructor Documentation
sChargeMap::sChargeMap (int nr, float rmin, float rmax, int np, float pmin, float pmax, int nz, float hz, float ev, float iv)
Definition at line 11 of file sChargeMap.cxx.
References fE, and fI.
virtual sChargeMap::~sChargeMap () inline virtual
Definition at line 12 of file sChargeMap.h.
Member Function Documentation
void sChargeMap::Fill (float r, float p, float z, float w)
Definition at line 87 of file sChargeMap.cxx.
References fE, and fI.
Referenced by main().
void sChargeMap::Propagate (float ms)
Definition at line 95 of file sChargeMap.cxx.
References fE, fEcmperus, fI, fIcmperms, and printf().
Referenced by main().
void sChargeMap::SaveIonMap (char * name)
Definition at line 46 of file sChargeMap.cxx.
References fI.
Referenced by main().
void sChargeMap::SaveRho (char * name, int nrad, int nphi, int nhz)
Definition at line 50 of file sChargeMap.cxx.
References fI, i, j, k, n, and TwoPi.
void sChargeMap::ScreenShot (char * name, char * ext, int n)
Definition at line 21 of file sChargeMap.cxx.
References fE, fI, main(), tmp1, and tmp2.
Referenced by main().
Member Data Documentation
TH3D* sChargeMap::fE protected
Definition at line 21 of file sChargeMap.h.
Referenced by Fill(), Propagate(), sChargeMap(), and ScreenShot().
float sChargeMap::fEcmperus protected
Definition at line 22 of file sChargeMap.h.
Referenced by Propagate().
TH3D* sChargeMap::fI protected
Definition at line 20 of file sChargeMap.h.
Referenced by Fill(), Propagate(), SaveIonMap(), SaveRho(), sChargeMap(), and ScreenShot().
float sChargeMap::fIcmperms protected
Definition at line 23 of file sChargeMap.h.
Referenced by Propagate().
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/SCDCorrections/sChargeMap.h
analysis/blob/master/TPC/SCDCorrections/sChargeMap.cxx