Analysis Software: PHGenFit::Measurement Class Reference
PHGenFit::Measurement Class Reference
#include <coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Measurement.h>
Public Member Functions
Measurement ()
ctor
~Measurement ()
dtor
genfit::AbsMeasurement * getMeasurement ()
unsigned int get_cluster_ID () const
void set_cluster_ID (unsigned int clusterId)
TrkrDefs::cluskey get_cluster_key () const
void set_cluster_key (TrkrDefs::cluskey clusterkey)
Protected Attributes
genfit::AbsMeasurement * _measurement
unsigned int _clusterID
TrkrDefs::cluskey _clusterkey
Detailed Description
Definition at line 17 of file Measurement.h.
Constructor & Destructor Documentation
PHGenFit::Measurement::Measurement () inline
ctor
Definition at line 21 of file Measurement.h.
PHGenFit::Measurement::~Measurement () inline
dtor
Definition at line 26 of file Measurement.h.
Member Function Documentation
unsigned int PHGenFit::Measurement::get_cluster_ID () const inline
Definition at line 35 of file Measurement.h.
References _clusterID.
Referenced by PHGenFit::Track::addMeasurement().
TrkrDefs::cluskey PHGenFit::Measurement::get_cluster_key () const inline
Definition at line 45 of file Measurement.h.
References _clusterkey.
Referenced by PHGenFit::Track::addMeasurement().
genfit::AbsMeasurement* PHGenFit::Measurement::getMeasurement () inline
Definition at line 29 of file Measurement.h.
References _measurement.
Referenced by PHGenFit::Track::addMeasurement(), PHGenFitTrkFitter::ReFitTrack(), and TpcPrototypeGenFitTrkFitter::ReFitTrack().
void PHGenFit::Measurement::set_cluster_ID (unsigned int clusterId) inline
Definition at line 39 of file Measurement.h.
References _clusterID.
void PHGenFit::Measurement::set_cluster_key (TrkrDefs::cluskey clusterkey) inline
Definition at line 49 of file Measurement.h.
References _clusterkey.
Referenced by PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
Member Data Documentation
unsigned int PHGenFit::Measurement::_clusterID protected
Definition at line 56 of file Measurement.h.
Referenced by get_cluster_ID(), and set_cluster_ID().
TrkrDefs::cluskey PHGenFit::Measurement::_clusterkey protected
Definition at line 57 of file Measurement.h.
Referenced by get_cluster_key(), and set_cluster_key().
genfit::AbsMeasurement* PHGenFit::Measurement::_measurement protected
Definition at line 55 of file Measurement.h.
Referenced by getMeasurement(), PHGenFit::PlanarMeasurement::init(), and PHGenFit::SpacepointMeasurement::init().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Measurement.h