Analysis Software: PJTranslator Class Reference
PJTranslator Class Reference
#include <analysis/blob/master/sPhenixAj/src/PJTranslator.h>
Public Member Functions
PJTranslator (const std::string &name="PJTranslator")
virtual ~PJTranslator ()
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int get_matched (double clus_energy, double track_energy)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PJContainer * particles
TF1 * match_tolerance_low
TF1 * match_tolerance_high
Static Private Attributes
static const float sfEMCAL = 0.03
static const float sfHCALIN = 0.071
static const float sfHCALOUT = 0.04
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 28 of file PJTranslator.h.
Constructor & Destructor Documentation
PJTranslator::PJTranslator (const std::string & name = "PJTranslator")
Definition at line 43 of file PJTranslator.cc.
References match_tolerance_high, and match_tolerance_low.
PJTranslator::~PJTranslator () virtual
Definition at line 63 of file PJTranslator.cc.
Member Function Documentation
int PJTranslator::get_matched (double clus_energy, double track_energy)
Definition at line 344 of file PJTranslator.cc.
References match_tolerance_high, and match_tolerance_low.
int PJTranslator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
: Create your own composite node, then attach to it.
Reimplemented from SubsysReco.
Definition at line 70 of file PJTranslator.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and particles.
int PJTranslator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
For EMCAL jets - Add kinematic cuts, add quality cuts, - add corrections
For HCALIN jets - Add kinematic cuts, add quality cuts, - add corrections
For HCALOUT jets - Add kinematic cuts, add quality cuts, - add corrections
Reimplemented from SubsysReco.
Definition at line 101 of file PJTranslator.cc.
References Fun4AllReturnCodes::ABORTRUN, assert, GlobalVertexMap::begin(), SvtxTrackMap::begin(), PJContainer::data, GlobalVertexMap::empty(), SvtxTrackMap::end(), energy, GlobalVertex::get_x(), GlobalVertex::get_y(), GlobalVertex::get_z(), RawClusterContainer::getCluster(), RawClusterUtility::GetEVec(), i, M_PI, particles, phi, sfEMCAL, sfHCALIN, sfHCALOUT, SvtxTrackMap::size(), and RawClusterContainer::size().
Member Data Documentation
TF1* PJTranslator::match_tolerance_high private
Definition at line 55 of file PJTranslator.h.
Referenced by get_matched(), and PJTranslator().
TF1* PJTranslator::match_tolerance_low private
Definition at line 54 of file PJTranslator.h.
Referenced by get_matched(), and PJTranslator().
PJContainer* PJTranslator::particles private
Definition at line 45 of file PJTranslator.h.
Referenced by Init(), and process_event().
const float PJTranslator::sfEMCAL = 0.03 static private
Definition at line 49 of file PJTranslator.h.
Referenced by process_event().
const float PJTranslator::sfHCALIN = 0.071 static private
Definition at line 50 of file PJTranslator.h.
Referenced by process_event().
const float PJTranslator::sfHCALOUT = 0.04 static private
Definition at line 51 of file PJTranslator.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/sPhenixAj/src/PJTranslator.h
analysis/blob/master/sPhenixAj/src/PJTranslator.cc