Analysis Software: analysis/blob/master/EMCal-analysis/macro/DrawEcal.C File Reference
DrawEcal.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawEcal (void)
void DrawEnergyDensity (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title="HIJING Au+Au 0-10% C + Geant4")
void DrawEnergyDensityXY (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title="HIJING Au+Au 0-10% C + Geant4")
void DrawTower_EMCTrigEff (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/")
void DrawTower_EMCTrigEff_SlideingWindow2 (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/")
TGraphErrors * Distribution2Efficiency (TH1F *hCEMC3_Max)
void DrawTower_EMCDistribution (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title="HIJING Au+Au 0-10% C + Geant4 + Digi.")
void DrawTower_EMCDistribution5x5 (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title="HIJING Au+Au 0-10% C + Geant4 + Digi.")
TH1 * DrawTower_Load (const TString infile="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString hist_name="EMCalAna_h_CEMC_TOWER_1x1")
void DrawCluster_Linearality (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config="")
void DrawCluster_Res_2Fit (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config="")
void DrawCluster_Res_2Fit_Electron_NoSVX (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config="")
void DrawCluster_Res_2Fit_1DSpacalNoSVX (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config="")
void DrawCluster_Res_2Fit_1DSpacalNoSVX_Eta3 (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config="")
void DrawCluster_Res_2Fit_2DSpacalNoSVX (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config="")
void DrawCluster_Res (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config="")
TGraphErrors * DrawCluster_AnaP (const TString config="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal1d_1dtower/zerofield/G4Hits_sPHENIX", const TString particle="gamma_eta0.90", bool mean_or_res=false)
TVectorD DrawCluster_SingleE (const TString config="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal2d/zerofield/G4Hits_sPHENIX", const TString particle="gamma_eta0", const double e=8)
void DrawTowerSum_Res_2Fit_1DSpacalNoSVX (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config="")
void DrawTowerSum_Res_2Fit_1DSpacalNoSVX_Eta3 (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config="")
TGraphErrors * DrawTowerSum_AnaP (const TString config="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/nosvtx/spacal1d/fieldmap/G4Hits_sPHENIX", const TString particle="e-_eta0", bool mean_or_res=false)
TVectorD DrawTowerSum_SingleE (const TString config="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/nosvtx/spacal1d/fieldmap/G4Hits_sPHENIX", const TString particle="e-_eta0", const double e=8)
void DrawSF (const TString base="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config="")
TGraphErrors * Load_CurveSet (const TString config="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal2d/zerofield/G4Hits_sPHENIX_gamma", const TString energy="24GeV")
TVectorD Load_SF (const TString eta_bin="eta0", const TString config="/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal1d/zerofield/G4Hits_sPHENIX_gamma", const TString energy="24GeV")
Function Documentation
TGraphErrors* Distribution2Efficiency (TH1F * hCEMC3_Max)
Definition at line 662 of file DrawEcal.C.
References A, assert, i, n, and z.
Referenced by DrawTower_EMCTrigEff(), DrawTower_EMCTrigEff_SlideingWindow2(), Edep_Checks(), Edep_LL_Distribution(), Ep_Checks(), EP_LL_Distribution(), GetSimRejCurve(), MakeRadiusCut(), and RejectionCompare().
TGraphErrors* DrawCluster_AnaP (const TString config = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal1d_1dtower/zerofield/G4Hits_sPHENIX", const TString particle = "gamma_eta0.90", bool mean_or_res = false)
Definition at line 2069 of file DrawEcal.C.
References DrawCluster_SingleE(), fit(), i, and N.
Referenced by DrawCluster_Linearality(), DrawCluster_Res(), DrawCluster_Res_2Fit(), DrawCluster_Res_2Fit_1DSpacalNoSVX(), DrawCluster_Res_2Fit_1DSpacalNoSVX_Eta3(), DrawCluster_Res_2Fit_2DSpacalNoSVX(), and DrawCluster_Res_2Fit_Electron_NoSVX().
void DrawCluster_Linearality (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config = "")
Definition at line 872 of file DrawEcal.C.
References DrawCluster_AnaP(), i, and SaveCanvas().
void DrawCluster_Res (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config = "")
Definition at line 1946 of file DrawEcal.C.
References DrawCluster_AnaP(), and SaveCanvas().
void DrawCluster_Res_2Fit (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config = "")
Definition at line 1048 of file DrawEcal.C.
References DrawCluster_AnaP(), entry, SaveCanvas(), and t.
void DrawCluster_Res_2Fit_1DSpacalNoSVX (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config = "")
Definition at line 1424 of file DrawEcal.C.
References DrawCluster_AnaP(), entry, and SaveCanvas().
void DrawCluster_Res_2Fit_1DSpacalNoSVX_Eta3 (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config = "")
Definition at line 1622 of file DrawEcal.C.
References DrawCluster_AnaP(), entry, and SaveCanvas().
void DrawCluster_Res_2Fit_2DSpacalNoSVX (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config = "")
Definition at line 1748 of file DrawEcal.C.
References DrawCluster_AnaP(), entry, and SaveCanvas().
void DrawCluster_Res_2Fit_Electron_NoSVX (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config = "")
Definition at line 1240 of file DrawEcal.C.
References DrawCluster_AnaP(), entry, SaveCanvas(), and t.
TVectorD DrawCluster_SingleE (const TString config = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal2d/zerofield/G4Hits_sPHENIX", const TString particle = "gamma_eta0", const double e = 8)
Definition at line 2131 of file DrawEcal.C.
References assert, and rms().
Referenced by DrawCluster_AnaP().
void DrawEcal (void)
Definition at line 12 of file DrawEcal.C.
References SetOKStyle().
void DrawEnergyDensity (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title = "HIJING Au+Au 0-10% C + Geant4")
Definition at line 65 of file DrawEcal.C.
References DrawTower_Load(), r, SaveCanvas(), t, title, and z.
void DrawEnergyDensityXY (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title = "HIJING Au+Au 0-10% C + Geant4")
Definition at line 113 of file DrawEcal.C.
References DrawTower_Load(), SaveCanvas(), t, and title.
void DrawSF (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/", const TString config = "")
Definition at line 2602 of file DrawEcal.C.
References Load_CurveSet(), and SaveCanvas().
void DrawTower_EMCDistribution (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title = "HIJING Au+Au 0-10% C + Geant4 + Digi.")
Definition at line 701 of file DrawEcal.C.
References DrawTower_Load(), SaveCanvas(), t, and title.
void DrawTower_EMCDistribution5x5 (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString title = "HIJING Au+Au 0-10% C + Geant4 + Digi.")
Definition at line 763 of file DrawEcal.C.
References DrawTower_Load(), SaveCanvas(), t, and title.
void DrawTower_EMCTrigEff (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/")
Definition at line 163 of file DrawEcal.C.
References Distribution2Efficiency(), DrawTower_Load(), i, SaveCanvas(), t, and y_max.
void DrawTower_EMCTrigEff_SlideingWindow2 (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/")
Definition at line 412 of file DrawEcal.C.
References Distribution2Efficiency(), DrawTower_Load(), i, SaveCanvas(), t, and y_max.
TH1* DrawTower_Load (const TString infile = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/sHijing/spacal2d/G4Hits_sPHENIX_sHijing-0-4.4fm_ALL.root_EMCalAna.root", const TString hist_name = "EMCalAna_h_CEMC_TOWER_1x1")
Definition at line 825 of file DrawEcal.C.
References assert, SVM_v1::h, n, and t.
Referenced by DrawEnergyDensity(), DrawEnergyDensityXY(), DrawTower_EMCDistribution(), DrawTower_EMCDistribution5x5(), DrawTower_EMCTrigEff(), and DrawTower_EMCTrigEff_SlideingWindow2().
TGraphErrors* DrawTowerSum_AnaP (const TString config = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/nosvtx/spacal1d/fieldmap/G4Hits_sPHENIX", const TString particle = "e-_eta0", bool mean_or_res = false)
Definition at line 2481 of file DrawEcal.C.
References DrawTowerSum_SingleE(), fit(), i, and N.
Referenced by DrawTowerSum_Res_2Fit_1DSpacalNoSVX(), and DrawTowerSum_Res_2Fit_1DSpacalNoSVX_Eta3().
void DrawTowerSum_Res_2Fit_1DSpacalNoSVX (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config = "")
Definition at line 2192 of file DrawEcal.C.
References DrawTowerSum_AnaP(), entry, and SaveCanvas().
void DrawTowerSum_Res_2Fit_1DSpacalNoSVX_Eta3 (const TString base = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/", const TString config = "")
Definition at line 2370 of file DrawEcal.C.
References DrawTowerSum_AnaP(), entry, and SaveCanvas().
TVectorD DrawTowerSum_SingleE (const TString config = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/production_analysis/emcstudies/nosvtx/spacal1d/fieldmap/G4Hits_sPHENIX", const TString particle = "e-_eta0", const double e = 8)
Definition at line 2542 of file DrawEcal.C.
References assert, rms(), and T.
Referenced by DrawTowerSum_AnaP().
TGraphErrors* Load_CurveSet (const TString config = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal2d/zerofield/G4Hits_sPHENIX_gamma", const TString energy = "24GeV")
Definition at line 2674 of file DrawEcal.C.
References energy, etas, Load_SF(), and n.
Referenced by DrawSF().
TVectorD Load_SF (const TString eta_bin = "eta0", const TString config = "/direct/phenix+sim02/phnxreco/ePHENIX/jinhuang/sPHENIX_work/single_particle/spacal1d/zerofield/G4Hits_sPHENIX_gamma", const TString energy = "24GeV")
Definition at line 2720 of file DrawEcal.C.
References assert, energy, and rms().
Referenced by Load_CurveSet().