Analysis Software: oncsSub_idtpcfeev1 Class Reference
oncsSub_idtpcfeev1 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_idtpcfeev1.h>
Public Member Functions
oncsSub_idtpcfeev1 (subevtdata_ptr)
~oncsSub_idtpcfeev1 ()
int iValue (const int chip, const int ch, const int sample)
int iValue (const int ch, const int sample)
int iValue (const int, const char *what)
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w4
oncsSubevent_w4 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
virtual int copyMe (int[], const int maxlength) const
Protected Member Functions
int decode ()
Protected Member Functions inherited from oncsSubevent_w4
virtual int * decode (int *)
Protected Attributes
int _broken
int _is_decoded
int _nchips
int _nchannels
int _nsamples
int _bx_count
int array [64][1002]
Detailed Description
Definition at line 7 of file oncsSub_idtpcfeev1.h.
Constructor & Destructor Documentation
oncsSub_idtpcfeev1::oncsSub_idtpcfeev1 (subevtdata_ptr data)
Definition at line 9 of file oncsSub_idtpcfeev1.cc.
References _is_decoded, _nchannels, _nchips, _nsamples, and array.
oncsSub_idtpcfeev1::~oncsSub_idtpcfeev1 ()
Definition at line 24 of file oncsSub_idtpcfeev1.cc.
Member Function Documentation
int oncsSub_idtpcfeev1::decode () protected
Definition at line 32 of file oncsSub_idtpcfeev1.cc.
References _broken, _bx_count, _is_decoded, _nchannels, _nchips, _nsamples, array, channel(), subevt_data::data, oncsSubevent::getLength(), oncsSubevent::getPadding(), HEADER_LENGTH, i, k, s, SEVTHEADERLENGTH, and oncsSubevent::SubeventHdr.
Referenced by iValue().
void oncsSub_idtpcfeev1::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w4.
Definition at line 140 of file oncsSub_idtpcfeev1.cc.
References c, oncsSubevent::identify(), iValue(), and s.
int oncsSub_idtpcfeev1::iValue (const int channel, const int iy, const int iz) virtual
this supports devices organized as three-dimensional data (card vs channel vs time slice)
Implements Packet.
Definition at line 96 of file oncsSub_idtpcfeev1.cc.
References _nchannels, _nchips, and _nsamples.
Referenced by dump().
int oncsSub_idtpcfeev1::iValue (const int channel, const int iy) virtual
this supports devices which are inherently organized as two-dimensional data, such as flash ADC's (channel vs time slice)
Implements Packet.
Definition at line 86 of file oncsSub_idtpcfeev1.cc.
References _nchannels, _nchips, _nsamples, array, and decode().
int oncsSub_idtpcfeev1::iValue (const int channel, const char * what) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Implements Packet.
Definition at line 106 of file oncsSub_idtpcfeev1.cc.
References _broken, _bx_count, _nchannels, _nchips, _nsamples, and decode().
Member Data Documentation
int oncsSub_idtpcfeev1::_broken protected
Definition at line 26 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), and iValue().
int oncsSub_idtpcfeev1::_bx_count protected
Definition at line 32 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), and iValue().
int oncsSub_idtpcfeev1::_is_decoded protected
Definition at line 28 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), and oncsSub_idtpcfeev1().
int oncsSub_idtpcfeev1::_nchannels protected
Definition at line 30 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), iValue(), and oncsSub_idtpcfeev1().
int oncsSub_idtpcfeev1::_nchips protected
Definition at line 29 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), iValue(), and oncsSub_idtpcfeev1().
int oncsSub_idtpcfeev1::_nsamples protected
Definition at line 31 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), iValue(), and oncsSub_idtpcfeev1().
int oncsSub_idtpcfeev1::array[64][1002] protected
Definition at line 34 of file oncsSub_idtpcfeev1.h.
Referenced by decode(), iValue(), and oncsSub_idtpcfeev1().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_idtpcfeev1.h
online_distribution/blob/master/newbasic/oncsSub_idtpcfeev1.cc