Analysis Software: SimpleHit3D Class Reference
SimpleHit3D Class Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/helix_hough/SimpleHit3D.h>
Public Member Functions
SimpleHit3D ()
virtual ~SimpleHit3D ()
TrkrDefs::cluskey get_cluskey () const
void set_cluskey (TrkrDefs::cluskey key)
unsigned int get_id () const
void set_id (unsigned int id)
int get_layer () const
void set_layer (int layer)
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
void print (std::ostream &out=std::cout) const
float get_error (unsigned int i, unsigned int j) const
void set_error (unsigned int i, unsigned int j, float value)
float get_size (unsigned int i, unsigned int j) const
void set_size (unsigned int i, unsigned int j, float value)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
Private Attributes
TrkrDefs::cluskey _cluskey
unsigned int _id
int _layer
float _x
float _y
float _z
float _err [6]
float _size [6]
Detailed Description
Definition at line 8 of file SimpleHit3D.h.
Constructor & Destructor Documentation
SimpleHit3D::SimpleHit3D ()
Definition at line 9 of file SimpleHit3D.cpp.
References i, j, set_error(), and set_size().
virtual SimpleHit3D::~SimpleHit3D () inline virtual
Definition at line 14 of file SimpleHit3D.h.
Member Function Documentation
unsigned int SimpleHit3D::covar_index (unsigned int i, unsigned int j) const private
Definition at line 83 of file SimpleHit3D.cpp.
References boost::swap().
Referenced by get_error(), get_size(), set_error(), and set_size().
TrkrDefs::cluskey SimpleHit3D::get_cluskey () const inline
Definition at line 16 of file SimpleHit3D.h.
References _cluskey.
float SimpleHit3D::get_error (unsigned int i, unsigned int j) const
Definition at line 70 of file SimpleHit3D.cpp.
References _err, and covar_index().
Referenced by print().
unsigned int SimpleHit3D::get_id () const inline
Definition at line 19 of file SimpleHit3D.h.
References _id.
Referenced by PHInitZVertexing::build_triplets_to_SimpleTrack3D(), PHPatternReco::build_triplets_to_SimpleTrack3D(), PHHoughSeeding::CleanupSeeds(), PHHoughSeeding::CleanupSeedsByHitPattern(), PHHoughSeeding::CleanupTracksByHitPattern(), print(), CellularAutomaton_v1::process_single_triplet(), PHPatternReco::translate_input(), and PHInitZVertexing::translate_input().
int SimpleHit3D::get_layer () const inline
Definition at line 22 of file SimpleHit3D.h.
References _layer.
Referenced by HelixKalman::addHit(), HelixKalmanFilter::addHit(), PHInitZVertexing::build_triplets_to_SimpleTrack3D(), PHPatternReco::build_triplets_to_SimpleTrack3D(), CylinderKalman::calculate_dxda(), HelixKalmanFilter::calculate_dxda(), CylinderKalman::calculateProjections(), HelixKalmanFilter::calculateProjections(), sPHENIXTrackerTpc::dzdlError(), sPHENIXTracker::dzdlError(), sPHENIXSeedFinder::dzdlError(), sPHENIXTracker::finalize(), sPHENIXSeedFinder::finalize(), sPHENIXTrackerTpc::phiError(), sPHENIXTracker::phiError(), sPHENIXSeedFinder::phiError(), print(), CellularAutomaton_v1::process_single_track(), and CellularAutomaton_v1::process_single_triplet().
float SimpleHit3D::get_size (unsigned int i, unsigned int j) const
Definition at line 79 of file SimpleHit3D.cpp.
References _size, and covar_index().
Referenced by CylinderKalman::calculateMeasurements(), HelixKalmanFilter::calculateMeasurements(), print(), and CellularAutomaton_v1::process_single_triplet().
float SimpleHit3D::get_x () const inline
Definition at line 25 of file SimpleHit3D.h.
References _x.
Referenced by PHInitZVertexing::build_triplets_to_SimpleTrack3D(), PHPatternReco::build_triplets_to_SimpleTrack3D(), CylinderKalman::calculate_dxda(), HelixKalmanFilter::calculate_dxda(), CylinderKalman::calculateMeasurements(), HelixKalmanFilter::calculateMeasurements(), CylinderKalman::calculateProjections(), HelixKalmanFilter::calculateProjections(), dzdsSimple(), print(), CellularAutomaton_v1::process_single_triplet(), PHPatternReco::shift_coordinate_system(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z_init(), PHPatternReco::vote_z_init(), and xyTangent().
float SimpleHit3D::get_y () const inline
Definition at line 28 of file SimpleHit3D.h.
References _y.
Referenced by PHInitZVertexing::build_triplets_to_SimpleTrack3D(), PHPatternReco::build_triplets_to_SimpleTrack3D(), CylinderKalman::calculate_dxda(), HelixKalmanFilter::calculate_dxda(), CylinderKalman::calculateMeasurements(), HelixKalmanFilter::calculateMeasurements(), CylinderKalman::calculateProjections(), HelixKalmanFilter::calculateProjections(), dzdsSimple(), print(), CellularAutomaton_v1::process_single_triplet(), PHPatternReco::shift_coordinate_system(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z_init(), PHPatternReco::vote_z_init(), and xyTangent().
float SimpleHit3D::get_z () const inline
Definition at line 31 of file SimpleHit3D.h.
References _z.
Referenced by PHInitZVertexing::build_triplets_to_SimpleTrack3D(), PHPatternReco::build_triplets_to_SimpleTrack3D(), CylinderKalman::calculateMeasurements(), HelixKalmanFilter::calculateMeasurements(), dzdsSimple(), print(), CellularAutomaton_v1::process_single_triplet(), PHPatternReco::shift_coordinate_system(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
void SimpleHit3D::print (std::ostream & out = std::cout) const
Definition at line 27 of file SimpleHit3D.cpp.
References _cluskey, get_error(), get_id(), get_layer(), get_size(), get_x(), get_y(), and get_z().
Referenced by PHInitZVertexing::translate_input(), and PHPatternReco::translate_input().
void SimpleHit3D::set_cluskey (TrkrDefs::cluskey key) inline
Definition at line 17 of file SimpleHit3D.h.
References _cluskey.
Referenced by PHInitZVertexing::translate_input(), PHPatternReco::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_error (unsigned int i, unsigned int j, float value)
Definition at line 65 of file SimpleHit3D.cpp.
References _err, covar_index(), and value.
Referenced by SimpleHit3D(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_id (unsigned int id) inline
Definition at line 20 of file SimpleHit3D.h.
References _id.
Referenced by PHHoughSeeding::CleanupSeeds(), PHHoughSeeding::CleanupSeedsByHitPattern(), PHHoughSeeding::CleanupTracksByHitPattern(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_layer (int layer) inline
Definition at line 23 of file SimpleHit3D.h.
References _layer.
Referenced by PHInitZVertexing::translate_input(), PHPatternReco::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_size (unsigned int i, unsigned int j, float value)
Definition at line 74 of file SimpleHit3D.cpp.
References _size, covar_index(), and value.
Referenced by SimpleHit3D(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_x (float x) inline
Definition at line 26 of file SimpleHit3D.h.
References _x, and x.
Referenced by sPHENIXTrackerTpc::finalize(), PHPatternReco::shift_coordinate_system(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_y (float y) inline
Definition at line 29 of file SimpleHit3D.h.
References _y, and y.
Referenced by sPHENIXTrackerTpc::finalize(), PHPatternReco::shift_coordinate_system(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
void SimpleHit3D::set_z (float z) inline
Definition at line 32 of file SimpleHit3D.h.
References _z, and z.
Referenced by sPHENIXTrackerTpc::finalize(), PHPatternReco::shift_coordinate_system(), PHInitZVertexing::shift_coordinate_system(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
Member Data Documentation
TrkrDefs::cluskey SimpleHit3D::_cluskey private
Definition at line 47 of file SimpleHit3D.h.
Referenced by get_cluskey(), print(), and set_cluskey().
float SimpleHit3D::_err[6] private
Definition at line 55 of file SimpleHit3D.h.
Referenced by get_error(), and set_error().
unsigned int SimpleHit3D::_id private
Definition at line 48 of file SimpleHit3D.h.
Referenced by get_id(), and set_id().
int SimpleHit3D::_layer private
Definition at line 49 of file SimpleHit3D.h.
Referenced by get_layer(), and set_layer().
float SimpleHit3D::_size[6] private
Definition at line 56 of file SimpleHit3D.h.
Referenced by get_size(), and set_size().
float SimpleHit3D::_x private
Definition at line 51 of file SimpleHit3D.h.
Referenced by get_x(), and set_x().
float SimpleHit3D::_y private
Definition at line 52 of file SimpleHit3D.h.
Referenced by get_y(), and set_y().
float SimpleHit3D::_z private
Definition at line 53 of file SimpleHit3D.h.
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/SimpleHit3D.h
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/SimpleHit3D.cpp