Analysis Software: PHG4HitContainer Class Reference
PHG4HitContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4HitContainer.h>
Public Types
typedef std::map
< PHG4HitDefs::keytype,
PHG4Hit * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
typedef std::set< unsigned int >
::const_iterator LayerIter
Public Member Functions
PHG4HitContainer ()
PHG4HitContainer (const std::string &nodename)
virtual ~PHG4HitContainer ()
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
void SetID (int i)
container ID should follow definition of PHG4HitDefs::get_volume_id(DST nodename)
int GetID () const
ConstIterator AddHit (PHG4Hit *newhit)
ConstIterator AddHit (const unsigned int detid, PHG4Hit *newhit)
Iterator findOrAddHit (PHG4HitDefs::keytype key)
PHG4Hit * findHit (PHG4HitDefs::keytype key)
PHG4HitDefs::keytype genkey (const unsigned int detid)
ConstRange getHits (const unsigned int detid) const
return all hits matching a given detid
ConstRange getHits (void) const
return all hist
unsigned int size (void) const
unsigned int num_layers (void) const
std::pair< LayerIter, LayerIter > getLayers () const
void AddLayer (const unsigned int ilayer)
void RemoveZeroEDep ()
PHG4HitDefs::keytype getmaxkey (const unsigned int detid)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int id
Map hitmap
std::set< unsigned int > layers
Detailed Description
Definition at line 18 of file PHG4HitContainer.h.
Member Typedef Documentation
typedef Map::const_iterator PHG4HitContainer::ConstIterator
Definition at line 24 of file PHG4HitContainer.h.
typedef std::pair<ConstIterator, ConstIterator> PHG4HitContainer::ConstRange
Definition at line 26 of file PHG4HitContainer.h.
typedef Map::iterator PHG4HitContainer::Iterator
Definition at line 23 of file PHG4HitContainer.h.
typedef std::set<unsigned int>::const_iterator PHG4HitContainer::LayerIter
Definition at line 27 of file PHG4HitContainer.h.
typedef std::map<PHG4HitDefs::keytype, PHG4Hit *> PHG4HitContainer::Map
Definition at line 22 of file PHG4HitContainer.h.
typedef std::pair<Iterator, Iterator> PHG4HitContainer::Range
Definition at line 25 of file PHG4HitContainer.h.
Constructor & Destructor Documentation
PHG4HitContainer::PHG4HitContainer ()
Definition at line 14 of file PHG4HitContainer.cc.
PHG4HitContainer::PHG4HitContainer (const std::string & nodename)
Definition at line 19 of file PHG4HitContainer.cc.
virtual PHG4HitContainer::~PHG4HitContainer () inline virtual
Definition at line 32 of file PHG4HitContainer.h.
Member Function Documentation
PHG4HitContainer::ConstIterator PHG4HitContainer::AddHit (PHG4Hit * newhit)
Definition at line 108 of file PHG4HitContainer.cc.
References PHG4Hit::get_hit_id(), PHG4HitDefs::hit_idbits, hitmap, and layers.
Referenced by PHG4RICHSteppingAction::MakeHit(), PHG4GenHit::process_event(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4Prototype2InnerHcalSteppingAction::UserSteppingAction(), PHG4Prototype2OuterHcalSteppingAction::UserSteppingAction(), PHG4Prototype3InnerHcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4ConeRegionSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HcalPrototypeSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), PHG4SpacalPrototype4SteppingAction::UserSteppingAction(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
PHG4HitContainer::ConstIterator PHG4HitContainer::AddHit (const unsigned int detid, PHG4Hit * newhit)
Definition at line 124 of file PHG4HitContainer.cc.
References genkey(), hitmap, layers, and PHG4Hit::set_hit_id().
void PHG4HitContainer::AddLayer (const unsigned int ilayer) inline
Definition at line 64 of file PHG4HitContainer.h.
References layers.
Referenced by PHG4HcalSubsystem::InitRun(), PHG4SpacalPrototype4Subsystem::InitRunSubsystem(), PHG4SpacalPrototypeSubsystem::InitRunSubsystem(), PHG4BlockSubsystem::InitRunSubsystem(), PHG4CylinderSubsystem::InitRunSubsystem(), and PHG4SpacalSubsystem::InitRunSubsystem().
PHG4Hit * PHG4HitContainer::findHit (PHG4HitDefs::keytype key)
Definition at line 168 of file PHG4HitContainer.cc.
References hitmap, and it.
Referenced by SvtxHitEval::all_truth_hits(), SvtxClusterEval::all_truth_hits(), CaloTruthEval::all_truth_hits(), CaloRawTowerEval::all_truth_hits(), TrkrEvaluator::fillOutputNtuples(), PHTruthTrackSeeding::Process(), and PHG4TruthEventAction::ProcessShowers().
PHG4HitContainer::Iterator PHG4HitContainer::findOrAddHit (PHG4HitDefs::keytype key)
Definition at line 153 of file PHG4HitContainer.cc.
References PHG4Hit::get_layer(), hitmap, it, layers, PHG4Hit::set_edep(), and PHG4Hit::set_hit_id().
Referenced by PHG4FPbScSteppingAction::UserSteppingAction(), and PHG4FCalSteppingAction::UserSteppingAction().
PHG4HitDefs::keytype PHG4HitContainer::genkey (const unsigned int detid)
Definition at line 79 of file PHG4HitContainer.cc.
References getmaxkey(), PHG4HitDefs::hit_idbits, hitmap, PHG4HitDefs::keybits, and PHWHERE.
Referenced by AddHit().
PHG4HitContainer::ConstRange PHG4HitContainer::getHits (const unsigned int detid) const
return all hits matching a given detid
Definition at line 133 of file PHG4HitContainer.cc.
References PHG4HitDefs::hit_idbits, hitmap, and PHG4HitDefs::keybits.
Referenced by SvtxTruthEval::all_truth_hits(), CaloTruthEval::all_truth_hits(), PHG4Prototype2HcalCellReco::CheckEnergy(), PHG4HcalCellReco::CheckEnergy(), PHG4ForwardCalCellReco::CheckEnergy(), PHAna::fill_sf_ntuple(), TrkrEvaluator::fillOutputNtuples(), SetupDualRICHAnalyzer::get_emission_momentum(), JetEnergies::GetTotalEnergy(), PHG4HitReadBack::process_event(), HCALAnalysis::process_event(), PHG4ConsistencyCheck::process_event(), G4HitTTree::process_event(), PHG4Prototype2HcalCellReco::process_event(), TPCIntegratedCharge::process_event(), PHG4MvtxHitReco::process_event(), PHG4HcalCellReco::process_event(), PHG4ForwardCalCellReco::process_event(), PHG4DstCompressReco::process_event(), RawTowerBuilderByHitIndex::process_event(), PHG4InttHitReco::process_event(), PHG4BlockCellReco::process_event(), PHG4CylinderCellReco::process_event(), G4EdepNtuple::process_event(), PHG4FullProjSpacalCellReco::process_event(), G4HitNtuple::process_event(), G4SnglNtuple::process_event(), EdepNtuple::process_event(), ShowerSize::process_event(), TimingNtuple::process_event(), PHG4TpcElectronDrift::process_event(), HijingShowerSize::process_event(), TPCDataStreamEmulator::process_event(), SigmaTimingNtuple::process_event(), Proto4SampleFrac::process_event(), TPCMLDataInterface::process_event(), PHG4DSTReader::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), EMCalAna::process_event_SF(), EMCalCalib::process_event_SF(), CaloAna::process_g4hits(), G4SnglTree::process_hit(), and DumpPHG4HitContainer::process_Node().
PHG4HitContainer::ConstRange PHG4HitContainer::getHits (void) const
return all hist
Definition at line 149 of file PHG4HitContainer.cc.
References hitmap.
Referenced by getmaxkey().
int PHG4HitContainer::GetID () const inline
Definition at line 40 of file PHG4HitContainer.h.
References id.
Referenced by PHG4RICHSteppingAction::MakeHit(), PHG4FPbScSteppingAction::UserSteppingAction(), PHG4FCalSteppingAction::UserSteppingAction(), PHG4EnvelopeSteppingAction::UserSteppingAction(), PHG4SectorSteppingAction::UserSteppingAction(), PHG4MvtxSteppingAction::UserSteppingAction(), PHG4TpcSteppingAction::UserSteppingAction(), PHG4HcalSteppingAction::UserSteppingAction(), PHG4Prototype3InnerHcalSteppingAction::UserSteppingAction(), PHG4PSTOFSteppingAction::UserSteppingAction(), PHG4Prototype2InnerHcalSteppingAction::UserSteppingAction(), PHG4Prototype2OuterHcalSteppingAction::UserSteppingAction(), PHG4CEmcTestBeamSteppingAction::UserSteppingAction(), PHG4OuterHcalSteppingAction::UserSteppingAction(), PHG4BlockSteppingAction::UserSteppingAction(), PHG4InttSteppingAction::UserSteppingAction(), PHG4CylinderSteppingAction::UserSteppingAction(), PHG4InnerHcalSteppingAction::UserSteppingAction(), PHG4ForwardHcalSteppingAction::UserSteppingAction(), PHG4FPbScRegionSteppingAction::UserSteppingAction(), PHG4ConeSteppingAction::UserSteppingAction(), PHG4CrystalCalorimeterSteppingAction::UserSteppingAction(), PHG4ConeRegionSteppingAction::UserSteppingAction(), PHG4ForwardEcalSteppingAction::UserSteppingAction(), PHG4HcalPrototypeSteppingAction::UserSteppingAction(), PHG4mRICHSteppingAction::UserSteppingAction(), PHG4SpacalSteppingAction::UserSteppingAction(), PHG4SpacalPrototype4SteppingAction::UserSteppingAction(), and PHG4SpacalPrototypeSteppingAction::UserSteppingAction().
std::pair<LayerIter, LayerIter> PHG4HitContainer::getLayers () const inline
Definition at line 62 of file PHG4HitContainer.h.
References layers.
Referenced by PHG4Prototype2HcalCellReco::process_event(), PHG4MvtxHitReco::process_event(), PHG4ForwardCalCellReco::process_event(), PHG4BlockCellReco::process_event(), and PHG4CylinderCellReco::process_event().
PHG4HitDefs::keytype PHG4HitContainer::getmaxkey (const unsigned int detid)
Definition at line 55 of file PHG4HitContainer.cc.
References getHits(), PHG4HitDefs::hit_idbits, and hitmap.
Referenced by genkey().
void PHG4HitContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 36 of file PHG4HitContainer.cc.
References hitmap, layers, num_layers(), and size().
Referenced by PHG4HitReadBack::process_event().
unsigned int PHG4HitContainer::num_layers (void) const inline
Definition at line 60 of file PHG4HitContainer.h.
References layers.
Referenced by identify(), and DumpPHG4HitContainer::process_Node().
void PHG4HitContainer::RemoveZeroEDep ()
Definition at line 180 of file PHG4HitContainer.cc.
References PHG4Hit::get_edep(), and hitmap.
Referenced by PHG4EventActionClearZeroEdep::EndOfEventAction().
void PHG4HitContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 25 of file PHG4HitContainer.cc.
References hitmap.
Referenced by PHG4DstCompressReco::process_event().
void PHG4HitContainer::SetID (int i) inline
container ID should follow definition of PHG4HitDefs::get_volume_id(DST nodename)
Definition at line 39 of file PHG4HitContainer.h.
References i.
unsigned int PHG4HitContainer::size (void) const inline
Definition at line 58 of file PHG4HitContainer.h.
References hitmap.
Referenced by identify(), Proto4SampleFrac::process_event(), PHG4DSTReader::process_event(), QAG4SimulationCalorimeter::process_event_G4Hit(), and DumpPHG4HitContainer::process_Node().
Member Data Documentation
Map PHG4HitContainer::hitmap protected
Definition at line 71 of file PHG4HitContainer.h.
Referenced by AddHit(), findHit(), findOrAddHit(), genkey(), getHits(), getmaxkey(), identify(), RemoveZeroEDep(), Reset(), and size().
int PHG4HitContainer::id protected
Definition at line 70 of file PHG4HitContainer.h.
Referenced by GetID().
std::set<unsigned int> PHG4HitContainer::layers protected
Definition at line 72 of file PHG4HitContainer.h.
Referenced by AddHit(), AddLayer(), findOrAddHit(), getLayers(), identify(), and num_layers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4HitContainer.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4HitContainer.cc