Analysis Software: PHPythia6 Class Reference
PHPythia6 Class Reference
#include <coresoftware/blob/master/generators/PHPythia6/PHPythia6.h>
Public Member Functions
PHPythia6 (const std::string &name="PHPythia6")
virtual ~PHPythia6 ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_config_file (const std::string &cfg_file)
void print_config () const
void beam_vertex_parameters (double beamX, double beamY, double beamZ, double beamXsigma, double beamYsigma, double beamZsigma)
void save_ascii (const std::string &fname="pythia_hepmc.dat")
void register_trigger (PHPy6GenTrigger *theTrigger)
set event selection criteria
void set_trigger_OR ()
void set_trigger_AND ()
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
PHPythia6 (const std::string &name="PHPythia6")
virtual ~PHPythia6 ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_config_file (const std::string cfg_file)
void print_config () const
void beam_vertex_parameters (double beamX, double beamY, double beamZ, double beamXsigma, double beamYsigma, double beamZsigma)
void save_ascii (std::string fname="pythia_hepmc.dat")
void register_trigger (PHPy6GenTrigger *theTrigger)
set event selection criteria
void set_trigger_OR ()
void set_trigger_AND ()
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int ReadConfig (const std::string &cfg_file="")
int CreateNodeTree (PHCompositeNode *topNode)
void IntegerTest (double number)
void initPythia ()
int ReadConfig (const std::string cfg_file="")
int CreateNodeTree (PHCompositeNode *topNode)
void IntegerTest (double number)
void initPythia ()
Private Attributes
int _eventcount
int _geneventcount
std::string _configFile
bool _save_ascii
std::string _filename_ascii
std::vector< PHPy6GenTrigger * > _registeredTriggers
bool _triggersOR
bool _triggersAND
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file PHPythia6.h.
Constructor & Destructor Documentation
PHPythia6::PHPythia6 (const std::string & name = "PHPythia6")
Definition at line 37 of file PHPythia6.cc.
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
PHPythia6::~PHPythia6 () inline virtual
Definition at line 18 of file PHPythia6.h.
PHPythia6::PHPythia6 (const std::string & name = "PHPythia6")
virtual PHPythia6::~PHPythia6 () virtual
Member Function Documentation
void PHPythia6::beam_vertex_parameters (double beamX, double beamY, double beamZ, double beamXsigma, double beamYsigma, double beamZsigma) inline
Definition at line 32 of file PHPythia6.h.
References set_vertex_distribution_mean(), and set_vertex_distribution_width().
void PHPythia6::beam_vertex_parameters (double beamX, double beamY, double beamZ, double beamXsigma, double beamYsigma, double beamZsigma) inline
Definition at line 37 of file PHPythia6.h.
References set_vertex_distribution_mean(), and set_vertex_distribution_width().
int PHPythia6::CreateNodeTree (PHCompositeNode * topNode) private
Definition at line 455 of file PHPythia6.cc.
References PHHepMCGenHelper::create_node_tree(), Fun4AllReturnCodes::EVENT_OK, and hepmc_helper.
Referenced by Init().
int PHPythia6::CreateNodeTree (PHCompositeNode * topNode) private
int PHPythia6::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 92 of file PHPythia6.cc.
References _eventcount, _geneventcount, and Fun4AllReturnCodes::EVENT_OK.
int PHPythia6::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int PHPythia6::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 82 of file PHPythia6.h.
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
int PHPythia6::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 87 of file PHPythia6.h.
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
int PHPythia6::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 51 of file PHPythia6.cc.
References _configFile, _eventcount, CreateNodeTree(), Fun4AllReturnCodes::EVENT_OK, PHWHERE, and ReadConfig().
int PHPythia6::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
void PHPythia6::initPythia () private
definition needed to use pythia wrapper headers from HepMC
void PHPythia6::initPythia () private
definition needed to use pythia wrapper headers from HepMC
void PHPythia6::IntegerTest (double number) private
Certain Pythia switches and parameters only accept integer values This function checks if input values are integers and warns the user if they are not
Definition at line 462 of file PHPythia6.cc.
Referenced by ReadConfig().
void PHPythia6::IntegerTest (double number) private
Certain Pythia switches and parameters only accept integer values This function checks if input values are integers and warns the user if they are not
void PHPythia6::print_config () const
Definition at line 335 of file PHPythia6.cc.
void PHPythia6::print_config () const
int PHPythia6::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 339 of file PHPythia6.cc.
References _eventcount, _filename_ascii, _geneventcount, _registeredTriggers, _save_ascii, _triggersAND, _triggersOR, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, hepmc_helper, PHHepMCGenHelper::insert_event(), and Fun4AllBase::Verbosity().
int PHPythia6::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int PHPythia6::ReadConfig (const std::string & cfg_file = "") private
Definition at line 113 of file PHPythia6.cc.
References _configFile, index, IntegerTest(), line, pydat1, pydat3, pyjets, pytune, and value.
Referenced by Init().
int PHPythia6::ReadConfig (const std::string cfg_file = "") private
Definition at line 121 of file PHPythia6.C.
References _configFile, index, IntegerTest(), line, pydat1, pydat3, pyjets, pytune, and value.
void PHPythia6::register_trigger (PHPy6GenTrigger * theTrigger)
set event selection criteria
Definition at line 481 of file PHPythia6.cc.
References _registeredTriggers, PHPy6GenTrigger::GetName(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector_LQ(), and Fun4All_Pythia6().
void PHPythia6::register_trigger (PHPy6GenTrigger * theTrigger)
set event selection criteria
int PHPythia6::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 476 of file PHPythia6.cc.
References Fun4AllReturnCodes::EVENT_OK.
int PHPythia6::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
void PHPythia6::save_ascii (const std::string & fname = "pythia_hepmc.dat") inline
Definition at line 43 of file PHPythia6.h.
References _filename_ascii, and _save_ascii.
void PHPythia6::save_ascii (std::string fname = "pythia_hepmc.dat") inline
Definition at line 48 of file PHPythia6.h.
References _filename_ascii, and _save_ascii.
void PHPythia6::set_config_file (const std::string & cfg_file) inline
Definition at line 28 of file PHPythia6.h.
References _configFile.
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_MCEventGen(), Fun4All_Pythia6(), and Fun4All_single_particle().
void PHPythia6::set_config_file (const std::string cfg_file) inline
Definition at line 33 of file PHPythia6.h.
References _configFile.
void PHPythia6::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 88 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
void PHPythia6::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 93 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
void PHPythia6::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 73 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), and Fun4All_G4_sPHENIX_truthphotonjet().
void PHPythia6::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 78 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
void PHPythia6::set_trigger_AND () inline
Definition at line 52 of file PHPythia6.h.
References _triggersAND.
void PHPythia6::set_trigger_AND () inline
Definition at line 57 of file PHPythia6.h.
References _triggersAND.
void PHPythia6::set_trigger_OR () inline
Definition at line 51 of file PHPythia6.h.
References _triggersOR.
void PHPythia6::set_trigger_OR () inline
Definition at line 56 of file PHPythia6.h.
References _triggersOR.
void PHPythia6::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 55 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void PHPythia6::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 60 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void PHPythia6::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 61 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
Referenced by beam_vertex_parameters().
void PHPythia6::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 66 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
void PHPythia6::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 67 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
Referenced by beam_vertex_parameters().
void PHPythia6::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 72 of file PHPythia6.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
Member Data Documentation
std::string PHPythia6::_configFile private
Definition at line 104 of file PHPythia6.h.
Referenced by Init(), ReadConfig(), and set_config_file().
int PHPythia6::_eventcount private
Definition at line 100 of file PHPythia6.h.
Referenced by End(), Init(), and process_event().
std::string PHPythia6::_filename_ascii private
ASCII file name to save HepMC event to
Definition at line 114 of file PHPythia6.h.
Referenced by process_event(), and save_ascii().
int PHPythia6::_geneventcount private
Definition at line 101 of file PHPythia6.h.
Referenced by End(), and process_event().
std::vector< PHPy6GenTrigger * > PHPythia6::_registeredTriggers private
Definition at line 117 of file PHPythia6.h.
Referenced by process_event(), and register_trigger().
bool PHPythia6::_save_ascii private
Save HepMC event to ASCII file?
Definition at line 109 of file PHPythia6.h.
Referenced by process_event(), and save_ascii().
bool PHPythia6::_triggersAND private
Definition at line 119 of file PHPythia6.h.
Referenced by process_event(), and set_trigger_AND().
bool PHPythia6::_triggersOR private
Definition at line 118 of file PHPythia6.h.
Referenced by process_event(), and set_trigger_OR().
PHHepMCGenHelper PHPythia6::hepmc_helper private
helper for insert HepMC event to DST node and add vertex smearing
Definition at line 126 of file PHPythia6.h.
Referenced by CreateNodeTree(), get_embedding_id(), PHPythia6(), process_event(), set_embedding_id(), set_reuse_vertex(), set_vertex_distribution_function(), set_vertex_distribution_mean(), and set_vertex_distribution_width().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/PHPythia6/PHPythia6.h
analysis/blob/master/EICTrigger/PHPythia6.h
coresoftware/blob/master/generators/PHPythia6/PHPythia6.cc
analysis/blob/master/EICTrigger/PHPythia6.C