Analysis Software: simpleRandom Class Reference
simpleRandom Class Reference
#include <online_distribution/blob/master/newbasic/simpleRandom.h>
Public Member Functions
simpleRandom ()
simpleRandom (const int iseed)
float gauss (const float mean, const float sigma)
float rnd (int low, int high)
Private Member Functions
void byteSwap (word32 *buf, unsigned words)
void xMD5Init (struct xMD5Context *ctx)
void xMD5Update (struct xMD5Context *ctx, byte const *buf, int len)
void xMD5Final (byte digest[16], struct xMD5Context *ctx)
void xMD5Transform (word32 buf[4], word32 const in[16])
void MD5 (byte *dest, const byte *orig, int len)
void load_seed ()
Private Attributes
unsigned int digest [4]
Detailed Description
Definition at line 66 of file simpleRandom.h.
Constructor & Destructor Documentation
simpleRandom::simpleRandom ()
Definition at line 232 of file simpleRandom.cc.
References digest.
simpleRandom::simpleRandom (const int iseed)
Definition at line 242 of file simpleRandom.cc.
References digest.
Member Function Documentation
void simpleRandom::byteSwap (word32 * buf, unsigned words) private
Definition at line 15 of file simpleRandom.cc.
Referenced by xMD5Final(), and xMD5Update().
float simpleRandom::gauss (const float mean, const float sigma)
Definition at line 251 of file simpleRandom.cc.
References BIGNUMBER, rnd(), x, y, and z.
Referenced by testEventiterator::getNextEvent(), ludecy(), and pydecy().
void simpleRandom::load_seed () private
void simpleRandom::MD5 (byte * dest, const byte * orig, int len) private
Definition at line 221 of file simpleRandom.cc.
References xMD5Final(), xMD5Init(), and xMD5Update().
Referenced by rnd().
float simpleRandom::rnd (int low, int high)
Definition at line 276 of file simpleRandom.cc.
References digest, mask, MD5(), num, and r.
Referenced by gauss().
void simpleRandom::xMD5Final (byte digest[16], struct xMD5Context * ctx) private
Definition at line 87 of file simpleRandom.cc.
References xMD5Context::buf, xMD5Context::bytes, byteSwap(), if(), xMD5Context::in, and xMD5Transform().
Referenced by MD5().
void simpleRandom::xMD5Init (struct xMD5Context * ctx) private
Definition at line 31 of file simpleRandom.cc.
References xMD5Context::buf, and xMD5Context::bytes.
Referenced by MD5().
void simpleRandom::xMD5Transform (word32 buf[4], word32 const in[16]) private
Definition at line 137 of file simpleRandom.cc.
References c, d, F1, F2, F3, F4, and MD5STEP.
Referenced by xMD5Final(), and xMD5Update().
void simpleRandom::xMD5Update (struct xMD5Context * ctx, byte const * buf, int len) private
Definition at line 47 of file simpleRandom.cc.
References xMD5Context::buf, xMD5Context::bytes, byteSwap(), xMD5Context::in, t, and xMD5Transform().
Referenced by MD5().
Member Data Documentation
unsigned int simpleRandom::digest[4] private
Definition at line 84 of file simpleRandom.h.
Referenced by rnd(), and simpleRandom().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/simpleRandom.h
online_distribution/blob/master/newbasic/simpleRandom.cc