Analysis Software: twrs_fwd Class Reference
twrs_fwd Class Reference
Public Member Functions
twrs_fwd (RawTower *)
virtual ~twrs_fwd ()
bool is_adjacent (twrs_fwd &)
void set_id (const int i)
int get_id () const
int get_j_bin () const
int get_k_bin () const
Protected Attributes
int bin_j
int bin_k
RawTowerDefs::keytype id
Detailed Description
Definition at line 37 of file RawClusterBuilderFwd.cc.
Constructor & Destructor Documentation
twrs_fwd::twrs_fwd (RawTower * rt)
Definition at line 66 of file RawClusterBuilderFwd.cc.
References bin_j, bin_k, RawTower::get_bineta(), and RawTower::get_binphi().
virtual twrs_fwd::~twrs_fwd () inline virtual
Definition at line 41 of file RawClusterBuilderFwd.cc.
Member Function Documentation
int twrs_fwd::get_id () const inline
Definition at line 47 of file RawClusterBuilderFwd.cc.
Referenced by RawClusterBuilderFwd::process_event().
int twrs_fwd::get_j_bin () const inline
Definition at line 51 of file RawClusterBuilderFwd.cc.
Referenced by is_adjacent(), and operator<().
int twrs_fwd::get_k_bin () const inline
Definition at line 55 of file RawClusterBuilderFwd.cc.
Referenced by is_adjacent(), and operator<().
bool twrs_fwd::is_adjacent (twrs_fwd & tower)
Definition at line 73 of file RawClusterBuilderFwd.cc.
References bin_j, bin_k, get_j_bin(), and get_k_bin().
void twrs_fwd::set_id (const int i) inline
Definition at line 43 of file RawClusterBuilderFwd.cc.
References i.
Referenced by RawClusterBuilderFwd::process_event().
Member Data Documentation
int twrs_fwd::bin_j protected
Definition at line 61 of file RawClusterBuilderFwd.cc.
Referenced by is_adjacent(), and twrs_fwd().
int twrs_fwd::bin_k protected
Definition at line 62 of file RawClusterBuilderFwd.cc.
Referenced by is_adjacent(), and twrs_fwd().
RawTowerDefs::keytype twrs_fwd::id protected
Definition at line 63 of file RawClusterBuilderFwd.cc.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderFwd.cc