Analysis Software: Packet_cdevring Class Reference
Packet_cdevring Class Reference
#include <online_distribution/blob/master/newbasic/packet_cdevring.h>
Public Member Functions
Packet_cdevring (PACKET_ptr)
virtual void dump (OSTREAM &)
virtual double dValue (const int channel, const char *what)
virtual int iValue (const int channel, const char *what)
Public Member Functions inherited from Packet_w4
Packet_w4 ()
Packet_w4 (PACKET_ptr)
void dump (OSTREAM &)
void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &=COUT) const
Public Member Functions inherited from Packet_A
Packet_A (PACKET_ptr packet_ptr)
Packet_A ()
~Packet_A ()
int getLength () const
int getErrorLength () const
int getDebugLength () const
get the length of the debug block
int getIdentifier () const
get the packet identifier
int getPadding () const
get the number of padding units in the packet data.
int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
int getDataLength () const
get what the name says...
void identify (OSTREAM &=COUT) const
void fullIdentify (OSTREAM &=COUT) const
void dumpErrorBlock (OSTREAM &=COUT)
void dumpDebugBlock (OSTREAM &=COUT)
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
float rValue (const int)
float rValue (const int, const char *)
float rValue (const int, const int)
int getArraylength (const char *)
int fillIntArray (int[], const int, int *, const char *what="")
int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
int * getIntArray (int *, const char *what="")
float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int getCheckSumStatus () const
int copyMe (int dest[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
Protected Member Functions
virtual int * decode (int *)
Protected Member Functions inherited from Packet_w4
int * decode (int *)
Protected Member Functions inherited from Packet_A
int standardIntArray (int[], const int, int *, const char *what="")
Protected Attributes
struct cdevRingData * ps
int haspoldata
int hasfilldata
int decoded
Additional Inherited Members
Static Protected Member Functions inherited from Packet_A
static void fix_endianess (long long *x)
static void fix_endianess (double *x)
static void fix_endianess (char *str, const int length)
Detailed Description
This is the packet which deals with data in CDEVRING format. It inherits from Packet_w4 because the data are 32bit entities.
Definition at line 17 of file packet_cdevring.h.
Constructor & Destructor Documentation
Packet_cdevring::Packet_cdevring (PACKET_ptr data)
Definition at line 3 of file packet_cdevring.cc.
References decoded, hasfilldata, haspoldata, and ps.
Member Function Documentation
int * Packet_cdevring::decode (int * nwout) protected virtual
with the "what" parameter you can decide which aspect of
the data is made available. This class is one of those which have several different "kinds" of data; we use this to bring up the misc. .
With iValue(i, "measuredFillPattern") returns the measuredFillPattern, and iValue(i, "intendedFillPattern") returns the intendedFillPattern. With iValue(i, "polarizationFillPattern") returns the polarizationFillPattern, iValue(i, "fillNumber") returns the fillNumber
{verbatim} dValue(i,"beamEnergy") ; gets the beamEnergy dValue(i,"gamma") ; get gamma dValue(i,"bunchOneRelativePhase") ; gets the bunch one relative phase {verbatim}
In addition, there is {verbatim} packet->iValue(0,"stoneType") The stoneType packet->iValue(0,"timeOfFillStart") The fill Start Time packet->iValue(0,"timeOfLuminosityStart") The luminosity start time
{verbatim}
Implements Packet_A.
Definition at line 12 of file packet_cdevring.cc.
References decoded, findPacketDataStart(), Packet_A::getHitFormat(), hasfilldata, haspoldata, IDCDEVRING, IDCDEVRINGFILL, IDCDEVRINGPOL, k, Packet_A::packet, and ps.
Referenced by dump(), dValue(), and iValue().
void Packet_cdevring::dump (OSTREAM & os) virtual
Definition at line 147 of file packet_cdevring.cc.
References decode(), hasfilldata, haspoldata, i, Packet_A::identify(), iValue(), cdevRingData::m_beamEnergy, cdevRingData::m_bunchLength, cdevRingData::m_chromaticityHorizontal, cdevRingData::m_chromaticityVertical, cdevRingData::m_emittanceVertical, cdevRingData::m_gamma, cdevRingData::m_ionSpecies, cdevRingData::m_momentumSpread, cdevRingData::m_ringState, cdevRingData::m_stoneType, and ps.
double Packet_cdevring::dValue (const int channel, const char * what) virtual
Reimplemented from Packet.
Definition at line 123 of file packet_cdevring.cc.
References decode(), i, cdevRingData::m_beamEnergy, cdevRingData::m_betaIPMHorizontal, cdevRingData::m_betaIPMVertical, cdevRingData::m_bunchLength, cdevRingData::m_bunchOneRelativePhase, cdevRingData::m_chromaticityHorizontal, cdevRingData::m_chromaticityVertical, cdevRingData::m_emittanceHorizontal, cdevRingData::m_emittanceVertical, cdevRingData::m_gamma, cdevRingData::m_momentumSpread, cdevRingData::m_synchrotronTune, and ps.
int Packet_cdevring::iValue (const int channel, const char * what) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Reimplemented from Packet_A.
Definition at line 52 of file packet_cdevring.cc.
References decode(), hasfilldata, haspoldata, i, cdevRingData::m_datavalidMask, cdevRingData::m_fillNumber, cdevRingData::m_intendedFillPattern, cdevRingData::m_ionSpecies, cdevRingData::m_measuredFillPattern, cdevRingData::m_measuredPolarizationDown, cdevRingData::m_measuredPolarizationUp, cdevRingData::m_polarizationFillPattern, cdevRingData::m_ringState, cdevRingData::m_stoneType, cdevRingData::m_timeOfFillStart, cdevRingData::m_timeOfLuminosityStart, and ps.
Referenced by dump().
Member Data Documentation
int Packet_cdevring::decoded protected
Definition at line 57 of file packet_cdevring.h.
Referenced by decode(), and Packet_cdevring().
int Packet_cdevring::hasfilldata protected
Definition at line 56 of file packet_cdevring.h.
Referenced by decode(), dump(), iValue(), and Packet_cdevring().
int Packet_cdevring::haspoldata protected
Definition at line 55 of file packet_cdevring.h.
Referenced by decode(), dump(), iValue(), and Packet_cdevring().
struct cdevRingData* Packet_cdevring::ps protected
Definition at line 54 of file packet_cdevring.h.
Referenced by decode(), dump(), dValue(), iValue(), and Packet_cdevring().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/packet_cdevring.h
online_distribution/blob/master/newbasic/packet_cdevring.cc