Analysis Software: PHG4ForwardHcalSubsystem Class Reference
PHG4ForwardHcalSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.h>
Public Member Functions
PHG4ForwardHcalSubsystem (const std::string &name="FORWARD_HCAL_DEFAULT", const int layer=0)
virtual ~PHG4ForwardHcalSubsystem ()
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
PHG4Detector * GetDetector () const
PHG4SteppingAction * GetSteppingAction () const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void SetTowerMappingFile (const std::string &filename)
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void BlackHole (const int i=1)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4ForwardHcalDetector * m_Detector
PHG4SteppingAction * m_SteppingAction
PHG4DisplayAction * m_DisplayAction
display attribute setting
int active
int absorber_active
int blackhole
std::string detector_type
std::string mappingfile_
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file PHG4ForwardHcalSubsystem.h.
Constructor & Destructor Documentation
PHG4ForwardHcalSubsystem::PHG4ForwardHcalSubsystem (const std::string & name = "FORWARD_HCAL_DEFAULT", const int layer = 0)
Constructor
Definition at line 26 of file PHG4ForwardHcalSubsystem.cc.
PHG4ForwardHcalSubsystem::~PHG4ForwardHcalSubsystem () virtual
Destructor
Definition at line 40 of file PHG4ForwardHcalSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
void PHG4ForwardHcalSubsystem::BlackHole (const int i = 1) inline
Definition at line 53 of file PHG4ForwardHcalSubsystem.h.
References blackhole, and i.
PHG4Detector * PHG4ForwardHcalSubsystem::GetDetector (void) const virtual
Accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 111 of file PHG4ForwardHcalSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4ForwardHcalSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 42 of file PHG4ForwardHcalSubsystem.h.
References m_DisplayAction.
PHG4SteppingAction* PHG4ForwardHcalSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 41 of file PHG4ForwardHcalSubsystem.h.
References m_SteppingAction.
int PHG4ForwardHcalSubsystem::Init (PHCompositeNode * topNode) virtual
Creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) Creates the stepping action and place it on the node tree, under "ACTIONS" node Creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 46 of file PHG4ForwardHcalSubsystem.cc.
References absorber_active, active, PHCompositeNode::addNode(), blackhole, PHG4ForwardHcalDetector::BlackHole(), PHG4Subsystem::CheckOverlap(), detector_type, PHNodeIterator::findFirst(), m_Detector, m_DisplayAction, m_SteppingAction, mappingfile_, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHG4ForwardHcalDetector::SetAbsorberActive(), PHG4ForwardHcalDetector::SetActive(), PHG4ForwardHcalDetector::SetTowerMappingFile(), PHG4Detector::topNode(), PHG4Detector::Verbosity(), and Fun4AllBase::Verbosity().
int PHG4ForwardHcalSubsystem::process_event (PHCompositeNode * topNode) virtual
Event processing
Reimplemented from SubsysReco.
Definition at line 99 of file PHG4ForwardHcalSubsystem.cc.
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4ForwardHcalSubsystem::SetAbsorberActive (const int i = 1) inline
Definition at line 52 of file PHG4ForwardHcalSubsystem.h.
References absorber_active, and i.
Referenced by FHCALSetup().
void PHG4ForwardHcalSubsystem::SetActive (const int i = 1) inline
Definition at line 51 of file PHG4ForwardHcalSubsystem.h.
References active, and i.
void PHG4ForwardHcalSubsystem::SetTowerMappingFile (const std::string & filename) inline
Set mapping file for calorimeter towers
Definition at line 46 of file PHG4ForwardHcalSubsystem.h.
References filename, and mappingfile_.
Referenced by FHCALSetup().
Member Data Documentation
int PHG4ForwardHcalSubsystem::absorber_active private
Definition at line 68 of file PHG4ForwardHcalSubsystem.h.
Referenced by Init(), and SetAbsorberActive().
int PHG4ForwardHcalSubsystem::active private
Definition at line 67 of file PHG4ForwardHcalSubsystem.h.
Referenced by Init(), and SetActive().
int PHG4ForwardHcalSubsystem::blackhole private
Definition at line 69 of file PHG4ForwardHcalSubsystem.h.
Referenced by BlackHole(), and Init().
std::string PHG4ForwardHcalSubsystem::detector_type private
Definition at line 71 of file PHG4ForwardHcalSubsystem.h.
Referenced by Init().
PHG4ForwardHcalDetector* PHG4ForwardHcalSubsystem::m_Detector private
Pointer to the Geant4 implementation of the detector
Definition at line 58 of file PHG4ForwardHcalSubsystem.h.
Referenced by GetDetector(), and Init().
PHG4DisplayAction* PHG4ForwardHcalSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 65 of file PHG4ForwardHcalSubsystem.h.
Referenced by GetDisplayAction(), Init(), and ~PHG4ForwardHcalSubsystem().
PHG4SteppingAction* PHG4ForwardHcalSubsystem::m_SteppingAction private
Stepping action
Definition at line 62 of file PHG4ForwardHcalSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
std::string PHG4ForwardHcalSubsystem::mappingfile_ private
Definition at line 72 of file PHG4ForwardHcalSubsystem.h.
Referenced by Init(), and SetTowerMappingFile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.cc