Analysis Software: HCalib Class Reference
HCalib Class Reference
#include <analysis/blob/master/HCalib/HCalib.h>
Public Types
enum detid { HCALIN =0, HCALOUT =1 }
typedef std::map
< PHG4ScintillatorSlatDefs::keytype,
TH1F * > SlatMap
typedef std::map
< RawTowerDefs::keytype, TH1F * > TowerMap
Public Member Functions
HCalib ()
virtual ~HCalib ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int genkey (const int detid, const int etabin, const int phibin)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void GetNodes (PHCompositeNode *topNode, const std::string &det="None")
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
bool is_proto
PHCompositeNode * topNode
RawTowerContainer * towers
PHG4CellContainer * slats
PHG4ScintillatorSlatContainer * proto_slats
float threshold
TFile * outfile
SlatMap slat_hists
TowerMap tower_hists
bool fill_towers
bool fill_slats
Detailed Description
Definition at line 20 of file HCalib.h.
Member Typedef Documentation
typedef std::map<PHG4ScintillatorSlatDefs::keytype,TH1F *> HCalib::SlatMap
Definition at line 23 of file HCalib.h.
typedef std::map<RawTowerDefs::keytype, TH1F *> HCalib::TowerMap
Definition at line 24 of file HCalib.h.
Member Enumeration Documentation
enum HCalib::detid
Enumerator:
HCALIN
HCALOUT
Definition at line 33 of file HCalib.h.
Constructor & Destructor Documentation
HCalib::HCalib ()
Definition at line 31 of file HCalib.C.
References fill_slats, fill_towers, is_proto, outfile, slats, threshold, and towers.
virtual HCalib::~HCalib () inline virtual
Definition at line 27 of file HCalib.h.
Member Function Documentation
int HCalib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 197 of file HCalib.C.
References Fun4AllReturnCodes::EVENT_OK, it, outfile, slat_hists, and tower_hists.
int HCalib::genkey (const int detid, const int etabin, const int phibin)
Definition at line 248 of file HCalib.C.
Referenced by process_event().
void HCalib::GetNodes (PHCompositeNode * topNode, const std::string & det = "None") protected
Definition at line 216 of file HCalib.C.
References is_proto, PHWHERE, proto_slats, slats, topNode, and towers.
Referenced by process_event().
int HCalib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 44 of file HCalib.C.
References Fun4AllReturnCodes::EVENT_OK, and outfile.
int HCalib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 50 of file HCalib.C.
References Fun4AllReturnCodes::EVENT_OK, fill_slats, fill_towers, genkey(), RawTower::get_bineta(), RawTower::get_binphi(), PHG4Cell::get_cellid(), PHG4ScintillatorSlat::get_column(), PHG4CellDefs::ScintillatorSlatBinning::get_column(), RawTower::get_energy(), PHG4ScintillatorSlat::get_light_yield(), PHG4Cell::get_light_yield(), PHG4ScintillatorSlat::get_row(), PHG4CellDefs::ScintillatorSlatBinning::get_row(), PHG4CellContainer::getCells(), GetNodes(), PHG4ScintillatorSlatContainer::getScintillatorSlats(), SVM_v1::h, is_proto, it, proto_slats, slat_hists, slats, tower_hists, and towers.
Member Data Documentation
bool HCalib::fill_slats protected
Definition at line 47 of file HCalib.h.
Referenced by HCalib(), and process_event().
bool HCalib::fill_towers protected
Definition at line 46 of file HCalib.h.
Referenced by HCalib(), and process_event().
bool HCalib::is_proto protected
Definition at line 35 of file HCalib.h.
Referenced by GetNodes(), HCalib(), and process_event().
TFile* HCalib::outfile protected
Definition at line 43 of file HCalib.h.
Referenced by End(), HCalib(), and Init().
PHG4ScintillatorSlatContainer* HCalib::proto_slats protected
Definition at line 41 of file HCalib.h.
Referenced by GetNodes(), and process_event().
SlatMap HCalib::slat_hists protected
Definition at line 44 of file HCalib.h.
Referenced by End(), and process_event().
PHG4CellContainer* HCalib::slats protected
Definition at line 40 of file HCalib.h.
Referenced by GetNodes(), HCalib(), and process_event().
float HCalib::threshold protected
Definition at line 42 of file HCalib.h.
Referenced by HCalib().
PHCompositeNode* HCalib::topNode protected
Definition at line 38 of file HCalib.h.
Referenced by GetNodes().
TowerMap HCalib::tower_hists protected
Definition at line 45 of file HCalib.h.
Referenced by End(), and process_event().
RawTowerContainer* HCalib::towers protected
Definition at line 39 of file HCalib.h.
Referenced by GetNodes(), HCalib(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/HCalib/HCalib.h
analysis/blob/master/HCalib/HCalib.C