Analysis Software: analysis/blob/master/TreeMaker/run_macro.C File Reference
run_macro.C File Reference
Functions
int run_macro (std::string infile="G4sPHENIX.root", std::string outfile="test.root")
Function Documentation
int run_macro (std::string infile = "G4sPHENIX.root", std::string outfile = "test.root")
Definition at line 1 of file run_macro.C.
References JetReco::add_algo(), TruthJetInput::add_embedding_flag(), JetReco::add_input(), Jet::ANTIKT, Jet::CEMC_TOWER, Jet::CEMC_TOWER_RETOWER, Fun4AllServer::End(), Fun4AllInputManager::fileopen(), Jet::HCALIN_TOWER, Jet::HCALOUT_TOWER, recoConsts::instance(), Fun4AllServer::instance(), Jet::PARTICLE, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), JetReco::set_algo_node(), JetReco::set_input_node(), and Fun4AllBase::Verbosity().