Analysis Software: RanSeed Class Reference
RanSeed Class Reference
Class definition for RanSeed, which is used to modify the Hijing RANSEED common.
#include <coresoftware/blob/master/generators/sHijing/RanSeed.h>
Classes
struct RANSEED
Public Member Functions
RanSeed ()
~RanSeed ()
int & nseed (void)
Static Private Attributes
static RANSEED * _ranseed =0
Friends
struct RANSEED
Detailed Description
Class definition for RanSeed, which is used to modify the Hijing RANSEED common.
Definition at line 12 of file RanSeed.h.
Constructor & Destructor Documentation
RanSeed::RanSeed () inline
Definition at line 37 of file RanSeed.h.
RanSeed::~RanSeed () inline
Definition at line 41 of file RanSeed.h.
Member Function Documentation
int & RanSeed::nseed (void) inline
Definition at line 45 of file RanSeed.h.
References _ranseed, RanSeed::RANSEED::nseed, and ranseed_address_().
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), ar3jet(), arorie(), attflv(), attrad(), hijcsc(), hijels(), hijflv(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hiptdi(), hirnd(), hirnd2(), quench(), and ran().
Friends And Related Function Documentation
friend struct RANSEED friend
Definition at line 22 of file RanSeed.h.
Member Data Documentation
RanSeed::RANSEED * RanSeed::_ranseed =0 static private
Definition at line 30 of file RanSeed.h.
Referenced by nseed().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/RanSeed.h