Analysis Software: PHPointerList< T > Class Template Reference
PHPointerList< T > Class Template Reference
#include <coresoftware/blob/master/offline/framework/phool/PHPointerList.h>
Public Member Functions
PHPointerList (size_t=2)
PHPointerList (const PHPointerList< T > &)
PHPointerList< T > & operator= (const PHPointerList< T > &)
virtual ~PHPointerList ()
T * operator[] (size_t) const
void clear ()
void clearAndDestroy ()
size_t length () const
T * removeLast ()
T * removeAt (size_t)
bool append (T *)
bool insertAt (T *, size_t)
Private Member Functions
bool grow (size_t=0)
Private Attributes
T ** items
size_t maxNItems
size_t nItems
Detailed Description
template<class T>
class PHPointerList< T >
Definition at line 30 of file PHPointerList.h.
Constructor & Destructor Documentation
template<class T > PHPointerList< T >::PHPointerList (size_t initialSize = 2) explicit
Definition at line 59 of file PHPointerList.h.
References T.
template<class T> PHPointerList< T >::PHPointerList (const PHPointerList< T > & l)
Definition at line 67 of file PHPointerList.h.
template<class T > PHPointerList< T >::~PHPointerList () virtual
Definition at line 90 of file PHPointerList.h.
Member Function Documentation
template<class T> bool PHPointerList< T >::append (T * item) inline
Definition at line 139 of file PHPointerList.h.
Referenced by PHCompositeNode::addNode(), and PHNodeIterator::ls().
template<class T > void PHPointerList< T >::clear () inline
Definition at line 190 of file PHPointerList.h.
Referenced by PHNodeIterator::ls().
template<class T > void PHPointerList< T >::clearAndDestroy () inline
Definition at line 198 of file PHPointerList.h.
References i.
Referenced by PHCompositeNode::~PHCompositeNode().
template<class T > bool PHPointerList< T >::grow (size_t newSize = 0) private
Definition at line 97 of file PHPointerList.h.
References i, and T.
template<class T> bool PHPointerList< T >::insertAt (T * item, size_t pos) inline
Definition at line 165 of file PHPointerList.h.
References i, and pos.
template<class T > size_t PHPointerList< T >::length () const inline
Definition at line 210 of file PHPointerList.h.
Referenced by PHPointerList< T >::operator=().
template<class T> PHPointerList< T > & PHPointerList< T >::operator= (const PHPointerList< T > & l)
Definition at line 74 of file PHPointerList.h.
References i, PHPointerList< T >::length(), and PHPointerList< T >::maxNItems.
template<class T > T * PHPointerList< T >::operator[] (size_t i) const inline
Definition at line 124 of file PHPointerList.h.
References i.
template<class T > T * PHPointerList< T >::removeAt (size_t i) inline
Definition at line 232 of file PHPointerList.h.
References i, j, and T.
Referenced by PHCompositeNode::forgetMe(), and PHCompositeNode::prune().
template<class T > T * PHPointerList< T >::removeLast () inline
Definition at line 217 of file PHPointerList.h.
Member Data Documentation
template<class T> T** PHPointerList< T >::items private
Definition at line 52 of file PHPointerList.h.
template<class T> size_t PHPointerList< T >::maxNItems private
Definition at line 53 of file PHPointerList.h.
Referenced by PHPointerList< T >::operator=().
template<class T> size_t PHPointerList< T >::nItems private
Definition at line 54 of file PHPointerList.h.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/phool/PHPointerList.h