Analysis Software: PHInitVertexing Class Reference
PHInitVertexing Class Reference abstract
Base class for inital vertexing.
#include <coresoftware/blob/master/offline/packages/trackreco/PHInitVertexing.h>
Public Member Functions
PHInitVertexing (const std::string &name="PHInitVertexing")
virtual ~PHInitVertexing ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int Setup (PHCompositeNode *topNode)
virtual int Process (PHCompositeNode *topNode)=0
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
create new node output pointers
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Base class for inital vertexing.
Definition at line 26 of file PHInitVertexing.h.
Constructor & Destructor Documentation
PHInitVertexing::PHInitVertexing (const std::string & name = "PHInitVertexing")
Definition at line 22 of file PHInitVertexing.cc.
virtual PHInitVertexing::~PHInitVertexing () inline virtual
Definition at line 30 of file PHInitVertexing.h.
Member Function Documentation
int PHInitVertexing::CreateNodes (PHCompositeNode * topNode) private
create new node output pointers
Definition at line 50 of file PHInitVertexing.cc.
References _vertex_map, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Setup().
int PHInitVertexing::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 86 of file PHInitVertexing.cc.
References _cluster_map, _vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHInitVertexing::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 29 of file PHInitVertexing.cc.
References Setup().
virtual int PHInitVertexing::Process (PHCompositeNode * topNode) protected pure virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implemented in PHInitZVertexing, and PHTruthVertexing.
Referenced by process_event().
int PHInitVertexing::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 34 of file PHInitVertexing.cc.
References Process().
int PHInitVertexing::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented in PHInitZVertexing, and PHTruthVertexing.
Definition at line 39 of file PHInitVertexing.cc.
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, and GetNodes().
Referenced by InitRun(), and PHInitZVertexing::Setup().
Member Data Documentation
TrkrClusterContainer* PHInitVertexing::_cluster_map protected
Definition at line 46 of file PHInitVertexing.h.
Referenced by PHInitZVertexing::export_output(), GetNodes(), and PHInitZVertexing::translate_input().
SvtxVertexMap* PHInitVertexing::_vertex_map protected
Definition at line 47 of file PHInitVertexing.h.
Referenced by CreateNodes(), PHInitZVertexing::export_output(), and GetNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHInitVertexing.h
coresoftware/blob/master/offline/packages/trackreco/PHInitVertexing.cc