Analysis Software: SvtxHitMap Class Reference
SvtxHitMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHitMap.h>
Public Types
typedef std::map< unsigned int,
SvtxHit * > HitMap
typedef std::map< unsigned int,
SvtxHit * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxHit * >::iterator Iter
Public Member Functions
virtual ~SvtxHitMap ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const SvtxHit * get (unsigned int idkey) const
virtual SvtxHit * get (unsigned int idkey)
virtual SvtxHit * insert (const SvtxHit *hit)
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxHitMap ()
Private Member Functions
ClassDef (SvtxHitMap, 1)
Detailed Description
Definition at line 10 of file SvtxHitMap.h.
Member Typedef Documentation
typedef std::map<unsigned int, SvtxHit*>::const_iterator SvtxHitMap::ConstIter
Definition at line 14 of file SvtxHitMap.h.
typedef std::map<unsigned int, SvtxHit*> SvtxHitMap::HitMap
Definition at line 13 of file SvtxHitMap.h.
typedef std::map<unsigned int, SvtxHit*>::iterator SvtxHitMap::Iter
Definition at line 15 of file SvtxHitMap.h.
Constructor & Destructor Documentation
virtual SvtxHitMap::~SvtxHitMap () inline virtual
Definition at line 17 of file SvtxHitMap.h.
SvtxHitMap::SvtxHitMap () inline protected
Definition at line 46 of file SvtxHitMap.h.
Member Function Documentation
virtual ConstIter SvtxHitMap::begin () const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 37 of file SvtxHitMap.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), HFMLTriggerInterface::process_event(), HFMLTriggerOccupancy::process_event(), TPCDataStreamEmulator::process_event(), and DumpSvtxHitMap::process_Node().
virtual Iter SvtxHitMap::begin () inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 41 of file SvtxHitMap.h.
SvtxHitMap::ClassDef (SvtxHitMap , 1) private
virtual void SvtxHitMap::clear () inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 30 of file SvtxHitMap.h.
virtual PHObject* SvtxHitMap::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxHitMap_v1.
Definition at line 25 of file SvtxHitMap.h.
virtual size_t SvtxHitMap::count (unsigned int idkey) const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 29 of file SvtxHitMap.h.
virtual bool SvtxHitMap::empty () const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 27 of file SvtxHitMap.h.
virtual ConstIter SvtxHitMap::end () const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 39 of file SvtxHitMap.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), HFMLTriggerInterface::process_event(), HFMLTriggerOccupancy::process_event(), TPCDataStreamEmulator::process_event(), and DumpSvtxHitMap::process_Node().
virtual Iter SvtxHitMap::end () inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 43 of file SvtxHitMap.h.
virtual size_t SvtxHitMap::erase (unsigned int idkey) inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 35 of file SvtxHitMap.h.
virtual ConstIter SvtxHitMap::find (unsigned int idkey) const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 38 of file SvtxHitMap.h.
Referenced by BDiJetModule::MakeGenFitTrack().
virtual Iter SvtxHitMap::find (unsigned int idkey) inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 42 of file SvtxHitMap.h.
virtual const SvtxHit* SvtxHitMap::get (unsigned int idkey) const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 32 of file SvtxHitMap.h.
Referenced by Conversion::firstLayer(), and Conversion::trackDLayer().
virtual SvtxHit* SvtxHitMap::get (unsigned int idkey) inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 33 of file SvtxHitMap.h.
virtual void SvtxHitMap::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxHitMap_v1.
Definition at line 19 of file SvtxHitMap.h.
References os.
virtual SvtxHit* SvtxHitMap::insert (const SvtxHit * hit) inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 34 of file SvtxHitMap.h.
virtual int SvtxHitMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxHitMap_v1.
Definition at line 24 of file SvtxHitMap.h.
virtual void SvtxHitMap::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxHitMap_v1.
Definition at line 23 of file SvtxHitMap.h.
virtual size_t SvtxHitMap::size (void) const inline virtual
Reimplemented in SvtxHitMap_v1.
Definition at line 28 of file SvtxHitMap.h.
Referenced by DumpSvtxHitMap::process_Node().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHitMap.h