Analysis Software: macros/blob/master/macros/g4simulations/G4_HcalIn_EIC.C File Reference
G4_HcalIn_EIC.C File Reference
Enumerations
enum enu_HCalIn_clusterizer {
kHCalInGraphClusterizer, kHCalInTemplateClusterizer, kHCalInGraphClusterizer, kHCalInTemplateClusterizer,
kHCalInGraphClusterizer, kHCalInTemplateClusterizer
}
Functions
void HCalInnerInit ()
graph clusterizer, RawClusterBuilderGraph
double HCalInner (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0, int verbosity=0)
void HCalInner_SupportRing (PHG4Reco *g4Reco, const int absorberactive=0)
A rough version of the inner HCal support ring, from Richie's CAD drawing. - Jin.
void HCALInner_Cells (int verbosity=0)
void HCALInner_Towers (int verbosity=0)
void HCALInner_Clusters (int verbosity=0)
void HCALInner_Eval (std::string outputfile, int verbosity=0)
Variables
const bool inner_hcal_material_Al = false
enu_HCalIn_clusterizer HCalIn_clusterizer = kHCalInTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Enumeration Type Documentation
enum enu_HCalIn_clusterizer
Enumerator:
kHCalInGraphClusterizer
kHCalInTemplateClusterizer
kHCalInGraphClusterizer
kHCalInTemplateClusterizer
kHCalInGraphClusterizer
kHCalInTemplateClusterizer
Definition at line 12 of file G4_HcalIn_EIC.C.
Function Documentation
double HCalInner (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0, int verbosity = 0)
Definition at line 28 of file G4_HcalIn_EIC.C.
References PHG4DetectorSubsystem::get_double_param(), HCalInner_SupportRing(), inner_hcal_material_Al, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().
void HCALInner_Cells (int verbosity = 0)
Definition at line 110 of file G4_HcalIn_EIC.C.
References PHG4HcalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCALInner_Clusters (int verbosity = 0)
Definition at line 175 of file G4_HcalIn_EIC.C.
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), HCalIn_clusterizer, Fun4AllServer::instance(), kHCalInGraphClusterizer, kHCalInTemplateClusterizer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCALInner_Eval (std::string outputfile, int verbosity = 0)
Definition at line 204 of file G4_HcalIn_EIC.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCalInner_SupportRing (PHG4Reco * g4Reco, const int absorberactive = 0)
A rough version of the inner HCal support ring, from Richie's CAD drawing. - Jin.
Definition at line 67 of file G4_HcalIn_EIC.C.
References i, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by HCalInner().
void HCALInner_Towers (int verbosity = 0)
Definition at line 132 of file G4_HcalIn_EIC.C.
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), inner_hcal_material_Al, Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCalInnerInit ()
graph clusterizer, RawClusterBuilderGraph
Definition at line 26 of file G4_HcalIn_EIC.C.
Referenced by G4Init().
Variable Documentation
enu_HCalIn_clusterizer HCalIn_clusterizer = kHCalInTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 20 of file G4_HcalIn_EIC.C.
Referenced by HCALInner_Clusters().
const bool inner_hcal_material_Al = false
Definition at line 9 of file G4_HcalIn_EIC.C.
Referenced by HCalInner(), and HCALInner_Towers().