Analysis Software: Prototype2RawTowerBuilder Class Reference
Prototype2RawTowerBuilder Class Reference
#include <prototype/blob/master/simulation/g4simulation/g4caloprototype/Prototype2RawTowerBuilder.h>
Public Types
enum enu_tower_energy_src { kEnergyDeposition, kLightYield, kIonizationEnergy }
Public Member Functions
Prototype2RawTowerBuilder (const std::string &name="Prototype2RawTowerBuilder")
virtual ~Prototype2RawTowerBuilder ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void Print (const std::string &what="ALL") const
void SetDefaultParameters ()
void Detector (const std::string &d)
void checkenergy (const int i=1)
enu_tower_energy_src get_tower_energy_src () const
void set_tower_energy_src (const enu_tower_energy_src towerEnergySrc)
std::string get_sim_tower_node_prefix () const
void set_sim_tower_node_prefix (const std::string &simTowerNodePrefix)
short get_tower_row (const short cellrow) const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Private Member Functions
void ReadParamsFromNodeTree (PHCompositeNode *topNode)
Private Attributes
std::string m_Detector
std::string m_TowerNodeName
std::string m_TowerGeomNodeName
std::string m_SimTowerNodePrefix
double m_Emin
int m_CheckEnergyConservationFlag
enu_tower_energy_src m_TowerEnergySrc
int m_NumCellToTower
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 14 of file Prototype2RawTowerBuilder.h.
Member Enumeration Documentation
enum Prototype2RawTowerBuilder::enu_tower_energy_src
Enumerator:
kEnergyDeposition
save Geant4 energy deposition as the weight of the cells
kLightYield
save light yield as the weight of the cells
kIonizationEnergy
save ionization energy
Definition at line 27 of file Prototype2RawTowerBuilder.h.
Constructor & Destructor Documentation
Prototype2RawTowerBuilder::Prototype2RawTowerBuilder (const std::string & name = "Prototype2RawTowerBuilder")
Definition at line 41 of file Prototype2RawTowerBuilder.cc.
References PHParameterInterface::InitializeParameters().
virtual Prototype2RawTowerBuilder::~Prototype2RawTowerBuilder () inline virtual
Definition at line 18 of file Prototype2RawTowerBuilder.h.
Member Function Documentation
void Prototype2RawTowerBuilder::checkenergy (const int i = 1) inline
Definition at line 26 of file Prototype2RawTowerBuilder.h.
References i, and m_CheckEnergyConservationFlag.
void Prototype2RawTowerBuilder::Detector (const std::string & d) inline
Definition at line 25 of file Prototype2RawTowerBuilder.h.
References d, and m_Detector.
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
std::string Prototype2RawTowerBuilder::get_sim_tower_node_prefix () const inline
Definition at line 46 of file Prototype2RawTowerBuilder.h.
References m_SimTowerNodePrefix.
enu_tower_energy_src Prototype2RawTowerBuilder::get_tower_energy_src () const inline
Definition at line 39 of file Prototype2RawTowerBuilder.h.
References m_TowerEnergySrc.
short Prototype2RawTowerBuilder::get_tower_row (const short cellrow) const
Definition at line 254 of file Prototype2RawTowerBuilder.cc.
References m_NumCellToTower.
Referenced by process_event().
int Prototype2RawTowerBuilder::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 54 of file Prototype2RawTowerBuilder.cc.
References RawTowerGeomContainer::add_tower_geometry(), PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHParameterInterface::get_double_param(), RawTowerGeomContainer::get_etabins(), PHParameterInterface::get_int_param(), RawTowerGeomContainer::get_phibins(), Fun4AllServer::instance(), kEnergyDeposition, kLightYield, m_Detector, m_Emin, m_NumCellToTower, m_SimTowerNodePrefix, m_TowerEnergySrc, m_TowerGeomNodeName, m_TowerNodeName, PHWHERE, Fun4AllServer::Print(), PHParameterInterface::PutOnParNode(), ReadParamsFromNodeTree(), PHParameterInterface::SaveToNodeTree(), PHG4PrototypeHcalDefs::scipertwr, RawTowerGeomv1::set_center_x(), RawTowerGeomv1::set_center_y(), RawTowerGeomv1::set_center_z(), RawTowerGeomContainer::set_etabins(), RawTowerGeomContainer::set_phibins(), PHParameterInterface::UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
void Prototype2RawTowerBuilder::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 286 of file Prototype2RawTowerBuilder.cc.
References m_NumCellToTower.
int Prototype2RawTowerBuilder::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 157 of file Prototype2RawTowerBuilder.cc.
References Fun4AllReturnCodes::ABORTEVENT, RawTowerContainer::AddTower(), RawTowerContainer::compress(), Fun4AllReturnCodes::EVENT_OK, PHG4ScintillatorSlat::get_column(), PHG4ScintillatorSlat::get_edep(), PHG4ScintillatorSlat::get_eion(), PHG4ScintillatorSlat::get_key(), PHG4ScintillatorSlat::get_light_yield(), PHG4ScintillatorSlat::get_row(), get_tower_row(), PHG4ScintillatorSlatContainer::getScintillatorSlats(), RawTowerContainer::getTotalEdep(), PHG4ScintillatorSlatContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), PHG4ScintillatorSlat::identify(), RawTowerContainer::identify(), kEnergyDeposition, kIonizationEnergy, kLightYield, m_CheckEnergyConservationFlag, m_Detector, m_Emin, m_TowerEnergySrc, m_TowerNodeName, PHWHERE, and Fun4AllBase::Verbosity().
void Prototype2RawTowerBuilder::ReadParamsFromNodeTree (PHCompositeNode * topNode) private
Definition at line 267 of file Prototype2RawTowerBuilder.cc.
References PHParameters::FillFrom(), PHParameters::get_int_param(), Fun4AllServer::instance(), m_Detector, pars, Fun4AllServer::Print(), PHG4PrototypeHcalDefs::scipertwr, and PHParameterInterface::set_int_param().
Referenced by InitRun().
void Prototype2RawTowerBuilder::set_sim_tower_node_prefix (const std::string & simTowerNodePrefix) inline
Definition at line 48 of file Prototype2RawTowerBuilder.h.
References m_SimTowerNodePrefix.
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
void Prototype2RawTowerBuilder::set_tower_energy_src (const enu_tower_energy_src towerEnergySrc) inline
Definition at line 41 of file Prototype2RawTowerBuilder.h.
References m_TowerEnergySrc.
void Prototype2RawTowerBuilder::SetDefaultParameters () virtual
Implements PHParameterInterface.
Definition at line 260 of file Prototype2RawTowerBuilder.cc.
References PHG4PrototypeHcalDefs::scipertwr, PHParameterInterface::set_default_double_param(), and PHParameterInterface::set_default_int_param().
Member Data Documentation
int Prototype2RawTowerBuilder::m_CheckEnergyConservationFlag private
Definition at line 64 of file Prototype2RawTowerBuilder.h.
Referenced by checkenergy(), and process_event().
std::string Prototype2RawTowerBuilder::m_Detector private
Definition at line 58 of file Prototype2RawTowerBuilder.h.
Referenced by Detector(), InitRun(), process_event(), and ReadParamsFromNodeTree().
double Prototype2RawTowerBuilder::m_Emin private
Definition at line 63 of file Prototype2RawTowerBuilder.h.
Referenced by InitRun(), and process_event().
int Prototype2RawTowerBuilder::m_NumCellToTower private
Definition at line 66 of file Prototype2RawTowerBuilder.h.
Referenced by get_tower_row(), InitRun(), and Print().
std::string Prototype2RawTowerBuilder::m_SimTowerNodePrefix private
Definition at line 61 of file Prototype2RawTowerBuilder.h.
Referenced by get_sim_tower_node_prefix(), InitRun(), and set_sim_tower_node_prefix().
enu_tower_energy_src Prototype2RawTowerBuilder::m_TowerEnergySrc private
Definition at line 65 of file Prototype2RawTowerBuilder.h.
Referenced by get_tower_energy_src(), InitRun(), process_event(), and set_tower_energy_src().
std::string Prototype2RawTowerBuilder::m_TowerGeomNodeName private
Definition at line 60 of file Prototype2RawTowerBuilder.h.
Referenced by InitRun().
std::string Prototype2RawTowerBuilder::m_TowerNodeName private
Definition at line 59 of file Prototype2RawTowerBuilder.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/simulation/g4simulation/g4caloprototype/Prototype2RawTowerBuilder.h
prototype/blob/master/simulation/g4simulation/g4caloprototype/Prototype2RawTowerBuilder.cc