Analysis Software: analysis/blob/master/EICAnalysis/macros/exclusive_analysis/jpsi_invariant_mass_plot_exclusiveReco.C File Reference
jpsi_invariant_mass_plot_exclusiveReco.C File Reference
Functions
int jpsi_invariant_mass_plot_exclusiveReco ()
void fillHist (TH1F *h, TTree *t, TString type_TString)
void hist_to_png (TH1F *h, TString saveTitle, TString type)
void hist_to_png_special (TH1F *h1, TH1F *h2, TH1F *h3, TH1F *h4, TH1F *h5, TH1F *h6, TString type)
Variables
TFile * f_1 = new TFile("/sphenix/user/gregtom3/data/Summer2018/ExclusiveReco_studies/latest_run/10x100_1M_dvmp.root","READ")
TTree * t_1_exclusive = (TTree*)f_1->Get("event_exclusive")
TTree * t_1_reco = (TTree*)f_1->Get("event_reco")
TTree * t_1_truth = (TTree*)f_1->Get("event_truth")
Function Documentation
void fillHist (TH1F * h, TTree * t, TString type_TString)
Definition at line 109 of file jpsi_invariant_mass_plot_exclusiveReco.C.
References i.
Referenced by jpsi_invariant_mass_plot_exclusiveReco(), jpsi_particle_plot(), and prob_EMC_e_pi_plotMacro().
void hist_to_png (TH1F * h, TString saveTitle, TString type)
Definition at line 175 of file jpsi_invariant_mass_plot_exclusiveReco.C.
void hist_to_png_special (TH1F * h1, TH1F * h2, TH1F * h3, TH1F * h4, TH1F * h5, TH1F * h6, TString type)
Definition at line 188 of file jpsi_invariant_mass_plot_exclusiveReco.C.
Referenced by jpsi_invariant_mass_plot_exclusiveReco().
int jpsi_invariant_mass_plot_exclusiveReco ()
Definition at line 26 of file jpsi_invariant_mass_plot_exclusiveReco.C.
References fillHist(), hist_to_png_special(), SetsPhenixStyle(), and t_1_exclusive.
Variable Documentation
TFile* f_1 = new TFile("/sphenix/user/gregtom3/data/Summer2018/ExclusiveReco_studies/latest_run/10x100_1M_dvmp.root","READ")
Definition at line 5 of file jpsi_invariant_mass_plot_exclusiveReco.C.
Referenced by track2cluster_plot().
TTree* t_1_exclusive = (TTree*)f_1->Get("event_exclusive")
Definition at line 10 of file jpsi_invariant_mass_plot_exclusiveReco.C.
Referenced by jpsi_invariant_mass_plot_exclusiveReco().
TTree* t_1_reco = (TTree*)f_1->Get("event_reco")
Definition at line 11 of file jpsi_invariant_mass_plot_exclusiveReco.C.
Referenced by jpsi_particle_plot().
TTree* t_1_truth = (TTree*)f_1->Get("event_truth")
Definition at line 12 of file jpsi_invariant_mass_plot_exclusiveReco.C.
Referenced by jpsi_particle_plot().