Analysis Software: tutorials/blob/master/cylinder/Fun4All_G4_Cylinder.C File Reference
Fun4All_G4_Cylinder.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4eval/PHG4DSTReader.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <phool/recoConsts.h>
Functions
int Fun4All_G4_Cylinder (const int nEvents=10, const char *outfile=NULL)
PHG4ParticleGenerator * get_gen (const char *name="PGENERATOR")
Function Documentation
int Fun4All_G4_Cylinder (const int nEvents = 10, const char * outfile = NULL)
Definition at line 20 of file Fun4All_G4_Cylinder.C.
References Fun4AllServer::End(), in, recoConsts::instance(), Fun4AllServer::instance(), nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4DetectorSubsystem::set_double_param(), PHG4ParticleGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4DetectorSubsystem::set_string_param(), PHG4ParticleGeneratorBase::set_vtx(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and Fun4AllBase::Verbosity().
PHG4ParticleGenerator* get_gen (const char * name = "PGENERATOR")
Definition at line 94 of file Fun4All_G4_Cylinder.C.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and name.