Analysis Software: PdbBankManager Class Reference
PdbBankManager Class Reference abstract
#include <coresoftware/blob/master/offline/database/pdbcal/base/PdbBankManager.h>
Public Member Functions
virtual PdbCalBankIterator * getIterator ()=0
Get an iterator to loop over banks.
virtual PdbCalBank * createBank (const std::string &, PdbBankID, const std::string &, PHTimeStamp &, PHTimeStamp &, const std::string &)=0
virtual PdbCalBank * createBank (const int, const std::string &, PdbBankID, const std::string &, const std::string &, const time_t duration=60)=0
virtual PdbCalBank * createBank (const int, const int, const std::string &, PdbBankID, const std::string &, const std::string &)=0
virtual PdbCalBank * fetchBank (const std::string &, PdbBankID, const std::string &, const int)=0
virtual PdbCalBank * fetchClosestBank (const std::string &, PdbBankID, const std::string &, const int)=0
virtual PdbCalBank * fetchBank (const std::string &, PdbBankID, const std::string &, const PHTimeStamp &)=0
virtual PdbCalBank * fetchClosestBank (const std::string &, PdbBankID, const std::string &, PHTimeStamp &)=0
virtual PdbApplication * getApplication ()=0
virtual void fillCalibObject (PdbCalBank *, const std::string &, PHTimeStamp &)=0
virtual void GetUsedBankRids (std::map< std::string, std::set< int > > &usedbanks) const
virtual void ClearUsedBankRids ()
virtual void SetMaxInsertTime (const PHTimeStamp &tMax)
Static Public Member Functions
static PdbBankManager * instance ()
Protected Member Functions
PdbBankManager ()
virtual ~PdbBankManager ()
Static Protected Attributes
static PdbBankManager * __instance = nullptr
Detailed Description
Definition at line 21 of file PdbBankManager.h.
Constructor & Destructor Documentation
PdbBankManager::PdbBankManager () inline protected
Definition at line 26 of file PdbBankManager.h.
PdbBankManager::~PdbBankManager () protected virtual
Definition at line 17 of file PdbBankManager.cc.
References __instance.
Member Function Documentation
virtual void PdbBankManager::ClearUsedBankRids () inline virtual
Reimplemented in PgPostBankManager.
Definition at line 107 of file PdbBankManager.h.
virtual PdbCalBank* PdbBankManager::createBank (const std::string & , PdbBankID , const std::string & , PHTimeStamp & , PHTimeStamp & , const std::string &) pure virtual
Implemented in PgPostBankManager.
Referenced by PHParametersContainer::WriteToDB(), and PHParameters::WriteToDB().
virtual PdbCalBank* PdbBankManager::createBank (const int , const std::string & , PdbBankID , const std::string & , const std::string & , const time_t duration = 60) pure virtual
Implemented in PgPostBankManager.
virtual PdbCalBank* PdbBankManager::createBank (const int , const int , const std::string & , PdbBankID , const std::string & , const std::string &) pure virtual
Implemented in PgPostBankManager.
virtual PdbCalBank* PdbBankManager::fetchBank (const std::string & , PdbBankID , const std::string & , const int) pure virtual
Implemented in PgPostBankManager.
Referenced by PHParameters::ReadFromDB().
virtual PdbCalBank* PdbBankManager::fetchBank (const std::string & , PdbBankID , const std::string & , const PHTimeStamp &) pure virtual
Implemented in PgPostBankManager.
virtual PdbCalBank* PdbBankManager::fetchClosestBank (const std::string & , PdbBankID , const std::string & , const int) pure virtual
Implemented in PgPostBankManager.
virtual PdbCalBank* PdbBankManager::fetchClosestBank (const std::string & , PdbBankID , const std::string & , PHTimeStamp &) pure virtual
Implemented in PgPostBankManager.
virtual void PdbBankManager::fillCalibObject (PdbCalBank * , const std::string & , PHTimeStamp &) pure virtual
Implemented in PgPostBankManager.
virtual PdbApplication* PdbBankManager::getApplication () pure virtual
Implemented in PgPostBankManager.
Referenced by PHParameters::ReadFromDB(), PHParametersContainer::WriteToDB(), and PHParameters::WriteToDB().
virtual PdbCalBankIterator* PdbBankManager::getIterator () pure virtual
Get an iterator to loop over banks.
Implemented in PgPostBankManager.
virtual void PdbBankManager::GetUsedBankRids (std::map< std::string, std::set< int > > & usedbanks) const inline virtual
Reimplemented in PgPostBankManager.
Definition at line 106 of file PdbBankManager.h.
PdbBankManager * PdbBankManager::instance () static
Definition at line 22 of file PdbBankManager.cc.
References __instance.
Referenced by PHParameters::ReadFromDB(), PHParametersContainer::WriteToDB(), and PHParameters::WriteToDB().
virtual void PdbBankManager::SetMaxInsertTime (const PHTimeStamp & tMax) inline virtual
Reimplemented in PgPostBankManager.
Definition at line 108 of file PdbBankManager.h.
Member Data Documentation
PdbBankManager * PdbBankManager::__instance = nullptr static protected
Definition at line 112 of file PdbBankManager.h.
Referenced by instance(), and ~PdbBankManager().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/base/PdbBankManager.h
coresoftware/blob/master/offline/database/pdbcal/base/PdbBankManager.cc