Analysis Software: PHPatternReco Class Reference
PHPatternReco Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHPatternReco.h>
Public Member Functions
PHPatternReco (unsigned int nlayers=7, unsigned int min_nlayers=7, const std::string &name="PHPatternReco")
virtual ~PHPatternReco ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_file_name (const std::string &fname)
void set_mag_field (float mag_field)
float get_mag_field () const
void set_min_pT (float pt)
void set_max_kappa (float kappa_max)
void set_min_d (float d_min)
void set_max_d (float d_max)
void set_min_dzdl (float dzdl_min)
void set_max_dzdl (float dzdl_max)
void set_min_z0 (float z0_min)
void set_max_z0 (float z0_max)
float get_max_kappa () const
float get_min_z0 () const
float get_max_z0 () const
void set_material (int layer, float value)
radiation length per layer, sequential layer indexes required here
void setCutOnDCA (bool cod)
turn on DCA limitation
void set_dcaxy_cut (float dcut)
sets an upper limit on X-Y DCA
void set_dcaz_cut (float dzcut)
sets an upper limit on Z DCA
void set_chi2_cut (float chi2_cut)
sets a chi2 cut
void set_ca_z_cut (float z_cut)
void setPtRescaleFactor (float pt_rescale)
void set_ca_phi_cut (float phi_cut)
void set_mult_onebin (float mult)
void set_mult_twobins (float mult)
void set_mult_threebins (float mult)
void set_min_zvtx_tracks (unsigned int min_zvtx_tracks)
const std::vector< int > & get_seeding_layer () const
void set_seeding_layer (const int *seedingLayer, const int n)
void add_zoom (unsigned int n_kappa, unsigned int n_phi, unsigned int n_d, unsigned int n_dzdl, unsigned int n_z0)
void set_nzooms ()
void reset_zooms ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int create_nodes (PHCompositeNode *topNode)
int initialize_geometry (PHCompositeNode *topNode)
int get_nodes (PHCompositeNode *topNode)
int translate_input (PHCompositeNode *topNode)
void set_nbins (unsigned int izoom)
void initialize_houghbin ()
void vote_z_init (unsigned int zoomlevel)
void find_track_candidates_z_init (unsigned int zoomlevel)
void vote_z (unsigned int zoomlevel)
void find_track_candidates_z (unsigned int zoomlevel)
void vote_xy (unsigned int zoomlevel)
void find_track_candidates_xy (unsigned int zoomlevel)
void prune_z (unsigned int zoomlevel)
void prune_xy (unsigned int zoomlevel)
void reset_hits_used ()
int export_output ()
float kappa_to_pt (float kappa)
convert from inverse curvature to momentum
float pt_to_kappa (float pt)
convert from momentum to inverse curvature
void bins_to_SimpleTrack3D (std::vector< SimpleTrack3D > &temp_tracks, int imap, unsigned int zoomlevel)
int build_triplets_to_SimpleTrack3D (std::vector< SimpleTrack3D > &new_tracks, bool forward)
int turnoff_hits_used_in_triplets ()
int cellular_automaton_zvtx_init (std::vector< SimpleTrack3D > &temp_tracks)
int fit_vertex ()
void convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const &input, Eigen::Matrix< float, 6, 6 > &output)
convert the covariance from HelixHough coords to x,y,z,px,py,pz
void shift_coordinate_system (double dx, double dy, double dz)
float shift_phi_range (float phi)
Private Attributes
int _event
PHTimer * _t_output_io
std::vector< int > _seeding_layer
unsigned int _nlayers
number of detector layers
unsigned int _min_nlayers
minimum number of layers to make a track
unsigned int _ca_nlayers
unsigned int _ca_min_nlayers
float _ca_chi2
std::vector< float > _radii
radial distance of each layer (cm)
std::vector< float > _material
material at each layer in rad. lengths
std::map< int, float > _user_material
material in user ladder indexes
float _mag_field
in Tesla
bool _remove_hits
bool _use_max_kappa
bool fill_multi_zvtx
float _min_pt
float _max_kappa
float _min_d
float _max_d
float _min_dzdl
float _max_dzdl
float _min_z0
float _max_z0
bool _cut_on_dca
float _dcaxy_cut
float _dcaz_cut
float _pt_rescale
float _ca_phi_cut
float _ca_z_cut
float _z_cut
float _mult_onebin
float _mult_twobins
float _mult_threebins
unsigned int _min_zvtx_tracks
unsigned int bin
unsigned int ik
unsigned int ip
unsigned int id
unsigned int il
unsigned int iz
unsigned int nkappa
unsigned int nphi
unsigned int nd
unsigned int ndzdl
unsigned int nz0
unsigned int cluster_id
std::map< int, unsigned int > _layer_ilayer_map
recorded layer indexes to internal sequential indexes
std::vector< SimpleTrack3D > _temp_tracks
std::vector< SimpleTrack3D > _tracks
working array of tracks
std::vector< HelixKalmanState > _track_states
std::vector< double > _track_errors
working array of track chisq
std::vector< Eigen::Matrix
< float, 5, 5 > > _track_covars
working array of track covariances
std::vector< float > _vertex
working array for collision vertex
std::vector< std::vector< float > > _vertex_list
BbcVertexMap * _bbc_vertexes
TrkrClusterContainer * _clustermap
SvtxTrackMap * _trackmap
SvtxVertexMap * _vertexmap
VertexFitter _vertex_finder
HelixHoughSpace * _hough_space
HelixHoughFuncs * _hough_funcs
int _mode
TNtuple * _ntp_zvtx_by_event
TNtuple * _ntp_zvtx_by_track
TH2D * _z0_dzdl
TH2D * _kappa_phi
TH2D * _d_phi
TH3D * _kappa_d_phi
TFile * _ofile
TFile * _ofile2
std::string _fname
int _nlayers_all
std::map< int, unsigned int > _layer_ilayer_map_all
std::vector< float > _radii_all
std::vector< std::vector
< unsigned int > > zooms_vec
std::map< unsigned int, bool > hits_used
std::map< unsigned int,
SimpleHit3D > hits_map
std::map< unsigned int,
HelixHoughBin * > bins_map
std::map< unsigned int,
HelixHoughBin * > bins_map_prev
std::map< unsigned int,
HelixHoughBin * > bins_map_cur
std::map< unsigned int,
HelixHoughBin * > bins_map_sel
std::map< unsigned int,
unsigned int > kappa_phi_map
std::map< unsigned int,
unsigned int > d_phi_map
std::map< unsigned int,
unsigned int > kappa_d_phi_map
float hit [50][3]
float hitpos3d [3]
unsigned int nzooms
bool separate_helicity
int helicity
int n_vtx_tracks
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 40 of file PHPatternReco.h.
Constructor & Destructor Documentation
PHPatternReco::PHPatternReco (unsigned int nlayers = 7, unsigned int min_nlayers = 7, const std::string & name = "PHPatternReco")
Definition at line 75 of file PHPatternReco.cc.
References _event, and zooms_vec.
PHPatternReco::~PHPatternReco () virtual
Definition at line 173 of file PHPatternReco.cc.
References _hough_funcs, _hough_space, and _t_output_io.
Member Function Documentation
void PHPatternReco::add_zoom (unsigned int n_kappa, unsigned int n_phi, unsigned int n_d, unsigned int n_dzdl, unsigned int n_z0)
Definition at line 498 of file PHPatternReco.cc.
References zooms_vec.
Referenced by process_event().
void PHPatternReco::bins_to_SimpleTrack3D (std::vector< SimpleTrack3D > & temp_tracks, int imap, unsigned int zoomlevel) private
Definition at line 1844 of file PHPatternReco.cc.
References _tracks, HelixHoughBin::begin_clusters(), bins_map_prev, bins_map_sel, SimpleTrack3D::d, SimpleTrack3D::dzdl, HelixHoughBin::end_clusters(), HelixHoughBin::get_count(), HelixHoughBin::get_dzdl_center(), HelixHoughBin::get_kappa_center(), HelixHoughBin::get_phi_center(), HelixHoughBin::get_z0_center(), hit, SimpleTrack3D::hits, hits_map, it, SimpleTrack3D::kappa, SimpleTrack3D::phi, and SimpleTrack3D::z0.
Referenced by process_event().
int PHPatternReco::build_triplets_to_SimpleTrack3D (std::vector< SimpleTrack3D > & new_tracks, bool forward) private
Definition at line 1906 of file PHPatternReco.cc.
References _ca_phi_cut, _nlayers, _z_cut, cluster_id, SimpleHit3D::get_id(), SimpleHit3D::get_layer(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), hit, SimpleTrack3D::hits, hits_map, hits_used, it, M_PI, and shift_phi_range().
Referenced by process_event().
int PHPatternReco::cellular_automaton_zvtx_init (std::vector< SimpleTrack3D > & temp_tracks) private
Definition at line 2048 of file PHPatternReco.cc.
References _ca_chi2, _ca_nlayers, _ca_phi_cut, _ca_z_cut, _dcaxy_cut, _hough_space, _mag_field, _material, _pt_rescale, _radii, _track_states, _tracks, Fun4AllReturnCodes::EVENT_OK, hits_map, hits_used, i, CellularAutomaton_v1::Reset(), CellularAutomaton_v1::run(), CellularAutomaton_v1::set_ca_chi2(), CellularAutomaton_v1::set_ca_chi2_layer(), CellularAutomaton_v1::set_ca_dcaxy_cut(), CellularAutomaton_v1::set_ca_phi_cut(), CellularAutomaton_v1::set_ca_z_cut(), CellularAutomaton_v1::set_hits_map(), CellularAutomaton_v1::set_hough_space(), CellularAutomaton_v1::set_mag_field(), CellularAutomaton_v1::set_n_layers(), CellularAutomaton_v1::set_propagate_forward(), CellularAutomaton_v1::set_pt_rescale(), CellularAutomaton_v1::set_remove_hits(), CellularAutomaton_v1::set_remove_inner_hits(), CellularAutomaton_v1::set_required_layers(), CellularAutomaton_v1::set_seeding_mode(), and CellularAutomaton_v1::set_triplet_mode().
Referenced by process_event().
void PHPatternReco::convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const & input, Eigen::Matrix< float, 6, 6 > & output) private
convert the covariance from HelixHough coords to x,y,z,px,py,pz
Definition at line 2371 of file PHPatternReco.cc.
References d, and dzdl.
int PHPatternReco::create_nodes (PHCompositeNode * topNode) private
Definition at line 503 of file PHPatternReco.cc.
References _trackmap, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int PHPatternReco::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 471 of file PHPatternReco.cc.
References _d_phi, _kappa_d_phi, _kappa_phi, _ntp_zvtx_by_event, _ntp_zvtx_by_track, _ofile, _ofile2, _temp_tracks, _z0_dzdl, and Fun4AllReturnCodes::EVENT_OK.
int PHPatternReco::export_output () private
Definition at line 816 of file PHPatternReco.cc.
References _clustermap, _mag_field, _track_covars, _track_errors, _trackmap, _tracks, _vertex, _vertex_list, _vertexmap, SvtxVertexMap::begin(), col, d, dzdl, SvtxVertexMap::end(), Fun4AllReturnCodes::EVENT_OK, SvtxVertex::get_id(), SvtxTrack_v1::get_id(), SvtxVertex::get_position(), SvtxTrack_v1::get_px(), SvtxTrack_v1::get_py(), SvtxTrack_v1::get_pz(), SvtxTrack_v1::get_quality(), TrkrDefs::getLayer(), helicity, hits_map, i, SvtxVertex::identify(), SvtxTrackMap::insert(), SvtxVertexMap::insert_clone(), SvtxTrack_v1::insert_cluster_key(), SvtxVertex_v1::insert_track(), it, kappa_to_pt(), M_PI, phi, SvtxTrack_v1::set_charge(), SvtxVertex_v1::set_chisq(), SvtxTrack_v1::set_dca2d(), SvtxVertex_v1::set_error(), SvtxTrack_v1::set_id(), SvtxTrack_v1::set_ndf(), SvtxVertex_v1::set_ndof(), SvtxVertex_v1::set_position(), SvtxTrack_v1::set_px(), SvtxTrack_v1::set_py(), SvtxTrack_v1::set_pz(), SvtxVertex_v1::set_t0(), SvtxTrack_v1::set_x(), SvtxTrack_v1::set_y(), SvtxTrack_v1::set_z(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHPatternReco::find_track_candidates_xy (unsigned int zoomlevel) private
Definition at line 1684 of file PHPatternReco.cc.
References _min_nlayers, bin, bins_map_cur, bins_map_prev, HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughBin::get_phi_bin(), HelixHoughBin::get_z0_bin(), ik, il, ip, it, and iz.
Referenced by process_event().
void PHPatternReco::find_track_candidates_z (unsigned int zoomlevel) private
Definition at line 1360 of file PHPatternReco.cc.
References _min_nlayers, bin, bins_map_cur, bins_map_sel, HelixHoughBin::get_count(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_z0_bin(), il, it, and iz.
Referenced by process_event().
void PHPatternReco::find_track_candidates_z_init (unsigned int zoomlevel) private
Definition at line 1175 of file PHPatternReco.cc.
References _hough_space, _min_nlayers, _z0_dzdl, bin, bins, bins_map, bins_map_sel, HelixHoughSpace::get_bin(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_z0_bins(), i, j, and k.
Referenced by process_event().
int PHPatternReco::fit_vertex () private
< working array of track chisq
< working array of track covariances
Definition at line 2135 of file PHPatternReco.cc.
References _dcaz_cut, _event, _max_z0, _min_z0, _min_zvtx_tracks, _mult_onebin, _mult_twobins, _ntp_zvtx_by_event, _ntp_zvtx_by_track, _track_covars, _track_errors, _track_states, _tracks, _vertex, _vertex_finder, _vertex_list, C, Fun4AllReturnCodes::EVENT_OK, fill_multi_zvtx, VertexFitter::findVertex(), i, iz, j, k, n_vtx_tracks, SimpleTrack3D::set_vertex_id(), and Fun4AllBase::Verbosity().
float PHPatternReco::get_mag_field () const inline
Definition at line 58 of file PHPatternReco.h.
References _mag_field.
float PHPatternReco::get_max_kappa () const inline
Definition at line 73 of file PHPatternReco.h.
References _max_kappa.
float PHPatternReco::get_max_z0 () const inline
Definition at line 75 of file PHPatternReco.h.
References _max_z0.
float PHPatternReco::get_min_z0 () const inline
Definition at line 74 of file PHPatternReco.h.
References _min_z0.
int PHPatternReco::get_nodes (PHCompositeNode * topNode) private
Definition at line 705 of file PHPatternReco.cc.
References _bbc_vertexes, _clustermap, _trackmap, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
const std::vector<int>& PHPatternReco::get_seeding_layer () const inline
Definition at line 133 of file PHPatternReco.h.
References _seeding_layer.
int PHPatternReco::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 181 of file PHPatternReco.cc.
References _d_phi, _hough_funcs, _hough_space, _kappa_d_phi, _kappa_phi, _max_d, _max_dzdl, _max_kappa, _max_z0, _min_d, _min_dzdl, _min_pt, _min_z0, _use_max_kappa, _z0_dzdl, HelixHoughSpace::add_one_zoom(), Fun4AllReturnCodes::EVENT_OK, HelixHoughSpace::get_d_max(), HelixHoughSpace::get_d_min(), HelixHoughSpace::get_dzdl_max(), HelixHoughSpace::get_dzdl_min(), HelixHoughSpace::get_kappa_max(), HelixHoughSpace::get_kappa_min(), HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), HelixHoughSpace::get_n_z0_bins(), HelixHoughSpace::get_phi_max(), HelixHoughSpace::get_phi_min(), HelixHoughSpace::get_z0_max(), HelixHoughSpace::get_z0_min(), M_PI, nzooms, pt_to_kappa(), HelixHoughSpace::set_d_max(), HelixHoughSpace::set_d_min(), HelixHoughSpace::set_dzdl_max(), HelixHoughSpace::set_dzdl_min(), HelixHoughFuncs::set_hough_space(), HelixHoughSpace::set_kappa_max(), HelixHoughSpace::set_kappa_min(), set_nzooms(), HelixHoughSpace::set_phi_max(), HelixHoughSpace::set_phi_min(), HelixHoughSpace::set_z0_max(), HelixHoughSpace::set_z0_min(), and zooms_vec.
Referenced by process_event().
int PHPatternReco::initialize_geometry (PHCompositeNode * topNode) private
Definition at line 544 of file PHPatternReco.cc.
References _layer_ilayer_map, _layer_ilayer_map_all, _material, _nlayers, _nlayers_all, _radii, _radii_all, _seeding_layer, _user_material, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderGeom::get_layer(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4CylinderCellGeom::get_thickness(), PHG4CylinderGeom::get_thickness(), and findNode::getClass().
Referenced by InitRun().
void PHPatternReco::initialize_houghbin () private
Definition at line 1052 of file PHPatternReco.cc.
References _hough_space, bin, bins, bins_map, HelixHoughSpace::get_bin(), id, HelixHoughBin::identify(), ik, il, HelixHoughBin::init(), ip, iz, nd, ndzdl, nkappa, nphi, nz0, HelixHoughBin::set_hough_space(), and HelixHoughBin::set_zoomlevel().
Referenced by process_event().
int PHPatternReco::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 237 of file PHPatternReco.cc.
References _cut_on_dca, _dcaxy_cut, _dcaz_cut, _fname, _mag_field, _material, _min_nlayers, _min_pt, _nlayers, _ntp_zvtx_by_event, _ntp_zvtx_by_track, _ofile2, _pt_rescale, _radii, _t_output_io, Fun4AllReturnCodes::ABORTRUN, create_nodes(), Fun4AllReturnCodes::EVENT_OK, i, initialize_geometry(), PHTimer::stop(), and Fun4AllBase::Verbosity().
float PHPatternReco::kappa_to_pt (float kappa) private
convert from inverse curvature to momentum
Definition at line 1031 of file PHPatternReco.cc.
References _mag_field, and _pt_rescale.
Referenced by export_output().
int PHPatternReco::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 287 of file PHPatternReco.cc.
References _ca_nlayers, _event, _temp_tracks, _track_covars, _track_errors, _track_states, _tracks, _vertex, _vertex_list, add_zoom(), bins_map, bins_map_cur, bins_map_prev, bins_map_sel, bins_to_SimpleTrack3D(), build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), Fun4AllReturnCodes::EVENT_OK, export_output(), find_track_candidates_xy(), find_track_candidates_z(), find_track_candidates_z_init(), get_nodes(), helicity, hits_map, hits_used, i, Init(), initialize_houghbin(), prune_xy(), prune_z(), reset_zooms(), separate_helicity, set_nbins(), shift_coordinate_system(), translate_input(), turnoff_hits_used_in_triplets(), Fun4AllBase::Verbosity(), vote_xy(), vote_z(), and vote_z_init().
void PHPatternReco::prune_xy (unsigned int zoomlevel) private
Definition at line 1780 of file PHPatternReco.cc.
References _nlayers, HelixHoughBin::add_cluster_ID(), bins_map_prev, HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_global_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughBin::get_neighbors_global_bin(), HelixHoughBin::get_phi_bin(), HelixHoughBin::get_z0_bin(), it, set_nbins(), and sign().
Referenced by process_event().
void PHPatternReco::prune_z (unsigned int zoomlevel) private
Definition at line 1727 of file PHPatternReco.cc.
References _nlayers, HelixHoughBin::add_cluster_ID(), bins_map_sel, HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_global_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughBin::get_neighbors_global_bin(), HelixHoughBin::get_phi_bin(), HelixHoughBin::get_z0_bin(), it, set_nbins(), and sign().
Referenced by process_event().
float PHPatternReco::pt_to_kappa (float pt) private
convert from momentum to inverse curvature
Definition at line 1035 of file PHPatternReco.cc.
References _mag_field, and _pt_rescale.
Referenced by Init().
void PHPatternReco::reset_hits_used () private
Definition at line 1836 of file PHPatternReco.cc.
References hits_used, and it.
void PHPatternReco::reset_zooms () inline
Definition at line 144 of file PHPatternReco.h.
References zooms_vec.
Referenced by process_event().
void PHPatternReco::set_ca_phi_cut (float phi_cut) inline
Definition at line 108 of file PHPatternReco.h.
References _ca_phi_cut.
void PHPatternReco::set_ca_z_cut (float z_cut) inline
Definition at line 97 of file PHPatternReco.h.
References _ca_z_cut.
void PHPatternReco::set_chi2_cut (float chi2_cut) inline
sets a chi2 cut
Definition at line 93 of file PHPatternReco.h.
References _ca_chi2.
void PHPatternReco::set_dcaxy_cut (float dcut) inline
sets an upper limit on X-Y DCA
Definition at line 85 of file PHPatternReco.h.
References _dcaxy_cut.
void PHPatternReco::set_dcaz_cut (float dzcut) inline
sets an upper limit on Z DCA
Definition at line 89 of file PHPatternReco.h.
References _dcaz_cut.
void PHPatternReco::set_file_name (const std::string & fname) inline
Definition at line 54 of file PHPatternReco.h.
References _fname.
void PHPatternReco::set_mag_field (float mag_field) inline
Definition at line 55 of file PHPatternReco.h.
References _mag_field.
void PHPatternReco::set_material (int layer, float value)
radiation length per layer, sequential layer indexes required here
Definition at line 494 of file PHPatternReco.cc.
References _user_material, and value.
void PHPatternReco::set_max_d (float d_max) inline
Definition at line 68 of file PHPatternReco.h.
References _max_d.
void PHPatternReco::set_max_dzdl (float dzdl_max) inline
Definition at line 70 of file PHPatternReco.h.
References _max_dzdl.
void PHPatternReco::set_max_kappa (float kappa_max)
Definition at line 1039 of file PHPatternReco.cc.
References _max_kappa, and _use_max_kappa.
void PHPatternReco::set_max_z0 (float z0_max) inline
Definition at line 72 of file PHPatternReco.h.
References _max_z0.
void PHPatternReco::set_min_d (float d_min) inline
Definition at line 67 of file PHPatternReco.h.
References _min_d.
void PHPatternReco::set_min_dzdl (float dzdl_min) inline
Definition at line 69 of file PHPatternReco.h.
References _min_dzdl.
void PHPatternReco::set_min_pT (float pt) inline
Definition at line 62 of file PHPatternReco.h.
References _min_pt.
void PHPatternReco::set_min_z0 (float z0_min) inline
Definition at line 71 of file PHPatternReco.h.
References _min_z0.
void PHPatternReco::set_min_zvtx_tracks (unsigned int min_zvtx_tracks) inline
Definition at line 128 of file PHPatternReco.h.
References _min_zvtx_tracks.
void PHPatternReco::set_mult_onebin (float mult) inline
Definition at line 113 of file PHPatternReco.h.
References _mult_onebin.
void PHPatternReco::set_mult_threebins (float mult) inline
Definition at line 123 of file PHPatternReco.h.
References _mult_threebins.
void PHPatternReco::set_mult_twobins (float mult) inline
Definition at line 118 of file PHPatternReco.h.
References _mult_twobins.
void PHPatternReco::set_nbins (unsigned int izoom) private
Definition at line 1044 of file PHPatternReco.cc.
References _hough_space, HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), HelixHoughSpace::get_n_z0_bins(), nd, ndzdl, nkappa, nphi, and nz0.
Referenced by process_event(), prune_xy(), prune_z(), vote_xy(), and vote_z().
void PHPatternReco::set_nzooms () inline
Definition at line 143 of file PHPatternReco.h.
References nzooms, and zooms_vec.
Referenced by Init().
void PHPatternReco::set_seeding_layer (const int * seedingLayer, const int n) inline
Definition at line 137 of file PHPatternReco.h.
References _seeding_layer.
void PHPatternReco::setCutOnDCA (bool cod) inline
turn on DCA limitation
Definition at line 81 of file PHPatternReco.h.
References _cut_on_dca.
void PHPatternReco::setPtRescaleFactor (float pt_rescale) inline
adjust the fit pt by a recalibration factor (constant B versus real mag field)
Definition at line 104 of file PHPatternReco.h.
References _pt_rescale.
void PHPatternReco::shift_coordinate_system (double dx, double dy, double dz) private
Definition at line 2412 of file PHPatternReco.cc.
References _tracks, _vertex, dx, dy, SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), hit, hits_map, it, SimpleHit3D::set_x(), SimpleHit3D::set_y(), and SimpleHit3D::set_z().
Referenced by process_event().
float PHPatternReco::shift_phi_range (float phi) private
Definition at line 2441 of file PHPatternReco.cc.
References M_PI.
Referenced by build_triplets_to_SimpleTrack3D().
int PHPatternReco::translate_input (PHCompositeNode * topNode) private
Definition at line 746 of file PHPatternReco.cc.
References _clustermap, _layer_ilayer_map, _nlayers, Fun4AllReturnCodes::EVENT_OK, SimpleHit3D::get_id(), TrkrClusterContainer::getClusters(), TrkrCluster::getError(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), hit, hits_map, hits_used, i, it, j, SimpleHit3D::print(), SimpleHit3D::set_cluskey(), SimpleHit3D::set_error(), SimpleHit3D::set_id(), SimpleHit3D::set_layer(), SimpleHit3D::set_size(), SimpleHit3D::set_x(), SimpleHit3D::set_y(), SimpleHit3D::set_z(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHPatternReco::turnoff_hits_used_in_triplets () private
Definition at line 2026 of file PHPatternReco.cc.
References _trackmap, SvtxTrackMap::begin(), SvtxTrack::begin_clusters(), cluster_id, SvtxTrackMap::end(), SvtxTrack::end_clusters(), and hits_used.
Referenced by process_event().
void PHPatternReco::vote_xy (unsigned int zoomlevel) private
Definition at line 1398 of file PHPatternReco.cc.
References _d_phi, _hough_funcs, _hough_space, _kappa_d_phi, _kappa_phi, HelixHoughBin::add_cluster_ID(), HelixHoughBin::begin_clusters(), bin, bins_map_cur, bins_map_sel, HelixHoughFuncs::calculate_phi_range(), HelixHoughBin::clear_clusters(), PHObject::Clone(), cluster_id, d_phi_map, HelixHoughBin::end_clusters(), HelixHoughSpace::get_bin(), HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughSpace::get_d_bin_size(), HelixHoughBin::get_d_center(), HelixHoughSpace::get_d_min(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_global_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughSpace::get_kappa_bin_size(), HelixHoughBin::get_kappa_center(), HelixHoughSpace::get_kappa_min(), HelixHoughSpace::get_n_phi_bins(), HelixHoughBin::get_phi_bin(), HelixHoughSpace::get_phi_bin(), HelixHoughSpace::get_phi_bin_size(), HelixHoughBin::get_phi_center(), HelixHoughSpace::get_phi_max(), HelixHoughSpace::get_phi_min(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), HelixHoughBin::get_z0_bin(), helicity, hit, hitpos3d, hits_map, i, id, ik, il, ip, it, iz, kappa_d_phi_map, kappa_phi_map, nd, nkappa, separate_helicity, HelixHoughBin::set_bin(), HelixHoughBin::set_bins(), HelixHoughFuncs::set_current_zoom(), set_nbins(), and HelixHoughBin::set_zoomlevel().
Referenced by process_event().
void PHPatternReco::vote_z (unsigned int zoomlevel) private
Definition at line 1232 of file PHPatternReco.cc.
References _hough_funcs, _hough_space, _z0_dzdl, HelixHoughBin::add_cluster_ID(), bin, bins_map_cur, bins_map_prev, HelixHoughFuncs::calculate_dzdl_range(), HelixHoughBin::clear_clusters(), PHObject::Clone(), cluster_id, HelixHoughSpace::get_bin(), HelixHoughSpace::get_d_bin_size(), HelixHoughBin::get_d_center(), HelixHoughSpace::get_dzdl_bin(), HelixHoughSpace::get_dzdl_bin_size(), HelixHoughBin::get_dzdl_center(), HelixHoughBin::get_global_bin(), HelixHoughSpace::get_kappa_bin_size(), HelixHoughBin::get_kappa_center(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_z0_bins(), HelixHoughSpace::get_phi_bin_size(), HelixHoughBin::get_phi_center(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), HelixHoughSpace::get_z0_bin_size(), HelixHoughBin::get_z0_center(), hit, hitpos3d, hits_map, il, it, iz, HelixHoughBin::set_bin(), HelixHoughBin::set_bins(), HelixHoughFuncs::set_current_zoom(), set_nbins(), and HelixHoughBin::set_zoomlevel().
Referenced by process_event().
void PHPatternReco::vote_z_init (unsigned int zoomlevel) private
Definition at line 1079 of file PHPatternReco.cc.
References _hough_funcs, _hough_space, bin, bins_map, HelixHoughFuncs::calculate_dzdl_range(), cluster_id, HelixHoughSpace::get_bin(), HelixHoughSpace::get_d_max(), HelixHoughSpace::get_d_min(), HelixHoughSpace::get_dzdl_bin(), HelixHoughSpace::get_dzdl_max(), HelixHoughSpace::get_dzdl_min(), HelixHoughSpace::get_kappa_max(), HelixHoughSpace::get_kappa_min(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_z0_bins(), HelixHoughSpace::get_phi_max(), HelixHoughSpace::get_phi_min(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), HelixHoughSpace::get_z0_bin_size(), HelixHoughSpace::get_z0_min(), hit, hitpos3d, hits_map, hits_used, il, it, iz, and HelixHoughFuncs::set_current_zoom().
Referenced by process_event().
Member Data Documentation
BbcVertexMap* PHPatternReco::_bbc_vertexes private
Definition at line 277 of file PHPatternReco.h.
Referenced by get_nodes().
float PHPatternReco::_ca_chi2 private
Definition at line 214 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), and set_chi2_cut().
unsigned int PHPatternReco::_ca_min_nlayers private
Definition at line 212 of file PHPatternReco.h.
unsigned int PHPatternReco::_ca_nlayers private
Definition at line 211 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), and process_event().
float PHPatternReco::_ca_phi_cut private
Definition at line 239 of file PHPatternReco.h.
Referenced by build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), and set_ca_phi_cut().
float PHPatternReco::_ca_z_cut private
Definition at line 240 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), and set_ca_z_cut().
TrkrClusterContainer* PHPatternReco::_clustermap private
Definition at line 278 of file PHPatternReco.h.
Referenced by export_output(), get_nodes(), and translate_input().
bool PHPatternReco::_cut_on_dca private
Definition at line 235 of file PHPatternReco.h.
Referenced by InitRun(), and setCutOnDCA().
TH2D* PHPatternReco::_d_phi private
Definition at line 293 of file PHPatternReco.h.
Referenced by End(), Init(), and vote_xy().
float PHPatternReco::_dcaxy_cut private
Definition at line 236 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), InitRun(), and set_dcaxy_cut().
float PHPatternReco::_dcaz_cut private
Definition at line 237 of file PHPatternReco.h.
Referenced by fit_vertex(), InitRun(), and set_dcaz_cut().
int PHPatternReco::_event private
Definition at line 204 of file PHPatternReco.h.
Referenced by fit_vertex(), PHPatternReco(), and process_event().
std::string PHPatternReco::_fname private
Definition at line 298 of file PHPatternReco.h.
Referenced by InitRun(), and set_file_name().
HelixHoughFuncs* PHPatternReco::_hough_funcs private
Definition at line 284 of file PHPatternReco.h.
Referenced by Init(), vote_xy(), vote_z(), vote_z_init(), and ~PHPatternReco().
HelixHoughSpace* PHPatternReco::_hough_space private
Definition at line 283 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), find_track_candidates_z_init(), Init(), initialize_houghbin(), set_nbins(), vote_xy(), vote_z(), vote_z_init(), and ~PHPatternReco().
TH3D* PHPatternReco::_kappa_d_phi private
Definition at line 294 of file PHPatternReco.h.
Referenced by End(), Init(), and vote_xy().
TH2D* PHPatternReco::_kappa_phi private
Definition at line 292 of file PHPatternReco.h.
Referenced by End(), Init(), and vote_xy().
std::map<int, unsigned int> PHPatternReco::_layer_ilayer_map private
recorded layer indexes to internal sequential indexes
Definition at line 265 of file PHPatternReco.h.
Referenced by initialize_geometry(), and translate_input().
std::map<int, unsigned int> PHPatternReco::_layer_ilayer_map_all private
Definition at line 300 of file PHPatternReco.h.
Referenced by initialize_geometry().
float PHPatternReco::_mag_field private
in Tesla
Definition at line 219 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), export_output(), get_mag_field(), InitRun(), kappa_to_pt(), pt_to_kappa(), and set_mag_field().
std::vector<float> PHPatternReco::_material private
material at each layer in rad. lengths
Definition at line 216 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), initialize_geometry(), and InitRun().
float PHPatternReco::_max_d private
Definition at line 229 of file PHPatternReco.h.
Referenced by Init(), and set_max_d().
float PHPatternReco::_max_dzdl private
Definition at line 231 of file PHPatternReco.h.
Referenced by Init(), and set_max_dzdl().
float PHPatternReco::_max_kappa private
Definition at line 227 of file PHPatternReco.h.
Referenced by get_max_kappa(), Init(), and set_max_kappa().
float PHPatternReco::_max_z0 private
Definition at line 233 of file PHPatternReco.h.
Referenced by fit_vertex(), get_max_z0(), Init(), and set_max_z0().
float PHPatternReco::_min_d private
Definition at line 228 of file PHPatternReco.h.
Referenced by Init(), and set_min_d().
float PHPatternReco::_min_dzdl private
Definition at line 230 of file PHPatternReco.h.
Referenced by Init(), and set_min_dzdl().
unsigned int PHPatternReco::_min_nlayers private
minimum number of layers to make a track
Definition at line 210 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), find_track_candidates_z_init(), and InitRun().
float PHPatternReco::_min_pt private
Definition at line 226 of file PHPatternReco.h.
Referenced by Init(), InitRun(), and set_min_pT().
float PHPatternReco::_min_z0 private
Definition at line 232 of file PHPatternReco.h.
Referenced by fit_vertex(), get_min_z0(), Init(), and set_min_z0().
unsigned int PHPatternReco::_min_zvtx_tracks private
Definition at line 245 of file PHPatternReco.h.
Referenced by fit_vertex(), and set_min_zvtx_tracks().
int PHPatternReco::_mode private
Definition at line 288 of file PHPatternReco.h.
float PHPatternReco::_mult_onebin private
Definition at line 242 of file PHPatternReco.h.
Referenced by fit_vertex(), and set_mult_onebin().
float PHPatternReco::_mult_threebins private
Definition at line 244 of file PHPatternReco.h.
Referenced by set_mult_threebins().
float PHPatternReco::_mult_twobins private
Definition at line 243 of file PHPatternReco.h.
Referenced by fit_vertex(), and set_mult_twobins().
unsigned int PHPatternReco::_nlayers private
number of detector layers
Definition at line 209 of file PHPatternReco.h.
Referenced by build_triplets_to_SimpleTrack3D(), initialize_geometry(), InitRun(), prune_xy(), prune_z(), and translate_input().
int PHPatternReco::_nlayers_all private
Definition at line 299 of file PHPatternReco.h.
Referenced by initialize_geometry().
TNtuple* PHPatternReco::_ntp_zvtx_by_event private
Definition at line 289 of file PHPatternReco.h.
Referenced by End(), fit_vertex(), and InitRun().
TNtuple* PHPatternReco::_ntp_zvtx_by_track private
Definition at line 290 of file PHPatternReco.h.
Referenced by End(), fit_vertex(), and InitRun().
TFile* PHPatternReco::_ofile private
Definition at line 295 of file PHPatternReco.h.
Referenced by End().
TFile* PHPatternReco::_ofile2 private
Definition at line 296 of file PHPatternReco.h.
Referenced by End(), and InitRun().
float PHPatternReco::_pt_rescale private
Definition at line 238 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), InitRun(), kappa_to_pt(), pt_to_kappa(), and setPtRescaleFactor().
std::vector<float> PHPatternReco::_radii private
radial distance of each layer (cm)
Definition at line 215 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), initialize_geometry(), and InitRun().
std::vector<float> PHPatternReco::_radii_all private
Definition at line 301 of file PHPatternReco.h.
Referenced by initialize_geometry().
bool PHPatternReco::_remove_hits private
Definition at line 222 of file PHPatternReco.h.
std::vector<int> PHPatternReco::_seeding_layer private
Definition at line 207 of file PHPatternReco.h.
Referenced by get_seeding_layer(), initialize_geometry(), and set_seeding_layer().
PHTimer* PHPatternReco::_t_output_io private
Definition at line 205 of file PHPatternReco.h.
Referenced by InitRun(), and ~PHPatternReco().
std::vector<SimpleTrack3D> PHPatternReco::_temp_tracks private
Definition at line 268 of file PHPatternReco.h.
Referenced by End(), and process_event().
std::vector<Eigen::Matrix<float, 5, 5> > PHPatternReco::_track_covars private
working array of track covariances
Definition at line 272 of file PHPatternReco.h.
Referenced by export_output(), fit_vertex(), and process_event().
std::vector<double> PHPatternReco::_track_errors private
working array of track chisq
Definition at line 271 of file PHPatternReco.h.
Referenced by export_output(), fit_vertex(), and process_event().
std::vector<HelixKalmanState> PHPatternReco::_track_states private
Definition at line 270 of file PHPatternReco.h.
Referenced by cellular_automaton_zvtx_init(), fit_vertex(), and process_event().
SvtxTrackMap* PHPatternReco::_trackmap private
Definition at line 279 of file PHPatternReco.h.
Referenced by create_nodes(), export_output(), get_nodes(), and turnoff_hits_used_in_triplets().
std::vector<SimpleTrack3D> PHPatternReco::_tracks private
working array of tracks
Definition at line 269 of file PHPatternReco.h.
Referenced by bins_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), export_output(), fit_vertex(), process_event(), and shift_coordinate_system().
bool PHPatternReco::_use_max_kappa private
Definition at line 223 of file PHPatternReco.h.
Referenced by Init(), and set_max_kappa().
std::map<int, float> PHPatternReco::_user_material private
material in user ladder indexes
Definition at line 217 of file PHPatternReco.h.
Referenced by initialize_geometry(), and set_material().
std::vector<float> PHPatternReco::_vertex private
working array for collision vertex
Definition at line 273 of file PHPatternReco.h.
Referenced by export_output(), fit_vertex(), process_event(), and shift_coordinate_system().
VertexFitter PHPatternReco::_vertex_finder private
Definition at line 281 of file PHPatternReco.h.
Referenced by fit_vertex().
std::vector<std::vector<float> > PHPatternReco::_vertex_list private
Definition at line 274 of file PHPatternReco.h.
Referenced by export_output(), fit_vertex(), and process_event().
SvtxVertexMap* PHPatternReco::_vertexmap private
Definition at line 280 of file PHPatternReco.h.
Referenced by create_nodes(), export_output(), and get_nodes().
TH2D* PHPatternReco::_z0_dzdl private
Definition at line 291 of file PHPatternReco.h.
Referenced by End(), find_track_candidates_z_init(), Init(), and vote_z().
float PHPatternReco::_z_cut private
Definition at line 241 of file PHPatternReco.h.
Referenced by build_triplets_to_SimpleTrack3D().
unsigned int PHPatternReco::bin private
Definition at line 248 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), find_track_candidates_z_init(), initialize_houghbin(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, HelixHoughBin* > PHPatternReco::bins_map private
Definition at line 306 of file PHPatternReco.h.
Referenced by find_track_candidates_z_init(), initialize_houghbin(), process_event(), and vote_z_init().
std::map<unsigned int, HelixHoughBin* > PHPatternReco::bins_map_cur private
Definition at line 308 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), process_event(), vote_xy(), and vote_z().
std::map<unsigned int, HelixHoughBin* > PHPatternReco::bins_map_prev private
Definition at line 307 of file PHPatternReco.h.
Referenced by bins_to_SimpleTrack3D(), find_track_candidates_xy(), process_event(), prune_xy(), and vote_z().
std::map<unsigned int, HelixHoughBin* > PHPatternReco::bins_map_sel private
Definition at line 309 of file PHPatternReco.h.
Referenced by bins_to_SimpleTrack3D(), find_track_candidates_z(), find_track_candidates_z_init(), process_event(), prune_z(), and vote_xy().
unsigned int PHPatternReco::cluster_id private
Definition at line 262 of file PHPatternReco.h.
Referenced by build_triplets_to_SimpleTrack3D(), turnoff_hits_used_in_triplets(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, unsigned int> PHPatternReco::d_phi_map private
Definition at line 312 of file PHPatternReco.h.
Referenced by vote_xy().
bool PHPatternReco::fill_multi_zvtx private
Definition at line 224 of file PHPatternReco.h.
Referenced by fit_vertex().
int PHPatternReco::helicity private
Definition at line 320 of file PHPatternReco.h.
Referenced by export_output(), process_event(), and vote_xy().
float PHPatternReco::hit[50][3] private
Definition at line 315 of file PHPatternReco.h.
Referenced by bins_to_SimpleTrack3D(), build_triplets_to_SimpleTrack3D(), shift_coordinate_system(), translate_input(), vote_xy(), vote_z(), and vote_z_init().
float PHPatternReco::hitpos3d[3] private
Definition at line 316 of file PHPatternReco.h.
Referenced by vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, SimpleHit3D> PHPatternReco::hits_map private
Definition at line 305 of file PHPatternReco.h.
Referenced by bins_to_SimpleTrack3D(), build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), export_output(), process_event(), shift_coordinate_system(), translate_input(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, bool> PHPatternReco::hits_used private
Definition at line 304 of file PHPatternReco.h.
Referenced by build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), process_event(), reset_hits_used(), translate_input(), turnoff_hits_used_in_triplets(), and vote_z_init().
unsigned int PHPatternReco::id private
Definition at line 252 of file PHPatternReco.h.
Referenced by initialize_houghbin(), and vote_xy().
unsigned int PHPatternReco::ik private
Definition at line 250 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), initialize_houghbin(), and vote_xy().
unsigned int PHPatternReco::il private
Definition at line 253 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), initialize_houghbin(), vote_xy(), vote_z(), and vote_z_init().
unsigned int PHPatternReco::ip private
Definition at line 251 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), initialize_houghbin(), and vote_xy().
unsigned int PHPatternReco::iz private
Definition at line 254 of file PHPatternReco.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), fit_vertex(), initialize_houghbin(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, unsigned int> PHPatternReco::kappa_d_phi_map private
Definition at line 313 of file PHPatternReco.h.
Referenced by vote_xy().
std::map<unsigned int, unsigned int> PHPatternReco::kappa_phi_map private
Definition at line 311 of file PHPatternReco.h.
Referenced by vote_xy().
int PHPatternReco::n_vtx_tracks private
Definition at line 321 of file PHPatternReco.h.
Referenced by fit_vertex().
unsigned int PHPatternReco::nd private
Definition at line 258 of file PHPatternReco.h.
Referenced by initialize_houghbin(), set_nbins(), and vote_xy().
unsigned int PHPatternReco::ndzdl private
Definition at line 259 of file PHPatternReco.h.
Referenced by initialize_houghbin(), and set_nbins().
unsigned int PHPatternReco::nkappa private
Definition at line 256 of file PHPatternReco.h.
Referenced by initialize_houghbin(), set_nbins(), and vote_xy().
unsigned int PHPatternReco::nphi private
Definition at line 257 of file PHPatternReco.h.
Referenced by initialize_houghbin(), and set_nbins().
unsigned int PHPatternReco::nz0 private
Definition at line 260 of file PHPatternReco.h.
Referenced by initialize_houghbin(), and set_nbins().
unsigned int PHPatternReco::nzooms private
Definition at line 317 of file PHPatternReco.h.
Referenced by Init(), and set_nzooms().
bool PHPatternReco::separate_helicity private
Definition at line 319 of file PHPatternReco.h.
Referenced by process_event(), and vote_xy().
std::vector<std::vector<unsigned int> > PHPatternReco::zooms_vec private
Definition at line 302 of file PHPatternReco.h.
Referenced by add_zoom(), Init(), PHPatternReco(), reset_zooms(), and set_nzooms().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHPatternReco.h
coresoftware/blob/master/offline/packages/trackreco/PHPatternReco.cc