Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetTickx (1)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetTicky (1)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 Draw ()
Draw_HFJetTruth_CrossSection2v2_EPR0 cd ()
Draw_HFJetTruth_CrossSection2v2_EPR0 Range (9.936709,-0.1810127, 41.58228, 0.3253165)
hframe__4 SetMinimum (-0.1)
hframe__4 SetMaximum (0.3)
hframe__4 SetDirectory (0)
hframe__4 SetStats (0)
hframe__4 SetLineWidth (2)
hframe__4 SetMarkerStyle (20)
hframe__4 SetMarkerSize (1.2)
hframe__4 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
hframe__4 GetYaxis () -> SetTitle("v_
hframe__4 GetZaxis () -> SetLabelFont(42)
hframe__4 Draw (" ")
gre SetName ("ge_h_b_copyv21025202362")
gre SetTitle ("Graph")
gre SetFillColor (1)
gre SetLineColor (ci)
gre SetLineWidth (3)
gre SetMarkerColor (ci)
gre SetMarkerSize (2)
gre SetPoint (0, 16.8, 0)
gre SetPointError (0, 0, 0.0093927)
gre SetPoint (1, 21.8, 0)
gre SetPointError (1, 0, 0.02258462)
gre SetPoint (2, 26.8, 0)
gre SetPointError (2, 0, 0.05160111)
gre SetPoint (3, 31.8, 0)
gre SetPointError (3, 0, 0.1135753)
gre SetHistogram (Graph_ge_h_b_copyv210252023625)
gre Draw ("pe")
gre SetName ("ge_h_b_copyv22044897763")
gre SetMarkerStyle (33)
gre SetPoint (0, 18.2, 0)
gre SetPoint (1, 23.2, 0)
gre SetPoint (2, 28.2, 0)
gre SetPoint (3, 33.2, 0)
gre SetHistogram (Graph_ge_h_b_copyv220448977636)
leg SetBorderSize (0)
leg SetLineColor (1)
leg SetLineStyle (1)
leg SetLineWidth (1)
leg SetFillStyle (0)
entry SetMarkerColor (1)
entry SetMarkerStyle (21)
entry SetMarkerSize (1)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2v2_EPR0 Modified ()
Draw_HFJetTruth_CrossSection2v2_EPR0 SetSelected (Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45)
Variables
TPad * Draw_HFJetTruth_CrossSection2v2_EPR0 = new TPad("Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45_1", "Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45_1",0.01,0.01,0.99,0.99)
TH1F * hframe__4 = new TH1F("hframe__4","",1000,15,40)
TGraphErrors * gre = new TGraphErrors(4)
Int_t ci = TColor::GetColor("#000066")
TColor * color
TH1F * Graph_ge_h_b_copyv210252023625 = new TH1F("Graph_ge_h_b_copyv210252023625","Graph",100,15.3,33.3)
TH1F * Graph_ge_h_b_copyv220448977636 = new TH1F("Graph_ge_h_b_copyv220448977636","Graph",100,16.7,34.7)
TLegend * leg = new TLegend(0,0.78,0.85,0.93,NULL,"brNDC")
TLegendEntry * entry =leg->AddEntry("NULL","#it{#bf{sPHENIX }} Simulation","")
Function Documentation
Draw_HFJetTruth_CrossSection2v2_EPR0 cd ()
Draw_HFJetTruth_CrossSection2v2_EPR0 Draw ()
hframe__4 Draw (" ")
gre Draw ("pe")
hframe__4 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
Definition at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
hframe__4 GetYaxis () -> SetTitle("v_
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
hframe__4 GetZaxis () -> SetLabelFont(42)
Draw_HFJetTruth_CrossSection2v2_EPR0 Modified ()
Draw_HFJetTruth_CrossSection2v2_EPR0 Range (0 , 0 , 1 , 1)
Draw_HFJetTruth_CrossSection2v2_EPR0 Range (9. 936709, -0. 1810127, 41. 58228, 0. 3253165)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetBorderSize (2)
leg SetBorderSize (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetBottomMargin (0. 16)
hframe__4 SetDirectory (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetFillColor (0)
gre SetFillColor (1)
leg SetFillStyle (0)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetFrameBorderMode (0)
gre SetHistogram (Graph_ge_h_b_copyv210252023625)
gre SetHistogram (Graph_ge_h_b_copyv220448977636)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetLeftMargin (0. 16)
gre SetLineColor (ci)
leg SetLineColor (1)
leg SetLineStyle (1)
hframe__4 SetLineWidth (2)
gre SetLineWidth (3)
leg SetLineWidth (1)
entry SetMarkerColor (ci)
entry SetMarkerColor (1)
hframe__4 SetMarkerSize (1. 2)
gre SetMarkerSize (2)
entry SetMarkerSize (1)
hframe__4 SetMarkerStyle (20)
entry SetMarkerStyle (33)
entry SetMarkerStyle (21)
Graph_ge_h_b_copyv216497604924 SetMaximum (0. 3)
Graph_ge_h_b_copyv216497604924 SetMinimum (-0. 1)
gre SetName ("ge_h_b_copyv21025202362")
Referenced by PgPostBankBackupStorage::format_name_title().
gre SetName ("ge_h_b_copyv22044897763")
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
gre SetPoint (0 , 16. 8, 0)
Referenced by hLabHelper::evDisplay(), and stack::getStackTime().
gre SetPoint (1 , 21. 8, 0)
gre SetPoint (2 , 26. 8, 0)
gre SetPoint (3 , 31. 8, 0)
gre SetPoint (0 , 18. 2, 0)
gre SetPoint (1 , 23. 2, 0)
gre SetPoint (2 , 28. 2, 0)
gre SetPoint (3 , 33. 2, 0)
gre SetPointError (0 , 0 , 0. 0093927)
gre SetPointError (1 , 0 , 0. 02258462)
gre SetPointError (2 , 0 , 0. 05160111)
gre SetPointError (3 , 0 , 0. 1135753)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetSelected (Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0. 45)
hframe__4 SetStats (0)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetTickx (1)
Draw_HFJetTruth_CrossSection2v2_EPR0 SetTicky (1)
gre SetTitle ("Graph")
Referenced by doSeries(), PgPostBankBackupStorage::format_name_title(), and stack::stack().
Draw_HFJetTruth_CrossSection2v2_EPR0 SetTopMargin (0. 05)
Variable Documentation
ci = TColor::GetColor("#000066")
Definition at line 68 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
TColor* color
Definition at line 69 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
TPad* Draw_HFJetTruth_CrossSection2v2_EPR0 = new TPad("Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45_1", "Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
entry =leg->AddEntry("NULL","#it{#bf{sPHENIX }} Simulation","")
Definition at line 168 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
TH1F* Graph_ge_h_b_copyv210252023625 = new TH1F("Graph_ge_h_b_copyv210252023625","Graph",100,15.3,33.3)
Definition at line 87 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
TH1F* Graph_ge_h_b_copyv220448977636 = new TH1F("Graph_ge_h_b_copyv220448977636","Graph",100,16.7,34.7)
Definition at line 135 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
gre = new TGraphErrors(4)
Definition at line 63 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
Referenced by BEmcRec::TwoGamma().
TH1F* hframe__4 = new TH1F("hframe__4","",1000,15,40)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.
leg = new TLegend(0,0.78,0.85,0.93,NULL,"brNDC")
Definition at line 161 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2v2_EPR0.4_deta0.45.C.