Analysis Software: TrackProjectionTools Class Reference
TrackProjectionTools Class Reference
#include <analysis/blob/master/EICAnalysis/TrackProjectionTools.h>
Public Member Functions
TrackProjectionTools (PHCompositeNode *)
virtual ~TrackProjectionTools ()
SvtxTrack * FindClosestTrack (RawCluster *, float &)
RawCluster * getCluster (SvtxTrack *, std::string)
float getE33Barrel (std::string, float, float)
float getE33Forward (std::string, float, float)
Protected Attributes
PHCompositeNode * _topNode
Detailed Description
Definition at line 23 of file TrackProjectionTools.h.
Constructor & Destructor Documentation
TrackProjectionTools::TrackProjectionTools (PHCompositeNode * topNode)
Definition at line 27 of file TrackProjectionTools.C.
virtual TrackProjectionTools::~TrackProjectionTools () inline virtual
Definition at line 29 of file TrackProjectionTools.h.
Member Function Documentation
SvtxTrack * TrackProjectionTools::FindClosestTrack (RawCluster * cluster, float & best_track_dr)
Find track with minimum delta R from given cluster
Definition at line 33 of file TrackProjectionTools.C.
References SvtxTrackMap::begin(), SvtxTrack::begin_states(), RawTowerDefs::convert_caloid_to_name(), RawTowerDefs::decode_caloid(), SvtxTrackMap::end(), SvtxTrack::end_states(), SvtxTrackState::get_eta(), SvtxTrackState::get_name(), SvtxTrackState::get_phi(), RawCluster::get_phi(), RawCluster::get_r(), RawCluster::get_towermap(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), RawCluster::get_z(), and PHWHERE.
RawCluster * TrackProjectionTools::getCluster (SvtxTrack * track, std::string detName)
Find closest cluster to track
Definition at line 182 of file TrackProjectionTools.C.
References RawCluster::get_phi(), RawCluster::get_r(), RawCluster::get_z(), RawClusterContainer::getCluster(), k, phi, PHWHERE, r, and RawClusterContainer::size().
float TrackProjectionTools::getE33Barrel (std::string detName, float phi, float eta)
get energy in 3x3 calorimeter towers around track projection to calorimeter surface. Copied from FastTrackingEval.C
Definition at line 251 of file TrackProjectionTools.C.
References RawTower::get_energy(), RawTowerGeomContainer::get_etabin(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_phibin(), RawTowerGeomContainer::get_phibins(), RawTowerContainer::getTower(), and PHWHERE.
float TrackProjectionTools::getE33Forward (std::string detName, float tkx, float tky)
get energy in 3x3 calorimeter towers around track projection to calorimeter surface. Copied from FastTrackingEval.C
Definition at line 307 of file TrackProjectionTools.C.
References RawTowerDefs::convert_name_to_caloid(), RawTowerDefs::decode_index1(), RawTowerDefs::decode_index2(), RawTowerDefs::encode_towerid(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTower::get_energy(), RawTowerGeom::get_size_x(), RawTowerGeom::get_size_y(), RawTowerGeomContainer::get_tower_geometry(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), PHWHERE, x, and y.
Referenced by DISKinematicsReco::InsertCandidateFromCluster().
Member Data Documentation
PHCompositeNode* TrackProjectionTools::_topNode protected
helper pointer to topNode
Definition at line 48 of file TrackProjectionTools.h.
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/TrackProjectionTools.h
analysis/blob/master/EICAnalysis/TrackProjectionTools.C