Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_Jets.C File Reference
G4_Jets.C File Reference
Functions
void Jet_Reco (int verbosity=0)
void Jet_Eval (std::string outfilename="g4jets_eval.root", int verbosity=0)
Function Documentation
void Jet_Eval (std::string outfilename = "g4jets_eval.root", int verbosity = 0)
Definition at line 75 of file G4_Jets.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void Jet_Reco (int verbosity = 0)
Definition at line 2 of file G4_Jets.C.
References JetReco::add_algo(), JetReco::add_input(), Jet::ANTIKT, Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, Fun4AllServer::instance(), Jet::PARTICLE, Fun4AllServer::registerSubsystem(), JetReco::set_algo_node(), JetReco::set_input_node(), Jet::TRACK, verbosity, and Fun4AllBase::Verbosity().