Analysis Software: VtxRegressor Class Reference
VtxRegressor Class Reference
#include <analysis/blob/master/PhotonConversion/truthconversion/VtxRegressor.h>
Public Member Functions
VtxRegressor (std::string, std::string)
~VtxRegressor ()
float regress (SvtxTrack *, SvtxTrack *, genfit::GFRaveVertex *)
Private Attributes
TMVA::Reader * reader =NULL
std::string _method
float pt1
float pt2
float phi
float dphi
float eta
float deta
float rin
Detailed Description
Definition at line 16 of file VtxRegressor.h.
Constructor & Destructor Documentation
VtxRegressor::VtxRegressor (std::string methodname, std::string pathname)
Definition at line 5 of file VtxRegressor.C.
References phi.
VtxRegressor::~VtxRegressor ()
Definition at line 18 of file VtxRegressor.C.
Member Function Documentation
float VtxRegressor::regress (SvtxTrack * reco1, SvtxTrack * reco2, genfit::GFRaveVertex * recoVertex)
Definition at line 22 of file VtxRegressor.C.
References SvtxTrack::get_eta(), SvtxTrack::get_phi(), SvtxTrack::get_pt(), and phi.
Referenced by RecoConversionEval::correctSecondaryVertex(), and Conversion::correctSecondaryVertex().
Member Data Documentation
std::string VtxRegressor::_method private
Definition at line 25 of file VtxRegressor.h.
float VtxRegressor::deta private
Definition at line 26 of file VtxRegressor.h.
float VtxRegressor::dphi private
Definition at line 26 of file VtxRegressor.h.
float VtxRegressor::eta private
Definition at line 26 of file VtxRegressor.h.
float VtxRegressor::phi private
Definition at line 26 of file VtxRegressor.h.
float VtxRegressor::pt1 private
Definition at line 26 of file VtxRegressor.h.
float VtxRegressor::pt2 private
Definition at line 26 of file VtxRegressor.h.
TMVA::Reader* VtxRegressor::reader =NULL private
Definition at line 24 of file VtxRegressor.h.
float VtxRegressor::rin private
Definition at line 26 of file VtxRegressor.h.
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/truthconversion/VtxRegressor.h
analysis/blob/master/PhotonConversion/truthconversion/VtxRegressor.C