Analysis Software: PgPostBankBackupStorage::BankHeader Class Reference
PgPostBankBackupStorage::BankHeader Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupStorage.h>
Public Types
enum { INVALID_BANKID = -999999 }
Public Member Functions
BankHeader ()
~BankHeader ()
virtual void Print (Option_t *option="") const
int getBankID () const
PHTimeStamp getInsertTime () const
PHTimeStamp getStartValTime () const
PHTimeStamp getEndValTime () const
std::string getDescription () const
std::string getUserName () const
std::string getTableName () const
int getRId () const
void setBankID (const int val)
void setInsertTime (const PHTimeStamp &val)
void setStartValTime (const PHTimeStamp &val)
void setEndValTime (const PHTimeStamp &val)
void setDescription (const std::string &val)
void setUserName (const std::string &val)
void setTableName (const std::string &val)
void setRId (int r)
std::string get_id_string () const
Private Attributes
int bankID
PHTimeStamp insertTime
PHTimeStamp startValTime
PHTimeStamp endValTime
std::string description
std::string userName
std::string tableName
int rid
Detailed Description
Definition at line 55 of file PgPostBankBackupStorage.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
INVALID_BANKID
Definition at line 58 of file PgPostBankBackupStorage.h.
Constructor & Destructor Documentation
PgPostBankBackupStorage::BankHeader::BankHeader () inline
Definition at line 63 of file PgPostBankBackupStorage.h.
PgPostBankBackupStorage::BankHeader::~BankHeader () inline
Definition at line 74 of file PgPostBankBackupStorage.h.
Member Function Documentation
string PgPostBankBackupStorage::BankHeader::get_id_string () const
Definition at line 135 of file PgPostBankBackupStorage.cc.
References bankID, endValTime, PHTimeStamp::getTics(), insertTime, rid, startValTime, and tableName.
Referenced by PgPostBankBackupStorage::format_name_title().
int PgPostBankBackupStorage::BankHeader::getBankID () const inline
Definition at line 82 of file PgPostBankBackupStorage.h.
References bankID.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupStorage::createBank(), and PgPostBankBackupStorage::isValid().
std::string PgPostBankBackupStorage::BankHeader::getDescription () const inline
Definition at line 106 of file PgPostBankBackupStorage.h.
References description.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupStorage::createBank(), and PgPostBankBackupStorage::format_name_title().
PHTimeStamp PgPostBankBackupStorage::BankHeader::getEndValTime () const inline
Definition at line 100 of file PgPostBankBackupStorage.h.
References endValTime.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), and PgPostBankBackupStorage::createBank().
PHTimeStamp PgPostBankBackupStorage::BankHeader::getInsertTime () const inline
Definition at line 88 of file PgPostBankBackupStorage.h.
References insertTime.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), and PgPostBankBackupStorage::createBank().
int PgPostBankBackupStorage::BankHeader::getRId () const inline
Definition at line 124 of file PgPostBankBackupStorage.h.
References rid.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupStorage::createBank(), and PgPostBankBackupStorage::isValid().
PHTimeStamp PgPostBankBackupStorage::BankHeader::getStartValTime () const inline
Definition at line 94 of file PgPostBankBackupStorage.h.
References startValTime.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), and PgPostBankBackupStorage::createBank().
std::string PgPostBankBackupStorage::BankHeader::getTableName () const inline
Definition at line 118 of file PgPostBankBackupStorage.h.
References tableName.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupStorage::createBank(), and PgPostBankBackupStorage::isValid().
std::string PgPostBankBackupStorage::BankHeader::getUserName () const inline
Definition at line 112 of file PgPostBankBackupStorage.h.
References userName.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), and PgPostBankBackupStorage::createBank().
void PgPostBankBackupStorage::BankHeader::Print (Option_t * option = "") const virtual
Definition at line 152 of file PgPostBankBackupStorage.cc.
References description.
Referenced by PgPostBankBackupStorage::Print(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setBankID (const int val) inline
Definition at line 130 of file PgPostBankBackupStorage.h.
References bankID.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setDescription (const std::string & val) inline
Definition at line 154 of file PgPostBankBackupStorage.h.
References description.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setEndValTime (const PHTimeStamp & val) inline
Definition at line 148 of file PgPostBankBackupStorage.h.
References endValTime.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setInsertTime (const PHTimeStamp & val) inline
Definition at line 136 of file PgPostBankBackupStorage.h.
References insertTime.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setRId (int r) inline
Definition at line 172 of file PgPostBankBackupStorage.h.
References r, and rid.
Referenced by PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setStartValTime (const PHTimeStamp & val) inline
Definition at line 142 of file PgPostBankBackupStorage.h.
References startValTime.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setTableName (const std::string & val) inline
Definition at line 166 of file PgPostBankBackupStorage.h.
References tableName.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
void PgPostBankBackupStorage::BankHeader::setUserName (const std::string & val) inline
Definition at line 160 of file PgPostBankBackupStorage.h.
References userName.
Referenced by PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
Member Data Documentation
int PgPostBankBackupStorage::BankHeader::bankID private
Definition at line 181 of file PgPostBankBackupStorage.h.
Referenced by get_id_string(), getBankID(), and setBankID().
std::string PgPostBankBackupStorage::BankHeader::description private
Definition at line 185 of file PgPostBankBackupStorage.h.
Referenced by getDescription(), and setDescription().
PHTimeStamp PgPostBankBackupStorage::BankHeader::endValTime private
Definition at line 184 of file PgPostBankBackupStorage.h.
Referenced by get_id_string(), getEndValTime(), and setEndValTime().
PHTimeStamp PgPostBankBackupStorage::BankHeader::insertTime private
Definition at line 182 of file PgPostBankBackupStorage.h.
Referenced by get_id_string(), getInsertTime(), and setInsertTime().
int PgPostBankBackupStorage::BankHeader::rid private
Definition at line 188 of file PgPostBankBackupStorage.h.
Referenced by get_id_string(), getRId(), and setRId().
PHTimeStamp PgPostBankBackupStorage::BankHeader::startValTime private
Definition at line 183 of file PgPostBankBackupStorage.h.
Referenced by get_id_string(), getStartValTime(), and setStartValTime().
std::string PgPostBankBackupStorage::BankHeader::tableName private
Definition at line 187 of file PgPostBankBackupStorage.h.
Referenced by get_id_string(), getTableName(), and setTableName().
std::string PgPostBankBackupStorage::BankHeader::userName private
Definition at line 186 of file PgPostBankBackupStorage.h.
Referenced by getUserName(), and setUserName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupStorage.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupStorage.cc