Analysis Software: PHG4BlockSteppingAction Class Reference
PHG4BlockSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.h>
Public Member Functions
PHG4BlockSteppingAction (PHG4BlockDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4BlockSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4BlockDetector * m_Detector
pointer to the detector
const PHParameters * m_Params
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4Hit * m_Hit
PHG4Shower * m_SaveShower
G4VPhysicalVolume * m_SaveVolPre
G4VPhysicalVolume * m_SaveVolPost
int m_SaveTrackId
int m_SavePreStepStatus
int m_SavePostStepStatus
int m_ActiveFlag
int m_BlackHoleFlag
int m_UseG4StepsFlag
Detailed Description
Definition at line 17 of file PHG4BlockSteppingAction.h.
Constructor & Destructor Documentation
PHG4BlockSteppingAction::PHG4BlockSteppingAction (PHG4BlockDetector * detector, const PHParameters * parameters)
constructor
Definition at line 42 of file PHG4BlockSteppingAction.cc.
PHG4BlockSteppingAction::~PHG4BlockSteppingAction () virtual
destructor
Definition at line 60 of file PHG4BlockSteppingAction.cc.
References m_Hit.
Member Function Documentation
void PHG4BlockSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 272 of file PHG4BlockSteppingAction.cc.
References PHG4Detector::GetName(), m_Detector, m_HitContainer, and PHG4BlockDetector::SuperDetector().
bool PHG4BlockSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 70 of file PHG4BlockSteppingAction.cc.
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4BlockDetector::get_Layer(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), PHG4StepStatusDecode::GetStepStatus(), PHG4BlockDetector::IsInBlock(), m_ActiveFlag, m_BlackHoleFlag, m_Detector, m_Hit, m_HitContainer, m_SavePostStepStatus, m_SavePreStepStatus, m_SaveShower, m_SaveTrackId, m_SaveVolPost, m_SaveVolPre, m_UseG4StepsFlag, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
int PHG4BlockSteppingAction::m_ActiveFlag private
Definition at line 45 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4BlockSteppingAction::m_BlackHoleFlag private
Definition at line 46 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
PHG4BlockDetector* PHG4BlockSteppingAction::m_Detector private
pointer to the detector
Definition at line 34 of file PHG4BlockSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4BlockSteppingAction::m_Hit private
Definition at line 38 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4BlockSteppingAction().
PHG4HitContainer* PHG4BlockSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 37 of file PHG4BlockSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
const PHParameters* PHG4BlockSteppingAction::m_Params private
Definition at line 35 of file PHG4BlockSteppingAction.h.
int PHG4BlockSteppingAction::m_SavePostStepStatus private
Definition at line 44 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4BlockSteppingAction::m_SavePreStepStatus private
Definition at line 43 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4BlockSteppingAction::m_SaveShower private
Definition at line 39 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4BlockSteppingAction::m_SaveTrackId private
Definition at line 42 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4BlockSteppingAction::m_SaveVolPost private
Definition at line 41 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
G4VPhysicalVolume* PHG4BlockSteppingAction::m_SaveVolPre private
Definition at line 40 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4BlockSteppingAction::m_UseG4StepsFlag private
Definition at line 48 of file PHG4BlockSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc