Analysis Software: PHRawDataNode Class Reference
PHRawDataNode Class Reference
#include <coresoftware/blob/master/offline/framework/phoolraw/PHRawDataNode.h>
Public Member Functions
PHRawDataNode (PHDWORD *, const std::string &, const int, const int, const int, const int)
virtual ~PHRawDataNode ()
virtual bool write (PHIOManager *, const std::string &="")
int getLength () const
int getID () const
int getWordLength () const
int getHitFormat () const
void setLength (const int val)
void setID (const int val)
void setWordLength (const int val)
void setHitFormat (const int val)
Public Member Functions inherited from PHDataNode< PHDWORD >
PHDataNode (PHDWORD *, const std::string &)
PHDataNode (PHDWORD *, const std::string &, const std::string &)
virtual ~PHDataNode ()
PHDWORD * getData ()
void setData (PHDWORD *d)
virtual void prune ()
virtual void forgetMe (PHNode *)
virtual void print (const std::string &)
Public Member Functions inherited from PHNode
PHNode (const std::string &)
PHNode (const std::string &, const std::string &)
virtual ~PHNode ()
PHNode * getParent () const
bool isPersistent () const
void makePersistent ()
const std::string getObjectType () const
const std::string getType () const
const std::string getName () const
const std::string getClass () const
void setParent (PHNode *p)
void setName (const std::string &n)
void setObjectType (const std::string &type)
virtual void setResetFlag (const bool b)
virtual bool getResetFlag () const
void makeTransient ()
Private Member Functions
PHRawDataNode ()=delete
Private Attributes
int length
int ID
int wordLength
int hitFormat
Additional Inherited Members
Protected Member Functions inherited from PHDataNode< PHDWORD >
PHDataNode ()=delete
Protected Attributes inherited from PHDataNode< PHDWORD >
tobjcast data
Detailed Description
Definition at line 18 of file PHRawDataNode.h.
Constructor & Destructor Documentation
PHRawDataNode::PHRawDataNode (PHDWORD * d, const std::string & n, const int l, const int i, const int w, const int h)
Definition at line 15 of file PHRawDataNode.cc.
PHRawDataNode::~PHRawDataNode () virtual
Definition at line 25 of file PHRawDataNode.cc.
References PHDataNode< PHDWORD >::setData().
PHRawDataNode::PHRawDataNode () private delete
Member Function Documentation
int PHRawDataNode::getHitFormat () const inline
Definition at line 30 of file PHRawDataNode.h.
References hitFormat.
Referenced by PHRawOManager::write().
int PHRawDataNode::getID () const inline
Definition at line 28 of file PHRawDataNode.h.
References ID.
Referenced by PHRawOManager::write().
int PHRawDataNode::getLength () const inline
Definition at line 27 of file PHRawDataNode.h.
References length.
Referenced by PHRawOManager::write().
int PHRawDataNode::getWordLength () const inline
Definition at line 29 of file PHRawDataNode.h.
References wordLength.
Referenced by PHRawOManager::write().
void PHRawDataNode::setHitFormat (const int val) inline
Definition at line 34 of file PHRawDataNode.h.
References hitFormat.
void PHRawDataNode::setID (const int val) inline
Definition at line 32 of file PHRawDataNode.h.
References ID.
void PHRawDataNode::setLength (const int val) inline
Definition at line 31 of file PHRawDataNode.h.
References length.
void PHRawDataNode::setWordLength (const int val) inline
Definition at line 33 of file PHRawDataNode.h.
References wordLength.
bool PHRawDataNode::write (PHIOManager * IOManager, const std::string & = "") virtual
Reimplemented from PHDataNode< PHDWORD >.
Definition at line 33 of file PHRawDataNode.cc.
References PHRawOManager::write().
Member Data Documentation
int PHRawDataNode::hitFormat private
Definition at line 41 of file PHRawDataNode.h.
Referenced by getHitFormat(), and setHitFormat().
int PHRawDataNode::ID private
Definition at line 39 of file PHRawDataNode.h.
Referenced by getID(), and setID().
int PHRawDataNode::length private
Definition at line 38 of file PHRawDataNode.h.
Referenced by getLength(), and setLength().
int PHRawDataNode::wordLength private
Definition at line 40 of file PHRawDataNode.h.
Referenced by getWordLength(), and setWordLength().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phoolraw/PHRawDataNode.h
coresoftware/blob/master/offline/framework/phoolraw/PHRawDataNode.cc