Analysis Software: macros/blob/master/macros/g4simulations/G4_Tracking.C File Reference
G4_Tracking.C File Reference
#include "GlobalVariables.C"
#include <fun4all/Fun4AllServer.h>
#include <g4eval/TrkrEvaluator.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4intt/PHG4InttDefs.h>
#include <g4intt/PHG4InttDigitizer.h>
#include <g4intt/PHG4InttSubsystem.h>
#include <g4intt/PHG4InttHitReco.h>
#include <g4main/PHG4Reco.h>
#include <g4mvtx/PHG4MvtxDefs.h>
#include <g4mvtx/PHG4MvtxDigitizer.h>
#include <g4mvtx/PHG4MvtxSubsystem.h>
#include <g4mvtx/PHG4MvtxHitReco.h>
#include <g4tpc/PHG4TpcDigitizer.h>
#include <g4tpc/PHG4TpcElectronDrift.h>
#include <g4tpc/PHG4TpcPadPlane.h>
#include <g4tpc/PHG4TpcPadPlaneReadout.h>
#include <g4tpc/PHG4TpcSubsystem.h>
#include <intt/InttClusterizer.h>
#include <mvtx/MvtxClusterizer.h>
#include <tpc/TpcClusterizer.h>
#include <trackreco/PHGenFitTrkFitter.h>
#include <trackreco/PHGenFitTrkProp.h>
#include <trackreco/PHHoughSeeding.h>
#include <trackreco/PHInitZVertexing.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHGenFitTrackProjection.h>
#include <trackbase/TrkrHitTruthAssoc.h>
#include <vector>
Enumerations
enum enu_InttDeadMapType { kInttNoDeadMap = 0, kIntt4PercentDeadMap = 4, kIntt8PercentDeadMap = 8 }
Functions
std::string vmethod ("avf-smoothing:1")
void TrackingInit (int verbosity=0)
double Tracking (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Tracking_Cells (int verbosity=0)
void Tracking_Clus (int verbosity=0)
void Tracking_Reco (int verbosity=0)
void Tracking_Eval (std::string outputfile, int verbosity=0)
Variables
const int n_maps_layer = 3
int n_intt_layer = 4
int laddertype [4]
int nladder [4] = {15, 15, 18, 18}
double sensor_radius [4] = { 8.987, 9.545, 10.835, 11.361}
double offsetphi [4] = {0.0, 0.5 * 360.0 / nladder[1] , 0.0, 0.5 * 360.0 / nladder[3]}
enu_InttDeadMapType InttDeadMapOption = kInttNoDeadMap
int n_tpc_layer_inner = 16
int tpc_layer_rphi_count_inner = 1152
int n_tpc_layer_mid = 16
int n_tpc_layer_outer = 16
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
const int init_vertexing_min_zvtx_tracks = 2
const bool use_track_prop = true
const bool g4eval_use_initial_vertex = false
const bool use_primary_vertex = false
const bool use_truth_vertex = true
Enumeration Type Documentation
enum enu_InttDeadMapType
Enumerator:
kInttNoDeadMap
kIntt4PercentDeadMap
kIntt8PercentDeadMap
Definition at line 71 of file G4_Tracking.C.
Function Documentation
double Tracking (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 106 of file G4_Tracking.C.
References PHG4MvtxDefs::ALPIDE_SEGMENTATION, PHG4MvtxDefs::GLOBAL, i, n_intt_layer, n_maps_layer, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4DetectorGroupSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorGroupSubsystem::set_double_param(), PHG4DetectorGroupSubsystem::set_int_param(), PHG4DetectorGroupSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorGroupSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), verbosity, and Fun4AllBase::Verbosity().
Referenced by G4Setup().
void Tracking_Cells (int verbosity = 0)
Definition at line 232 of file G4_Tracking.C.
References PHG4TpcElectronDrift::Detector(), Fun4AllServer::instance(), n_maps_layer, PHG4TpcElectronDrift::registerPadPlane(), Fun4AllServer::registerSubsystem(), PHParameterInterface::set_double_param(), PHParameterInterface::set_int_param(), PHG4MvtxHitReco::set_timing_window(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void Tracking_Clus (int verbosity = 0)
Definition at line 313 of file G4_Tracking.C.
References i, Fun4AllServer::instance(), kIntt4PercentDeadMap, kIntt8PercentDeadMap, kInttNoDeadMap, n_intt_layer, Fun4AllServer::registerSubsystem(), PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, PHG4InttDigitizer::set_adc_scale(), InttClusterizer::set_z_clustering(), PHG4TpcDigitizer::SetADCThreshold(), PHG4TpcDigitizer::SetENC(), PHG4TpcDigitizer::SetTpcMinLayer(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void Tracking_Eval (std::string outputfile, int verbosity = 0)
Definition at line 579 of file G4_Tracking.C.
References SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_eval_light(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), Fun4AllServer::instance(), n_gas_layer, n_intt_layer, n_maps_layer, Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), SvtxEvaluator::set_use_initial_vertex(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), and Fun4All_G4_sPHENIX().
void Tracking_Reco (int verbosity = 0)
Definition at line 470 of file G4_Tracking.C.
References i, Fun4AllServer::instance(), n_intt_layer, Fun4AllServer::registerSubsystem(), PHGenFitTrkFitter::set_fit_primary_tracks(), PHGenFitTrkProp::set_max_search_win_phi_intt(), PHGenFitTrkProp::set_max_search_win_theta_intt(), PHGenFitTrkProp::set_min_search_win_phi_intt(), PHGenFitTrkProp::set_min_search_win_theta_intt(), PHInitZVertexing::set_min_zvtx_tracks(), PHInitZVertexing::set_seeding_layer(), PHGenFitTrkFitter::set_use_truth_vertex(), PHGenFitTrkFitter::set_vertexing_method(), verbosity, Fun4AllBase::Verbosity(), and vmethod().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_fsPHENIX(), Fun4All_G4_sPHENIX(), and ReadClustersRunTracking().
void TrackingInit (int verbosity = 0)
Definition at line 102 of file G4_Tracking.C.
Referenced by G4Init().
std::string vmethod ("avf-smoothing:1")
Referenced by Tracking_Reco().
Variable Documentation
const bool g4eval_use_initial_vertex = false
Definition at line 90 of file G4_Tracking.C.
const int init_vertexing_min_zvtx_tracks = 2
Definition at line 88 of file G4_Tracking.C.
enu_InttDeadMapType InttDeadMapOption = kInttNoDeadMap
Definition at line 77 of file G4_Tracking.C.
int laddertype[4]
Initial value:
= {PHG4InttDefs::SEGMENTATION_PHI,
                       PHG4InttDefs::SEGMENTATION_PHI,
                       PHG4InttDefs::SEGMENTATION_PHI,
                       PHG4InttDefs::SEGMENTATION_PHI}
Definition at line 64 of file G4_Tracking.C.
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
Definition at line 84 of file G4_Tracking.C.
int n_intt_layer = 4
Definition at line 63 of file G4_Tracking.C.
const int n_maps_layer = 3
Definition at line 60 of file G4_Tracking.C.
int n_tpc_layer_inner = 16
Definition at line 80 of file G4_Tracking.C.
int n_tpc_layer_mid = 16
Definition at line 82 of file G4_Tracking.C.
int n_tpc_layer_outer = 16
Definition at line 83 of file G4_Tracking.C.
int nladder[4] = {15, 15, 18, 18}
Definition at line 68 of file G4_Tracking.C.
double offsetphi[4] = {0.0, 0.5 * 360.0 / nladder[1] , 0.0, 0.5 * 360.0 / nladder[3]}
Definition at line 70 of file G4_Tracking.C.
Referenced by PHG4InttDetector::ConstructIntt().
double sensor_radius[4] = { 8.987, 9.545, 10.835, 11.361}
Definition at line 69 of file G4_Tracking.C.
Referenced by PHG4InttSubsystem::SetDefaultParameters().
int tpc_layer_rphi_count_inner = 1152
Definition at line 81 of file G4_Tracking.C.
const bool use_primary_vertex = false
Definition at line 91 of file G4_Tracking.C.
const bool use_track_prop = true
Definition at line 89 of file G4_Tracking.C.
Referenced by Fun4All_G4_TPC().
const bool use_truth_vertex = true
Definition at line 95 of file G4_Tracking.C.