Analysis Software: PgPostBankBackupStorage Class Reference
PgPostBankBackupStorage Class Reference
PgPostBankBackupStorage.
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupStorage.h>
Classes
class BankHeader
Public Member Functions
PgPostBankBackupStorage (PdbCalBank *b)
PgPostBankBackupStorage ()
virtual ~PgPostBankBackupStorage ()
virtual void Print (Option_t *option="") const
bool isValid () const
void format_name_title ()
PgPostCalBank * createBank ()
use this storage object to recover the PdbCalBankWrapper
void printEntry (size_t s)
size_t getLength () const
PdbCalChan & getEntry (size_t pos)
const PdbCalBank * get_bank () const
PdbCalBank * get_bank ()
const BankHeader & get_database_header () const
BankHeader & get_database_header ()
void set_database_header (const BankHeader &databaseHeader)
const std::string & get_obj_classname () const
std::string & get_obj_classname ()
void set_obj_classname (const std::string &name)
const BankHeader & get_obj_header () const
BankHeader & get_obj_header ()
void set_obj_header (const BankHeader &objHeader)
void set_obj_info (const PgPostCalBank *bankwapper)
record bankwapper to obj_header and obj_classname
Private Attributes
BankHeader database_header
header as written in database table
BankHeader obj_header
header as written in the bank wrapper object
std::string obj_classname
class name of the PgPostCalBank object as in the database
PdbCalBank * bank
storage of the original calibration bank (vector of PdbCalChan)
Detailed Description
PgPostBankBackupStorage.
Definition at line 30 of file PgPostBankBackupStorage.h.
Constructor & Destructor Documentation
PgPostBankBackupStorage::PgPostBankBackupStorage (PdbCalBank * b)
constructor
Parameters
[in] b pointer to a bank (not wrappers!). PgPostBankBackupStorage will own this pointer
Definition at line 33 of file PgPostBankBackupStorage.cc.
References bank.
PgPostBankBackupStorage::PgPostBankBackupStorage ()
Definition at line 57 of file PgPostBankBackupStorage.cc.
PgPostBankBackupStorage::~PgPostBankBackupStorage () virtual
Definition at line 64 of file PgPostBankBackupStorage.cc.
References bank.
Member Function Documentation
PgPostCalBank * PgPostBankBackupStorage::createBank ()
use this storage object to recover the PdbCalBankWrapper
use this storage object to recover the PdbCalBankWrapper/PdbCalBankWrapper2 user code are responsible to delete the returned PdbCalBank
Definition at line 72 of file PgPostBankBackupStorage.cc.
References assert, bank, PHObject::Clone(), database_header, PdbClassMap< T >::end(), PdbClassMap< T >::find(), get_obj_classname(), PgPostBankBackupStorage::BankHeader::getBankID(), PgPostBankBackupStorage::BankHeader::getDescription(), PgPostBankBackupStorage::BankHeader::getEndValTime(), PgPostBankBackupStorage::BankHeader::getInsertTime(), PgPostBankBackupStorage::BankHeader::getRId(), PgPostBankBackupStorage::BankHeader::getStartValTime(), PgPostBankBackupStorage::BankHeader::getTableName(), PgPostBankBackupStorage::BankHeader::getUserName(), PdbClassMap< T >::instance(), isValid(), obj_classname, obj_header, PgPostCalBank::setBankID(), PgPostCalBank::setDescription(), PgPostCalBank::setEndValTime(), PgPostCalBank::setInsertTime(), PgPostCalBank::setStartValTime(), PgPostCalBank::setTableName(), and PgPostCalBank::setUserName().
Referenced by PgPostBankBackupManager::commit(), and PgPostBankBackupManager::commitAllBankfromTFile().
void PgPostBankBackupStorage::format_name_title ()
Definition at line 213 of file PgPostBankBackupStorage.cc.
References database_header, PgPostBankBackupStorage::BankHeader::get_id_string(), PgPostBankBackupStorage::BankHeader::getDescription(), SetName(), and SetTitle().
Referenced by PgPostBankBackupManager::SQLResultSet2BackupStorage().
const PdbCalBank* PgPostBankBackupStorage::get_bank () const inline
Definition at line 206 of file PgPostBankBackupStorage.h.
References bank.
PdbCalBank* PgPostBankBackupStorage::get_bank () inline
Definition at line 212 of file PgPostBankBackupStorage.h.
References bank.
const BankHeader& PgPostBankBackupStorage::get_database_header () const inline
Definition at line 218 of file PgPostBankBackupStorage.h.
References database_header.
Referenced by PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
BankHeader& PgPostBankBackupStorage::get_database_header () inline
Definition at line 224 of file PgPostBankBackupStorage.h.
References database_header.
const std::string& PgPostBankBackupStorage::get_obj_classname () const inline
Definition at line 236 of file PgPostBankBackupStorage.h.
References obj_classname.
Referenced by createBank().
std::string& PgPostBankBackupStorage::get_obj_classname () inline
Definition at line 242 of file PgPostBankBackupStorage.h.
References obj_classname.
const BankHeader& PgPostBankBackupStorage::get_obj_header () const inline
Definition at line 254 of file PgPostBankBackupStorage.h.
References obj_header.
Referenced by PgPostBankBackupManager::SQLResultSet2BackupStorage().
BankHeader& PgPostBankBackupStorage::get_obj_header () inline
Definition at line 260 of file PgPostBankBackupStorage.h.
References obj_header.
PdbCalChan & PgPostBankBackupStorage::getEntry (size_t pos)
Definition at line 226 of file PgPostBankBackupStorage.cc.
References bank, and PdbCalBank::getEntry().
Referenced by printEntry().
size_t PgPostBankBackupStorage::getLength () const
Definition at line 220 of file PgPostBankBackupStorage.cc.
References bank, and PdbCalBank::getLength().
bool PgPostBankBackupStorage::isValid () const
Definition at line 231 of file PgPostBankBackupStorage.cc.
References bank, database_header, PgPostBankBackupStorage::BankHeader::getBankID(), PgPostBankBackupStorage::BankHeader::getRId(), PgPostBankBackupStorage::BankHeader::getTableName(), PgPostBankBackupStorage::BankHeader::INVALID_BANKID, and obj_classname.
Referenced by PgPostBankBackupManager::commit(), createBank(), and PgPostBankBackupManager::fetchBank2TFile().
void PgPostBankBackupStorage::Print (Option_t * option = "") const virtual
Definition at line 200 of file PgPostBankBackupStorage.cc.
References assert, bank, database_header, obj_header, Print(), PdbCalBank::print(), and PgPostBankBackupStorage::BankHeader::Print().
Referenced by PgPostBankBackupManager::fetchBank2TFile().
void PgPostBankBackupStorage::printEntry (size_t s) inline
Definition at line 194 of file PgPostBankBackupStorage.h.
References getEntry(), and PdbCalChan::print().
void PgPostBankBackupStorage::set_database_header (const BankHeader & databaseHeader) inline
Definition at line 230 of file PgPostBankBackupStorage.h.
References database_header.
void PgPostBankBackupStorage::set_obj_classname (const std::string & name) inline
Definition at line 248 of file PgPostBankBackupStorage.h.
References name, and obj_classname.
void PgPostBankBackupStorage::set_obj_header (const BankHeader & objHeader) inline
Definition at line 266 of file PgPostBankBackupStorage.h.
References obj_header.
void PgPostBankBackupStorage::set_obj_info (const PgPostCalBank * bankwapper)
record bankwapper to obj_header and obj_classname
Definition at line 159 of file PgPostBankBackupStorage.cc.
References assert, PdbClassMap< T >::end(), PdbClassMap< T >::find(), PgPostCalBank::getBankID(), PgPostCalBank::getDescription(), PgPostCalBank::getEndValTime(), PgPostCalBank::getInsertTime(), PdbBankID::getInternalValue(), PgPostCalBank::getStartValTime(), PgPostCalBank::getTableName(), PgPostCalBank::getUserName(), PdbClassMap< T >::instance(), obj_classname, obj_header, PgPostBankBackupStorage::BankHeader::setBankID(), PgPostBankBackupStorage::BankHeader::setDescription(), PgPostBankBackupStorage::BankHeader::setEndValTime(), PgPostBankBackupStorage::BankHeader::setInsertTime(), PgPostBankBackupStorage::BankHeader::setStartValTime(), PgPostBankBackupStorage::BankHeader::setTableName(), and PgPostBankBackupStorage::BankHeader::setUserName().
Referenced by PgPostBankBackupManager::SQLResultSet2BackupStorage().
Member Data Documentation
PdbCalBank* PgPostBankBackupStorage::bank private
storage of the original calibration bank (vector of PdbCalChan)
Definition at line 283 of file PgPostBankBackupStorage.h.
Referenced by createBank(), get_bank(), getEntry(), getLength(), isValid(), PgPostBankBackupStorage(), Print(), and ~PgPostBankBackupStorage().
BankHeader PgPostBankBackupStorage::database_header private
header as written in database table
Definition at line 277 of file PgPostBankBackupStorage.h.
Referenced by createBank(), format_name_title(), get_database_header(), isValid(), Print(), and set_database_header().
std::string PgPostBankBackupStorage::obj_classname private
class name of the PgPostCalBank object as in the database
Definition at line 281 of file PgPostBankBackupStorage.h.
Referenced by createBank(), get_obj_classname(), isValid(), set_obj_classname(), and set_obj_info().
BankHeader PgPostBankBackupStorage::obj_header private
header as written in the bank wrapper object
Definition at line 279 of file PgPostBankBackupStorage.h.
Referenced by createBank(), get_obj_header(), Print(), set_obj_header(), and set_obj_info().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupStorage.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupStorage.cc