Analysis Software: DumpTrkrClusterContainer Class Reference
DumpTrkrClusterContainer Class Reference
#include <coresoftware/blob/master/offline/packages/NodeDump/DumpTrkrClusterContainer.h>
Public Member Functions
DumpTrkrClusterContainer (const std::string &NodeName)
virtual ~DumpTrkrClusterContainer ()
Public Member Functions inherited from DumpObject
DumpObject (const std::string &NodeName="DUMMY")
virtual ~DumpObject ()
virtual int Init ()
virtual int process_event (PHNode *mynode)
virtual int CloseOutputFile ()
virtual const char * Name () const
virtual void Print (const char *what) const
virtual void SetOutDir (const std::string &outdir)
virtual void SetPrecision (const int digits)
void SetParentNodeDump (PHNodeDump *nd)
void NoOutput (const int i=1)
void WriteRunEvent (int i)
Protected Member Functions
int process_Node (PHNode *mynode)
Protected Member Functions inherited from DumpObject
virtual int OpenOutFile ()
Additional Inherited Members
Protected Attributes inherited from DumpObject
std::ostream * fout
Detailed Description
Definition at line 10 of file DumpTrkrClusterContainer.h.
Constructor & Destructor Documentation
DumpTrkrClusterContainer::DumpTrkrClusterContainer (const std::string & NodeName)
Definition at line 17 of file DumpTrkrClusterContainer.cc.
virtual DumpTrkrClusterContainer::~DumpTrkrClusterContainer () inline virtual
Definition at line 14 of file DumpTrkrClusterContainer.h.
Member Function Documentation
int DumpTrkrClusterContainer::process_Node (PHNode * mynode) protected virtual
Reimplemented from DumpObject.
Definition at line 23 of file DumpTrkrClusterContainer.cc.
References DumpObject::fout, TrkrCluster::getAdc(), TrkrClusterContainer::getClusters(), PHDataNode< T >::getData(), TrkrCluster::getPhiError(), TrkrCluster::getPhiSize(), TrkrCluster::getRPhiError(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), TrkrCluster::getZError(), and TrkrClusterContainer::size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/NodeDump/DumpTrkrClusterContainer.h
coresoftware/blob/master/offline/packages/NodeDump/DumpTrkrClusterContainer.cc