Analysis Software: TpcClusterizer Class Reference
TpcClusterizer Class Reference
#include <coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.h>
Public Member Functions
TpcClusterizer (const std::string &name="TpcClusterizer")
virtual ~TpcClusterizer ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool is_local_maximum (int phi, int z, std::vector< std::vector< double >> &adcval)
void get_cluster (int phibin, int zbin, int &phiup, int &phidown, int &zup, int &zdown, std::vector< std::vector< double >> &adcval)
Private Attributes
TrkrHitSetContainer * m_hits
TrkrClusterContainer * m_clusterlist
TrkrClusterHitAssoc * m_clusterhitassoc
double zz_shaping_correction
double pedestal
int NPhiBinsMax
int NPhiBinsMin
int NZBinsMax
int NZBinsMin
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file TpcClusterizer.h.
Constructor & Destructor Documentation
TpcClusterizer::TpcClusterizer (const std::string & name = "TpcClusterizer")
Definition at line 40 of file TpcClusterizer.cc.
virtual TpcClusterizer::~TpcClusterizer () inline virtual
Definition at line 18 of file TpcClusterizer.h.
Member Function Documentation
void TpcClusterizer::get_cluster (int phibin, int zbin, int & phiup, int & phidown, int & zup, int & zdown, std::vector< std::vector< double >> & adcval) private
Definition at line 83 of file TpcClusterizer.cc.
References NPhiBinsMax, NPhiBinsMin, NZBinsMax, and NZBinsMin.
Referenced by process_event().
int TpcClusterizer::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 142 of file TpcClusterizer.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
bool TpcClusterizer::is_local_maximum (int phi, int z, std::vector< std::vector< double >> & adcval) private
Definition at line 55 of file TpcClusterizer.cc.
References NPhiBinsMax, NPhiBinsMin, NZBinsMax, and NZBinsMin.
Referenced by process_event().
int TpcClusterizer::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 193 of file TpcClusterizer.cc.
References Fun4AllReturnCodes::ABORTRUN, TrkrClusterHitAssoc::addAssoc(), double(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), TrkrClusterContainer::findOrAddCluster(), TpcDefs::genClusKey(), TpcDefs::genHitKey(), get_cluster(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeom::get_zstep(), TrkrHitSet::getHits(), TrkrHitSet::getHitSetKey(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), TpcDefs::getPad(), TpcDefs::getSectorId(), TpcDefs::getSide(), TpcDefs::getTBin(), i, TrkrClusterHitAssoc::identify(), TrkrClusterContainer::identify(), TrkrHitSet::identify(), is_local_maximum(), m_clusterhitassoc, m_clusterlist, m_hits, NPhiBinsMax, NPhiBinsMin, NZBinsMax, NZBinsMin, pedestal, PHWHERE, TrkrDefs::tpcId, Fun4AllBase::Verbosity(), z, and zz_shaping_correction.
Member Data Documentation
TrkrClusterHitAssoc* TpcClusterizer::m_clusterhitassoc private
Definition at line 29 of file TpcClusterizer.h.
Referenced by process_event().
TrkrClusterContainer* TpcClusterizer::m_clusterlist private
Definition at line 28 of file TpcClusterizer.h.
Referenced by process_event().
TrkrHitSetContainer* TpcClusterizer::m_hits private
Definition at line 27 of file TpcClusterizer.h.
Referenced by process_event().
int TpcClusterizer::NPhiBinsMax private
Definition at line 34 of file TpcClusterizer.h.
Referenced by get_cluster(), is_local_maximum(), and process_event().
int TpcClusterizer::NPhiBinsMin private
Definition at line 35 of file TpcClusterizer.h.
Referenced by get_cluster(), is_local_maximum(), and process_event().
int TpcClusterizer::NZBinsMax private
Definition at line 36 of file TpcClusterizer.h.
Referenced by get_cluster(), is_local_maximum(), and process_event().
int TpcClusterizer::NZBinsMin private
Definition at line 37 of file TpcClusterizer.h.
Referenced by get_cluster(), is_local_maximum(), and process_event().
double TpcClusterizer::pedestal private
Definition at line 32 of file TpcClusterizer.h.
Referenced by process_event().
double TpcClusterizer::zz_shaping_correction private
Definition at line 31 of file TpcClusterizer.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.h
coresoftware/blob/master/offline/packages/tpc/TpcClusterizer.cc