Analysis Software: BbcVertex Class Reference
BbcVertex Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertex.h>
Public Member Functions
virtual ~BbcVertex ()
virtual void identify (std::ostream &os=std::cout) const
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual float get_t () const
virtual void set_t (float t)
virtual float get_t_err () const
virtual void set_t_err (float t_err)
virtual float get_z () const
virtual void set_z (float z)
virtual float get_z_err () const
virtual void set_z_err (float z_err)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
BbcVertex ()
Private Member Functions
ClassDef (BbcVertex, 1)
Detailed Description
Definition at line 9 of file BbcVertex.h.
Constructor & Destructor Documentation
virtual BbcVertex::~BbcVertex () inline virtual
Definition at line 12 of file BbcVertex.h.
BbcVertex::BbcVertex () inline protected
Definition at line 39 of file BbcVertex.h.
Member Function Documentation
BbcVertex::ClassDef (BbcVertex , 1) private
virtual PHObject* BbcVertex::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in BbcVertexv1.
Definition at line 17 of file BbcVertex.h.
virtual unsigned int BbcVertex::get_id () const inline virtual
Reimplemented in BbcVertexv1.
Definition at line 23 of file BbcVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual float BbcVertex::get_t () const inline virtual
Reimplemented in BbcVertexv1.
Definition at line 26 of file BbcVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual float BbcVertex::get_t_err () const inline virtual
Reimplemented in BbcVertexv1.
Definition at line 29 of file BbcVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual float BbcVertex::get_z () const inline virtual
Reimplemented in BbcVertexv1.
Definition at line 32 of file BbcVertex.h.
Referenced by PHHoughSeeding::fast_vertex_from_bbc(), and GlobalVertexReco::process_event().
virtual float BbcVertex::get_z_err () const inline virtual
Reimplemented in BbcVertexv1.
Definition at line 35 of file BbcVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual void BbcVertex::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in BbcVertexv1.
Definition at line 16 of file BbcVertex.h.
References os.
virtual int BbcVertex::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in BbcVertexv1.
Definition at line 19 of file BbcVertex.h.
virtual void BbcVertex::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in BbcVertexv1.
Definition at line 18 of file BbcVertex.h.
virtual void BbcVertex::set_id (unsigned int id) inline virtual
Reimplemented in BbcVertexv1.
Definition at line 24 of file BbcVertex.h.
virtual void BbcVertex::set_t (float t) inline virtual
Reimplemented in BbcVertexv1.
Definition at line 27 of file BbcVertex.h.
Referenced by BbcVertexFastSimReco::process_event().
virtual void BbcVertex::set_t_err (float t_err) inline virtual
Reimplemented in BbcVertexv1.
Definition at line 30 of file BbcVertex.h.
Referenced by BbcVertexFastSimReco::process_event().
virtual void BbcVertex::set_z (float z) inline virtual
Reimplemented in BbcVertexv1.
Definition at line 33 of file BbcVertex.h.
Referenced by BbcVertexFastSimReco::process_event().
virtual void BbcVertex::set_z_err (float z_err) inline virtual
Reimplemented in BbcVertexv1.
Definition at line 36 of file BbcVertex.h.
Referenced by BbcVertexFastSimReco::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertex.h