Analysis Software: analysis/blob/master/Fluence/DrawFluence.C File Reference
DrawFluence.C File Reference
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TH1.h>
#include <TH2.h>
#include <TH3.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
void DrawFluence (const TString infile="/phenix/u/jinhuang/links/sPHENIX_work/Fluence/AuAu200_25k_Iter4_FTFP/AuAu200_25k_Iter4_FTFP_SUM.xml_g4score.root", const TString config="FTFP_BERT_HP", const TString disc="Au+Au #sqrt{s_{NN}}=200 GeV, sHIJING 0-20fm", const double nTarget=1.5e12, const TString projection_desc="5-year run plan (1.5 Trillion Collisions)")
void VertexCyl (const double normalization, const TString projection_desc)
void FullCyl (const double normalization, const TString projection_desc)
void FullCylEIC (const double normalization, const TString projection_desc)
void FullCylRProj (const double normalization, const TString projection_desc, const double z_range=100)
void FullCylRProjPHENIXComparison (const double normalization, const TString projection_desc)
TGraph * GetPHENIXDose ()
TGraph * GetPHENIXNeutron ()
void FullCylZProj (const double normalization, const TString projection_desc, const int r_bin=2)
void dNchdEta ()
double Check ()
TH1 * GetZProjection (const TH3 *h3, const double z_range_min, const double z_range_max, const double normalization)
TH1 * GetRProjection (const TH3 *h3, const int r_bin, const double normalization)
Variables
TFile * _file0 = NULL
TString description
TString configuration
Function Documentation
double Check ()
Definition at line 830 of file DrawFluence.C.
References _file0, assert, hNormalization, and SaveCanvas().
Referenced by DrawFluence(), DrawTPCIntegratedCharge(), and OccupancySim().
void dNchdEta ()
Definition at line 804 of file DrawFluence.C.
References _file0, assert, hNormalization, and SaveCanvas().
Referenced by DrawFluence().
void DrawFluence (const TString infile = "/phenix/u/jinhuang/links/sPHENIX_work/Fluence/AuAu200_25k_Iter4_FTFP/AuAu200_25k_Iter4_FTFP_SUM.xml_g4score.root", const TString config = "FTFP_BERT_HP", const TString disc = "Au+Au #sqrt{s_{NN}}=200 GeV, sHIJING 0-20fm", const double nTarget = 1.5e12, const TString projection_desc = "5-year run plan (1.5 Trillion Collisions)")
Definition at line 21 of file DrawFluence.C.
References _file0, assert, Check(), configuration, description, dNchdEta(), FullCyl(), FullCylRProj(), FullCylZProj(), hNormalization, and SetsPhenixStyle().
void FullCyl (const double normalization, const TString projection_desc)
Definition at line 238 of file DrawFluence.C.
References _file0, assert, configuration, description, leg, and SaveCanvas().
Referenced by DrawFluence().
void FullCylEIC (const double normalization, const TString projection_desc)
Definition at line 333 of file DrawFluence.C.
References _file0, assert, description, leg, and SaveCanvas().
void FullCylRProj (const double normalization, const TString projection_desc, const double z_range = 100)
Definition at line 428 of file DrawFluence.C.
References _file0, assert, configuration, description, GetZProjection(), leg, and SaveCanvas().
Referenced by DrawFluence().
void FullCylRProjPHENIXComparison (const double normalization, const TString projection_desc)
Definition at line 517 of file DrawFluence.C.
References _file0, assert, configuration, description, GetPHENIXDose(), GetPHENIXNeutron(), GetZProjection(), leg, and SaveCanvas().
void FullCylZProj (const double normalization, const TString projection_desc, const int r_bin = 2)
Definition at line 712 of file DrawFluence.C.
References _file0, assert, configuration, description, GetRProjection(), leg, and SaveCanvas().
Referenced by DrawFluence().
TGraph* GetPHENIXDose ()
Definition at line 620 of file DrawFluence.C.
References g.
Referenced by FullCylRProjPHENIXComparison().
TGraph* GetPHENIXNeutron ()
Definition at line 673 of file DrawFluence.C.
References g.
Referenced by FullCylRProjPHENIXComparison().
TH1* GetRProjection (const TH3 * h3, const int r_bin, const double normalization)
Definition at line 908 of file DrawFluence.C.
References assert.
Referenced by FullCylZProj().
TH1* GetZProjection (const TH3 * h3, const double z_range_min, const double z_range_max, const double normalization)
Definition at line 882 of file DrawFluence.C.
References assert, and nbins.
Referenced by FullCylRProj(), and FullCylRProjPHENIXComparison().
void VertexCyl (const double normalization, const TString projection_desc)
Definition at line 82 of file DrawFluence.C.
References _file0, assert, configuration, description, leg, and SaveCanvas().
Variable Documentation
TFile* _file0 = NULL
Definition at line 17 of file DrawFluence.C.
TString configuration
Definition at line 19 of file DrawFluence.C.
Referenced by DrawFluence(), FullCyl(), FullCylRProj(), FullCylRProjPHENIXComparison(), FullCylZProj(), and VertexCyl().
TString description
Definition at line 18 of file DrawFluence.C.
Referenced by ChargePerLayer(), Check(), ClusterQA(), Clusters3D(), DataRate(), dNdeta(), DrawFluence(), DrawTPCDataStreamEmulator(), DrawTPCIntegratedCharge(), DrawTpcPrototypeGenFitTrkFitter(), DrawTpcPrototypeUnpacker(), FEEDataSize(), FullCyl(), FullCylEIC(), FullCylRProj(), FullCylRProjPHENIXComparison(), FullCylZProj(), MakeChipMultiplicitySet(), OccupancySim(), PgPostBankBackupStorage::BankHeader::Print(), Resolution(), SectorDataSize(), PHGenIntegralv1::set_Description(), Track3D(), TrackClusterEnergy(), TriggerMultiplicity(), VertexCyl(), and WaveletCheck().