Analysis Software: FlagSavev1 Class Reference
FlagSavev1 Class Reference
#include <coresoftware/blob/master/offline/framework/ffaobjects/FlagSavev1.h>
Public Member Functions
FlagSavev1 ()
ctor
virtual ~FlagSavev1 ()
dtor
PHObject * CloneMe () const
Virtual copy constructor.
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains valid data
void identify (std::ostream &os=std::cout) const
int FillFromPHFlag (const PHFlag *flags)
int PutFlagsBack (PHFlag *flags)
Public Member Functions inherited from FlagSave
virtual ~FlagSave ()
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
int FillIntFromPHFlag (const PHFlag *flags)
int FillDoubleFromPHFlag (const PHFlag *flags)
int FillFloatFromPHFlag (const PHFlag *flags)
int FillCharFromPHFlag (const PHFlag *flags)
int PutIntToPHFlag (PHFlag *flags)
int PutDoubleToPHFlag (PHFlag *flags)
int PutFloatToPHFlag (PHFlag *flags)
int PutCharToPHFlag (PHFlag *flags)
void PrintIntFlag (std::ostream &os) const
void PrintDoubleFlag (std::ostream &os) const
void PrintFloatFlag (std::ostream &os) const
void PrintStringFlag (std::ostream &os) const
Protected Attributes
std::map< std::string, int > intflag
std::map< std::string, double > doubleflag
std::map< std::string, float > floatflag
std::map< std::string,
std::string > stringflag
Detailed Description
Definition at line 16 of file FlagSavev1.h.
Constructor & Destructor Documentation
FlagSavev1::FlagSavev1 () inline
ctor
Definition at line 21 of file FlagSavev1.h.
virtual FlagSavev1::~FlagSavev1 () inline virtual
dtor
Definition at line 23 of file FlagSavev1.h.
Member Function Documentation
PHObject * FlagSavev1::CloneMe () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 12 of file FlagSavev1.cc.
References doubleflag, floatflag, intflag, and stringflag.
int FlagSavev1::FillCharFromPHFlag (const PHFlag * flags) protected
Definition at line 106 of file FlagSavev1.cc.
References PHFlag::CharMap().
int FlagSavev1::FillDoubleFromPHFlag (const PHFlag * flags) protected
Definition at line 82 of file FlagSavev1.cc.
References PHFlag::DoubleMap().
int FlagSavev1::FillFloatFromPHFlag (const PHFlag * flags) protected
Definition at line 94 of file FlagSavev1.cc.
References PHFlag::FloatMap().
int FlagSavev1::FillFromPHFlag (const PHFlag * flags) virtual
Reimplemented from FlagSave.
Definition at line 49 of file FlagSavev1.cc.
int FlagSavev1::FillIntFromPHFlag (const PHFlag * flags) protected
Definition at line 70 of file FlagSavev1.cc.
References PHFlag::IntMap().
void FlagSavev1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from FlagSave.
Definition at line 38 of file FlagSavev1.cc.
References return().
int FlagSavev1::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from FlagSave.
Definition at line 25 of file FlagSavev1.cc.
void FlagSavev1::PrintDoubleFlag (std::ostream & os) const protected
Definition at line 179 of file FlagSavev1.cc.
References return().
void FlagSavev1::PrintFloatFlag (std::ostream & os) const protected
Definition at line 195 of file FlagSavev1.cc.
References return().
void FlagSavev1::PrintIntFlag (std::ostream & os) const protected
Definition at line 163 of file FlagSavev1.cc.
References return().
void FlagSavev1::PrintStringFlag (std::ostream & os) const protected
Definition at line 211 of file FlagSavev1.cc.
References return().
int FlagSavev1::PutCharToPHFlag (PHFlag * flags) protected
Definition at line 152 of file FlagSavev1.cc.
References PHFlag::set_CharFlag().
int FlagSavev1::PutDoubleToPHFlag (PHFlag * flags) protected
Definition at line 130 of file FlagSavev1.cc.
References PHFlag::set_DoubleFlag().
int FlagSavev1::PutFlagsBack (PHFlag * flags) virtual
Reimplemented from FlagSave.
Definition at line 59 of file FlagSavev1.cc.
int FlagSavev1::PutFloatToPHFlag (PHFlag * flags) protected
Definition at line 141 of file FlagSavev1.cc.
References PHFlag::set_FloatFlag().
int FlagSavev1::PutIntToPHFlag (PHFlag * flags) protected
Definition at line 119 of file FlagSavev1.cc.
References PHFlag::set_IntFlag().
void FlagSavev1::Reset () inline virtual
Clear Event.
Reimplemented from FlagSave.
Definition at line 28 of file FlagSavev1.h.
Member Data Documentation
std::map<std::string, double> FlagSavev1::doubleflag protected
Definition at line 56 of file FlagSavev1.h.
Referenced by CloneMe().
std::map<std::string, float> FlagSavev1::floatflag protected
Definition at line 57 of file FlagSavev1.h.
Referenced by CloneMe().
std::map<std::string, int> FlagSavev1::intflag protected
Definition at line 55 of file FlagSavev1.h.
Referenced by CloneMe().
std::map<std::string, std::string> FlagSavev1::stringflag protected
Definition at line 58 of file FlagSavev1.h.
Referenced by CloneMe().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/FlagSavev1.h
coresoftware/blob/master/offline/framework/ffaobjects/FlagSavev1.cc