Analysis Software: PHHoughSeeding Class Reference
PHHoughSeeding Class Reference
A fun4all implementation of Alan's Hough Transform.
#include <coresoftware/blob/master/offline/packages/trackreco/PHHoughSeeding.h>
Public Member Functions
PHHoughSeeding (const std::string &name="PHHoughSeeding", unsigned int nlayers_maps=3, unsigned int nlayers_intt=8, unsigned int nlayers_tpc=60, unsigned int seeding_nlayer=12, unsigned int min_seeding_nlayer=4)
virtual ~PHHoughSeeding ()
void set_mag_field (float magField)
float get_mag_field () const
void set_chi2_cut_fast (double cut_par0, double cut_par1=0.0, double cut_max=FLT_MAX)
set the tracking pt-dependent chi2 cut for fast fit, cut = min(par0 + par1 / pt, max)
void set_chi2_cut_full (double chi2_cut)
set the tracking chi2 cut for full fit
double get_chi2_cut_full () const
get the tracking chi2 cut for full fit
void set_ca_chi2_cut (double chi2_cut)
set early combination-land chi2 cut(?)
double get_ca_chi2_cut () const
get early combination-land chi2 cut(?)
void set_cos_angle_cut (double cos_angle_cut)
set early curvature cut between hits, lower values are more open
double get_cos_angle_cut () const
get early curvature cut between hits, lower values are more open
void set_min_pT (float pt)
void set_z0_range (float min_z0, float max_z0)
set the z0 search window
void set_r_max (float max_r)
set the r search window
void set_material (int layer, float value)
radiation length per layer, sequential layer indexes required here
void setRejectGhosts (bool rg)
set internal ghost rejection
void setRemoveHits (bool rh)
set for internal hit rejection
void setBinScale (float scale)
adjusts the rate of zooming
void setZBinScale (float scale)
adjusts the rate of zooming
void setCutOnDCA (bool cod)
turn on DCA limitation
void setDCACut (float dcut)
sets an upper limit on X-Y DCA
void setDCAZCut (float dzcut)
sets an upper limit on Z DCA
void setPtRescaleFactor (float pt_rescale)
void setVoteErrorScale (unsigned int layer, float scale)
adjust the relative voting error scale w.r.t. the cluster size
void setFitErrorScale (unsigned int layer, float scale)
adjust the relative fit error scale w.r.t. the cluster size
void set_use_vertex (bool b)
set option to produce initial vertex for further tracking
void setInitialResMultiplier (int beta)
void setFullResMultiplier (int lambda)
void set_min_pT_init (float PT)
set the minimum pT to try to find during initial vertex finding tracking
void setMaxClusterError (float max_cluster_error)
limit the maximum error reported by cluster (in number of cell units)
void setUseCellSize (bool use_cell_size)
use the cell size as cluster size instead of value stored on cluster
void set_chi2_cut_init (double chi2_cut)
set the tracking chi2 for initial vertex finding
const std::vector< int > & get_seeding_layer () const
void set_seeding_layer (const int *seedingLayer, const int n)
void set_analyzing_mode (bool analyzingMode)
float get_max_merging_deta () const
void set_max_merging_deta (float maxMergingDeta)
float get_max_merging_dphi () const
void set_max_merging_dphi (float maxMergingDphi)
float get_max_merging_dr () const
void set_max_merging_dr (float maxMergingDr)
float get_max_merging_dz () const
void set_max_merging_dz (float maxMergingDz)
unsigned int get_min_nlayers_seeding () const
void set_min_nlayers_seeding (unsigned int minNlayersSeeding)
Public Member Functions inherited from PHTrackSeeding
PHTrackSeeding (const std::string &name="PHTrackSeeding")
virtual ~PHTrackSeeding ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode)
int Process (PHCompositeNode *topNode)
int End ()
Called in SubsysReco::End.
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
int InitializeGeometry (PHCompositeNode *topNode)
create new node output pointers
int InitializePHGenFit (PHCompositeNode *topNode)
track propagation
int setup_seed_tracker_objects ()
code to setup seed tracking objects
int setup_initial_tracker_object ()
code to setup initial vertexing tracker
int setup_tracker_object ()
code to setup full tracking object
int translate_input ()
fetch node pointers
int fast_composite_seed ()
code to combine seed tracking vertex with BBCZ if available
int fast_vertex_from_bbc ()
code to seed vertex from bbc
int vertexing ()
code to seed vertex from initial tracking using a broad search window
int full_track_seeding (int ivert)
code to perform the final tracking and vertexing
int export_output ()
code to translate back to the SVTX universe
int CleanupSeedsByHitPattern ()
int CleanupTracksByHitPattern ()
int CleanupSeeds ()
void print_timers ()
float kappaToPt (float kappa)
convert from inverse curvature to momentum
float ptToKappa (float pt)
convert from momentum to inverse curvature
void convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const &input, Eigen::Matrix< float, 6, 6 > &output)
convert the covariance from HelixHough coords to x,y,z,px,py,pz
void shift_coordinate_system (double dx, double dy, double dz, int ivertex)
translate the clusters, tracks, and vertex from one origin to another
Private Attributes
int _event
PHTimer * _t_seeding
PHTimer * _t_seed_init1
PHTimer * _t_seed_init2
PHTimer * _t_seed_init3
PHTimer * _t_seeds_cleanup
PHTimer * _t_translate_to_PHGenFitTrack
PHTimer * _t_translate1
PHTimer * _t_translate2
PHTimer * _t_translate3
PHTimer * _t_kalman_pat_rec
PHTimer * _t_search_clusters
PHTimer * _t_search_clusters_encoding
PHTimer * _t_search_clusters_map_iter
PHTimer * _t_track_propagation
PHTimer * _t_full_fitting
PHTimer * _t_output_io
std::vector< int > _seeding_layer
unsigned int _nlayers_seeding
number of detector layers
unsigned int _min_nlayers_seeding
minimum number of layers to make a track
std::vector< float > _radii
radial distance of each layer (cm)
std::vector< float > _material
material at each layer in rad. lengths
std::map< int, float > _user_material
material in user ladder indexes
float _magField
in Tesla
bool _reject_ghosts
bool _remove_hits
float _min_pt
float _min_z0
float _max_z0
float _max_r
bool _cut_on_dca
float _dcaxy_cut
float _dcaz_cut
double _chi2_cut_fast_par0
fit quality chisq/dof for fast fit track fitting
double _chi2_cut_fast_par1
fit quality chisq/dof for fast fit track fitting
double _chi2_cut_fast_max
fit quality chisq/dof for fast fit track fitting
double _chi2_cut_full
fit quality chisq/dof for kalman track fitting
double _ca_chi2_cut
initial combination cut?
double _cos_angle_cut
curvature restriction on cluster combos
float _bin_scale
float _z_bin_scale
unsigned int _min_combo_hits
minimum hits to enter combination gun
unsigned int _max_combo_hits
maximum hits to enter combination gun
float _pt_rescale
std::vector< float > _fit_error_scale
std::vector< float > _vote_error_scale
std::map< int, unsigned int > _layer_ilayer_map
recorded layer indexes to internal sequential indexes
std::vector< SimpleHit3D > _clusters
working array of clusters
std::vector< SimpleTrack3D > _tracks
working array of tracks
std::vector< double > _track_errors
working array of track chisq
std::vector< Eigen::Matrix
< float, 5, 5 > > _track_covars
working array of track covariances
std::vector< SimpleTrack3D > _all_tracks
working array of tracks
std::vector< double > _all_track_errors
working array of track chisq
std::vector< Eigen::Matrix
< float, 5, 5 > > _all_track_covars
working array of track covariances
std::vector< std::vector< float > > _vertex
working array for collision vertex list
std::vector< std::vector< float > > _vertex_error
sqrt(cov)
std::vector< int > _vertex_tracks
sPHENIXSeedFinder * _tracker
tracks in this vertex
sPHENIXSeedFinder * _tracker_vertex
finds a subset of tracks for initial vertex-finding
sPHENIXSeedFinder * _tracker_etap_seed
finds a subset of tracks for the vertex guess
sPHENIXSeedFinder * _tracker_etam_seed
finds a subset of tracks for the vertex guess
VertexFinder _vertexFinder
vertex finding object
BbcVertexMap * _bbc_vertexes
int * _hit_used_map
int _hit_used_map_size
PHG4CylinderGeomContainer * _geom_container_intt
PHG4CylinderGeomContainer * _geom_container_maps
bool _analyzing_mode
TFile * _analyzing_file
TNtuple * _analyzing_ntuple
float _max_merging_dphi
Cleanup Seeds.
float _max_merging_deta
float _max_merging_dr
float _max_merging_dz
unsigned int _max_share_hits
if two seeds have common hits more than this number, merge them
double _cut_min_pT
unsigned int _nlayers_maps
unsigned int _nlayers_intt
unsigned int _nlayers_tpc
int _nlayers_all
std::map< int, unsigned int > _layer_ilayer_map_all
std::vector< float > _radii_all
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHTrackSeeding
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
Detailed Description
A fun4all implementation of Alan's Hough Transform.
This module run Alan's Hough Transform and quick vertex finding on the SvxClusterList of the event. It will produce both SvxTrack and SvxSegments for the time being.
Definition at line 46 of file PHHoughSeeding.h.
Constructor & Destructor Documentation
PHHoughSeeding::PHHoughSeeding (const std::string & name = "PHHoughSeeding", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 8, unsigned int nlayers_tpc = 60, unsigned int seeding_nlayer = 12, unsigned int min_seeding_nlayer = 4)
Definition at line 83 of file PHHoughSeeding.cc.
References _analyzing_file, _analyzing_mode, _analyzing_ntuple, _event, _nlayers_all, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _user_material, _vertex_error, i, and set_seeding_layer().
virtual PHHoughSeeding::~PHHoughSeeding () inline virtual
Definition at line 58 of file PHHoughSeeding.h.
Member Function Documentation
int PHHoughSeeding::CleanupSeeds () private
find tracks winthin neighbor bins
Add hits from other related tracks
hits from itrack already registered
Definition at line 2259 of file PHHoughSeeding.cc.
References _event, _max_merging_deta, _max_merging_dphi, _max_merging_dr, _max_merging_dz, _max_share_hits, _tracks, SimpleTrack3D::d, SimpleTrack3D::dzdl, Fun4AllReturnCodes::EVENT_OK, SimpleHit3D::get_id(), SimpleTrack3D::hits, it, SimpleTrack3D::phi, printf(), SimpleHit3D::set_id(), and SimpleTrack3D::z0.
Referenced by full_track_seeding().
int PHHoughSeeding::CleanupSeedsByHitPattern () private
Definition at line 1880 of file PHHoughSeeding.cc.
References _event, _tracks, Fun4AllReturnCodes::EVENT_OK, SimpleHit3D::get_id(), SimpleTrack3D::hits, it, SimpleHit3D::set_id(), and Fun4AllBase::Verbosity().
int PHHoughSeeding::CleanupTracksByHitPattern () private
Definition at line 2071 of file PHHoughSeeding.cc.
References _event, _track_covars, _track_errors, _tracker, _tracks, C, Fun4AllReturnCodes::EVENT_OK, SimpleHit3D::get_id(), HelixHough::getKalmanStates(), SimpleTrack3D::hits, it, SimpleHit3D::set_id(), and Fun4AllBase::Verbosity().
void PHHoughSeeding::convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const & input, Eigen::Matrix< float, 6, 6 > & output) private
convert the covariance from HelixHough coords to x,y,z,px,py,pz
Definition at line 1809 of file PHHoughSeeding.cc.
References d, and dzdl.
Referenced by export_output().
int PHHoughSeeding::End () protected virtual
Called in SubsysReco::End.
Implements PHTrackSeeding.
Definition at line 471 of file PHHoughSeeding.cc.
References _analyzing_file, _analyzing_mode, _analyzing_ntuple, _t_full_fitting, _t_kalman_pat_rec, _t_output_io, _t_search_clusters, _t_seeding, _t_seeds_cleanup, _t_track_propagation, _t_translate1, _t_translate2, _t_translate3, _t_translate_to_PHGenFitTrack, _tracker, _tracker_etam_seed, _tracker_etap_seed, _tracker_vertex, Fun4AllReturnCodes::EVENT_OK, and LogDebug.
int PHHoughSeeding::export_output () private
code to translate back to the SVTX universe
Definition at line 1583 of file PHHoughSeeding.cc.
References _all_track_covars, _all_track_errors, _all_tracks, PHTrackSeeding::_assoc_container, PHTrackSeeding::_cluster_map, _clusters, _magField, _track_covars, _track_errors, PHTrackSeeding::_track_map, _tracks, _vertex, PHTrackSeeding::_vertex_map, SvtxVertexMap::clear(), col, convertHelixCovarianceToEuclideanCovariance(), d, dzdl, Fun4AllReturnCodes::EVENT_OK, TrkrClusterContainer::findCluster(), SvtxTrackMap::get(), SvtxTrack_v1::get_id(), SvtxTrack_v1::get_px(), SvtxTrack_v1::get_py(), SvtxTrack_v1::get_pz(), SvtxTrack_v1::get_quality(), SvtxVertex_v1::get_x(), SvtxVertex_v1::get_y(), SvtxVertex_v1::get_z(), i, SvtxTrackMap::identify(), SvtxVertex::identify(), TrkrCluster::identify(), SvtxTrack::identify(), SvtxTrackMap::insert(), SvtxVertexMap::insert_clone(), SvtxTrack_v1::insert_cluster_key(), SvtxVertex_v1::insert_track(), kappaToPt(), M_PI, phi, PHWHERE, SvtxTrack_v1::set_charge(), SvtxVertex_v1::set_chisq(), SvtxTrack_v1::set_chisq(), SvtxTrack_v1::set_dca2d(), SvtxTrack_v1::set_dca2d_error(), SvtxVertex_v1::set_error(), SvtxTrack_v1::set_error(), SvtxTrack_v1::set_id(), SvtxTrack_v1::set_ndf(), SvtxVertex_v1::set_ndof(), SvtxVertex_v1::set_position(), SvtxTrack_v1::set_px(), SvtxTrack_v1::set_py(), SvtxTrack_v1::set_pz(), SvtxVertex_v1::set_t0(), SvtxTrack_v1::set_vertex_id(), SvtxTrack_v1::set_x(), SvtxTrack_v1::set_y(), SvtxTrack_v1::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrackMap::size(), TrkrClusterContainer::size(), SvtxTrack_v1::size_cluster_keys(), and Fun4AllBase::Verbosity().
Referenced by Process().
int PHHoughSeeding::fast_composite_seed () private
code to combine seed tracking vertex with BBCZ if available
int PHHoughSeeding::fast_vertex_from_bbc () private
code to seed vertex from bbc
Definition at line 1189 of file PHHoughSeeding.cc.
References _bbc_vertexes, _vertex, BbcVertexMap::begin(), Fun4AllReturnCodes::EVENT_OK, BbcVertex::get_z(), and Fun4AllBase::Verbosity().
int PHHoughSeeding::full_track_seeding (int ivert) private
code to perform the final tracking and vertexing
Definition at line 1434 of file PHHoughSeeding.cc.
References _clusters, _event, _max_combo_hits, _min_combo_hits, _min_nlayers_seeding, _t_seeds_cleanup, _track_covars, _track_errors, _tracker, _tracks, _vertex, _vertexFinder, C, CleanupSeeds(), sPHENIXSeedFinder::clear(), Fun4AllReturnCodes::EVENT_OK, sPHENIXSeedFinder::finalize(), HelixHough::findHelices(), VertexFinder::findVertex(), HelixHough::getKalmanStates(), PHTimer::restart(), shift_coordinate_system(), PHTimer::stop(), and Fun4AllBase::Verbosity().
Referenced by Process().
double PHHoughSeeding::get_ca_chi2_cut () const inline
get early combination-land chi2 cut(?)
Definition at line 109 of file PHHoughSeeding.h.
References _ca_chi2_cut.
double PHHoughSeeding::get_chi2_cut_full () const inline
get the tracking chi2 cut for full fit
Definition at line 98 of file PHHoughSeeding.h.
References _chi2_cut_full.
double PHHoughSeeding::get_cos_angle_cut () const inline
get early curvature cut between hits, lower values are more open
Definition at line 120 of file PHHoughSeeding.h.
References _cos_angle_cut.
float PHHoughSeeding::get_mag_field () const inline
Definition at line 78 of file PHHoughSeeding.h.
References _magField.
float PHHoughSeeding::get_max_merging_deta () const inline
Definition at line 274 of file PHHoughSeeding.h.
References _max_merging_deta.
float PHHoughSeeding::get_max_merging_dphi () const inline
Definition at line 284 of file PHHoughSeeding.h.
References _max_merging_dphi.
float PHHoughSeeding::get_max_merging_dr () const inline
Definition at line 294 of file PHHoughSeeding.h.
References _max_merging_dr.
float PHHoughSeeding::get_max_merging_dz () const inline
Definition at line 304 of file PHHoughSeeding.h.
References _max_merging_dz.
unsigned int PHHoughSeeding::get_min_nlayers_seeding () const inline
Definition at line 322 of file PHHoughSeeding.h.
References _min_nlayers_seeding.
const std::vector<int>& PHHoughSeeding::get_seeding_layer () const inline
Definition at line 254 of file PHHoughSeeding.h.
References _seeding_layer.
int PHHoughSeeding::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 1046 of file PHHoughSeeding.cc.
References _bbc_vertexes, and Fun4AllReturnCodes::EVENT_OK.
Referenced by Setup().
int PHHoughSeeding::InitializeGeometry (PHCompositeNode * topNode) private
create new node output pointers
scan tracker geometry objects
Now have to load geometry nodes to get norm vector
Definition at line 516 of file PHHoughSeeding.cc.
References _geom_container_intt, _geom_container_maps, _layer_ilayer_map, _layer_ilayer_map_all, _material, _min_nlayers_seeding, _nlayers_all, _nlayers_seeding, _radii, _radii_all, _seeding_layer, _tracker, _tracker_etap_seed, _tracker_vertex, _user_material, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderGeom::get_layer(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4CylinderCellGeom::get_thickness(), PHG4CylinderGeom::get_thickness(), findNode::getClass(), setup_initial_tracker_object(), setup_seed_tracker_objects(), setup_tracker_object(), and Fun4AllBase::Verbosity().
Referenced by Setup().
int PHHoughSeeding::InitializePHGenFit (PHCompositeNode * topNode) private
track propagation
float PHHoughSeeding::kappaToPt (float kappa) private
convert from inverse curvature to momentum
Definition at line 1799 of file PHHoughSeeding.cc.
References _magField, and _pt_rescale.
Referenced by export_output().
void PHHoughSeeding::print_timers () private
Definition at line 449 of file PHHoughSeeding.cc.
References _t_full_fitting, _t_kalman_pat_rec, _t_output_io, _t_search_clusters, _t_search_clusters_encoding, _t_search_clusters_map_iter, _t_seed_init1, _t_seed_init2, _t_seed_init3, _t_seeding, _t_seeds_cleanup, _t_track_propagation, _t_translate1, _t_translate2, _t_translate3, _t_translate_to_PHGenFitTrack, and PHTimer::get_accumulated_time().
Referenced by Process().
int PHHoughSeeding::Process (PHCompositeNode * topNode) protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHTrackSeeding.
Definition at line 363 of file PHHoughSeeding.cc.
References _all_track_covars, _all_track_errors, _all_tracks, _clusters, _event, _min_nlayers_seeding, _nlayers_intt, _nlayers_maps, _nlayers_seeding, _nlayers_tpc, _t_seed_init1, _t_seeding, _track_covars, _track_errors, _tracks, _vertex, _vertex_error, _vertex_tracks, Fun4AllReturnCodes::EVENT_OK, export_output(), full_track_seeding(), PHWHERE, print_timers(), PHTimer::restart(), PHTimer::stop(), translate_input(), Fun4AllBase::Verbosity(), and vertexing().
float PHHoughSeeding::ptToKappa (float pt) private
convert from momentum to inverse curvature
Definition at line 1804 of file PHHoughSeeding.cc.
References _magField, and _pt_rescale.
Referenced by setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
void PHHoughSeeding::set_analyzing_mode (bool analyzingMode) inline
Definition at line 269 of file PHHoughSeeding.h.
References _analyzing_mode.
void PHHoughSeeding::set_ca_chi2_cut (double chi2_cut) inline
set early combination-land chi2 cut(?)
Definition at line 104 of file PHHoughSeeding.h.
References _ca_chi2_cut.
void PHHoughSeeding::set_chi2_cut_fast (double cut_par0, double cut_par1 = 0.0, double cut_max = FLT_MAX) inline
set the tracking pt-dependent chi2 cut for fast fit, cut = min(par0 + par1 / pt, max)
Definition at line 84 of file PHHoughSeeding.h.
References _chi2_cut_fast_max, _chi2_cut_fast_par0, and _chi2_cut_fast_par1.
void PHHoughSeeding::set_chi2_cut_full (double chi2_cut) inline
set the tracking chi2 cut for full fit
Definition at line 93 of file PHHoughSeeding.h.
References _chi2_cut_full.
void PHHoughSeeding::set_chi2_cut_init (double chi2_cut) inline
set the tracking chi2 for initial vertex finding
Definition at line 250 of file PHHoughSeeding.h.
void PHHoughSeeding::set_cos_angle_cut (double cos_angle_cut) inline
set early curvature cut between hits, lower values are more open
Definition at line 115 of file PHHoughSeeding.h.
References _cos_angle_cut.
void PHHoughSeeding::set_mag_field (float magField) inline
Definition at line 74 of file PHHoughSeeding.h.
References _magField.
void PHHoughSeeding::set_material (int layer, float value)
radiation length per layer, sequential layer indexes required here
Definition at line 511 of file PHHoughSeeding.cc.
References _user_material, and value.
void PHHoughSeeding::set_max_merging_deta (float maxMergingDeta) inline
Definition at line 279 of file PHHoughSeeding.h.
References _max_merging_deta.
void PHHoughSeeding::set_max_merging_dphi (float maxMergingDphi) inline
Definition at line 289 of file PHHoughSeeding.h.
References _max_merging_dphi.
void PHHoughSeeding::set_max_merging_dr (float maxMergingDr) inline
Definition at line 299 of file PHHoughSeeding.h.
References _max_merging_dr.
void PHHoughSeeding::set_max_merging_dz (float maxMergingDz) inline
Definition at line 309 of file PHHoughSeeding.h.
References _max_merging_dz.
void PHHoughSeeding::set_min_nlayers_seeding (unsigned int minNlayersSeeding) inline
Definition at line 327 of file PHHoughSeeding.h.
References _min_combo_hits, and _min_nlayers_seeding.
Referenced by Setup().
void PHHoughSeeding::set_min_pT (float pt) inline
Definition at line 125 of file PHHoughSeeding.h.
References _min_pt.
void PHHoughSeeding::set_min_pT_init (float PT) inline
set the minimum pT to try to find during initial vertex finding tracking
Definition at line 235 of file PHHoughSeeding.h.
void PHHoughSeeding::set_r_max (float max_r) inline
set the r search window
Definition at line 138 of file PHHoughSeeding.h.
References _max_r.
void PHHoughSeeding::set_seeding_layer (const int * seedingLayer, const int n) inline
Definition at line 263 of file PHHoughSeeding.h.
References _seeding_layer.
Referenced by PHHoughSeeding(), and Setup().
void PHHoughSeeding::set_use_vertex (bool b) inline
set option to produce initial vertex for further tracking
Definition at line 223 of file PHHoughSeeding.h.
void PHHoughSeeding::set_z0_range (float min_z0, float max_z0) inline
set the z0 search window
Definition at line 131 of file PHHoughSeeding.h.
References _max_z0, and _min_z0.
void PHHoughSeeding::setBinScale (float scale) inline
adjusts the rate of zooming
Definition at line 158 of file PHHoughSeeding.h.
References _bin_scale.
void PHHoughSeeding::setCutOnDCA (bool cod) inline
turn on DCA limitation
Definition at line 169 of file PHHoughSeeding.h.
References _cut_on_dca.
void PHHoughSeeding::setDCACut (float dcut) inline
sets an upper limit on X-Y DCA
Definition at line 174 of file PHHoughSeeding.h.
References _dcaxy_cut.
void PHHoughSeeding::setDCAZCut (float dzcut) inline
sets an upper limit on Z DCA
Definition at line 179 of file PHHoughSeeding.h.
References _dcaz_cut.
void PHHoughSeeding::setFitErrorScale (unsigned int layer, float scale) inline
adjust the relative fit error scale w.r.t. the cluster size
Definition at line 206 of file PHHoughSeeding.h.
References _fit_error_scale.
void PHHoughSeeding::setFullResMultiplier (int lambda) inline
Definition at line 230 of file PHHoughSeeding.h.
void PHHoughSeeding::setInitialResMultiplier (int beta) inline
Definition at line 227 of file PHHoughSeeding.h.
void PHHoughSeeding::setMaxClusterError (float max_cluster_error) inline
limit the maximum error reported by cluster (in number of cell units)
Definition at line 240 of file PHHoughSeeding.h.
void PHHoughSeeding::setPtRescaleFactor (float pt_rescale) inline
adjust the fit pt by a recalibration factor (constant B versus real mag field)
Definition at line 186 of file PHHoughSeeding.h.
References _pt_rescale.
void PHHoughSeeding::setRejectGhosts (bool rg) inline
set internal ghost rejection
Definition at line 147 of file PHHoughSeeding.h.
References _reject_ghosts.
void PHHoughSeeding::setRemoveHits (bool rh) inline
set for internal hit rejection
Definition at line 152 of file PHHoughSeeding.h.
References _remove_hits.
int PHHoughSeeding::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Initilize parameters
Reimplemented from PHTrackSeeding.
Definition at line 202 of file PHHoughSeeding.cc.
References _bin_scale, _ca_chi2_cut, _chi2_cut_fast_max, _chi2_cut_fast_par0, _chi2_cut_fast_par1, _chi2_cut_full, _cos_angle_cut, _cut_on_dca, _dcaxy_cut, _dcaz_cut, _fit_error_scale, _magField, _material, _min_nlayers_seeding, _min_pt, _nlayers_intt, _nlayers_maps, _nlayers_seeding, _pt_rescale, _radii, _reject_ghosts, _remove_hits, _t_full_fitting, _t_kalman_pat_rec, _t_output_io, _t_search_clusters, _t_search_clusters_encoding, _t_search_clusters_map_iter, _t_seed_init1, _t_seed_init2, _t_seed_init3, _t_seeding, _t_seeds_cleanup, _t_track_propagation, _t_translate1, _t_translate2, _t_translate3, _t_translate_to_PHGenFitTrack, _vote_error_scale, _z_bin_scale, Fun4AllReturnCodes::EVENT_OK, GetNodes(), i, InitializeGeometry(), set_min_nlayers_seeding(), set_seeding_layer(), PHTrackSeeding::Setup(), PHTimer::stop(), and Fun4AllBase::Verbosity().
int PHHoughSeeding::setup_initial_tracker_object () private
code to setup initial vertexing tracker
Definition at line 883 of file PHHoughSeeding.cc.
References _bin_scale, _ca_chi2_cut, _chi2_cut_fast_max, _chi2_cut_fast_par0, _chi2_cut_fast_par1, _chi2_cut_full, _cos_angle_cut, _fit_error_scale, _magField, _material, _min_nlayers_seeding, _min_pt, _nlayers_seeding, _radii, _reject_ghosts, _remove_hits, _tracker_vertex, _vote_error_scale, _z_bin_scale, Fun4AllReturnCodes::EVENT_OK, i, M_PI, ptToKappa(), sPHENIXSeedFinder::requireLayers(), sPHENIXSeedFinder::setBinScale(), sPHENIXSeedFinder::setCellularAutomatonChi2Cut(), sPHENIXSeedFinder::setChi2Cut(), sPHENIXSeedFinder::setChi2RemovalCut(), HelixHough::setClusterStartBin(), sPHENIXSeedFinder::setCosAngleCut(), sPHENIXSeedFinder::setCutOnDca(), sPHENIXSeedFinder::setFastChi2Cut(), sPHENIXSeedFinder::setHitErrorScale(), sPHENIXSeedFinder::setMaxHitsPairs(), sPHENIXSeedFinder::setNLayers(), HelixHough::setPrintTimings(), sPHENIXSeedFinder::setRejectGhosts(), sPHENIXSeedFinder::setRemoveHits(), sPHENIXSeedFinder::setSeparateByHelicity(), HelixHough::setSmoothBack(), and sPHENIXSeedFinder::setZBinScale().
Referenced by InitializeGeometry().
int PHHoughSeeding::setup_seed_tracker_objects () private
code to setup seed tracking objects
Definition at line 770 of file PHHoughSeeding.cc.
References _bin_scale, _ca_chi2_cut, _chi2_cut_fast_max, _chi2_cut_fast_par0, _chi2_cut_fast_par1, _chi2_cut_full, _cos_angle_cut, _fit_error_scale, _magField, _material, _max_r, _max_z0, _min_nlayers_seeding, _min_pt, _min_z0, _nlayers_seeding, _radii, _reject_ghosts, _remove_hits, _tracker_etam_seed, _tracker_etap_seed, _vote_error_scale, _z_bin_scale, Fun4AllReturnCodes::EVENT_OK, i, M_PI, ptToKappa(), sPHENIXSeedFinder::requireLayers(), sPHENIXSeedFinder::setBinScale(), sPHENIXSeedFinder::setCellularAutomatonChi2Cut(), sPHENIXSeedFinder::setChi2Cut(), sPHENIXSeedFinder::setChi2RemovalCut(), HelixHough::setClusterStartBin(), sPHENIXSeedFinder::setCosAngleCut(), sPHENIXSeedFinder::setCutOnDca(), sPHENIXSeedFinder::setFastChi2Cut(), sPHENIXSeedFinder::setHitErrorScale(), sPHENIXSeedFinder::setMaxHitsPairs(), sPHENIXSeedFinder::setNLayers(), HelixHough::setPrintTimings(), sPHENIXSeedFinder::setRejectGhosts(), sPHENIXSeedFinder::setRemoveHits(), sPHENIXSeedFinder::setSeparateByHelicity(), HelixHough::setSmoothBack(), and sPHENIXSeedFinder::setZBinScale().
Referenced by InitializeGeometry().
int PHHoughSeeding::setup_tracker_object () private
code to setup full tracking object
Definition at line 965 of file PHHoughSeeding.cc.
References _bin_scale, _ca_chi2_cut, _chi2_cut_fast_max, _chi2_cut_fast_par0, _chi2_cut_fast_par1, _chi2_cut_full, _cos_angle_cut, _cut_on_dca, _dcaxy_cut, _dcaz_cut, _fit_error_scale, _magField, _material, _min_nlayers_seeding, _min_pt, _nlayers_seeding, _radii, _reject_ghosts, _remove_hits, _tracker, _vote_error_scale, _z_bin_scale, Fun4AllReturnCodes::EVENT_OK, i, M_PI, ptToKappa(), sPHENIXSeedFinder::requireLayers(), sPHENIXSeedFinder::setBinScale(), sPHENIXSeedFinder::setCellularAutomatonChi2Cut(), sPHENIXSeedFinder::setChi2Cut(), sPHENIXSeedFinder::setChi2RemovalCut(), HelixHough::setClusterStartBin(), sPHENIXSeedFinder::setCosAngleCut(), sPHENIXSeedFinder::setCutOnDca(), sPHENIXSeedFinder::setDcaCut(), sPHENIXSeedFinder::setFastChi2Cut(), sPHENIXSeedFinder::setHitErrorScale(), sPHENIXSeedFinder::setMaxHitsPairs(), sPHENIXSeedFinder::setNLayers(), HelixHough::setPrintTimings(), sPHENIXSeedFinder::setRejectGhosts(), sPHENIXSeedFinder::setRemoveHits(), sPHENIXSeedFinder::setSeparateByHelicity(), HelixHough::setSmoothBack(), sPHENIXSeedFinder::setVerbosity(), sPHENIXSeedFinder::setZBinScale(), and Fun4AllBase::Verbosity().
Referenced by InitializeGeometry().
void PHHoughSeeding::setUseCellSize (bool use_cell_size) inline
use the cell size as cluster size instead of value stored on cluster
Definition at line 245 of file PHHoughSeeding.h.
void PHHoughSeeding::setVoteErrorScale (unsigned int layer, float scale) inline
adjust the relative voting error scale w.r.t. the cluster size
Definition at line 192 of file PHHoughSeeding.h.
References _vote_error_scale.
void PHHoughSeeding::setZBinScale (float scale) inline
adjusts the rate of zooming
Definition at line 163 of file PHHoughSeeding.h.
References _z_bin_scale.
void PHHoughSeeding::shift_coordinate_system (double dx, double dy, double dz, int ivertex) private
translate the clusters, tracks, and vertex from one origin to another
Definition at line 1850 of file PHHoughSeeding.cc.
References _clusters, _tracks, _vertex, dx, and dy.
Referenced by full_track_seeding().
int PHHoughSeeding::translate_input () private
fetch node pointers
code to translate into the HelixHough universe
Definition at line 1075 of file PHHoughSeeding.cc.
References PHTrackSeeding::_cluster_map, _clusters, _layer_ilayer_map, _nlayers_seeding, Fun4AllReturnCodes::EVENT_OK, TrkrCluster::getClusKey(), TrkrClusterContainer::getClusters(), TrkrCluster::getError(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), i, if(), it, j, SimpleHit3D::set_cluskey(), SimpleHit3D::set_error(), SimpleHit3D::set_id(), SimpleHit3D::set_layer(), SimpleHit3D::set_size(), SimpleHit3D::set_x(), SimpleHit3D::set_y(), SimpleHit3D::set_z(), and Fun4AllBase::Verbosity().
Referenced by Process().
int PHHoughSeeding::vertexing () private
code to seed vertex from initial tracking using a broad search window
code to produce an initial track vertex from the seed SvtxVtxMap[0] -> _vertex and _vertex_error
Definition at line 1393 of file PHHoughSeeding.cc.
References _vertex, _vertex_error, PHTrackSeeding::_vertex_map, _vertex_tracks, Fun4AllReturnCodes::EVENT_OK, SvtxVertexMap::get(), SvtxVertex::get_error(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), PHWHERE, SvtxVertexMap::size(), SvtxVertex::size_tracks(), and Fun4AllBase::Verbosity().
Referenced by Process().
Member Data Documentation
std::vector<Eigen::Matrix<float, 5, 5> > PHHoughSeeding::_all_track_covars private
working array of track covariances
Definition at line 489 of file PHHoughSeeding.h.
Referenced by export_output(), and Process().
std::vector<double> PHHoughSeeding::_all_track_errors private
working array of track chisq
Definition at line 488 of file PHHoughSeeding.h.
Referenced by export_output(), and Process().
std::vector<SimpleTrack3D> PHHoughSeeding::_all_tracks private
working array of tracks
Definition at line 487 of file PHHoughSeeding.h.
Referenced by export_output(), and Process().
TFile* PHHoughSeeding::_analyzing_file private
Definition at line 517 of file PHHoughSeeding.h.
Referenced by End(), and PHHoughSeeding().
bool PHHoughSeeding::_analyzing_mode private
Definition at line 516 of file PHHoughSeeding.h.
Referenced by End(), PHHoughSeeding(), and set_analyzing_mode().
TNtuple* PHHoughSeeding::_analyzing_ntuple private
Definition at line 518 of file PHHoughSeeding.h.
Referenced by End(), and PHHoughSeeding().
BbcVertexMap* PHHoughSeeding::_bbc_vertexes private
Definition at line 503 of file PHHoughSeeding.h.
Referenced by fast_vertex_from_bbc(), and GetNodes().
float PHHoughSeeding::_bin_scale private
Definition at line 467 of file PHHoughSeeding.h.
Referenced by setBinScale(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
double PHHoughSeeding::_ca_chi2_cut private
initial combination cut?
Definition at line 464 of file PHHoughSeeding.h.
Referenced by get_ca_chi2_cut(), set_ca_chi2_cut(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
double PHHoughSeeding::_chi2_cut_fast_max private
fit quality chisq/dof for fast fit track fitting
Definition at line 462 of file PHHoughSeeding.h.
Referenced by set_chi2_cut_fast(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
double PHHoughSeeding::_chi2_cut_fast_par0 private
fit quality chisq/dof for fast fit track fitting
Definition at line 460 of file PHHoughSeeding.h.
Referenced by set_chi2_cut_fast(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
double PHHoughSeeding::_chi2_cut_fast_par1 private
fit quality chisq/dof for fast fit track fitting
Definition at line 461 of file PHHoughSeeding.h.
Referenced by set_chi2_cut_fast(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
double PHHoughSeeding::_chi2_cut_full private
fit quality chisq/dof for kalman track fitting
Definition at line 463 of file PHHoughSeeding.h.
Referenced by get_chi2_cut_full(), set_chi2_cut_full(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
std::vector<SimpleHit3D> PHHoughSeeding::_clusters private
working array of clusters
Definition at line 481 of file PHHoughSeeding.h.
Referenced by export_output(), full_track_seeding(), Process(), shift_coordinate_system(), and translate_input().
double PHHoughSeeding::_cos_angle_cut private
curvature restriction on cluster combos
Definition at line 465 of file PHHoughSeeding.h.
Referenced by get_cos_angle_cut(), set_cos_angle_cut(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
double PHHoughSeeding::_cut_min_pT private
Definition at line 529 of file PHHoughSeeding.h.
bool PHHoughSeeding::_cut_on_dca private
Definition at line 456 of file PHHoughSeeding.h.
Referenced by setCutOnDCA(), Setup(), and setup_tracker_object().
float PHHoughSeeding::_dcaxy_cut private
Definition at line 457 of file PHHoughSeeding.h.
Referenced by setDCACut(), Setup(), and setup_tracker_object().
float PHHoughSeeding::_dcaz_cut private
Definition at line 458 of file PHHoughSeeding.h.
Referenced by setDCAZCut(), Setup(), and setup_tracker_object().
int PHHoughSeeding::_event private
Definition at line 420 of file PHHoughSeeding.h.
Referenced by CleanupSeeds(), CleanupSeedsByHitPattern(), CleanupTracksByHitPattern(), full_track_seeding(), PHHoughSeeding(), and Process().
std::vector<float> PHHoughSeeding::_fit_error_scale private
Definition at line 474 of file PHHoughSeeding.h.
Referenced by setFitErrorScale(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
PHG4CylinderGeomContainer* PHHoughSeeding::_geom_container_intt private
Definition at line 513 of file PHHoughSeeding.h.
Referenced by InitializeGeometry().
PHG4CylinderGeomContainer* PHHoughSeeding::_geom_container_maps private
Definition at line 514 of file PHHoughSeeding.h.
Referenced by InitializeGeometry().
int* PHHoughSeeding::_hit_used_map private
Definition at line 510 of file PHHoughSeeding.h.
int PHHoughSeeding::_hit_used_map_size private
Definition at line 511 of file PHHoughSeeding.h.
std::map<int, unsigned int> PHHoughSeeding::_layer_ilayer_map private
recorded layer indexes to internal sequential indexes
Definition at line 478 of file PHHoughSeeding.h.
Referenced by InitializeGeometry(), and translate_input().
std::map<int, unsigned int> PHHoughSeeding::_layer_ilayer_map_all private
Definition at line 537 of file PHHoughSeeding.h.
Referenced by InitializeGeometry().
float PHHoughSeeding::_magField private
in Tesla
Definition at line 446 of file PHHoughSeeding.h.
Referenced by export_output(), get_mag_field(), kappaToPt(), ptToKappa(), set_mag_field(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
std::vector<float> PHHoughSeeding::_material private
material at each layer in rad. lengths
Definition at line 443 of file PHHoughSeeding.h.
Referenced by InitializeGeometry(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
unsigned int PHHoughSeeding::_max_combo_hits private
maximum hits to enter combination gun
Definition at line 471 of file PHHoughSeeding.h.
Referenced by full_track_seeding().
float PHHoughSeeding::_max_merging_deta private
Definition at line 522 of file PHHoughSeeding.h.
Referenced by CleanupSeeds(), get_max_merging_deta(), and set_max_merging_deta().
float PHHoughSeeding::_max_merging_dphi private
Cleanup Seeds.
Definition at line 521 of file PHHoughSeeding.h.
Referenced by CleanupSeeds(), get_max_merging_dphi(), and set_max_merging_dphi().
float PHHoughSeeding::_max_merging_dr private
Definition at line 523 of file PHHoughSeeding.h.
Referenced by CleanupSeeds(), get_max_merging_dr(), and set_max_merging_dr().
float PHHoughSeeding::_max_merging_dz private
Definition at line 524 of file PHHoughSeeding.h.
Referenced by CleanupSeeds(), get_max_merging_dz(), and set_max_merging_dz().
float PHHoughSeeding::_max_r private
Definition at line 454 of file PHHoughSeeding.h.
Referenced by set_r_max(), and setup_seed_tracker_objects().
unsigned int PHHoughSeeding::_max_share_hits private
if two seeds have common hits more than this number, merge them
Definition at line 527 of file PHHoughSeeding.h.
Referenced by CleanupSeeds().
float PHHoughSeeding::_max_z0 private
Definition at line 453 of file PHHoughSeeding.h.
Referenced by set_z0_range(), and setup_seed_tracker_objects().
unsigned int PHHoughSeeding::_min_combo_hits private
minimum hits to enter combination gun
Definition at line 470 of file PHHoughSeeding.h.
Referenced by full_track_seeding(), and set_min_nlayers_seeding().
unsigned int PHHoughSeeding::_min_nlayers_seeding private
minimum number of layers to make a track
Definition at line 441 of file PHHoughSeeding.h.
Referenced by full_track_seeding(), get_min_nlayers_seeding(), InitializeGeometry(), Process(), set_min_nlayers_seeding(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
float PHHoughSeeding::_min_pt private
Definition at line 451 of file PHHoughSeeding.h.
Referenced by set_min_pT(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
float PHHoughSeeding::_min_z0 private
Definition at line 452 of file PHHoughSeeding.h.
Referenced by set_z0_range(), and setup_seed_tracker_objects().
int PHHoughSeeding::_nlayers_all private
Definition at line 535 of file PHHoughSeeding.h.
Referenced by InitializeGeometry(), and PHHoughSeeding().
unsigned int PHHoughSeeding::_nlayers_intt private
Definition at line 532 of file PHHoughSeeding.h.
Referenced by PHHoughSeeding(), Process(), and Setup().
unsigned int PHHoughSeeding::_nlayers_maps private
Definition at line 531 of file PHHoughSeeding.h.
Referenced by PHHoughSeeding(), Process(), and Setup().
unsigned int PHHoughSeeding::_nlayers_seeding private
number of detector layers
Definition at line 440 of file PHHoughSeeding.h.
Referenced by InitializeGeometry(), Process(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), setup_tracker_object(), and translate_input().
unsigned int PHHoughSeeding::_nlayers_tpc private
Definition at line 533 of file PHHoughSeeding.h.
Referenced by PHHoughSeeding(), and Process().
float PHHoughSeeding::_pt_rescale private
Definition at line 473 of file PHHoughSeeding.h.
Referenced by kappaToPt(), ptToKappa(), setPtRescaleFactor(), and Setup().
std::vector<float> PHHoughSeeding::_radii private
radial distance of each layer (cm)
Definition at line 442 of file PHHoughSeeding.h.
Referenced by InitializeGeometry(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
std::vector<float> PHHoughSeeding::_radii_all private
Definition at line 538 of file PHHoughSeeding.h.
Referenced by InitializeGeometry().
bool PHHoughSeeding::_reject_ghosts private
Definition at line 448 of file PHHoughSeeding.h.
Referenced by setRejectGhosts(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
bool PHHoughSeeding::_remove_hits private
Definition at line 449 of file PHHoughSeeding.h.
Referenced by setRemoveHits(), Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), and setup_tracker_object().
std::vector<int> PHHoughSeeding::_seeding_layer private
Definition at line 438 of file PHHoughSeeding.h.
Referenced by get_seeding_layer(), InitializeGeometry(), and set_seeding_layer().
PHTimer* PHHoughSeeding::_t_full_fitting private
Definition at line 435 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_kalman_pat_rec private
Definition at line 430 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_output_io private
Definition at line 436 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_search_clusters private
Definition at line 431 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_search_clusters_encoding private
Definition at line 432 of file PHHoughSeeding.h.
Referenced by print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_search_clusters_map_iter private
Definition at line 433 of file PHHoughSeeding.h.
Referenced by print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_seed_init1 private
Definition at line 422 of file PHHoughSeeding.h.
Referenced by print_timers(), Process(), and Setup().
PHTimer* PHHoughSeeding::_t_seed_init2 private
Definition at line 423 of file PHHoughSeeding.h.
Referenced by print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_seed_init3 private
Definition at line 424 of file PHHoughSeeding.h.
Referenced by print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_seeding private
Definition at line 421 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), Process(), and Setup().
PHTimer* PHHoughSeeding::_t_seeds_cleanup private
Definition at line 425 of file PHHoughSeeding.h.
Referenced by End(), full_track_seeding(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_track_propagation private
Definition at line 434 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_translate1 private
Definition at line 427 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_translate2 private
Definition at line 428 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_translate3 private
Definition at line 429 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
PHTimer* PHHoughSeeding::_t_translate_to_PHGenFitTrack private
Definition at line 426 of file PHHoughSeeding.h.
Referenced by End(), print_timers(), and Setup().
std::vector<Eigen::Matrix<float, 5, 5> > PHHoughSeeding::_track_covars private
working array of track covariances
Definition at line 485 of file PHHoughSeeding.h.
Referenced by CleanupTracksByHitPattern(), export_output(), full_track_seeding(), and Process().
std::vector<double> PHHoughSeeding::_track_errors private
working array of track chisq
Definition at line 484 of file PHHoughSeeding.h.
Referenced by CleanupTracksByHitPattern(), export_output(), full_track_seeding(), and Process().
sPHENIXSeedFinder* PHHoughSeeding::_tracker private
tracks in this vertex
finds full tracks
Definition at line 496 of file PHHoughSeeding.h.
Referenced by CleanupTracksByHitPattern(), End(), full_track_seeding(), InitializeGeometry(), and setup_tracker_object().
sPHENIXSeedFinder* PHHoughSeeding::_tracker_etam_seed private
finds a subset of tracks for the vertex guess
Definition at line 499 of file PHHoughSeeding.h.
Referenced by End(), and setup_seed_tracker_objects().
sPHENIXSeedFinder* PHHoughSeeding::_tracker_etap_seed private
finds a subset of tracks for the vertex guess
Definition at line 498 of file PHHoughSeeding.h.
Referenced by End(), InitializeGeometry(), and setup_seed_tracker_objects().
sPHENIXSeedFinder* PHHoughSeeding::_tracker_vertex private
finds a subset of tracks for initial vertex-finding
Definition at line 497 of file PHHoughSeeding.h.
Referenced by End(), InitializeGeometry(), and setup_initial_tracker_object().
std::vector<SimpleTrack3D> PHHoughSeeding::_tracks private
working array of tracks
Definition at line 483 of file PHHoughSeeding.h.
Referenced by CleanupSeeds(), CleanupSeedsByHitPattern(), CleanupTracksByHitPattern(), export_output(), full_track_seeding(), Process(), and shift_coordinate_system().
std::map<int, float> PHHoughSeeding::_user_material private
material in user ladder indexes
Definition at line 444 of file PHHoughSeeding.h.
Referenced by InitializeGeometry(), PHHoughSeeding(), and set_material().
std::vector<std::vector<float> > PHHoughSeeding::_vertex private
working array for collision vertex list
Definition at line 491 of file PHHoughSeeding.h.
Referenced by export_output(), fast_vertex_from_bbc(), full_track_seeding(), Process(), shift_coordinate_system(), and vertexing().
std::vector<std::vector<float> > PHHoughSeeding::_vertex_error private
sqrt(cov)
Definition at line 492 of file PHHoughSeeding.h.
Referenced by PHHoughSeeding(), Process(), and vertexing().
std::vector<int> PHHoughSeeding::_vertex_tracks private
Definition at line 493 of file PHHoughSeeding.h.
Referenced by Process(), and vertexing().
VertexFinder PHHoughSeeding::_vertexFinder private
vertex finding object
Definition at line 500 of file PHHoughSeeding.h.
Referenced by full_track_seeding().
std::vector<float> PHHoughSeeding::_vote_error_scale private
Definition at line 475 of file PHHoughSeeding.h.
Referenced by Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), setup_tracker_object(), and setVoteErrorScale().
float PHHoughSeeding::_z_bin_scale private
Definition at line 468 of file PHHoughSeeding.h.
Referenced by Setup(), setup_initial_tracker_object(), setup_seed_tracker_objects(), setup_tracker_object(), and setZBinScale().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHHoughSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHHoughSeeding.cc