Analysis Software: coresoftware/blob/master/offline/packages/PHGeometry/macros/PHGeom_DSTInspection.C File Reference
PHGeom_DSTInspection.C File Reference
Quick inspection of PHGeoTGeo object in RUN/GEOMETRY node inside a DST file.
#include <cassert>
Functions
void PHGeom_DSTInspection (string DST_file_name="sPHENIX.root_DST.root", bool do_clip=true)
Detailed Description
Quick inspection of PHGeoTGeo object in RUN/GEOMETRY node inside a DST file.
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file PHGeom_DSTInspection.C.
Function Documentation
void PHGeom_DSTInspection (string DST_file_name = "sPHENIX.root_DST.root", bool do_clip = true)
Quick inspection of PHGeoTGeo object in RUN/GEOMETRY node inside a DST file Based on abhisek's display macro
Definition at line 16 of file PHGeom_DSTInspection.C.
References assert, Fun4AllInputManager::fileopen(), PHGeomUtility::GetTGeoManager(), recoConsts::instance(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::run(), PHFlag::set_IntFlag(), Fun4AllServer::topNode(), v, and Fun4AllBase::Verbosity().