Analysis Software: macros/blob/master/macros/g4simulations/G4Setup_EICDetector.C File Reference
G4Setup_EICDetector.C File Reference
#include "GlobalVariables.C"
#include "G4_Pipe.C"
#include "G4_Tracking_EIC.C"
#include "G4_PSTOF.C"
#include "G4_CEmc_EIC.C"
#include "G4_HcalIn_ref.C"
#include "G4_Magnet.C"
#include "G4_HcalOut_ref.C"
#include "G4_PlugDoor_EIC.C"
#include "G4_FEMC_EIC.C"
#include "G4_FHCAL.C"
#include "G4_EEMC.C"
#include "G4_DIRC.C"
#include "G4_RICH.C"
#include "G4_Aerogel.C"
#include <g4eval/PHG4DstCompressReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4decayer/EDecayType.hh>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/PHG4Reco.h>
#include <phfield/PHFieldConfig.h>
Functions
void RunLoadTest ()
void G4Init (bool do_svtx=true, bool do_cemc=true, bool do_hcalin=true, bool do_magnet=true, bool do_hcalout=true, bool do_pipe=true, bool do_plugdoor=true, bool do_FEMC=true, bool do_FHCAL=true, bool do_EEMC=true, bool do_DIRC=true, bool do_RICH=true, bool do_Aerogel=true)
int G4Setup (const int absorberactive=0, const string &field="1.5", const EDecayType decayType=EDecayType::kAll, const bool do_svtx=true, const bool do_cemc=true, const bool do_hcalin=true, const bool do_magnet=true, const bool do_hcalout=true, const bool do_pipe=true, const bool do_plugdoor=true, const bool do_FEMC=false, const bool do_FHCAL=false, const bool do_EEMC=true, const bool do_DIRC=true, const bool do_RICH=true, const bool do_Aerogel=true, const float magfield_rescale=1.0)
void ShowerCompress (int verbosity=0)
void DstCompress (Fun4AllDstOutputManager *out)
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 377 of file G4Setup_EICDetector.C.
References Fun4AllDstOutputManager::StripNode().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_sPHENIX(), Fun4All_single_particle(), and Jin_BJet().
void G4Init (bool do_svtx = true, bool do_cemc = true, bool do_hcalin = true, bool do_magnet = true, bool do_hcalout = true, bool do_pipe = true, bool do_plugdoor = true, bool do_FEMC = true, bool do_FHCAL = true, bool do_EEMC = true, bool do_DIRC = true, bool do_RICH = true, bool do_Aerogel = true)
Definition at line 36 of file G4Setup_EICDetector.C.
References AerogelInit(), CEmcInit(), DIRCInit(), EEMCInit(), FEMCInit(), FHCALInit(), HCalInnerInit(), HCalOuterInit(), MagnetInit(), PipeInit(), PlugDoorInit(), RICHInit(), and TrackingInit().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
int G4Setup (const int absorberactive = 0, const string & field = "1.5", const EDecayType decayType = EDecayType::kAll, const bool do_svtx = true, const bool do_cemc = true, const bool do_hcalin = true, const bool do_magnet = true, const bool do_hcalout = true, const bool do_pipe = true, const bool do_plugdoor = true, const bool do_FEMC = false, const bool do_FHCAL = false, const bool do_EEMC = true, const bool do_DIRC = true, const bool do_RICH = true, const bool do_Aerogel = true, const float magfield_rescale = 1.0)
Definition at line 133 of file G4Setup_EICDetector.C.
References AerogelSetup(), PHG4DetectorSubsystem::BlackHole(), CEmc(), DIRCSetup(), EEMCSetup(), FEMCSetup(), FHCALSetup(), PHFieldConfig::Field3DCartesian, PHG4Reco::GetWorldSizeZ(), HCalInner(), HCalOuter(), Fun4AllServer::instance(), kAll, PHFieldConfig::kField2D, Magnet(), no_overlapp, PHG4DetectorSubsystem::OverlapCheck(), Pipe(), PlugDoor(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), RICHSetup(), PHG4DetectorSubsystem::set_double_param(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4DetectorSubsystem::set_int_param(), PHG4Reco::set_rapidity_coverage(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and Tracking().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_EICIR(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void RunLoadTest ()
Definition at line 34 of file G4Setup_EICDetector.C.
void ShowerCompress (int verbosity = 0)
Definition at line 316 of file G4Setup_EICDetector.C.
References PHG4DstCompressReco::AddCellContainer(), PHG4DstCompressReco::AddHitContainer(), PHG4DstCompressReco::AddTowerContainer(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and Jin_BJet().