Analysis Software: TowerJetInput Class Reference
TowerJetInput Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/TowerJetInput.h>
Public Member Functions
TowerJetInput (Jet::SRC input)
virtual ~TowerJetInput ()
void identify (std::ostream &os=std::cout)
Jet::SRC get_src ()
std::vector< Jet * > get_input (PHCompositeNode *topNode)
Public Member Functions inherited from JetInput
virtual ~JetInput ()
Private Attributes
int _verbosity
Jet::SRC _input
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 14 of file TowerJetInput.h.
Constructor & Destructor Documentation
TowerJetInput::TowerJetInput (Jet::SRC input)
Definition at line 25 of file TowerJetInput.cc.
virtual TowerJetInput::~TowerJetInput () inline virtual
Definition at line 18 of file TowerJetInput.h.
Member Function Documentation
std::vector< Jet * > TowerJetInput::get_input (PHCompositeNode * topNode) virtual
Reimplemented from JetInput.
Definition at line 47 of file TowerJetInput.cc.
References _input, _verbosity, assert, GlobalVertexMap::begin(), Jet::CEMC_TOWER, Jet::CEMC_TOWER_RETOWER, Jet::CEMC_TOWER_SUB1, Jet::CEMC_TOWER_SUB1CS, GlobalVertexMap::empty(), Jet::FEMC_TOWER, Jet::FHCAL_TOWER, RawTowerGeom::get_center_radius(), RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTower::get_energy(), RawTower::get_id(), RawTower::get_key(), RawTowerGeomContainer::get_tower_geometry(), GlobalVertex::get_z(), RawTowerContainer::getTowers(), Jet::HCALIN_TOWER, Jet::HCALIN_TOWER_SUB1, Jet::HCALIN_TOWER_SUB1CS, Jet::HCALOUT_TOWER, Jet::HCALOUT_TOWER_SUB1, Jet::HCALOUT_TOWER_SUB1CS, Jet::insert_comp(), phi, r, Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), and z.
Jet::SRC TowerJetInput::get_src () inline virtual
Reimplemented from JetInput.
Definition at line 22 of file TowerJetInput.h.
References _input.
void TowerJetInput::identify (std::ostream & os = std::cout) virtual
Reimplemented from JetInput.
Definition at line 31 of file TowerJetInput.cc.
References _input, Jet::CEMC_TOWER, Jet::FEMC_TOWER, Jet::FHCAL_TOWER, Jet::HCALIN_TOWER, and Jet::HCALOUT_TOWER.
Member Data Documentation
Jet::SRC TowerJetInput::_input private
Definition at line 28 of file TowerJetInput.h.
Referenced by get_input(), get_src(), and identify().
int TowerJetInput::_verbosity private
Definition at line 27 of file TowerJetInput.h.
Referenced by get_input().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/TowerJetInput.h
coresoftware/blob/master/simulation/g4simulation/g4jets/TowerJetInput.cc