Analysis Software: coresoftware/blob/master/generators/hijing/src/hijini.f File Reference
hijini.f File Reference
Functions/Subroutines
subroutine hijini
Function/Subroutine Documentation
subroutine hijini ()
Definition at line 4 of file hijini.f.
References atl_ran(), attflv(), HiParnt::hint1(), HiParnt::hipr1(), i, HijJet4::iadr(), HijJet2::iasg(), HiParnt::ihnt2(), HiParnt::ihpr2(), HijJet2::k1sg(), HijJet2::k2sg(), HijJet4::kfdr(), HijJet1::kfpj(), HijJet1::kftj(), HijJet4::ndr(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HijJet1::ntj(), HijJet4::pdr(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), HiStrng::pp(), HiStrng::pt(), HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), and ulmass().
Referenced by hijing().