Analysis Software: coresoftware/blob/master/generators/hijing/examples/example_2.f File Reference
example_2.f File Reference
Functions/Subroutines
program __example_2.f__
function ran (NSEED)
Function/Subroutine Documentation
program __example_2.f__ ()
Definition at line 7 of file example_2.f.
References HiMain1::eatt(), efrm, go(), hijing(), hijset(), HiParnt::hint1(), HiParnt::hipr1(), i, iap, HijJet2::iasg(), iat, HiParnt::ihnt2(), HiParnt::ihpr2(), izp, izt, j, HiMain1::jatt(), k, HijJet2::k1sg(), HijJet2::k2sg(), HiMain2::katt(), HijJet1::kfpj(), HijJet1::kftj(), luchge(), HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HiMain1::np(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HiMain1::nt(), HijJet1::ntj(), HiMain2::patt(), HijJet2::pesg(), HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), HiStrng::pp(), HiStrng::pt(), HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), PHTimer::stop(), x, and y.
function ran (NSEED)
Definition at line 179 of file example_2.f.
References RanSeed::nseed(), ran(), and rlu().