Analysis Software: FastJetAlgo Class Reference
FastJetAlgo Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/FastJetAlgo.h>
Public Member Functions
FastJetAlgo (Jet::ALGO algo, float par, int verbosity=0)
virtual ~FastJetAlgo ()
void identify (std::ostream &os=std::cout)
Jet::ALGO get_algo ()
float get_par ()
std::vector< Jet * > get_jets (std::vector< Jet * > particles)
Public Member Functions inherited from JetAlgo
virtual ~JetAlgo ()
Private Attributes
int _verbosity
Jet::ALGO _algo
float _par
Additional Inherited Members
Protected Member Functions inherited from JetAlgo
JetAlgo ()
Detailed Description
Definition at line 10 of file FastJetAlgo.h.
Constructor & Destructor Documentation
FastJetAlgo::FastJetAlgo (Jet::ALGO algo, float par, int verbosity = 0)
Definition at line 21 of file FastJetAlgo.cc.
References _verbosity.
virtual FastJetAlgo::~FastJetAlgo () inline virtual
Definition at line 14 of file FastJetAlgo.h.
Member Function Documentation
Jet::ALGO FastJetAlgo::get_algo () inline virtual
Reimplemented from JetAlgo.
Definition at line 17 of file FastJetAlgo.h.
References _algo.
std::vector< Jet * > FastJetAlgo::get_jets (std::vector< Jet * > particles) virtual
Reimplemented from JetAlgo.
Definition at line 52 of file FastJetAlgo.cc.
References _algo, _par, _verbosity, Jet::ANTIKT, Jet::begin_comp(), Jet::CAMBRIDGE, Jet::end_comp(), Jet::insert_comp(), Jet::KT, Jet::set_e(), Jet::set_id(), Jet::set_px(), Jet::set_py(), and Jet::set_pz().
float FastJetAlgo::get_par () inline virtual
Reimplemented from JetAlgo.
Definition at line 18 of file FastJetAlgo.h.
References _par.
void FastJetAlgo::identify (std::ostream & os = std::cout) virtual
Reimplemented from JetAlgo.
Definition at line 40 of file FastJetAlgo.cc.
References _algo, _par, Jet::ANTIKT, Jet::CAMBRIDGE, and Jet::KT.
Member Data Documentation
Jet::ALGO FastJetAlgo::_algo private
Definition at line 24 of file FastJetAlgo.h.
Referenced by get_algo(), get_jets(), and identify().
float FastJetAlgo::_par private
Definition at line 25 of file FastJetAlgo.h.
Referenced by get_jets(), get_par(), and identify().
int FastJetAlgo::_verbosity private
Definition at line 23 of file FastJetAlgo.h.
Referenced by FastJetAlgo(), and get_jets().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/FastJetAlgo.h
coresoftware/blob/master/simulation/g4simulation/g4jets/FastJetAlgo.cc