Analysis Software: macros/blob/master/macros/g4simulations/G4_Tracking_EIC.C File Reference
G4_Tracking_EIC.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <trackreco/PHRaveVertexing.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include <vector>
#include "G4_GEM_EIC.C"
#include "G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec_EIC.C"
Functions
void TrackingInit (int verbosity=0)
double Tracking (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Tracking_Reco (int verbosity=0, bool displaced_vertex=false)
void Tracking_Eval (std::string outputfile, int verbosity=0)
Function Documentation
double Tracking (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 33 of file G4_Tracking_EIC.C.
References EGEMSetup(), FGEMSetup(), and Svtx().
void Tracking_Eval (std::string outputfile, int verbosity = 0)
Definition at line 221 of file G4_Tracking_EIC.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and PHG4TrackFastSimEval::set_filename().
void Tracking_Reco (int verbosity = 0, bool displaced_vertex = false)
Definition at line 49 of file G4_Tracking_EIC.C.
References PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::add_state_name(), PHG4TrackFastSim::Cylinder, PHG4TrackFastSim::enable_vertexing(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), verbosity, PHG4TrackFastSim::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.
void TrackingInit (int verbosity = 0)
Definition at line 21 of file G4_Tracking_EIC.C.
References EGEM_Init(), FGEM_Init(), and SvtxInit().