Analysis Software: macros/blob/master/macros/QA/calorimeter/QA_Draw_Utility.C File Reference
QA_Draw_Utility.C File Reference
#include <TCanvas.h>
#include <TClass.h>
#include <TDirectory.h>
#include <TFile.h>
#include <TSystem.h>
#include <TGraphErrors.h>
#include <TH1F.h>
#include <TList.h>
#include <TObject.h>
#include <TString.h>
#include <TStyle.h>
#include <TTree.h>
#include <TLegend.h>
#include <TLegendEntry.h>
#include <TLine.h>
#include <TPad.h>
#include <cassert>
#include <cmath>
#include <iostream>
Macros
#define QA_Draw_Utility_C
Functions
void SavePad (TPad *p)
Service function to SaveCanvas()
void SaveCanvas (TCanvas *c, TString name="", Bool_t bEPS=kTRUE)
Save canvas to multiple formats.
double DrawReference (TH1 *hnew, TH1 *href, bool draw_href_error=false)
void DrawReference (TGraph *hnew, TGraph *href, bool draw_href_error=true)
TGraphErrors * FitResolution (const TH2F *h2, const bool normalize_mean=true)
Fit for resolution of TH2F.
TGraphErrors * FitProfile (const TH2F *h2)
Fit for profile along the Y direction of TH2F.
TH1 * GetBinominalRatio (TH1 *h_pass, TH1 *h_n_trial, bool process_zero_bins=false)
ratio between two histograms with binominal error based on Wilson score interval. Assuming each histogram is count.
void PutInputFileName (TCanvas *c1, const double height, const char *new_file_name, const char *ref_file_name)
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file QA_Draw_Utility.C.
Macro Definition Documentation
#define QA_Draw_Utility_C
Definition at line 12 of file QA_Draw_Utility.C.
Function Documentation
double DrawReference (TH1 * hnew, TH1 * href, bool draw_href_error = false)
Draw 1D histogram along with its reference as shade
Parameters
[in] draw_href_error whether to draw error band for reference plot. Otherwise, it is a filled histogram (default)
Definition at line 125 of file QA_Draw_Utility.C.
Referenced by QA_Draw_Calorimeter_Sum_Cluster(), QA_Draw_Calorimeter_Sum_TrackProj(), QA_Draw_Calorimeter_Sum_TrackProjEP(), QA_Draw_CEMC_G4Hit(), QA_Draw_CEMC_TowerCluster(), QA_Draw_HCALIN_G4Hit(), QA_Draw_HCALIN_TowerCluster(), QA_Draw_HCALOUT_G4Hit(), QA_Draw_HCALOUT_TowerCluster(), QA_Draw_Jet_Spectrum(), and QA_Draw_Jet_TruthMatching().
void DrawReference (TGraph * hnew, TGraph * href, bool draw_href_error = true)
Draw 1D TGraph along with its reference as shade
Parameters
[in] draw_href_error whether to draw error band for reference plot. Otherwise, it is a filled histogram (default)
Definition at line 212 of file QA_Draw_Utility.C.
TGraphErrors* FitProfile (const TH2F * h2)
Fit for profile along the Y direction of TH2F.
Definition at line 312 of file QA_Draw_Utility.C.
References f2(), h1, i, n, x, and y.
Referenced by DCACheck(), EMCDistributionVSBeam_SUM(), PositionDependenceData(), PositionDependenceSim(), QA_Draw_Jet_TruthMatching(), RecoCheck(), Resolution(), and TrackDistortion().
TGraphErrors* FitResolution (const TH2F * h2, const bool normalize_mean = true)
Fit for resolution of TH2F.
Definition at line 259 of file QA_Draw_Utility.C.
References f2(), h1, i, n, norm, x, and y.
TH1* GetBinominalRatio (TH1 * h_pass, TH1 * h_n_trial, bool process_zero_bins = false)
ratio between two histograms with binominal error based on Wilson score interval. Assuming each histogram is count.
Definition at line 374 of file QA_Draw_Utility.C.
References assert, x, y, and z.
Referenced by QA_Draw_Jet_TruthMatching().
void PutInputFileName (TCanvas * c1, const double height, const char * new_file_name, const char * ref_file_name)
Put input file name on the canvas
Parameters
[in] c1 canvas pointer
[in] bottom height fraction height of the canvas to be used for this label
[in] new_file_name new file name being inspected
[in] ref_file_name reference file name
Definition at line 421 of file QA_Draw_Utility.C.
References t.
void SaveCanvas (TCanvas * c, TString name = "", Bool_t bEPS = kTRUE)
Save canvas to multiple formats.
Parameters
[in] c pointer to the canvas
[in] name Base of the file name. The default is the name of the cavas
[in] bEPS true = save .eps and .pdf format too.
Definition at line 82 of file QA_Draw_Utility.C.
References name, SavePad(), x, and y.
Referenced by AmplitudeCheck(), CentralCalorimeterRate(), ChannelCheck(), ChargeCheck(), ChargePerLayer(), Check(), Check1(), Check2(), ClusterQA(), Clusters3D(), ClusterSizeScan(), CrossSection2RAA(), CrossSection2RAA_Proposal(), CrossSection2v2(), DataRate(), DCACheck(), dNchdEta(), dNdeta(), Draw_HFJetTruth_DrawCrossSection_PR(), Draw_HFJetTruth_InvMass_DrawCrossSection_PR(), DrawCalibratedE(), DrawCalibratedE_Plot(), DrawCalibratedE_PlotTestBeam(), DrawCalibratedE_Tower(), DrawCluster_Linearality(), DrawCluster_Res(), DrawCluster_Res_2Fit(), DrawCluster_Res_2Fit_1DSpacalNoSVX(), DrawCluster_Res_2Fit_1DSpacalNoSVX_Eta3(), DrawCluster_Res_2Fit_2DSpacalNoSVX(), DrawCluster_Res_2Fit_Electron_NoSVX(), DrawCrossSection(), DrawDist(), DrawEcal_BlockCalibration(), DrawEMCalTower_LineShape(), DrawEMCalTower_Resolution(), DrawEMCalTower_Resolution_Compare(), DrawEnergyDensity(), DrawEnergyDensityXY(), DrawFieldMap(), DrawLeakage(), DrawLeakage_LY(), DrawLeakage_Phi(), DrawLeakage_Phi_Folding(), DrawLeakage_Wide(), DrawPrototype2EMCalTower_Resolution(), DrawPrototype2EMCalTower_ResolutionRecalib(), DrawSF(), DrawTower_EMCDistribution(), DrawTower_EMCDistribution5x5(), DrawTower_EMCTrigEff(), DrawTower_EMCTrigEff_SlideingWindow2(), DrawTower_Raw_E(), DrawTowerIDCheck(), DrawTowerSum_Res_2Fit_1DSpacalNoSVX(), DrawTowerSum_Res_2Fit_1DSpacalNoSVX_Eta3(), DrawTpcPrototypeGenFitTrkFitter_Summary(), Edep_Checks(), Edep_Distribution(), Edep_LL_Distribution(), EMC_HodoScope_Calibration(), EMCDistribution(), EMCDistribution_ADC(), EMCDistribution_Fast(), EMCDistribution_HCalCalibration(), EMCDistribution_PeakSample_Fast(), EMCDistribution_ShowShape(), EMCDistribution_SUM(), EMCDistribution_SUM_RawADC(), EMCDistributionVSBeam_SUM(), Ep_Checks(), EP_LL_Distribution(), EtaScan(), EventCheck(), example_save_canvas(), FEEDataSize(), FitVerticalScan(), ForwardCalorimeterRate(), FullCyl(), FullCylEIC(), FullCylRProj(), FullCylRProjPHENIXComparison(), FullCylZProj(), Get_Res_linear_Summmary(), Get_Res_linear_Summmary_Sim(), GetBeamMom(), getMeanRMS(), GetResolution(), HitPositionCheck(), HodoscopeCheck(), KinematicsChecks(), LineShapeCompare(), LineShapeCompare_Electron(), LineShapeData(), LineShapeSim(), MakeChipMultiplicitySet(), MakeRadiusCut(), Occupancy(), PIDScan(), PositionDependenceData(), PositionDependenceSim(), QA_Draw_Calorimeter_Sum_Cluster(), QA_Draw_Calorimeter_Sum_TrackProj(), QA_Draw_Calorimeter_Sum_TrackProjEP(), QA_Draw_CEMC_G4Hit(), QA_Draw_CEMC_TowerCluster(), QA_Draw_HCALIN_G4Hit(), QA_Draw_HCALIN_TowerCluster(), QA_Draw_HCALOUT_G4Hit(), QA_Draw_HCALOUT_TowerCluster(), QA_Draw_Jet_Spectrum(), QA_Draw_Jet_Summary(), QA_Draw_Jet_TruthMatching(), RecoCheck(), RejectionCompare(), RejectionCurve(), RejectionCurve_AuAuSummary(), RejectionCurve_AuAuSummary_Compare(), RejectionCurve_AuAuSummary_Compare2(), RejectionCurve_AuAuSummaryPos(), RejectionCurve_PIDComparison(), RejectionCurve_PiProton(), RejectionCurve_PiProtonPos(), RejectionCurve_ppSummary(), RejectionCurve_ppSummaryPos(), RejectionCurve_RejMethodComparison(), RejectionCurve_RejMethodComparison_AntiProton(), RejectionCurvePos(), Resolution(), Sampling(), SectorDataSize(), ShowerShape_Checks(), SimPositionCheck(), Track3D(), TrackClusterEnergy(), TrackDistortion(), TrackerRate(), TrackProjection_Checks(), TrackProjection_Checks_Comparison(), TrackQA(), TriggerMultiplicity(), UpsilonPair_Checks(), VertexChecks(), VertexCyl(), and WaveletCheck().
void SavePad (TPad * p)
Service function to SaveCanvas()
Definition at line 41 of file QA_Draw_Utility.C.
Referenced by SaveCanvas(), and SavePad().