Analysis Software: macros/blob/master/macros/g4simulations/G4_HcalIn_ref.C File Reference
G4_HcalIn_ref.C File Reference
#include "GlobalVariables.C"
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4detectors/PHG4InnerHcalSubsystem.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
Enumerations
enum enu_HCalIn_clusterizer {
kHCalInGraphClusterizer, kHCalInTemplateClusterizer, kHCalInGraphClusterizer, kHCalInTemplateClusterizer,
kHCalInGraphClusterizer, kHCalInTemplateClusterizer
}
Functions
void HCalInner_SupportRing (PHG4Reco *g4Reco, const int absorberactive=0)
A rough version of the inner HCal support ring, from Richie's CAD drawing. - Jin.
void HCalInnerInit (const int iflag=0)
graph clusterizer, RawClusterBuilderGraph
double HCalInner (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0, int verbosity=0)
void HCALInner_Cells (int verbosity=0)
void HCALInner_Towers (int verbosity=0)
void HCALInner_Clusters (int verbosity=0)
void HCALInner_Eval (std::string outputfile, int verbosity=0)
Variables
const bool inner_hcal_material_Al = true
static int inner_hcal_eic = 0
enu_HCalIn_clusterizer HCalIn_clusterizer = kHCalInTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Enumeration Type Documentation
enum enu_HCalIn_clusterizer
Enumerator:
kHCalInGraphClusterizer
kHCalInTemplateClusterizer
kHCalInGraphClusterizer
kHCalInTemplateClusterizer
kHCalInGraphClusterizer
kHCalInTemplateClusterizer
Definition at line 31 of file G4_HcalIn_ref.C.
Function Documentation
double HCalInner (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0, int verbosity = 0)
Definition at line 53 of file G4_HcalIn_ref.C.
References PHG4DetectorSubsystem::get_double_param(), HCalInner_SupportRing(), no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
void HCALInner_Cells (int verbosity = 0)
Definition at line 173 of file G4_HcalIn_ref.C.
References PHG4HcalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
void HCALInner_Clusters (int verbosity = 0)
Definition at line 238 of file G4_HcalIn_ref.C.
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), Fun4AllServer::instance(), kHCalInGraphClusterizer, kHCalInTemplateClusterizer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void HCALInner_Eval (std::string outputfile, int verbosity = 0)
Definition at line 267 of file G4_HcalIn_ref.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void HCalInner_SupportRing (PHG4Reco * g4Reco, const int absorberactive = 0)
A rough version of the inner HCal support ring, from Richie's CAD drawing. - Jin.
void HCALInner_Towers (int verbosity = 0)
Definition at line 195 of file G4_HcalIn_ref.C.
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), verbosity, and Fun4AllBase::Verbosity().
void HCalInnerInit (const int iflag = 0)
graph clusterizer, RawClusterBuilderGraph
Definition at line 45 of file G4_HcalIn_ref.C.
Variable Documentation
enu_HCalIn_clusterizer HCalIn_clusterizer = kHCalInTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 39 of file G4_HcalIn_ref.C.
int inner_hcal_eic = 0 static
Definition at line 29 of file G4_HcalIn_ref.C.
const bool inner_hcal_material_Al = true
Definition at line 27 of file G4_HcalIn_ref.C.