Analysis Software: oncsSub_iddreamv0 Class Reference
oncsSub_iddreamv0 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_iddreamv0.h>
Classes
struct FEU_decoded_data
Public Member Functions
oncsSub_iddreamv0 (subevtdata_ptr)
~oncsSub_iddreamv0 ()
int iValue (const int channel, const char *)
int iValue (const int channel, const int sample)
int iValue (const int dreamchip, const int sample, const char *)
int iValue (const int dreamchip, const int channel, const int sample)
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w4
oncsSubevent_w4 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
virtual int copyMe (int[], const int maxlength) const
Protected Member Functions
int * decode (int *)
int decode_payload (unsigned short *d, const int size)
int decode_dream (FEU_decoded_data *fd, unsigned short *d, const int size, const unsigned int sample_nr)
int decode_dream (FEU_decoded_data *fd, const int offset, const int size, const unsigned int sample_nr)
Protected Attributes
std::map< int, struct
FEU_decoded_data * > feu_map
int _nr_feus
int _is_decoded
unsigned short * swapped_array
Detailed Description
Definition at line 12 of file oncsSub_iddreamv0.h.
Constructor & Destructor Documentation
oncsSub_iddreamv0::oncsSub_iddreamv0 (subevtdata_ptr data)
Definition at line 12 of file oncsSub_iddreamv0.cc.
References _is_decoded, and swapped_array.
oncsSub_iddreamv0::~oncsSub_iddreamv0 ()
Definition at line 22 of file oncsSub_iddreamv0.cc.
References fd, feu_map, it, and swapped_array.
Member Function Documentation
int * oncsSub_iddreamv0::decode (int * nwout) protected virtual
Reimplemented from oncsSubevent_w4.
Definition at line 230 of file oncsSub_iddreamv0.cc.
References _is_decoded, d, subevt_data::data, decode_payload(), dlength, oncsSubevent::getLength(), oncsSubevent::getPadding(), i, k, oncsSubevent::SubeventHdr, and swapped_array.
Referenced by dump(), and iValue().
int oncsSub_iddreamv0::decode_dream (FEU_decoded_data * fd, unsigned short * d, const int size, const unsigned int sample_nr) protected
Definition at line 448 of file oncsSub_iddreamv0.cc.
References oncsSub_iddreamv0::FEU_decoded_data::cellids, i, and oncsSub_iddreamv0::FEU_decoded_data::samples.
Referenced by decode_payload().
int oncsSub_iddreamv0::decode_dream (FEU_decoded_data * fd, const int offset, const int size, const unsigned int sample_nr) protected
int oncsSub_iddreamv0::decode_payload (unsigned short * d, const int size) protected
Definition at line 268 of file oncsSub_iddreamv0.cc.
References oncsSub_iddreamv0::FEU_decoded_data::_dream_enabled, oncsSub_iddreamv0::FEU_decoded_data::_feu_C, oncsSub_iddreamv0::FEU_decoded_data::_feu_id, oncsSub_iddreamv0::FEU_decoded_data::_feu_P, oncsSub_iddreamv0::FEU_decoded_data::_feu_Z, oncsSub_iddreamv0::FEU_decoded_data::_nr_dreams, oncsSub_iddreamv0::FEU_decoded_data::_nr_samples, oncsSub_iddreamv0::FEU_decoded_data::cellids, decode_dream(), fd, feu_map, index, and oncsSub_iddreamv0::FEU_decoded_data::samples.
Referenced by decode().
void oncsSub_iddreamv0::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w4.
Definition at line 150 of file oncsSub_iddreamv0.cc.
References channel(), decode(), i, oncsSubevent::identify(), and iValue().
int oncsSub_iddreamv0::iValue (const int channel, const char * what) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Implements Packet.
Definition at line 37 of file oncsSub_iddreamv0.cc.
References oncsSub_iddreamv0::FEU_decoded_data::_feu_C, oncsSub_iddreamv0::FEU_decoded_data::_feu_id, oncsSub_iddreamv0::FEU_decoded_data::_feu_P, oncsSub_iddreamv0::FEU_decoded_data::_feu_Z, oncsSub_iddreamv0::FEU_decoded_data::_nr_dreams, oncsSub_iddreamv0::FEU_decoded_data::_nr_samples, decode(), fd, feu_map, i, it, and k.
Referenced by dump().
int oncsSub_iddreamv0::iValue (const int channel, const int iy) virtual
this supports devices which are inherently organized as two-dimensional data, such as flash ADC's (channel vs time slice)
Implements Packet.
Definition at line 119 of file oncsSub_iddreamv0.cc.
int oncsSub_iddreamv0::iValue (const int channel, const int y, const char * what) virtual
we have a few recent devices which have one more dimension (such as card, time sample, channel)
Implements Packet.
Definition at line 99 of file oncsSub_iddreamv0.cc.
References oncsSub_iddreamv0::FEU_decoded_data::_dream_enabled, fd, and feu_map.
int oncsSub_iddreamv0::iValue (const int channel, const int iy, const int iz) virtual
this supports devices organized as three-dimensional data (card vs channel vs time slice)
Implements Packet.
Definition at line 128 of file oncsSub_iddreamv0.cc.
References oncsSub_iddreamv0::FEU_decoded_data::_dream_enabled, decode(), fd, feu_map, and oncsSub_iddreamv0::FEU_decoded_data::samples.
Member Data Documentation
int oncsSub_iddreamv0::_is_decoded protected
Definition at line 61 of file oncsSub_iddreamv0.h.
Referenced by decode(), and oncsSub_iddreamv0().
int oncsSub_iddreamv0::_nr_feus protected
Definition at line 59 of file oncsSub_iddreamv0.h.
std::map<int,struct FEU_decoded_data *> oncsSub_iddreamv0::feu_map protected
Definition at line 55 of file oncsSub_iddreamv0.h.
Referenced by decode_payload(), iValue(), and ~oncsSub_iddreamv0().
unsigned short* oncsSub_iddreamv0::swapped_array protected
Definition at line 65 of file oncsSub_iddreamv0.h.
Referenced by decode(), oncsSub_iddreamv0(), and ~oncsSub_iddreamv0().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_iddreamv0.h
online_distribution/blob/master/newbasic/oncsSub_iddreamv0.cc