Analysis Software: analysis/blob/master/TPC/groot/FindBlobs.C File Reference
FindBlobs.C File Reference
#include "FindBlobs.h"
#include "groot.h"
#include "ABlob.h"
#include "AZigzag.h"
#include "Quiver.h"
#include "Riostream.h"
#include <iostream>
Functions
void FindBlobs ()
Function Documentation
void FindBlobs ()
Definition at line 11 of file FindBlobs.C.
References Quiver::BlobTimeCut, i, groot::instance(), AZigzag::IsHit(), j, k, Nphi, Nr, Quiver::PaddingLimit, AZigzag::Q(), AZigzag::T(), groot::theBlobs, and groot::ZigzagMap2.
Referenced by process_event().