Analysis Software: ReadLD Class Reference
ReadLD Class Reference
Public Member Functions
ReadLD (std::vector< std::string > &theInputVars)
virtual ~ReadLD ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadLD (std::vector< std::string > &theInputVars)
virtual ~ReadLD ()
double GetMvaValue (const std::vector< double > &inputValues) const
Public Member Functions inherited from IClassifierReader
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
Private Member Functions
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
Private Attributes
const char * fClassName
const size_t fNvars
const bool fIsNormalised
double fVmin [10]
double fVmax [10]
char fType [10]
std::vector< double > fLDCoefficients
Additional Inherited Members
Protected Attributes inherited from IClassifierReader
bool fStatusIsClean
Detailed Description
Definition at line 81 of file eback_LD.class.C.
Constructor & Destructor Documentation
ReadLD::ReadLD (std::vector< std::string > & theInputVars) inline
Definition at line 86 of file eback_LD.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadLD::~ReadLD () inline virtual
Definition at line 156 of file eback_LD.class.C.
References Clear().
ReadLD::ReadLD (std::vector< std::string > & theInputVars) inline
Definition at line 86 of file hback_LD.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadLD::~ReadLD () inline virtual
Definition at line 156 of file hback_LD.class.C.
References Clear().
Member Function Documentation
void ReadLD::Clear () inline private
Definition at line 231 of file eback_LD.class.C.
References fLDCoefficients.
Referenced by ~ReadLD().
void ReadLD::Clear () private
double ReadLD::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadLD::GetMvaValue (const std::vector< double > & inputValues) const inline virtual
Implements IClassifierReader.
Definition at line 236 of file eback_LD.class.C.
References fClassName, fVmax, fVmin, GetMvaValue__(), IsNormalised(), IClassifierReader::IsStatusClean(), and NormVariable().
double ReadLD::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadLD::GetMvaValue__ (const std::vector< double > & inputValues) const inline private
Definition at line 220 of file eback_LD.class.C.
References fLDCoefficients, and fNvars.
Referenced by GetMvaValue().
size_t ReadLD::GetNvar () const inline private
Definition at line 174 of file hback_LD.class.C.
References fNvars.
size_t ReadLD::GetNvar () const inline private
Definition at line 174 of file eback_LD.class.C.
References fNvars.
char ReadLD::GetType (int ivar) const inline private
Definition at line 175 of file eback_LD.class.C.
References fType.
char ReadLD::GetType (int ivar) const inline private
Definition at line 175 of file hback_LD.class.C.
References fType.
void ReadLD::Initialize () private
void ReadLD::Initialize () inline private
Definition at line 198 of file eback_LD.class.C.
References fClassName, fLDCoefficients, fNvars, and IClassifierReader::fStatusIsClean.
Referenced by ReadLD().
bool ReadLD::IsNormalised () const inline private
Definition at line 179 of file hback_LD.class.C.
References fIsNormalised.
bool ReadLD::IsNormalised () const inline private
Definition at line 179 of file eback_LD.class.C.
References fIsNormalised.
Referenced by GetMvaValue().
double ReadLD::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 182 of file eback_LD.class.C.
Referenced by GetMvaValue().
double ReadLD::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 182 of file hback_LD.class.C.
Member Data Documentation
const char * ReadLD::fClassName private
Definition at line 171 of file eback_LD.class.C.
Referenced by GetMvaValue(), Initialize(), and ReadLD().
const bool ReadLD::fIsNormalised private
Definition at line 178 of file eback_LD.class.C.
Referenced by IsNormalised().
std::vector< double > ReadLD::fLDCoefficients private
Definition at line 195 of file eback_LD.class.C.
Referenced by Clear(), GetMvaValue__(), and Initialize().
const size_t ReadLD::fNvars private
Definition at line 173 of file eback_LD.class.C.
Referenced by GetMvaValue__(), GetNvar(), Initialize(), and ReadLD().
char ReadLD::fType private
Definition at line 188 of file eback_LD.class.C.
Referenced by GetType(), and ReadLD().
double ReadLD::fVmax private
Definition at line 181 of file eback_LD.class.C.
Referenced by GetMvaValue(), and ReadLD().
double ReadLD::fVmin private
Definition at line 180 of file eback_LD.class.C.
Referenced by GetMvaValue(), and ReadLD().
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/Training/weights/eback_LD.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_LD.class.C