Analysis Software: Proto4SampleFrac Class Reference
Proto4SampleFrac Class Reference
you get started
#include <analysis/blob/master/Prototype4/HCal/SampleFrac/Proto4SampleFrac.h>
Public Member Functions
Proto4SampleFrac (const std::string &calo_name, const std::string &filename)
constructor
virtual ~Proto4SampleFrac ()
destructor
int Init (PHCompositeNode *topNode)
Standard function called at initialization.
int InitRun (PHCompositeNode *topNode)
Standard function called when a new run is processed.
int process_event (PHCompositeNode *topNode)
Standard function called at each event.
int End (PHCompositeNode *topNode)
Standard function called at the end of processing. Save your stuff here.
void is_sim (bool b)
Is processing simulation files?
std::string get_histo_prefix ()
common prefix for QA histograms
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { n_size = 8 }
Private Member Functions
Fun4AllHistoManager * get_HistoManager ()
get manager of histograms
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
Private Attributes
bool _is_sim
is processing simulation files?
std::string _filename
output root file name
std::string _calo_name
PHG4HitContainer * _calo_hit_container
PHG4HitContainer * _calo_abs_hit_container
PHG4TruthInfoContainer * _truth_container
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
you get started
Definition at line 24 of file Proto4SampleFrac.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
n_size
Definition at line 57 of file Proto4SampleFrac.h.
Constructor & Destructor Documentation
Proto4SampleFrac::Proto4SampleFrac (const std::string & calo_name, const std::string & filename)
constructor
Definition at line 49 of file Proto4SampleFrac.C.
References Fun4AllBase::Verbosity().
Proto4SampleFrac::~Proto4SampleFrac () virtual
destructor
Definition at line 59 of file Proto4SampleFrac.C.
Member Function Documentation
int Proto4SampleFrac::End (PHCompositeNode * topNode) virtual
Standard function called at the end of processing. Save your stuff here.
Reimplemented from SubsysReco.
Definition at line 136 of file Proto4SampleFrac.C.
References _filename, assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, and Fun4AllHistoManager::nHistos().
pair< int, int > Proto4SampleFrac::find_max (RawTowerContainer * towers, int cluster_size) private
Definition at line 448 of file Proto4SampleFrac.C.
References assert, col, energy, RawTower::get_energy(), RawTowerContainer::getTower(), max, n_size, and t.
string Proto4SampleFrac::get_histo_prefix ()
common prefix for QA histograms
Definition at line 83 of file Proto4SampleFrac.C.
References _calo_name.
Referenced by Init(), and process_event().
Fun4AllHistoManager * Proto4SampleFrac::get_HistoManager () private
get manager of histograms
Definition at line 63 of file Proto4SampleFrac.C.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), Init(), and process_event().
int Proto4SampleFrac::Init (PHCompositeNode * topNode) virtual
Standard function called at initialization.
Reimplemented from SubsysReco.
Definition at line 152 of file Proto4SampleFrac.C.
References _calo_name, _filename, assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_histo_prefix(), get_HistoManager(), SVM_v1::h, i, PHTFileServer::open(), and Fun4AllHistoManager::registerHisto().
int Proto4SampleFrac::InitRun (PHCompositeNode * topNode) virtual
Standard function called when a new run is processed.
Reimplemented from SubsysReco.
Definition at line 88 of file Proto4SampleFrac.C.
References _calo_abs_hit_container, _calo_hit_container, _calo_name, _truth_container, assert, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
void Proto4SampleFrac::is_sim (bool b) inline
Is processing simulation files?
Definition at line 47 of file Proto4SampleFrac.h.
References _is_sim.
int Proto4SampleFrac::process_event (PHCompositeNode * topNode) virtual
Standard function called at each event.
Reimplemented from SubsysReco.
Definition at line 233 of file Proto4SampleFrac.C.
References _calo_abs_hit_container, _calo_hit_container, _calo_name, _truth_container, assert, Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_avg_t(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), PHG4Particle::get_e(), PHG4Hit::get_edep(), get_histo_prefix(), get_HistoManager(), PHG4Hit::get_light_yield(), PHG4Particle::get_pid(), PHG4VtxPoint::get_t(), PHG4Hit::get_trkid(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), Fun4AllHistoManager::getHisto(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetMap(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVtx(), SVM_v1::h, PHG4VtxPoint::identify(), PHG4HitContainer::size(), and Fun4AllBase::Verbosity().
Member Data Documentation
PHG4HitContainer* Proto4SampleFrac::_calo_abs_hit_container private
Definition at line 76 of file Proto4SampleFrac.h.
Referenced by InitRun(), and process_event().
PHG4HitContainer* Proto4SampleFrac::_calo_hit_container private
Definition at line 75 of file Proto4SampleFrac.h.
Referenced by InitRun(), and process_event().
std::string Proto4SampleFrac::_calo_name private
Definition at line 73 of file Proto4SampleFrac.h.
Referenced by get_histo_prefix(), Init(), InitRun(), and process_event().
std::string Proto4SampleFrac::_filename private
output root file name
Definition at line 72 of file Proto4SampleFrac.h.
Referenced by End(), and Init().
bool Proto4SampleFrac::_is_sim private
is processing simulation files?
Definition at line 63 of file Proto4SampleFrac.h.
Referenced by is_sim().
PHG4TruthInfoContainer* Proto4SampleFrac::_truth_container private
Definition at line 77 of file Proto4SampleFrac.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype4/HCal/SampleFrac/Proto4SampleFrac.h
analysis/blob/master/Prototype4/HCal/SampleFrac/Proto4SampleFrac.C