Analysis Software: Packet_w2 Class Reference
Packet_w2 Class Reference
#include <online_distribution/blob/master/newbasic/packet_w124.h>
Public Member Functions
Packet_w2 ()
Packet_w2 (PACKET_ptr)
void dump (OSTREAM &)
void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &=COUT) const
Public Member Functions inherited from Packet_A
Packet_A (PACKET_ptr packet_ptr)
Packet_A ()
~Packet_A ()
int getLength () const
int getErrorLength () const
int getDebugLength () const
get the length of the debug block
int getIdentifier () const
get the packet identifier
int getPadding () const
get the number of padding units in the packet data.
int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
int getDataLength () const
get what the name says...
void identify (OSTREAM &=COUT) const
void fullIdentify (OSTREAM &=COUT) const
void dumpErrorBlock (OSTREAM &=COUT)
void dumpDebugBlock (OSTREAM &=COUT)
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
float rValue (const int)
float rValue (const int, const char *)
float rValue (const int, const int)
int getArraylength (const char *)
int fillIntArray (int[], const int, int *, const char *what="")
int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
int * getIntArray (int *, const char *what="")
float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int getCheckSumStatus () const
int copyMe (int dest[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
Protected Member Functions
int * decode (int *)
Protected Member Functions inherited from Packet_A
int standardIntArray (int[], const int, int *, const char *what="")
Additional Inherited Members
Static Protected Member Functions inherited from Packet_A
static void fix_endianess (long long *x)
static void fix_endianess (double *x)
static void fix_endianess (char *str, const int length)
Protected Attributes inherited from Packet_A
PACKET_ptr packet
int is_data_type
int data1_length
int data2_length
int data3_length
int data4_length
int data5_length
int data6_length
int data7_length
int data8_length
int data9_length
int data10_length
int * decoded_data1
int * decoded_data2
int * decoded_data3
int * decoded_data4
int * decoded_data5
int * decoded_data6
int * decoded_data7
int * decoded_data8
int * decoded_data9
int * decoded_data10
Detailed Description
Based on the packet_A definition, we build the other classes of packets, which are the base classes of packets with wordsizes 1, 2, and 4.
Note that this class can be instantiated and will be used if we encounter a packet with an as yet unknown decoding method, or if we want to customize the decoding step. It can still handle all the operations such as return raw data or envelope information, but none of those which require the data to be decoded.
Definition at line 54 of file packet_w124.h.
Constructor & Destructor Documentation
Packet_w2::Packet_w2 ()
Definition at line 12 of file packet_w124.cc.
Packet_w2::Packet_w2 (PACKET_ptr packet_ptr)
Definition at line 15 of file packet_w124.cc.
Member Function Documentation
int* Packet_w2::decode (int *) inline protected virtual
Implements Packet_A.
Definition at line 66 of file packet_w124.h.
void Packet_w2::dump (OSTREAM & out)
Definition at line 40 of file packet_w124.cc.
References Packet_A::dumpDebugBlock(), Packet_A::dumpErrorBlock(), and gdump().
void Packet_w2::gdump (const int how = EVT_HEXADECIMAL, OSTREAM & out = COUT) const
Definition at line 125 of file packet_w124.cc.
References EVT_DECIMAL, EVT_HEXADECIMAL, EVT_RAW, EVT_RAW_WH, findPacketDataStart(), Packet_A::getDataLength(), Packet_A::getLength(), Packet_A::getPadding(), Packet_A::identify(), j, Packet_A::packet, and SETW.
Referenced by dump().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/packet_w124.h
online_distribution/blob/master/newbasic/packet_w124.cc