Analysis Software: macros/blob/master/macros/sPHENIXStyle/sPhenixStyle.h File Reference
sPhenixStyle.h File Reference
#include <TStyle.h>
Functions
void SetsPhenixStyle ()
sPHENIX Style, based on a style file from ATLAS by Peter Steinberg
TStyle * sPhenixStyle ()
Function Documentation
void SetsPhenixStyle ()
sPHENIX Style, based on a style file from ATLAS by Peter Steinberg
Definition at line 13 of file sPhenixStyle.C.
References sPhenixStyle().
Referenced by Draw_EICRate(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), Draw_HFJetTruth(), Draw_HFJetTruth_InvMass(), DrawEcal_BlockCalibration(), DrawFieldMap(), DrawFluence(), DrawHadronShowers(), DrawTPCDataStreamEmulator(), DrawTPCFEE(), DrawTPCIntegratedCharge(), DrawTpcPrototypeGenFitTrkFitter(), DrawTpcPrototypeGenFitTrkFitter_Summary(), DrawTpcPrototypeUnpacker(), DrawTrackingEval(), eicsmear_dvmp_plot(), eicsmear_dvmp_tree(), jpsi_invariant_mass_plot_exclusiveReco(), LivePlot_Energy_EMC(), OccupancySim(), Plot_FastTrack_Efficiency(), Plot_Hit_Count(), Plot_Measured_Energy_EMC(), Plot_Measured_Energy_Over_True_Energy_EMC(), Plot_SVTX_Efficiency(), plot_true_false_positive(), prob_EMC_e_pi_plotMacro(), QA_Draw_Calorimeter_Sum_Cluster(), QA_Draw_Calorimeter_Sum_TrackProj(), QA_Draw_Calorimeter_Sum_TrackProjEP(), QA_Draw_CEMC_G4Hit(), QA_Draw_CEMC_TowerCluster(), QA_Draw_HCALIN_G4Hit(), QA_Draw_HCALIN_TowerCluster(), QA_Draw_HCALOUT_G4Hit(), QA_Draw_HCALOUT_TowerCluster(), QA_Draw_Jet_Spectrum(), QA_Draw_Jet_Summary(), and QA_Draw_Jet_TruthMatching().
TStyle* sPhenixStyle ()
Definition at line 22 of file sPhenixStyle.C.
Referenced by SetsPhenixStyle().