Analysis Software: RawClusterBuilderTemplateEEMC Class Reference
RawClusterBuilderTemplateEEMC Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.h>
Public Member Functions
RawClusterBuilderTemplateEEMC (const std::string &name="RawClusterBuilderGraph")
virtual ~RawClusterBuilderTemplateEEMC ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void Detector (const std::string &d)
void set_threshold_energy (const float e)
void setEnergyNorm (float norm)
void checkenergy (const int i=1)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool Cell2Abs (RawTowerGeomContainer *towergeom, float phiC, float etaC, float &phi, float &eta)
Private Attributes
RawClusterContainer * _clusters
BEmcRecEEMC * bemc
float fEnergyNorm
float _min_tower_e
int chkenergyconservation
std::string detector
std::string ClusterNodeName
int BINX0
int NBINX
int BINY0
int NBINY
float Zcenter
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file RawClusterBuilderTemplateEEMC.h.
Constructor & Destructor Documentation
RawClusterBuilderTemplateEEMC::RawClusterBuilderTemplateEEMC (const std::string & name = "RawClusterBuilderGraph")
Definition at line 41 of file RawClusterBuilderTemplateEEMC.cc.
References bemc, BINX0, BINY0, fEnergyNorm, NBINX, NBINY, BEmcRec::SetGeometry(), BEmcRec::SetPlaneGeometry(), BEmcRec::SetTowerThreshold(), BEmcRec::SetVertex(), and Zcenter.
RawClusterBuilderTemplateEEMC::~RawClusterBuilderTemplateEEMC () virtual
Definition at line 36 of file RawClusterBuilderTemplateEEMC.cc.
Member Function Documentation
bool RawClusterBuilderTemplateEEMC::Cell2Abs (RawTowerGeomContainer * towergeom, float phiC, float etaC, float & phi, float & eta) private
Definition at line 141 of file RawClusterBuilderTemplateEEMC.cc.
References BINX0, BINY0, dx, dy, RawTowerDefs::encode_towerid(), RawTowerGeomContainer::get_calorimeter_id(), RawTowerGeomContainer::get_tower_geometry(), NBINX, NBINY, and printf().
void RawClusterBuilderTemplateEEMC::checkenergy (const int i = 1) inline
Definition at line 26 of file RawClusterBuilderTemplateEEMC.h.
References chkenergyconservation, and i.
void RawClusterBuilderTemplateEEMC::CreateNodes (PHCompositeNode * topNode) private
Definition at line 369 of file RawClusterBuilderTemplateEEMC.cc.
References _clusters, PHCompositeNode::addNode(), ClusterNodeName, detector, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void RawClusterBuilderTemplateEEMC::Detector (const std::string & d) inline
Definition at line 22 of file RawClusterBuilderTemplateEEMC.h.
References d.
int RawClusterBuilderTemplateEEMC::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 364 of file RawClusterBuilderTemplateEEMC.cc.
References Fun4AllReturnCodes::EVENT_OK.
int RawClusterBuilderTemplateEEMC::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 69 of file RawClusterBuilderTemplateEEMC.cc.
References Fun4AllReturnCodes::ABORTEVENT, bemc, BINX0, BINY0, CreateNodes(), RawTowerDefs::decode_index1(), RawTowerDefs::decode_index2(), detector, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTowerGeom::get_id(), RawTowerGeomContainer::get_tower_geometries(), NBINX, NBINY, PHWHERE, BEmcRec::SetGeometry(), BEmcRec::SetTowerGeometry(), and Zcenter.
int RawClusterBuilderTemplateEEMC::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 201 of file RawClusterBuilderTemplateEEMC.cc.
References _clusters, _min_tower_e, Fun4AllReturnCodes::ABORTEVENT, RawClusterContainer::AddCluster(), RawCluster::addTower(), EmcModule::amp, bemc, BINX0, BINY0, detector, Fun4AllReturnCodes::DISCARDEVENT, RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, fEnergyNorm, BEmcRec::FindClusters(), RawTower::get_bineta(), RawTower::get_binphi(), RawTower::get_energy(), RawTowerContainer::getCalorimeterID(), BEmcRec::GetClusters(), RawTowerContainer::getTowers(), EmcModule::ich, NBINX, NBINY, PHWHERE, printf(), RawCluster::set_chi2(), RawCluster::set_ecore(), RawCluster::set_energy(), RawCluster::set_phi(), RawCluster::set_prob(), RawCluster::set_r(), RawCluster::set_z(), BEmcRec::SetModules(), and EmcModule::tof.
void RawClusterBuilderTemplateEEMC::set_threshold_energy (const float e) inline
Definition at line 24 of file RawClusterBuilderTemplateEEMC.h.
References _min_tower_e.
void RawClusterBuilderTemplateEEMC::setEnergyNorm (float norm) inline
Definition at line 25 of file RawClusterBuilderTemplateEEMC.h.
References fEnergyNorm, and norm.
Member Data Documentation
RawClusterContainer* RawClusterBuilderTemplateEEMC::_clusters private
Definition at line 32 of file RawClusterBuilderTemplateEEMC.h.
Referenced by CreateNodes(), and process_event().
float RawClusterBuilderTemplateEEMC::_min_tower_e private
Definition at line 37 of file RawClusterBuilderTemplateEEMC.h.
Referenced by process_event(), and set_threshold_energy().
BEmcRecEEMC* RawClusterBuilderTemplateEEMC::bemc private
Definition at line 34 of file RawClusterBuilderTemplateEEMC.h.
Referenced by InitRun(), process_event(), and RawClusterBuilderTemplateEEMC().
int RawClusterBuilderTemplateEEMC::BINX0 private
Definition at line 43 of file RawClusterBuilderTemplateEEMC.h.
Referenced by Cell2Abs(), InitRun(), process_event(), and RawClusterBuilderTemplateEEMC().
int RawClusterBuilderTemplateEEMC::BINY0 private
Definition at line 45 of file RawClusterBuilderTemplateEEMC.h.
Referenced by Cell2Abs(), InitRun(), process_event(), and RawClusterBuilderTemplateEEMC().
int RawClusterBuilderTemplateEEMC::chkenergyconservation private
Definition at line 38 of file RawClusterBuilderTemplateEEMC.h.
Referenced by checkenergy().
std::string RawClusterBuilderTemplateEEMC::ClusterNodeName private
Definition at line 41 of file RawClusterBuilderTemplateEEMC.h.
Referenced by CreateNodes().
std::string RawClusterBuilderTemplateEEMC::detector private
Definition at line 40 of file RawClusterBuilderTemplateEEMC.h.
Referenced by CreateNodes(), InitRun(), and process_event().
float RawClusterBuilderTemplateEEMC::fEnergyNorm private
Definition at line 35 of file RawClusterBuilderTemplateEEMC.h.
Referenced by process_event(), RawClusterBuilderTemplateEEMC(), and setEnergyNorm().
int RawClusterBuilderTemplateEEMC::NBINX private
Definition at line 44 of file RawClusterBuilderTemplateEEMC.h.
Referenced by Cell2Abs(), InitRun(), process_event(), and RawClusterBuilderTemplateEEMC().
int RawClusterBuilderTemplateEEMC::NBINY private
Definition at line 46 of file RawClusterBuilderTemplateEEMC.h.
Referenced by Cell2Abs(), InitRun(), process_event(), and RawClusterBuilderTemplateEEMC().
float RawClusterBuilderTemplateEEMC::Zcenter private
Definition at line 47 of file RawClusterBuilderTemplateEEMC.h.
Referenced by InitRun(), and RawClusterBuilderTemplateEEMC().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.cc