Analysis Software: JetRecoEval Class Reference
JetRecoEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/JetRecoEval.h>
Public Member Functions
JetRecoEval (PHCompositeNode *topNode, const std::string &recojetname, const std::string &truthjetname)
virtual ~JetRecoEval ()
void next_event (PHCompositeNode *topNode)
reinitialize the eval for a new event
void do_caching (bool do_cache)
activate or deactivate the memory caching inside the evaluation module
void set_strict (bool strict)
unsigned int get_errors ()
get a count of the errors discovered thus far
void set_verbosity (int verbosity)
adjust the messaging from the evalutaion module
JetTruthEval * get_truth_eval ()
get a copy of the lower level eval and its memory cache
SvtxEvalStack * get_svtx_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_cemc_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_hcalin_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_hcalout_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_femc_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_fhcal_eval_stack ()
get a copy of the lower level eval and its memory cache
std::set< PHG4Shower * > all_truth_showers (Jet *recojet)
what truth showers contributed to this reconstructed jet?
std::set< PHG4Particle * > all_truth_particles (Jet *recojet)
what truth particles contributed to this reconstructed jet?
std::set< Jet * > all_truth_jets (Jet *recojet)
what truth jets contributed to this reconstructed jet?
Jet * max_truth_jet_by_energy (Jet *recojet)
which truth jet contributed the most energy to this reconstructed jet?
std::set< Jet * > all_jets_from (Jet *truthjet)
what reconstructed jets had contributions from this truth jet?
Jet * best_jet_from (Jet *truthjet)
which reconstructed jet had the largest energy contribution from this truth jet?
Jet * unique_reco_jet_from_truth (Jet *truthjet)
Jet * unique_truth_jet_from_reco (Jet *recojet)
float get_energy_contribution (Jet *recojet, Jet *truthjet)
what was the energy contribution to this reconstructed jet from this truth jet?
float get_energy_contribution (Jet *recojet, Jet::SRC src)
what was the energy contribution to this reconstructed jet from a particular source
std::set< PHG4Hit * > all_truth_hits (Jet *recojet)
which truth hits contributed to this reconstructed jet?
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
Private Attributes
JetTruthEval _jettrutheval
std::string _recojetname
std::string _truthjetname
JetMap * _recojets
JetMap * _truthjets
SvtxTrackMap * _trackmap
RawTowerContainer * _cemctowers
RawClusterContainer * _cemcclusters
RawTowerContainer * _hcalintowers
RawClusterContainer * _hcalinclusters
RawTowerContainer * _hcalouttowers
RawClusterContainer * _hcaloutclusters
RawTowerContainer * _femctowers
RawClusterContainer * _femcclusters
RawTowerContainer * _fhcaltowers
RawClusterContainer * _fhcalclusters
bool _strict
int _verbosity
unsigned int _errors
bool _do_cache
std::map< Jet *, std::set
< PHG4Shower * > > _cache_all_truth_showers
std::map< Jet *, std::set
< PHG4Particle * > > _cache_all_truth_particles
std::map< Jet *, std::set< Jet * > > _cache_all_truth_jets
std::map< Jet *, Jet * > _cache_max_truth_jet_by_energy
std::map< Jet *, std::set< Jet * > > _cache_all_jets_from
std::map< Jet *, Jet * > _cache_best_jet_from
std::map< std::pair< Jet
*, Jet * >, float > _cache_get_energy_contribution
std::map< std::pair< Jet
*, Jet::SRC >, float > _cache_get_energy_contribution_src
std::map< Jet *, std::set
< PHG4Hit * > > _cache_all_truth_hits
used in get_energy_contribution (Jet* recojet, Jet::SRC src);
Detailed Description
Definition at line 29 of file JetRecoEval.h.
Constructor & Destructor Documentation
JetRecoEval::JetRecoEval (PHCompositeNode * topNode, const std::string & recojetname, const std::string & truthjetname)
example recojetname: AntiKt_Tower_r03 example truthjetname: AntiKt_Truth_r03
Definition at line 37 of file JetRecoEval.cc.
References get_node_pointers().
JetRecoEval::~JetRecoEval () virtual
Definition at line 73 of file JetRecoEval.cc.
References _errors, and _verbosity.
Member Function Documentation
std::set< Jet * > JetRecoEval::all_jets_from (Jet * truthjet)
what reconstructed jets had contributions from this truth jet?
Definition at line 789 of file JetRecoEval.cc.
References _cache_all_jets_from, _do_cache, _errors, _recojets, _strict, all_truth_jets(), assert, JetMap::begin(), JetMap::end(), and Jet::get_id().
Referenced by best_jet_from().
std::set< PHG4Hit * > JetRecoEval::all_truth_hits (Jet * recojet)
which truth hits contributed to this reconstructed jet?
Definition at line 1422 of file JetRecoEval.cc.
References _cache_all_truth_hits, _cemcclusters, _cemctowers, _do_cache, _errors, _femcclusters, _femctowers, _fhcalclusters, _fhcaltowers, _hcalinclusters, _hcalintowers, _hcaloutclusters, _hcalouttowers, _strict, _trackmap, SvtxTrackEval::all_truth_hits(), CaloRawTowerEval::all_truth_hits(), CaloRawClusterEval::all_truth_hits(), assert, Jet::begin_comp(), Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::end_comp(), Jet::FEMC_CLUSTER, Jet::FEMC_TOWER, Jet::FHCAL_CLUSTER, Jet::FHCAL_TOWER, SvtxTrackMap::get(), get_cemc_eval_stack(), get_femc_eval_stack(), get_fhcal_eval_stack(), get_hcalin_eval_stack(), get_hcalout_eval_stack(), CaloEvalStack::get_rawcluster_eval(), CaloEvalStack::get_rawtower_eval(), get_svtx_eval_stack(), SvtxEvalStack::get_track_eval(), RawClusterContainer::getCluster(), RawTowerContainer::getTower(), Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, index, PHWHERE, and Jet::TRACK.
std::set< Jet * > JetRecoEval::all_truth_jets (Jet * recojet)
what truth jets contributed to this reconstructed jet?
Definition at line 679 of file JetRecoEval.cc.
References _cache_all_truth_jets, _do_cache, _errors, _jettrutheval, _strict, all_truth_particles(), assert, JetTruthEval::get_truth_jet(), and particles.
Referenced by all_jets_from(), and max_truth_jet_by_energy().
std::set< PHG4Particle * > JetRecoEval::all_truth_particles (Jet * recojet)
what truth particles contributed to this reconstructed jet?
Definition at line 387 of file JetRecoEval.cc.
References _cache_all_truth_particles, _cemcclusters, _cemctowers, _do_cache, _errors, _femcclusters, _femctowers, _fhcalclusters, _fhcaltowers, _hcalinclusters, _hcalintowers, _hcaloutclusters, _hcalouttowers, _strict, _trackmap, SvtxTrackEval::all_truth_particles(), CaloRawTowerEval::all_truth_primary_particles(), CaloRawClusterEval::all_truth_primary_particles(), assert, Jet::begin_comp(), Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::end_comp(), Jet::FEMC_CLUSTER, Jet::FEMC_TOWER, Jet::FHCAL_CLUSTER, Jet::FHCAL_TOWER, SvtxTrackMap::get(), get_cemc_eval_stack(), get_femc_eval_stack(), get_fhcal_eval_stack(), get_hcalin_eval_stack(), get_hcalout_eval_stack(), CaloEvalStack::get_rawcluster_eval(), CaloEvalStack::get_rawtower_eval(), get_svtx_eval_stack(), SvtxEvalStack::get_track_eval(), RawClusterContainer::getCluster(), RawTowerContainer::getTower(), Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, index, PHWHERE, and Jet::TRACK.
Referenced by all_truth_jets().
std::set< PHG4Shower * > JetRecoEval::all_truth_showers (Jet * recojet)
what truth showers contributed to this reconstructed jet?
Definition at line 101 of file JetRecoEval.cc.
References _cache_all_truth_showers, _cemcclusters, _cemctowers, _do_cache, _errors, _femcclusters, _femctowers, _fhcalclusters, _fhcaltowers, _hcalinclusters, _hcalintowers, _hcaloutclusters, _hcalouttowers, _strict, _trackmap, CaloRawTowerEval::all_truth_primary_showers(), CaloRawClusterEval::all_truth_primary_showers(), assert, Jet::begin_comp(), Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::end_comp(), Jet::FEMC_CLUSTER, Jet::FEMC_TOWER, Jet::FHCAL_CLUSTER, Jet::FHCAL_TOWER, get_cemc_eval_stack(), get_femc_eval_stack(), get_fhcal_eval_stack(), get_hcalin_eval_stack(), get_hcalout_eval_stack(), CaloEvalStack::get_rawcluster_eval(), CaloEvalStack::get_rawtower_eval(), RawClusterContainer::getCluster(), RawTowerContainer::getTower(), Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, index, PHWHERE, and Jet::TRACK.
Jet * JetRecoEval::best_jet_from (Jet * truthjet)
which reconstructed jet had the largest energy contribution from this truth jet?
Definition at line 850 of file JetRecoEval.cc.
References _cache_best_jet_from, _do_cache, _errors, _strict, all_jets_from(), assert, energy, and get_energy_contribution().
Referenced by JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), BJetModule::process_event(), QAG4SimulationJet::process_TruthMatching(), unique_reco_jet_from_truth(), and unique_truth_jet_from_reco().
void JetRecoEval::do_caching (bool do_cache) inline
activate or deactivate the memory caching inside the evaluation module
Definition at line 43 of file JetRecoEval.h.
References _do_cache, _jettrutheval, and JetTruthEval::do_caching().
Referenced by JetEvalStack::do_caching().
CaloEvalStack* JetRecoEval::get_cemc_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 74 of file JetRecoEval.h.
References _jettrutheval, and JetTruthEval::get_cemc_eval_stack().
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), JetEvalStack::get_cemc_eval_stack(), and get_energy_contribution().
float JetRecoEval::get_energy_contribution (Jet * recojet, Jet * truthjet)
what was the energy contribution to this reconstructed jet from this truth jet?
Definition at line 960 of file JetRecoEval.cc.
References _cache_get_energy_contribution, _cemcclusters, _cemctowers, _do_cache, _errors, _femcclusters, _femctowers, _fhcalclusters, _fhcaltowers, _hcalinclusters, _hcalintowers, _hcaloutclusters, _hcalouttowers, _strict, _trackmap, JetTruthEval::all_truth_particles(), assert, Jet::begin_comp(), Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, Jet::end_comp(), energy, Jet::FEMC_CLUSTER, Jet::FEMC_TOWER, Jet::FHCAL_CLUSTER, Jet::FHCAL_TOWER, SvtxTrackMap::get(), get_cemc_eval_stack(), CaloRawTowerEval::get_energy_contribution(), CaloRawClusterEval::get_energy_contribution(), get_femc_eval_stack(), get_fhcal_eval_stack(), get_hcalin_eval_stack(), get_hcalout_eval_stack(), SvtxTrack::get_p(), CaloEvalStack::get_rawcluster_eval(), CaloEvalStack::get_rawtower_eval(), get_svtx_eval_stack(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), get_truth_eval(), RawClusterContainer::getCluster(), RawTowerContainer::getTower(), Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, index, SvtxTrackEval::max_truth_particle_by_nclusters(), and Jet::TRACK.
Referenced by best_jet_from(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), max_truth_jet_by_energy(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
float JetRecoEval::get_energy_contribution (Jet * recojet, Jet::SRC src)
what was the energy contribution to this reconstructed jet from a particular source
Definition at line 1216 of file JetRecoEval.cc.
References _cache_get_energy_contribution_src, _cemcclusters, _cemctowers, _do_cache, _errors, _femcclusters, _femctowers, _fhcalclusters, _fhcaltowers, _hcalinclusters, _hcalintowers, _hcaloutclusters, _hcalouttowers, _strict, _trackmap, assert, Jet::CEMC_CLUSTER, Jet::CEMC_TOWER, energy, Jet::FEMC_CLUSTER, Jet::FEMC_TOWER, Jet::FHCAL_CLUSTER, Jet::FHCAL_TOWER, SvtxTrackMap::get(), RawCluster::get_energy(), RawTower::get_energy(), SvtxTrack::get_p(), RawClusterContainer::getCluster(), RawTowerContainer::getTower(), Jet::HCALIN_CLUSTER, Jet::HCALIN_TOWER, Jet::HCALOUT_CLUSTER, Jet::HCALOUT_TOWER, index, Jet::lower_bound_comp(), Jet::TRACK, and Jet::upper_bound_comp().
unsigned int JetRecoEval::get_errors () inline
get a count of the errors discovered thus far
Definition at line 58 of file JetRecoEval.h.
References _errors, _jettrutheval, and JetTruthEval::get_errors().
CaloEvalStack* JetRecoEval::get_femc_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 83 of file JetRecoEval.h.
References _jettrutheval, and JetTruthEval::get_femc_eval_stack().
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and JetEvalStack::get_femc_eval_stack().
CaloEvalStack* JetRecoEval::get_fhcal_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 86 of file JetRecoEval.h.
References _jettrutheval, and JetTruthEval::get_fhcal_eval_stack().
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and JetEvalStack::get_fhcal_eval_stack().
CaloEvalStack* JetRecoEval::get_hcalin_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 77 of file JetRecoEval.h.
References _jettrutheval, and JetTruthEval::get_hcalin_eval_stack().
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and JetEvalStack::get_hcalin_eval_stack().
CaloEvalStack* JetRecoEval::get_hcalout_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 80 of file JetRecoEval.h.
References _jettrutheval, and JetTruthEval::get_hcalout_eval_stack().
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and JetEvalStack::get_hcalout_eval_stack().
void JetRecoEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 1714 of file JetRecoEval.cc.
References _cemcclusters, _cemctowers, _femcclusters, _femctowers, _fhcalclusters, _fhcaltowers, _hcalinclusters, _hcalintowers, _hcaloutclusters, _hcalouttowers, _recojetname, _recojets, _trackmap, _truthjetname, _truthjets, and PHWHERE.
Referenced by JetRecoEval(), and next_event().
SvtxEvalStack* JetRecoEval::get_svtx_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 71 of file JetRecoEval.h.
References _jettrutheval, and JetTruthEval::get_svtx_eval_stack().
Referenced by all_truth_hits(), all_truth_particles(), get_energy_contribution(), and JetEvalStack::get_stvx_eval_stack().
JetTruthEval* JetRecoEval::get_truth_eval () inline
get a copy of the lower level eval and its memory cache
Definition at line 68 of file JetRecoEval.h.
References _jettrutheval.
Referenced by get_energy_contribution(), and JetEvalStack::get_truth_eval().
Jet * JetRecoEval::max_truth_jet_by_energy (Jet * recojet)
which truth jet contributed the most energy to this reconstructed jet?
Definition at line 734 of file JetRecoEval.cc.
References _cache_max_truth_jet_by_energy, _do_cache, _errors, _strict, all_truth_jets(), assert, energy, and get_energy_contribution().
Referenced by JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::process_event(), MyJetAnalysis::process_event(), QAG4SimulationJet::process_TruthMatching(), unique_reco_jet_from_truth(), and unique_truth_jet_from_reco().
void JetRecoEval::next_event (PHCompositeNode * topNode)
reinitialize the eval for a new event
Definition at line 84 of file JetRecoEval.cc.
References _cache_all_jets_from, _cache_all_truth_hits, _cache_all_truth_jets, _cache_all_truth_particles, _cache_all_truth_showers, _cache_best_jet_from, _cache_get_energy_contribution, _cache_get_energy_contribution_src, _cache_max_truth_jet_by_energy, _jettrutheval, get_node_pointers(), and JetTruthEval::next_event().
Referenced by JetEvalStack::next_event().
void JetRecoEval::set_strict (bool strict) inline
strict mode will assert when an error is detected non-strict mode will notice and report at the End()
Definition at line 51 of file JetRecoEval.h.
References _jettrutheval, _strict, and JetTruthEval::set_strict().
Referenced by JetEvalStack::set_strict().
void JetRecoEval::set_verbosity (int verbosity) inline
adjust the messaging from the evalutaion module
Definition at line 61 of file JetRecoEval.h.
References _jettrutheval, _verbosity, JetTruthEval::set_verbosity(), and verbosity.
Referenced by JetEvalStack::set_verbosity().
Jet * JetRecoEval::unique_reco_jet_from_truth (Jet * truthjet)
which reconstructed jet had the largest energy contribution from this truth jet in a unique match?
Returns
pointer to reco jet. And NULL if no unique match
Definition at line 905 of file JetRecoEval.cc.
References _errors, _strict, assert, best_jet_from(), Jet::get_id(), and max_truth_jet_by_energy().
Referenced by QAG4SimulationJet::process_TruthMatching().
Jet * JetRecoEval::unique_truth_jet_from_reco (Jet * recojet)
which truth jet had the largest energy contribution from this reco jet in a unique match?
Returns
pointer to truth jet. And NULL if no unique match
Definition at line 932 of file JetRecoEval.cc.
References _errors, _strict, assert, best_jet_from(), Jet::get_id(), and max_truth_jet_by_energy().
Referenced by QAG4SimulationJet::process_TruthMatching().
Member Data Documentation
std::map<Jet*, std::set<Jet*> > JetRecoEval::_cache_all_jets_from private
Definition at line 158 of file JetRecoEval.h.
Referenced by all_jets_from(), and next_event().
std::map<Jet*, std::set<PHG4Hit*> > JetRecoEval::_cache_all_truth_hits private
used in get_energy_contribution (Jet* recojet, Jet::SRC src);
Definition at line 162 of file JetRecoEval.h.
Referenced by all_truth_hits(), and next_event().
std::map<Jet*, std::set<Jet*> > JetRecoEval::_cache_all_truth_jets private
Definition at line 156 of file JetRecoEval.h.
Referenced by all_truth_jets(), and next_event().
std::map<Jet*, std::set<PHG4Particle*> > JetRecoEval::_cache_all_truth_particles private
Definition at line 155 of file JetRecoEval.h.
Referenced by all_truth_particles(), and next_event().
std::map<Jet*, std::set<PHG4Shower*> > JetRecoEval::_cache_all_truth_showers private
Definition at line 154 of file JetRecoEval.h.
Referenced by all_truth_showers(), and next_event().
std::map<Jet*, Jet*> JetRecoEval::_cache_best_jet_from private
Definition at line 159 of file JetRecoEval.h.
Referenced by best_jet_from(), and next_event().
std::map<std::pair<Jet*, Jet*>, float> JetRecoEval::_cache_get_energy_contribution private
Definition at line 160 of file JetRecoEval.h.
Referenced by get_energy_contribution(), and next_event().
std::map<std::pair<Jet*, Jet::SRC>, float> JetRecoEval::_cache_get_energy_contribution_src private
Definition at line 161 of file JetRecoEval.h.
Referenced by get_energy_contribution(), and next_event().
std::map<Jet*, Jet*> JetRecoEval::_cache_max_truth_jet_by_energy private
Definition at line 157 of file JetRecoEval.h.
Referenced by max_truth_jet_by_energy(), and next_event().
RawClusterContainer* JetRecoEval::_cemcclusters private
Definition at line 139 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawTowerContainer* JetRecoEval::_cemctowers private
Definition at line 138 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
bool JetRecoEval::_do_cache private
Definition at line 153 of file JetRecoEval.h.
Referenced by all_jets_from(), all_truth_hits(), all_truth_jets(), all_truth_particles(), all_truth_showers(), best_jet_from(), do_caching(), get_energy_contribution(), and max_truth_jet_by_energy().
unsigned int JetRecoEval::_errors private
Definition at line 151 of file JetRecoEval.h.
Referenced by all_jets_from(), all_truth_hits(), all_truth_jets(), all_truth_particles(), all_truth_showers(), best_jet_from(), get_energy_contribution(), get_errors(), max_truth_jet_by_energy(), unique_reco_jet_from_truth(), unique_truth_jet_from_reco(), and ~JetRecoEval().
RawClusterContainer* JetRecoEval::_femcclusters private
Definition at line 145 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawTowerContainer* JetRecoEval::_femctowers private
Definition at line 144 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawClusterContainer* JetRecoEval::_fhcalclusters private
Definition at line 147 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawTowerContainer* JetRecoEval::_fhcaltowers private
Definition at line 146 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawClusterContainer* JetRecoEval::_hcalinclusters private
Definition at line 141 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawTowerContainer* JetRecoEval::_hcalintowers private
Definition at line 140 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawClusterContainer* JetRecoEval::_hcaloutclusters private
Definition at line 143 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
RawTowerContainer* JetRecoEval::_hcalouttowers private
Definition at line 142 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
JetTruthEval JetRecoEval::_jettrutheval private
Definition at line 130 of file JetRecoEval.h.
Referenced by all_truth_jets(), do_caching(), get_cemc_eval_stack(), get_errors(), get_femc_eval_stack(), get_fhcal_eval_stack(), get_hcalin_eval_stack(), get_hcalout_eval_stack(), get_svtx_eval_stack(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
std::string JetRecoEval::_recojetname private
Definition at line 131 of file JetRecoEval.h.
Referenced by get_node_pointers().
JetMap* JetRecoEval::_recojets private
Definition at line 134 of file JetRecoEval.h.
Referenced by all_jets_from(), and get_node_pointers().
bool JetRecoEval::_strict private
Definition at line 149 of file JetRecoEval.h.
Referenced by all_jets_from(), all_truth_hits(), all_truth_jets(), all_truth_particles(), all_truth_showers(), best_jet_from(), get_energy_contribution(), max_truth_jet_by_energy(), set_strict(), unique_reco_jet_from_truth(), and unique_truth_jet_from_reco().
SvtxTrackMap* JetRecoEval::_trackmap private
Definition at line 137 of file JetRecoEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_energy_contribution(), and get_node_pointers().
std::string JetRecoEval::_truthjetname private
Definition at line 132 of file JetRecoEval.h.
Referenced by get_node_pointers().
JetMap* JetRecoEval::_truthjets private
Definition at line 135 of file JetRecoEval.h.
Referenced by get_node_pointers().
int JetRecoEval::_verbosity private
Definition at line 150 of file JetRecoEval.h.
Referenced by set_verbosity(), and ~JetRecoEval().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/JetRecoEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/JetRecoEval.cc