Analysis Software: TpcPrototypeGenFitTrkFitter Class Reference
TpcPrototypeGenFitTrkFitter Class Reference
Refit SvtxTracks with PHGenFit.
#include <prototype/blob/master/offline/packages/tpc2019/TpcPrototypeGenFitTrkFitter.h>
Public Types
enum OutPutMode { MakeNewNode, OverwriteOriginalNode, DebugMode }
enum DetectorType {
MIE, MAPS_TPC, MAPS_IT_TPC, LADDER_MAPS_TPC,
LADDER_MAPS_IT_TPC, LADDER_MAPS_LADDER_IT_TPC, MAPS_LADDER_IT_TPC
}
enum Flag { NONE = 0 }
Public Member Functions
TpcPrototypeGenFitTrkFitter (const std::string &name="TpcPrototypeGenFitTrkFitter")
Default constructor.
~TpcPrototypeGenFitTrkFitter ()
dtor
int Init (PHCompositeNode *)
Initialization, called for initialization.
int InitRun (PHCompositeNode *)
Initialization Run, called for initialization of a run.
int process_event (PHCompositeNode *)
Process Event, called for each event.
int End (PHCompositeNode *)
End, write and close files.
void set_flag (const Flag &flag, const bool &value)
void set_eval_filename (const std::string &file)
std::string get_eval_filename () const
void fill_eval_tree (PHCompositeNode *)
void init_eval_tree ()
void reset_eval_variables ()
bool is_do_eval () const
void set_do_eval (bool doEval)
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
const std::string & get_vertexing_method () const
void set_vertexing_method (const std::string &vertexingMethod)
bool is_fit_primary_tracks () const
void set_fit_primary_tracks (bool fitPrimaryTracks)
OutPutMode get_output_mode () const
void set_output_mode (OutPutMode outputMode)
const std::string & get_track_fitting_alg_name () const
void set_track_fitting_alg_name (const std::string &trackFittingAlgName)
int get_primary_pid_guess () const
void set_primary_pid_guess (int primaryPidGuess)
double get_fit_min_pT () const
void set_fit_min_pT (double cutMinPT)
bool is_over_write_svtxtrackmap () const
void set_over_write_svtxtrackmap (bool overWriteSvtxtrackmap)
bool is_over_write_svtxvertexmap () const
void set_over_write_svtxvertexmap (bool overWriteSvtxvertexmap)
bool is_use_truth_vertex () const
void set_use_truth_vertex (bool useTruthVertex)
double get_vertex_min_ndf () const
void set_vertex_min_ndf (double vertexMinPT)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *)
Get all the nodes.
int CreateNodes (PHCompositeNode *)
Create New nodes.
std::shared_ptr< PHGenFit::Track > ReFitTrack (PHCompositeNode *, const SvtxTrack *intrack, const SvtxVertex *invertex=NULL)
std::shared_ptr< PHGenFit::Track > DisplayCluster (const TrkrCluster *cluster)
std::shared_ptr< SvtxTrack > MakeSvtxTrack (const SvtxTrack *svtxtrack, const std::shared_ptr< PHGenFit::Track > &genfit_track, const SvtxVertex *vertex=NULL)
Make SvtxTrack from PHGenFit::Track and SvtxTrack.
std::shared_ptr
< TpcPrototypeTrack > MakeTpcPrototypeTrack (const SvtxTrack *svtxtrack)
Make TpcPrototypeTrack from SvtxTrack, refit by "excluding" each cluster.
bool FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const std::vector< genfit::Track * > &gf_tracks)
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
bool pos_cov_uvn_to_rz (const TVector3 &u, const TVector3 &v, const TVector3 &n, const TMatrixF &pos_in, const TMatrixF &cov_in, TMatrixF &pos_out, TMatrixF &cov_out) const
bool get_vertex_error_uvn (const TVector3 &u, const TVector3 &v, const TVector3 &n, const TMatrixF &cov_in, TMatrixF &cov_out) const
bool pos_cov_XYZ_to_RZ (const TVector3 &n, const TMatrixF &pos_in, const TMatrixF &cov_in, TMatrixF &pos_out, TMatrixF &cov_out) const
TMatrixF get_rotation_matrix (const TVector3 x, const TVector3 y, const TVector3 z, const TVector3 xp=TVector3(1., 0., 0.), const TVector3 yp=TVector3(0., 1., 0.), const TVector3 zp=TVector3(0., 0., 1.)) const
Private Attributes
int _event
Event counter.
unsigned int _flags
flags
OutPutMode _output_mode
bool _over_write_svtxtrackmap
bool _over_write_svtxvertexmap
bool _fit_primary_tracks
bool _use_truth_vertex
PHGenFit::Fitter * _fitter
std::string _track_fitting_alg_name
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
int _primary_pid_guess
double _fit_min_pT
double _vertex_min_ndf
genfit::GFRaveVertexFactory * _vertex_finder
std::string _vertexing_method
https://rave.hepforge.org/trac/wiki/RaveMethods
TrkrClusterContainer * _clustermap
Input Node pointers.
SvtxTrackMap * _trackmap
SvtxVertexMap * _vertexmap
SvtxTrackMap * _trackmap_refit
Output Node pointers.
SvtxTrackMap * _primary_trackmap
SvtxVertexMap * _vertexmap_refit
bool _do_eval
std::string _eval_outname
eval output filename
TTree * _eval_tree
int _tca_ntrack
TClonesArray * _tca_particlemap
TClonesArray * _tca_vtxmap
TClonesArray * _tca_trackmap
TClonesArray * _tca_tpctrackmap
TClonesArray * _tca_vertexmap
TClonesArray * _tca_trackmap_refit
TClonesArray * _tca_primtrackmap
TClonesArray * _tca_vertexmap_refit
TTree * _cluster_eval_tree
float _cluster_eval_tree_x
float _cluster_eval_tree_y
float _cluster_eval_tree_z
float _cluster_eval_tree_gx
float _cluster_eval_tree_gy
float _cluster_eval_tree_gz
bool _do_evt_display
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Refit SvtxTracks with PHGenFit.
Definition at line 52 of file TpcPrototypeGenFitTrkFitter.h.
Member Enumeration Documentation
enum TpcPrototypeGenFitTrkFitter::DetectorType
Enumerator:
MIE
MAPS_TPC
MAPS_IT_TPC
LADDER_MAPS_TPC
LADDER_MAPS_IT_TPC
LADDER_MAPS_LADDER_IT_TPC
MAPS_LADDER_IT_TPC
Definition at line 67 of file TpcPrototypeGenFitTrkFitter.h.
enum TpcPrototypeGenFitTrkFitter::Flag
Enumerator:
NONE
Definition at line 97 of file TpcPrototypeGenFitTrkFitter.h.
enum TpcPrototypeGenFitTrkFitter::OutPutMode
OverwriteOriginalNode: default mode, overwrite original node MakeNewNode: Output extra new refit nodes DebugMode: overwrite original node also make extra new refit nodes
Enumerator:
MakeNewNode
OverwriteOriginalNode
DebugMode
Definition at line 60 of file TpcPrototypeGenFitTrkFitter.h.
Constructor & Destructor Documentation
TpcPrototypeGenFitTrkFitter::TpcPrototypeGenFitTrkFitter (const std::string & name = "TpcPrototypeGenFitTrkFitter")
Default constructor.
Definition at line 185 of file TpcPrototypeGenFitTrkFitter.cc.
References _cluster_eval_tree, _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _event, Fun4AllBase::Verbosity(), and WILD_FLOAT.
TpcPrototypeGenFitTrkFitter::~TpcPrototypeGenFitTrkFitter ()
dtor
Definition at line 531 of file TpcPrototypeGenFitTrkFitter.cc.
References _fitter, and _vertex_finder.
Member Function Documentation
int TpcPrototypeGenFitTrkFitter::CreateNodes (PHCompositeNode * topNode) private
Create New nodes.
Definition at line 672 of file TpcPrototypeGenFitTrkFitter.cc.
References _fit_primary_tracks, _output_mode, _over_write_svtxtrackmap, _over_write_svtxvertexmap, _primary_trackmap, _trackmap_refit, _vertexmap, _vertexmap_refit, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), DebugMode, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
std::shared_ptr< PHGenFit::Track > TpcPrototypeGenFitTrkFitter::DisplayCluster (const TrkrCluster * cluster) private
mu+: -13 mu-: 13 pi+: 211 pi-: -211 e-: 11 e+: -11
Fit the track ret code 0 means 0 error or good status
Definition at line 827 of file TpcPrototypeGenFitTrkFitter.cc.
References _fitter, assert, TrkrCluster::getClusKey(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), TrkrCluster::getRPhiError(), TrkrCluster::getZError(), i, TrkrCluster::identify(), j, LogWarning, n, pos, PHGenFit::Fitter::processTrack(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int TpcPrototypeGenFitTrkFitter::End (PHCompositeNode * topNode) virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 496 of file TpcPrototypeGenFitTrkFitter.cc.
References _cluster_eval_tree, _do_eval, _do_evt_display, _eval_outname, _eval_tree, _fitter, PHTFileServer::cd(), PHGenFit::Fitter::displayEvent(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHGenFit::Fitter::getEventDisplay(), PHWHERE, and Fun4AllBase::Verbosity().
void TpcPrototypeGenFitTrkFitter::fill_eval_tree (PHCompositeNode * topNode)
Make sure to reset all the TTree variables before trying to set them.
Definition at line 540 of file TpcPrototypeGenFitTrkFitter.cc.
References _eval_tree, _fit_primary_tracks, _primary_trackmap, _tca_ntrack, _tca_primtrackmap, _tca_trackmap_refit, _tca_vertexmap, _tca_vertexmap_refit, _trackmap, _trackmap_refit, _vertexmap, _vertexmap_refit, SvtxTrackMap::begin(), SvtxVertexMap::begin(), SvtxTrackMap::end(), SvtxVertexMap::end(), i, MakeTpcPrototypeTrack(), and reset_eval_variables().
Referenced by process_event().
bool TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const std::vector< genfit::Track * > & gf_tracks) private
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
Definition at line 1603 of file TpcPrototypeGenFitTrkFitter.cc.
References _over_write_svtxvertexmap, _vertexmap, _vertexmap_refit, SvtxVertexMap::clear(), i, SvtxVertexMap::insert_clone(), j, LogError, and PHWHERE.
std::string TpcPrototypeGenFitTrkFitter::get_eval_filename () const inline
Definition at line 119 of file TpcPrototypeGenFitTrkFitter.h.
References _eval_outname.
double TpcPrototypeGenFitTrkFitter::get_fit_min_pT () const inline
Definition at line 201 of file TpcPrototypeGenFitTrkFitter.h.
References _fit_min_pT.
OutPutMode TpcPrototypeGenFitTrkFitter::get_output_mode () const inline
Definition at line 168 of file TpcPrototypeGenFitTrkFitter.h.
References _output_mode.
int TpcPrototypeGenFitTrkFitter::get_primary_pid_guess () const inline
Definition at line 191 of file TpcPrototypeGenFitTrkFitter.h.
References _primary_pid_guess.
TMatrixF TpcPrototypeGenFitTrkFitter::get_rotation_matrix (const TVector3 x, const TVector3 y, const TVector3 z, const TVector3 xp = TVector3(1., 0., 0.), const TVector3 yp = TVector3(0., 1., 0.), const TVector3 zp = TVector3(0., 0., 1.)) const private
Get 3D Rotation Matrix that rotates frame (x,y,z) to (x',y',z') Default rotate local to global, or rotate vector in global to local representation
Decompose x',y',z' in x,y,z and call them u,v,n Then the question will be rotate the standard X,Y,Z to u,v,n
Rotation that rotate standard (X, Y, Z) to (u, v, n)
Definition at line 1856 of file TpcPrototypeGenFitTrkFitter.cc.
References LogWarning, n, v, and Fun4AllBase::Verbosity().
Referenced by get_vertex_error_uvn().
const std::string& TpcPrototypeGenFitTrkFitter::get_track_fitting_alg_name () const inline
Definition at line 181 of file TpcPrototypeGenFitTrkFitter.h.
References _track_fitting_alg_name.
bool TpcPrototypeGenFitTrkFitter::get_vertex_error_uvn (const TVector3 & u, const TVector3 & v, const TVector3 & n, const TMatrixF & cov_in, TMatrixF & cov_out) const private
Get matrix that rotates frame (u,v,n) to (x,y,z) or the matrix that rotates vector defined in (x,y,z) to defined (u,v,n)
Definition at line 1743 of file TpcPrototypeGenFitTrkFitter.cc.
References get_rotation_matrix(), LogWarning, and Fun4AllBase::Verbosity().
double TpcPrototypeGenFitTrkFitter::get_vertex_min_ndf () const inline
Definition at line 241 of file TpcPrototypeGenFitTrkFitter.h.
References _vertex_min_ndf.
const std::string& TpcPrototypeGenFitTrkFitter::get_vertexing_method () const inline
Definition at line 148 of file TpcPrototypeGenFitTrkFitter.h.
References _vertexing_method.
int TpcPrototypeGenFitTrkFitter::GetNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 744 of file TpcPrototypeGenFitTrkFitter.cc.
References _clustermap, _event, _fit_primary_tracks, _output_mode, _over_write_svtxtrackmap, _over_write_svtxvertexmap, _primary_trackmap, _trackmap, _trackmap_refit, _vertexmap, _vertexmap_refit, Fun4AllReturnCodes::ABORTEVENT, DebugMode, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
int TpcPrototypeGenFitTrkFitter::Init (PHCompositeNode * topNode) virtual
Initialization, called for initialization.
Reimplemented from SubsysReco.
Definition at line 237 of file TpcPrototypeGenFitTrkFitter.cc.
References Fun4AllReturnCodes::EVENT_OK.
void TpcPrototypeGenFitTrkFitter::init_eval_tree ()
create TTree
Definition at line 600 of file TpcPrototypeGenFitTrkFitter.cc.
References _cluster_eval_tree, _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _eval_tree, _fit_primary_tracks, _tca_ntrack, _tca_particlemap, _tca_primtrackmap, _tca_tpctrackmap, _tca_trackmap, _tca_trackmap_refit, _tca_vertexmap, _tca_vertexmap_refit, and _tca_vtxmap.
Referenced by InitRun().
int TpcPrototypeGenFitTrkFitter::InitRun (PHCompositeNode * topNode) virtual
Initialization Run, called for initialization of a run.
Reimplemented from SubsysReco.
Definition at line 247 of file TpcPrototypeGenFitTrkFitter.cc.
References _do_eval, _do_evt_display, _eval_outname, _fitter, _track_fitting_alg_name, _vertex_finder, _vertexing_method, Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), init_eval_tree(), PHTFileServer::open(), PHWHERE, PHGenFit::Fitter::set_verbosity(), and Fun4AllBase::Verbosity().
bool TpcPrototypeGenFitTrkFitter::is_do_eval () const inline
Definition at line 128 of file TpcPrototypeGenFitTrkFitter.h.
References _do_eval.
bool TpcPrototypeGenFitTrkFitter::is_do_evt_display () const inline
Definition at line 138 of file TpcPrototypeGenFitTrkFitter.h.
References _do_evt_display.
bool TpcPrototypeGenFitTrkFitter::is_fit_primary_tracks () const inline
Definition at line 158 of file TpcPrototypeGenFitTrkFitter.h.
References _fit_primary_tracks.
bool TpcPrototypeGenFitTrkFitter::is_over_write_svtxtrackmap () const inline
Definition at line 211 of file TpcPrototypeGenFitTrkFitter.h.
References _over_write_svtxtrackmap.
bool TpcPrototypeGenFitTrkFitter::is_over_write_svtxvertexmap () const inline
Definition at line 221 of file TpcPrototypeGenFitTrkFitter.h.
References _over_write_svtxvertexmap.
bool TpcPrototypeGenFitTrkFitter::is_use_truth_vertex () const inline
Definition at line 231 of file TpcPrototypeGenFitTrkFitter.h.
References _use_truth_vertex.
std::shared_ptr< SvtxTrack > TpcPrototypeGenFitTrkFitter::MakeSvtxTrack (const SvtxTrack * svtxtrack, const std::shared_ptr< PHGenFit::Track > & genfit_track, const SvtxVertex * vertex = NULL) private
Make SvtxTrack from PHGenFit::Track and SvtxTrack.
1/p, u'/z', v'/z', u, v u is defined as momentum X beam line at POCA of the beam line v is alone the beam line so u is the dca2d direction
Definition at line 1345 of file TpcPrototypeGenFitTrkFitter.cc.
References i, j, LogWarning, pos, pos_cov_XYZ_to_RZ(), v, and Fun4AllBase::Verbosity().
Referenced by process_event().
shared_ptr< TpcPrototypeTrack > TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack (const SvtxTrack * svtxtrack) private
Make TpcPrototypeTrack from SvtxTrack, refit by "excluding" each cluster.
Definition at line 1135 of file TpcPrototypeGenFitTrkFitter.cc.
References _clustermap, _fitter, _primary_pid_guess, assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), SvtxTrack::get_chisq(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), TrkrDefs::getLayer(), i, TrkrCluster::identify(), SvtxTrack::identify(), j, LogWarning, n, pos, PHGenFit::Fitter::processTrack(), and Fun4AllBase::Verbosity().
Referenced by fill_eval_tree().
bool TpcPrototypeGenFitTrkFitter::pos_cov_uvn_to_rz (const TVector3 & u, const TVector3 & v, const TVector3 & n, const TMatrixF & pos_in, const TMatrixF & cov_in, TMatrixF & pos_out, TMatrixF & cov_out) const private
Definition at line 1681 of file TpcPrototypeGenFitTrkFitter.cc.
References LogWarning, phi, and Fun4AllBase::Verbosity().
bool TpcPrototypeGenFitTrkFitter::pos_cov_XYZ_to_RZ (const TVector3 & n, const TMatrixF & pos_in, const TMatrixF & cov_in, TMatrixF & pos_out, TMatrixF & cov_out) const private
Definition at line 1790 of file TpcPrototypeGenFitTrkFitter.cc.
References LogWarning, phi, r, and Fun4AllBase::Verbosity().
Referenced by MakeSvtxTrack().
int TpcPrototypeGenFitTrkFitter::process_event (PHCompositeNode * topNode) virtual
Process Event, called for each event.
stands for Refit_GenFit_Tracks
stands for Refit_PHGenFit_Track
Reimplemented from SubsysReco.
Definition at line 298 of file TpcPrototypeGenFitTrkFitter.cc.
References _clustermap, _do_eval, _do_evt_display, _event, _fit_min_pT, _fitter, _output_mode, _over_write_svtxtrackmap, _over_write_svtxvertexmap, _trackmap, _trackmap_refit, _vertex_min_ndf, _vertexmap, _vertexmap_refit, assert, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), DebugMode, DisplayCluster(), SvtxTrackMap::empty(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), SvtxTrackMap::erase(), Fun4AllReturnCodes::EVENT_OK, fill_eval_tree(), TrkrClusterContainer::findCluster(), SvtxVertexMap::get(), SvtxTrack::get_id(), SvtxTrack::get_pt(), TrkrClusterContainer::getClusters(), PHGenFit::Fitter::getEventDisplay(), GetNodes(), SvtxTrack::identify(), SvtxTrackMap::insert(), MakeSvtxTrack(), PHWHERE, ReFitTrack(), SvtxVertexMap::size(), t, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
std::shared_ptr< PHGenFit::Track > TpcPrototypeGenFitTrkFitter::ReFitTrack (PHCompositeNode * topNode, const SvtxTrack * intrack, const SvtxVertex * invertex = NULL) private
1000 is a arbitrary number for now
mu+: -13 mu-: 13 pi+: 211 pi-: -211 e-: 11 e+: -11
Fit the track ret code 0 means 0 error or good status
Definition at line 958 of file TpcPrototypeGenFitTrkFitter.cc.
References _clustermap, _fitter, _primary_pid_guess, assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), SvtxVertex::get_chisq(), SvtxVertex::get_error(), SvtxVertex::get_ndof(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), TrkrDefs::getLayer(), PHGenFit::Measurement::getMeasurement(), TrkrCluster::getPosition(), TrkrCluster::getRPhiError(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), i, SvtxTrack::identify(), TrkrDefs::inttId, j, LogError, LogWarning, TrkrDefs::mvtxId, n, PHWHERE, pos, PHGenFit::Fitter::processTrack(), r, SvtxVertex::size_tracks(), Fun4AllBase::Verbosity(), x, and y.
Referenced by process_event().
void TpcPrototypeGenFitTrkFitter::reset_eval_variables ()
Definition at line 650 of file TpcPrototypeGenFitTrkFitter.cc.
References _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _fit_primary_tracks, _tca_ntrack, _tca_particlemap, _tca_primtrackmap, _tca_tpctrackmap, _tca_trackmap, _tca_trackmap_refit, _tca_vertexmap, _tca_vertexmap_refit, _tca_vtxmap, and WILD_FLOAT.
Referenced by fill_eval_tree().
void TpcPrototypeGenFitTrkFitter::set_do_eval (bool doEval) inline
Definition at line 133 of file TpcPrototypeGenFitTrkFitter.h.
References _do_eval.
Referenced by Fun4All_G4_TPC(), and Fun4All_TestBeam_TPC().
void TpcPrototypeGenFitTrkFitter::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 143 of file TpcPrototypeGenFitTrkFitter.h.
References _do_evt_display.
Referenced by Fun4All_G4_TPC(), and Fun4All_TestBeam_TPC().
void TpcPrototypeGenFitTrkFitter::set_eval_filename (const std::string & file) inline
For evalution Change eval output filename
Definition at line 115 of file TpcPrototypeGenFitTrkFitter.h.
References _eval_outname, and file.
Referenced by Fun4All_TestBeam_TPC().
void TpcPrototypeGenFitTrkFitter::set_fit_min_pT (double cutMinPT) inline
Definition at line 206 of file TpcPrototypeGenFitTrkFitter.h.
References _fit_min_pT.
void TpcPrototypeGenFitTrkFitter::set_fit_primary_tracks (bool fitPrimaryTracks) inline
Definition at line 163 of file TpcPrototypeGenFitTrkFitter.h.
References _fit_primary_tracks.
void TpcPrototypeGenFitTrkFitter::set_flag (const Flag & flag, const bool & value) inline
Definition at line 105 of file TpcPrototypeGenFitTrkFitter.h.
References _flags.
void TpcPrototypeGenFitTrkFitter::set_output_mode (OutPutMode outputMode) inline
set output mode, default is OverwriteOriginalNode
Definition at line 176 of file TpcPrototypeGenFitTrkFitter.h.
References _output_mode.
void TpcPrototypeGenFitTrkFitter::set_over_write_svtxtrackmap (bool overWriteSvtxtrackmap) inline
Definition at line 216 of file TpcPrototypeGenFitTrkFitter.h.
References _over_write_svtxtrackmap.
void TpcPrototypeGenFitTrkFitter::set_over_write_svtxvertexmap (bool overWriteSvtxvertexmap) inline
Definition at line 226 of file TpcPrototypeGenFitTrkFitter.h.
References _over_write_svtxvertexmap.
void TpcPrototypeGenFitTrkFitter::set_primary_pid_guess (int primaryPidGuess) inline
Definition at line 196 of file TpcPrototypeGenFitTrkFitter.h.
References _primary_pid_guess.
void TpcPrototypeGenFitTrkFitter::set_track_fitting_alg_name (const std::string & trackFittingAlgName) inline
Definition at line 186 of file TpcPrototypeGenFitTrkFitter.h.
References _track_fitting_alg_name.
void TpcPrototypeGenFitTrkFitter::set_use_truth_vertex (bool useTruthVertex) inline
Definition at line 236 of file TpcPrototypeGenFitTrkFitter.h.
References _use_truth_vertex.
void TpcPrototypeGenFitTrkFitter::set_vertex_min_ndf (double vertexMinPT) inline
Definition at line 246 of file TpcPrototypeGenFitTrkFitter.h.
References _vertex_min_ndf.
void TpcPrototypeGenFitTrkFitter::set_vertexing_method (const std::string & vertexingMethod) inline
Definition at line 153 of file TpcPrototypeGenFitTrkFitter.h.
References _vertexing_method.
Member Data Documentation
TTree* TpcPrototypeGenFitTrkFitter::_cluster_eval_tree private
Definition at line 376 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by End(), init_eval_tree(), and TpcPrototypeGenFitTrkFitter().
float TpcPrototypeGenFitTrkFitter::_cluster_eval_tree_gx private
Definition at line 380 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFitter().
float TpcPrototypeGenFitTrkFitter::_cluster_eval_tree_gy private
Definition at line 381 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFitter().
float TpcPrototypeGenFitTrkFitter::_cluster_eval_tree_gz private
Definition at line 382 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFitter().
float TpcPrototypeGenFitTrkFitter::_cluster_eval_tree_x private
Definition at line 377 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFitter().
float TpcPrototypeGenFitTrkFitter::_cluster_eval_tree_y private
Definition at line 378 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFitter().
float TpcPrototypeGenFitTrkFitter::_cluster_eval_tree_z private
Definition at line 379 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFitter().
TrkrClusterContainer* TpcPrototypeGenFitTrkFitter::_clustermap private
Input Node pointers.
Definition at line 349 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by GetNodes(), MakeTpcPrototypeTrack(), process_event(), and ReFitTrack().
bool TpcPrototypeGenFitTrkFitter::_do_eval private
Evaluation switch eval out
Definition at line 360 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by End(), InitRun(), is_do_eval(), process_event(), and set_do_eval().
bool TpcPrototypeGenFitTrkFitter::_do_evt_display private
Definition at line 384 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by End(), InitRun(), is_do_evt_display(), process_event(), and set_do_evt_display().
std::string TpcPrototypeGenFitTrkFitter::_eval_outname private
eval output filename
Definition at line 363 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by End(), get_eval_filename(), InitRun(), and set_eval_filename().
TTree* TpcPrototypeGenFitTrkFitter::_eval_tree private
Definition at line 365 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by End(), fill_eval_tree(), and init_eval_tree().
int TpcPrototypeGenFitTrkFitter::_event private
Event counter.
Definition at line 253 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by GetNodes(), process_event(), and TpcPrototypeGenFitTrkFitter().
double TpcPrototypeGenFitTrkFitter::_fit_min_pT private
Definition at line 337 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by get_fit_min_pT(), process_event(), and set_fit_min_pT().
bool TpcPrototypeGenFitTrkFitter::_fit_primary_tracks private
Definition at line 326 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), init_eval_tree(), is_fit_primary_tracks(), reset_eval_variables(), and set_fit_primary_tracks().
PHGenFit::Fitter* TpcPrototypeGenFitTrkFitter::_fitter private
Definition at line 331 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by DisplayCluster(), End(), InitRun(), MakeTpcPrototypeTrack(), process_event(), ReFitTrack(), and ~TpcPrototypeGenFitTrkFitter().
unsigned int TpcPrototypeGenFitTrkFitter::_flags private
flags
Definition at line 318 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by set_flag().
OutPutMode TpcPrototypeGenFitTrkFitter::_output_mode private
Definition at line 321 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), get_output_mode(), GetNodes(), process_event(), and set_output_mode().
bool TpcPrototypeGenFitTrkFitter::_over_write_svtxtrackmap private
Definition at line 323 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), GetNodes(), is_over_write_svtxtrackmap(), process_event(), and set_over_write_svtxtrackmap().
bool TpcPrototypeGenFitTrkFitter::_over_write_svtxvertexmap private
Definition at line 324 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), FillSvtxVertexMap(), GetNodes(), is_over_write_svtxvertexmap(), process_event(), and set_over_write_svtxvertexmap().
int TpcPrototypeGenFitTrkFitter::_primary_pid_guess private
Definition at line 336 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by get_primary_pid_guess(), MakeTpcPrototypeTrack(), ReFitTrack(), and set_primary_pid_guess().
SvtxTrackMap* TpcPrototypeGenFitTrkFitter::_primary_trackmap private
Definition at line 355 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), fill_eval_tree(), and GetNodes().
int TpcPrototypeGenFitTrkFitter::_tca_ntrack private
Definition at line 366 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by fill_eval_tree(), init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_particlemap private
Definition at line 367 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_primtrackmap private
Definition at line 373 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by fill_eval_tree(), init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_tpctrackmap private
Definition at line 370 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_trackmap private
Definition at line 369 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_trackmap_refit private
Definition at line 372 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by fill_eval_tree(), init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_vertexmap private
Definition at line 371 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by fill_eval_tree(), init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_vertexmap_refit private
Definition at line 374 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by fill_eval_tree(), init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFitter::_tca_vtxmap private
Definition at line 368 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by init_eval_tree(), and reset_eval_variables().
std::string TpcPrototypeGenFitTrkFitter::_track_fitting_alg_name private
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
Definition at line 334 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by get_track_fitting_alg_name(), InitRun(), and set_track_fitting_alg_name().
SvtxTrackMap* TpcPrototypeGenFitTrkFitter::_trackmap private
Definition at line 350 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by fill_eval_tree(), GetNodes(), and process_event().
SvtxTrackMap* TpcPrototypeGenFitTrkFitter::_trackmap_refit private
Output Node pointers.
Definition at line 354 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), and process_event().
bool TpcPrototypeGenFitTrkFitter::_use_truth_vertex private
Definition at line 329 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by is_use_truth_vertex(), and set_use_truth_vertex().
genfit::GFRaveVertexFactory* TpcPrototypeGenFitTrkFitter::_vertex_finder private
Definition at line 340 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by InitRun(), and ~TpcPrototypeGenFitTrkFitter().
double TpcPrototypeGenFitTrkFitter::_vertex_min_ndf private
Definition at line 338 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by get_vertex_min_ndf(), process_event(), and set_vertex_min_ndf().
std::string TpcPrototypeGenFitTrkFitter::_vertexing_method private
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 343 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by get_vertexing_method(), InitRun(), and set_vertexing_method().
SvtxVertexMap* TpcPrototypeGenFitTrkFitter::_vertexmap private
Definition at line 351 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), fill_eval_tree(), FillSvtxVertexMap(), GetNodes(), and process_event().
SvtxVertexMap* TpcPrototypeGenFitTrkFitter::_vertexmap_refit private
Definition at line 356 of file TpcPrototypeGenFitTrkFitter.h.
Referenced by CreateNodes(), fill_eval_tree(), FillSvtxVertexMap(), GetNodes(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeGenFitTrkFitter.h
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeGenFitTrkFitter.cc