Analysis Software: SvtxTrackEval Class Reference
SvtxTrackEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTrackEval.h>
Public Member Functions
SvtxTrackEval (PHCompositeNode *topNode)
virtual ~SvtxTrackEval ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
SvtxClusterEval * get_cluster_eval ()
SvtxHitEval * get_hit_eval ()
SvtxTruthEval * get_truth_eval ()
std::set< PHG4Hit * > all_truth_hits (SvtxTrack *track)
std::set< PHG4Particle * > all_truth_particles (SvtxTrack *track)
PHG4Particle * max_truth_particle_by_nclusters (SvtxTrack *track)
std::set< SvtxTrack * > all_tracks_from (PHG4Particle *truthparticle)
SvtxTrack * best_track_from (PHG4Particle *truthparticle)
std::set< SvtxTrack * > all_tracks_from (PHG4Hit *truthhit)
std::set< SvtxTrack * > all_tracks_from (TrkrDefs::cluskey cluster_key)
SvtxTrack * best_track_from (TrkrDefs::cluskey cluster_key)
void create_cache_track_from_cluster ()
void calc_cluster_contribution (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_nclusters_contribution (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_layer_range_contribution (SvtxTrack *track, PHG4Particle *particle, unsigned int start_layer, unsigned int end_layer)
unsigned int get_nclusters_contribution_by_layer (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_nwrongclusters_contribution (SvtxTrack *svtxtrack, PHG4Particle *truthparticle)
unsigned int get_errors ()
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
bool has_node_pointers ()
Private Attributes
SvtxClusterEval _clustereval
SvtxTrackMap * _trackmap
bool _strict
int _verbosity
unsigned int _errors
bool _do_cache
bool _cache_track_from_cluster_exists
std::map< SvtxTrack
*, std::set< PHG4Hit * > > _cache_all_truth_hits
std::map< SvtxTrack
*, std::set< PHG4Particle * > > _cache_all_truth_particles
std::map< SvtxTrack
*, PHG4Particle * > _cache_max_truth_particle_by_nclusters
std::map< PHG4Particle
*, std::set< SvtxTrack * > > _cache_all_tracks_from_particle
std::map< PHG4Particle
*, SvtxTrack * > _cache_best_track_from_particle
std::map< PHG4Hit *, std::set
< SvtxTrack * > > _cache_all_tracks_from_g4hit
std::map< TrkrDefs::cluskey,
std::set< SvtxTrack * > > _cache_all_tracks_from_cluster
std::map< TrkrDefs::cluskey,
SvtxTrack * > _cache_best_track_from_cluster
std::map< std::pair< SvtxTrack
*, PHG4Particle * >, unsigned
int > _cache_get_nclusters_contribution
std::map< std::pair< SvtxTrack
*, PHG4Particle * >, unsigned
int > _cache_get_nclusters_contribution_by_layer
std::map< std::pair< SvtxTrack
*, PHG4Particle * >, unsigned
int > _cache_get_nwrongclusters_contribution
Detailed Description
Definition at line 22 of file SvtxTrackEval.h.
Constructor & Destructor Documentation
SvtxTrackEval::SvtxTrackEval (PHCompositeNode * topNode)
Definition at line 22 of file SvtxTrackEval.cc.
References get_node_pointers().
SvtxTrackEval::~SvtxTrackEval () virtual
Definition at line 45 of file SvtxTrackEval.cc.
References _errors, and _verbosity.
Member Function Documentation
std::set< SvtxTrack * > SvtxTrackEval::all_tracks_from (PHG4Particle * truthparticle)
Definition at line 236 of file SvtxTrackEval.cc.
References _cache_all_tracks_from_particle, _clustereval, _do_cache, _errors, _strict, _trackmap, SvtxClusterEval::all_truth_particles(), SvtxTruthEval::are_same_particle(), assert, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), get_truth_eval(), has_node_pointers(), particles, and tracks().
Referenced by best_track_from(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), and SvtxEvaluator::printOutputInfo().
std::set< SvtxTrack * > SvtxTrackEval::all_tracks_from (PHG4Hit * truthhit)
Definition at line 306 of file SvtxTrackEval.cc.
References _cache_all_tracks_from_g4hit, _clustereval, _do_cache, _errors, _strict, _trackmap, SvtxClusterEval::all_truth_hits(), assert, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), PHG4Hit::get_trkid(), has_node_pointers(), and tracks().
std::set< SvtxTrack * > SvtxTrackEval::all_tracks_from (TrkrDefs::cluskey cluster_key)
Definition at line 482 of file SvtxTrackEval.cc.
References _cache_all_tracks_from_cluster, _cache_track_from_cluster_exists, _do_cache, _errors, _trackmap, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), create_cache_track_from_cluster(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), has_node_pointers(), and tracks().
std::set< PHG4Hit * > SvtxTrackEval::all_truth_hits (SvtxTrack * track)
Definition at line 74 of file SvtxTrackEval.cc.
References _cache_all_truth_hits, _clustereval, _do_cache, _errors, _strict, SvtxClusterEval::all_truth_hits(), assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), and has_node_pointers().
Referenced by JetRecoEval::all_truth_hits().
std::set< PHG4Particle * > SvtxTrackEval::all_truth_particles (SvtxTrack * track)
Definition at line 132 of file SvtxTrackEval.cc.
References _cache_all_truth_particles, _clustereval, _do_cache, _errors, _strict, SvtxClusterEval::all_truth_particles(), assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), and has_node_pointers().
Referenced by JetRecoEval::all_truth_particles(), and max_truth_particle_by_nclusters().
SvtxTrack * SvtxTrackEval::best_track_from (PHG4Particle * truthparticle)
Definition at line 381 of file SvtxTrackEval.cc.
References _cache_best_track_from_particle, _do_cache, _errors, _strict, all_tracks_from(), assert, get_nclusters_contribution(), has_node_pointers(), and tracks().
Referenced by EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), Conversion::get_cluster_id(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), STACalorimeterCharacterization::process_event(), SimpleTrackingAnalysis::process_event(), VtxTest::process_event(), TruthConversionEval::process_event(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), and Conversion::setRecoTracks().
SvtxTrack * SvtxTrackEval::best_track_from (TrkrDefs::cluskey cluster_key)
Definition at line 553 of file SvtxTrackEval.cc.
References _cache_best_track_from_cluster, _do_cache, _errors, all_tracks_from(), SvtxTrack::get_quality(), has_node_pointers(), and tracks().
void SvtxTrackEval::calc_cluster_contribution (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 667 of file SvtxTrackEval.cc.
References _cache_get_nclusters_contribution, _cache_get_nwrongclusters_contribution, _clustereval, _errors, _strict, SvtxClusterEval::all_truth_particles(), SvtxTruthEval::are_same_particle(), assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), get_truth_eval(), has_node_pointers(), and particles.
Referenced by get_nclusters_contribution(), and get_nwrongclusters_contribution().
void SvtxTrackEval::create_cache_track_from_cluster ()
Definition at line 430 of file SvtxTrackEval.cc.
References _cache_all_tracks_from_cluster, _cache_track_from_cluster_exists, _errors, _trackmap, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), has_node_pointers(), and tracks().
Referenced by all_tracks_from().
void SvtxTrackEval::do_caching (bool do_cache) inline
Definition at line 29 of file SvtxTrackEval.h.
References _clustereval, _do_cache, and SvtxClusterEval::do_caching().
Referenced by SvtxVertexEval::do_caching().
SvtxClusterEval* SvtxTrackEval::get_cluster_eval () inline
Definition at line 46 of file SvtxTrackEval.h.
References _clustereval.
Referenced by SvtxVertexEval::get_cluster_eval().
unsigned int SvtxTrackEval::get_errors () inline
Definition at line 71 of file SvtxTrackEval.h.
References _clustereval, _errors, and SvtxClusterEval::get_errors().
Referenced by SvtxVertexEval::get_errors().
SvtxHitEval* SvtxTrackEval::get_hit_eval () inline
Definition at line 47 of file SvtxTrackEval.h.
References _clustereval, and SvtxClusterEval::get_hit_eval().
Referenced by SvtxVertexEval::get_hit_eval().
unsigned int SvtxTrackEval::get_layer_range_contribution (SvtxTrack * track, PHG4Particle * particle, unsigned int start_layer, unsigned int end_layer)
Definition at line 811 of file SvtxTrackEval.cc.
References _clustereval, _errors, _strict, SvtxClusterEval::all_truth_particles(), SvtxTruthEval::are_same_particle(), assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), get_truth_eval(), TrkrDefs::getLayer(), has_node_pointers(), i, and particles.
Referenced by SvtxEvaluator::fillOutputNtuples().
unsigned int SvtxTrackEval::get_nclusters_contribution (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 605 of file SvtxTrackEval.cc.
References _cache_get_nclusters_contribution, _errors, _strict, assert, calc_cluster_contribution(), and has_node_pointers().
Referenced by best_track_from(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), max_truth_particle_by_nclusters(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), SimpleTrackingAnalysis::process_event(), and BJetModule::process_event().
unsigned int SvtxTrackEval::get_nclusters_contribution_by_layer (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 738 of file SvtxTrackEval.cc.
References _cache_get_nclusters_contribution_by_layer, _clustereval, _do_cache, _errors, _strict, SvtxClusterEval::all_truth_particles(), SvtxTruthEval::are_same_particle(), assert, SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), get_truth_eval(), TrkrDefs::getLayer(), has_node_pointers(), i, and particles.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxSimPerformanceCheckReco::process_event(), and BJetModule::process_event().
void SvtxTrackEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 880 of file SvtxTrackEval.cc.
References _trackmap.
Referenced by next_event(), and SvtxTrackEval().
unsigned int SvtxTrackEval::get_nwrongclusters_contribution (SvtxTrack * svtxtrack, PHG4Particle * truthparticle)
Definition at line 635 of file SvtxTrackEval.cc.
References _cache_get_nwrongclusters_contribution, _errors, _strict, assert, calc_cluster_contribution(), and has_node_pointers().
Referenced by SvtxEvaluator::fillOutputNtuples().
SvtxTruthEval* SvtxTrackEval::get_truth_eval () inline
Definition at line 48 of file SvtxTrackEval.h.
References _clustereval, and SvtxClusterEval::get_truth_eval().
Referenced by all_tracks_from(), calc_cluster_contribution(), get_layer_range_contribution(), get_nclusters_contribution_by_layer(), and SvtxVertexEval::get_truth_eval().
bool SvtxTrackEval::has_node_pointers () private
Definition at line 888 of file SvtxTrackEval.cc.
References _strict, _trackmap, and assert.
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), calc_cluster_contribution(), create_cache_track_from_cluster(), get_layer_range_contribution(), get_nclusters_contribution(), get_nclusters_contribution_by_layer(), get_nwrongclusters_contribution(), and max_truth_particle_by_nclusters().
PHG4Particle * SvtxTrackEval::max_truth_particle_by_nclusters (SvtxTrack * track)
Definition at line 190 of file SvtxTrackEval.cc.
References _cache_max_truth_particle_by_nclusters, _do_cache, _errors, _strict, all_truth_particles(), assert, get_nclusters_contribution(), has_node_pointers(), and particles.
Referenced by LeptoquarksReco::AddTrackInformation(), SvtxVertexEval::all_truth_particles(), GenFitTrackProp::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), JetRecoEval::get_energy_contribution(), SvtxVertexEval::get_ntracks_contribution(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), SvtxSimPerformanceCheckReco::process_event(), TrackingPerformanceCheck::process_event(), SimpleTrackingAnalysis::process_event(), BJetModule::process_event(), and PhotonJet::process_event().
void SvtxTrackEval::next_event (PHCompositeNode * topNode)
Definition at line 56 of file SvtxTrackEval.cc.
References _cache_all_tracks_from_cluster, _cache_all_tracks_from_g4hit, _cache_all_tracks_from_particle, _cache_all_truth_hits, _cache_all_truth_particles, _cache_best_track_from_cluster, _cache_best_track_from_particle, _cache_get_nclusters_contribution, _cache_get_nclusters_contribution_by_layer, _cache_get_nwrongclusters_contribution, _cache_max_truth_particle_by_nclusters, _clustereval, get_node_pointers(), and SvtxClusterEval::next_event().
Referenced by SvtxVertexEval::next_event().
void SvtxTrackEval::set_strict (bool strict) inline
Definition at line 34 of file SvtxTrackEval.h.
References _clustereval, _strict, and SvtxClusterEval::set_strict().
Referenced by SvtxVertexEval::set_strict().
void SvtxTrackEval::set_verbosity (int verbosity) inline
Definition at line 39 of file SvtxTrackEval.h.
References _clustereval, _verbosity, SvtxClusterEval::set_verbosity(), and verbosity.
Referenced by SvtxVertexEval::set_verbosity().
Member Data Documentation
std::map<TrkrDefs::cluskey, std::set<SvtxTrack*> > SvtxTrackEval::_cache_all_tracks_from_cluster private
Definition at line 92 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), create_cache_track_from_cluster(), and next_event().
std::map<PHG4Hit*, std::set<SvtxTrack*> > SvtxTrackEval::_cache_all_tracks_from_g4hit private
Definition at line 91 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), and next_event().
std::map<PHG4Particle*, std::set<SvtxTrack*> > SvtxTrackEval::_cache_all_tracks_from_particle private
Definition at line 89 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), and next_event().
std::map<SvtxTrack*, std::set<PHG4Hit*> > SvtxTrackEval::_cache_all_truth_hits private
Definition at line 86 of file SvtxTrackEval.h.
Referenced by all_truth_hits(), and next_event().
std::map<SvtxTrack*, std::set<PHG4Particle*> > SvtxTrackEval::_cache_all_truth_particles private
Definition at line 87 of file SvtxTrackEval.h.
Referenced by all_truth_particles(), and next_event().
std::map<TrkrDefs::cluskey, SvtxTrack*> SvtxTrackEval::_cache_best_track_from_cluster private
Definition at line 93 of file SvtxTrackEval.h.
Referenced by best_track_from(), and next_event().
std::map<PHG4Particle*, SvtxTrack*> SvtxTrackEval::_cache_best_track_from_particle private
Definition at line 90 of file SvtxTrackEval.h.
Referenced by best_track_from(), and next_event().
std::map<std::pair<SvtxTrack*, PHG4Particle*>, unsigned int> SvtxTrackEval::_cache_get_nclusters_contribution private
Definition at line 94 of file SvtxTrackEval.h.
Referenced by calc_cluster_contribution(), get_nclusters_contribution(), and next_event().
std::map<std::pair<SvtxTrack*, PHG4Particle*>, unsigned int> SvtxTrackEval::_cache_get_nclusters_contribution_by_layer private
Definition at line 95 of file SvtxTrackEval.h.
Referenced by get_nclusters_contribution_by_layer(), and next_event().
std::map<std::pair<SvtxTrack*, PHG4Particle*>, unsigned int> SvtxTrackEval::_cache_get_nwrongclusters_contribution private
Definition at line 96 of file SvtxTrackEval.h.
Referenced by calc_cluster_contribution(), get_nwrongclusters_contribution(), and next_event().
std::map<SvtxTrack*, PHG4Particle*> SvtxTrackEval::_cache_max_truth_particle_by_nclusters private
Definition at line 88 of file SvtxTrackEval.h.
Referenced by max_truth_particle_by_nclusters(), and next_event().
bool SvtxTrackEval::_cache_track_from_cluster_exists private
Definition at line 85 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), and create_cache_track_from_cluster().
SvtxClusterEval SvtxTrackEval::_clustereval private
Definition at line 77 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), calc_cluster_contribution(), do_caching(), get_cluster_eval(), get_errors(), get_hit_eval(), get_layer_range_contribution(), get_nclusters_contribution_by_layer(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
bool SvtxTrackEval::_do_cache private
Definition at line 84 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), do_caching(), get_nclusters_contribution_by_layer(), and max_truth_particle_by_nclusters().
unsigned int SvtxTrackEval::_errors private
Definition at line 82 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), calc_cluster_contribution(), create_cache_track_from_cluster(), get_errors(), get_layer_range_contribution(), get_nclusters_contribution(), get_nclusters_contribution_by_layer(), get_nwrongclusters_contribution(), max_truth_particle_by_nclusters(), and ~SvtxTrackEval().
bool SvtxTrackEval::_strict private
Definition at line 80 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), all_truth_hits(), all_truth_particles(), best_track_from(), calc_cluster_contribution(), get_layer_range_contribution(), get_nclusters_contribution(), get_nclusters_contribution_by_layer(), get_nwrongclusters_contribution(), has_node_pointers(), max_truth_particle_by_nclusters(), and set_strict().
SvtxTrackMap* SvtxTrackEval::_trackmap private
Definition at line 78 of file SvtxTrackEval.h.
Referenced by all_tracks_from(), create_cache_track_from_cluster(), get_node_pointers(), and has_node_pointers().
int SvtxTrackEval::_verbosity private
Definition at line 81 of file SvtxTrackEval.h.
Referenced by set_verbosity(), and ~SvtxTrackEval().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTrackEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxTrackEval.cc