Analysis Software: RawTowerGeomContainerv1 Class Reference
RawTowerGeomContainerv1 Class Reference
Generic tower geometry class, store each tower's geometry individually.
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainerv1.h>
Public Member Functions
RawTowerGeomContainerv1 (RawTowerDefs::CalorimeterId caloid=RawTowerDefs::NONE)
virtual ~RawTowerGeomContainerv1 ()
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
void set_calorimeter_id (RawTowerDefs::CalorimeterId caloid)
8-bit calorimeter ID
RawTowerDefs::CalorimeterId get_calorimeter_id () const
ConstIterator add_tower_geometry (RawTowerGeom *geo)
go through all towers
RawTowerGeom * get_tower_geometry (RawTowerDefs::keytype key)
ConstRange get_tower_geometries (void) const
return all tower geometries
Range get_tower_geometries (void)
unsigned int size () const
Public Member Functions inherited from RawTowerGeomContainer
virtual ~RawTowerGeomContainer ()
default constructor for ROOT IO
virtual double get_radius () const
virtual double get_thickness () const
virtual int get_phibins () const
virtual int get_etabins () const
virtual std::pair< double, double > get_phibounds (const int ibin) const
virtual std::pair< double, double > get_etabounds (const int ibin) const
virtual double get_etacenter (const int ibin) const
virtual double get_phicenter (const int ibin) const
virtual int get_etabin (const double eta) const
virtual int get_phibin (const double phi) const
virtual void set_radius (const double r)
virtual void set_thickness (const double t)
virtual void set_phibins (const int i)
virtual void set_etabins (const int i)
virtual void set_etabounds (const int ibin, const std::pair< double, double > &bounds)
virtual void set_phibounds (const int ibin, const std::pair< double, double > &bounds)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::CalorimeterId _caloid
Map _geoms
Additional Inherited Members
Public Types inherited from RawTowerGeomContainer
typedef std::map
< RawTowerDefs::keytype,
RawTowerGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Protected Member Functions inherited from RawTowerGeomContainer
RawTowerGeomContainer ()
this class is not for use. Base class only
Detailed Description
Generic tower geometry class, store each tower's geometry individually.
Definition at line 15 of file RawTowerGeomContainerv1.h.
Constructor & Destructor Documentation
RawTowerGeomContainerv1::RawTowerGeomContainerv1 (RawTowerDefs::CalorimeterId caloid = RawTowerDefs::NONE)
Definition at line 13 of file RawTowerGeomContainerv1.cc.
RawTowerGeomContainerv1::~RawTowerGeomContainerv1 () virtual
Definition at line 18 of file RawTowerGeomContainerv1.cc.
References Reset().
Member Function Documentation
RawTowerGeomContainerv1::ConstIterator RawTowerGeomContainerv1::add_tower_geometry (RawTowerGeom * geo) virtual
go through all towers
Reimplemented from RawTowerGeomContainer.
Definition at line 36 of file RawTowerGeomContainerv1.cc.
References _geoms, assert, RawTowerDefs::decode_caloid(), get_calorimeter_id(), RawTowerGeom::get_id(), RawTowerGeom::identify(), and it.
RawTowerDefs::CalorimeterId RawTowerGeomContainerv1::get_calorimeter_id () const inline virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 26 of file RawTowerGeomContainerv1.h.
References _caloid.
Referenced by add_tower_geometry().
RawTowerGeomContainerv1::ConstRange RawTowerGeomContainerv1::get_tower_geometries (void) const virtual
return all tower geometries
Reimplemented from RawTowerGeomContainer.
Definition at line 24 of file RawTowerGeomContainerv1.cc.
References _geoms.
RawTowerGeomContainerv1::Range RawTowerGeomContainerv1::get_tower_geometries (void) virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 30 of file RawTowerGeomContainerv1.cc.
References _geoms.
RawTowerGeom * RawTowerGeomContainerv1::get_tower_geometry (RawTowerDefs::keytype key) virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 68 of file RawTowerGeomContainerv1.cc.
References _geoms, and it.
Referenced by CaloTriggerSim::process_event().
void RawTowerGeomContainerv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeomContainer.
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 92 of file RawTowerGeomContainerv1.cc.
References size().
int RawTowerGeomContainerv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 78 of file RawTowerGeomContainerv1.cc.
References _geoms.
void RawTowerGeomContainerv1::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 83 of file RawTowerGeomContainerv1.cc.
References _geoms.
Referenced by RawTowerGeomContainer_Cylinderv1::Reset(), and ~RawTowerGeomContainerv1().
void RawTowerGeomContainerv1::set_calorimeter_id (RawTowerDefs::CalorimeterId) inline virtual
8-bit calorimeter ID
Reimplemented from RawTowerGeomContainer.
Definition at line 25 of file RawTowerGeomContainerv1.h.
References _caloid.
unsigned int RawTowerGeomContainerv1::size (void) const inline virtual
Reimplemented from RawTowerGeomContainer.
Definition at line 35 of file RawTowerGeomContainerv1.h.
References _geoms.
Referenced by identify().
Member Data Documentation
RawTowerDefs::CalorimeterId RawTowerGeomContainerv1::_caloid protected
Definition at line 38 of file RawTowerGeomContainerv1.h.
Referenced by get_calorimeter_id(), and set_calorimeter_id().
Map RawTowerGeomContainerv1::_geoms protected
Definition at line 39 of file RawTowerGeomContainerv1.h.
Referenced by add_tower_geometry(), get_tower_geometries(), get_tower_geometry(), isValid(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainerv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainerv1.cc