Analysis Software: groot Class Reference
groot Class Reference
#include <analysis/blob/master/TPC/groot/groot.h>
Public Member Functions
virtual ~groot ()
void FillAccessBlobs ()
void Report ()
void ClearTheDetector ()
void SaveTheHistograms (std::string filename)
Static Public Member Functions
static groot * instance ()
Public Attributes
std::vector< ATrace * > theTraces
std::vector< AZigzag * > theZigzags
std::vector< ABlob * > theBlobs [Nr]
ABlob * AccessBlobs [Nr][10]
int BlobCount [Nr]
std::vector< ATrack * > theTracks
Event * event
std::vector< TH1 * > theHistograms
TRandom Randy
AZigzag * ZigzagMap2 [Nr][Nphi]
AZigzag * ZigzagMap [Nsrs]
AZigzag * ZWaveMap [Nsrs]
Protected Member Functions
groot ()
void CreateZigzags ()
void FillZigzagMaps ()
void CreateZigzagMaps ()
void FindNeighbors ()
int PanPinToChannel (int PanPin)
int ConnectorToHybrid (std::string Conn)
Protected Attributes
int demapper [128]
int remapper [128]
std::map< std::string,
std::string > Padplane_NameToConnector
std::map< std::string,
std::string > Padplane_NameToSamPin
std::map< std::string, int > PanSam_SamPinToPanPin
Static Protected Attributes
static groot * __instance =0
Detailed Description
Definition at line 45 of file groot.h.
Constructor & Destructor Documentation
groot::~groot () virtual
Definition at line 68 of file groot.C.
References i, j, and Nr.
groot::groot () protected
Definition at line 25 of file groot.C.
References channel(), CHhybrid, i, j, Nphi, Nr, Nsrs, and AZigzag::ReadCalibration().
Referenced by instance().
Member Function Documentation
void groot::ClearTheDetector ()
Definition at line 127 of file groot.C.
References AZigzag::Cal, i, j, Nr, Nsrs, and AZigzag::Raw.
Referenced by process_event().
int groot::ConnectorToHybrid (std::string Conn) protected
Definition at line 285 of file groot.C.
void groot::CreateZigzagMaps () protected
void groot::CreateZigzags () protected
Definition at line 311 of file groot.C.
References c, channel(), CHhybrid, file, CheveronPad_t::fName, CheveronPad_t::fPolyLayer, CheveronPad_t::fPolyWidth, CheveronPad_t::fVia, CheveronPad_t::fWire, CheveronPad_t::fX, CheveronPad_t::fY, index, AZigzag::MyChannel, AZigzag::MyHybrid, AZigzag::MyWaveIndex, Nhybrid, CheveronPad_t::phi, CheveronPad_t::r, AZigzag::SetMyID(), x, and y.
void groot::FillAccessBlobs ()
Definition at line 438 of file groot.C.
References i, j, and Nr.
void groot::FillZigzagMaps () protected
Definition at line 194 of file groot.C.
References c, file, and line.
void groot::FindNeighbors () protected
Definition at line 161 of file groot.C.
References CHhybrid, i, j, k, Nhybrid, Nphi, and Nr.
static groot* groot::instance () inline static
Definition at line 48 of file groot.h.
References __instance, and groot().
Referenced by AZigzag::ApplyCalibration(), AZigzag::DetermineCommonMode(), FillBlobHist(), FillCalHist(), FillHoughHist(), FindBlobs(), ABlob::GetPHI(), groot100(), NoiseSimulator(), OutputVisualsTPC(), pinit(), process_event(), and ReconstructTracks().
int groot::PanPinToChannel (int PanPin) protected
Definition at line 272 of file groot.C.
void groot::Report ()
Definition at line 85 of file groot.C.
References i, j, and Nr.
void groot::SaveTheHistograms (std::string filename)
Definition at line 426 of file groot.C.
References i.
Referenced by groot100().
Member Data Documentation
groot * groot::__instance =0 static protected
Definition at line 97 of file groot.h.
Referenced by instance().
ABlob* groot::AccessBlobs[Nr][10]
Definition at line 70 of file groot.h.
int groot::BlobCount[Nr]
Definition at line 71 of file groot.h.
int groot::demapper[128] protected
Definition at line 106 of file groot.h.
Event* groot::event
Definition at line 78 of file groot.h.
Referenced by process_event().
std::map<std::string,std::string> groot::Padplane_NameToConnector protected
Definition at line 109 of file groot.h.
std::map<std::string,std::string> groot::Padplane_NameToSamPin protected
Definition at line 110 of file groot.h.
std::map<std::string,int> groot::PanSam_SamPinToPanPin protected
Definition at line 112 of file groot.h.
TRandom groot::Randy
Definition at line 87 of file groot.h.
int groot::remapper[128] protected
Definition at line 107 of file groot.h.
std::vector<ABlob*> groot::theBlobs[Nr]
Definition at line 67 of file groot.h.
Referenced by FillBlobHist(), FillHoughHist(), FindBlobs(), and OutputVisualsTPC().
std::vector<TH1*> groot::theHistograms
Definition at line 80 of file groot.h.
Referenced by FillBlobHist(), and ABlob::GetPHI().
std::vector<ATrace*> groot::theTraces
Definition at line 63 of file groot.h.
Referenced by process_event().
std::vector<ATrack*> groot::theTracks
Definition at line 76 of file groot.h.
Referenced by process_event(), and ReconstructTracks().
std::vector<AZigzag*> groot::theZigzags
Definition at line 66 of file groot.h.
Referenced by AZigzag::DetermineCommonMode(), FillBlobHist(), FillCalHist(), OutputVisualsTPC(), and process_event().
AZigzag* groot::ZigzagMap[Nsrs]
Definition at line 92 of file groot.h.
Referenced by AZigzag::ApplyCalibration().
AZigzag* groot::ZigzagMap2[Nr][Nphi]
Definition at line 91 of file groot.h.
Referenced by FillBlobHist(), FillHoughHist(), FindBlobs(), ABlob::GetPHI(), and NoiseSimulator().
AZigzag* groot::ZWaveMap[Nsrs]
Definition at line 93 of file groot.h.
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/groot/groot.h
analysis/blob/master/TPC/groot/groot.C