Analysis Software: SvtxTrackMap Class Reference
SvtxTrackMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap.h>
Public Types
typedef std::map< unsigned int,
SvtxTrack * > TrackMap
typedef std::map< unsigned int,
SvtxTrack * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxTrack * >::iterator Iter
Public Member Functions
virtual ~SvtxTrackMap ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const SvtxTrack * get (unsigned int idkey) const
virtual SvtxTrack * get (unsigned int idkey)
virtual SvtxTrack * insert (const SvtxTrack *cluster)
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxTrackMap ()
Private Member Functions
ClassDef (SvtxTrackMap, 1)
Detailed Description
Definition at line 10 of file SvtxTrackMap.h.
Member Typedef Documentation
typedef std::map<unsigned int, SvtxTrack*>::const_iterator SvtxTrackMap::ConstIter
Definition at line 14 of file SvtxTrackMap.h.
typedef std::map<unsigned int, SvtxTrack*>::iterator SvtxTrackMap::Iter
Definition at line 15 of file SvtxTrackMap.h.
typedef std::map<unsigned int, SvtxTrack*> SvtxTrackMap::TrackMap
Definition at line 13 of file SvtxTrackMap.h.
Constructor & Destructor Documentation
virtual SvtxTrackMap::~SvtxTrackMap () inline virtual
Definition at line 17 of file SvtxTrackMap.h.
SvtxTrackMap::SvtxTrackMap () inline protected
Definition at line 46 of file SvtxTrackMap.h.
Member Function Documentation
virtual ConstIter SvtxTrackMap::begin () const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 37 of file SvtxTrackMap.h.
Referenced by LeptoquarksReco::AddTrackInformation(), SvtxTrackEval::all_tracks_from(), PhotonJet::ConeSum(), SvtxTrackEval::create_cache_track_from_cluster(), TpcPrototypeGenFitTrkFinder::fill_eval_tree(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_track(), TrackJetInput::get_input(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), SVReco::InitEvent(), PHGenFitTrkProp::KalmanTrkProp(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluator::printInputInfo(), PHTruthTrackSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), MomentumEvaluator::process_event(), SimpleTrackingAnalysis::process_event(), BJetModule::process_event(), PJTranslator::process_event(), PHGenFitTrackProjection::process_event(), RecoConversionEval::process_event(), MyJetAnalysis::process_event(), PHRaveVertexing::process_event(), BDiJetModule::process_event(), TruthConversionEval::process_event(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), DumpSvtxTrackMap::process_Node(), PHFlowJetMaker::run_particle_flow(), and PHPatternReco::turnoff_hits_used_in_triplets().
virtual Iter SvtxTrackMap::begin () inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 41 of file SvtxTrackMap.h.
SvtxTrackMap::ClassDef (SvtxTrackMap , 1) private
virtual void SvtxTrackMap::clear () inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 30 of file SvtxTrackMap.h.
Referenced by PHInitZVertexing::export_output().
virtual PHObject* SvtxTrackMap::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1.
Definition at line 25 of file SvtxTrackMap.h.
virtual size_t SvtxTrackMap::count (unsigned int idkey) const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 29 of file SvtxTrackMap.h.
virtual bool SvtxTrackMap::empty () const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 27 of file SvtxTrackMap.h.
Referenced by PHG4TrackFastSim::process_event(), PHGenFitTrkFitter::process_event(), and TpcPrototypeGenFitTrkFitter::process_event().
virtual ConstIter SvtxTrackMap::end () const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 39 of file SvtxTrackMap.h.
Referenced by LeptoquarksReco::AddTrackInformation(), SvtxTrackEval::all_tracks_from(), PhotonJet::ConeSum(), SvtxTrackEval::create_cache_track_from_cluster(), TpcPrototypeGenFitTrkFinder::fill_eval_tree(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_track_tree(), FastTrackingEval::fill_tree(), GenFitTrackProp::fill_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TrackProjectionTools::FindClosestTrack(), TrackProjectorPlaneECAL::get_best_track(), TrackJetInput::get_input(), PhotonJet::GetRecoHadronsAndJets(), AnaTutorial::getTracks(), SVReco::InitEvent(), PHGenFitTrkProp::KalmanTrkProp(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluator::printInputInfo(), PHTruthTrackSeeding::Process(), SvtxSimPerformanceCheckReco::process_event(), MomentumEvaluator::process_event(), SimpleTrackingAnalysis::process_event(), BJetModule::process_event(), PJTranslator::process_event(), PHGenFitTrackProjection::process_event(), RecoConversionEval::process_event(), MyJetAnalysis::process_event(), PHRaveVertexing::process_event(), BDiJetModule::process_event(), TruthConversionEval::process_event(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), DumpSvtxTrackMap::process_Node(), PHFlowJetMaker::run_particle_flow(), and PHPatternReco::turnoff_hits_used_in_triplets().
virtual Iter SvtxTrackMap::end () inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 43 of file SvtxTrackMap.h.
virtual size_t SvtxTrackMap::erase (unsigned int idkey) inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 35 of file SvtxTrackMap.h.
Referenced by PHGenFitTrkProp::KalmanTrkProp(), PHGenFitTrkFitter::process_event(), and TpcPrototypeGenFitTrkFitter::process_event().
virtual ConstIter SvtxTrackMap::find (unsigned int idkey) const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 38 of file SvtxTrackMap.h.
Referenced by PHG4TrackFastSimEval::fill_vertex_tree().
virtual Iter SvtxTrackMap::find (unsigned int idkey) inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 42 of file SvtxTrackMap.h.
virtual const SvtxTrack* SvtxTrackMap::get (unsigned int idkey) const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 32 of file SvtxTrackMap.h.
Referenced by JetRecoEval::all_truth_hits(), SvtxVertexEval::all_truth_particles(), JetRecoEval::all_truth_particles(), PHHoughSeeding::export_output(), TrkrEvaluator::fillOutputNtuples(), TrackProjectorPlaneECAL::get_best_track(), JetRecoEval::get_energy_contribution(), and SvtxVertexEval::get_ntracks_contribution().
virtual SvtxTrack* SvtxTrackMap::get (unsigned int idkey) inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 33 of file SvtxTrackMap.h.
virtual void SvtxTrackMap::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1.
Definition at line 19 of file SvtxTrackMap.h.
References os.
Referenced by PHTrackSeeding::CreateNodes(), PHHoughSeeding::export_output(), and PHTruthTrackSeeding::Process().
virtual SvtxTrack* SvtxTrackMap::insert (const SvtxTrack * cluster) inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 34 of file SvtxTrackMap.h.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), PHTruthTrackSeeding::Process(), TpcPrototypeGenFitTrkFinder::process_event(), PHG4TrackFastSim::process_event(), PHGenFitTrkFitter::process_event(), and TpcPrototypeGenFitTrkFitter::process_event().
virtual int SvtxTrackMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1.
Definition at line 24 of file SvtxTrackMap.h.
virtual void SvtxTrackMap::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxTrackMap_v1.
Definition at line 23 of file SvtxTrackMap.h.
virtual size_t SvtxTrackMap::size (void) const inline virtual
Reimplemented in SvtxTrackMap_v1.
Definition at line 28 of file SvtxTrackMap.h.
Referenced by PHHoughSeeding::export_output(), TrkrEvaluator::fillOutputNtuples(), PHGenFitTrkProp::KalmanTrkProp(), PHGenFitTrkProp::OutputPHGenFitTrack(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluator::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxEvaluator::printOutputInfo(), PHTruthTrackSeeding::Process(), PJTranslator::process_event(), TpcPrototypeGenFitTrkFinder::process_event(), and DumpSvtxTrackMap::process_Node().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap.h