Analysis Software: property map definitions
property map definitions
Setters
Classes
union RawClusterv1::u_property
convert between 32bit inputs and storage type prop_storage_t
Typedefs
typedef uint8_t RawClusterv1::prop_id_t
storage types for additional property
typedef uint32_t RawClusterv1::prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > RawClusterv1::prop_map_t
Enumerations
enum RawCluster::PROPERTY {
RawCluster::prop_ecore = 0, RawCluster::prop_prob = 1, RawCluster::prop_chi2 = 2, RawCluster::prop_et_iso_calotower_sub_R01 = 20,
RawCluster::prop_et_iso_calotower_R01 = 21, RawCluster::prop_et_iso_calotower_sub_R02 = 22, RawCluster::prop_et_iso_calotower_R02 = 23, RawCluster::prop_et_iso_calotower_sub_R03 = 24,
RawCluster::prop_et_iso_calotower_R03 = 25, RawCluster::prop_et_iso_calotower_sub_R04 = 26, RawCluster::prop_et_iso_calotower_R04 = 27, RawCluster::prop_MAX_NUMBER = UCHAR_MAX
}
enum RawCluster::PROPERTY_TYPE { RawCluster::type_int = 1, RawCluster::type_uint = 2, RawCluster::type_float = 3, RawCluster::type_unknown = -1 }
Functions
virtual bool RawCluster::has_property (const PROPERTY prop_id) const
getters
virtual float RawCluster::get_property_float (const PROPERTY prop_id) const
virtual int RawCluster::get_property_int (const PROPERTY prop_id) const
virtual unsigned int RawCluster::get_property_uint (const PROPERTY prop_id) const
virtual void RawCluster::set_property (const PROPERTY prop_id, const float value)
setters
virtual void RawCluster::set_property (const PROPERTY prop_id, const int value)
virtual void RawCluster::set_property (const PROPERTY prop_id, const unsigned int value)
static std::pair< const
std::string, PROPERTY_TYPE > RawCluster::get_property_info (PROPERTY prop_id)
type management
static bool RawCluster::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string RawCluster::get_property_type (const PROPERTY_TYPE prop_type)
bool RawClusterv1::has_property (const PROPERTY prop_id) const
float RawClusterv1::get_property_float (const PROPERTY prop_id) const
int RawClusterv1::get_property_int (const PROPERTY prop_id) const
unsigned int RawClusterv1::get_property_uint (const PROPERTY prop_id) const
void RawClusterv1::set_property (const PROPERTY prop_id, const float value)
void RawClusterv1::set_property (const PROPERTY prop_id, const int value)
void RawClusterv1::set_property (const PROPERTY prop_id, const unsigned int value)
unsigned int RawClusterv1::get_property_nocheck (const PROPERTY prop_id) const
void RawClusterv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Variables
prop_map_t RawClusterv1::prop_map
container for additional property
Detailed Description
Typedef Documentation
typedef uint8_t RawClusterv1::prop_id_t protected
storage types for additional property
Definition at line 133 of file RawClusterv1.h.
typedef std::map<prop_id_t, prop_storage_t> RawClusterv1::prop_map_t protected
Definition at line 135 of file RawClusterv1.h.
typedef uint32_t RawClusterv1::prop_storage_t protected
Definition at line 134 of file RawClusterv1.h.
Enumeration Type Documentation
enum RawCluster::PROPERTY
Procedure to add a new PROPERTY tag: 1.add new tag below with unique value, 2.add a short name to RawCluster::get_property_info()
Enumerator:
prop_ecore
cluster core energy for EM shower
prop_prob
cluster template probability for EM shower
prop_chi2
reduced chi2 for EM shower
prop_et_iso_calotower_sub_R01
isolation ET by the calorimeter tower heuristic with subtracted background R=.1
prop_et_iso_calotower_R01
isolation ET by the calorimeter tower heuristic no subtracted background R=.1
prop_et_iso_calotower_sub_R02
isolation ET by the calorimeter tower heuristic with subtracted background R=.2
prop_et_iso_calotower_R02
isolation ET by the calorimeter tower heuristic with subtracted background R=.2
prop_et_iso_calotower_sub_R03
isolation ET by the calorimeter tower heuristic with subtracted background R=.2
prop_et_iso_calotower_R03
isolation ET by the calorimeter tower heuristic with subtracted background R=.2
prop_et_iso_calotower_sub_R04
isolation ET by the calorimeter tower heuristic with subtracted background R=.2
prop_et_iso_calotower_R04
isolation ET by the calorimeter tower heuristic with subtracted background R=.2
prop_MAX_NUMBER
max limit in order to fit into 8 bit unsigned number
Definition at line 233 of file RawCluster.h.
enum RawCluster::PROPERTY_TYPE
Enumerator:
type_int
type_uint
type_float
type_unknown
Definition at line 270 of file RawCluster.h.
Function Documentation
bool RawCluster::check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type) static
Definition at line 73 of file RawCluster.cc.
Referenced by RawClusterv1::get_property_float(), RawClusterv1::get_property_int(), and RawClusterv1::get_property_uint().
float RawClusterv1::get_property_float (const PROPERTY prop_id) const
Definition at line 94 of file RawClusterv1.cc.
References RawCluster::check_property(), RawClusterv1::u_property::fdata, RawCluster::get_property_info(), RawCluster::get_property_type(), i, PHWHERE, RawClusterv1::prop_map, and RawCluster::type_float.
Referenced by RawClusterv1::get_chi2(), RawClusterv1::get_ecore(), RawClusterv1::get_et_iso(), RawClusterv1::get_prob(), and RawClusterv1::identify().
virtual float RawCluster::get_property_float (const PROPERTY prop_id) const inline virtual
Definition at line 280 of file RawCluster.h.
std::pair< const std::string, RawCluster::PROPERTY_TYPE > RawCluster::get_property_info (PROPERTY prop_id) static
type management
Definition at line 20 of file RawCluster.cc.
References RawCluster::type_float.
Referenced by RawClusterv1::get_property_float(), RawClusterv1::get_property_int(), RawClusterv1::get_property_uint(), and RawClusterv1::identify().
int RawClusterv1::get_property_int (const PROPERTY prop_id) const
Definition at line 111 of file RawClusterv1.cc.
References RawCluster::check_property(), RawCluster::get_property_info(), RawCluster::get_property_type(), i, RawClusterv1::u_property::idata, PHWHERE, RawClusterv1::prop_map, and RawCluster::type_int.
Referenced by RawClusterv1::identify().
virtual int RawCluster::get_property_int (const PROPERTY prop_id) const inline virtual
Definition at line 281 of file RawCluster.h.
unsigned int RawClusterv1::get_property_nocheck (const PROPERTY prop_id) const protected
Definition at line 240 of file RawClusterv1.cc.
References RawClusterv1::prop_map.
string RawCluster::get_property_type (const PROPERTY_TYPE prop_type) static
Definition at line 84 of file RawCluster.cc.
Referenced by RawClusterv1::get_property_float(), RawClusterv1::get_property_int(), and RawClusterv1::get_property_uint().
unsigned int RawClusterv1::get_property_uint (const PROPERTY prop_id) const
Definition at line 129 of file RawClusterv1.cc.
References RawCluster::check_property(), RawCluster::get_property_info(), RawCluster::get_property_type(), i, PHWHERE, RawClusterv1::prop_map, RawCluster::type_uint, and RawClusterv1::u_property::uidata.
Referenced by RawClusterv1::identify().
virtual unsigned int RawCluster::get_property_uint (const PROPERTY prop_id) const inline virtual
Definition at line 282 of file RawCluster.h.
bool RawClusterv1::has_property (const PROPERTY prop_id) const
Definition at line 88 of file RawClusterv1.cc.
References i, and RawClusterv1::prop_map.
virtual bool RawCluster::has_property (const PROPERTY prop_id) const inline virtual
getters
Definition at line 279 of file RawCluster.h.
void RawClusterv1::set_property (const PROPERTY prop_id, const float value)
Referenced by RawClusterv1::set_chi2(), RawClusterv1::set_ecore(), RawClusterv1::set_et_iso(), and RawClusterv1::set_prob().
void RawClusterv1::set_property (const PROPERTY prop_id, const int value)
void RawClusterv1::set_property (const PROPERTY prop_id, const unsigned int value)
virtual void RawCluster::set_property (const PROPERTY prop_id, const float value) inline virtual
setters
Definition at line 284 of file RawCluster.h.
virtual void RawCluster::set_property (const PROPERTY prop_id, const int value) inline virtual
Definition at line 285 of file RawCluster.h.
virtual void RawCluster::set_property (const PROPERTY prop_id, const unsigned int value) inline virtual
Definition at line 286 of file RawCluster.h.
void RawClusterv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline protected
Definition at line 131 of file RawClusterv1.h.
References RawClusterv1::prop_map.
Variable Documentation
prop_map_t RawClusterv1::prop_map protected
container for additional property
Definition at line 164 of file RawClusterv1.h.
Referenced by RawClusterv1::get_property_float(), RawClusterv1::get_property_int(), RawClusterv1::get_property_nocheck(), RawClusterv1::get_property_uint(), RawClusterv1::has_property(), RawClusterv1::identify(), RawClusterv1::Reset(), and RawClusterv1::set_property_nocheck().