Analysis Software: ReadFisher Class Reference
ReadFisher Class Reference
Public Member Functions
ReadFisher (std::vector< std::string > &theInputVars)
virtual ~ReadFisher ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadFisher (std::vector< std::string > &theInputVars)
virtual ~ReadFisher ()
double GetMvaValue (const std::vector< double > &inputValues) const
Public Member Functions inherited from IClassifierReader
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
Private Member Functions
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
Private Attributes
const char * fClassName
const size_t fNvars
const bool fIsNormalised
double fVmin [10]
double fVmax [10]
char fType [10]
double fFisher0
std::vector< double > fFisherCoefficients
Additional Inherited Members
Protected Attributes inherited from IClassifierReader
bool fStatusIsClean
Detailed Description
Definition at line 82 of file eback_Fisher.class.C.
Constructor & Destructor Documentation
ReadFisher::ReadFisher (std::vector< std::string > & theInputVars) inline
Definition at line 87 of file eback_Fisher.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadFisher::~ReadFisher () inline virtual
Definition at line 157 of file eback_Fisher.class.C.
References Clear().
ReadFisher::ReadFisher (std::vector< std::string > & theInputVars) inline
Definition at line 87 of file hback_Fisher.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadFisher::~ReadFisher () inline virtual
Definition at line 157 of file hback_Fisher.class.C.
References Clear().
Member Function Documentation
void ReadFisher::Clear () inline private
Definition at line 233 of file eback_Fisher.class.C.
References fFisherCoefficients.
Referenced by ~ReadFisher().
void ReadFisher::Clear () private
double ReadFisher::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadFisher::GetMvaValue (const std::vector< double > & inputValues) const inline virtual
Implements IClassifierReader.
Definition at line 238 of file eback_Fisher.class.C.
References fClassName, fVmax, fVmin, GetMvaValue__(), IsNormalised(), IClassifierReader::IsStatusClean(), and NormVariable().
double ReadFisher::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadFisher::GetMvaValue__ (const std::vector< double > & inputValues) const inline private
Definition at line 222 of file eback_Fisher.class.C.
References fFisher0, fFisherCoefficients, and fNvars.
Referenced by GetMvaValue().
size_t ReadFisher::GetNvar () const inline private
Definition at line 175 of file hback_Fisher.class.C.
References fNvars.
size_t ReadFisher::GetNvar () const inline private
Definition at line 175 of file eback_Fisher.class.C.
References fNvars.
char ReadFisher::GetType (int ivar) const inline private
Definition at line 176 of file eback_Fisher.class.C.
References fType.
char ReadFisher::GetType (int ivar) const inline private
Definition at line 176 of file hback_Fisher.class.C.
References fType.
void ReadFisher::Initialize () private
void ReadFisher::Initialize () inline private
Definition at line 200 of file eback_Fisher.class.C.
References fClassName, fFisher0, fFisherCoefficients, fNvars, and IClassifierReader::fStatusIsClean.
Referenced by ReadFisher().
bool ReadFisher::IsNormalised () const inline private
Definition at line 180 of file hback_Fisher.class.C.
References fIsNormalised.
bool ReadFisher::IsNormalised () const inline private
Definition at line 180 of file eback_Fisher.class.C.
References fIsNormalised.
Referenced by GetMvaValue().
double ReadFisher::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 183 of file eback_Fisher.class.C.
Referenced by GetMvaValue().
double ReadFisher::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 183 of file hback_Fisher.class.C.
Member Data Documentation
const char * ReadFisher::fClassName private
Definition at line 172 of file eback_Fisher.class.C.
Referenced by GetMvaValue(), Initialize(), and ReadFisher().
double ReadFisher::fFisher0 private
Definition at line 196 of file eback_Fisher.class.C.
Referenced by GetMvaValue__(), and Initialize().
std::vector< double > ReadFisher::fFisherCoefficients private
Definition at line 197 of file eback_Fisher.class.C.
Referenced by Clear(), GetMvaValue__(), and Initialize().
const bool ReadFisher::fIsNormalised private
Definition at line 179 of file eback_Fisher.class.C.
Referenced by IsNormalised().
const size_t ReadFisher::fNvars private
Definition at line 174 of file eback_Fisher.class.C.
Referenced by GetMvaValue__(), GetNvar(), Initialize(), and ReadFisher().
char ReadFisher::fType private
Definition at line 189 of file eback_Fisher.class.C.
Referenced by GetType(), and ReadFisher().
double ReadFisher::fVmax private
Definition at line 182 of file eback_Fisher.class.C.
Referenced by GetMvaValue(), and ReadFisher().
double ReadFisher::fVmin private
Definition at line 181 of file eback_Fisher.class.C.
Referenced by GetMvaValue(), and ReadFisher().
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/Training/weights/eback_Fisher.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_Fisher.class.C