Analysis Software: TruthTrackerHepMC Class Reference
TruthTrackerHepMC Class Reference
#include <analysis/blob/master/EICAnalysis/TruthTrackerHepMC.h>
Public Member Functions
TruthTrackerHepMC ()
~TruthTrackerHepMC ()
void set_hepmc_geneventmap (PHHepMCGenEventMap *evtmap)
HepMC::GenParticle * FindParticle (int)
HepMC::GenParticle * FindDaughterParticle (int, HepMC::GenParticle *)
HepMC::GenParticle * FindBeamLepton ()
HepMC::GenParticle * FindBeamHadron ()
HepMC::GenParticle * FindScatteredLepton ()
void FindDecayParticles (HepMC::GenParticle *, uint &, uint &, uint &)
void FindMissingPt (float &, float &)
Private Member Functions
void UpdateFinalStateParticle (HepMC::GenParticle *&)
Private Attributes
PHHepMCGenEventMap * _genevtmap
Detailed Description
Class with helpful functions to trace particle and event information through HepMC event records.
Some useful PDG codes:
particle ... PGD code
LQ_ue ... 39 tau- ... 15 pi+ ... 211 pi- ... -211 u ... 2 d ... 1
Definition at line 23 of file TruthTrackerHepMC.h.
Constructor & Destructor Documentation
TruthTrackerHepMC::TruthTrackerHepMC ()
Default constructor.
Definition at line 13 of file TruthTrackerHepMC.C.
TruthTrackerHepMC::~TruthTrackerHepMC () inline
Default destructor.
Definition at line 32 of file TruthTrackerHepMC.h.
Member Function Documentation
HepMC::GenParticle * TruthTrackerHepMC::FindBeamHadron ()
Locate beam hadron; the incident hadron is assumed to be the second particle in the particle list.
Definition at line 108 of file TruthTrackerHepMC.C.
References PHHepMCGenEvent::getEvent().
HepMC::GenParticle * TruthTrackerHepMC::FindBeamLepton ()
Locate beam lepton; the incident lepton is assumed to be the first particle in the particle list.
Definition at line 87 of file TruthTrackerHepMC.C.
References PHHepMCGenEvent::getEvent().
HepMC::GenParticle * TruthTrackerHepMC::FindDaughterParticle (int pid, HepMC::GenParticle * particle_mother)
Locate a daughet particle with specific PDG code in event record that is a child of a given particle. Return pointer to first daughter particle with matching ID found.
Definition at line 56 of file TruthTrackerHepMC.C.
References pid.
Referenced by LeptoquarksReco::AddTrueTauTag(), and Leptoquarks::process_event().
void TruthTrackerHepMC::FindDecayParticles (HepMC::GenParticle * particle_mother, uint & decay_prong, uint & decay_hcharged, uint & decay_lcharged)
Function to find final decay products of given particle
Definition at line 208 of file TruthTrackerHepMC.C.
Referenced by LeptoquarksReco::AddTrueTauTag(), and Leptoquarks::process_event().
void TruthTrackerHepMC::FindMissingPt (float & pt_miss, float & pt_miss_phi)
Function to calculate missing transverse momentum (pT_miss) and azimuthal angle of missing pT (pT_miss_phi)
Definition at line 319 of file TruthTrackerHepMC.C.
References PHHepMCGenEvent::getEvent().
Referenced by Leptoquarks::process_event().
HepMC::GenParticle * TruthTrackerHepMC::FindParticle (int pid)
Locate a particle with specific PDG code in event record. Return pointer to first particle with matching ID found.
Definition at line 19 of file TruthTrackerHepMC.C.
References PHHepMCGenEvent::getEvent(), and pid.
Referenced by LeptoquarksReco::AddTrueTauTag(), and Leptoquarks::process_event().
HepMC::GenParticle * TruthTrackerHepMC::FindScatteredLepton ()
Locate scattered lepton; the scattered lepton beam is assumed to be the first final-state particle in the particle list with the same PDG code as the incident lepton beam.
Definition at line 130 of file TruthTrackerHepMC.C.
References PHHepMCGenEvent::getEvent().
Referenced by ExclusiveReco::AddInvariantMassInformation(), and DISKinematicsReco::CollectEmCandidatesFromTruth().
void TruthTrackerHepMC::set_hepmc_geneventmap (PHHepMCGenEventMap * evtmap) inline
Set pointer to PHHeoMCGenEventMap to use for this event.
Definition at line 35 of file TruthTrackerHepMC.h.
References _genevtmap.
Referenced by ExclusiveReco::AddInvariantMassInformation(), LeptoquarksReco::AddTrueTauTag(), DISKinematicsReco::CollectEmCandidatesFromTruth(), and Leptoquarks::process_event().
void TruthTrackerHepMC::UpdateFinalStateParticle (HepMC::GenParticle *& particle) private
Check if this is the final state particle or not- update pointer if needed
Definition at line 179 of file TruthTrackerHepMC.C.
Member Data Documentation
PHHepMCGenEventMap* TruthTrackerHepMC::_genevtmap private
The PHHepMCGenEvent map with all HepMC information for this event
Definition at line 66 of file TruthTrackerHepMC.h.
Referenced by set_hepmc_geneventmap().
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/TruthTrackerHepMC.h
analysis/blob/master/EICAnalysis/TruthTrackerHepMC.C