Analysis Software: DataStr Class Reference
DataStr Class Reference
Public Member Functions
double PixSz ()
int minX ()
int maxX ()
int NoverX ()
int OmiXs ()
int OmiX ()
int OmaX ()
int minY ()
int maxY ()
int IsOver (int x, int y)
int IsOverX (int x)
Static Public Member Functions
static DataStr * Instance (int nx, int ny)
Protected Member Functions
DataStr (int nx, int ny)
~DataStr ()
Protected Attributes
double pixsz
int device
int xmin
int xmax
int ymin
int ymax
int NXpres
int NYpres
int NXover
int NYover
int oxmin
int oxmax
int oymin
int oymax
Static Private Attributes
static DataStr * pInstance = 0
Detailed Description
Definition at line 242 of file Bias.cpp.
Constructor & Destructor Documentation
DataStr::DataStr (int nx, int ny) protected
Definition at line 283 of file Bias.cpp.
References printf(), and ymax.
DataStr::~DataStr () inline protected
Definition at line 256 of file Bias.cpp.
Member Function Documentation
DataStr * DataStr::Instance (int nx, int ny) static
Definition at line 273 of file Bias.cpp.
Referenced by Bias::Bias(), Fe55::Fe55(), and SimX::SimX().
int DataStr::IsOver (int x, int y)
Definition at line 397 of file Bias.cpp.
Referenced by Fe55::BaLiC(), and Fe55::BaLiS().
int DataStr::IsOverX (int x)
Definition at line 406 of file Bias.cpp.
Referenced by Fe55::BaLiS(), and Bias::Bias().
int DataStr::maxX () inline
Definition at line 261 of file Bias.cpp.
Referenced by Fe55::BaLiC(), Fe55::BaLiS(), Bias::Bias(), Fe55::Fe55(), and SimX::SimX().
int DataStr::maxY () inline
Definition at line 267 of file Bias.cpp.
References ymax.
Referenced by Fe55::BaLiC(), Fe55::BaLiS(), Bias::Bias(), Fe55::Fe55(), and SimX::SimX().
int DataStr::minX () inline
Definition at line 260 of file Bias.cpp.
Referenced by Fe55::BaLiC(), Fe55::BaLiS(), Bias::Bias(), Fe55::Fe55(), and SimX::SimX().
int DataStr::minY () inline
Definition at line 266 of file Bias.cpp.
Referenced by Fe55::BaLiC(), Fe55::BaLiS(), Bias::Bias(), Fe55::Fe55(), and SimX::SimX().
int DataStr::NoverX () inline
Definition at line 262 of file Bias.cpp.
Referenced by Fe55::BaLiS(), and Bias::Bias().
int DataStr::OmaX () inline
Definition at line 265 of file Bias.cpp.
Referenced by Fe55::BaLiS().
int DataStr::OmiX () inline
Definition at line 264 of file Bias.cpp.
Referenced by Fe55::BaLiS().
int DataStr::OmiXs () inline
Definition at line 263 of file Bias.cpp.
double DataStr::PixSz () inline
Definition at line 259 of file Bias.cpp.
Referenced by Fe55::Fe55(), and SimX::SimX().
Member Data Documentation
int DataStr::device protected
Definition at line 247 of file Bias.cpp.
int DataStr::NXover protected
Definition at line 251 of file Bias.cpp.
int DataStr::NXpres protected
Definition at line 250 of file Bias.cpp.
int DataStr::NYover protected
Definition at line 251 of file Bias.cpp.
int DataStr::NYpres protected
Definition at line 250 of file Bias.cpp.
int DataStr::oxmax protected
Definition at line 252 of file Bias.cpp.
int DataStr::oxmin protected
Definition at line 252 of file Bias.cpp.
int DataStr::oymax protected
Definition at line 253 of file Bias.cpp.
int DataStr::oymin protected
Definition at line 253 of file Bias.cpp.
DataStr * DataStr::pInstance = 0 static private
Definition at line 244 of file Bias.cpp.
double DataStr::pixsz protected
Definition at line 246 of file Bias.cpp.
int DataStr::xmax protected
Definition at line 248 of file Bias.cpp.
int DataStr::xmin protected
Definition at line 248 of file Bias.cpp.
int DataStr::ymax protected
Definition at line 249 of file Bias.cpp.
int DataStr::ymin protected
Definition at line 249 of file Bias.cpp.
The documentation for this class was generated from the following file:
analysis/blob/master/TPC/DAMAlgorithm/Bias.cpp