Analysis Software: SvtxVertexMap Class Reference
SvtxVertexMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap.h>
Public Types
typedef std::map< unsigned int,
SvtxVertex * > VertexMap
typedef std::map< unsigned int,
SvtxVertex * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxVertex * >::iterator Iter
Public Member Functions
virtual ~SvtxVertexMap ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const SvtxVertex * get (unsigned int idkey) const
virtual SvtxVertex * get (unsigned int idkey)
virtual SvtxVertex * insert (SvtxVertex *cluster)
Add vertex to container. Note the container take to ownership.
virtual SvtxVertex * insert_clone (const SvtxVertex *vertex)
legacy interface. Add vertex to container. Note the container does not take ownership
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxVertexMap ()
Private Member Functions
ClassDef (SvtxVertexMap, 1)
Detailed Description
Definition at line 10 of file SvtxVertexMap.h.
Member Typedef Documentation
typedef std::map<unsigned int, SvtxVertex*>::const_iterator SvtxVertexMap::ConstIter
Definition at line 14 of file SvtxVertexMap.h.
typedef std::map<unsigned int, SvtxVertex*>::iterator SvtxVertexMap::Iter
Definition at line 15 of file SvtxVertexMap.h.
typedef std::map<unsigned int, SvtxVertex*> SvtxVertexMap::VertexMap
Definition at line 13 of file SvtxVertexMap.h.
Constructor & Destructor Documentation
virtual SvtxVertexMap::~SvtxVertexMap () inline virtual
Definition at line 17 of file SvtxVertexMap.h.
SvtxVertexMap::SvtxVertexMap () inline protected
Definition at line 51 of file SvtxVertexMap.h.
Member Function Documentation
virtual ConstIter SvtxVertexMap::begin () const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 42 of file SvtxVertexMap.h.
Referenced by SvtxVertexEval::all_vertexes_from(), PHPatternReco::export_output(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), BDiJetModule::FillVertexMap(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), GlobalVertexReco::process_event(), and DumpSvtxVertexMap::process_Node().
virtual Iter SvtxVertexMap::begin () inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 46 of file SvtxVertexMap.h.
SvtxVertexMap::ClassDef (SvtxVertexMap , 1) private
virtual void SvtxVertexMap::clear () inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 30 of file SvtxVertexMap.h.
Referenced by PHInitZVertexing::export_output(), PHHoughSeeding::export_output(), PHRaveVertexing::FillSvtxVertexMap(), and TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap().
virtual PHObject* SvtxVertexMap::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 25 of file SvtxVertexMap.h.
virtual size_t SvtxVertexMap::count (unsigned int idkey) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 29 of file SvtxVertexMap.h.
virtual bool SvtxVertexMap::empty () const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 27 of file SvtxVertexMap.h.
Referenced by psTOFTimezeroEval::printOutputInfo(), and SvtxEvaluatorHaiwang::printOutputInfo().
virtual ConstIter SvtxVertexMap::end () const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 44 of file SvtxVertexMap.h.
Referenced by SvtxVertexEval::all_vertexes_from(), PHPatternReco::export_output(), PHGenFitTrkFitter::fill_eval_tree(), TpcPrototypeGenFitTrkFitter::fill_eval_tree(), PHG4TrackFastSimEval::fill_vertex_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), BDiJetModule::FillVertexMap(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), SvtxSimPerformanceCheckReco::process_event(), SimpleTrackingAnalysis::process_event(), GlobalVertexReco::process_event(), and DumpSvtxVertexMap::process_Node().
virtual Iter SvtxVertexMap::end () inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 48 of file SvtxVertexMap.h.
virtual size_t SvtxVertexMap::erase (unsigned int idkey) inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 40 of file SvtxVertexMap.h.
virtual ConstIter SvtxVertexMap::find (unsigned int idkey) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 43 of file SvtxVertexMap.h.
virtual Iter SvtxVertexMap::find (unsigned int idkey) inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 47 of file SvtxVertexMap.h.
virtual const SvtxVertex* SvtxVertexMap::get (unsigned int idkey) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 32 of file SvtxVertexMap.h.
Referenced by TruthConversionEval::get_primary_vertex(), PHGenFitTrkProp::Process(), BDiJetModule::process_event(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), and PHHoughSeeding::vertexing().
virtual SvtxVertex* SvtxVertexMap::get (unsigned int idkey) inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 33 of file SvtxVertexMap.h.
virtual void SvtxVertexMap::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 19 of file SvtxVertexMap.h.
References os.
Referenced by PHGenFitTrkFitter::FillSvtxVertexMap(), and PHRaveVertexing::process_event().
virtual SvtxVertex* SvtxVertexMap::insert (SvtxVertex * cluster) inline virtual
Add vertex to container. Note the container take to ownership.
Reimplemented in SvtxVertexMap_v1.
Definition at line 36 of file SvtxVertexMap.h.
virtual SvtxVertex* SvtxVertexMap::insert_clone (const SvtxVertex * vertex) inline virtual
legacy interface. Add vertex to container. Note the container does not take ownership
Reimplemented in SvtxVertexMap_v1.
Definition at line 38 of file SvtxVertexMap.h.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), PHRaveVertexing::FillSvtxVertexMap(), PHG4TrackFastSim::FillSvtxVertexMap(), PHGenFitTrkFitter::FillSvtxVertexMap(), and TpcPrototypeGenFitTrkFitter::FillSvtxVertexMap().
virtual int SvtxVertexMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 24 of file SvtxVertexMap.h.
virtual void SvtxVertexMap::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxVertexMap_v1.
Definition at line 23 of file SvtxVertexMap.h.
virtual size_t SvtxVertexMap::size (void) const inline virtual
Reimplemented in SvtxVertexMap_v1.
Definition at line 28 of file SvtxVertexMap.h.
Referenced by psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), SvtxEvaluator::printInputInfo(), PHGenFitTrkProp::Process(), PHGenFitTrkFitter::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), DumpSvtxVertexMap::process_Node(), and PHHoughSeeding::vertexing().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap.h