Analysis Software: SvtxVertex_v1 Class Reference
SvtxVertex_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertex_v1.h>
Public Member Functions
SvtxVertex_v1 ()
virtual ~SvtxVertex_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
float get_t0 () const
void set_t0 (float t0)
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
float get_chisq () const
void set_chisq (float chisq)
unsigned int get_ndof () const
void set_ndof (unsigned int ndof)
float get_position (unsigned int coor) const
void set_position (unsigned int coor, float xi)
float get_error (unsigned int i, unsigned int j) const
void set_error (unsigned int i, unsigned int j, float value)
void clear_tracks ()
bool empty_tracks ()
size_t size_tracks () const
void insert_track (unsigned int trackid)
size_t erase_track (unsigned int trackid)
ConstTrackIter begin_tracks () const
ConstTrackIter find_track (unsigned int trackid) const
ConstTrackIter end_tracks () const
TrackIter begin_tracks ()
TrackIter find_track (unsigned int trackid)
TrackIter end_tracks ()
Public Member Functions inherited from SvtxVertex
virtual ~SvtxVertex ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
ClassDef (SvtxVertex_v1, 1)
Private Attributes
unsigned int _id
float _t0
float _pos [3]
float _chisq
unsigned int _ndof
float _err [6]
std::set< unsigned int > _track_ids
Additional Inherited Members
Public Types inherited from SvtxVertex
typedef std::set< unsigned int > TrackSet
typedef std::set< unsigned int >
::const_iterator ConstTrackIter
typedef std::set< unsigned int >
::iterator TrackIter
Protected Member Functions inherited from SvtxVertex
SvtxVertex ()
ClassDef (SvtxVertex, 1)
Detailed Description
Definition at line 12 of file SvtxVertex_v1.h.
Constructor & Destructor Documentation
SvtxVertex_v1::SvtxVertex_v1 ()
Definition at line 8 of file SvtxVertex_v1.cc.
References _pos, i, j, and set_error().
Referenced by CloneMe(), and Reset().
virtual SvtxVertex_v1::~SvtxVertex_v1 () inline virtual
Definition at line 16 of file SvtxVertex_v1.h.
Member Function Documentation
ConstTrackIter SvtxVertex_v1::begin_tracks () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 62 of file SvtxVertex_v1.h.
References _track_ids.
Referenced by identify().
TrackIter SvtxVertex_v1::begin_tracks () inline virtual
Reimplemented from SvtxVertex.
Definition at line 65 of file SvtxVertex_v1.h.
References _track_ids.
SvtxVertex_v1::ClassDef (SvtxVertex_v1 , 1) private
void SvtxVertex_v1::clear_tracks () inline virtual
Reimplemented from SvtxVertex.
Definition at line 57 of file SvtxVertex_v1.h.
References _track_ids.
PHObject* SvtxVertex_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxVertex.
Definition at line 23 of file SvtxVertex_v1.h.
References SvtxVertex_v1().
unsigned int SvtxVertex_v1::covar_index (unsigned int i, unsigned int j) const private
Definition at line 98 of file SvtxVertex_v1.cc.
References boost::swap().
Referenced by get_error(), and set_error().
bool SvtxVertex_v1::empty_tracks () inline virtual
Reimplemented from SvtxVertex.
Definition at line 58 of file SvtxVertex_v1.h.
References _track_ids.
ConstTrackIter SvtxVertex_v1::end_tracks () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 64 of file SvtxVertex_v1.h.
References _track_ids.
Referenced by identify().
TrackIter SvtxVertex_v1::end_tracks () inline virtual
Reimplemented from SvtxVertex.
Definition at line 67 of file SvtxVertex_v1.h.
References _track_ids.
size_t SvtxVertex_v1::erase_track (unsigned int trackid) inline virtual
Reimplemented from SvtxVertex.
Definition at line 61 of file SvtxVertex_v1.h.
References _track_ids.
ConstTrackIter SvtxVertex_v1::find_track (unsigned int trackid) const inline virtual
Reimplemented from SvtxVertex.
Definition at line 63 of file SvtxVertex_v1.h.
References _track_ids.
TrackIter SvtxVertex_v1::find_track (unsigned int trackid) inline virtual
Reimplemented from SvtxVertex.
Definition at line 66 of file SvtxVertex_v1.h.
References _track_ids.
float SvtxVertex_v1::get_chisq () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 42 of file SvtxVertex_v1.h.
References _chisq.
Referenced by identify().
float SvtxVertex_v1::get_error (unsigned int i, unsigned int j) const virtual
Reimplemented from SvtxVertex.
Definition at line 93 of file SvtxVertex_v1.cc.
References _err, and covar_index().
Referenced by identify(), and isValid().
unsigned int SvtxVertex_v1::get_id () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 27 of file SvtxVertex_v1.h.
References _id.
Referenced by identify().
unsigned int SvtxVertex_v1::get_ndof () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 45 of file SvtxVertex_v1.h.
References _ndof.
Referenced by identify().
float SvtxVertex_v1::get_position (unsigned int coor) const inline virtual
Reimplemented from SvtxVertex.
Definition at line 48 of file SvtxVertex_v1.h.
References _pos.
Referenced by identify().
float SvtxVertex_v1::get_t0 () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 30 of file SvtxVertex_v1.h.
References _t0.
Referenced by identify().
float SvtxVertex_v1::get_x () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 33 of file SvtxVertex_v1.h.
References _pos.
Referenced by PHHoughSeeding::export_output().
float SvtxVertex_v1::get_y () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 36 of file SvtxVertex_v1.h.
References _pos.
Referenced by PHHoughSeeding::export_output().
float SvtxVertex_v1::get_z () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 39 of file SvtxVertex_v1.h.
References _pos.
Referenced by PHHoughSeeding::export_output().
void SvtxVertex_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxVertex.
Definition at line 27 of file SvtxVertex_v1.cc.
References begin_tracks(), end_tracks(), get_chisq(), get_error(), get_id(), get_ndof(), get_position(), and get_t0().
void SvtxVertex_v1::insert_track (unsigned int trackid) inline virtual
Reimplemented from SvtxVertex.
Definition at line 60 of file SvtxVertex_v1.h.
References _track_ids.
Referenced by PHPatternReco::export_output(), and PHHoughSeeding::export_output().
int SvtxVertex_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxVertex.
Definition at line 65 of file SvtxVertex_v1.cc.
References _chisq, _id, _ndof, _pos, _t0, _track_ids, get_error(), i, and j.
void SvtxVertex_v1::Reset () inline virtual
Clear Event.
Reimplemented from SvtxVertex.
Definition at line 21 of file SvtxVertex_v1.h.
References SvtxVertex_v1().
void SvtxVertex_v1::set_chisq (float chisq) inline virtual
Reimplemented from SvtxVertex.
Definition at line 43 of file SvtxVertex_v1.h.
References _chisq.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), and PHHoughSeeding::export_output().
void SvtxVertex_v1::set_error (unsigned int i, unsigned int j, float value) virtual
Reimplemented from SvtxVertex.
Definition at line 87 of file SvtxVertex_v1.cc.
References _err, covar_index(), and value.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), and SvtxVertex_v1().
void SvtxVertex_v1::set_id (unsigned int id) inline virtual
Reimplemented from SvtxVertex.
Definition at line 28 of file SvtxVertex_v1.h.
References _id.
void SvtxVertex_v1::set_ndof (unsigned int ndof) inline virtual
Reimplemented from SvtxVertex.
Definition at line 46 of file SvtxVertex_v1.h.
References _ndof.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), and PHHoughSeeding::export_output().
void SvtxVertex_v1::set_position (unsigned int coor, float xi) inline virtual
Reimplemented from SvtxVertex.
Definition at line 49 of file SvtxVertex_v1.h.
References _pos.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), and PHHoughSeeding::export_output().
void SvtxVertex_v1::set_t0 (float t0) inline virtual
Reimplemented from SvtxVertex.
Definition at line 31 of file SvtxVertex_v1.h.
References _t0.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), and PHHoughSeeding::export_output().
void SvtxVertex_v1::set_x (float x) inline virtual
Reimplemented from SvtxVertex.
Definition at line 34 of file SvtxVertex_v1.h.
References _pos, and x.
void SvtxVertex_v1::set_y (float y) inline virtual
Reimplemented from SvtxVertex.
Definition at line 37 of file SvtxVertex_v1.h.
References _pos, and y.
void SvtxVertex_v1::set_z (float z) inline virtual
Reimplemented from SvtxVertex.
Definition at line 40 of file SvtxVertex_v1.h.
References _pos, and z.
size_t SvtxVertex_v1::size_tracks () const inline virtual
Reimplemented from SvtxVertex.
Definition at line 59 of file SvtxVertex_v1.h.
References _track_ids.
Member Data Documentation
float SvtxVertex_v1::_chisq private
Definition at line 75 of file SvtxVertex_v1.h.
Referenced by get_chisq(), isValid(), and set_chisq().
float SvtxVertex_v1::_err[6] private
Definition at line 77 of file SvtxVertex_v1.h.
Referenced by get_error(), and set_error().
unsigned int SvtxVertex_v1::_id private
Definition at line 72 of file SvtxVertex_v1.h.
Referenced by get_id(), isValid(), and set_id().
unsigned int SvtxVertex_v1::_ndof private
Definition at line 76 of file SvtxVertex_v1.h.
Referenced by get_ndof(), isValid(), and set_ndof().
float SvtxVertex_v1::_pos[3] private
Definition at line 74 of file SvtxVertex_v1.h.
Referenced by get_position(), get_x(), get_y(), get_z(), isValid(), set_position(), set_x(), set_y(), set_z(), and SvtxVertex_v1().
float SvtxVertex_v1::_t0 private
Definition at line 73 of file SvtxVertex_v1.h.
Referenced by get_t0(), isValid(), and set_t0().
std::set<unsigned int> SvtxVertex_v1::_track_ids private
Definition at line 78 of file SvtxVertex_v1.h.
Referenced by begin_tracks(), clear_tracks(), empty_tracks(), end_tracks(), erase_track(), find_track(), insert_track(), isValid(), and size_tracks().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertex_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertex_v1.cc