Analysis Software: TowerBackground Class Reference
TowerBackground Class Reference
#include <coresoftware/blob/master/offline/packages/jetbackground/TowerBackground.h>
Public Member Functions
virtual ~TowerBackground ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void set_UE (int layer, const std::vector< float > &UE)
virtual void set_v2 (float v2)
virtual void set_Psi2 (float Psi2)
virtual void set_nStripsUsedForFlow (int nStrips)
virtual void set_nTowersUsedForBkg (int nTowers)
virtual std::vector< float > get_UE (int layer)
virtual float get_v2 ()
virtual float get_Psi2 ()
virtual int get_nStripsUsedForFlow ()
virtual int get_nTowersUsedForBkg ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
TowerBackground ()
Private Member Functions
ClassDef (TowerBackground, 1)
Detailed Description
Definition at line 8 of file TowerBackground.h.
Constructor & Destructor Documentation
virtual TowerBackground::~TowerBackground () inline virtual
Definition at line 11 of file TowerBackground.h.
TowerBackground::TowerBackground () inline protected
Definition at line 30 of file TowerBackground.h.
Member Function Documentation
TowerBackground::ClassDef (TowerBackground , 1) private
virtual int TowerBackground::get_nStripsUsedForFlow () inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 26 of file TowerBackground.h.
virtual int TowerBackground::get_nTowersUsedForBkg () inline virtual
Definition at line 27 of file TowerBackground.h.
virtual float TowerBackground::get_Psi2 () inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 25 of file TowerBackground.h.
Referenced by SubtractTowers::process_event(), SubtractTowersCS::process_event(), and DumpTowerBackground::process_Node().
virtual std::vector<float> TowerBackground::get_UE (int layer) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 23 of file TowerBackground.h.
Referenced by SubtractTowers::process_event(), SubtractTowersCS::process_event(), and CopyAndSubtractJets::process_event().
virtual float TowerBackground::get_v2 () inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 24 of file TowerBackground.h.
Referenced by SubtractTowers::process_event(), SubtractTowersCS::process_event(), and DumpTowerBackground::process_Node().
virtual void TowerBackground::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in TowerBackgroundv1.
Definition at line 13 of file TowerBackground.h.
References os.
virtual int TowerBackground::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in TowerBackgroundv1.
Definition at line 15 of file TowerBackground.h.
virtual void TowerBackground::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in TowerBackgroundv1.
Definition at line 14 of file TowerBackground.h.
virtual void TowerBackground::set_nStripsUsedForFlow (int nStrips) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 20 of file TowerBackground.h.
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_nTowersUsedForBkg (int nTowers) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 21 of file TowerBackground.h.
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_Psi2 (float Psi2) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 19 of file TowerBackground.h.
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_UE (int layer, const std::vector< float > & UE) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 17 of file TowerBackground.h.
Referenced by DetermineTowerBackground::FillNode().
virtual void TowerBackground::set_v2 (float v2) inline virtual
Reimplemented in TowerBackgroundv1.
Definition at line 18 of file TowerBackground.h.
Referenced by DetermineTowerBackground::FillNode().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/jetbackground/TowerBackground.h