Analysis Software: buffer Class Reference
buffer Class Reference abstract
#include <online_distribution/blob/master/newbasic/buffer.h>
Public Member Functions
buffer ()
virtual ~buffer ()
virtual Event * getEvent ()=0
virtual int * getEventData ()=0
virtual int isGood () const =0
Static Public Member Functions
static int makeBuffer (PHDWORD *bp, const int allocatedsize, buffer **bptr)
static int i4swap (const int in)
static unsigned int u4swap (const unsigned int in)
static int i22swap (const int in)
static short i2swap (const short in)
Detailed Description
Definition at line 11 of file buffer.h.
Constructor & Destructor Documentation
buffer::buffer ()
Definition at line 8 of file buffer.cc.
buffer::~buffer () virtual
Definition at line 14 of file buffer.cc.
Member Function Documentation
virtual Event* buffer::getEvent () pure virtual
Implemented in oncsBuffer, prdfBuffer, lzobuffer, and gzbuffer.
Referenced by gzbuffer::getEvent(), lzobuffer::getEvent(), and fileEventiterator::getNextEvent().
virtual int* buffer::getEventData () pure virtual
Implemented in oncsBuffer, and prdfBuffer.
int buffer::i22swap (const int in) static
Definition at line 86 of file buffer.cc.
References c, i, and in.
short buffer::i2swap (const short in) static
Definition at line 103 of file buffer.cc.
References c, i, and in.
int buffer::i4swap (const int in) static
Definition at line 51 of file buffer.cc.
References c, i, and in.
Referenced by prdfBuffer::buffer_swap(), check_buffermarker(), Packet_gl1psum::decode(), Packet_A::fix_endianess(), prdfBuffer::frame_swap(), gzbuffer::gzbuffer(), lzobuffer::lzobuffer(), and main().
virtual int buffer::isGood () const pure virtual
Implemented in oncsBuffer, and prdfBuffer.
int buffer::makeBuffer (PHDWORD * bp, const int allocatedsize, buffer ** bptr) static
Definition at line 18 of file buffer.cc.
References BUFFERMARKER, GZBUFFERMARKER, LZO1XBUFFERMARKER, ONCSBUFFERMARKER, and u4swap().
Referenced by rcdaqEventiterator::read_next_buffer(), and fileEventiterator::read_next_buffer().
unsigned int buffer::u4swap (const unsigned int in) static
Definition at line 68 of file buffer.cc.
References c, i, and in.
Referenced by gzbuffer::gzbuffer(), lzobuffer::lzobuffer(), makeBuffer(), prdfBuffer::prdfBuffer(), and fileEventiterator::read_next_buffer().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/buffer.h
online_distribution/blob/master/newbasic/buffer.cc