Analysis Software: online_distribution/blob/master/newbasic/framePackets.h File Reference
framePackets.h File Reference
#include "phenixOnline.h"
#include "framePublic.h"
#include "packetPublic.h"
Functions
PTR_ret appendEmptyFramePacket (FRAME_ptr, PHDWORD, UINT)
PTR_ret findFirstFramePacket (FRAME_ptr)
PTR_ret findLastFramePacket (FRAME_ptr)
LOGIC_ret isLastFramePacket (FRAME_ptr, PACKET_ptr)
PTR_ret findFramePacketIndex (FRAME_ptr, UINT)
PTR_ret findFramePacketId (FRAME_ptr, UINT)
PTR_ret findNextFramePacketId (FRAME_ptr, PACKET_ptr, UINT)
PTR_ret findNextFramePacket (FRAME_ptr, PACKET_ptr)
VALUE_ret frameNumPackets (FRAME_ptr)
Function Documentation
PTR_ret appendEmptyFramePacket (FRAME_ptr , PHDWORD , UINT)
Definition at line 44 of file framePackets.C.
References extendFrameData(), findFrameDataStart(), FORMAT_ERR_BUFFER_OVERFLOW, makeEmptyPacket(), packetV1HdrLength, ptrFailure, setPacketSuccess(), setUserError(), validFrameHdr(), and valueFailure.
PTR_ret findFirstFramePacket (FRAME_ptr)
Definition at line 146 of file framePackets.C.
References findFramePacketIndex().
Referenced by dumpFramePackets(), findLastFramePacket(), and frameNumPackets().
PTR_ret findFramePacketId (FRAME_ptr , UINT)
Definition at line 181 of file framePackets.C.
References findFrameDataStart(), findNextFramePacket(), getPacketId(), ptrFailure, and validFrameHdr().
Referenced by X_Event::change_id(), A_Event::getFrameEntry(), A_Event::listError(), A_Event::listFrame(), and A_Event::listHistory().
PTR_ret findFramePacketIndex (FRAME_ptr , UINT)
Definition at line 103 of file framePackets.C.
References findFrameDataStart(), findNextFramePacket(), index, ptrFailure, validFrameHdr(), and validPacketHdr().
Referenced by X_Event::change_hf(), A_Event::createMap(), findFirstFramePacket(), and A_Event::getPacketList().
PTR_ret findLastFramePacket (FRAME_ptr)
Definition at line 154 of file framePackets.C.
References findFirstFramePacket(), findNextFramePacket(), and ptrFailure.
Referenced by isLastFramePacket().
PTR_ret findNextFramePacket (FRAME_ptr , PACKET_ptr)
Definition at line 230 of file framePackets.C.
References findFrameDataEnd(), findFrameDataStart(), findPacketEnd(), and ptrFailure.
Referenced by X_Event::change_hf(), A_Event::createMap(), dumpFramePackets(), findFramePacketId(), findFramePacketIndex(), findLastFramePacket(), findNextFramePacketId(), frameNumPackets(), and A_Event::getPacketList().
PTR_ret findNextFramePacketId (FRAME_ptr , PACKET_ptr , UINT)
Definition at line 207 of file framePackets.C.
References findNextFramePacket(), getPacketId(), and ptrFailure.
VALUE_ret frameNumPackets (FRAME_ptr)
Definition at line 260 of file framePackets.C.
References findFirstFramePacket(), findNextFramePacket(), and ptrFailure.
LOGIC_ret isLastFramePacket (FRAME_ptr , PACKET_ptr)
Definition at line 80 of file framePackets.C.
References FALSE, findLastFramePacket(), validFrameHdr(), and validPacketHdr().