Analysis Software: ATrack Class Reference
ATrack Class Reference
#include <analysis/blob/master/TPC/groot/ATrack.h>
Public Member Functions
ATrack ()
virtual ~ATrack ()
double X ()
double Y ()
double GetXForZ (double z)
double GetYForZ (double z)
void SetBlobs (std::vector< ABlob * >)
std::vector< ABlob * > GetBlobs ()
void SetSlope (double s)
void SetOffset (double o)
double check ()
Public Attributes
double Slope
double Offset
Protected Member Functions
void DetermineParameters ()
Protected Attributes
double x0
double y0
double z0
double dxdz
double dydz
std::vector< ABlob * > blobs
Detailed Description
Definition at line 20 of file ATrack.h.
Constructor & Destructor Documentation
ATrack::ATrack ()
Definition at line 7 of file ATrack.C.
virtual ATrack::~ATrack () inline virtual
Definition at line 24 of file ATrack.h.
Member Function Documentation
double ATrack::check () inline
Definition at line 37 of file ATrack.h.
Referenced by dokinematics(), genevent(), init(), jewel(), makebranch(), makeinsplit(), makesplitting(), pyslha(), and pywidt().
void ATrack::DetermineParameters () protected
std::vector<ABlob*> ATrack::GetBlobs () inline
Definition at line 34 of file ATrack.h.
References blobs.
double ATrack::GetXForZ (double z) inline
Definition at line 29 of file ATrack.h.
References dxdz, x0, and z0.
Referenced by X().
double ATrack::GetYForZ (double z) inline
Definition at line 30 of file ATrack.h.
Referenced by Y().
void ATrack::SetBlobs (std::vector< ABlob * >)
void ATrack::SetOffset (double o) inline
Definition at line 36 of file ATrack.h.
References Offset.
void ATrack::SetSlope (double s) inline
Definition at line 35 of file ATrack.h.
References s, and Slope.
double ATrack::X () inline
Definition at line 27 of file ATrack.h.
References GetXForZ().
double ATrack::Y () inline
Definition at line 28 of file ATrack.h.
References GetYForZ().
Member Data Documentation
std::vector<ABlob*> ATrack::blobs protected
Definition at line 51 of file ATrack.h.
Referenced by GetBlobs().
double ATrack::dxdz protected
Definition at line 45 of file ATrack.h.
Referenced by GetXForZ().
double ATrack::dydz protected
Definition at line 46 of file ATrack.h.
double ATrack::Offset
Definition at line 32 of file ATrack.h.
Referenced by SetOffset().
double ATrack::Slope
Definition at line 30 of file ATrack.h.
Referenced by SetSlope().
double ATrack::x0 protected
Definition at line 42 of file ATrack.h.
Referenced by GetXForZ().
double ATrack::y0 protected
Definition at line 43 of file ATrack.h.
double ATrack::z0 protected
Definition at line 44 of file ATrack.h.
Referenced by GetXForZ().
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/groot/ATrack.h
analysis/blob/master/TPC/groot/ATrack.C