Analysis Software: RawTowerCalibration Class Reference
RawTowerCalibration Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawTowerCalibration.h>
Public Types
enum enu_calib_algorithm { kNo_calibration = 0, kSimple_linear_calibration = 1, kTower_by_tower_calibration = 2 }
Public Member Functions
RawTowerCalibration (const std::string &name="RawTowerCalibration")
virtual ~RawTowerCalibration ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void Detector (const std::string &d)
void TowerType (const int type)
enu_calib_algorithm get_calib_algorithm () const
void set_calib_algorithm (enu_calib_algorithm calibAlgorithm)
double get_calib_const_GeV_ADC () const
void set_calib_const_GeV_ADC (double calibConstGeVAdc)
std::string get_calib_tower_node_prefix () const
void set_calib_tower_node_prefix (const std::string &calibTowerNodePrefix)
double get_pedstal_ADC () const
void set_pedstal_ADC (double pedstalAdc)
std::string get_raw_tower_node_prefix () const
void set_raw_tower_node_prefix (const std::string &rawTowerNodePrefix)
double get_zero_suppression_GeV () const
void set_zero_suppression_GeV (double zeroSuppressionGeV)
PHParameters & GetCalibrationParameters ()
Get the parameters for update. Useful fields are listed in SetDefaultParameters();.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void CreateNodes (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
enu_calib_algorithm _calib_algorithm
RawTowerContainer * _calib_towers
RawTowerContainer * _raw_towers
RawTowerGeomContainer * rawtowergeom
std::string detector
std::string RawTowerNodeName
std::string CaliTowerNodeName
std::string TowerGeomNodeName
std::string _calib_tower_node_prefix
std::string _raw_tower_node_prefix
double _pedstal_ADC
pedstal in unit of ADC
double _calib_const_GeV_ADC
calibration constant in unit of GeV per ADC
double _zero_suppression_GeV
zero suppression in unit of GeV
int _tower_type
tower type to act on
PHParameters _tower_calib_params
Tower by tower calibration parameters.
Detailed Description
calibrate ADC value to measured energy deposition in calorimeter towers default input DST node is TOWER_RAW_DETECTOR default output DST node is TOWER_CALIB_DETECTOR
Definition at line 17 of file RawTowerCalibration.h.
Member Enumeration Documentation
enum RawTowerCalibration::enu_calib_algorithm
Enumerator:
kNo_calibration
directly pass the energy of raw tower to calibrated tower. Zero suppression is applied
kSimple_linear_calibration
simple calibration with pedstal subtraction and a global energy scale (sampling fraction) correction
kTower_by_tower_calibration
input calibration file for tower by tower calibration. Use GetCalibrationParameters() to set the calibration parameters
Definition at line 40 of file RawTowerCalibration.h.
Constructor & Destructor Documentation
RawTowerCalibration::RawTowerCalibration (const std::string & name = "RawTowerCalibration")
Definition at line 34 of file RawTowerCalibration.cc.
virtual RawTowerCalibration::~RawTowerCalibration () inline virtual
Definition at line 21 of file RawTowerCalibration.h.
Member Function Documentation
void RawTowerCalibration::CreateNodes (PHCompositeNode * topNode) protected
Definition at line 180 of file RawTowerCalibration.cc.
References _calib_tower_node_prefix, _calib_towers, _raw_tower_node_prefix, _raw_towers, CaliTowerNodeName, detector, PHNodeIterator::findFirst(), RawTowerContainer::getCalorimeterID(), RawTowerGeomContainer::identify(), Fun4AllBase::Name(), rawtowergeom, RawTowerNodeName, TowerGeomNodeName, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerCalibration::Detector (const std::string & d) inline
Definition at line 29 of file RawTowerCalibration.h.
References _tower_calib_params, d, and PHParameters::set_name().
Referenced by CEMC_Towers(), EEMC_Towers(), FEMC_Towers(), FHCAL_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
int RawTowerCalibration::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 175 of file RawTowerCalibration.cc.
References Fun4AllReturnCodes::EVENT_OK.
enu_calib_algorithm RawTowerCalibration::get_calib_algorithm () const inline
Definition at line 53 of file RawTowerCalibration.h.
References _calib_algorithm.
double RawTowerCalibration::get_calib_const_GeV_ADC () const inline
Definition at line 65 of file RawTowerCalibration.h.
References _calib_const_GeV_ADC.
std::string RawTowerCalibration::get_calib_tower_node_prefix () const inline
Definition at line 77 of file RawTowerCalibration.h.
References _calib_tower_node_prefix.
double RawTowerCalibration::get_pedstal_ADC () const inline
Definition at line 89 of file RawTowerCalibration.h.
References _pedstal_ADC.
std::string RawTowerCalibration::get_raw_tower_node_prefix () const inline
Definition at line 101 of file RawTowerCalibration.h.
References _raw_tower_node_prefix.
double RawTowerCalibration::get_zero_suppression_GeV () const inline
Definition at line 113 of file RawTowerCalibration.h.
References _zero_suppression_GeV.
PHParameters& RawTowerCalibration::GetCalibrationParameters () inline
Get the parameters for update. Useful fields are listed in SetDefaultParameters();.
Definition at line 126 of file RawTowerCalibration.h.
References _tower_calib_params.
Referenced by CEMC_Towers().
int RawTowerCalibration::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 61 of file RawTowerCalibration.cc.
References Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and Fun4AllBase::Name().
int RawTowerCalibration::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 88 of file RawTowerCalibration.cc.
References _calib_algorithm, _calib_const_GeV_ADC, _calib_towers, _pedstal_ADC, _raw_towers, _tower_calib_params, _tower_type, _zero_suppression_GeV, Fun4AllReturnCodes::ABORTRUN, RawTowerContainer::AddTower(), assert, Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), RawTower::get_binphi(), PHParameters::get_double_param(), RawTower::get_energy(), RawTower::get_id(), RawTowerGeomContainer::get_tower_geometry(), RawTowerGeom::get_tower_type(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTowers(), kNo_calibration, kSimple_linear_calibration, kTower_by_tower_calibration, Fun4AllBase::Name(), phi, rawtowergeom, RawTower::set_energy(), and Fun4AllBase::Verbosity().
void RawTowerCalibration::set_calib_algorithm (enu_calib_algorithm calibAlgorithm) inline
Definition at line 59 of file RawTowerCalibration.h.
References _calib_algorithm.
Referenced by CEMC_Towers(), EEMC_Towers(), FEMC_Towers(), FHCAL_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerCalibration::set_calib_const_GeV_ADC (double calibConstGeVAdc) inline
Definition at line 71 of file RawTowerCalibration.h.
References _calib_const_GeV_ADC.
Referenced by CEMC_Towers(), EEMC_Towers(), FEMC_Towers(), FHCAL_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerCalibration::set_calib_tower_node_prefix (const std::string & calibTowerNodePrefix) inline
Definition at line 83 of file RawTowerCalibration.h.
References _calib_tower_node_prefix.
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
void RawTowerCalibration::set_pedstal_ADC (double pedstalAdc) inline
Definition at line 95 of file RawTowerCalibration.h.
References _pedstal_ADC.
Referenced by CEMC_Towers(), EEMC_Towers(), FEMC_Towers(), FHCAL_Towers(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerCalibration::set_raw_tower_node_prefix (const std::string & rawTowerNodePrefix) inline
Definition at line 107 of file RawTowerCalibration.h.
References _raw_tower_node_prefix.
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
void RawTowerCalibration::set_zero_suppression_GeV (double zeroSuppressionGeV) inline
Definition at line 119 of file RawTowerCalibration.h.
References _zero_suppression_GeV.
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), HCALInner_Towers(), and HCALOuter_Towers().
void RawTowerCalibration::TowerType (const int type) inline
Definition at line 35 of file RawTowerCalibration.h.
References _tower_type.
Referenced by FEMC_Towers().
Member Data Documentation
enu_calib_algorithm RawTowerCalibration::_calib_algorithm protected
Definition at line 135 of file RawTowerCalibration.h.
Referenced by get_calib_algorithm(), process_event(), and set_calib_algorithm().
double RawTowerCalibration::_calib_const_GeV_ADC protected
calibration constant in unit of GeV per ADC
Definition at line 153 of file RawTowerCalibration.h.
Referenced by get_calib_const_GeV_ADC(), process_event(), and set_calib_const_GeV_ADC().
std::string RawTowerCalibration::_calib_tower_node_prefix protected
Definition at line 146 of file RawTowerCalibration.h.
Referenced by CreateNodes(), get_calib_tower_node_prefix(), and set_calib_tower_node_prefix().
RawTowerContainer* RawTowerCalibration::_calib_towers protected
Definition at line 137 of file RawTowerCalibration.h.
Referenced by CreateNodes(), and process_event().
double RawTowerCalibration::_pedstal_ADC protected
pedstal in unit of ADC
Definition at line 150 of file RawTowerCalibration.h.
Referenced by get_pedstal_ADC(), process_event(), and set_pedstal_ADC().
std::string RawTowerCalibration::_raw_tower_node_prefix protected
Definition at line 147 of file RawTowerCalibration.h.
Referenced by CreateNodes(), get_raw_tower_node_prefix(), and set_raw_tower_node_prefix().
RawTowerContainer* RawTowerCalibration::_raw_towers protected
Definition at line 138 of file RawTowerCalibration.h.
Referenced by CreateNodes(), and process_event().
PHParameters RawTowerCalibration::_tower_calib_params protected
Tower by tower calibration parameters.
Definition at line 162 of file RawTowerCalibration.h.
Referenced by Detector(), GetCalibrationParameters(), and process_event().
int RawTowerCalibration::_tower_type protected
tower type to act on
Definition at line 159 of file RawTowerCalibration.h.
Referenced by process_event(), and TowerType().
double RawTowerCalibration::_zero_suppression_GeV protected
zero suppression in unit of GeV
Definition at line 156 of file RawTowerCalibration.h.
Referenced by get_zero_suppression_GeV(), process_event(), and set_zero_suppression_GeV().
std::string RawTowerCalibration::CaliTowerNodeName protected
Definition at line 143 of file RawTowerCalibration.h.
Referenced by CreateNodes().
std::string RawTowerCalibration::detector protected
Definition at line 141 of file RawTowerCalibration.h.
Referenced by CreateNodes().
RawTowerGeomContainer* RawTowerCalibration::rawtowergeom protected
Definition at line 139 of file RawTowerCalibration.h.
Referenced by CreateNodes(), and process_event().
std::string RawTowerCalibration::RawTowerNodeName protected
Definition at line 142 of file RawTowerCalibration.h.
Referenced by CreateNodes().
std::string RawTowerCalibration::TowerGeomNodeName protected
Definition at line 144 of file RawTowerCalibration.h.
Referenced by CreateNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawTowerCalibration.h
coresoftware/blob/master/offline/packages/CaloReco/RawTowerCalibration.cc