Analysis Software: macros/blob/master/macros/g4simulations/G4_EEMC.C File Reference
G4_EEMC.C File Reference
#include "GlobalVariables.C"
#include <fun4all/Fun4AllServer.h>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawTowerCalibration.h>
#include <g4detectors/PHG4CrystalCalorimeterSubsystem.h>
#include <g4detectors/PHG4ForwardCalCellReco.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
Functions
void EEMCInit ()
void EEMC_Cells (int verbosity=0)
void EEMCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void EEMC_Towers (int verbosity=0)
void EEMC_Clusters (int verbosity=0)
void EEMC_Eval (std::string outputfile, int verbosity=0)
Variables
const int use_projective_geometry = 0
Function Documentation
void EEMC_Cells (int verbosity = 0)
Definition at line 26 of file G4_EEMC.C.
References PHG4ForwardCalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void EEMC_Clusters (int verbosity = 0)
Definition at line 128 of file G4_EEMC.C.
References RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void EEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 142 of file G4_EEMC.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), and Fun4All_G4_EICDetector_RICH().
void EEMC_Towers (int verbosity = 0)
Definition at line 78 of file G4_EEMC.C.
References RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerDigitizer::set_raw_tower_node_prefix(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void EEMCInit ()
Definition at line 22 of file G4_EEMC.C.
Referenced by G4Init().
void EEMCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated EEMC module
Definition at line 40 of file G4_EEMC.C.
References eemc, overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4CrystalCalorimeterSubsystem::SetProjectiveGeometry(), PHG4CrystalCalorimeterSubsystem::SetTowerMappingFile(), and use_projective_geometry.
Referenced by G4Setup().
Variable Documentation
const int use_projective_geometry = 0
Definition at line 20 of file G4_EEMC.C.
Referenced by EEMCSetup().