Analysis Software: coresoftware/blob/master/generators/hijing/src/hijing.f File Reference
hijing.f File Reference
Functions/Subroutines
subroutine hijing (FRAME, BMIN0, BMAX0)
Function/Subroutine Documentation
subroutine hijing (character FRAME, BMIN0, BMAX0)
Definition at line 192 of file hijing.f.
References atl_ran(), HiMain1::eatt(), go(), hiboost(), hijcsc(), hijfrg(), hijhrd(), hijini(), hijsft(), HiParnt::hint1(), HiParnt::hipr1(), hirnd(), i, HijJet4::iadr(), HijJet2::iasg(), HiMain1::ierrstat(), HiParnt::ihnt2(), HiParnt::ihpr2(), j, HiMain1::jatt(), jetini(), k, HijJet2::k1sg(), HijJet2::k2sg(), HiMain2::katt(), HijJet4::kfdr(), HijJet1::kfpj(), HijJet1::kftj(), luedit(), lulist(), max, min, n, HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HijJet4::ndr(), HiStrng::nfp(), HiStrng::nft(), HijJet2::njsg(), HiMain1::np(), HijJet1::npj(), RanSeed::nseed(), HijJet2::nsg(), HiMain1::nt(), HijJet1::ntj(), HiMain2::patt(), HijJet4::pdr(), HijJet2::pesg(), phi, HijJet1::pjpe(), HijJet1::pjpm(), HijJet1::pjpx(), HijJet1::pjpy(), HijJet1::pjpz(), HijJet1::pjte(), HijJet1::pjtm(), HijJet1::pjtx(), HijJet1::pjty(), HijJet1::pjtz(), HijJet2::pmsg(), HiStrng::pp(), print(), HiStrng::pt(), HijJet2::pxsg(), HijJet2::pysg(), HijJet2::pzsg(), quench(), r, r2, romg(), PHTimer::stop(), v, HiMain2::vatt(), x, y3, HijCrdn::yp(), and HijCrdn::yt().
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), and ConfigureInput().