Analysis Software: HFJetTruthTrigger Class Reference
HFJetTruthTrigger Class Reference
#include <analysis/blob/master/HF-Jet/TruthGeneration/HFJetTruthTrigger.h>
Public Member Functions
HFJetTruthTrigger (std::string filename, int flavor=5, std::string jet_node="AntiKt_Truth_r04", int maxevent=INT_MAX)
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
float deltaR (float eta1, float eta2, float phi1, float phi2)
double get_eta_max () const
void set_eta_max (double etaMax)
double get_eta_min () const
void set_eta_min (double etaMin)
double get_pt_max () const
void set_pt_max (double ptMax)
double get_pt_min () const
void set_pt_min (double ptMin)
void set_rejection_action (int action)
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int parton_tagging (Jet *jet, HepMC::GenEvent *, const double match_radius)
tag jet flavor by parton matching, like PRL 113, 132301 (2014)
int hadron_tagging (Jet *jet, HepMC::GenEvent *, const double match_radius)
tag jet flavor by hadron matching, like MIE proposal
Private Attributes
bool _verbose
int _ievent
int _total_pass
TFile * _f
TH2D * _h2
TH2D * _h2all
TH2D * _h2_b
TH2D * _h2_c
std::string _foutname
int _flavor
int _maxevent
double _pt_min
double _pt_max
double _eta_min
double _eta_max
std::string _jet_name
int _rejection_action
action to take if no jet fitting _flavor requirement found. Action defined in <fun4all/Fun4AllReturnCodes.h>
int _embedding_id
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 22 of file HFJetTruthTrigger.h.
Constructor & Destructor Documentation
HFJetTruthTrigger::HFJetTruthTrigger (std::string filename, int flavor = 5, std::string jet_node = "AntiKt_Truth_r04", int maxevent = INT_MAX)
Definition at line 33 of file HFJetTruthTrigger.C.
References _eta_max, _eta_min, _flavor, _foutname, _jet_name, _maxevent, _pt_max, _pt_min, _rejection_action, Fun4AllReturnCodes::DISCARDEVENT, and filename.
Member Function Documentation
float HFJetTruthTrigger::deltaR (float eta1, float eta2, float phi1, float phi2) inline
Definition at line 37 of file HFJetTruthTrigger.h.
Referenced by hadron_tagging(), and parton_tagging().
int HFJetTruthTrigger::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 194 of file HFJetTruthTrigger.C.
References _f, _total_pass, verbosity, and Fun4AllBase::VERBOSITY_SOME.
int HFJetTruthTrigger::get_embedding_id () const inline
The embedding ID for the HepMC subevent to be analyzed. embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 112 of file HFJetTruthTrigger.h.
References _embedding_id.
double HFJetTruthTrigger::get_eta_max () const inline
Definition at line 52 of file HFJetTruthTrigger.h.
References _eta_max.
double HFJetTruthTrigger::get_eta_min () const inline
Definition at line 64 of file HFJetTruthTrigger.h.
References _eta_min.
double HFJetTruthTrigger::get_pt_max () const inline
Definition at line 76 of file HFJetTruthTrigger.h.
References _pt_max.
double HFJetTruthTrigger::get_pt_min () const inline
Definition at line 88 of file HFJetTruthTrigger.h.
References _pt_min.
int HFJetTruthTrigger::hadron_tagging (Jet * jet, HepMC::GenEvent * theEvent, const double match_radius) private
tag jet flavor by hadron matching, like MIE proposal
Definition at line 289 of file HFJetTruthTrigger.C.
References deltaR(), Jet::get_eta(), Jet::get_phi(), Jet::get_pt(), prop_JetHadronFlavor, prop_JetHadronZT, Jet::set_property(), verbosity, and Fun4AllBase::VERBOSITY_MORE.
Referenced by process_event().
int HFJetTruthTrigger::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 63 of file HFJetTruthTrigger.C.
References _f, _foutname, _h2, _h2_b, _h2_c, _h2all, _ievent, _total_pass, and _verbose.
int HFJetTruthTrigger::parton_tagging (Jet * jet, HepMC::GenEvent * theEvent, const double match_radius) private
tag jet flavor by parton matching, like PRL 113, 132301 (2014)
Definition at line 208 of file HFJetTruthTrigger.C.
References _h2_b, _h2_c, deltaR(), Jet::get_eta(), Jet::get_phi(), Jet::get_pt(), prop_JetPartonFlavor, prop_JetPartonZT, Jet::set_property(), verbosity, and Fun4AllBase::VERBOSITY_MORE.
Referenced by process_event().
int HFJetTruthTrigger::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 81 of file HFJetTruthTrigger.C.
References _embedding_id, _eta_max, _eta_min, _flavor, _h2, _h2all, _ievent, _jet_name, _maxevent, _pt_max, _pt_min, _rejection_action, _total_pass, Fun4AllReturnCodes::ABORTRUN, JetMap::begin(), JetMap::end(), Fun4AllReturnCodes::EVENT_OK, PHHepMCGenEventMap::get(), Jet::get_eta(), JetMap::get_par(), Jet::get_pt(), PHHepMCGenEvent::getEvent(), hadron_tagging(), PHHepMCGenEventMap::identify(), Jet::identify(), parton_tagging(), PHWHERE, JetMap::size(), verbosity, Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
void HFJetTruthTrigger::set_embedding_id (int id) inline
The embedding ID for the HepMC subevent to be analyzed. embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 119 of file HFJetTruthTrigger.h.
References _embedding_id.
void HFJetTruthTrigger::set_eta_max (double etaMax) inline
Definition at line 58 of file HFJetTruthTrigger.h.
References _eta_max.
void HFJetTruthTrigger::set_eta_min (double etaMin) inline
Definition at line 70 of file HFJetTruthTrigger.h.
References _eta_min.
void HFJetTruthTrigger::set_pt_max (double ptMax) inline
Definition at line 82 of file HFJetTruthTrigger.h.
References _pt_max.
void HFJetTruthTrigger::set_pt_min (double ptMin) inline
Definition at line 94 of file HFJetTruthTrigger.h.
References _pt_min.
Referenced by Jin_BJet().
void HFJetTruthTrigger::set_rejection_action (int action) inline
action to take if no jet fitting _flavor requirement found. Action defined in <fun4all/Fun4AllReturnCodes.h> Default action is DISCARDEVENT for DST level filtering, one can further choose ABORTEVENT to use it as processing level filtering
Definition at line 102 of file HFJetTruthTrigger.h.
References _rejection_action.
Member Data Documentation
int HFJetTruthTrigger::_embedding_id private
The embedding ID for the HepMC subevent to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 162 of file HFJetTruthTrigger.h.
Referenced by get_embedding_id(), process_event(), and set_embedding_id().
double HFJetTruthTrigger::_eta_max private
Definition at line 151 of file HFJetTruthTrigger.h.
Referenced by get_eta_max(), HFJetTruthTrigger(), process_event(), and set_eta_max().
double HFJetTruthTrigger::_eta_min private
Definition at line 150 of file HFJetTruthTrigger.h.
Referenced by get_eta_min(), HFJetTruthTrigger(), process_event(), and set_eta_min().
TFile* HFJetTruthTrigger::_f private
Definition at line 135 of file HFJetTruthTrigger.h.
Referenced by End(), and Init().
int HFJetTruthTrigger::_flavor private
Definition at line 144 of file HFJetTruthTrigger.h.
Referenced by HFJetTruthTrigger(), and process_event().
std::string HFJetTruthTrigger::_foutname private
Definition at line 142 of file HFJetTruthTrigger.h.
Referenced by HFJetTruthTrigger(), and Init().
TH2D* HFJetTruthTrigger::_h2 private
Definition at line 137 of file HFJetTruthTrigger.h.
Referenced by Init(), and process_event().
TH2D* HFJetTruthTrigger::_h2_b private
Definition at line 139 of file HFJetTruthTrigger.h.
Referenced by Init(), and parton_tagging().
TH2D* HFJetTruthTrigger::_h2_c private
Definition at line 140 of file HFJetTruthTrigger.h.
Referenced by Init(), and parton_tagging().
TH2D* HFJetTruthTrigger::_h2all private
Definition at line 138 of file HFJetTruthTrigger.h.
Referenced by Init(), and process_event().
int HFJetTruthTrigger::_ievent private
Definition at line 132 of file HFJetTruthTrigger.h.
Referenced by Init(), and process_event().
std::string HFJetTruthTrigger::_jet_name private
Definition at line 153 of file HFJetTruthTrigger.h.
Referenced by HFJetTruthTrigger(), and process_event().
int HFJetTruthTrigger::_maxevent private
Definition at line 145 of file HFJetTruthTrigger.h.
Referenced by HFJetTruthTrigger(), and process_event().
double HFJetTruthTrigger::_pt_max private
Definition at line 148 of file HFJetTruthTrigger.h.
Referenced by get_pt_max(), HFJetTruthTrigger(), process_event(), and set_pt_max().
double HFJetTruthTrigger::_pt_min private
Definition at line 147 of file HFJetTruthTrigger.h.
Referenced by get_pt_min(), HFJetTruthTrigger(), process_event(), and set_pt_min().
int HFJetTruthTrigger::_rejection_action private
action to take if no jet fitting _flavor requirement found. Action defined in <fun4all/Fun4AllReturnCodes.h>
Definition at line 156 of file HFJetTruthTrigger.h.
Referenced by HFJetTruthTrigger(), process_event(), and set_rejection_action().
int HFJetTruthTrigger::_total_pass private
Definition at line 133 of file HFJetTruthTrigger.h.
Referenced by End(), Init(), and process_event().
bool HFJetTruthTrigger::_verbose private
Definition at line 130 of file HFJetTruthTrigger.h.
Referenced by Init().
The documentation for this class was generated from the following files:
analysis/blob/master/HF-Jet/TruthGeneration/HFJetTruthTrigger.h
analysis/blob/master/HF-Jet/TruthGeneration/HFJetTruthTrigger.C