Analysis Software: PHNodeIOManager Class Reference
PHNodeIOManager Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHNodeIOManager.h>
Public Member Functions
PHNodeIOManager ()
PHNodeIOManager (const std::string &, const PHAccessType=PHReadOnly)
PHNodeIOManager (const std::string &, const std::string &, const PHAccessType=PHReadOnly)
PHNodeIOManager (const std::string &, const PHAccessType, const PHTreeType)
virtual ~PHNodeIOManager ()
virtual void closeFile ()
virtual bool write (PHCompositeNode *)
virtual void print () const
bool setFile (const std::string &, const std::string &, const PHAccessType=PHReadOnly)
PHCompositeNode * read (PHCompositeNode *=nullptr, size_t=0)
bool read (size_t requestedEvent)
int readSpecific (size_t requestedEvent, const char *objectName)
void selectObjectToRead (const char *objectName, bool readit)
bool isSelected (const char *objectName)
int isFunctional () const
bool SetCompressionLevel (const int level)
double GetBytesWritten ()
std::map< std::string, TBranch * > * GetBranchMap ()
bool write (TObject **, const std::string &, int buffersize, int splitlevel)
Public Member Functions inherited from PHIOManager
virtual ~PHIOManager ()
std::string getFilename () const
size_t getEventNumber () const
void setEventNumber (const size_t evno)
Private Member Functions
int FillBranchMap ()
PHCompositeNode * reconstructNodeTree (PHCompositeNode *)
bool readEventFromFile (size_t requestedEvent)
std::string getBranchClassName (TBranch *)
Private Attributes
TFile * file
TTree * tree
std::string TreeName
int accessMode
int CompressionLevel
std::map< std::string, TBranch * > fBranches
std::map< std::string, bool > objectToRead
int isFunctionalFlag
Additional Inherited Members
Protected Member Functions inherited from PHIOManager
PHIOManager ()
Protected Attributes inherited from PHIOManager
std::string filename
size_t eventNumber
Detailed Description
Definition at line 22 of file PHNodeIOManager.h.
Constructor & Destructor Documentation
PHNodeIOManager::PHNodeIOManager ()
Definition at line 39 of file PHNodeIOManager.cc.
PHNodeIOManager::PHNodeIOManager (const std::string & f, const PHAccessType a = PHReadOnly)
Definition at line 49 of file PHNodeIOManager.cc.
References isFunctionalFlag, and setFile().
PHNodeIOManager::PHNodeIOManager (const std::string & f, const std::string & title, const PHAccessType a = PHReadOnly)
Definition at line 59 of file PHNodeIOManager.cc.
References isFunctionalFlag, and setFile().
PHNodeIOManager::PHNodeIOManager (const std::string & f, const PHAccessType a, const PHTreeType treeindex)
Definition at line 69 of file PHNodeIOManager.cc.
References isFunctionalFlag, PHEventTree, setFile(), and TreeName.
PHNodeIOManager::~PHNodeIOManager () virtual
Definition at line 85 of file PHNodeIOManager.cc.
References closeFile(), and file.
Member Function Documentation
void PHNodeIOManager::closeFile () virtual
Implements PHIOManager.
Definition at line 91 of file PHNodeIOManager.cc.
References accessMode, file, PHUpdate, and PHWrite.
Referenced by setFile(), and ~PHNodeIOManager().
int PHNodeIOManager::FillBranchMap () private
Definition at line 581 of file PHNodeIOManager.cc.
References fBranches, file, PHIOManager::filename, i, PHWHERE, and TreeName.
Referenced by GetBranchMap().
string PHNodeIOManager::getBranchClassName (TBranch * branch) private
Definition at line 263 of file PHNodeIOManager.cc.
References assert, and PHWHERE.
Referenced by reconstructNodeTree().
map< string, TBranch * > * PHNodeIOManager::GetBranchMap ()
Definition at line 575 of file PHNodeIOManager.cc.
References fBranches, and FillBranchMap().
Referenced by Fun4AllDstInputManager::ReadNextEventSyncObject().
double PHNodeIOManager::GetBytesWritten ()
Definition at line 568 of file PHNodeIOManager.cc.
References file.
int PHNodeIOManager::isFunctional () const inline
Definition at line 41 of file PHNodeIOManager.h.
References isFunctionalFlag.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllDstOutputManager::Fun4AllDstOutputManager(), and Fun4AllDstOutputManager::outfileopen().
bool PHNodeIOManager::isSelected (const char * objectName)
Definition at line 539 of file PHNodeIOManager.cc.
References fBranches, and name.
void PHNodeIOManager::print () const virtual
Implements PHIOManager.
Definition at line 237 of file PHNodeIOManager.cc.
References accessMode, file, PHIOManager::filename, objectToRead, PHReadOnly, and tree.
Referenced by Fun4AllDstInputManager::fileopen(), and Fun4AllDstInputManager::Print().
PHCompositeNode * PHNodeIOManager::read (PHCompositeNode * topNode = nullptr, size_t requestedEvent = 0)
Definition at line 217 of file PHNodeIOManager.cc.
References readEventFromFile(), reconstructNodeTree(), and tree.
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllDstInputManager::ReadNextEventSyncObject(), Fun4AllDstInputManager::run(), and Fun4AllDstInputManager::SyncIt().
bool PHNodeIOManager::read (size_t requestedEvent)
Definition at line 204 of file PHNodeIOManager.cc.
References readEventFromFile().
bool PHNodeIOManager::readEventFromFile (size_t requestedEvent) private
Definition at line 297 of file PHNodeIOManager.cc.
References PHIOManager::eventNumber, file, PHError, PHMessage(), PHWHERE, and tree.
Referenced by read().
int PHNodeIOManager::readSpecific (size_t requestedEvent, const char * objectName)
Definition at line 345 of file PHNodeIOManager.cc.
References fBranches, name, PHError, and PHMessage().
Referenced by Fun4AllDstInputManager::ReadNextEventSyncObject().
PHCompositeNode * PHNodeIOManager::reconstructNodeTree (PHCompositeNode * topNode) private
Definition at line 370 of file PHNodeIOManager.cc.
References PHNodeIterator::addNode(), assert, phooldefs::branchpathdelim, PHNodeIterator::cd(), PHDataNode< T >::data, fBranches, file, PHIOManager::filename, PHNodeIterator::findFirst(), getBranchClassName(), PHDataNode< T >::getData(), i, it, j, phooldefs::legacypathdelims, objectToRead, PHWHERE, PHNode::setObjectType(), tree, and TreeName.
Referenced by read().
void PHNodeIOManager::selectObjectToRead (const char * objectName, bool readit)
Definition at line 521 of file PHNodeIOManager.cc.
References it, objectToRead, and tree.
Referenced by Fun4AllDstInputManager::setBranches(), setFile(), and Fun4AllDstInputManager::setSyncBranches().
bool PHNodeIOManager::SetCompressionLevel (const int level)
Definition at line 552 of file PHNodeIOManager.cc.
References CompressionLevel, and file.
Referenced by Fun4AllDstOutputManager::Fun4AllDstOutputManager(), and Fun4AllDstOutputManager::outfileopen().
bool PHNodeIOManager::setFile (const std::string & f, const std::string & title, const PHAccessType a = PHReadOnly)
Definition at line 103 of file PHNodeIOManager.cc.
References accessMode, closeFile(), CompressionLevel, file, PHIOManager::filename, PHReadOnly, PHUpdate, PHWrite, selectObjectToRead(), tree, and TreeName.
Referenced by PHNodeIOManager().
bool PHNodeIOManager::write (PHCompositeNode * topNode) virtual
Implements PHIOManager.
Definition at line 160 of file PHNodeIOManager.cc.
References PHIOManager::eventNumber, file, tree, and PHCompositeNode::write().
Referenced by Fun4AllDstOutputManager::Write(), PHIODataNode< T >::write(), and Fun4AllDstOutputManager::WriteNode().
bool PHNodeIOManager::write (TObject ** data, const std::string & path, int buffersize, int splitlevel)
Definition at line 181 of file PHNodeIOManager.cc.
References data, file, and tree.
Member Data Documentation
int PHNodeIOManager::accessMode private
Definition at line 57 of file PHNodeIOManager.h.
Referenced by closeFile(), print(), and setFile().
int PHNodeIOManager::CompressionLevel private
Definition at line 58 of file PHNodeIOManager.h.
Referenced by SetCompressionLevel(), and setFile().
std::map<std::string, TBranch *> PHNodeIOManager::fBranches private
Definition at line 59 of file PHNodeIOManager.h.
Referenced by FillBranchMap(), GetBranchMap(), isSelected(), readSpecific(), and reconstructNodeTree().
TFile* PHNodeIOManager::file private
Definition at line 54 of file PHNodeIOManager.h.
Referenced by closeFile(), FillBranchMap(), GetBytesWritten(), print(), readEventFromFile(), reconstructNodeTree(), SetCompressionLevel(), setFile(), write(), and ~PHNodeIOManager().
int PHNodeIOManager::isFunctionalFlag private
Definition at line 62 of file PHNodeIOManager.h.
Referenced by isFunctional(), and PHNodeIOManager().
std::map<std::string, bool> PHNodeIOManager::objectToRead private
Definition at line 60 of file PHNodeIOManager.h.
Referenced by print(), reconstructNodeTree(), and selectObjectToRead().
TTree* PHNodeIOManager::tree private
Definition at line 55 of file PHNodeIOManager.h.
Referenced by print(), read(), readEventFromFile(), reconstructNodeTree(), selectObjectToRead(), setFile(), and write().
std::string PHNodeIOManager::TreeName private
Definition at line 56 of file PHNodeIOManager.h.
Referenced by FillBranchMap(), PHNodeIOManager(), reconstructNodeTree(), and setFile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHNodeIOManager.h
coresoftware/blob/master/offline/framework/phool/PHNodeIOManager.cc