Analysis Software: PHFlag Class Reference
PHFlag Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHFlag.h>
Public Member Functions
PHFlag ()
virtual ~PHFlag ()
virtual const std::string get_CharFlag (const std::string &name) const
virtual const std::string get_CharFlag (const std::string &name, const std::string &defaultval)
virtual void set_CharFlag (const std::string &name, const std::string &flag)
virtual double get_DoubleFlag (const std::string &name) const
virtual double get_DoubleFlag (const std::string &name, const double defaultval)
virtual void set_DoubleFlag (const std::string &name, const double flag)
virtual float get_FloatFlag (const std::string &name) const
virtual float get_FloatFlag (const std::string &name, const float defaultval)
virtual void set_FloatFlag (const std::string &name, const float flag)
virtual int get_IntFlag (const std::string &name) const
virtual int get_IntFlag (const std::string &name, const int defaultval)
virtual void set_IntFlag (const std::string &name, const int flag)
virtual void Print () const
virtual void PrintDoubleFlags () const
virtual void PrintIntFlags () const
virtual void PrintFloatFlags () const
virtual void PrintCharFlags () const
virtual void ReadFromFile (const std::string &name)
virtual void WriteToFile (const std::string &name)
virtual int FlagExist (const std::string &name) const
virtual const std::map
< std::string, int > * IntMap () const
virtual const std::map
< std::string, float > * FloatMap () const
virtual const std::map
< std::string, double > * DoubleMap () const
virtual const std::map
< std::string, std::string > * CharMap () const
Protected Attributes
std::map< std::string, int > intflag
std::map< std::string, double > doubleflag
std::map< std::string, float > floatflag
std::map< std::string,
std::string > charflag
Detailed Description
Definition at line 19 of file PHFlag.h.
Constructor & Destructor Documentation
PHFlag::PHFlag () inline
Definition at line 22 of file PHFlag.h.
virtual PHFlag::~PHFlag () inline virtual
Definition at line 23 of file PHFlag.h.
Member Function Documentation
virtual const std::map<std::string, std::string>* PHFlag::CharMap () const inline virtual
Definition at line 53 of file PHFlag.h.
References charflag.
Referenced by FlagSavev1::FillCharFromPHFlag().
virtual const std::map<std::string, double>* PHFlag::DoubleMap () const inline virtual
Definition at line 52 of file PHFlag.h.
References doubleflag.
Referenced by FlagSavev1::FillDoubleFromPHFlag().
int PHFlag::FlagExist (const std::string & name) const virtual
Definition at line 205 of file PHFlag.cc.
Referenced by Fun4AllHistoManager::dumpHistos(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), PHGeomUtility::GetVerbosity(), Fun4AllPrdfOutputManager::InitPrdfManager(), PHRandomSeed::InitSeed(), and Fun4AllServer::run().
virtual const std::map<std::string, float>* PHFlag::FloatMap () const inline virtual
Definition at line 51 of file PHFlag.h.
References floatflag.
Referenced by FlagSavev1::FillFloatFromPHFlag().
const string PHFlag::get_CharFlag (const std::string & name) const virtual
Definition at line 11 of file PHFlag.cc.
References Print().
Referenced by HepMCNodeReader::process_event().
const string PHFlag::get_CharFlag (const std::string & name, const std::string & defaultval) virtual
Definition at line 25 of file PHFlag.cc.
double PHFlag::get_DoubleFlag (const std::string & name) const virtual
Definition at line 45 of file PHFlag.cc.
References Print().
double PHFlag::get_DoubleFlag (const std::string & name, const double defaultval) virtual
Definition at line 58 of file PHFlag.cc.
float PHFlag::get_FloatFlag (const std::string & name) const virtual
Definition at line 78 of file PHFlag.cc.
References Print().
Referenced by HepMCNodeReader::process_event().
float PHFlag::get_FloatFlag (const std::string & name, const float defaultval) virtual
Definition at line 91 of file PHFlag.cc.
int PHFlag::get_IntFlag (const std::string & name) const virtual
Definition at line 111 of file PHFlag.cc.
References Print().
Referenced by Fun4AllHistoManager::dumpHistos(), Fun4AllServer::End(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), PHGeomUtility::GetVerbosity(), Fun4AllPrdfOutputManager::InitPrdfManager(), PHRandomSeed::InitSeed(), Fun4AllServer::run(), and Fun4AllDummyInputManager::setSyncManager().
int PHFlag::get_IntFlag (const std::string & name, const int defaultval) virtual
Definition at line 124 of file PHFlag.cc.
virtual const std::map<std::string, int>* PHFlag::IntMap () const inline virtual
Definition at line 50 of file PHFlag.h.
References intflag.
Referenced by FlagSavev1::FillIntFromPHFlag().
void PHFlag::Print () const virtual
Reimplemented in recoConsts.
Definition at line 144 of file PHFlag.cc.
void PHFlag::PrintCharFlags () const virtual
Definition at line 192 of file PHFlag.cc.
Referenced by recoConsts::Print().
void PHFlag::PrintDoubleFlags () const virtual
Definition at line 166 of file PHFlag.cc.
void PHFlag::PrintFloatFlags () const virtual
Definition at line 179 of file PHFlag.cc.
Referenced by recoConsts::Print().
void PHFlag::PrintIntFlags () const virtual
Definition at line 153 of file PHFlag.cc.
Referenced by recoConsts::Print().
void PHFlag::ReadFromFile (const std::string & name) virtual
Definition at line 230 of file PHFlag.cc.
void PHFlag::set_CharFlag (const std::string & name, const std::string & flag) virtual
Definition at line 39 of file PHFlag.cc.
References name.
Referenced by PHG4PhenixDetector::Construct(), Fun4All_EICAnalysis_Leptoquarks(), Fun4All_MCEventGen(), Fun4All_Pythia6(), and FlagSavev1::PutCharToPHFlag().
void PHFlag::set_DoubleFlag (const std::string & name, const double flag) virtual
Definition at line 72 of file PHFlag.cc.
References name.
Referenced by FlagSavev1::PutDoubleToPHFlag().
void PHFlag::set_FloatFlag (const std::string & name, const float flag) virtual
Definition at line 105 of file PHFlag.cc.
References name.
Referenced by Fun4All_EICAnalysis_Leptoquarks(), Fun4All_MCEventGen(), Fun4All_Pythia6(), PHG4Reco::InitRun(), and FlagSavev1::PutFloatToPHFlag().
void PHFlag::set_IntFlag (const std::string & name, const int flag) virtual
Definition at line 138 of file PHFlag.cc.
References name.
Referenced by Fun4All_EMCalLikelihood(), Fun4All_ExportGeom(), Fun4All_G4_TPC(), Fun4All_TestBeam(), Fun4All_TestBeam_TPC(), generate_hepmc_bjet(), MakeTree(), PHGeom_DSTInspection(), FlagSavev1::PutIntToPHFlag(), RunBoth(), Fun4AllServer::setRun(), PHGeomUtility::SetVerbosity(), and Wrapper().
void PHFlag::WriteToFile (const std::string & name) virtual
Definition at line 294 of file PHFlag.cc.
Member Data Documentation
std::map<std::string, std::string> PHFlag::charflag protected
Definition at line 59 of file PHFlag.h.
Referenced by CharMap().
std::map<std::string, double> PHFlag::doubleflag protected
Definition at line 57 of file PHFlag.h.
Referenced by DoubleMap().
std::map<std::string, float> PHFlag::floatflag protected
Definition at line 58 of file PHFlag.h.
Referenced by FloatMap().
std::map<std::string, int> PHFlag::intflag protected
Definition at line 56 of file PHFlag.h.
Referenced by IntMap().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHFlag.h
coresoftware/blob/master/offline/framework/phool/PHFlag.cc