Analysis Software: PHPy6GenTrigger Class Reference
PHPy6GenTrigger Class Reference
#include <coresoftware/blob/master/generators/PHPythia6/PHPy6GenTrigger.h>
Public Member Functions
virtual ~PHPy6GenTrigger ()
virtual bool Apply (const HepMC::GenEvent *evt)
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
void Verbosity (int v)
virtual ~PHPy6GenTrigger ()
virtual bool Apply (const HepMC::GenEvent *evt)
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
void Verbosity (int v)
Protected Member Functions
PHPy6GenTrigger (const std::string &name="PHPy6GenTrigger")
constructor
PHPy6GenTrigger (const std::string &name="PHPy6GenTrigger")
constructor
Protected Attributes
int _verbosity
Private Attributes
std::string _name
Detailed Description
Definition at line 14 of file PHPy6GenTrigger.h.
Constructor & Destructor Documentation
PHPy6GenTrigger::PHPy6GenTrigger (const std::string & name = "PHPy6GenTrigger") protected
constructor
Definition at line 6 of file PHPy6GenTrigger.cc.
PHPy6GenTrigger::~PHPy6GenTrigger () virtual
Definition at line 13 of file PHPy6GenTrigger.cc.
PHPy6GenTrigger::PHPy6GenTrigger (const std::string & name = "PHPy6GenTrigger") protected
constructor
virtual PHPy6GenTrigger::~PHPy6GenTrigger () virtual
Member Function Documentation
virtual bool PHPy6GenTrigger::Apply (const HepMC::GenEvent * evt) inline virtual
Reimplemented in PHPy6ParticleTrigger, PHPy6ParticleTrigger, PHPy6ForwardElectronTrig, PHPy6ForwardElectronTrig, PHPy6JetTrigger, and PHPy6JetTrigger.
Definition at line 24 of file PHPy6GenTrigger.h.
virtual bool PHPy6GenTrigger::Apply (const HepMC::GenEvent * evt) inline virtual
Reimplemented in PHPy6ParticleTrigger, PHPy6ParticleTrigger, PHPy6ForwardElectronTrig, PHPy6ForwardElectronTrig, PHPy6JetTrigger, and PHPy6JetTrigger.
Definition at line 26 of file PHPy6GenTrigger.h.
std::vector<int> PHPy6GenTrigger::convertToInts (std::string s)
std::vector< int > PHPy6GenTrigger::convertToInts (std::string s)
Definition at line 15 of file PHPy6GenTrigger.cc.
References i.
Referenced by PHPy6ParticleTrigger::AddParents(), and PHPy6ParticleTrigger::AddParticles().
virtual std::string PHPy6GenTrigger::GetName () inline virtual
Definition at line 31 of file PHPy6GenTrigger.h.
References _name.
Referenced by PHPythia6::register_trigger().
virtual std::string PHPy6GenTrigger::GetName () inline virtual
Definition at line 32 of file PHPy6GenTrigger.h.
References _name.
void PHPy6GenTrigger::Verbosity (int v) inline
Definition at line 36 of file PHPy6GenTrigger.h.
References _verbosity, and v.
void PHPy6GenTrigger::Verbosity (int v) inline
Definition at line 38 of file PHPy6GenTrigger.h.
References _verbosity, and v.
Member Data Documentation
std::string PHPy6GenTrigger::_name private
Definition at line 44 of file PHPy6GenTrigger.h.
Referenced by GetName().
int PHPy6GenTrigger::_verbosity protected
Definition at line 41 of file PHPy6GenTrigger.h.
Referenced by PHPy6JetTrigger::Apply(), PHPy6ParticleTrigger::Apply(), Verbosity(), and PHPy6JetTrigger::~PHPy6JetTrigger().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/PHPythia6/PHPy6GenTrigger.h
analysis/blob/master/EICTrigger/PHPy6GenTrigger.h
coresoftware/blob/master/generators/PHPythia6/PHPy6GenTrigger.cc
analysis/blob/master/EICTrigger/PHPy6GenTrigger.C