Analysis Software: CaloUnpackPRDF Class Reference
CaloUnpackPRDF Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/CaloUnpackPRDF.h>
Public Member Functions
CaloUnpackPRDF ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void CreateNodeTree (PHCompositeNode *topNode)
CaloUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void set_use_high_eta_EMCal (bool b)
whether to use high eta EMCal
CaloUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
Event * _event
Packet * _packet
int _nevents
PHCompositeNode * dst_node
PHCompositeNode * data_node
RawTowerContainer * hcalin_towers_lg
RawTowerContainer * hcalout_towers_lg
RawTowerContainer * hcalin_towers_hg
RawTowerContainer * hcalout_towers_hg
RawTowerContainer * emcal_towers
int _use_high_eta_EMCal
-1 - read from RunInfo, +1, true, 0 false;
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file CaloUnpackPRDF.h.
Constructor & Destructor Documentation
CaloUnpackPRDF::CaloUnpackPRDF ()
Definition at line 33 of file CaloUnpackPRDF.cc.
CaloUnpackPRDF::CaloUnpackPRDF ()
CaloUnpackPRDF::CaloUnpackPRDF ()
Member Function Documentation
void CaloUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
void CaloUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
void CaloUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 226 of file CaloUnpackPRDF.cc.
References PHCompositeNode::addNode(), RawTowerDefs::CEMC, data_node, dst_node, emcal_towers, PHNodeIterator::findFirst(), RawTowerDefs::HCALIN, hcalin_towers_hg, hcalin_towers_lg, RawTowerDefs::HCALOUT, hcalout_towers_hg, hcalout_towers_lg, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int CaloUnpackPRDF::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 279 of file CaloUnpackPRDF.cc.
References Fun4AllReturnCodes::EVENT_OK.
int CaloUnpackPRDF::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 59 of file CaloUnpackPRDF.cc.
References Fun4AllReturnCodes::EVENT_OK.
int CaloUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int CaloUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int CaloUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 65 of file CaloUnpackPRDF.cc.
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
int CaloUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int CaloUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int CaloUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 72 of file CaloUnpackPRDF.cc.
References _event, _nevents, _packet, Fun4AllReturnCodes::ABORTEVENT, RawTowerContainer::AddTower(), assert, emcal_towers, Fun4AllReturnCodes::EVENT_OK, RawTower_Prototype2::get_signal_samples(), Event::getEvtType(), PROTOTYPE2_FEM::GetHBDCh(), Event::getPacket(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), hcalin_towers_hg, hcalin_towers_lg, hcalout_towers_hg, hcalout_towers_lg, RawTower_Prototype2::identify(), RawTowerContainer::identify(), Event::identify(), Packet::iValue(), PROTOTYPE2_FEM::NCH_EMCAL_COLUMNS, PROTOTYPE2_FEM::NCH_EMCAL_ROWS, PROTOTYPE2_FEM::NCH_IHCAL_COLUMNS, PROTOTYPE2_FEM::NCH_IHCAL_ROWS, PROTOTYPE2_FEM::NCH_OHCAL_COLUMNS, PROTOTYPE2_FEM::NCH_OHCAL_ROWS, PROTOTYPE2_FEM::NSAMPLES, PROTOTYPE2_FEM::PACKET_ID, PHWHERE, RawTower_Prototype2::set_energy(), RawTower_Prototype2::set_HBD_channel_number(), RawTower_Prototype2::set_signal_samples(), Packet::setInternalParameter(), and Fun4AllBase::Verbosity().
void CaloUnpackPRDF::set_use_high_eta_EMCal (bool b) inline
whether to use high eta EMCal
Definition at line 28 of file CaloUnpackPRDF.h.
References _use_high_eta_EMCal.
Member Data Documentation
Event * CaloUnpackPRDF::_event private
Definition at line 32 of file CaloUnpackPRDF.h.
Referenced by process_event().
int CaloUnpackPRDF::_nevents private
Definition at line 34 of file CaloUnpackPRDF.h.
Referenced by process_event().
Packet * CaloUnpackPRDF::_packet private
Definition at line 33 of file CaloUnpackPRDF.h.
Referenced by process_event().
int CaloUnpackPRDF::_use_high_eta_EMCal private
-1 - read from RunInfo, +1, true, 0 false;
Definition at line 36 of file CaloUnpackPRDF.h.
Referenced by set_use_high_eta_EMCal().
PHCompositeNode * CaloUnpackPRDF::data_node private
Definition at line 38 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree().
PHCompositeNode * CaloUnpackPRDF::dst_node private
Definition at line 37 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree().
RawTowerContainer * CaloUnpackPRDF::emcal_towers private
Definition at line 47 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
RawTowerContainer * CaloUnpackPRDF::hcalin_towers_hg private
Definition at line 44 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
RawTowerContainer * CaloUnpackPRDF::hcalin_towers_lg private
Definition at line 41 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
RawTowerContainer * CaloUnpackPRDF::hcalout_towers_hg private
Definition at line 45 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
RawTowerContainer * CaloUnpackPRDF::hcalout_towers_lg private
Definition at line 42 of file CaloUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/CaloUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype3/CaloUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype4/CaloUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype2/CaloUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype3/CaloUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype4/CaloUnpackPRDF.cc