Analysis Software: PHG4CylinderDetector Class Reference
PHG4CylinderDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderDetector.h>
Public Member Functions
PHG4CylinderDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4CylinderDetector ()
destructor
void ConstructMe (G4LogicalVolume *world)
construct
bool IsInCylinder (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params
G4VPhysicalVolume * m_CylinderPhysicalVolume
PHG4CylinderDisplayAction * m_DisplayAction
int m_Layer
std::string m_SuperDetector
Detailed Description
Definition at line 17 of file PHG4CylinderDetector.h.
Constructor & Destructor Documentation
PHG4CylinderDetector::PHG4CylinderDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 32 of file PHG4CylinderDetector.cc.
virtual PHG4CylinderDetector::~PHG4CylinderDetector () inline virtual
destructor
Definition at line 24 of file PHG4CylinderDetector.h.
Member Function Documentation
void PHG4CylinderDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 52 of file PHG4CylinderDetector.cc.
References PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), m_CylinderPhysicalVolume, m_DisplayAction, m_Params, PHG4Detector::OverlapCheck(), PHG4Subsystem::SetLogicalVolume(), PHG4CylinderDisplayAction::SetMyVolume(), and twopi.
int PHG4CylinderDetector::get_Layer () const inline
Definition at line 34 of file PHG4CylinderDetector.h.
References m_Layer.
Referenced by PHG4CylinderSteppingAction::UserSteppingAction().
bool PHG4CylinderDetector::IsInCylinder (const G4VPhysicalVolume * volume) const
Definition at line 42 of file PHG4CylinderDetector.cc.
References m_CylinderPhysicalVolume.
Referenced by PHG4CylinderSteppingAction::UserSteppingAction().
void PHG4CylinderDetector::SuperDetector (const std::string & name) inline
Definition at line 32 of file PHG4CylinderDetector.h.
References m_SuperDetector, and name.
Referenced by PHG4CylinderSubsystem::InitRunSubsystem(), PHG4CylinderSteppingAction::SetInterfacePointers(), and PHG4CylinderSteppingAction::UserSteppingAction().
const std::string PHG4CylinderDetector::SuperDetector () const inline
Definition at line 33 of file PHG4CylinderDetector.h.
References m_SuperDetector.
Member Data Documentation
G4VPhysicalVolume* PHG4CylinderDetector::m_CylinderPhysicalVolume private
Definition at line 39 of file PHG4CylinderDetector.h.
Referenced by ConstructMe(), and IsInCylinder().
PHG4CylinderDisplayAction* PHG4CylinderDetector::m_DisplayAction private
Definition at line 40 of file PHG4CylinderDetector.h.
Referenced by ConstructMe().
int PHG4CylinderDetector::m_Layer private
Definition at line 42 of file PHG4CylinderDetector.h.
Referenced by get_Layer().
PHParameters* PHG4CylinderDetector::m_Params private
Definition at line 37 of file PHG4CylinderDetector.h.
Referenced by ConstructMe().
std::string PHG4CylinderDetector::m_SuperDetector private
Definition at line 43 of file PHG4CylinderDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc