Analysis Software: TrkrHitSet Class Reference
TrkrHitSet Class Reference
Container for storing TrkrHit's.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitSet.h>
Public Types
typedef std::map
< TrkrDefs::hitkey, TrkrHit * > Map
typedef Map::const_iterator ConstIterator
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
TrkrHitSet ()
ctor
virtual ~TrkrHitSet ()
dtor
void identify (std::ostream &os=std::cout) const
TObject functions.
void Reset ()
Clear Event.
void print () const
void setHitSetKey (const TrkrDefs::hitsetkey key)
Set the key for this object.
TrkrDefs::hitsetkey getHitSetKey () const
Get the key for this object.
ConstIterator addHitSpecificKey (const TrkrDefs::hitkey key, TrkrHit *hit)
Add a hit to this container using a specific key.
void removeHit (TrkrDefs::hitkey key)
Remove a hit using its key.
TrkrHit * getHit (const TrkrDefs::hitkey key)
Get a specific hit based on its index.
ConstRange getHits ()
Get all hits.
unsigned int size ()
Get the number of hits stored.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (TrkrHitSet, 1)
storage for TrkrHit objects
Private Attributes
TrkrDefs::hitsetkey m_hitSetKey
Map m_hits
unique key for this object
Detailed Description
Container for storing TrkrHit's.
Container object which stores a set of TrkrHit objects. A single TrkrHitSet is meant to represent a geometric detector object which bounds clustering. Therefore, a TrkrHitSet should contain all TrkrHits which could belong the the same cluster.
Definition at line 28 of file TrkrHitSet.h.
Member Typedef Documentation
typedef Map::const_iterator TrkrHitSet::ConstIterator
Definition at line 33 of file TrkrHitSet.h.
typedef std::pair<ConstIterator, ConstIterator> TrkrHitSet::ConstRange
Definition at line 34 of file TrkrHitSet.h.
typedef std::map<TrkrDefs::hitkey, TrkrHit*> TrkrHitSet::Map
Definition at line 32 of file TrkrHitSet.h.
Constructor & Destructor Documentation
TrkrHitSet::TrkrHitSet ()
ctor
Definition at line 16 of file TrkrHitSet.cc.
TrkrHitSet::~TrkrHitSet () virtual
dtor
Definition at line 22 of file TrkrHitSet.cc.
References Reset().
Member Function Documentation
TrkrHitSet::ConstIterator TrkrHitSet::addHitSpecificKey (const TrkrDefs::hitkey key, TrkrHit * hit)
Add a hit to this container using a specific key.
Parameters
[in] key Hit key
[in] hit Hit to be added.
NOTE: This TrkrHitSet takes ownership of the passed TrkrHit pointer and will delete it in the Reset() method.
Definition at line 81 of file TrkrHitSet.cc.
References m_hits.
TrkrHitSet::ClassDef (TrkrHitSet , 1) private
storage for TrkrHit objects
TrkrHit * TrkrHitSet::getHit (const TrkrDefs::hitkey key)
Get a specific hit based on its index.
Parameters
key of the desired hit
[out] Pointer to the desired hit. nullptr if no hit.
Get a desired hit based on its key.
Definition at line 97 of file TrkrHitSet.cc.
References it, and m_hits.
Referenced by SvtxHitEval::all_truth_hits().
TrkrHitSet::ConstRange TrkrHitSet::getHits ()
Get all hits.
Parameters
[out] Pair of iterator to vector begin and end
Definition at line 110 of file TrkrHitSet.cc.
References m_hits.
Referenced by InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), SvtxEvaluator::fillOutputNtuples(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), PHG4TpcElectronDrift::process_event(), TPCMLDataInterface::process_event(), AnaMvtxTestBeam2019::process_event(), and DumpTrkrHitSetContainer::process_Node().
TrkrDefs::hitsetkey TrkrHitSet::getHitSetKey () const inline
Get the key for this object.
Parameters
[out] object key
Definition at line 55 of file TrkrHitSet.h.
References m_hitSetKey.
Referenced by TrkrHitSetContainer::addHitSet(), InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), identify(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), and AnaMvtxTestBeam2019::process_event().
void TrkrHitSet::identify (std::ostream & os = std::cout) const virtual
TObject functions.
Reimplemented from PHObject.
Definition at line 46 of file TrkrHitSet.cc.
References entry, getHitSetKey(), TrkrDefs::getLayer(), TrkrDefs::getTrkrId(), and m_hits.
Referenced by InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), print(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), TPCMLDataInterface::process_event(), and removeHit().
void TrkrHitSet::print () const
Definition at line 28 of file TrkrHitSet.cc.
References identify().
void TrkrHitSet::removeHit (TrkrDefs::hitkey key)
Remove a hit using its key.
Parameters
[in] key to be removed
Definition at line 60 of file TrkrHitSet.cc.
References identify(), it, and m_hits.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells().
void TrkrHitSet::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 33 of file TrkrHitSet.cc.
References m_hits, and m_hitSetKey.
Referenced by ~TrkrHitSet().
void TrkrHitSet::setHitSetKey (const TrkrDefs::hitsetkey key) inline
Set the key for this object.
Parameters
key
Definition at line 49 of file TrkrHitSet.h.
References m_hitSetKey.
unsigned int TrkrHitSet::size (void) inline
Get the number of hits stored.
Parameters
[out] number of hits
Definition at line 93 of file TrkrHitSet.h.
References m_hits.
Referenced by TPCMLDataInterface::process_event().
Member Data Documentation
Map TrkrHitSet::m_hits private
unique key for this object
Definition at line 97 of file TrkrHitSet.h.
Referenced by addHitSpecificKey(), getHit(), getHits(), identify(), removeHit(), Reset(), and size().
TrkrDefs::hitsetkey TrkrHitSet::m_hitSetKey private
Definition at line 96 of file TrkrHitSet.h.
Referenced by getHitSetKey(), Reset(), and setHitSetKey().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSet.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSet.cc