Analysis Software: LeptoquarksReco Class Reference
LeptoquarksReco Class Reference
#include <analysis/blob/master/EICAnalysis/LeptoquarksReco.h>
Public Member Functions
LeptoquarksReco (std::string filename)
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_save_towers (bool savetower=true)
void set_save_tracks (bool savetracks=true)
void set_beam_energies (float beam_electron, float beam_proton)
void set_reco_jet_collection (std::string newname)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum CALOTYPE {
calo_cemc, calo_ihcal, calo_ohcal, calo_femc,
calo_fhcal, calo_eemc
}
Private Member Functions
int AddTrueTauTag (type_map_tcan &, PHHepMCGenEventMap *)
int AddJetInformation (type_map_tcan &, JetMap *, type_map_cdata *)
int AddJetStructureInformation (type_map_tcan &, type_map_cdata *)
int AddTrackInformation (type_map_tcan &, SvtxTrackMap *, SvtxVertexMap *, SvtxEvalStack *, double)
int WritePidCandidatesToTree (type_map_tcan &)
int AddGlobalEventInformation (type_map_tcan &, type_map_cdata *)
PidCandidate * FindMinDeltaRCandidate (type_map_tcan *, const float, const float)
float CalculateDeltaR (float, float, float, float)
void ResetBranchMap ()
Private Attributes
bool _verbose
bool _save_towers
bool _save_tracks
int _ievent
int _total_pass
std::string _filename
TFile * _tfile
TTree * _t_event
TNtuple * _ntp_tower
TNtuple * _ntp_track
float _ebeam_E
float _pbeam_E
float _tau_jet_emin
std::string _jetcolname
std::map< std::string,
CaloRawTowerEval * > _map_towereval
std::map
< PidCandidate::PROPERTY,
std::vector< float > > _map_tau_candidate_branches
std::map< std::string, float > _map_event_branches
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 37 of file LeptoquarksReco.h.
Member Enumeration Documentation
enum LeptoquarksReco::CALOTYPE private
Enum to identify calorimeter types
Enumerator:
calo_cemc
calo_ihcal
calo_ohcal
calo_femc
calo_fhcal
calo_eemc
Definition at line 140 of file LeptoquarksReco.h.
Constructor & Destructor Documentation
LeptoquarksReco::LeptoquarksReco (std::string filename)
Definition at line 43 of file LeptoquarksReco.C.
Member Function Documentation
int LeptoquarksReco::AddGlobalEventInformation (type_map_tcan & tauCandidateMap, type_map_cdata * map_towers) private
Definition at line 1045 of file LeptoquarksReco.C.
References _map_event_branches, PidCandidate::evtgen_pid, RawTower::get_energy(), RawTowerGeom::get_eta(), RawTowerGeom::get_phi(), PidCandidate::get_property_float(), PidCandidate::get_property_int(), PidCandidate::jet_eta, PidCandidate::jet_phi, and PidCandidate::jet_ptotal.
Referenced by process_event().
int LeptoquarksReco::AddJetInformation (type_map_tcan & tauCandidateMap, JetMap * recojets, type_map_cdata * map_calotower) private
Definition at line 488 of file LeptoquarksReco.C.
References Jet::begin_comp(), RawTowerDefs::CEMC, Jet::CEMC_TOWER, Jet::count_comp(), Jet::end_comp(), JetMap::get(), Jet::get_e(), Jet::get_et(), Jet::get_eta(), Jet::get_mass(), Jet::get_p(), Jet::get_phi(), Jet::get_pt(), RawTowerDefs::HCALIN, Jet::HCALIN_TOWER, RawTowerDefs::HCALOUT, Jet::HCALOUT_TOWER, PidCandidate::jet_eta, PidCandidate::jet_etotal, PidCandidate::jet_etrans, PidCandidate::jet_id, PidCandidate::jet_minv, PidCandidate::jet_mtrans, PidCandidate::jet_ncomp, PidCandidate::jet_ncomp_above_0p1, PidCandidate::jet_ncomp_above_1, PidCandidate::jet_ncomp_above_10, PidCandidate::jet_ncomp_emcal, PidCandidate::jet_phi, PidCandidate::jet_ptotal, PidCandidate::jet_ptrans, RawTowerDefs::NONE, and Jet::size_comp().
Referenced by process_event().
int LeptoquarksReco::AddJetStructureInformation (type_map_tcan & tauCandidateMap, type_map_cdata * map_towers) private
Definition at line 565 of file LeptoquarksReco.C.
References _ievent, _ntp_tower, _save_towers, CalculateDeltaR(), RawTowerDefs::CEMC, PidCandidate::evtgen_decay_hcharged, PidCandidate::evtgen_decay_lcharged, PidCandidate::evtgen_decay_prong, PidCandidate::evtgen_eta, PidCandidate::evtgen_etotal, PidCandidate::evtgen_phi, PidCandidate::evtgen_pid, RawTower::get_energy(), RawTowerGeom::get_eta(), RawTowerGeom::get_phi(), PidCandidate::jet_eta, PidCandidate::jet_etotal, PidCandidate::jet_id, PidCandidate::jet_phi, PidCandidate::jetshape_econe_r01, PidCandidate::jetshape_econe_r02, PidCandidate::jetshape_econe_r03, PidCandidate::jetshape_econe_r04, PidCandidate::jetshape_econe_r05, PidCandidate::jetshape_emcal_econe_r01, PidCandidate::jetshape_emcal_econe_r02, PidCandidate::jetshape_emcal_econe_r03, PidCandidate::jetshape_emcal_econe_r04, PidCandidate::jetshape_emcal_econe_r05, PidCandidate::jetshape_emcal_r90, PidCandidate::jetshape_emcal_radius, PidCandidate::jetshape_emcal_rms, PidCandidate::jetshape_r90, PidCandidate::jetshape_radius, PidCandidate::jetshape_rms, and rms().
Referenced by process_event().
int LeptoquarksReco::AddTrackInformation (type_map_tcan & tauCandidateMap, SvtxTrackMap * trackmap, SvtxVertexMap * vertexmap, SvtxEvalStack * svtxevalstack, double R_max) private
Definition at line 808 of file LeptoquarksReco.C.
References _ievent, _ntp_track, _save_tracks, Average(), SvtxTrackMap::begin(), CalculateDeltaR(), SvtxTrackMap::end(), PidCandidate::evtgen_decay_hcharged, PidCandidate::evtgen_decay_lcharged, PidCandidate::evtgen_decay_prong, PidCandidate::evtgen_eta, PidCandidate::evtgen_etotal, PidCandidate::evtgen_phi, PidCandidate::evtgen_pid, SvtxTrack::get_charge(), SvtxTrack::get_eta(), SvtxTrack::get_p(), SvtxTrack::get_phi(), SvtxTrack::get_quality(), SvtxEvalStack::get_track_eval(), SvtxEvalStack::get_truth_eval(), SvtxTruthEval::get_vertex(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PidCandidate::jet_eta, PidCandidate::jet_etotal, PidCandidate::jet_id, PidCandidate::jet_phi, SvtxTrackEval::max_truth_particle_by_nclusters(), PidCandidate::tracks_chargesum_R, PidCandidate::tracks_chargesum_r02, PidCandidate::tracks_chargesum_r04, PidCandidate::tracks_count_R, PidCandidate::tracks_count_r02, PidCandidate::tracks_count_r04, PidCandidate::tracks_rmax_R, PidCandidate::tracks_rmax_r02, PidCandidate::tracks_rmax_r04, and PidCandidate::tracks_vertex.
Referenced by process_event().
int LeptoquarksReco::AddTrueTauTag (type_map_tcan & tauCandidateMap, PHHepMCGenEventMap * genevtmap) private
Definition at line 326 of file LeptoquarksReco.C.
References _map_event_branches, PidCandidate::evtgen_decay_hcharged, PidCandidate::evtgen_decay_lcharged, PidCandidate::evtgen_decay_prong, PidCandidate::evtgen_eta, PidCandidate::evtgen_etotal, PidCandidate::evtgen_phi, PidCandidate::evtgen_pid, TruthTrackerHepMC::FindDaughterParticle(), TruthTrackerHepMC::FindDecayParticles(), FindMinDeltaRCandidate(), TruthTrackerHepMC::FindParticle(), PidCandidate::get_property_int(), PHHepMCGenEvent::getEvent(), PHHepMCGenEventMap::rbegin(), PHHepMCGenEventMap::rend(), TruthTrackerHepMC::set_hepmc_geneventmap(), and PidCandidate::set_property().
Referenced by process_event().
float LeptoquarksReco::CalculateDeltaR (float eta1, float phi1, float eta2, float phi2) private
Calculate Delta R ("distance in eta-phi space") between two sets of eta, phi angles
Definition at line 1030 of file LeptoquarksReco.C.
Referenced by AddJetStructureInformation(), AddTrackInformation(), and FindMinDeltaRCandidate().
int LeptoquarksReco::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 1174 of file LeptoquarksReco.C.
References _ntp_tower, _ntp_track, _t_event, and _tfile.
PidCandidate * LeptoquarksReco::FindMinDeltaRCandidate (type_map_tcan * candidates, const float eta_ref, const float phi_ref) private
Find tau candidate in map that is closest to given eta, phi angle
Definition at line 989 of file LeptoquarksReco.C.
References CalculateDeltaR(), PidCandidate::jet_eta, PidCandidate::jet_phi, and phi.
Referenced by AddTrueTauTag().
int LeptoquarksReco::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 62 of file LeptoquarksReco.C.
References _filename, _ievent, _map_event_branches, _map_tau_candidate_branches, _ntp_tower, _ntp_track, _save_towers, _save_tracks, _t_event, _tfile, PidCandidate::evtgen_decay_hcharged, PidCandidate::evtgen_decay_lcharged, PidCandidate::evtgen_decay_prong, PidCandidate::evtgen_eta, PidCandidate::evtgen_etotal, PidCandidate::evtgen_phi, PidCandidate::evtgen_pid, PidCandidate::evtgen_ptotal, PidCandidate::evtgen_theta, PidCandidate::get_property_info(), PidCandidate::jet_eta, PidCandidate::jet_etotal, PidCandidate::jet_etrans, PidCandidate::jet_id, PidCandidate::jet_minv, PidCandidate::jet_mtrans, PidCandidate::jet_ncomp, PidCandidate::jet_ncomp_above_0p1, PidCandidate::jet_ncomp_above_1, PidCandidate::jet_ncomp_above_10, PidCandidate::jet_ncomp_emcal, PidCandidate::jet_phi, PidCandidate::jet_ptotal, PidCandidate::jet_ptrans, PidCandidate::jetshape_econe_r01, PidCandidate::jetshape_econe_r02, PidCandidate::jetshape_econe_r03, PidCandidate::jetshape_econe_r04, PidCandidate::jetshape_econe_r05, PidCandidate::jetshape_emcal_econe_r01, PidCandidate::jetshape_emcal_econe_r02, PidCandidate::jetshape_emcal_econe_r03, PidCandidate::jetshape_emcal_econe_r04, PidCandidate::jetshape_emcal_econe_r05, PidCandidate::jetshape_emcal_r90, PidCandidate::jetshape_emcal_radius, PidCandidate::jetshape_emcal_rms, PidCandidate::jetshape_r90, PidCandidate::jetshape_radius, PidCandidate::jetshape_rms, PidCandidate::tracks_chargesum_R, PidCandidate::tracks_chargesum_r02, PidCandidate::tracks_chargesum_r04, PidCandidate::tracks_count_R, PidCandidate::tracks_count_r02, PidCandidate::tracks_count_r04, PidCandidate::tracks_rmax_R, PidCandidate::tracks_rmax_r02, PidCandidate::tracks_rmax_r04, and PidCandidate::tracks_vertex.
int LeptoquarksReco::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 174 of file LeptoquarksReco.C.
References _ievent, _jetcolname, _t_event, _tau_jet_emin, Fun4AllReturnCodes::ABORTEVENT, AddGlobalEventInformation(), AddJetInformation(), AddJetStructureInformation(), AddTrackInformation(), AddTrueTauTag(), JetMap::begin(), RawTowerDefs::CEMC, RawTowerDefs::convert_caloid_to_name(), RawTowerDefs::EEMC, JetMap::end(), PidCandidate::evtgen_pid, RawTowerDefs::FEMC, RawTowerDefs::FHCAL, JetMap::get_par(), RawTowerDefs::HCALIN, RawTowerDefs::HCALOUT, i, PidCandidate::jet_id, PHWHERE, ResetBranchMap(), PidCandidatev1::set_candidate_id(), PidCandidatev1::set_property(), and WritePidCandidatesToTree().
void LeptoquarksReco::ResetBranchMap () private
Reset branch maps for each event
Definition at line 1151 of file LeptoquarksReco.C.
References _map_event_branches, and _map_tau_candidate_branches.
Referenced by process_event().
void LeptoquarksReco::set_beam_energies (float beam_electron, float beam_proton) inline
Definition at line 67 of file LeptoquarksReco.h.
References _ebeam_E, and _pbeam_E.
void LeptoquarksReco::set_reco_jet_collection (std::string newname) inline
Definition at line 74 of file LeptoquarksReco.h.
References _jetcolname.
Referenced by G4_Lepto().
void LeptoquarksReco::set_save_towers (bool savetower = true) inline
Definition at line 53 of file LeptoquarksReco.h.
References _save_towers.
Referenced by G4_Lepto().
void LeptoquarksReco::set_save_tracks (bool savetracks = true) inline
Definition at line 60 of file LeptoquarksReco.h.
References _save_tracks.
Referenced by G4_Lepto().
int LeptoquarksReco::WritePidCandidatesToTree (type_map_tcan & tauCandidateMap) private
Definition at line 952 of file LeptoquarksReco.C.
References _map_tau_candidate_branches, PidCandidate::get_property_info(), PidCandidate::type_float, PidCandidate::type_int, PidCandidate::type_uint, and PidCandidate::type_unknown.
Referenced by process_event().
Member Data Documentation
float LeptoquarksReco::_ebeam_E private
Definition at line 97 of file LeptoquarksReco.h.
Referenced by set_beam_energies().
std::string LeptoquarksReco::_filename private
Definition at line 88 of file LeptoquarksReco.h.
Referenced by Init().
int LeptoquarksReco::_ievent private
Definition at line 85 of file LeptoquarksReco.h.
Referenced by AddJetStructureInformation(), AddTrackInformation(), Init(), and process_event().
std::string LeptoquarksReco::_jetcolname private
name of jet collection
Definition at line 104 of file LeptoquarksReco.h.
Referenced by process_event(), and set_reco_jet_collection().
std::map< std::string , float > LeptoquarksReco::_map_event_branches private
Map of Event properties that will be written to output ROOT Tree
Definition at line 116 of file LeptoquarksReco.h.
Referenced by AddGlobalEventInformation(), AddTrueTauTag(), Init(), and ResetBranchMap().
std::map< PidCandidate::PROPERTY , std::vector< float > > LeptoquarksReco::_map_tau_candidate_branches private
Map of PidCandidate properties that will be written to output ROOT Tree
Definition at line 112 of file LeptoquarksReco.h.
Referenced by Init(), ResetBranchMap(), and WritePidCandidatesToTree().
std::map< std::string, CaloRawTowerEval* > LeptoquarksReco::_map_towereval private
CaloRawTowerEvaluators to access tru particle info for given towers
Definition at line 108 of file LeptoquarksReco.h.
TNtuple* LeptoquarksReco::_ntp_tower private
Definition at line 93 of file LeptoquarksReco.h.
Referenced by AddJetStructureInformation(), End(), and Init().
TNtuple* LeptoquarksReco::_ntp_track private
Definition at line 94 of file LeptoquarksReco.h.
Referenced by AddTrackInformation(), End(), and Init().
float LeptoquarksReco::_pbeam_E private
Definition at line 98 of file LeptoquarksReco.h.
Referenced by set_beam_energies().
bool LeptoquarksReco::_save_towers private
Definition at line 82 of file LeptoquarksReco.h.
Referenced by AddJetStructureInformation(), Init(), and set_save_towers().
bool LeptoquarksReco::_save_tracks private
Definition at line 83 of file LeptoquarksReco.h.
Referenced by AddTrackInformation(), Init(), and set_save_tracks().
TTree* LeptoquarksReco::_t_event private
Definition at line 92 of file LeptoquarksReco.h.
Referenced by End(), Init(), and process_event().
float LeptoquarksReco::_tau_jet_emin private
Definition at line 101 of file LeptoquarksReco.h.
Referenced by process_event().
TFile* LeptoquarksReco::_tfile private
Definition at line 89 of file LeptoquarksReco.h.
Referenced by End(), and Init().
int LeptoquarksReco::_total_pass private
Definition at line 86 of file LeptoquarksReco.h.
bool LeptoquarksReco::_verbose private
Definition at line 81 of file LeptoquarksReco.h.
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/LeptoquarksReco.h
analysis/blob/master/EICAnalysis/LeptoquarksReco.C