Analysis Software: analysis/blob/master/Prototype2/hcalLab/hcalUtil.C File Reference
hcalUtil.C File Reference
#include <iomanip>
#include <algorithm>
#include <numeric>
#include <iostream>
#include <fstream>
#include <cmath>
#include <ctime>
#include <cstdlib>
#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <fileEventiterator.h>
#include <Event.h>
#include <EventTypes.h>
#include <PHTimeStamp.h>
#include <packetConstants.h>
#include <packet.h>
#include <packet_hbd_fpgashort.h>
#include "hcalUtil.h"
#include "hLabHelper.C"
#include "hcalHelper.C"
#include "hcalTree.C"
#include "tileHelper.C"
#include "tileTree.C"
Functions
Double_t ps (Double_t *chadc, Double_t *par)
Int_t calibPeaks (0)
Int_t calibMode (0)
Double_t spCalib (10.)
Double_t sipmPeaks (Double_t *x, Double_t *par)
Int_t sipmCalib (TString &hName, Int_t mode)
Double_t AsymToX (Double_t ax)
Double_t signalShape (Double_t *x, Double_t *par)
Double_t erfunc (Double_t *x, Double_t *par)
Double_t erf_g (Double_t *x, Double_t *par)
Double_t powerFun (Double_t *x, Double_t *par)
Double_t power_g (Double_t *x, Double_t *par)
Variables
TCanvas * fitFunc
TCanvas * scCalibDisplay
static const int cosmicruns = 12
int cosmicRN [cosmicruns] = {212, 215, 216, 218, 223, 337, 338, 339, 405, 406, 229, 240}
static const int pedruns = 1
int pedcalibRN [pedruns] = {646}
static const int ledruns = 1
int ledcalibRN [ledruns] = {647}
Double_t par0 [] = { 1., (Double_t)NSAMPLES/2, 3., 2., PEDESTAL, 0. }
Double_t par0Max [] = { -100., (Double_t)NSAMPLES, 4., 5., 50000., 0.3}
Double_t par0Min [] = {-50000., 0., 2., 0., -50000., -0.3}
TString runId
Function Documentation
Double_t AsymToX (Double_t ax)
Definition at line 303 of file hcalUtil.C.
Referenced by tileHelper::collectTileSummary().
Int_t calibMode (0)
Referenced by sipmCalib(), and sipmPeaks().
Int_t calibPeaks (0)
Referenced by sipmCalib(), and sipmPeaks().
Double_t erf_g (Double_t * x, Double_t * par)
Definition at line 346 of file hcalUtil.C.
References g.
Double_t erfunc (Double_t * x, Double_t * par)
Definition at line 339 of file hcalUtil.C.
Referenced by hcalUtil::shapeFit().
Double_t power_g (Double_t * x, Double_t * par)
Definition at line 360 of file hcalUtil.C.
References g.
Referenced by hcalUtil::twrMipFit(), and hcalUtil::twrTimeFit().
Double_t powerFun (Double_t * x, Double_t * par)
Definition at line 352 of file hcalUtil.C.
Referenced by hcalUtil::twrMipFit(), and hcalUtil::twrTimeFit().
Double_t ps (Double_t * chadc, Double_t * par)
Definition at line 102 of file hcalUtil.C.
References g, n, norm, sum(), and x.
Referenced by ReadLikelihoodD::GetMvaValue__(), luclus(), ludecy(), luexec(), lujmas(), lulist(), lushow(), lusphe(), luthru(), pyclus(), pydecy(), pyexec(), pyjmas(), pylist(), pymael(), pyrand(), pyresd(), pyshow(), pysphe(), pysspa(), pytbhg(), pytbhq(), and pythru().
Double_t signalShape (Double_t * x, Double_t * par)
Definition at line 310 of file hcalUtil.C.
References pedestal(), and signal().
Int_t sipmCalib (TString & hName, Int_t mode)
Definition at line 155 of file hcalUtil.C.
References calibMode(), calibPeaks(), cd(), data, Draw(), fit(), peaks(), printf(), s, sipmPeaks(), spCalib(), and ymax.
Double_t sipmPeaks (Double_t * x, Double_t * par)
Definition at line 133 of file hcalUtil.C.
References calibMode(), calibPeaks(), norm, and spCalib().
Referenced by sipmCalib().
Double_t spCalib (10.)
Referenced by sipmCalib(), and sipmPeaks().
Variable Documentation
int cosmicRN[cosmicruns] = {212, 215, 216, 218, 223, 337, 338, 339, 405, 406, 229, 240}
Definition at line 79 of file hcalUtil.C.
const int cosmicruns = 12 static
Definition at line 78 of file hcalUtil.C.
TCanvas* fitFunc
Definition at line 67 of file hcalUtil.C.
int ledcalibRN[ledruns] = {647}
Definition at line 85 of file hcalUtil.C.
const int ledruns = 1 static
Definition at line 84 of file hcalUtil.C.
Double_t par0[] = { 1., (Double_t)NSAMPLES/2, 3., 2., PEDESTAL, 0. }
Definition at line 90 of file hcalUtil.C.
Double_t par0Max[] = { -100., (Double_t)NSAMPLES, 4., 5., 50000., 0.3}
Definition at line 91 of file hcalUtil.C.
Double_t par0Min[] = {-50000., 0., 2., 0., -50000., -0.3}
Definition at line 93 of file hcalUtil.C.
int pedcalibRN[pedruns] = {646}
Definition at line 83 of file hcalUtil.C.
const int pedruns = 1 static
Definition at line 82 of file hcalUtil.C.
TString runId
Definition at line 96 of file hcalUtil.C.
Referenced by hLabHelper::attachrootrun(), extractMIPEnergy(), extractShowerCalibFactor_OHCal(), plotQA_tower_distribution(), tileHelper::runtilesummary::runtilesummary(), hLabHelper::runToPRDFFile(), hLabHelper::runToRootFile(), sccalib(), tileHelper::status(), tileHelper::tilePattern(), and tileHelper::tileTriggerDisplay().
TCanvas* scCalibDisplay
Definition at line 69 of file hcalUtil.C.
Referenced by sccalib().