Analysis Software: TrkrClusterHitAssoc Class Reference
TrkrClusterHitAssoc Class Reference
Class for associating clusters to the hits that went into them.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssoc.h>
Public Types
typedef std::multimap
< TrkrDefs::cluskey,
TrkrDefs::hitkey > MMap
typedefs for convenience
typedef MMap::iterator Iterator
typedef MMap::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
TrkrClusterHitAssoc ()
ctor
virtual ~TrkrClusterHitAssoc ()
dtor
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
void addAssoc (TrkrDefs::cluskey ckey, unsigned int hidx)
Add association between cluster and hit.
ConstRange getHits (TrkrDefs::cluskey ckey)
Get all the hits associated with a cluster by key.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (TrkrClusterHitAssoc, 1)
Private Attributes
MMap m_map
Detailed Description
Class for associating clusters to the hits that went into them.
Store the associations between clusters and the hits that went into them.
Definition at line 23 of file TrkrClusterHitAssoc.h.
Member Typedef Documentation
typedef MMap::const_iterator TrkrClusterHitAssoc::ConstIterator
Definition at line 29 of file TrkrClusterHitAssoc.h.
typedef std::pair<ConstIterator, ConstIterator> TrkrClusterHitAssoc::ConstRange
Definition at line 31 of file TrkrClusterHitAssoc.h.
typedef MMap::iterator TrkrClusterHitAssoc::Iterator
Definition at line 28 of file TrkrClusterHitAssoc.h.
typedef std::multimap<TrkrDefs::cluskey, TrkrDefs::hitkey> TrkrClusterHitAssoc::MMap
typedefs for convenience
Definition at line 27 of file TrkrClusterHitAssoc.h.
typedef std::pair<Iterator, Iterator> TrkrClusterHitAssoc::Range
Definition at line 30 of file TrkrClusterHitAssoc.h.
Constructor & Destructor Documentation
TrkrClusterHitAssoc::TrkrClusterHitAssoc ()
ctor
Definition at line 12 of file TrkrClusterHitAssoc.cc.
TrkrClusterHitAssoc::~TrkrClusterHitAssoc () virtual
dtor
Definition at line 18 of file TrkrClusterHitAssoc.cc.
Member Function Documentation
void TrkrClusterHitAssoc::addAssoc (TrkrDefs::cluskey ckey, unsigned int hidx)
Add association between cluster and hit.
Parameters
[in] ckey Cluster key
[in] hidx Index of the hit in TrkrHitSet
Definition at line 48 of file TrkrClusterHitAssoc.cc.
References m_map.
Referenced by InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), TpcClusterizer::process_event(), and TpcPrototypeClusterizer::process_event().
TrkrClusterHitAssoc::ClassDef (TrkrClusterHitAssoc , 1) private
TrkrClusterHitAssoc::ConstRange TrkrClusterHitAssoc::getHits (TrkrDefs::cluskey ckey)
Get all the hits associated with a cluster by key.
Parameters
[in] ckey Cluster key
[out] Range over hits associated with ckey
Definition at line 54 of file TrkrClusterHitAssoc.cc.
References m_map.
Referenced by SvtxClusterEval::all_truth_hits(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), and PHTruthTrackSeeding::Process().
void TrkrClusterHitAssoc::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 29 of file TrkrClusterHitAssoc.cc.
References entry, and m_map.
Referenced by InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), TpcClusterizer::process_event(), and TpcPrototypeClusterizer::process_event().
void TrkrClusterHitAssoc::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 23 of file TrkrClusterHitAssoc.cc.
References m_map.
Member Data Documentation
MMap TrkrClusterHitAssoc::m_map private
Definition at line 56 of file TrkrClusterHitAssoc.h.
Referenced by addAssoc(), getHits(), identify(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssoc.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterHitAssoc.cc