Analysis Software: PHG4SimpleEventGenerator Class Reference
PHG4SimpleEventGenerator Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h>
Public Types
enum FUNCTION { Uniform, Gaus }
supported function distributions
Public Member Functions
PHG4SimpleEventGenerator (const std::string &name="EVTGENERATOR")
virtual ~PHG4SimpleEventGenerator ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void add_particles (const std::string &name, const unsigned int count)
interface for adding particles by name
void add_particles (const int pid, const unsigned int count)
interface for adding particle by pid
void set_t0 (const double t)
set the starting time for the event
void set_eta_range (const double eta_min, const double eta_max)
range of randomized eta values
void set_phi_range (const double phi_min, const double phi_max)
range of randomized phi values
void set_pt_range (const double pt_min, const double pt_max, const double pt_gaus_width=0)
void set_p_range (const double p_min, const double p_max, const double p_gaus_width=0)
void set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
void set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
void set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
void set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
void set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
Public Member Functions inherited from PHG4ParticleGeneratorBase
virtual ~PHG4ParticleGeneratorBase ()
virtual void set_name (const std::string &particle="proton")
virtual void set_pid (const int pid)
virtual void set_mom (const double x, const double y, const double z)
virtual void set_vtx (const double x, const double y, const double z)
virtual double get_vtx_x () const
virtual double get_vtx_y () const
virtual double get_vtx_z () const
virtual double get_t0 () const
virtual void Print (const std::string &what="ALL") const
virtual void PrintParticles (const std::string &what="ALL") const
virtual void AddParticle (const std::string &particle, const double x, const double y, const double z)
virtual void AddParticle (const int pid, const double x, const double y, const double z)
virtual void Embed (const int i=1)
virtual int ReuseExistingVertex (PHCompositeNode *topNode)
int get_reuse_existing_vertex () const
void set_reuse_existing_vertex (const int i=1)
void set_seed (const unsigned int iseed)
unsigned int get_seed () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
double smearvtx (const double position, const double width, FUNCTION dist) const
Private Attributes
std::vector< std::pair< int,
unsigned int > > _particle_codes
std::vector< std::pair
< std::string, unsigned int > > _particle_names
FUNCTION _vertex_func_x
FUNCTION _vertex_func_y
FUNCTION _vertex_func_z
double _t0
double _vertex_x
double _vertex_y
double _vertex_z
double _vertex_width_x
double _vertex_width_y
double _vertex_width_z
double _vertex_offset_x
double _vertex_offset_y
double _vertex_offset_z
FUNCTION _vertex_size_func_r
double _vertex_size_mean
double _vertex_size_width
double _eta_min
double _eta_max
double _phi_min
double _phi_max
double _pt_min
double _pt_max
double _pt_gaus_width
double _p_min
double _p_max
double _p_gaus_width
PHG4InEvent * _ineve
Additional Inherited Members
Protected Member Functions inherited from PHG4ParticleGeneratorBase
PHG4ParticleGeneratorBase (const std::string &name="GENERATORBASE")
int get_pdgcode (const std::string &name) const
std::string get_pdgname (const int pdgcode) const
double get_mass (const int pdgcode) const
void CheckAndCreateParticleVector ()
void SetParticleId (PHG4Particle *particle, PHG4InEvent *ineve)
Protected Attributes inherited from PHG4ParticleGeneratorBase
int embedflag
int reuse_existing_vertex
double vtx_x
double vtx_y
double vtx_z
double t0
std::vector< PHG4Particle * > particlelist
unsigned int seed
gsl_rng * RandomGenerator
Detailed Description
Definition at line 15 of file PHG4SimpleEventGenerator.h.
Member Enumeration Documentation
enum PHG4SimpleEventGenerator::FUNCTION
supported function distributions
Enumerator:
Uniform
Gaus
Definition at line 20 of file PHG4SimpleEventGenerator.h.
Constructor & Destructor Documentation
PHG4SimpleEventGenerator::PHG4SimpleEventGenerator (const std::string & name = "EVTGENERATOR")
Definition at line 28 of file PHG4SimpleEventGenerator.cc.
virtual PHG4SimpleEventGenerator::~PHG4SimpleEventGenerator () inline virtual
Definition at line 23 of file PHG4SimpleEventGenerator.h.
Member Function Documentation
void PHG4SimpleEventGenerator::add_particles (const std::string & name, const unsigned int count)
interface for adding particles by name
Definition at line 63 of file PHG4SimpleEventGenerator.cc.
References _particle_names.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::add_particles (const int pid, const unsigned int count)
interface for adding particle by pid
Definition at line 68 of file PHG4SimpleEventGenerator.cc.
References _particle_codes.
int PHG4SimpleEventGenerator::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 167 of file PHG4SimpleEventGenerator.cc.
References _eta_max, _eta_min, _ineve, _particle_codes, _particle_names, _phi_max, _phi_min, _pt_max, _pt_min, _t0, _vertex_func_x, _vertex_func_y, _vertex_func_z, _vertex_offset_x, _vertex_offset_y, _vertex_offset_z, _vertex_size_func_r, _vertex_size_mean, _vertex_size_width, _vertex_width_x, _vertex_width_y, _vertex_width_z, _vertex_x, _vertex_y, _vertex_z, Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), Gaus, PHG4ParticleGeneratorBase::get_pdgname(), PHG4ParticleGeneratorBase::get_reuse_existing_vertex(), PHG4ParticleGeneratorBase::get_seed(), i, PHWHERE, Uniform, and Fun4AllBase::Verbosity().
int PHG4SimpleEventGenerator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 242 of file PHG4SimpleEventGenerator.cc.
References _eta_max, _eta_min, _ineve, _p_gaus_width, _p_max, _p_min, _particle_names, _phi_max, _phi_min, _pt_gaus_width, _pt_max, _pt_min, _t0, _vertex_func_x, _vertex_func_y, _vertex_func_z, _vertex_offset_x, _vertex_offset_y, _vertex_offset_z, _vertex_size_func_r, _vertex_size_mean, _vertex_size_width, _vertex_width_x, _vertex_width_y, _vertex_width_z, _vertex_x, _vertex_y, _vertex_z, PHG4InEvent::AddEmbeddedParticle(), PHG4InEvent::AddParticle(), PHG4InEvent::AddVtx(), PHG4ParticleGeneratorBase::embedflag, Fun4AllReturnCodes::EVENT_OK, PHG4ParticleGeneratorBase::get_mass(), PHG4ParticleGeneratorBase::get_pdgcode(), i, PHG4InEvent::identify(), j, nparticles, phi, PHWHERE, r, PHG4ParticleGeneratorBase::RandomGenerator, PHG4ParticleGeneratorBase::reuse_existing_vertex, PHG4ParticleGeneratorBase::ReuseExistingVertex(), PHG4Particle::set_e(), PHG4Particle::set_name(), PHG4Particle::set_parent_id(), PHG4Particle::set_pid(), PHG4Particle::set_px(), PHG4Particle::set_py(), PHG4Particle::set_pz(), PHG4Particle::set_track_id(), PHG4Particle::set_vtx_id(), smearvtx(), Fun4AllBase::Verbosity(), PHG4ParticleGeneratorBase::vtx_x, PHG4ParticleGeneratorBase::vtx_y, PHG4ParticleGeneratorBase::vtx_z, x, y, and z.
void PHG4SimpleEventGenerator::set_eta_range (const double eta_min, const double eta_max)
range of randomized eta values
Definition at line 73 of file PHG4SimpleEventGenerator.cc.
References _eta_max, _eta_min, max, and min.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_existing_vertex_offset_vector (const double x, const double y, const double z)
set an offset vector from the existing vertex
Definition at line 149 of file PHG4SimpleEventGenerator.cc.
References _vertex_offset_x, _vertex_offset_y, _vertex_offset_z, x, y, and z.
Referenced by ConfigureInput(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_p_range (const double p_min, const double p_max, const double p_gaus_width = 0)
range of randomized p values
Parameters
[in] p_gaus_width if non-zero, further apply a Gauss smearing to the p_min - p_max flat distribution
Definition at line 112 of file PHG4SimpleEventGenerator.cc.
References _p_gaus_width, _p_max, _p_min, _pt_gaus_width, _pt_max, _pt_min, assert, max, and min.
Referenced by ConstructGeometry(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_TPC(), Fun4All_G4_W(), and Jin_BJet().
void PHG4SimpleEventGenerator::set_phi_range (const double phi_min, const double phi_max)
range of randomized phi values
Definition at line 84 of file PHG4SimpleEventGenerator.cc.
References _phi_max, _phi_min, max, and min.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_pt_range (const double pt_min, const double pt_max, const double pt_gaus_width = 0)
range of randomized pt values
Parameters
[in] pt_gaus_width if non-zero, further apply a Gauss smearing to the pt_min - pt_max flat distribution
Definition at line 95 of file PHG4SimpleEventGenerator.cc.
References _p_gaus_width, _p_max, _p_min, _pt_gaus_width, _pt_max, _pt_min, assert, max, and min.
Referenced by ConfigureInput(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_single_particle(), and Wrapper().
void PHG4SimpleEventGenerator::set_t0 (const double t) inline virtual
set the starting time for the event
Reimplemented from PHG4ParticleGeneratorBase.
Definition at line 35 of file PHG4SimpleEventGenerator.h.
References _t0, and t.
void PHG4SimpleEventGenerator::set_vertex_distribution_function (FUNCTION x, FUNCTION y, FUNCTION z)
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 128 of file PHG4SimpleEventGenerator.cc.
References _vertex_func_x, _vertex_func_y, _vertex_func_z, x, y, and z.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_distribution_mean (const double x, const double y, const double z)
set the mean value of the vertex distribution
Definition at line 135 of file PHG4SimpleEventGenerator.cc.
References _vertex_x, _vertex_y, _vertex_z, x, y, and z.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_distribution_width (const double x, const double y, const double z)
set the width of the vertex distribution function about the mean
Definition at line 142 of file PHG4SimpleEventGenerator.cc.
References _vertex_width_x, _vertex_width_y, _vertex_width_z, x, y, and z.
Referenced by ConfigureInput(), ConstructGeometry(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_TPC(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_size_function (FUNCTION r)
set the distribution function of particles about the vertex
Definition at line 156 of file PHG4SimpleEventGenerator.cc.
References _vertex_size_func_r, and r.
Referenced by ConfigureInput(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void PHG4SimpleEventGenerator::set_vertex_size_parameters (const double mean, const double width)
set the dimensions of the distribution of particles about the vertex
Definition at line 161 of file PHG4SimpleEventGenerator.cc.
References _vertex_size_mean, and _vertex_size_width.
Referenced by ConfigureInput(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_G4_W(), Fun4All_Generator_Display(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
double PHG4SimpleEventGenerator::smearvtx (const double position, const double width, FUNCTION dist) const private
Definition at line 343 of file PHG4SimpleEventGenerator.cc.
References Gaus, position, PHG4ParticleGeneratorBase::RandomGenerator, and Uniform.
Referenced by process_event().
Member Data Documentation
double PHG4SimpleEventGenerator::_eta_max private
Definition at line 93 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_eta_range().
double PHG4SimpleEventGenerator::_eta_min private
Definition at line 92 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_eta_range().
PHG4InEvent* PHG4SimpleEventGenerator::_ineve private
Definition at line 103 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), and process_event().
double PHG4SimpleEventGenerator::_p_gaus_width private
Definition at line 101 of file PHG4SimpleEventGenerator.h.
Referenced by process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::_p_max private
Definition at line 100 of file PHG4SimpleEventGenerator.h.
Referenced by process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::_p_min private
Definition at line 99 of file PHG4SimpleEventGenerator.h.
Referenced by process_event(), set_p_range(), and set_pt_range().
std::vector<std::pair<int, unsigned int> > PHG4SimpleEventGenerator::_particle_codes private
Definition at line 74 of file PHG4SimpleEventGenerator.h.
Referenced by add_particles(), and InitRun().
std::vector<std::pair<std::string, unsigned int> > PHG4SimpleEventGenerator::_particle_names private
Definition at line 75 of file PHG4SimpleEventGenerator.h.
Referenced by add_particles(), InitRun(), and process_event().
double PHG4SimpleEventGenerator::_phi_max private
Definition at line 95 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_phi_range().
double PHG4SimpleEventGenerator::_phi_min private
Definition at line 94 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_phi_range().
double PHG4SimpleEventGenerator::_pt_gaus_width private
Definition at line 98 of file PHG4SimpleEventGenerator.h.
Referenced by process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::_pt_max private
Definition at line 97 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::_pt_min private
Definition at line 96 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), set_p_range(), and set_pt_range().
double PHG4SimpleEventGenerator::_t0 private
Definition at line 79 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_t0().
FUNCTION PHG4SimpleEventGenerator::_vertex_func_x private
Definition at line 76 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_function().
FUNCTION PHG4SimpleEventGenerator::_vertex_func_y private
Definition at line 77 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_function().
FUNCTION PHG4SimpleEventGenerator::_vertex_func_z private
Definition at line 78 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_function().
double PHG4SimpleEventGenerator::_vertex_offset_x private
Definition at line 86 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_existing_vertex_offset_vector().
double PHG4SimpleEventGenerator::_vertex_offset_y private
Definition at line 87 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_existing_vertex_offset_vector().
double PHG4SimpleEventGenerator::_vertex_offset_z private
Definition at line 88 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_existing_vertex_offset_vector().
FUNCTION PHG4SimpleEventGenerator::_vertex_size_func_r private
Definition at line 89 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_size_function().
double PHG4SimpleEventGenerator::_vertex_size_mean private
Definition at line 90 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_size_parameters().
double PHG4SimpleEventGenerator::_vertex_size_width private
Definition at line 91 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_size_parameters().
double PHG4SimpleEventGenerator::_vertex_width_x private
Definition at line 83 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_width().
double PHG4SimpleEventGenerator::_vertex_width_y private
Definition at line 84 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_width().
double PHG4SimpleEventGenerator::_vertex_width_z private
Definition at line 85 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_width().
double PHG4SimpleEventGenerator::_vertex_x private
Definition at line 80 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_mean().
double PHG4SimpleEventGenerator::_vertex_y private
Definition at line 81 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_mean().
double PHG4SimpleEventGenerator::_vertex_z private
Definition at line 82 of file PHG4SimpleEventGenerator.h.
Referenced by InitRun(), process_event(), and set_vertex_distribution_mean().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc