Analysis Software: RawTowerContainer Class Reference
RawTowerContainer Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerContainer.h>
Public Types
typedef std::map
< RawTowerDefs::keytype,
RawTower * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
RawTowerContainer (RawTowerDefs::CalorimeterId caloid=RawTowerDefs::NONE)
virtual ~RawTowerContainer ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
void setCalorimeterID (RawTowerDefs::CalorimeterId caloid)
RawTowerDefs::CalorimeterId getCalorimeterID ()
ConstIterator AddTower (const unsigned int ieta, const unsigned int iphi, RawTower *twr)
ConstIterator AddTower (RawTowerDefs::keytype key, RawTower *twr)
RawTower * getTower (RawTowerDefs::keytype key)
const RawTower * getTower (RawTowerDefs::keytype key) const
RawTower * getTower (const unsigned int ieta, const unsigned int iphi)
const RawTower * getTower (const unsigned int ieta, const unsigned int iphi) const
ConstRange getTowers (void) const
return all towers
Range getTowers (void)
unsigned int size () const
void compress (const double emin)
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::CalorimeterId _caloid
Map _towers
Detailed Description
Definition at line 14 of file RawTowerContainer.h.
Member Typedef Documentation
typedef Map::const_iterator RawTowerContainer::ConstIterator
Definition at line 19 of file RawTowerContainer.h.
typedef std::pair<ConstIterator, ConstIterator> RawTowerContainer::ConstRange
Definition at line 21 of file RawTowerContainer.h.
typedef Map::iterator RawTowerContainer::Iterator
Definition at line 18 of file RawTowerContainer.h.
typedef std::map<RawTowerDefs::keytype, RawTower *> RawTowerContainer::Map
Definition at line 17 of file RawTowerContainer.h.
typedef std::pair<Iterator, Iterator> RawTowerContainer::Range
Definition at line 20 of file RawTowerContainer.h.
Constructor & Destructor Documentation
RawTowerContainer::RawTowerContainer (RawTowerDefs::CalorimeterId caloid = RawTowerDefs::NONE) inline
Definition at line 23 of file RawTowerContainer.h.
virtual RawTowerContainer::~RawTowerContainer () inline virtual
Definition at line 28 of file RawTowerContainer.h.
Member Function Documentation
ConstIterator RawTowerContainer::AddTower (const unsigned int ieta, const unsigned int iphi, RawTower * twr)
Referenced by TempInfoUnpackPRDF::addPacketInfo(), RawTowerBuilder::process_event(), Prototype2RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), GenericUnpackPRDF::process_event(), RawTowerDeadTowerInterp::process_event(), CaloUnpackPRDF::process_event(), CaloCalibration::process_event(), RawTowerCalibration::process_event(), RawTowerBuilderByHitIndex::process_event(), RawTowerDigitizer::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), RetowerCEMC::process_event(), and RawTowerCombiner::process_event().
RawTowerContainer::ConstIterator RawTowerContainer::AddTower (RawTowerDefs::keytype key, RawTower * twr)
Definition at line 56 of file RawTowerContainer.cc.
References RawTowerDefs::decode_caloid(), and RawTower::set_id().
void RawTowerContainer::compress (const double emin)
Definition at line 10 of file RawTowerContainer.cc.
References RawTower::get_energy().
Referenced by alphas(), converttohepmc(), deriv(), dofistatescat(), doinstatescat(), dokinematics(), generatez(), genevent(), getdeltat(), getinspliti(), getinsudafast(), getinsudakov(), getinsudared(), getmass(), getnewmass(), getpdf(), getpdfxintexact(), getpnorad1(), getqvec(), getspliti(), getsscat(), getsudakov(), gett(), getxsecint(), init(), initpythia(), insudaint(), intpgghigh(), intpgglow(), intpqghigh(), intpqglow(), intpqq(), makebranch(), makecascade(), makeinsplit(), makesplitting(), makestrings_minl(), makestrings_vac(), pdfint(), RawTowerBuilder::process_event(), Prototype2RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), RawTowerBuilderByHitIndex::process_event(), scatprimfunc(), splitfncint(), and xsecint().
RawTowerDefs::CalorimeterId RawTowerContainer::getCalorimeterID () inline
Definition at line 35 of file RawTowerContainer.h.
References _caloid.
Referenced by RawTowerCalibration::CreateNodes(), RawTowerDigitizer::CreateNodes(), CaloCalibration::CreateNodeTree(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
double RawTowerContainer::getTotalEdep () const
Definition at line 127 of file RawTowerContainer.cc.
Referenced by RawClusterBuilderGraph::process_event(), RawTowerBuilder::process_event(), Prototype2RawTowerBuilder::process_event(), RawClusterBuilderFwd::process_event(), HcalRawTowerBuilder::process_event(), RawClusterBuilderTemplate::process_event(), RawTowerDeadTowerInterp::process_event(), CaloCalibration::process_event(), RawTowerCalibration::process_event(), RawTowerBuilderByHitIndex::process_event(), RawTowerDigitizer::process_event(), and RawTowerCombiner::process_event().
RawTower * RawTowerContainer::getTower (RawTowerDefs::keytype key)
Definition at line 72 of file RawTowerContainer.cc.
References it.
Referenced by TempInfoUnpackPRDF::addPacketInfo(), CaloRawClusterEval::all_truth_hits(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), CaloRawClusterEval::all_truth_primary_showers(), JetRecoEval::all_truth_showers(), TreeMaker::CopyAndMakeJets(), RawClusterBuilderFwd::CorrectPhi(), RawClusterBuilderTemplate::CorrectPhi(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), EpFinderEval::fill_tree(), Proto4SampleFrac::find_max(), Proto4ShowerCalib::find_max(), Proto2ShowerCalib::find_max(), Proto3ShowerCalib::find_max(), Proto4TowerCalib::find_max(), ExampleAnalysisModule::find_max(), CaloRawClusterEval::get_energy_contribution(), JetRecoEval::get_energy_contribution(), STACalorimeterCharacterization::get_ordered_towers(), TrackProjectionTools::getE33Barrel(), TrackProjectionTools::getE33Forward(), RawTowerBuilder::process_event(), RawClusterBuilderGraph::process_event(), EventInfoSummary::process_event(), RawClusterPositionCorrection::process_event(), Prototype2RawTowerBuilder::process_event(), RawClusterDeadAreaMask::process_event(), HcalRawTowerBuilder::process_event(), RawClusterBuilderFwd::process_event(), GenericUnpackPRDF::process_event(), RawTowerDeadTowerInterp::process_event(), CaloUnpackPRDF::process_event(), RawTowerBuilderByHitIndex::process_event(), RawTowerDigitizer::process_event(), Proto4ShowerCalib::process_event(), SubtractTowersCS::process_event(), SubtractTowers::process_event(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), Proto3ShowerCalib::process_event(), Proto2ShowerCalib::process_event(), PHGenFitTrackProjection::process_event(), ExampleAnalysisModule::process_event(), PhotonJet::process_event(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), EMCalCalib::process_event_Tower(), and EMCalCalib_TestBeam::process_event_Tower().
const RawTower * RawTowerContainer::getTower (RawTowerDefs::keytype key) const
Definition at line 83 of file RawTowerContainer.cc.
References it.
RawTower * RawTowerContainer::getTower (const unsigned int ieta, const unsigned int iphi)
Definition at line 94 of file RawTowerContainer.cc.
References RawTowerDefs::encode_towerid().
const RawTower * RawTowerContainer::getTower (const unsigned int ieta, const unsigned int iphi) const
Definition at line 101 of file RawTowerContainer.cc.
References RawTowerDefs::encode_towerid().
RawTowerContainer::ConstRange RawTowerContainer::getTowers (void) const
return all towers
Definition at line 34 of file RawTowerContainer.cc.
Referenced by DISKinematicsReco::AddGlobalCalorimeterInformation(), CaloRawTowerEval::all_towers_from(), EpFinderEval::fill_tree(), CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), STACalorimeterCharacterization::get_ordered_towers(), TrackProjectionTools::getE33Forward(), RawClusterBuilderGraph::process_event(), RawTowerBuilder::process_event(), EventInfoSummary::process_event(), Prototype2RawTowerBuilder::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), RawClusterBuilderFwd::process_event(), HcalRawTowerBuilder::process_event(), RawClusterBuilderTemplate::process_event(), RecoInfoExport::process_event(), RawClusterBuilderTopo::process_event(), CaloUnpackPRDF::process_event(), CaloCalibration::process_event(), RawTowerCalibration::process_event(), PHG4DstCompressReco::process_event(), RawTowerBuilderByHitIndex::process_event(), G4TowerNtuple::process_event(), Proto4ShowerCalib::process_event(), TowerTiming::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), RetowerCEMC::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), Proto2ShowerCalib::process_event(), Proto3ShowerCalib::process_event(), Proto4TowerCalib::process_event(), Prototype2DSTReader::process_event(), Prototype3DSTReader::process_event(), Prototype4DSTReader::process_event(), ExampleAnalysisModule::process_event(), PHG4DSTReader::process_event(), RawTowerCombiner::process_event(), DumpRawTowerContainer::process_Node(), and CaloAna::process_towers().
RawTowerContainer::Range RawTowerContainer::getTowers (void)
Definition at line 40 of file RawTowerContainer.cc.
void RawTowerContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 121 of file RawTowerContainer.cc.
Referenced by RawTowerBuilder::process_event(), Prototype2RawTowerBuilder::process_event(), HcalRawTowerBuilder::process_event(), CaloUnpackPRDF::process_event(), and RawTowerBuilderByHitIndex::process_event().
int RawTowerContainer::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 107 of file RawTowerContainer.cc.
void RawTowerContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 112 of file RawTowerContainer.cc.
Referenced by RawTowerCombiner::process_event().
void RawTowerContainer::setCalorimeterID (RawTowerDefs::CalorimeterId caloid) inline
Definition at line 34 of file RawTowerContainer.h.
References _caloid.
unsigned int RawTowerContainer::size (void) const inline
Definition at line 50 of file RawTowerContainer.h.
References _towers.
Referenced by RawClusterBuilderTopo::process_event(), ClusterIso::process_event(), SubtractTowers::process_event(), SubtractTowersCS::process_event(), RetowerCEMC::process_event(), CaloTriggerSim::process_event(), DetermineTowerBackground::process_event(), Prototype2DSTReader::process_event(), Prototype3DSTReader::process_event(), Prototype4DSTReader::process_event(), PHG4DSTReader::process_event(), RawTowerCombiner::process_event(), QAG4SimulationCalorimeter::process_event_Tower(), and DumpRawTowerContainer::process_Node().
Member Data Documentation
RawTowerDefs::CalorimeterId RawTowerContainer::_caloid protected
Definition at line 55 of file RawTowerContainer.h.
Referenced by getCalorimeterID(), and setCalorimeterID().
Map RawTowerContainer::_towers protected
Definition at line 56 of file RawTowerContainer.h.
Referenced by size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerContainer.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerContainer.cc