Analysis Software: macros/blob/master/macros/g4simulations/G4_Global.C File Reference
G4_Global.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4vertex/GlobalVertexReco.h>
#include <g4vertex/GlobalVertexFastSimReco.h>
Functions
void GlobalInit ()
void Global_Reco (int verbosity=0)
void Global_FastSim (int verbosity=0)
Function Documentation
void Global_FastSim (int verbosity = 0)
Definition at line 32 of file G4_Global.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), GlobalVertexFastSimReco::set_t_smearing(), GlobalVertexFastSimReco::set_x_smearing(), GlobalVertexFastSimReco::set_y_smearing(), and GlobalVertexFastSimReco::set_z_smearing().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and Jin_BJet().
void Global_Reco (int verbosity = 0)
Definition at line 11 of file G4_Global.C.
References Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and Jin_BJet().
void GlobalInit ()
Definition at line 9 of file G4_Global.C.