Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 Draw ()
Draw_HFJetTruth_CrossSection2RAA_deta0 cd ()
Draw_HFJetTruth_CrossSection2RAA_deta0 Range (7.911393,-0.243038, 52.21519, 1.275949)
hframe__1 SetMinimum (0)
hframe__1 SetMaximum (1.2)
hframe__1 SetDirectory (0)
hframe__1 SetStats (0)
hframe__1 SetLineWidth (2)
hframe__1 SetMarkerStyle (20)
hframe__1 SetMarkerSize (1.2)
hframe__1 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
hframe__1 GetYaxis () -> SetTitle("#it
Anti entry SetLineColor (1)
entry SetLineStyle (1)
entry SetLineWidth (1)
entry SetMarkerColor (1)
entry SetMarkerStyle (21)
entry SetMarkerSize (1)
entry SetTextFont (42)
leg SetBorderSize (0)
leg SetFillStyle (1001)
entry SetLineWidth (3)
entry SetMarkerSize (2)
Draw_HFJetTruth_CrossSection2RAA_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA_deta0 SetSelected (Draw_HFJetTruth_CrossSection2RAA_deta0.45)
Variables
TPad * Draw_HFJetTruth_CrossSection2RAA_deta0 = new TPad("Draw_HFJetTruth_CrossSection2RAA_deta0.45_1", "Draw_HFJetTruth_CrossSection2RAA_deta0.45_1",0.01,0.01,0.99,0.99)
TH1F * hframe__1 = new TH1F("hframe__1","",1000,15,50)
_
Anti k_ {T} R=0.4
entry =leg->AddEntry("NULL","#it{p}+#it{p}: 200 pb^{-1}, 60% Eff., 40% Pur.","")
leg = new TLegend(0.17,0.7,0.88,0.77,NULL,"brNDC")
Function Documentation
Draw_HFJetTruth_CrossSection2RAA_deta0 cd ()
Draw_HFJetTruth_CrossSection2RAA_deta0 Draw ()
hframe__1 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
Definition at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
hframe__1 GetYaxis () -> SetTitle("#it
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
Draw_HFJetTruth_CrossSection2RAA_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA_deta0 Range (0 , 0 , 1 , 1)
Draw_HFJetTruth_CrossSection2RAA_deta0 Range (7. 911393, -0. 243038, 52. 21519, 1. 275949)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetBorderSize (2)
leg SetBorderSize (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetBottomMargin (0. 16)
hframe__1 SetDirectory (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetFillColor (0)
leg SetFillStyle (1001)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetLeftMargin (0. 16)
Anti entry SetLineColor (1)
entry SetLineStyle (1)
hframe__1 SetLineWidth (2)
entry SetLineWidth (1)
entry SetLineWidth (3)
entry SetMarkerColor (1)
hframe__1 SetMarkerSize (1. 2)
entry SetMarkerSize (1)
entry SetMarkerSize (2)
hframe__1 SetMarkerStyle (20)
entry SetMarkerStyle (21)
hframe__1 SetMaximum (1. 2)
hframe__1 SetMinimum (0)
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetSelected (Draw_HFJetTruth_CrossSection2RAA_deta0. 45)
hframe__1 SetStats (0)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA_deta0 SetTopMargin (0. 05)
Variable Documentation
_
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
TPad* Draw_HFJetTruth_CrossSection2RAA_deta0 = new TPad("Draw_HFJetTruth_CrossSection2RAA_deta0.45_1", "Draw_HFJetTruth_CrossSection2RAA_deta0.45_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
entry =leg->AddEntry("NULL","#it{p}+#it{p}: 200 pb^{-1}, 60% Eff., 40% Pur.","")
Definition at line 134 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
TH1F* hframe__1 = new TH1F("hframe__1","",1000,15,50)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
Anti k_ {T} R=0.4
Definition at line 126 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
leg = new TLegend(0.17,0.7,0.88,0.77,NULL,"brNDC")
Definition at line 152 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_deta0.45.C.
Referenced by CentralCalorimeterRate(), ChargePerLayer(), Check(), ClusterQA(), Clusters3D(), ClusterSizeScan(), CrossSection2RAA(), CrossSection2v2(), DataRate(), dNdeta(), Draw_BDiJetImbalance_ncoll(), Draw_HFJetTruth_DrawCrossSection_PR(), Draw_HFJetTruth_InvMass_DrawCrossSection_PR(), DrawCrossSection(), DrawEcal_BlockCalibration(), DrawEMCalTower_Resolution_Compare(), DrawPrototype2EMCalTower_ResolutionRecalib(), EtaScan(), extractShowerCalibFactor(), FEEDataSize(), FitVerticalScan(), ForwardCalorimeterRate(), FullCyl(), FullCylEIC(), FullCylRProj(), FullCylRProjPHENIXComparison(), FullCylZProj(), Get_Res_linear_Summmary(), Get_Res_linear_Summmary_Sim(), getMeanRMS(), MakeChipMultiplicitySet(), MakeDCA2DResolution(), MakeEfficiency(), MakePtResolution(), MakeTH1F(), OnlineAnalysis(), PIDScan(), plot_amatrix(), plotQA_cosmic_TowerCalib(), plotQA_cosmic_vertical(), plotQA_cosmic_XY(), RejectionCompare(), Resolution(), SectorDataSize(), Track3D(), TrackClusterEnergy(), TrackerRate(), TriggerMultiplicity(), VertexCyl(), and WaveletCheck().