Analysis Software: online_distribution/blob/master/newbasic/frameRoutines.h File Reference
frameRoutines.h File Reference
#include "phenixOnline.h"
#include "framePublic.h"
Functions
VALUE_ret makeFrameHdr (PHDWORD *, UINT, UINT, UINT, UINT)
VALUE_ret storeFrameData (FRAME_ptr, UINT, PHDWORD *, UINT)
VALUE_ret storeFrameHistory (FRAME_ptr, UINT, PHDWORD *, UINT)
VALUE_ret extendFrameData (FRAME_ptr, UINT, UINT)
VALUE_ret extendFrameDataNopad (FRAME_ptr, UINT, UINT)
VALUE_ret extendFrameHistory (FRAME_ptr, UINT, UINT)
VALUE_ret extendFrameHistoryNopad (FRAME_ptr, UINT, UINT)
Function Documentation
VALUE_ret extendFrameData (FRAME_ptr , UINT , UINT)
Definition at line 136 of file frameRoutines.C.
References adjustFrameDataLength(), adjustFrameLength(), TRUE, and valueFailure.
Referenced by appendEmptyFramePacket(), and storeFrameData().
VALUE_ret extendFrameDataNopad (FRAME_ptr , UINT , UINT)
Definition at line 150 of file frameRoutines.C.
References adjustFrameDataLength(), adjustFrameLength(), FALSE, and valueFailure.
Referenced by fakeFrame().
VALUE_ret extendFrameHistory (FRAME_ptr , UINT , UINT)
Definition at line 165 of file frameRoutines.C.
References adjustFrameHistoryLength(), adjustFrameLength(), TRUE, and valueFailure.
VALUE_ret extendFrameHistoryNopad (FRAME_ptr , UINT , UINT)
Definition at line 179 of file frameRoutines.C.
References adjustFrameHistoryLength(), adjustFrameLength(), FALSE, and valueFailure.
Referenced by storeFrameHistory().
VALUE_ret makeFrameHdr (PHDWORD * , UINT , UINT , UINT , UINT)
VALUE_ret storeFrameData (FRAME_ptr , UINT , PHDWORD * , UINT)
VALUE_ret storeFrameHistory (FRAME_ptr , UINT , PHDWORD * , UINT)