Analysis Software: Fun4AllDstOutputManager Class Reference
Fun4AllDstOutputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstOutputManager.h>
Public Member Functions
Fun4AllDstOutputManager (const std::string &myname="DSTOUT", const std::string &filename="dstout.root")
virtual ~Fun4AllDstOutputManager ()
int AddNode (const std::string &nodename)
add a node in outputmanager
int StripNode (const std::string &nodename)
not write a node in outputmanager
int StripRunNode (const std::string &nodename)
not write a runwise node in outputmanager
int outfileopen (const std::string &fname)
opens output file
void Print (const std::string &what="ALL") const
print method (dump event selector)
int Write (PHCompositeNode *startNode)
write starting from given node
int WriteNode (PHCompositeNode *thisNode)
write specified node
Public Member Functions inherited from Fun4AllOutputManager
virtual ~Fun4AllOutputManager ()
destructor
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual std::vector
< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual void IncrementEvents (const unsigned int i)
increment number of events
virtual std::string OutFileName () const
get output file name
void OutFileName (const std::string &name)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::set< std::string > savenodes
std::set< std::string > stripnodes
std::set< std::string > striprunnodes
PHNodeIOManager * dstOut
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllOutputManager
Fun4AllOutputManager (const std::string &myname)
Fun4AllOutputManager (const std::string &myname, const std::string &outfname)
Detailed Description
Definition at line 14 of file Fun4AllDstOutputManager.h.
Constructor & Destructor Documentation
Fun4AllDstOutputManager::Fun4AllDstOutputManager (const std::string & myname = "DSTOUT", const std::string & filename = "dstout.root")
Definition at line 18 of file Fun4AllDstOutputManager.cc.
References dstOut, PHNodeIOManager::isFunctional(), PHWHERE, PHWrite, and PHNodeIOManager::SetCompressionLevel().
Fun4AllDstOutputManager::~Fun4AllDstOutputManager () virtual
Definition at line 33 of file Fun4AllDstOutputManager.cc.
References dstOut.
Member Function Documentation
int Fun4AllDstOutputManager::AddNode (const std::string &) virtual
add a node in outputmanager
Reimplemented from Fun4AllOutputManager.
Definition at line 39 of file Fun4AllDstOutputManager.cc.
References savenodes.
Referenced by Fun4All_EMCalLikelihood(), Fun4All_G4_Clusters(), and generate_hepmc_bjet().
int Fun4AllDstOutputManager::outfileopen (const std::string &) virtual
opens output file
Reimplemented from Fun4AllOutputManager.
Definition at line 57 of file Fun4AllDstOutputManager.cc.
References dstOut, PHNodeIOManager::isFunctional(), PHWHERE, PHWrite, and PHNodeIOManager::SetCompressionLevel().
void Fun4AllDstOutputManager::Print (const std::string & what = "ALL") const virtual
print method (dump event selector)
Reimplemented from Fun4AllOutputManager.
Definition at line 73 of file Fun4AllDstOutputManager.cc.
References Fun4AllBase::Name(), Fun4AllOutputManager::OutFileName(), Fun4AllOutputManager::Print(), savenodes, and stripnodes.
int Fun4AllDstOutputManager::StripNode (const std::string &) virtual
not write a node in outputmanager
Reimplemented from Fun4AllOutputManager.
Definition at line 45 of file Fun4AllDstOutputManager.cc.
References stripnodes.
Referenced by DstCompress().
int Fun4AllDstOutputManager::StripRunNode (const std::string &) virtual
not write a runwise node in outputmanager
Reimplemented from Fun4AllOutputManager.
Definition at line 51 of file Fun4AllDstOutputManager.cc.
References striprunnodes.
int Fun4AllDstOutputManager::Write (PHCompositeNode *) virtual
write starting from given node
Reimplemented from Fun4AllOutputManager.
Definition at line 115 of file Fun4AllDstOutputManager.cc.
References dstOut, PHNodeIterator::findFirst(), Fun4AllServer::instance(), Fun4AllServer::MakeNodesPersistent(), Fun4AllServer::MakeNodesTransient(), PHNode::makePersistent(), PHNode::makeTransient(), Fun4AllBase::Name(), PHWHERE, savenodes, stripnodes, Fun4AllBase::Verbosity(), and PHNodeIOManager::write().
int Fun4AllDstOutputManager::WriteNode (PHCompositeNode *) virtual
write specified node
Reimplemented from Fun4AllOutputManager.
Definition at line 183 of file Fun4AllDstOutputManager.cc.
References dstOut, PHNodeIterator::findFirst(), Fun4AllServer::instance(), Fun4AllServer::MakeNodesPersistent(), PHNode::makeTransient(), Fun4AllOutputManager::OutFileName(), PHRunTree, PHUpdate, striprunnodes, and PHNodeIOManager::write().
Member Data Documentation
PHNodeIOManager* Fun4AllDstOutputManager::dstOut private
Definition at line 34 of file Fun4AllDstOutputManager.h.
Referenced by Fun4AllDstOutputManager(), outfileopen(), Write(), WriteNode(), and ~Fun4AllDstOutputManager().
std::set<std::string> Fun4AllDstOutputManager::savenodes private
Definition at line 31 of file Fun4AllDstOutputManager.h.
Referenced by AddNode(), Print(), and Write().
std::set<std::string> Fun4AllDstOutputManager::stripnodes private
Definition at line 32 of file Fun4AllDstOutputManager.h.
Referenced by Print(), StripNode(), and Write().
std::set<std::string> Fun4AllDstOutputManager::striprunnodes private
Definition at line 33 of file Fun4AllDstOutputManager.h.
Referenced by StripRunNode(), and WriteNode().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstOutputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstOutputManager.cc