Analysis Software: PHFieldUtility Class Reference
PHFieldUtility Class Reference
Toolsets to do geometry operations.
#include <coresoftware/blob/master/offline/packages/PHField/PHFieldUtility.h>
Static Public Member Functions
static PHFieldConfig * DefaultFieldConfig ()
static PHField * GetFieldMapNode (const PHFieldConfig *default_config=nullptr, PHCompositeNode *topNode=nullptr, const int verbosity=0)
Get transient PHField from DST nodes. If not found, make a new one based on default_config.
static PHFieldConfig * GetFieldConfigNode (const PHFieldConfig *default_config=nullptr, PHCompositeNode *topNode=nullptr, const int verbosity=0)
Get persistent PHGeomIOTGeo from DST nodes. If not found, make a new one.
static PHField * BuildFieldMap (const PHFieldConfig *field_config, const int verbosity=0)
Build or build field map with a configuration object.
static std::string GetDSTFieldMapNodeName ()
DST node name for RunTime field map object.
static std::string GetDSTConfigNodeName ()
DST node name for persistent field configuration node.
Private Member Functions
PHFieldUtility ()=delete
~PHFieldUtility ()=delete
Detailed Description
Toolsets to do geometry operations.
Definition at line 11 of file PHFieldUtility.h.
Constructor & Destructor Documentation
PHFieldUtility::PHFieldUtility () private delete
PHFieldUtility::~PHFieldUtility () private delete
Member Function Documentation
PHField * PHFieldUtility::BuildFieldMap (const PHFieldConfig * field_config, const int verbosity = 0) static
Build or build field map with a configuration object.
Definition at line 28 of file PHFieldUtility.cc.
References assert, PHFieldConfig::Field3DCartesian, PHFieldConfig::get_field_config(), PHFieldConfig::get_field_mag_x(), PHFieldConfig::get_field_mag_y(), PHFieldConfig::get_field_mag_z(), PHFieldConfig::get_filename(), PHFieldConfig::get_magfield_rescale(), PHFieldConfig::identify(), PHFieldConfig::kField2D, PHFieldConfig::kField3DCylindrical, PHFieldConfig::kFieldUniform, and verbosity.
Referenced by main().
PHFieldConfig * PHFieldUtility::DefaultFieldConfig () static
Make a default PHFieldConfig as in default macro of pro.3 release Field map = /phenix/upgrades/decadal/fieldmaps/sPHENIX.2d.root Field Scale to 1.4/1.5 default field configuration object. Caller assumes ownership
Make a default PHFieldConfig Field map = /phenix/upgrades/decadal/fieldmaps/sPHENIX.2d.root Field Scale to 1.4/1.5 default field configuration object. Caller assumes ownership
Definition at line 89 of file PHFieldUtility.cc.
References PHFieldConfig::kField2D.
Referenced by main().
static std::string PHFieldUtility::GetDSTConfigNodeName () inline static
DST node name for persistent field configuration node.
Definition at line 45 of file PHFieldUtility.h.
static std::string PHFieldUtility::GetDSTFieldMapNodeName () inline static
DST node name for RunTime field map object.
Definition at line 38 of file PHFieldUtility.h.
PHFieldConfig * PHFieldUtility::GetFieldConfigNode (const PHFieldConfig * default_config = nullptr, PHCompositeNode * topNode = nullptr, const int verbosity = 0) static
Get persistent PHGeomIOTGeo from DST nodes. If not found, make a new one.
Get persistent PHFieldConfig from DST nodes. If not found, make a new one based on default_config
Parameters
[in] default_config default configuraiton if not on DST. If nullptr, use DefaultFieldConfig() as the default
[in] topNode you know who....
Definition at line 136 of file PHFieldUtility.cc.
References assert, PHFieldConfig::CloneMe(), PHNodeIterator::findFirst(), PHFieldConfig::identify(), Fun4AllServer::instance(), and Fun4AllServer::topNode().
PHField * PHFieldUtility::GetFieldMapNode (const PHFieldConfig * default_config = nullptr, PHCompositeNode * topNode = nullptr, const int verbosity = 0) static
Get transient PHField from DST nodes. If not found, make a new one based on default_config.
Get transient PHField from DST nodes. If not found, make a new one based on default_config
Parameters
[in] default_config default configuraiton if not on DST. If nullptr, use DefaultFieldConfig() as the default
[in] topNode you know who....
Definition at line 98 of file PHFieldUtility.cc.
References assert, PHNodeIterator::findFirst(), Fun4AllServer::instance(), and Fun4AllServer::topNode().
Referenced by PHG4Reco::InitField(), TpcPrototypeUnpacker::InitField(), PHGenFitTrkProp::InitializePHGenFit(), PHGenFitTrackProjection::InitRun(), TpcPrototypeGenFitTrkFinder::InitRun(), SVReco::InitRun(), GenFitTrackProp::InitRun(), PHRaveVertexing::InitRun(), BDiJetModule::InitRun(), PHG4TrackFastSim::InitRun(), PHGenFitTrkFitter::InitRun(), TpcPrototypeGenFitTrkFitter::InitRun(), TrackProjectorPid::TrackProjectorPid(), and TrackProjectorPlaneECAL::TrackProjectorPlaneECAL().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHField/PHFieldUtility.h
coresoftware/blob/master/offline/packages/PHField/PHFieldUtility.cc