Analysis Software: oEvent Class Reference
oEvent Class Reference
#include <online_distribution/blob/master/newbasic/oEvent.h>
Public Member Functions
oEvent (PHDWORD *, const int maxlength, const int irun, const int itype, const int eseq)
virtual ~oEvent ()
virtual int prepare_next ()
virtual int prepare_next (const int, const int)
virtual void set_event_type (const int)
virtual int addFrame (PHDWORD *)
virtual int addPacket (const Packet *p)
virtual int addUnstructPacketData (PHDWORD *data, const int length, const int id, const int wordsize, const int hitformat)
Protected Attributes
PHDWORD * event_base
int current
int in_frame
PHDWORD * currentFramePtr
evtdata_ptr evthdr
int max_length
int left
int maxSizeOfThisFrame
Detailed Description
Definition at line 14 of file oEvent.h.
Constructor & Destructor Documentation
oEvent::oEvent (PHDWORD * where, const int maxlength, const int irun, const int itype, const int eseq)
Definition at line 13 of file oEvent.cc.
References event_base, evt_data::evt_type, evthdr, max_length, maxSizeOfThisFrame, and prepare_next().
virtual oEvent::~oEvent () inline virtual
Definition at line 25 of file oEvent.h.
Member Function Documentation
int oEvent::addFrame (PHDWORD * frame) virtual
Definition at line 72 of file oEvent.cc.
References current, evt_data::data, evt_data::evt_length, evthdr, getFrameLength(), i, in_frame, and left.
Referenced by oBuffer::addFrame().
int oEvent::addPacket (const Packet * p) virtual
Definition at line 90 of file oEvent.cc.
References adjustFrameLength(), Packet::copyMe(), current, currentFrameHdrLength, currentFramePtr, evt_data::data, evt_data::evt_length, evthdr, findFrameDataEnd(), Packet::getLength(), in_frame, left, makeFrameHdr(), maxSizeOfThisFrame, oncsFrame, and rawData.
Referenced by oBuffer::addPacket().
int oEvent::addUnstructPacketData (PHDWORD * data, const int length, const int id, const int wordsize, const int hitformat) virtual
Definition at line 128 of file oEvent.cc.
References adjustFrameLength(), current, currentFrameHdrLength, currentFramePtr, evt_data::data, evt_data::evt_length, evthdr, findFrameDataEnd(), in_frame, left, makeFrameHdr(), makeUnstructPacket(), maxSizeOfThisFrame, oncsFrame, rawData, and storePacketHits().
Referenced by oBuffer::addUnstructPacketData().
int oEvent::prepare_next () virtual
Definition at line 29 of file oEvent.cc.
References current, evt_data::date, evt_data::evt_length, evt_data::evt_sequence, evthdr, EVTHEADERLENGTH, in_frame, left, max_length, and evt_data::time.
Referenced by oEvent().
int oEvent::prepare_next (const int evtseq, const int irun) virtual
Definition at line 48 of file oEvent.cc.
References current, evt_data::date, evt_data::evt_length, evt_data::evt_sequence, evthdr, EVTHEADERLENGTH, in_frame, left, max_length, evt_data::run_number, and evt_data::time.
void oEvent::set_event_type (const int etype) virtual
Definition at line 24 of file oEvent.cc.
References evt_data::evt_type, and evthdr.
Member Data Documentation
int oEvent::current protected
Definition at line 43 of file oEvent.h.
Referenced by addFrame(), addPacket(), addUnstructPacketData(), and prepare_next().
PHDWORD* oEvent::currentFramePtr protected
Definition at line 45 of file oEvent.h.
Referenced by addPacket(), and addUnstructPacketData().
PHDWORD* oEvent::event_base protected
Definition at line 42 of file oEvent.h.
Referenced by oEvent().
evtdata_ptr oEvent::evthdr protected
Definition at line 46 of file oEvent.h.
Referenced by addFrame(), addPacket(), addUnstructPacketData(), oEvent(), prepare_next(), and set_event_type().
int oEvent::in_frame protected
Definition at line 44 of file oEvent.h.
Referenced by addFrame(), addPacket(), addUnstructPacketData(), and prepare_next().
int oEvent::left protected
Definition at line 48 of file oEvent.h.
Referenced by addFrame(), addPacket(), addUnstructPacketData(), and prepare_next().
int oEvent::max_length protected
Definition at line 47 of file oEvent.h.
Referenced by oEvent(), and prepare_next().
int oEvent::maxSizeOfThisFrame protected
Definition at line 49 of file oEvent.h.
Referenced by addPacket(), addUnstructPacketData(), and oEvent().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oEvent.h
online_distribution/blob/master/newbasic/oEvent.cc