Analysis Software: sHelix Class Reference
sHelix Class Reference
#include <analysis/blob/master/TPC/SCDCorrections/sHelix.h>
Public Member Functions
sHelix ()
sHelix (float x0, float y0, float z0, float px, float py, float pz, float q, float b=1.5)
virtual ~sHelix ()
float x (float t)
float y (float t)
float z (float t)
float r (float t)
float u (float t)
float v (float t)
float w (float t)
float k ()
float s (float t1, float t2)
void breakIntoPieces (float t1, float t2, float x[100][3])
float findFirstInterceptTo (float rd, float hz)
void SaveTracktoRootScript (float ri, float ro, float z, char *filec)
float W ()
float R ()
float C ()
float Phi ()
void Debug ()
Protected Attributes
float fW
float fR
float fC
float fPhi
float fX0
float fY0
float fZ0
float fDebug
Detailed Description
Definition at line 9 of file sHelix.h.
Constructor & Destructor Documentation
sHelix::sHelix ()
Definition at line 7 of file sHelix.cxx.
sHelix::sHelix (float x0, float y0, float z0, float px, float py, float pz, float q, float b = 1.5)
Definition at line 19 of file sHelix.cxx.
References fC, fDebug, fPhi, fR, fW, fX0, fY0, fZ0, and x0.
virtual sHelix::~sHelix () inline virtual
Definition at line 13 of file sHelix.h.
Member Function Documentation
void sHelix::breakIntoPieces (float t1, float t2, float x[100][3])
Definition at line 34 of file sHelix.cxx.
References n, t1, x(), y(), and z().
Referenced by main().
float sHelix::C () inline
Definition at line 32 of file sHelix.h.
References fC.
void sHelix::Debug () inline
Definition at line 34 of file sHelix.h.
References fDebug.
float sHelix::findFirstInterceptTo (float rd, float hz)
Definition at line 46 of file sHelix.cxx.
References c, fC, fDebug, fPhi, fR, fW, fX0, fY0, fZ0, r(), t1, t2, TwoPi, x(), y(), and z().
Referenced by main(), and SaveTracktoRootScript().
float sHelix::k () inline
Definition at line 23 of file sHelix.h.
References fC, and fR.
float sHelix::Phi () inline
Definition at line 33 of file sHelix.h.
References fPhi.
float sHelix::r (float t) inline
Definition at line 17 of file sHelix.h.
References x(), and y().
Referenced by findFirstInterceptTo().
float sHelix::R () inline
Definition at line 31 of file sHelix.h.
References fR.
float sHelix::s (float t1, float t2) inline
Definition at line 24 of file sHelix.h.
References fC, fR, fW, and t1.
Referenced by main().
void sHelix::SaveTracktoRootScript (float ri, float ro, float z, char * filec)
Definition at line 147 of file sHelix.cxx.
References findFirstInterceptTo(), t, t1, t2, x(), y(), and z().
float sHelix::u (float t) inline
Definition at line 19 of file sHelix.h.
References fPhi, fR, and fW.
Referenced by aiz(), biz(), fg(), fgp(), g(), gauss1(), gauss2(), gauss3(), gauss4(), gphoton(), poissonian(), pyct5l(), pyct5m(), pyeig4(), pygau2(), pygaus(), pythag(), subcrs1(), subcrs2(), subcrs3(), subcrs4(), subcrs5(), subcrs6(), subcrs7(), and x().
float sHelix::v (float t) inline
Definition at line 20 of file sHelix.h.
References fPhi, fR, and fW.
Referenced by y().
float sHelix::w (float t) inline
Definition at line 21 of file sHelix.h.
References fC, and t.
Referenced by airy1(), airy1d(), airy2(), airy2d(), aiz(), arorie(), gauss1(), gauss2(), gauss3(), gauss4(), hijwds(), luindf(), medderiv(), pyboei(), pyeig4(), pyfill(), pygau2(), pygaus(), pyindf(), pymirm(), pytbbc(), pytbbn(), wdsax(), and z().
float sHelix::W () inline
Definition at line 30 of file sHelix.h.
References fW.
float sHelix::x (float t) inline
Definition at line 14 of file sHelix.h.
References fPhi, fR, fX0, and u().
Referenced by breakIntoPieces(), findFirstInterceptTo(), r(), and SaveTracktoRootScript().
float sHelix::y (float t) inline
Definition at line 15 of file sHelix.h.
References fPhi, fR, fY0, and v().
Referenced by breakIntoPieces(), findFirstInterceptTo(), r(), and SaveTracktoRootScript().
float sHelix::z (float t) inline
Definition at line 16 of file sHelix.h.
References fZ0, and w().
Referenced by breakIntoPieces(), findFirstInterceptTo(), and SaveTracktoRootScript().
Member Data Documentation
float sHelix::fC protected
Definition at line 39 of file sHelix.h.
Referenced by C(), findFirstInterceptTo(), k(), s(), sHelix(), and w().
float sHelix::fDebug protected
Definition at line 44 of file sHelix.h.
Referenced by Debug(), findFirstInterceptTo(), and sHelix().
float sHelix::fPhi protected
Definition at line 40 of file sHelix.h.
Referenced by findFirstInterceptTo(), Phi(), sHelix(), u(), v(), x(), and y().
float sHelix::fR protected
Definition at line 38 of file sHelix.h.
Referenced by findFirstInterceptTo(), k(), R(), s(), sHelix(), u(), v(), x(), and y().
float sHelix::fW protected
Definition at line 37 of file sHelix.h.
Referenced by findFirstInterceptTo(), s(), sHelix(), u(), v(), and W().
float sHelix::fX0 protected
Definition at line 41 of file sHelix.h.
Referenced by findFirstInterceptTo(), sHelix(), and x().
float sHelix::fY0 protected
Definition at line 42 of file sHelix.h.
Referenced by findFirstInterceptTo(), sHelix(), and y().
float sHelix::fZ0 protected
Definition at line 43 of file sHelix.h.
Referenced by findFirstInterceptTo(), sHelix(), and z().
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/SCDCorrections/sHelix.h
analysis/blob/master/TPC/SCDCorrections/sHelix.cxx