Analysis Software: HelixKalman Class Reference
HelixKalman Class Reference abstract
#include <coresoftware/blob/master/offline/packages/HelixHough/helix_hough/Kalman/HelixKalman.h>
Public Member Functions
HelixKalman (float B)
virtual ~HelixKalman ()
void addHit (SimpleHit3D &hit, HelixKalmanState &state)
Protected Member Functions
virtual void calculateProjections (SimpleHit3D &hit, HelixKalmanState &state, Eigen::Matrix< float, 2, 5 > &H, Eigen::Matrix< float, 2, 1 > &ha)=0
virtual void calculateMeasurements (SimpleHit3D &hit, Eigen::Matrix< float, 2, 1 > &m, Eigen::Matrix< float, 2, 2 > &G)=0
virtual bool calculateScatteringVariance (HelixKalmanState &state, float &var)=0
virtual void updateIntersection (HelixKalmanState &state, int layer)=0
virtual void subtractProjections (Eigen::Matrix< float, 2, 1 > &m, Eigen::Matrix< float, 2, 1 > &ha, Eigen::Matrix< float, 2, 1 > &diff)
void calculateMSCovariance (HelixKalmanState &state, Eigen::Matrix< float, 5, 5 > &Q)
void calculate_dbdt (Eigen::Matrix< float, 3, 2 > &dbdt_out)
void calculate_dpdb (Eigen::Vector3f &p, Eigen::Matrix< float, 3, 3 > &dpdb)
void calculate_dApdp (HelixKalmanState &state, Eigen::Matrix< float, 3, 3 > &dApdp, Eigen::Vector3f &p, float phi, float cosphi, float sinphi)
void calculate_dAdAp (HelixKalmanState &state, Eigen::Matrix< float, 5, 3 > &dAdAp, float &phi_p, float &cosphi_p, float &sinphi_p)
Protected Attributes
float Bfield
float Bfield_inv
Detailed Description
Definition at line 10 of file HelixKalman.h.
Constructor & Destructor Documentation
HelixKalman::HelixKalman (float B)
Definition at line 18 of file HelixKalman.cpp.
HelixKalman::~HelixKalman () virtual
Definition at line 20 of file HelixKalman.cpp.
Member Function Documentation
void HelixKalman::addHit (SimpleHit3D & hit, HelixKalmanState & state)
Definition at line 28 of file HelixKalman.cpp.
References HelixKalmanState::C, calculateMeasurements(), calculateMSCovariance(), calculateProjections(), HelixKalmanState::chi2, HelixKalmanState::d, HelixKalmanState::dzdl, G, SimpleHit3D::get_layer(), H, HelixKalmanState::kappa, HelixKalmanState::nu, HelixKalmanState::phi, subtractProjections(), updateIntersection(), and HelixKalmanState::z0.
Referenced by sPHENIXTracker::finalize(), sPHENIXTrackerTpc::finalize(), sPHENIXSeedFinder::finalize(), sPHENIXTrackerTpc::findTracksByCombinatorialKalman(), sPHENIXTrackerTpc::findTracksBySegments(), sPHENIXTracker::findTracksBySegments(), and sPHENIXSeedFinder::findTracksBySegments().
void HelixKalman::calculate_dAdAp (HelixKalmanState & state, Eigen::Matrix< float, 5, 3 > & dAdAp, float & phi_p, float & cosphi_p, float & sinphi_p) protected
Definition at line 88 of file HelixKalman.cpp.
References HelixKalmanState::d, d, dx, dy, dz2, HelixKalmanState::dzdl, dzdl, k, k2, HelixKalmanState::kappa, HelixKalmanState::nu, HelixKalmanState::phi, phi, s, sign(), temp1, temp2, tmp1, tmp2, tmp3, v, x0, HelixKalmanState::x_int, and HelixKalmanState::y_int.
Referenced by calculateMSCovariance().
void HelixKalman::calculate_dApdp (HelixKalmanState & state, Eigen::Matrix< float, 3, 3 > & dApdp, Eigen::Vector3f & p, float phi, float cosphi, float sinphi) protected
Definition at line 314 of file HelixKalman.cpp.
References Bfield, HelixKalmanState::dzdl, dzdl, k, HelixKalmanState::kappa, and HelixKalmanState::nu.
Referenced by calculateMSCovariance().
void HelixKalman::calculate_dbdt (Eigen::Matrix< float, 3, 2 > & dbdt_out) protected
Definition at line 396 of file HelixKalman.cpp.
Referenced by calculateMSCovariance().
void HelixKalman::calculate_dpdb (Eigen::Vector3f & p, Eigen::Matrix< float, 3, 3 > & dpdb) protected
Definition at line 364 of file HelixKalman.cpp.
Referenced by calculateMSCovariance().
virtual void HelixKalman::calculateMeasurements (SimpleHit3D & hit, Eigen::Matrix< float, 2, 1 > & m, Eigen::Matrix< float, 2, 2 > & G) protected pure virtual
Implemented in CylinderKalman.
Referenced by addHit().
void HelixKalman::calculateMSCovariance (HelixKalmanState & state, Eigen::Matrix< float, 5, 5 > & Q) protected
Definition at line 436 of file HelixKalman.cpp.
References calculate_dAdAp(), calculate_dApdp(), calculate_dbdt(), calculate_dpdb(), calculateScatteringVariance(), i, and j.
Referenced by addHit().
virtual void HelixKalman::calculateProjections (SimpleHit3D & hit, HelixKalmanState & state, Eigen::Matrix< float, 2, 5 > & H, Eigen::Matrix< float, 2, 1 > & ha) protected pure virtual
Implemented in CylinderKalman.
Referenced by addHit().
virtual bool HelixKalman::calculateScatteringVariance (HelixKalmanState & state, float & var) protected pure virtual
Implemented in CylinderKalman.
Referenced by calculateMSCovariance().
void HelixKalman::subtractProjections (Eigen::Matrix< float, 2, 1 > & m, Eigen::Matrix< float, 2, 1 > & ha, Eigen::Matrix< float, 2, 1 > & diff) protected virtual
Reimplemented in CylinderKalman.
Definition at line 22 of file HelixKalman.cpp.
Referenced by addHit().
virtual void HelixKalman::updateIntersection (HelixKalmanState & state, int layer) protected pure virtual
Implemented in CylinderKalman.
Referenced by addHit().
Member Data Documentation
float HelixKalman::Bfield protected
Definition at line 31 of file HelixKalman.h.
Referenced by calculate_dApdp().
float HelixKalman::Bfield_inv protected
Definition at line 31 of file HelixKalman.h.
Referenced by CylinderKalman::calculateScatteringVariance().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/Kalman/HelixKalman.h
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/Kalman/HelixKalman.cpp