Analysis Software: analysis/blob/master/Test/RecoInfoExport/RecoInfoExport.C File Reference
RecoInfoExport.C File Reference
#include "RecoInfoExport.h"
#include <phool/getClass.h>
#include <fun4all/Fun4AllServer.h>
#include <phool/PHCompositeNode.h>
#include <fun4all/Fun4AllReturnCodes.h>
#include <g4main/PHG4TruthInfoContainer.h>
#include <g4main/PHG4Particle.h>
#include <g4main/PHG4VtxPoint.h>
#include <g4main/PHG4Hit.h>
#include <g4hough/SvtxVertexMap.h>
#include <g4hough/SvtxVertex.h>
#include <g4hough/SvtxTrackMap.h>
#include <g4hough/SvtxTrack.h>
#include <g4eval/SvtxEvalStack.h>
#include <g4eval/SvtxTrackEval.h>
#include <g4eval/SvtxVertexEval.h>
#include <g4eval/SvtxTruthEval.h>
#include <calobase/RawTowerContainer.h>
#include <calobase/RawTowerGeomContainer.h>
#include <calobase/RawTower.h>
#include <calobase/RawClusterContainer.h>
#include <calobase/RawCluster.h>
#include <TH1D.h>
#include <TH2D.h>
#include <TDatabasePDG.h>
#include <TVector3.h>
#include <iostream>
#include <cassert>
#include <fstream>
#include <sstream>
#include <boost/format.hpp>
#include <boost/math/special_functions/sign.hpp>
Functions
_tower_threshold (0)
_pT_threshold (0)
_min_track_hit_dist (0)
Function Documentation
_min_track_hit_dist (0)
Definition at line 46 of file RecoInfoExport.C.
Referenced by RecoInfoExport::process_event().
_pT_threshold (0)
Referenced by RecoInfoExport::process_event().
_tower_threshold (0)
Referenced by RecoInfoExport::process_event().