Analysis Software: Fun4AllFileOutStream Class Reference
Fun4AllFileOutStream Class Reference
#include <coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllFileOutStream.h>
Public Member Functions
Fun4AllFileOutStream (const std::string &frule="OUTDATA-%010d-%04d.PRDFF", const std::string &name="FILEOUTSTREAM")
virtual ~Fun4AllFileOutStream ()
int WriteEventOut (Event *evt)
int CloseOutStream ()
void identify (std::ostream &os=std::cout) const
oBuffer * GetoBuffer ()
void SetoBuffer (oBuffer *bf)
unsigned long long MaxSize () const
void DeleteoBuffer ()
std::string FileRule () const
int iSeq () const
void iSeq (const int i)
unsigned long long BytesWritten () const
void BytesWritten (const unsigned long long i)
int OutFileDescriptor () const
void OutFileDescriptor (const int i)
PHDWORD * xb ()
Public Member Functions inherited from Fun4AllEventOutStream
virtual ~Fun4AllEventOutStream ()
virtual int StreamStatus ()
virtual int WriteEvent (Event *evt)
int AddPacket (const int ipkt)
int DropPacket (const int ipkt)
int AddPacketRange (const int minpacket, const int maxpacket)
int DropPacketRange (const int minpacket, const int maxpacket)
void SetManager (Fun4AllEventOutputManager *myman)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Print (const std::string &what="ALL") const
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Static Public Attributes
static const unsigned int LENGTH = (4 * 1024 * 1024)
Private Attributes
std::string m_FileRule
oBuffer * m_ob
int m_iSeq
PHDWORD m_xb [LENGTH]
int m_OutFileDesc
unsigned long long m_BytesWritten
unsigned long long m_MaxSize
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllEventOutStream
Fun4AllEventOutStream (const std::string &name="OUTSTREAM")
int resize_evtbuf (const unsigned int newsize)
Fun4AllEventOutputManager * MyManager ()
Detailed Description
Definition at line 16 of file Fun4AllFileOutStream.h.
Constructor & Destructor Documentation
Fun4AllFileOutStream::Fun4AllFileOutStream (const std::string & frule = "OUTDATA-%010d-%04d.PRDFF", const std::string & name = "FILEOUTSTREAM")
Definition at line 21 of file Fun4AllFileOutStream.cc.
References m_xb.
Fun4AllFileOutStream::~Fun4AllFileOutStream () virtual
Definition at line 33 of file Fun4AllFileOutStream.cc.
References m_ob, and m_OutFileDesc.
Member Function Documentation
unsigned long long Fun4AllFileOutStream::BytesWritten () const inline
Definition at line 32 of file Fun4AllFileOutStream.h.
References m_BytesWritten.
Referenced by Fun4AllRolloverFileOutStream::WriteEventOut().
void Fun4AllFileOutStream::BytesWritten (const unsigned long long i) inline
Definition at line 33 of file Fun4AllFileOutStream.h.
References i, and m_BytesWritten.
int Fun4AllFileOutStream::CloseOutStream () virtual
Reimplemented from Fun4AllEventOutStream.
Definition at line 94 of file Fun4AllFileOutStream.cc.
References DeleteoBuffer().
void Fun4AllFileOutStream::DeleteoBuffer ()
Definition at line 106 of file Fun4AllFileOutStream.cc.
References m_ob.
Referenced by CloseOutStream(), Fun4AllRolloverFileOutStream::WriteEventOut(), and WriteEventOut().
std::string Fun4AllFileOutStream::FileRule () const inline
Definition at line 29 of file Fun4AllFileOutStream.h.
References m_FileRule.
Referenced by Fun4AllRolloverFileOutStream::identify(), and Fun4AllRolloverFileOutStream::WriteEventOut().
oBuffer* Fun4AllFileOutStream::GetoBuffer () inline
Definition at line 25 of file Fun4AllFileOutStream.h.
References m_ob.
Referenced by Fun4AllRolloverFileOutStream::WriteEventOut().
void Fun4AllFileOutStream::identify (std::ostream & os = std::cout) const
Definition at line 100 of file Fun4AllFileOutStream.cc.
References m_OutFileDesc.
int Fun4AllFileOutStream::iSeq () const inline
Definition at line 30 of file Fun4AllFileOutStream.h.
References m_iSeq.
Referenced by Fun4AllRolloverFileOutStream::WriteEventOut().
void Fun4AllFileOutStream::iSeq (const int i) inline
Definition at line 31 of file Fun4AllFileOutStream.h.
References i, and m_iSeq.
unsigned long long Fun4AllFileOutStream::MaxSize () const inline
Definition at line 27 of file Fun4AllFileOutStream.h.
References m_MaxSize.
Referenced by Fun4AllRolloverFileOutStream::Fun4AllRolloverFileOutStream().
int Fun4AllFileOutStream::OutFileDescriptor () const inline
Definition at line 34 of file Fun4AllFileOutStream.h.
References m_OutFileDesc.
Referenced by Fun4AllRolloverFileOutStream::WriteEventOut().
void Fun4AllFileOutStream::OutFileDescriptor (const int i) inline
Definition at line 35 of file Fun4AllFileOutStream.h.
References i, and m_OutFileDesc.
void Fun4AllFileOutStream::SetoBuffer (oBuffer * bf) inline
Definition at line 26 of file Fun4AllFileOutStream.h.
References m_ob.
Referenced by Fun4AllRolloverFileOutStream::WriteEventOut().
int Fun4AllFileOutStream::WriteEventOut (Event * evt) virtual
Reimplemented from Fun4AllEventOutStream.
Reimplemented in Fun4AllRolloverFileOutStream.
Definition at line 43 of file Fun4AllFileOutStream.cc.
References oBuffer::addEvent(), DeleteoBuffer(), oBuffer::getBytesWritten(), Event::getEvtSequence(), Event::getRunNumber(), Fun4AllServer::instance(), LENGTH, m_BytesWritten, m_FileRule, m_iSeq, m_MaxSize, m_ob, m_OutFileDesc, m_xb, Fun4AllBase::Name(), PHWHERE, and Fun4AllServer::SegmentNumber().
PHDWORD* Fun4AllFileOutStream::xb () inline
Definition at line 36 of file Fun4AllFileOutStream.h.
References m_xb.
Referenced by __example_3.f__(), profile(), pyhisspa(), pyptis(), pyreco(), pysspa(), pytbhb(), and Fun4AllRolloverFileOutStream::WriteEventOut().
Member Data Documentation
const unsigned int Fun4AllFileOutStream::LENGTH = (4 * 1024 * 1024) static
Definition at line 19 of file Fun4AllFileOutStream.h.
Referenced by WriteEventOut(), and Fun4AllRolloverFileOutStream::WriteEventOut().
unsigned long long Fun4AllFileOutStream::m_BytesWritten private
Definition at line 44 of file Fun4AllFileOutStream.h.
Referenced by BytesWritten(), and WriteEventOut().
std::string Fun4AllFileOutStream::m_FileRule private
Definition at line 39 of file Fun4AllFileOutStream.h.
Referenced by FileRule(), and WriteEventOut().
int Fun4AllFileOutStream::m_iSeq private
Definition at line 41 of file Fun4AllFileOutStream.h.
Referenced by iSeq(), and WriteEventOut().
unsigned long long Fun4AllFileOutStream::m_MaxSize private
Definition at line 45 of file Fun4AllFileOutStream.h.
Referenced by MaxSize(), and WriteEventOut().
oBuffer* Fun4AllFileOutStream::m_ob private
Definition at line 40 of file Fun4AllFileOutStream.h.
Referenced by DeleteoBuffer(), GetoBuffer(), SetoBuffer(), WriteEventOut(), and ~Fun4AllFileOutStream().
int Fun4AllFileOutStream::m_OutFileDesc private
Definition at line 43 of file Fun4AllFileOutStream.h.
Referenced by identify(), OutFileDescriptor(), WriteEventOut(), and ~Fun4AllFileOutStream().
PHDWORD Fun4AllFileOutStream::m_xb[LENGTH] private
Definition at line 42 of file Fun4AllFileOutStream.h.
Referenced by Fun4AllFileOutStream(), WriteEventOut(), and xb().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllFileOutStream.h
coresoftware/blob/master/offline/framework/fun4allraw/Fun4AllFileOutStream.cc