Analysis Software: SvtxHit Class Reference
SvtxHit Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHit.h>
Public Member Functions
virtual ~SvtxHit ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual unsigned int get_layer () const
virtual void set_layer (unsigned int layer)
virtual unsigned int get_adc () const
virtual void set_adc (unsigned int adc)
virtual float get_e () const
virtual void set_e (float e)
virtual PHG4CellDefs::keytype get_cellid () const
virtual void set_cellid (PHG4CellDefs::keytype cellid)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxHit ()
Private Member Functions
ClassDef (SvtxHit, 2)
Detailed Description
Definition at line 11 of file SvtxHit.h.
Constructor & Destructor Documentation
virtual SvtxHit::~SvtxHit () inline virtual
Definition at line 14 of file SvtxHit.h.
SvtxHit::SvtxHit () inline protected
Definition at line 44 of file SvtxHit.h.
Member Function Documentation
SvtxHit::ClassDef (SvtxHit , 2) private
virtual PHObject* SvtxHit::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxHit_v1.
Definition at line 24 of file SvtxHit.h.
Referenced by SvtxHitMap_v1::insert().
virtual unsigned int SvtxHit::get_adc () const inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 34 of file SvtxHit.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and TPCDataStreamEmulator::process_event().
virtual PHG4CellDefs::keytype SvtxHit::get_cellid () const inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 40 of file SvtxHit.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), BDiJetModule::MakeGenFitTrack(), and TPCDataStreamEmulator::process_event().
virtual float SvtxHit::get_e () const inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 37 of file SvtxHit.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluatorHaiwang::fillOutputNtuples().
virtual unsigned int SvtxHit::get_id () const inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 28 of file SvtxHit.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxHitMap_v1::operator=(), HFMLTriggerOccupancy::process_event(), HFMLTriggerInterface::process_event(), and SvtxHitMap_v1::SvtxHitMap_v1().
virtual unsigned int SvtxHit::get_layer () const inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 31 of file SvtxHit.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), Conversion::firstLayer(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), HFMLTriggerInterface::process_event(), TPCDataStreamEmulator::process_event(), HFMLTriggerOccupancy::process_event(), and Conversion::trackDLayer().
virtual void SvtxHit::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxHit_v1.
Definition at line 18 of file SvtxHit.h.
References os.
virtual int SvtxHit::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxHit_v1.
Definition at line 23 of file SvtxHit.h.
virtual void SvtxHit::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxHit_v1.
Definition at line 22 of file SvtxHit.h.
virtual void SvtxHit::set_adc (unsigned int adc) inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 35 of file SvtxHit.h.
virtual void SvtxHit::set_cellid (PHG4CellDefs::keytype cellid) inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 41 of file SvtxHit.h.
virtual void SvtxHit::set_e (float e) inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 38 of file SvtxHit.h.
virtual void SvtxHit::set_id (unsigned int id) inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 29 of file SvtxHit.h.
virtual void SvtxHit::set_layer (unsigned int layer) inline virtual
Reimplemented in SvtxHit_v1.
Definition at line 32 of file SvtxHit.h.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHit.h