Analysis Software: InttDefs Namespace Reference
InttDefs Namespace Reference
Utility functions for INTT.
Functions
static const unsigned int
kBitShiftLadderZId __attribute__ ((unused)) = 16
uint8_t getLadderZId (TrkrDefs::hitsetkey key)
Get the ladder id from hitsetkey.
uint8_t getLadderZId (TrkrDefs::cluskey key)
Get the ladder id from cluskey.
uint8_t getLadderPhiId (TrkrDefs::hitsetkey key)
Get the sensor id from hitsetkey.
uint8_t getLadderPhiId (TrkrDefs::cluskey key)
Get the sensor id from cluskey.
uint16_t getCol (TrkrDefs::hitkey key)
Generate a hitkey from a strip id.
uint16_t getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
TrkrDefs::hitkey genHitKey (const uint16_t col, const uint16_t row)
TrkrDefs::hitsetkey genHitSetKey (const uint8_t lyr, const uint8_t ladder_z_index, const uint8_t ladder_phi_index)
Generate a hitsetkey for the intt.
TrkrDefs::cluskey genClusKey (const uint8_t lyr, const uint8_t LadderZId, const uint8_t LadderPhiId, const uint32_t clusid)
Generate a cluster key from indeces.
TrkrDefs::cluskey genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
Generate a cluster key using a hitsetkey and cluster id.
Detailed Description
Utility functions for INTT.
Contains the functions for manipulating the various keys used by the intt for hits, hit sets, and clusters
Function Documentation
static const unsigned int kBitShiftRow InttDefs::__attribute__ ((unused)) = 16 static
TrkrDefs::cluskey InttDefs::genClusKey (const uint8_t lyr, const uint8_t LadderZId, const uint8_t LadderPhiId, const uint32_t clusid)
Generate a cluster key from indeces.
Parameters
[in] lyr Layer index
[in] ladder_z_index z index of sensor in ladder
[in] ladder_phi_ndex phi index of ladder in layer
[in] clusid Cluster id
[out] cluskey
Definition at line 74 of file InttDefs.cc.
References genHitSetKey().
Referenced by InttClusterizer::ClusterLadderCells().
TrkrDefs::cluskey InttDefs::genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
Generate a cluster key using a hitsetkey and cluster id.
Parameters
[in] hskey hitsetkey
[in] clusid Cluster id
[out] cluskey
Definition at line 83 of file InttDefs.cc.
TrkrDefs::hitkey InttDefs::genHitKey (const uint16_t col, const uint16_t row)
Definition at line 54 of file InttDefs.cc.
Referenced by PHG4InttHitReco::process_event().
TrkrDefs::hitsetkey InttDefs::genHitSetKey (const uint8_t lyr, const uint8_t ladder_z_index, const uint8_t ladder_phi_index)
Generate a hitsetkey for the intt.
Parameters
[in] lyr Layer index
[in] ladder Ladder index
[in] sensor Sensor index
[out] hitsetkey Generate a hitsetkey for the intt. The tracker id is known implicitly and used in the function.
Definition at line 63 of file InttDefs.cc.
References TrkrDefs::genHitSetKey(), and TrkrDefs::inttId.
Referenced by genClusKey(), MvtxDefs::genClusKey(), TpcDefs::genClusKey(), TrkrDefs::getClusKeyHi(), TrkrDefs::getClusKeyLo(), TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and PHG4InttHitReco::process_event().
uint16_t InttDefs::getCol (TrkrDefs::hitkey key)
Generate a hitkey from a strip id.
Parameters
[in] strip Strip id
[out] hitkey Get the column index from hitkey
[in] hitkey
[out] column index
Definition at line 40 of file InttDefs.cc.
Referenced by InttClusterizer::ClusterLadderCells(), PHG4InttDigitizer::DigitizeLadderCells(), and InttClusterizer::ladder_are_adjacent().
uint8_t InttDefs::getLadderPhiId (TrkrDefs::hitsetkey key)
Get the sensor id from hitsetkey.
Parameters
[in] hitsetkey
[out] sensor id
Definition at line 26 of file InttDefs.cc.
Referenced by InttClusterizer::ClusterLadderCells(), PHG4InttDigitizer::DigitizeLadderCells(), getLadderPhiId(), SVReco::MakeGenFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
uint8_t InttDefs::getLadderPhiId (TrkrDefs::cluskey key)
Get the sensor id from cluskey.
Parameters
[in] cluskey
[out] sensor id
Definition at line 33 of file InttDefs.cc.
References getLadderPhiId().
uint8_t InttDefs::getLadderZId (TrkrDefs::hitsetkey key)
Get the ladder id from hitsetkey.
Parameters
[in] hitsetkey
[out] ladder id
Definition at line 12 of file InttDefs.cc.
Referenced by InttClusterizer::ClusterLadderCells(), PHG4InttDigitizer::DigitizeLadderCells(), getLadderZId(), SVReco::MakeGenFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
uint8_t InttDefs::getLadderZId (TrkrDefs::cluskey key)
Get the ladder id from cluskey.
Parameters
[in] cluskey
[out] ladder id
Definition at line 19 of file InttDefs.cc.
References getLadderZId().
uint16_t InttDefs::getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
Parameters
[in] hitkey
[out] row index
Definition at line 47 of file InttDefs.cc.
Referenced by InttClusterizer::ClusterLadderCells(), PHG4InttDigitizer::DigitizeLadderCells(), and InttClusterizer::ladder_are_adjacent().