Analysis Software: PHG4CylinderGeomv1 Class Reference
PHG4CylinderGeomv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.h>
Public Member Functions
PHG4CylinderGeomv1 ()
PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn)
virtual ~PHG4CylinderGeomv1 ()
void identify (std::ostream &os=std::cout) const
int get_layer () const
double get_radius () const
double get_thickness () const
double get_zmin () const
double get_zmax () const
void set_layer (const int i)
void set_radius (const double r)
void set_thickness (const double t)
void set_zmin (const double z)
void set_zmax (const double z)
virtual void ImportParameters (const PHParameters &param)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHG4CylinderGeom
virtual ~PHG4CylinderGeom ()
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_nscint (const int i)
virtual void set_tiltangle (const double i)
virtual void set_phi_slat_zero (const double phi)
virtual void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[])
virtual void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
virtual void find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int &strip_y_index, int &strip_z_index)
virtual void find_strip_center_local_coords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int layer
double radius
double zmin
double zmax
double thickness
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 12 of file PHG4CylinderGeomv1.h.
Constructor & Destructor Documentation
PHG4CylinderGeomv1::PHG4CylinderGeomv1 ()
Definition at line 9 of file PHG4CylinderGeomv1.cc.
PHG4CylinderGeomv1::PHG4CylinderGeomv1 (const double r, const double zmi, const double zma, const double thickn) inline
Definition at line 16 of file PHG4CylinderGeomv1.h.
virtual PHG4CylinderGeomv1::~PHG4CylinderGeomv1 () inline virtual
Definition at line 25 of file PHG4CylinderGeomv1.h.
Member Function Documentation
int PHG4CylinderGeomv1::get_layer () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 28 of file PHG4CylinderGeomv1.h.
References layer.
Referenced by PHG4FullProjSpacalCellReco::InitRun().
double PHG4CylinderGeomv1::get_radius () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 29 of file PHG4CylinderGeomv1.h.
References radius.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_half_radius(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeom_Spacalv2::get_sec_depth(), and PHG4FullProjSpacalCellReco::InitRun().
double PHG4CylinderGeomv1::get_thickness () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 30 of file PHG4CylinderGeomv1.h.
References thickness.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_half_radius(), PHG4CylinderGeom_Spacalv1::get_max_radius(), PHG4CylinderGeom_Spacalv2::get_sec_depth(), and PHG4FullProjSpacalCellReco::InitRun().
double PHG4CylinderGeomv1::get_zmax () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 32 of file PHG4CylinderGeomv1.h.
References zmax.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4SpacalSteppingAction::get_zmax(), PHG4SpacalPrototype4SteppingAction::get_zmax(), and PHG4SpacalPrototypeSteppingAction::get_zmax().
double PHG4CylinderGeomv1::get_zmin () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 31 of file PHG4CylinderGeomv1.h.
References zmin.
Referenced by PHG4SpacalPrototype4Detector::Construct_AzimuthalSeg(), PHG4SpacalPrototypeDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalPrototype4Detector::ConstructMe(), PHG4SpacalPrototypeDetector::ConstructMe(), PHG4SpacalDetector::ConstructMe(), PHG4CylinderGeom_Spacalv1::get_length(), PHG4SpacalSteppingAction::get_zmin(), PHG4SpacalPrototype4SteppingAction::get_zmin(), and PHG4SpacalPrototypeSteppingAction::get_zmin().
void PHG4CylinderGeomv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom.
Reimplemented in PHG4CylinderGeomv2, and PHG4CylinderGeomv3.
Definition at line 20 of file PHG4CylinderGeomv1.cc.
References layer, radius, thickness, zmax, and zmin.
void PHG4CylinderGeomv1::ImportParameters (const PHParameters & param) virtual
load parameters from PHParameters, which interface to Database/XML/ROOT files
Reimplemented from PHG4CylinderGeom.
Reimplemented in PHG4CylinderGeom_Spacalv1, PHG4CylinderGeom_Spacalv2, PHG4CylinderGeom_Spacalv3, and PHG4CylinderGeomv2.
Definition at line 33 of file PHG4CylinderGeomv1.cc.
References PHParameters::exist_double_param(), PHParameters::exist_int_param(), PHParameters::get_double_param(), PHParameters::get_int_param(), PHG4CylinderGeom::ImportParameters(), layer, radius, thickness, zmax, and zmin.
Referenced by PHG4CylinderGeomv2::ImportParameters().
void PHG4CylinderGeomv1::set_layer (const int i) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 34 of file PHG4CylinderGeomv1.h.
References i, and layer.
void PHG4CylinderGeomv1::set_radius (const double r) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 35 of file PHG4CylinderGeomv1.h.
References r, and radius.
void PHG4CylinderGeomv1::set_thickness (const double t) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 36 of file PHG4CylinderGeomv1.h.
References t, and thickness.
void PHG4CylinderGeomv1::set_zmax (const double z) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 38 of file PHG4CylinderGeomv1.h.
References z, and zmax.
void PHG4CylinderGeomv1::set_zmin (const double z) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 37 of file PHG4CylinderGeomv1.h.
References z, and zmin.
Member Data Documentation
int PHG4CylinderGeomv1::layer protected
Definition at line 44 of file PHG4CylinderGeomv1.h.
Referenced by get_layer(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), ImportParameters(), and set_layer().
double PHG4CylinderGeomv1::radius protected
Definition at line 45 of file PHG4CylinderGeomv1.h.
Referenced by get_radius(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), and set_radius().
double PHG4CylinderGeomv1::thickness protected
Definition at line 48 of file PHG4CylinderGeomv1.h.
Referenced by get_thickness(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), and set_thickness().
double PHG4CylinderGeomv1::zmax protected
Definition at line 47 of file PHG4CylinderGeomv1.h.
Referenced by get_zmax(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), and set_zmax().
double PHG4CylinderGeomv1::zmin protected
Definition at line 46 of file PHG4CylinderGeomv1.h.
Referenced by get_zmin(), PHG4CylinderGeomv2::identify(), PHG4CylinderGeomv3::identify(), identify(), ImportParameters(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map1(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map2(), PHG4CylinderGeom_Spacalv3::load_demo_sector_tower_map4(), and set_zmin().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.cc