Analysis Software: SvtxHitEval Class Reference
SvtxHitEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxHitEval.h>
Public Member Functions
SvtxHitEval (PHCompositeNode *topNode)
virtual ~SvtxHitEval ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
SvtxTruthEval * get_truth_eval ()
std::set< PHG4Hit * > all_truth_hits (TrkrDefs::hitkey hit_key)
PHG4Hit * max_truth_hit_by_energy (TrkrDefs::hitkey hit_key)
std::set< PHG4Particle * > all_truth_particles (TrkrDefs::hitkey hit_key)
PHG4Particle * max_truth_particle_by_energy (TrkrDefs::hitkey hit_key)
std::set< TrkrDefs::hitkey > all_hits_from (PHG4Particle *truthparticle)
std::set< TrkrDefs::hitkey > all_hits_from (PHG4Hit *truthhit)
TrkrDefs::hitkey best_hit_from (PHG4Hit *truthhit)
float get_energy_contribution (TrkrDefs::hitkey, PHG4Particle *truthparticle)
float get_energy_contribution (TrkrDefs::hitkey, PHG4Hit *truthhit)
unsigned int get_errors ()
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
bool has_node_pointers ()
Private Attributes
SvtxTruthEval _trutheval
TrkrHitSetContainer * _hitmap
TrkrClusterContainer * _clustermap
TrkrHitTruthAssoc * _hit_truth_map
PHG4HitContainer * _g4hits_tpc
PHG4HitContainer * _g4hits_intt
PHG4HitContainer * _g4hits_mvtx
PHG4TruthInfoContainer * _truthinfo
bool _strict
int _verbosity
unsigned int _errors
bool _do_cache
std::map< TrkrDefs::hitkey,
std::set< PHG4Hit * > > _cache_all_truth_hits
std::map< TrkrDefs::hitkey,
PHG4Hit * > _cache_max_truth_hit_by_energy
std::map< TrkrDefs::hitkey,
std::set< PHG4Particle * > > _cache_all_truth_particles
std::map< TrkrDefs::hitkey,
PHG4Particle * > _cache_max_truth_particle_by_energy
std::map< PHG4Particle
*, std::set< TrkrDefs::hitkey > > _cache_all_hits_from_particle
std::map< PHG4Hit *, std::set
< TrkrDefs::hitkey > > _cache_all_hits_from_g4hit
std::map< PHG4Hit
*, TrkrDefs::hitkey > _cache_best_hit_from_g4hit
std::map< std::pair
< TrkrDefs::hitkey,
PHG4Particle * >, float > _cache_get_energy_contribution_g4particle
std::map< std::pair
< TrkrDefs::hitkey, PHG4Hit * >
, float > _cache_get_energy_contribution_g4hit
Detailed Description
Definition at line 23 of file SvtxHitEval.h.
Constructor & Destructor Documentation
SvtxHitEval::SvtxHitEval (PHCompositeNode * topNode)
Definition at line 29 of file SvtxHitEval.cc.
References get_node_pointers().
SvtxHitEval::~SvtxHitEval () virtual
Definition at line 56 of file SvtxHitEval.cc.
References _errors, and _verbosity.
Member Function Documentation
std::set< TrkrDefs::hitkey > SvtxHitEval::all_hits_from (PHG4Particle * truthparticle)
Definition at line 401 of file SvtxHitEval.cc.
References _cache_all_hits_from_particle, _do_cache, _errors, _hitmap, _strict, _truthinfo, all_truth_hits(), assert, PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), TrkrHitSetContainer::getHitSets(), PHG4TruthInfoContainer::GetParticle(), has_node_pointers(), and PHWHERE.
Referenced by best_hit_from().
std::set< TrkrDefs::hitkey > SvtxHitEval::all_hits_from (PHG4Hit * truthhit)
Definition at line 465 of file SvtxHitEval.cc.
References _cache_all_hits_from_g4hit, _do_cache, _errors, _hitmap, _strict, all_truth_hits(), assert, PHG4Hit::get_hit_id(), PHG4Hit::get_layer(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), has_node_pointers(), and PHWHERE.
std::set< PHG4Hit * > SvtxHitEval::all_truth_hits (TrkrDefs::hitkey hit_key)
Definition at line 126 of file SvtxHitEval.cc.
References _cache_all_truth_hits, _do_cache, _errors, _g4hits_intt, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _hitmap, _strict, assert, PHG4HitContainer::findHit(), TrkrHitTruthAssoc::getG4Hits(), TrkrHitSet::getHit(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getTrkrId(), has_node_pointers(), TrkrDefs::inttId, PHWHERE, and TrkrDefs::tpcId.
Referenced by all_hits_from(), all_truth_particles(), get_energy_contribution(), and max_truth_hit_by_energy().
std::set< PHG4Particle * > SvtxHitEval::all_truth_particles (TrkrDefs::hitkey hit_key)
Definition at line 290 of file SvtxHitEval.cc.
References _cache_all_truth_particles, _do_cache, _errors, _strict, all_truth_hits(), assert, SvtxTruthEval::get_particle(), get_truth_eval(), has_node_pointers(), and PHWHERE.
Referenced by max_truth_particle_by_energy().
TrkrDefs::hitkey SvtxHitEval::best_hit_from (PHG4Hit * truthhit)
Definition at line 532 of file SvtxHitEval.cc.
References _cache_best_hit_from_g4hit, _do_cache, _errors, _strict, all_hits_from(), assert, energy, get_energy_contribution(), has_node_pointers(), and PHWHERE.
void SvtxHitEval::do_caching (bool do_cache) inline
Definition at line 30 of file SvtxHitEval.h.
References _do_cache, _trutheval, and SvtxTruthEval::do_caching().
float SvtxHitEval::get_energy_contribution (TrkrDefs::hitkey hit_key, PHG4Particle * truthparticle)
Definition at line 584 of file SvtxHitEval.cc.
References _cache_get_energy_contribution_g4particle, _do_cache, _errors, _strict, all_truth_hits(), assert, energy, PHG4Hit::get_edep(), get_truth_eval(), has_node_pointers(), SvtxTruthEval::is_g4hit_from_particle(), and PHWHERE.
Referenced by best_hit_from(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), and max_truth_particle_by_energy().
float SvtxHitEval::get_energy_contribution (TrkrDefs::hitkey hit_key, PHG4Hit * truthhit)
Definition at line 633 of file SvtxHitEval.cc.
References _cache_get_energy_contribution_g4hit, _do_cache, _errors, _strict, all_truth_hits(), assert, energy, PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), has_node_pointers(), and PHWHERE.
unsigned int SvtxHitEval::get_errors () inline
Definition at line 68 of file SvtxHitEval.h.
References _errors, _trutheval, and SvtxTruthEval::get_errors().
void SvtxHitEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 683 of file SvtxHitEval.cc.
References _clustermap, _g4hits_intt, _g4hits_mvtx, _g4hits_tpc, _hit_truth_map, _hitmap, and _truthinfo.
Referenced by next_event(), and SvtxHitEval().
SvtxTruthEval* SvtxHitEval::get_truth_eval () inline
Definition at line 47 of file SvtxHitEval.h.
References _trutheval.
Referenced by all_truth_particles(), and get_energy_contribution().
bool SvtxHitEval::has_node_pointers () private
Definition at line 700 of file SvtxHitEval.cc.
References _g4hits_intt, _g4hits_mvtx, _g4hits_tpc, _hitmap, _strict, _truthinfo, and assert.
Referenced by all_hits_from(), all_truth_hits(), all_truth_particles(), best_hit_from(), get_energy_contribution(), max_truth_hit_by_energy(), and max_truth_particle_by_energy().
PHG4Hit * SvtxHitEval::max_truth_hit_by_energy (TrkrDefs::hitkey hit_key)
Definition at line 240 of file SvtxHitEval.cc.
References _cache_max_truth_hit_by_energy, _do_cache, _errors, _strict, all_truth_hits(), assert, PHG4Hit::get_edep(), has_node_pointers(), and PHWHERE.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and SvtxEvaluator::fillOutputNtuples().
PHG4Particle * SvtxHitEval::max_truth_particle_by_energy (TrkrDefs::hitkey hit_key)
Definition at line 348 of file SvtxHitEval.cc.
References _cache_max_truth_particle_by_energy, _do_cache, _errors, _strict, all_truth_particles(), assert, get_energy_contribution(), has_node_pointers(), particles, and PHWHERE.
void SvtxHitEval::next_event (PHCompositeNode * topNode)
Definition at line 67 of file SvtxHitEval.cc.
References _cache_all_hits_from_g4hit, _cache_all_hits_from_particle, _cache_all_truth_hits, _cache_all_truth_particles, _cache_best_hit_from_g4hit, _cache_get_energy_contribution_g4hit, _cache_get_energy_contribution_g4particle, _cache_max_truth_hit_by_energy, _cache_max_truth_particle_by_energy, _trutheval, get_node_pointers(), and SvtxTruthEval::next_event().
Referenced by SvtxClusterEval::next_event().
void SvtxHitEval::set_strict (bool strict) inline
Definition at line 35 of file SvtxHitEval.h.
References _strict, _trutheval, and SvtxTruthEval::set_strict().
void SvtxHitEval::set_verbosity (int verbosity) inline
Definition at line 40 of file SvtxHitEval.h.
References _trutheval, _verbosity, SvtxTruthEval::set_verbosity(), and verbosity.
Member Data Documentation
std::map<PHG4Hit*, std::set<TrkrDefs::hitkey> > SvtxHitEval::_cache_all_hits_from_g4hit private
Definition at line 95 of file SvtxHitEval.h.
Referenced by all_hits_from(), and next_event().
std::map<PHG4Particle*, std::set<TrkrDefs::hitkey> > SvtxHitEval::_cache_all_hits_from_particle private
Definition at line 94 of file SvtxHitEval.h.
Referenced by all_hits_from(), and next_event().
std::map<TrkrDefs::hitkey, std::set<PHG4Hit*> > SvtxHitEval::_cache_all_truth_hits private
Definition at line 90 of file SvtxHitEval.h.
Referenced by all_truth_hits(), and next_event().
std::map<TrkrDefs::hitkey, std::set<PHG4Particle*> > SvtxHitEval::_cache_all_truth_particles private
Definition at line 92 of file SvtxHitEval.h.
Referenced by all_truth_particles(), and next_event().
std::map<PHG4Hit*, TrkrDefs::hitkey> SvtxHitEval::_cache_best_hit_from_g4hit private
Definition at line 96 of file SvtxHitEval.h.
Referenced by best_hit_from(), and next_event().
std::map<std::pair<TrkrDefs::hitkey, PHG4Hit*>, float> SvtxHitEval::_cache_get_energy_contribution_g4hit private
Definition at line 98 of file SvtxHitEval.h.
Referenced by get_energy_contribution(), and next_event().
std::map<std::pair<TrkrDefs::hitkey, PHG4Particle*>, float> SvtxHitEval::_cache_get_energy_contribution_g4particle private
Definition at line 97 of file SvtxHitEval.h.
Referenced by get_energy_contribution(), and next_event().
std::map<TrkrDefs::hitkey, PHG4Hit*> SvtxHitEval::_cache_max_truth_hit_by_energy private
Definition at line 91 of file SvtxHitEval.h.
Referenced by max_truth_hit_by_energy(), and next_event().
std::map<TrkrDefs::hitkey, PHG4Particle*> SvtxHitEval::_cache_max_truth_particle_by_energy private
Definition at line 93 of file SvtxHitEval.h.
Referenced by max_truth_particle_by_energy(), and next_event().
TrkrClusterContainer* SvtxHitEval::_clustermap private
Definition at line 76 of file SvtxHitEval.h.
Referenced by get_node_pointers().
bool SvtxHitEval::_do_cache private
Definition at line 89 of file SvtxHitEval.h.
Referenced by all_hits_from(), all_truth_hits(), all_truth_particles(), best_hit_from(), do_caching(), get_energy_contribution(), max_truth_hit_by_energy(), and max_truth_particle_by_energy().
unsigned int SvtxHitEval::_errors private
Definition at line 87 of file SvtxHitEval.h.
Referenced by all_hits_from(), all_truth_hits(), all_truth_particles(), best_hit_from(), get_energy_contribution(), get_errors(), max_truth_hit_by_energy(), max_truth_particle_by_energy(), and ~SvtxHitEval().
PHG4HitContainer* SvtxHitEval::_g4hits_intt private
Definition at line 80 of file SvtxHitEval.h.
Referenced by all_truth_hits(), get_node_pointers(), and has_node_pointers().
PHG4HitContainer* SvtxHitEval::_g4hits_mvtx private
Definition at line 81 of file SvtxHitEval.h.
Referenced by all_truth_hits(), get_node_pointers(), and has_node_pointers().
PHG4HitContainer* SvtxHitEval::_g4hits_tpc private
Definition at line 79 of file SvtxHitEval.h.
Referenced by all_truth_hits(), get_node_pointers(), and has_node_pointers().
TrkrHitTruthAssoc* SvtxHitEval::_hit_truth_map private
Definition at line 77 of file SvtxHitEval.h.
Referenced by all_truth_hits(), and get_node_pointers().
TrkrHitSetContainer* SvtxHitEval::_hitmap private
Definition at line 75 of file SvtxHitEval.h.
Referenced by all_hits_from(), all_truth_hits(), get_node_pointers(), and has_node_pointers().
bool SvtxHitEval::_strict private
Definition at line 85 of file SvtxHitEval.h.
Referenced by all_hits_from(), all_truth_hits(), all_truth_particles(), best_hit_from(), get_energy_contribution(), has_node_pointers(), max_truth_hit_by_energy(), max_truth_particle_by_energy(), and set_strict().
SvtxTruthEval SvtxHitEval::_trutheval private
Definition at line 74 of file SvtxHitEval.h.
Referenced by do_caching(), get_errors(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
PHG4TruthInfoContainer* SvtxHitEval::_truthinfo private
Definition at line 83 of file SvtxHitEval.h.
Referenced by all_hits_from(), get_node_pointers(), and has_node_pointers().
int SvtxHitEval::_verbosity private
Definition at line 86 of file SvtxHitEval.h.
Referenced by set_verbosity(), and ~SvtxHitEval().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxHitEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxHitEval.cc