Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4Setup_fsPHENIX.C File Reference
G4Setup_fsPHENIX.C File Reference
Functions
void G4Init (bool do_svtx=true, bool do_cemc=true, bool do_hcalin=true, bool do_magnet=true, bool do_hcalout=true, bool do_pipe=true, bool do_FGEM=true, bool do_FEMC=true, bool do_FHCAL=true, int n_TPC_layers=40)
int G4Setup (const int absorberactive=0, const string &field="1.5", const EDecayType decayType=TPythia6Decayer::kAll, const bool do_svtx=true, const bool do_cemc=true, const bool do_hcalin=true, const bool do_magnet=true, const bool do_hcalout=true, const bool do_pipe=true, const bool do_FGEM=true, const bool do_FEMC=false, const bool do_FHCAL=false, const float magfield_rescale=1.0)
void ShowerCompress (int verbosity=0)
void DstCompress (Fun4AllDstOutputManager *out)
int make_piston (string name, PHG4Reco *g4Reco)
Variables
double no_overlapp = 0.0001
bool overlapcheck = false
Function Documentation
void DstCompress (Fun4AllDstOutputManager * out)
Definition at line 309 of file G4Setup_fsPHENIX.C.
References Fun4AllDstOutputManager::StripNode().
void G4Init (bool do_svtx = true, bool do_cemc = true, bool do_hcalin = true, bool do_magnet = true, bool do_hcalout = true, bool do_pipe = true, bool do_FGEM = true, bool do_FEMC = true, bool do_FHCAL = true, int n_TPC_layers = 40)
Definition at line 5 of file G4Setup_fsPHENIX.C.
References CEmcInit(), FEMCInit(), FGEM_Init(), FHCALInit(), HCalInnerInit(), HCalOuterInit(), MagnetInit(), PipeInit(), and SvtxInit().
int G4Setup (const int absorberactive = 0, const string & field = "1.5", const EDecayType decayType = TPythia6Decayer::kAll, const bool do_svtx = true, const bool do_cemc = true, const bool do_hcalin = true, const bool do_magnet = true, const bool do_hcalout = true, const bool do_pipe = true, const bool do_FGEM = true, const bool do_FEMC = false, const bool do_FHCAL = false, const float magfield_rescale = 1.0)
Definition at line 72 of file G4Setup_fsPHENIX.C.
References PHG4DetectorSubsystem::BlackHole(), CEmc(), FEMCSetup(), FGEMSetup(), FHCALSetup(), PHG4Reco::GetWorldSizeZ(), HCalInner(), HCalOuter(), Fun4AllServer::instance(), kAll, Magnet(), make_piston(), no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), Pipe(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4Reco::save_DST_geometry(), PHG4DetectorSubsystem::set_double_param(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4DetectorSubsystem::set_int_param(), PHG4Reco::set_rapidity_coverage(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and Svtx().
int make_piston (string name, PHG4Reco * g4Reco)
Definition at line 340 of file G4Setup_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::eta_to_polar_angle(), i, name, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), pos, PHG4Reco::registerSubsystem(), s, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and PHG4ConeSubsystem::SuperDetector().
void ShowerCompress (int verbosity = 0)
Definition at line 255 of file G4Setup_fsPHENIX.C.
References PHG4DstCompressReco::AddCellContainer(), PHG4DstCompressReco::AddHitContainer(), PHG4DstCompressReco::AddTowerContainer(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Variable Documentation
double no_overlapp = 0.0001
Definition at line 2 of file G4Setup_fsPHENIX.C.
bool overlapcheck = false
Definition at line 3 of file G4Setup_fsPHENIX.C.