Analysis Software: TempInfoUnpackPRDF Class Reference
TempInfoUnpackPRDF Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/TempInfoUnpackPRDF.h>
Public Member Functions
TempInfoUnpackPRDF ()
virtual ~TempInfoUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
TempInfoUnpackPRDF ()
virtual ~TempInfoUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
TempInfoUnpackPRDF ()
virtual ~TempInfoUnpackPRDF ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int addPacketInfo (Packet *p, PHCompositeNode *topNode, const time_t etime, const int evtnr)
int addPacketInfo (Packet *p, PHCompositeNode *topNode, const time_t etime, const int evtnr)
int addPacketInfo (Packet *p, PHCompositeNode *topNode, const time_t etime, const int evtnr)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
RawTowerContainer * hcalin_temperature
RawTowerContainer * hcalout_temperature
RawTowerContainer * emcal_temperature
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 14 of file TempInfoUnpackPRDF.h.
Constructor & Destructor Documentation
TempInfoUnpackPRDF::TempInfoUnpackPRDF ()
Definition at line 29 of file TempInfoUnpackPRDF.cc.
virtual TempInfoUnpackPRDF::~TempInfoUnpackPRDF () inline virtual
Definition at line 18 of file TempInfoUnpackPRDF.h.
TempInfoUnpackPRDF::TempInfoUnpackPRDF ()
virtual TempInfoUnpackPRDF::~TempInfoUnpackPRDF () inline virtual
Definition at line 18 of file TempInfoUnpackPRDF.h.
TempInfoUnpackPRDF::TempInfoUnpackPRDF ()
virtual TempInfoUnpackPRDF::~TempInfoUnpackPRDF () inline virtual
Definition at line 18 of file TempInfoUnpackPRDF.h.
Member Function Documentation
int TempInfoUnpackPRDF::addPacketInfo (Packet * p, PHCompositeNode * topNode, const time_t etime, const int evtnr) protected
Definition at line 115 of file TempInfoUnpackPRDF.cc.
References RawTower_Temperature::add_entry(), RawTowerContainer::AddTower(), emcal_temperature, Packet::getIdentifier(), RawTowerContainer::getTower(), hcalin_temperature, hcalout_temperature, Packet::iValue(), PROTOTYPE2_FEM::NCH_EMCAL_COLUMNS, PROTOTYPE2_FEM::NCH_EMCAL_ROWS, PROTOTYPE2_FEM::NCH_IHCAL_COLUMNS, PROTOTYPE2_FEM::NCH_IHCAL_ROWS, PROTOTYPE2_FEM::NCH_OHCAL_COLUMNS, and PROTOTYPE2_FEM::NCH_OHCAL_ROWS.
Referenced by process_event().
int TempInfoUnpackPRDF::addPacketInfo (Packet * p, PHCompositeNode * topNode, const time_t etime, const int evtnr) protected
int TempInfoUnpackPRDF::addPacketInfo (Packet * p, PHCompositeNode * topNode, const time_t etime, const int evtnr) protected
void TempInfoUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 195 of file TempInfoUnpackPRDF.cc.
References PHCompositeNode::addNode(), RawTowerDefs::CEMC, emcal_temperature, PHNodeIterator::findFirst(), RawTowerDefs::HCALIN, hcalin_temperature, RawTowerDefs::HCALOUT, and hcalout_temperature.
Referenced by InitRun().
void TempInfoUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
void TempInfoUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
int TempInfoUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 38 of file TempInfoUnpackPRDF.cc.
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
int TempInfoUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int TempInfoUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int TempInfoUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int TempInfoUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int TempInfoUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 45 of file TempInfoUnpackPRDF.cc.
References addPacketInfo(), BEGRUNEVENT, Fun4AllReturnCodes::DISCARDEVENT, Packet::dump(), Fun4AllReturnCodes::EVENT_OK, Packet::identify(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Member Data Documentation
RawTowerContainer * TempInfoUnpackPRDF::emcal_temperature protected
Definition at line 32 of file TempInfoUnpackPRDF.h.
Referenced by addPacketInfo(), and CreateNodeTree().
RawTowerContainer * TempInfoUnpackPRDF::hcalin_temperature protected
Definition at line 30 of file TempInfoUnpackPRDF.h.
Referenced by addPacketInfo(), and CreateNodeTree().
RawTowerContainer * TempInfoUnpackPRDF::hcalout_temperature protected
Definition at line 31 of file TempInfoUnpackPRDF.h.
Referenced by addPacketInfo(), and CreateNodeTree().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/TempInfoUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype3/TempInfoUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype4/TempInfoUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype2/TempInfoUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype3/TempInfoUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype4/TempInfoUnpackPRDF.cc