Analysis Software: CylinderGeomIntt Class Reference
CylinderGeomIntt Class Reference
#include <coresoftware/blob/master/offline/packages/intt/CylinderGeomIntt.h>
Public Member Functions
CylinderGeomIntt ()
CylinderGeomIntt (const int layer, const double strip_x, const double strip_y, const double strip_z0, const double strip_z1, const int nstrips_z_sensor0, const int nstrips_z_sensor1, const int nstrips_phi_cell, const int nladders_layer, const double ladder_z0, const double ladder_z1, const double sensor_radius, const double strip_x_offset, const double offsetphi, const double offsetrot)
void identify (std::ostream &os=std::cout) const
void set_layer (const int i)
int get_layer () const
double get_radius () const
bool load_geometry ()
void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[])
void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
void find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int &strip_y_index, int &strip_z_index)
void find_strip_center_localcoords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
double get_thickness () const
double get_strip_y_spacing () const
double get_strip_z_spacing () const
double get_strip_tilt () const
double get_strip_phi_tilt () const
Public Member Functions inherited from PHG4CylinderGeom
virtual ~PHG4CylinderGeom ()
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_radius (const double r)
virtual void set_thickness (const double t)
virtual void set_zmin (const double z)
virtual void set_zmax (const double z)
virtual void set_nscint (const int i)
virtual void set_tiltangle (const double i)
virtual void set_phi_slat_zero (const double phi)
virtual void find_strip_center_local_coords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual double get_pixel_z () const
virtual double get_pixel_x () const
virtual double get_pixel_thickness () const
virtual void ImportParameters (const PHParameters &param)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int m_Layer
int m_NStripsPhiCell
int m_NStripsZSensor [2]
double m_StripX
double m_StripY
double m_SensorRadius
double m_StripXOffset
double m_OffsetPhi
double m_OffsetRot
double m_dPhi
double m_StripZ [2]
double m_LadderZ [2]
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 9 of file CylinderGeomIntt.h.
Constructor & Destructor Documentation
CylinderGeomIntt::CylinderGeomIntt ()
Definition at line 11 of file CylinderGeomIntt.cc.
References m_LadderZ, m_NStripsZSensor, and m_StripZ.
CylinderGeomIntt::CylinderGeomIntt (const int layer, const double strip_x, const double strip_y, const double strip_z0, const double strip_z1, const int nstrips_z_sensor0, const int nstrips_z_sensor1, const int nstrips_phi_cell, const int nladders_layer, const double ladder_z0, const double ladder_z1, const double sensor_radius, const double strip_x_offset, const double offsetphi, const double offsetrot) inline
Definition at line 13 of file CylinderGeomIntt.h.
References m_dPhi, m_LadderZ, m_NStripsZSensor, M_PI, and m_StripZ.
Member Function Documentation
void CylinderGeomIntt::find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[]) virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 40 of file CylinderGeomIntt.cc.
References m_dPhi, m_LadderZ, m_OffsetPhi, m_SensorRadius, and phi.
Referenced by InttClusterizer::ClusterLadderCells(), find_strip_center(), SVReco::MakeGenFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
void CylinderGeomIntt::find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[]) virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 54 of file CylinderGeomIntt.cc.
References find_segment_center(), m_dPhi, m_NStripsPhiCell, m_NStripsZSensor, m_OffsetPhi, m_OffsetRot, m_StripXOffset, m_StripY, m_StripZ, and phi.
Referenced by InttClusterizer::ClusterLadderCells().
void CylinderGeomIntt::find_strip_center_localcoords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
Definition at line 121 of file CylinderGeomIntt.cc.
References double(), m_NStripsPhiCell, m_NStripsZSensor, m_StripY, and m_StripZ.
Referenced by PHG4InttHitReco::process_event().
void CylinderGeomIntt::find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int & strip_y_index, int & strip_z_index) virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 85 of file CylinderGeomIntt.cc.
References double(), m_NStripsPhiCell, m_NStripsZSensor, m_StripY, and m_StripZ.
Referenced by PHG4InttHitReco::process_event().
int CylinderGeomIntt::get_layer () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 57 of file CylinderGeomIntt.h.
References m_Layer.
Referenced by identify().
double CylinderGeomIntt::get_radius () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 62 of file CylinderGeomIntt.h.
References m_SensorRadius.
Referenced by identify().
double CylinderGeomIntt::get_strip_phi_tilt () const inline
Definition at line 93 of file CylinderGeomIntt.h.
References m_OffsetRot.
Referenced by InttClusterizer::ClusterLadderCells(), SVReco::MakeGenFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
double CylinderGeomIntt::get_strip_tilt () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 88 of file CylinderGeomIntt.h.
double CylinderGeomIntt::get_strip_y_spacing () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 78 of file CylinderGeomIntt.h.
References m_StripY.
Referenced by InttClusterizer::ClusterLadderCells(), and PHG4InttHitReco::process_event().
double CylinderGeomIntt::get_strip_z_spacing () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 83 of file CylinderGeomIntt.h.
References m_StripZ.
Referenced by InttClusterizer::ClusterLadderCells(), and PHG4InttHitReco::process_event().
double CylinderGeomIntt::get_thickness () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 73 of file CylinderGeomIntt.h.
References m_StripX.
Referenced by InttClusterizer::ClusterLadderCells().
void CylinderGeomIntt::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom.
Definition at line 28 of file CylinderGeomIntt.cc.
References get_layer(), and get_radius().
bool CylinderGeomIntt::load_geometry ()
Definition at line 35 of file CylinderGeomIntt.cc.
void CylinderGeomIntt::set_layer (const int i) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 52 of file CylinderGeomIntt.h.
References i, and m_Layer.
Member Data Documentation
double CylinderGeomIntt::m_dPhi protected
Definition at line 108 of file CylinderGeomIntt.h.
Referenced by CylinderGeomIntt(), find_segment_center(), and find_strip_center().
double CylinderGeomIntt::m_LadderZ[2] protected
Definition at line 111 of file CylinderGeomIntt.h.
Referenced by CylinderGeomIntt(), and find_segment_center().
int CylinderGeomIntt::m_Layer protected
Definition at line 99 of file CylinderGeomIntt.h.
Referenced by get_layer(), and set_layer().
int CylinderGeomIntt::m_NStripsPhiCell protected
Definition at line 100 of file CylinderGeomIntt.h.
Referenced by find_strip_center(), find_strip_center_localcoords(), and find_strip_index_values().
int CylinderGeomIntt::m_NStripsZSensor[2] protected
Definition at line 101 of file CylinderGeomIntt.h.
Referenced by CylinderGeomIntt(), find_strip_center(), find_strip_center_localcoords(), and find_strip_index_values().
double CylinderGeomIntt::m_OffsetPhi protected
Definition at line 106 of file CylinderGeomIntt.h.
Referenced by find_segment_center(), and find_strip_center().
double CylinderGeomIntt::m_OffsetRot protected
Definition at line 107 of file CylinderGeomIntt.h.
Referenced by find_strip_center(), and get_strip_phi_tilt().
double CylinderGeomIntt::m_SensorRadius protected
Definition at line 104 of file CylinderGeomIntt.h.
Referenced by find_segment_center(), and get_radius().
double CylinderGeomIntt::m_StripX protected
Definition at line 102 of file CylinderGeomIntt.h.
Referenced by get_thickness().
double CylinderGeomIntt::m_StripXOffset protected
Definition at line 105 of file CylinderGeomIntt.h.
Referenced by find_strip_center().
double CylinderGeomIntt::m_StripY protected
Definition at line 103 of file CylinderGeomIntt.h.
Referenced by find_strip_center(), find_strip_center_localcoords(), find_strip_index_values(), and get_strip_y_spacing().
double CylinderGeomIntt::m_StripZ[2] protected
Definition at line 110 of file CylinderGeomIntt.h.
Referenced by CylinderGeomIntt(), find_strip_center(), find_strip_center_localcoords(), find_strip_index_values(), and get_strip_z_spacing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/CylinderGeomIntt.h
coresoftware/blob/master/offline/packages/intt/CylinderGeomIntt.cc