Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2RAA SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_1 Draw ()
Draw_HFJetTruth_CrossSection2RAA_1 cd ()
Draw_HFJetTruth_CrossSection2RAA_1 Range (7.911393,-0.243038, 52.21519, 1.275949)
hframe__2 SetMinimum (0)
hframe__2 SetMaximum (1.2)
hframe__2 SetDirectory (0)
hframe__2 SetStats (0)
hframe__2 SetLineWidth (2)
hframe__2 SetMarkerStyle (20)
hframe__2 SetMarkerSize (1.2)
hframe__2 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
hframe__2 GetYaxis () -> SetTitle("#it
Au Au entry SetLineColor (1)
entry SetLineStyle (1)
entry SetLineWidth (1)
entry SetMarkerColor (1)
entry SetMarkerStyle (21)
entry SetMarkerSize (1)
entry SetTextFont (42)
Draw_HFJetTruth_CrossSection2RAA_1 Modified ()
Draw_HFJetTruth_CrossSection2RAA SetSelected (Draw_HFJetTruth_CrossSection2RAA)
Variables
TCanvas * Draw_HFJetTruth_CrossSection2RAA = new TCanvas("Draw_HFJetTruth_CrossSection2RAA", "Draw_HFJetTruth_CrossSection2RAA",24,157,700,600)
TPad * Draw_HFJetTruth_CrossSection2RAA_1 = new TPad("Draw_HFJetTruth_CrossSection2RAA_1", "Draw_HFJetTruth_CrossSection2RAA_1",0.01,0.01,0.99,0.99)
TH1F * hframe__2 = new TH1F("hframe__2","",1000,15,50)
_
Au Au C
entry =leg->AddEntry("NULL","PYTHIA-8 #it{b}-jet, Anti-k_{T} R=0.4, |#eta|<0.7, CTEQ6L","")
Function Documentation
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 cd ()
Referenced by tower::display(), stack::displayEvent(), stack::displayStackSummary(), hcal::displaySummary(), stack::displayTowerSummary(), AnaMvtxTestBeam2019::End(), plot(), pygrvd(), pygrvl(), pygrvm(), tileHelper::runtilesummary::runtilesummary(), sccalib(), sipmCalib(), spmcalib(), and tileHelper::tilePattern().
Draw_HFJetTruth_CrossSection2RAA_1 Draw ()
hframe__2 GetXaxis () -> SetTitle("Transverse Momentum [GeV/#it
Definition at line 45 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
hframe__2 GetYaxis () -> SetTitle("#it
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA Range (0 , 0 , 1 , 1)
Draw_HFJetTruth_CrossSection2RAA_1 Range (7. 911393, -0. 243038, 52. 21519, 1. 275949)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetBorderMode (0)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetBorderSize (2)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetBottomMargin (0. 16)
Graph_Graph1D_y11 SetDirectory (0)
leg SetFillColor (0)
Draw_HFJetTruth_InvMass_DrawCrossSection_PR SetFrameBorderMode (0)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetLeftMargin (0. 16)
entry SetLineColor (1)
Referenced by Draw_BDiJetImbalance(), plot(), PlotLine(), and sccalib().
entry SetLineStyle (1)
Referenced by PlotLine().
entry SetLineWidth (2)
Referenced by plot(), and PlotLine().
entry SetLineWidth (1)
entry SetMarkerColor (1)
entry SetMarkerSize (1. 2)
entry SetMarkerSize (1)
entry SetMarkerStyle (20)
entry SetMarkerStyle (21)
hframe__2 SetMaximum (1. 2)
Referenced by plot().
hframe__2 SetMinimum (0)
gStyle SetOptFit (1)
gStyle SetOptStat (0)
Referenced by plot().
gStyle SetOptTitle (0)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2RAA SetSelected (Draw_HFJetTruth_CrossSection2RAA)
Graph_ge_h_b_copyv216497604924 SetStats (0)
entry SetTextFont (42)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetTickx (1)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetTicky (1)
Draw_HFJetTruth_InvMass_CrossSection2RAARatio_Theory_deta0 SetTopMargin (0. 05)
Variable Documentation
_
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
Au Au C
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
Referenced by PHHoughSeeding::CleanupTracksByHitPattern(), PHG4HcalDetector::ConstructMe(), counting_sort(), FillHoughHist(), PHPatternReco::fit_vertex(), PHInitZVertexing::fit_vertex(), PHHoughSeeding::full_track_seeding(), get_parametrization_F2(), TrkrEvaluator::line_circle_intersection(), SvtxEvaluator::line_circle_intersection(), mergeClusters(), HelixHough::vote(), and HelixHough::vote_pairs().
TCanvas* Draw_HFJetTruth_CrossSection2RAA = new TCanvas("Draw_HFJetTruth_CrossSection2RAA", "Draw_HFJetTruth_CrossSection2RAA",24,157,700,600)
Definition at line 4 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
TPad* Draw_HFJetTruth_CrossSection2RAA_1 = new TPad("Draw_HFJetTruth_CrossSection2RAA_1", "Draw_HFJetTruth_CrossSection2RAA_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
entry =leg->AddEntry("NULL","PYTHIA-8 #it{b}-jet, Anti-k_{T} R=0.4, |#eta|<0.7, CTEQ6L","")
Definition at line 134 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
Referenced by HelixHough::attemptClusterMerge(), DrawCalibratedE_PlotTestBeam(), DrawCluster_Res_2Fit(), DrawCluster_Res_2Fit_1DSpacalNoSVX(), DrawCluster_Res_2Fit_1DSpacalNoSVX_Eta3(), DrawCluster_Res_2Fit_2DSpacalNoSVX(), DrawCluster_Res_2Fit_Electron_NoSVX(), DrawTowerSum_Res_2Fit_1DSpacalNoSVX(), DrawTowerSum_Res_2Fit_1DSpacalNoSVX_Eta3(), eicsmear_dvmp_plot(), HelixHough::findHelices(), HelixHough::findSeededHelices(), RawTower_Temperature::get_eventnumber_from_entry(), RawTower_Temperature::get_temperature_from_entry(), RawTower_Temperature::get_time_from_entry(), TrkrClusterHitAssoc::identify(), TrkrHitSet::identify(), TrkrHitTruthAssoc::identify(), lurobo(), HelixHough::makeClusters(), PHG4TruthEventAction::ProcessShowers(), HelixHough::splitIntoBins(), and vegas().
TH1F* hframe__2 = new TH1F("hframe__2","",1000,15,50)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.