Analysis Software: Setters
Setters
Modules
property map definitions
Functions
virtual void RawCluster::set_id (const RawClusterDefs::keytype id)
cluster ID
virtual void RawCluster::addTower (const RawClusterDefs::keytype twrid, const float etower)
Tower operations.
virtual void RawCluster::set_energy (const float energy)
total energy
virtual void RawCluster::set_phi (const float phi)
access to intrinsic cylindrical coordinate system
virtual void RawCluster::set_z (const float z)
virtual void RawCluster::set_r (const float r)
virtual void RawCluster::set_ecore (const float ecore)
virtual void RawCluster::set_chi2 (const float chi2)
reduced chi2 for EM shower
virtual void RawCluster::set_prob (const float prob)
cluster template probability for EM shower
virtual void RawCluster::set_et_iso (const float e)
isolation ET
virtual void RawCluster::set_et_iso (const float e, const int radiusx10, bool subtracted, bool clusterTower)
RawCluster::RawCluster ()
void RawClusterv1::set_id (const RawClusterDefs::keytype id)
cluster ID
void RawClusterv1::addTower (const RawClusterDefs::keytype twrid, const float etower)
Tower operations.
void RawClusterv1::set_energy (const float energy)
total energy
void RawClusterv1::set_phi (const float phi)
access to intrinsic cylindrical coordinate system
void RawClusterv1::set_z (const float z)
void RawClusterv1::set_r (const float r)
virtual void RawClusterv1::set_ecore (const float ecore)
virtual void RawClusterv1::set_chi2 (const float chi2)
reduced chi2 for EM shower
virtual void RawClusterv1::set_prob (const float prob)
cluster template probability for EM shower
virtual void RawClusterv1::set_et_iso (const float e)
isolation ET default
virtual void RawClusterv1::set_et_iso (const float et_iso, const int radiusx10, bool subtracted, bool clusterTower)
isolation ET the radius and hueristic can be specified
RawClusterv1::u_property::u_property (int32_t in)
RawClusterv1::u_property::u_property (uint32_t in)
RawClusterv1::u_property::u_property (float in)
RawClusterv1::u_property::u_property ()
prop_storage_t RawClusterv1::u_property::get_storage () const
Variables
float RawClusterv1::u_property::fdata
int32_t RawClusterv1::u_property::idata
uint32_t RawClusterv1::u_property::uidata
RawClusterDefs::keytype RawClusterv1::clusterid
cluster ID
float RawClusterv1::_energy
total energy
TowerMap RawClusterv1::towermap
Tower operations.
float RawClusterv1::_r
location of cluster in cylindrical coordinate
float RawClusterv1::_phi
float RawClusterv1::_z
Detailed Description
Function Documentation
void RawClusterv1::addTower (const RawClusterDefs::keytype twrid, const float etower) virtual
Tower operations.
Reimplemented from RawCluster.
Definition at line 34 of file RawClusterv1.cc.
References RawClusterv1::towermap.
virtual void RawCluster::addTower (const RawClusterDefs::keytype twrid, const float etower) inline virtual
Tower operations.
Reimplemented in RawClusterv1.
Definition at line 196 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderFwd::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
prop_storage_t RawClusterv1::u_property::get_storage () const inline
Definition at line 160 of file RawClusterv1.h.
References RawClusterv1::u_property::uidata.
RawCluster::RawCluster () inline protected
Definition at line 295 of file RawCluster.h.
virtual void RawClusterv1::set_chi2 (const float chi2) inline virtual
reduced chi2 for EM shower
Reimplemented from RawCluster.
Definition at line 100 of file RawClusterv1.h.
References RawCluster::prop_chi2, and RawClusterv1::set_property().
virtual void RawCluster::set_chi2 (const float chi2) inline virtual
reduced chi2 for EM shower
Reimplemented in RawClusterv1.
Definition at line 209 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
virtual void RawClusterv1::set_ecore (const float ecore) inline virtual
access additional optional properties cluster core energy for EM shower
Reimplemented from RawCluster.
Definition at line 98 of file RawClusterv1.h.
References RawCluster::prop_ecore, and RawClusterv1::set_property().
virtual void RawCluster::set_ecore (const float ecore) inline virtual
access additional optional properties cluster core energy for EM shower
Reimplemented in RawClusterv1.
Definition at line 207 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterPositionCorrection::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_energy (const float energy) inline virtual
total energy
Reimplemented from RawCluster.
Definition at line 90 of file RawClusterv1.h.
References RawClusterv1::_energy, and energy.
virtual void RawCluster::set_energy (const float energy) inline virtual
total energy
Reimplemented in RawClusterv1.
Definition at line 198 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterPositionCorrection::process_event(), RawClusterBuilderTemplateFEMC::process_event(), RawClusterBuilderFwd::process_event(), and RawClusterBuilderTemplate::process_event().
virtual void RawClusterv1::set_et_iso (const float e) inline virtual
isolation ET default
Reimplemented from RawCluster.
Definition at line 104 of file RawClusterv1.h.
References RawCluster::prop_et_iso_calotower_R03, and RawClusterv1::set_property().
void RawClusterv1::set_et_iso (const float et_iso, const int radiusx10, bool subtracted, bool clusterTower = 1) virtual
isolation ET the radius and hueristic can be specified
Reimplemented from RawCluster.
Definition at line 184 of file RawClusterv1.cc.
References PHOOL_VIRTUAL_WARN, RawCluster::prop_et_iso_calotower_R01, RawCluster::prop_et_iso_calotower_R02, RawCluster::prop_et_iso_calotower_R03, RawCluster::prop_et_iso_calotower_R04, RawCluster::prop_et_iso_calotower_sub_R01, RawCluster::prop_et_iso_calotower_sub_R02, RawCluster::prop_et_iso_calotower_sub_R03, RawCluster::prop_et_iso_calotower_sub_R04, and RawClusterv1::set_property().
virtual void RawCluster::set_et_iso (const float e) inline virtual
isolation ET
Reimplemented in RawClusterv1.
Definition at line 213 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by ClusterIso::process_event().
virtual void RawCluster::set_et_iso (const float e, const int radiusx10, bool subtracted, bool clusterTower) inline virtual
Reimplemented in RawClusterv1.
Definition at line 214 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
void RawClusterv1::set_id (const RawClusterDefs::keytype id) inline virtual
cluster ID
Reimplemented from RawCluster.
Definition at line 86 of file RawClusterv1.h.
References RawClusterv1::clusterid.
virtual void RawCluster::set_id (const RawClusterDefs::keytype id) inline virtual
cluster ID
Reimplemented in RawClusterv1.
Definition at line 194 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by RawClusterContainer::AddCluster(), and TreeMaker::CopyAndMakeClusters().
void RawClusterv1::set_phi (const float phi) inline virtual
access to intrinsic cylindrical coordinate system
Reimplemented from RawCluster.
Definition at line 92 of file RawClusterv1.h.
References RawClusterv1::_phi, and phi.
virtual void RawCluster::set_phi (const float phi) inline virtual
access to intrinsic cylindrical coordinate system
Reimplemented in RawClusterv1.
Definition at line 201 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderFwd::CorrectPhi(), RawClusterBuilderTemplate::CorrectPhi(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderFwd::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
virtual void RawClusterv1::set_prob (const float prob) inline virtual
cluster template probability for EM shower
Reimplemented from RawCluster.
Definition at line 102 of file RawClusterv1.h.
References RawCluster::prop_prob, and RawClusterv1::set_property().
virtual void RawCluster::set_prob (const float prob) inline virtual
cluster template probability for EM shower
Reimplemented in RawClusterv1.
Definition at line 211 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_r (const float r) inline virtual
Reimplemented from RawCluster.
Definition at line 94 of file RawClusterv1.h.
References RawClusterv1::_r, and r.
virtual void RawCluster::set_r (const float r) inline virtual
Reimplemented in RawClusterv1.
Definition at line 203 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderFwd::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
void RawClusterv1::set_z (const float z) inline virtual
Reimplemented from RawCluster.
Definition at line 93 of file RawClusterv1.h.
References RawClusterv1::_z, and z.
virtual void RawCluster::set_z (const float z) inline virtual
Reimplemented in RawClusterv1.
Definition at line 202 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by TreeMaker::CopyAndMakeClusters(), RawClusterBuilderGraph::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderFwd::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
RawClusterv1::u_property::u_property (int32_t in) inline
Definition at line 143 of file RawClusterv1.h.
RawClusterv1::u_property::u_property (uint32_t in) inline
Definition at line 147 of file RawClusterv1.h.
RawClusterv1::u_property::u_property (float in) inline
Definition at line 151 of file RawClusterv1.h.
RawClusterv1::u_property::u_property () inline
Definition at line 155 of file RawClusterv1.h.
Variable Documentation
float RawClusterv1::_energy protected
total energy
Definition at line 173 of file RawClusterv1.h.
Referenced by RawClusterv1::get_energy(), RawClusterv1::Reset(), and RawClusterv1::set_energy().
float RawClusterv1::_phi protected
Definition at line 179 of file RawClusterv1.h.
Referenced by RawClusterv1::get_phi(), RawClusterv1::Reset(), and RawClusterv1::set_phi().
float RawClusterv1::_r protected
location of cluster in cylindrical coordinate
Definition at line 178 of file RawClusterv1.h.
Referenced by RawClusterv1::get_r(), RawClusterv1::Reset(), and RawClusterv1::set_r().
float RawClusterv1::_z protected
Definition at line 180 of file RawClusterv1.h.
Referenced by RawClusterv1::get_z(), RawClusterv1::Reset(), and RawClusterv1::set_z().
RawClusterDefs::keytype RawClusterv1::clusterid protected
cluster ID
Definition at line 171 of file RawClusterv1.h.
Referenced by RawClusterv1::get_id(), RawClusterv1::Reset(), and RawClusterv1::set_id().
float RawClusterv1::u_property::fdata
Definition at line 139 of file RawClusterv1.h.
Referenced by RawClusterv1::get_property_float().
int32_t RawClusterv1::u_property::idata
Definition at line 140 of file RawClusterv1.h.
Referenced by RawClusterv1::get_property_int().
TowerMap RawClusterv1::towermap protected
Tower operations.
Definition at line 175 of file RawClusterv1.h.
Referenced by RawClusterv1::addTower(), RawClusterv1::get_towermap(), RawClusterv1::get_towers(), RawClusterv1::getNTowers(), RawClusterv1::isValid(), and RawClusterv1::Reset().
uint32_t RawClusterv1::u_property::uidata
Definition at line 141 of file RawClusterv1.h.
Referenced by RawClusterv1::get_property_uint(), and RawClusterv1::u_property::get_storage().