Analysis Software: SeamStress::Pincushion< TClass > Class Template Reference
SeamStress::Pincushion< TClass > Class Template Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/Seamstress/Pincushion.h>
Public Member Functions
Pincushion (TClass *glove, std::vector< Seamstress * > *ss)
virtual ~Pincushion ()
void operator() (void *thread)
void sew (void(TClass::*design)(void *), std::vector< void * > threads)
void sewSoftly (void(TClass::*design)(void *))
void sewSoftly (void(TClass::*design)(void *), unsigned long int N)
void sewStraight (void(TClass::*design)(void *))
void sewStraight (void(TClass::*design)(void *), unsigned long int N)
void sewOpenlyStraight (void(TClass::*design)(void *))
void sewOpenlyStraight (void(TClass::*design)(void *), unsigned long int N)
void sewOpenlySoft (void(TClass::*design)(void *))
void sewOpenlySoft (void(TClass::*design)(void *), unsigned long int N)
void tieOff ()
void tieOff (unsigned long int N)
Public Member Functions inherited from SeamStress::Needle
Needle ()
virtual ~Needle ()
Public Attributes
std::vector< Seamstress * > * seamstresses
TClass * hand
void(TClass::* pattern)(void *)
Public Attributes inherited from SeamStress::Needle
void(* func)(void *)
Detailed Description
template<class TClass>
class SeamStress::Pincushion< TClass >
Definition at line 10 of file Pincushion.h.
Constructor & Destructor Documentation
template<class TClass> SeamStress::Pincushion< TClass >::Pincushion (TClass * glove, std::vector< Seamstress * > * ss) inline
Definition at line 13 of file Pincushion.h.
template<class TClass> virtual SeamStress::Pincushion< TClass >::~Pincushion () inline virtual
Definition at line 18 of file Pincushion.h.
Member Function Documentation
template<class TClass> void SeamStress::Pincushion< TClass >::operator() (void * thread) inline virtual
Reimplemented from SeamStress::Needle.
Definition at line 21 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sew (void(TClass::*)(void *) design, std::vector< void * > threads) inline
Definition at line 27 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewOpenlySoft (void(TClass::*)(void *) design) inline
Definition at line 141 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewOpenlySoft (void(TClass::*)(void *) design, unsigned long int N) inline
Definition at line 153 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewOpenlyStraight (void(TClass::*)(void *) design) inline
Definition at line 113 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewOpenlyStraight (void(TClass::*)(void *) design, unsigned long int N) inline
Definition at line 127 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewSoftly (void(TClass::*)(void *) design) inline
Definition at line 45 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewSoftly (void(TClass::*)(void *) design, unsigned long int N) inline
Definition at line 61 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::sewStraight (void(TClass::*)(void *) design) inline
Definition at line 77 of file Pincushion.h.
Referenced by FitNewton::ChiSquareGradHessian::calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGradHessian(), FitNewton::GaussianRegGradHessian::calcValGradHessian(), sPHENIXTracker::findHelicesParallelOneHelicity(), sPHENIXSeedFinder::findHelicesParallelOneHelicity(), FitNewton::GaussianRegGradHessian::setData(), FitNewton::GaussianRegGradHessian::setErrors(), and FitNewton::GaussianRegGradHessian::setPoints().
template<class TClass> void SeamStress::Pincushion< TClass >::sewStraight (void(TClass::*)(void *) design, unsigned long int N) inline
Definition at line 95 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::tieOff () inline
Definition at line 165 of file Pincushion.h.
template<class TClass> void SeamStress::Pincushion< TClass >::tieOff (unsigned long int N) inline
Definition at line 174 of file Pincushion.h.
Member Data Documentation
template<class TClass> TClass* SeamStress::Pincushion< TClass >::hand
Definition at line 184 of file Pincushion.h.
Referenced by SeamStress::Pincushion< sPHENIXTrackerTpc >::operator()(), and SeamStress::Pincushion< sPHENIXTrackerTpc >::Pincushion().
template<class TClass> void(TClass::* SeamStress::Pincushion< TClass >::pattern)(void *)
Definition at line 185 of file Pincushion.h.
Referenced by SeamStress::Pincushion< sPHENIXTrackerTpc >::operator()(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sew(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewOpenlySoft(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewOpenlyStraight(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewSoftly(), and SeamStress::Pincushion< sPHENIXTrackerTpc >::sewStraight().
template<class TClass> std::vector<Seamstress*>* SeamStress::Pincushion< TClass >::seamstresses
Definition at line 183 of file Pincushion.h.
Referenced by SeamStress::Pincushion< sPHENIXTrackerTpc >::Pincushion(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sew(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewOpenlySoft(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewOpenlyStraight(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewSoftly(), SeamStress::Pincushion< sPHENIXTrackerTpc >::sewStraight(), and SeamStress::Pincushion< sPHENIXTrackerTpc >::tieOff().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/HelixHough/Seamstress/Pincushion.h