Analysis Software: RawClusterPositionCorrection Class Reference
RawClusterPositionCorrection Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterPositionCorrection.h>
Public Member Functions
RawClusterPositionCorrection (const std::string &name)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void CreateNodeTree (PHCompositeNode *topNode)
const PHParameters & Get_eclus_CalibrationParameters () const
PHParameters & Get_eclus_CalibrationParameters ()
const PHParameters & Get_eore_CalibrationParameters () const
PHParameters & Get_ecore_CalibrationParameters ()
void Set_eclus_CalibrationParameters (const PHParameters &calib_params)
void Set_ecore_CalibrationParameters (const PHParameters &calib_params)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters (PHParameters &param)
Private Attributes
PHParameters _eclus_calib_params
PHParameters _ecore_calib_params
RawClusterContainer * _recalib_clusters
std::string _det_name
int bins
std::vector< float > binvals
std::vector< std::vector
< double > > eclus_calib_constants
std::vector< std::vector
< double > > ecore_calib_constants
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file RawClusterPositionCorrection.h.
Constructor & Destructor Documentation
RawClusterPositionCorrection::RawClusterPositionCorrection (const std::string & name) explicit
Definition at line 34 of file RawClusterPositionCorrection.cc.
References _eclus_calib_params, _ecore_calib_params, and SetDefaultParameters().
Member Function Documentation
void RawClusterPositionCorrection::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 259 of file RawClusterPositionCorrection.cc.
References _det_name, _eclus_calib_params, _ecore_calib_params, _recalib_clusters, PHCompositeNode::addNode(), assert, PHNodeIterator::findFirst(), and PHParameters::SaveToNodeTree().
Referenced by InitRun().
int RawClusterPositionCorrection::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 302 of file RawClusterPositionCorrection.cc.
References Fun4AllReturnCodes::EVENT_OK.
const PHParameters& RawClusterPositionCorrection::Get_eclus_CalibrationParameters () const inline
Definition at line 25 of file RawClusterPositionCorrection.h.
References _eclus_calib_params.
Referenced by CEMC_Clusters().
PHParameters& RawClusterPositionCorrection::Get_eclus_CalibrationParameters () inline
Definition at line 29 of file RawClusterPositionCorrection.h.
References _eclus_calib_params.
PHParameters& RawClusterPositionCorrection::Get_ecore_CalibrationParameters () inline
Definition at line 37 of file RawClusterPositionCorrection.h.
References _ecore_calib_params.
Referenced by CEMC_Clusters().
const PHParameters& RawClusterPositionCorrection::Get_eore_CalibrationParameters () const inline
Definition at line 33 of file RawClusterPositionCorrection.h.
References _ecore_calib_params.
int RawClusterPositionCorrection::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 45 of file RawClusterPositionCorrection.cc.
References _eclus_calib_params, _ecore_calib_params, bins, binvals, CreateNodeTree(), eclus_calib_constants, ecore_calib_constants, Fun4AllReturnCodes::EVENT_OK, PHParameters::get_double_param(), PHParameters::get_int_param(), i, j, PHParameters::Print(), and Fun4AllBase::Verbosity().
int RawClusterPositionCorrection::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 106 of file RawClusterPositionCorrection.cc.
References _det_name, _recalib_clusters, Fun4AllReturnCodes::ABORTEVENT, RawClusterContainer::AddCluster(), assert, bins, binvals, RawCluster::CloneMe(), eclus_calib_constants, ecore_calib_constants, Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), RawTower::get_binphi(), RawCluster::get_ecore(), RawCluster::get_energy(), RawTower::get_energy(), RawTowerGeomContainer::get_phibins(), RawCluster::get_towers(), RawClusterContainer::getClusters(), RawTowerContainer::getTower(), j, PHWHERE, RawCluster::set_ecore(), RawCluster::set_energy(), and Fun4AllBase::Verbosity().
void RawClusterPositionCorrection::Set_eclus_CalibrationParameters (const PHParameters & calib_params) inline
Definition at line 42 of file RawClusterPositionCorrection.h.
References _eclus_calib_params.
void RawClusterPositionCorrection::Set_ecore_CalibrationParameters (const PHParameters & calib_params) inline
Definition at line 46 of file RawClusterPositionCorrection.h.
References _ecore_calib_params.
void RawClusterPositionCorrection::SetDefaultParameters (PHParameters & param) private
Definition at line 306 of file RawClusterPositionCorrection.cc.
References bins, i, j, PHParameters::set_double_param(), and PHParameters::set_int_param().
Referenced by RawClusterPositionCorrection().
Member Data Documentation
std::string RawClusterPositionCorrection::_det_name private
Definition at line 57 of file RawClusterPositionCorrection.h.
Referenced by CreateNodeTree(), and process_event().
PHParameters RawClusterPositionCorrection::_eclus_calib_params private
Definition at line 52 of file RawClusterPositionCorrection.h.
Referenced by CreateNodeTree(), Get_eclus_CalibrationParameters(), InitRun(), RawClusterPositionCorrection(), and Set_eclus_CalibrationParameters().
PHParameters RawClusterPositionCorrection::_ecore_calib_params private
Definition at line 53 of file RawClusterPositionCorrection.h.
Referenced by CreateNodeTree(), Get_ecore_CalibrationParameters(), Get_eore_CalibrationParameters(), InitRun(), RawClusterPositionCorrection(), and Set_ecore_CalibrationParameters().
RawClusterContainer* RawClusterPositionCorrection::_recalib_clusters private
Definition at line 55 of file RawClusterPositionCorrection.h.
Referenced by CreateNodeTree(), and process_event().
int RawClusterPositionCorrection::bins private
Definition at line 59 of file RawClusterPositionCorrection.h.
Referenced by InitRun(), process_event(), and SetDefaultParameters().
std::vector<float> RawClusterPositionCorrection::binvals private
Definition at line 60 of file RawClusterPositionCorrection.h.
Referenced by InitRun(), and process_event().
std::vector<std::vector<double> > RawClusterPositionCorrection::eclus_calib_constants private
Definition at line 61 of file RawClusterPositionCorrection.h.
Referenced by InitRun(), and process_event().
std::vector<std::vector<double> > RawClusterPositionCorrection::ecore_calib_constants private
Definition at line 62 of file RawClusterPositionCorrection.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterPositionCorrection.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterPositionCorrection.cc