Analysis Software: analysis/blob/master/EICAnalysis/macros/scattered-electron_analysis/plot_true_false_positive.C File Reference
plot_true_false_positive.C File Reference
#include "TGraph.h"
Functions
void add_CEMC_Cut (double, double)
void add_EEMC_Cut (double)
void add_FEMC_Cut (double)
int plot_true_false_positive ()
Variables
vector< TString > v_cuts_CEMC
vector< TString > v_cuts_CEMC_short
vector< TString > v_cuts_EEMC
vector< TString > v_cuts_EEMC_short
vector< TString > v_cuts_FEMC
vector< TString > v_cuts_FEMC_short
Function Documentation
void add_CEMC_Cut (double ep, double prob)
Definition at line 372 of file plot_true_false_positive.C.
References v_cuts_CEMC, and v_cuts_CEMC_short.
Referenced by plot_true_false_positive().
void add_EEMC_Cut (double ep)
Definition at line 415 of file plot_true_false_positive.C.
References v_cuts_EEMC, and v_cuts_EEMC_short.
Referenced by plot_true_false_positive().
void add_FEMC_Cut (double ep)
Definition at line 428 of file plot_true_false_positive.C.
References v_cuts_FEMC, and v_cuts_FEMC_short.
Referenced by plot_true_false_positive().
int plot_true_false_positive ()
Definition at line 15 of file plot_true_false_positive.C.
References add_CEMC_Cut(), add_EEMC_Cut(), add_FEMC_Cut(), i, SetsPhenixStyle(), v_cuts_CEMC, v_cuts_CEMC_short, v_cuts_EEMC, v_cuts_EEMC_short, v_cuts_FEMC, and v_cuts_FEMC_short.
Variable Documentation
vector< TString > v_cuts_CEMC
Definition at line 2 of file plot_true_false_positive.C.
Referenced by add_CEMC_Cut(), and plot_true_false_positive().
vector< TString > v_cuts_CEMC_short
Definition at line 3 of file plot_true_false_positive.C.
Referenced by add_CEMC_Cut(), and plot_true_false_positive().
vector< TString > v_cuts_EEMC
Definition at line 4 of file plot_true_false_positive.C.
Referenced by add_EEMC_Cut(), and plot_true_false_positive().
vector< TString > v_cuts_EEMC_short
Definition at line 5 of file plot_true_false_positive.C.
Referenced by add_EEMC_Cut(), and plot_true_false_positive().
vector< TString > v_cuts_FEMC
Definition at line 6 of file plot_true_false_positive.C.
Referenced by add_FEMC_Cut(), and plot_true_false_positive().
vector< TString > v_cuts_FEMC_short
Definition at line 7 of file plot_true_false_positive.C.
Referenced by add_FEMC_Cut(), and plot_true_false_positive().