Analysis Software: RawClusterDeadAreaMask Class Reference
RawClusterDeadAreaMask Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterDeadAreaMask.h>
Public Member Functions
RawClusterDeadAreaMask (const std::string &name="RawClusterDeadAreaMask")
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void deadTowerMaskHalfWidth (double deadTowerMaskHalfWidth)
half width of the dead area around the center of a dead tower, if cluster center fall into this region it is rejected.
void detector (const std::string &detector)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodeTree (PHCompositeNode *topNode)
Private Attributes
std::string m_detector
double m_deadTowerMaskHalfWidth
half width of the dead area around the center of a dead tower, if cluster center fall into this region it is rejected.
RawClusterContainer * m_rawClusters
RawTowerDeadMap * m_deadMap
RawTowerContainer * m_calibTowers
RawTowerGeomContainer * m_geometry
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file RawClusterDeadAreaMask.h.
Constructor & Destructor Documentation
RawClusterDeadAreaMask::RawClusterDeadAreaMask (const std::string & name = "RawClusterDeadAreaMask") explicit
Definition at line 32 of file RawClusterDeadAreaMask.cc.
Member Function Documentation
void RawClusterDeadAreaMask::CreateNodeTree (PHCompositeNode * topNode) private
Definition at line 210 of file RawClusterDeadAreaMask.cc.
References PHNodeIterator::findFirst(), RawTowerDeadMap::identify(), m_calibTowers, m_deadMap, m_detector, m_geometry, m_rawClusters, and Fun4AllBase::Name().
Referenced by InitRun().
void RawClusterDeadAreaMask::deadTowerMaskHalfWidth (double deadTowerMaskHalfWidth) inline
half width of the dead area around the center of a dead tower, if cluster center fall into this region it is rejected.
Definition at line 24 of file RawClusterDeadAreaMask.h.
References m_deadTowerMaskHalfWidth.
void RawClusterDeadAreaMask::detector (const std::string & detector) inline
Definition at line 29 of file RawClusterDeadAreaMask.h.
References m_detector.
int RawClusterDeadAreaMask::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 265 of file RawClusterDeadAreaMask.cc.
References Fun4AllReturnCodes::EVENT_OK.
int RawClusterDeadAreaMask::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 43 of file RawClusterDeadAreaMask.cc.
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
int RawClusterDeadAreaMask::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 50 of file RawClusterDeadAreaMask.cc.
References assert, Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), RawTower::get_binphi(), RawTower::get_energy(), RawTowerGeomContainer::get_etabins(), RawCluster::get_id(), RawTowerGeomContainer::get_phibins(), RawCluster::get_towers(), RawClusterContainer::getClusters(), RawClusterContainer::getClustersMap(), RawTowerContainer::getTower(), RawCluster::identify(), RawTowerDeadMap::isDeadTower(), j, m_calibTowers, m_deadMap, m_deadTowerMaskHalfWidth, m_detector, m_geometry, m_rawClusters, Fun4AllBase::Name(), RawClusterContainer::size(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
Member Data Documentation
RawTowerContainer* RawClusterDeadAreaMask::m_calibTowers private
Definition at line 44 of file RawClusterDeadAreaMask.h.
Referenced by CreateNodeTree(), and process_event().
RawTowerDeadMap* RawClusterDeadAreaMask::m_deadMap private
Definition at line 43 of file RawClusterDeadAreaMask.h.
Referenced by CreateNodeTree(), and process_event().
double RawClusterDeadAreaMask::m_deadTowerMaskHalfWidth private
half width of the dead area around the center of a dead tower, if cluster center fall into this region it is rejected.
Definition at line 40 of file RawClusterDeadAreaMask.h.
Referenced by deadTowerMaskHalfWidth(), and process_event().
std::string RawClusterDeadAreaMask::m_detector private
Definition at line 37 of file RawClusterDeadAreaMask.h.
Referenced by CreateNodeTree(), detector(), and process_event().
RawTowerGeomContainer* RawClusterDeadAreaMask::m_geometry private
Definition at line 45 of file RawClusterDeadAreaMask.h.
Referenced by CreateNodeTree(), and process_event().
RawClusterContainer* RawClusterDeadAreaMask::m_rawClusters private
Definition at line 42 of file RawClusterDeadAreaMask.h.
Referenced by CreateNodeTree(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterDeadAreaMask.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterDeadAreaMask.cc