Analysis Software: macros/blob/master/macros/g4simulations/G4_FEMC.C File Reference
G4_FEMC.C File Reference
#include "GlobalVariables.C"
#include <fun4all/Fun4AllServer.h>
#include <g4calo/RawTowerBuilderByHitIndex.h>
#include <g4calo/RawTowerDigitizer.h>
#include <caloreco/RawClusterBuilderFwd.h>
#include <caloreco/RawClusterBuilderTemplateFEMC.h>
#include <caloreco/RawTowerCalibration.h>
#include <g4detectors/PHG4ForwardCalCellReco.h>
#include <g4detectors/PHG4ForwardEcalSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
Enumerations
enum enu_Femc_clusterizer { kFemcGraphClusterizer, kFemcTemplateClusterizer, kFemcGraphClusterizer, kFemcTemplateClusterizer }
Functions
void FEMCInit ()
void FEMC_Cells (int verbosity=0)
void FEMCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void FEMC_Towers (int verbosity=0)
void FEMC_Clusters (int verbosity=0)
void FEMC_Eval (std::string outputfile, int verbosity=0)
Variables
enu_Femc_clusterizer Femc_clusterizer = kFemcTemplateClusterizer
Enumeration Type Documentation
enum enu_Femc_clusterizer
Enumerator:
kFemcGraphClusterizer
kFemcTemplateClusterizer
kFemcGraphClusterizer
kFemcTemplateClusterizer
Definition at line 22 of file G4_FEMC.C.
Function Documentation
void FEMC_Cells (int verbosity = 0)
Definition at line 38 of file G4_FEMC.C.
References PHG4ForwardCalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), and Fun4All_G4_sPHENIX().
void FEMC_Clusters (int verbosity = 0)
Definition at line 204 of file G4_FEMC.C.
References RawClusterBuilderTemplateFEMC::Detector(), RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), kFemcGraphClusterizer, kFemcTemplateClusterizer, RawClusterBuilderTemplateFEMC::LoadProfile(), Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), RawClusterBuilderTemplateFEMC::set_threshold_energy(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), and Fun4All_G4_sPHENIX().
void FEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 241 of file G4_FEMC.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_RICH(), and Fun4All_G4_sPHENIX().
void FEMC_Towers (int verbosity = 0)
Definition at line 81 of file G4_FEMC.C.
References RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::TowerType(), RawTowerCalibration::TowerType(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), and Fun4All_G4_sPHENIX().
void FEMCInit ()
Definition at line 34 of file G4_FEMC.C.
Referenced by G4Init().
void FEMCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated FEMC module
Definition at line 52 of file G4_FEMC.C.
References femc, Fun4AllServer::instance(), overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), PHG4ForwardEcalSubsystem::SetfsPHENIXDetector(), PHG4ForwardEcalSubsystem::SetTowerMappingFile(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().
Variable Documentation
enu_Femc_clusterizer Femc_clusterizer = kFemcTemplateClusterizer
Definition at line 29 of file G4_FEMC.C.