Analysis Software: Packet_fvtx_dcm0 Class Reference
Packet_fvtx_dcm0 Class Reference
#include <online_distribution/blob/master/newbasic/packet_fvtx_dcm0.h>
Public Member Functions
Packet_fvtx_dcm0 ()
Packet_fvtx_dcm0 (PACKET_ptr)
~Packet_fvtx_dcm0 ()
virtual int iValue (const int channel, const char *what)
virtual int iValue (const int chip, const int what)
virtual void dump (OSTREAM &)
Public Member Functions inherited from Packet_w4
Packet_w4 ()
Packet_w4 (PACKET_ptr)
void dump (OSTREAM &)
void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &=COUT) const
Public Member Functions inherited from Packet_A
Packet_A (PACKET_ptr packet_ptr)
Packet_A ()
~Packet_A ()
int getLength () const
int getErrorLength () const
int getDebugLength () const
get the length of the debug block
int getIdentifier () const
get the packet identifier
int getPadding () const
get the number of padding units in the packet data.
int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
int getDataLength () const
get what the name says...
void identify (OSTREAM &=COUT) const
void fullIdentify (OSTREAM &=COUT) const
void dumpErrorBlock (OSTREAM &=COUT)
void dumpDebugBlock (OSTREAM &=COUT)
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
float rValue (const int)
float rValue (const int, const char *)
float rValue (const int, const int)
int getArraylength (const char *)
int fillIntArray (int[], const int, int *, const char *what="")
int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
int * getIntArray (int *, const char *what="")
float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int getCheckSumStatus () const
int copyMe (int dest[], const int maxlength) const
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
Protected Member Functions
virtual int * decode (int *)
virtual int * decode_misc (int *)
int calculate_parity ()
Protected Member Functions inherited from Packet_w4
int * decode (int *)
Protected Member Functions inherited from Packet_A
int standardIntArray (int[], const int, int *, const char *what="")
Protected Attributes
int calculated_parity
int parity_comparison
int number_of_hits
int error_code
Additional Inherited Members
Static Protected Member Functions inherited from Packet_A
static void fix_endianess (long long *x)
static void fix_endianess (double *x)
static void fix_endianess (char *str, const int length)
Detailed Description
This is the packet which deals with data in PXL_DCM0 format. It inherits from Packet_w4 because the data are 32bit entities.
Definition at line 12 of file packet_fvtx_dcm0.h.
Constructor & Destructor Documentation
Packet_fvtx_dcm0::Packet_fvtx_dcm0 ()
Definition at line 3 of file packet_fvtx_dcm0.cc.
References calculated_parity, error_code, number_of_hits, and parity_comparison.
Packet_fvtx_dcm0::Packet_fvtx_dcm0 (PACKET_ptr data)
Definition at line 12 of file packet_fvtx_dcm0.cc.
References calculated_parity, error_code, number_of_hits, and parity_comparison.
Packet_fvtx_dcm0::~Packet_fvtx_dcm0 ()
Definition at line 22 of file packet_fvtx_dcm0.cc.
Member Function Documentation
int Packet_fvtx_dcm0::calculate_parity () protected
Definition at line 374 of file packet_fvtx_dcm0.cc.
References calculated_parity, dlength, findPacketDataStart(), Packet_A::getDataLength(), Packet_A::getHitFormat(), i, IDFVTX_SIM, iValue(), k, Packet_A::packet, and parity_comparison.
Referenced by iValue().
int * Packet_fvtx_dcm0::decode (int * nwout) protected virtual
Implements Packet_A.
Definition at line 238 of file packet_fvtx_dcm0.cc.
References Packet_A::data2_length, Packet_A::data3_length, Packet_A::data4_length, Packet_A::decoded_data2, Packet_A::decoded_data3, Packet_A::decoded_data4, dlength, error_code, findPacketDataStart(), Packet_A::getDataLength(), Packet_A::getHitFormat(), i, Packet_A::identify(), IDFVTX_SIM, k, number_of_hits, and Packet_A::packet.
Referenced by iValue().
int * Packet_fvtx_dcm0::decode_misc (int * nwout) protected virtual
Definition at line 422 of file packet_fvtx_dcm0.cc.
References dlength, findPacketDataStart(), Packet_A::getDataLength(), k, and Packet_A::packet.
Referenced by iValue().
void Packet_fvtx_dcm0::dump (OSTREAM & os) virtual
Definition at line 454 of file packet_fvtx_dcm0.cc.
References calculated_parity, Packet_A::identify(), and iValue().
int Packet_fvtx_dcm0::iValue (const int channel, const char * what) virtual
with the "what" parameter you can decide which aspect of
the data is made available. This class is one of those which have several different "kinds" of data; we use this to bring up the misc. items in the FEM headers and trailers.
In addition, there is {verbatim} packet->iValue(0,"EVTNR") packet->iValue(0,"DETID") packet->iValue(0,"MODADDR") packet->iValue(0,"FLAG") packet->iValue(0,"BCLCK") packet->iValue(0,"CHECKPARITY")
packet->iValue(0,"HITS") packet->iValue(i,"FEMID") == packet->iValue(i,0) packet->iValue(i,"CHIPID") == packet->iValue(i,1) packet->iValue(i,"CHANNEL") == packet->iValue(i,2) packet->iValue(i,"ADC") == packet->iValue(i,3)
{verbatim}
Reimplemented from Packet_A.
Definition at line 71 of file packet_fvtx_dcm0.cc.
References calculate_parity(), Packet_A::data1_length, Packet_A::data5_length, decode(), decode_misc(), Packet_A::decoded_data1, Packet_A::decoded_data2, Packet_A::decoded_data3, Packet_A::decoded_data4, Packet_A::decoded_data5, error_code, number_of_hits, and parity_comparison.
Referenced by calculate_parity(), and dump().
int Packet_fvtx_dcm0::iValue (const int channel, const int iy) virtual
this supports devices which are inherently organized as two-dimensional data, such as flash ADC's (channel vs time slice)
Reimplemented from Packet_A.
Definition at line 28 of file packet_fvtx_dcm0.cc.
References Packet_A::data1_length, decode(), Packet_A::decoded_data1, Packet_A::decoded_data2, Packet_A::decoded_data3, Packet_A::decoded_data4, error_code, and number_of_hits.
Member Data Documentation
int Packet_fvtx_dcm0::calculated_parity protected
Definition at line 58 of file packet_fvtx_dcm0.h.
Referenced by calculate_parity(), dump(), and Packet_fvtx_dcm0().
int Packet_fvtx_dcm0::error_code protected
Definition at line 62 of file packet_fvtx_dcm0.h.
Referenced by decode(), iValue(), and Packet_fvtx_dcm0().
int Packet_fvtx_dcm0::number_of_hits protected
Definition at line 60 of file packet_fvtx_dcm0.h.
Referenced by decode(), iValue(), and Packet_fvtx_dcm0().
int Packet_fvtx_dcm0::parity_comparison protected
Definition at line 59 of file packet_fvtx_dcm0.h.
Referenced by calculate_parity(), iValue(), and Packet_fvtx_dcm0().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/packet_fvtx_dcm0.h
online_distribution/blob/master/newbasic/packet_fvtx_dcm0.cc