Analysis Software: online_distribution/blob/master/newbasic/frameRoutines.C File Reference
frameRoutines.C File Reference
#include "phenixOnline.h"
#include "frameRoutines.h"
#include "framePublic.h"
#include "Cframe.h"
Functions
VALUE_ret storeFrameData (PHDWORD *frame_ptr, UINT maxFrameLen, PHDWORD *frameData, UINT dataDwords)
VALUE_ret storeFrameHistory (PHDWORD *frame_ptr, UINT maxFrameLen, PHDWORD *frameHistory, UINT historyDwords)
VALUE_ret extendFrameData (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT dataDwords)
VALUE_ret extendFrameDataNopad (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT dataDwords)
VALUE_ret extendFrameHistory (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT historyDwords)
VALUE_ret extendFrameHistoryNopad (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT historyDwords)
Function Documentation
VALUE_ret extendFrameData (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT dataDwords)
Definition at line 136 of file frameRoutines.C.
References adjustFrameDataLength(), adjustFrameLength(), TRUE, and valueFailure.
Referenced by appendEmptyFramePacket(), and storeFrameData().
VALUE_ret extendFrameDataNopad (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT dataDwords)
Definition at line 150 of file frameRoutines.C.
References adjustFrameDataLength(), adjustFrameLength(), FALSE, and valueFailure.
Referenced by fakeFrame().
VALUE_ret extendFrameHistory (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT historyDwords)
Definition at line 165 of file frameRoutines.C.
References adjustFrameHistoryLength(), adjustFrameLength(), TRUE, and valueFailure.
VALUE_ret extendFrameHistoryNopad (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT historyDwords)
Definition at line 179 of file frameRoutines.C.
References adjustFrameHistoryLength(), adjustFrameLength(), FALSE, and valueFailure.
Referenced by storeFrameHistory().
VALUE_ret storeFrameData (PHDWORD * frame_ptr, UINT maxFrameLen, PHDWORD * frameData, UINT dataDwords)
Definition at line 38 of file frameRoutines.C.
References currentFrameHdr(), dwordCopy, emptyFrame(), extendFrameData(), findFrameDataStart(), ptrFailure, removeFramePadding(), and valueFailure.
VALUE_ret storeFrameHistory (PHDWORD * frame_ptr, UINT maxFrameLen, PHDWORD * frameHistory, UINT historyDwords)
Definition at line 87 of file frameRoutines.C.
References currentFrameHdr(), dwordCopy, extendFrameHistoryNopad(), findFrameHistoryStart(), getFrameHistoryLength(), ptrFailure, removeFramePadding(), validFrameHdr(), and valueFailure.
Referenced by fakeFrame().