Analysis Software: SetupDualRICHAnalyzer Class Reference
SetupDualRICHAnalyzer Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/SetupDualRICHAnalyzer.h>
Public Member Functions
SetupDualRICHAnalyzer ()
double calculate_emission_angle (double m_emi[3], double momv[3], PHG4Hit *hit)
bool get_true_momentum (PHG4TruthInfoContainer *truthinfo, SvtxTrack *track, double arr_mom[3])
bool get_emission_momentum (PHG4TruthInfoContainer *truthinfo, PHG4HitContainer *richhits, SvtxTrack *track, double arr_mom[3])
Public Attributes
eic_dual_rich * _analyzer
Detailed Description
Definition at line 29 of file SetupDualRICHAnalyzer.h.
Constructor & Destructor Documentation
SetupDualRICHAnalyzer::SetupDualRICHAnalyzer ()
Definition at line 11 of file SetupDualRICHAnalyzer.cc.
Member Function Documentation
double SetupDualRICHAnalyzer::calculate_emission_angle (double m_emi[3], double momv[3], PHG4Hit * hit)
Definition at line 17 of file SetupDualRICHAnalyzer.cc.
References Dx, Dy, PHG4Hit::get_detid(), PHG4Hit::get_x(), PHG4Hit::get_y(), and PHG4Hit::get_z().
Referenced by RICHEvaluator::process_event(), and RICHParticleID::process_event().
bool SetupDualRICHAnalyzer::get_emission_momentum (PHG4TruthInfoContainer * truthinfo, PHG4HitContainer * richhits, SvtxTrack * track, double arr_mom[3])
Definition at line 69 of file SetupDualRICHAnalyzer.cc.
References dx, dy, PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetParticle(), and PHG4TruthInfoContainer::GetVtx().
Referenced by RICHEvaluator::process_event(), and RICHParticleID::process_event().
bool SetupDualRICHAnalyzer::get_true_momentum (PHG4TruthInfoContainer * truthinfo, SvtxTrack * track, double arr_mom[3])
Definition at line 50 of file SetupDualRICHAnalyzer.cc.
References PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_truth_track_id(), and PHG4TruthInfoContainer::GetParticle().
Referenced by RICHEvaluator::process_event(), and RICHParticleID::process_event().
Member Data Documentation
eic_dual_rich* SetupDualRICHAnalyzer::_analyzer
Definition at line 43 of file SetupDualRICHAnalyzer.h.
The documentation for this class was generated from the following files:
analysis/blob/master/ParticleID/RICHAnalysis/SetupDualRICHAnalyzer.h
analysis/blob/master/ParticleID/RICHAnalysis/SetupDualRICHAnalyzer.cc