Analysis Software: ZHough_Cylindrical Class Reference
ZHough_Cylindrical Class Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/helix_hough/CylindricalHough/ZHough_Cylindrical.h>
Public Member Functions
ZHough_Cylindrical (unsigned int z0_nbin, unsigned int theta_nbin, ZResolution &min_resolution, ZResolution &max_resolution, ZRange &range, double sxy, double sz)
~ZHough_Cylindrical ()
void findTracks (unsigned int zoomlevel, float xydiffcut, unsigned int max_hits, unsigned int tracks_per_hit, double chi2_cut, float max_kappa_cut, std::vector< SimpleTrack3D > &tracks, std::vector< SimpleHit3D > &hits, float min_k, float max_k, float min_phi, float max_phi, float min_d, float max_d, float min_z0, float max_z0, float min_theta, float max_theta, std::vector< float > &params)
void findTracksCombo_noVertex (std::vector< SimpleHit3D > &comb_hits, unsigned int zoomlevel, float xydiffcut, unsigned int max_hits, unsigned int tracks_per_hit, double chi2_cut, float max_kappa_cut, std::vector< SimpleTrack3D > &tracks, std::vector< SimpleHit3D > &hits, float min_k, float max_k, float min_phi, float max_phi, float min_d, float max_d, float min_z0, float max_z0, float min_theta, float max_theta, std::vector< float > &params)
void findTracksCombo_withVertex (std::vector< SimpleHit3D > &comb_hits, unsigned int zoomlevel, float xydiffcut, unsigned int max_hits, unsigned int tracks_per_hit, double chi2_cut, float max_kappa_cut, std::vector< SimpleTrack3D > &tracks, std::vector< SimpleHit3D > &hits, float min_k, float max_k, float min_phi, float max_phi, float min_d, float max_d, float min_z0, float max_z0, float min_theta, float max_theta, std::vector< float > &params)
void setNLayers (unsigned int n)
double fitTrack (SimpleTrack3D &track, std::vector< double > &chi2_hit)
void setLayerResolution (std::vector< double > &lxy, std::vector< double > &lz)
void setVertexResolution (double vxy, double vz)
double getLayerResolution_xy (unsigned int l)
double getLayerResolution_z (unsigned int l)
Private Attributes
unsigned int nlayers
std::vector< double > layer_xy_resolution
std::vector< double > layer_z_resolution
double vertex_sigma_xy
double vertex_sigma_z
Detailed Description
Definition at line 8 of file ZHough_Cylindrical.h.
Constructor & Destructor Documentation
ZHough_Cylindrical::ZHough_Cylindrical (unsigned int z0_nbin, unsigned int theta_nbin, ZResolution & min_resolution, ZResolution & max_resolution, ZRange & range, double sxy, double sz)
Definition at line 14 of file ZHough_Cylindrical.cpp.
ZHough_Cylindrical::~ZHough_Cylindrical ()
Definition at line 20 of file ZHough_Cylindrical.cpp.
Member Function Documentation
void ZHough_Cylindrical::findTracks (unsigned int zoomlevel, float xydiffcut, unsigned int max_hits, unsigned int tracks_per_hit, double chi2_cut, float max_kappa_cut, std::vector< SimpleTrack3D > & tracks, std::vector< SimpleHit3D > & hits, float min_k, float max_k, float min_phi, float max_phi, float min_d, float max_d, float min_z0, float max_z0, float min_theta, float max_theta, std::vector< float > & params)
Definition at line 26 of file ZHough_Cylindrical.cpp.
References findTracksCombo_noVertex(), and findTracksCombo_withVertex().
void ZHough_Cylindrical::findTracksCombo_noVertex (std::vector< SimpleHit3D > & comb_hits, unsigned int zoomlevel, float xydiffcut, unsigned int max_hits, unsigned int tracks_per_hit, double chi2_cut, float max_kappa_cut, std::vector< SimpleTrack3D > & tracks, std::vector< SimpleHit3D > & hits, float min_k, float max_k, float min_phi, float max_phi, float min_d, float max_d, float min_z0, float max_z0, float min_theta, float max_theta, std::vector< float > & params)
Definition at line 47 of file ZHough_Cylindrical.cpp.
References fitTrack(), SimpleTrack3D::hits, i, j, SimpleTrack3D::kappa, and M_PI.
Referenced by findTracks().
void ZHough_Cylindrical::findTracksCombo_withVertex (std::vector< SimpleHit3D > & comb_hits, unsigned int zoomlevel, float xydiffcut, unsigned int max_hits, unsigned int tracks_per_hit, double chi2_cut, float max_kappa_cut, std::vector< SimpleTrack3D > & tracks, std::vector< SimpleHit3D > & hits, float min_k, float max_k, float min_phi, float max_phi, float min_d, float max_d, float min_z0, float max_z0, float min_theta, float max_theta, std::vector< float > & params)
Definition at line 167 of file ZHough_Cylindrical.cpp.
References fitTrack(), SimpleTrack3D::hits, i, j, SimpleTrack3D::kappa, and M_PI.
Referenced by findTracks().
double ZHough_Cylindrical::fitTrack (SimpleTrack3D & track, std::vector< double > & chi2_hit)
Definition at line 272 of file ZHough_Cylindrical.cpp.
References SimpleTrack3D::d, d, double(), dx, dy, SimpleTrack3D::dzdl, dzdl, SVM_v1::h, SimpleTrack3D::hits, i, k, SimpleTrack3D::kappa, layer_xy_resolution, layer_z_resolution, SimpleTrack3D::phi, phi, r, s, temp1, temp2, v, vertex_sigma_xy, vertex_sigma_z, X, y, and SimpleTrack3D::z0.
Referenced by findTracksCombo_noVertex(), and findTracksCombo_withVertex().
double ZHough_Cylindrical::getLayerResolution_xy (unsigned int l) inline
Definition at line 36 of file ZHough_Cylindrical.h.
References layer_xy_resolution.
double ZHough_Cylindrical::getLayerResolution_z (unsigned int l) inline
Definition at line 37 of file ZHough_Cylindrical.h.
References layer_z_resolution.
void ZHough_Cylindrical::setLayerResolution (std::vector< double > & lxy, std::vector< double > & lz) inline
Definition at line 24 of file ZHough_Cylindrical.h.
References layer_xy_resolution, and layer_z_resolution.
void ZHough_Cylindrical::setNLayers (unsigned int n) inline
Definition at line 20 of file ZHough_Cylindrical.h.
References n, and nlayers.
void ZHough_Cylindrical::setVertexResolution (double vxy, double vz) inline
Definition at line 30 of file ZHough_Cylindrical.h.
References vertex_sigma_xy, and vertex_sigma_z.
Member Data Documentation
std::vector<double> ZHough_Cylindrical::layer_xy_resolution private
Definition at line 41 of file ZHough_Cylindrical.h.
Referenced by fitTrack(), getLayerResolution_xy(), and setLayerResolution().
std::vector<double> ZHough_Cylindrical::layer_z_resolution private
Definition at line 42 of file ZHough_Cylindrical.h.
Referenced by fitTrack(), getLayerResolution_z(), and setLayerResolution().
unsigned int ZHough_Cylindrical::nlayers private
Definition at line 40 of file ZHough_Cylindrical.h.
Referenced by setNLayers().
double ZHough_Cylindrical::vertex_sigma_xy private
Definition at line 43 of file ZHough_Cylindrical.h.
Referenced by fitTrack(), and setVertexResolution().
double ZHough_Cylindrical::vertex_sigma_z private
Definition at line 43 of file ZHough_Cylindrical.h.
Referenced by fitTrack(), and setVertexResolution().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/CylindricalHough/ZHough_Cylindrical.h
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/CylindricalHough/ZHough_Cylindrical.cpp