Analysis Software: SigmaTimingNtuple Class Reference
SigmaTimingNtuple Class Reference
#include <analysis/blob/master/AntiSigma/src/SigmaTimingNtuple.h>
Public Member Functions
SigmaTimingNtuple (const std::string &name="SigmaTimingNtuple", const std::string &filename="SigmaTimingNtuple.root")
constructor
virtual ~SigmaTimingNtuple ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
void AddNode (const std::string &name, const int detid=0)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
double get_dtotal (const PHG4Hit *hit, const double phi, const double theta)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
int nblocks
Fun4AllHistoManager * hm
std::vector< TH1 * > nhits
std::vector< TH1 * > eloss
std::string _filename
std::set< std::string > _node_postfix
std::map< std::string, int > _detid
TNtuple * ntupprim
TNtuple * ntupsec
TNtuple * ntupt
TNtuple * ntupsigma
TFile * outfile
gsl_rng * RandomGenerator
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 24 of file SigmaTimingNtuple.h.
Constructor & Destructor Documentation
SigmaTimingNtuple::SigmaTimingNtuple (const std::string & name = "SigmaTimingNtuple", const std::string & filename = "SigmaTimingNtuple.root")
constructor
Definition at line 35 of file SigmaTimingNtuple.cc.
References Fun4AllBase::Name(), RandomGenerator, and TauVsDIS_MachineLearning_Differentiation::seed.
SigmaTimingNtuple::~SigmaTimingNtuple () virtual
destructor
Definition at line 49 of file SigmaTimingNtuple.cc.
References hm.
Member Function Documentation
void SigmaTimingNtuple::AddNode (const std::string & name, const int detid = 0)
Definition at line 255 of file SigmaTimingNtuple.cc.
References _detid, _node_postfix, and name.
int SigmaTimingNtuple::End (PHCompositeNode * topNode) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 239 of file SigmaTimingNtuple.cc.
References _filename, Fun4AllHistoManager::dumpHistos(), hm, ntupprim, ntupsec, ntupsigma, ntupt, and outfile.
double SigmaTimingNtuple::get_dtotal (const PHG4Hit * hit, const double phi, const double theta) protected
Definition at line 263 of file SigmaTimingNtuple.cc.
References PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), M_PI, and phi.
Referenced by process_event().
int SigmaTimingNtuple::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 57 of file SigmaTimingNtuple.cc.
References _filename, eloss, h1, hm, Fun4AllBase::Name(), ntupprim, ntupsec, ntupsigma, ntupt, and outfile.
int SigmaTimingNtuple::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 77 of file SigmaTimingNtuple.cc.
References Fun4AllReturnCodes::ABORTEVENT, C_light, get_dtotal(), PHG4Particle::get_e(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetSecondaryParticleRange(), M_PI, MASSNEUTRON, MASSPION, ntupprim, ntupsec, ntupsigma, ntupt, RandomGenerator, and PHG4TruthInfoContainer::size().
Member Data Documentation
std::map<std::string, int> SigmaTimingNtuple::_detid protected
Definition at line 54 of file SigmaTimingNtuple.h.
Referenced by AddNode().
std::string SigmaTimingNtuple::_filename protected
Definition at line 52 of file SigmaTimingNtuple.h.
Referenced by End(), and Init().
std::set<std::string> SigmaTimingNtuple::_node_postfix protected
Definition at line 53 of file SigmaTimingNtuple.h.
Referenced by AddNode().
std::vector<TH1 *> SigmaTimingNtuple::eloss protected
Definition at line 50 of file SigmaTimingNtuple.h.
Referenced by Init().
Fun4AllHistoManager* SigmaTimingNtuple::hm protected
Definition at line 48 of file SigmaTimingNtuple.h.
Referenced by End(), Init(), and ~SigmaTimingNtuple().
int SigmaTimingNtuple::nblocks protected
Definition at line 47 of file SigmaTimingNtuple.h.
std::vector<TH1 *> SigmaTimingNtuple::nhits protected
Definition at line 49 of file SigmaTimingNtuple.h.
TNtuple* SigmaTimingNtuple::ntupprim protected
Definition at line 55 of file SigmaTimingNtuple.h.
Referenced by End(), Init(), and process_event().
TNtuple* SigmaTimingNtuple::ntupsec protected
Definition at line 56 of file SigmaTimingNtuple.h.
Referenced by End(), Init(), and process_event().
TNtuple* SigmaTimingNtuple::ntupsigma protected
Definition at line 58 of file SigmaTimingNtuple.h.
Referenced by End(), Init(), and process_event().
TNtuple* SigmaTimingNtuple::ntupt protected
Definition at line 57 of file SigmaTimingNtuple.h.
Referenced by End(), Init(), and process_event().
TFile* SigmaTimingNtuple::outfile protected
Definition at line 59 of file SigmaTimingNtuple.h.
Referenced by End(), and Init().
gsl_rng* SigmaTimingNtuple::RandomGenerator protected
Definition at line 61 of file SigmaTimingNtuple.h.
Referenced by process_event(), and SigmaTimingNtuple().
The documentation for this class was generated from the following files:
analysis/blob/master/AntiSigma/src/SigmaTimingNtuple.h
analysis/blob/master/AntiSigma/src/SigmaTimingNtuple.cc