Analysis Software: HijJet2 Class Reference
HijJet2 Class Reference
Class definition for HijJet2, which is used to modify the Hijing HIJJET2 common.
#include <coresoftware/blob/master/generators/sHijing/HijJet2.h>
Classes
struct HIJJET2
Public Member Functions
HijJet2 ()
~HijJet2 ()
int & nsg (void)
int & njsg (int i)
int & iasg (int i, int k)
int & k1sg (int i, int j)
int & k2sg (int i, int j)
float & pxsg (int i, int j)
float & pysg (int i, int j)
float & pzsg (int i, int j)
float & pesg (int i, int j)
float & pmsg (int i, int j)
void init (void)
int lenI () const
int lenJ () const
int lenK () const
Private Attributes
int _dummy
float _realdummy
Static Private Attributes
static const int _lenI = 900
static const int _lenJ = 100
static const int _lenK = 3
static HIJJET2 * _hijjet2 =0
Friends
struct HIJJET2
Detailed Description
Class definition for HijJet2, which is used to modify the Hijing HIJJET2 common.
Definition at line 12 of file HijJet2.h.
Constructor & Destructor Documentation
HijJet2::HijJet2 () inline
Definition at line 74 of file HijJet2.h.
HijJet2::~HijJet2 () inline
Definition at line 81 of file HijJet2.h.
Member Function Documentation
int & HijJet2::iasg (int i, int k) inline
Definition at line 100 of file HijJet2.h.
References _dummy, _hijjet2, HijJet2::HIJJET2::iasg, init(), lenI(), and lenK().
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
void HijJet2::init (void) inline
Definition at line 69 of file HijJet2.h.
References _hijjet2, and hijjet2_address_().
Referenced by iasg(), k1sg(), k2sg(), njsg(), nsg(), pesg(), pmsg(), pxsg(), pysg(), and pzsg().
int & HijJet2::k1sg (int i, int j) inline
Definition at line 110 of file HijJet2.h.
References _dummy, _hijjet2, init(), HijJet2::HIJJET2::k1sg, lenI(), and lenJ().
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
int & HijJet2::k2sg (int i, int j) inline
Definition at line 120 of file HijJet2.h.
References _dummy, _hijjet2, init(), HijJet2::HIJJET2::k2sg, lenI(), and lenJ().
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
int HijJet2::lenI () const inline
Definition at line 31 of file HijJet2.h.
References _lenI.
Referenced by iasg(), k1sg(), k2sg(), njsg(), pesg(), pmsg(), pxsg(), pysg(), and pzsg().
int HijJet2::lenJ () const inline
Definition at line 32 of file HijJet2.h.
References _lenJ.
Referenced by k1sg(), k2sg(), pesg(), pmsg(), pxsg(), pysg(), and pzsg().
int HijJet2::lenK () const inline
Definition at line 33 of file HijJet2.h.
References _lenK.
Referenced by iasg().
int & HijJet2::njsg (int i) inline
Definition at line 92 of file HijJet2.h.
References _dummy, _hijjet2, init(), lenI(), and HijJet2::HIJJET2::njsg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
int & HijJet2::nsg (void) inline
Definition at line 85 of file HijJet2.h.
References _hijjet2, init(), and HijJet2::HIJJET2::nsg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
float & HijJet2::pesg (int i, int j) inline
Definition at line 160 of file HijJet2.h.
References _hijjet2, _realdummy, init(), lenI(), lenJ(), and HijJet2::HIJJET2::pesg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
float & HijJet2::pmsg (int i, int j) inline
Definition at line 170 of file HijJet2.h.
References _hijjet2, _realdummy, init(), lenI(), lenJ(), and HijJet2::HIJJET2::pmsg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
float & HijJet2::pxsg (int i, int j) inline
Definition at line 130 of file HijJet2.h.
References _hijjet2, _realdummy, init(), lenI(), lenJ(), and HijJet2::HIJJET2::pxsg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
float & HijJet2::pysg (int i, int j) inline
Definition at line 140 of file HijJet2.h.
References _hijjet2, _realdummy, init(), lenI(), lenJ(), and HijJet2::HIJJET2::pysg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
float & HijJet2::pzsg (int i, int j) inline
Definition at line 150 of file HijJet2.h.
References _hijjet2, _realdummy, init(), lenI(), lenJ(), and HijJet2::HIJJET2::pzsg.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), and quench().
Friends And Related Function Documentation
friend struct HIJJET2 friend
Definition at line 42 of file HijJet2.h.
Member Data Documentation
int HijJet2::_dummy private
Definition at line 59 of file HijJet2.h.
Referenced by iasg(), k1sg(), k2sg(), and njsg().
HijJet2::HIJJET2 * HijJet2::_hijjet2 =0 static private
Definition at line 62 of file HijJet2.h.
Referenced by iasg(), init(), k1sg(), k2sg(), njsg(), nsg(), pesg(), pmsg(), pxsg(), pysg(), and pzsg().
const int HijJet2::_lenI = 900 static private
Definition at line 38 of file HijJet2.h.
Referenced by lenI().
const int HijJet2::_lenJ = 100 static private
Definition at line 39 of file HijJet2.h.
Referenced by lenJ().
const int HijJet2::_lenK = 3 static private
Definition at line 40 of file HijJet2.h.
Referenced by lenK().
float HijJet2::_realdummy private
Definition at line 60 of file HijJet2.h.
Referenced by pesg(), pmsg(), pxsg(), pysg(), and pzsg().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HijJet2.h