Analysis Software: GlobalVertexv1 Class Reference
GlobalVertexv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexv1.h>
Public Member Functions
GlobalVertexv1 ()
virtual ~GlobalVertexv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
float get_t () const
void set_t (float t)
float get_t_err () const
void set_t_err (float t_err)
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
float get_chisq () const
void set_chisq (float chisq)
unsigned int get_ndof () const
void set_ndof (unsigned int ndof)
float get_position (unsigned int coor) const
void set_position (unsigned int coor, float xi)
float get_error (unsigned int i, unsigned int j) const
void set_error (unsigned int i, unsigned int j, float value)
bool empty_vtxids () const
size_t size_vtxids () const
size_t count_vtxids (GlobalVertex::VTXTYPE type) const
void clear_vtxids ()
void insert_vtxids (GlobalVertex::VTXTYPE type, unsigned int vtxid)
size_t erase_vtxids (GlobalVertex::VTXTYPE type)
void erase_vtxids (GlobalVertex::VtxIter iter)
void erase_vtxids (GlobalVertex::VtxIter first, GlobalVertex::VtxIter last)
GlobalVertex::ConstVtxIter begin_vtxids () const
GlobalVertex::ConstVtxIter find_vtxids (GlobalVertex::VTXTYPE type) const
GlobalVertex::ConstVtxIter end_vtxids () const
GlobalVertex::VtxIter begin_vtxids ()
GlobalVertex::VtxIter find_vtxids (GlobalVertex::VTXTYPE type)
GlobalVertex::VtxIter end_vtxids ()
Public Member Functions inherited from GlobalVertex
virtual ~GlobalVertex ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
ClassDef (GlobalVertexv1, 1)
Private Attributes
unsigned int _id
float _t
float _t_err
float _pos [3]
float _chisq
unsigned int _ndof
float _err [6]
std::map
< GlobalVertex::VTXTYPE,
unsigned int > _vtx_ids
Additional Inherited Members
Public Types inherited from GlobalVertex
enum VTXTYPE { NONE = 0, BBC = 1, SVTX = 2 }
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::const_iterator ConstVtxIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::iterator VtxIter
Protected Member Functions inherited from GlobalVertex
GlobalVertex ()
Detailed Description
Definition at line 15 of file GlobalVertexv1.h.
Constructor & Destructor Documentation
GlobalVertexv1::GlobalVertexv1 ()
Definition at line 7 of file GlobalVertexv1.cc.
References _pos, i, j, and set_error().
Referenced by CloneMe(), and Reset().
GlobalVertexv1::~GlobalVertexv1 () virtual
Definition at line 28 of file GlobalVertexv1.cc.
Member Function Documentation
GlobalVertex::ConstVtxIter GlobalVertexv1::begin_vtxids () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 74 of file GlobalVertexv1.h.
References _vtx_ids.
Referenced by identify().
GlobalVertex::VtxIter GlobalVertexv1::begin_vtxids () inline virtual
Reimplemented from GlobalVertex.
Definition at line 78 of file GlobalVertexv1.h.
References _vtx_ids.
GlobalVertexv1::ClassDef (GlobalVertexv1 , 1) private
void GlobalVertexv1::clear_vtxids () inline virtual
Reimplemented from GlobalVertex.
Definition at line 68 of file GlobalVertexv1.h.
References _vtx_ids.
PHObject* GlobalVertexv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from GlobalVertex.
Definition at line 26 of file GlobalVertexv1.h.
References GlobalVertexv1().
size_t GlobalVertexv1::count_vtxids (GlobalVertex::VTXTYPE type) const inline virtual
Reimplemented from GlobalVertex.
Definition at line 66 of file GlobalVertexv1.h.
References _vtx_ids.
unsigned int GlobalVertexv1::covar_index (unsigned int i, unsigned int j) const private
Definition at line 101 of file GlobalVertexv1.cc.
References boost::swap().
Referenced by get_error(), and set_error().
bool GlobalVertexv1::empty_vtxids () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 64 of file GlobalVertexv1.h.
References _vtx_ids.
GlobalVertex::ConstVtxIter GlobalVertexv1::end_vtxids () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 76 of file GlobalVertexv1.h.
References _vtx_ids.
Referenced by identify().
GlobalVertex::VtxIter GlobalVertexv1::end_vtxids () inline virtual
Reimplemented from GlobalVertex.
Definition at line 80 of file GlobalVertexv1.h.
References _vtx_ids.
size_t GlobalVertexv1::erase_vtxids (GlobalVertex::VTXTYPE type) inline virtual
Reimplemented from GlobalVertex.
Definition at line 70 of file GlobalVertexv1.h.
References _vtx_ids.
void GlobalVertexv1::erase_vtxids (GlobalVertex::VtxIter iter) inline virtual
Reimplemented from GlobalVertex.
Definition at line 71 of file GlobalVertexv1.h.
References _vtx_ids.
void GlobalVertexv1::erase_vtxids (GlobalVertex::VtxIter first, GlobalVertex::VtxIter last) inline virtual
Reimplemented from GlobalVertex.
Definition at line 72 of file GlobalVertexv1.h.
References _vtx_ids.
GlobalVertex::ConstVtxIter GlobalVertexv1::find_vtxids (GlobalVertex::VTXTYPE type) const inline virtual
Reimplemented from GlobalVertex.
Definition at line 75 of file GlobalVertexv1.h.
References _vtx_ids.
GlobalVertex::VtxIter GlobalVertexv1::find_vtxids (GlobalVertex::VTXTYPE type) inline virtual
Reimplemented from GlobalVertex.
Definition at line 79 of file GlobalVertexv1.h.
References _vtx_ids.
float GlobalVertexv1::get_chisq () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 48 of file GlobalVertexv1.h.
References _chisq.
Referenced by identify().
float GlobalVertexv1::get_error (unsigned int i, unsigned int j) const virtual
Reimplemented from GlobalVertex.
Definition at line 96 of file GlobalVertexv1.cc.
References _err, and covar_index().
Referenced by identify(), and isValid().
unsigned int GlobalVertexv1::get_id () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 30 of file GlobalVertexv1.h.
References _id.
Referenced by identify().
unsigned int GlobalVertexv1::get_ndof () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 51 of file GlobalVertexv1.h.
References _ndof.
Referenced by identify().
float GlobalVertexv1::get_position (unsigned int coor) const inline virtual
Reimplemented from GlobalVertex.
Definition at line 54 of file GlobalVertexv1.h.
References _pos.
Referenced by identify().
float GlobalVertexv1::get_t () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 33 of file GlobalVertexv1.h.
References _t.
Referenced by identify().
float GlobalVertexv1::get_t_err () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 36 of file GlobalVertexv1.h.
References _t_err.
float GlobalVertexv1::get_x () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 39 of file GlobalVertexv1.h.
References _pos.
float GlobalVertexv1::get_y () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 42 of file GlobalVertexv1.h.
References _pos.
float GlobalVertexv1::get_z () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 45 of file GlobalVertexv1.h.
References _pos.
void GlobalVertexv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from GlobalVertex.
Definition at line 30 of file GlobalVertexv1.cc.
References begin_vtxids(), end_vtxids(), get_chisq(), get_error(), get_id(), get_ndof(), get_position(), and get_t().
void GlobalVertexv1::insert_vtxids (GlobalVertex::VTXTYPE type, unsigned int vtxid) inline virtual
Reimplemented from GlobalVertex.
Definition at line 69 of file GlobalVertexv1.h.
References _vtx_ids.
int GlobalVertexv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from GlobalVertex.
Definition at line 67 of file GlobalVertexv1.cc.
References _chisq, _id, _ndof, _pos, _t, _t_err, _vtx_ids, get_error(), i, and j.
void GlobalVertexv1::Reset () inline virtual
Clear Event.
Reimplemented from GlobalVertex.
Definition at line 24 of file GlobalVertexv1.h.
References GlobalVertexv1().
void GlobalVertexv1::set_chisq (float chisq) inline virtual
Reimplemented from GlobalVertex.
Definition at line 49 of file GlobalVertexv1.h.
References _chisq.
void GlobalVertexv1::set_error (unsigned int i, unsigned int j, float value) virtual
Reimplemented from GlobalVertex.
Definition at line 90 of file GlobalVertexv1.cc.
References _err, covar_index(), and value.
Referenced by GlobalVertexv1().
void GlobalVertexv1::set_id (unsigned int id) inline virtual
Reimplemented from GlobalVertex.
Definition at line 31 of file GlobalVertexv1.h.
References _id.
void GlobalVertexv1::set_ndof (unsigned int ndof) inline virtual
Reimplemented from GlobalVertex.
Definition at line 52 of file GlobalVertexv1.h.
References _ndof.
void GlobalVertexv1::set_position (unsigned int coor, float xi) inline virtual
Reimplemented from GlobalVertex.
Definition at line 55 of file GlobalVertexv1.h.
References _pos.
void GlobalVertexv1::set_t (float t) inline virtual
Reimplemented from GlobalVertex.
Definition at line 34 of file GlobalVertexv1.h.
References _t, and t.
void GlobalVertexv1::set_t_err (float t_err) inline virtual
Reimplemented from GlobalVertex.
Definition at line 37 of file GlobalVertexv1.h.
References _t_err.
void GlobalVertexv1::set_x (float x) inline virtual
Reimplemented from GlobalVertex.
Definition at line 40 of file GlobalVertexv1.h.
References _pos, and x.
void GlobalVertexv1::set_y (float y) inline virtual
Reimplemented from GlobalVertex.
Definition at line 43 of file GlobalVertexv1.h.
References _pos, and y.
void GlobalVertexv1::set_z (float z) inline virtual
Reimplemented from GlobalVertex.
Definition at line 46 of file GlobalVertexv1.h.
References _pos, and z.
size_t GlobalVertexv1::size_vtxids () const inline virtual
Reimplemented from GlobalVertex.
Definition at line 65 of file GlobalVertexv1.h.
References _vtx_ids.
Member Data Documentation
float GlobalVertexv1::_chisq private
Definition at line 89 of file GlobalVertexv1.h.
Referenced by get_chisq(), isValid(), and set_chisq().
float GlobalVertexv1::_err[6] private
Definition at line 91 of file GlobalVertexv1.h.
Referenced by get_error(), and set_error().
unsigned int GlobalVertexv1::_id private
Definition at line 85 of file GlobalVertexv1.h.
Referenced by get_id(), isValid(), and set_id().
unsigned int GlobalVertexv1::_ndof private
Definition at line 90 of file GlobalVertexv1.h.
Referenced by get_ndof(), isValid(), and set_ndof().
float GlobalVertexv1::_pos[3] private
Definition at line 88 of file GlobalVertexv1.h.
Referenced by get_position(), get_x(), get_y(), get_z(), GlobalVertexv1(), isValid(), set_position(), set_x(), set_y(), and set_z().
float GlobalVertexv1::_t private
Definition at line 86 of file GlobalVertexv1.h.
Referenced by get_t(), isValid(), and set_t().
float GlobalVertexv1::_t_err private
Definition at line 87 of file GlobalVertexv1.h.
Referenced by get_t_err(), isValid(), and set_t_err().
std::map<GlobalVertex::VTXTYPE, unsigned int> GlobalVertexv1::_vtx_ids private
Definition at line 92 of file GlobalVertexv1.h.
Referenced by begin_vtxids(), clear_vtxids(), count_vtxids(), empty_vtxids(), end_vtxids(), erase_vtxids(), find_vtxids(), insert_vtxids(), isValid(), and size_vtxids().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexv1.h
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexv1.cc