Analysis Software: GlobalVertex Class Reference
GlobalVertex Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertex.h>
Public Types
enum VTXTYPE { NONE = 0, BBC = 1, SVTX = 2 }
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::const_iterator ConstVtxIter
typedef std::map
< GlobalVertex::VTXTYPE,
unsigned int >::iterator VtxIter
Public Member Functions
virtual ~GlobalVertex ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual float get_t () const
virtual void set_t (float t)
virtual float get_t_err () const
virtual void set_t_err (float t_err)
virtual float get_x () const
virtual void set_x (float x)
virtual float get_y () const
virtual void set_y (float y)
virtual float get_z () const
virtual void set_z (float z)
virtual float get_chisq () const
virtual void set_chisq (float chisq)
virtual unsigned int get_ndof () const
virtual void set_ndof (unsigned int ndof)
virtual float get_position (unsigned int coor) const
virtual void set_position (unsigned int coor, float xi)
virtual float get_error (unsigned int i, unsigned int j) const
virtual void set_error (unsigned int i, unsigned int j, float value)
virtual bool empty_vtxids () const
virtual size_t size_vtxids () const
virtual size_t count_vtxids (VTXTYPE type) const
virtual void clear_vtxids ()
virtual void insert_vtxids (VTXTYPE type, unsigned int vtxid)
virtual size_t erase_vtxids (VTXTYPE type)
virtual void erase_vtxids (VtxIter iter)
virtual void erase_vtxids (VtxIter first, VtxIter last)
virtual ConstVtxIter begin_vtxids () const
virtual ConstVtxIter find_vtxids (VTXTYPE type) const
virtual ConstVtxIter end_vtxids () const
virtual VtxIter begin_vtxids ()
virtual VtxIter find_vtxids (VTXTYPE type)
virtual VtxIter end_vtxids ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
GlobalVertex ()
Private Member Functions
ClassDef (GlobalVertex, 1)
Detailed Description
Definition at line 12 of file GlobalVertex.h.
Member Typedef Documentation
typedef std::map<GlobalVertex::VTXTYPE, unsigned int>::const_iterator GlobalVertex::ConstVtxIter
Definition at line 22 of file GlobalVertex.h.
typedef std::map<GlobalVertex::VTXTYPE, unsigned int>::iterator GlobalVertex::VtxIter
Definition at line 23 of file GlobalVertex.h.
Member Enumeration Documentation
enum GlobalVertex::VTXTYPE
Enumerator:
NONE
BBC
SVTX
Definition at line 15 of file GlobalVertex.h.
Constructor & Destructor Documentation
virtual GlobalVertex::~GlobalVertex () inline virtual
Definition at line 25 of file GlobalVertex.h.
GlobalVertex::GlobalVertex () inline protected
Definition at line 91 of file GlobalVertex.h.
Member Function Documentation
virtual ConstVtxIter GlobalVertex::begin_vtxids () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 82 of file GlobalVertex.h.
virtual VtxIter GlobalVertex::begin_vtxids () inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 86 of file GlobalVertex.h.
GlobalVertex::ClassDef (GlobalVertex , 1) private
virtual void GlobalVertex::clear_vtxids () inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 76 of file GlobalVertex.h.
virtual PHObject* GlobalVertex::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in GlobalVertexv1.
Definition at line 35 of file GlobalVertex.h.
virtual size_t GlobalVertex::count_vtxids (VTXTYPE type) const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 74 of file GlobalVertex.h.
virtual bool GlobalVertex::empty_vtxids () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 72 of file GlobalVertex.h.
virtual ConstVtxIter GlobalVertex::end_vtxids () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 84 of file GlobalVertex.h.
virtual VtxIter GlobalVertex::end_vtxids () inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 88 of file GlobalVertex.h.
virtual size_t GlobalVertex::erase_vtxids (VTXTYPE type) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 78 of file GlobalVertex.h.
virtual void GlobalVertex::erase_vtxids (VtxIter iter) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 79 of file GlobalVertex.h.
virtual void GlobalVertex::erase_vtxids (VtxIter first, VtxIter last) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 80 of file GlobalVertex.h.
virtual ConstVtxIter GlobalVertex::find_vtxids (VTXTYPE type) const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 83 of file GlobalVertex.h.
virtual VtxIter GlobalVertex::find_vtxids (VTXTYPE type) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 87 of file GlobalVertex.h.
virtual float GlobalVertex::get_chisq () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 57 of file GlobalVertex.h.
virtual float GlobalVertex::get_error (unsigned int i, unsigned int j) const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 66 of file GlobalVertex.h.
virtual unsigned int GlobalVertex::get_id () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 39 of file GlobalVertex.h.
virtual unsigned int GlobalVertex::get_ndof () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 60 of file GlobalVertex.h.
virtual float GlobalVertex::get_position (unsigned int coor) const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 63 of file GlobalVertex.h.
virtual float GlobalVertex::get_t () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 42 of file GlobalVertex.h.
virtual float GlobalVertex::get_t_err () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 45 of file GlobalVertex.h.
virtual float GlobalVertex::get_x () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 48 of file GlobalVertex.h.
Referenced by PhotonJet::ConeSum(), CaloEvaluator::fillOutputNtuples(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), CaloEvaluator::printOutputInfo(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), PhotonJet::process_event(), and PHFlowJetMaker::run_particle_flow().
virtual float GlobalVertex::get_y () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 51 of file GlobalVertex.h.
Referenced by PhotonJet::ConeSum(), CaloEvaluator::fillOutputNtuples(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), CaloEvaluator::printOutputInfo(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), PhotonJet::process_event(), and PHFlowJetMaker::run_particle_flow().
virtual float GlobalVertex::get_z () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 54 of file GlobalVertex.h.
Referenced by PhotonJet::ConeSum(), CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), CaloEvaluator::printOutputInfo(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), PhotonJet::process_event(), and PHFlowJetMaker::run_particle_flow().
virtual void GlobalVertex::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in GlobalVertexv1.
Definition at line 29 of file GlobalVertex.h.
References os.
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::insert_vtxids (VTXTYPE type, unsigned int vtxid) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 77 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual int GlobalVertex::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in GlobalVertexv1.
Definition at line 34 of file GlobalVertex.h.
virtual void GlobalVertex::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in GlobalVertexv1.
Definition at line 33 of file GlobalVertex.h.
virtual void GlobalVertex::set_chisq (float chisq) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 58 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::set_error (unsigned int i, unsigned int j, float value) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 67 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_id (unsigned int id) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 40 of file GlobalVertex.h.
virtual void GlobalVertex::set_ndof (unsigned int ndof) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 61 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::set_position (unsigned int coor, float xi) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 64 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event().
virtual void GlobalVertex::set_t (float t) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 43 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_t_err (float t_err) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 46 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_x (float x) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 49 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_y (float y) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 52 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual void GlobalVertex::set_z (float z) inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 55 of file GlobalVertex.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual size_t GlobalVertex::size_vtxids () const inline virtual
Reimplemented in GlobalVertexv1.
Definition at line 73 of file GlobalVertex.h.
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertex.h