Analysis Software: PgPostCalBankIterator Class Reference
PgPostCalBankIterator Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBankIterator.h>
Classes
class ValPeriod
Public Member Functions
PgPostCalBankIterator (PgPostBankManager &bm)
virtual ~PgPostCalBankIterator ()
virtual bool init (const std::string &fulldbname, const PdbBankID &bankid)
virtual bool isValid () const
virtual void print (std::ostream &os=std::cout) const
virtual void setBankID (const PdbBankID &id)
virtual void setEndValTimeLimits (const PHTimeStamp &min=PHTimeStamp(0), const PHTimeStamp &max=PHTimeStamp(PHTimeStamp::PHFarFuture))
virtual void setInsertTimeLimits (const PHTimeStamp &min=PHTimeStamp(0), const PHTimeStamp &max=PHTimeStamp(PHTimeStamp::PHFarFuture))
virtual void setStartValTimeLimits (const PHTimeStamp &min=PHTimeStamp(0), const PHTimeStamp &max=PHTimeStamp(PHTimeStamp::PHFarFuture))
virtual PdbCalBank * next ()
Public Member Functions inherited from PdbCalBankIterator
virtual ~PdbCalBankIterator ()
Private Types
typedef std::map< std::string,
ValPeriod > TimeMap
Private Attributes
TimeMap fTimeMap
PgPostBankManager & fBM
PgPostApplication * fApplication
std::string fDBName
std::string fTableName
bool fIsValid
PdbBankID fBankID
TSQLStatement * fSQLStatement
TSQLResultSet * fSQLResultSet
Detailed Description
Definition at line 22 of file PgPostCalBankIterator.h.
Member Typedef Documentation
typedef std::map<std::string, ValPeriod> PgPostCalBankIterator::TimeMap private
Definition at line 66 of file PgPostCalBankIterator.h.
Constructor & Destructor Documentation
PgPostCalBankIterator::PgPostCalBankIterator (PgPostBankManager & bm)
Definition at line 28 of file PgPostCalBankIterator.cc.
References fApplication, fBM, PgPostBankManager::getApplication(), and PHWHERE.
PgPostCalBankIterator::~PgPostCalBankIterator () virtual
Definition at line 47 of file PgPostCalBankIterator.cc.
References fSQLResultSet, and fSQLStatement.
Member Function Documentation
bool PgPostCalBankIterator::init (const std::string & fulldbname, const PdbBankID & bankid) virtual
Implements PdbCalBankIterator.
Definition at line 54 of file PgPostCalBankIterator.cc.
References fApplication, fBankID, fDBName, fIsValid, fSQLResultSet, fSQLStatement, PgPostApplication::getConnection(), PdbBankID::getInternalValue(), PHWHERE, and PgPostApplication::startRead().
bool PgPostCalBankIterator::isValid () const virtual
Implements PdbCalBankIterator.
Definition at line 98 of file PgPostCalBankIterator.cc.
References fIsValid.
PdbCalBank * PgPostCalBankIterator::next () virtual
Implements PdbCalBankIterator.
Definition at line 105 of file PgPostCalBankIterator.cc.
References PgPostCalBankIterator::ValPeriod::end(), fIsValid, fSQLResultSet, fTableName, fTimeMap, it, PgPostBankWrapper::setBankID(), PgPostBankWrapper::setDescription(), PgPostBankWrapper::setEndValTime(), PgPostBankWrapper::setInsertTime(), PgPostBankWrapper::setStartValTime(), PgPostBankWrapper::setTableName(), PgPostBankWrapper::setUserName(), and PgPostCalBankIterator::ValPeriod::start().
void PgPostCalBankIterator::print (std::ostream & os = std::cout) const virtual
Implements PdbCalBankIterator.
Definition at line 195 of file PgPostCalBankIterator.cc.
References fBankID, fDBName, fTableName, fTimeMap, PdbBankID::getInternalValue(), and it.
void PgPostCalBankIterator::setBankID (const PdbBankID & id) virtual
Implements PdbCalBankIterator.
Definition at line 212 of file PgPostCalBankIterator.cc.
References fBankID.
void PgPostCalBankIterator::setEndValTimeLimits (const PHTimeStamp & min = PHTimeStamp(0), const PHTimeStamp & max = PHTimeStamp(PHTimeStamp::PHFarFuture)) virtual
Implements PdbCalBankIterator.
Definition at line 218 of file PgPostCalBankIterator.cc.
References fTimeMap.
void PgPostCalBankIterator::setInsertTimeLimits (const PHTimeStamp & min = PHTimeStamp(0), const PHTimeStamp & max = PHTimeStamp(PHTimeStamp::PHFarFuture)) virtual
Implements PdbCalBankIterator.
Definition at line 225 of file PgPostCalBankIterator.cc.
References fTimeMap.
void PgPostCalBankIterator::setStartValTimeLimits (const PHTimeStamp & min = PHTimeStamp(0), const PHTimeStamp & max = PHTimeStamp(PHTimeStamp::PHFarFuture)) virtual
Implements PdbCalBankIterator.
Definition at line 232 of file PgPostCalBankIterator.cc.
References fTimeMap.
Member Data Documentation
PgPostApplication* PgPostCalBankIterator::fApplication private
Definition at line 70 of file PgPostCalBankIterator.h.
Referenced by init(), and PgPostCalBankIterator().
PdbBankID PgPostCalBankIterator::fBankID private
Definition at line 74 of file PgPostCalBankIterator.h.
Referenced by init(), print(), and setBankID().
PgPostBankManager& PgPostCalBankIterator::fBM private
Definition at line 69 of file PgPostCalBankIterator.h.
Referenced by PgPostCalBankIterator().
std::string PgPostCalBankIterator::fDBName private
Definition at line 71 of file PgPostCalBankIterator.h.
Referenced by init(), and print().
bool PgPostCalBankIterator::fIsValid private
Definition at line 73 of file PgPostCalBankIterator.h.
Referenced by init(), isValid(), and next().
TSQLResultSet* PgPostCalBankIterator::fSQLResultSet private
Definition at line 76 of file PgPostCalBankIterator.h.
Referenced by init(), next(), and ~PgPostCalBankIterator().
TSQLStatement* PgPostCalBankIterator::fSQLStatement private
Definition at line 75 of file PgPostCalBankIterator.h.
Referenced by init(), and ~PgPostCalBankIterator().
std::string PgPostCalBankIterator::fTableName private
Definition at line 72 of file PgPostCalBankIterator.h.
Referenced by next(), and print().
TimeMap PgPostCalBankIterator::fTimeMap private
Definition at line 67 of file PgPostCalBankIterator.h.
Referenced by next(), print(), setEndValTimeLimits(), setInsertTimeLimits(), and setStartValTimeLimits().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBankIterator.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBankIterator.cc