Analysis Software: JetTruthEval Class Reference
JetTruthEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/JetTruthEval.h>
Public Member Functions
JetTruthEval (PHCompositeNode *topNode, const std::string &truthjetname)
example truthjetname: AntiKt_Truth_r03
virtual ~JetTruthEval ()
void next_event (PHCompositeNode *topNode)
reinitialize the eval for a new event
void do_caching (bool do_cache)
activate or deactivate the memory caching inside the evaluation module
void set_strict (bool strict)
unsigned int get_errors ()
get a count of the errors discovered thus far
void set_verbosity (int verbosity)
adjust the messaging from the evalutaion module
SvtxEvalStack * get_svtx_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_cemc_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_hcalin_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_hcalout_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_femc_eval_stack ()
get a copy of the lower level eval and its memory cache
CaloEvalStack * get_fhcal_eval_stack ()
get a copy of the lower level eval and its memory cache
Jet * get_truth_jet (PHG4Particle *truthparticle)
which truth jet in the specified node contains this truth particle?
std::set< PHG4Particle * > all_truth_particles (Jet *truthjet)
which truth particle contributed to this truth jet?
std::set< PHG4Shower * > all_truth_showers (Jet *truthjet)
which showers were left by particles contributing to this truth jet?
std::set< PHG4Hit * > all_truth_hits (Jet *truthjet)
which truth hits were left by particles contributing to this truth jet?
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
Private Attributes
std::string _truthjetname
SvtxEvalStack _svtxevalstack
CaloEvalStack _cemcevalstack
CaloEvalStack _hcalinevalstack
CaloEvalStack _hcaloutevalstack
CaloEvalStack _femcevalstack
CaloEvalStack _fhcalevalstack
PHG4TruthInfoContainer * _truthinfo
JetMap * _truthjets
bool _strict
int _verbosity
unsigned int _errors
bool _do_cache
std::map< Jet *, std::set
< PHG4Particle * > > _cache_all_truth_particles
std::map< Jet *, std::set
< PHG4Shower * > > _cache_all_truth_showers
std::map< Jet *, std::set
< PHG4Hit * > > _cache_all_truth_hits
std::map< PHG4Particle *, Jet * > _cache_get_truth_jet
Detailed Description
Definition at line 21 of file JetTruthEval.h.
Constructor & Destructor Documentation
JetTruthEval::JetTruthEval (PHCompositeNode * topNode, const std::string & truthjetname)
example truthjetname: AntiKt_Truth_r03
Definition at line 22 of file JetTruthEval.cc.
References get_node_pointers().
JetTruthEval::~JetTruthEval () virtual
Definition at line 45 of file JetTruthEval.cc.
References _errors, and _verbosity.
Member Function Documentation
std::set< PHG4Hit * > JetTruthEval::all_truth_hits (Jet * truthjet)
which truth hits were left by particles contributing to this truth jet?
Definition at line 187 of file JetTruthEval.cc.
References _cache_all_truth_hits, _do_cache, _errors, _strict, _svtxevalstack, SvtxTruthEval::all_truth_hits(), all_truth_particles(), assert, and SvtxEvalStack::get_truth_eval().
std::set< PHG4Particle * > JetTruthEval::all_truth_particles (Jet * truthjet)
which truth particle contributed to this truth jet?
Definition at line 73 of file JetTruthEval.cc.
References _cache_all_truth_particles, _do_cache, _errors, _strict, _truthinfo, assert, Jet::begin_comp(), Jet::end_comp(), PHG4TruthInfoContainer::GetParticle(), index, Jet::PARTICLE, and PHWHERE.
Referenced by all_truth_hits(), all_truth_showers(), JetRecoEval::get_energy_contribution(), PhotonJet::GetRecoHadronsAndJets(), and PhotonJet::process_event().
std::set< PHG4Shower * > JetTruthEval::all_truth_showers (Jet * truthjet)
which showers were left by particles contributing to this truth jet?
Definition at line 130 of file JetTruthEval.cc.
References _cache_all_truth_showers, _cemcevalstack, _do_cache, _errors, _strict, all_truth_particles(), assert, CaloTruthEval::get_primary_shower(), and CaloEvalStack::get_truth_eval().
void JetTruthEval::do_caching (bool do_cache) inline
activate or deactivate the memory caching inside the evaluation module
Definition at line 33 of file JetTruthEval.h.
References _cemcevalstack, _do_cache, _femcevalstack, _fhcalevalstack, _hcalinevalstack, _hcaloutevalstack, _svtxevalstack, SvtxEvalStack::do_caching(), and CaloEvalStack::do_caching().
Referenced by JetRecoEval::do_caching().
CaloEvalStack* JetTruthEval::get_cemc_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 79 of file JetTruthEval.h.
References _cemcevalstack.
Referenced by JetRecoEval::get_cemc_eval_stack().
unsigned int JetTruthEval::get_errors () inline
get a count of the errors discovered thus far
Definition at line 58 of file JetTruthEval.h.
References _cemcevalstack, _errors, _femcevalstack, _fhcalevalstack, _hcalinevalstack, _hcaloutevalstack, _svtxevalstack, CaloEvalStack::get_errors(), and SvtxEvalStack::get_errors().
Referenced by JetRecoEval::get_errors().
CaloEvalStack* JetTruthEval::get_femc_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 88 of file JetTruthEval.h.
References _femcevalstack.
Referenced by JetRecoEval::get_femc_eval_stack().
CaloEvalStack* JetTruthEval::get_fhcal_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 91 of file JetTruthEval.h.
References _fhcalevalstack.
Referenced by JetRecoEval::get_fhcal_eval_stack().
CaloEvalStack* JetTruthEval::get_hcalin_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 82 of file JetTruthEval.h.
References _hcalinevalstack.
Referenced by JetRecoEval::get_hcalin_eval_stack().
CaloEvalStack* JetTruthEval::get_hcalout_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 85 of file JetTruthEval.h.
References _hcaloutevalstack.
Referenced by JetRecoEval::get_hcalout_eval_stack().
void JetTruthEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 323 of file JetTruthEval.cc.
References _truthinfo, _truthjetname, _truthjets, and PHWHERE.
Referenced by JetTruthEval(), and next_event().
SvtxEvalStack* JetTruthEval::get_svtx_eval_stack () inline
get a copy of the lower level eval and its memory cache
Definition at line 76 of file JetTruthEval.h.
References _svtxevalstack.
Referenced by JetRecoEval::get_svtx_eval_stack(), and get_truth_jet().
Jet * JetTruthEval::get_truth_jet (PHG4Particle * truthparticle)
which truth jet in the specified node contains this truth particle?
Definition at line 259 of file JetTruthEval.cc.
References _cache_get_truth_jet, _do_cache, _errors, _strict, _truthinfo, _truthjets, assert, JetMap::begin(), Jet::begin_comp(), JetMap::end(), Jet::end_comp(), get_svtx_eval_stack(), PHG4TruthInfoContainer::GetParticle(), and index.
Referenced by JetRecoEval::all_truth_jets().
void JetTruthEval::next_event (PHCompositeNode * topNode)
reinitialize the eval for a new event
Definition at line 56 of file JetTruthEval.cc.
References _cache_all_truth_hits, _cache_all_truth_particles, _cache_all_truth_showers, _cache_get_truth_jet, _cemcevalstack, _femcevalstack, _fhcalevalstack, _hcalinevalstack, _hcaloutevalstack, _svtxevalstack, get_node_pointers(), SvtxEvalStack::next_event(), and CaloEvalStack::next_event().
Referenced by JetRecoEval::next_event().
void JetTruthEval::set_strict (bool strict) inline
strict mode will assert when an error is detected non-strict mode will notice and report at the End()
Definition at line 46 of file JetTruthEval.h.
References _cemcevalstack, _femcevalstack, _fhcalevalstack, _hcalinevalstack, _hcaloutevalstack, _strict, _svtxevalstack, SvtxEvalStack::set_strict(), and CaloEvalStack::set_strict().
Referenced by JetRecoEval::set_strict().
void JetTruthEval::set_verbosity (int verbosity) inline
adjust the messaging from the evalutaion module
Definition at line 64 of file JetTruthEval.h.
References _cemcevalstack, _femcevalstack, _fhcalevalstack, _hcalinevalstack, _hcaloutevalstack, _svtxevalstack, _verbosity, CaloEvalStack::set_verbosity(), SvtxEvalStack::set_verbosity(), and verbosity.
Referenced by JetRecoEval::set_verbosity().
Member Data Documentation
std::map<Jet*, std::set<PHG4Hit*> > JetTruthEval::_cache_all_truth_hits private
Definition at line 130 of file JetTruthEval.h.
Referenced by all_truth_hits(), and next_event().
std::map<Jet*, std::set<PHG4Particle*> > JetTruthEval::_cache_all_truth_particles private
Definition at line 128 of file JetTruthEval.h.
Referenced by all_truth_particles(), and next_event().
std::map<Jet*, std::set<PHG4Shower*> > JetTruthEval::_cache_all_truth_showers private
Definition at line 129 of file JetTruthEval.h.
Referenced by all_truth_showers(), and next_event().
std::map<PHG4Particle*, Jet*> JetTruthEval::_cache_get_truth_jet private
Definition at line 131 of file JetTruthEval.h.
Referenced by get_truth_jet(), and next_event().
CaloEvalStack JetTruthEval::_cemcevalstack private
Definition at line 114 of file JetTruthEval.h.
Referenced by all_truth_showers(), do_caching(), get_cemc_eval_stack(), get_errors(), next_event(), set_strict(), and set_verbosity().
bool JetTruthEval::_do_cache private
Definition at line 127 of file JetTruthEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), do_caching(), and get_truth_jet().
unsigned int JetTruthEval::_errors private
Definition at line 125 of file JetTruthEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_errors(), get_truth_jet(), and ~JetTruthEval().
CaloEvalStack JetTruthEval::_femcevalstack private
Definition at line 117 of file JetTruthEval.h.
Referenced by do_caching(), get_errors(), get_femc_eval_stack(), next_event(), set_strict(), and set_verbosity().
CaloEvalStack JetTruthEval::_fhcalevalstack private
Definition at line 118 of file JetTruthEval.h.
Referenced by do_caching(), get_errors(), get_fhcal_eval_stack(), next_event(), set_strict(), and set_verbosity().
CaloEvalStack JetTruthEval::_hcalinevalstack private
Definition at line 115 of file JetTruthEval.h.
Referenced by do_caching(), get_errors(), get_hcalin_eval_stack(), next_event(), set_strict(), and set_verbosity().
CaloEvalStack JetTruthEval::_hcaloutevalstack private
Definition at line 116 of file JetTruthEval.h.
Referenced by do_caching(), get_errors(), get_hcalout_eval_stack(), next_event(), set_strict(), and set_verbosity().
bool JetTruthEval::_strict private
Definition at line 123 of file JetTruthEval.h.
Referenced by all_truth_hits(), all_truth_particles(), all_truth_showers(), get_truth_jet(), and set_strict().
SvtxEvalStack JetTruthEval::_svtxevalstack private
Definition at line 113 of file JetTruthEval.h.
Referenced by all_truth_hits(), do_caching(), get_errors(), get_svtx_eval_stack(), next_event(), set_strict(), and set_verbosity().
PHG4TruthInfoContainer* JetTruthEval::_truthinfo private
Definition at line 120 of file JetTruthEval.h.
Referenced by all_truth_particles(), get_node_pointers(), and get_truth_jet().
std::string JetTruthEval::_truthjetname private
Definition at line 112 of file JetTruthEval.h.
Referenced by get_node_pointers().
JetMap* JetTruthEval::_truthjets private
Definition at line 121 of file JetTruthEval.h.
Referenced by get_node_pointers(), and get_truth_jet().
int JetTruthEval::_verbosity private
Definition at line 124 of file JetTruthEval.h.
Referenced by set_verbosity(), and ~JetTruthEval().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/JetTruthEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/JetTruthEval.cc