Analysis Software: TpcPrototypeDefs::FEEv2 Namespace Reference
TpcPrototypeDefs::FEEv2 Namespace Reference
TPC v1 FEE test stand decoder.
Classes
class SampleFit_PowerLawDoubleExp_PDFMaker
Functions
bool SampleFit_PowerLawDoubleExp (const std::vector< double > &samples,double &peak,double &peak_sample,double &pedestal,std::map< int, double > &parameters_io,const int verbosity=0)
Power law double exp fit.
double SignalShape_PowerLawExp (double *x, double *par)
double SignalShape_PowerLawDoubleExp (double *x, double *par)
Variables
static const unsigned int kPACKET_ID = 3000
static const unsigned int kPACKET_LENGTH = 137
static const unsigned int kN_CHANNELS = 256
static const unsigned int kSAMPLE_LENGTH = 128
static const unsigned int kN_FEES = 8
static const unsigned int kMaxPadY =16*8
static const unsigned int kMaxPadX =16
static TPCR2Map TpcR2Map
static R2 channel map
Detailed Description
TPC v1 FEE test stand decoder.
Function Documentation
bool TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp (const std::vector< double > & samples, double & peak, double & peak_sample, double & pedestal, std::map< int, double > & parameters_io, const int verbosity)
Power law double exp fit.
Parameters
peak_sample peak amplitude.
pedestal peak sample position. Fixed to the input value if NOT NAN
parameters_io pedestal
verbosity IO for fullset of parameters. If a parameter exist and not an NAN, the fit parameter will be fixed to that value. The order of the parameters are ("Amplitude 1", "Sample Start", "Power", "Peak Time 1", "Pedestal", "Amplitude 2", "Peak Time 2")
Definition at line 68 of file TpcPrototypeDefs.cc.
References assert, f2(), gpulse, i, max, min, NSAMPLES, pedestal(), TPCDaqDefs::FEEv1::SignalShape_PowerLawDoubleExp(), and TPCDaqDefs::FEEv1::SignalShape_PowerLawExp().
Referenced by RawTower_Prototype4::get_energy_power_law_double_exp().
double TpcPrototypeDefs::FEEv2::SignalShape_PowerLawDoubleExp (double * x, double * par)
Definition at line 298 of file TpcPrototypeDefs.cc.
References pedestal(), and signal().
double TpcPrototypeDefs::FEEv2::SignalShape_PowerLawExp (double * x, double * par)
Definition at line 286 of file TpcPrototypeDefs.cc.
References pedestal(), and signal().
Variable Documentation
const unsigned int TpcPrototypeDefs::FEEv2::kMaxPadX =16 static
Definition at line 28 of file TpcPrototypeDefs.h.
const unsigned int TpcPrototypeDefs::FEEv2::kMaxPadY =16*8 static
Definition at line 27 of file TpcPrototypeDefs.h.
const unsigned int TpcPrototypeDefs::FEEv2::kN_CHANNELS = 256 static
Definition at line 23 of file TpcPrototypeDefs.h.
const unsigned int TpcPrototypeDefs::FEEv2::kN_FEES = 8 static
Definition at line 26 of file TpcPrototypeDefs.h.
Referenced by TpcPrototypeUnpacker::process_event().
const unsigned int TpcPrototypeDefs::FEEv2::kPACKET_ID = 3000 static
Definition at line 20 of file TpcPrototypeDefs.h.
const unsigned int TpcPrototypeDefs::FEEv2::kPACKET_LENGTH = 137 static
Definition at line 22 of file TpcPrototypeDefs.h.
const unsigned int TpcPrototypeDefs::FEEv2::kSAMPLE_LENGTH = 128 static
Definition at line 24 of file TpcPrototypeDefs.h.
TPCR2Map TpcPrototypeDefs::FEEv2::TpcR2Map static
static R2 channel map
Definition at line 32 of file TpcPrototypeDefs.h.
Referenced by TpcPrototypeUnpacker::process_event().