Analysis Software: RawClusterBuilderTemplate Class Reference
RawClusterBuilderTemplate Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTemplate.h>
Public Member Functions
RawClusterBuilderTemplate (const std::string &name="RawClusterBuilderGraph")
virtual ~RawClusterBuilderTemplate ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void Detector (const std::string &d)
void set_threshold_energy (const float e)
void setEnergyNorm (float norm)
void checkenergy (const int i=1)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool CorrectPhi (RawCluster *cluster, RawTowerContainer *towers, RawTowerGeomContainer *towergemom)
bool Cell2Abs (RawTowerGeomContainer *towergeom, float phiC, float etaC, float &phi, float &eta)
Private Attributes
RawClusterContainer * _clusters
BEmcRecCEMC * bemc
float fEnergyNorm
float _min_tower_e
int chkenergyconservation
std::string detector
std::string ClusterNodeName
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 15 of file RawClusterBuilderTemplate.h.
Constructor & Destructor Documentation
RawClusterBuilderTemplate::RawClusterBuilderTemplate (const std::string & name = "RawClusterBuilderGraph")
Definition at line 42 of file RawClusterBuilderTemplate.cc.
References bemc, fEnergyNorm, BEmcRec::SetGeometry(), BEmcRec::SetTowerThreshold(), and BEmcRec::SetVertex().
RawClusterBuilderTemplate::~RawClusterBuilderTemplate () virtual
Definition at line 37 of file RawClusterBuilderTemplate.cc.
Member Function Documentation
bool RawClusterBuilderTemplate::Cell2Abs (RawTowerGeomContainer * towergeom, float phiC, float etaC, float & phi, float & eta) private
Definition at line 105 of file RawClusterBuilderTemplate.cc.
References RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_etacenter(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_phicenter(), and printf().
Referenced by process_event().
void RawClusterBuilderTemplate::checkenergy (const int i = 1) inline
Definition at line 28 of file RawClusterBuilderTemplate.h.
References chkenergyconservation, and i.
bool RawClusterBuilderTemplate::CorrectPhi (RawCluster * cluster, RawTowerContainer * towers, RawTowerGeomContainer * towergemom) private
Definition at line 345 of file RawClusterBuilderTemplate.cc.
References RawTower::get_binphi(), RawCluster::get_energy(), RawTower::get_energy(), RawTowerGeomContainer::get_phicenter(), RawCluster::get_towers(), RawTowerContainer::getTower(), M_PI, phi, phimin, RawCluster::set_phi(), and sum().
void RawClusterBuilderTemplate::CreateNodes (PHCompositeNode * topNode) private
Definition at line 398 of file RawClusterBuilderTemplate.cc.
References _clusters, PHCompositeNode::addNode(), ClusterNodeName, detector, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void RawClusterBuilderTemplate::Detector (const std::string & d) inline
Definition at line 24 of file RawClusterBuilderTemplate.h.
References d.
Referenced by CEMC_Clusters(), HCALInner_Clusters(), and HCALOuter_Clusters().
int RawClusterBuilderTemplate::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 393 of file RawClusterBuilderTemplate.cc.
References Fun4AllReturnCodes::EVENT_OK.
int RawClusterBuilderTemplate::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 63 of file RawClusterBuilderTemplate.cc.
References Fun4AllReturnCodes::ABORTEVENT, CreateNodes(), RawTowerDefs::decode_index1(), RawTowerDefs::decode_index2(), detector, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_id(), RawTowerGeomContainer::get_tower_geometries(), and PHWHERE.
int RawClusterBuilderTemplate::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 152 of file RawClusterBuilderTemplate.cc.
References _clusters, _min_tower_e, Fun4AllReturnCodes::ABORTEVENT, RawClusterContainer::AddCluster(), RawCluster::addTower(), EmcModule::amp, bemc, Cell2Abs(), chkenergyconservation, detector, Fun4AllReturnCodes::DISCARDEVENT, RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, fEnergyNorm, BEmcRec::FindClusters(), RawTower::get_bineta(), RawTower::get_binphi(), RawTower::get_energy(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_radius(), RawTowerContainer::getCalorimeterID(), BEmcRec::GetClusters(), RawClusterContainer::getTotalEdep(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTowers(), EmcModule::ich, M_PI, phi, PHWHERE, printf(), RawCluster::set_chi2(), RawCluster::set_ecore(), RawCluster::set_energy(), RawCluster::set_phi(), RawCluster::set_prob(), RawCluster::set_r(), RawCluster::set_z(), BEmcRec::SetGeometry(), BEmcRec::SetModules(), and EmcModule::tof.
void RawClusterBuilderTemplate::set_threshold_energy (const float e) inline
Definition at line 26 of file RawClusterBuilderTemplate.h.
References _min_tower_e.
void RawClusterBuilderTemplate::setEnergyNorm (float norm) inline
Definition at line 27 of file RawClusterBuilderTemplate.h.
References fEnergyNorm, and norm.
Member Data Documentation
RawClusterContainer* RawClusterBuilderTemplate::_clusters private
Definition at line 35 of file RawClusterBuilderTemplate.h.
Referenced by CreateNodes(), and process_event().
float RawClusterBuilderTemplate::_min_tower_e private
Definition at line 40 of file RawClusterBuilderTemplate.h.
Referenced by process_event(), and set_threshold_energy().
BEmcRecCEMC* RawClusterBuilderTemplate::bemc private
Definition at line 37 of file RawClusterBuilderTemplate.h.
Referenced by process_event(), and RawClusterBuilderTemplate().
int RawClusterBuilderTemplate::chkenergyconservation private
Definition at line 41 of file RawClusterBuilderTemplate.h.
Referenced by checkenergy(), and process_event().
std::string RawClusterBuilderTemplate::ClusterNodeName private
Definition at line 44 of file RawClusterBuilderTemplate.h.
Referenced by CreateNodes().
std::string RawClusterBuilderTemplate::detector private
Definition at line 43 of file RawClusterBuilderTemplate.h.
Referenced by CreateNodes(), InitRun(), and process_event().
float RawClusterBuilderTemplate::fEnergyNorm private
Definition at line 38 of file RawClusterBuilderTemplate.h.
Referenced by process_event(), RawClusterBuilderTemplate(), and setEnergyNorm().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTemplate.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderTemplate.cc