Analysis Software: PHG4InttSubsystem Class Reference
PHG4InttSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttSubsystem.h>
Public Types
typedef std::vector< std::pair
< int, int > > vpair
Public Types inherited from PHG4DetectorGroupSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Public Member Functions
PHG4InttSubsystem (const std::string &name="PHG4InttSubsystem", const vpair &layerconfig=vpair(0))
constructor
virtual ~PHG4InttSubsystem ()
destructor
int InitRunSubsystem (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
PHG4Detector * GetDetector (void) const
accessors (reimplemented)
PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void Print (const std::string &what="ALL") const
Public Member Functions inherited from PHG4DetectorGroupSubsystem
virtual ~PHG4DetectorGroupSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParametersContainer * GetParamsContainer () const
void set_double_param (const int detid, const std::string &name, const double dval)
double get_double_param (const int detid, const std::string &name) const
void set_int_param (const int detid, const std::string &name, const int ival)
int get_int_param (const int detid, const std::string &name) const
void set_string_param (const int detid, const std::string &name, const std::string &sval)
std::string get_string_param (const int detid, const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int detid, const int i)
void SetActive (const int i=1)
void SetAbsorberActive (const int detid, const int i)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int detid, const int i)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int detid, const int i)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters ()
Private Attributes
PHG4InttDetector * m_Detector
detector geometry
PHG4SteppingAction * m_SteppingAction
particle tracking "stepping" action
PHG4DisplayAction * m_DisplayAction
display attribute setting
vpair m_LayerConfigVector
std::string m_DetectorType
Additional Inherited Members
Protected Member Functions inherited from PHG4DetectorGroupSubsystem
PHG4DetectorGroupSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void AddDetId (const int i)
std::pair< std::set< int >
::const_iterator, std::set
< int >::const_iterator > GetDetIds () const
void set_default_double_param (const int detid, const std::string &name, const double dval)
void set_default_int_param (const int detid, const std::string &name, const int ival)
void set_default_string_param (const int detid, const std::string &name, const std::string &sval)
int BeginRunExecuted () const
void PrintDefaultParams () const
void PrintMacroParams () const
Detailed Description
Definition at line 18 of file PHG4InttSubsystem.h.
Member Typedef Documentation
typedef std::vector<std::pair<int, int> > PHG4InttSubsystem::vpair
Definition at line 21 of file PHG4InttSubsystem.h.
Constructor & Destructor Documentation
PHG4InttSubsystem::PHG4InttSubsystem (const std::string & name = "PHG4InttSubsystem", const vpair & layerconfig = vpair(0))
constructor
Definition at line 34 of file PHG4InttSubsystem.cc.
References PHG4DetectorGroupSubsystem::AddDetId(), PHG4DetectorGroupSubsystem::InitializeParameters(), Fun4AllBase::Name(), and PHG4DetectorGroupSubsystem::SuperDetector().
PHG4InttSubsystem::~PHG4InttSubsystem () virtual
destructor
Definition at line 54 of file PHG4InttSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
PHG4Detector * PHG4InttSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 153 of file PHG4InttSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4InttSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 50 of file PHG4InttSubsystem.h.
References m_DisplayAction.
PHG4SteppingAction* PHG4InttSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 48 of file PHG4InttSubsystem.h.
References m_SteppingAction.
int PHG4InttSubsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
init
called during InitRun (the original InitRun does common setup and calls this one) creates the detector object ceates the stepping action creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorGroupSubsystem.
Definition at line 60 of file PHG4InttSubsystem.cc.
References PHCompositeNode::addNode(), PHG4DetectorGroupSubsystem::CheckOverlap(), PHNodeIterator::findFirst(), PHParameters::get_int_param(), PHG4DetectorGroupSubsystem::GetDetIds(), PHParametersContainer::GetParameters(), PHG4DetectorGroupSubsystem::GetParamsContainer(), m_Detector, m_DetectorType, m_DisplayAction, m_LayerConfigVector, m_SteppingAction, Fun4AllBase::Name(), PHG4DetectorGroupSubsystem::SuperDetector(), PHG4InttDefs::SUPPORTPARAMS, PHG4Detector::topNode(), and Fun4AllBase::Verbosity().
void PHG4InttSubsystem::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 326 of file PHG4InttSubsystem.cc.
References PHG4DetectorGroupSubsystem::GetParamsContainer(), PHParametersContainer::Print(), PHG4DetectorGroupSubsystem::PrintDefaultParams(), and PHG4DetectorGroupSubsystem::PrintMacroParams().
int PHG4InttSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 140 of file PHG4InttSubsystem.cc.
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4InttSubsystem::SetDefaultParameters () private virtual
Implements PHG4DetectorGroupSubsystem.
Definition at line 158 of file PHG4InttSubsystem.cc.
References PHG4DetectorGroupSubsystem::GetDetIds(), laddertype, nladder, PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, sensor_radius, PHG4DetectorGroupSubsystem::set_default_double_param(), PHG4DetectorGroupSubsystem::set_default_int_param(), and PHG4InttDefs::SUPPORTPARAMS.
Member Data Documentation
PHG4InttDetector* PHG4InttSubsystem::m_Detector private
detector geometry
defives from PHG4Detector
Definition at line 59 of file PHG4InttSubsystem.h.
Referenced by GetDetector(), and InitRunSubsystem().
std::string PHG4InttSubsystem::m_DetectorType private
Definition at line 70 of file PHG4InttSubsystem.h.
Referenced by InitRunSubsystem().
PHG4DisplayAction* PHG4InttSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 67 of file PHG4InttSubsystem.h.
Referenced by GetDisplayAction(), InitRunSubsystem(), and ~PHG4InttSubsystem().
vpair PHG4InttSubsystem::m_LayerConfigVector private
Definition at line 69 of file PHG4InttSubsystem.h.
Referenced by InitRunSubsystem().
PHG4SteppingAction* PHG4InttSubsystem::m_SteppingAction private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 63 of file PHG4InttSubsystem.h.
Referenced by GetSteppingAction(), InitRunSubsystem(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttSubsystem.cc