Analysis Software: RawClusterBuilderFwd Class Reference
RawClusterBuilderFwd Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderFwd.h>
Public Member Functions
RawClusterBuilderFwd (const std::string &name="RawClusterBuilder")
virtual ~RawClusterBuilderFwd ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void Detector (const std::string &d)
void set_threshold_energy (const float e)
void checkenergy (const int i=1)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool CorrectPhi (RawCluster *cluster, RawTowerContainer *towers, RawTowerGeomContainer *towergemom)
Private Attributes
RawClusterContainer * _clusters
float _min_tower_e
int chkenergyconservation
std::string detector
std::string ClusterNodeName
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file RawClusterBuilderFwd.h.
Constructor & Destructor Documentation
RawClusterBuilderFwd::RawClusterBuilderFwd (const std::string & name = "RawClusterBuilder")
Definition at line 95 of file RawClusterBuilderFwd.cc.
virtual RawClusterBuilderFwd::~RawClusterBuilderFwd () inline virtual
Definition at line 18 of file RawClusterBuilderFwd.h.
Member Function Documentation
void RawClusterBuilderFwd::checkenergy (const int i = 1) inline
Definition at line 26 of file RawClusterBuilderFwd.h.
References chkenergyconservation, and i.
bool RawClusterBuilderFwd::CorrectPhi (RawCluster * cluster, RawTowerContainer * towers, RawTowerGeomContainer * towergemom) private
Definition at line 257 of file RawClusterBuilderFwd.cc.
References RawCluster::get_energy(), RawTower::get_energy(), RawTower::get_id(), RawTowerGeom::get_phi(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_towers(), RawTowerContainer::getTower(), M_PI, phi, phimin, RawCluster::set_phi(), and sum().
void RawClusterBuilderFwd::CreateNodes (PHCompositeNode * topNode) private
Definition at line 314 of file RawClusterBuilderFwd.cc.
References _clusters, PHCompositeNode::addNode(), ClusterNodeName, detector, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void RawClusterBuilderFwd::Detector (const std::string & d) inline
Definition at line 23 of file RawClusterBuilderFwd.h.
References d.
Referenced by EEMC_Clusters(), FEMC_Clusters(), and FHCAL_Clusters().
int RawClusterBuilderFwd::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 309 of file RawClusterBuilderFwd.cc.
References Fun4AllReturnCodes::EVENT_OK.
int RawClusterBuilderFwd::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 104 of file RawClusterBuilderFwd.cc.
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
int RawClusterBuilderFwd::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 119 of file RawClusterBuilderFwd.cc.
References _clusters, _min_tower_e, Fun4AllReturnCodes::ABORTEVENT, RawClusterContainer::AddCluster(), RawCluster::addTower(), assert, chkenergyconservation, detector, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_center_x(), RawTowerGeom::get_center_y(), RawTowerGeom::get_center_z(), RawTower::get_energy(), RawTower::get_id(), twrs_fwd::get_id(), RawCluster::get_id(), RawTowerGeomContainer::get_tower_geometry(), RawCluster::get_towermap(), RawClusterContainer::getClustersMap(), RawClusterContainer::getTotalEdep(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), RawCluster::identify(), PHMakeGroups(), PHWHERE, RawCluster::set_energy(), twrs_fwd::set_id(), RawCluster::set_phi(), RawCluster::set_r(), RawCluster::set_z(), and Fun4AllBase::Verbosity().
void RawClusterBuilderFwd::set_threshold_energy (const float e) inline
Definition at line 25 of file RawClusterBuilderFwd.h.
References _min_tower_e.
Referenced by FEMC_Clusters(), and FHCAL_Clusters().
Member Data Documentation
RawClusterContainer* RawClusterBuilderFwd::_clusters private
Definition at line 32 of file RawClusterBuilderFwd.h.
Referenced by CreateNodes(), and process_event().
float RawClusterBuilderFwd::_min_tower_e private
Definition at line 34 of file RawClusterBuilderFwd.h.
Referenced by process_event(), and set_threshold_energy().
int RawClusterBuilderFwd::chkenergyconservation private
Definition at line 35 of file RawClusterBuilderFwd.h.
Referenced by checkenergy(), and process_event().
std::string RawClusterBuilderFwd::ClusterNodeName private
Definition at line 38 of file RawClusterBuilderFwd.h.
Referenced by CreateNodes().
std::string RawClusterBuilderFwd::detector private
Definition at line 37 of file RawClusterBuilderFwd.h.
Referenced by CreateNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderFwd.h
coresoftware/blob/master/offline/packages/CaloReco/RawClusterBuilderFwd.cc