Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_FEMC_EIC.C File Reference
G4_FEMC_EIC.C File Reference
Functions
void FEMCInit ()
void FEMC_Cells (int verbosity=0)
void FEMCSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void FEMC_Towers (int verbosity=0)
void FEMC_Clusters (int verbosity=0)
void FEMC_Eval (std::string outputfile, int verbosity=0)
Function Documentation
void FEMC_Cells (int verbosity = 0)
Definition at line 8 of file G4_FEMC_EIC.C.
References PHG4ForwardCalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
void FEMC_Clusters (int verbosity = 0)
Definition at line 86 of file G4_FEMC_EIC.C.
References RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void FEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 100 of file G4_FEMC_EIC.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void FEMC_Towers (int verbosity = 0)
Definition at line 49 of file G4_FEMC_EIC.C.
References RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), RawTowerDigitizer::TowerType(), RawTowerCalibration::TowerType(), verbosity, and Fun4AllBase::Verbosity().
void FEMCInit ()
Definition at line 4 of file G4_FEMC_EIC.C.
void FEMCSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated FEMC module
Definition at line 22 of file G4_FEMC_EIC.C.
References femc, Fun4AllServer::instance(), overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4ForwardEcalSubsystem::SetEICDetector(), and PHG4ForwardEcalSubsystem::SetTowerMappingFile().