Analysis Software: JetHepMCLoader Class Reference
JetHepMCLoader Class Reference
JetHepMCLoader loads special jet objects encoded in HepMC records to DST Jet nodes. Example use are loading sHijing HIJFRG jets.
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/JetHepMCLoader.h>
Classes
struct hepmc_jet_src
Public Member Functions
JetHepMCLoader (const std::string &jetInputCategory)
virtual ~JetHepMCLoader ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void addJet (const std::string &name, int embeddingID, Jet::ALGO algorithm, double parameter, int tagPID, int tagStatus)
addJet add HepMC entries for a particular type of jets Example of adding sHijing HIJFRG truth jets with R=0.4:
void saveQAPlots (bool b=true)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
Fun4AllHistoManager * getHistoManager ()
Private Attributes
std::string m_jetInputCategory
bool m_saveQAPlots
std::vector< hepmc_jet_src > m_jetSrc
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
JetHepMCLoader loads special jet objects encoded in HepMC records to DST Jet nodes. Example use are loading sHijing HIJFRG jets.
Example use for readback HIJFRAG truth jets from the sHijing HepMC records:
JetHepMCLoader * hepmcjet = new JetHepMCLoader("sHijing_HIJFRG");
hepmcjet->saveQAPlots();
hepmcjet->addJet("AntiKt_sHijing_HIJFRG_r02",0,Jet::ANTIKT,0.2,2000000,103);
hepmcjet->addJet("AntiKt_sHijing_HIJFRG_r04",0,Jet::ANTIKT,0.4,4000000,103);
hepmcjet->addJet("AntiKt_sHijing_HIJFRG_r06",0,Jet::ANTIKT,0.6,6000000,103);
se->registerSubsystem(hepmcjet);
Definition at line 42 of file JetHepMCLoader.h.
Constructor & Destructor Documentation
JetHepMCLoader::JetHepMCLoader (const std::string & jetInputCategory)
Parameters
[in] jetInputCategory is the DST PHCompositeNode name that list the output jet maps, e.g. sHijing_HIJFRG for sHijing HIJFRG truth jets
Definition at line 49 of file JetHepMCLoader.cc.
JetHepMCLoader::~JetHepMCLoader () virtual
Definition at line 56 of file JetHepMCLoader.cc.
Member Function Documentation
void JetHepMCLoader::addJet (const std::string & name, int embeddingID, Jet::ALGO algorithm, double parameter, int tagPID, int tagStatus)
addJet add HepMC entries for a particular type of jets Example of adding sHijing HIJFRG truth jets with R=0.4:
addJet("AntiKt_sHijing_HIJFRG_r04",0,"ANTIKT",0.4,4000000,103);
Parameters
[in] name name of the jet category
[in] embeddingID hepmc event's embedding ID
[in] algorithm pick one from Jet::ALGO
[in] parameter jet parameter, e.g. radius
[in] tagPID HepMC entry identifying tag on PID
[in] tagStatus HepMC entry identifying tag on status
Definition at line 215 of file JetHepMCLoader.cc.
References algorithm, Jet::ANTIKT, Jet::CAMBRIDGE, Jet::KT, m_jetSrc, and name.
int JetHepMCLoader::CreateNodes (PHCompositeNode * topNode) private
Definition at line 249 of file JetHepMCLoader.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_jetInputCategory, m_jetSrc, and PHWHERE.
Referenced by InitRun().
int JetHepMCLoader::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 201 of file JetHepMCLoader.cc.
References assert, Fun4AllHistoManager::dumpHistos(), Fun4AllReturnCodes::EVENT_OK, getHistoManager(), m_saveQAPlots, and Fun4AllBase::Name().
Fun4AllHistoManager * JetHepMCLoader::getHistoManager () private
Definition at line 292 of file JetHepMCLoader.cc.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), Fun4AllBase::Name(), and Fun4AllServer::registerHistoManager().
Referenced by End(), InitRun(), and process_event().
int JetHepMCLoader::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 60 of file JetHepMCLoader.cc.
References Fun4AllReturnCodes::EVENT_OK.
int JetHepMCLoader::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 65 of file JetHepMCLoader.cc.
References assert, CreateNodes(), getHistoManager(), SVM_v1::h, i, m_jetSrc, m_saveQAPlots, and Fun4AllHistoManager::registerHisto().
int JetHepMCLoader::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 98 of file JetHepMCLoader.cc.
References Fun4AllReturnCodes::ABORTEVENT, assert, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, PHHepMCGenEventMap::get(), PHHepMCGenEvent::get_embedding_id(), Jet::get_et(), Jet::get_eta(), PHHepMCGenEvent::getEvent(), Fun4AllHistoManager::getHisto(), getHistoManager(), Jet::HEPMC_IMPORT, PHHepMCGenEvent::identify(), JetMap::insert(), Jet::insert_comp(), JetMap::insert_src(), m_jetSrc, m_saveQAPlots, PHWHERE, JetMap::set_algo(), Jet::set_e(), JetMap::set_par(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_A_LOT.
void JetHepMCLoader::saveQAPlots (bool b = true) inline
Definition at line 73 of file JetHepMCLoader.h.
References m_saveQAPlots.
Member Data Documentation
std::string JetHepMCLoader::m_jetInputCategory private
Definition at line 79 of file JetHepMCLoader.h.
Referenced by CreateNodes().
std::vector<hepmc_jet_src> JetHepMCLoader::m_jetSrc private
Definition at line 106 of file JetHepMCLoader.h.
Referenced by addJet(), CreateNodes(), InitRun(), and process_event().
bool JetHepMCLoader::m_saveQAPlots private
Definition at line 81 of file JetHepMCLoader.h.
Referenced by End(), InitRun(), process_event(), and saveQAPlots().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/JetHepMCLoader.h
coresoftware/blob/master/simulation/g4simulation/g4jets/JetHepMCLoader.cc