Analysis Software: GenericUnpackPRDF Class Reference
GenericUnpackPRDF Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/GenericUnpackPRDF.h>
Public Member Functions
GenericUnpackPRDF (const std::string &detector)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const int packet_id, const int channel, const int tower_id)
add stuff to be unpacked
GenericUnpackPRDF (const std::string &detector)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const int packet_id, const int channel, const int tower_id)
add stuff to be unpacked
GenericUnpackPRDF (const std::string &detector)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
void add_channel (const int packet_id, const int channel, const int tower_id)
add stuff to be unpacked
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
typedef std::pair< int, int > hbd_channel_typ
packet_id, channel number to define a hbd_channel
typedef std::map
< hbd_channel_typ, int > hbd_channel_map
list of hbd_channel -> channel id which is also tower id
typedef std::pair< int, int > hbd_channel_typ
packet_id, channel number to define a hbd_channel
typedef std::map
< hbd_channel_typ, int > hbd_channel_map
list of hbd_channel -> channel id which is also tower id
typedef std::pair< int, int > channel_typ
packet_id, channel number to define a hbd_channel
typedef std::map< channel_typ,
int > channel_map
list of hbd_channel -> channel id which is also tower id
Private Attributes
std::string _detector
hbd_channel_map _hbd_channel_map
RawTowerContainer * _towers
channel_map _channel_map
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 15 of file GenericUnpackPRDF.h.
Member Typedef Documentation
typedef std::map<channel_typ, int> GenericUnpackPRDF::channel_map private
list of hbd_channel -> channel id which is also tower id
Definition at line 39 of file GenericUnpackPRDF.h.
typedef std::pair<int, int> GenericUnpackPRDF::channel_typ private
packet_id, channel number to define a hbd_channel
Definition at line 36 of file GenericUnpackPRDF.h.
typedef std::map<hbd_channel_typ, int> GenericUnpackPRDF::hbd_channel_map private
list of hbd_channel -> channel id which is also tower id
Definition at line 39 of file GenericUnpackPRDF.h.
typedef std::map<hbd_channel_typ, int> GenericUnpackPRDF::hbd_channel_map private
list of hbd_channel -> channel id which is also tower id
Definition at line 39 of file GenericUnpackPRDF.h.
typedef std::pair<int, int> GenericUnpackPRDF::hbd_channel_typ private
packet_id, channel number to define a hbd_channel
Definition at line 36 of file GenericUnpackPRDF.h.
typedef std::pair<int, int> GenericUnpackPRDF::hbd_channel_typ private
packet_id, channel number to define a hbd_channel
Definition at line 36 of file GenericUnpackPRDF.h.
Constructor & Destructor Documentation
GenericUnpackPRDF::GenericUnpackPRDF (const std::string & detector)
Definition at line 32 of file GenericUnpackPRDF.cc.
GenericUnpackPRDF::GenericUnpackPRDF (const std::string & detector)
GenericUnpackPRDF::GenericUnpackPRDF (const std::string & detector)
Member Function Documentation
void GenericUnpackPRDF::add_channel (const int packet_id, const int channel, const int tower_id)
add stuff to be unpacked
Parameters
channel packet id
tower_id channel in packet output tower id
Definition at line 145 of file GenericUnpackPRDF.cc.
References _hbd_channel_map.
Referenced by Fun4All_TestBeam().
void GenericUnpackPRDF::add_channel (const int packet_id, const int channel, const int tower_id)
add stuff to be unpacked
Parameters
channel packet id
tower_id channel in packet output tower id
void GenericUnpackPRDF::add_channel (const int packet_id, const int channel, const int tower_id)
add stuff to be unpacked
Parameters
channel packet id
tower_id channel in packet output tower id
void GenericUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 114 of file GenericUnpackPRDF.cc.
References _detector, _towers, PHCompositeNode::addNode(), PHNodeIterator::findFirst(), RawTowerDefs::NONE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
void GenericUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
void GenericUnpackPRDF::CreateNodeTree (PHCompositeNode * topNode)
int GenericUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file GenericUnpackPRDF.cc.
References CreateNodeTree(), and Fun4AllReturnCodes::EVENT_OK.
int GenericUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int GenericUnpackPRDF::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int GenericUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int GenericUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int GenericUnpackPRDF::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 48 of file GenericUnpackPRDF.cc.
References _hbd_channel_map, _towers, RawTowerContainer::AddTower(), assert, channel(), Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, Event::getPacket(), RawTowerContainer::getTower(), Event::identify(), it, Packet::iValue(), PROTOTYPE2_FEM::NSAMPLES, RawTower_Prototype2::set_energy(), RawTower_Prototype2::set_HBD_channel_number(), RawTower_Prototype2::set_signal_samples(), Packet::setInternalParameter(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Member Data Documentation
channel_map GenericUnpackPRDF::_channel_map private
Definition at line 41 of file GenericUnpackPRDF.h.
std::string GenericUnpackPRDF::_detector private
Definition at line 33 of file GenericUnpackPRDF.h.
Referenced by CreateNodeTree().
hbd_channel_map GenericUnpackPRDF::_hbd_channel_map private
Definition at line 41 of file GenericUnpackPRDF.h.
Referenced by add_channel(), and process_event().
RawTowerContainer * GenericUnpackPRDF::_towers private
Definition at line 44 of file GenericUnpackPRDF.h.
Referenced by CreateNodeTree(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/GenericUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype3/GenericUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype4/GenericUnpackPRDF.h
prototype/blob/master/offline/packages/Prototype2/GenericUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype3/GenericUnpackPRDF.cc
prototype/blob/master/offline/packages/Prototype4/GenericUnpackPRDF.cc