Analysis Software: JetEvalStack Class Reference
JetEvalStack Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/JetEvalStack.h>
Public Member Functions
JetEvalStack (PHCompositeNode *topNode, const std::string &recojetname, const std::string &truthjetname)
virtual ~JetEvalStack ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
JetRecoEval * get_reco_eval ()
JetTruthEval * get_truth_eval ()
SvtxEvalStack * get_stvx_eval_stack ()
CaloEvalStack * get_cemc_eval_stack ()
CaloEvalStack * get_hcalin_eval_stack ()
CaloEvalStack * get_hcalout_eval_stack ()
CaloEvalStack * get_femc_eval_stack ()
CaloEvalStack * get_fhcal_eval_stack ()
Private Attributes
JetRecoEval _recoeval
Detailed Description
Definition at line 19 of file JetEvalStack.h.
Constructor & Destructor Documentation
JetEvalStack::JetEvalStack (PHCompositeNode * topNode, const std::string & recojetname, const std::string & truthjetname)
Definition at line 3 of file JetEvalStack.cc.
virtual JetEvalStack::~JetEvalStack () inline virtual
Definition at line 25 of file JetEvalStack.h.
Member Function Documentation
void JetEvalStack::do_caching (bool do_cache) inline
Definition at line 28 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::do_caching().
CaloEvalStack* JetEvalStack::get_cemc_eval_stack () inline
Definition at line 36 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_cemc_eval_stack().
CaloEvalStack* JetEvalStack::get_femc_eval_stack () inline
Definition at line 39 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_femc_eval_stack().
CaloEvalStack* JetEvalStack::get_fhcal_eval_stack () inline
Definition at line 40 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_fhcal_eval_stack().
CaloEvalStack* JetEvalStack::get_hcalin_eval_stack () inline
Definition at line 37 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_hcalin_eval_stack().
CaloEvalStack* JetEvalStack::get_hcalout_eval_stack () inline
Definition at line 38 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_hcalout_eval_stack().
JetRecoEval* JetEvalStack::get_reco_eval () inline
Definition at line 32 of file JetEvalStack.h.
References _recoeval.
Referenced by JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), and PhotonJet::process_event().
SvtxEvalStack* JetEvalStack::get_stvx_eval_stack () inline
Definition at line 35 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_svtx_eval_stack().
JetTruthEval* JetEvalStack::get_truth_eval () inline
Definition at line 33 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::get_truth_eval().
Referenced by TruthPhotonJet::process_event(), and PhotonJet::process_event().
void JetEvalStack::next_event (PHCompositeNode * topNode)
Definition at line 10 of file JetEvalStack.cc.
References _recoeval, and JetRecoEval::next_event().
Referenced by JetEvaluator::process_event(), and JetEnergies::process_event().
void JetEvalStack::set_strict (bool strict) inline
Definition at line 29 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::set_strict().
Referenced by JetEvaluator::process_event(), and JetEnergies::process_event().
void JetEvalStack::set_verbosity (int verbosity) inline
Definition at line 30 of file JetEvalStack.h.
References _recoeval, and JetRecoEval::set_verbosity().
Referenced by JetEvaluator::process_event(), and JetEnergies::process_event().
Member Data Documentation
JetRecoEval JetEvalStack::_recoeval private
Definition at line 43 of file JetEvalStack.h.
Referenced by do_caching(), get_cemc_eval_stack(), get_femc_eval_stack(), get_fhcal_eval_stack(), get_hcalin_eval_stack(), get_hcalout_eval_stack(), get_reco_eval(), get_stvx_eval_stack(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/JetEvalStack.h
coresoftware/blob/master/simulation/g4simulation/g4eval/JetEvalStack.cc