Analysis Software: BDiJetModule Class Reference
BDiJetModule Class Reference
#include <analysis/blob/master/HF-Jet/HFDiJetMomImbalance/BDiJetModule.h>
Public Member Functions
BDiJetModule (const std::string &name="BDiJetModule", const std::string &ofName="out.root")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void ResetVariables ()
int GetNodes (PHCompositeNode *)
Reset TTree variables.
void InitTree ()
Get all nodes.
PHGenFit::Track * MakeGenFitTrack (PHCompositeNode *, const SvtxTrack *intrack, const SvtxVertex *vertex)
Initialize the TTree.
void FillVertexMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const std::vector< genfit::Track * > &gf_tracks)
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
int GetSVMass_mom (const genfit::GFRaveVertex *rave_vtx, float &vtx_mass, float &vtx_px, float &vtx_py, float &vtx_pz)
Private Attributes
JetMap * _jetmap_truth
SvtxClusterMap * _clustermap
Truth jet information.
SvtxTrackMap * _trackmap
SvtxVertexMap * _vertexmap
bool _verbose
bool _write_tree
Verbose printing.
bool _ana_truth
bool _ana_reco
Analyze truth info.
bool _do_evt_display
Analyze reconstructed info.
bool _use_ladder_geom
Event display for GenFit.
bool _cut_jet
bool _cut_Ncluster
std::string _foutname
TFile * _f
TTree * _tree
int _b_event
int _truthjet_n
Event counter.
int _truthjet_parton_flavor [10]
Number of truth jets.
int _truthjet_hadron_flavor [10]
Truth jet parton flavor.
float _truthjet_pt [10]
Truth jet hadron flavor.
float _truthjet_eta [10]
Truth jet pT.
float _truthjet_phi [10]
Truth jet eta.
float gf_prim_vtx [3]
Truth jet phi.
float gf_prim_vtx_err [3]
int gf_prim_vtx_ntrk
float rv_prim_vtx [3]
float rv_prim_vtx_err [3]
int rv_prim_vtx_ntrk
int rv_sv_njets
int rv_sv_jet_id [10]
int rv_sv_jet_prop [10][2]
float rv_sv_jet_pT [10]
float rv_sv_jet_phi [10]
int rv_sv_pT00_nvtx [10]
float rv_sv_pT00_vtx_x [10][30]
float rv_sv_pT00_vtx_y [10][30]
float rv_sv_pT00_vtx_z [10][30]
float rv_sv_pT00_vtx_ex [10][30]
float rv_sv_pT00_vtx_ey [10][30]
float rv_sv_pT00_vtx_ez [10][30]
int rv_sv_pT00_vtx_ntrk [10][30]
int rv_sv_pT00_vtx_ntrk_good [10][30]
float rv_sv_pT00_vtx_mass [10][30]
float rv_sv_pT00_vtx_mass_corr [10][30]
float rv_sv_pT00_vtx_pT [10][30]
int _ievent
int _primary_pid_guess
double _cut_min_pT
Particle ID guess for GenFit.
double _cut_chi2_ndf
Cut on min track pT.
double _cut_jet_pT
Cut on max track chi2.
double _cut_jet_eta
Cut on min jet pT.
double _cut_jet_R
Cut on jet eta.
std::string _track_fitting_alg_name
Cut on jet R.
PHGenFit::Fitter * _fitter
std::string _vertexing_method
https://rave.hepforge.org/trac/wiki/RaveMethods
genfit::GFRaveVertexFactory * _vertex_finder
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 48 of file BDiJetModule.h.
Constructor & Destructor Documentation
BDiJetModule::BDiJetModule (const std::string & name = "BDiJetModule", const std::string & ofName = "out.root")
Definition at line 90 of file BDiJetModule.C.
Member Function Documentation
int BDiJetModule::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 491 of file BDiJetModule.C.
References _f, and _write_tree.
void BDiJetModule::FillVertexMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const std::vector< genfit::Track * > & gf_tracks) private
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
Definition at line 875 of file BDiJetModule.C.
References _vertexmap, SvtxVertexMap::begin(), SvtxVertexMap::end(), SvtxVertex::get_error(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), gf_prim_vtx, gf_prim_vtx_err, gf_prim_vtx_ntrk, rv_prim_vtx, rv_prim_vtx_err, rv_prim_vtx_ntrk, and SvtxVertex::size_tracks().
Referenced by process_event().
int BDiJetModule::GetNodes (PHCompositeNode * topNode) private
Reset TTree variables.
Definition at line 619 of file BDiJetModule.C.
References _ana_reco, _ana_truth, _clustermap, _ievent, _jetmap_truth, _trackmap, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
int BDiJetModule::GetSVMass_mom (const genfit::GFRaveVertex * rave_vtx, float & vtx_mass, float & vtx_px, float & vtx_py, float & vtx_pz) private
Definition at line 916 of file BDiJetModule.C.
Referenced by process_event().
int BDiJetModule::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 123 of file BDiJetModule.C.
References _write_tree, InitTree(), and ResetVariables().
int BDiJetModule::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 137 of file BDiJetModule.C.
References _b_event, _do_evt_display, _fitter, _ievent, _track_fitting_alg_name, _vertex_finder, _vertexing_method, Fun4AllReturnCodes::ABORTRUN, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), PHWHERE, and verbosity.
void BDiJetModule::InitTree () private
Get all nodes.
Definition at line 505 of file BDiJetModule.C.
References _ana_reco, _ana_truth, _b_event, _f, _foutname, _tree, _truthjet_eta, _truthjet_hadron_flavor, _truthjet_n, _truthjet_parton_flavor, _truthjet_phi, _truthjet_pt, gf_prim_vtx, gf_prim_vtx_err, gf_prim_vtx_ntrk, rv_prim_vtx, rv_prim_vtx_err, rv_prim_vtx_ntrk, rv_sv_jet_id, rv_sv_jet_phi, rv_sv_jet_prop, rv_sv_jet_pT, rv_sv_njets, rv_sv_pT00_nvtx, rv_sv_pT00_vtx_ex, rv_sv_pT00_vtx_ey, rv_sv_pT00_vtx_ez, rv_sv_pT00_vtx_mass, rv_sv_pT00_vtx_mass_corr, rv_sv_pT00_vtx_ntrk, rv_sv_pT00_vtx_ntrk_good, rv_sv_pT00_vtx_pT, rv_sv_pT00_vtx_x, rv_sv_pT00_vtx_y, and rv_sv_pT00_vtx_z.
Referenced by Init().
PHGenFit::Track * BDiJetModule::MakeGenFitTrack (PHCompositeNode * topNode, const SvtxTrack * intrack, const SvtxVertex * vertex) private
Initialize the TTree.
Definition at line 665 of file BDiJetModule.C.
References _clustermap, _fitter, _primary_pid_guess, _use_ladder_geom, PHGenFit::Track::addMeasurements(), SvtxTrack::begin_clusters(), SvtxCluster::begin_hits(), SvtxTrack::end_clusters(), PHGenFit::Track::extrapolateToPoint(), SvtxHitMap::find(), PHG4CylinderGeom::find_segment_center(), SvtxClusterMap::get(), SvtxHit::get_cellid(), PHG4Cell::get_chip_index(), PHG4Cell::get_half_stave_index(), PHG4Cell::get_ladder_phi_index(), PHG4Cell::get_ladder_z_index(), SvtxCluster::get_layer(), PHG4Cell::get_module_index(), SvtxCluster::get_rphi_error(), PHG4Cell::get_stave_index(), SvtxCluster::get_x(), SvtxVertex::get_x(), SvtxCluster::get_y(), SvtxVertex::get_y(), SvtxCluster::get_z(), SvtxVertex::get_z(), SvtxCluster::get_z_error(), PHG4CylinderGeomContainer::GetLayerGeom(), i, j, LogError, LogWarning, n, PHWHERE, pos, PHGenFit::Fitter::processTrack(), r, verbosity, x, and y.
Referenced by process_event().
int BDiJetModule::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
stands for Refit_GenFit_Tracks
find vertex using tracks
change the vertex finding method
scan jetmap
SV reco
jet information
Reimplemented from SubsysReco.
Definition at line 169 of file BDiJetModule.C.
References _ana_reco, _ana_truth, _b_event, _clustermap, _cut_chi2_ndf, _cut_jet_eta, _cut_jet_pT, _cut_jet_R, _cut_min_pT, _cut_Ncluster, _ievent, _jetmap_truth, _trackmap, _tree, _truthjet_eta, _truthjet_hadron_flavor, _truthjet_n, _truthjet_parton_flavor, _truthjet_phi, _truthjet_pt, _verbose, _vertex_finder, _vertexing_method, _vertexmap, _write_tree, A, Fun4AllReturnCodes::ABORTEVENT, SvtxTrackMap::begin(), JetMap::begin(), SvtxTrack::begin_clusters(), SvtxTrackMap::end(), JetMap::end(), SvtxTrack::end_clusters(), Fun4AllReturnCodes::EVENT_OK, FillVertexMap(), SvtxClusterMap::get(), SvtxVertexMap::get(), SvtxTrack::get_chisq(), Jet::get_eta(), SvtxTrack::get_eta(), SvtxTrack::get_id(), Jet::get_id(), SvtxCluster::get_layer(), SvtxTrack::get_ndf(), Jet::get_phi(), SvtxTrack::get_phi(), Jet::get_property(), Jet::get_pt(), SvtxTrack::get_pt(), PHGenFit::Track::getGenFitTrack(), GetNodes(), GetSVMass_mom(), Jet::has_property(), MakeGenFitTrack(), PHWHERE, prop_JetHadronFlavor, prop_JetPartonFlavor, ResetVariables(), rv_prim_vtx, rv_sv_jet_id, rv_sv_jet_phi, rv_sv_jet_prop, rv_sv_jet_pT, rv_sv_njets, rv_sv_pT00_nvtx, rv_sv_pT00_vtx_ex, rv_sv_pT00_vtx_ey, rv_sv_pT00_vtx_ez, rv_sv_pT00_vtx_mass, rv_sv_pT00_vtx_mass_corr, rv_sv_pT00_vtx_ntrk, rv_sv_pT00_vtx_ntrk_good, rv_sv_pT00_vtx_pT, rv_sv_pT00_vtx_x, rv_sv_pT00_vtx_y, rv_sv_pT00_vtx_z, Jet::size_comp(), and verbosity.
void BDiJetModule::ResetVariables () private
Definition at line 561 of file BDiJetModule.C.
References _truthjet_eta, _truthjet_hadron_flavor, _truthjet_n, _truthjet_parton_flavor, _truthjet_phi, _truthjet_pt, gf_prim_vtx, gf_prim_vtx_err, gf_prim_vtx_ntrk, i, n, rv_prim_vtx, rv_prim_vtx_err, rv_prim_vtx_ntrk, rv_sv_jet_id, rv_sv_jet_phi, rv_sv_jet_prop, rv_sv_jet_pT, rv_sv_njets, rv_sv_pT00_nvtx, rv_sv_pT00_vtx_ex, rv_sv_pT00_vtx_ey, rv_sv_pT00_vtx_ez, rv_sv_pT00_vtx_mass, rv_sv_pT00_vtx_mass_corr, rv_sv_pT00_vtx_ntrk, rv_sv_pT00_vtx_ntrk_good, rv_sv_pT00_vtx_pT, rv_sv_pT00_vtx_x, rv_sv_pT00_vtx_y, and rv_sv_pT00_vtx_z.
Referenced by Init(), and process_event().
Member Data Documentation
bool BDiJetModule::_ana_reco private
Analyze truth info.
Definition at line 95 of file BDiJetModule.h.
Referenced by GetNodes(), InitTree(), and process_event().
bool BDiJetModule::_ana_truth private
Definition at line 94 of file BDiJetModule.h.
Referenced by GetNodes(), InitTree(), and process_event().
int BDiJetModule::_b_event private
Definition at line 107 of file BDiJetModule.h.
Referenced by InitRun(), InitTree(), and process_event().
SvtxClusterMap* BDiJetModule::_clustermap private
Truth jet information.
Definition at line 86 of file BDiJetModule.h.
Referenced by GetNodes(), MakeGenFitTrack(), and process_event().
double BDiJetModule::_cut_chi2_ndf private
Cut on min track pT.
Definition at line 149 of file BDiJetModule.h.
Referenced by process_event().
bool BDiJetModule::_cut_jet private
Definition at line 98 of file BDiJetModule.h.
double BDiJetModule::_cut_jet_eta private
Cut on min jet pT.
Definition at line 151 of file BDiJetModule.h.
Referenced by process_event().
double BDiJetModule::_cut_jet_pT private
Cut on max track chi2.
Definition at line 150 of file BDiJetModule.h.
Referenced by process_event().
double BDiJetModule::_cut_jet_R private
Cut on jet eta.
Definition at line 152 of file BDiJetModule.h.
Referenced by process_event().
double BDiJetModule::_cut_min_pT private
Particle ID guess for GenFit.
Definition at line 148 of file BDiJetModule.h.
Referenced by process_event().
bool BDiJetModule::_cut_Ncluster private
Definition at line 99 of file BDiJetModule.h.
Referenced by process_event().
bool BDiJetModule::_do_evt_display private
Analyze reconstructed info.
Definition at line 96 of file BDiJetModule.h.
Referenced by InitRun().
TFile* BDiJetModule::_f private
Definition at line 103 of file BDiJetModule.h.
Referenced by End(), and InitTree().
PHGenFit::Fitter* BDiJetModule::_fitter private
Definition at line 155 of file BDiJetModule.h.
Referenced by InitRun(), and MakeGenFitTrack().
std::string BDiJetModule::_foutname private
Definition at line 102 of file BDiJetModule.h.
Referenced by InitTree().
int BDiJetModule::_ievent private
Definition at line 144 of file BDiJetModule.h.
Referenced by GetNodes(), InitRun(), and process_event().
JetMap* BDiJetModule::_jetmap_truth private
Definition at line 85 of file BDiJetModule.h.
Referenced by GetNodes(), and process_event().
int BDiJetModule::_primary_pid_guess private
Definition at line 146 of file BDiJetModule.h.
Referenced by MakeGenFitTrack().
std::string BDiJetModule::_track_fitting_alg_name private
Cut on jet R.
Definition at line 154 of file BDiJetModule.h.
Referenced by InitRun().
SvtxTrackMap* BDiJetModule::_trackmap private
Definition at line 87 of file BDiJetModule.h.
Referenced by GetNodes(), and process_event().
TTree* BDiJetModule::_tree private
Definition at line 104 of file BDiJetModule.h.
Referenced by InitTree(), and process_event().
float BDiJetModule::_truthjet_eta[10] private
Truth jet pT.
Definition at line 113 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::_truthjet_hadron_flavor[10] private
Truth jet parton flavor.
Definition at line 111 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::_truthjet_n private
Event counter.
Definition at line 109 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::_truthjet_parton_flavor[10] private
Number of truth jets.
Definition at line 110 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::_truthjet_phi[10] private
Truth jet eta.
Definition at line 114 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::_truthjet_pt[10] private
Truth jet hadron flavor.
Definition at line 112 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
bool BDiJetModule::_use_ladder_geom private
Event display for GenFit.
Definition at line 97 of file BDiJetModule.h.
Referenced by MakeGenFitTrack().
bool BDiJetModule::_verbose private
Definition at line 92 of file BDiJetModule.h.
Referenced by process_event().
genfit::GFRaveVertexFactory* BDiJetModule::_vertex_finder private
Definition at line 159 of file BDiJetModule.h.
Referenced by InitRun(), and process_event().
std::string BDiJetModule::_vertexing_method private
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 158 of file BDiJetModule.h.
Referenced by InitRun(), and process_event().
SvtxVertexMap* BDiJetModule::_vertexmap private
Definition at line 88 of file BDiJetModule.h.
Referenced by FillVertexMap(), GetNodes(), and process_event().
bool BDiJetModule::_write_tree private
Verbose printing.
Definition at line 93 of file BDiJetModule.h.
Referenced by End(), Init(), and process_event().
float BDiJetModule::gf_prim_vtx[3] private
Truth jet phi.
Definition at line 116 of file BDiJetModule.h.
Referenced by FillVertexMap(), InitTree(), and ResetVariables().
float BDiJetModule::gf_prim_vtx_err[3] private
Definition at line 117 of file BDiJetModule.h.
Referenced by FillVertexMap(), InitTree(), and ResetVariables().
int BDiJetModule::gf_prim_vtx_ntrk private
Definition at line 118 of file BDiJetModule.h.
Referenced by FillVertexMap(), InitTree(), and ResetVariables().
float BDiJetModule::rv_prim_vtx[3] private
Definition at line 119 of file BDiJetModule.h.
Referenced by FillVertexMap(), InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_prim_vtx_err[3] private
Definition at line 120 of file BDiJetModule.h.
Referenced by FillVertexMap(), InitTree(), and ResetVariables().
int BDiJetModule::rv_prim_vtx_ntrk private
Definition at line 121 of file BDiJetModule.h.
Referenced by FillVertexMap(), InitTree(), and ResetVariables().
int BDiJetModule::rv_sv_jet_id[10] private
Definition at line 124 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_jet_phi[10] private
Definition at line 127 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::rv_sv_jet_prop[10][2] private
Definition at line 125 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_jet_pT[10] private
Definition at line 126 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::rv_sv_njets private
Definition at line 123 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::rv_sv_pT00_nvtx[10] private
Definition at line 129 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_ex[10][30] private
Definition at line 133 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_ey[10][30] private
Definition at line 134 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_ez[10][30] private
Definition at line 135 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_mass[10][30] private
Definition at line 138 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_mass_corr[10][30] private
Definition at line 139 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::rv_sv_pT00_vtx_ntrk[10][30] private
Definition at line 136 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
int BDiJetModule::rv_sv_pT00_vtx_ntrk_good[10][30] private
Definition at line 137 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_pT[10][30] private
Definition at line 140 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_x[10][30] private
Definition at line 130 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_y[10][30] private
Definition at line 131 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
float BDiJetModule::rv_sv_pT00_vtx_z[10][30] private
Definition at line 132 of file BDiJetModule.h.
Referenced by InitTree(), process_event(), and ResetVariables().
The documentation for this class was generated from the following files:
analysis/blob/master/HF-Jet/HFDiJetMomImbalance/BDiJetModule.h
analysis/blob/master/HF-Jet/HFDiJetMomImbalance/BDiJetModule.C