Analysis Software: macros/blob/master/macros/g4simulations/G4_CEmc_EIC.C File Reference
G4_CEmc_EIC.C File Reference
#include "GlobalVariables.C"
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <g4calo/RawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4CylinderCellReco.h>
#include <g4detectors/PHG4CylinderSubsystem.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
Enumerations
enum enu_Cemc_clusterizer {
kCemcGraphClusterizer, kCemcTemplateClusterizer, kCemcGraphClusterizer, kCemcTemplateClusterizer,
kCemcGraphClusterizer, kCemcTemplateClusterizer
}
Functions
void CEmcInit (const int nslats=1)
graph clusterizer, RawClusterBuilderGraph
double CEmc (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0)
void CEMC_Cells (int verbosity=0)
void CEMC_Towers (int verbosity=0)
void CEMC_Clusters (int verbosity=0)
void CEMC_Eval (std::string outputfile, int verbosity=0)
Variables
double cemcdepth = 9
double scint_width = 0.05
double tungs_width = 0.245
int min_cemc_layer = 1
int max_cemc_layer = 41
double topradius = 106.8
double bottomradius = 95
double negrapidity = -1.5
double posrapidity = 1.24
enu_Cemc_clusterizer Cemc_clusterizer = kCemcTemplateClusterizer
Enumeration Type Documentation
enum enu_Cemc_clusterizer
Enumerator:
kCemcGraphClusterizer
kCemcTemplateClusterizer
kCemcGraphClusterizer
kCemcTemplateClusterizer
kCemcGraphClusterizer
kCemcTemplateClusterizer
Definition at line 39 of file G4_CEmc_EIC.C.
Function Documentation
double CEmc (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0)
Definition at line 53 of file G4_CEmc_EIC.C.
References cemc, max_cemc_layer, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), scint_width, PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), tungs_width, z1, and z2.
Referenced by G4Setup().
void CEMC_Cells (int verbosity = 0)
Definition at line 162 of file G4_CEmc_EIC.C.
References PHG4CylinderCellReco::cellsize(), PHG4CylinderCellReco::Detector(), i, Fun4AllServer::instance(), max_cemc_layer, Fun4AllServer::registerSubsystem(), tungs_width, verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void CEMC_Clusters (int verbosity = 0)
Definition at line 227 of file G4_CEmc_EIC.C.
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), Fun4AllServer::instance(), kCemcGraphClusterizer, kCemcTemplateClusterizer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void CEMC_Eval (std::string outputfile, int verbosity = 0)
Definition at line 252 of file G4_CEmc_EIC.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void CEMC_Towers (int verbosity = 0)
Definition at line 182 of file G4_CEmc_EIC.C.
References RawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), RawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void CEmcInit (const int nslats = 1)
graph clusterizer, RawClusterBuilderGraph
Definition at line 51 of file G4_CEmc_EIC.C.
Referenced by G4Init().
Variable Documentation
double bottomradius = 95
Definition at line 32 of file G4_CEmc_EIC.C.
enu_Cemc_clusterizer Cemc_clusterizer = kCemcTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 47 of file G4_CEmc_EIC.C.
Referenced by CEMC_Clusters().
double cemcdepth = 9
Definition at line 20 of file G4_CEmc_EIC.C.
int max_cemc_layer = 41
Definition at line 29 of file G4_CEmc_EIC.C.
Referenced by CEmc(), and CEMC_Cells().
int min_cemc_layer = 1
Definition at line 28 of file G4_CEmc_EIC.C.
double negrapidity = -1.5
Definition at line 33 of file G4_CEmc_EIC.C.
double posrapidity = 1.24
Definition at line 34 of file G4_CEmc_EIC.C.
double scint_width = 0.05
Definition at line 25 of file G4_CEmc_EIC.C.
Referenced by CEmc().
double topradius = 106.8
Definition at line 31 of file G4_CEmc_EIC.C.
double tungs_width = 0.245
Definition at line 26 of file G4_CEmc_EIC.C.
Referenced by CEmc(), and CEMC_Cells().