Analysis Software: CaloEvalStack Class Reference
CaloEvalStack Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvalStack.h>
Public Member Functions
CaloEvalStack (PHCompositeNode *topNode, const std::string &caloname)
virtual ~CaloEvalStack ()
int get_caloid ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
CaloRawClusterEval * get_rawcluster_eval ()
CaloRawTowerEval * get_rawtower_eval ()
CaloTruthEval * get_truth_eval ()
unsigned int get_errors ()
Private Attributes
CaloRawClusterEval _clustereval
Detailed Description
Definition at line 18 of file CaloEvalStack.h.
Constructor & Destructor Documentation
CaloEvalStack::CaloEvalStack (PHCompositeNode * topNode, const std::string & caloname)
Definition at line 3 of file CaloEvalStack.cc.
virtual CaloEvalStack::~CaloEvalStack () inline virtual
Definition at line 22 of file CaloEvalStack.h.
Member Function Documentation
void CaloEvalStack::do_caching (bool do_cache) inline
Definition at line 26 of file CaloEvalStack.h.
References _clustereval, and CaloRawClusterEval::do_caching().
Referenced by JetTruthEval::do_caching().
int CaloEvalStack::get_caloid () inline
Definition at line 24 of file CaloEvalStack.h.
References CaloTruthEval::get_caloid(), and get_truth_eval().
unsigned int CaloEvalStack::get_errors () inline
Definition at line 34 of file CaloEvalStack.h.
References _clustereval, and CaloRawClusterEval::get_errors().
Referenced by JetTruthEval::get_errors().
CaloRawClusterEval* CaloEvalStack::get_rawcluster_eval () inline
Definition at line 30 of file CaloEvalStack.h.
References _clustereval.
Referenced by JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetRecoEval::all_truth_showers(), CaloEvaluator::fillOutputNtuples(), JetRecoEval::get_energy_contribution(), DISKinematicsReco::InsertCandidateFromCluster(), CaloEvaluator::printOutputInfo(), and STACalorimeterCharacterization::process_event().
CaloRawTowerEval* CaloEvalStack::get_rawtower_eval () inline
Definition at line 31 of file CaloEvalStack.h.
References _clustereval, and CaloRawClusterEval::get_rawtower_eval().
Referenced by JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetRecoEval::all_truth_showers(), CaloEvaluator::fillOutputNtuples(), and JetRecoEval::get_energy_contribution().
CaloTruthEval* CaloEvalStack::get_truth_eval () inline
Definition at line 32 of file CaloEvalStack.h.
References _clustereval, and CaloRawClusterEval::get_truth_eval().
Referenced by JetTruthEval::all_truth_showers(), CaloEvaluator::fillOutputNtuples(), get_caloid(), and CaloEvaluator::printOutputInfo().
void CaloEvalStack::next_event (PHCompositeNode * topNode)
Definition at line 8 of file CaloEvalStack.cc.
References _clustereval, and CaloRawClusterEval::next_event().
Referenced by JetTruthEval::next_event(), and CaloEvaluator::process_event().
void CaloEvalStack::set_strict (bool strict) inline
Definition at line 27 of file CaloEvalStack.h.
References _clustereval, and CaloRawClusterEval::set_strict().
Referenced by CaloEvaluator::process_event(), and JetTruthEval::set_strict().
void CaloEvalStack::set_verbosity (int verbosity) inline
Definition at line 28 of file CaloEvalStack.h.
References _clustereval, and CaloRawClusterEval::set_verbosity().
Referenced by CaloEvaluator::process_event(), and JetTruthEval::set_verbosity().
Member Data Documentation
CaloRawClusterEval CaloEvalStack::_clustereval private
Definition at line 37 of file CaloEvalStack.h.
Referenced by do_caching(), get_errors(), get_rawcluster_eval(), get_rawtower_eval(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvalStack.h
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloEvalStack.cc