Analysis Software: SelectorDijetWorker Class Reference
SelectorDijetWorker Class Reference
#include <analysis/blob/master/sPhenixAj/src/JetAnalyzer.hh>
Public Member Functions
SelectorDijetWorker (double dPhi)
std::string description () const
the selector's description
bool applies_jet_by_jet () const
Returns false, we need a jet ensemble.
bool pass (const fastjet::PseudoJet &pj) const
Returns false, we need a jet ensemble.
void terminator (std::vector< const fastjet::PseudoJet * > &jets) const
The relevant method.
Private Attributes
const double dPhi
Opening angle, searching for |φ1 - φ2 - π| < Δφ.
Detailed Description
Dijet finding as a Selector. Fashioned after fastjet::SW_NHardest. Searches for and returns dijet pairs within |φ1 - φ2 - π| < Δφ. returns 0 if no pair is found. In the current implementation, only the top two jets are compared.
NOTE: Could also use something like
Selector sel = SelectorCircle(dPhi);
sel.set_reference(-jet1); // Pseudocode
vector<PseudoJet> jets_near_MinusJet1 = sel(jets);
Definition at line 196 of file JetAnalyzer.hh.
Constructor & Destructor Documentation
SelectorDijetWorker::SelectorDijetWorker (double dPhi) inline
Standard constructor
Parameters
dPhi,: Opening angle, searching for |φ1 - φ2 - π| < Δφ
Definition at line 201 of file JetAnalyzer.hh.
Member Function Documentation
bool SelectorDijetWorker::applies_jet_by_jet () const inline
Returns false, we need a jet ensemble.
Definition at line 212 of file JetAnalyzer.hh.
Referenced by pass().
std::string SelectorDijetWorker::description () const inline
the selector's description
Definition at line 205 of file JetAnalyzer.hh.
References dPhi.
bool SelectorDijetWorker::pass (const fastjet::PseudoJet & pj) const inline
Returns false, we need a jet ensemble.
Definition at line 215 of file JetAnalyzer.hh.
References applies_jet_by_jet().
void SelectorDijetWorker::terminator (std::vector< const fastjet::PseudoJet * > & jets) const
The relevant method.
Definition at line 125 of file JetAnalyzer.cxx.
References dPhi, i, JetAnalyzer::phimod2pi(), and JetAnalyzer::pi.
Member Data Documentation
const double SelectorDijetWorker::dPhi private
Opening angle, searching for |φ1 - φ2 - π| < Δφ.
Definition at line 225 of file JetAnalyzer.hh.
Referenced by description(), and terminator().
The documentation for this class was generated from the following files:
analysis/blob/master/sPhenixAj/src/JetAnalyzer.hh
analysis/blob/master/sPhenixAj/src/JetAnalyzer.cxx