Analysis Software: oncsSub_idfnalmwpcv2 Class Reference
oncsSub_idfnalmwpcv2 Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_idfnalmwpcv2.h>
Classes
struct SpillInfo
struct TDC_hit
struct TDCData
struct TDCEvent
struct TDCspillheader
Public Member Functions
oncsSub_idfnalmwpcv2 (subevtdata_ptr)
~oncsSub_idfnalmwpcv2 ()
int iValue (const int n, const char *)
int iValue (const int trigger, const int tdc, const char *what)
int iValue (const int trigger, const int tdc, const int index)
int iValue (const int trigger, const int tdc, const int index, const char *what)
void dump (OSTREAM &os=COUT)
Public Member Functions inherited from oncsSubevent_w4
oncsSubevent_w4 (subevtdata_ptr)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
virtual int copyMe (int[], const int maxlength) const
Protected Member Functions
int * decode (int *)
Protected Attributes
int _decoded
int tdcmask
int n_tdcs
int length
SpillInfo spillinfo
TDCspillheader tsh [MAXNROFTDCS]
std::vector< TDCEvent * > TDCEventVector
Detailed Description
Definition at line 10 of file oncsSub_idfnalmwpcv2.h.
Constructor & Destructor Documentation
oncsSub_idfnalmwpcv2::oncsSub_idfnalmwpcv2 (subevtdata_ptr data)
Definition at line 10 of file oncsSub_idfnalmwpcv2.cc.
References _decoded, length, MAXNROFTDCS, n_tdcs, spillinfo, and tsh.
oncsSub_idfnalmwpcv2::~oncsSub_idfnalmwpcv2 ()
Definition at line 23 of file oncsSub_idfnalmwpcv2.cc.
Member Function Documentation
int * oncsSub_idfnalmwpcv2::decode (int * nwout) protected virtual
Reimplemented from oncsSubevent_w4.
Definition at line 26 of file oncsSub_idfnalmwpcv2.cc.
References _decoded, oncsSub_idfnalmwpcv2::TDCData::absolute_time, oncsSub_idfnalmwpcv2::TDCEvent::absolute_time, d, subevt_data::data, oncsSub_idfnalmwpcv2::SpillInfo::day, dlength, oncsSub_idfnalmwpcv2::TDCData::EventStatus, oncsSub_idfnalmwpcv2::TDCData::evt_timestamp, oncsSub_idfnalmwpcv2::TDCEvent::evt_timestamp, for(), oncsSubevent::getLength(), oncsSubevent::getPadding(), SVM_v1::h, oncsSub_idfnalmwpcv2::TDCData::hits, oncsSub_idfnalmwpcv2::SpillInfo::hour, i, length, oncsSub_idfnalmwpcv2::TDCData::local_ts_lower, oncsSub_idfnalmwpcv2::TDCEvent::local_ts_lower, oncsSub_idfnalmwpcv2::TDCData::local_ts_upper, oncsSub_idfnalmwpcv2::TDCEvent::local_ts_upper, MAXNROFTDCS, oncsSub_idfnalmwpcv2::SpillInfo::minute, oncsSub_idfnalmwpcv2::SpillInfo::month, n_tdcs, pos, s, oncsSub_idfnalmwpcv2::SpillInfo::second, oncsSub_idfnalmwpcv2::SpillInfo::Spill_Link_Status_Bits, oncsSub_idfnalmwpcv2::SpillInfo::spillcounter, spillinfo, oncsSub_idfnalmwpcv2::TDCspillheader::spillstatus, oncsSub_idfnalmwpcv2::TDCspillheader::spilltriggercount, oncsSub_idfnalmwpcv2::SpillInfo::spillwords, oncsSub_idfnalmwpcv2::TDCspillheader::spillwords, oncsSubevent::SubeventHdr, oncsSub_idfnalmwpcv2::TDCEvent::td, oncsSub_idfnalmwpcv2::TDCData::TDC, oncsSub_idfnalmwpcv2::TDCspillheader::TDC, oncsSub_idfnalmwpcv2::SpillInfo::TDC_Status_Bits, TDCEventVector, oncsSub_idfnalmwpcv2::TDCData::TDCHitlist, tdcmask, oncsSub_idfnalmwpcv2::TDC_hit::timestamp, oncsSub_idfnalmwpcv2::TDCEvent::trigger_nr, oncsSub_idfnalmwpcv2::SpillInfo::triggercount, oncsSub_idfnalmwpcv2::TDCData::triggertype, tsh, v, oncsSub_idfnalmwpcv2::TDC_hit::wire, oncsSub_idfnalmwpcv2::TDCData::words, x, and oncsSub_idfnalmwpcv2::SpillInfo::year.
Referenced by dump(), and iValue().
void oncsSub_idfnalmwpcv2::dump (OSTREAM & os = COUT) virtual
Reimplemented from oncsSubevent_w4.
Definition at line 380 of file oncsSub_idfnalmwpcv2.cc.
References decode(), i, oncsSubevent::identify(), iValue(), j, and k.
int oncsSub_idfnalmwpcv2::iValue (const int channel, const char * what) virtual
with the "what" parameter you can decide which aspect of the data you want to see (for devices which have more than one)
Implements Packet.
Definition at line 259 of file oncsSub_idfnalmwpcv2.cc.
References oncsSub_idfnalmwpcv2::SpillInfo::day, decode(), oncsSub_idfnalmwpcv2::SpillInfo::hour, oncsSub_idfnalmwpcv2::SpillInfo::minute, oncsSub_idfnalmwpcv2::SpillInfo::month, n_tdcs, oncsSub_idfnalmwpcv2::SpillInfo::second, oncsSub_idfnalmwpcv2::SpillInfo::Spill_Link_Status_Bits, oncsSub_idfnalmwpcv2::SpillInfo::spillcounter, spillinfo, oncsSub_idfnalmwpcv2::SpillInfo::TDC_Status_Bits, oncsSub_idfnalmwpcv2::SpillInfo::triggercount, and oncsSub_idfnalmwpcv2::SpillInfo::year.
Referenced by dump(), and iValue().
int oncsSub_idfnalmwpcv2::iValue (const int channel, const int y, const char * what) virtual
we have a few recent devices which have one more dimension (such as card, time sample, channel)
Implements Packet.
Definition at line 333 of file oncsSub_idfnalmwpcv2.cc.
References decode(), n_tdcs, and TDCEventVector.
int oncsSub_idfnalmwpcv2::iValue (const int channel, const int iy, const int iz) virtual
this supports devices organized as three-dimensional data (card vs channel vs time slice)
Implements Packet.
Definition at line 323 of file oncsSub_idfnalmwpcv2.cc.
References decode(), index, n_tdcs, and TDCEventVector.
int oncsSub_idfnalmwpcv2::iValue (const int channel, const int iy, const int iz, const char * what) virtual
this supports devices organized as three-dimensional data (card vs channel vs time slice, with a "what" selection)
Implements Packet.
Definition at line 358 of file oncsSub_idfnalmwpcv2.cc.
References decode(), index, iValue(), n_tdcs, and TDCEventVector.
Member Data Documentation
int oncsSub_idfnalmwpcv2::_decoded protected
Definition at line 38 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode(), and oncsSub_idfnalmwpcv2().
int oncsSub_idfnalmwpcv2::length protected
Definition at line 98 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode(), and oncsSub_idfnalmwpcv2().
int oncsSub_idfnalmwpcv2::n_tdcs protected
Definition at line 97 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode(), iValue(), and oncsSub_idfnalmwpcv2().
SpillInfo oncsSub_idfnalmwpcv2::spillinfo protected
Definition at line 100 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode(), iValue(), and oncsSub_idfnalmwpcv2().
std::vector<TDCEvent *> oncsSub_idfnalmwpcv2::TDCEventVector protected
Definition at line 105 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode(), and iValue().
int oncsSub_idfnalmwpcv2::tdcmask protected
Definition at line 96 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode().
TDCspillheader oncsSub_idfnalmwpcv2::tsh[MAXNROFTDCS] protected
Definition at line 102 of file oncsSub_idfnalmwpcv2.h.
Referenced by decode(), and oncsSub_idfnalmwpcv2().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_idfnalmwpcv2.h
online_distribution/blob/master/newbasic/oncsSub_idfnalmwpcv2.cc