Analysis Software: PHG4BeamlineMagnetDetector Class Reference
PHG4BeamlineMagnetDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.h>
Public Member Functions
PHG4BeamlineMagnetDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int layer=0)
constructor
virtual ~PHG4BeamlineMagnetDetector (void)
destructor
void ConstructMe (G4LogicalVolume *world)
construct
bool IsInBeamlineMagnet (const G4VPhysicalVolume *) const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * params
G4VPhysicalVolume * magnet_physi
G4VPhysicalVolume * cylinder_physi
int layer
std::string superdetector
Detailed Description
Definition at line 16 of file PHG4BeamlineMagnetDetector.h.
Constructor & Destructor Documentation
PHG4BeamlineMagnetDetector::PHG4BeamlineMagnetDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int layer = 0)
constructor
Definition at line 42 of file PHG4BeamlineMagnetDetector.cc.
virtual PHG4BeamlineMagnetDetector::~PHG4BeamlineMagnetDetector (void) inline virtual
destructor
Definition at line 23 of file PHG4BeamlineMagnetDetector.h.
Member Function Documentation
void PHG4BeamlineMagnetDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 62 of file PHG4BeamlineMagnetDetector.cc.
References cylinder_physi, PHParameters::get_double_param(), PHParameters::get_int_param(), PHParameters::get_string_param(), PHG4Detector::GetName(), magnet_physi, PHG4Detector::OverlapCheck(), params, PHWHERE, PHG4Utils::SetColour(), twopi, and PHG4Detector::Verbosity().
int PHG4BeamlineMagnetDetector::get_Layer () const inline
Definition at line 33 of file PHG4BeamlineMagnetDetector.h.
References layer.
bool PHG4BeamlineMagnetDetector::IsInBeamlineMagnet (const G4VPhysicalVolume * volume) const
Definition at line 52 of file PHG4BeamlineMagnetDetector.cc.
References magnet_physi.
void PHG4BeamlineMagnetDetector::SuperDetector (const std::string & name) inline
Definition at line 31 of file PHG4BeamlineMagnetDetector.h.
References name, and superdetector.
const std::string PHG4BeamlineMagnetDetector::SuperDetector () const inline
Definition at line 32 of file PHG4BeamlineMagnetDetector.h.
References superdetector.
Member Data Documentation
G4VPhysicalVolume* PHG4BeamlineMagnetDetector::cylinder_physi private
Definition at line 39 of file PHG4BeamlineMagnetDetector.h.
Referenced by ConstructMe().
int PHG4BeamlineMagnetDetector::layer private
Definition at line 41 of file PHG4BeamlineMagnetDetector.h.
Referenced by get_Layer().
G4VPhysicalVolume* PHG4BeamlineMagnetDetector::magnet_physi private
Definition at line 38 of file PHG4BeamlineMagnetDetector.h.
Referenced by ConstructMe(), and IsInBeamlineMagnet().
PHParameters* PHG4BeamlineMagnetDetector::params private
Definition at line 36 of file PHG4BeamlineMagnetDetector.h.
Referenced by ConstructMe().
std::string PHG4BeamlineMagnetDetector::superdetector private
Definition at line 42 of file PHG4BeamlineMagnetDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.cc