Analysis Software: RawClusterv1 Class Reference
RawClusterv1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawClusterv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
RawClusterv1 ()
virtual ~RawClusterv1 ()
virtual void Reset ()
Clear Event.
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
RawClusterDefs::keytype get_id () const
cluster ID
float get_energy () const
total energy
size_t getNTowers () const
Tower operations.
RawCluster::TowerConstRange get_towers () const
const TowerMap & get_towermap () const
return tower map for c++11 range-based for-loop
virtual CLHEP::Hep3Vector get_position () const
cluster position in 3D
float get_phi () const
access to intrinsic cylindrical coordinate system
float get_r () const
float get_z () const
virtual float get_x () const
access Cartesian coordinate system
virtual float get_y () const
virtual float get_ecore () const
virtual float get_chi2 () const
reduced chi2 for EM shower
virtual float get_prob () const
cluster template probability for EM shower
virtual float get_et_iso () const
isolation ET default
virtual float get_et_iso (const int radiusx10, bool subtracted, bool clusterTower) const
isolation ET the radius and hueristic can be specified
void set_id (const RawClusterDefs::keytype id)
cluster ID
void addTower (const RawClusterDefs::keytype twrid, const float etower)
Tower operations.
void set_energy (const float energy)
total energy
void set_phi (const float phi)
access to intrinsic cylindrical coordinate system
void set_z (const float z)
void set_r (const float r)
virtual void set_ecore (const float ecore)
virtual void set_chi2 (const float chi2)
reduced chi2 for EM shower
virtual void set_prob (const float prob)
cluster template probability for EM shower
virtual void set_et_iso (const float e)
isolation ET default
virtual void set_et_iso (const float et_iso, const int radiusx10, bool subtracted, bool clusterTower)
isolation ET the radius and hueristic can be specified
bool has_property (const PROPERTY prop_id) const
float get_property_float (const PROPERTY prop_id) const
int get_property_int (const PROPERTY prop_id) const
unsigned int get_property_uint (const PROPERTY prop_id) const
void set_property (const PROPERTY prop_id, const float value)
void set_property (const PROPERTY prop_id, const int value)
void set_property (const PROPERTY prop_id, const unsigned int value)
Public Member Functions inherited from RawCluster
virtual ~RawCluster ()
virtual bool has_property (const PROPERTY prop_id) const
getters
virtual float get_property_float (const PROPERTY prop_id) const
virtual int get_property_int (const PROPERTY prop_id) const
virtual unsigned int get_property_uint (const PROPERTY prop_id) const
virtual void set_property (const PROPERTY prop_id, const float value)
setters
virtual void set_property (const PROPERTY prop_id, const int value)
virtual void set_property (const PROPERTY prop_id, const unsigned int value)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Protected Member Functions inherited from RawCluster
RawCluster ()
Protected Attributes
prop_map_t prop_map
container for additional property
RawClusterDefs::keytype clusterid
cluster ID
float _energy
total energy
TowerMap towermap
Tower operations.
float _r
location of cluster in cylindrical coordinate
float _phi
float _z
Additional Inherited Members
Public Types inherited from RawCluster
enum PROPERTY {
prop_ecore = 0, prop_prob = 1, prop_chi2 = 2, prop_et_iso_calotower_sub_R01 = 20,
prop_et_iso_calotower_R01 = 21, prop_et_iso_calotower_sub_R02 = 22, prop_et_iso_calotower_R02 = 23, prop_et_iso_calotower_sub_R03 = 24,
prop_et_iso_calotower_R03 = 25, prop_et_iso_calotower_sub_R04 = 26, prop_et_iso_calotower_R04 = 27, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< RawTowerDefs::keytype, float > TowerMap
typedef TowerMap::iterator TowerIterator
typedef TowerMap::const_iterator TowerConstIterator
typedef std::pair
< TowerIterator, TowerIterator > TowerRange
typedef std::pair
< TowerConstIterator,
TowerConstIterator > TowerConstRange
Static Public Member Functions inherited from RawCluster
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
type management
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 22 of file RawClusterv1.h.
Constructor & Destructor Documentation
RawClusterv1::RawClusterv1 ()
Definition at line 13 of file RawClusterv1.cc.
Referenced by CloneMe().
virtual RawClusterv1::~RawClusterv1 () inline virtual
Definition at line 26 of file RawClusterv1.h.
Member Function Documentation
virtual PHObject* RawClusterv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from RawCluster.
Definition at line 28 of file RawClusterv1.h.
References RawClusterv1().
void RawClusterv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawCluster.
Definition at line 45 of file RawClusterv1.cc.
References get_energy(), get_id(), get_phi(), get_property_float(), RawCluster::get_property_info(), get_property_int(), get_property_uint(), get_r(), get_x(), get_y(), get_z(), getNTowers(), i, prop_map, RawCluster::type_float, RawCluster::type_int, and RawCluster::type_uint.
virtual int RawClusterv1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawCluster.
Definition at line 29 of file RawClusterv1.h.
References towermap.
void RawClusterv1::Reset () virtual
Clear Event.
Reimplemented from RawCluster.
Definition at line 23 of file RawClusterv1.cc.
References _energy, _phi, _r, _z, clusterid, prop_map, and towermap.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawClusterv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawClusterv1.cc