Analysis Software: analysis/blob/master/ParticleID/RICHAnalysis_macros/macros_fun4all/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C File Reference
G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C File Reference
#include <vector>
Functions
void SvtxInit (int n_TPC_layers=40, int verbosity=0)
double Svtx (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Svtx_Cells (int verbosity=0)
void Svtx_Reco (int verbosity=0)
void G4_Svtx_Reco ()
void Svtx_Eval (std::string outputfile, int verbosity=0)
Variables
bool use_primary_vertex = false
const int n_maps_layer = 3
const int n_intt_layer = 4
int n_gas_layer = 40
double inner_cage_radius = 20.
double TPCDriftVelocity = 3.0 / 1000.0
double TPCShapingRMSLead = 32.0
double TPCShapingRMSTail = 48.0
double TPCADCClock = 53.0
double tpc_cell_x = 0.15
double tpc_cell_y = TPCADCClock * TPCDriftVelocity
int Max_si_layer
Function Documentation
void G4_Svtx_Reco ()
Definition at line 505 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References Svtx_Reco().
double Svtx (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 33 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References i, inner_cage_radius, inner_readout_radius, Max_si_layer, n_intt_layer, n_maps_layer, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), verbosity, and Fun4AllBase::Verbosity().
void Svtx_Cells (int verbosity = 0)
Definition at line 208 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References i, inner_cage_radius, Fun4AllServer::instance(), Max_si_layer, n_gas_layer, n_intt_layer, n_maps_layer, Fun4AllServer::registerSubsystem(), tpc_cell_x, tpc_cell_y, TPCDriftVelocity, TPCShapingRMSLead, TPCShapingRMSTail, and verbosity.
void Svtx_Eval (std::string outputfile, int verbosity = 0)
Definition at line 515 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), use_primary_vertex, verbosity, and Fun4AllBase::Verbosity().
void Svtx_Reco (int verbosity = 0)
Definition at line 321 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References i, Fun4AllServer::instance(), Max_si_layer, n_gas_layer, n_intt_layer, n_maps_layer, Fun4AllServer::registerSubsystem(), use_primary_vertex, and verbosity.
void SvtxInit (int n_TPC_layers = 40, int verbosity = 0)
Definition at line 27 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References Max_si_layer, n_gas_layer, n_intt_layer, and n_maps_layer.
Variable Documentation
double inner_cage_radius = 20.
Definition at line 12 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int Max_si_layer
Definition at line 25 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int n_gas_layer = 40
Definition at line 10 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
const int n_intt_layer = 4
Definition at line 9 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
const int n_maps_layer = 3
Definition at line 8 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double tpc_cell_x = 0.15
Definition at line 22 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
Referenced by Svtx_Cells().
double tpc_cell_y = TPCADCClock * TPCDriftVelocity
Definition at line 23 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
Referenced by Svtx_Cells().
double TPCADCClock = 53.0
Definition at line 20 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCDriftVelocity = 3.0 / 1000.0
Definition at line 17 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCShapingRMSLead = 32.0
Definition at line 18 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCShapingRMSTail = 48.0
Definition at line 19 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
bool use_primary_vertex = false
Definition at line 6 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.