Analysis Software: DVMPHelper Class Reference
DVMPHelper Class Reference
#include <analysis/blob/master/EICAnalysis/DVMPHelper.h>
Classes
struct particle_reco
struct particle_truth
Public Member Functions
DVMPHelper (std::vector< float > reco_eta, std::vector< float > reco_phi, std::vector< float > reco_ptotal, std::vector< int > reco_charge, std::vector< float > reco_cluster_e, std::vector< bool > reco_is_scattered_lepton, std::vector< float > true_eta, std::vector< float > true_phi, std::vector< float > true_ptotal, std::vector< int > pid, std::vector< bool > is_scattered_lepton)
~DVMPHelper ()
std::vector< float > calculateInvariantMass_1 ()
std::vector< float > calculateInvariantMass_2 ()
std::vector< float > calculateInvariantMass_3 ()
std::vector< float > calculateInvariantMass_4 ()
std::vector< float > calculateInvariantMass_5 ()
std::vector< float > calculateInvariantMass_6 ()
particle_reco GetParticleReco (float eta, float phi, float ptotal, int charge, float e, bool is_scattered_lepton)
particle_truth GetParticleTruth (float eta, float phi, float ptotal, int pid, bool is_scattered_lepton)
float get_invariant_mass (DVMPHelper::particle_reco, DVMPHelper::particle_reco)
float get_invariant_mass (DVMPHelper::particle_truth, DVMPHelper::particle_truth)
float get_pt (float eta, float ptotal)
bool find_positron ()
bool pass_cut (int index)
Public Attributes
int _size_reco
int _size_truth
DVMPHelper::particle_reco * rparticles
DVMPHelper::particle_truth * tparticles
Detailed Description
Definition at line 6 of file DVMPHelper.h.
Constructor & Destructor Documentation
DVMPHelper::DVMPHelper (std::vector< float > reco_eta, std::vector< float > reco_phi, std::vector< float > reco_ptotal, std::vector< int > reco_charge, std::vector< float > reco_cluster_e, std::vector< bool > reco_is_scattered_lepton, std::vector< float > true_eta, std::vector< float > true_phi, std::vector< float > true_ptotal, std::vector< int > pid, std::vector< bool > is_scattered_lepton)
Definition at line 5 of file DVMPHelper.C.
References _size_reco, _size_truth, GetParticleReco(), GetParticleTruth(), i, j, rparticles, and tparticles.
DVMPHelper::~DVMPHelper () inline
Definition at line 20 of file DVMPHelper.h.
Member Function Documentation
std::vector< float > DVMPHelper::calculateInvariantMass_1 ()
Definition at line 112 of file DVMPHelper.C.
References _size_reco, find_positron(), get_invariant_mass(), i, pass_cut(), and rparticles.
Referenced by ExclusiveReco::AddInvariantMassInformation().
std::vector< float > DVMPHelper::calculateInvariantMass_2 ()
Definition at line 167 of file DVMPHelper.C.
References _size_truth, get_invariant_mass(), i, pid, and tparticles.
Referenced by ExclusiveReco::AddInvariantMassInformation().
std::vector< float > DVMPHelper::calculateInvariantMass_3 ()
Definition at line 191 of file DVMPHelper.C.
References _size_reco, find_positron(), get_invariant_mass(), i, pass_cut(), and rparticles.
Referenced by ExclusiveReco::AddInvariantMassInformation().
std::vector< float > DVMPHelper::calculateInvariantMass_4 ()
Definition at line 246 of file DVMPHelper.C.
References _size_reco, find_positron(), get_invariant_mass(), i, pass_cut(), and rparticles.
Referenced by ExclusiveReco::AddInvariantMassInformation().
std::vector< float > DVMPHelper::calculateInvariantMass_5 ()
Definition at line 301 of file DVMPHelper.C.
References _size_truth, get_invariant_mass(), i, pid, and tparticles.
Referenced by ExclusiveReco::AddInvariantMassInformation().
std::vector< float > DVMPHelper::calculateInvariantMass_6 ()
Definition at line 326 of file DVMPHelper.C.
References _size_truth, get_invariant_mass(), i, pid, and tparticles.
Referenced by ExclusiveReco::AddInvariantMassInformation().
bool DVMPHelper::find_positron ()
Definition at line 91 of file DVMPHelper.C.
References _size_reco, i, and rparticles.
Referenced by calculateInvariantMass_1(), calculateInvariantMass_3(), and calculateInvariantMass_4().
float DVMPHelper::get_invariant_mass (DVMPHelper::particle_reco p1, DVMPHelper::particle_reco p2)
Definition at line 49 of file DVMPHelper.C.
References DVMPHelper::particle_reco::eta, get_pt(), DVMPHelper::particle_reco::phi, and DVMPHelper::particle_reco::ptotal.
Referenced by calculateInvariantMass_1(), calculateInvariantMass_2(), calculateInvariantMass_3(), calculateInvariantMass_4(), calculateInvariantMass_5(), and calculateInvariantMass_6().
float DVMPHelper::get_invariant_mass (DVMPHelper::particle_truth p1, DVMPHelper::particle_truth p2)
Definition at line 66 of file DVMPHelper.C.
References DVMPHelper::particle_truth::eta, get_pt(), DVMPHelper::particle_truth::phi, and DVMPHelper::particle_truth::ptotal.
float DVMPHelper::get_pt (float eta, float ptotal)
Definition at line 83 of file DVMPHelper.C.
Referenced by get_invariant_mass().
DVMPHelper::particle_reco DVMPHelper::GetParticleReco (float eta, float phi, float ptotal, int charge, float e, bool is_scattered_lepton)
Definition at line 35 of file DVMPHelper.C.
References phi.
Referenced by DVMPHelper().
DVMPHelper::particle_truth DVMPHelper::GetParticleTruth (float eta, float phi, float ptotal, int pid, bool is_scattered_lepton)
Definition at line 42 of file DVMPHelper.C.
References phi, and pid.
Referenced by DVMPHelper().
bool DVMPHelper::pass_cut (int index)
Definition at line 102 of file DVMPHelper.C.
References rparticles.
Referenced by calculateInvariantMass_1(), calculateInvariantMass_3(), and calculateInvariantMass_4().
Member Data Documentation
int DVMPHelper::_size_reco
Definition at line 61 of file DVMPHelper.h.
Referenced by calculateInvariantMass_1(), calculateInvariantMass_3(), calculateInvariantMass_4(), DVMPHelper(), and find_positron().
int DVMPHelper::_size_truth
Definition at line 62 of file DVMPHelper.h.
Referenced by calculateInvariantMass_2(), calculateInvariantMass_5(), calculateInvariantMass_6(), and DVMPHelper().
DVMPHelper::particle_reco* DVMPHelper::rparticles
Definition at line 65 of file DVMPHelper.h.
Referenced by calculateInvariantMass_1(), calculateInvariantMass_3(), calculateInvariantMass_4(), DVMPHelper(), find_positron(), and pass_cut().
DVMPHelper::particle_truth* DVMPHelper::tparticles
Definition at line 66 of file DVMPHelper.h.
Referenced by calculateInvariantMass_2(), calculateInvariantMass_5(), calculateInvariantMass_6(), and DVMPHelper().
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/DVMPHelper.h
analysis/blob/master/EICAnalysis/DVMPHelper.C