Analysis Software: BEmcRec Class Reference
BEmcRec Class Reference abstract
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcRec.h>
Public Member Functions
BEmcRec ()
virtual ~BEmcRec ()
void SetVertex (float *vv)
void SetGeometry (int nx, int ny, float txsz, float tysz)
void SetConf (int nx, int ny)
bool SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
bool GetTowerGeometry (int ix, int iy, TowerGeom &geom)
void PrintTowerGeometry (const char *fname)
void SetPlaneGeometry ()
void SetCylindricalGeometry ()
bool isCylindrical () const
int GetNx () const
int GetNy () const
float GetModSizex () const
float GetModSizey () const
float GetVx () const
float GetVy () const
float GetVz () const
void SetPeakThreshold (float Thresh)
float GetPeakThreshold ()
float GetTowerThreshold ()
void SetModules (std::vector< EmcModule > const *modules)
std::vector< EmcModule > * GetModules ()
std::vector< EmcCluster > * GetClusters ()
int iTowerDist (int ix1, int ix2)
float fTowerDist (float x1, float x2)
int FindClusters ()
void GlobalToSector (float, float, float, float *, float *, float *)
void SectorToGlobal (float xsec, float ysec, float zsec, float *px, float *py, float *pz)
void SectorToGlobalErr (float dxsec, float dysec, float dzsec, float *pdx, float *pdy, float *pdz)
void TowersToSector (float, float, float &, float &)
Converts coordinates in units of towers into cm's (Local coord. system)
void TowersToSector (int, int, float &, float &)
Returns coordinates of the tower centers in cm's (Local coord. system)
void SectorToTowers (float, float, int &, int &)
Converts Local Sector coordinates in cm into integer tower numbers.
void Gamma (int, EmcModule *, float *, float *, float *, float *, float *, float *, float *, float *, int &ndf)
void Momenta (int, EmcModule *, float *, float *, float *, float *, float *, float *)
int ShiftX (int ishift, int nh, EmcModule *phit0, EmcModule *phit1)
EmcModule ShiftX (int ish, EmcModule &ehit)
void SetTowerThreshold (float Thresh)
void SetProfileParameters (int, float, float, float)
void SetChi2Limit (int lim)
int GetTowerID (int iy, int iz, int nn, int *iyy, int *izz, float *ee)
float GetProb (std::vector< EmcModule > HitList, float &chi2, int &ndf)
float ClusterChisq (int, EmcModule *, float, float, float, int &ndf)
float Chi2Correct (float chi2, int ndf)
virtual void CorrectEnergy (float energy, float x, float y, float *ecorr)=0
virtual void CorrectPosition (float energy, float x, float y, float *xcorr, float *ycorr)=0
virtual void CorrectECore (float ecore, float x, float y, float *ecorecorr)=0
virtual void Tower2Global (float en, float xsec, float ysec, float &xA, float &yA, float &zA)=0
void TwoGamma (int, EmcModule *, float *, float *, float *, float *, float *, float *, float *)
float Chi2Limit (int ndf)
float PredictEnergy (float, float, float)
void CalculateErrors (float e, float x, float y, float *pde, float *pdx, float *pdy, float *pdz)
void getTowerPos (int ix, int iy, float &x, float &y)
Static Public Member Functions
static int HitNCompare (const void *, const void *)
static int HitACompare (const void *, const void *)
static void CopyVector (int *, int *, int)
static void CopyVector (EmcModule *, EmcModule *, int)
static void ZeroVector (int *, int)
static void ZeroVector (float *, int)
static void ZeroVector (EmcModule *, int)
static void c3to5 (float, float, float, float, float, float, float *, float *, float *, float *, float *, float *)
Protected Attributes
bool bCYL
int fNx
int fNy
std::map< int, TowerGeom > fTowerGeom
float fModSizex
float fModSizey
float fVx
float fVy
float fVz
std::vector< EmcModule > * fModules
std::vector< EmcCluster > * fClusters
float fgTowerThresh
float fgMinPeakEnergy
float fSin4T
float fSinTx
float fSinTy
float fPpar1
float fPpar2
float fPpar3
float fPpar4
float fPshiftx
float fPshifty
Static Protected Attributes
static float fgChi2Level1 []
static float fgChi2Level2 []
static float fgChi2Level []
static float const fgMinShowerEnergy = 0.1
static int const fgMaxLen = 10000
static float fgEpar00 = 0.005
static float fgEpar0 = 0.0014
static float fgEpar1 = 0.03
static float fgEpar2 = -0.03
static float fgEpar3 = 0.
static float fgEpar4 = 4.0
Private Member Functions
BEmcRec (const BEmcRec &)=delete
Detailed Description
ABC of a clusterizer for one EMCAL sector.
Definition at line 39 of file BEmcRec.h.
Constructor & Destructor Documentation
BEmcRec::BEmcRec ()
Definition at line 72 of file BEmcRec.cc.
References fClusters, fModules, SetChi2Limit(), and SetPeakThreshold().
BEmcRec::~BEmcRec () virtual
Definition at line 101 of file BEmcRec.cc.
References fClusters, and fModules.
BEmcRec::BEmcRec (const BEmcRec &) private delete
Member Function Documentation
void BEmcRec::c3to5 (float e0, float x0, float y0, float eps, float dx, float dy, float * pe1, float * px1, float * py1, float * pe2, float * px2, float * py2) static
Definition at line 876 of file BEmcRec.cc.
Referenced by TwoGamma().
void BEmcRec::CalculateErrors (float e, float x, float y, float * pde, float * pdx, float * pdy, float * pdz)
Definition at line 1001 of file BEmcRec.cc.
References d, dx, dy, fSinTx, fSinTy, and SectorToGlobalErr().
Referenced by EmcCluster::GetChar(), EmcPeakarea::GetChar(), and EmcCluster::GetErrors().
float BEmcRec::Chi2Correct (float chi2, int ndf)
Definition at line 1489 of file BEmcRec.cc.
References c, and Chi2.
Referenced by EmcPeakarea::GetChar().
float BEmcRec::Chi2Limit (int ndf)
Definition at line 1469 of file BEmcRec.cc.
References fgChi2Level, and EmcCluster::min().
float BEmcRec::ClusterChisq (int nh, EmcModule * phit, float e, float x, float y, int & ndf)
Definition at line 1445 of file BEmcRec.cc.
References EmcModule::amp, d, fgEpar0, fgEpar00, fgEpar1, fgEpar2, fgEpar3, fgEpar4, fNx, fSin4T, EmcModule::ich, in, and PredictEnergy().
Referenced by Gamma().
void BEmcRec::CopyVector (int * from, int * to, int N) static
Definition at line 860 of file BEmcRec.cc.
References i, and N.
Referenced by FindClusters().
void BEmcRec::CopyVector (EmcModule * from, EmcModule * to, int N) static
Definition at line 868 of file BEmcRec.cc.
References i, and N.
virtual void BEmcRec::CorrectECore (float ecore, float x, float y, float * ecorecorr) pure virtual
Implemented in BEmcRecEEMC, BEmcRecFEMC, and BEmcRecCEMC.
Referenced by EmcPeakarea::GetChar(), and EmcCluster::GetECoreCorrected().
virtual void BEmcRec::CorrectEnergy (float energy, float x, float y, float * ecorr) pure virtual
Implemented in BEmcRecCEMC, BEmcRecEEMC, and BEmcRecFEMC.
virtual void BEmcRec::CorrectPosition (float energy, float x, float y, float * xcorr, float * ycorr) pure virtual
Implemented in BEmcRecEEMC, BEmcRecFEMC, and BEmcRecCEMC.
Referenced by EmcCluster::GetChar(), EmcPeakarea::GetChar(), and EmcCluster::GetCorrPos().
int BEmcRec::FindClusters ()
Definition at line 264 of file BEmcRec.cc.
References bCYL, CopyVector(), fClusters, fgMaxLen, fModules, fNx, HitNCompare(), i, EmcModule::ich, and EmcCluster::ReInitialize().
Referenced by RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
float BEmcRec::fTowerDist (float x1, float x2)
Definition at line 245 of file BEmcRec.cc.
References bCYL, and fNx.
Referenced by EmcCluster::GetECore(), and EmcCluster::GetPeaks().
void BEmcRec::Gamma (int nh, EmcModule * phit0, float * pchi, float * pchi0, float * pe1, float * px1, float * py1, float * pe2, float * px2, float * py2, int & ndf)
!!!! Begin: Exclude chi2 minimizitation and 2-phot splitting
!!!! End: Exclude chi2 minimizitation and 2-phot splitting
Definition at line 489 of file BEmcRec.cc.
References EmcCluster::ABS(), ClusterChisq(), fgMinShowerEnergy, fNx, Momenta(), SetProfileParameters(), ShiftX(), TwoGamma(), x0, and x2.
Referenced by EmcPeakarea::GetCGmin(), EmcPeakarea::GetChar(), and EmcPeakarea::GetChi2().
std::vector<EmcCluster>* BEmcRec::GetClusters () inline
Definition at line 75 of file BEmcRec.h.
References fClusters.
Referenced by RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
float BEmcRec::GetModSizex () const inline
Definition at line 64 of file BEmcRec.h.
References fModSizex.
Referenced by BEmcRecCEMC::CorrectPosition(), EmcPeakarea::GetCGmin(), EmcPeakarea::GetChar(), EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), EmcCluster::GetE4(), and EmcCluster::GetImpactTower().
float BEmcRec::GetModSizey () const inline
Definition at line 65 of file BEmcRec.h.
References fModSizey.
Referenced by EmcPeakarea::GetCGmin(), EmcPeakarea::GetChar(), EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), EmcCluster::GetE4(), and EmcCluster::GetImpactTower().
std::vector<EmcModule>* BEmcRec::GetModules () inline
Definition at line 74 of file BEmcRec.h.
References fModules.
int BEmcRec::GetNx () const inline
Definition at line 62 of file BEmcRec.h.
References fNx.
Referenced by EmcCluster::GetE9(), EmcCluster::GetECore(), EmcCluster::GetImpactTower(), EmcCluster::GetPeaks(), and EmcCluster::GetTowerEnergy().
int BEmcRec::GetNy () const inline
Definition at line 63 of file BEmcRec.h.
References fNy.
Referenced by EmcCluster::GetImpactTower().
float BEmcRec::GetPeakThreshold () inline
Definition at line 70 of file BEmcRec.h.
References fgMinPeakEnergy.
Referenced by EmcCluster::GetPeaks().
float BEmcRec::GetProb (std::vector< EmcModule > HitList, float & chi2, int & ndf)
Definition at line 1282 of file BEmcRec.cc.
References c2, fNx, GetTowerID(), i, and printf().
Referenced by EmcCluster::GetProb().
bool BEmcRec::GetTowerGeometry (int ix, int iy, TowerGeom & geom)
Definition at line 159 of file BEmcRec.cc.
References fNx, fNy, fTowerGeom, and it.
Referenced by BEmcRecEEMC::Tower2Global(), and BEmcRecFEMC::Tower2Global().
int BEmcRec::GetTowerID (int iy, int iz, int nn, int * iyy, int * izz, float * ee)
Definition at line 1270 of file BEmcRec.cc.
References fNx, and i.
Referenced by GetProb().
void BEmcRec::getTowerPos (int ix, int iy, float & x, float & y)
Definition at line 1519 of file BEmcRec.cc.
float BEmcRec::GetTowerThreshold () inline
Definition at line 71 of file BEmcRec.h.
References fgTowerThresh.
float BEmcRec::GetVx () const inline
Definition at line 66 of file BEmcRec.h.
References fVx.
float BEmcRec::GetVy () const inline
Definition at line 67 of file BEmcRec.h.
References fVy.
float BEmcRec::GetVz () const inline
Definition at line 68 of file BEmcRec.h.
References fVz.
void BEmcRec::GlobalToSector (float xgl, float ygl, float zgl, float * px, float * py, float * pz)
Definition at line 392 of file BEmcRec.cc.
References fModSizex, fModSizey, fNx, and fNy.
int BEmcRec::HitACompare (const void * h1, const void * h2) static
Definition at line 822 of file BEmcRec.cc.
References h1, and h2.
Referenced by EmcCluster::GetHits().
int BEmcRec::HitNCompare (const void * h1, const void * h2) static
Definition at line 815 of file BEmcRec.cc.
Referenced by FindClusters(), and EmcCluster::GetPeaks().
bool BEmcRec::isCylindrical () const inline
Definition at line 60 of file BEmcRec.h.
References bCYL.
int BEmcRec::iTowerDist (int ix1, int ix2)
Definition at line 226 of file BEmcRec.cc.
References bCYL, and fNx.
Referenced by EmcCluster::GetE9(), EmcCluster::GetPeaks(), and Momenta().
void BEmcRec::Momenta (int nh, EmcModule * phit, float * pe, float * px, float * py, float * pxx, float * pyy, float * pyx)
Definition at line 727 of file BEmcRec.cc.
References EmcModule::amp, fNx, i, EmcModule::ich, iTowerDist(), x, and y.
Referenced by Gamma(), EmcCluster::GetMoments(), and TwoGamma().
float BEmcRec::PredictEnergy (float xc, float yc, float en)
Definition at line 1090 of file BEmcRec.cc.
References EmcCluster::ABS(), dx, dy, fPpar1, fPpar2, fPpar3, fPpar4, fPshiftx, fPshifty, r1, r2, and SetProfileParameters().
Referenced by ClusterChisq(), EmcCluster::GetECore(), EmcCluster::GetPeaks(), and TwoGamma().
void BEmcRec::PrintTowerGeometry (const char * fname)
Definition at line 126 of file BEmcRec.cc.
References fclose(), fNx, fNy, fprintf(), fTowerGeom, it, printf(), TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
void BEmcRec::SectorToGlobal (float xsec, float ysec, float zsec, float * px, float * py, float * pz)
Definition at line 409 of file BEmcRec.cc.
References dx, dy, fNx, fNy, fTowerGeom, it, printf(), TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
Referenced by EmcCluster::GetChar(), and EmcPeakarea::GetChar().
void BEmcRec::SectorToGlobalErr (float dxsec, float dysec, float dzsec, float * pdx, float * pdy, float * pdz)
Definition at line 479 of file BEmcRec.cc.
Referenced by CalculateErrors().
void BEmcRec::SectorToTowers (float xS, float yS, int & xT, int & yT)
Converts Local Sector coordinates in cm into integer tower numbers.
Definition at line 1548 of file BEmcRec.cc.
References fModSizex, and fModSizey.
void BEmcRec::SetChi2Limit (int lim)
Definition at line 894 of file BEmcRec.cc.
References fgChi2Level, fgChi2Level1, fgChi2Level2, and i.
Referenced by BEmcRec().
void BEmcRec::SetConf (int nx, int ny) inline
Definition at line 53 of file BEmcRec.h.
References SetGeometry().
void BEmcRec::SetCylindricalGeometry () inline
Definition at line 59 of file BEmcRec.h.
References bCYL.
void BEmcRec::SetGeometry (int nx, int ny, float txsz, float tysz)
Definition at line 118 of file BEmcRec.cc.
References fModSizex, fModSizey, fNx, and fNy.
Referenced by RawClusterBuilderTemplateEEMC::InitRun(), RawClusterBuilderTemplateFEMC::InitRun(), RawClusterBuilderTemplate::process_event(), RawClusterBuilderTemplate::RawClusterBuilderTemplate(), RawClusterBuilderTemplateEEMC::RawClusterBuilderTemplateEEMC(), RawClusterBuilderTemplateFEMC::RawClusterBuilderTemplateFEMC(), and SetConf().
void BEmcRec::SetModules (std::vector< EmcModule > const * modules)
Definition at line 212 of file BEmcRec.cc.
References fModules.
Referenced by RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), and RawClusterBuilderTemplate::process_event().
void BEmcRec::SetPeakThreshold (float Thresh) inline
Definition at line 69 of file BEmcRec.h.
References fgMinPeakEnergy.
Referenced by BEmcRec().
void BEmcRec::SetPlaneGeometry () inline
Definition at line 58 of file BEmcRec.h.
References bCYL.
Referenced by RawClusterBuilderTemplateEEMC::RawClusterBuilderTemplateEEMC(), and RawClusterBuilderTemplateFEMC::RawClusterBuilderTemplateFEMC().
void BEmcRec::SetProfileParameters (int sec, float Energy, float x, float y)
Definition at line 1029 of file BEmcRec.cc.
References dx, fModSizex, fPpar1, fPpar2, fPpar3, fPpar4, fPshiftx, fPshifty, fSin4T, fSinTx, fSinTy, and sign().
Referenced by BEmcRecCEMC::CorrectPosition(), Gamma(), EmcCluster::GetECore(), EmcCluster::GetPeaks(), and PredictEnergy().
bool BEmcRec::SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
Definition at line 171 of file BEmcRec.cc.
References fNx, fNy, fTowerGeom, TowerGeom::Xcenter, TowerGeom::Ycenter, and TowerGeom::Zcenter.
Referenced by RawClusterBuilderTemplateEEMC::InitRun(), and RawClusterBuilderTemplateFEMC::InitRun().
void BEmcRec::SetTowerThreshold (float Thresh)
Definition at line 1510 of file BEmcRec.cc.
References fgEpar0, fgEpar00, fgTowerThresh, and EmcCluster::max().
Referenced by RawClusterBuilderTemplate::RawClusterBuilderTemplate(), RawClusterBuilderTemplateEEMC::RawClusterBuilderTemplateEEMC(), and RawClusterBuilderTemplateFEMC::RawClusterBuilderTemplateFEMC().
void BEmcRec::SetVertex (float * vv) inline
Definition at line 45 of file BEmcRec.h.
References fVx, fVy, and fVz.
Referenced by RawClusterBuilderTemplate::RawClusterBuilderTemplate(), RawClusterBuilderTemplateEEMC::RawClusterBuilderTemplateEEMC(), and RawClusterBuilderTemplateFEMC::RawClusterBuilderTemplateFEMC().
int BEmcRec::ShiftX (int ishift, int nh, EmcModule * phit0, EmcModule * phit1)
Definition at line 673 of file BEmcRec.cc.
References fNx, i, EmcModule::ich, and printf().
Referenced by Gamma().
EmcModule BEmcRec::ShiftX (int ish, EmcModule & ehit)
Definition at line 661 of file BEmcRec.cc.
References fNx, and EmcModule::ich.
virtual void BEmcRec::Tower2Global (float en, float xsec, float ysec, float & xA, float & yA, float & zA) pure virtual
Implemented in BEmcRecEEMC, BEmcRecFEMC, and BEmcRecCEMC.
Referenced by EmcCluster::GetGlobalPos().
void BEmcRec::TowersToSector (float xT, float yT, float & xS, float & yS)
Converts coordinates in units of towers into cm's (Local coord. system)
Definition at line 1528 of file BEmcRec.cc.
References dx, dy, fModSizex, fModSizey, x, and y.
void BEmcRec::TowersToSector (int xT, int yT, float & xS, float & yS)
Returns coordinates of the tower centers in cm's (Local coord. system)
Definition at line 1540 of file BEmcRec.cc.
References fModSizex, and fModSizey.
void BEmcRec::TwoGamma (int nh, EmcModule * phit, float * pchi, float * pe1, float * px1, float * py1, float * pe2, float * px2, float * py2)
Definition at line 1112 of file BEmcRec.cc.
References EmcCluster::ABS(), EmcModule::amp, c3to5(), d, fgEpar0, fgEpar00, fgEpar1, fgEpar2, fgEpar3, fgEpar4, fNx, fSin4T, gr, gre, EmcModule::ich, in, Momenta(), PredictEnergy(), r, step, and x0.
Referenced by Gamma().
void BEmcRec::ZeroVector (int * v, int N) static
Definition at line 831 of file BEmcRec.cc.
References i, N, and v.
Referenced by EmcCluster::GetHits(), and EmcCluster::GetPeaks().
void BEmcRec::ZeroVector (float * v, int N) static
Definition at line 839 of file BEmcRec.cc.
References i, N, and v.
void BEmcRec::ZeroVector (EmcModule * v, int N) static
Definition at line 847 of file BEmcRec.cc.
References EmcModule::amp, i, EmcModule::ich, N, and EmcModule::tof.
Member Data Documentation
bool BEmcRec::bCYL protected
Definition at line 138 of file BEmcRec.h.
Referenced by FindClusters(), fTowerDist(), isCylindrical(), iTowerDist(), SetCylindricalGeometry(), and SetPlaneGeometry().
std::vector<EmcCluster>* BEmcRec::fClusters protected
Definition at line 155 of file BEmcRec.h.
Referenced by BEmcRec(), FindClusters(), GetClusters(), and ~BEmcRec().
float BEmcRec::fgChi2Level static protected
Initial value:
= {
    6.634899, 4.605171, 3.780564, 3.318915, 3.017103,
    2.801872, 2.639259, 2.511249, 2.407341, 2.320967,
    2.247720, 2.184744, 2.129863, 2.081515, 2.038526,
    1.999994, 1.965214, 1.933627, 1.904781, 1.878311,
    1.853912, 1.831334, 1.810365, 1.790825, 1.772564,
    1.755449, 1.739367, 1.724222, 1.709926, 1.696406,
    1.683593, 1.671430, 1.659864, 1.648850, 1.638344,
    1.628311, 1.618716, 1.609528, 1.600721, 1.592268,
    1.584148, 1.576338, 1.568822, 1.561579, 1.554596,
    1.547856, 1.541346, 1.535055, 1.528968, 1.523077}
Definition at line 152 of file BEmcRec.h.
Referenced by Chi2Limit(), and SetChi2Limit().
float BEmcRec::fgChi2Level1 static protected
Initial value:
= {
    6.634899, 4.605171, 3.780564, 3.318915, 3.017103,
    2.801872, 2.639259, 2.511249, 2.407341, 2.320967,
    2.247720, 2.184744, 2.129863, 2.081515, 2.038526,
    1.999994, 1.965214, 1.933627, 1.904781, 1.878311,
    1.853912, 1.831334, 1.810365, 1.790825, 1.772564,
    1.755449, 1.739367, 1.724222, 1.709926, 1.696406,
    1.683593, 1.671430, 1.659864, 1.648850, 1.638344,
    1.628311, 1.618716, 1.609528, 1.600721, 1.592268,
    1.584148, 1.576338, 1.568822, 1.561579, 1.554596,
    1.547856, 1.541346, 1.535055, 1.528968, 1.523077}
Definition at line 150 of file BEmcRec.h.
Referenced by SetChi2Limit().
float BEmcRec::fgChi2Level2 static protected
Initial value:
= {
    5.411895, 3.912024, 3.278443, 2.916812, 2.677547,
    2.505458, 2.374582, 2.271008, 2.186567, 2.116065,
    2.056169, 2.004491, 1.959343, 1.919481, 1.883964,
    1.852072, 1.823237, 1.797008, 1.773021, 1.750981,
    1.730640, 1.711795, 1.694274, 1.677931, 1.662643,
    1.648301, 1.634814, 1.622101, 1.610093, 1.598727,
    1.587948, 1.577709, 1.567968, 1.558684, 1.549824,
    1.541357, 1.533256, 1.525494, 1.518051, 1.510903,
    1.504033, 1.497424, 1.491059, 1.484924, 1.479006,
    1.473292, 1.467771, 1.462433, 1.457267, 1.452265}
Definition at line 151 of file BEmcRec.h.
Referenced by SetChi2Limit().
float BEmcRec::fgEpar0 = 0.0014 static protected
Definition at line 167 of file BEmcRec.h.
Referenced by ClusterChisq(), SetTowerThreshold(), and TwoGamma().
float BEmcRec::fgEpar00 = 0.005 static protected
Definition at line 166 of file BEmcRec.h.
Referenced by ClusterChisq(), SetTowerThreshold(), and TwoGamma().
float BEmcRec::fgEpar1 = 0.03 static protected
Definition at line 168 of file BEmcRec.h.
Referenced by ClusterChisq(), and TwoGamma().
float BEmcRec::fgEpar2 = -0.03 static protected
Definition at line 169 of file BEmcRec.h.
Referenced by ClusterChisq(), and TwoGamma().
float BEmcRec::fgEpar3 = 0. static protected
Definition at line 170 of file BEmcRec.h.
Referenced by ClusterChisq(), and TwoGamma().
float BEmcRec::fgEpar4 = 4.0 static protected
Definition at line 171 of file BEmcRec.h.
Referenced by ClusterChisq(), and TwoGamma().
int const BEmcRec::fgMaxLen = 10000 static protected
Definition at line 160 of file BEmcRec.h.
Referenced by FindClusters().
float BEmcRec::fgMinPeakEnergy protected
Definition at line 158 of file BEmcRec.h.
Referenced by GetPeakThreshold(), and SetPeakThreshold().
float const BEmcRec::fgMinShowerEnergy = 0.1 static protected
Definition at line 159 of file BEmcRec.h.
Referenced by Gamma().
float BEmcRec::fgTowerThresh protected
Definition at line 157 of file BEmcRec.h.
Referenced by GetTowerThreshold(), and SetTowerThreshold().
float BEmcRec::fModSizex protected
Definition at line 142 of file BEmcRec.h.
Referenced by GetModSizex(), GlobalToSector(), SectorToTowers(), SetGeometry(), SetProfileParameters(), and TowersToSector().
float BEmcRec::fModSizey protected
Definition at line 143 of file BEmcRec.h.
Referenced by GetModSizey(), GlobalToSector(), SectorToTowers(), SetGeometry(), and TowersToSector().
std::vector<EmcModule>* BEmcRec::fModules protected
Definition at line 154 of file BEmcRec.h.
Referenced by BEmcRec(), FindClusters(), GetModules(), SetModules(), and ~BEmcRec().
int BEmcRec::fNx protected
Definition at line 139 of file BEmcRec.h.
Referenced by ClusterChisq(), FindClusters(), fTowerDist(), Gamma(), GetNx(), GetProb(), GetTowerGeometry(), GetTowerID(), GlobalToSector(), iTowerDist(), Momenta(), PrintTowerGeometry(), SectorToGlobal(), SetGeometry(), SetTowerGeometry(), ShiftX(), BEmcRecEEMC::Tower2Global(), BEmcRecFEMC::Tower2Global(), and TwoGamma().
int BEmcRec::fNy protected
Definition at line 140 of file BEmcRec.h.
Referenced by GetNy(), GetTowerGeometry(), GlobalToSector(), PrintTowerGeometry(), SectorToGlobal(), SetGeometry(), SetTowerGeometry(), BEmcRecFEMC::Tower2Global(), and BEmcRecEEMC::Tower2Global().
float BEmcRec::fPpar1 protected
Definition at line 178 of file BEmcRec.h.
Referenced by PredictEnergy(), and SetProfileParameters().
float BEmcRec::fPpar2 protected
Definition at line 179 of file BEmcRec.h.
Referenced by PredictEnergy(), and SetProfileParameters().
float BEmcRec::fPpar3 protected
Definition at line 180 of file BEmcRec.h.
Referenced by PredictEnergy(), and SetProfileParameters().
float BEmcRec::fPpar4 protected
Definition at line 181 of file BEmcRec.h.
Referenced by PredictEnergy(), and SetProfileParameters().
float BEmcRec::fPshiftx protected
Definition at line 182 of file BEmcRec.h.
Referenced by PredictEnergy(), and SetProfileParameters().
float BEmcRec::fPshifty protected
Definition at line 183 of file BEmcRec.h.
Referenced by PredictEnergy(), and SetProfileParameters().
float BEmcRec::fSin4T protected
Definition at line 175 of file BEmcRec.h.
Referenced by ClusterChisq(), SetProfileParameters(), and TwoGamma().
float BEmcRec::fSinTx protected
Definition at line 176 of file BEmcRec.h.
Referenced by CalculateErrors(), BEmcRecCEMC::CorrectPosition(), and SetProfileParameters().
float BEmcRec::fSinTy protected
Definition at line 177 of file BEmcRec.h.
Referenced by CalculateErrors(), BEmcRecCEMC::CorrectPosition(), and SetProfileParameters().
std::map<int, TowerGeom> BEmcRec::fTowerGeom protected
Definition at line 141 of file BEmcRec.h.
Referenced by GetTowerGeometry(), PrintTowerGeometry(), SectorToGlobal(), and SetTowerGeometry().
float BEmcRec::fVx protected
Definition at line 144 of file BEmcRec.h.
Referenced by GetVx(), and SetVertex().
float BEmcRec::fVy protected
Definition at line 145 of file BEmcRec.h.
Referenced by GetVy(), and SetVertex().
float BEmcRec::fVz protected
Definition at line 146 of file BEmcRec.h.
Referenced by BEmcRecFEMC::CorrectECore(), BEmcRecFEMC::CorrectPosition(), BEmcRecEEMC::CorrectPosition(), GetVz(), SetVertex(), BEmcRecEEMC::Tower2Global(), and BEmcRecFEMC::Tower2Global().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcRec.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcRec.cc