Analysis Software: EmcPeakarea Class Reference
EmcPeakarea Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcCluster.h>
Public Member Functions
EmcPeakarea ()
Constructor (zero Hit List)
EmcPeakarea (BEmcRec *sector)
EmcPeakarea (const std::vector< EmcModule > &hlist, BEmcRec *sector)
Constructor (inputs Hit List)
virtual ~EmcPeakarea ()
float GetChi2 ()
Returns Chi2.
float GetChi2New ()
int GetNdf () const
float GetCL () const
float GetCLNew ()
void GetCGmin (float *pxcgmin, float *pycgmin)
Returns peakarea's 1st momentum (COG) after Shower Shape fit.
void GetChar (float *pe, float *pec, float *pecore, float *pecorec, float *pxcg, float *pysg, float *pxcgmin, float *pysgmin, float *pxc, float *pyc, float *pxg, float *pyg, float *pzg, float *pxx, float *pxy, float *pyy, float *pchi, float *pde, float *pdx, float *pdy, float *pdz)
Substitutes a number of functions above (to save CPU time)
Public Member Functions inherited from EmcCluster
EmcCluster ()
Constructor (zero Hit List)
EmcCluster (BEmcRec *sector)
EmcCluster (const std::vector< EmcModule > &hlist, BEmcRec *sector)
Constructor (inputs Hit List)
virtual ~EmcCluster ()
void ReInitialize (const std::vector< EmcModule > &hlist)
Reinitializes EmcCluster supplying new Hit List.
int GetNofHits ()
Returns number of EmcModules in EmcCluster.
void GetHits (EmcModule *phit, int n)
Returns n EmcModules (sorted) with the maximum energy.
std::vector< EmcModule > GetHitList ()
Returns EmcCluster fHitList.
EmcModule GetMaxTower ()
Returns the EmcModule with the maximum energy.
EmcModule GetImpactTower ()
Returns the EmcModule corresponding to the reconstructed impact tower.
float GetTowerEnergy (int ich)
Returns the energy of the ich-tower (numbering from 0)
float GetTowerEnergy (int ix, int iy)
Returns the energy of the tower ix,iy (numbering from 0)
float GetTowerToF (int ich)
Returns the ToF of the ich-tower (numbering from 0)
int GetTowerDeadMap (int ich)
Returns the Dead Map of the ich-tower (numbering from 0)
int GetTowerWarnMap (int ich)
Returns the Warning Map of the ich-tower (numbering from 0)
float GetTowerADC (int ich)
float GetTowerTAC (int ich)
int GetNDead ()
Returns the number of dead channels around MaxTower.
int GetDeadMap ()
int GetWarnMap ()
float GetE4 ()
Returns the energy in 2x2 towers around the cluster Center of Gravity.
float GetE9 ()
Returns the energy in 3x3 towers around the cluster Center of Gravity.
float GetE9 (int ich)
Returns the energy in 3x3 towers around the tower ich.
float GetECore ()
Returns the cluster energy taking into account towers with E>Ethresh.
float GetECoreCorrected ()
Ecore corrected for energy leak sidewise core towers.
float GetTotalEnergy ()
Returns the EmcCluster total energy.
void GetMoments (float *pxcg, float *pycg, float *pxx, float *pxy, float *pyy)
Returns EmcCluster 1-st (pxcg,pycg) and 2-d momenta (pxx,pxy,pyy)
void GetCorrPos (float *pxc, float *pyc)
Returns the EmcCluster corrected position in Sector (SM) frame.
void GetGlobalPos (float &xg, float &yg, float &zg)
Returns the EmcCluster position in PHENIX global coord system.
void GetErrors (float *pde, float *pdx, float *pdy, float *pdz)
Returns the errors for the reconstructed energy and position.
void GetChar (float *pe, float *pxcg, float *pysg, float *pxc, float *pyc, float *pxg, float *pyg, float *pzg, float *pxx, float *pxy, float *pyy, float *pde, float *pdx, float *pdy, float *pdz)
Substitutes a number of functions above (to save CPU time)
int GetPeaks (std::vector< EmcPeakarea > *PkList, std::vector< EmcModule > *ppeaks)
Splits the EmcCluster onto peakarea's; also returns peak tower array corresponding to peakarea array.
float GetProb (float &chi2, int &ndf)
Protected Attributes
int fNdf
float fCL
Protected Attributes inherited from EmcCluster
std::vector< EmcModule > fHitList
BEmcRec * fOwner
Additional Inherited Members
Static Public Member Functions inherited from EmcCluster
static int max (int a, int b)
static float max (float a, float b)
static double max (double a, double b)
static int min (int a, int b)
static float min (float a, float b)
static double min (double a, double b)
static int ABS (int x)
static float ABS (float x)
static double ABS (double x)
static int lowint (float x)
Static Protected Attributes inherited from EmcCluster
static int const fgMaxNofPeaks = 1000
static int const fgPeakIter = 6
static float const fgEmin = 0.002
static float const fgChisq = 3.
static float const fgXABSURD = -999999.
static float const fgYABSURD = -999999.
Detailed Description
The 2-d level of the EMCal clustering. Every local maximum in cluster gives peakarea.
Definition at line 219 of file BEmcCluster.h.
Constructor & Destructor Documentation
EmcPeakarea::EmcPeakarea () inline
Constructor (zero Hit List)
Definition at line 223 of file BEmcCluster.h.
EmcPeakarea::EmcPeakarea (BEmcRec * sector) inline
Definition at line 229 of file BEmcCluster.h.
EmcPeakarea::EmcPeakarea (const std::vector< EmcModule > & hlist, BEmcRec * sector) inline
Constructor (inputs Hit List)
Definition at line 238 of file BEmcCluster.h.
virtual EmcPeakarea::~EmcPeakarea () inline virtual
Definition at line 245 of file BEmcCluster.h.
Member Function Documentation
void EmcPeakarea::GetCGmin (float * pxcgmin, float * pycgmin)
Returns peakarea's 1st momentum (COG) after Shower Shape fit.
Definition at line 1162 of file BEmcCluster.cc.
References EmcCluster::fgChisq, EmcCluster::fgXABSURD, EmcCluster::fgYABSURD, EmcCluster::fHitList, fNdf, EmcCluster::fOwner, BEmcRec::Gamma(), BEmcRec::GetModSizex(), BEmcRec::GetModSizey(), and x2.
void EmcPeakarea::GetChar (float * pe, float * pec, float * pecore, float * pecorec, float * pxcg, float * pysg, float * pxcgmin, float * pysgmin, float * pxc, float * pyc, float * pxg, float * pyg, float * pzg, float * pxx, float * pxy, float * pyy, float * pchi, float * pde, float * pdx, float * pdy, float * pdz)
Substitutes a number of functions above (to save CPU time)
Definition at line 926 of file BEmcCluster.cc.
References BEmcRec::CalculateErrors(), BEmcRec::Chi2Correct(), BEmcRec::CorrectECore(), BEmcRec::CorrectPosition(), fCL, EmcCluster::fgChisq, EmcCluster::fHitList, fNdf, EmcCluster::fOwner, BEmcRec::Gamma(), EmcCluster::GetECore(), BEmcRec::GetModSizex(), BEmcRec::GetModSizey(), EmcCluster::GetMoments(), EmcCluster::GetTotalEnergy(), BEmcRec::SectorToGlobal(), and x2.
float EmcPeakarea::GetChi2 ()
Returns Chi2.
Definition at line 988 of file BEmcCluster.cc.
References EmcCluster::fgChisq, EmcCluster::fHitList, fNdf, EmcCluster::fOwner, BEmcRec::Gamma(), and x2.
float EmcPeakarea::GetChi2New ()
Definition at line 1091 of file BEmcCluster.cc.
References EmcCluster::ABS(), dx, dy, EmcCluster::fOwner, BEmcRec::GetModSizex(), BEmcRec::GetModSizey(), EmcCluster::GetMoments(), EmcCluster::GetTotalEnergy(), EmcCluster::GetTowerEnergy(), and s1.
float EmcPeakarea::GetCL () const inline
Definition at line 257 of file BEmcCluster.h.
References fCL.
float EmcPeakarea::GetCLNew ()
Definition at line 1019 of file BEmcCluster.cc.
References EmcCluster::ABS(), dx, dy, EmcCluster::fOwner, BEmcRec::GetModSizex(), BEmcRec::GetModSizey(), EmcCluster::GetMoments(), EmcCluster::GetTotalEnergy(), EmcCluster::GetTowerEnergy(), and s1.
int EmcPeakarea::GetNdf () const inline
Definition at line 252 of file BEmcCluster.h.
References fNdf.
Member Data Documentation
float EmcPeakarea::fCL protected
Definition at line 279 of file BEmcCluster.h.
Referenced by GetChar(), and GetCL().
int EmcPeakarea::fNdf protected
Definition at line 278 of file BEmcCluster.h.
Referenced by GetCGmin(), GetChar(), GetChi2(), and GetNdf().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcCluster.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcCluster.cc