Analysis Software: CaloAna Class Reference
CaloAna Class Reference
#include <tutorials/blob/master/CaloAna/src/CaloAna.h>
Public Member Functions
CaloAna (const std::string &name="CaloAna", const std::string &fname="MyNtuple.root")
constructor
virtual ~CaloAna ()
destructor
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
int process_g4hits (PHCompositeNode *)
int process_g4cells (PHCompositeNode *)
int process_towers (PHCompositeNode *)
int process_clusters (PHCompositeNode *)
void Detector (const std::string &name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
std::string detector
std::string outfilename
Fun4AllHistoManager * hm
TFile * outfile
TNtuple * g4hitntuple
TNtuple * g4cellntuple
TNtuple * towerntuple
TNtuple * clusterntuple
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 12 of file CaloAna.h.
Constructor & Destructor Documentation
CaloAna::CaloAna (const std::string & name = "CaloAna", const std::string & fname = "MyNtuple.root")
constructor
Definition at line 35 of file CaloAna.cc.
CaloAna::~CaloAna () virtual
destructor
Definition at line 48 of file CaloAna.cc.
References clusterntuple, g4cellntuple, g4hitntuple, hm, and towerntuple.
Member Function Documentation
void CaloAna::Detector (const std::string & name) inline
Definition at line 35 of file CaloAna.h.
References name.
Referenced by Fun4All_CaloAna().
int CaloAna::End (PHCompositeNode * topNode) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 217 of file CaloAna.cc.
References clusterntuple, Fun4AllHistoManager::dumpHistos(), g4cellntuple, g4hitntuple, hm, outfile, outfilename, and towerntuple.
int CaloAna::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 57 of file CaloAna.cc.
References clusterntuple, g4cellntuple, g4hitntuple, hm, Fun4AllBase::Name(), outfile, outfilename, and towerntuple.
int CaloAna::process_clusters (PHCompositeNode * topNode)
Definition at line 195 of file CaloAna.cc.
References clusterntuple, detector, Fun4AllReturnCodes::EVENT_OK, and RawClusterContainer::getClusters().
Referenced by process_event().
int CaloAna::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 71 of file CaloAna.cc.
References Fun4AllReturnCodes::EVENT_OK, process_clusters(), process_g4cells(), process_g4hits(), and process_towers().
int CaloAna::process_g4cells (PHCompositeNode * topNode)
Definition at line 117 of file CaloAna.cc.
References detector, Fun4AllReturnCodes::EVENT_OK, g4cellntuple, PHG4CellDefs::get_binning(), PHG4CellDefs::ScintillatorSlatBinning::get_column(), PHG4CellDefs::SpacalBinning::get_etabin(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CellDefs::SpacalBinning::get_phibin(), PHG4CellDefs::ScintillatorSlatBinning::get_row(), PHG4CellDefs::SizeBinning::get_zbin(), PHG4CellContainer::getCells(), PHG4CellDefs::scintillatorslatbinning, PHG4CellDefs::sizebinning, and PHG4CellDefs::spacalbinning.
Referenced by process_event().
int CaloAna::process_g4hits (PHCompositeNode * topNode)
Definition at line 89 of file CaloAna.cc.
References detector, Fun4AllReturnCodes::EVENT_OK, g4hitntuple, and PHG4HitContainer::getHits().
Referenced by process_event().
int CaloAna::process_towers (PHCompositeNode * topNode)
Definition at line 160 of file CaloAna.cc.
References detector, Fun4AllReturnCodes::EVENT_OK, RawTowerGeomContainer::get_etacenter(), RawTowerGeomContainer::get_phicenter(), RawTowerContainer::getTowers(), phi, and towerntuple.
Referenced by process_event().
Member Data Documentation
TNtuple* CaloAna::clusterntuple protected
Definition at line 45 of file CaloAna.h.
Referenced by End(), Init(), process_clusters(), and ~CaloAna().
std::string CaloAna::detector protected
Definition at line 38 of file CaloAna.h.
Referenced by process_clusters(), process_g4cells(), process_g4hits(), and process_towers().
TNtuple* CaloAna::g4cellntuple protected
Definition at line 43 of file CaloAna.h.
Referenced by End(), Init(), process_g4cells(), and ~CaloAna().
TNtuple* CaloAna::g4hitntuple protected
Definition at line 42 of file CaloAna.h.
Referenced by End(), Init(), process_g4hits(), and ~CaloAna().
Fun4AllHistoManager* CaloAna::hm protected
Definition at line 40 of file CaloAna.h.
Referenced by End(), Init(), and ~CaloAna().
TFile* CaloAna::outfile protected
Definition at line 41 of file CaloAna.h.
Referenced by End(), and Init().
std::string CaloAna::outfilename protected
Definition at line 39 of file CaloAna.h.
Referenced by End(), and Init().
TNtuple* CaloAna::towerntuple protected
Definition at line 44 of file CaloAna.h.
Referenced by End(), Init(), process_towers(), and ~CaloAna().
The documentation for this class was generated from the following files:
tutorials/blob/master/CaloAna/src/CaloAna.h
tutorials/blob/master/CaloAna/src/CaloAna.cc