Analysis Software: RunHeader Class Reference
RunHeader Class Reference
#include <coresoftware/blob/master/offline/framework/ffaobjects/RunHeader.h>
Public Member Functions
virtual ~RunHeader ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void Reset ()
Clear Event.
virtual void identify (std::ostream &os=std::cout) const
virtual int isValid () const
isValid returns non zero if object contains valid data
virtual int get_RunNumber () const
get Run Number
virtual void set_RunNumber (const int run)
set Run Number
virtual double get_Bfield () const
get BField (deprecated in v2)
virtual void set_Bfield (const double rval)
set Bfield (deprecated in v2)
virtual time_t get_TimeStart () const
get Start Time of run (in unix ticks, use ctime to convert to date string)
virtual void set_TimeStart (const time_t ival)
set Start Time
virtual time_t get_TimeStop () const
get Time of End Run (in unix ticks)
virtual void set_TimeStop (const time_t ival)
set Time of End Run
virtual void NoWarning (const int i=1)
switches off the pesky virtual warning messages
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
void warning (const char *func) const
Detailed Description
Definition at line 12 of file RunHeader.h.
Constructor & Destructor Documentation
virtual RunHeader::~RunHeader () inline virtual
dtor
Definition at line 17 of file RunHeader.h.
Member Function Documentation
PHObject * RunHeader::CloneMe () const virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 14 of file RunHeader.cc.
double RunHeader::get_Bfield () const virtual
get BField (deprecated in v2)
Reimplemented in RunHeaderv1.
Definition at line 56 of file RunHeader.cc.
int RunHeader::get_RunNumber () const virtual
get Run Number
Reimplemented in RunHeaderv1.
Definition at line 42 of file RunHeader.cc.
Referenced by Fun4AllDstInputManager::fileopen(), PHNodeDump::GetGlobalVars(), and DumpRunHeader::process_Node().
time_t RunHeader::get_TimeStart () const virtual
get Start Time of run (in unix ticks, use ctime to convert to date string)
Reimplemented in RunHeaderv1.
Definition at line 70 of file RunHeader.cc.
Referenced by DumpRunHeader::process_Node().
time_t RunHeader::get_TimeStop () const virtual
get Time of End Run (in unix ticks)
Reimplemented in RunHeaderv1.
Definition at line 84 of file RunHeader.cc.
Referenced by DumpRunHeader::process_Node().
void RunHeader::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RunHeaderv1.
Definition at line 28 of file RunHeader.cc.
References return().
int RunHeader::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from PHObject.
Reimplemented in RunHeaderv1.
Definition at line 35 of file RunHeader.cc.
References PHWHERE.
Referenced by DumpRunHeader::process_Node().
void RunHeader::NoWarning (const int i = 1) virtual
switches off the pesky virtual warning messages
Definition at line 99 of file RunHeader.cc.
References i, nowarning, and return().
void RunHeader::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RunHeaderv1.
Definition at line 21 of file RunHeader.cc.
References PHWHERE, and return().
void RunHeader::set_Bfield (const double rval) virtual
set Bfield (deprecated in v2)
Reimplemented in RunHeaderv1.
Definition at line 63 of file RunHeader.cc.
void RunHeader::set_RunNumber (const int run) virtual
set Run Number
Reimplemented in RunHeaderv1.
Definition at line 49 of file RunHeader.cc.
References return().
void RunHeader::set_TimeStart (const time_t ival) virtual
set Start Time
Reimplemented in RunHeaderv1.
Definition at line 77 of file RunHeader.cc.
void RunHeader::set_TimeStop (const time_t ival) virtual
set Time of End Run
Reimplemented in RunHeaderv1.
Definition at line 91 of file RunHeader.cc.
void RunHeader::warning (const char * func) const protected
Definition at line 115 of file RunHeader.cc.
References nowarning, and return().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/RunHeader.h
coresoftware/blob/master/offline/framework/ffaobjects/RunHeader.cc