Analysis Software: Fun4AllHepMCInputManager Class Reference
Fun4AllHepMCInputManager Class Reference
#include <coresoftware/blob/master/generators/phhepmc/Fun4AllHepMCInputManager.h>
Public Member Functions
Fun4AllHepMCInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
virtual ~Fun4AllHepMCInputManager ()
virtual int fileopen (const std::string &filenam)
virtual int fileclose ()
virtual int run (const int nevents=0)
void ReadOscar (const int i=1)
virtual void Print (const std::string &what="ALL") const
virtual int PushBackEvents (const int i)
int SyncIt (const SyncObject *)
int GetSyncObject (SyncObject **)
int NoSyncPushBackEvents (const int nevt)
HepMC::GenEvent * ConvertFromOscar ()
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
int events_total
int events_thisfile
int readoscar
std::string filename
std::string topNodeName
PHCompositeNode * topNode
HepMC::IO_GenEvent * ascii_in
HepMC::GenEvent * evt
HepMC::GenEvent * save_evt
std::ifstream * filestream
std::istream * unzipstream
std::ifstream theOscarFile
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
boost::iostreams::filtering_streambuf
< boost::iostreams::input > zinbuffer
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Detailed Description
Definition at line 29 of file Fun4AllHepMCInputManager.h.
Constructor & Destructor Documentation
Fun4AllHepMCInputManager::Fun4AllHepMCInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP")
Definition at line 45 of file Fun4AllHepMCInputManager.cc.
References PHCompositeNode::addNode(), Fun4AllServer::getNode(), hepmc_helper, Fun4AllInputManager::InputNode(), Fun4AllServer::instance(), set_embedding_id(), PHHepMCGenHelper::set_geneventmap(), Fun4AllServer::topNode(), topNode, and topNodeName.
Fun4AllHepMCInputManager::~Fun4AllHepMCInputManager () virtual
Definition at line 77 of file Fun4AllHepMCInputManager.cc.
References ascii_in, fileclose(), filestream, and unzipstream.
Member Function Documentation
HepMC::GenEvent * Fun4AllHepMCInputManager::ConvertFromOscar ()
Definition at line 334 of file Fun4AllHepMCInputManager.cc.
References E, events_total, evt, i, pid, theOscarFile, toMM, v, and Fun4AllBase::Verbosity().
Referenced by Fun4AllHepMCPileupInputManager::run(), and run().
int Fun4AllHepMCInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 246 of file Fun4AllHepMCInputManager.cc.
References ascii_in, Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), readoscar, theOscarFile, and Fun4AllInputManager::UpdateFileList().
Referenced by fileopen(), PushBackEvents(), Fun4AllHepMCPileupInputManager::run(), run(), and ~Fun4AllHepMCInputManager().
int Fun4AllHepMCInputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 86 of file Fun4AllHepMCInputManager.cc.
References Fun4AllInputManager::AddToFileOpened(), ascii_in, Fun4AllSyncManager::CurrentRun(), events_thisfile, fileclose(), filename, filestream, PHFlag::FlagExist(), PHFlag::get_IntFlag(), in, recoConsts::instance(), Fun4AllInputManager::IsOpen(), FROG::location(), Fun4AllInputManager::MySyncManager(), Fun4AllBase::Name(), readoscar, theOscarFile, unzipstream, Fun4AllBase::Verbosity(), and zinbuffer.
int Fun4AllHepMCInputManager::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 76 of file Fun4AllHepMCInputManager.h.
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
int Fun4AllHepMCInputManager::GetSyncObject (SyncObject **) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 44 of file Fun4AllHepMCInputManager.h.
References Fun4AllReturnCodes::SYNC_NOOBJECT.
int Fun4AllHepMCInputManager::NoSyncPushBackEvents (const int nevt) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 45 of file Fun4AllHepMCInputManager.h.
References PushBackEvents().
void Fun4AllHepMCInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 269 of file Fun4AllHepMCInputManager.cc.
References Fun4AllInputManager::Print().
int Fun4AllHepMCInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 275 of file Fun4AllHepMCInputManager.cc.
References ascii_in, evt, fileclose(), i, Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), nevents(), PHWHERE, save_evt, and Fun4AllBase::Verbosity().
Referenced by NoSyncPushBackEvents().
void Fun4AllHepMCInputManager::ReadOscar (const int i = 1) inline
Definition at line 37 of file Fun4AllHepMCInputManager.h.
References i, and readoscar.
int Fun4AllHepMCInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllHepMCPileupInputManager.
Definition at line 158 of file Fun4AllHepMCInputManager.cc.
References ascii_in, ConvertFromOscar(), Fun4AllSyncManager::CurrentEvent(), PHHepMCGenEventMap::end(), Fun4AllReturnCodes::EVENT_OK, events_thisfile, events_total, evt, fileclose(), Fun4AllInputManager::FileListEmpty(), PHHepMCGenEventMap::find(), PHHepMCGenHelper::get_embedding_id(), PHHepMCGenHelper::get_geneventmap(), hepmc_helper, PHHepMCGenHelper::insert_event(), Fun4AllInputManager::IsOpen(), Fun4AllInputManager::MySyncManager(), Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), readoscar, Fun4AllInputManager::RejectEvent(), Fun4AllInputManager::ResetEvent(), save_evt, and Fun4AllBase::Verbosity().
void Fun4AllHepMCInputManager::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 82 of file Fun4AllHepMCInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
Referenced by Fun4AllHepMCInputManager().
void Fun4AllHepMCInputManager::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 67 of file Fun4AllHepMCInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
void Fun4AllHepMCInputManager::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 49 of file Fun4AllHepMCInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void Fun4AllHepMCInputManager::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 55 of file Fun4AllHepMCInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
void Fun4AllHepMCInputManager::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 61 of file Fun4AllHepMCInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
int Fun4AllHepMCInputManager::SyncIt (const SyncObject *) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 43 of file Fun4AllHepMCInputManager.h.
References Fun4AllReturnCodes::SYNC_OK.
Member Data Documentation
HepMC::IO_GenEvent* Fun4AllHepMCInputManager::ascii_in protected
Definition at line 94 of file Fun4AllHepMCInputManager.h.
Referenced by fileclose(), fileopen(), PushBackEvents(), Fun4AllHepMCPileupInputManager::run(), run(), and ~Fun4AllHepMCInputManager().
int Fun4AllHepMCInputManager::events_thisfile protected
Definition at line 87 of file Fun4AllHepMCInputManager.h.
Referenced by fileopen(), Fun4AllHepMCPileupInputManager::run(), and run().
int Fun4AllHepMCInputManager::events_total protected
Definition at line 86 of file Fun4AllHepMCInputManager.h.
Referenced by ConvertFromOscar(), Fun4AllHepMCPileupInputManager::run(), and run().
HepMC::GenEvent* Fun4AllHepMCInputManager::evt protected
Definition at line 95 of file Fun4AllHepMCInputManager.h.
Referenced by ConvertFromOscar(), PushBackEvents(), Fun4AllHepMCPileupInputManager::run(), and run().
std::string Fun4AllHepMCInputManager::filename protected
Definition at line 90 of file Fun4AllHepMCInputManager.h.
Referenced by fileopen().
std::ifstream* Fun4AllHepMCInputManager::filestream protected
Definition at line 99 of file Fun4AllHepMCInputManager.h.
Referenced by fileopen(), and ~Fun4AllHepMCInputManager().
PHHepMCGenHelper Fun4AllHepMCInputManager::hepmc_helper protected
helper for insert HepMC event to DST node and add vertex smearing
Definition at line 104 of file Fun4AllHepMCInputManager.h.
Referenced by Fun4AllHepMCInputManager(), Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager(), get_embedding_id(), Fun4AllHepMCPileupInputManager::run(), run(), set_embedding_id(), set_reuse_vertex(), set_vertex_distribution_function(), set_vertex_distribution_mean(), and set_vertex_distribution_width().
int Fun4AllHepMCInputManager::readoscar protected
Definition at line 88 of file Fun4AllHepMCInputManager.h.
Referenced by fileclose(), fileopen(), ReadOscar(), Fun4AllHepMCPileupInputManager::run(), and run().
HepMC::GenEvent* Fun4AllHepMCInputManager::save_evt protected
Definition at line 96 of file Fun4AllHepMCInputManager.h.
Referenced by PushBackEvents(), Fun4AllHepMCPileupInputManager::run(), and run().
std::ifstream Fun4AllHepMCInputManager::theOscarFile protected
Definition at line 101 of file Fun4AllHepMCInputManager.h.
Referenced by ConvertFromOscar(), fileclose(), and fileopen().
PHCompositeNode* Fun4AllHepMCInputManager::topNode protected
Definition at line 92 of file Fun4AllHepMCInputManager.h.
Referenced by Fun4AllHepMCInputManager().
std::string Fun4AllHepMCInputManager::topNodeName protected
Definition at line 91 of file Fun4AllHepMCInputManager.h.
Referenced by Fun4AllHepMCInputManager().
std::istream* Fun4AllHepMCInputManager::unzipstream protected
Definition at line 100 of file Fun4AllHepMCInputManager.h.
Referenced by fileopen(), and ~Fun4AllHepMCInputManager().
boost::iostreams::filtering_streambuf<boost::iostreams::input> Fun4AllHepMCInputManager::zinbuffer protected
Definition at line 107 of file Fun4AllHepMCInputManager.h.
Referenced by fileopen().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/Fun4AllHepMCInputManager.h
coresoftware/blob/master/generators/phhepmc/Fun4AllHepMCInputManager.cc