Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C File Reference
G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C File Reference
#include <vector>
Enumerations
enum TPC_Gas {
Ne2K_100, Ne2K_400, NeCF4_100, NeCF4_300,
NeCF4_400, ByHand, Ne2K_100, Ne2K_400,
NeCF4_100, NeCF4_300, NeCF4_400, ByHand
}
Functions
void SvtxInit (int n_TPC_layers=40, int verbosity=0)
double Svtx (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Svtx_Cells (int verbosity=0)
void Svtx_Reco (int verbosity=0)
void G4_Svtx_Reco ()
void Svtx_Eval (std::string outputfile, int verbosity=0)
Variables
bool use_primary_vertex = false
const int n_maps_layer = 3
const int n_intt_layer = 4
int n_tpc_layer_inner = 8
double tpc_layer_thick_inner = 1.25
int tpc_layer_rphi_count_inner = 1920
int n_tpc_layer_mid = 16
double tpc_layer_thick_mid = 1.25
int tpc_layer_rphi_count_mid = 1536
int n_tpc_layer_outer = 16
double tpc_layer_thick_outer = 1.125
int tpc_layer_rphi_count_outer = 2304
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
double inner_cage_radius = 20.
double inner_readout_radius = 30.
TPC_Gas ether = TPC_Gas::NeCF4_400
double Ne_dEdx = 1.56
double CF4_dEdx = 7.00
double iBut_dEdx = 5.93
double Ne_NPrimary = 12
double CF4_NPrimary = 51
double iBut_NPrimary = 84
double Ne_NTotal = 43
double CF4_NTotal = 100
double iBut_NTotal = 195
double TPC_SigmaT = 0.03
double TPCDriftVelocity
double TPC_Trans_Diffusion
double TPC_Long_Diffusion
double TPC_dEdx
double TPC_NPri
double TPC_NTot
double TPC_ElectronsPerKeV
double TPCADCClock
double TPCShapingRMSLead
double TPCShapingRMSTail
double tpc_cell_z
double TPC_SmearRPhi
double TPC_SmearZ
int Max_si_layer
Enumeration Type Documentation
enum TPC_Gas
Enumerator:
Ne2K_100
Ne2K_400
NeCF4_100
NeCF4_300
NeCF4_400
ByHand
Ne2K_100
Ne2K_400
NeCF4_100
NeCF4_300
NeCF4_400
ByHand
Definition at line 38 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
Function Documentation
void G4_Svtx_Reco ()
Definition at line 791 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References Svtx_Reco().
double Svtx (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 203 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References i, inner_cage_radius, inner_readout_radius, n_gas_layer, n_intt_layer, n_maps_layer, n_tpc_layer_inner, n_tpc_layer_mid, n_tpc_layer_outer, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), tpc_layer_thick_inner, tpc_layer_thick_mid, tpc_layer_thick_outer, verbosity, and Fun4AllBase::Verbosity().
void Svtx_Cells (int verbosity = 0)
Definition at line 424 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References double(), i, inner_cage_radius, inner_readout_radius, Fun4AllServer::instance(), n_gas_layer, n_intt_layer, n_maps_layer, n_tpc_layer_inner, n_tpc_layer_mid, n_tpc_layer_outer, Fun4AllServer::registerSubsystem(), tpc_cell_x, tpc_cell_y, tpc_cell_z, TPC_dEdx, TPC_ElectronsPerKeV, tpc_layer_rphi_count_inner, tpc_layer_rphi_count_mid, tpc_layer_rphi_count_outer, tpc_layer_thick_inner, tpc_layer_thick_mid, tpc_layer_thick_outer, TPC_Long_Diffusion, TPC_NPri, TPC_NTot, TPC_SigmaT, TPC_SmearRPhi, TPC_SmearZ, TPC_Trans_Diffusion, TPCADCClock, TPCDriftVelocity, TPCShapingRMSLead, TPCShapingRMSTail, and verbosity.
void Svtx_Eval (std::string outputfile, int verbosity = 0)
Definition at line 801 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References SvtxEvaluator::do_cluster_eval(), SvtxEvaluator::do_g4hit_eval(), SvtxEvaluator::do_gpoint_eval(), SvtxEvaluator::do_hit_eval(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), SvtxEvaluator::scan_for_embedded(), use_primary_vertex, verbosity, and Fun4AllBase::Verbosity().
void Svtx_Reco (int verbosity = 0)
Definition at line 606 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References i, Fun4AllServer::instance(), Max_si_layer, n_gas_layer, n_intt_layer, n_maps_layer, Fun4AllServer::registerSubsystem(), use_primary_vertex, and verbosity.
void SvtxInit (int n_TPC_layers = 40, int verbosity = 0)
Definition at line 89 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
References ByHand, CF4_dEdx, CF4_NPrimary, CF4_NTotal, ether, iBut_dEdx, iBut_NPrimary, iBut_NTotal, Max_si_layer, n_gas_layer, n_intt_layer, n_maps_layer, Ne2K_100, Ne2K_400, Ne_dEdx, Ne_NPrimary, Ne_NTotal, NeCF4_100, NeCF4_300, NeCF4_400, tpc_cell_z, TPC_dEdx, TPC_ElectronsPerKeV, TPC_Long_Diffusion, TPC_NPri, TPC_NTot, TPC_SmearRPhi, TPC_SmearZ, TPC_Trans_Diffusion, TPCADCClock, TPCDriftVelocity, TPCShapingRMSLead, TPCShapingRMSTail, and verbosity.
Variable Documentation
double CF4_dEdx = 7.00
Definition at line 53 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double CF4_NPrimary = 51
Definition at line 57 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double CF4_NTotal = 100
Definition at line 61 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
TPC_Gas ether = TPC_Gas::NeCF4_400
Definition at line 47 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double iBut_dEdx = 5.93
Definition at line 54 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double iBut_NPrimary = 84
Definition at line 58 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double iBut_NTotal = 195
Definition at line 62 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double inner_cage_radius = 20.
Definition at line 32 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double inner_readout_radius = 30.
Definition at line 33 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int Max_si_layer
Definition at line 87 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
Definition at line 30 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
const int n_intt_layer = 4
Definition at line 9 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
const int n_maps_layer = 3
Definition at line 8 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int n_tpc_layer_inner = 8
Definition at line 11 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int n_tpc_layer_mid = 16
Definition at line 22 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int n_tpc_layer_outer = 16
Definition at line 26 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double Ne_dEdx = 1.56
Definition at line 52 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double Ne_NPrimary = 12
Definition at line 56 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double Ne_NTotal = 43
Definition at line 60 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double tpc_cell_z
Definition at line 83 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_dEdx
Definition at line 71 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_ElectronsPerKeV
Definition at line 74 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int tpc_layer_rphi_count_inner = 1920
Definition at line 13 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int tpc_layer_rphi_count_mid = 1536
Definition at line 24 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
int tpc_layer_rphi_count_outer = 2304
Definition at line 28 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double tpc_layer_thick_inner = 1.25
Definition at line 12 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double tpc_layer_thick_mid = 1.25
Definition at line 23 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double tpc_layer_thick_outer = 1.125
Definition at line 27 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_Long_Diffusion
Definition at line 70 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_NPri
Definition at line 72 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_NTot
Definition at line 73 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_SigmaT = 0.03
Definition at line 65 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_SmearRPhi
Definition at line 84 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_SmearZ
Definition at line 85 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPC_Trans_Diffusion
Definition at line 69 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCADCClock
Definition at line 80 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCDriftVelocity
Definition at line 68 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCShapingRMSLead
Definition at line 81 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
double TPCShapingRMSTail
Definition at line 82 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.
bool use_primary_vertex = false
Definition at line 6 of file G4_Svtx_maps_ladders+intt_ladders+tpc_KalmanPatRec.C.