Analysis Software: PidInfo Class Reference
PidInfo Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/PidInfo.h>
Public Types
enum PID_CANDIDATE { ELECTRON =0, CHARGEDPION =1, CHARGEDKAON =2, PROTON =3 }
Public Member Functions
virtual ~PidInfo ()
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
virtual int get_track_id () const
virtual SvtxTrackState * get_track_state () const
virtual float get_likelihood (const PID_CANDIDATE candidate)
virtual void set_track_id (const int id)
virtual void set_track_state (SvtxTrackState *state)
virtual void set_likelihood (const PID_CANDIDATE candidate, const float candidate_prob)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PidInfo (int id)
Detailed Description
Definition at line 12 of file PidInfo.h.
Member Enumeration Documentation
enum PidInfo::PID_CANDIDATE
Enumerator:
ELECTRON
CHARGEDPION
CHARGEDKAON
PROTON
Definition at line 16 of file PidInfo.h.
Constructor & Destructor Documentation
virtual PidInfo::~PidInfo () inline virtual
Definition at line 18 of file PidInfo.h.
PidInfo::PidInfo (int id) inline protected
Definition at line 38 of file PidInfo.h.
Member Function Documentation
virtual float PidInfo::get_likelihood (const PID_CANDIDATE candidate) inline virtual
Reimplemented in PidInfo_RICH_v1.
Definition at line 28 of file PidInfo.h.
References PHOOL_VIRTUAL_WARN.
Referenced by FastPid_RICH::process_event().
virtual int PidInfo::get_track_id () const inline virtual
Reimplemented in PidInfo_RICH_v1.
Definition at line 24 of file PidInfo.h.
References PHOOL_VIRTUAL_WARN.
Referenced by PidInfoContainer::AddPidInfo().
virtual SvtxTrackState* PidInfo::get_track_state () const inline virtual
Reimplemented in PidInfo_RICH_v1.
Definition at line 26 of file PidInfo.h.
References PHOOL_VIRTUAL_WARN.
Referenced by FastPid_RICH::process_event().
virtual void PidInfo::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PidInfo_RICH_v1.
Definition at line 22 of file PidInfo.h.
References PHOOL_VIRTUAL_WARNING.
virtual int PidInfo::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PidInfo_RICH_v1.
Definition at line 21 of file PidInfo.h.
References PHOOL_VIRTUAL_WARNING.
virtual void PidInfo::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PidInfo_RICH_v1.
Definition at line 20 of file PidInfo.h.
References PHOOL_VIRTUAL_WARNING.
virtual void PidInfo::set_likelihood (const PID_CANDIDATE candidate, const float candidate_prob) inline virtual
Definition at line 34 of file PidInfo.h.
References PHOOL_VIRTUAL_WARN.
Referenced by FastPid_RICH::process_event(), and RICHParticleID::process_event().
virtual void PidInfo::set_track_id (const int id) inline virtual
Reimplemented in PidInfo_RICH_v1.
Definition at line 30 of file PidInfo.h.
References PHOOL_VIRTUAL_WARN.
virtual void PidInfo::set_track_state (SvtxTrackState * state) inline virtual
Reimplemented in PidInfo_RICH_v1.
Definition at line 32 of file PidInfo.h.
References PHOOL_VIRTUAL_WARN.
Referenced by FastPid_RICH::process_event().
The documentation for this class was generated from the following file:
analysis/blob/master/ParticleID/RICHAnalysis/PidInfo.h