Analysis Software: RawTowerGeomv1 Class Reference
RawTowerGeomv1 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv1.h>
Public Member Functions
RawTowerGeomv1 ()
RawTowerGeomv1 (RawTowerDefs::keytype id)
virtual ~RawTowerGeomv1 ()
void identify (std::ostream &os=std::cout) const
void set_id (RawTowerDefs::keytype key)
RawTowerDefs::keytype get_id () const
int get_bineta () const
int get_binphi () const
int get_column () const
int get_row () const
void set_center_x (double x)
void set_center_y (double y)
void set_center_z (double z)
double get_center_x () const
double get_center_y () const
double get_center_z () const
double get_center_radius () const
double get_eta () const
double get_phi () const
Public Member Functions inherited from RawTowerGeom
virtual ~RawTowerGeom ()
virtual void set_size_x (double)
virtual void set_size_y (double)
virtual void set_size_z (double)
virtual double get_size_x () const
virtual double get_size_y () const
virtual double get_size_z () const
virtual double get_volume () const
virtual void set_tower_type (int)
virtual int get_tower_type () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype _towerid
double _center_x
double _center_y
double _center_z
Additional Inherited Members
Protected Member Functions inherited from RawTowerGeom
RawTowerGeom ()
Detailed Description
Definition at line 10 of file RawTowerGeomv1.h.
Constructor & Destructor Documentation
RawTowerGeomv1::RawTowerGeomv1 ()
Definition at line 8 of file RawTowerGeomv1.cc.
RawTowerGeomv1::RawTowerGeomv1 (RawTowerDefs::keytype id)
Definition at line 16 of file RawTowerGeomv1.cc.
virtual RawTowerGeomv1::~RawTowerGeomv1 () inline virtual
Definition at line 15 of file RawTowerGeomv1.h.
Member Function Documentation
int RawTowerGeomv1::get_bineta () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 22 of file RawTowerGeomv1.h.
References _towerid, and RawTowerDefs::decode_index1().
int RawTowerGeomv1::get_binphi () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 23 of file RawTowerGeomv1.h.
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv1::get_center_radius () const virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv1.cc.
References _center_x, and _center_y.
double RawTowerGeomv1::get_center_x () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 43 of file RawTowerGeomv1.h.
References _center_x.
Referenced by identify().
double RawTowerGeomv1::get_center_y () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 44 of file RawTowerGeomv1.h.
References _center_y.
Referenced by identify().
double RawTowerGeomv1::get_center_z () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 45 of file RawTowerGeomv1.h.
References _center_z.
Referenced by identify().
int RawTowerGeomv1::get_column () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv1.h.
References _towerid, and RawTowerDefs::decode_index1().
double RawTowerGeomv1::get_eta () const virtual
Reimplemented from RawTowerGeom.
Definition at line 30 of file RawTowerGeomv1.cc.
References _center_x, _center_y, and _center_z.
RawTowerDefs::keytype RawTowerGeomv1::get_id () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 20 of file RawTowerGeomv1.h.
References _towerid.
double RawTowerGeomv1::get_phi () const virtual
Reimplemented from RawTowerGeom.
Definition at line 42 of file RawTowerGeomv1.cc.
References _center_x, and _center_y.
int RawTowerGeomv1::get_row () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 25 of file RawTowerGeomv1.h.
References _towerid, and RawTowerDefs::decode_index2().
void RawTowerGeomv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeom.
Definition at line 47 of file RawTowerGeomv1.cc.
References get_center_x(), get_center_y(), and get_center_z().
void RawTowerGeomv1::set_center_x (double x) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 27 of file RawTowerGeomv1.h.
References _center_x, and x.
Referenced by RawTowerCombiner::CreateNodes(), and Prototype2RawTowerBuilder::InitRun().
void RawTowerGeomv1::set_center_y (double y) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 32 of file RawTowerGeomv1.h.
References _center_y, and y.
Referenced by RawTowerCombiner::CreateNodes(), and Prototype2RawTowerBuilder::InitRun().
void RawTowerGeomv1::set_center_z (double z) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 37 of file RawTowerGeomv1.h.
References _center_z, and z.
Referenced by RawTowerCombiner::CreateNodes(), and Prototype2RawTowerBuilder::InitRun().
void RawTowerGeomv1::set_id (RawTowerDefs::keytype key) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 19 of file RawTowerGeomv1.h.
References _towerid.
Member Data Documentation
double RawTowerGeomv1::_center_x protected
Definition at line 54 of file RawTowerGeomv1.h.
Referenced by get_center_radius(), get_center_x(), get_eta(), get_phi(), and set_center_x().
double RawTowerGeomv1::_center_y protected
Definition at line 55 of file RawTowerGeomv1.h.
Referenced by get_center_radius(), get_center_y(), get_eta(), get_phi(), and set_center_y().
double RawTowerGeomv1::_center_z protected
Definition at line 56 of file RawTowerGeomv1.h.
Referenced by get_center_z(), get_eta(), and set_center_z().
RawTowerDefs::keytype RawTowerGeomv1::_towerid protected
Definition at line 52 of file RawTowerGeomv1.h.
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv1.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv1.cc