Analysis Software: PgPostCalBank Class Reference
PgPostCalBank Class Reference abstract
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBank.h>
Public Member Functions
PgPostCalBank ()
virtual ~PgPostCalBank ()
virtual void printHeader () const
virtual void printEntry (size_t)=0
virtual void print ()=0
virtual size_t getLength ()=0
virtual PdbCalChan & getEntry (size_t)=0
virtual void setLength (size_t val)=0
virtual PdbBankID getBankID () const
virtual PHTimeStamp getInsertTime () const
virtual PHTimeStamp getStartValTime () const
virtual PHTimeStamp getEndValTime () const
virtual std::string getDescription () const
virtual std::string getUserName () const
virtual std::string getTableName () const
virtual void setBankID (const PdbBankID &val)
virtual void setInsertTime (const PHTimeStamp &val)
virtual void setStartValTime (const PHTimeStamp &val)
virtual void setEndValTime (const PHTimeStamp &val)
virtual void setDescription (const std::string &val)
virtual void setUserName (const std::string &val)
virtual void setTableName (const std::string &val)
virtual int isValid (const PHTimeStamp &) const
ClassDef (PgPostCalBank, 2)
Public Member Functions inherited from PdbCalBank
PdbCalBank ()
virtual ~PdbCalBank ()
virtual PHObject * CloneMe () const =0
Virtual copy constructor.
ClassDef (PdbCalBank, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 16 of file PgPostCalBank.h.
Constructor & Destructor Documentation
PgPostCalBank::PgPostCalBank () inline
Definition at line 19 of file PgPostCalBank.h.
virtual PgPostCalBank::~PgPostCalBank () inline virtual
Definition at line 20 of file PgPostCalBank.h.
Member Function Documentation
PgPostCalBank::ClassDef (PgPostCalBank , 2)
virtual PdbBankID PgPostCalBank::getBankID () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 31 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual std::string PgPostCalBank::getDescription () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 35 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual PHTimeStamp PgPostCalBank::getEndValTime () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 34 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual PdbCalChan& PgPostCalBank::getEntry (size_t) pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
Referenced by PgPostBankBackupManager::dumpTable().
virtual PHTimeStamp PgPostCalBank::getInsertTime () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 32 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual size_t PgPostCalBank::getLength () pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
Referenced by PgPostBankBackupManager::dumpTable().
virtual PHTimeStamp PgPostCalBank::getStartValTime () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 33 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual std::string PgPostCalBank::getTableName () const inline virtual
Reimplemented in PgPostBankWrapper.
Definition at line 37 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual std::string PgPostCalBank::getUserName () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 36 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::set_obj_info().
virtual int PgPostCalBank::isValid (const PHTimeStamp &) const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 47 of file PgPostCalBank.h.
virtual void PgPostCalBank::print () pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
virtual void PgPostCalBank::printEntry (size_t) pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
virtual void PgPostCalBank::printHeader () const inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 22 of file PgPostCalBank.h.
virtual void PgPostCalBank::setBankID (const PdbBankID & val) inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 39 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setDescription (const std::string & val) inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 43 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setEndValTime (const PHTimeStamp & val) inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 42 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setInsertTime (const PHTimeStamp & val) inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 40 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setLength (size_t val) pure virtual
Implements PdbCalBank.
Implemented in PgPostBankWrapper.
virtual void PgPostCalBank::setStartValTime (const PHTimeStamp & val) inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 41 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setTableName (const std::string & val) inline virtual
Reimplemented in PgPostBankWrapper.
Definition at line 45 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
virtual void PgPostCalBank::setUserName (const std::string & val) inline virtual
Implements PdbCalBank.
Reimplemented in PgPostBankWrapper.
Definition at line 44 of file PgPostCalBank.h.
Referenced by PgPostBankBackupStorage::createBank().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBank.h