Analysis Software: Prototype4DSTReader Class Reference
Prototype4DSTReader Class Reference
Prototype4DSTReader save information from DST to an evaluator, which could include hit. particle, vertex, towers and jet (to be activated)
#include <prototype/blob/master/offline/packages/Prototype4/Prototype4DSTReader.h>
Classes
struct record
Public Member Functions
Prototype4DSTReader (const std::string &filename)
virtual ~Prototype4DSTReader ()
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
void AddTower (const std::string &name)
void AddTowerTemperature (const std::string &name)
void AddRunInfo (const std::string &name)
void AddEventInfo (const std::string &name)
double get_tower_zero_sup ()
zero suppression for all calorimeters
void set_tower_zero_sup (double b)
zero suppression for all calorimeters
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Types
typedef std::shared_ptr
< TClonesArray > arr_ptr
typedef std::vector< record > records_t
typedef RawTower_Prototype4 RawTower_type
typedef RawTower_Temperature RawTowerT_type
Protected Member Functions
void build_tree ()
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::vector< std::string > _tower_postfix
std::vector< std::string > _towertemp_postfix
tower temperature
std::vector< std::string > _runinfo_list
std::vector< std::string > _eventinfo_list
int nblocks
records_t _records
int _event
std::string _out_file_name
TTree * _T
double _tower_zero_sup
zero suppression for all calorimeters
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Prototype4DSTReader save information from DST to an evaluator, which could include hit. particle, vertex, towers and jet (to be activated)
Definition at line 33 of file Prototype4DSTReader.h.
Member Typedef Documentation
typedef std::shared_ptr<TClonesArray> Prototype4DSTReader::arr_ptr protected
Definition at line 81 of file Prototype4DSTReader.h.
typedef RawTower_Prototype4 Prototype4DSTReader::RawTower_type protected
Definition at line 107 of file Prototype4DSTReader.h.
typedef RawTower_Temperature Prototype4DSTReader::RawTowerT_type protected
Definition at line 109 of file Prototype4DSTReader.h.
typedef std::vector<record> Prototype4DSTReader::records_t protected
Definition at line 104 of file Prototype4DSTReader.h.
Constructor & Destructor Documentation
Prototype4DSTReader::Prototype4DSTReader (const std::string & filename)
Definition at line 41 of file Prototype4DSTReader.cc.
Prototype4DSTReader::~Prototype4DSTReader () virtual
Definition at line 53 of file Prototype4DSTReader.cc.
References _records, and _T.
Member Function Documentation
void Prototype4DSTReader::AddEventInfo (const std::string & name) inline
Definition at line 56 of file Prototype4DSTReader.h.
References _eventinfo_list.
void Prototype4DSTReader::AddRunInfo (const std::string & name) inline
Definition at line 55 of file Prototype4DSTReader.h.
References _runinfo_list.
Referenced by Fun4All_TestBeam().
void Prototype4DSTReader::AddTower (const std::string & name) inline
Definition at line 48 of file Prototype4DSTReader.h.
References _tower_postfix.
Referenced by Fun4All_TestBeam().
void Prototype4DSTReader::AddTowerTemperature (const std::string & name) inline
Definition at line 50 of file Prototype4DSTReader.h.
References _towertemp_postfix.
void Prototype4DSTReader::build_tree () protected
Definition at line 165 of file Prototype4DSTReader.cc.
References Prototype4DSTReader::record::_arr_ptr, Prototype4DSTReader::record::_cnt, Prototype4DSTReader::record::_dvalue, Prototype4DSTReader::record::_name, _out_file_name, _records, _T, Prototype4DSTReader::record::_type, BUFFER_SIZE, PHTFileServer::get(), it, nblocks, PHTFileServer::open(), Prototype4DSTReader::record::typ_eventinfo, Prototype4DSTReader::record::typ_runinfo, Prototype4DSTReader::record::typ_tower, and Prototype4DSTReader::record::typ_towertemp.
Referenced by Init().
int Prototype4DSTReader::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 411 of file Prototype4DSTReader.cc.
References _out_file_name, _records, _T, PHTFileServer::cd(), and PHTFileServer::get().
double Prototype4DSTReader::get_tower_zero_sup () inline
zero suppression for all calorimeters
Definition at line 62 of file Prototype4DSTReader.h.
References _tower_zero_sup.
int Prototype4DSTReader::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 65 of file Prototype4DSTReader.cc.
References Prototype4DSTReader::record::_arr, Prototype4DSTReader::record::_arr_ptr, Prototype4DSTReader::record::_cnt, Prototype4DSTReader::record::_dvalue, _eventinfo_list, Prototype4DSTReader::record::_name, _records, _runinfo_list, _tower_postfix, _tower_zero_sup, _towertemp_postfix, Prototype4DSTReader::record::_type, build_tree(), it, nblocks, Prototype4DSTReader::record::typ_eventinfo, Prototype4DSTReader::record::typ_runinfo, Prototype4DSTReader::record::typ_tower, and Prototype4DSTReader::record::typ_towertemp.
int Prototype4DSTReader::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 223 of file Prototype4DSTReader.cc.
References Prototype4DSTReader::record::_arr, Prototype4DSTReader::record::_arr_ptr, Prototype4DSTReader::record::_cnt, Prototype4DSTReader::record::_dvalue, _event, Prototype4DSTReader::record::_name, _records, _T, _tower_zero_sup, Prototype4DSTReader::record::_type, assert, PHParameters::exist_double_param(), PHParameters::FillFrom(), PHParameters::get_double_param(), RawTower_Prototype4::get_energy(), RawTower_Temperature::get_nr_entries(), RawTower_Temperature::get_temperature_from_entry(), RawTowerContainer::getTowers(), it, RawTowerContainer::size(), Prototype4DSTReader::record::typ_eventinfo, Prototype4DSTReader::record::typ_hit, Prototype4DSTReader::record::typ_part, Prototype4DSTReader::record::typ_runinfo, Prototype4DSTReader::record::typ_tower, Prototype4DSTReader::record::typ_towertemp, Prototype4DSTReader::record::typ_vertex, and Fun4AllBase::Verbosity().
void Prototype4DSTReader::set_tower_zero_sup (double b) inline
zero suppression for all calorimeters
Definition at line 65 of file Prototype4DSTReader.h.
References _tower_zero_sup.
Member Data Documentation
int Prototype4DSTReader::_event protected
Definition at line 112 of file Prototype4DSTReader.h.
Referenced by process_event().
std::vector<std::string> Prototype4DSTReader::_eventinfo_list protected
Definition at line 75 of file Prototype4DSTReader.h.
Referenced by AddEventInfo(), and Init().
std::string Prototype4DSTReader::_out_file_name protected
Definition at line 114 of file Prototype4DSTReader.h.
Referenced by build_tree(), and End().
records_t Prototype4DSTReader::_records protected
Definition at line 105 of file Prototype4DSTReader.h.
Referenced by build_tree(), End(), Init(), process_event(), and ~Prototype4DSTReader().
std::vector<std::string> Prototype4DSTReader::_runinfo_list protected
Definition at line 74 of file Prototype4DSTReader.h.
Referenced by AddRunInfo(), and Init().
TTree* Prototype4DSTReader::_T protected
Definition at line 117 of file Prototype4DSTReader.h.
Referenced by build_tree(), End(), process_event(), and ~Prototype4DSTReader().
std::vector<std::string> Prototype4DSTReader::_tower_postfix protected
Definition at line 69 of file Prototype4DSTReader.h.
Referenced by AddTower(), and Init().
double Prototype4DSTReader::_tower_zero_sup protected
zero suppression for all calorimeters
Definition at line 120 of file Prototype4DSTReader.h.
Referenced by get_tower_zero_sup(), Init(), process_event(), and set_tower_zero_sup().
std::vector<std::string> Prototype4DSTReader::_towertemp_postfix protected
tower temperature
Definition at line 71 of file Prototype4DSTReader.h.
Referenced by AddTowerTemperature(), and Init().
int Prototype4DSTReader::nblocks protected
Definition at line 77 of file Prototype4DSTReader.h.
Referenced by build_tree(), and Init().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype4/Prototype4DSTReader.h
prototype/blob/master/offline/packages/Prototype4/Prototype4DSTReader.cc