Analysis Software: PHG4TrackFastSimEval Class Reference
PHG4TrackFastSimEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h>
Public Types
enum Flag { NONE = 0 }
Public Member Functions
PHG4TrackFastSimEval (const std::string &name="PHG4TrackFastSimEval", const std::string &filename="g4eval.root", const std::string &trackmapname="SvtxTrackMap")
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_filename (const char *file)
void set_flag (const Flag &flag, const bool &value)
void reset_variables ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void fill_track_tree (PHCompositeNode *)
void fill_vertex_tree (PHCompositeNode *)
int GetNodes (PHCompositeNode *)
Private Attributes
std::string _outfile_name
std::string _trackmapname
int _event
unsigned int _flags
TTree * _eval_tree_tracks
TTree * _eval_tree_vertex
int event
int gtrackID
int gflavor
float gpx
float gpy
float gpz
float gvx
float gvy
float gvz
float gvt
int trackID
int charge
int nhits
float px
float py
float pz
float pcax
float pcay
float pcaz
float dca2d
float vx
float vy
float vz
float deltavx
float deltavy
float deltavz
int ntracks
int n_from_truth
TH2D * _h2d_Delta_mom_vs_truth_mom
TH2D * _h2d_Delta_mom_vs_truth_eta
PHG4TruthInfoContainer * _truth_container
SvtxTrackMap * _trackmap
SvtxVertexMap * _vertexmap
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 25 of file PHG4TrackFastSimEval.h.
Member Enumeration Documentation
enum PHG4TrackFastSimEval::Flag
Enumerator:
NONE
Definition at line 49 of file PHG4TrackFastSimEval.h.
Constructor & Destructor Documentation
PHG4TrackFastSimEval::PHG4TrackFastSimEval (const std::string & name = "PHG4TrackFastSimEval", const std::string & filename = "g4eval.root", const std::string & trackmapname = "SvtxTrackMap")
Definition at line 47 of file PHG4TrackFastSimEval.cc.
References reset_variables().
Member Function Documentation
int PHG4TrackFastSimEval::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 151 of file PHG4TrackFastSimEval.cc.
References _eval_tree_tracks, _eval_tree_vertex, _h2d_Delta_mom_vs_truth_eta, _h2d_Delta_mom_vs_truth_mom, _outfile_name, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, and PHTFileServer::get().
void PHG4TrackFastSimEval::fill_track_tree (PHCompositeNode * topNode) private
Definition at line 170 of file PHG4TrackFastSimEval.cc.
References _eval_tree_tracks, _event, _h2d_Delta_mom_vs_truth_eta, _h2d_Delta_mom_vs_truth_mom, _trackmap, _truth_container, SvtxTrackMap::begin(), charge, dca2d, SvtxTrackMap::end(), SvtxTrack_v1::get_charge(), SvtxTrack_v1::get_dca2d(), SvtxTrack_v1::get_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), SvtxTrack_v1::get_px(), PHG4Particle::get_py(), SvtxTrack_v1::get_py(), PHG4Particle::get_pz(), SvtxTrack_v1::get_pz(), PHG4VtxPoint::get_t(), PHG4Particle::get_track_id(), SvtxTrack_FastSim::get_truth_track_id(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), SvtxTrack_v1::get_x(), PHG4VtxPoint::get_y(), SvtxTrack_v1::get_y(), PHG4VtxPoint::get_z(), SvtxTrack_v1::get_z(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetVtx(), gflavor, gpx, gpy, gpz, gtrackID, gvt, gvx, gvy, gvz, LogDebug, LogError, nhits, pcax, pcay, pcaz, px, py, pz, reset_variables(), SvtxTrack_v1::size_clusters(), and trackID.
Referenced by process_event().
void PHG4TrackFastSimEval::fill_vertex_tree (PHCompositeNode * topNode) private
Definition at line 282 of file PHG4TrackFastSimEval.cc.
References _eval_tree_vertex, _event, _trackmap, _truth_container, _vertexmap, assert, SvtxVertexMap::begin(), SvtxVertex::begin_tracks(), deltavx, deltavy, deltavz, SvtxTrackMap::end(), SvtxVertexMap::end(), SvtxVertex::end_tracks(), SvtxTrackMap::find(), SvtxVertex::get_error(), SvtxVertex::get_id(), SvtxTrack_FastSim::get_truth_track_id(), PHG4Particle::get_vtx_id(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetVtx(), gtrackID, gvt, gvx, gvy, gvz, LogDebug, LogError, n_from_truth, ntracks, reset_variables(), SvtxVertex::size_tracks(), trackID, vx, vy, and vz.
Referenced by process_event().
int PHG4TrackFastSimEval::GetNodes (PHCompositeNode * topNode) private
Definition at line 421 of file PHG4TrackFastSimEval.cc.
References _event, _trackmap, _trackmapname, _truth_container, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, PHWHERE, and Fun4AllBase::Verbosity().
Referenced by process_event().
int PHG4TrackFastSimEval::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 68 of file PHG4TrackFastSimEval.cc.
References _eval_tree_tracks, _eval_tree_vertex, _h2d_Delta_mom_vs_truth_eta, _h2d_Delta_mom_vs_truth_mom, _outfile_name, charge, dca2d, deltavx, deltavy, deltavz, event, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), gflavor, gpx, gpy, gpz, gtrackID, gvt, gvx, gvy, gvz, n_from_truth, nhits, ntracks, PHTFileServer::open(), pcax, pcay, pcaz, PHWHERE, px, py, pz, trackID, vx, vy, and vz.
int PHG4TrackFastSimEval::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 130 of file PHG4TrackFastSimEval.cc.
References _event, Fun4AllReturnCodes::EVENT_OK, fill_track_tree(), fill_vertex_tree(), GetNodes(), PHWHERE, and Fun4AllBase::Verbosity().
void PHG4TrackFastSimEval::reset_variables ()
Definition at line 379 of file PHG4TrackFastSimEval.cc.
References charge, dca2d, deltavx, deltavy, deltavz, gflavor, gpx, gpy, gpz, gtrackID, gvt, gvx, gvy, gvz, n_from_truth, nhits, ntracks, pcax, pcay, pcaz, px, py, pz, trackID, vx, vy, and vz.
Referenced by fill_track_tree(), fill_vertex_tree(), and PHG4TrackFastSimEval().
void PHG4TrackFastSimEval::set_filename (const char * file) inline
Definition at line 43 of file PHG4TrackFastSimEval.h.
References _outfile_name, and file.
Referenced by FGEM_FastSim_Eval(), Fun4All_G4_Momentum(), and Tracking_Eval().
void PHG4TrackFastSimEval::set_flag (const Flag & flag, const bool & value) inline
Definition at line 57 of file PHG4TrackFastSimEval.h.
References _flags.
Member Data Documentation
TTree* PHG4TrackFastSimEval::_eval_tree_tracks private
Definition at line 88 of file PHG4TrackFastSimEval.h.
Referenced by End(), fill_track_tree(), and Init().
TTree* PHG4TrackFastSimEval::_eval_tree_vertex private
Definition at line 89 of file PHG4TrackFastSimEval.h.
Referenced by End(), fill_vertex_tree(), and Init().
int PHG4TrackFastSimEval::_event private
Definition at line 79 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), GetNodes(), and process_event().
unsigned int PHG4TrackFastSimEval::_flags private
Definition at line 85 of file PHG4TrackFastSimEval.h.
Referenced by set_flag().
TH2D* PHG4TrackFastSimEval::_h2d_Delta_mom_vs_truth_eta private
Definition at line 126 of file PHG4TrackFastSimEval.h.
Referenced by End(), fill_track_tree(), and Init().
TH2D* PHG4TrackFastSimEval::_h2d_Delta_mom_vs_truth_mom private
Definition at line 125 of file PHG4TrackFastSimEval.h.
Referenced by End(), fill_track_tree(), and Init().
std::string PHG4TrackFastSimEval::_outfile_name private
Definition at line 73 of file PHG4TrackFastSimEval.h.
Referenced by End(), Init(), and set_filename().
SvtxTrackMap* PHG4TrackFastSimEval::_trackmap private
Definition at line 130 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), and GetNodes().
std::string PHG4TrackFastSimEval::_trackmapname private
Definition at line 76 of file PHG4TrackFastSimEval.h.
Referenced by GetNodes().
PHG4TruthInfoContainer* PHG4TrackFastSimEval::_truth_container private
Definition at line 129 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), and GetNodes().
SvtxVertexMap* PHG4TrackFastSimEval::_vertexmap private
Definition at line 131 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), and GetNodes().
int PHG4TrackFastSimEval::charge private
Definition at line 104 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::dca2d private
Definition at line 112 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::deltavx private
Definition at line 118 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::deltavy private
Definition at line 119 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::deltavz private
Definition at line 120 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
int PHG4TrackFastSimEval::event private
Definition at line 90 of file PHG4TrackFastSimEval.h.
Referenced by Init().
int PHG4TrackFastSimEval::gflavor private
Definition at line 93 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gpx private
Definition at line 94 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gpy private
Definition at line 95 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gpz private
Definition at line 96 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
int PHG4TrackFastSimEval::gtrackID private
Definition at line 92 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gvt private
Definition at line 100 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gvx private
Definition at line 97 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gvy private
Definition at line 98 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::gvz private
Definition at line 99 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), Init(), and reset_variables().
int PHG4TrackFastSimEval::n_from_truth private
Definition at line 122 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
int PHG4TrackFastSimEval::nhits private
Definition at line 105 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
int PHG4TrackFastSimEval::ntracks private
Definition at line 121 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::pcax private
Definition at line 109 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::pcay private
Definition at line 110 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::pcaz private
Definition at line 111 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::px private
Definition at line 106 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::py private
Definition at line 107 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::pz private
Definition at line 108 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), Init(), and reset_variables().
int PHG4TrackFastSimEval::trackID private
Definition at line 103 of file PHG4TrackFastSimEval.h.
Referenced by fill_track_tree(), fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::vx private
Definition at line 115 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::vy private
Definition at line 116 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
float PHG4TrackFastSimEval::vz private
Definition at line 117 of file PHG4TrackFastSimEval.h.
Referenced by fill_vertex_tree(), Init(), and reset_variables().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h
coresoftware/blob/master/simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc