Analysis Software: HelixHoughSpace Class Reference
HelixHoughSpace Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/HelixHoughSpace.h>
Public Member Functions
virtual ~HelixHoughSpace ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void add_one_zoom (std::vector< unsigned int > &one_zoom)
virtual unsigned int get_max_zoom ()
virtual void print_zoom_profile ()
virtual void print_para_range ()
virtual void set_kappa_min (float kappa_min)
virtual float get_kappa_min () const
virtual void set_kappa_max (float kappa_max)
virtual float get_kappa_max () const
virtual void set_phi_min (float phi_min)
virtual float get_phi_min () const
virtual void set_phi_max (float phi_max)
virtual float get_phi_max () const
virtual void set_d_min (float d_min)
virtual float get_d_min () const
virtual void set_d_max (float d_max)
virtual float get_d_max () const
virtual void set_dzdl_min (float dzdl_min)
virtual float get_dzdl_min () const
virtual void set_dzdl_max (float dzdl_max)
virtual float get_dzdl_max () const
virtual void set_z0_min (float z0_min)
virtual float get_z0_min () const
virtual void set_z0_max (float z0_max)
virtual float get_z0_max () const
virtual unsigned int get_n_kappa_bins (unsigned int zoomlevel) const
virtual unsigned int get_n_phi_bins (unsigned int zoomlevel) const
virtual unsigned int get_n_d_bins (unsigned int zoomlevel) const
virtual unsigned int get_n_dzdl_bins (unsigned int zoomlevel) const
virtual unsigned int get_n_z0_bins (unsigned int zoomlevel) const
virtual float get_kappa_bin_size (unsigned int zoomlevel) const
virtual float get_phi_bin_size (unsigned int zoomlevel) const
virtual float get_d_bin_size (unsigned int zoomlevel) const
virtual float get_dzdl_bin_size (unsigned int zoomlevel) const
virtual float get_z0_bin_size (unsigned int zoomlevel) const
virtual unsigned int get_kappa_bin (unsigned int zoomlevel, float kappa) const
virtual unsigned int get_phi_bin (unsigned int zoomlevel, float phi) const
virtual unsigned int get_d_bin (unsigned int zoomlevel, float d) const
virtual unsigned int get_dzdl_bin (unsigned int zoomlevel, float dzdl) const
virtual unsigned int get_z0_bin (unsigned int zoomlevel, float z0) const
virtual unsigned int get_bin (unsigned int zoomlevel, unsigned int *bins) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
HelixHoughSpace ()
ClassDef (HelixHoughSpace, 1)
Detailed Description
Definition at line 13 of file HelixHoughSpace.h.
Constructor & Destructor Documentation
virtual HelixHoughSpace::~HelixHoughSpace () inline virtual
Definition at line 16 of file HelixHoughSpace.h.
HelixHoughSpace::HelixHoughSpace () inline protected
Definition at line 84 of file HelixHoughSpace.h.
Member Function Documentation
virtual void HelixHoughSpace::add_one_zoom (std::vector< unsigned int > & one_zoom) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 28 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
HelixHoughSpace::ClassDef (HelixHoughSpace , 1) protected
virtual PHObject* HelixHoughSpace::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in HelixHoughSpace_v1.
Definition at line 25 of file HelixHoughSpace.h.
Referenced by CellularAutomaton_v1::set_hough_space(), and HelixHoughBin_v1::set_hough_space().
virtual unsigned int HelixHoughSpace::get_bin (unsigned int zoomlevel, unsigned int * bins) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 81 of file HelixHoughSpace.h.
Referenced by PHInitZVertexing::find_track_candidates_z_init(), PHPatternReco::find_track_candidates_z_init(), HelixHoughBin_v1::get_neighbors_global_bin(), PHInitZVertexing::initialize_houghbin(), PHPatternReco::initialize_houghbin(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual unsigned int HelixHoughSpace::get_d_bin (unsigned int zoomlevel, float d) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 76 of file HelixHoughSpace.h.
virtual float HelixHoughSpace::get_d_bin_size (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 63 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_d_center(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_z(), and PHInitZVertexing::vote_z().
virtual float HelixHoughSpace::get_d_max () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 44 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), PHInitZVertexing::Setup(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual float HelixHoughSpace::get_d_min () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 42 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_d_center(), PHPatternReco::Init(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual unsigned int HelixHoughSpace::get_dzdl_bin (unsigned int zoomlevel, float dzdl) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 77 of file HelixHoughSpace.h.
Referenced by PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual float HelixHoughSpace::get_dzdl_bin_size (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 64 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_dzdl_center(), PHPatternReco::vote_z(), and PHInitZVertexing::vote_z().
virtual float HelixHoughSpace::get_dzdl_max () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 48 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), PHInitZVertexing::Setup(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual float HelixHoughSpace::get_dzdl_min () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 46 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_dzdl_center(), PHPatternReco::Init(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual unsigned int HelixHoughSpace::get_kappa_bin (unsigned int zoomlevel, float kappa) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 74 of file HelixHoughSpace.h.
virtual float HelixHoughSpace::get_kappa_bin_size (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 61 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_kappa_center(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_z(), and PHInitZVertexing::vote_z().
virtual float HelixHoughSpace::get_kappa_max () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 36 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), CellularAutomaton_v1::process_single_triplet(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual float HelixHoughSpace::get_kappa_min () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 34 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_kappa_center(), PHPatternReco::Init(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual unsigned int HelixHoughSpace::get_max_zoom () inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 29 of file HelixHoughSpace.h.
virtual unsigned int HelixHoughSpace::get_n_d_bins (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 57 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_neighbors_global_bin(), PHPatternReco::Init(), HelixHoughBin_v1::set_bins(), HelixHoughBin_v1::set_global_bin(), PHInitZVertexing::set_nbins(), PHPatternReco::set_nbins(), and PHInitZVertexing::Setup().
virtual unsigned int HelixHoughSpace::get_n_dzdl_bins (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 58 of file HelixHoughSpace.h.
Referenced by PHInitZVertexing::find_track_candidates_z_init(), PHPatternReco::find_track_candidates_z_init(), HelixHoughBin_v1::get_neighbors_global_bin(), PHPatternReco::Init(), HelixHoughBin_v1::set_bins(), HelixHoughBin_v1::set_global_bin(), PHInitZVertexing::set_nbins(), PHPatternReco::set_nbins(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual unsigned int HelixHoughSpace::get_n_kappa_bins (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 55 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_neighbors_global_bin(), PHPatternReco::Init(), HelixHoughBin_v1::set_bins(), HelixHoughBin_v1::set_global_bin(), PHInitZVertexing::set_nbins(), PHPatternReco::set_nbins(), and PHInitZVertexing::Setup().
virtual unsigned int HelixHoughSpace::get_n_phi_bins (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 56 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_neighbors_global_bin(), PHPatternReco::Init(), HelixHoughBin_v1::set_bins(), HelixHoughBin_v1::set_global_bin(), PHPatternReco::set_nbins(), PHInitZVertexing::set_nbins(), PHInitZVertexing::Setup(), PHPatternReco::vote_xy(), and PHInitZVertexing::vote_xy().
virtual unsigned int HelixHoughSpace::get_n_z0_bins (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 59 of file HelixHoughSpace.h.
Referenced by PHInitZVertexing::find_track_candidates_z_init(), PHPatternReco::find_track_candidates_z_init(), HelixHoughBin_v1::get_neighbors_global_bin(), PHPatternReco::Init(), HelixHoughBin_v1::set_global_bin(), PHPatternReco::set_nbins(), PHInitZVertexing::set_nbins(), PHInitZVertexing::Setup(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual unsigned int HelixHoughSpace::get_phi_bin (unsigned int zoomlevel, float phi) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 75 of file HelixHoughSpace.h.
Referenced by PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
virtual float HelixHoughSpace::get_phi_bin_size (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 62 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_phi_center(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_z(), and PHInitZVertexing::vote_z().
virtual float HelixHoughSpace::get_phi_max () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 40 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), PHInitZVertexing::Setup(), PHPatternReco::vote_xy(), PHInitZVertexing::vote_xy(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual float HelixHoughSpace::get_phi_min () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 38 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_phi_center(), PHPatternReco::Init(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual unsigned int HelixHoughSpace::get_z0_bin (unsigned int zoomlevel, float z0) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 78 of file HelixHoughSpace.h.
virtual float HelixHoughSpace::get_z0_bin_size (unsigned int zoomlevel) const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 65 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_z0_center(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual float HelixHoughSpace::get_z0_max () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 52 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual float HelixHoughSpace::get_z0_min () const inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 50 of file HelixHoughSpace.h.
Referenced by HelixHoughBin_v1::get_z0_center(), PHPatternReco::Init(), PHInitZVertexing::Setup(), PHInitZVertexing::vote_z_init(), and PHPatternReco::vote_z_init().
virtual void HelixHoughSpace::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in HelixHoughSpace_v1.
Definition at line 20 of file HelixHoughSpace.h.
References os.
virtual int HelixHoughSpace::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in HelixHoughSpace_v1.
Definition at line 24 of file HelixHoughSpace.h.
virtual void HelixHoughSpace::print_para_range () inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 31 of file HelixHoughSpace.h.
virtual void HelixHoughSpace::print_zoom_profile () inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 30 of file HelixHoughSpace.h.
virtual void HelixHoughSpace::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in HelixHoughSpace_v1.
Definition at line 23 of file HelixHoughSpace.h.
virtual void HelixHoughSpace::set_d_max (float d_max) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 43 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_d_min (float d_min) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 41 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_dzdl_max (float dzdl_max) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 47 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_dzdl_min (float dzdl_min) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 45 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_kappa_max (float kappa_max) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 35 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_kappa_min (float kappa_min) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 33 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_phi_max (float phi_max) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 39 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_phi_min (float phi_min) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 37 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_z0_max (float z0_max) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 51 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
virtual void HelixHoughSpace::set_z0_min (float z0_min) inline virtual
Reimplemented in HelixHoughSpace_v1.
Definition at line 49 of file HelixHoughSpace.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/HelixHoughSpace.h