Analysis Software: PHG4ConeDetector Class Reference
PHG4ConeDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeDetector.h>
Public Member Functions
PHG4ConeDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam, const int lyr=0)
constructor
virtual ~PHG4ConeDetector (void)
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
void SetR1 (const G4double min, const G4double max)
set inner and outter radius1
void SetR2 (const G4double min, const G4double max)
set inner and outter radius2
void SetZlength (const G4double a)
set length in Z
void SetPhi (const G4double a, const G4double b)
set phi offset and extention
void SetMaterial (const std::string &mat)
void SetPlaceZ (const G4double place_z)
void SetPlace (const G4double place_x, const G4double place_y, const G4double place_z)
void SetZRot (const G4double z_angle)
virtual G4UserSteppingAction * GetSteppingAction ()
void SetActive (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
volume accessors
bool IsInConeActive (G4VPhysicalVolume *)
bool IsInConeInactive (G4VPhysicalVolume *)
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
G4Material * TrackerMaterial
G4Cons * block_solid
G4LogicalVolume * block_logic
G4VPhysicalVolume * block_physi
G4String material
G4double place_in_x
G4double place_in_y
G4double place_in_z
G4double rMin1
G4double rMax1
G4double rMin2
G4double rMax2
G4double dZ
G4double sPhi
G4double dPhi
G4double z_rot
G4Region * _region
int active
int layer
std::string superdetector
Detailed Description
Definition at line 23 of file PHG4ConeDetector.h.
Constructor & Destructor Documentation
PHG4ConeDetector::PHG4ConeDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam, const int lyr = 0)
constructor
Definition at line 26 of file PHG4ConeDetector.cc.
virtual PHG4ConeDetector::~PHG4ConeDetector (void) inline virtual
destructor
Definition at line 30 of file PHG4ConeDetector.h.
Member Function Documentation
void PHG4ConeDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 67 of file PHG4ConeDetector.cc.
References block_logic, block_physi, block_solid, dPhi, dZ, PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), material, PHG4Detector::OverlapCheck(), place_in_x, place_in_y, place_in_z, rMax1, rMax2, rMin1, rMin2, PHG4Utils::SetColour(), PHG4Subsystem::SetLogicalVolume(), sPhi, TrackerMaterial, and z_rot.
int PHG4ConeDetector::get_Layer () const inline
Definition at line 89 of file PHG4ConeDetector.h.
References layer.
Referenced by PHG4ConeSteppingAction::UserSteppingAction().
virtual G4UserSteppingAction* PHG4ConeDetector::GetSteppingAction (void) inline virtual
Reimplemented from PHG4Detector.
Definition at line 79 of file PHG4ConeDetector.h.
References _region.
bool PHG4ConeDetector::IsInConeActive (G4VPhysicalVolume * volume)
Definition at line 51 of file PHG4ConeDetector.cc.
References block_physi.
Referenced by PHG4ConeRegionSteppingAction::UserSteppingAction(), and PHG4ConeSteppingAction::UserSteppingAction().
bool PHG4ConeDetector::IsInConeInactive (G4VPhysicalVolume * volume)
Definition at line 61 of file PHG4ConeDetector.cc.
void PHG4ConeDetector::SetActive (const int i = 1) inline
Definition at line 86 of file PHG4ConeDetector.h.
References active, and i.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetMaterial (const std::string & mat) inline
Definition at line 70 of file PHG4ConeDetector.h.
References material.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetPhi (const G4double a, const G4double b) inline
set phi offset and extention
Definition at line 64 of file PHG4ConeDetector.h.
References dPhi, g, and sPhi.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetPlace (const G4double place_x, const G4double place_y, const G4double place_z) inline
Definition at line 72 of file PHG4ConeDetector.h.
References place_in_x, place_in_y, and place_in_z.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetPlaceZ (const G4double place_z) inline
Definition at line 71 of file PHG4ConeDetector.h.
References place_in_z.
void PHG4ConeDetector::SetR1 (const G4double min, const G4double max) inline
set inner and outter radius1
Definition at line 44 of file PHG4ConeDetector.h.
References rMax1, and rMin1.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetR2 (const G4double min, const G4double max) inline
set inner and outter radius2
Definition at line 51 of file PHG4ConeDetector.h.
References rMax2, and rMin2.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetZlength (const G4double a) inline
set length in Z
Definition at line 58 of file PHG4ConeDetector.h.
References dZ.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SetZRot (const G4double z_angle) inline
Definition at line 78 of file PHG4ConeDetector.h.
References z_rot.
Referenced by PHG4ConeSubsystem::Init().
void PHG4ConeDetector::SuperDetector (const std::string & name) inline
Definition at line 87 of file PHG4ConeDetector.h.
References name, and superdetector.
Referenced by PHG4ConeSubsystem::Init(), and PHG4ConeSteppingAction::SetInterfacePointers().
const std::string PHG4ConeDetector::SuperDetector () const inline
Definition at line 88 of file PHG4ConeDetector.h.
References superdetector.
Member Data Documentation
G4Region* PHG4ConeDetector::_region private
Definition at line 111 of file PHG4ConeDetector.h.
Referenced by GetSteppingAction().
int PHG4ConeDetector::active private
Definition at line 112 of file PHG4ConeDetector.h.
Referenced by SetActive().
G4LogicalVolume* PHG4ConeDetector::block_logic private
Definition at line 95 of file PHG4ConeDetector.h.
Referenced by ConstructMe().
G4VPhysicalVolume* PHG4ConeDetector::block_physi private
Definition at line 96 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and IsInConeActive().
G4Cons* PHG4ConeDetector::block_solid private
Definition at line 94 of file PHG4ConeDetector.h.
Referenced by ConstructMe().
G4double PHG4ConeDetector::dPhi private
Definition at line 108 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetPhi().
G4double PHG4ConeDetector::dZ private
Definition at line 106 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetZlength().
int PHG4ConeDetector::layer private
Definition at line 113 of file PHG4ConeDetector.h.
Referenced by get_Layer().
G4String PHG4ConeDetector::material private
Definition at line 98 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetMaterial().
G4double PHG4ConeDetector::place_in_x private
Definition at line 99 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetPlace().
G4double PHG4ConeDetector::place_in_y private
Definition at line 100 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetPlace().
G4double PHG4ConeDetector::place_in_z private
Definition at line 101 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), SetPlace(), and SetPlaceZ().
G4double PHG4ConeDetector::rMax1 private
Definition at line 103 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetR1().
G4double PHG4ConeDetector::rMax2 private
Definition at line 105 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetR2().
G4double PHG4ConeDetector::rMin1 private
Definition at line 102 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetR1().
G4double PHG4ConeDetector::rMin2 private
Definition at line 104 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetR2().
G4double PHG4ConeDetector::sPhi private
Definition at line 107 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetPhi().
std::string PHG4ConeDetector::superdetector private
Definition at line 114 of file PHG4ConeDetector.h.
Referenced by SuperDetector().
G4Material* PHG4ConeDetector::TrackerMaterial private
Definition at line 92 of file PHG4ConeDetector.h.
Referenced by ConstructMe().
G4double PHG4ConeDetector::z_rot private
Definition at line 109 of file PHG4ConeDetector.h.
Referenced by ConstructMe(), and SetZRot().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeDetector.cc