Analysis Software: analysis/blob/master/EMCal-analysis/macro/DrawEcal_Likelihood_Sum.C File Reference
DrawEcal_Likelihood_Sum.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawEcal_Likelihood_Sum (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/embedding/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0")
void RejectionCurvePos (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", TString ll_config="Edep_LL_Distribution_eval_sample", TString hist_name="hll_edep_diff", const double min_eff=0.85)
void RejectionCurve (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", TString ll_config="Edep_LL_Distribution_eval_sample", TString hist_name="hll_edep_diff", const double min_eff=0.85)
void RejectionCurve_PiProton (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", TString ll_config="Edep_LL_Distribution_eval_sample", TString hist_name="hll_edep_diff", const double min_eff=0.85)
void RejectionCurve_PiProtonPos (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", TString ll_config="Edep_LL_Distribution_eval_sample", TString hist_name="hll_edep_diff", const double min_eff=0.85)
void RejectionCurve_RejMethodComparison (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", const double min_eff=0.85)
void RejectionCurve_ppSummary (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", const double min_eff=0.85)
void RejectionCurve_ppSummaryPos (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", const double min_eff=0.85)
void RejectionCurve_AuAuSummary (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/embedding/emcstudies/pidstudies/spacal2d/fieldmap/", TString label="2-D Proj. SPACAL, e^{-} VS h^{-} in Au+Au 10%C", const double min_eff=0.6)
void RejectionCurve_AuAuSummaryPos (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/embedding/emcstudies/pidstudies/spacal2d/fieldmap/", TString label="2-D Proj. SPACAL, e^{-} VS h^{+} in Au+Au 10%C", const double min_eff=0.6)
TGraph * rejection_ratio (TFile *f_2d, TFile *f_1d, TString graph_name)
void RejectionCurve_AuAuSummary_Compare ()
void RejectionCurve_AuAuSummary_Compare2 ()
void RejectionCurve_RejMethodComparison_AntiProton (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", const double min_eff=0.85)
void RejectionCurve_PIDComparison (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0", const double min_eff=0.85)
TGraphErrors * ExtractRejCurve (TString base_dir="../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config="eta0_4GeV", TString ll_config="EP_LL_Distribution_ll_sample", TString hist_name="hll_ep_diff", TString signal="e-", TString background="pi-")
TGraphErrors * MergeRejCurve (TGraphErrors *ge1, const double weight1, TGraphErrors *ge2, const double weight2, TGraphErrors *ge3=NULL, const double weight3=0)
double GetHPiRatio (const double pt, TString hadron, TString collision)
Variables
TFile * _file0 = NULL
TTree * T = NULL
TString cuts = ""
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file DrawEcal_Likelihood_Sum.C.
Function Documentation
void DrawEcal_Likelihood_Sum (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/embedding/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0")
Definition at line 26 of file DrawEcal_Likelihood_Sum.C.
References RejectionCurve_AuAuSummaryPos(), and SetOKStyle().
TGraphErrors* ExtractRejCurve (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0_4GeV", TString ll_config = "EP_LL_Distribution_ll_sample", TString hist_name = "hll_ep_diff", TString signal = "e-", TString background = "pi-")
Definition at line 1907 of file DrawEcal_Likelihood_Sum.C.
References A, assert, i, signal(), and z.
Referenced by RejectionCurve(), RejectionCurve_AuAuSummary(), RejectionCurve_AuAuSummaryPos(), RejectionCurve_PIDComparison(), RejectionCurve_PiProton(), RejectionCurve_PiProtonPos(), RejectionCurve_ppSummary(), RejectionCurve_ppSummaryPos(), RejectionCurve_RejMethodComparison(), RejectionCurve_RejMethodComparison_AntiProton(), and RejectionCurvePos().
double GetHPiRatio (const double pt, TString hadron, TString collision)
Definition at line 2080 of file DrawEcal_Likelihood_Sum.C.
References assert, and ratio.
Referenced by RejectionCurve_AuAuSummary(), RejectionCurve_AuAuSummaryPos(), RejectionCurve_ppSummary(), and RejectionCurve_ppSummaryPos().
TGraphErrors* MergeRejCurve (TGraphErrors * ge1, const double weight1, TGraphErrors * ge2, const double weight2, TGraphErrors * ge3 = NULL, const double weight3 = 0)
Definition at line 2015 of file DrawEcal_Likelihood_Sum.C.
References assert, and i.
Referenced by RejectionCurve_AuAuSummary(), RejectionCurve_AuAuSummaryPos(), RejectionCurve_ppSummary(), and RejectionCurve_ppSummaryPos().
TGraph* rejection_ratio (TFile * f_2d, TFile * f_1d, TString graph_name)
Definition at line 1382 of file DrawEcal_Likelihood_Sum.C.
References assert, i, and x.
Referenced by RejectionCurve_AuAuSummary_Compare(), and RejectionCurve_AuAuSummary_Compare2().
void RejectionCurve (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", TString ll_config = "Edep_LL_Distribution_eval_sample", TString hist_name = "hll_edep_diff", const double min_eff = 0.85)
Definition at line 207 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), and SaveCanvas().
void RejectionCurve_AuAuSummary (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/embedding/emcstudies/pidstudies/spacal2d/fieldmap/", TString label = "2-D Proj. SPACAL, e^{-} VS h^{-} in Au+Au 10%C", const double min_eff = 0.6)
Definition at line 1031 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), GetHPiRatio(), MergeRejCurve(), SaveCanvas(), and text().
void RejectionCurve_AuAuSummary_Compare ()
Definition at line 1432 of file DrawEcal_Likelihood_Sum.C.
References assert, name, rejection_ratio(), SaveCanvas(), and text().
void RejectionCurve_AuAuSummary_Compare2 ()
Definition at line 1531 of file DrawEcal_Likelihood_Sum.C.
References assert, name, rejection_ratio(), SaveCanvas(), and text().
void RejectionCurve_AuAuSummaryPos (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/embedding/emcstudies/pidstudies/spacal2d/fieldmap/", TString label = "2-D Proj. SPACAL, e^{-} VS h^{+} in Au+Au 10%C", const double min_eff = 0.6)
Definition at line 1207 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), GetHPiRatio(), MergeRejCurve(), SaveCanvas(), and text().
Referenced by DrawEcal_Likelihood_Sum().
void RejectionCurve_PIDComparison (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", const double min_eff = 0.85)
Definition at line 1768 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), SaveCanvas(), and text().
void RejectionCurve_PiProton (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", TString ll_config = "Edep_LL_Distribution_eval_sample", TString hist_name = "hll_edep_diff", const double min_eff = 0.85)
Definition at line 321 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), and SaveCanvas().
void RejectionCurve_PiProtonPos (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", TString ll_config = "Edep_LL_Distribution_eval_sample", TString hist_name = "hll_edep_diff", const double min_eff = 0.85)
Definition at line 436 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), and SaveCanvas().
void RejectionCurve_ppSummary (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", const double min_eff = 0.85)
Definition at line 691 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), GetHPiRatio(), MergeRejCurve(), SaveCanvas(), and text().
void RejectionCurve_ppSummaryPos (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", const double min_eff = 0.85)
Definition at line 861 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), GetHPiRatio(), MergeRejCurve(), SaveCanvas(), and text().
void RejectionCurve_RejMethodComparison (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", const double min_eff = 0.85)
Definition at line 552 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), SaveCanvas(), and text().
void RejectionCurve_RejMethodComparison_AntiProton (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", const double min_eff = 0.85)
Definition at line 1628 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), SaveCanvas(), and text().
void RejectionCurvePos (TString base_dir = "../../sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString kine_config = "eta0", TString ll_config = "Edep_LL_Distribution_eval_sample", TString hist_name = "hll_edep_diff", const double min_eff = 0.85)
Definition at line 92 of file DrawEcal_Likelihood_Sum.C.
References ExtractRejCurve(), and SaveCanvas().
Variable Documentation
TFile* _file0 = NULL
Definition at line 21 of file DrawEcal_Likelihood_Sum.C.
TString cuts = ""
Definition at line 23 of file DrawEcal_Likelihood_Sum.C.
TTree* T = NULL
Definition at line 22 of file DrawEcal_Likelihood_Sum.C.