Analysis Software: RawTowerDeadMap Class Reference
RawTowerDeadMap Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerDeadMap.h>
Public Types
typedef std::set
< RawTowerDefs::keytype > Map
Public Member Functions
virtual ~RawTowerDeadMap ()
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
virtual void setCalorimeterID (RawTowerDefs::CalorimeterId caloid)
virtual RawTowerDefs::CalorimeterId getCalorimeterID ()
virtual void addDeadTower (const unsigned int ieta, const unsigned int iphi)
virtual void addDeadTower (RawTowerDefs::keytype key)
virtual bool isDeadTower (RawTowerDefs::keytype key)
virtual bool isDeadTower (const unsigned int ieta, const unsigned int iphi)
virtual const Map & getDeadTowers (void) const
return all towers
virtual Map & getDeadTowers (void)
virtual unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawTowerDeadMap (RawTowerDefs::CalorimeterId caloid=RawTowerDefs::NONE)
Detailed Description
Definition at line 11 of file RawTowerDeadMap.h.
Member Typedef Documentation
typedef std::set<RawTowerDefs::keytype> RawTowerDeadMap::Map
Definition at line 14 of file RawTowerDeadMap.h.
Constructor & Destructor Documentation
virtual RawTowerDeadMap::~RawTowerDeadMap () inline virtual
Definition at line 16 of file RawTowerDeadMap.h.
RawTowerDeadMap::RawTowerDeadMap (RawTowerDefs::CalorimeterId caloid = RawTowerDefs::NONE) inline protected
Definition at line 36 of file RawTowerDeadMap.h.
Member Function Documentation
virtual void RawTowerDeadMap::addDeadTower (const unsigned int ieta, const unsigned int iphi) virtual
Reimplemented in RawTowerDeadMapv1.
Referenced by RawTowerDeadMapLoader::InitRun().
void RawTowerDeadMap::addDeadTower (RawTowerDefs::keytype key) virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 25 of file RawTowerDeadMap.cc.
virtual RawTowerDefs::CalorimeterId RawTowerDeadMap::getCalorimeterID () inline virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 23 of file RawTowerDeadMap.h.
References RawTowerDefs::NONE.
const RawTowerDeadMap::Map & RawTowerDeadMap::getDeadTowers (void) const virtual
return all towers
Reimplemented in RawTowerDeadMapv1.
Definition at line 8 of file RawTowerDeadMap.cc.
Referenced by RawTowerDeadTowerInterp::process_event().
RawTowerDeadMap::Map & RawTowerDeadMap::getDeadTowers (void) virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 15 of file RawTowerDeadMap.cc.
void RawTowerDeadMap::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTowerDeadMapv1.
Definition at line 48 of file RawTowerDeadMap.cc.
Referenced by RawTowerDeadTowerInterp::CreateNodes(), RawTowerDigitizer::CreateNodes(), RawClusterDeadAreaMask::CreateNodeTree(), and RawTowerDeadMapLoader::InitRun().
bool RawTowerDeadMap::isDeadTower (RawTowerDefs::keytype key) virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 29 of file RawTowerDeadMap.cc.
Referenced by RawClusterDeadAreaMask::process_event(), RawTowerDeadTowerInterp::process_event(), and RawTowerDigitizer::process_event().
bool RawTowerDeadMap::isDeadTower (const unsigned int ieta, const unsigned int iphi) virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 34 of file RawTowerDeadMap.cc.
int RawTowerDeadMap::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in RawTowerDeadMapv1.
Definition at line 39 of file RawTowerDeadMap.cc.
void RawTowerDeadMap::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawTowerDeadMapv1.
Definition at line 44 of file RawTowerDeadMap.cc.
virtual void RawTowerDeadMap::setCalorimeterID (RawTowerDefs::CalorimeterId caloid) inline virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 22 of file RawTowerDeadMap.h.
virtual unsigned int RawTowerDeadMap::size (void) const inline virtual
Reimplemented in RawTowerDeadMapv1.
Definition at line 33 of file RawTowerDeadMap.h.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerDeadMap.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerDeadMap.cc