Analysis Software: PHTimeStamp Class Reference
PHTimeStamp Class Reference
#include <coresoftware/blob/master/offline/framework/phool/PHTimeStamp.h>
Public Member Functions
PHTimeStamp ()
PHTimeStamp (const int, const int, const int, const int, const int, const int, const int=0)
PHTimeStamp (const time_t)
void setBinTics (const phtime_t t)
virtual ~PHTimeStamp ()
void set (const int, const int, const int, const int, const int, const int, const int=0)
void set (const char *)
void setToSystemTime ()
void setToFarFuture ()
phtime_t getBinaryTime () const
time_t getTics () const
void setTics (const time_t)
int isInRange (const PHTimeStamp &, const PHTimeStamp &)
void print ()
int operator== (const PHTimeStamp &) const
int operator!= (const PHTimeStamp &) const
int operator> (const PHTimeStamp &) const
int operator>= (const PHTimeStamp &) const
int operator< (const PHTimeStamp &) const
int operator<= (const PHTimeStamp &) const
PHTimeStamp operator+= (time_t)
PHTimeStamp operator-= (time_t)
char * formatTimeString () const
void print () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Static Public Attributes
static const unsigned long long PHFarFuture = ULLONG_MAX
Protected Attributes
phtime_t binaryTime
Private Member Functions
phtime_t ticsToBinaryTime (time_t) const
time_t binaryTimeToTics (phtime_t) const
Detailed Description
Definition at line 20 of file PHTimeStamp.h.
Constructor & Destructor Documentation
PHTimeStamp::PHTimeStamp ()
Definition at line 29 of file PHTimeStamp.cc.
PHTimeStamp::PHTimeStamp (const int year, const int month, const int day, const int hour, const int minute, const int second, const int fraction = 0)
Definition at line 36 of file PHTimeStamp.cc.
PHTimeStamp::PHTimeStamp (const time_t t)
Definition at line 42 of file PHTimeStamp.cc.
virtual PHTimeStamp::~PHTimeStamp () inline virtual
Definition at line 31 of file PHTimeStamp.h.
Member Function Documentation
time_t PHTimeStamp::binaryTimeToTics (phtime_t bt) const private
Definition at line 107 of file PHTimeStamp.cc.
References ticFactor, and ticOffset.
char * PHTimeStamp::formatTimeString () const
Definition at line 171 of file PHTimeStamp.cc.
References line.
phtime_t PHTimeStamp::getBinaryTime () const inline
Definition at line 40 of file PHTimeStamp.h.
References binaryTime.
Referenced by isInRange(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
time_t PHTimeStamp::getTics () const
Definition at line 87 of file PHTimeStamp.cc.
Referenced by PgPostBankBackupManager::CleanTable(), PgPostCalBankIterator::ValPeriod::end(), PgPostBankManager::fetchBank(), PgPostBankBackupStorage::BankHeader::get_id_string(), RunToTimePg::getRunNumber(), operator-(), operator<<(), PgPostBankManager::SetMaxInsertTime(), PgPostCalBankIterator::ValPeriod::start(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), and PHParameters::WriteToFile().
int PHTimeStamp::isInRange (const PHTimeStamp & t1, const PHTimeStamp & t2)
Definition at line 112 of file PHTimeStamp.cc.
References getBinaryTime().
int PHTimeStamp::operator!= (const PHTimeStamp & t) const
Definition at line 130 of file PHTimeStamp.cc.
References getBinaryTime().
PHTimeStamp PHTimeStamp::operator+= (time_t t)
Definition at line 155 of file PHTimeStamp.cc.
References ticFactor.
PHTimeStamp PHTimeStamp::operator-= (time_t t)
Definition at line 161 of file PHTimeStamp.cc.
References ticFactor.
int PHTimeStamp::operator< (const PHTimeStamp & t) const
Definition at line 140 of file PHTimeStamp.cc.
References getBinaryTime().
int PHTimeStamp::operator<= (const PHTimeStamp & t) const
Definition at line 150 of file PHTimeStamp.cc.
References getBinaryTime().
int PHTimeStamp::operator== (const PHTimeStamp & t) const
Definition at line 125 of file PHTimeStamp.cc.
References getBinaryTime().
int PHTimeStamp::operator> (const PHTimeStamp & t) const
Definition at line 135 of file PHTimeStamp.cc.
References getBinaryTime().
int PHTimeStamp::operator>= (const PHTimeStamp & t) const
Definition at line 145 of file PHTimeStamp.cc.
References getBinaryTime().
void PHTimeStamp::print ()
Definition at line 117 of file PHTimeStamp.cc.
Referenced by Fun4AllServer::BeginRun(), Fun4AllServer::BeginRunTimeStamp(), and Fun4AllServer::setRun().
void PHTimeStamp::print () const
Definition at line 167 of file PHTimeStamp.cc.
void PHTimeStamp::set (const int year, const int month, const int day, const int hour, const int minute, const int second, const int fraction = 0)
Definition at line 48 of file PHTimeStamp.cc.
Referenced by operator>>().
void PHTimeStamp::set (const char * timeString)
Definition at line 73 of file PHTimeStamp.cc.
References strptime().
void PHTimeStamp::setBinTics (const phtime_t t)
Definition at line 97 of file PHTimeStamp.cc.
References t.
void PHTimeStamp::setTics (const time_t tics)
Definition at line 92 of file PHTimeStamp.cc.
Referenced by setToFarFuture().
void PHTimeStamp::setToFarFuture () inline
Definition at line 39 of file PHTimeStamp.h.
References PHFarFuture, and setTics().
void PHTimeStamp::setToSystemTime ()
Definition at line 82 of file PHTimeStamp.cc.
phtime_t PHTimeStamp::ticsToBinaryTime (time_t tics) const private
Definition at line 102 of file PHTimeStamp.cc.
References ticFactor, and ticOffset.
Member Data Documentation
phtime_t PHTimeStamp::binaryTime protected
Definition at line 65 of file PHTimeStamp.h.
Referenced by getBinaryTime().
const unsigned long long PHTimeStamp::PHFarFuture = ULLONG_MAX static
Definition at line 23 of file PHTimeStamp.h.
Referenced by setToFarFuture().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHTimeStamp.h
coresoftware/blob/master/offline/framework/phool/PHTimeStamp.cc