Analysis Software: half Class Reference
half Class Reference
#include <coresoftware/blob/master/offline/packages/Half/half.h>
Classes
union uif
Public Member Functions
half ()
half (float f)
operator float () const
half operator- () const
half & operator= (half h)
half & operator= (float f)
half & operator+= (half h)
half & operator+= (float f)
half & operator-= (half h)
half & operator-= (float f)
half & operator*= (half h)
half & operator*= (float f)
half & operator/= (half h)
half & operator/= (float f)
half round (unsigned int n) const
bool isFinite () const
bool isNormalized () const
bool isDenormalized () const
bool isZero () const
bool isNan () const
bool isInfinity () const
bool isNegative () const
unsigned short bits () const
void setBits (unsigned short bits)
Static Public Member Functions
static half posInf ()
static half negInf ()
static half qNan ()
static half sNan ()
Static Private Member Functions
static short convert (int i)
static float overflow ()
Private Attributes
unsigned short _h
Static Private Attributes
static HALF_EXPORT_CONST uif _toFloat [1<< 16]
static HALF_EXPORT_CONST
unsigned short _eLut [1<< 9]
Detailed Description
Definition at line 102 of file half.h.
Constructor & Destructor Documentation
half::half () inline
Definition at line 427 of file half.h.
Referenced by operator*=(), operator+=(), operator-=(), operator/=(), and operator=().
half::half (float f) inline
Definition at line 438 of file half.h.
References _eLut, _h, convert(), half::uif::f, half::uif::i, and x.
Member Function Documentation
unsigned short half::bits () const inline
Definition at line 754 of file half.h.
References _h.
Referenced by HepMCCompress::FloatToInt(), VariableArrayUtils::FloatToShortBits(), halfFunction< T >::operator()(), and setBits().
static short half::convert (int i) static private
Referenced by half().
bool half::isDenormalized () const inline
Definition at line 677 of file half.h.
References _h.
bool half::isFinite () const inline
Definition at line 661 of file half.h.
References _h.
bool half::isInfinity () const inline
Definition at line 702 of file half.h.
References _h.
Referenced by halfFunction< T >::halfFunction().
bool half::isNan () const inline
Definition at line 693 of file half.h.
References _h.
Referenced by halfFunction< T >::halfFunction().
bool half::isNegative () const inline
Definition at line 711 of file half.h.
References _h.
Referenced by halfFunction< T >::halfFunction().
bool half::isNormalized () const inline
Definition at line 669 of file half.h.
References _h.
bool half::isZero () const inline
Definition at line 686 of file half.h.
References _h.
half half::negInf () inline static
Definition at line 727 of file half.h.
References _h, and SVM_v1::h.
half::operator float () const inline
Definition at line 502 of file half.h.
half & half::operator*= (half h) inline
Definition at line 629 of file half.h.
References half().
half & half::operator*= (float f) inline
Definition at line 637 of file half.h.
References half().
half & half::operator+= (half h) inline
Definition at line 597 of file half.h.
References half().
half & half::operator+= (float f) inline
Definition at line 605 of file half.h.
References half().
half half::operator- () const inline
Definition at line 572 of file half.h.
References _h, and SVM_v1::h.
half & half::operator-= (half h) inline
Definition at line 613 of file half.h.
References half().
half & half::operator-= (float f) inline
Definition at line 621 of file half.h.
References half().
half & half::operator/= (half h) inline
Definition at line 645 of file half.h.
References half().
half & half::operator/= (float f) inline
Definition at line 653 of file half.h.
References half().
half & half::operator= (half h) inline
Definition at line 581 of file half.h.
References _h.
half & half::operator= (float f) inline
Definition at line 589 of file half.h.
References half().
static float half::overflow () static private
half half::posInf () inline static
Definition at line 718 of file half.h.
References _h, and SVM_v1::h.
Referenced by std::numeric_limits< half >::infinity().
half half::qNan () inline static
Definition at line 736 of file half.h.
References _h, and SVM_v1::h.
Referenced by std::numeric_limits< half >::quiet_NaN().
half half::round (unsigned int n) const inline
Definition at line 513 of file half.h.
References _h, SVM_v1::h, n, and s.
void half::setBits (unsigned short bits) inline
Definition at line 761 of file half.h.
References _h, and bits().
Referenced by halfFunction< T >::halfFunction(), and VariableArrayUtils::ShortBitsToFloat().
half half::sNan () inline static
Definition at line 745 of file half.h.
References _h, and SVM_v1::h.
Referenced by std::numeric_limits< half >::signaling_NaN().
Member Data Documentation
HALF_EXPORT_CONST unsigned short half::_eLut[1<< 9] static private
Definition at line 231 of file half.h.
Referenced by half().
unsigned short half::_h private
Definition at line 228 of file half.h.
Referenced by bits(), half(), isDenormalized(), isFinite(), isInfinity(), isNan(), isNegative(), isNormalized(), isZero(), negInf(), operator-(), operator=(), posInf(), qNan(), round(), setBits(), and sNan().
HALF_EXPORT_CONST uif half::_toFloat[1<< 16] static private
Definition at line 230 of file half.h.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/Half/half.h