Analysis Software: sPHENIXSeedFinder Class Reference
sPHENIXSeedFinder Class Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXSeedFinder.h>
Public Member Functions
sPHENIXSeedFinder (unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, HelixResolution &min_resolution, HelixResolution &max_resolution, HelixRange &range, std::vector< float > &material, std::vector< float > &radius, float Bfield)
sPHENIXSeedFinder (std::vector< std::vector< unsigned int > > &zoom_profile, unsigned int minzoom, HelixRange &range, std::vector< float > &material, std::vector< float > &radius, float Bfield, bool parallel=false, unsigned int num_threads=1)
virtual ~sPHENIXSeedFinder ()
void finalize (std::vector< SimpleTrack3D > &input, std::vector< SimpleTrack3D > &output)
void findTracks (std::vector< SimpleHit3D > &hits, std::vector< SimpleTrack3D > &tracks, const HelixRange &range)
void findTracksBySegments (std::vector< SimpleHit3D > &hits, std::vector< SimpleTrack3D > &tracks, const HelixRange &range)
void initEvent (std::vector< SimpleHit3D > &hits, unsigned int min_hits)
void initSeeding (std::vector< SimpleTrack3D > &seeds)
void clear ()
void findHelicesParallel (std::vector< SimpleHit3D > &hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks)
void findHelicesParallelOneHelicity (std::vector< SimpleHit3D > &hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks)
float dcaToVertexXY (SimpleTrack3D &track, float vx, float vy)
bool breakRecursion (const std::vector< SimpleHit3D > &hits, const HelixRange &range)
float phiError (SimpleHit3D &hit, float min_k, float max_k, float min_d, float max_d, float min_z0, float max_z0, float min_dzdl, float max_dzdl, bool pairvoting=false)
float dzdlError (SimpleHit3D &hit, float min_k, float max_k, float min_d, float max_d, float min_z0, float max_z0, float min_dzdl, float max_dzdl, bool pairvoting=false)
void setVerbosity (int v)
void setCutOnDca (bool dcut)
void setDcaCut (float dcut)
void setVertex (float vx, float vy, float vz)
void setRejectGhosts (bool rg)
std::vector< float > & getIsolation ()
void calculateKappaTangents (float *x1_a, float *y1_a, float *z1_a, float *x2_a, float *y2_a, float *z2_a, float *x3_a, float *y3_a, float *z3_a, float *dx1_a, float *dy1_a, float *dz1_a, float *dx2_a, float *dy2_a, float *dz2_a, float *dx3_a, float *dy3_a, float *dz3_a, float *kappa_a, float *dkappa_a, float *ux_mid_a, float *uy_mid_a, float *ux_end_a, float *uy_end_a, float *dzdl_1_a, float *dzdl_2_a, float *ddzdl_1_a, float *ddzdl_2_a, float sinang_cut, float cosang_diff_inv, float *cur_kappa_a, float *cur_dkappa_a, float *cur_ux_a, float *cur_uy_a, float *cur_chi2_a, float *chi2_a)
void projectToLayer (SimpleTrack3D &seed, unsigned int layer, float &x, float &y, float &z)
void setRangeFromSeed (HelixRange &range, SimpleTrack3D &seed)
void pairRejection (std::vector< SimpleTrack3D > &input, std::vector< SimpleTrack3D > &output, std::vector< bool > &usetrack, std::vector< float > &next_best_chi2)
void tripletRejection (std::vector< SimpleTrack3D > &input, std::vector< SimpleTrack3D > &output, std::vector< bool > &usetrack, std::vector< float > &next_best_chi2)
bool seedWasUsed (unsigned int seed_index)
void setSeparateByHelicity (bool sbh)
void requireLayers (unsigned int nl)
virtual void setMaxHitsPairs (unsigned int mhp)
void setBinScale (float b_scl)
void setZBinScale (float b_scl)
void setRemoveHits (bool rh)
void setSeedLayer (int sl)
void setNLayers (unsigned int n)
void setFastChi2Cut (float par0, float par1, float max)
void setChi2Cut (float c)
void setChi2RemovalCut (float c)
void setNRemovalHits (unsigned int n)
void setCosAngleCut (float cut)
void setCellularAutomatonChi2Cut (float cut)
void setThread ()
void initSplitting (std::vector< SimpleHit3D > &hits, unsigned int min_hits, unsigned int max_hits)
void setHitErrorScale (unsigned int layer, float scale)
Public Member Functions inherited from HelixHough
HelixHough (unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, HelixResolution &min_resolution, HelixResolution &max_resolution, HelixRange &range)
HelixHough (std::vector< std::vector< unsigned int > > &zoom_profile, unsigned int minzoom, HelixRange &range)
virtual ~HelixHough ()
void initHelixHough (unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, HelixResolution &min_resolution, HelixResolution &max_resolution, HelixRange &range)
void findHelices (std::vector< SimpleHit3D > &hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks=0)
void findHelices (unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks, unsigned int zoomlevel)
void findSeededHelices (std::vector< SimpleTrack3D > &seeds, std::vector< SimpleHit3D > &hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks=0)
void findSeededHelices_run (std::vector< SimpleTrack3D > &seeds, std::vector< SimpleHit3D > &hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks=0)
void findSeededHelices (unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks, unsigned int zoomlevel)
void vote (unsigned int zoomlevel)
void setPrintTimings (bool pt)
virtual void findSeededTracks (std::vector< SimpleTrack3D > &seeds, std::vector< SimpleHit3D > &hits, std::vector< SimpleTrack3D > &tracks, const HelixRange &range)
virtual void setOnlyOneHelicity (bool ooh)
void setHelicity (bool hel)
virtual void setTopRange (HelixRange &tr)
void splitIntoBins (unsigned int min_hits, unsigned int max_hits, std::vector< HelixRange > &ranges, std::vector< std::vector< SimpleHit3D > > &split_hits, unsigned int zoomlevel)
virtual void setStartZoom (unsigned int sz)
void setClusterStartBin (unsigned int csb)
void setSeedStates (std::vector< HelixKalmanState > &states)
std::vector< HelixKalmanState > & getKalmanStates ()
void setLayersAtATime (unsigned int l)
void setSmoothBack (bool sb)
void setCullInputHits (bool cih)
void setIterateClustering (bool icl)
Static Public Member Functions
static float fitTrack (SimpleTrack3D &track)
static float fitTrack (SimpleTrack3D &track, std::vector< float > &chi2_hit)
static void calculateKappaTangents (float *x1_a, float *y1_a, float *z1_a, float *x2_a, float *y2_a, float *z2_a, float *x3_a, float *y3_a, float *z3_a, float *dx1_a, float *dy1_a, float *dz1_a, float *dx2_a, float *dy2_a, float *dz2_a, float *dx3_a, float *dy3_a, float *dz3_a, float *kappa_a, float *dkappa_a, float *ux_mid_a, float *uy_mid_a, float *ux_end_a, float *uy_end_a, float *dzdl_1_a, float *dzdl_2_a, float *ddzdl_1_a, float *ddzdl_2_a)
Static Public Member Functions inherited from HelixHough
static void phiRange_sse (float *hit_x, float *hit_y, float *min_d, float *max_d, float *min_k, float *max_k, float *min_phi_1, float *max_phi_1, float *min_phi_2, float *max_phi_2)
static void phiRange_sse (float *hit_x, float *hit_y, float *min_d, float *max_d, float *min_k, float *max_k, float *min_phi, float *max_phi, float hel, __m128 &phi_3_out, __m128 &phi_4_out)
static void phiRange_sse (float *hit_x, float *hit_y, float *min_d, float *max_d, float *max_k, float *min_phi, float *max_phi, float hel, __m128 &phi_3, __m128 &phi_4, __m128 &phi_3_out, __m128 &phi_4_out)
static void dzdlRange_sse (float *x_a, float *y_a, float *z_a, float cosphi1, float sinphi1, float cosphi2, float sinphi2, float min_k, float max_k, float min_d, float max_d, float *min_z0, float *max_z0, float *min_dzdl_a, float *max_dzdl_a)
static void phiRange_sse (float *hit_x, float *hit_y, float *min_d, float *max_d, float *min_k, float *max_k, float *min_phi, float *max_phi, float *min_phi_2, float *max_phi_2, float hel, __m128 &phi_3_out, __m128 &phi_4_out, float *hit_x_2, float *hit_y_2, __m128 &phi_3_out_2, __m128 &phi_4_out_2)
static void phiRange_sse (float *hit_x, float *hit_y, float *min_d, float *max_d, float *min_k, float *max_k, float *min_phi, float *max_phi, float *min_phi_2, float *max_phi_2, float hel, __m128 &phi_3, __m128 &phi_4, __m128 &phi_3_out, __m128 &phi_4_out, float *hit_x_2, float *hit_y_2, __m128 &phi_3_2, __m128 &phi_4_2, __m128 &phi_3_out_2, __m128 &phi_4_out_2)
Private Member Functions
float kappaToPt (float kappa)
float ptToKappa (float pt)
void findHelicesParallelThread (void *arg)
void splitHitsParallelThread (void *arg)
void initDummyHits (std::vector< SimpleHit3D > &dummies, const HelixRange &range, HelixKalmanState &init_state)
Private Attributes
float fast_chi2_cut_par0
float fast_chi2_cut_par1
float fast_chi2_cut_max
float chi2_cut
float chi2_removal_cut
unsigned int n_removal_hits
std::set< std::vector
< unsigned int > > combos
std::map< std::vector
< unsigned int >
, HelixKalmanState > pass_combos
std::set< std::vector
< unsigned int > > fail_combos
std::vector< float > detector_scatter
std::vector< float > integrated_scatter
std::vector< float > detector_radii
bool seeding
int verbosity
bool cut_on_dca
float dca_cut
float vertex_x
float vertex_y
float vertex_z
unsigned int required_layers
bool reject_ghosts
unsigned int nfits
CylinderKalman * kalman
std::vector< float > isolation_variable
unsigned int findtracksiter
float prev_max_k
float prev_max_dzdl
float prev_p_inv
float detector_B_field
std::vector< TrackSegment > segments1
std::vector< TrackSegment > segments2
std::vector< std::vector
< SimpleHit3D > > layer_sorted
std::vector< unsigned int > temp_comb
int seed_layer
std::vector< bool > seed_used
unsigned int nthreads
std::vector
< SeamStress::Seamstress * > * vssp
std::vector
< SeamStress::Seamstress > vss
SeamStress::Pincushion
< sPHENIXSeedFinder > * pins
std::vector< sPHENIXSeedFinder * > thread_trackers
std::vector< std::vector
< SimpleTrack3D > > thread_tracks
std::vector< HelixRange > thread_ranges
std::vector< std::vector
< SimpleHit3D > > thread_hits
std::vector< std::vector
< SimpleHit3D > > split_input_hits
std::vector< std::vector
< std::vector< SimpleHit3D > > * > split_output_hits
std::vector< std::vector
< HelixRange > * > split_ranges
bool is_parallel
unsigned int thread_min_hits
unsigned int thread_max_hits
bool is_thread
std::vector< AngleIndexList > angle_list
double CAtime
double KALtime
std::vector< std::vector
< SimpleHit3D > > layer_sorted_1 [4]
unsigned int findtracks_bin
float ca_chi2_cut
float cosang_cut
std::vector< float > hit_error_scale
Additional Inherited Members
Protected Member Functions inherited from HelixHough
void setRange (const BinEntryPair5D &bp, HelixRange &range1, HelixRange &range2, unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0)
void fillBins (unsigned int total_bins, unsigned int hit_counter, float *min_phi_a, float *max_phi_a, std::vector< SimpleHit3D > &four_hits, fastvec2d &z_bins, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, unsigned int d_bin, unsigned int k_bin, unsigned int n_phi, unsigned int zoomlevel, float low_phi, float high_phi, float inv_phi_range, fastvec &vote_array)
void makeClusters (unsigned int zoomlevel, unsigned int MAX, unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, unsigned int min_hits, std::vector< ParameterCluster > &clusters, bool &use_clusters, bool &is_super_bin)
bool attemptClusterMerge (unsigned int zoomlevel, unsigned int MAX, unsigned int ca, unsigned int d, unsigned int r, unsigned int th, unsigned int zz0, unsigned int bin, unsigned int newbin, std::vector< unsigned char > &good_bins, unsigned int volume, float cluster_size_cut, float overlap_cut, std::vector< ParameterCluster > &clusters, unsigned int *bins_start, unsigned int *bins_end, std::vector< unsigned int > &map_clus, std::vector< unsigned char > &too_big, std::vector< unsigned int > &temp_merged, std::vector< unsigned int > &C)
void vote_z (unsigned int zoomlevel, unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, fastvec2d &z_bins)
void vote_pairs (unsigned int zoomlevel)
void fillBins (unsigned int total_bins, unsigned int pair_counter, unsigned int *pair_index, float *min_phi, float *max_phi, float *min_d, float *max_d, float *min_dzdl, float *max_dzdl, float *min_z0, float *max_z0, std::vector< std::vector< SimpleHit3D > > &four_pairs, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, unsigned int k_bin, unsigned int n_phi, unsigned int zoomlevel, float low_phi, float high_phi, float low_d, float high_d, float low_z0, float high_z0, float low_dzdl, float high_dzdl, float inv_phi_range, float inv_d_range, float inv_z0_range, float inv_dzdl_range, fastvec &vote_array)
void findHelicesByPairsBegin (unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks, unsigned int zoomlevel)
void findHelicesByPairs (unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > &tracks, unsigned int maxtracks, unsigned int zoomlevel)
Static Protected Member Functions inherited from HelixHough
static void allButKappaRange_sse (float *x1_a, float *x2_a, float *y1_a, float *y2_a, float *z1_a, float *z2_a, float *min_k_a, float *max_k_a, float *min_phi_1_a, float *max_phi_1_a, float *min_phi_2_a, float *max_phi_2_a, float *min_d_1_a, float *max_d_1_a, float *min_d_2_a, float *max_d_2_a, float *min_dzdl_a, float *max_dzdl_a, float *min_z0_1_a, float *max_z0_1_a, float *min_z0_2_a, float *max_z0_2_a)
Protected Attributes inherited from HelixHough
bool remove_hits
std::vector< unsigned int > * hit_used
std::vector< unsigned int > n_phi_bins
std::vector< unsigned int > n_d_bins
std::vector< unsigned int > n_k_bins
std::vector< unsigned int > n_dzdl_bins
std::vector< unsigned int > n_z0_bins
std::vector< SimpleHit3D > * base_hits
std::vector< std::vector
< SimpleHit3D > * > hits_vec
std::vector< std::vector
< std::pair< unsigned int,
unsigned int > > * > pairs_vec
std::vector< unsigned int > index_mapping
std::vector< std::vector
< BinEntryPair5D > * > bins_vec
vector of BinEntryPairs which list the parameter bins each hit gets voted into
std::vector< std::vector
< SimpleTrack3D > * > seeds_vec
HelixRange top_range
HelixRange current_range
std::vector< HelixRange > zoomranges
std::vector< std::vector
< ParameterCluster > * > clusters_vec
std::vector< unsigned int > num_clusters
std::vector< unsigned int > C_clus
std::vector< unsigned int > temp_merged_clus
unsigned int max_zoom
unsigned int min_zoom
bool using_vertex
unsigned int max_tracks
double vote_time
double xy_vote_time
double z_vote_time
double cluster_time
bool print_timings
bool separate_by_helicity
bool helicity
bool only_one_helicity
bool check_layers
unsigned int req_layers
float bin_scale
float z_bin_scale
unsigned int start_zoom
unsigned int max_hits_pairs
std::vector< std::pair
< unsigned int, unsigned int > > temp_pairs
std::set< unsigned int > new_hits
std::map< unsigned int,
unsigned int > old_to_new
unsigned int cluster_start_bin
unsigned int bins_start [1<< 12]
unsigned int bins_end [1<< 12]
unsigned int layers_at_a_time
std::vector< HelixKalmanState > track_states
std::vector< HelixKalmanState > seed_states
unsigned int n_layers
int layer_start
int layer_end
bool smooth_back
bool cull_input_hits
bool iterate_clustering
Detailed Description
Definition at line 205 of file sPHENIXSeedFinder.h.
Constructor & Destructor Documentation
sPHENIXSeedFinder::sPHENIXSeedFinder (unsigned int n_phi, unsigned int n_d, unsigned int n_k, unsigned int n_dzdl, unsigned int n_z0, HelixResolution & min_resolution, HelixResolution & max_resolution, HelixRange & range, std::vector< float > & material, std::vector< float > & radius, float Bfield)
Definition at line 158 of file sPHENIXSeedFinder.cpp.
References detector_B_field, detector_radii, detector_scatter, i, integrated_scatter, kalman, layer_sorted, layer_sorted_1, HelixHough::n_layers, and temp_comb.
Referenced by sPHENIXSeedFinder().
sPHENIXSeedFinder::sPHENIXSeedFinder (std::vector< std::vector< unsigned int > > & zoom_profile, unsigned int minzoom, HelixRange & range, std::vector< float > & material, std::vector< float > & radius, float Bfield, bool parallel = false, unsigned int num_threads = 1)
Definition at line 221 of file sPHENIXSeedFinder.cpp.
References detector_B_field, detector_radii, detector_scatter, i, integrated_scatter, is_parallel, kalman, layer_sorted, layer_sorted_1, HelixHough::n_layers, nthreads, pins, sPHENIXSeedFinder(), split_input_hits, split_output_hits, split_ranges, temp_comb, thread_hits, thread_ranges, thread_trackers, thread_tracks, vss, and vssp.
sPHENIXSeedFinder::~sPHENIXSeedFinder () virtual
Definition at line 316 of file sPHENIXSeedFinder.cpp.
References i, kalman, pins, split_output_hits, split_ranges, thread_trackers, vss, and vssp.
Member Function Documentation
bool sPHENIXSeedFinder::breakRecursion (const std::vector< SimpleHit3D > & hits, const HelixRange & range) virtual
Reimplemented from HelixHough.
Definition at line 524 of file sPHENIXSeedFinder.cpp.
References i, required_layers, and seeding.
void sPHENIXSeedFinder::calculateKappaTangents (float * x1_a, float * y1_a, float * z1_a, float * x2_a, float * y2_a, float * z2_a, float * x3_a, float * y3_a, float * z3_a, float * dx1_a, float * dy1_a, float * dz1_a, float * dx2_a, float * dy2_a, float * dz2_a, float * dx3_a, float * dy3_a, float * dz3_a, float * kappa_a, float * dkappa_a, float * ux_mid_a, float * uy_mid_a, float * ux_end_a, float * uy_end_a, float * dzdl_1_a, float * dzdl_2_a, float * ddzdl_1_a, float * ddzdl_2_a) static
Definition at line 829 of file sPHENIXSeedFinder.cpp.
References dz2, k, one, s1, tmp1, tmp2, two, v, x2, x3, y3, z1, z2, and zero.
Referenced by findTracksBySegments().
void sPHENIXSeedFinder::calculateKappaTangents (float * x1_a, float * y1_a, float * z1_a, float * x2_a, float * y2_a, float * z2_a, float * x3_a, float * y3_a, float * z3_a, float * dx1_a, float * dy1_a, float * dz1_a, float * dx2_a, float * dy2_a, float * dz2_a, float * dx3_a, float * dy3_a, float * dz3_a, float * kappa_a, float * dkappa_a, float * ux_mid_a, float * uy_mid_a, float * ux_end_a, float * uy_end_a, float * dzdl_1_a, float * dzdl_2_a, float * ddzdl_1_a, float * ddzdl_2_a, float sinang_cut, float cosang_diff_inv, float * cur_kappa_a, float * cur_dkappa_a, float * cur_ux_a, float * cur_uy_a, float * cur_chi2_a, float * chi2_a)
Definition at line 979 of file sPHENIXSeedFinder.cpp.
References dz2, k, one, one_o_2, s1, tmp1, tmp2, two, v, x2, x3, y3, z1, z2, and zero.
void sPHENIXSeedFinder::clear () inline virtual
Reimplemented from HelixHough.
Definition at line 263 of file sPHENIXSeedFinder.h.
References isolation_variable, and HelixHough::track_states.
Referenced by PHHoughSeeding::full_track_seeding().
float sPHENIXSeedFinder::dcaToVertexXY (SimpleTrack3D & track, float vx, float vy)
Definition at line 403 of file sPHENIXSeedFinder.cpp.
References SimpleTrack3D::d, SimpleTrack3D::kappa, SimpleTrack3D::phi, and x0.
float sPHENIXSeedFinder::dzdlError (SimpleHit3D & hit, float min_k, float max_k, float min_d, float max_d, float min_z0, float max_z0, float min_dzdl, float max_dzdl, bool pairvoting = false) virtual
Reimplemented from HelixHough.
Definition at line 588 of file sPHENIXSeedFinder.cpp.
References detector_B_field, detector_radii, detector_scatter, SimpleHit3D::get_layer(), i, prev_max_dzdl, prev_max_k, prev_p_inv, and seed_layer.
void sPHENIXSeedFinder::finalize (std::vector< SimpleTrack3D > & input, std::vector< SimpleTrack3D > & output) virtual
Reimplemented from HelixHough.
Definition at line 430 of file sPHENIXSeedFinder.cpp.
References HelixKalman::addHit(), CAtime, HelixKalmanState::chi2, findtracksiter, SimpleHit3D::get_layer(), SVM_v1::h, hit_error_scale, i, is_thread, isolation_variable, kalman, KALtime, nfits, reject_ghosts, HelixHough::smooth_back, HelixHough::track_states, tripletRejection(), and verbosity.
Referenced by findHelicesParallel(), and PHHoughSeeding::full_track_seeding().
void sPHENIXSeedFinder::findHelicesParallel (std::vector< SimpleHit3D > & hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > & tracks)
Definition at line 1979 of file sPHENIXSeedFinder.cpp.
References HelixHough::cluster_start_bin, finalize(), findHelicesParallelOneHelicity(), i, initSplitting(), j, nthreads, HelixHough::separate_by_helicity, split_input_hits, split_output_hits, thread_max_hits, thread_min_hits, thread_trackers, thread_tracks, and HelixHough::track_states.
void sPHENIXSeedFinder::findHelicesParallelOneHelicity (std::vector< SimpleHit3D > & hits, unsigned int min_hits, unsigned int max_hits, std::vector< SimpleTrack3D > & tracks)
Definition at line 1936 of file sPHENIXSeedFinder.cpp.
References findHelicesParallelThread(), i, j, nbins, nthreads, pins, pos, SeamStress::Pincushion< TClass >::sewStraight(), split_input_hits, split_output_hits, split_ranges, splitHitsParallelThread(), thread_hits, thread_max_hits, thread_min_hits, thread_ranges, thread_trackers, and HelixHough::top_range.
Referenced by findHelicesParallel().
void sPHENIXSeedFinder::findHelicesParallelThread (void * arg) private
Definition at line 2044 of file sPHENIXSeedFinder.cpp.
References i, nthreads, thread_hits, thread_max_hits, thread_min_hits, thread_ranges, thread_trackers, and thread_tracks.
Referenced by findHelicesParallelOneHelicity().
void sPHENIXSeedFinder::findTracks (std::vector< SimpleHit3D > & hits, std::vector< SimpleTrack3D > & tracks, const HelixRange & range) virtual
Implements HelixHough.
Definition at line 517 of file sPHENIXSeedFinder.cpp.
References findTracksBySegments(), and findtracksiter.
void sPHENIXSeedFinder::findTracksBySegments (std::vector< SimpleHit3D > & hits, std::vector< SimpleTrack3D > & tracks, const HelixRange & range)
Definition at line 1282 of file sPHENIXSeedFinder.cpp.
References __attribute__(), HelixKalman::addHit(), HelixKalmanState::C, ca_chi2_cut, calculateKappaTangents(), CAtime, HelixKalmanState::chi2, TrackSegment::chi2, chi2_cut, chi2_removal_cut, combos, cosang_cut, cut_on_dca, HelixKalmanState::d, SimpleTrack3D::d, dca_cut, TrackSegment::dkappa, double(), HelixKalmanState::dzdl, SimpleTrack3D::dzdl, fast_chi2_cut_max, fast_chi2_cut_par0, fast_chi2_cut_par1, fitTrack(), SVM_v1::h, SimpleTrack3D::hits, TrackSegment::hits, i, it, j, k, kalman, KALtime, HelixKalmanState::kappa, SimpleTrack3D::kappa, TrackSegment::kappa, kappaToPt(), layer_sorted, M_PI, HelixRange::max_k, min, TrackSegment::n_hits, HelixHough::n_layers, n_removal_hits, nfits, HelixKalmanState::nu, HelixKalmanState::phi, SimpleTrack3D::phi, HelixKalmanState::position, HelixHough::remove_hits, HelixHough::req_layers, segments1, segments2, boost::swap(), t1, t2, temp_comb, HelixHough::top_range, HelixHough::track_states, TrackSegment::ux, TrackSegment::uy, HelixKalmanState::x_int, HelixKalmanState::y_int, HelixKalmanState::z0, SimpleTrack3D::z0, and HelixKalmanState::z_int.
Referenced by findTracks().
float sPHENIXSeedFinder::fitTrack (SimpleTrack3D & track) static
Definition at line 662 of file sPHENIXSeedFinder.cpp.
Referenced by findTracksBySegments().
float sPHENIXSeedFinder::fitTrack (SimpleTrack3D & track, std::vector< float > & chi2_hit) static
Definition at line 667 of file sPHENIXSeedFinder.cpp.
References SimpleTrack3D::d, d, dx, dy, SimpleTrack3D::dzdl, dzdl, SVM_v1::h, SimpleTrack3D::hits, i, k, SimpleTrack3D::kappa, SimpleTrack3D::phi, phi, r, s, temp1, temp2, v, X, y, and SimpleTrack3D::z0.
std::vector<float>& sPHENIXSeedFinder::getIsolation () inline
Definition at line 310 of file sPHENIXSeedFinder.h.
References isolation_variable.
void sPHENIXSeedFinder::initDummyHits (std::vector< SimpleHit3D > & dummies, const HelixRange & range, HelixKalmanState & init_state) private
Definition at line 1171 of file sPHENIXSeedFinder.cpp.
References HelixKalmanState::C, HelixKalmanState::chi2, HelixKalmanState::d, SimpleTrack3D::d, HelixKalmanState::dzdl, SimpleTrack3D::dzdl, SimpleTrack3D::hits, i, HelixKalmanState::kappa, SimpleTrack3D::kappa, HelixRange::max_d, HelixRange::max_dzdl, HelixRange::max_k, HelixRange::max_phi, HelixRange::max_z0, HelixRange::min_d, HelixRange::min_dzdl, HelixRange::min_k, HelixRange::min_phi, HelixRange::min_z0, HelixHough::n_layers, HelixKalmanState::nu, HelixKalmanState::phi, SimpleTrack3D::phi, HelixKalmanState::position, projectToLayer(), x, HelixKalmanState::x_int, y, HelixKalmanState::y_int, z, HelixKalmanState::z0, SimpleTrack3D::z0, and HelixKalmanState::z_int.
void sPHENIXSeedFinder::initEvent (std::vector< SimpleHit3D > & hits, unsigned int min_hits) inline virtual
Reimplemented from HelixHough.
Definition at line 227 of file sPHENIXSeedFinder.h.
References CAtime, combos, fail_combos, findtracks_bin, findtracksiter, i, KALtime, nfits, pass_combos, HelixHough::req_layers, required_layers, seeding, setNLayers(), and setSeedLayer().
Referenced by initSplitting().
void sPHENIXSeedFinder::initSeeding (std::vector< SimpleTrack3D > & seeds) inline virtual
Reimplemented from HelixHough.
Definition at line 254 of file sPHENIXSeedFinder.h.
References angle_list, HelixHough::n_layers, seed_used, and seeding.
void sPHENIXSeedFinder::initSplitting (std::vector< SimpleHit3D > & hits, unsigned int min_hits, unsigned int max_hits)
Definition at line 1926 of file sPHENIXSeedFinder.cpp.
References HelixHough::hits_vec, initEvent(), HelixHough::max_zoom, HelixHough::top_range, z, and HelixHough::zoomranges.
Referenced by findHelicesParallel().
float sPHENIXSeedFinder::kappaToPt (float kappa) private
Definition at line 334 of file sPHENIXSeedFinder.cpp.
References detector_B_field.
Referenced by findTracksBySegments().
void sPHENIXSeedFinder::pairRejection (std::vector< SimpleTrack3D > & input, std::vector< SimpleTrack3D > & output, std::vector< bool > & usetrack, std::vector< float > & next_best_chi2)
float sPHENIXSeedFinder::phiError (SimpleHit3D & hit, float min_k, float max_k, float min_d, float max_d, float min_z0, float max_z0, float min_dzdl, float max_dzdl, bool pairvoting = false) virtual
Reimplemented from HelixHough.
Definition at line 549 of file sPHENIXSeedFinder.cpp.
References detector_B_field, detector_radii, detector_scatter, SimpleHit3D::get_layer(), i, prev_max_dzdl, prev_max_k, prev_p_inv, and seed_layer.
void sPHENIXSeedFinder::projectToLayer (SimpleTrack3D & seed, unsigned int layer, float & x, float & y, float & z)
Definition at line 1843 of file sPHENIXSeedFinder.cpp.
References SimpleTrack3D::d, d, detector_radii, SimpleTrack3D::dzdl, dzdl, SVM_v1::h, SimpleTrack3D::hits, k, SimpleTrack3D::kappa, SimpleTrack3D::phi, phi, s, sign(), temp1, temp2, tmp1, ux, uy, v, x2, and SimpleTrack3D::z0.
Referenced by initDummyHits().
float sPHENIXSeedFinder::ptToKappa (float pt) private
Definition at line 338 of file sPHENIXSeedFinder.cpp.
References detector_B_field.
void sPHENIXSeedFinder::requireLayers (unsigned int nl) inline virtual
Reimplemented from HelixHough.
Definition at line 356 of file sPHENIXSeedFinder.h.
References HelixHough::check_layers, i, is_parallel, HelixHough::req_layers, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
bool sPHENIXSeedFinder::seedWasUsed (unsigned int seed_index) inline
Definition at line 343 of file sPHENIXSeedFinder.h.
References seed_used.
void sPHENIXSeedFinder::setBinScale (float b_scl) inline virtual
Reimplemented from HelixHough.
Definition at line 375 of file sPHENIXSeedFinder.h.
References HelixHough::bin_scale, i, is_parallel, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setCellularAutomatonChi2Cut (float cut) inline
Definition at line 467 of file sPHENIXSeedFinder.h.
References ca_chi2_cut, i, is_parallel, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setChi2Cut (float c) inline
Definition at line 432 of file sPHENIXSeedFinder.h.
References c, chi2_cut, i, is_parallel, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setChi2RemovalCut (float c) inline
Definition at line 440 of file sPHENIXSeedFinder.h.
References c, chi2_removal_cut, i, is_parallel, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setCosAngleCut (float cut) inline
Definition at line 458 of file sPHENIXSeedFinder.h.
References cosang_cut, i, is_parallel, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setCutOnDca (bool dcut) inline
Definition at line 294 of file sPHENIXSeedFinder.h.
References cut_on_dca.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setDcaCut (float dcut) inline
Definition at line 297 of file sPHENIXSeedFinder.h.
References dca_cut.
Referenced by PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setFastChi2Cut (float par0, float par1, float max) inline
Definition at line 422 of file sPHENIXSeedFinder.h.
References fast_chi2_cut_max, fast_chi2_cut_par0, fast_chi2_cut_par1, i, is_parallel, max, par0, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setHitErrorScale (unsigned int layer, float scale) inline
Definition at line 483 of file sPHENIXSeedFinder.h.
References hit_error_scale.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
virtual void sPHENIXSeedFinder::setMaxHitsPairs (unsigned int mhp) inline virtual
Reimplemented from HelixHough.
Definition at line 366 of file sPHENIXSeedFinder.h.
References i, is_parallel, HelixHough::max_hits_pairs, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setNLayers (unsigned int n) inline
Definition at line 409 of file sPHENIXSeedFinder.h.
References i, is_parallel, layer_sorted, n, HelixHough::n_layers, temp_comb, and thread_trackers.
Referenced by initEvent(), PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setNRemovalHits (unsigned int n) inline
Definition at line 449 of file sPHENIXSeedFinder.h.
References i, is_parallel, n, n_removal_hits, and thread_trackers.
void sPHENIXSeedFinder::setRangeFromSeed (HelixRange & range, SimpleTrack3D & seed) virtual
Reimplemented from HelixHough.
Definition at line 627 of file sPHENIXSeedFinder.cpp.
References HelixKalmanState::C, SimpleTrack3D::d, SimpleTrack3D::dzdl, SimpleTrack3D::index, SimpleTrack3D::kappa, M_PI, HelixRange::max_d, HelixRange::max_dzdl, HelixRange::max_k, HelixRange::max_phi, HelixRange::max_z0, HelixRange::min_d, HelixRange::min_dzdl, HelixRange::min_k, HelixRange::min_phi, HelixRange::min_z0, SimpleTrack3D::phi, HelixHough::seed_states, and SimpleTrack3D::z0.
void sPHENIXSeedFinder::setRejectGhosts (bool rg) inline
Definition at line 306 of file sPHENIXSeedFinder.h.
References reject_ghosts.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setRemoveHits (bool rh) inline virtual
Reimplemented from HelixHough.
Definition at line 391 of file sPHENIXSeedFinder.h.
References i, is_parallel, HelixHough::remove_hits, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setSeedLayer (int sl) inline
Definition at line 400 of file sPHENIXSeedFinder.h.
References i, is_parallel, seed_layer, and thread_trackers.
Referenced by initEvent().
void sPHENIXSeedFinder::setSeparateByHelicity (bool sbh) inline virtual
Reimplemented from HelixHough.
Definition at line 347 of file sPHENIXSeedFinder.h.
References i, is_parallel, HelixHough::separate_by_helicity, and thread_trackers.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setThread () inline
Definition at line 476 of file sPHENIXSeedFinder.h.
References is_thread.
void sPHENIXSeedFinder::setVerbosity (int v) inline
Definition at line 290 of file sPHENIXSeedFinder.h.
References v, and verbosity.
Referenced by PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::setVertex (float vx, float vy, float vz) inline
Definition at line 300 of file sPHENIXSeedFinder.h.
References vertex_x, vertex_y, and vertex_z.
void sPHENIXSeedFinder::setZBinScale (float b_scl) inline virtual
Reimplemented from HelixHough.
Definition at line 383 of file sPHENIXSeedFinder.h.
References i, is_parallel, thread_trackers, and HelixHough::z_bin_scale.
Referenced by PHHoughSeeding::setup_initial_tracker_object(), PHHoughSeeding::setup_seed_tracker_objects(), and PHHoughSeeding::setup_tracker_object().
void sPHENIXSeedFinder::splitHitsParallelThread (void * arg) private
Definition at line 2038 of file sPHENIXSeedFinder.cpp.
References split_output_hits, split_ranges, thread_max_hits, thread_min_hits, and thread_trackers.
Referenced by findHelicesParallelOneHelicity().
void sPHENIXSeedFinder::tripletRejection (std::vector< SimpleTrack3D > & input, std::vector< SimpleTrack3D > & output, std::vector< bool > & usetrack, std::vector< float > & next_best_chi2)
Definition at line 81 of file sPHENIXSeedFinder.cpp.
References h1, h2, i, and pos.
Referenced by finalize().
Member Data Documentation
std::vector<AngleIndexList> sPHENIXSeedFinder::angle_list private
Definition at line 559 of file sPHENIXSeedFinder.h.
Referenced by initSeeding().
float sPHENIXSeedFinder::ca_chi2_cut private
Definition at line 567 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setCellularAutomatonChi2Cut().
double sPHENIXSeedFinder::CAtime private
Definition at line 561 of file sPHENIXSeedFinder.h.
Referenced by finalize(), findTracksBySegments(), and initEvent().
float sPHENIXSeedFinder::chi2_cut private
Definition at line 503 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setChi2Cut().
float sPHENIXSeedFinder::chi2_removal_cut private
Definition at line 504 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setChi2RemovalCut().
std::set<std::vector<unsigned int> > sPHENIXSeedFinder::combos private
Definition at line 506 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and initEvent().
float sPHENIXSeedFinder::cosang_cut private
Definition at line 568 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setCosAngleCut().
bool sPHENIXSeedFinder::cut_on_dca private
Definition at line 514 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setCutOnDca().
float sPHENIXSeedFinder::dca_cut private
Definition at line 515 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setDcaCut().
float sPHENIXSeedFinder::detector_B_field private
Definition at line 531 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), kappaToPt(), phiError(), ptToKappa(), and sPHENIXSeedFinder().
std::vector<float> sPHENIXSeedFinder::detector_radii private
Definition at line 511 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), phiError(), projectToLayer(), and sPHENIXSeedFinder().
std::vector<float> sPHENIXSeedFinder::detector_scatter private
Definition at line 509 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), phiError(), and sPHENIXSeedFinder().
std::set<std::vector<unsigned int> > sPHENIXSeedFinder::fail_combos private
Definition at line 508 of file sPHENIXSeedFinder.h.
Referenced by initEvent().
float sPHENIXSeedFinder::fast_chi2_cut_max private
Definition at line 502 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setFastChi2Cut().
float sPHENIXSeedFinder::fast_chi2_cut_par0 private
Definition at line 500 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setFastChi2Cut().
float sPHENIXSeedFinder::fast_chi2_cut_par1 private
Definition at line 501 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setFastChi2Cut().
unsigned int sPHENIXSeedFinder::findtracks_bin private
Definition at line 565 of file sPHENIXSeedFinder.h.
Referenced by initEvent().
unsigned int sPHENIXSeedFinder::findtracksiter private
Definition at line 525 of file sPHENIXSeedFinder.h.
Referenced by finalize(), findTracks(), and initEvent().
std::vector<float> sPHENIXSeedFinder::hit_error_scale private
Definition at line 570 of file sPHENIXSeedFinder.h.
Referenced by finalize(), and setHitErrorScale().
std::vector<float> sPHENIXSeedFinder::integrated_scatter private
Definition at line 510 of file sPHENIXSeedFinder.h.
Referenced by sPHENIXSeedFinder().
bool sPHENIXSeedFinder::is_parallel private
Definition at line 554 of file sPHENIXSeedFinder.h.
Referenced by requireLayers(), setBinScale(), setCellularAutomatonChi2Cut(), setChi2Cut(), setChi2RemovalCut(), setCosAngleCut(), setFastChi2Cut(), setMaxHitsPairs(), setNLayers(), setNRemovalHits(), setRemoveHits(), setSeedLayer(), setSeparateByHelicity(), setZBinScale(), and sPHENIXSeedFinder().
bool sPHENIXSeedFinder::is_thread private
Definition at line 557 of file sPHENIXSeedFinder.h.
Referenced by finalize(), and setThread().
std::vector<float> sPHENIXSeedFinder::isolation_variable private
Definition at line 523 of file sPHENIXSeedFinder.h.
Referenced by clear(), finalize(), and getIsolation().
CylinderKalman* sPHENIXSeedFinder::kalman private
Definition at line 521 of file sPHENIXSeedFinder.h.
Referenced by finalize(), findTracksBySegments(), sPHENIXSeedFinder(), and ~sPHENIXSeedFinder().
double sPHENIXSeedFinder::KALtime private
Definition at line 562 of file sPHENIXSeedFinder.h.
Referenced by finalize(), findTracksBySegments(), and initEvent().
std::vector<std::vector<SimpleHit3D> > sPHENIXSeedFinder::layer_sorted private
Definition at line 536 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), setNLayers(), and sPHENIXSeedFinder().
std::vector<std::vector<SimpleHit3D> > sPHENIXSeedFinder::layer_sorted_1[4] private
Definition at line 564 of file sPHENIXSeedFinder.h.
Referenced by sPHENIXSeedFinder().
unsigned int sPHENIXSeedFinder::n_removal_hits private
Definition at line 505 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), and setNRemovalHits().
unsigned int sPHENIXSeedFinder::nfits private
Definition at line 519 of file sPHENIXSeedFinder.h.
Referenced by finalize(), findTracksBySegments(), and initEvent().
unsigned int sPHENIXSeedFinder::nthreads private
Definition at line 543 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelOneHelicity(), findHelicesParallelThread(), and sPHENIXSeedFinder().
std::map<std::vector<unsigned int>, HelixKalmanState> sPHENIXSeedFinder::pass_combos private
Definition at line 507 of file sPHENIXSeedFinder.h.
Referenced by initEvent().
SeamStress::Pincushion<sPHENIXSeedFinder>* sPHENIXSeedFinder::pins private
Definition at line 546 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallelOneHelicity(), sPHENIXSeedFinder(), and ~sPHENIXSeedFinder().
float sPHENIXSeedFinder::prev_max_dzdl private
Definition at line 528 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), and phiError().
float sPHENIXSeedFinder::prev_max_k private
Definition at line 527 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), and phiError().
float sPHENIXSeedFinder::prev_p_inv private
Definition at line 529 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), and phiError().
bool sPHENIXSeedFinder::reject_ghosts private
Definition at line 518 of file sPHENIXSeedFinder.h.
Referenced by finalize(), and setRejectGhosts().
unsigned int sPHENIXSeedFinder::required_layers private
Definition at line 517 of file sPHENIXSeedFinder.h.
Referenced by breakRecursion(), and initEvent().
int sPHENIXSeedFinder::seed_layer private
Definition at line 539 of file sPHENIXSeedFinder.h.
Referenced by dzdlError(), phiError(), and setSeedLayer().
std::vector<bool> sPHENIXSeedFinder::seed_used private
Definition at line 541 of file sPHENIXSeedFinder.h.
Referenced by initSeeding(), and seedWasUsed().
bool sPHENIXSeedFinder::seeding private
Definition at line 512 of file sPHENIXSeedFinder.h.
Referenced by breakRecursion(), initEvent(), and initSeeding().
std::vector<TrackSegment> sPHENIXSeedFinder::segments1 private
Definition at line 533 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments().
std::vector<TrackSegment> sPHENIXSeedFinder::segments2 private
Definition at line 534 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments().
std::vector<std::vector<SimpleHit3D> > sPHENIXSeedFinder::split_input_hits private
Definition at line 551 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelOneHelicity(), and sPHENIXSeedFinder().
std::vector<std::vector<std::vector<SimpleHit3D> >*> sPHENIXSeedFinder::split_output_hits private
Definition at line 552 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelOneHelicity(), sPHENIXSeedFinder(), splitHitsParallelThread(), and ~sPHENIXSeedFinder().
std::vector<std::vector<HelixRange>*> sPHENIXSeedFinder::split_ranges private
Definition at line 553 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallelOneHelicity(), sPHENIXSeedFinder(), splitHitsParallelThread(), and ~sPHENIXSeedFinder().
std::vector<unsigned int> sPHENIXSeedFinder::temp_comb private
Definition at line 537 of file sPHENIXSeedFinder.h.
Referenced by findTracksBySegments(), setNLayers(), and sPHENIXSeedFinder().
std::vector<std::vector<SimpleHit3D> > sPHENIXSeedFinder::thread_hits private
Definition at line 550 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallelOneHelicity(), findHelicesParallelThread(), and sPHENIXSeedFinder().
unsigned int sPHENIXSeedFinder::thread_max_hits private
Definition at line 556 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelOneHelicity(), findHelicesParallelThread(), and splitHitsParallelThread().
unsigned int sPHENIXSeedFinder::thread_min_hits private
Definition at line 555 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelOneHelicity(), findHelicesParallelThread(), and splitHitsParallelThread().
std::vector<HelixRange> sPHENIXSeedFinder::thread_ranges private
Definition at line 549 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallelOneHelicity(), findHelicesParallelThread(), and sPHENIXSeedFinder().
std::vector<sPHENIXSeedFinder*> sPHENIXSeedFinder::thread_trackers private
Definition at line 547 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelOneHelicity(), findHelicesParallelThread(), requireLayers(), setBinScale(), setCellularAutomatonChi2Cut(), setChi2Cut(), setChi2RemovalCut(), setCosAngleCut(), setFastChi2Cut(), setMaxHitsPairs(), setNLayers(), setNRemovalHits(), setRemoveHits(), setSeedLayer(), setSeparateByHelicity(), setZBinScale(), sPHENIXSeedFinder(), splitHitsParallelThread(), and ~sPHENIXSeedFinder().
std::vector<std::vector<SimpleTrack3D> > sPHENIXSeedFinder::thread_tracks private
Definition at line 548 of file sPHENIXSeedFinder.h.
Referenced by findHelicesParallel(), findHelicesParallelThread(), and sPHENIXSeedFinder().
int sPHENIXSeedFinder::verbosity private
Definition at line 513 of file sPHENIXSeedFinder.h.
Referenced by finalize(), and setVerbosity().
float sPHENIXSeedFinder::vertex_x private
Definition at line 516 of file sPHENIXSeedFinder.h.
Referenced by setVertex().
float sPHENIXSeedFinder::vertex_y private
Definition at line 516 of file sPHENIXSeedFinder.h.
Referenced by setVertex().
float sPHENIXSeedFinder::vertex_z private
Definition at line 516 of file sPHENIXSeedFinder.h.
Referenced by setVertex().
std::vector<SeamStress::Seamstress> sPHENIXSeedFinder::vss private
Definition at line 545 of file sPHENIXSeedFinder.h.
Referenced by sPHENIXSeedFinder(), and ~sPHENIXSeedFinder().
std::vector<SeamStress::Seamstress*>* sPHENIXSeedFinder::vssp private
Definition at line 544 of file sPHENIXSeedFinder.h.
Referenced by sPHENIXSeedFinder(), and ~sPHENIXSeedFinder().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXSeedFinder.h
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXSeedFinder.cpp