Analysis Software: prdfBuffer Class Reference
prdfBuffer Class Reference
#include <online_distribution/blob/master/newbasic/prdfBuffer.h>
Classes
struct buffer_ptr
Public Member Functions
prdfBuffer ()
prdfBuffer (PHDWORD *array, const int length)
~prdfBuffer ()
Event * getEvent ()
int * getEventData ()
int isGood () const
int buffer_swap ()
int frame_swap (PHDWORD *fp, const int eventlength)
Public Member Functions inherited from buffer
buffer ()
virtual ~buffer ()
Protected Attributes
buffer_ptr bptr
PHDWORD * data_ptr
int buffer_size
int max_length
int current_index
int is_good
Additional Inherited Members
Static Public Member Functions inherited from buffer
static int makeBuffer (PHDWORD *bp, const int allocatedsize, buffer **bptr)
static int i4swap (const int in)
static unsigned int u4swap (const unsigned int in)
static int i22swap (const int in)
static short i2swap (const short in)
Detailed Description
Definition at line 12 of file prdfBuffer.h.
Constructor & Destructor Documentation
prdfBuffer::prdfBuffer ()
Definition at line 9 of file prdfBuffer.cc.
References is_good.
Referenced by gzbuffer::gzbuffer(), and lzobuffer::lzobuffer().
prdfBuffer::prdfBuffer (PHDWORD * array, const int length)
Definition at line 14 of file prdfBuffer.cc.
References bptr, buffer_size, buffer_swap(), BUFFERMARKER, COUT, current_index, prdfBuffer::buffer_ptr::data, data_ptr, prdfBuffer::buffer_ptr::ID, is_good, max_length, and buffer::u4swap().
prdfBuffer::~prdfBuffer ()
Definition at line 44 of file prdfBuffer.cc.
Member Function Documentation
int prdfBuffer::buffer_swap ()
Definition at line 47 of file prdfBuffer.cc.
References bptr, BUFFERHEADERLENGTH, prdfBuffer::buffer_ptr::Bufseq, CORRUPTEVENTMASK, COUT, evt_data::data, prdfBuffer::buffer_ptr::data, evt_data::evt_length, evt_data::evt_type, EVTHEADERLENGTH, frame_swap(), getFrameLength(), i, buffer::i4swap(), prdfBuffer::buffer_ptr::ID, prdfBuffer::buffer_ptr::Length, and prdfBuffer::buffer_ptr::Runnr.
Referenced by prdfBuffer().
int prdfBuffer::frame_swap (PHDWORD * fp, const int eventlength)
Definition at line 131 of file prdfBuffer.cc.
References i, and buffer::i4swap().
Referenced by buffer_swap().
Event * prdfBuffer::getEvent () virtual
Implements buffer.
Definition at line 150 of file prdfBuffer.cc.
References bptr, buffer_size, current_index, prdfBuffer::buffer_ptr::data, is_good, and max_length.
int * prdfBuffer::getEventData () virtual
Implements buffer.
Definition at line 205 of file prdfBuffer.cc.
References bptr, buffer_size, current_index, prdfBuffer::buffer_ptr::data, and max_length.
int prdfBuffer::isGood () const inline virtual
Implements buffer.
Definition at line 30 of file prdfBuffer.h.
Member Data Documentation
buffer_ptr prdfBuffer::bptr protected
Definition at line 45 of file prdfBuffer.h.
Referenced by buffer_swap(), getEvent(), getEventData(), and prdfBuffer().
int prdfBuffer::buffer_size protected
Definition at line 47 of file prdfBuffer.h.
Referenced by getEvent(), getEventData(), and prdfBuffer().
int prdfBuffer::current_index protected
Definition at line 49 of file prdfBuffer.h.
Referenced by getEvent(), getEventData(), and prdfBuffer().
PHDWORD* prdfBuffer::data_ptr protected
Definition at line 46 of file prdfBuffer.h.
Referenced by prdfBuffer().
int prdfBuffer::is_good protected
Definition at line 50 of file prdfBuffer.h.
Referenced by getEvent(), gzbuffer::gzbuffer(), lzobuffer::lzobuffer(), and prdfBuffer().
int prdfBuffer::max_length protected
Definition at line 48 of file prdfBuffer.h.
Referenced by getEvent(), getEventData(), and prdfBuffer().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/prdfBuffer.h
online_distribution/blob/master/newbasic/prdfBuffer.cc