Analysis Software: analysis/blob/master/TPC/SCDCorrections/airy.f File Reference
airy.f File Reference
Functions/Subroutines
subroutine aiz (IFUN, IFAC, X0, Y0, GAIR, GAII, IERRO)
subroutine airy1 (X, W, GAIR, GAII)
subroutine airy2 (X, W, GAIR, GAII)
subroutine airy1d (X, W, GAIR, GAII)
subroutine airy2d (X, W, GAIR, GAII)
DOUBLE PRECISION function phase (X, Y)
subroutine fgp (X, Y, EPS, FR, FI, GR, GI)
subroutine fg (X, Y, EPS, FR, FI, GR, GI)
subroutine serai (X, Y, AIR, AII)
subroutine seraid (X, Y, AIR, AII)
subroutine expai (GAIR, GAII)
subroutine expaid (GAIR, GAII)
subroutine biz (IFUN, IFAC, X0, Y0, GBIR, GBII, IERRO)
Function/Subroutine Documentation
subroutine airy1 (double precision, dimension(25) X, double precision, dimension(25) W, double precision GAIR, double precision GAII)
Definition at line 605 of file airy.f.
References c2, i, phase(), phi, r, s1, sHelix::w(), and x.
Referenced by aiz().
subroutine airy1d (double precision, dimension(25) X, double precision, dimension(25) W, double precision GAIR, double precision GAII)
Definition at line 705 of file airy.f.
References c2, i, phase(), phi, r, s1, sHelix::w(), and x.
Referenced by aiz().
subroutine airy2 (double precision, dimension(25) X, double precision, dimension(25) W, double precision GAIR, double precision GAII)
Definition at line 647 of file airy.f.
References c2, i, phase(), phi, r, s1, tau, sHelix::w(), and x.
Referenced by aiz().
subroutine airy2d (double precision, dimension(25) X, double precision, dimension(25) W, double precision GAIR, double precision GAII)
Definition at line 747 of file airy.f.
References c2, i, phase(), phi, r, s1, tau, sHelix::w(), and x.
Referenced by aiz().
subroutine aiz (integer IFUN, integer IFAC, double precision X0, double precision Y0, double precision GAIR, double precision GAII, integer IERRO)
Definition at line 2 of file airy.f.
References airy1(), airy1d(), airy2(), airy2d(), c, d, d1mach(), expai(), expaid(), n, phase(), pi, r, s, s1, serai(), seraid(), sHelix::u(), v, sHelix::w(), x, and x0.
Referenced by biz().
subroutine biz (integer IFUN, integer IFAC, double precision X0, double precision Y0, double precision GBIR, double precision GBII, integer IERRO)
Definition at line 1106 of file airy.f.
References aiz(), b1, c, d, d1mach(), phase(), pi, r, s, s1, sHelix::u(), v, x, x0, and y.
subroutine expai (double precision GAIR, double precision GAII)
Definition at line 979 of file airy.f.
References d, d1mach(), k, r, and s1.
Referenced by aiz().
subroutine expaid (double precision GAIR, double precision GAII)
Definition at line 1041 of file airy.f.
References d, d1mach(), k, r, and s1.
Referenced by aiz().
subroutine fg (double precision X, double precision Y, double precision EPS, double precision FR, double precision FI, double precision GR, double precision GI)
Definition at line 880 of file airy.f.
References ci, gr, sHelix::u(), v, x, x2, and y.
subroutine fgp (double precision X, double precision Y, double precision EPS, double precision FR, double precision FI, double precision GR, double precision GI)
Definition at line 826 of file airy.f.
References ci, gr, sHelix::u(), v, x, x2, and y.
Referenced by seraid().
DOUBLE PRECISION function phase (double precision X, double precision Y)
Definition at line 805 of file airy.f.
References pi, x, and y.
Referenced by airy1(), airy1d(), airy2(), airy2d(), aiz(), and biz().
subroutine serai (double precision X, double precision Y, double precision AIR, double precision AII)
Definition at line 933 of file airy.f.
References d, d1mach(), fg, x, and y.
Referenced by aiz().
subroutine seraid (double precision X, double precision Y, double precision AIR, double precision AII)
Definition at line 956 of file airy.f.
References d, d1mach(), fgp(), x, and y.
Referenced by aiz().