Analysis Software: Fe55 Class Reference
Fe55 Class Reference
Public Types
enum { Nhs = 16 }
enum { Nham = Co::Nsumh }
enum { Ncte = 33 }
enum { Zone = 2 }
enum { NZ = 4 }
Public Types inherited from FileF
enum { MaxP = 22 }
enum { MAXIS = 10 }
enum { Lcard = FLEN_CARD }
enum { NbCol = 2 }
typedef pair< string, double > H_Pair
Public Member Functions
Fe55 (string dir_name, const char *outName, const double *Noise, const vector< double > *b_avbuf, const int dofft)
void BaLiC (DataStr *Dev)
void BaLiS (DataStr *Dev)
void PlotBase (void)
void Catalogs (void)
void FitG (TH1D *hm, double *Amp, double *Shift, double *Noise)
void PlotXfit (void)
void PlotSpectra (void)
void PlotXlines (void)
void PlotCTE (void)
void PlotAvHit (void)
void PlotProfiles (void)
void Plot_FFT ()
void PlotHits (void)
~Fe55 ()
Public Member Functions inherited from FileF
FileF ()
~FileF ()
int Open (const char *file_name)
void Close ()
int Read (int copy=0)
void PrimeOut (long Nx, long Ny)
void CloseOut ()
int OpenOutF (const char *fOutName="Out_bufzs")
int OutFitsF (unsigned short *buf)
int getValue (const char *name, double *value)
void PrintKeys (void)
Static Public Member Functions
static double GGF (double *v, double *par)
static double Gauss (double *v, double *par)
Public Attributes
int XminSearch
int XmaxSearch
int YminSearch
int YmaxSearch
double PixSz
double AminSearch [MaxP]
double ANoise [MaxP]
const double HighCut
int Nchan
int ch_idx
int Flag
string dname
string filename
const char * OutExt
FILE * pFlist
FILE * pFreg
FILE * pFcat
const vector< double > * avbuf
double * bufzs
double * bz_save
const int doFFT
FFT * Col
FFT * Row
TH1D * hblc
TH1D * hs [MaxP][Nhs]
TH1D * hfe [MaxP]
TH1D * hmap [MaxP]
TH1D * hpile [MaxP]
TH1D * hclean [MaxP]
TH1D * hYpro [MaxP]
TH1D * hXpro [MaxP]
TH1D * hXtst [MaxP]
TH2D * hYX [MaxP]
TH1F * hNp [MaxP]
TH1F * hNph [MaxP]
TH1F * horm [MaxP]
TH1F * hra [MaxP]
TH1F * hspr [MaxP]
TH1D * hXf [MaxP][7]
TH1D * hSig
TH1D * ham [MaxP][Nham]
TH1D * hXstat [MaxP]
TH1F * xcte [MaxP][Ncte]
TH1F * ycte [MaxP][Ncte]
int NgrX
int NgrY
int Zind
double NKhit [MaxP][NZ]
double AvHit [MaxP][NZ][Co::NXpix][Co::NYpix]
double A2Hit [MaxP][NZ][Co::NXpix][Co::NYpix]
TH2D * AvrHit [MaxP]
TH1D * hpixA [MaxP][Co::NXpix][Co::NYpix]
TH2F * ClustQ [MaxP]
TH2F * Xcte [MaxP]
TH2F * Ycte [MaxP]
TH1D * hitSumA [MaxP]
Public Attributes inherited from FileF
const char * fname
fitsfile * fptr
fitsfile * fout
int iEOF
int Nhdu
int hdu
int hdutype
long * buffer
int anynull
char strnull [10]
int status
char comment [FLEN_CARD]
int bitpix
double bzero
double bscale
int naxis
long naxes [MAXIS]
long nx
long ny
unsigned long npixels
const long fpixel
unsigned short datamin
unsigned short datamax
int Ncards
char card [Lcard]
char value_str [Lcard]
char keyword [Lcard]
double value
double ltv1
double ltv2
double ltm1_1
double ltm1_2
double ltm2_1
double ltm2_2
map< string, double >::iterator H_Iter
std::pair< map< string, double >
::iterator, bool > pptr
map< string, double > mHeader
int lTable
char TableName [FLEN_VALUE]
int ncols
char * ColName [NbCol]
Static Public Attributes
static const float left_margin = (float)0.06
static const float right_margin = (float)0.006
static const float top_margin = (float)0.01
static const float bot_margin = (float)0.04
static const int Npar = 4
Static Public Attributes inherited from FileF
static unsigned short nullval = 0
static const int klength = 8
static const char valuebegin = '='
static const char valuend = '/'
static long nrows
static vector< double > TabData [NbCol]
static const char * FieldName [NbCol] ={"TIMES","CURRENT"}
Detailed Description
Definition at line 1266 of file Fe55_main.dev20190528.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
Nhs
Definition at line 1312 of file Fe55_main.dev20190528.cpp.
anonymous enum
Enumerator:
Nham
Definition at line 1331 of file Fe55_main.dev20190528.cpp.
anonymous enum
Enumerator:
Ncte
Definition at line 1335 of file Fe55_main.dev20190528.cpp.
anonymous enum
Enumerator:
Zone
Definition at line 1338 of file Fe55_main.dev20190528.cpp.
anonymous enum
Enumerator:
NZ
Definition at line 1342 of file Fe55_main.dev20190528.cpp.
Constructor & Destructor Documentation
Fe55::Fe55 (string dir_name, const char * outName, const double * Noise, const vector< double > * b_avbuf, const int dofft)
Sum
Sum
Definition at line 1830 of file Fe55_main.dev20190528.cpp.
References A2Hit, Hits::Acut, OneHit::Acut1, Hits::AcutL, OneHit::AcutL1, AminSearch, Ohit::Amp, ANoise, Hits::arow, AvHit, AvrHit, BaLiS(), bufzs, bz_save, Catalogs(), ch_idx, Ohit::chi2, Ohit::chiR, Ohit::Clear(), FileF::Close(), Ohit::Cluster(), Hits::ClusterMatch(), Hits::ClusterSeed(), ClustQ, Col, Co::ConvGain, Hits::crow, dname, Co::doCTE, doFFT, Co::doFit, double(), FFT::DTrans(), Ohit::efit, fclose(), filename, fit(), Ohit::fitflag, Ohit::FitX(), Ohit::Flag, Flag, FileList::FName, FileList::FName_Iter, fprintf(), G2DI(), Hits::GetRow(), FileF::getValue(), ham, hblc, hclean, FileF::hdu, hfe, hitSumA, hmap, hNp, hNph, horm, hpile, hpixA, hra, hs, hSig, hspr, hXf, hXpro, hXstat, hXtst, hYpro, hYX, i, FileF::iEOF, DataStr::Instance(), it, Ohit::ixb, j, OneHit::jy_c, Ohit::jyb, KeyList, FileF::ltm1_1, FileF::ltm2_2, FileF::ltv1, FileF::ltv2, FileF::MaxP, DataStr::maxX(), DataStr::maxY(), DataStr::minX(), DataStr::minY(), Ohit::MRatio, FileF::naxis, Nchan, Ncte, FileList::Nfile, FFT::Nfreq, NgrX, NgrY, Nham, Hits::NHits, Nhs, Nkey, NKhit, Ohit::Npix, FileF::npixels, Ohit::NpixH, Hits::Nrpix, OneHit::Nrpix1, FileF::nx, Co::NXpix, Ohit::NXsrch, FileF::ny, Co::NYpix, Ohit::NYsrch, NZ, FileF::Open(), OneHit::p_arow, OneHit::p_crow, pFcat, pFlist, pFreg, DataStr::PixSz(), PixSz, printf(), FFT::PSDav, FileF::Read(), Ohit::rms, Row, Qhit::Set(), Ohit::sfit, Ohit::Sum, Ohit::SumCTE, Ohit::Sumf, T1995, title, v, Vval, Hits::Wpad, Hits::Wtime, x, xcte, Xcte, Ohit::xfit, Ohit::xfitG, Ohit::xhit, Ohit::xhitG, XmaxSearch, XminSearch, y, ycte, Ycte, Ohit::yfit, Ohit::yfitG, Ohit::yhit, Ohit::yhitG, YmaxSearch, YminSearch, and Zind.
Fe55::~Fe55 ()
Definition at line 1389 of file Fe55_main.dev20190528.cpp.
Member Function Documentation
void Fe55::BaLiC (DataStr * Dev)
Definition at line 1521 of file Fe55_main.dev20190528.cpp.
References ANoise, avbuf, bufzs, ch_idx, double(), FitG(), hblc, FileF::hdu, hfe, DataStr::IsOver(), j, DataStr::maxX(), DataStr::maxY(), DataStr::minX(), DataStr::minY(), FileF::npixels, FileF::nx, FileF::ny, and printf().
void Fe55::BaLiS (DataStr * Dev)
Definition at line 1564 of file Fe55_main.dev20190528.cpp.
References ANoise, bufzs, ch_idx, FitG(), FileF::hdu, hfe, hs, DataStr::IsOver(), DataStr::IsOverX(), it, j, DataStr::maxX(), DataStr::maxY(), DataStr::minX(), DataStr::minY(), DataStr::NoverX(), FileF::nx, FileF::ny, DataStr::OmaX(), DataStr::OmiX(), and printf().
Referenced by Fe55().
void Fe55::Catalogs (void)
Definition at line 1757 of file Fe55_main.dev20190528.cpp.
References filename, Flag, fprintf(), pFcat, pFlist, pFreg, and printf().
Referenced by Fe55().
void Fe55::FitG (TH1D * hm, double * Amp, double * Shift, double * Noise)
Definition at line 2522 of file Fe55_main.dev20190528.cpp.
References fit(), Gauss(), par0, PeakRange(), and printf().
Referenced by BaLiC(), and BaLiS().
double Fe55::Gauss (double * v, double * par) static
Definition at line 2510 of file Fe55_main.dev20190528.cpp.
References s1, and x.
Referenced by FitG().
double Fe55::GGF (double * v, double * par) static
Definition at line 2401 of file Fe55_main.dev20190528.cpp.
References Co::Ea, Co::Eb, Co::Fano, s1, Co::w_pair, and x.
Referenced by PlotXfit(), and PlotXlines().
void Fe55::Plot_FFT ()
Definition at line 1399 of file Fe55_main.dev20190528.cpp.
References bot_margin, Col, FFT::Freq, FFT::hbuf, i, left_margin, FileF::MaxP, printf(), FFT::PSDav, right_margin, Row, and top_margin.
Referenced by Fe55_main().
void Fe55::PlotAvHit (void)
Definition at line 2558 of file Fe55_main.dev20190528.cpp.
References A2Hit, AvHit, dname, fclose(), Flag, fprintf(), FileF::MaxP, Nchan, NKhit, Co::NXpix, Co::NYpix, NZ, OutExt, printf(), rms(), x, and y.
void Fe55::PlotBase (void)
Definition at line 1697 of file Fe55_main.dev20190528.cpp.
References bot_margin, hs, i, left_margin, FileF::MaxP, Nchan, printf(), right_margin, and top_margin.
Referenced by Fe55_main().
void Fe55::PlotCTE (void)
Definition at line 3625 of file Fe55_main.dev20190528.cpp.
References bot_margin, ClustQ, left_margin, FileF::MaxP, Nchan, right_margin, top_margin, Xcte, and Ycte.
Referenced by Fe55_main().
void Fe55::PlotHits (void)
Definition at line 3752 of file Fe55_main.dev20190528.cpp.
References bot_margin, hitSumA, left_margin, FileF::MaxP, Nchan, printf(), right_margin, and top_margin.
Referenced by Fe55_main().
void Fe55::PlotProfiles (void)
Definition at line 3711 of file Fe55_main.dev20190528.cpp.
References bot_margin, hpixA, left_margin, FileF::MaxP, Nchan, Co::NXpix, Co::NYpix, printf(), right_margin, top_margin, x, and y.
Referenced by Fe55_main().
void Fe55::PlotSpectra (void)
Definition at line 2425 of file Fe55_main.dev20190528.cpp.
References bot_margin, ch_idx, hclean, hfe, hmap, hpile, hXpro, hYpro, hYX, left_margin, FileF::MaxP, Nchan, right_margin, and top_margin.
Referenced by Fe55_main().
void Fe55::PlotXfit (void)
Definition at line 3303 of file Fe55_main.dev20190528.cpp.
References ANoise, bot_margin, Co::Ea, Co::Eb, fit(), GGF(), hSig, hXf, left_margin, FileF::MaxP, Nchan, Co::NeKa, Npar, par0, PeakRange(), printf(), right_margin, and top_margin.
Referenced by Fe55_main().
void Fe55::PlotXlines (void)
Definition at line 2639 of file Fe55_main.dev20190528.cpp.
References ANoise, bot_margin, CteX, CteY, dname, Co::doCTE, double(), Co::Ea, Co::Eb, fclose(), fit(), Flag, fprintf(), GGF(), ham, hNp, hNph, hXstat, i, left_margin, FileF::MaxP, Nchan, Ncte, Co::NeKa, NgrX, NgrY, Nham, Npar, OutExt, par0, PeakRange(), printf(), right_margin, top_margin, Co::w_pair, X, xcte, Xcte, XmaxSearch, Y, ycte, Ycte, and YmaxSearch.
Referenced by Fe55_main().
Member Data Documentation
double Fe55::A2Hit[MaxP][NZ][Co::NXpix][Co::NYpix]
Definition at line 1346 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotAvHit().
double Fe55::AminSearch[MaxP]
Definition at line 1283 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
double Fe55::ANoise[MaxP]
Definition at line 1284 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiC(), BaLiS(), Fe55(), PlotXfit(), and PlotXlines().
const vector<double>* Fe55::avbuf
Definition at line 1300 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiC().
double Fe55::AvHit[MaxP][NZ][Co::NXpix][Co::NYpix]
Definition at line 1345 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotAvHit().
TH2D* Fe55::AvrHit[MaxP]
Definition at line 1347 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
const float Fe55::bot_margin = (float)0.04 static
Definition at line 1272 of file Fe55_main.dev20190528.cpp.
Referenced by Plot_FFT(), PlotBase(), PlotCTE(), PlotHits(), PlotProfiles(), PlotSpectra(), PlotXfit(), and PlotXlines().
double* Fe55::bufzs
Definition at line 1302 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiC(), BaLiS(), and Fe55().
double* Fe55::bz_save
Definition at line 1303 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
int Fe55::ch_idx
Definition at line 1288 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiC(), BaLiS(), Fe55(), and PlotSpectra().
TH2F* Fe55::ClustQ[MaxP]
Definition at line 1350 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotCTE().
FFT* Fe55::Col
Definition at line 1307 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and Plot_FFT().
string Fe55::dname
Definition at line 1292 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), PlotAvHit(), and PlotXlines().
const int Fe55::doFFT
Definition at line 1306 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
string Fe55::filename
Definition at line 1293 of file Fe55_main.dev20190528.cpp.
Referenced by Catalogs(), and Fe55().
int Fe55::Flag
Definition at line 1290 of file Fe55_main.dev20190528.cpp.
Referenced by Catalogs(), Fe55(), Fe55_main(), PlotAvHit(), and PlotXlines().
TH1D* Fe55::ham[MaxP][Nham]
Definition at line 1332 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
TH1D* Fe55::hblc
Definition at line 1311 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiC(), and Fe55().
TH1D* Fe55::hclean[MaxP]
Definition at line 1317 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotSpectra().
TH1D* Fe55::hfe[MaxP]
Definition at line 1314 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiC(), BaLiS(), Fe55(), and PlotSpectra().
const double Fe55::HighCut
Definition at line 1285 of file Fe55_main.dev20190528.cpp.
TH1D* Fe55::hitSumA[MaxP]
Definition at line 1354 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotHits().
TH1D* Fe55::hmap[MaxP]
Definition at line 1315 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotSpectra().
TH1F* Fe55::hNp[MaxP]
Definition at line 1322 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
TH1F* Fe55::hNph[MaxP]
Definition at line 1323 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
TH1F* Fe55::horm[MaxP]
Definition at line 1324 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
TH1D* Fe55::hpile[MaxP]
Definition at line 1316 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotSpectra().
TH1D* Fe55::hpixA[MaxP][Co::NXpix][Co::NYpix]
Definition at line 1348 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotProfiles().
TH1F* Fe55::hra[MaxP]
Definition at line 1325 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
TH1D* Fe55::hs[MaxP][Nhs]
Definition at line 1313 of file Fe55_main.dev20190528.cpp.
Referenced by BaLiS(), Fe55(), and PlotBase().
TH1D* Fe55::hSig
Definition at line 1329 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXfit().
TH1F* Fe55::hspr[MaxP]
Definition at line 1326 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
TH1D* Fe55::hXf[MaxP][7]
Definition at line 1328 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXfit().
TH1D* Fe55::hXpro[MaxP]
Definition at line 1319 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotSpectra().
TH1D* Fe55::hXstat[MaxP]
Definition at line 1333 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
TH1D* Fe55::hXtst[MaxP]
Definition at line 1320 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
TH1D* Fe55::hYpro[MaxP]
Definition at line 1318 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotSpectra().
TH2D* Fe55::hYX[MaxP]
Definition at line 1321 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotSpectra().
const float Fe55::left_margin = (float)0.06 static
Definition at line 1269 of file Fe55_main.dev20190528.cpp.
Referenced by Plot_FFT(), PlotBase(), PlotCTE(), PlotHits(), PlotProfiles(), PlotSpectra(), PlotXfit(), and PlotXlines().
int Fe55::Nchan
Definition at line 1287 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), PlotAvHit(), PlotBase(), PlotCTE(), PlotHits(), PlotProfiles(), PlotSpectra(), PlotXfit(), and PlotXlines().
int Fe55::NgrX
Definition at line 1339 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
int Fe55::NgrY
Definition at line 1340 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
double Fe55::NKhit[MaxP][NZ]
Definition at line 1344 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotAvHit().
const int Fe55::Npar = 4 static
Definition at line 1275 of file Fe55_main.dev20190528.cpp.
Referenced by PlotXfit(), and PlotXlines().
const char* Fe55::OutExt
Definition at line 1294 of file Fe55_main.dev20190528.cpp.
Referenced by PlotAvHit(), and PlotXlines().
FILE* Fe55::pFcat
Definition at line 1297 of file Fe55_main.dev20190528.cpp.
Referenced by Catalogs(), and Fe55().
FILE* Fe55::pFlist
Definition at line 1295 of file Fe55_main.dev20190528.cpp.
Referenced by Catalogs(), and Fe55().
FILE* Fe55::pFreg
Definition at line 1296 of file Fe55_main.dev20190528.cpp.
Referenced by Catalogs(), and Fe55().
double Fe55::PixSz
Definition at line 1282 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
const float Fe55::right_margin = (float)0.006 static
Definition at line 1270 of file Fe55_main.dev20190528.cpp.
Referenced by Plot_FFT(), PlotBase(), PlotCTE(), PlotHits(), PlotProfiles(), PlotSpectra(), PlotXfit(), and PlotXlines().
FFT* Fe55::Row
Definition at line 1308 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and Plot_FFT().
const float Fe55::top_margin = (float)0.01 static
Definition at line 1271 of file Fe55_main.dev20190528.cpp.
Referenced by Plot_FFT(), PlotBase(), PlotCTE(), PlotHits(), PlotProfiles(), PlotSpectra(), PlotXfit(), and PlotXlines().
TH1F* Fe55::xcte[MaxP][Ncte]
Definition at line 1336 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
TH2F* Fe55::Xcte[MaxP]
Definition at line 1351 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), PlotCTE(), and PlotXlines().
int Fe55::XmaxSearch
Definition at line 1279 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
int Fe55::XminSearch
Definition at line 1278 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
TH1F* Fe55::ycte[MaxP][Ncte]
Definition at line 1337 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
TH2F* Fe55::Ycte[MaxP]
Definition at line 1352 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), PlotCTE(), and PlotXlines().
int Fe55::YmaxSearch
Definition at line 1281 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55(), and PlotXlines().
int Fe55::YminSearch
Definition at line 1280 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
int Fe55::Zind
Definition at line 1343 of file Fe55_main.dev20190528.cpp.
Referenced by Fe55().
The documentation for this class was generated from the following file:
analysis/blob/master/TPC/DAMAlgorithm/Fe55_main.dev20190528.cpp