Analysis Software: macros/blob/master/macros/QA/calorimeter/QA_Draw_Calorimeter_Sum_TrackProj.C File Reference
QA_Draw_Calorimeter_Sum_TrackProj.C File Reference
#include <TFile.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include <string>
#include <vector>
#include "../../sPHENIXStyle/sPhenixStyle.C"
#include "QA_Draw_Utility.C"
Functions
void QA_Draw_Calorimeter_Sum_TrackProj (const char *qa_file_name_new="/phenix/u/jinhuang/links/ePHENIX_work/sPHENIX_work/production_analysis_updates/spacal1d/fieldmap/G4Hits_sPHENIX_pi-_eta0.30_32GeV-0000.root_qa.root", const char *qa_file_name_ref="/phenix/u/jinhuang/links/ePHENIX_work/sPHENIX_work/production_analysis_updates/spacal1d/fieldmap/G4Hits_sPHENIX_pi+_eta0.30_32GeV-0000.root_qa.root")
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file QA_Draw_Calorimeter_Sum_TrackProj.C.
Function Documentation
void QA_Draw_Calorimeter_Sum_TrackProj (const char * qa_file_name_new = "/phenix/u/jinhuang/links/ePHENIX_work/sPHENIX_work/production_analysis_updates/spacal1d/fieldmap/G4Hits_sPHENIX_pi-_eta0.30_32GeV-0000.root_qa.root", const char * qa_file_name_ref = "/phenix/u/jinhuang/links/ePHENIX_work/sPHENIX_work/production_analysis_updates/spacal1d/fieldmap/G4Hits_sPHENIX_pi+_eta0.30_32GeV-0000.root_qa.root")
Definition at line 26 of file QA_Draw_Calorimeter_Sum_TrackProj.C.
References assert, DrawReference(), i, SaveCanvas(), and SetsPhenixStyle().