Analysis Software: FastJetAlgoSub Class Reference
FastJetAlgoSub Class Reference
#include <coresoftware/blob/master/offline/packages/jetbackground/FastJetAlgoSub.h>
Public Member Functions
FastJetAlgoSub (Jet::ALGO algo, float par, float verbosity=0)
virtual ~FastJetAlgoSub ()
void identify (std::ostream &os=std::cout)
Jet::ALGO get_algo ()
float get_par ()
std::vector< Jet * > get_jets (std::vector< Jet * > particles)
Public Member Functions inherited from JetAlgo
virtual ~JetAlgo ()
Private Attributes
int _verbosity
Jet::ALGO _algo
float _par
Additional Inherited Members
Protected Member Functions inherited from JetAlgo
JetAlgo ()
Detailed Description
Definition at line 11 of file FastJetAlgoSub.h.
Constructor & Destructor Documentation
FastJetAlgoSub::FastJetAlgoSub (Jet::ALGO algo, float par, float verbosity = 0)
Definition at line 22 of file FastJetAlgoSub.cc.
References _verbosity.
virtual FastJetAlgoSub::~FastJetAlgoSub () inline virtual
Definition at line 15 of file FastJetAlgoSub.h.
Member Function Documentation
Jet::ALGO FastJetAlgoSub::get_algo () inline virtual
Reimplemented from JetAlgo.
Definition at line 18 of file FastJetAlgoSub.h.
References _algo.
std::vector< Jet * > FastJetAlgoSub::get_jets (std::vector< Jet * > particles) virtual
Reimplemented from JetAlgo.
Definition at line 53 of file FastJetAlgoSub.cc.
References _algo, _par, _verbosity, Jet::ANTIKT, Jet::begin_comp(), Jet::CAMBRIDGE, Jet::end_comp(), Jet::get_e(), Jet::get_eta(), Jet::get_phi(), Jet::get_pt(), Jet::get_px(), Jet::get_py(), Jet::get_pz(), Jet::insert_comp(), Jet::KT, Jet::set_e(), Jet::set_id(), Jet::set_px(), Jet::set_py(), and Jet::set_pz().
float FastJetAlgoSub::get_par () inline virtual
Reimplemented from JetAlgo.
Definition at line 19 of file FastJetAlgoSub.h.
References _par.
void FastJetAlgoSub::identify (std::ostream & os = std::cout) virtual
Reimplemented from JetAlgo.
Definition at line 41 of file FastJetAlgoSub.cc.
References _algo, _par, Jet::ANTIKT, Jet::CAMBRIDGE, and Jet::KT.
Member Data Documentation
Jet::ALGO FastJetAlgoSub::_algo private
Definition at line 25 of file FastJetAlgoSub.h.
Referenced by get_algo(), get_jets(), and identify().
float FastJetAlgoSub::_par private
Definition at line 26 of file FastJetAlgoSub.h.
Referenced by get_jets(), get_par(), and identify().
int FastJetAlgoSub::_verbosity private
Definition at line 24 of file FastJetAlgoSub.h.
Referenced by FastJetAlgoSub(), and get_jets().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbackground/FastJetAlgoSub.h
coresoftware/blob/master/offline/packages/jetbackground/FastJetAlgoSub.cc