Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Range (0, 0, 1, 1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetLeftMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetRightMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetTopMargin (0.05)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetBottomMargin (0.16)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Draw ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 cd ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Range (-20.25316,-0.3422642, 106.3291, 1.796887)
h_b_copy846930886 SetBinContent (4, 1)
h_b_copy846930886 SetBinContent (5, 1)
h_b_copy846930886 SetBinContent (6, 1)
h_b_copy846930886 SetBinContent (7, 1)
h_b_copy846930886 SetBinContent (8, 1)
h_b_copy846930886 SetBinContent (9, 1)
h_b_copy846930886 SetBinContent (10, 1)
h_b_copy846930886 SetBinError (4, 0.005565988)
h_b_copy846930886 SetBinError (5, 0.01338334)
h_b_copy846930886 SetBinError (6, 0.03057812)
h_b_copy846930886 SetBinError (7, 0.06730322)
h_b_copy846930886 SetBinError (8, 0.1643582)
h_b_copy846930886 SetBinError (9, 0.3675161)
h_b_copy846930886 SetBinError (10, 0.6094566)
h_b_copy846930886 SetEntries (58360)
h_b_copy846930886 SetLineColor (ci)
h_b_copy846930886 SetLineWidth (2)
h_b_copy846930886 SetMarkerStyle (20)
h_b_copy846930886 SetMarkerSize (1.2)
h_b_copy846930886 GetXaxis () -> SetTitle("p_
h_b_copy846930886 GetYaxis () -> SetTitle("Relative Cross Section and Uncertainty")
h_b_copy846930886 GetZaxis () -> SetLabelFont(42)
h_b_copy846930886 Draw ("")
h_b_copy1681692777 SetBinContent (4, 0.6)
h_b_copy1681692777 SetBinContent (5, 0.6)
h_b_copy1681692777 SetBinContent (6, 0.6)
h_b_copy1681692777 SetBinContent (7, 0.6)
h_b_copy1681692777 SetBinContent (8, 0.6)
h_b_copy1681692777 SetBinContent (9, 0.6)
h_b_copy1681692777 SetBinContent (10, 0.6)
h_b_copy1681692777 Draw ("same")
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetSelected (Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45)
Variables
TPad * Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 = new TPad("Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45_1", "Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45_1",0.01,0.01,0.99,0.99)
TH1F * h_b_copy846930886 = new TH1F("h_b_copy846930886","",20,0,100)
Int_t ci = TColor::GetColor("#ff0000")
TColor * color
TH1F * h_b_copy1681692777 = new TH1F("h_b_copy1681692777","",20,0,100)
Function Documentation
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 cd ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Draw ()
h_b_copy846930886 Draw ("")
h_b_copy1681692777 Draw ("same")
h_b_copy846930886 GetXaxis () -> SetTitle("p_
Definition at line 61 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C.
h_b_copy846930886 GetYaxis () -> SetTitle("Relative Cross Section and Uncertainty")
Definition at line 51 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA.C.
h_b_copy846930886 GetZaxis () -> SetLabelFont(42)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Modified ()
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Range (0 , 0 , 1 , 1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 Range (-20. 25316, -0. 3422642, 106. 3291, 1. 796887)
h_b_copy846930886 SetBinContent (4 , 1)
h_b_copy846930886 SetBinContent (5 , 1)
h_b_copy846930886 SetBinContent (6 , 1)
h_b_copy846930886 SetBinContent (7 , 1)
h_b_copy846930886 SetBinContent (8 , 1)
h_b_copy846930886 SetBinContent (9 , 1)
h_b_copy846930886 SetBinContent (10 , 1)
h_b_copy1681692777 SetBinContent (4 , 0. 6)
h_b_copy1681692777 SetBinContent (5 , 0. 6)
h_b_copy1681692777 SetBinContent (6 , 0. 6)
h_b_copy1681692777 SetBinContent (7 , 0. 6)
h_b_copy1681692777 SetBinContent (8 , 0. 6)
h_b_copy1681692777 SetBinContent (9 , 0. 6)
h_b_copy1681692777 SetBinContent (10 , 0. 6)
h_b_copy1681692777 SetBinError (4 , 0. 005565988)
h_b_copy1681692777 SetBinError (5 , 0. 01338334)
h_b_copy1681692777 SetBinError (6 , 0. 03057812)
h_b_copy1681692777 SetBinError (7 , 0. 06730322)
h_b_copy1681692777 SetBinError (8 , 0. 1643582)
h_b_copy1681692777 SetBinError (9 , 0. 3675161)
h_b_copy1681692777 SetBinError (10 , 0. 6094566)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetBorderSize (2)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetBottomMargin (0. 16)
h_b_copy1681692777 SetEntries (58360)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetFillColor (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetFrameBorderMode (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetLeftMargin (0. 16)
entry SetLineColor (ci)
h_b_copy846930886 SetLineWidth (2)
h_b_copy846930886 SetMarkerSize (1. 2)
h_b_copy846930886 SetMarkerStyle (20)
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetRightMargin (0. 05)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetSelected (Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0. 45)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetTickx (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetTicky (1)
Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 SetTopMargin (0. 05)
Variable Documentation
ci = TColor::GetColor("#ff0000")
Definition at line 54 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C.
Referenced by fg(), fgp(), MakeShowerGraph(), pycdiv(), and pyrnmq().
TColor* color
Definition at line 55 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C.
Referenced by PHG4TpcDisplayAction::ApplyDisplayAction(), ChargePerLayer(), DrawTpcPrototypeGenFitTrkFitter_Summary(), getResolutions(), and MakeShowerGraph().
TPad* Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0 = new TPad("Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45_1", "Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45_1",0.01,0.01,0.99,0.99)
Definition at line 21 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C.
TH1F* h_b_copy1681692777 = new TH1F("h_b_copy1681692777","",20,0,100)
Definition at line 80 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C.
TH1F* h_b_copy846930886 = new TH1F("h_b_copy846930886","",20,0,100)
Definition at line 37 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root_Draw_HFJetTruth_CrossSection2RAA_Ratio_deta0.45.C.