Analysis Software: InttClusterizer Class Reference
InttClusterizer Class Reference
#include <coresoftware/blob/master/offline/packages/intt/InttClusterizer.h>
Public Member Functions
InttClusterizer (const std::string &name="InttClusterizer", unsigned int min_layer=0, unsigned int max_layer=UINT_MAX)
virtual ~InttClusterizer ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void set_threshold (const float fraction_of_mip)
set an energy requirement relative to the thickness MIP expectation
float get_threshold_by_layer (const int layer) const
void set_z_clustering (const int layer, const bool make_z_clustering)
option to turn off z-dimension clustering
bool get_z_clustering (const int layer) const
void set_energy_weighting (const int layer, const bool make_e_weights)
option to turn on/off energy weighted clustering
bool get_energy_weighting (const int layer) const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool ladder_are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > &lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > &rhs, const int layer)
void CalculateLadderThresholds (PHCompositeNode *topNode)
void ClusterLadderCells (PHCompositeNode *topNode)
void PrintClusters (PHCompositeNode *topNode)
Private Attributes
TrkrHitSetContainer * m_hits
TrkrClusterContainer * m_clusterlist
TrkrClusterHitAssoc * m_clusterhitassoc
float _fraction_of_mip
std::map< int, float > _thresholds_by_layer
std::map< int, bool > _make_z_clustering
std::map< int, bool > _make_e_weights
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 19 of file InttClusterizer.h.
Constructor & Destructor Documentation
InttClusterizer::InttClusterizer (const std::string & name = "InttClusterizer", unsigned int min_layer = 0, unsigned int max_layer = UINT_MAX)
Definition at line 67 of file InttClusterizer.cc.
virtual InttClusterizer::~InttClusterizer () inline virtual
Definition at line 24 of file InttClusterizer.h.
Member Function Documentation
void InttClusterizer::CalculateLadderThresholds (PHCompositeNode * topNode) private
Definition at line 216 of file InttClusterizer.cc.
References _fraction_of_mip, _make_e_weights, _make_z_clustering, _thresholds_by_layer, and PHG4CylinderGeomContainer::get_begin_end().
Referenced by InitRun().
void InttClusterizer::ClusterLadderCells (PHCompositeNode * topNode) private
Definition at line 254 of file InttClusterizer.cc.
References _make_e_weights, TrkrClusterHitAssoc::addAssoc(), col, CylinderGeomIntt::find_segment_center(), CylinderGeomIntt::find_strip_center(), TrkrClusterContainer::findOrAddCluster(), G, InttDefs::genClusKey(), CylinderGeomIntt::get_strip_phi_tilt(), CylinderGeomIntt::get_strip_y_spacing(), CylinderGeomIntt::get_strip_z_spacing(), CylinderGeomIntt::get_thickness(), InttDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSet::getHitSetKey(), TrkrHitSetContainer::getHitSets(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), InttDefs::getRow(), i, TrkrClusterHitAssoc::identify(), TrkrHitSet::identify(), TrkrDefs::inttId, j, ladder_are_adjacent(), m_clusterhitassoc, m_clusterlist, m_hits, phibins, and Fun4AllBase::Verbosity().
Referenced by process_event().
int InttClusterizer::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 36 of file InttClusterizer.h.
bool InttClusterizer::get_energy_weighting (const int layer) const inline
Definition at line 65 of file InttClusterizer.h.
References _make_e_weights.
float InttClusterizer::get_threshold_by_layer (const int layer) const inline
Definition at line 43 of file InttClusterizer.h.
References _thresholds_by_layer.
bool InttClusterizer::get_z_clustering (const int layer) const inline
Definition at line 54 of file InttClusterizer.h.
References _make_z_clustering.
int InttClusterizer::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 27 of file InttClusterizer.h.
int InttClusterizer::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 81 of file InttClusterizer.cc.
References _fraction_of_mip, _make_e_weights, _make_z_clustering, _thresholds_by_layer, Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), CalculateLadderThresholds(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
bool InttClusterizer::ladder_are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > & lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > & rhs, const int layer) private
Definition at line 43 of file InttClusterizer.cc.
References InttDefs::getCol(), and InttDefs::getRow().
Referenced by ClusterLadderCells().
void InttClusterizer::PrintClusters (PHCompositeNode * topNode) private
Definition at line 562 of file InttClusterizer.cc.
References TrkrClusterContainer::identify(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int InttClusterizer::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 183 of file InttClusterizer.cc.
References Fun4AllReturnCodes::ABORTRUN, ClusterLadderCells(), Fun4AllReturnCodes::EVENT_OK, m_clusterhitassoc, m_clusterlist, m_hits, PHWHERE, and PrintClusters().
void InttClusterizer::set_energy_weighting (const int layer, const bool make_e_weights) inline
option to turn on/off energy weighted clustering
Definition at line 61 of file InttClusterizer.h.
References _make_e_weights.
void InttClusterizer::set_threshold (const float fraction_of_mip) inline
set an energy requirement relative to the thickness MIP expectation
Definition at line 39 of file InttClusterizer.h.
References _fraction_of_mip.
void InttClusterizer::set_z_clustering (const int layer, const bool make_z_clustering) inline
option to turn off z-dimension clustering
Definition at line 50 of file InttClusterizer.h.
References _make_z_clustering.
Referenced by Tracking_Clus().
Member Data Documentation
float InttClusterizer::_fraction_of_mip private
Definition at line 86 of file InttClusterizer.h.
Referenced by CalculateLadderThresholds(), InitRun(), and set_threshold().
std::map<int, bool> InttClusterizer::_make_e_weights private
Definition at line 89 of file InttClusterizer.h.
Referenced by CalculateLadderThresholds(), ClusterLadderCells(), get_energy_weighting(), InitRun(), and set_energy_weighting().
std::map<int, bool> InttClusterizer::_make_z_clustering private
Definition at line 88 of file InttClusterizer.h.
Referenced by CalculateLadderThresholds(), get_z_clustering(), InitRun(), and set_z_clustering().
std::map<int, float> InttClusterizer::_thresholds_by_layer private
Definition at line 87 of file InttClusterizer.h.
Referenced by CalculateLadderThresholds(), get_threshold_by_layer(), and InitRun().
TrkrClusterHitAssoc* InttClusterizer::m_clusterhitassoc private
Definition at line 82 of file InttClusterizer.h.
Referenced by ClusterLadderCells(), and process_event().
TrkrClusterContainer* InttClusterizer::m_clusterlist private
Definition at line 81 of file InttClusterizer.h.
Referenced by ClusterLadderCells(), and process_event().
TrkrHitSetContainer* InttClusterizer::m_hits private
Definition at line 80 of file InttClusterizer.h.
Referenced by ClusterLadderCells(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/intt/InttClusterizer.h
coresoftware/blob/master/offline/packages/intt/InttClusterizer.cc