Analysis Software: PHGenFit::PlanarMeasurement Class Reference
PHGenFit::PlanarMeasurement Class Reference
#include <coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h>
Public Member Functions
PlanarMeasurement (const TVector3 &pos, const TVector3 &u, const TVector3 &v, const double du, const double dv)
ctor
PlanarMeasurement (const TVector3 &pos, const TVector3 &n, const double du, const double dv)
void init (const TVector3 &pos, const TVector3 &u, const TVector3 &v, const double du, const double dv)
~PlanarMeasurement ()
dtor
Public Member Functions inherited from PHGenFit::Measurement
Measurement ()
ctor
~Measurement ()
dtor
genfit::AbsMeasurement * getMeasurement ()
unsigned int get_cluster_ID () const
void set_cluster_ID (unsigned int clusterId)
TrkrDefs::cluskey get_cluster_key () const
void set_cluster_key (TrkrDefs::cluskey clusterkey)
Additional Inherited Members
Protected Attributes inherited from PHGenFit::Measurement
genfit::AbsMeasurement * _measurement
unsigned int _clusterID
TrkrDefs::cluskey _clusterkey
Detailed Description
Definition at line 16 of file PlanarMeasurement.h.
Constructor & Destructor Documentation
PHGenFit::PlanarMeasurement::PlanarMeasurement (const TVector3 & pos, const TVector3 & u, const TVector3 & v, const double du, const double dv)
ctor
Definition at line 45 of file PlanarMeasurement.cc.
References init().
PHGenFit::PlanarMeasurement::PlanarMeasurement (const TVector3 & pos, const TVector3 & n, const double du, const double dv)
Mainly for "n" in xy plane, or n.z() = 0; In this case, According to https://root.cern.ch/doc/master/TVector3_8h_source.html#l00301 u = n.Orthogonal() is always in xy plane v = n x u, is along z direction. If z is not 0, but z <= x or y, then u will still be in xy plane, phi direction error, but v will not be along z axis.
Definition at line 50 of file PlanarMeasurement.cc.
References init(), and v.
PHGenFit::PlanarMeasurement::~PlanarMeasurement () inline
dtor
Definition at line 27 of file PlanarMeasurement.h.
Member Function Documentation
void PHGenFit::PlanarMeasurement::init (const TVector3 & pos, const TVector3 & u, const TVector3 & v, const double du, const double dv)
Definition at line 22 of file PlanarMeasurement.cc.
References PHGenFit::Measurement::_measurement.
Referenced by PlanarMeasurement().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.cc