Analysis Software: analysis/blob/master/ForwardTracking/macros/ePHENIXFieldRICH.m File Reference
ePHENIXFieldRICH.m File Reference
Functions
fclose (fileID)
Variables
close all clear all RICH input p_RICH_Ref = 10
n_index = 1.00137
CF4 Theta_max = acos(1./n_index)*1000
mrad MaxLength = 350
etas = [1.02:.05:1.3,1.4:.2:3, 3:.5:4]'
N_step = 1000
open field map file1 = 'DrawFieldMap_hfield_sPHENIX.2d.root.data'
file2 = 'DrawFieldMap_hfield_fsPHENIX.2d.root.data'
fileID = fopen(file1)
data1 = fscanf(fileID,'%f%f%f%f\n', [4 Inf])'
resampling bc1 = griddata(data1(:,2),data1(:,1),data1(:,4),0,0,'natural')
data1_scale = 1.4/1.5
br1 = griddata(data1(:,2),data1(:,1),data1(:,3),Z,R,'natural') .* data1_scale
bz1 = griddata(data1(:,2),data1(:,1),data1(:,4),Z,R,'natural') .* data1_scale
b1 = sqrt(br1.^2 + bz1.^2)
RICH trajectory sampling thetas = (2. .* atan(exp(-etas))) * ones(1, N_step)
trajectory_step = ones(size(etas)) * linspace(0,MaxLength,N_step)
step = MaxLength ./ (N_step-1)
trajectory_r = sin(thetas) .* trajectory_step
trajectory_z = cos(thetas) .* trajectory_step
Field mapping trajectory_br = griddata(data1(:,2),data1(:,1),data1(:,3),trajectory_z,trajectory_r,'natural') .* data1_scale
trajectory_bz = griddata(data1(:,2),data1(:,1),data1(:,4),trajectory_z,trajectory_r,'natural') .* data1_scale
bending B trajectory_bt = trajectory_bz.*cos(thetas + pi ./ 2) + trajectory_br.*sin(thetas + pi ./ 2)
longitudinal B trajectory_bl = trajectory_bz.*cos(thetas) + trajectory_br.*sin(thetas)
angular kicks BdL in T *m trajectory_bdL = 0.01 .* step.* cumsum(trajectory_bt,2)
trajectory_angle_kick = 0.3 .* trajectory_bdL ./ p_RICH_Ref
ring spread RICH_volumne_cut = IsInCurvedRich(trajectory_z, etas * ones(1, N_step))
std_RICH = zeros(size(etas))
for trajectory
end ring plot ylim = 8.01e-2*Theta_max
max mrad font_size = 17
m2014 = matfile('BABAR_V11_StationCuts_Z5.0cm_300.0cm.mat')
Function Documentation
fclose (fileID)
Variable Documentation
b1 = sqrt(br1.^2 + bz1.^2)
Definition at line 37 of file ePHENIXFieldRICH.m.
Referenced by __example_3.f__(), biz(), PgPostBankManager::createBank(), fgp1(), fgp2(), fgp3(), flap(), flap1(), flap2(), genevent(), get_parametrization_F2(), jewel(), mednextevt(), plot_compare_fun4all_eicroot(), plot_track_multi(), profile(), pyalps(), pyeig4(), pytbbn(), hcalUtil::twrMipFit(), hcalUtil::twrTimeFit(), and ulalps().
resampling bc1 = griddata(data1(:,2),data1(:,1),data1(:,4),0,0,'natural')
Definition at line 29 of file ePHENIXFieldRICH.m.
br1 = griddata(data1(:,2),data1(:,1),data1(:,3),Z,R,'natural') .* data1_scale
Definition at line 35 of file ePHENIXFieldRICH.m.
bz1 = griddata(data1(:,2),data1(:,1),data1(:,4),Z,R,'natural') .* data1_scale
Definition at line 36 of file ePHENIXFieldRICH.m.
data1 = fscanf(fileID,'%f%f%f%f\n', [4 Inf])'
Definition at line 24 of file ePHENIXFieldRICH.m.
data1_scale = 1.4/1.5
Definition at line 30 of file ePHENIXFieldRICH.m.
etas = [1.02:.05:1.3,1.4:.2:3, 3:.5:4]'
Definition at line 14 of file ePHENIXFieldRICH.m.
Referenced by eicsmear_check_calorimeter(), eicsmear_check_tracking(), and Load_CurveSet().
open field map file1 = 'DrawFieldMap_hfield_sPHENIX.2d.root.data'
Definition at line 20 of file ePHENIXFieldRICH.m.
Referenced by ParticleShowerSizeHistoMaker().
file2 = 'DrawFieldMap_hfield_fsPHENIX.2d.root.data'
Definition at line 21 of file ePHENIXFieldRICH.m.
Referenced by ParticleShowerSizeHistoMaker().
fileID = fopen(file1)
Definition at line 23 of file ePHENIXFieldRICH.m.
max mrad font_size = 17
Definition at line 81 of file ePHENIXFieldRICH.m.
m2014 = matfile('BABAR_V11_StationCuts_Z5.0cm_300.0cm.mat')
Definition at line 83 of file ePHENIXFieldRICH.m.
mrad MaxLength = 350
Definition at line 13 of file ePHENIXFieldRICH.m.
CF4 n_index = 1.00137
Definition at line 7 of file ePHENIXFieldRICH.m.
N_step = 1000
Definition at line 15 of file ePHENIXFieldRICH.m.
close all clear all RICH input p_RICH_Ref = 10
Definition at line 6 of file ePHENIXFieldRICH.m.
ring spread RICH_volumne_cut = IsInCurvedRich(trajectory_z, etas * ones(1, N_step))
Definition at line 70 of file ePHENIXFieldRICH.m.
std_RICH = zeros(size(etas))
Definition at line 72 of file ePHENIXFieldRICH.m.
step = MaxLength ./ (N_step-1)
Definition at line 44 of file ePHENIXFieldRICH.m.
Referenced by DataAna(), DataAna2(), EnergyGlance(), FillEnergy(), LaplaceSolution::FindBetamn(), Interlopation0Degree(), InterlopationV4(), InterlopationV4reverse(), langaufun(), ProjectionReverse(), ProjectionReverse2(), ReadHis(), ReadHis2(), ReadHis3(), and BEmcRec::TwoGamma().
CF4 Theta_max = acos(1./n_index)*1000
Definition at line 10 of file ePHENIXFieldRICH.m.
RICH trajectory sampling thetas = (2. .* atan(exp(-etas))) * ones(1, N_step)
Definition at line 41 of file ePHENIXFieldRICH.m.
for trajectory
Initial value:
= 1:size(etas)
    std_RICH(trajectory) = std(trajectory_angle_kick(trajectory,RICH_volumne_cut(trajectory,:)))
Definition at line 73 of file ePHENIXFieldRICH.m.
trajectory_angle_kick = 0.3 .* trajectory_bdL ./ p_RICH_Ref
Definition at line 66 of file ePHENIXFieldRICH.m.
angular kicks BdL in T* m trajectory_bdL = 0.01 .* step.* cumsum(trajectory_bt,2)
Definition at line 65 of file ePHENIXFieldRICH.m.
longitudinal B trajectory_bl = trajectory_bz.*cos(thetas) + trajectory_br.*sin(thetas)
Definition at line 58 of file ePHENIXFieldRICH.m.
Field mapping trajectory_br = griddata(data1(:,2),data1(:,1),data1(:,3),trajectory_z,trajectory_r,'natural') .* data1_scale
Definition at line 52 of file ePHENIXFieldRICH.m.
bending B trajectory_bt = trajectory_bz.*cos(thetas + pi ./ 2) + trajectory_br.*sin(thetas + pi ./ 2)
Definition at line 56 of file ePHENIXFieldRICH.m.
trajectory_bz = griddata(data1(:,2),data1(:,1),data1(:,4),trajectory_z,trajectory_r,'natural') .* data1_scale
Definition at line 53 of file ePHENIXFieldRICH.m.
trajectory_r = sin(thetas) .* trajectory_step
Definition at line 46 of file ePHENIXFieldRICH.m.
trajectory_step = ones(size(etas)) * linspace(0,MaxLength,N_step)
Definition at line 43 of file ePHENIXFieldRICH.m.
trajectory_z = cos(thetas) .* trajectory_step
Definition at line 47 of file ePHENIXFieldRICH.m.
end ring plot ylim = 8.01e-2*Theta_max
Definition at line 80 of file ePHENIXFieldRICH.m.