Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/macros/Draw_HFJetTruth_InvMass.C File Reference
Draw_HFJetTruth_InvMass.C File Reference
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
void Draw_HFJetTruth_InvMass (const TString infile="/sphenix/user/jinhuang/HF-jet/event_gen/200pp_pythia8_CTEQ6L_7GeV/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root", double int_lumi=891093/3.332e-02/1e9, const double dy=0.6 *2)
void DrawCrossSection (double int_lumi, const double dy)
void Draw_HFJetTruth_InvMass_DrawCrossSection_PR (const TString infile)
void CrossSection2RAA (const TString infile, const bool use_AA_jet_trigger=true, const double dy=.7 *2)
TGraphErrors * GetRAA (TH1 *h_pp, TH1 *h_AA)
TH1 * CrossSection2RelUncert (const TH1F *h_cross, const double suppression, const double deta, const double pp_quiv_int_lum)
void Convert2CrossSection (TH1 *h, const double int_lumi, const double dy)
TGraphAsymmErrors * GetSTAR2019 (const TString hepdata="/sphenix/user/jinhuang/HF-jet/event_gen/HEPData-ins1493842-v1-Table_4.root")
TGraph * GetRAAKang2019 (const int mass=1, const double g=1.8)
TGraph * GetRAARatioKang2019 (const int mass=1, const double g=1.8)
Variables
TFile * _file0 = NULL
TTree * T = NULL
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file Draw_HFJetTruth_InvMass.C.
Function Documentation
void Convert2CrossSection (TH1 * h, const double int_lumi, const double dy)
Definition at line 558 of file Draw_HFJetTruth_InvMass.C.
References dy, and i.
void CrossSection2RAA (const TString infile, const bool use_AA_jet_trigger = true, const double dy = .7 * 2)
Definition at line 277 of file Draw_HFJetTruth_InvMass.C.
References assert, CrossSection2RelUncert(), dy, GetRAA(), GetRAAKang2019(), GetRAARatioKang2019(), h_b, hall, leg, and SaveCanvas().
TH1* CrossSection2RelUncert (const TH1F * h_cross, const double suppression, const double deta, const double pp_quiv_int_lum)
Definition at line 519 of file Draw_HFJetTruth_InvMass.C.
References assert, and i.
void Draw_HFJetTruth_InvMass (const TString infile = "/sphenix/user/jinhuang/HF-jet/event_gen/200pp_pythia8_CTEQ6L_7GeV/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root", double int_lumi = 891093 / 3.332e-02 / 1e9, const double dy = 0.6 * 2)
Definition at line 26 of file Draw_HFJetTruth_InvMass.C.
References _file0, assert, CrossSection2RAA(), Draw_HFJetTruth_InvMass_DrawCrossSection_PR(), n, SetsPhenixStyle(), T, and t.
void Draw_HFJetTruth_InvMass_DrawCrossSection_PR (const TString infile)
Definition at line 218 of file Draw_HFJetTruth_InvMass.C.
References _file0, assert, GetSTAR2019(), h_b, hall, leg, and SaveCanvas().
Referenced by Draw_HFJetTruth_InvMass().
void DrawCrossSection (double int_lumi, const double dy)
Definition at line 89 of file Draw_HFJetTruth_InvMass.C.
References _file0, assert, Convert2CrossSection(), h_b, hall, leg, SaveCanvas(), and T.
TGraphErrors* GetRAA (TH1 * h_pp, TH1 * h_AA)
Definition at line 485 of file Draw_HFJetTruth_InvMass.C.
References assert, and i.
TGraph* GetRAAKang2019 (const int mass = 1, const double g = 1.8)
Definition at line 609 of file Draw_HFJetTruth_InvMass.C.
References assert, and g.
Referenced by CrossSection2RAA().
TGraph* GetRAARatioKang2019 (const int mass = 1, const double g = 1.8)
Definition at line 1021 of file Draw_HFJetTruth_InvMass.C.
References assert, and g.
Referenced by CrossSection2RAA().
TGraphAsymmErrors* GetSTAR2019 (const TString hepdata = "/sphenix/user/jinhuang/HF-jet/event_gen/HEPData-ins1493842-v1-Table_4.root")
Definition at line 582 of file Draw_HFJetTruth_InvMass.C.
References _file0, and assert.
Referenced by Draw_HFJetTruth_InvMass_DrawCrossSection_PR().
Variable Documentation
TFile* _file0 = NULL
Definition at line 23 of file Draw_HFJetTruth_InvMass.C.
TTree* T = NULL
Definition at line 24 of file Draw_HFJetTruth_InvMass.C.