Analysis Software: Proto3ShowerCalib Class Reference
Proto3ShowerCalib Class Reference
#include <analysis/blob/master/Prototype3/EMCal/ShowerCalib/Proto3ShowerCalib.h>
Classes
class Eval_Cluster
class Eval_Run
class HCAL_shower
class Scientillators
class Time_Samples
Public Member Functions
Proto3ShowerCalib (const std::string &filename="cemc_ana.root")
virtual ~Proto3ShowerCalib ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int LoadRecalibMap (const std::string &file)
void is_sim (bool b)
Proto3ShowerCalib (const std::string &filename="cemc_ana.root")
virtual ~Proto3ShowerCalib ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int LoadRecalibMap (const std::string &file)
void is_sim (bool b)
Proto3ShowerCalib (const std::string &filename="ana.root")
virtual ~Proto3ShowerCalib ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int LoadRecalibMap (const std::string &file)
void set_sim (const bool b)
void fill_tower_samples (const bool)
void fill_time_samples (const bool)
void fill_slat_values (const bool)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { n_size = 8 }
enum { n_size = 8 }
enum { n_size_emcal = 8, n_size_hcalin = 4, n_size_hcalout = 4 }
Private Member Functions
Fun4AllHistoManager * get_HistoManager ()
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
Fun4AllHistoManager * get_HistoManager ()
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
Fun4AllHistoManager * get_HistoManager ()
Private Attributes
bool _is_sim
std::string _filename
unsigned long _ievent
fstream fdata
Eval_Run _eval_run
Eval_Cluster _eval_3x3_raw
Eval_Cluster _eval_5x5_raw
Eval_Cluster _eval_3x3_prod
Eval_Cluster _eval_5x5_prod
Eval_Cluster _eval_3x3_temp
Eval_Cluster _eval_5x5_temp
Eval_Cluster _eval_3x3_recalib
Eval_Cluster _eval_5x5_recalib
std::map< std::pair< int, int >
, double > _recalib_const
bool _use_hodoscope_calibs
float fmodbins [nfmodbins]
float hodoscope_recalibrations [8][8]
float clus_3x3_sim_recalibs [nfmodbins-1][nfmodbins-1]
float clus_5x5_sim_recalibs [nfmodbins-1][nfmodbins-1]
HCAL_shower _shower
Time_Samples _time_samples
Scientillators _slats
TF1 * smearing
bool _fill_tower_samples
bool _fill_time_samples
bool _fill_slats
std::map< std::pair< int, int >
, double > _emcal_recalib_const
std::map< std::pair< int, int >
, double > _hcalin_recalib_const
std::map< std::pair< int, int >
, double > _hcalout_recalib_const
Static Private Attributes
static const int nfmodbins = 17
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file Proto3ShowerCalib.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
n_size
Definition at line 166 of file Proto3ShowerCalib.h.
anonymous enum private
Enumerator:
n_size
Definition at line 185 of file Proto3ShowerCalib.h.
anonymous enum private
Enumerator:
n_size_emcal
n_size_hcalin
n_size_hcalout
Definition at line 198 of file Proto3ShowerCalib.h.
Constructor & Destructor Documentation
Proto3ShowerCalib::Proto3ShowerCalib (const std::string & filename = "cemc_ana.root")
Definition at line 47 of file Proto3ShowerCalib.C.
References _eval_3x3_prod, _eval_3x3_raw, _eval_3x3_recalib, _eval_3x3_temp, _eval_5x5_prod, _eval_5x5_raw, _eval_5x5_recalib, _eval_5x5_temp, _eval_run, _recalib_const, col, n_size, Proto3ShowerCalib::Eval_Run::reset(), Proto3ShowerCalib::Eval_Cluster::reset(), and verbosity.
Proto3ShowerCalib::~Proto3ShowerCalib () virtual
Definition at line 72 of file Proto3ShowerCalib.C.
Proto3ShowerCalib::Proto3ShowerCalib (const std::string & filename = "cemc_ana.root")
virtual Proto3ShowerCalib::~Proto3ShowerCalib () virtual
Proto3ShowerCalib::Proto3ShowerCalib (const std::string & filename = "ana.root")
virtual Proto3ShowerCalib::~Proto3ShowerCalib () virtual
Member Function Documentation
int Proto3ShowerCalib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 119 of file Proto3ShowerCalib.C.
References _filename, assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, fdata, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, and Fun4AllHistoManager::nHistos().
int Proto3ShowerCalib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
int Proto3ShowerCalib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
void Proto3ShowerCalib::fill_slat_values (const bool b)
Definition at line 93 of file Proto3ShowerCalib.C.
References _fill_slats.
void Proto3ShowerCalib::fill_time_samples (const bool b)
Definition at line 88 of file Proto3ShowerCalib.C.
References _fill_time_samples.
void Proto3ShowerCalib::fill_tower_samples (const bool b)
Definition at line 83 of file Proto3ShowerCalib.C.
References _fill_tower_samples.
pair< int, int > Proto3ShowerCalib::find_max (RawTowerContainer * towers, int cluster_size) private
Definition at line 654 of file Proto3ShowerCalib.C.
References assert, col, energy, RawTower::get_energy(), RawTowerContainer::getTower(), max, n_size, and t.
Referenced by process_event().
std::pair<int, int> Proto3ShowerCalib::find_max (RawTowerContainer * towers, int cluster_size) private
Fun4AllHistoManager * Proto3ShowerCalib::get_HistoManager () private
Definition at line 77 of file Proto3ShowerCalib.C.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), Init(), and process_event().
Fun4AllHistoManager* Proto3ShowerCalib::get_HistoManager () private
Fun4AllHistoManager* Proto3ShowerCalib::get_HistoManager () private
int Proto3ShowerCalib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 138 of file Proto3ShowerCalib.C.
References _eval_3x3_prod, _eval_3x3_raw, _eval_3x3_recalib, _eval_3x3_temp, _eval_5x5_prod, _eval_5x5_raw, _eval_5x5_recalib, _eval_5x5_temp, _eval_run, _filename, _ievent, assert, Fun4AllReturnCodes::EVENT_OK, fdata, PHTFileServer::get(), get_HistoManager(), hNormalization, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), and T.
int Proto3ShowerCalib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int Proto3ShowerCalib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int Proto3ShowerCalib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 98 of file Proto3ShowerCalib.C.
References _ievent, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and verbosity.
int Proto3ShowerCalib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int Proto3ShowerCalib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
void Proto3ShowerCalib::is_sim (bool b) inline
Definition at line 45 of file Proto3ShowerCalib.h.
References _is_sim.
void Proto3ShowerCalib::is_sim (bool b) inline
Definition at line 46 of file Proto3ShowerCalib.h.
References _is_sim.
int Proto3ShowerCalib::LoadRecalibMap (const std::string & file)
Definition at line 691 of file Proto3ShowerCalib.C.
References _recalib_const, assert, col, line, and verbosity.
Referenced by Fun4All_TestBeam_ShowerCalib().
int Proto3ShowerCalib::LoadRecalibMap (const std::string & file)
int Proto3ShowerCalib::LoadRecalibMap (const std::string & file)
int Proto3ShowerCalib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 202 of file Proto3ShowerCalib.C.
References _eval_3x3_prod, _eval_3x3_raw, _eval_3x3_recalib, _eval_3x3_temp, _eval_5x5_prod, _eval_5x5_raw, _eval_5x5_recalib, _eval_5x5_temp, _eval_run, _is_sim, _recalib_const, assert, Proto3ShowerCalib::Eval_Cluster::average_col, Proto3ShowerCalib::Eval_Cluster::average_row, Proto3ShowerCalib::Eval_Run::beam_2CH_mm, Proto3ShowerCalib::Eval_Run::beam_2CV_mm, Proto3ShowerCalib::Eval_Run::beam_mom, Proto3ShowerCalib::Eval_Run::C2_sum, col, Proto3ShowerCalib::Eval_Run::EoP, Proto3ShowerCalib::Eval_Run::event, Fun4AllReturnCodes::EVENT_OK, fdata, PHParameters::FillFrom(), find_max(), RawTower::get_bineta(), RawTower::get_binphi(), PHParameters::get_double_param(), RawTower::get_energy(), EventHeader::get_EvtSequence(), get_HistoManager(), RawTower::get_id(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), EventHeader::get_RunNumber(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), findNode::getClass(), Fun4AllHistoManager::getHisto(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), PHG4TruthInfoContainer::GetVtx(), Proto3ShowerCalib::Eval_Run::good_data, Proto3ShowerCalib::Eval_Run::good_e, Proto3ShowerCalib::Eval_Run::good_temp, hNormalization, Proto3ShowerCalib::Eval_Run::hodo_h, Proto3ShowerCalib::Eval_Run::hodo_v, it, Proto3ShowerCalib::Eval_Cluster::max_col, Proto3ShowerCalib::Eval_Cluster::max_row, Proto3ShowerCalib::Eval_Run::reset(), Proto3ShowerCalib::Eval_Cluster::reset(), Proto3ShowerCalib::Eval_Cluster::reweight_clus_pol(), round(), Proto3ShowerCalib::Eval_Run::run, Proto3ShowerCalib::Eval_Cluster::sum_E, Proto3ShowerCalib::Eval_Run::sum_energy_T, T, Proto3ShowerCalib::Eval_Run::trigger_veto_pass, Proto3ShowerCalib::Eval_Run::truth_y, Proto3ShowerCalib::Eval_Run::truth_z, v, Proto3ShowerCalib::Eval_Run::valid_hodo_h, Proto3ShowerCalib::Eval_Run::valid_hodo_v, and verbosity.
int Proto3ShowerCalib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int Proto3ShowerCalib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
void Proto3ShowerCalib::set_sim (const bool b) inline
Definition at line 189 of file Proto3ShowerCalib.h.
References _is_sim.
Member Data Documentation
std::map<std::pair<int, int>, double> Proto3ShowerCalib::_emcal_recalib_const private
Definition at line 229 of file Proto3ShowerCalib.h.
Eval_Cluster Proto3ShowerCalib::_eval_3x3_prod private
Definition at line 190 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_3x3_raw private
Definition at line 187 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_3x3_recalib private
Definition at line 196 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_3x3_temp private
Definition at line 193 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_5x5_prod private
Definition at line 191 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_5x5_raw private
Definition at line 188 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_5x5_recalib private
Definition at line 197 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Cluster Proto3ShowerCalib::_eval_5x5_temp private
Definition at line 194 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
Eval_Run Proto3ShowerCalib::_eval_run private
Definition at line 185 of file Proto3ShowerCalib.h.
Referenced by Init(), process_event(), and Proto3ShowerCalib().
std::string Proto3ShowerCalib::_filename private
Definition at line 179 of file Proto3ShowerCalib.h.
Referenced by End(), and Init().
bool Proto3ShowerCalib::_fill_slats private
Definition at line 227 of file Proto3ShowerCalib.h.
Referenced by fill_slat_values().
bool Proto3ShowerCalib::_fill_time_samples private
Definition at line 226 of file Proto3ShowerCalib.h.
Referenced by fill_time_samples().
bool Proto3ShowerCalib::_fill_tower_samples private
Definition at line 225 of file Proto3ShowerCalib.h.
Referenced by fill_tower_samples().
std::map<std::pair<int, int>, double> Proto3ShowerCalib::_hcalin_recalib_const private
Definition at line 230 of file Proto3ShowerCalib.h.
std::map<std::pair<int, int>, double> Proto3ShowerCalib::_hcalout_recalib_const private
Definition at line 231 of file Proto3ShowerCalib.h.
unsigned long Proto3ShowerCalib::_ievent private
Definition at line 181 of file Proto3ShowerCalib.h.
Referenced by Init(), and InitRun().
bool Proto3ShowerCalib::_is_sim private
Definition at line 171 of file Proto3ShowerCalib.h.
Referenced by is_sim(), process_event(), and set_sim().
std::map< std::pair< int, int >, double > Proto3ShowerCalib::_recalib_const private
Definition at line 199 of file Proto3ShowerCalib.h.
Referenced by LoadRecalibMap(), process_event(), and Proto3ShowerCalib().
HCAL_shower Proto3ShowerCalib::_shower private
Definition at line 216 of file Proto3ShowerCalib.h.
Scientillators Proto3ShowerCalib::_slats private
Definition at line 220 of file Proto3ShowerCalib.h.
Time_Samples Proto3ShowerCalib::_time_samples private
Definition at line 218 of file Proto3ShowerCalib.h.
bool Proto3ShowerCalib::_use_hodoscope_calibs private
Definition at line 191 of file Proto3ShowerCalib.h.
float Proto3ShowerCalib::clus_3x3_sim_recalibs[nfmodbins-1][nfmodbins-1] private
Definition at line 204 of file Proto3ShowerCalib.h.
float Proto3ShowerCalib::clus_5x5_sim_recalibs[nfmodbins-1][nfmodbins-1] private
Definition at line 205 of file Proto3ShowerCalib.h.
fstream Proto3ShowerCalib::fdata private
Definition at line 183 of file Proto3ShowerCalib.h.
Referenced by End(), Init(), and process_event().
float Proto3ShowerCalib::fmodbins[nfmodbins] private
Definition at line 198 of file Proto3ShowerCalib.h.
float Proto3ShowerCalib::hodoscope_recalibrations[8][8] private
Definition at line 202 of file Proto3ShowerCalib.h.
const int Proto3ShowerCalib::nfmodbins = 17 static private
Definition at line 197 of file Proto3ShowerCalib.h.
TF1* Proto3ShowerCalib::smearing private
Definition at line 223 of file Proto3ShowerCalib.h.
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype3/EMCal/ShowerCalib/Proto3ShowerCalib.h
analysis/blob/master/Prototype3/EMCal/ShowerCalib_PositionDependent/Proto3ShowerCalib.h
analysis/blob/master/Prototype3/HCAL/ShowerCalib/Proto3ShowerCalib.h
analysis/blob/master/Prototype3/EMCal/ShowerCalib/Proto3ShowerCalib.C
analysis/blob/master/Prototype3/EMCal/ShowerCalib_PositionDependent/Proto3ShowerCalib.C
analysis/blob/master/Prototype3/HCAL/ShowerCalib/Proto3ShowerCalib.C