Analysis Software: analysis/blob/master/EICAnalysis/LeptoquarksReco.C File Reference
LeptoquarksReco.C File Reference
#include "LeptoquarksReco.h"
#include "PidCandidatev1.h"
#include "TruthTrackerHepMC.h"
#include <cassert>
#include <trackbase_historic/SvtxTrackMap_v1.h>
#include <trackbase_historic/SvtxVertexMap_v1.h>
#include <trackbase_historic/SvtxClusterMap_v1.h>
#include <phool/getClass.h>
#include <fun4all/Fun4AllReturnCodes.h>
#include <g4jets/JetMap.h>
#include <calobase/RawTowerGeomContainer.h>
#include <calobase/RawTowerContainer.h>
#include <calobase/RawTowerGeom.h>
#include <calobase/RawTowerv1.h>
#include <g4vertex/GlobalVertexMap.h>
#include <g4vertex/GlobalVertex.h>
#include <g4main/PHG4VtxPoint.h>
#include <g4main/PHG4Particle.h>
#include <g4eval/CaloRawTowerEval.h>
#include <g4eval/SvtxEvalStack.h>
#include <TLorentzVector.h>
#include <TString.h>
#include <TNtuple.h>
#include <TTree.h>
#include <TFile.h>
Functions
float Average (vector< float > v)
Function Documentation
float Average (vector< float > v)
Definition at line 312 of file LeptoquarksReco.C.
References i, j, and sum().
Referenced by LeptoquarksReco::AddTrackInformation(), likelihood(), and likelihood_topology().