Analysis Software: analysis/blob/master/Prototype2/EMCal/macros/FitVerticalScan.C File Reference
FitVerticalScan.C File Reference
#include <cmath>
#include <vector>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TMultiGraph.h>
#include <TLegend.h>
#include <TF1.h>
#include <cassert>
#include <iostream>
#include <fstream>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void OnlineAnalysis (TString filename="/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2016/column3_214x.txt")
void FitVerticalScan (const TString input="/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2016/getMeanRMS_Summary.root")
Variables
vector< TGraphErrors * > vg_src
Function Documentation
void FitVerticalScan (const TString input = "/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2016/getMeanRMS_Summary.root")
Definition at line 144 of file FitVerticalScan.C.
References _file0, assert, c2, i, j, leg, SaveCanvas(), SetOKStyle(), sum(), t, and vg_src.
void OnlineAnalysis (TString filename = "/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2016/column3_214x.txt")
Definition at line 33 of file FitVerticalScan.C.
References col, filename, gr, i, index, leg, line, title, and vg_src.
Variable Documentation
vector<TGraphErrors *> vg_src
Definition at line 30 of file FitVerticalScan.C.
Referenced by FitVerticalScan(), and OnlineAnalysis().