Analysis Software: HijJet4 Class Reference
HijJet4 Class Reference
Class definition for HijJet4, which is used to modify the Hijing HIJJET4 common.
#include <coresoftware/blob/master/generators/sHijing/HijJet4.h>
Classes
struct HIJJET4
Public Member Functions
HijJet4 ()
~HijJet4 ()
int & ndr (void)
int & iadr (int i, int j)
int & kfdr (int i)
float & pdr (int i, int k)
void init (void)
int lenI () const
int lenJ () const
int lenK () const
Private Attributes
int _dummy
float _realdummy
Static Private Attributes
static const int _lenI = 900
static const int _lenJ = 2
static const int _lenK = 5
static HIJJET4 * _hijjet4 =0
Friends
struct HIJJET4
Detailed Description
Class definition for HijJet4, which is used to modify the Hijing HIJJET4 common.
Definition at line 13 of file HijJet4.h.
Constructor & Destructor Documentation
HijJet4::HijJet4 () inline
Definition at line 63 of file HijJet4.h.
HijJet4::~HijJet4 () inline
Definition at line 70 of file HijJet4.h.
Member Function Documentation
int & HijJet4::iadr (int i, int j) inline
Definition at line 81 of file HijJet4.h.
References _dummy, _hijjet4, HijJet4::HIJJET4::iadr, init(), lenI(), and lenJ().
Referenced by hijhrd(), hijing(), and hijini().
void HijJet4::init (void) inline
Definition at line 58 of file HijJet4.h.
References _hijjet4, and hijjet4_address_().
Referenced by iadr(), kfdr(), ndr(), and pdr().
int & HijJet4::kfdr (int i) inline
Definition at line 91 of file HijJet4.h.
References _dummy, _hijjet4, init(), HijJet4::HIJJET4::kfdr, and lenI().
Referenced by hijhrd(), hijing(), and hijini().
int HijJet4::lenI () const inline
Definition at line 26 of file HijJet4.h.
References _lenI.
Referenced by iadr(), kfdr(), and pdr().
int HijJet4::lenJ () const inline
Definition at line 27 of file HijJet4.h.
References _lenJ.
Referenced by iadr().
int HijJet4::lenK () const inline
Definition at line 28 of file HijJet4.h.
References _lenK.
Referenced by pdr().
int & HijJet4::ndr (void) inline
Definition at line 74 of file HijJet4.h.
References _hijjet4, init(), and HijJet4::HIJJET4::ndr.
Referenced by hijhrd(), hijing(), and hijini().
float & HijJet4::pdr (int i, int k) inline
Definition at line 99 of file HijJet4.h.
References _hijjet4, _realdummy, init(), lenI(), lenK(), and HijJet4::HIJJET4::pdr.
Referenced by hijhrd(), hijing(), hijini(), lustrf(), and pystrf().
Friends And Related Function Documentation
friend struct HIJJET4 friend
Definition at line 37 of file HijJet4.h.
Member Data Documentation
int HijJet4::_dummy private
Definition at line 48 of file HijJet4.h.
Referenced by iadr(), and kfdr().
HijJet4::HIJJET4 * HijJet4::_hijjet4 =0 static private
Definition at line 51 of file HijJet4.h.
Referenced by iadr(), init(), kfdr(), ndr(), and pdr().
const int HijJet4::_lenI = 900 static private
Definition at line 33 of file HijJet4.h.
Referenced by lenI().
const int HijJet4::_lenJ = 2 static private
Definition at line 34 of file HijJet4.h.
Referenced by lenJ().
const int HijJet4::_lenK = 5 static private
Definition at line 35 of file HijJet4.h.
Referenced by lenK().
float HijJet4::_realdummy private
Definition at line 49 of file HijJet4.h.
Referenced by pdr().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HijJet4.h