Analysis Software: lzobuffer Class Reference
lzobuffer Class Reference
#include <online_distribution/blob/master/newbasic/lzobuffer.h>
Public Member Functions
lzobuffer (PHDWORD *array, const int length)
~lzobuffer ()
Event * getEvent ()
Public Member Functions inherited from prdfBuffer
prdfBuffer ()
prdfBuffer (PHDWORD *array, const int length)
~prdfBuffer ()
Event * getEvent ()
int * getEventData ()
int isGood () const
int buffer_swap ()
int frame_swap (PHDWORD *fp, const int eventlength)
Public Member Functions inherited from buffer
buffer ()
virtual ~buffer ()
Protected Attributes
PHDWORD * bufferarray
buffer * theBuffer
lzo_byte * wrkmem
int _broken
Protected Attributes inherited from prdfBuffer
buffer_ptr bptr
PHDWORD * data_ptr
int buffer_size
int max_length
int current_index
int is_good
Static Protected Attributes
static int lzo_initialized = 0
Additional Inherited Members
Static Public Member Functions inherited from buffer
static int makeBuffer (PHDWORD *bp, const int allocatedsize, buffer **bptr)
static int i4swap (const int in)
static unsigned int u4swap (const unsigned int in)
static int i22swap (const int in)
static short i2swap (const short in)
Detailed Description
Definition at line 9 of file lzobuffer.h.
Constructor & Destructor Documentation
lzobuffer::lzobuffer (PHDWORD * array, const int length)
Definition at line 8 of file lzobuffer.cc.
References _broken, bufferarray, BUFFERHEADERLENGTH, COUT, buffer::i4swap(), prdfBuffer::is_good, LZO1XBUFFERMARKER, lzo_initialized, prdfBuffer::prdfBuffer(), theBuffer, and buffer::u4swap().
lzobuffer::~lzobuffer ()
Definition at line 83 of file lzobuffer.cc.
References bufferarray, and theBuffer.
Member Function Documentation
Event * lzobuffer::getEvent () virtual
Implements buffer.
Definition at line 75 of file lzobuffer.cc.
References buffer::getEvent(), and theBuffer.
Member Data Documentation
int lzobuffer::_broken protected
Definition at line 31 of file lzobuffer.h.
Referenced by lzobuffer().
PHDWORD* lzobuffer::bufferarray protected
Definition at line 27 of file lzobuffer.h.
Referenced by lzobuffer(), and ~lzobuffer().
int lzobuffer::lzo_initialized = 0 static protected
Definition at line 25 of file lzobuffer.h.
Referenced by lzobuffer().
buffer* lzobuffer::theBuffer protected
Definition at line 28 of file lzobuffer.h.
Referenced by getEvent(), lzobuffer(), and ~lzobuffer().
lzo_byte* lzobuffer::wrkmem protected
Definition at line 29 of file lzobuffer.h.
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/lzobuffer.h
online_distribution/blob/master/newbasic/lzobuffer.cc