Analysis Software: EpInfo Class Reference
EpInfo Class Reference
#include <analysis/blob/master/EpFinder/EpInfo.h>
Public Member Functions
EpInfo ()
~EpInfo ()
TVector2 RawQ (int order)
TVector2 PhiWeightedQ (int order)
double RawPsi (int order)
double PhiWeightedPsi (int order)
double PhiWeightedAndShiftedPsi (int order)
double SWRaw (int order)
double SWPhiWeighted (int order)
Private Member Functions
bool ArgumentOutOfBounds (int order)
double Range (double psi, int order)
protection against user selecting "order=0" or order that has not been defined
Private Attributes
double QrawOneSide [_EpOrderMax][2]
puts angle psi into range (0,2pi/n)
double QphiWeightedOneSide [_EpOrderMax][2]
indices: [order][x,y]
double PsiRaw [_EpOrderMax]
indices: [order][x,y]
double PsiPhiWeighted [_EpOrderMax]
indices: [order]
double PsiPhiWeightedAndShifted [_EpOrderMax]
indices: [order]
double WheelSumWeightsRaw [_EpOrderMax]
indices: [order]
double WheelSumWeightsPhiWeighted [_EpOrderMax]
indices: [order]
Friends
class EpFinder
Detailed Description
the class EpInfo has only public members. No need to hide information. Indeed, it's really only a struct, with the possibility to create some methods.
Definition at line 11 of file EpInfo.h.
Constructor & Destructor Documentation
EpInfo::EpInfo ()
Definition at line 5 of file EpInfo.C.
References _EpOrderMax, PsiPhiWeighted, PsiPhiWeightedAndShifted, PsiRaw, QphiWeightedOneSide, and QrawOneSide.
EpInfo::~EpInfo () inline
Definition at line 19 of file EpInfo.h.
Member Function Documentation
bool EpInfo::ArgumentOutOfBounds (int order) private
Definition at line 90 of file EpInfo.C.
References _EpOrderMax.
Referenced by PhiWeightedAndShiftedPsi(), PhiWeightedPsi(), PhiWeightedQ(), Range(), RawPsi(), RawQ(), SWPhiWeighted(), and SWRaw().
double EpInfo::PhiWeightedAndShiftedPsi (int order)
Phi-weighted and shift-corrected Event plane angle order order of the Q-vector. Begins at unity (order=1 means first-order Q)
Definition at line 72 of file EpInfo.C.
References ArgumentOutOfBounds(), PsiPhiWeightedAndShifted, and Range().
Referenced by EpFinderEval::fill_tree().
double EpInfo::PhiWeightedPsi (int order)
Phi-weighted (but not shift flattened) Event plane angle order order of the Q-vector. Begins at unity (order=1 means first-order Q)
Definition at line 65 of file EpInfo.C.
References ArgumentOutOfBounds(), PsiPhiWeighted, and Range().
Referenced by EpFinderEval::fill_tree().
TVector2 EpInfo::PhiWeightedQ (int order)
Phi weighted Q vector order order of the Q-vector. Begins at unity (order=1 means first-order Q)
Definition at line 34 of file EpInfo.C.
References ArgumentOutOfBounds(), and QphiWeightedOneSide.
double EpInfo::Range (double psi, int order) private
protection against user selecting "order=0" or order that has not been defined
Definition at line 81 of file EpInfo.C.
References ArgumentOutOfBounds(), and double().
Referenced by PhiWeightedAndShiftedPsi(), PhiWeightedPsi(), and RawPsi().
double EpInfo::RawPsi (int order)
Raw (no phi-weighting, no shifting) Event plane angle order order of the Q-vector. Begins at unity (order=1 means first-order Q)
Definition at line 58 of file EpInfo.C.
References ArgumentOutOfBounds(), PsiRaw, and Range().
Referenced by EpFinderEval::fill_tree().
TVector2 EpInfo::RawQ (int order)
Raw (no phi-weighting) Q vector order order of the Q-vector. Begins at unity (order=1 means first-order Q)
Definition at line 24 of file EpInfo.C.
References ArgumentOutOfBounds(), and QrawOneSide.
double EpInfo::SWPhiWeighted (int order)
The sum of weights used to calculate Q-vector, for entire detector. This is phi-weighted This is useful if one wants to un-normalize the Q-vector ** note that this depends on "order," because the eta-weighting or ring-weighting can depend on order (user sets it) ** this stands in contrast to the ring-by-ring Qvectors, which do not depend on order. order order of the EP. Begins at unity (order=1 means first-order EP)
Definition at line 50 of file EpInfo.C.
References ArgumentOutOfBounds(), and WheelSumWeightsPhiWeighted.
double EpInfo::SWRaw (int order)
The sum of weights used to calculate Q-vector, for entire detector. This is RAW, not phi-weighted This is useful if one wants to un-normalize the Q-vector ** note that this depends on "order," because the eta-weighting or ring-weighting can depend on order (user sets it) ** this stands in contrast to the ring-by-ring Qvectors, which do not depend on order. order order of the EP. Begins at unity (order=1 means first-order EP)
Definition at line 44 of file EpInfo.C.
References ArgumentOutOfBounds(), and WheelSumWeightsRaw.
Friends And Related Function Documentation
friend class EpFinder friend
Definition at line 15 of file EpInfo.h.
Member Data Documentation
double EpInfo::PsiPhiWeighted[_EpOrderMax] private
indices: [order]
Definition at line 73 of file EpInfo.h.
Referenced by EpInfo(), PhiWeightedPsi(), and EpFinder::Results().
double EpInfo::PsiPhiWeightedAndShifted[_EpOrderMax] private
indices: [order]
Definition at line 74 of file EpInfo.h.
Referenced by EpInfo(), PhiWeightedAndShiftedPsi(), and EpFinder::Results().
double EpInfo::PsiRaw[_EpOrderMax] private
indices: [order][x,y]
Definition at line 72 of file EpInfo.h.
Referenced by EpInfo(), RawPsi(), and EpFinder::Results().
double EpInfo::QphiWeightedOneSide[_EpOrderMax][2] private
indices: [order][x,y]
Definition at line 71 of file EpInfo.h.
Referenced by EpInfo(), PhiWeightedQ(), and EpFinder::Results().
double EpInfo::QrawOneSide[_EpOrderMax][2] private
puts angle psi into range (0,2pi/n)
Definition at line 70 of file EpInfo.h.
Referenced by EpInfo(), RawQ(), and EpFinder::Results().
double EpInfo::WheelSumWeightsPhiWeighted[_EpOrderMax] private
indices: [order]
Definition at line 76 of file EpInfo.h.
Referenced by EpFinder::Results(), and SWPhiWeighted().
double EpInfo::WheelSumWeightsRaw[_EpOrderMax] private
indices: [order]
Definition at line 75 of file EpInfo.h.
Referenced by EpFinder::Results(), and SWRaw().
The documentation for this class was generated from the following files:
analysis/blob/master/EpFinder/EpInfo.h
analysis/blob/master/EpFinder/EpInfo.C