Analysis Software: MvtxDefs Namespace Reference
MvtxDefs Namespace Reference
Utility functions for MVTX.
Functions
static const unsigned int
kBitShiftStaveId __attribute__ ((unused)) = 16
uint8_t getStaveId (TrkrDefs::hitsetkey key)
Get the stave id from hitsetkey.
uint8_t getStaveId (TrkrDefs::cluskey key)
Get the stave id from cluskey.
uint8_t getChipId (TrkrDefs::hitsetkey key)
Get the chip id from hitsetkey.
uint8_t getChipId (TrkrDefs::cluskey key)
Get the chip id from cluskey.
uint16_t getCol (TrkrDefs::hitkey key)
Get the column index from hitkey.
uint16_t getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
TrkrDefs::hitkey genHitKey (const uint16_t col, const uint16_t row)
Generate a hitkey from a pixels column and row index.
TrkrDefs::hitsetkey genHitSetKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip)
Generate a hitsetkey for the mvtx.
TrkrDefs::cluskey genClusKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip, const uint32_t clusid)
Generate a cluster key from indeces.
TrkrDefs::cluskey genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
Generate a cluster key using a hitsetkey and cluster id.
Detailed Description
Utility functions for MVTX.
Contains the functions for manipulating the various keys used by the mvtx for hits, hit sets, and clusters
Function Documentation
static const uint16_t MAXROW MvtxDefs::__attribute__ ((unused)) = 16 static
TrkrDefs::cluskey MvtxDefs::genClusKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip, const uint32_t clusid)
Generate a cluster key from indeces.
Parameters
[in] lyr Layer index
[in] stave Stave index
[in] chip Chip index
[in] clusid Cluster id
[out] cluskey
Definition at line 68 of file MvtxDefs.cc.
References InttDefs::genHitSetKey().
Referenced by MvtxClusterizer::ClusterMvtx().
TrkrDefs::cluskey MvtxDefs::genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
Generate a cluster key using a hitsetkey and cluster id.
Parameters
[in] hskey hitsetkey
[in] clusid Cluster id
[out] cluskey
Definition at line 77 of file MvtxDefs.cc.
TrkrDefs::hitkey MvtxDefs::genHitKey (const uint16_t col, const uint16_t row)
Generate a hitkey from a pixels column and row index.
Parameters
[in] col Column index
[in] row Row index
[out] hitkey
Definition at line 48 of file MvtxDefs.cc.
Referenced by PHG4MvtxHitReco::process_event().
TrkrDefs::hitsetkey MvtxDefs::genHitSetKey (const uint8_t lyr, const uint8_t stave, const uint8_t chip)
Generate a hitsetkey for the mvtx.
Parameters
[in] lyr Layer index
[in] stave Stave index
[in] chip Chip index
[out] hitsetkey Generate a hitsetkey for the mvtx. The tracker id is known implicitly and used in the function.
Definition at line 57 of file MvtxDefs.cc.
References TrkrDefs::genHitSetKey(), and TrkrDefs::mvtxId.
Referenced by PHG4MvtxHitReco::process_event().
uint8_t MvtxDefs::getChipId (TrkrDefs::hitsetkey key)
Get the chip id from hitsetkey.
Parameters
[in] hitsetkey
[out] chip id
Definition at line 20 of file MvtxDefs.cc.
Referenced by MvtxClusterizer::ClusterMvtx(), getChipId(), SVReco::MakeGenFitTrack(), AnaMvtxTestBeam2019::process_event(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
uint8_t MvtxDefs::getChipId (TrkrDefs::cluskey key)
Get the chip id from cluskey.
Parameters
[in] cluskey
[out] chip id
Definition at line 27 of file MvtxDefs.cc.
References getChipId().
uint16_t MvtxDefs::getCol (TrkrDefs::hitkey key)
Get the column index from hitkey.
Parameters
[in] hitkey
[out] column index
Definition at line 34 of file MvtxDefs.cc.
Referenced by MvtxClusterizer::are_adjacent(), MvtxClusterizer::ClusterMvtx(), and AnaMvtxTestBeam2019::process_event().
uint16_t MvtxDefs::getRow (TrkrDefs::hitkey key)
Get the row index from hitkey.
Parameters
[in] hitkey
[out] row index
Definition at line 41 of file MvtxDefs.cc.
Referenced by MvtxClusterizer::are_adjacent(), MvtxClusterizer::ClusterMvtx(), and AnaMvtxTestBeam2019::process_event().
uint8_t MvtxDefs::getStaveId (TrkrDefs::hitsetkey key)
Get the stave id from hitsetkey.
Parameters
[in] hitsetkey
[out] stave id
Definition at line 6 of file MvtxDefs.cc.
Referenced by MvtxClusterizer::ClusterMvtx(), getStaveId(), SVReco::MakeGenFitTrack(), AnaMvtxTestBeam2019::process_event(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
uint8_t MvtxDefs::getStaveId (TrkrDefs::cluskey key)
Get the stave id from cluskey.
Parameters
[in] cluskey
[out] stave id
Definition at line 13 of file MvtxDefs.cc.
References getStaveId().