Analysis Software: HiMain2 Class Reference
HiMain2 Class Reference
Class definition for HiMain2, which is used to modify the Hijing HIMAIN2 common.
#include <coresoftware/blob/master/generators/sHijing/HiMain2.h>
Classes
struct HIMAIN2
Public Member Functions
HiMain2 ()
~HiMain2 ()
int & katt (int i, int j)
float & patt (int i, int j)
float & vatt (int i, int j)
void init (void)
int leniKatt () const
int lenjKatt () const
int leniPatt () const
int lenjPatt () const
int leniVatt () const
int lenjVatt () const
Private Attributes
int _dummy
float _realdummy
Static Private Attributes
static const int _leniKatt = 130000
static const int _lenjKatt = 4
static const int _leniPatt = 130000
static const int _lenjPatt = 4
static const int _leniVatt = 130000
static const int _lenjVatt = 4
static HIMAIN2 * _himain2 =0
Friends
struct HIMAIN2
Detailed Description
Class definition for HiMain2, which is used to modify the Hijing HIMAIN2 common.
Definition at line 11 of file HiMain2.h.
Constructor & Destructor Documentation
HiMain2::HiMain2 () inline
Definition at line 65 of file HiMain2.h.
HiMain2::~HiMain2 () inline
Definition at line 72 of file HiMain2.h.
Member Function Documentation
void HiMain2::init (void) inline
Definition at line 60 of file HiMain2.h.
References _himain2, and himain2_address_().
Referenced by katt(), patt(), and vatt().
int & HiMain2::katt (int i, int j) inline
Definition at line 76 of file HiMain2.h.
References _dummy, _himain2, init(), HiMain2::HIMAIN2::katt, leniKatt(), and lenjKatt().
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
int HiMain2::leniKatt () const inline
Definition at line 23 of file HiMain2.h.
References _leniKatt.
Referenced by katt().
int HiMain2::leniPatt () const inline
Definition at line 25 of file HiMain2.h.
References _leniPatt.
Referenced by patt().
int HiMain2::leniVatt () const inline
Definition at line 27 of file HiMain2.h.
References _leniVatt.
Referenced by vatt().
int HiMain2::lenjKatt () const inline
Definition at line 24 of file HiMain2.h.
References _lenjKatt.
Referenced by katt().
int HiMain2::lenjPatt () const inline
Definition at line 26 of file HiMain2.h.
References _lenjPatt.
Referenced by patt().
int HiMain2::lenjVatt () const inline
Definition at line 28 of file HiMain2.h.
References _lenjVatt.
Referenced by vatt().
float & HiMain2::patt (int i, int j) inline
Definition at line 86 of file HiMain2.h.
References _himain2, _realdummy, init(), leniPatt(), lenjPatt(), and HiMain2::HIMAIN2::patt.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), fillEvent(), and hijing().
float & HiMain2::vatt (int i, int j) inline
Definition at line 96 of file HiMain2.h.
References _himain2, _realdummy, init(), leniVatt(), lenjVatt(), and HiMain2::HIMAIN2::vatt.
Referenced by fillEvent(), and hijing().
Friends And Related Function Documentation
friend struct HIMAIN2 friend
Definition at line 40 of file HiMain2.h.
Member Data Documentation
int HiMain2::_dummy private
Definition at line 50 of file HiMain2.h.
Referenced by katt().
HiMain2::HIMAIN2 * HiMain2::_himain2 =0 static private
Definition at line 53 of file HiMain2.h.
Referenced by init(), katt(), patt(), and vatt().
const int HiMain2::_leniKatt = 130000 static private
Definition at line 33 of file HiMain2.h.
Referenced by leniKatt().
const int HiMain2::_leniPatt = 130000 static private
Definition at line 35 of file HiMain2.h.
Referenced by leniPatt().
const int HiMain2::_leniVatt = 130000 static private
Definition at line 37 of file HiMain2.h.
Referenced by leniVatt().
const int HiMain2::_lenjKatt = 4 static private
Definition at line 34 of file HiMain2.h.
Referenced by lenjKatt().
const int HiMain2::_lenjPatt = 4 static private
Definition at line 36 of file HiMain2.h.
Referenced by lenjPatt().
const int HiMain2::_lenjVatt = 4 static private
Definition at line 38 of file HiMain2.h.
Referenced by lenjVatt().
float HiMain2::_realdummy private
Definition at line 51 of file HiMain2.h.
Referenced by patt(), and vatt().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HiMain2.h