Analysis Software: PgPostBankBackupLog Class Reference
PgPostBankBackupLog Class Reference
PgPostBankBackupLog.
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupLog.h>
Public Types
enum enu_ops {
kOptFailed = -1, kOptSuccess = 1, kOptNull = 0, kOptBackup2File = 10,
kOptFile2Db = 20, kOptFile2Db_Skip = 21, kOptDump = 30, kOptDelete = 100
}
Public Member Functions
PgPostBankBackupLog (const std::string &TableName, const std::string &Tag)
virtual ~PgPostBankBackupLog ()
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
void Init ()
initialization. Always called to check connections in Log()
void Log (const int rid, const enu_ops ops)
enter one log entry
Protected Types
typedef TSQLConnection * TSQLConnection_PTR
Protected Attributes
int verbosity
The verbosity level. 0 means not verbose at all.
std::string tablename
std::string tag
TSQLPreparedStatement * pstmt
Static Protected Attributes
static TSQLConnection_PTR con
Detailed Description
PgPostBankBackupLog.
Definition at line 24 of file PgPostBankBackupLog.h.
Member Typedef Documentation
typedef TSQLConnection* PgPostBankBackupLog::TSQLConnection_PTR protected
Definition at line 80 of file PgPostBankBackupLog.h.
Member Enumeration Documentation
enum PgPostBankBackupLog::enu_ops
Enumerator:
kOptFailed
kOptFailed can be multiplied to other operations to flag a failure
kOptSuccess
positive value means fine
kOptNull
kOptBackup2File
use in PgPostBankBackupManager::fetchAllBank2TFile
kOptFile2Db
use in PgPostBankBackupManager::commitAllBankfromTFile
kOptFile2Db_Skip
kOptDump
use in PgPostBankBackupManager::dumpTable
kOptDelete
use in PgPostBankBackupManager::CleanTable
Definition at line 45 of file PgPostBankBackupLog.h.
Constructor & Destructor Documentation
PgPostBankBackupLog::PgPostBankBackupLog (const std::string & TableName, const std::string & Tag)
Definition at line 22 of file PgPostBankBackupLog.cc.
PgPostBankBackupLog::~PgPostBankBackupLog () virtual
Definition at line 31 of file PgPostBankBackupLog.cc.
Member Function Documentation
void PgPostBankBackupLog::Init ()
initialization. Always called to check connections in Log()
Definition at line 35 of file PgPostBankBackupLog.cc.
References assert, con, pstmt, tablename, tag, and Verbosity().
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), and Log().
void PgPostBankBackupLog::Log (const int rid, const enu_ops ops)
enter one log entry
Definition at line 85 of file PgPostBankBackupLog.cc.
References assert, con, Init(), pstmt, tablename, tag, and Verbosity().
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankBackupManager::dumpTable(), and PgPostBankBackupManager::fetchAllBank2TFile().
virtual void PgPostBankBackupLog::Verbosity (const int ival) inline virtual
Sets the verbosity of this module (0 by default=quiet).
Definition at line 33 of file PgPostBankBackupLog.h.
References verbosity.
virtual int PgPostBankBackupLog::Verbosity () const inline virtual
Gets the verbosity of this module.
Definition at line 40 of file PgPostBankBackupLog.h.
References verbosity.
Referenced by Init(), and Log().
Member Data Documentation
PgPostBankBackupLog::TSQLConnection_PTR PgPostBankBackupLog::con static protected
Definition at line 81 of file PgPostBankBackupLog.h.
Referenced by Init(), and Log().
TSQLPreparedStatement* PgPostBankBackupLog::pstmt protected
Definition at line 86 of file PgPostBankBackupLog.h.
Referenced by Init(), and Log().
std::string PgPostBankBackupLog::tablename protected
Definition at line 83 of file PgPostBankBackupLog.h.
Referenced by Init(), and Log().
std::string PgPostBankBackupLog::tag protected
Definition at line 84 of file PgPostBankBackupLog.h.
Referenced by Init(), and Log().
int PgPostBankBackupLog::verbosity protected
The verbosity level. 0 means not verbose at all.
Definition at line 78 of file PgPostBankBackupLog.h.
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupLog.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankBackupLog.cc