Analysis Software: PHG4mRICHDetector::mRichParameter Class Reference
PHG4mRICHDetector::mRichParameter Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4mRICHDetector.h>
Public Member Functions
mRichParameter ()
~mRichParameter ()
void SetPar_glassWindow (int i, G4double x, G4double y)
void SetPar_sensor (int i, G4double x, G4double y)
BoxPar * GetBoxPar (std::string componentName)
LensPar * GetLensPar (std::string componentName)
PolyPar * GetPolyPar (std::string componentName)
Private Attributes
BoxPar * holderBox
BoxPar * hollowVolume
BoxPar * foamHolderBox
PolyPar * foamHolderPoly
BoxPar * aerogel
LensPar * fresnelLens
PolyPar * mirror
BoxPar * glassWindow
BoxPar * sensor
PolyPar * readout
Detailed Description
Definition at line 112 of file PHG4mRICHDetector.h.
Constructor & Destructor Documentation
PHG4mRICHDetector::mRichParameter::mRichParameter ()
Definition at line 265 of file PHG4mRICHDetector.cc.
References i, and max.
PHG4mRICHDetector::mRichParameter::~mRichParameter ()
Definition at line 536 of file PHG4mRICHDetector.cc.
Member Function Documentation
PHG4mRICHDetector::BoxPar * PHG4mRICHDetector::mRichParameter::GetBoxPar (std::string componentName)
Definition at line 554 of file PHG4mRICHDetector.cc.
References printf().
Referenced by PHG4mRICHDetector::build_aerogel(), PHG4mRICHDetector::build_foamHolder(), PHG4mRICHDetector::build_holderBox(), and PHG4mRICHDetector::build_sensor().
PHG4mRICHDetector::LensPar * PHG4mRICHDetector::mRichParameter::GetLensPar (std::string componentName)
Definition at line 574 of file PHG4mRICHDetector.cc.
References printf().
Referenced by PHG4mRICHDetector::Construct_a_mRICH().
PHG4mRICHDetector::PolyPar * PHG4mRICHDetector::mRichParameter::GetPolyPar (std::string componentName)
Definition at line 583 of file PHG4mRICHDetector.cc.
References printf().
Referenced by PHG4mRICHDetector::build_foamHolder(), PHG4mRICHDetector::build_mirror(), and PHG4mRICHDetector::Construct_a_mRICH().
void PHG4mRICHDetector::mRichParameter::SetPar_glassWindow (int i, G4double x, G4double y)
Definition at line 538 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::build_sensor().
void PHG4mRICHDetector::mRichParameter::SetPar_sensor (int i, G4double x, G4double y)
Definition at line 546 of file PHG4mRICHDetector.cc.
Referenced by PHG4mRICHDetector::build_sensor().
Member Data Documentation
BoxPar* PHG4mRICHDetector::mRichParameter::aerogel private
Definition at line 119 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::foamHolderBox private
Definition at line 117 of file PHG4mRICHDetector.h.
PolyPar* PHG4mRICHDetector::mRichParameter::foamHolderPoly private
Definition at line 118 of file PHG4mRICHDetector.h.
LensPar* PHG4mRICHDetector::mRichParameter::fresnelLens private
Definition at line 120 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::glassWindow private
Definition at line 122 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::holderBox private
Definition at line 115 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::hollowVolume private
Definition at line 116 of file PHG4mRICHDetector.h.
PolyPar* PHG4mRICHDetector::mRichParameter::mirror private
Definition at line 121 of file PHG4mRICHDetector.h.
PolyPar* PHG4mRICHDetector::mRichParameter::readout private
Definition at line 124 of file PHG4mRICHDetector.h.
BoxPar* PHG4mRICHDetector::mRichParameter::sensor private
Definition at line 123 of file PHG4mRICHDetector.h.
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4mRICHDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4mRICHDetector.cc