Analysis Software: PHG4SectorDetector Class Reference
PHG4SectorDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorDetector.h>
Public Member Functions
PHG4SectorDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam)
constructor
virtual ~PHG4SectorDetector (void)
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
virtual void OverlapCheck (const bool chk=true)
volume accessors
bool IsInSectorActive (G4VPhysicalVolume *physvol)
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Public Member Functions inherited from PHG4Sector::PHG4SectorConstructor
PHG4SectorConstructor (const std::string &name, PHG4Subsystem *subsys)
virtual ~PHG4SectorConstructor ()
void Construct_Sectors (G4LogicalVolume *WorldLog)
void OverlapCheck (bool check)
Private Attributes
PHG4SectorDisplayAction * m_DisplayAction
std::string superdetector
Additional Inherited Members
Public Attributes inherited from PHG4Sector::PHG4SectorConstructor
std::string name_base
Sector_Geometry geom
Protected Types inherited from PHG4Sector::PHG4SectorConstructor
typedef std::map< G4String,
G4LogicalVolume * > map_log_vol_t
typedef std::pair< G4String,
G4int > phy_vol_idx_t
typedef std::map
< phy_vol_idx_t, G4PVPlacement * > map_phy_vol_t
Protected Member Functions inherited from PHG4Sector::PHG4SectorConstructor
G4VSolid * Construct_Sectors_Plane (const std::string &name, const double start_z, const double thickness, G4VSolid *SecConeBoundary_Det)
G4LogicalVolume * RegisterLogicalVolume (G4LogicalVolume *)
G4PVPlacement * RegisterPhysicalVolume (G4PVPlacement *v, const bool active=false)
Protected Attributes inherited from PHG4Sector::PHG4SectorConstructor
bool overlapcheck_sector
map_log_vol_t map_log_vol
map_phy_vol_t map_phy_vol
map_phy_vol_t map_active_phy_vol
all physics volume
Detailed Description
Definition at line 18 of file PHG4SectorDetector.h.
Constructor & Destructor Documentation
PHG4SectorDetector::PHG4SectorDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam)
constructor
Definition at line 23 of file PHG4SectorDetector.cc.
virtual PHG4SectorDetector::~PHG4SectorDetector (void) inline virtual
destructor
Definition at line 25 of file PHG4SectorDetector.h.
Member Function Documentation
void PHG4SectorDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 47 of file PHG4SectorDetector.cc.
References PHG4SectorDisplayAction::AddVolume(), PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), it, m_DisplayAction, PHG4Sector::PHG4SectorConstructor::map_log_vol, and PHG4Sector::PHG4SectorConstructor::name_base.
bool PHG4SectorDetector::IsInSectorActive (G4VPhysicalVolume * physvol)
Definition at line 32 of file PHG4SectorDetector.cc.
References it, and PHG4Sector::PHG4SectorConstructor::map_active_phy_vol.
Referenced by PHG4SectorSteppingAction::UserSteppingAction().
virtual void PHG4SectorDetector::OverlapCheck (const bool chk = true) inline virtual
Reimplemented from PHG4Detector.
Definition at line 40 of file PHG4SectorDetector.h.
References PHG4Detector::OverlapCheck().
Referenced by PHG4SectorSubsystem::Init().
void PHG4SectorDetector::SuperDetector (const std::string & name) inline
Definition at line 37 of file PHG4SectorDetector.h.
References name, and superdetector.
Referenced by PHG4SectorSubsystem::Init(), and PHG4SectorSteppingAction::SetInterfacePointers().
const std::string PHG4SectorDetector::SuperDetector () const inline
Definition at line 38 of file PHG4SectorDetector.h.
References superdetector.
Member Data Documentation
PHG4SectorDisplayAction* PHG4SectorDetector::m_DisplayAction private
Definition at line 47 of file PHG4SectorDetector.h.
Referenced by ConstructMe().
std::string PHG4SectorDetector::superdetector private
Definition at line 49 of file PHG4SectorDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorDetector.cc