Analysis Software: analysis/blob/master/sPhenixAj/Wrapper.cxx File Reference
Wrapper.cxx File Reference
Functions
int Wrapper (int nEvents=1, const char *fileList="/star/u/kkauder/sphenix/analysis/sPhenixAj/SingleEventPythia.list", const char *outputFile="G4sPHENIXCells.root")
int Get_Min_cemc_layer ()
int Get_Max_cemc_layer ()
int Get_Min_hcal_in_layer ()
int Get_Max_hcal_in_layer ()
int Get_Min_hcal_out_layer ()
int Get_Max_hcal_out_layer ()
int Get_Min_si_layer ()
int Get_Max_si_layer ()
int Get_Min_preshower_layer ()
int Get_Max_preshower_layer ()
Variables
int Min_cemc_layer = -1
int Max_cemc_layer = -1
int Min_hcal_in_layer = -1
int Max_hcal_in_layer = -1
int Min_hcal_out_layer = -1
int Max_hcal_out_layer = -1
int Min_preshower_layer = -1
int Max_preshower_layer = -1
int Min_si_layer = -1
int Max_si_layer = -1
int Cemc_slats_per_cell = 72
Function Documentation
int Get_Max_cemc_layer ()
Definition at line 266 of file Wrapper.cxx.
References Max_cemc_layer.
int Get_Max_hcal_in_layer ()
Definition at line 276 of file Wrapper.cxx.
References Max_hcal_in_layer.
int Get_Max_hcal_out_layer ()
Definition at line 286 of file Wrapper.cxx.
References Max_hcal_out_layer.
int Get_Max_preshower_layer ()
Definition at line 306 of file Wrapper.cxx.
References Max_preshower_layer.
int Get_Max_si_layer ()
Definition at line 296 of file Wrapper.cxx.
References Max_si_layer.
int Get_Min_cemc_layer ()
Definition at line 261 of file Wrapper.cxx.
References Min_cemc_layer.
int Get_Min_hcal_in_layer ()
Definition at line 271 of file Wrapper.cxx.
References Min_hcal_in_layer.
int Get_Min_hcal_out_layer ()
Definition at line 281 of file Wrapper.cxx.
References Min_hcal_out_layer.
int Get_Min_preshower_layer ()
Definition at line 301 of file Wrapper.cxx.
References Min_preshower_layer.
int Get_Min_si_layer ()
Definition at line 291 of file Wrapper.cxx.
References Min_si_layer.
int Wrapper (int nEvents = 1, const char * fileList = "/star/u/kkauder/sphenix/analysis/sPhenixAj/SingleEventPythia.list", const char * outputFile = "G4sPHENIXCells.root")
Definition at line 15 of file Wrapper.cxx.
References PHG4SimpleEventGenerator::add_particles(), Fun4AllInputManager::AddListFile(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_Towers(), Fun4AllServer::dumpHistos(), Fun4AllServer::End(), G4Init(), G4Setup(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), in, recoConsts::instance(), Fun4AllServer::instance(), kAll, nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHFlag::set_IntFlag(), PHG4SimpleEventGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_pt_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHG4ParticleGeneratorBase::set_seed(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), Svtx_Cells(), Svtx_Eval(), Svtx_Reco(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
Variable Documentation
int Cemc_slats_per_cell = 72
Definition at line 11 of file Wrapper.cxx.
int Max_cemc_layer = -1
Definition at line 2 of file Wrapper.cxx.
int Max_hcal_in_layer = -1
Definition at line 4 of file Wrapper.cxx.
Referenced by Get_Max_hcal_in_layer().
int Max_hcal_out_layer = -1
Definition at line 6 of file Wrapper.cxx.
Referenced by Get_Max_hcal_out_layer().
int Max_preshower_layer = -1
Definition at line 8 of file Wrapper.cxx.
Referenced by Get_Max_preshower_layer().
int Max_si_layer = -1
Definition at line 10 of file Wrapper.cxx.
int Min_cemc_layer = -1
Definition at line 1 of file Wrapper.cxx.
int Min_hcal_in_layer = -1
Definition at line 3 of file Wrapper.cxx.
Referenced by Get_Min_hcal_in_layer().
int Min_hcal_out_layer = -1
Definition at line 5 of file Wrapper.cxx.
Referenced by Get_Min_hcal_out_layer().
int Min_preshower_layer = -1
Definition at line 7 of file Wrapper.cxx.
Referenced by Get_Min_preshower_layer().
int Min_si_layer = -1
Definition at line 9 of file Wrapper.cxx.