Analysis Software: JetMapv1 Class Reference
JetMapv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/JetMapv1.h>
Public Member Functions
JetMapv1 ()
JetMapv1 (const JetMap *jets)
JetMapv1 & operator= (const JetMapv1 &jets)
virtual ~JetMapv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
void set_algo (Jet::ALGO algo)
Jet::ALGO get_algo () const
void set_par (float par)
float get_par () const
bool empty_src () const
void insert_src (Jet::SRC src)
ConstSrcIter begin_src () const
ConstSrcIter find_src (Jet::SRC src) const
ConstSrcIter end_src () const
SrcIter begin_src ()
SrcIter find_src (Jet::SRC src)
SrcIter end_src ()
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const Jet * get (unsigned int idkey) const
Jet * get (unsigned int idkey)
Jet * insert (Jet *jet)
insert Jet to the map. Once inserted, the JetMap owns the Jet memory
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from JetMap
JetMap ()
virtual ~JetMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (JetMapv1, 1)
Private Attributes
Jet::ALGO _algo
float _par
std::set< Jet::SRC > _src
typ_JetMap _map
Additional Inherited Members
Public Types inherited from JetMap
typedef std::map< unsigned int,
Jet * > typ_JetMap
typedef typ_JetMap::const_iterator ConstIter
typedef typ_JetMap::iterator Iter
typedef std::set< Jet::SRC >
::const_iterator ConstSrcIter
typedef std::set< Jet::SRC >
::iterator SrcIter
Detailed Description
Definition at line 14 of file JetMapv1.h.
Constructor & Destructor Documentation
JetMapv1::JetMapv1 ()
Definition at line 15 of file JetMapv1.cc.
Referenced by CloneMe().
JetMapv1::JetMapv1 (const JetMap * jets)
Definition at line 23 of file JetMapv1.cc.
References _map, _src, assert, JetMap::begin(), JetMap::begin_src(), CloneMe(), JetMap::end(), JetMap::end_src(), and Jet::get_id().
JetMapv1::~JetMapv1 () virtual
Definition at line 72 of file JetMapv1.cc.
References Reset().
Member Function Documentation
ConstIter JetMapv1::begin () const inline virtual
Reimplemented from JetMap.
Definition at line 62 of file JetMapv1.h.
References _map.
Referenced by operator=().
Iter JetMapv1::begin () inline virtual
Reimplemented from JetMap.
Definition at line 66 of file JetMapv1.h.
References _map.
ConstSrcIter JetMapv1::begin_src () const inline virtual
Reimplemented from JetMap.
Definition at line 40 of file JetMapv1.h.
References _src.
Referenced by identify(), and operator=().
SrcIter JetMapv1::begin_src () inline virtual
Reimplemented from JetMap.
Definition at line 44 of file JetMapv1.h.
References _src.
JetMapv1::ClassDef (JetMapv1 , 1) private
void JetMapv1::clear () inline virtual
Reimplemented from JetMap.
Definition at line 53 of file JetMapv1.h.
References Reset().
PHObject * JetMapv1::CloneMe () const virtual
Virtual copy constructor.
Reimplemented from JetMap.
Definition at line 90 of file JetMapv1.cc.
References JetMapv1().
Referenced by JetMapv1(), and operator=().
size_t JetMapv1::count (unsigned int idkey) const inline virtual
Reimplemented from JetMap.
Definition at line 52 of file JetMapv1.h.
References _map.
bool JetMapv1::empty () const inline virtual
Reimplemented from JetMap.
Definition at line 50 of file JetMapv1.h.
References _map.
bool JetMapv1::empty_src () const inline virtual
Reimplemented from JetMap.
Definition at line 37 of file JetMapv1.h.
References _src.
ConstIter JetMapv1::end () const inline virtual
Reimplemented from JetMap.
Definition at line 64 of file JetMapv1.h.
References _map.
Referenced by operator=().
Iter JetMapv1::end () inline virtual
Reimplemented from JetMap.
Definition at line 68 of file JetMapv1.h.
References _map.
ConstSrcIter JetMapv1::end_src () const inline virtual
Reimplemented from JetMap.
Definition at line 42 of file JetMapv1.h.
References _src.
Referenced by identify(), and operator=().
SrcIter JetMapv1::end_src () inline virtual
Reimplemented from JetMap.
Definition at line 46 of file JetMapv1.h.
References _src.
size_t JetMapv1::erase (unsigned int idkey) inline virtual
Reimplemented from JetMap.
Definition at line 60 of file JetMapv1.h.
References _map.
ConstIter JetMapv1::find (unsigned int idkey) const inline virtual
Reimplemented from JetMap.
Definition at line 63 of file JetMapv1.h.
References _map.
Iter JetMapv1::find (unsigned int idkey) inline virtual
Reimplemented from JetMap.
Definition at line 67 of file JetMapv1.h.
References _map.
ConstSrcIter JetMapv1::find_src (Jet::SRC src) const inline virtual
Reimplemented from JetMap.
Definition at line 41 of file JetMapv1.h.
References _src.
SrcIter JetMapv1::find_src (Jet::SRC src) inline virtual
Reimplemented from JetMap.
Definition at line 45 of file JetMapv1.h.
References _src.
const Jet * JetMapv1::get (unsigned int idkey) const virtual
Reimplemented from JetMap.
Definition at line 110 of file JetMapv1.cc.
References _map.
Jet * JetMapv1::get (unsigned int idkey) virtual
Reimplemented from JetMap.
Definition at line 117 of file JetMapv1.cc.
References _map.
Jet::ALGO JetMapv1::get_algo () const inline virtual
Reimplemented from JetMap.
Definition at line 30 of file JetMapv1.h.
References _algo.
Referenced by operator=().
float JetMapv1::get_par () const inline virtual
Reimplemented from JetMap.
Definition at line 33 of file JetMapv1.h.
References _par.
Referenced by operator=().
void JetMapv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from JetMap.
Definition at line 96 of file JetMapv1.cc.
References _map, _par, begin_src(), end_src(), and i.
Jet * JetMapv1::insert (Jet * jet) virtual
insert Jet to the map. Once inserted, the JetMap owns the Jet memory
Reimplemented from JetMap.
Definition at line 124 of file JetMapv1.cc.
References _map, and index.
void JetMapv1::insert_src (Jet::SRC src) inline virtual
Reimplemented from JetMap.
Definition at line 38 of file JetMapv1.h.
References _src.
int JetMapv1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from JetMap.
Definition at line 24 of file JetMapv1.h.
JetMapv1 & JetMapv1::operator= (const JetMapv1 & jets)
Definition at line 46 of file JetMapv1.cc.
References _algo, _map, _par, _src, assert, begin(), begin_src(), CloneMe(), end(), end_src(), get_algo(), Jet::get_id(), get_par(), and Reset().
void JetMapv1::Reset () virtual
Clear Event.
Reimplemented from JetMap.
Definition at line 77 of file JetMapv1.cc.
References _algo, _map, _par, _src, and Jet::NONE.
Referenced by clear(), operator=(), and ~JetMapv1().
void JetMapv1::set_algo (Jet::ALGO algo) inline virtual
Reimplemented from JetMap.
Definition at line 29 of file JetMapv1.h.
References _algo.
void JetMapv1::set_par (float par) inline virtual
Reimplemented from JetMap.
Definition at line 32 of file JetMapv1.h.
References _par.
size_t JetMapv1::size (void) const inline virtual
Reimplemented from JetMap.
Definition at line 51 of file JetMapv1.h.
References _map.
Member Data Documentation
Jet::ALGO JetMapv1::_algo private
Definition at line 71 of file JetMapv1.h.
Referenced by get_algo(), operator=(), Reset(), and set_algo().
typ_JetMap JetMapv1::_map private
Definition at line 74 of file JetMapv1.h.
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), JetMapv1(), operator=(), Reset(), and size().
float JetMapv1::_par private
Definition at line 72 of file JetMapv1.h.
Referenced by get_par(), identify(), operator=(), Reset(), and set_par().
std::set<Jet::SRC> JetMapv1::_src private
Definition at line 73 of file JetMapv1.h.
Referenced by begin_src(), empty_src(), end_src(), find_src(), insert_src(), JetMapv1(), operator=(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/JetMapv1.h
coresoftware/blob/master/simulation/g4simulation/g4jets/JetMapv1.cc