Analysis Software: PHG4MvtxSubsystem Class Reference
PHG4MvtxSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.h>
Public Member Functions
PHG4MvtxSubsystem (const std::string &name="PHG4MvtxSubsystem", const int _n_layers=3)
constructor
virtual ~PHG4MvtxSubsystem ()
destructor
int InitRunSubsystem (PHCompositeNode *)
InitRunSubsystem.
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
Public Member Functions inherited from PHG4DetectorGroupSubsystem
virtual ~PHG4DetectorGroupSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParametersContainer * GetParamsContainer () const
void set_double_param (const int detid, const std::string &name, const double dval)
double get_double_param (const int detid, const std::string &name) const
void set_int_param (const int detid, const std::string &name, const int ival)
int get_int_param (const int detid, const std::string &name) const
void set_string_param (const int detid, const std::string &name, const std::string &sval)
std::string get_string_param (const int detid, const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int detid, const int i)
void SetActive (const int i=1)
void SetAbsorberActive (const int detid, const int i)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int detid, const int i)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int detid, const int i)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters ()
Private Attributes
PHG4MvtxDetector * m_Detector
detector geometry
PHG4SteppingAction * steppingAction_
particle tracking "stepping" action
PHG4DisplayAction * m_DisplayAction
display attribute setting
unsigned int n_layers
std::string detector_type
Additional Inherited Members
Public Types inherited from PHG4DetectorGroupSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Protected Member Functions inherited from PHG4DetectorGroupSubsystem
PHG4DetectorGroupSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void AddDetId (const int i)
std::pair< std::set< int >
::const_iterator, std::set
< int >::const_iterator > GetDetIds () const
void set_default_double_param (const int detid, const std::string &name, const double dval)
void set_default_int_param (const int detid, const std::string &name, const int ival)
void set_default_string_param (const int detid, const std::string &name, const std::string &sval)
int BeginRunExecuted () const
void PrintDefaultParams () const
void PrintMacroParams () const
Detailed Description
Definition at line 16 of file PHG4MvtxSubsystem.h.
Constructor & Destructor Documentation
PHG4MvtxSubsystem::PHG4MvtxSubsystem (const std::string & name = "PHG4MvtxSubsystem", const int _n_layers = 3)
constructor
Definition at line 37 of file PHG4MvtxSubsystem.cc.
References PHG4DetectorGroupSubsystem::AddDetId(), PHG4DetectorGroupSubsystem::InitializeParameters(), n_layers, Fun4AllBase::Name(), and PHG4DetectorGroupSubsystem::SuperDetector().
PHG4MvtxSubsystem::~PHG4MvtxSubsystem () virtual
destructor
Definition at line 57 of file PHG4MvtxSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
PHG4Detector * PHG4MvtxSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 182 of file PHG4MvtxSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4MvtxSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 45 of file PHG4MvtxSubsystem.h.
References m_DisplayAction.
PHG4SteppingAction * PHG4MvtxSubsystem::GetSteppingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 188 of file PHG4MvtxSubsystem.cc.
References steppingAction_.
int PHG4MvtxSubsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
InitRunSubsystem.
called during InitRun (the original InitRun does common setup and calls this one) creates the detector object ceates the stepping action creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorGroupSubsystem.
Definition at line 63 of file PHG4MvtxSubsystem.cc.
References PHCompositeNode::addNode(), PHG4DetectorGroupSubsystem::CheckOverlap(), PHG4MvtxDetector::Detector(), detector_type, PHNodeIterator::findFirst(), PHParameters::get_int_param(), PHG4DetectorGroupSubsystem::GetDetIds(), PHParametersContainer::GetParameters(), PHG4DetectorGroupSubsystem::GetParamsContainer(), m_Detector, m_DisplayAction, n_layers, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHWHERE, PHParametersContainer::Print(), steppingAction_, PHG4MvtxDetector::SuperDetector(), PHG4DetectorGroupSubsystem::SuperDetector(), PHG4Detector::topNode(), PHG4Detector::Verbosity(), and Fun4AllBase::Verbosity().
int PHG4MvtxSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 170 of file PHG4MvtxSubsystem.cc.
References PHG4SteppingAction::SetInterfacePointers(), and steppingAction_.
void PHG4MvtxSubsystem::SetDefaultParameters () private virtual
Implements PHG4DetectorGroupSubsystem.
Definition at line 193 of file PHG4MvtxSubsystem.cc.
References PHG4MvtxDefs::ALPIDE_SEGMENTATION, PHG4DetectorGroupSubsystem::GetDetIds(), PHG4MvtxDefs::GLOBAL, PHG4DetectorGroupSubsystem::set_default_double_param(), PHG4DetectorGroupSubsystem::set_default_int_param(), and PHG4DetectorGroupSubsystem::set_default_string_param().
Member Data Documentation
std::string PHG4MvtxSubsystem::detector_type private
Definition at line 65 of file PHG4MvtxSubsystem.h.
Referenced by InitRunSubsystem().
PHG4MvtxDetector* PHG4MvtxSubsystem::m_Detector private
detector geometry
defives from PHG4Detector
Definition at line 52 of file PHG4MvtxSubsystem.h.
Referenced by GetDetector(), and InitRunSubsystem().
PHG4DisplayAction* PHG4MvtxSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 60 of file PHG4MvtxSubsystem.h.
Referenced by GetDisplayAction(), InitRunSubsystem(), and ~PHG4MvtxSubsystem().
unsigned int PHG4MvtxSubsystem::n_layers private
Definition at line 63 of file PHG4MvtxSubsystem.h.
Referenced by InitRunSubsystem(), and PHG4MvtxSubsystem().
PHG4SteppingAction* PHG4MvtxSubsystem::steppingAction_ private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 56 of file PHG4MvtxSubsystem.h.
Referenced by GetSteppingAction(), InitRunSubsystem(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc