Analysis Software: SvtxEvaluator Class Reference
SvtxEvaluator Class Reference
Compares reconstructed tracks to truth particles.
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvaluator.h>
Public Member Functions
SvtxEvaluator (const std::string &name="SVTXEVALUATOR", const std::string &filename="g4eval.root", const std::string &trackmapname="SvtxTrackMap", unsigned int nlayers_maps=3, unsigned int nlayers_intt=8, unsigned int nlayers_tpc=60)
virtual ~SvtxEvaluator ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_strict (bool b)
void set_use_initial_vertex (bool use_init_vtx)
void do_vertex_eval (bool b)
void do_gpoint_eval (bool b)
void do_g4hit_eval (bool b)
void do_hit_eval (bool b)
void do_cluster_eval (bool b)
void do_gtrack_eval (bool b)
void do_track_eval (bool b)
void do_gseed_eval (bool b)
void do_track_match (bool b)
void do_eval_light (bool b)
void scan_for_embedded (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
float line_circle_intersection (float x[], float y[], float z[], float radius)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
unsigned int _ievent
SvtxEvalStack * _svtxevalstack
bool _strict
bool _use_initial_vertex
unsigned int _errors
bool _do_vertex_eval
bool _do_gpoint_eval
bool _do_g4hit_eval
bool _do_hit_eval
bool _do_cluster_eval
bool _do_gtrack_eval
bool _do_track_eval
bool _do_gseed_eval
bool _do_track_match
bool _do_eval_light
bool _scan_for_embedded
unsigned int _nlayers_maps = 3
unsigned int _nlayers_intt = 8
unsigned int _nlayers_tpc = 60
TNtuple * _ntp_vertex
TNtuple * _ntp_gpoint
TNtuple * _ntp_g4hit
TNtuple * _ntp_hit
TNtuple * _ntp_cluster
TNtuple * _ntp_gtrack
TNtuple * _ntp_track
TNtuple * _ntp_gseed
std::string _filename
std::string _trackmapname
TFile * _tfile
PHTimer * _timer
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Compares reconstructed tracks to truth particles.
Plan: This module will trace the reconstructed tracks back to the greatest contributor Monte Carlo particle and then test one against the other.
Definition at line 28 of file SvtxEvaluator.h.
Constructor & Destructor Documentation
SvtxEvaluator::SvtxEvaluator (const std::string & name = "SVTXEVALUATOR", const std::string & filename = "g4eval.root", const std::string & trackmapname = "SvtxTrackMap", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 8, unsigned int nlayers_tpc = 60)
Definition at line 56 of file SvtxEvaluator.cc.
SvtxEvaluator::~SvtxEvaluator () virtual
Definition at line 95 of file SvtxEvaluator.cc.
References _timer.
Member Function Documentation
void SvtxEvaluator::do_cluster_eval (bool b) inline
Definition at line 50 of file SvtxEvaluator.h.
References _do_cluster_eval.
Referenced by Fun4All_G4_TPC(), ReadClustersRunTracking(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_eval_light (bool b) inline
Definition at line 56 of file SvtxEvaluator.h.
References _do_eval_light.
Referenced by Fun4All_G4_TPC(), ReadClustersRunTracking(), and Tracking_Eval().
void SvtxEvaluator::do_g4hit_eval (bool b) inline
Definition at line 48 of file SvtxEvaluator.h.
References _do_g4hit_eval.
Referenced by Fun4All_G4_TPC(), ReadClustersRunTracking(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_gpoint_eval (bool b) inline
Definition at line 47 of file SvtxEvaluator.h.
References _do_gpoint_eval.
Referenced by Fun4All_G4_TPC(), ReadClustersRunTracking(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_gseed_eval (bool b) inline
Definition at line 53 of file SvtxEvaluator.h.
References _do_gseed_eval.
void SvtxEvaluator::do_gtrack_eval (bool b) inline
Definition at line 51 of file SvtxEvaluator.h.
References _do_gtrack_eval.
void SvtxEvaluator::do_hit_eval (bool b) inline
Definition at line 49 of file SvtxEvaluator.h.
References _do_hit_eval.
Referenced by Fun4All_G4_TPC(), ReadClustersRunTracking(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::do_track_eval (bool b) inline
Definition at line 52 of file SvtxEvaluator.h.
References _do_track_eval.
void SvtxEvaluator::do_track_match (bool b) inline
Definition at line 55 of file SvtxEvaluator.h.
References _do_track_match.
void SvtxEvaluator::do_vertex_eval (bool b) inline
Definition at line 46 of file SvtxEvaluator.h.
References _do_vertex_eval.
int SvtxEvaluator::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 239 of file SvtxEvaluator.cc.
References _errors, _filename, _ievent, _ntp_cluster, _ntp_g4hit, _ntp_gpoint, _ntp_gseed, _ntp_gtrack, _ntp_hit, _ntp_track, _ntp_vertex, _svtxevalstack, _tfile, Fun4AllReturnCodes::EVENT_OK, SvtxEvalStack::get_errors(), and Fun4AllBase::Verbosity().
void SvtxEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 693 of file SvtxEvaluator.cc.
References _do_eval_light, _do_track_match, _ievent, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _ntp_cluster, _ntp_g4hit, _ntp_gpoint, _ntp_gseed, _ntp_gtrack, _ntp_hit, _ntp_track, _ntp_vertex, _scan_for_embedded, _svtxevalstack, _timer, _trackmapname, _use_initial_vertex, SvtxClusterEval::all_clusters_from(), SvtxTruthEval::all_truth_hits(), SvtxClusterEval::all_truth_hits(), SvtxClusterEval::all_truth_particles(), SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrack::begin_clusters(), SvtxClusterEval::best_cluster_from(), SvtxTrackEval::best_track_from(), SvtxVertexEval::best_vertex_from(), SvtxTrack::CEMC, SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), SvtxTrack::end_clusters(), TrkrClusterContainer::findCluster(), PHTimer::get_accumulated_time(), PHG4Hit::get_avg_t(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), SvtxTrack::get_cal_cluster_e(), SvtxTrack::get_cal_deta(), SvtxTrack::get_cal_dphi(), SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxEvalStack::get_cluster_eval(), SvtxTrack::get_dca2d(), SvtxTrack::get_dca2d_error(), SvtxTrack::get_dca3d_xy(), SvtxTrack::get_dca3d_xy_error(), SvtxTrack::get_dca3d_z(), SvtxTrack::get_dca3d_z_error(), PHG4Hit::get_edep(), SvtxTruthEval::get_embed(), SvtxHitEval::get_energy_contribution(), SvtxClusterEval::get_energy_contribution(), SvtxTrack::get_error(), SvtxEvalStack::get_hit_eval(), PHG4Hit::get_hit_id(), PHG4VtxPoint::get_id(), SvtxTrack::get_id(), PHG4Hit::get_layer(), SvtxTrackEval::get_layer_range_contribution(), SvtxTrackEval::get_nclusters_contribution(), SvtxTrackEval::get_nclusters_contribution_by_layer(), SvtxTrack::get_ndf(), SvtxVertexEval::get_ntracks_contribution(), SvtxTrackEval::get_nwrongclusters_contribution(), SvtxTruthEval::get_outermost_truth_hit(), SvtxTruthEval::get_particle(), PHG4CylinderCellGeom::get_phicenter(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Hit::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), PHG4Hit::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), PHG4Hit::get_pz(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), PHG4CylinderCellGeom::get_radius(), PHG4VtxPoint::get_t(), PHG4CylinderCellGeom::get_thickness(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), SvtxEvalStack::get_truth_eval(), SvtxTruthEval::get_vertex(), SvtxEvalStack::get_vertex_eval(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), SvtxVertex::get_x(), SvtxTrack::get_x(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), SvtxVertex::get_y(), SvtxTrack::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), SvtxVertex::get_z(), SvtxTrack::get_z(), PHG4CylinderCellGeom::get_zcenter(), TrkrHit::getAdc(), TrkrCluster::getAdc(), TrkrClusterContainer::getClusters(), TrkrHit::getEnergy(), TrkrCluster::getError(), TrkrClusterHitAssoc::getHits(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), PHG4TruthInfoContainer::GetNumPrimaryVertexParticles(), TpcDefs::getPad(), TrkrCluster::getPhiSize(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVtxRange(), TrkrCluster::getRPhiError(), TpcDefs::getTBin(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), TrkrCluster::getZError(), TrkrCluster::getZSize(), gpos, gr, SvtxTrack::HCALIN, SvtxTrack::HCALOUT, i, SvtxTruthEval::is_primary(), PHG4TruthInfoContainer::isEmbededVtx(), line_circle_intersection(), SvtxHitEval::max_truth_hit_by_energy(), SvtxClusterEval::max_truth_hit_by_energy(), SvtxTrackEval::max_truth_particle_by_nclusters(), SvtxVertexEval::max_truth_point_by_ntracks(), nparticles, phi, PHWHERE, pos, SvtxTrack::PRES, r, PHTimer::restart(), TrkrClusterContainer::size(), SvtxTrack::size_cluster_keys(), SvtxVertex::size_tracks(), PHTimer::stop(), boost::swap(), t, v, Fun4AllBase::Verbosity(), x, y, and z.
Referenced by process_event().
int SvtxEvaluator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 100 of file SvtxEvaluator.cc.
References _do_cluster_eval, _do_g4hit_eval, _do_gpoint_eval, _do_gseed_eval, _do_gtrack_eval, _do_hit_eval, _do_track_eval, _do_vertex_eval, _filename, _ievent, _ntp_cluster, _ntp_g4hit, _ntp_gpoint, _ntp_gseed, _ntp_gtrack, _ntp_hit, _ntp_track, _ntp_vertex, _tfile, _timer, Fun4AllReturnCodes::EVENT_OK, and PHTimer::stop().
int SvtxEvaluator::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 194 of file SvtxEvaluator.cc.
References Fun4AllReturnCodes::EVENT_OK.
float SvtxEvaluator::line_circle_intersection (float x[], float y[], float z[], float radius) private
Definition at line 2983 of file SvtxEvaluator.cc.
References A, C, PHWHERE, and t.
Referenced by fillOutputNtuples().
void SvtxEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 281 of file SvtxEvaluator.cc.
References _ievent, _strict, _svtxevalstack, _trackmapname, _use_initial_vertex, SvtxTruthEval::all_truth_hits(), SvtxTrackMap::begin(), SvtxTrackMap::end(), SvtxEvalStack::get_truth_eval(), TrkrClusterContainer::getClusters(), PHG4Hit::identify(), SvtxVertex::identify(), SvtxTrack::identify(), PHWHERE, SvtxTruthEval::set_strict(), SvtxVertexMap::size(), SvtxTrackMap::size(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void SvtxEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 368 of file SvtxEvaluator.cc.
References _ievent, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _svtxevalstack, _trackmapname, _use_initial_vertex, SvtxClusterEval::all_clusters_from(), SvtxTrackEval::all_tracks_from(), SvtxTruthEval::all_truth_hits(), SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), TrkrClusterContainer::findCluster(), SvtxEvalStack::get_cluster_eval(), PHG4Hit::get_hit_id(), SvtxTrack::get_id(), PHG4Hit::get_layer(), SvtxTrackEval::get_nclusters_contribution(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), SvtxEvalStack::get_track_eval(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), SvtxEvalStack::get_truth_eval(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), SvtxVertex::get_x(), PHG4Hit::get_y(), SvtxVertex::get_y(), PHG4Hit::get_z(), SvtxVertex::get_z(), TrkrClusterContainer::getClusters(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), PHG4TruthInfoContainer::GetVtx(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), PHG4Hit::identify(), TrkrCluster::identify(), PHG4Particle::identify(), PHG4TruthInfoContainer::isEmbeded(), SvtxClusterEval::max_truth_hit_by_energy(), PHWHERE, SvtxTrackMap::size(), tracks(), Fun4AllBase::Verbosity(), x, y, and z.
Referenced by process_event().
int SvtxEvaluator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 199 of file SvtxEvaluator.cc.
References _ievent, _strict, _svtxevalstack, _use_initial_vertex, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), SvtxEvalStack::next_event(), printInputInfo(), printOutputInfo(), SvtxEvalStack::set_strict(), SvtxEvalStack::set_use_initial_vertex(), SvtxEvalStack::set_verbosity(), and Fun4AllBase::Verbosity().
void SvtxEvaluator::scan_for_embedded (bool b) inline
Definition at line 57 of file SvtxEvaluator.h.
References _scan_for_embedded.
Referenced by Fun4All_G4_TPC(), ReadClustersRunTracking(), Svtx_Eval(), and Tracking_Eval().
void SvtxEvaluator::set_strict (bool b) inline
Definition at line 44 of file SvtxEvaluator.h.
References _strict.
void SvtxEvaluator::set_use_initial_vertex (bool use_init_vtx) inline
Definition at line 45 of file SvtxEvaluator.h.
References _use_initial_vertex.
Referenced by Tracking_Eval().
Member Data Documentation
bool SvtxEvaluator::_do_cluster_eval private
Definition at line 76 of file SvtxEvaluator.h.
Referenced by do_cluster_eval(), and Init().
bool SvtxEvaluator::_do_eval_light private
Definition at line 82 of file SvtxEvaluator.h.
Referenced by do_eval_light(), and fillOutputNtuples().
bool SvtxEvaluator::_do_g4hit_eval private
Definition at line 74 of file SvtxEvaluator.h.
Referenced by do_g4hit_eval(), and Init().
bool SvtxEvaluator::_do_gpoint_eval private
Definition at line 73 of file SvtxEvaluator.h.
Referenced by do_gpoint_eval(), and Init().
bool SvtxEvaluator::_do_gseed_eval private
Definition at line 79 of file SvtxEvaluator.h.
Referenced by do_gseed_eval(), and Init().
bool SvtxEvaluator::_do_gtrack_eval private
Definition at line 77 of file SvtxEvaluator.h.
Referenced by do_gtrack_eval(), and Init().
bool SvtxEvaluator::_do_hit_eval private
Definition at line 75 of file SvtxEvaluator.h.
Referenced by do_hit_eval(), and Init().
bool SvtxEvaluator::_do_track_eval private
Definition at line 78 of file SvtxEvaluator.h.
Referenced by do_track_eval(), and Init().
bool SvtxEvaluator::_do_track_match private
Definition at line 81 of file SvtxEvaluator.h.
Referenced by do_track_match(), and fillOutputNtuples().
bool SvtxEvaluator::_do_vertex_eval private
Definition at line 72 of file SvtxEvaluator.h.
Referenced by do_vertex_eval(), and Init().
unsigned int SvtxEvaluator::_errors private
Definition at line 70 of file SvtxEvaluator.h.
Referenced by End().
std::string SvtxEvaluator::_filename private
Definition at line 99 of file SvtxEvaluator.h.
Referenced by End(), and Init().
unsigned int SvtxEvaluator::_ievent private
Definition at line 60 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), printInputInfo(), printOutputInfo(), and process_event().
unsigned int SvtxEvaluator::_nlayers_intt = 8 private
Definition at line 86 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), and printOutputInfo().
unsigned int SvtxEvaluator::_nlayers_maps = 3 private
Definition at line 85 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), and printOutputInfo().
unsigned int SvtxEvaluator::_nlayers_tpc = 60 private
Definition at line 87 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), and printOutputInfo().
TNtuple* SvtxEvaluator::_ntp_cluster private
Definition at line 93 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_g4hit private
Definition at line 91 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_gpoint private
Definition at line 90 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_gseed private
Definition at line 96 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_gtrack private
Definition at line 94 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_hit private
Definition at line 92 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_track private
Definition at line 95 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* SvtxEvaluator::_ntp_vertex private
Definition at line 89 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
bool SvtxEvaluator::_scan_for_embedded private
Definition at line 83 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), and scan_for_embedded().
bool SvtxEvaluator::_strict private
Definition at line 68 of file SvtxEvaluator.h.
Referenced by printInputInfo(), process_event(), and set_strict().
SvtxEvalStack* SvtxEvaluator::_svtxevalstack private
Definition at line 63 of file SvtxEvaluator.h.
Referenced by End(), fillOutputNtuples(), printInputInfo(), printOutputInfo(), and process_event().
TFile* SvtxEvaluator::_tfile private
Definition at line 102 of file SvtxEvaluator.h.
Referenced by End(), and Init().
PHTimer* SvtxEvaluator::_timer private
Definition at line 104 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), Init(), and ~SvtxEvaluator().
std::string SvtxEvaluator::_trackmapname private
Definition at line 101 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), printInputInfo(), and printOutputInfo().
bool SvtxEvaluator::_use_initial_vertex private
Definition at line 69 of file SvtxEvaluator.h.
Referenced by fillOutputNtuples(), printInputInfo(), printOutputInfo(), process_event(), and set_use_initial_vertex().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxEvaluator.cc