Analysis Software: PHTimeServer Class Reference
PHTimeServer Class Reference
PHTimer server for accessing external information.
#include <coresoftware/blob/master/offline/framework/phool/PHTimeServer.h>
Classes
class iterator
light iterator over PHTimer map
class timer
wrapper around PHTimer, for storage in a map
Public Member Functions
virtual ~PHTimeServer ()
destructor
timer insert_new (const std::string &)
insert new timer in map.
timer insert_new_single_shot (const std::string &)
insert new single_shot timer in map.
timer get_timer (const std::string &)
retrieve existing timer. throw exception if not found
timer get_single_shot_timer (const std::string &)
retrieve existing timer. throw exception if not found
void print (std::ostream &out=std::cout) const
dump all registered timer value.
void print_stat (std::ostream &out=std::cout) const
dump all registered timer statistics.
iterator range (void)
return iterator over the map, located at begin
Static Public Member Functions
static PHTimeServer * get (void)
singleton accessor
Protected Member Functions
PHTimeServer ()
constructor
Private Types
typedef std::map< std::string,
timer > time_map
map
typedef std::map< std::string,
timer >::iterator time_iterator
iterator over the map.
typedef std::map< std::string,
timer >::const_iterator const_time_iterator
iterator over the map.
Private Attributes
time_map _timers
list of timers
time_map _single_shot_timers
list of single shot timers
unsigned short _timer_id
running timer unique id
unsigned short _single_shot_timer_id
running single shot timer unique id
Detailed Description
PHTimer server for accessing external information.
Definition at line 25 of file PHTimeServer.h.
Member Typedef Documentation
typedef std::map<std::string, timer>::const_iterator PHTimeServer::const_time_iterator private
iterator over the map.
Definition at line 106 of file PHTimeServer.h.
typedef std::map<std::string, timer>::iterator PHTimeServer::time_iterator private
iterator over the map.
Definition at line 103 of file PHTimeServer.h.
typedef std::map<std::string, timer> PHTimeServer::time_map private
map
Definition at line 100 of file PHTimeServer.h.
Constructor & Destructor Documentation
virtual PHTimeServer::~PHTimeServer () inline virtual
destructor
Definition at line 68 of file PHTimeServer.h.
PHTimeServer::PHTimeServer () inline protected
constructor
Definition at line 92 of file PHTimeServer.h.
Referenced by get().
Member Function Documentation
static PHTimeServer* PHTimeServer::get (void) inline static
singleton accessor
Definition at line 61 of file PHTimeServer.h.
References PHTimeServer().
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankBackupManager::commitAllBankfromTFile(), and PgPostBankBackupManager::fetchAllBank2TFile().
PHTimeServer::timer PHTimeServer::get_single_shot_timer (const std::string & key)
retrieve existing timer. throw exception if not found
Definition at line 77 of file PHTimeServer.cc.
References _single_shot_timers.
PHTimeServer::timer PHTimeServer::get_timer (const std::string & key)
retrieve existing timer. throw exception if not found
Definition at line 62 of file PHTimeServer.cc.
PHTimeServer::timer PHTimeServer::insert_new (const std::string & key)
insert new timer in map.
Definition at line 19 of file PHTimeServer.cc.
PHTimeServer::timer PHTimeServer::insert_new_single_shot (const std::string & key)
insert new single_shot timer in map.
Definition at line 40 of file PHTimeServer.cc.
void PHTimeServer::print (std::ostream & out = std::cout) const
dump all registered timer value.
Definition at line 92 of file PHTimeServer.cc.
References _single_shot_timers, _timers, PHTimer::PRINT(), and PHTimer::RUN.
void PHTimeServer::print_stat (std::ostream & out = std::cout) const
dump all registered timer statistics.
Definition at line 127 of file PHTimeServer.cc.
References _single_shot_timers, _timers, and PHTimer::PRINT().
iterator PHTimeServer::range (void) inline
return iterator over the map, located at begin
Definition at line 160 of file PHTimeServer.h.
References _timers.
Member Data Documentation
unsigned short PHTimeServer::_single_shot_timer_id private
running single shot timer unique id
Definition at line 118 of file PHTimeServer.h.
time_map PHTimeServer::_single_shot_timers private
list of single shot timers
Definition at line 112 of file PHTimeServer.h.
Referenced by get_single_shot_timer(), print(), and print_stat().
unsigned short PHTimeServer::_timer_id private
running timer unique id
Definition at line 115 of file PHTimeServer.h.
time_map PHTimeServer::_timers private
list of timers
Definition at line 109 of file PHTimeServer.h.
Referenced by print(), print_stat(), and range().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phool/PHTimeServer.h
coresoftware/blob/master/offline/framework/phool/PHTimeServer.cc