Analysis Software: online_distribution/blob/master/newbasic/ddump.cc File Reference
ddump.cc File Reference
#include <stdlib.h>
#include <signal.h>
#include <string>
#include "fileEventiterator.h"
#include "testEventiterator.h"
#include "rcdaqEventiterator.h"
#include "oncsEventiterator.h"
#include <stdio.h>
#include <vector>
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>
Macros
#define RCDAQEVENTITERATOR 1
#define FILEEVENTITERATOR 2
#define TESTEVENTITERATOR 3
#define ONCSEVENTITERATOR 4
Functions
void sig_handler (...)
void exitmsg ()
void evtcountexitmsg ()
void exithelp ()
int rangeParser (const std::string string, std::vector< int > &selection)
int main (int argc, char *argv[])
Variables
Eventiterator * it
Macro Definition Documentation
#define FILEEVENTITERATOR 2
Definition at line 22 of file ddump.cc.
Referenced by main().
#define ONCSEVENTITERATOR 4
Definition at line 24 of file ddump.cc.
Referenced by main().
#define RCDAQEVENTITERATOR 1
Definition at line 21 of file ddump.cc.
Referenced by main().
#define TESTEVENTITERATOR 3
Definition at line 23 of file ddump.cc.
Referenced by main().
Function Documentation
void evtcountexitmsg ()
Definition at line 43 of file ddump.cc.
References COUT.
Referenced by main().
void exithelp ()
Definition at line 51 of file ddump.cc.
References COUT.
void exitmsg ()
Definition at line 36 of file ddump.cc.
References COUT.
int main (int argc, char * argv[])
Definition at line 175 of file ddump.cc.
References c, COUT, Packet::dump(), EVT_DECIMAL, EVT_HEXADECIMAL, EVT_OCTAL, EVT_RAW, EVT_RAW_WH, evtcountexitmsg(), exithelp(), exitmsg(), FILEEVENTITERATOR, Packet::fullIdentify(), Packet::gdump(), Event::getEvtSequence(), Event::getEvtType(), Eventiterator::getNextEvent(), Event::getPacket(), Event::getPacketList(), i, Event::identify(), it, Event::listError(), Event::listFrame(), Event::listHistory(), ONCSEVENTITERATOR, rangeParser(), RCDAQEVENTITERATOR, s, Eventiterator::setVerbosity(), sig_handler(), signal(), and TESTEVENTITERATOR.
int rangeParser (const std::string string, std::vector< int > & selection)
Definition at line 140 of file ddump.cc.
References i, it, and r.
Referenced by main().
void sig_handler (...)
Definition at line 245 of file changehitformat.cc.
Variable Documentation
Eventiterator* it
Definition at line 34 of file ddump.cc.