Analysis Software: PHG4DstCompressReco Class Reference
PHG4DstCompressReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/PHG4DstCompressReco.h>
Public Member Functions
PHG4DstCompressReco (const std::string &name="PHG4DstCompressReco")
virtual ~PHG4DstCompressReco ()
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
void AddHitContainer (const std::string &name)
void AddCellContainer (const std::string &name)
void AddTowerContainer (const std::string &name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SearchG4HitNodes (PHCompositeNode *topNode)
Private Attributes
PHG4TruthInfoContainer * _truth_info
std::set< std::string > _compress_g4hit_names
std::set< std::string > _compress_g4cell_names
std::set< std::string > _compress_tower_names
std::set< PHG4CellContainer * > _g4cells
std::set< PHG4HitContainer * > _g4hits
std::set< PHG4HitContainer * > _keep_g4hits
std::set< RawTowerContainer * > _towers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 17 of file PHG4DstCompressReco.h.
Constructor & Destructor Documentation
PHG4DstCompressReco::PHG4DstCompressReco (const std::string & name = "PHG4DstCompressReco")
Definition at line 29 of file PHG4DstCompressReco.cc.
virtual PHG4DstCompressReco::~PHG4DstCompressReco () inline virtual
Definition at line 21 of file PHG4DstCompressReco.h.
Member Function Documentation
void PHG4DstCompressReco::AddCellContainer (const std::string & name) inline
Definition at line 30 of file PHG4DstCompressReco.h.
References _compress_g4cell_names.
Referenced by ShowerCompress().
void PHG4DstCompressReco::AddHitContainer (const std::string & name) inline
Definition at line 29 of file PHG4DstCompressReco.h.
References _compress_g4hit_names.
Referenced by ShowerCompress().
void PHG4DstCompressReco::AddTowerContainer (const std::string & name) inline
Definition at line 31 of file PHG4DstCompressReco.h.
References _compress_tower_names.
Referenced by ShowerCompress().
int PHG4DstCompressReco::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 40 of file PHG4DstCompressReco.cc.
References _compress_g4cell_names, _compress_tower_names, _g4cells, _towers, _truth_info, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, name, and SearchG4HitNodes().
int PHG4DstCompressReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 78 of file PHG4DstCompressReco.cc.
References _g4cells, _g4hits, _keep_g4hits, _towers, _truth_info, RawTower::clear_g4cells(), PHG4Shower::clear_g4hit_id(), PHG4Shower::clear_g4particle_id(), PHG4Shower::clear_g4vertex_id(), PHG4TruthInfoContainer::delete_particle(), PHG4TruthInfoContainer::delete_vtx(), Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetSecondaryParticleRange(), PHG4TruthInfoContainer::GetSecondaryVtxRange(), PHG4TruthInfoContainer::GetShowerRange(), RawTowerContainer::getTowers(), PHG4CellContainer::Reset(), and PHG4HitContainer::Reset().
void PHG4DstCompressReco::SearchG4HitNodes (PHCompositeNode * topNode) private
Definition at line 193 of file PHG4DstCompressReco.cc.
References _compress_g4hit_names, _g4hits, _keep_g4hits, PHDataNode< T >::getData(), and PHNodeIterator::ls().
Referenced by InitRun().
Member Data Documentation
std::set<std::string> PHG4DstCompressReco::_compress_g4cell_names private
Definition at line 38 of file PHG4DstCompressReco.h.
Referenced by AddCellContainer(), and InitRun().
std::set<std::string> PHG4DstCompressReco::_compress_g4hit_names private
Definition at line 37 of file PHG4DstCompressReco.h.
Referenced by AddHitContainer(), and SearchG4HitNodes().
std::set<std::string> PHG4DstCompressReco::_compress_tower_names private
Definition at line 39 of file PHG4DstCompressReco.h.
Referenced by AddTowerContainer(), and InitRun().
std::set<PHG4CellContainer *> PHG4DstCompressReco::_g4cells private
Definition at line 41 of file PHG4DstCompressReco.h.
Referenced by InitRun(), and process_event().
std::set<PHG4HitContainer *> PHG4DstCompressReco::_g4hits private
Definition at line 42 of file PHG4DstCompressReco.h.
Referenced by process_event(), and SearchG4HitNodes().
std::set<PHG4HitContainer *> PHG4DstCompressReco::_keep_g4hits private
Definition at line 43 of file PHG4DstCompressReco.h.
Referenced by process_event(), and SearchG4HitNodes().
std::set<RawTowerContainer *> PHG4DstCompressReco::_towers private
Definition at line 45 of file PHG4DstCompressReco.h.
Referenced by InitRun(), and process_event().
PHG4TruthInfoContainer* PHG4DstCompressReco::_truth_info private
Definition at line 36 of file PHG4DstCompressReco.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/PHG4DstCompressReco.h
coresoftware/blob/master/simulation/g4simulation/g4eval/PHG4DstCompressReco.cc