Analysis Software: online_distribution/blob/master/newbasic/formatError.C File Reference
formatError.C File Reference
#include "formatError.h"
Classes
struct formatError
Macros
#define ERROR_PACKAGE_RAWFMT 1
Typedefs
typedef struct formatError FORMATERROR
Functions
void setFrameError (ERRORVALUE errorNumber, PHDWORD *pointer, PHDWORD additionalData)
void setPacketError (ERRORVALUE errorNumber, PHDWORD *pointer, PHDWORD additionalData)
void setUserError (ERRORVALUE errorNumber, PHDWORD additionalData)
void setFrameSuccess ()
void setPacketSuccess ()
ERRORVALUE formatGetErrorNumber ()
ERRORVALUE formatGetError (UINT *subType, PHDWORD **errorPointer, PHDWORD *additionalData)
PHDWORD * formatGetErrorPointer ()
PHDWORD formatGetErrorAdditionalData ()
Variables
FORMATERROR rawfmtLastError
Macro Definition Documentation
#define ERROR_PACKAGE_RAWFMT 1
Definition at line 28 of file formatError.C.
Typedef Documentation
typedef struct formatError FORMATERROR
Function Documentation
ERRORVALUE formatGetError (UINT * subType, PHDWORD ** errorPointer, PHDWORD * additionalData)
Definition at line 93 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, formatError::frameOrPacket_ptr, and formatError::subType.
PHDWORD formatGetErrorAdditionalData ()
Definition at line 114 of file formatError.C.
References formatError::additionalData, and formatError::errorNumber.
ERRORVALUE formatGetErrorNumber ()
Definition at line 86 of file formatError.C.
References formatError::errorNumber.
PHDWORD* formatGetErrorPointer ()
Definition at line 104 of file formatError.C.
References formatError::errorNumber, and formatError::frameOrPacket_ptr.
void setFrameError (ERRORVALUE errorNumber, PHDWORD * pointer, PHDWORD additionalData)
Definition at line 43 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, errorTypeFrame, formatError::frameOrPacket_ptr, and formatError::subType.
Referenced by adjustFrameErrorLengthV1(), adjustFrameHistoryLengthV1(), adjustFrameLength(), checkFrameHdrVersion(), getFrameDataLengthV1(), getFrameHdrLength(), getFrameHdrVersion(), getFrameLength(), and validFrameHdrV1().
void setFrameSuccess ()
Definition at line 72 of file formatError.C.
References formatError::errorNumber.
Referenced by adjustFrameErrorLengthV1(), adjustFrameHistoryLengthV1(), checkFrameHdrVersion(), findFrameEnd(), getFrameDataLengthV1(), and validFrameHdrV1().
void setPacketError (ERRORVALUE errorNumber, PHDWORD * pointer, PHDWORD additionalData)
Definition at line 53 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, errorTypePacket, formatError::frameOrPacket_ptr, and formatError::subType.
Referenced by extendPacketLength(), findPacketEnd(), getPacketHdrVersion(), getUnstructPacketDataLengthWords(), removePacketPadding(), reservePacketDebugData(), setPacketHdrLength(), setPacketHdrVersion(), setPacketLength(), storePacketHits(), and validPacketV1Hdr().
void setPacketSuccess ()
Definition at line 79 of file formatError.C.
References formatError::errorNumber.
Referenced by appendEmptyFramePacket(), findPacketEnd(), and validPacketV1Hdr().
void setUserError (ERRORVALUE errorNumber, PHDWORD additionalData)
Definition at line 63 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, errorTypeUser, and formatError::subType.
Referenced by appendEmptyFramePacket(), orFrameStatusV1(), orPacketV1Status(), and startUnstructDataWrite().
Variable Documentation
FORMATERROR rawfmtLastError
Definition at line 38 of file formatError.C.