Analysis Software: Pythia6 Class Reference
Pythia6 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4decayer/Pythia6.hh>
Public Member Functions
Pythia6 ()
virtual ~Pythia6 ()
int Pycomp (int kf)
void Py1ent (int line, int kf, double pe, double theta, double phi)
ParticleVector * ImportParticles ()
int ImportParticles (ParticleVector *particles, const char *option="")
void SetMSTJ (int i, int m)
int GetMDCY (int i, int j)
int GetKFDP (int i, int j)
void SetMDCY (int i, int j, int m)
void SetMDME (int i, int j, int m)
Pythia6 ()
virtual ~Pythia6 ()
int Pycomp (int kf)
void Py1ent (int line, int kf, double pe, double theta, double phi)
ParticleVector * ImportParticles ()
int ImportParticles (ParticleVector *particles, const char *option="")
void SetMSTJ (int i, int m)
int GetMDCY (int i, int j)
int GetKFDP (int i, int j)
void SetMDCY (int i, int j, int m)
void SetMDME (int i, int j, int m)
Static Public Member Functions
static Pythia6 * Instance ()
static Pythia6 * Instance ()
Private Attributes
ParticleVector * fParticles
Pyjets_t * fPyjets
Pydat1_t * fPydat1
Pydat3_t * fPydat3
Static Private Attributes
static Pythia6 * fgInstance = 0
Detailed Description
The C++ interface class to Pythia6
According to TPythia6 class from Root: (The TPythia6 class is an interface class to F77 routines in Pythia6 // CERNLIB event generators, written by T.Sjostrand.) http://root.cern.ch/ see http://root.cern.ch/root/License.html
The complete Pythia6 documentation can be found at: http://home.thep.lu.se/~torbjorn/pythiaaux/recent.html
Definition at line 163 of file Pythia6.hh.
Constructor & Destructor Documentation
Pythia6::Pythia6 ()
Pythia6 constructor: creates a vector of Pythia6Particle in which it will store all particles. Note that there may be only one functional Pythia6 object at a time, so it's not use to create more than one instance of it.
Definition at line 129 of file Pythia6.cc.
References fgInstance, fParticles, fPydat1, fPydat3, fPyjets, Pydat1_t::MSTU, and pythia6_common_address().
Referenced by Instance().
Pythia6::~Pythia6 () virtual
Destroy the object, delete and dispose all Pythia6Particles currently on list.
Definition at line 160 of file Pythia6.cc.
References fParticles, and it.
Pythia6::Pythia6 ()
virtual Pythia6::~Pythia6 () virtual
Member Function Documentation
int Pythia6::GetKFDP (int i, int j) inline
Definition at line 187 of file Pythia6.hh.
References fPydat3, and Pydat3_t::KFDP.
Referenced by G4Pythia6Decayer::ForceHadronicD(), and G4Pythia6Decayer::ForceOmega().
int Pythia6::GetKFDP (int i, int j) inline
Definition at line 187 of file Pythia6.hh.
References fPydat3, and Pydat3_t::KFDP.
int Pythia6::GetMDCY (int i, int j) inline
Definition at line 186 of file Pythia6.hh.
References fPydat3, and Pydat3_t::MDCY.
Referenced by G4Pythia6Decayer::ForceHadronicD(), G4Pythia6Decayer::ForceOmega(), and G4Pythia6Decayer::ForceParticleDecay().
int Pythia6::GetMDCY (int i, int j) inline
Definition at line 186 of file Pythia6.hh.
References fPydat3, and Pydat3_t::MDCY.
ParticleVector* Pythia6::ImportParticles ()
Referenced by G4Pythia6Decayer::ImportParticles().
ParticleVector* Pythia6::ImportParticles ()
int Pythia6::ImportParticles (ParticleVector * particles, const char * option = "")
Default primary creation method. It reads the /HEPEVT/ common block which has been filled by the GenerateEvent method. If the event generator does not use the HEPEVT common block, This routine has to be overloaded by the subclasses. The function loops on the generated particles and store them in the TClonesArray pointed by the argument particles. The default action is to store only the stable particles (ISTHEP = 1) This can be demanded explicitly by setting the option = "Final" If the option = "All", all the particles are stored.
Definition at line 210 of file Pythia6.cc.
References fPyjets, i, it, Pyjets_t::K, Pyjets_t::N, Pyjets_t::P, and Pyjets_t::V.
int Pythia6::ImportParticles (ParticleVector * particles, const char * option = "")
Pythia6 * Pythia6::Instance () static
Static access method
Definition at line 118 of file Pythia6.cc.
References fgInstance, and Pythia6().
Referenced by G4Pythia6Decayer::CountProducts(), G4Pythia6Decayer::Decay(), G4Pythia6Decayer::ForceDecay(), G4Pythia6Decayer::ForceHadronicD(), G4Pythia6Decayer::ForceOmega(), G4Pythia6Decayer::ForceParticleDecay(), and G4Pythia6Decayer::ImportParticles().
static Pythia6* Pythia6::Instance () static
void Pythia6::Py1ent (int line, int kf, double pe, double theta, double phi)
void Pythia6::Py1ent (int line, int kf, double pe, double theta, double phi)
Add one entry to the event record, i.e. either a parton or a particle.
IP: normally line number for the parton/particle. There are two exceptions:
If IP = 0: line number 1 is used and PYEXEC is called. If IP < 0: line -IP is used, with status code K(-IP,2)=2 rather than 1; thus a parton system may be built up by filling all but the last parton of the system with IP < 0. KF: parton/particle flavour code (PDG code) PE: parton/particle energy. If PE is smaller than the mass, the parton/particle is taken to be at rest. THETA: PHI: polar and azimuthal angle for the momentum vector of the parton/particle.
Definition at line 185 of file Pythia6.cc.
References py1ent.
Referenced by G4Pythia6Decayer::Decay().
int Pythia6::Pycomp (int kf)
Interface with fortran routine pycomp
Definition at line 176 of file Pythia6.cc.
References pycomp.
Referenced by G4Pythia6Decayer::ForceHadronicD(), G4Pythia6Decayer::ForceOmega(), and G4Pythia6Decayer::ForceParticleDecay().
int Pythia6::Pycomp (int kf)
void Pythia6::SetMDCY (int i, int j, int m) inline
Definition at line 188 of file Pythia6.hh.
References fPydat3, and Pydat3_t::MDCY.
Referenced by G4Pythia6Decayer::ForceHadronicD(), G4Pythia6Decayer::ForceOmega(), and G4Pythia6Decayer::ForceParticleDecay().
void Pythia6::SetMDCY (int i, int j, int m) inline
Definition at line 188 of file Pythia6.hh.
References fPydat3, and Pydat3_t::MDCY.
void Pythia6::SetMDME (int i, int j, int m) inline
Definition at line 189 of file Pythia6.hh.
References fPydat3, and Pydat3_t::MDME.
Referenced by G4Pythia6Decayer::ForceHadronicD(), G4Pythia6Decayer::ForceOmega(), and G4Pythia6Decayer::ForceParticleDecay().
void Pythia6::SetMDME (int i, int j, int m) inline
Definition at line 189 of file Pythia6.hh.
References fPydat3, and Pydat3_t::MDME.
void Pythia6::SetMSTJ (int i, int m) inline
Definition at line 182 of file Pythia6.hh.
References fPydat1, and Pydat1_t::MSTJ.
Referenced by G4Pythia6Decayer::ForceDecay().
void Pythia6::SetMSTJ (int i, int m) inline
Definition at line 182 of file Pythia6.hh.
References fPydat1, and Pydat1_t::MSTJ.
Member Data Documentation
static Pythia6 * Pythia6::fgInstance = 0 static private
Definition at line 192 of file Pythia6.hh.
Referenced by Instance(), and Pythia6().
ParticleVector * Pythia6::fParticles private
Definition at line 194 of file Pythia6.hh.
Referenced by Pythia6(), and ~Pythia6().
Pydat1_t * Pythia6::fPydat1 private
Definition at line 196 of file Pythia6.hh.
Referenced by Pythia6(), and SetMSTJ().
Pydat3_t * Pythia6::fPydat3 private
Definition at line 197 of file Pythia6.hh.
Referenced by GetKFDP(), GetMDCY(), Pythia6(), SetMDCY(), and SetMDME().
Pyjets_t * Pythia6::fPyjets private
Definition at line 195 of file Pythia6.hh.
Referenced by ImportParticles(), and Pythia6().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4decayer/Pythia6.hh
analysis/blob/master/EMCal-analysis/DirectPhoton/Pythia6.hh
coresoftware/blob/master/simulation/g4simulation/g4decayer/Pythia6.cc