Analysis Software: PHFieldConfig Class Reference
PHFieldConfig Class Reference
PHFieldConfig store field configuration information.
#include <coresoftware/blob/master/offline/packages/PHField/PHFieldConfig.h>
Public Types
enum FieldConfigTypes {
kFieldUniform = 0, kField2D = 2, kField3DCylindrical = 3, Field3DCartesian = 1,
kFieldInvalid = 9999
}
Public Member Functions
virtual ~PHFieldConfig ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual FieldConfigTypes get_field_config () const
std::string get_field_config_description () const
virtual void set_field_config (FieldConfigTypes fieldConfig)
virtual const std::string & get_filename () const
virtual void set_filename (const std::string &filename)
virtual double get_magfield_rescale () const
virtual void set_magfield_rescale (double magfieldRescale)
virtual double get_field_mag_x () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_x (double fieldMagX)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_y () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_y (double fieldMagY)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual double get_field_mag_z () const
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
virtual void set_field_mag_z (double fieldMagZ)
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
PHFieldConfig ()
pure virtual interface class. not for direct use
Static Protected Attributes
static const std::string kInvalid_FileName
Detailed Description
PHFieldConfig store field configuration information.
Definition at line 21 of file PHFieldConfig.h.
Member Enumeration Documentation
enum PHFieldConfig::FieldConfigTypes
Enumerator:
kFieldUniform
Constant field.
kField2D
2D field map expressed in cylindrical coordinates
kField3DCylindrical
3D field map expressed in cylindrical coordinates
Field3DCartesian
3D field map expressed in Cartesian coordinates
kFieldInvalid
invalid value
Definition at line 42 of file PHFieldConfig.h.
Constructor & Destructor Documentation
virtual PHFieldConfig::~PHFieldConfig () inline virtual
Definition at line 24 of file PHFieldConfig.h.
PHFieldConfig::PHFieldConfig () inline protected
pure virtual interface class. not for direct use
Definition at line 90 of file PHFieldConfig.h.
Member Function Documentation
virtual PHObject* PHFieldConfig::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in PHFieldConfigv1, and PHFieldConfigv2.
Definition at line 40 of file PHFieldConfig.h.
Referenced by PHFieldUtility::GetFieldConfigNode().
PHFieldConfig::FieldConfigTypes PHFieldConfig::get_field_config () const virtual
Reimplemented in PHFieldConfigv1, and PHFieldConfigv2.
Definition at line 60 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
string PHFieldConfig::get_field_config_description () const
Definition at line 20 of file PHFieldConfig.cc.
Referenced by PHFieldConfigv1::identify(), and PHFieldConfigv2::identify().
double PHFieldConfig::get_field_mag_x () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfigv2.
Definition at line 88 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
double PHFieldConfig::get_field_mag_y () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfigv2.
Definition at line 99 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
double PHFieldConfig::get_field_mag_z () const virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfigv2.
Definition at line 110 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
const std::string & PHFieldConfig::get_filename () const virtual
Reimplemented in PHFieldConfigv1.
Definition at line 69 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
double PHFieldConfig::get_magfield_rescale () const virtual
Reimplemented in PHFieldConfigv1.
Definition at line 78 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap().
void PHFieldConfig::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHFieldConfigv1, and PHFieldConfigv2.
Definition at line 44 of file PHFieldConfig.cc.
Referenced by PHFieldUtility::BuildFieldMap(), and PHFieldUtility::GetFieldConfigNode().
int PHFieldConfig::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in PHFieldConfigv1, and PHFieldConfigv2.
Definition at line 55 of file PHFieldConfig.cc.
void PHFieldConfig::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in PHFieldConfigv1, and PHFieldConfigv2.
Definition at line 50 of file PHFieldConfig.cc.
void PHFieldConfig::set_field_config (PHFieldConfig::FieldConfigTypes fieldConfig) virtual
Definition at line 65 of file PHFieldConfig.cc.
void PHFieldConfig::set_field_mag_x (double fieldMagX) virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfigv2.
Definition at line 94 of file PHFieldConfig.cc.
void PHFieldConfig::set_field_mag_y (double fieldMagY) virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfigv2.
Definition at line 105 of file PHFieldConfig.cc.
void PHFieldConfig::set_field_mag_z (double fieldMagZ) virtual
field value in Tesla for uniform field model ONLY for PHFieldConfig_v2
Reimplemented in PHFieldConfigv2.
Definition at line 116 of file PHFieldConfig.cc.
void PHFieldConfig::set_filename (const std::string & filename) virtual
Reimplemented in PHFieldConfigv1.
Definition at line 74 of file PHFieldConfig.cc.
void PHFieldConfig::set_magfield_rescale (double magfieldRescale) virtual
Reimplemented in PHFieldConfigv1.
Definition at line 83 of file PHFieldConfig.cc.
Member Data Documentation
const std::string PHFieldConfig::kInvalid_FileName static protected
Definition at line 92 of file PHFieldConfig.h.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHField/PHFieldConfig.h
coresoftware/blob/master/offline/packages/PHField/PHFieldConfig.cc