Analysis Software: PHG4InnerHcalSubsystem Class Reference
PHG4InnerHcalSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h>
Public Member Functions
PHG4InnerHcalSubsystem (const std::string &name="HCALIN", const int layer=0)
constructor
virtual ~PHG4InnerHcalSubsystem ()
destructor
int InitRunSubsystem (PHCompositeNode *)
int process_event (PHCompositeNode *)
event processing
void Print (const std::string &what="ALL") const
Print info (from SubsysReco)
PHG4Detector * GetDetector (void) const
accessors (reimplemented)
PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
Public Member Functions inherited from PHG4DetectorSubsystem
virtual ~PHG4DetectorSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams () const
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters ()
Private Attributes
PHG4InnerHcalDetector * m_Detector
detector geometry
PHG4SteppingAction * m_SteppingAction
detector "stepping" action, executes after every G4 step
PHG4DisplayAction * m_DisplayAction
display attribute setting
Additional Inherited Members
Public Types inherited from PHG4DetectorSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Protected Member Functions inherited from PHG4DetectorSubsystem
PHG4DetectorSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
int BeginRunExecuted () const
Detailed Description
Definition at line 16 of file PHG4InnerHcalSubsystem.h.
Constructor & Destructor Documentation
PHG4InnerHcalSubsystem::PHG4InnerHcalSubsystem (const std::string & name = "HCALIN", const int layer = 0)
constructor
Definition at line 33 of file PHG4InnerHcalSubsystem.cc.
References PHG4DetectorSubsystem::InitializeParameters().
PHG4InnerHcalSubsystem::~PHG4InnerHcalSubsystem () virtual
destructor
Definition at line 43 of file PHG4InnerHcalSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
PHG4Detector * PHG4InnerHcalSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 148 of file PHG4InnerHcalSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4InnerHcalSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 45 of file PHG4InnerHcalSubsystem.h.
References m_DisplayAction.
PHG4SteppingAction* PHG4InnerHcalSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 44 of file PHG4InnerHcalSubsystem.h.
References m_SteppingAction.
int PHG4InnerHcalSubsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
creates the m_Detector object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorSubsystem.
Definition at line 49 of file PHG4InnerHcalSubsystem.cc.
References PHCompositeNode::addNode(), PHG4DetectorSubsystem::CheckOverlap(), PHNodeIterator::findFirst(), PHParameters::get_int_param(), PHG4DetectorSubsystem::get_int_param(), PHG4DetectorSubsystem::GetParams(), m_Detector, m_DisplayAction, m_SteppingAction, Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHG4InnerHcalDetector::SuperDetector(), PHG4DetectorSubsystem::SuperDetector(), and PHG4Detector::topNode().
void PHG4InnerHcalSubsystem::Print (const std::string & what = "ALL") const virtual
Print info (from SubsysReco)
Reimplemented from SubsysReco.
Definition at line 131 of file PHG4InnerHcalSubsystem.cc.
References PHG4DetectorSubsystem::GetParams(), m_Detector, m_SteppingAction, Fun4AllBase::Name(), PHParameters::Print(), PHG4InnerHcalDetector::Print(), and PHG4SteppingAction::Print().
int PHG4InnerHcalSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 120 of file PHG4InnerHcalSubsystem.cc.
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4InnerHcalSubsystem::SetDefaultParameters () private virtual
Implements PHG4DetectorSubsystem.
Definition at line 153 of file PHG4InnerHcalSubsystem.cc.
References PHG4HcalDefs::innerrad, PHG4HcalDefs::n_scinti_tiles, PHG4HcalDefs::n_towers, PHG4HcalDefs::outerrad, PHG4HcalDefs::scipertwr, PHG4DetectorSubsystem::set_default_double_param(), PHG4DetectorSubsystem::set_default_int_param(), and PHG4DetectorSubsystem::set_default_string_param().
void PHG4InnerHcalSubsystem::SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
Definition at line 192 of file PHG4InnerHcalSubsystem.cc.
References PHG4DetectorSubsystem::set_double_param().
Member Data Documentation
PHG4InnerHcalDetector* PHG4InnerHcalSubsystem::m_Detector private
detector geometry
derives from PHG4Detector
Definition at line 54 of file PHG4InnerHcalSubsystem.h.
Referenced by GetDetector(), InitRunSubsystem(), and Print().
PHG4DisplayAction* PHG4InnerHcalSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 62 of file PHG4InnerHcalSubsystem.h.
Referenced by GetDisplayAction(), InitRunSubsystem(), and ~PHG4InnerHcalSubsystem().
PHG4SteppingAction* PHG4InnerHcalSubsystem::m_SteppingAction private
detector "stepping" action, executes after every G4 step
derives from PHG4SteppingAction
Definition at line 58 of file PHG4InnerHcalSubsystem.h.
Referenced by GetSteppingAction(), InitRunSubsystem(), Print(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc