Analysis Software: RawClusterUtility Class Reference
RawClusterUtility Class Reference
RawClusterUtility.
#include <coresoftware/blob/master/offline/packages/CaloBase/RawClusterUtility.h>
Public Member Functions
virtual ~RawClusterUtility ()
Static Public Member Functions
static float GetPolarAngle (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
polar angle of cluster with respect to given vertex position
static float GetAzimuthAngle (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
azimuth angle of cluster with respect to given vertex position
static float GetPseudorapidity (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
Pseudorapidity of cluster with respect to given vertex position.
static float GetET (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
Transverse energy of cluster with respect to given vertex position.
static float GetETCore (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
Transverse core energy of cluster with respect to given vertex position.
static CLHEP::Hep3Vector GetEVec (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
Get energy vector of cluster based on cluster energy.
static CLHEP::Hep3Vector GetECoreVec (const RawCluster &cluster, const CLHEP::Hep3Vector vertex)
Get energy vector of cluster based on E_core.
Private Member Functions
RawClusterUtility ()
not intended to make an instance
Detailed Description
RawClusterUtility.
Definition at line 21 of file RawClusterUtility.h.
Constructor & Destructor Documentation
virtual RawClusterUtility::~RawClusterUtility () inline virtual
Definition at line 24 of file RawClusterUtility.h.
RawClusterUtility::RawClusterUtility () inline private
not intended to make an instance
Definition at line 65 of file RawClusterUtility.h.
Member Function Documentation
static float RawClusterUtility::GetAzimuthAngle (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
azimuth angle of cluster with respect to given vertex position
Definition at line 33 of file RawClusterUtility.h.
References RawCluster::get_position().
static CLHEP::Hep3Vector RawClusterUtility::GetECoreVec (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
Get energy vector of cluster based on E_core.
Definition at line 61 of file RawClusterUtility.h.
References RawCluster::get_ecore(), and RawCluster::get_position().
Referenced by PhotonJet::ConeSum(), AnaTutorial::getEMCalClusters(), PhotonJet::GetRecoHadronsAndJets(), PhotonJet::GetRecoHadronsAndJetsAA(), Forward_pi0s::process_event(), and PhotonJet::process_event().
static float RawClusterUtility::GetET (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
Transverse energy of cluster with respect to given vertex position.
Definition at line 41 of file RawClusterUtility.h.
References RawCluster::get_energy(), and RawCluster::get_position().
static float RawClusterUtility::GetETCore (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
Transverse core energy of cluster with respect to given vertex position.
Definition at line 51 of file RawClusterUtility.h.
References RawCluster::get_ecore(), and RawCluster::get_position().
static CLHEP::Hep3Vector RawClusterUtility::GetEVec (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
Get energy vector of cluster based on cluster energy.
Definition at line 59 of file RawClusterUtility.h.
References RawCluster::get_energy(), and RawCluster::get_position().
Referenced by ClusterJetInput::get_input(), ClusterIso::process_event(), Forward_pi0s::process_event(), Photons::process_event(), PJTranslator::process_event(), and PHFlowJetMaker::run_particle_flow().
static float RawClusterUtility::GetPolarAngle (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
polar angle of cluster with respect to given vertex position
Definition at line 29 of file RawClusterUtility.h.
References RawCluster::get_position().
static float RawClusterUtility::GetPseudorapidity (const RawCluster & cluster, const CLHEP::Hep3Vector vertex) inline static
Pseudorapidity of cluster with respect to given vertex position.
Definition at line 37 of file RawClusterUtility.h.
References RawCluster::get_position().
Referenced by CaloEvaluator::fillOutputNtuples(), and PHGenFitTrackProjection::process_event().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/CaloBase/RawClusterUtility.h