Analysis Software: QAHistManagerDef Namespace Reference
QAHistManagerDef Namespace Reference
Functions
Fun4AllHistoManager * getHistoManager ()
Get a pointer to the default hist manager for QA modules.
void saveQARootFile (const std::string &file_name)
Save hist to root files.
void useLogBins (TAxis *axis)
utility function to
Variables
static const std::string HistoManagerName = "QA_HISTOS"
default name for QA histogram manager
Function Documentation
Fun4AllHistoManager * QAHistManagerDef::getHistoManager ()
Get a pointer to the default hist manager for QA modules.
Definition at line 28 of file QAHistManagerDef.cc.
References assert, Fun4AllServer::getHistoManager(), HistoManagerName, Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by QAG4SimulationCalorimeterSum::eval_trk_proj(), QAG4SimulationCalorimeter::Init(), QAG4SimulationCalorimeterSum::Init(), QAG4SimulationJet::Init(), QAG4SimulationCalorimeter::Init_Cluster(), QAG4SimulationCalorimeterSum::Init_Cluster(), QAG4SimulationCalorimeter::Init_G4Hit(), QAG4SimulationJet::Init_Spectrum(), QAG4SimulationCalorimeter::Init_Tower(), QAG4SimulationCalorimeterSum::Init_TrackProj(), QAG4SimulationJet::Init_TruthMatching(), QAG4SimulationCalorimeter::process_event(), QAG4SimulationCalorimeterSum::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), QAG4SimulationCalorimeterSum::process_event_Cluster(), QAG4SimulationCalorimeter::process_event_G4Hit(), QAG4SimulationCalorimeter::process_event_Tower(), QAG4SimulationCalorimeterSum::process_event_TrackProj(), QAG4SimulationJet::process_Spectrum(), QAG4SimulationJet::process_TruthMatching(), and saveQARootFile().
void QAHistManagerDef::saveQARootFile (const std::string & file_name)
Save hist to root files.
Save hist to root files. It will overwrite the old file if exist.
Definition at line 48 of file QAHistManagerDef.cc.
References Fun4AllHistoManager::dumpHistos(), and getHistoManager().
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), Fun4All_G4_Prototype4(), Fun4All_G4_sPHENIX(), and Fun4All_G4_W().
void QAHistManagerDef::useLogBins (TAxis * axis)
utility function to
utility function to convert TAxis to log scale binning (usually for x axis)
Definition at line 54 of file QAHistManagerDef.cc.
References assert, bins, and i.
Referenced by DCACheck(), EMCDistribution(), EMCDistribution_Fast(), EMCDistribution_PeakSample_Fast(), QAG4SimulationCalorimeter::Init_G4Hit(), QAG4SimulationJet::Init_Spectrum(), QAG4SimulationCalorimeter::Init_Tower(), and RecoCheck().
Variable Documentation
const std::string QAHistManagerDef::HistoManagerName = "QA_HISTOS" static
default name for QA histogram manager
Definition at line 29 of file QAHistManagerDef.h.
Referenced by getHistoManager().