Analysis Software: TrkrClusterv1 Class Reference
TrkrClusterv1 Class Reference
Version 1 of TrkrCluster.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv1.h>
Public Member Functions
TrkrClusterv1 ()
ctor
virtual ~TrkrClusterv1 ()
dtor
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void setClusKey (TrkrDefs::cluskey id)
virtual TrkrDefs::cluskey getClusKey () const
virtual float getX () const
virtual void setX (float x)
virtual float getY () const
virtual void setY (float y)
virtual float getZ () const
virtual void setZ (float z)
virtual float getPosition (int coor) const
virtual void setPosition (int coor, float xi)
virtual void setGlobal ()
virtual void setLocal ()
virtual bool isGlobal ()
virtual unsigned int getAdc () const
virtual void setAdc (unsigned int adc)
virtual float getSize (unsigned int i, unsigned int j) const
virtual void setSize (unsigned int i, unsigned int j, float value)
virtual float getError (unsigned int i, unsigned int j) const
virtual void setError (unsigned int i, unsigned int j, float value)
virtual float getPhiSize () const
virtual float getZSize () const
virtual float getRPhiError () const
virtual float getPhiError () const
virtual float getZError () const
Public Member Functions inherited from TrkrCluster
virtual ~TrkrCluster ()
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
unsigned int covarIndex (unsigned int i, unsigned int j) const
Protected Member Functions inherited from TrkrCluster
TrkrCluster ()
Protected Attributes
TrkrDefs::cluskey m_cluskey
float m_pos [3]
bool m_isGlobal
unsigned int m_adc
float m_size [6]
float m_err [6]
Detailed Description
Version 1 of TrkrCluster.
Note - D. McGlinchey June 2018: CINT does not like "override", so ignore where CINT complains. Should be checked with ROOT 6 once migration occurs.
Definition at line 25 of file TrkrClusterv1.h.
Constructor & Destructor Documentation
TrkrClusterv1::TrkrClusterv1 ()
ctor
Definition at line 16 of file TrkrClusterv1.cc.
References i, j, m_pos, setError(), and setSize().
Referenced by CloneMe().
virtual TrkrClusterv1::~TrkrClusterv1 () inline virtual
dtor
Definition at line 32 of file TrkrClusterv1.h.
Member Function Documentation
virtual PHObject* TrkrClusterv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 37 of file TrkrClusterv1.h.
References TrkrClusterv1().
unsigned int TrkrClusterv1::covarIndex (unsigned int i, unsigned int j) const protected
Definition at line 224 of file TrkrClusterv1.cc.
References boost::swap().
Referenced by getError(), getSize(), setError(), and setSize().
virtual unsigned int TrkrClusterv1::getAdc () const inline virtual
Reimplemented from TrkrCluster.
Definition at line 57 of file TrkrClusterv1.h.
References m_adc.
Referenced by identify().
virtual TrkrDefs::cluskey TrkrClusterv1::getClusKey () const inline virtual
Reimplemented from TrkrCluster.
Definition at line 39 of file TrkrClusterv1.h.
References m_cluskey.
Referenced by identify().
float TrkrClusterv1::getError (unsigned int i, unsigned int j) const virtual
Reimplemented from TrkrCluster.
Definition at line 123 of file TrkrClusterv1.cc.
References covarIndex(), and m_err.
Referenced by getRPhiError(), getZError(), identify(), and isValid().
float TrkrClusterv1::getPhiError () const virtual
Reimplemented from TrkrCluster.
Definition at line 166 of file TrkrClusterv1.cc.
References getRPhiError(), and m_pos.
float TrkrClusterv1::getPhiSize () const virtual
Reimplemented from TrkrCluster.
Definition at line 128 of file TrkrClusterv1.cc.
References getSize(), i, j, m_pos, and phi.
Referenced by identify().
virtual float TrkrClusterv1::getPosition (int coor) const inline virtual
Reimplemented from TrkrCluster.
Definition at line 49 of file TrkrClusterv1.h.
References m_pos.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), identify(), and isValid().
float TrkrClusterv1::getRPhiError () const virtual
Reimplemented from TrkrCluster.
Definition at line 173 of file TrkrClusterv1.cc.
References getError(), i, j, m_pos, and phi.
Referenced by getPhiError().
float TrkrClusterv1::getSize (unsigned int i, unsigned int j) const virtual
Reimplemented from TrkrCluster.
Definition at line 112 of file TrkrClusterv1.cc.
References covarIndex(), and m_size.
Referenced by getPhiSize(), getZSize(), identify(), and isValid().
virtual float TrkrClusterv1::getX () const inline virtual
Reimplemented from TrkrCluster.
Definition at line 43 of file TrkrClusterv1.h.
References m_pos.
virtual float TrkrClusterv1::getY () const inline virtual
Reimplemented from TrkrCluster.
Definition at line 45 of file TrkrClusterv1.h.
References m_pos.
virtual float TrkrClusterv1::getZ () const inline virtual
Reimplemented from TrkrCluster.
Definition at line 47 of file TrkrClusterv1.h.
References m_pos.
float TrkrClusterv1::getZError () const virtual
Reimplemented from TrkrCluster.
Definition at line 219 of file TrkrClusterv1.cc.
References getError().
float TrkrClusterv1::getZSize () const virtual
Reimplemented from TrkrCluster.
Definition at line 161 of file TrkrClusterv1.cc.
References getSize().
Referenced by identify().
void TrkrClusterv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from TrkrCluster.
Definition at line 36 of file TrkrClusterv1.cc.
References getAdc(), getClusKey(), getError(), getPhiSize(), getPosition(), getSize(), getZSize(), and m_isGlobal.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual bool TrkrClusterv1::isGlobal () inline virtual
Reimplemented from TrkrCluster.
Definition at line 53 of file TrkrClusterv1.h.
References m_isGlobal.
int TrkrClusterv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from TrkrCluster.
Definition at line 86 of file TrkrClusterv1.cc.
References getError(), getPosition(), getSize(), i, j, m_adc, and m_cluskey.
virtual void TrkrClusterv1::Reset () inline virtual
Clear Event.
Reimplemented from TrkrCluster.
Definition at line 35 of file TrkrClusterv1.h.
virtual void TrkrClusterv1::setAdc (unsigned int adc) inline virtual
Reimplemented from TrkrCluster.
Definition at line 58 of file TrkrClusterv1.h.
References m_adc.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual void TrkrClusterv1::setClusKey (TrkrDefs::cluskey id) inline virtual
Reimplemented from TrkrCluster.
Definition at line 38 of file TrkrClusterv1.h.
References m_cluskey.
void TrkrClusterv1::setError (unsigned int i, unsigned int j, float value) virtual
Reimplemented from TrkrCluster.
Definition at line 117 of file TrkrClusterv1.cc.
References covarIndex(), m_err, and value.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), and TrkrClusterv1().
virtual void TrkrClusterv1::setGlobal () inline virtual
Reimplemented from TrkrCluster.
Definition at line 51 of file TrkrClusterv1.h.
References m_isGlobal.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
virtual void TrkrClusterv1::setLocal () inline virtual
Reimplemented from TrkrCluster.
Definition at line 52 of file TrkrClusterv1.h.
References m_isGlobal.
virtual void TrkrClusterv1::setPosition (int coor, float xi) inline virtual
Reimplemented from TrkrCluster.
Definition at line 50 of file TrkrClusterv1.h.
References m_pos.
Referenced by TpcPrototypeUnpacker::exportDSTCluster().
void TrkrClusterv1::setSize (unsigned int i, unsigned int j, float value) virtual
Reimplemented from TrkrCluster.
Definition at line 106 of file TrkrClusterv1.cc.
References covarIndex(), m_size, and value.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), and TrkrClusterv1().
virtual void TrkrClusterv1::setX (float x) inline virtual
Reimplemented from TrkrCluster.
Definition at line 44 of file TrkrClusterv1.h.
References m_pos, and x.
virtual void TrkrClusterv1::setY (float y) inline virtual
Reimplemented from TrkrCluster.
Definition at line 46 of file TrkrClusterv1.h.
References m_pos, and y.
virtual void TrkrClusterv1::setZ (float z) inline virtual
Reimplemented from TrkrCluster.
Definition at line 48 of file TrkrClusterv1.h.
References m_pos, and z.
Member Data Documentation
unsigned int TrkrClusterv1::m_adc protected
Definition at line 81 of file TrkrClusterv1.h.
Referenced by getAdc(), isValid(), and setAdc().
TrkrDefs::cluskey TrkrClusterv1::m_cluskey protected
Definition at line 78 of file TrkrClusterv1.h.
Referenced by getClusKey(), isValid(), and setClusKey().
float TrkrClusterv1::m_err[6] protected
Definition at line 83 of file TrkrClusterv1.h.
Referenced by getError(), and setError().
bool TrkrClusterv1::m_isGlobal protected
Definition at line 80 of file TrkrClusterv1.h.
Referenced by identify(), isGlobal(), setGlobal(), and setLocal().
float TrkrClusterv1::m_pos[3] protected
Definition at line 79 of file TrkrClusterv1.h.
Referenced by getPhiError(), getPhiSize(), getPosition(), getRPhiError(), getX(), getY(), getZ(), setPosition(), setX(), setY(), setZ(), and TrkrClusterv1().
float TrkrClusterv1::m_size[6] protected
Definition at line 82 of file TrkrClusterv1.h.
Referenced by getSize(), and setSize().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv1.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterv1.cc