Analysis Software: PgPostApplication Class Reference
PgPostApplication Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostApplication.h>
Public Member Functions
virtual ~PgPostApplication ()
PdbStatus startUpdate ()
PdbStatus startRead ()
PdbStatus commit ()
PdbStatus commit (PdbCalBank *)
PdbStatus commit (PdbCalBank *, int rid, long, long, long)
PdbStatus abort ()
PdbStatus isActive ()
TSQLConnection * getConnection ()
int setDBName (const std::string &name)
int DisconnectDB ()
Public Member Functions inherited from PdbApplication
virtual ~PdbApplication ()
Static Public Member Functions
static int Register (const std::string &dbname="calibrations")
static int releaseConnection ()
static PgPostApplication * instance ()
Static Public Member Functions inherited from PdbApplication
static PdbApplication * instance ()
Protected Member Functions
PgPostApplication (const std::string &dbname)
Protected Member Functions inherited from PdbApplication
PdbApplication ()
Protected Attributes
bool readOnly
std::string dsn
Static Protected Attributes
static TSQLConnection * con = nullptr
static PgPostApplication * mySpecificCopy = nullptr
Static Protected Attributes inherited from PdbApplication
static std::unique_ptr
< PdbApplication > __instance
Detailed Description
Definition at line 14 of file PgPostApplication.h.
Constructor & Destructor Documentation
PgPostApplication::PgPostApplication (const std::string & dbname) protected
Definition at line 66 of file PgPostApplication.cc.
PgPostApplication::~PgPostApplication () virtual
Definition at line 72 of file PgPostApplication.cc.
References con, and mySpecificCopy.
Member Function Documentation
PdbStatus PgPostApplication::abort () virtual
Implements PdbApplication.
Definition at line 132 of file PgPostApplication.cc.
References PgPostBankWrapperManager::clear(), con, and PgPostBankWrapperManager::instance().
PdbStatus PgPostApplication::commit () virtual
Implements PdbApplication.
Definition at line 141 of file PgPostApplication.cc.
References PgPostBankWrapperManager::clear(), PgPostBankWrapperManager::commit(), con, PgPostBankWrapperManager::instance(), and readOnly.
PdbStatus PgPostApplication::commit (PdbCalBank * b) virtual
Implements PdbApplication.
Definition at line 159 of file PgPostApplication.cc.
References PgPostBankWrapper::commit(), and PHWHERE.
PdbStatus PgPostApplication::commit (PdbCalBank * b, int rid, long it, long st, long et) virtual
Implements PdbApplication.
Definition at line 174 of file PgPostApplication.cc.
References PgPostBankWrapper::commit(), and PHWHERE.
int PgPostApplication::DisconnectDB () virtual
Implements PdbApplication.
Definition at line 188 of file PgPostApplication.cc.
References con.
TSQLConnection * PgPostApplication::getConnection ()
Definition at line 82 of file PgPostApplication.cc.
References PdbApplication::__instance, con, dsn, and Register().
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupManager::deleteODBCPreparedStatement(), PgPostBankBackupManager::deleteSQLStatement(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), PgPostBankBackupManager::fetchBank(), PgPostBankBackupManager::getListOfRId(), PgPostBankBackupManager::getTotalRowCount(), PgPostCalBankIterator::init(), and PgPostBankBackupManager::isRIdExist().
PgPostApplication * PgPostApplication::instance () static
Definition at line 42 of file PgPostApplication.cc.
Referenced by PgPostBankBackupManager::CleanTable(), PgPostBankWrapper::commit(), PgPostBankBackupManager::commit(), PgPostBankBackupManager::commitAllBankfromTFile(), PgPostBankBackupManager::deleteODBCPreparedStatement(), PgPostBankBackupManager::deleteSQLStatement(), PgPostBankBackupManager::dumpTable(), PgPostBankBackupManager::fetchAllBank2TFile(), PgPostBankManager::fetchBank(), PgPostBankBackupManager::fetchBank(), PgPostBankManager::getApplication(), PgPostBankBackupManager::getListOfRId(), PgPostBankBackupManager::getTotalRowCount(), and PgPostBankBackupManager::isRIdExist().
PdbStatus PgPostApplication::isActive () inline virtual
Implements PdbApplication.
Definition at line 28 of file PgPostApplication.h.
int PgPostApplication::Register (const std::string & dbname = "calibrations") static
Definition at line 47 of file PgPostApplication.cc.
Referenced by getConnection().
int PgPostApplication::releaseConnection () static
Definition at line 55 of file PgPostApplication.cc.
int PgPostApplication::setDBName (const std::string & name) virtual
Implements PdbApplication.
Definition at line 97 of file PgPostApplication.cc.
References con, dsn, name, and PHWHERE.
PdbStatus PgPostApplication::startRead () virtual
Implements PdbApplication.
Definition at line 125 of file PgPostApplication.cc.
References readOnly.
Referenced by PgPostCalBankIterator::init().
PdbStatus PgPostApplication::startUpdate () virtual
Implements PdbApplication.
Definition at line 118 of file PgPostApplication.cc.
References readOnly.
Member Data Documentation
TSQLConnection * PgPostApplication::con = nullptr static protected
Definition at line 38 of file PgPostApplication.h.
Referenced by abort(), commit(), DisconnectDB(), getConnection(), setDBName(), and ~PgPostApplication().
std::string PgPostApplication::dsn protected
Definition at line 41 of file PgPostApplication.h.
Referenced by getConnection(), and setDBName().
PgPostApplication * PgPostApplication::mySpecificCopy = nullptr static protected
Definition at line 39 of file PgPostApplication.h.
Referenced by ~PgPostApplication().
bool PgPostApplication::readOnly protected
Definition at line 40 of file PgPostApplication.h.
Referenced by commit(), startRead(), and startUpdate().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostApplication.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostApplication.cc