Analysis Software: PHG4RICHSubsystem Class Reference
PHG4RICHSubsystem Class Reference
Fun4All module to simulate the RICH detector.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4RICHSubsystem.h>
Public Member Functions
PHG4RICHSubsystem (const std::string &name="RICH")
constructor
virtual ~PHG4RICHSubsystem ()
destructor
int Init (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
ePHENIXRICH::RICH_Geometry & get_RICH_geometry ()
void set_RICH_geometry (const ePHENIXRICH::RICH_Geometry &g)
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4RICHDetector * m_Detector
detector geometry
PHG4DisplayAction * m_DisplayAction
display attribute setting
ePHENIXRICH::RICH_Geometry geom
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Fun4All module to simulate the RICH detector.
The detector is constructed and registered via PHG4RICHDetector, ePHENIXRICH::ePHENIXRICHConstruction and ePHENIXRICH::RICH_Geometry.
The PHG4SteppingAction provides the method to detect Cerenkov photons. The x,y,z positions of where photons are detected are stored in a PHG4Hits collection.
See Also
ePHENIXRICH::RICH_Geometry
ePHENIXRICH::ePHENIXRICHConstruction
PHG4RICHDetector
PHG4RICHSteppingAction
PHG4RICHSubsystem
Definition at line 42 of file PHG4RICHSubsystem.h.
Constructor & Destructor Documentation
PHG4RICHSubsystem::PHG4RICHSubsystem (const std::string & name = "RICH")
constructor
Definition at line 35 of file PHG4RICHSubsystem.cc.
PHG4RICHSubsystem::~PHG4RICHSubsystem () virtual
destructor
Definition at line 43 of file PHG4RICHSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
ePHENIXRICH::RICH_Geometry& PHG4RICHSubsystem::get_RICH_geometry () inline
Definition at line 70 of file PHG4RICHSubsystem.h.
References geom.
Referenced by RICHSetup().
PHG4Detector * PHG4RICHSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 82 of file PHG4RICHSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4RICHSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 68 of file PHG4RICHSubsystem.h.
References m_DisplayAction.
int PHG4RICHSubsystem::Init (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 49 of file PHG4RICHSubsystem.cc.
References PHCompositeNode::addNode(), PHG4Subsystem::CheckOverlap(), PHNodeIterator::findFirst(), geom, m_Detector, m_DisplayAction, Fun4AllBase::Name(), PHG4RICHDetector::OverlapCheck(), PHG4Detector::topNode(), PHG4Detector::Verbosity(), and Fun4AllBase::Verbosity().
int PHG4RICHSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 73 of file PHG4RICHSubsystem.cc.
References PHG4RICHDetector::GetSteppingAction(), and m_Detector.
void PHG4RICHSubsystem::set_RICH_geometry (const ePHENIXRICH::RICH_Geometry & g) inline
Definition at line 72 of file PHG4RICHSubsystem.h.
References g, and geom.
Member Data Documentation
ePHENIXRICH::RICH_Geometry PHG4RICHSubsystem::geom private
Definition at line 82 of file PHG4RICHSubsystem.h.
Referenced by get_RICH_geometry(), Init(), and set_RICH_geometry().
PHG4RICHDetector* PHG4RICHSubsystem::m_Detector private
detector geometry
defives from PHG4Detector
Definition at line 77 of file PHG4RICHSubsystem.h.
Referenced by GetDetector(), Init(), and process_event().
PHG4DisplayAction* PHG4RICHSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 80 of file PHG4RICHSubsystem.h.
Referenced by GetDisplayAction(), Init(), and ~PHG4RICHSubsystem().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4RICHSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4RICHSubsystem.cc