Analysis Software: macros/blob/master/macros/g4simulations/G4_HcalOut_ref.C File Reference
G4_HcalOut_ref.C File Reference
#include "GlobalVariables.C"
#include <caloreco/RawClusterBuilderGraph.h>
#include <caloreco/RawClusterBuilderTemplate.h>
#include <caloreco/RawTowerCalibration.h>
#include <fun4all/Fun4AllServer.h>
#include <g4calo/HcalRawTowerBuilder.h>
#include <g4calo/RawTowerDigitizer.h>
#include <g4detectors/PHG4OuterHcalSubsystem.h>
#include <g4detectors/PHG4HcalCellReco.h>
#include <g4eval/CaloEvaluator.h>
#include <g4main/PHG4Reco.h>
Enumerations
enum enu_HCalOut_clusterizer { kHCalOutGraphClusterizer, kHCalOutTemplateClusterizer, kHCalOutGraphClusterizer, kHCalOutTemplateClusterizer }
Functions
void HCalOuterInit ()
graph clusterizer, RawClusterBuilderGraph
double HCalOuter (PHG4Reco *g4Reco, double radius, const int crossings, const int absorberactive=0, int verbosity=0)
void HCALOuter_Cells (int verbosity=0)
void HCALOuter_Towers (int verbosity=0)
void HCALOuter_Clusters (int verbosity=0)
void HCALOuter_Eval (std::string outputfile, int verbosity=0)
Variables
enu_HCalOut_clusterizer HCalOut_clusterizer = kHCalOutTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Enumeration Type Documentation
enum enu_HCalOut_clusterizer
Enumerator:
kHCalOutGraphClusterizer
kHCalOutTemplateClusterizer
kHCalOutGraphClusterizer
kHCalOutTemplateClusterizer
Definition at line 20 of file G4_HcalOut_ref.C.
Function Documentation
double HCalOuter (PHG4Reco * g4Reco, double radius, const int crossings, const int absorberactive = 0, int verbosity = 0)
Definition at line 35 of file G4_HcalOut_ref.C.
References PHG4DetectorSubsystem::get_double_param(), no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::SetAbsorberActive(), PHG4DetectorSubsystem::SetActive(), and PHG4DetectorSubsystem::SuperDetector().
Referenced by G4Setup().
void HCALOuter_Cells (int verbosity = 0)
Definition at line 99 of file G4_HcalOut_ref.C.
References PHG4HcalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCALOuter_Clusters (int verbosity = 0)
Definition at line 161 of file G4_HcalOut_ref.C.
References RawClusterBuilderGraph::Detector(), RawClusterBuilderTemplate::Detector(), Fun4AllServer::instance(), kHCalOutGraphClusterizer, kHCalOutTemplateClusterizer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCALOuter_Eval (std::string outputfile, int verbosity = 0)
Definition at line 191 of file G4_HcalOut_ref.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCALOuter_Towers (int verbosity = 0)
Definition at line 121 of file G4_HcalOut_ref.C.
References HcalRawTowerBuilder::Detector(), RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), Fun4AllServer::instance(), RawTowerCalibration::kSimple_linear_calibration, RawTowerDigitizer::kSimple_photon_digitalization, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerDigitizer::set_pedstal_central_ADC(), RawTowerDigitizer::set_pedstal_width_ADC(), RawTowerDigitizer::set_photonelec_ADC(), RawTowerDigitizer::set_photonelec_yield_visible_GeV(), HcalRawTowerBuilder::set_sim_tower_node_prefix(), RawTowerDigitizer::set_zero_suppression_ADC(), RawTowerCalibration::set_zero_suppression_GeV(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void HCalOuterInit ()
graph clusterizer, RawClusterBuilderGraph
Definition at line 33 of file G4_HcalOut_ref.C.
Referenced by G4Init().
Variable Documentation
enu_HCalOut_clusterizer HCalOut_clusterizer = kHCalOutTemplateClusterizer
template clusterizer, RawClusterBuilderTemplate, as developed by Sasha Bazilevsky
Definition at line 28 of file G4_HcalOut_ref.C.
Referenced by HCALOuter_Clusters().