Analysis Software: Fun4AllOscarInputManager Class Reference
Fun4AllOscarInputManager Class Reference
#include <coresoftware/blob/master/generators/phhepmc/Fun4AllOscarInputManager.h>
Public Member Functions
Fun4AllOscarInputManager (const std::string &name="DUMMY", const std::string &topnodename="TOP")
virtual ~Fun4AllOscarInputManager ()
int fileopen (const std::string &filenam)
int fileclose ()
int run (const int nevents=0)
void Print (const std::string &what="ALL") const
int ResetEvent ()
int PushBackEvents (const int i)
int skip (const int i)
int SyncIt (const SyncObject *)
int GetSyncObject (SyncObject **)
int NoSyncPushBackEvents (const int nevt)
int ConvertFromOscar ()
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
int events_total
int events_thisfile
std::string filename
std::string topNodeName
PHCompositeNode * topNode
HepMC::GenEvent * evt
int skipEvents
int skippedEvents
std::ifstream * filestream
std::istream * unzipstream
std::ifstream theOscarFile
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
bool isCompressed
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Detailed Description
Definition at line 21 of file Fun4AllOscarInputManager.h.
Constructor & Destructor Documentation
Fun4AllOscarInputManager::Fun4AllOscarInputManager (const std::string & name = "DUMMY", const std::string & topnodename = "TOP")
Definition at line 48 of file Fun4AllOscarInputManager.cc.
References PHCompositeNode::addNode(), Fun4AllServer::getNode(), hepmc_helper, Fun4AllInputManager::InputNode(), Fun4AllServer::instance(), PHHepMCGenHelper::set_geneventmap(), Fun4AllServer::topNode(), topNode, and topNodeName.
Fun4AllOscarInputManager::~Fun4AllOscarInputManager () virtual
Definition at line 76 of file Fun4AllOscarInputManager.cc.
References fileclose(), filestream, and unzipstream.
Member Function Documentation
int Fun4AllOscarInputManager::ConvertFromOscar ()
Definition at line 277 of file Fun4AllOscarInputManager.cc.
References E, PHHepMCGenEventMap::end(), events_total, evt, PHHepMCGenEventMap::find(), PHHepMCGenHelper::get_embedding_id(), PHHepMCGenHelper::get_geneventmap(), hepmc_helper, i, PHHepMCGenHelper::insert_event(), isCompressed, pid, skippedEvents, theOscarFile, toMM, v, and Fun4AllBase::Verbosity().
Referenced by run().
int Fun4AllOscarInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 207 of file Fun4AllOscarInputManager.cc.
References filestream, isCompressed, Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), theOscarFile, and Fun4AllInputManager::UpdateFileList().
Referenced by fileopen(), run(), and ~Fun4AllOscarInputManager().
int Fun4AllOscarInputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 83 of file Fun4AllOscarInputManager.cc.
References Fun4AllInputManager::AddToFileOpened(), Fun4AllSyncManager::CurrentRun(), events_thisfile, fileclose(), filename, filestream, PHFlag::FlagExist(), PHFlag::get_IntFlag(), in, recoConsts::instance(), isCompressed, Fun4AllInputManager::IsOpen(), FROG::location(), Fun4AllInputManager::MySyncManager(), Fun4AllBase::Name(), theOscarFile, unzipstream, Fun4AllBase::Verbosity(), and zinbuffer.
int Fun4AllOscarInputManager::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 69 of file Fun4AllOscarInputManager.h.
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
int Fun4AllOscarInputManager::GetSyncObject (SyncObject **) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 37 of file Fun4AllOscarInputManager.h.
References Fun4AllReturnCodes::SYNC_NOOBJECT.
int Fun4AllOscarInputManager::NoSyncPushBackEvents (const int nevt) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 38 of file Fun4AllOscarInputManager.h.
References PushBackEvents().
void Fun4AllOscarInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 229 of file Fun4AllOscarInputManager.cc.
References Fun4AllInputManager::Print().
int Fun4AllOscarInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 242 of file Fun4AllOscarInputManager.cc.
References skippedEvents, and theOscarFile.
Referenced by NoSyncPushBackEvents(), and skip().
int Fun4AllOscarInputManager::ResetEvent () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 235 of file Fun4AllOscarInputManager.cc.
int Fun4AllOscarInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 147 of file Fun4AllOscarInputManager.cc.
References ConvertFromOscar(), Fun4AllReturnCodes::EVENT_OK, events_thisfile, events_total, evt, fileclose(), Fun4AllInputManager::FileListEmpty(), Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), Fun4AllInputManager::RejectEvent(), and Fun4AllBase::Verbosity().
void Fun4AllOscarInputManager::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 75 of file Fun4AllOscarInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
void Fun4AllOscarInputManager::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 60 of file Fun4AllOscarInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
void Fun4AllOscarInputManager::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 42 of file Fun4AllOscarInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void Fun4AllOscarInputManager::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 48 of file Fun4AllOscarInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
void Fun4AllOscarInputManager::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 54 of file Fun4AllOscarInputManager.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
int Fun4AllOscarInputManager::skip (const int i) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 32 of file Fun4AllOscarInputManager.h.
References PushBackEvents().
int Fun4AllOscarInputManager::SyncIt (const SyncObject *) inline virtual
Reimplemented from Fun4AllInputManager.
Definition at line 36 of file Fun4AllOscarInputManager.h.
References Fun4AllReturnCodes::SYNC_OK.
Member Data Documentation
int Fun4AllOscarInputManager::events_thisfile protected
Definition at line 79 of file Fun4AllOscarInputManager.h.
Referenced by fileopen(), and run().
int Fun4AllOscarInputManager::events_total protected
Definition at line 78 of file Fun4AllOscarInputManager.h.
Referenced by ConvertFromOscar(), and run().
HepMC::GenEvent* Fun4AllOscarInputManager::evt protected
Definition at line 83 of file Fun4AllOscarInputManager.h.
Referenced by ConvertFromOscar(), and run().
std::string Fun4AllOscarInputManager::filename protected
Definition at line 80 of file Fun4AllOscarInputManager.h.
Referenced by fileopen().
std::ifstream* Fun4AllOscarInputManager::filestream protected
Definition at line 88 of file Fun4AllOscarInputManager.h.
Referenced by fileclose(), fileopen(), and ~Fun4AllOscarInputManager().
PHHepMCGenHelper Fun4AllOscarInputManager::hepmc_helper protected
helper for insert HepMC event to DST node and add vertex smearing
Definition at line 93 of file Fun4AllOscarInputManager.h.
Referenced by ConvertFromOscar(), Fun4AllOscarInputManager(), get_embedding_id(), set_embedding_id(), set_reuse_vertex(), set_vertex_distribution_function(), set_vertex_distribution_mean(), and set_vertex_distribution_width().
bool Fun4AllOscarInputManager::isCompressed protected
Definition at line 94 of file Fun4AllOscarInputManager.h.
Referenced by ConvertFromOscar(), fileclose(), and fileopen().
int Fun4AllOscarInputManager::skipEvents protected
Definition at line 85 of file Fun4AllOscarInputManager.h.
int Fun4AllOscarInputManager::skippedEvents protected
Definition at line 85 of file Fun4AllOscarInputManager.h.
Referenced by ConvertFromOscar(), and PushBackEvents().
std::ifstream Fun4AllOscarInputManager::theOscarFile protected
Definition at line 90 of file Fun4AllOscarInputManager.h.
Referenced by ConvertFromOscar(), fileclose(), fileopen(), and PushBackEvents().
PHCompositeNode* Fun4AllOscarInputManager::topNode protected
Definition at line 82 of file Fun4AllOscarInputManager.h.
Referenced by Fun4AllOscarInputManager().
std::string Fun4AllOscarInputManager::topNodeName protected
Definition at line 81 of file Fun4AllOscarInputManager.h.
Referenced by Fun4AllOscarInputManager().
std::istream* Fun4AllOscarInputManager::unzipstream protected
Definition at line 89 of file Fun4AllOscarInputManager.h.
Referenced by fileopen(), and ~Fun4AllOscarInputManager().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/Fun4AllOscarInputManager.h
coresoftware/blob/master/generators/phhepmc/Fun4AllOscarInputManager.cc