Analysis Software: SvtxCluster Class Reference
SvtxCluster Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxCluster.h>
Public Types
typedef std::set< unsigned int > HitSet
typedef std::set< unsigned int >
::const_iterator ConstHitIter
typedef std::set< unsigned int >
::iterator HitIter
Public Member Functions
virtual ~SvtxCluster ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual unsigned int get_id () const
virtual void set_id (unsigned int id)
virtual unsigned int get_layer () const
virtual void set_layer (unsigned int layer)
virtual float get_x () const
virtual void set_x (float x)
virtual float get_y () const
virtual void set_y (float y)
virtual float get_z () const
virtual void set_z (float z)
virtual float get_position (int coor) const
virtual void set_position (int coor, float xi)
virtual float get_e () const
virtual void set_e (float e)
virtual unsigned int get_adc () const
virtual void set_adc (unsigned int adc)
virtual float get_size (unsigned int i, unsigned int j) const
virtual void set_size (unsigned int i, unsigned int j, float value)
virtual float get_error (unsigned int i, unsigned int j) const
virtual void set_error (unsigned int i, unsigned int j, float value)
virtual void clear_hits ()
virtual bool empty_hits ()
virtual size_t size_hits ()
virtual void insert_hit (unsigned int hit_id)
virtual size_t erase_hit (unsigned int hit_id)
virtual ConstHitIter begin_hits () const
virtual ConstHitIter find_hit (unsigned int hitid) const
virtual ConstHitIter end_hits () const
virtual HitIter begin_hits ()
virtual HitIter find_hit (unsigned int hitid)
virtual HitIter end_hits ()
virtual float get_phi_size () const
virtual float get_z_size () const
virtual float get_phi_error () const
virtual float get_rphi_error () const
virtual float get_z_error () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxCluster ()
ClassDef (SvtxCluster, 1)
Detailed Description
Definition at line 11 of file SvtxCluster.h.
Member Typedef Documentation
typedef std::set<unsigned int>::const_iterator SvtxCluster::ConstHitIter
Definition at line 15 of file SvtxCluster.h.
typedef std::set<unsigned int>::iterator SvtxCluster::HitIter
Definition at line 16 of file SvtxCluster.h.
typedef std::set<unsigned int> SvtxCluster::HitSet
Definition at line 14 of file SvtxCluster.h.
Constructor & Destructor Documentation
virtual SvtxCluster::~SvtxCluster () inline virtual
Definition at line 18 of file SvtxCluster.h.
SvtxCluster::SvtxCluster () inline protected
Definition at line 87 of file SvtxCluster.h.
Member Function Documentation
virtual ConstHitIter SvtxCluster::begin_hits () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 70 of file SvtxCluster.h.
Referenced by Conversion::firstLayer(), BDiJetModule::MakeGenFitTrack(), and Conversion::trackDLayer().
virtual HitIter SvtxCluster::begin_hits () inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 73 of file SvtxCluster.h.
SvtxCluster::ClassDef (SvtxCluster , 1) protected
virtual void SvtxCluster::clear_hits () inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 65 of file SvtxCluster.h.
virtual PHObject* SvtxCluster::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxCluster_v1.
Definition at line 28 of file SvtxCluster.h.
Referenced by SvtxClusterMap_v1::insert().
virtual bool SvtxCluster::empty_hits () inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 66 of file SvtxCluster.h.
virtual ConstHitIter SvtxCluster::end_hits () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 72 of file SvtxCluster.h.
virtual HitIter SvtxCluster::end_hits () inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 75 of file SvtxCluster.h.
virtual size_t SvtxCluster::erase_hit (unsigned int hit_id) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 69 of file SvtxCluster.h.
virtual ConstHitIter SvtxCluster::find_hit (unsigned int hitid) const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 71 of file SvtxCluster.h.
virtual HitIter SvtxCluster::find_hit (unsigned int hitid) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 74 of file SvtxCluster.h.
virtual unsigned int SvtxCluster::get_adc () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 53 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluatorHaiwang::fillOutputNtuples().
virtual float SvtxCluster::get_e () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 50 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluatorHaiwang::fillOutputNtuples().
virtual float SvtxCluster::get_error (unsigned int i, unsigned int j) const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 59 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluatorHaiwang::fillOutputNtuples().
virtual unsigned int SvtxCluster::get_id () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 32 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxClusterMap_v1::operator=(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), and SvtxClusterMap_v1::SvtxClusterMap_v1().
virtual unsigned int SvtxCluster::get_layer () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 35 of file SvtxCluster.h.
Referenced by EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), Conversion::firstLayer(), Conversion::hasSilicon(), BDiJetModule::MakeGenFitTrack(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), TrackingPerformanceCheck::process_event(), BJetModule::process_event(), AnaMvtxTelescopeHits::process_event(), and BDiJetModule::process_event().
virtual float SvtxCluster::get_phi_error () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 82 of file SvtxCluster.h.
virtual float SvtxCluster::get_phi_size () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 79 of file SvtxCluster.h.
Referenced by AnaSvtxTracksForGenFit::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), and AnaMvtxTelescopeHits::process_event().
virtual float SvtxCluster::get_position (int coor) const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 47 of file SvtxCluster.h.
virtual float SvtxCluster::get_rphi_error () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 83 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and BDiJetModule::MakeGenFitTrack().
virtual float SvtxCluster::get_size (unsigned int i, unsigned int j) const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 56 of file SvtxCluster.h.
virtual float SvtxCluster::get_x () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 38 of file SvtxCluster.h.
Referenced by Conversion::dist(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), BDiJetModule::MakeGenFitTrack(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), and AnaMvtxTelescopeHits::process_event().
virtual float SvtxCluster::get_y () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 41 of file SvtxCluster.h.
Referenced by Conversion::dist(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), BDiJetModule::MakeGenFitTrack(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), and AnaMvtxTelescopeHits::process_event().
virtual float SvtxCluster::get_z () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 44 of file SvtxCluster.h.
Referenced by Conversion::dist(), AnaSvtxTracksForGenFit::fill_tree(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), BDiJetModule::MakeGenFitTrack(), SvtxEvaluatorHaiwang::printOutputInfo(), psTOFTimezeroEval::printOutputInfo(), and AnaMvtxTelescopeHits::process_event().
virtual float SvtxCluster::get_z_error () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 84 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and BDiJetModule::MakeGenFitTrack().
virtual float SvtxCluster::get_z_size () const inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 80 of file SvtxCluster.h.
Referenced by AnaSvtxTracksForGenFit::fill_tree(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), and AnaMvtxTelescopeHits::process_event().
virtual void SvtxCluster::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxCluster_v1.
Definition at line 22 of file SvtxCluster.h.
References os.
Referenced by psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), and psTOFTimezeroEval::printOutputInfo().
virtual void SvtxCluster::insert_hit (unsigned int hit_id) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 68 of file SvtxCluster.h.
virtual int SvtxCluster::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxCluster_v1.
Definition at line 27 of file SvtxCluster.h.
virtual void SvtxCluster::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxCluster_v1.
Definition at line 26 of file SvtxCluster.h.
virtual void SvtxCluster::set_adc (unsigned int adc) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 54 of file SvtxCluster.h.
virtual void SvtxCluster::set_e (float e) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 51 of file SvtxCluster.h.
virtual void SvtxCluster::set_error (unsigned int i, unsigned int j, float value) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 60 of file SvtxCluster.h.
virtual void SvtxCluster::set_id (unsigned int id) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 33 of file SvtxCluster.h.
virtual void SvtxCluster::set_layer (unsigned int layer) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 36 of file SvtxCluster.h.
virtual void SvtxCluster::set_position (int coor, float xi) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 48 of file SvtxCluster.h.
virtual void SvtxCluster::set_size (unsigned int i, unsigned int j, float value) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 57 of file SvtxCluster.h.
virtual void SvtxCluster::set_x (float x) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 39 of file SvtxCluster.h.
virtual void SvtxCluster::set_y (float y) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 42 of file SvtxCluster.h.
virtual void SvtxCluster::set_z (float z) inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 45 of file SvtxCluster.h.
virtual size_t SvtxCluster::size_hits () inline virtual
Reimplemented in SvtxCluster_v1.
Definition at line 67 of file SvtxCluster.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), and SvtxEvaluatorHaiwang::fillOutputNtuples().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxCluster.h