Analysis Software: HijJet1 Class Reference
HijJet1 Class Reference
Class definition for HijJet1, which is used to modify the Hijing HIJJET1 common.
#include <coresoftware/blob/master/generators/sHijing/HijJet1.h>
Classes
struct HIJJET1
Public Member Functions
HijJet1 ()
~HijJet1 ()
int & npj (int i)
int & kfpj (int i, int j)
float & pjpx (int i, int j)
float & pjpy (int i, int j)
float & pjpz (int i, int j)
float & pjpe (int i, int j)
float & pjpm (int i, int j)
int & ntj (int i)
int & kftj (int i, int j)
float & pjtx (int i, int j)
float & pjty (int i, int j)
float & pjtz (int i, int j)
float & pjte (int i, int j)
float & pjtm (int i, int j)
void init (void)
int lenI () const
int lenJ () const
Private Attributes
int _dummy
float _realdummy
Static Private Attributes
static const int _lenI = 300
static const int _lenJ = 500
static HIJJET1 * _hijjet1 =0
Friends
struct HIJJET1
Detailed Description
Class definition for HijJet1, which is used to modify the Hijing HIJJET1 common.
Definition at line 10 of file HijJet1.h.
Constructor & Destructor Documentation
HijJet1::HijJet1 () inline
Definition at line 78 of file HijJet1.h.
HijJet1::~HijJet1 () inline
Definition at line 85 of file HijJet1.h.
Member Function Documentation
void HijJet1::init (void) inline
Definition at line 73 of file HijJet1.h.
References _hijjet1, and hijjet1_address_().
Referenced by kfpj(), kftj(), npj(), ntj(), pjpe(), pjpm(), pjpx(), pjpy(), pjpz(), pjte(), pjtm(), pjtx(), pjty(), and pjtz().
int & HijJet1::kfpj (int i, int j) inline
Definition at line 97 of file HijJet1.h.
References _dummy, _hijjet1, init(), HijJet1::HIJJET1::kfpj, lenI(), and lenJ().
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
int & HijJet1::kftj (int i, int j) inline
Definition at line 165 of file HijJet1.h.
References _dummy, _hijjet1, init(), HijJet1::HIJJET1::kftj, lenI(), and lenJ().
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
int HijJet1::lenI () const inline
Definition at line 33 of file HijJet1.h.
References _lenI.
Referenced by kfpj(), kftj(), npj(), ntj(), pjpe(), pjpm(), pjpx(), pjpy(), pjpz(), pjte(), pjtm(), pjtx(), pjty(), and pjtz().
int HijJet1::lenJ () const inline
Definition at line 34 of file HijJet1.h.
References _lenJ.
Referenced by kfpj(), kftj(), pjpe(), pjpm(), pjpx(), pjpy(), pjpz(), pjte(), pjtm(), pjtx(), pjty(), and pjtz().
int & HijJet1::npj (int i) inline
Definition at line 89 of file HijJet1.h.
References _dummy, _hijjet1, init(), lenI(), and HijJet1::HIJJET1::npj.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
int & HijJet1::ntj (int i) inline
Definition at line 157 of file HijJet1.h.
References _dummy, _hijjet1, init(), lenI(), and HijJet1::HIJJET1::ntj.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjpe (int i, int j) inline
Definition at line 137 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjpe.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjpm (int i, int j) inline
Definition at line 147 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjpm.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjpx (int i, int j) inline
Definition at line 107 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjpx.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjpy (int i, int j) inline
Definition at line 117 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjpy.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjpz (int i, int j) inline
Definition at line 127 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjpz.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjte (int i, int j) inline
Definition at line 205 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjte.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjtm (int i, int j) inline
Definition at line 215 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjtm.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjtx (int i, int j) inline
Definition at line 175 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjtx.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjty (int i, int j) inline
Definition at line 185 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjty.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
float & HijJet1::pjtz (int i, int j) inline
Definition at line 195 of file HijJet1.h.
References _hijjet1, _realdummy, init(), lenI(), lenJ(), and HijJet1::HIJJET1::pjtz.
Referenced by __example_1.f__(), __example_2.f__(), __example_8.f__(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hijsrt(), and quench().
Friends And Related Function Documentation
friend struct HIJJET1 friend
Definition at line 42 of file HijJet1.h.
Member Data Documentation
int HijJet1::_dummy private
Definition at line 63 of file HijJet1.h.
Referenced by kfpj(), kftj(), npj(), and ntj().
HijJet1::HIJJET1 * HijJet1::_hijjet1 =0 static private
Definition at line 66 of file HijJet1.h.
Referenced by init(), kfpj(), kftj(), npj(), ntj(), pjpe(), pjpm(), pjpx(), pjpy(), pjpz(), pjte(), pjtm(), pjtx(), pjty(), and pjtz().
const int HijJet1::_lenI = 300 static private
Definition at line 39 of file HijJet1.h.
Referenced by lenI().
const int HijJet1::_lenJ = 500 static private
Definition at line 40 of file HijJet1.h.
Referenced by lenJ().
float HijJet1::_realdummy private
Definition at line 64 of file HijJet1.h.
Referenced by pjpe(), pjpm(), pjpx(), pjpy(), pjpz(), pjte(), pjtm(), pjtx(), pjty(), and pjtz().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HijJet1.h