Analysis Software: TrackJetInput Class Reference
TrackJetInput Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/TrackJetInput.h>
Public Member Functions
TrackJetInput (Jet::SRC input)
virtual ~TrackJetInput ()
void identify (std::ostream &os=std::cout)
Jet::SRC get_src ()
std::vector< Jet * > get_input (PHCompositeNode *topNode)
Public Member Functions inherited from JetInput
virtual ~JetInput ()
Private Attributes
int _verbosity
Jet::SRC _input
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 13 of file TrackJetInput.h.
Constructor & Destructor Documentation
TrackJetInput::TrackJetInput (Jet::SRC input)
Definition at line 19 of file TrackJetInput.cc.
virtual TrackJetInput::~TrackJetInput () inline virtual
Definition at line 17 of file TrackJetInput.h.
Member Function Documentation
std::vector< Jet * > TrackJetInput::get_input (PHCompositeNode * topNode) virtual
Reimplemented from JetInput.
Definition at line 30 of file TrackJetInput.cc.
References _verbosity, SvtxTrackMap::begin(), SvtxTrackMap::end(), SvtxTrack::get_id(), SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), Jet::insert_comp(), Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), and Jet::TRACK.
Jet::SRC TrackJetInput::get_src () inline virtual
Reimplemented from JetInput.
Definition at line 21 of file TrackJetInput.h.
References _input.
void TrackJetInput::identify (std::ostream & os = std::cout) virtual
Reimplemented from JetInput.
Definition at line 25 of file TrackJetInput.cc.
Member Data Documentation
Jet::SRC TrackJetInput::_input private
Definition at line 27 of file TrackJetInput.h.
Referenced by get_src().
int TrackJetInput::_verbosity private
Definition at line 26 of file TrackJetInput.h.
Referenced by get_input().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/TrackJetInput.h
coresoftware/blob/master/simulation/g4simulation/g4jets/TrackJetInput.cc