Analysis Software: SvtxHit_v1 Class Reference
SvtxHit_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHit_v1.h>
Public Member Functions
SvtxHit_v1 ()
virtual ~SvtxHit_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
unsigned int get_layer () const
void set_layer (unsigned int layer)
unsigned int get_adc () const
void set_adc (unsigned int adc)
float get_e () const
void set_e (float e)
PHG4CellDefs::keytype get_cellid () const
void set_cellid (PHG4CellDefs::keytype cellid)
Public Member Functions inherited from SvtxHit
virtual ~SvtxHit ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (SvtxHit_v1, 2)
Private Attributes
unsigned int _id
unsigned int _layer
unsigned int _adc
float _e
PHG4CellDefs::keytype _cellid
Additional Inherited Members
Protected Member Functions inherited from SvtxHit
SvtxHit ()
Detailed Description
Definition at line 12 of file SvtxHit_v1.h.
Constructor & Destructor Documentation
SvtxHit_v1::SvtxHit_v1 ()
Definition at line 8 of file SvtxHit_v1.cc.
Referenced by CloneMe(), and Reset().
virtual SvtxHit_v1::~SvtxHit_v1 () inline virtual
Definition at line 16 of file SvtxHit_v1.h.
Member Function Documentation
SvtxHit_v1::ClassDef (SvtxHit_v1 , 2) private
PHObject* SvtxHit_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxHit.
Definition at line 23 of file SvtxHit_v1.h.
References SvtxHit_v1().
unsigned int SvtxHit_v1::get_adc () const inline virtual
Reimplemented from SvtxHit.
Definition at line 33 of file SvtxHit_v1.h.
References _adc.
Referenced by identify().
PHG4CellDefs::keytype SvtxHit_v1::get_cellid () const inline virtual
Reimplemented from SvtxHit.
Definition at line 39 of file SvtxHit_v1.h.
References _cellid.
Referenced by identify().
float SvtxHit_v1::get_e () const inline virtual
Reimplemented from SvtxHit.
Definition at line 36 of file SvtxHit_v1.h.
References _e.
Referenced by identify().
unsigned int SvtxHit_v1::get_id () const inline virtual
Reimplemented from SvtxHit.
Definition at line 27 of file SvtxHit_v1.h.
References _id.
Referenced by identify().
unsigned int SvtxHit_v1::get_layer () const inline virtual
Reimplemented from SvtxHit.
Definition at line 30 of file SvtxHit_v1.h.
References _layer.
Referenced by identify().
void SvtxHit_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxHit.
Definition at line 17 of file SvtxHit_v1.cc.
References get_adc(), get_cellid(), get_e(), get_id(), and get_layer().
int SvtxHit_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxHit.
Definition at line 28 of file SvtxHit_v1.cc.
References _adc, _cellid, _e, _id, and _layer.
void SvtxHit_v1::Reset () inline virtual
Clear Event.
Reimplemented from SvtxHit.
Definition at line 21 of file SvtxHit_v1.h.
References SvtxHit_v1().
void SvtxHit_v1::set_adc (unsigned int adc) inline virtual
Reimplemented from SvtxHit.
Definition at line 34 of file SvtxHit_v1.h.
References _adc.
void SvtxHit_v1::set_cellid (PHG4CellDefs::keytype cellid) inline virtual
Reimplemented from SvtxHit.
Definition at line 40 of file SvtxHit_v1.h.
References _cellid.
void SvtxHit_v1::set_e (float e) inline virtual
Reimplemented from SvtxHit.
Definition at line 37 of file SvtxHit_v1.h.
References _e.
void SvtxHit_v1::set_id (unsigned int id) inline virtual
Reimplemented from SvtxHit.
Definition at line 28 of file SvtxHit_v1.h.
References _id.
void SvtxHit_v1::set_layer (unsigned int layer) inline virtual
Reimplemented from SvtxHit.
Definition at line 31 of file SvtxHit_v1.h.
References _layer.
Member Data Documentation
unsigned int SvtxHit_v1::_adc private
Definition at line 45 of file SvtxHit_v1.h.
Referenced by get_adc(), isValid(), and set_adc().
PHG4CellDefs::keytype SvtxHit_v1::_cellid private
Definition at line 47 of file SvtxHit_v1.h.
Referenced by get_cellid(), isValid(), and set_cellid().
float SvtxHit_v1::_e private
Definition at line 46 of file SvtxHit_v1.h.
Referenced by get_e(), isValid(), and set_e().
unsigned int SvtxHit_v1::_id private
Definition at line 43 of file SvtxHit_v1.h.
Referenced by get_id(), isValid(), and set_id().
unsigned int SvtxHit_v1::_layer private
Definition at line 44 of file SvtxHit_v1.h.
Referenced by get_layer(), isValid(), and set_layer().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHit_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHit_v1.cc