Analysis Software: PHG4PSTOFDetector Class Reference
PHG4PSTOFDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4PSTOFDetector.h>
Public Member Functions
PHG4PSTOFDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParametersContainer *params_array, const std::string &dnam)
constructor
virtual ~PHG4PSTOFDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
virtual void Print (const std::string &what="ALL") const
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
volume accessors
int IsInPSTOF (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Protected Attributes
int IsActive
int IsAbsorberActive
int nmod
int nrows
PHParametersContainer * paramscontainer
std::map< G4VPhysicalVolume
*, int > active_phys_vols
std::string superdetector
Detailed Description
Definition at line 17 of file PHG4PSTOFDetector.h.
Constructor & Destructor Documentation
PHG4PSTOFDetector::PHG4PSTOFDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParametersContainer * params_array, const std::string & dnam)
constructor
Definition at line 27 of file PHG4PSTOFDetector.cc.
References PHParameters::get_int_param(), PHParametersContainer::GetParameters(), IsAbsorberActive, IsActive, nmod, nrows, and paramscontainer.
virtual PHG4PSTOFDetector::~PHG4PSTOFDetector () inline virtual
destructor
Definition at line 24 of file PHG4PSTOFDetector.h.
Member Function Documentation
void PHG4PSTOFDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 53 of file PHG4PSTOFDetector.cc.
References active_phys_vols, PHParameters::get_double_param(), PHParametersContainer::GetParameters(), IsActive, M_PI, nmod, nrows, PHG4Detector::OverlapCheck(), paramscontainer, phi, r, x, y, and z.
int PHG4PSTOFDetector::IsInPSTOF (G4VPhysicalVolume * volume) const
Definition at line 40 of file PHG4PSTOFDetector.cc.
References active_phys_vols.
Referenced by PHG4PSTOFSteppingAction::UserSteppingAction().
void PHG4PSTOFDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 110 of file PHG4PSTOFDetector.cc.
Referenced by PHG4PSTOFSubsystem::Print().
void PHG4PSTOFDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file PHG4PSTOFDetector.h.
References name, and superdetector.
Referenced by PHG4PSTOFSubsystem::InitRunSubsystem(), and PHG4PSTOFSteppingAction::SetInterfacePointers().
const std::string PHG4PSTOFDetector::SuperDetector () const inline
Definition at line 37 of file PHG4PSTOFDetector.h.
References superdetector.
Member Data Documentation
std::map<G4VPhysicalVolume *, int> PHG4PSTOFDetector::active_phys_vols protected
Definition at line 45 of file PHG4PSTOFDetector.h.
Referenced by ConstructMe(), and IsInPSTOF().
int PHG4PSTOFDetector::IsAbsorberActive protected
Definition at line 41 of file PHG4PSTOFDetector.h.
Referenced by PHG4PSTOFDetector().
int PHG4PSTOFDetector::IsActive protected
Definition at line 40 of file PHG4PSTOFDetector.h.
Referenced by ConstructMe(), and PHG4PSTOFDetector().
int PHG4PSTOFDetector::nmod protected
Definition at line 42 of file PHG4PSTOFDetector.h.
Referenced by ConstructMe(), and PHG4PSTOFDetector().
int PHG4PSTOFDetector::nrows protected
Definition at line 43 of file PHG4PSTOFDetector.h.
Referenced by ConstructMe(), and PHG4PSTOFDetector().
PHParametersContainer* PHG4PSTOFDetector::paramscontainer protected
Definition at line 44 of file PHG4PSTOFDetector.h.
Referenced by ConstructMe(), and PHG4PSTOFDetector().
std::string PHG4PSTOFDetector::superdetector protected
Definition at line 47 of file PHG4PSTOFDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4PSTOFDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4PSTOFDetector.cc