Analysis Software: TrkrClusterContainer Class Reference
TrkrClusterContainer Class Reference
Cluster container object.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainer.h>
Public Types
typedef std::map
< TrkrDefs::cluskey,
TrkrCluster * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
TrkrClusterContainer ()
virtual ~TrkrClusterContainer ()
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
ConstIterator addCluster (TrkrCluster *newClus)
ConstIterator addClusterSpecifyKey (const TrkrDefs::cluskey key, TrkrCluster *newClus)
void removeCluster (TrkrDefs::cluskey key)
preferred removal method, key is currently the clus id
void removeCluster (TrkrCluster *clus)
inefficent, use key where possible instead
Iterator findOrAddCluster (TrkrDefs::cluskey key)
ConstRange getClusters (const TrkrDefs::TrkrId trackerid) const
return all Clusters matching a given detid
ConstRange getClusters (const TrkrDefs::TrkrId trackerid, const char layer) const
return all Clusters matching a given detid and layer
ConstRange getClusters (void) const
return all clusters
TrkrCluster * findCluster (TrkrDefs::cluskey key)
unsigned int size (void) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map m_clusmap
Detailed Description
Cluster container object.
Container for TrkrCluster objects
Definition at line 25 of file TrkrClusterContainer.h.
Member Typedef Documentation
typedef Map::const_iterator TrkrClusterContainer::ConstIterator
Definition at line 30 of file TrkrClusterContainer.h.
typedef std::pair<ConstIterator, ConstIterator> TrkrClusterContainer::ConstRange
Definition at line 32 of file TrkrClusterContainer.h.
typedef Map::iterator TrkrClusterContainer::Iterator
Definition at line 29 of file TrkrClusterContainer.h.
typedef std::map<TrkrDefs::cluskey, TrkrCluster *> TrkrClusterContainer::Map
Definition at line 28 of file TrkrClusterContainer.h.
typedef std::pair<Iterator, Iterator> TrkrClusterContainer::Range
Definition at line 31 of file TrkrClusterContainer.h.
Constructor & Destructor Documentation
TrkrClusterContainer::TrkrClusterContainer () inline
Definition at line 34 of file TrkrClusterContainer.h.
virtual TrkrClusterContainer::~TrkrClusterContainer () inline virtual
Definition at line 36 of file TrkrClusterContainer.h.
Member Function Documentation
TrkrClusterContainer::ConstIterator TrkrClusterContainer::addCluster (TrkrCluster * newClus)
Definition at line 39 of file TrkrClusterContainer.cc.
References addClusterSpecifyKey(), and TrkrCluster::getClusKey().
TrkrClusterContainer::ConstIterator TrkrClusterContainer::addClusterSpecifyKey (const TrkrDefs::cluskey key, TrkrCluster * newClus)
Definition at line 45 of file TrkrClusterContainer.cc.
References m_clusmap.
Referenced by addCluster().
TrkrCluster * TrkrClusterContainer::findCluster (TrkrDefs::cluskey key)
Definition at line 110 of file TrkrClusterContainer.cc.
References it, and m_clusmap.
Referenced by PHGenFitTrkProp::check_track_exists(), Conversion::dist(), PHHoughSeeding::export_output(), SvtxEvaluator::fillOutputNtuples(), Conversion::firstLayer(), RecoConversionEval::hitCuts(), SVReco::MakeGenFitTrack(), TpcPrototypeGenFitTrkFitter::MakeTpcPrototypeTrack(), SvtxEvaluator::printOutputInfo(), PHTruthTrackSeeding::Process(), TpcPrototypeGenFitTrkFitter::process_event(), TruthConversionEval::processTrackBackground(), PHGenFitTrkFitter::ReFitTrack(), TpcPrototypeGenFitTrkFitter::ReFitTrack(), PHGenFitTrkProp::SvtxTrackToPHGenFitTracks(), Conversion::trackDLayer(), and PHGenFitTrkProp::TrackPropPatRec().
TrkrClusterContainer::Iterator TrkrClusterContainer::findOrAddCluster (TrkrDefs::cluskey key)
Definition at line 96 of file TrkrClusterContainer.cc.
References it, and m_clusmap.
Referenced by InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), TpcPrototypeUnpacker::exportDSTCluster(), TpcClusterizer::process_event(), and TpcPrototypeClusterizer::process_event().
TrkrClusterContainer::ConstRange TrkrClusterContainer::getClusters (const TrkrDefs::TrkrId trackerid) const
return all Clusters matching a given detid
Definition at line 60 of file TrkrClusterContainer.cc.
References TrkrDefs::getClusKeyHi(), TrkrDefs::getClusKeyLo(), and m_clusmap.
Referenced by SvtxClusterEval::all_clusters_from(), PHGenFitTrkProp::BuildLayerZPhiHitMap(), SvtxClusterEval::fill_cluster_layer_map(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxEvaluator::printInputInfo(), SvtxEvaluator::printOutputInfo(), PHTruthTrackSeeding::Process(), TpcPrototypeGenFitTrkFinder::process_event(), AnaMvtxTestBeam2019::process_event(), TpcPrototypeGenFitTrkFitter::process_event(), DumpTrkrClusterContainer::process_Node(), PHPatternReco::translate_input(), PHInitZVertexing::translate_input(), and PHHoughSeeding::translate_input().
TrkrClusterContainer::ConstRange TrkrClusterContainer::getClusters (const TrkrDefs::TrkrId trackerid, const char layer) const
return all Clusters matching a given detid and layer
Definition at line 78 of file TrkrClusterContainer.cc.
References TrkrDefs::getClusKeyHi(), TrkrDefs::getClusKeyLo(), and m_clusmap.
TrkrClusterContainer::ConstRange TrkrClusterContainer::getClusters (void) const
return all clusters
Definition at line 90 of file TrkrClusterContainer.cc.
References m_clusmap.
void TrkrClusterContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 23 of file TrkrClusterContainer.cc.
References TrkrDefs::getLayer(), m_clusmap, and size().
Referenced by MvtxClusterizer::PrintClusters(), InttClusterizer::PrintClusters(), TpcClusterizer::process_event(), and TpcPrototypeClusterizer::process_event().
void TrkrClusterContainer::removeCluster (TrkrDefs::cluskey key) inline
preferred removal method, key is currently the clus id
Definition at line 45 of file TrkrClusterContainer.h.
References m_clusmap.
void TrkrClusterContainer::removeCluster (TrkrCluster * clus) inline
inefficent, use key where possible instead
Definition at line 51 of file TrkrClusterContainer.h.
References m_clusmap.
void TrkrClusterContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 13 of file TrkrClusterContainer.cc.
References m_clusmap.
unsigned int TrkrClusterContainer::size (void) const inline
Definition at line 81 of file TrkrClusterContainer.h.
References m_clusmap.
Referenced by PHInitZVertexing::export_output(), PHPatternReco::export_output(), PHHoughSeeding::export_output(), SvtxEvaluator::fillOutputNtuples(), identify(), MvtxClusterizer::PrintClusters(), InttClusterizer::PrintClusters(), SvtxEvaluator::printInputInfo(), AnaMvtxPrototype1::process_event(), AnaMvtxTestBeam2019::process_event(), DumpTrkrClusterContainer::process_Node(), and PHInitZVertexing::translate_input().
Member Data Documentation
Map TrkrClusterContainer::m_clusmap protected
Definition at line 87 of file TrkrClusterContainer.h.
Referenced by addClusterSpecifyKey(), findCluster(), findOrAddCluster(), getClusters(), identify(), removeCluster(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainer.h
coresoftware/blob/master/offline/packages/trackbase/TrkrClusterContainer.cc