Analysis Software: RawCluster Class Reference
RawCluster Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawCluster.h>
Public Types
enum PROPERTY {
prop_ecore = 0, prop_prob = 1, prop_chi2 = 2, prop_et_iso_calotower_sub_R01 = 20,
prop_et_iso_calotower_R01 = 21, prop_et_iso_calotower_sub_R02 = 22, prop_et_iso_calotower_R02 = 23, prop_et_iso_calotower_sub_R03 = 24,
prop_et_iso_calotower_R03 = 25, prop_et_iso_calotower_sub_R04 = 26, prop_et_iso_calotower_R04 = 27, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< RawTowerDefs::keytype, float > TowerMap
typedef TowerMap::iterator TowerIterator
typedef TowerMap::const_iterator TowerConstIterator
typedef std::pair
< TowerIterator, TowerIterator > TowerRange
typedef std::pair
< TowerConstIterator,
TowerConstIterator > TowerConstRange
Public Member Functions
virtual ~RawCluster ()
virtual void Reset ()
Clear Event.
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
virtual RawClusterDefs::keytype get_id () const
cluster ID
virtual float get_energy () const
total energy
virtual size_t getNTowers () const
Tower operations.
virtual TowerConstRange get_towers () const
virtual const TowerMap & get_towermap () const
return tower map for c++11 range-based for-loop
virtual CLHEP::Hep3Vector get_position () const
virtual float get_phi () const
access to intrinsic cylindrical coordinate system
virtual float get_r () const
virtual float get_z () const
virtual float get_x () const
access Cartesian coordinate system
virtual float get_y () const
virtual float get_ecore () const
virtual float get_chi2 () const
reduced chi2 for EM shower
virtual float get_prob () const
cluster template probability for EM shower
virtual float get_et_iso () const
isolation ET default
virtual float get_et_iso (const int radiusx10, bool subtracted, bool clusterTower) const
isolation ET the radius and hueristic can be specified
virtual void set_id (const RawClusterDefs::keytype id)
cluster ID
virtual void addTower (const RawClusterDefs::keytype twrid, const float etower)
Tower operations.
virtual void set_energy (const float energy)
total energy
virtual void set_phi (const float phi)
access to intrinsic cylindrical coordinate system
virtual void set_z (const float z)
virtual void set_r (const float r)
virtual void set_ecore (const float ecore)
virtual void set_chi2 (const float chi2)
reduced chi2 for EM shower
virtual void set_prob (const float prob)
cluster template probability for EM shower
virtual void set_et_iso (const float e)
isolation ET
virtual void set_et_iso (const float e, const int radiusx10, bool subtracted, bool clusterTower)
virtual bool has_property (const PROPERTY prop_id) const
getters
virtual float get_property_float (const PROPERTY prop_id) const
virtual int get_property_int (const PROPERTY prop_id) const
virtual unsigned int get_property_uint (const PROPERTY prop_id) const
virtual void set_property (const PROPERTY prop_id, const float value)
setters
virtual void set_property (const PROPERTY prop_id, const int value)
virtual void set_property (const PROPERTY prop_id, const unsigned int value)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Static Public Member Functions
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
type management
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Protected Member Functions
RawCluster ()
Detailed Description
Definition at line 24 of file RawCluster.h.
Member Typedef Documentation
typedef TowerMap::const_iterator RawCluster::TowerConstIterator
Definition at line 29 of file RawCluster.h.
typedef std::pair<TowerConstIterator, TowerConstIterator> RawCluster::TowerConstRange
Definition at line 31 of file RawCluster.h.
typedef TowerMap::iterator RawCluster::TowerIterator
Definition at line 28 of file RawCluster.h.
typedef std::map<RawTowerDefs::keytype, float> RawCluster::TowerMap
Definition at line 27 of file RawCluster.h.
typedef std::pair<TowerIterator, TowerIterator> RawCluster::TowerRange
Definition at line 30 of file RawCluster.h.
Constructor & Destructor Documentation
virtual RawCluster::~RawCluster () inline virtual
Definition at line 33 of file RawCluster.h.
Member Function Documentation
virtual PHObject* RawCluster::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in RawClusterv1.
Definition at line 36 of file RawCluster.h.
Referenced by RawClusterPositionCorrection::process_event(), and TruthConversionEval::recordConversion().
virtual void RawCluster::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawClusterv1.
Definition at line 43 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
Referenced by RawClusterBuilderGraph::process_event(), RawClusterDeadAreaMask::process_event(), RawClusterBuilderFwd::process_event(), and ClusterIso::process_event().
virtual int RawCluster::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in RawClusterv1.
Definition at line 38 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
virtual void RawCluster::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in RawClusterv1.
Definition at line 34 of file RawCluster.h.
References PHOOL_VIRTUAL_WARNING.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawCluster.h
coresoftware/blob/master/offline/packages/CaloBase/RawCluster.cc