Analysis Software: macros/blob/master/macros/QA/calorimeter/QA_Draw_Jet_TruthMatching.C File Reference
QA_Draw_Jet_TruthMatching.C File Reference
#include <TFile.h>
#include <TGraphErrors.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include <vector>
#include "../../sPHENIXStyle/sPhenixStyle.C"
#include "QA_Draw_Utility.C"
Functions
vector< TGraphErrors * > QA_Draw_Jet_TruthMatching (const char *jet="h_QAG4SimJet_AntiKt_Truth_r07_AntiKt_Tower_r07", const char *qa_file_name_new="data/G4sPHENIXCells_250jets25GeV.root_qa.root", const char *qa_file_name_ref="data/G4sPHENIXCells_2000jets25GeV.root_qa.root")
Function Documentation
vector<TGraphErrors *> QA_Draw_Jet_TruthMatching (const char * jet = "h_QAG4SimJet_AntiKt_Truth_r07_AntiKt_Tower_r07", const char * qa_file_name_new = "data/G4sPHENIXCells_250jets25GeV.root_qa.root", const char * qa_file_name_ref = "data/G4sPHENIXCells_2000jets25GeV.root_qa.root")
drawing energy range
Definition at line 26 of file QA_Draw_Jet_TruthMatching.C.
References assert, DrawReference(), FitProfile(), GetBinominalRatio(), h2, SaveCanvas(), and SetsPhenixStyle().
Referenced by QA_Draw_Jet_Summary().