Analysis Software: DetermineTowerBackground Class Reference
DetermineTowerBackground Class Reference
UE background calculator.
#include <coresoftware/blob/master/offline/packages/jetbackground/DetermineTowerBackground.h>
Public Member Functions
DetermineTowerBackground (const std::string &name="DetermineTowerBackground")
virtual ~DetermineTowerBackground ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void SetBackgroundOutputName (const std::string &name)
void SetSeedType (int seed_type)
void SetFlow (int do_flow)
void SetSeedJetD (float D)
void SetSeedJetPt (float pt)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNode (PHCompositeNode *topNode)
void FillNode (PHCompositeNode *topNode)
Private Attributes
int _do_flow
float _v2
float _Psi2
std::vector< std::vector< float > > _UE
int _nStrips
int _nTowers
int _HCAL_NETA
int _HCAL_NPHI
std::vector< std::vector< float > > _EMCAL_E
std::vector< std::vector< float > > _IHCAL_E
std::vector< std::vector< float > > _OHCAL_E
std::vector< float > _FULLCALOFLOW_PHI_E
std::vector< float > _FULLCALOFLOW_PHI_VAL
std::string _backgroundName
int _seed_type
float _seed_jet_D
float _seed_jet_pt
std::vector< float > _seed_eta
std::vector< float > _seed_phi
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
UE background calculator.
This module constructs dE/deta vs. eta and v2 estimates given an (unsubtracted) set of calorimeter towers and possible a set of exclusion jets (seeds)
Definition at line 27 of file DetermineTowerBackground.h.
Constructor & Destructor Documentation
DetermineTowerBackground::DetermineTowerBackground (const std::string & name = "DetermineTowerBackground")
Definition at line 40 of file DetermineTowerBackground.cc.
References _UE.
virtual DetermineTowerBackground::~DetermineTowerBackground () inline virtual
Definition at line 31 of file DetermineTowerBackground.h.
Member Function Documentation
int DetermineTowerBackground::CreateNode (PHCompositeNode * topNode) private
Definition at line 627 of file DetermineTowerBackground.cc.
References _backgroundName, Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
void DetermineTowerBackground::FillNode (PHCompositeNode * topNode) private
Definition at line 664 of file DetermineTowerBackground.cc.
References _backgroundName, _nStrips, _nTowers, _Psi2, _UE, _v2, TowerBackground::set_nStripsUsedForFlow(), TowerBackground::set_nTowersUsedForBkg(), TowerBackground::set_Psi2(), TowerBackground::set_UE(), and TowerBackground::set_v2().
Referenced by process_event().
int DetermineTowerBackground::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 57 of file DetermineTowerBackground.cc.
References CreateNode().
int DetermineTowerBackground::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 62 of file DetermineTowerBackground.cc.
References _do_flow, _EMCAL_E, _FULLCALOFLOW_PHI_E, _FULLCALOFLOW_PHI_VAL, _HCAL_NETA, _HCAL_NPHI, _IHCAL_E, _nStrips, _nTowers, _OHCAL_E, _Psi2, _seed_eta, _seed_jet_D, _seed_jet_pt, _seed_phi, _seed_type, _UE, _v2, JetMap::begin(), Jet::begin_comp(), E, JetMap::end(), Jet::end_comp(), Fun4AllReturnCodes::EVENT_OK, FillNode(), PHG4Particle::get_e(), RawTower::get_energy(), Jet::get_eta(), RawTowerGeom::get_eta(), RawTowerGeomContainer::get_etabin(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_etabounds(), RawTowerGeomContainer::get_etacenter(), RawTower::get_key(), Jet::get_phi(), RawTowerGeom::get_phi(), RawTowerGeomContainer::get_phibin(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_phibounds(), RawTowerGeomContainer::get_phicenter(), PHG4Particle::get_pid(), Jet::get_pt(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), RawTowerGeomContainer::get_tower_geometry(), PHG4Particle::get_track_id(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), if(), PHG4TruthInfoContainer::isEmbeded(), phi, Jet::set_property(), RawTowerContainer::size(), t, total_E, and Fun4AllBase::Verbosity().
void DetermineTowerBackground::SetBackgroundOutputName (const std::string & name) inline
Definition at line 36 of file DetermineTowerBackground.h.
References _backgroundName, and name.
Referenced by HIJetReco().
void DetermineTowerBackground::SetFlow (int do_flow) inline
Definition at line 38 of file DetermineTowerBackground.h.
References _do_flow.
Referenced by HIJetReco().
void DetermineTowerBackground::SetSeedJetD (float D) inline
Definition at line 40 of file DetermineTowerBackground.h.
References _seed_jet_D.
Referenced by HIJetReco().
void DetermineTowerBackground::SetSeedJetPt (float pt) inline
Definition at line 41 of file DetermineTowerBackground.h.
References _seed_jet_pt.
Referenced by HIJetReco().
void DetermineTowerBackground::SetSeedType (int seed_type) inline
Definition at line 37 of file DetermineTowerBackground.h.
References _seed_type.
Referenced by HIJetReco().
Member Data Documentation
std::string DetermineTowerBackground::_backgroundName private
Definition at line 66 of file DetermineTowerBackground.h.
Referenced by CreateNode(), FillNode(), and SetBackgroundOutputName().
int DetermineTowerBackground::_do_flow private
Definition at line 47 of file DetermineTowerBackground.h.
Referenced by process_event(), and SetFlow().
std::vector<std::vector<float> > DetermineTowerBackground::_EMCAL_E private
Definition at line 57 of file DetermineTowerBackground.h.
Referenced by process_event().
std::vector<float> DetermineTowerBackground::_FULLCALOFLOW_PHI_E private
Definition at line 63 of file DetermineTowerBackground.h.
Referenced by process_event().
std::vector<float> DetermineTowerBackground::_FULLCALOFLOW_PHI_VAL private
Definition at line 64 of file DetermineTowerBackground.h.
Referenced by process_event().
int DetermineTowerBackground::_HCAL_NETA private
Definition at line 54 of file DetermineTowerBackground.h.
Referenced by process_event().
int DetermineTowerBackground::_HCAL_NPHI private
Definition at line 55 of file DetermineTowerBackground.h.
Referenced by process_event().
std::vector<std::vector<float> > DetermineTowerBackground::_IHCAL_E private
Definition at line 58 of file DetermineTowerBackground.h.
Referenced by process_event().
int DetermineTowerBackground::_nStrips private
Definition at line 51 of file DetermineTowerBackground.h.
Referenced by FillNode(), and process_event().
int DetermineTowerBackground::_nTowers private
Definition at line 52 of file DetermineTowerBackground.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<float> > DetermineTowerBackground::_OHCAL_E private
Definition at line 59 of file DetermineTowerBackground.h.
Referenced by process_event().
float DetermineTowerBackground::_Psi2 private
Definition at line 49 of file DetermineTowerBackground.h.
Referenced by FillNode(), and process_event().
std::vector<float> DetermineTowerBackground::_seed_eta private
Definition at line 72 of file DetermineTowerBackground.h.
Referenced by process_event().
float DetermineTowerBackground::_seed_jet_D private
Definition at line 69 of file DetermineTowerBackground.h.
Referenced by process_event(), and SetSeedJetD().
float DetermineTowerBackground::_seed_jet_pt private
Definition at line 70 of file DetermineTowerBackground.h.
Referenced by process_event(), and SetSeedJetPt().
std::vector<float> DetermineTowerBackground::_seed_phi private
Definition at line 73 of file DetermineTowerBackground.h.
Referenced by process_event().
int DetermineTowerBackground::_seed_type private
Definition at line 68 of file DetermineTowerBackground.h.
Referenced by process_event(), and SetSeedType().
std::vector<std::vector<float> > DetermineTowerBackground::_UE private
Definition at line 50 of file DetermineTowerBackground.h.
Referenced by DetermineTowerBackground(), FillNode(), and process_event().
float DetermineTowerBackground::_v2 private
Definition at line 48 of file DetermineTowerBackground.h.
Referenced by FillNode(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbackground/DetermineTowerBackground.h
coresoftware/blob/master/offline/packages/jetbackground/DetermineTowerBackground.cc