Analysis Software: online_distribution/blob/master/newbasic/formatIO.h File Reference
formatIO.h File Reference
#include <stdio.h>
#include "Cpacket.h"
#include "framePackets.h"
#include "phenixOnline.h"
#include "framePublic.h"
#include "packetPublic.h"
Functions
VALUE_ret dumpFrameHdr (FRAME_ptr)
VALUE_ret dumpFrame (FRAME_ptr)
VALUE_ret dumpFramePackets (FRAME_ptr)
VALUE_ret dumpPacket (PACKET_ptr)
Function Documentation
VALUE_ret dumpFrame (FRAME_ptr)
Definition at line 49 of file formatIO.C.
References dumpFrameHdr(), findFrameDataStart(), getFrameDataLength(), printf(), and valueFailure.
VALUE_ret dumpFrameHdr (FRAME_ptr)
Definition at line 130 of file formatIO.C.
References findFrameAlignBlock(), getFrameAlignLength(), getFrameDataType(), getFrameErrorLength(), getFrameHdrLength(), getFrameHdrVersion(), getFrameHistoryLength(), getFrameLength(), getFrameMark(), getFramePadding(), getFrameSourceId(), getFrameStatus(), getFrameType(), printf(), validFrameHdr(), and valueFailure.
Referenced by dumpFrame(), and dumpFramePackets().
VALUE_ret dumpFramePackets (FRAME_ptr)
Definition at line 89 of file formatIO.C.
References dumpFrameHdr(), dumpPacket(), findFirstFramePacket(), findNextFramePacket(), printf(), ptrFailure, and valueFailure.
VALUE_ret dumpPacket (PACKET_ptr)
Definition at line 183 of file formatIO.C.
References findPacketDataStart(), getPacketDebugLength(), getPacketEndianism(), getPacketErrorLength(), getPacketHdrLength(), getPacketHdrVersion(), getPacketId(), getPacketLength(), getPacketPadding(), getPacketStatus(), getPacketStructure(), getUnstructPacketDataLengthWords(), getUnstructPacketHitFormat(), getUnstructPacketWordSize(), printf(), Unstructured, validPacketHdr(), and valueFailure.
Referenced by dumpFramePackets().