Analysis Software: fixGDML Namespace Reference
fixGDML Namespace Reference
Variables
tuple root xml.etree.ElementTree.parse(sys.argv[1])
tuple posname pv.find('positionref')
tuple posinfo re.split(r'(\d+)in', posname.strip())
list pvname posinfo[0]
tuple element xml.etree.ElementTree.SubElement(lv, 'auxiliary')
tuple rough_string xml.etree.ElementTree.tostring(root, 'utf-8')
tuple reparsed_string minidom.parseString(rough_string)
string final_string '\n'
tuple fout open(sys.argv[2], 'w')
Variable Documentation
tuple fixGDML.element xml.etree.ElementTree.SubElement(lv, 'auxiliary')
Definition at line 27 of file fixGDML.py.
string fixGDML.final_string '\n'
Definition at line 36 of file fixGDML.py.
tuple fixGDML.fout open(sys.argv[2], 'w')
Definition at line 39 of file fixGDML.py.
Referenced by Prototype2_DSTReader.Begin(), calculate_g1_projection_per_bin(), DataAna(), DataAna2(), Draw_BDiJetImbalance(), draw_G4_bjet_truth_tagging(), draw_G4_dibjet_truth_tagging(), EdepPercentE(), EdepPercentIH(), EdepPercentOH(), EdepPercentSmall(), eic_sphenix_sidis_countbins(), fasthadv4(), FillEnergy(), hera_dis_countbins(), hera_dis_fillbins(), Hijing(), Interlopation0Degree(), InterlopationV4(), InterlopationV4reverse(), MakeFile(), Neutrals(), Prototype2_DSTReader.Process(), ProjectionReverse(), ProjectionReverse2(), ReadHis(), ReadHis2(), ReadHis3(), hcal.Save(), ShSizeHist(), ShSizePrep(), Prototype2_DSTReader.Terminate(), and ThreeGraphs().
tuple fixGDML.posinfo re.split(r'(\d+)in', posname.strip())
Definition at line 16 of file fixGDML.py.
tuple fixGDML.posname pv.find('positionref')
Definition at line 14 of file fixGDML.py.
list fixGDML.pvname posinfo[0]
Definition at line 17 of file fixGDML.py.
tuple fixGDML.reparsed_string minidom.parseString(rough_string)
Definition at line 33 of file fixGDML.py.
tuple fixGDML.root xml.etree.ElementTree.parse(sys.argv[1])
Definition at line 9 of file fixGDML.py.
tuple fixGDML.rough_string xml.etree.ElementTree.tostring(root, 'utf-8')
Definition at line 32 of file fixGDML.py.