Analysis Software: LaplaceSolution Class Reference
LaplaceSolution Class Reference
#include <analysis/blob/master/TPC/SCDCorrections/LaplaceSolution.h>
Public Member Functions
LaplaceSolution (std::string filename)
LaplaceSolution (double a=30, double b=80, double L=80)
virtual ~LaplaceSolution ()
void Verbosity (int v)
double Rmn (int m, int n, double r)
double Rmn1 (int m, int n, double r)
double Rmn2 (int m, int n, double r)
double RPrime (int m, int n, double a, double r)
double Rnk (int n, int k, double r)
double Ez (double r, double phi, double z, double r1, double phi1, double z1)
double Er (double r, double phi, double z, double r1, double phi1, double z1)
double Ephi (double r, double phi, double z, double r1, double phi1, double z1)
Protected Member Functions
void FindBetamn (double epsilon)
void FindMunk (double epsilon)
double ByFileER (double r, double phi, double z, double r1, double phi1, double z1)
double ByFileEZ (double r, double phi, double z, double r1, double phi1, double z1)
Protected Attributes
bool fByFile
double a
double b
double L
int verbosity
double pi
double Betamn [NumberOfOrders][NumberOfOrders]
double N2mn [NumberOfOrders][NumberOfOrders]
double Munk [NumberOfOrders][NumberOfOrders]
Detailed Description
Definition at line 23 of file LaplaceSolution.h.
Constructor & Destructor Documentation
LaplaceSolution::LaplaceSolution (std::string filename)
Definition at line 19 of file LaplaceSolution.cxx.
References file.
LaplaceSolution::LaplaceSolution (double a = 30, double b = 80, double L = 80)
Definition at line 24 of file LaplaceSolution.cxx.
References pi, return(), and verbosity.
virtual LaplaceSolution::~LaplaceSolution () inline virtual
Definition at line 28 of file LaplaceSolution.h.
Member Function Documentation
double LaplaceSolution::ByFileER (double r, double phi, double z, double r1, double phi1, double z1) protected
Definition at line 261 of file LaplaceSolution.cxx.
double LaplaceSolution::ByFileEZ (double r, double phi, double z, double r1, double phi1, double z1) protected
Definition at line 256 of file LaplaceSolution.cxx.
double LaplaceSolution::Ephi (double r, double phi, double z, double r1, double phi1, double z1)
Definition at line 378 of file LaplaceSolution.cxx.
References G, pi, and z1.
double LaplaceSolution::Er (double r, double phi, double z, double r1, double phi1, double z1)
Definition at line 322 of file LaplaceSolution.cxx.
References G, n, NumberOfOrders, pi, verbosity, and z1.
Referenced by FieldMapsLaplace::ComputeE().
double LaplaceSolution::Ez (double r, double phi, double z, double r1, double phi1, double z1)
Definition at line 266 of file LaplaceSolution.cxx.
References G, n, NumberOfOrders, pi, verbosity, and z1.
Referenced by FieldMapsLaplace::ComputeE().
void LaplaceSolution::FindBetamn (double epsilon) protected
Definition at line 47 of file LaplaceSolution.cxx.
References n, NumberOfOrders, pi, r, step, value, verbosity, x, and x0.
void LaplaceSolution::FindMunk (double epsilon) protected
Definition at line 104 of file LaplaceSolution.cxx.
double LaplaceSolution::Rmn (int m, int n, double r)
Definition at line 111 of file LaplaceSolution.cxx.
References NumberOfOrders, and verbosity.
double LaplaceSolution::Rmn1 (int m, int n, double r)
Definition at line 136 of file LaplaceSolution.cxx.
References NumberOfOrders, and pi.
double LaplaceSolution::Rmn2 (int m, int n, double r)
Definition at line 159 of file LaplaceSolution.cxx.
References NumberOfOrders, and pi.
double LaplaceSolution::Rnk (int n, int k, double r)
Definition at line 212 of file LaplaceSolution.cxx.
References A, dkia_(), dlia_(), k, n, NumberOfOrders, pi, r, and X.
double LaplaceSolution::RPrime (int m, int n, double a, double r)
Definition at line 182 of file LaplaceSolution.cxx.
References NumberOfOrders, and pi.
void LaplaceSolution::Verbosity (int v) inline
Definition at line 30 of file LaplaceSolution.h.
References v, and verbosity.
Member Data Documentation
double LaplaceSolution::a protected
Definition at line 44 of file LaplaceSolution.h.
double LaplaceSolution::b protected
Definition at line 44 of file LaplaceSolution.h.
double LaplaceSolution::Betamn[NumberOfOrders][NumberOfOrders] protected
Definition at line 51 of file LaplaceSolution.h.
bool LaplaceSolution::fByFile protected
Definition at line 43 of file LaplaceSolution.h.
double LaplaceSolution::L protected
Definition at line 44 of file LaplaceSolution.h.
double LaplaceSolution::Munk[NumberOfOrders][NumberOfOrders] protected
Definition at line 53 of file LaplaceSolution.h.
double LaplaceSolution::N2mn[NumberOfOrders][NumberOfOrders] protected
Definition at line 52 of file LaplaceSolution.h.
double LaplaceSolution::pi protected
Definition at line 46 of file LaplaceSolution.h.
int LaplaceSolution::verbosity protected
Definition at line 45 of file LaplaceSolution.h.
Referenced by Verbosity().
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/SCDCorrections/LaplaceSolution.h
analysis/blob/master/TPC/SCDCorrections/LaplaceSolution.cxx