Analysis Software: SvtxVertexEval Class Reference
SvtxVertexEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxVertexEval.h>
Public Member Functions
SvtxVertexEval (PHCompositeNode *topNode)
virtual ~SvtxVertexEval ()
void next_event (PHCompositeNode *topNode)
void do_caching (bool do_cache)
void set_strict (bool strict)
void set_verbosity (int verbosity)
SvtxTrackEval * get_track_eval ()
SvtxClusterEval * get_cluster_eval ()
SvtxHitEval * get_hit_eval ()
SvtxTruthEval * get_truth_eval ()
std::set< PHG4Particle * > all_truth_particles (SvtxVertex *vertex)
std::set< PHG4VtxPoint * > all_truth_points (SvtxVertex *vertex)
PHG4VtxPoint * max_truth_point_by_ntracks (SvtxVertex *vertex)
std::set< SvtxVertex * > all_vertexes_from (PHG4VtxPoint *truthpoint)
SvtxVertex * best_vertex_from (PHG4VtxPoint *truthpoint)
unsigned int get_ntracks_contribution (SvtxVertex *svtxvertex, PHG4VtxPoint *truthpoint)
unsigned int get_errors ()
void set_use_initial_vertex (bool use_init_vertex)
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
bool has_node_pointers ()
Private Attributes
SvtxTrackEval _trackeval
SvtxVertexMap * _vertexmap
SvtxTrackMap * _trackmap
PHG4TruthInfoContainer * _truthinfo
bool _strict
bool _use_initial_vertex
int _verbosity
unsigned int _errors
bool _do_cache
std::map< SvtxVertex
*, std::set< PHG4Particle * > > _cache_all_truth_particles
std::map< SvtxVertex
*, std::set< PHG4VtxPoint * > > _cache_all_truth_points
std::map< SvtxVertex
*, PHG4VtxPoint * > _cache_max_truth_point_by_ntracks
std::map< PHG4VtxPoint
*, std::set< SvtxVertex * > > _cache_all_vertexes_from_point
std::map< PHG4VtxPoint
*, SvtxVertex * > _cache_best_vertex_from_point
std::map< std::pair
< SvtxVertex *, PHG4VtxPoint * >
, unsigned int > _cache_get_ntracks_contribution
Detailed Description
Definition at line 23 of file SvtxVertexEval.h.
Constructor & Destructor Documentation
SvtxVertexEval::SvtxVertexEval (PHCompositeNode * topNode)
Definition at line 22 of file SvtxVertexEval.cc.
References get_node_pointers().
SvtxVertexEval::~SvtxVertexEval () virtual
Definition at line 42 of file SvtxVertexEval.cc.
References _errors, and _verbosity.
Member Function Documentation
std::set< PHG4Particle * > SvtxVertexEval::all_truth_particles (SvtxVertex * vertex)
Definition at line 67 of file SvtxVertexEval.cc.
References _cache_all_truth_particles, _do_cache, _errors, _strict, _trackeval, _trackmap, assert, SvtxVertex::begin_tracks(), SvtxVertex::end_tracks(), SvtxTrackMap::get(), has_node_pointers(), and SvtxTrackEval::max_truth_particle_by_nclusters().
Referenced by all_truth_points().
std::set< PHG4VtxPoint * > SvtxVertexEval::all_truth_points (SvtxVertex * vertex)
Definition at line 134 of file SvtxVertexEval.cc.
References _cache_all_truth_points, _do_cache, _errors, _strict, all_truth_particles(), assert, get_truth_eval(), SvtxTruthEval::get_vertex(), has_node_pointers(), and particles.
Referenced by all_vertexes_from(), and max_truth_point_by_ntracks().
std::set< SvtxVertex * > SvtxVertexEval::all_vertexes_from (PHG4VtxPoint * truthpoint)
Definition at line 241 of file SvtxVertexEval.cc.
References _cache_all_vertexes_from_point, _do_cache, _errors, _strict, _vertexmap, all_truth_points(), SvtxTruthEval::are_same_vertex(), assert, SvtxVertexMap::begin(), SvtxVertexMap::end(), get_truth_eval(), and has_node_pointers().
Referenced by best_vertex_from().
SvtxVertex * SvtxVertexEval::best_vertex_from (PHG4VtxPoint * truthpoint)
Definition at line 296 of file SvtxVertexEval.cc.
References _cache_best_vertex_from_point, _do_cache, _errors, _strict, all_vertexes_from(), assert, get_ntracks_contribution(), has_node_pointers(), and tracks().
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), and SvtxEvaluator::fillOutputNtuples().
void SvtxVertexEval::do_caching (bool do_cache) inline
Definition at line 30 of file SvtxVertexEval.h.
References _do_cache, _trackeval, and SvtxTrackEval::do_caching().
Referenced by SvtxEvalStack::do_caching().
SvtxClusterEval* SvtxVertexEval::get_cluster_eval () inline
Definition at line 48 of file SvtxVertexEval.h.
References _trackeval, and SvtxTrackEval::get_cluster_eval().
Referenced by SvtxEvalStack::get_cluster_eval().
unsigned int SvtxVertexEval::get_errors () inline
Definition at line 66 of file SvtxVertexEval.h.
References _errors, _trackeval, and SvtxTrackEval::get_errors().
Referenced by SvtxEvalStack::get_errors().
SvtxHitEval* SvtxVertexEval::get_hit_eval () inline
Definition at line 49 of file SvtxVertexEval.h.
References _trackeval, and SvtxTrackEval::get_hit_eval().
Referenced by SvtxEvalStack::get_hit_eval().
void SvtxVertexEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 407 of file SvtxVertexEval.cc.
References _trackmap, _truthinfo, _use_initial_vertex, and _vertexmap.
Referenced by next_event(), and SvtxVertexEval().
unsigned int SvtxVertexEval::get_ntracks_contribution (SvtxVertex * svtxvertex, PHG4VtxPoint * truthpoint)
Definition at line 346 of file SvtxVertexEval.cc.
References _cache_get_ntracks_contribution, _do_cache, _errors, _strict, _trackeval, _trackmap, assert, SvtxVertex::begin_tracks(), SvtxVertex::end_tracks(), SvtxTrackMap::get(), get_truth_eval(), SvtxTruthEval::get_vertex(), has_node_pointers(), and SvtxTrackEval::max_truth_particle_by_nclusters().
Referenced by best_vertex_from(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), and max_truth_point_by_ntracks().
SvtxTrackEval* SvtxVertexEval::get_track_eval () inline
Definition at line 47 of file SvtxVertexEval.h.
References _trackeval.
Referenced by SvtxEvalStack::get_track_eval().
SvtxTruthEval* SvtxVertexEval::get_truth_eval () inline
Definition at line 50 of file SvtxVertexEval.h.
References _trackeval, and SvtxTrackEval::get_truth_eval().
Referenced by all_truth_points(), all_vertexes_from(), get_ntracks_contribution(), and SvtxEvalStack::get_truth_eval().
bool SvtxVertexEval::has_node_pointers () private
Definition at line 427 of file SvtxVertexEval.cc.
References _strict, _trackmap, _truthinfo, _vertexmap, and assert.
Referenced by all_truth_particles(), all_truth_points(), all_vertexes_from(), best_vertex_from(), get_ntracks_contribution(), and max_truth_point_by_ntracks().
PHG4VtxPoint * SvtxVertexEval::max_truth_point_by_ntracks (SvtxVertex * vertex)
Definition at line 190 of file SvtxVertexEval.cc.
References _cache_max_truth_point_by_ntracks, _do_cache, _errors, _strict, all_truth_points(), assert, get_ntracks_contribution(), and has_node_pointers().
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxSimPerformanceCheckReco::process_event(), and SimpleTrackingAnalysis::process_event().
void SvtxVertexEval::next_event (PHCompositeNode * topNode)
Definition at line 53 of file SvtxVertexEval.cc.
References _cache_all_truth_particles, _cache_all_truth_points, _cache_all_vertexes_from_point, _cache_best_vertex_from_point, _cache_get_ntracks_contribution, _cache_max_truth_point_by_ntracks, _trackeval, get_node_pointers(), and SvtxTrackEval::next_event().
Referenced by SvtxEvalStack::next_event().
void SvtxVertexEval::set_strict (bool strict) inline
Definition at line 35 of file SvtxVertexEval.h.
References _strict, _trackeval, and SvtxTrackEval::set_strict().
Referenced by SvtxEvalStack::set_strict().
void SvtxVertexEval::set_use_initial_vertex (bool use_init_vertex) inline
Definition at line 68 of file SvtxVertexEval.h.
References _use_initial_vertex.
Referenced by SvtxEvalStack::set_use_initial_vertex().
void SvtxVertexEval::set_verbosity (int verbosity) inline
Definition at line 40 of file SvtxVertexEval.h.
References _trackeval, _verbosity, SvtxTrackEval::set_verbosity(), and verbosity.
Referenced by SvtxEvalStack::set_verbosity().
Member Data Documentation
std::map<SvtxVertex*, std::set<PHG4Particle*> > SvtxVertexEval::_cache_all_truth_particles private
Definition at line 85 of file SvtxVertexEval.h.
Referenced by all_truth_particles(), and next_event().
std::map<SvtxVertex*, std::set<PHG4VtxPoint*> > SvtxVertexEval::_cache_all_truth_points private
Definition at line 86 of file SvtxVertexEval.h.
Referenced by all_truth_points(), and next_event().
std::map<PHG4VtxPoint*, std::set<SvtxVertex*> > SvtxVertexEval::_cache_all_vertexes_from_point private
Definition at line 88 of file SvtxVertexEval.h.
Referenced by all_vertexes_from(), and next_event().
std::map<PHG4VtxPoint*, SvtxVertex*> SvtxVertexEval::_cache_best_vertex_from_point private
Definition at line 89 of file SvtxVertexEval.h.
Referenced by best_vertex_from(), and next_event().
std::map<std::pair<SvtxVertex*, PHG4VtxPoint*>, unsigned int> SvtxVertexEval::_cache_get_ntracks_contribution private
Definition at line 90 of file SvtxVertexEval.h.
Referenced by get_ntracks_contribution(), and next_event().
std::map<SvtxVertex*, PHG4VtxPoint*> SvtxVertexEval::_cache_max_truth_point_by_ntracks private
Definition at line 87 of file SvtxVertexEval.h.
Referenced by max_truth_point_by_ntracks(), and next_event().
bool SvtxVertexEval::_do_cache private
Definition at line 84 of file SvtxVertexEval.h.
Referenced by all_truth_particles(), all_truth_points(), all_vertexes_from(), best_vertex_from(), do_caching(), get_ntracks_contribution(), and max_truth_point_by_ntracks().
unsigned int SvtxVertexEval::_errors private
Definition at line 82 of file SvtxVertexEval.h.
Referenced by all_truth_particles(), all_truth_points(), all_vertexes_from(), best_vertex_from(), get_errors(), get_ntracks_contribution(), max_truth_point_by_ntracks(), and ~SvtxVertexEval().
bool SvtxVertexEval::_strict private
Definition at line 79 of file SvtxVertexEval.h.
Referenced by all_truth_particles(), all_truth_points(), all_vertexes_from(), best_vertex_from(), get_ntracks_contribution(), has_node_pointers(), max_truth_point_by_ntracks(), and set_strict().
SvtxTrackEval SvtxVertexEval::_trackeval private
Definition at line 74 of file SvtxVertexEval.h.
Referenced by all_truth_particles(), do_caching(), get_cluster_eval(), get_errors(), get_hit_eval(), get_ntracks_contribution(), get_track_eval(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
SvtxTrackMap* SvtxVertexEval::_trackmap private
Definition at line 76 of file SvtxVertexEval.h.
Referenced by all_truth_particles(), get_node_pointers(), get_ntracks_contribution(), and has_node_pointers().
PHG4TruthInfoContainer* SvtxVertexEval::_truthinfo private
Definition at line 77 of file SvtxVertexEval.h.
Referenced by get_node_pointers(), and has_node_pointers().
bool SvtxVertexEval::_use_initial_vertex private
Definition at line 80 of file SvtxVertexEval.h.
Referenced by get_node_pointers(), and set_use_initial_vertex().
int SvtxVertexEval::_verbosity private
Definition at line 81 of file SvtxVertexEval.h.
Referenced by set_verbosity(), and ~SvtxVertexEval().
SvtxVertexMap* SvtxVertexEval::_vertexmap private
Definition at line 75 of file SvtxVertexEval.h.
Referenced by all_vertexes_from(), get_node_pointers(), and has_node_pointers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxVertexEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/SvtxVertexEval.cc