Analysis Software: PHG4ConeSteppingAction Class Reference
PHG4ConeSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.h>
Public Member Functions
PHG4ConeSteppingAction (PHG4ConeDetector *)
constructor
virtual ~PHG4ConeSteppingAction ()
destructor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4ConeDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4Hit * hit
PHG4Shower * saveshower
Detailed Description
Definition at line 15 of file PHG4ConeSteppingAction.h.
Constructor & Destructor Documentation
PHG4ConeSteppingAction::PHG4ConeSteppingAction (PHG4ConeDetector * detector)
constructor
Definition at line 35 of file PHG4ConeSteppingAction.cc.
PHG4ConeSteppingAction::~PHG4ConeSteppingAction () virtual
destructor
Definition at line 43 of file PHG4ConeSteppingAction.cc.
References hit.
Member Function Documentation
void PHG4ConeSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 179 of file PHG4ConeSteppingAction.cc.
References detector_, PHG4Detector::GetName(), hits_, and PHG4ConeDetector::SuperDetector().
Referenced by PHG4ConeSubsystem::process_event().
bool PHG4ConeSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 53 of file PHG4ConeSteppingAction.cc.
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4ConeDetector::get_Layer(), PHG4HitContainer::GetID(), hit, hits_, PHG4ConeDetector::IsInConeActive(), PHG4Hit::Reset(), saveshower, PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4ConeDetector* PHG4ConeSteppingAction::detector_ private
pointer to the detector
Definition at line 36 of file PHG4ConeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4ConeSteppingAction::hit private
Definition at line 40 of file PHG4ConeSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4ConeSteppingAction().
PHG4HitContainer* PHG4ConeSteppingAction::hits_ private
pointer to hit container
Definition at line 39 of file PHG4ConeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Shower* PHG4ConeSteppingAction::saveshower private
Definition at line 41 of file PHG4ConeSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.cc