Analysis Software: FastPid_RICH Class Reference
FastPid_RICH Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/FastPid_RICH.h>
Public Member Functions
FastPid_RICH (std::string richname, std::string tracksname)
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
Private Attributes
bool _verbose
int _ievent
std::string _detector
std::string _trackmap_name
std::string _pidinfo_node_name
PidInfoContainer * _pidinfos
TrackProjectorPid * _trackproj
float _radius
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Class that allows to use a parametrized response of a RICH detector based on the information of the reconstructed incoming charged track for particle ID.
Definition at line 20 of file FastPid_RICH.h.
Constructor & Destructor Documentation
FastPid_RICH::FastPid_RICH (std::string richname, std::string tracksname)
Definition at line 28 of file FastPid_RICH.C.
References _detector, and _pidinfo_node_name.
Member Function Documentation
void FastPid_RICH::CreateNodes (PHCompositeNode * topNode) private
Definition at line 177 of file FastPid_RICH.C.
References _detector, _pidinfo_node_name, _pidinfos, PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int FastPid_RICH::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 172 of file FastPid_RICH.C.
int FastPid_RICH::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 42 of file FastPid_RICH.C.
References _ievent, and _verbose.
int FastPid_RICH::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 52 of file FastPid_RICH.C.
References _trackproj, CreateNodes(), and PHWHERE.
int FastPid_RICH::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 73 of file FastPid_RICH.C.
References _ievent, _pidinfos, _radius, _trackmap_name, _trackproj, Fun4AllReturnCodes::ABORTEVENT, PidInfoContainer::AddPidInfo(), PidInfo::CHARGEDKAON, PidInfo::CHARGEDPION, PidInfo::ELECTRON, SvtxTrackState::get_eta(), SvtxTrack::get_id(), PidInfo::get_likelihood(), SvtxTrackState::get_p(), PHG4Particle::get_pid(), SvtxTrackState::get_px(), SvtxTrackState::get_py(), SvtxTrackState::get_pz(), PidInfo::get_track_state(), SvtxTrack::get_truth_track_id(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), PHG4TruthInfoContainer::GetParticle(), PidInfoContainer::getPidInfo(), PHWHERE, pid, TrackProjectorPid::project_track(), PidInfo::PROTON, PidInfo::set_likelihood(), PidInfo::set_track_state(), and TrackProjectorPid::SPHERE.
Member Data Documentation
std::string FastPid_RICH::_detector private
Definition at line 45 of file FastPid_RICH.h.
Referenced by CreateNodes(), and FastPid_RICH().
int FastPid_RICH::_ievent private
Definition at line 42 of file FastPid_RICH.h.
Referenced by Init(), and process_event().
std::string FastPid_RICH::_pidinfo_node_name private
Definition at line 51 of file FastPid_RICH.h.
Referenced by CreateNodes(), and FastPid_RICH().
PidInfoContainer* FastPid_RICH::_pidinfos private
Definition at line 54 of file FastPid_RICH.h.
Referenced by CreateNodes(), and process_event().
float FastPid_RICH::_radius private
Definition at line 60 of file FastPid_RICH.h.
Referenced by process_event().
std::string FastPid_RICH::_trackmap_name private
Definition at line 48 of file FastPid_RICH.h.
Referenced by process_event().
TrackProjectorPid* FastPid_RICH::_trackproj private
Definition at line 57 of file FastPid_RICH.h.
Referenced by InitRun(), and process_event().
bool FastPid_RICH::_verbose private
Definition at line 40 of file FastPid_RICH.h.
Referenced by Init().
The documentation for this class was generated from the following files:
analysis/blob/master/ParticleID/RICHAnalysis/FastPid_RICH.h
analysis/blob/master/ParticleID/RICHAnalysis/FastPid_RICH.C