Analysis Software: analysis/blob/master/PhotonConversion/ana/minBiasRecoAna.C File Reference
minBiasRecoAna.C File Reference
#include <iostream>
#include "TFile.h"
#include "TTree.h"
#include "TChain.h"
#include "TLegend.h"
#include "math.h"
#include "TH1.h"
#include "TH2.h"
#include "TEfficiency.h"
Functions
TChain * handleFile (string name, string extension, string treename, unsigned int filecount)
int reportBackground (TChain *truthTree, TChain *recoTree, TFile *out_file)
void reportCuts (TChain *_treeBackground, int signal)
int analyzeSignal (TChain *_signalCutTree, TFile *outFile)
void minBiasRecoAna ()
Function Documentation
int analyzeSignal (TChain * _signalCutTree, TFile * outFile)
Definition at line 94 of file minBiasRecoAna.C.
References i.
Referenced by minBiasRecoAna().
TChain* handleFile (string name, string extension, string treename, unsigned int filecount)
Definition at line 13 of file minBiasRecoAna.C.
References i, and s.
void minBiasRecoAna ()
Definition at line 143 of file minBiasRecoAna.C.
References analyzeSignal(), filename, handleFile(), and reportCuts().
int reportBackground (TChain * truthTree, TChain * recoTree, TFile * out_file)
Definition at line 27 of file minBiasRecoAna.C.
References signal().
void reportCuts (TChain * _treeBackground, int signal)
Definition at line 54 of file minBiasRecoAna.C.
References i, and signal().
Referenced by minBiasRecoAna().