Analysis Software: prototype/blob/master/macros/tpc2019/DrawTpcPrototypeUnpacker.C File Reference
DrawTpcPrototypeUnpacker.C File Reference
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
#include <TChain.h>
#include <TCut.h>
#include <TEfficiency.h>
#include <TF1.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TH2.h>
#include <TH3.h>
#include <TPolyLine.h>
#include <TTree.h>
#include <TFile.h>
#include <TColor.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TLine.h>
#include <TStyle.h>
#include <TDirectory.h>
#include <TMath.h>
#include <TPad.h>
#include <TString.h>
#include <TVirtualFitter.h>
#include <cmath>
#include <iostream>
Macros
#define assert(exp)
Functions
TTree * eventT (nullptr)
TTree * chanT (nullptr)
void useLogBins (TAxis *axis)
utility function to
TGraphErrors * FitProfile (const TH2 *h2)
void Clusters3D ()
void ClusterQA ()
void DrawTpcPrototypeUnpacker (const TString infile="data/tpc_beam/tpc_beam_00000292-0000.evt_TpcPrototypeUnpacker.root", const TString desc="Run 292")
Variables
TFile * _file0 = NULL
TString description
Macro Definition Documentation
#define assert (exp)
Value:
{                                                                                             \
    if (!(exp))                                                                                 \
    {                                                                                           \
      cout << "Assert (" << #exp << ") failed at " << __FILE__ << " line " << __LINE__ << endl; \
      exit(1);                                                                                  \
    }                                                                                           \
  }
Definition at line 39 of file DrawTpcPrototypeUnpacker.C.
Function Documentation
TTree* chanT (nullptr)
void ClusterQA ()
Definition at line 177 of file DrawTpcPrototypeUnpacker.C.
References _file0, assert, description, eventT, leg, and SaveCanvas().
Referenced by DrawTpcPrototypeUnpacker().
void Clusters3D ()
Definition at line 138 of file DrawTpcPrototypeUnpacker.C.
References _file0, description, eventT, leg, and SaveCanvas().
Referenced by DrawTpcPrototypeUnpacker().
void DrawTpcPrototypeUnpacker (const TString infile = "data/tpc_beam/tpc_beam_00000292-0000.evt_TpcPrototypeUnpacker.root", const TString desc = "Run 292")
Definition at line 223 of file DrawTpcPrototypeUnpacker.C.
References _file0, assert, chanT, ClusterQA(), Clusters3D(), description, eventT, n, SetsPhenixStyle(), and t.
TTree* eventT (nullptr)
TGraphErrors* FitProfile (const TH2 * h2)
Definition at line 75 of file DrawTpcPrototypeUnpacker.C.
References f2(), h1, i, n, x, and y.
void useLogBins (TAxis * axis)
utility function to
Definition at line 54 of file DrawTpcPrototypeUnpacker.C.
References assert, bins, and i.
Variable Documentation
TFile* _file0 = NULL
Definition at line 48 of file DrawTpcPrototypeUnpacker.C.
TString description
Definition at line 49 of file DrawTpcPrototypeUnpacker.C.