Analysis Software: DumpCaloTriggerInfo Class Reference
DumpCaloTriggerInfo Class Reference
#include <coresoftware/blob/master/offline/packages/NodeDump/DumpCaloTriggerInfo.h>
Public Member Functions
DumpCaloTriggerInfo (const std::string &NodeName)
virtual ~DumpCaloTriggerInfo ()
Public Member Functions inherited from DumpObject
DumpObject (const std::string &NodeName="DUMMY")
virtual ~DumpObject ()
virtual int Init ()
virtual int process_event (PHNode *mynode)
virtual int CloseOutputFile ()
virtual const char * Name () const
virtual void Print (const char *what) const
virtual void SetOutDir (const std::string &outdir)
virtual void SetPrecision (const int digits)
void SetParentNodeDump (PHNodeDump *nd)
void NoOutput (const int i=1)
void WriteRunEvent (int i)
Protected Member Functions
int process_Node (PHNode *mynode)
Protected Member Functions inherited from DumpObject
virtual int OpenOutFile ()
Additional Inherited Members
Protected Attributes inherited from DumpObject
std::ostream * fout
Detailed Description
Definition at line 9 of file DumpCaloTriggerInfo.h.
Constructor & Destructor Documentation
DumpCaloTriggerInfo::DumpCaloTriggerInfo (const std::string & NodeName)
Definition at line 14 of file DumpCaloTriggerInfo.cc.
virtual DumpCaloTriggerInfo::~DumpCaloTriggerInfo () inline virtual
Definition at line 13 of file DumpCaloTriggerInfo.h.
Member Function Documentation
int DumpCaloTriggerInfo::process_Node (PHNode * mynode) protected virtual
Reimplemented from DumpObject.
Definition at line 20 of file DumpCaloTriggerInfo.cc.
References DumpObject::fout, CaloTriggerInfo::get_best2_EMCal_4x4_E(), CaloTriggerInfo::get_best2_EMCal_4x4_eta(), CaloTriggerInfo::get_best2_EMCal_4x4_phi(), CaloTriggerInfo::get_best_EMCal_2x2_E(), CaloTriggerInfo::get_best_EMCal_2x2_eta(), CaloTriggerInfo::get_best_EMCal_2x2_phi(), CaloTriggerInfo::get_best_EMCal_4x4_E(), CaloTriggerInfo::get_best_EMCal_4x4_eta(), CaloTriggerInfo::get_best_EMCal_4x4_phi(), CaloTriggerInfo::get_best_FullCalo_0p2x0p2_E(), CaloTriggerInfo::get_best_FullCalo_0p2x0p2_eta(), CaloTriggerInfo::get_best_FullCalo_0p2x0p2_phi(), CaloTriggerInfo::get_best_FullCalo_0p4x0p4_E(), CaloTriggerInfo::get_best_FullCalo_0p4x0p4_eta(), CaloTriggerInfo::get_best_FullCalo_0p4x0p4_phi(), CaloTriggerInfo::get_best_FullCalo_0p6x0p6_E(), CaloTriggerInfo::get_best_FullCalo_0p6x0p6_eta(), CaloTriggerInfo::get_best_FullCalo_0p6x0p6_phi(), CaloTriggerInfo::get_best_FullCalo_0p8x0p8_E(), CaloTriggerInfo::get_best_FullCalo_0p8x0p8_eta(), CaloTriggerInfo::get_best_FullCalo_0p8x0p8_phi(), CaloTriggerInfo::get_best_FullCalo_1p0x1p0_E(), CaloTriggerInfo::get_best_FullCalo_1p0x1p0_eta(), CaloTriggerInfo::get_best_FullCalo_1p0x1p0_phi(), and PHDataNode< T >::getData().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/NodeDump/DumpCaloTriggerInfo.h
coresoftware/blob/master/offline/packages/NodeDump/DumpCaloTriggerInfo.cc