Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/projections/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C File Reference
200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C File Reference
Functions
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_InvMass_DrawCrossSection Range (-4.430378,-3.530474, 210.7595, 4.400373)
Draw_HFJetTruth_InvMass_DrawCrossSection SetFillColor (0)
Draw_HFJetTruth_InvMass_DrawCrossSection SetBorderMode (0)
Draw_HFJetTruth_InvMass_DrawCrossSection SetBorderSize (2)
Draw_HFJetTruth_InvMass_DrawCrossSection SetLogy ()
Draw_HFJetTruth_InvMass_DrawCrossSection SetTickx (1)
Draw_HFJetTruth_InvMass_DrawCrossSection SetTicky (1)
Draw_HFJetTruth_InvMass_DrawCrossSection SetLeftMargin (0.16)
Draw_HFJetTruth_InvMass_DrawCrossSection SetRightMargin (0.05)
Draw_HFJetTruth_InvMass_DrawCrossSection SetTopMargin (0.05)
Draw_HFJetTruth_InvMass_DrawCrossSection SetBottomMargin (0.16)
Draw_HFJetTruth_InvMass_DrawCrossSection SetFrameBorderMode (0)
hall SetBinContent (22, 0.01869614)
hall SetBinContent (23, 1.121768)
hall SetBinContent (24, 11.1242)
hall SetBinContent (25, 69.2505)
hall SetBinContent (26, 595.416)
hall SetBinContent (27, 1976.78)
hall SetBinContent (28, 3422.964)
hall SetBinContent (29, 4480.624)
hall SetBinContent (30, 5081.256)
hall SetBinContent (31, 5314.565)
hall SetBinContent (32, 5186.421)
hall SetBinContent (33, 4816.649)
hall SetBinContent (34, 4319.818)
hall SetBinContent (35, 3801.075)
hall SetBinContent (36, 3291.605)
hall SetBinContent (37, 2828.614)
hall SetBinContent (38, 2444.165)
hall SetBinContent (39, 2083.872)
hall SetBinContent (40, 1788.809)
hall SetBinContent (41, 1545.329)
hall SetBinContent (42, 1327.202)
hall SetBinContent (43, 1134.463)
hall SetBinContent (44, 980.7247)
hall SetBinContent (45, 855.7784)
hall SetBinContent (46, 740.1615)
hall SetBinContent (47, 633.2944)
hall SetBinContent (48, 560.1738)
hall SetBinContent (49, 486.324)
hall SetBinContent (50, 426.3468)
hall SetBinContent (51, 372.5767)
hall SetBinContent (52, 321.6297)
hall SetBinContent (53, 283.3213)
hall SetBinContent (54, 247.7426)
hall SetBinContent (55, 220.147)
hall SetBinContent (56, 195.8795)
hall SetBinContent (57, 168.1718)
hall SetBinContent (58, 146.8956)
hall SetBinContent (59, 130.7982)
hall SetBinContent (60, 116.907)
hall SetBinContent (61, 103.2588)
hall SetBinContent (62, 90.00322)
hall SetBinContent (63, 80.35601)
hall SetBinContent (64, 69.96096)
hall SetBinContent (65, 61.5103)
hall SetBinContent (66, 54.03185)
hall SetBinContent (67, 47.69386)
hall SetBinContent (68, 42.02892)
hall SetBinContent (69, 39.20581)
hall SetBinContent (70, 34.19524)
hall SetBinContent (71, 30.23166)
hall SetBinContent (72, 27.20288)
hall SetBinContent (73, 25.78198)
hall SetBinContent (74, 21.93057)
hall SetBinContent (75, 20.30401)
hall SetBinContent (76, 18.02308)
hall SetBinContent (77, 14.91952)
hall SetBinContent (78, 12.54511)
hall SetBinContent (79, 12.20858)
hall SetBinContent (80, 11.47943)
hall SetBinContent (81, 9.796778)
hall SetBinContent (82, 8.544136)
hall SetBinContent (83, 7.160622)
hall SetBinContent (84, 5.964069)
hall SetBinContent (85, 6.076246)
hall SetBinContent (86, 4.898389)
hall SetBinContent (87, 4.954477)
hall SetBinContent (88, 4.094455)
hall SetBinContent (89, 3.907493)
hall SetBinContent (90, 3.234432)
hall SetBinContent (91, 2.841813)
hall SetBinContent (92, 2.542675)
hall SetBinContent (93, 2.393106)
hall SetBinContent (94, 2.112664)
hall SetBinContent (95, 1.64526)
hall SetBinContent (96, 1.290034)
hall SetBinContent (97, 1.570476)
hall SetBinContent (98, 1.103072)
hall SetBinContent (99, 1.046984)
hall SetBinContent (100, 1.009592)
hall SetBinContent (101, 0.8600225)
hall SetBinContent (102, 1.028288)
hall SetBinContent (103, 0.7665418)
hall SetBinContent (104, 0.6356688)
hall SetBinContent (105, 0.5982765)
hall SetBinContent (106, 0.5982765)
hall SetBinContent (107, 0.3552267)
hall SetBinContent (108, 0.392619)
hall SetBinContent (109, 0.5047958)
hall SetBinContent (110, 0.1869614)
hall SetBinContent (111, 0.2056575)
hall SetBinContent (112, 0.2243537)
hall SetBinContent (113, 0.2430498)
hall SetBinContent (114, 0.1495691)
hall SetBinContent (115, 0.130873)
hall SetBinContent (116, 0.2056575)
hall SetBinContent (117, 0.07478456)
hall SetBinContent (118, 0.1682653)
hall SetBinContent (119, 0.07478456)
hall SetBinContent (120, 0.01869614)
hall SetBinContent (121, 0.05608842)
hall SetBinContent (122, 0.05608842)
hall SetBinContent (123, 0.09348071)
hall SetBinContent (126, 0.05608842)
hall SetBinContent (128, 0.03739228)
hall SetBinContent (129, 0.01869614)
hall SetBinContent (130, 0.01869614)
hall SetBinContent (131, 0.03739228)
hall SetBinContent (134, 0.01869614)
hall SetBinContent (140, 0.01869614)
hall SetBinContent (145, 0.01869614)
hall SetBinError (22, 0.01869614)
hall SetBinError (23, 0.1448197)
hall SetBinError (24, 0.4560479)
hall SetBinError (25, 1.137856)
hall SetBinError (26, 3.336462)
hall SetBinError (27, 6.079323)
hall SetBinError (28, 7.999764)
hall SetBinError (29, 9.152615)
hall SetBinError (30, 9.746788)
hall SetBinError (31, 9.968042)
hall SetBinError (32, 9.847135)
hall SetBinError (33, 9.489613)
hall SetBinError (34, 8.986875)
hall SetBinError (35, 8.430032)
hall SetBinError (36, 7.844763)
hall SetBinError (37, 7.27215)
hall SetBinError (38, 6.759915)
hall SetBinError (39, 6.241824)
hall SetBinError (40, 5.783064)
hall SetBinError (41, 5.3751)
hall SetBinError (42, 4.98132)
hall SetBinError (43, 4.60544)
hall SetBinError (44, 4.282028)
hall SetBinError (45, 3.999969)
hall SetBinError (46, 3.719968)
hall SetBinError (47, 3.440953)
hall SetBinError (48, 3.236215)
hall SetBinError (49, 3.015358)
hall SetBinError (50, 2.823303)
hall SetBinError (51, 2.63927)
hall SetBinError (52, 2.45219)
hall SetBinError (53, 2.301525)
hall SetBinError (54, 2.152169)
hall SetBinError (55, 2.028768)
hall SetBinError (56, 1.913685)
hall SetBinError (57, 1.773179)
hall SetBinError (58, 1.657221)
hall SetBinError (59, 1.563784)
hall SetBinError (60, 1.478414)
hall SetBinError (61, 1.389439)
hall SetBinError (62, 1.297194)
hall SetBinError (63, 1.225703)
hall SetBinError (64, 1.143678)
hall SetBinError (65, 1.072383)
hall SetBinError (66, 1.005081)
hall SetBinError (67, 0.9442939)
hall SetBinError (68, 0.8864416)
hall SetBinError (69, 0.8561526)
hall SetBinError (70, 0.7995743)
hall SetBinError (71, 0.7518081)
hall SetBinError (72, 0.7131542)
hall SetBinError (73, 0.6942791)
hall SetBinError (74, 0.6403258)
hall SetBinError (75, 0.6161222)
hall SetBinError (76, 0.5804843)
hall SetBinError (77, 0.5281453)
hall SetBinError (78, 0.4842986)
hall SetBinError (79, 0.4777586)
hall SetBinError (80, 0.4632721)
hall SetBinError (81, 0.4279742)
hall SetBinError (82, 0.3996778)
hall SetBinError (83, 0.3658907)
hall SetBinError (84, 0.3339237)
hall SetBinError (85, 0.3370495)
hall SetBinError (86, 0.3026235)
hall SetBinError (87, 0.3043511)
hall SetBinError (88, 0.2766776)
hall SetBinError (89, 0.270287)
hall SetBinError (90, 0.2459093)
hall SetBinError (91, 0.2305015)
hall SetBinError (92, 0.2180326)
hall SetBinError (93, 0.2115227)
hall SetBinError (94, 0.1987427)
hall SetBinError (95, 0.1753853)
hall SetBinError (96, 0.1553018)
hall SetBinError (97, 0.171353)
hall SetBinError (98, 0.1436078)
hall SetBinError (99, 0.1399091)
hall SetBinError (100, 0.137388)
hall SetBinError (101, 0.1268034)
hall SetBinError (102, 0.1386543)
hall SetBinError (103, 0.1197137)
hall SetBinError (104, 0.1090163)
hall SetBinError (105, 0.1057613)
hall SetBinError (106, 0.1057613)
hall SetBinError (107, 0.08149459)
hall SetBinError (108, 0.08567648)
hall SetBinError (109, 0.097148)
hall SetBinError (110, 0.05912239)
hall SetBinError (111, 0.06200808)
hall SetBinError (112, 0.06476533)
hall SetBinError (113, 0.06740989)
hall SetBinError (114, 0.05288067)
hall SetBinError (115, 0.04946534)
hall SetBinError (116, 0.06200808)
hall SetBinError (117, 0.03739228)
hall SetBinError (118, 0.05608842)
hall SetBinError (119, 0.03739228)
hall SetBinError (120, 0.01869614)
hall SetBinError (121, 0.03238267)
hall SetBinError (122, 0.03238267)
hall SetBinError (123, 0.04180584)
hall SetBinError (126, 0.03238267)
hall SetBinError (128, 0.02644034)
hall SetBinError (129, 0.01869614)
hall SetBinError (130, 0.01869614)
hall SetBinError (131, 0.02644034)
hall SetBinError (134, 0.01869614)
hall SetBinError (140, 0.01869614)
hall SetBinError (145, 0.01869614)
hall SetEntries (3386403)
hall SetLineWidth (2)
hall SetMarkerStyle (20)
hall SetMarkerSize (1.2)
hall GetXaxis () -> SetTitle("m_
hall GetYaxis () -> SetTitle("d^
hall GetZaxis () -> SetLabelFont(42)
hall Draw ("")
h_b SetBinContent (25, 0.1121768)
h_b SetBinContent (26, 0.8787186)
h_b SetBinContent (27, 2.636156)
h_b SetBinContent (28, 5.010566)
h_b SetBinContent (29, 6.506257)
h_b SetBinContent (30, 6.88018)
h_b SetBinContent (31, 7.441064)
h_b SetBinContent (32, 7.21671)
h_b SetBinContent (33, 6.936268)
h_b SetBinContent (34, 6.337992)
h_b SetBinContent (35, 5.421881)
h_b SetBinContent (36, 5.029262)
h_b SetBinContent (37, 4.300112)
h_b SetBinContent (38, 3.645747)
h_b SetBinContent (39, 3.271825)
h_b SetBinContent (40, 3.103559)
h_b SetBinContent (41, 2.505283)
h_b SetBinContent (42, 2.206145)
h_b SetBinContent (43, 2.075272)
h_b SetBinContent (44, 1.626564)
h_b SetBinContent (45, 1.233945)
h_b SetBinContent (46, 1.177857)
h_b SetBinContent (47, 0.8600225)
h_b SetBinContent (48, 0.9161109)
h_b SetBinContent (49, 0.803934)
h_b SetBinContent (50, 0.6356688)
h_b SetBinContent (51, 0.5795804)
h_b SetBinContent (52, 0.4674035)
h_b SetBinContent (53, 0.392619)
h_b SetBinContent (54, 0.4487074)
h_b SetBinContent (55, 0.2804421)
h_b SetBinContent (56, 0.3552267)
h_b SetBinContent (57, 0.2804421)
h_b SetBinContent (58, 0.2056575)
h_b SetBinContent (59, 0.1869614)
h_b SetBinContent (60, 0.1682653)
h_b SetBinContent (61, 0.130873)
h_b SetBinContent (62, 0.05608842)
h_b SetBinContent (63, 0.1121768)
h_b SetBinContent (64, 0.1869614)
h_b SetBinContent (65, 0.09348071)
h_b SetBinContent (66, 0.1121768)
h_b SetBinContent (67, 0.01869614)
h_b SetBinContent (68, 0.03739228)
h_b SetBinContent (69, 0.03739228)
h_b SetBinContent (70, 0.09348071)
h_b SetBinContent (72, 0.03739228)
h_b SetBinContent (75, 0.01869614)
h_b SetBinContent (77, 0.01869614)
h_b SetBinContent (78, 0.01869614)
h_b SetBinContent (80, 0.01869614)
h_b SetBinContent (82, 0.01869614)
h_b SetBinContent (87, 0.03739228)
h_b SetBinContent (96, 0.01869614)
h_b SetBinError (25, 0.045796)
h_b SetBinError (26, 0.1281743)
h_b SetBinError (27, 0.2220044)
h_b SetBinError (28, 0.306069)
h_b SetBinError (29, 0.348772)
h_b SetBinError (30, 0.3586542)
h_b SetBinError (31, 0.3729868)
h_b SetBinError (32, 0.3673209)
h_b SetBinError (33, 0.3601131)
h_b SetBinError (34, 0.3442325)
h_b SetBinError (35, 0.3183838)
h_b SetBinError (36, 0.3066395)
h_b SetBinError (37, 0.283541)
h_b SetBinError (38, 0.2610774)
h_b SetBinError (39, 0.2473267)
h_b SetBinError (40, 0.2408829)
h_b SetBinError (41, 0.2164235)
h_b SetBinError (42, 0.2030921)
h_b SetBinError (43, 0.1969761)
h_b SetBinError (44, 0.174386)
h_b SetBinError (45, 0.1518882)
h_b SetBinError (46, 0.148396)
h_b SetBinError (47, 0.1268034)
h_b SetBinError (48, 0.130873)
h_b SetBinError (49, 0.1225988)
h_b SetBinError (50, 0.1090163)
h_b SetBinError (51, 0.1040957)
h_b SetBinError (52, 0.0934807)
h_b SetBinError (53, 0.08567648)
h_b SetBinError (54, 0.09159201)
h_b SetBinError (55, 0.07240984)
h_b SetBinError (56, 0.08149459)
h_b SetBinError (57, 0.07240984)
h_b SetBinError (58, 0.06200808)
h_b SetBinError (59, 0.05912239)
h_b SetBinError (60, 0.05608842)
h_b SetBinError (61, 0.04946534)
h_b SetBinError (62, 0.03238267)
h_b SetBinError (63, 0.045796)
h_b SetBinError (64, 0.05912239)
h_b SetBinError (65, 0.04180584)
h_b SetBinError (66, 0.045796)
h_b SetEntries (5185)
h_b SetLineColor (ci)
h_b SetMarkerColor (ci)
h_b Draw ("same")
leg SetBorderSize (0)
leg SetLineColor (1)
leg SetLineStyle (1)
leg SetLineWidth (1)
leg SetFillStyle (1001)
entry SetMarkerColor (1)
entry SetMarkerStyle (21)
entry SetMarkerSize (1)
entry SetTextFont (42)
leg Draw ()
Draw_HFJetTruth_InvMass_DrawCrossSection Modified ()
Draw_HFJetTruth_InvMass_DrawCrossSection cd ()
Draw_HFJetTruth_InvMass_DrawCrossSection SetSelected (Draw_HFJetTruth_InvMass_DrawCrossSection)
Variables
TH1F * hall = new TH1F("hall","",200,0,200)
TH1F * h_b = new TH1F("h_b","",200,0,200)
Int_t ci = TColor::GetColor("#0000ff")
TColor * color
TLegend * leg = new TLegend(0.45,0.6,0.99,0.95,NULL,"brNDC")
TLegendEntry * entry =leg->AddEntry("NULL","#splitline{#it{#bf{sPHENIX}} fast simulation, p+p #sqrt{s} = 200 GeV}{|#eta_{1,2}|<0.6, |#Delta#phi_{1,2}|>2#pi/3, p_{T,1}>15 GeV/c, p_{T,2}>10 GeV/c}","h")
Function Documentation
Draw_HFJetTruth_InvMass_DrawCrossSection cd ()
hall Draw ("")
h_b Draw ("same")
leg Draw ()
hall GetXaxis () -> SetTitle("m_
Definition at line 247 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
hall GetYaxis () -> SetTitle("d^
Definition at line 254 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
hall GetZaxis () -> SetLabelFont(42)
Draw_HFJetTruth_InvMass_DrawCrossSection Modified ()
Draw_HFJetTruth_InvMass_DrawCrossSection Range (-4. 430378, -3. 530474, 210. 7595, 4. 400373)
hall SetBinContent (22 , 0. 01869614)
hall SetBinContent (23 , 1. 121768)
hall SetBinContent (24 , 11. 1242)
hall SetBinContent (25 , 69. 2505)
hall SetBinContent (26 , 595. 416)
hall SetBinContent (27 , 1976. 78)
hall SetBinContent (28 , 3422. 964)
hall SetBinContent (29 , 4480. 624)
hall SetBinContent (30 , 5081. 256)
hall SetBinContent (31 , 5314. 565)
hall SetBinContent (32 , 5186. 421)
hall SetBinContent (33 , 4816. 649)
hall SetBinContent (34 , 4319. 818)
hall SetBinContent (35 , 3801. 075)
hall SetBinContent (36 , 3291. 605)
hall SetBinContent (37 , 2828. 614)
hall SetBinContent (38 , 2444. 165)
hall SetBinContent (39 , 2083. 872)
hall SetBinContent (40 , 1788. 809)
hall SetBinContent (41 , 1545. 329)
hall SetBinContent (42 , 1327. 202)
hall SetBinContent (43 , 1134. 463)
hall SetBinContent (44 , 980. 7247)
hall SetBinContent (45 , 855. 7784)
hall SetBinContent (46 , 740. 1615)
hall SetBinContent (47 , 633. 2944)
hall SetBinContent (48 , 560. 1738)
hall SetBinContent (49 , 486. 324)
hall SetBinContent (50 , 426. 3468)
hall SetBinContent (51 , 372. 5767)
hall SetBinContent (52 , 321. 6297)
hall SetBinContent (53 , 283. 3213)
hall SetBinContent (54 , 247. 7426)
hall SetBinContent (55 , 220. 147)
hall SetBinContent (56 , 195. 8795)
hall SetBinContent (57 , 168. 1718)
hall SetBinContent (58 , 146. 8956)
hall SetBinContent (59 , 130. 7982)
hall SetBinContent (60 , 116. 907)
hall SetBinContent (61 , 103. 2588)
hall SetBinContent (62 , 90. 00322)
hall SetBinContent (63 , 80. 35601)
hall SetBinContent (64 , 69. 96096)
hall SetBinContent (65 , 61. 5103)
hall SetBinContent (66 , 54. 03185)
hall SetBinContent (67 , 47. 69386)
hall SetBinContent (68 , 42. 02892)
hall SetBinContent (69 , 39. 20581)
hall SetBinContent (70 , 34. 19524)
hall SetBinContent (71 , 30. 23166)
hall SetBinContent (72 , 27. 20288)
hall SetBinContent (73 , 25. 78198)
hall SetBinContent (74 , 21. 93057)
hall SetBinContent (75 , 20. 30401)
hall SetBinContent (76 , 18. 02308)
hall SetBinContent (77 , 14. 91952)
hall SetBinContent (78 , 12. 54511)
hall SetBinContent (79 , 12. 20858)
hall SetBinContent (80 , 11. 47943)
hall SetBinContent (81 , 9. 796778)
hall SetBinContent (82 , 8. 544136)
hall SetBinContent (83 , 7. 160622)
hall SetBinContent (84 , 5. 964069)
hall SetBinContent (85 , 6. 076246)
hall SetBinContent (86 , 4. 898389)
hall SetBinContent (87 , 4. 954477)
hall SetBinContent (88 , 4. 094455)
hall SetBinContent (89 , 3. 907493)
hall SetBinContent (90 , 3. 234432)
hall SetBinContent (91 , 2. 841813)
hall SetBinContent (92 , 2. 542675)
hall SetBinContent (93 , 2. 393106)
hall SetBinContent (94 , 2. 112664)
hall SetBinContent (95 , 1. 64526)
hall SetBinContent (96 , 1. 290034)
hall SetBinContent (97 , 1. 570476)
hall SetBinContent (98 , 1. 103072)
hall SetBinContent (99 , 1. 046984)
hall SetBinContent (100 , 1. 009592)
hall SetBinContent (101 , 0. 8600225)
hall SetBinContent (102 , 1. 028288)
hall SetBinContent (103 , 0. 7665418)
hall SetBinContent (104 , 0. 6356688)
hall SetBinContent (105 , 0. 5982765)
hall SetBinContent (106 , 0. 5982765)
hall SetBinContent (107 , 0. 3552267)
hall SetBinContent (108 , 0. 392619)
hall SetBinContent (109 , 0. 5047958)
hall SetBinContent (110 , 0. 1869614)
hall SetBinContent (111 , 0. 2056575)
hall SetBinContent (112 , 0. 2243537)
hall SetBinContent (113 , 0. 2430498)
hall SetBinContent (114 , 0. 1495691)
hall SetBinContent (115 , 0. 130873)
hall SetBinContent (116 , 0. 2056575)
hall SetBinContent (117 , 0. 07478456)
hall SetBinContent (118 , 0. 1682653)
hall SetBinContent (119 , 0. 07478456)
hall SetBinContent (120 , 0. 01869614)
hall SetBinContent (121 , 0. 05608842)
hall SetBinContent (122 , 0. 05608842)
hall SetBinContent (123 , 0. 09348071)
hall SetBinContent (126 , 0. 05608842)
hall SetBinContent (128 , 0. 03739228)
hall SetBinContent (129 , 0. 01869614)
hall SetBinContent (130 , 0. 01869614)
hall SetBinContent (131 , 0. 03739228)
hall SetBinContent (134 , 0. 01869614)
hall SetBinContent (140 , 0. 01869614)
hall SetBinContent (145 , 0. 01869614)
h_b SetBinContent (25 , 0. 1121768)
h_b SetBinContent (26 , 0. 8787186)
h_b SetBinContent (27 , 2. 636156)
h_b SetBinContent (28 , 5. 010566)
h_b SetBinContent (29 , 6. 506257)
h_b SetBinContent (30 , 6. 88018)
h_b SetBinContent (31 , 7. 441064)
h_b SetBinContent (32 , 7. 21671)
h_b SetBinContent (33 , 6. 936268)
h_b SetBinContent (34 , 6. 337992)
h_b SetBinContent (35 , 5. 421881)
h_b SetBinContent (36 , 5. 029262)
h_b SetBinContent (37 , 4. 300112)
h_b SetBinContent (38 , 3. 645747)
h_b SetBinContent (39 , 3. 271825)
h_b SetBinContent (40 , 3. 103559)
h_b SetBinContent (41 , 2. 505283)
h_b SetBinContent (42 , 2. 206145)
h_b SetBinContent (43 , 2. 075272)
h_b SetBinContent (44 , 1. 626564)
h_b SetBinContent (45 , 1. 233945)
h_b SetBinContent (46 , 1. 177857)
h_b SetBinContent (47 , 0. 8600225)
h_b SetBinContent (48 , 0. 9161109)
h_b SetBinContent (49 , 0. 803934)
h_b SetBinContent (50 , 0. 6356688)
h_b SetBinContent (51 , 0. 5795804)
h_b SetBinContent (52 , 0. 4674035)
h_b SetBinContent (53 , 0. 392619)
h_b SetBinContent (54 , 0. 4487074)
h_b SetBinContent (55 , 0. 2804421)
h_b SetBinContent (56 , 0. 3552267)
h_b SetBinContent (57 , 0. 2804421)
h_b SetBinContent (58 , 0. 2056575)
h_b SetBinContent (59 , 0. 1869614)
h_b SetBinContent (60 , 0. 1682653)
h_b SetBinContent (61 , 0. 130873)
h_b SetBinContent (62 , 0. 05608842)
h_b SetBinContent (63 , 0. 1121768)
h_b SetBinContent (64 , 0. 1869614)
h_b SetBinContent (65 , 0. 09348071)
h_b SetBinContent (66 , 0. 1121768)
h_b SetBinContent (67 , 0. 01869614)
h_b SetBinContent (68 , 0. 03739228)
h_b SetBinContent (69 , 0. 03739228)
h_b SetBinContent (70 , 0. 09348071)
h_b SetBinContent (72 , 0. 03739228)
h_b SetBinContent (75 , 0. 01869614)
h_b SetBinContent (77 , 0. 01869614)
h_b SetBinContent (78 , 0. 01869614)
h_b SetBinContent (80 , 0. 01869614)
h_b SetBinContent (82 , 0. 01869614)
h_b SetBinContent (87 , 0. 03739228)
h_b SetBinContent (96 , 0. 01869614)
hall SetBinError (22 , 0. 01869614)
hall SetBinError (23 , 0. 1448197)
hall SetBinError (24 , 0. 4560479)
hall SetBinError (25 , 1. 137856)
hall SetBinError (26 , 3. 336462)
hall SetBinError (27 , 6. 079323)
hall SetBinError (28 , 7. 999764)
hall SetBinError (29 , 9. 152615)
hall SetBinError (30 , 9. 746788)
hall SetBinError (31 , 9. 968042)
hall SetBinError (32 , 9. 847135)
hall SetBinError (33 , 9. 489613)
hall SetBinError (34 , 8. 986875)
hall SetBinError (35 , 8. 430032)
hall SetBinError (36 , 7. 844763)
hall SetBinError (37 , 7. 27215)
hall SetBinError (38 , 6. 759915)
hall SetBinError (39 , 6. 241824)
hall SetBinError (40 , 5. 783064)
hall SetBinError (41 , 5. 3751)
hall SetBinError (42 , 4. 98132)
hall SetBinError (43 , 4. 60544)
hall SetBinError (44 , 4. 282028)
hall SetBinError (45 , 3. 999969)
hall SetBinError (46 , 3. 719968)
hall SetBinError (47 , 3. 440953)
hall SetBinError (48 , 3. 236215)
hall SetBinError (49 , 3. 015358)
hall SetBinError (50 , 2. 823303)
hall SetBinError (51 , 2. 63927)
hall SetBinError (52 , 2. 45219)
hall SetBinError (53 , 2. 301525)
hall SetBinError (54 , 2. 152169)
hall SetBinError (55 , 2. 028768)
hall SetBinError (56 , 1. 913685)
hall SetBinError (57 , 1. 773179)
hall SetBinError (58 , 1. 657221)
hall SetBinError (59 , 1. 563784)
hall SetBinError (60 , 1. 478414)
hall SetBinError (61 , 1. 389439)
hall SetBinError (62 , 1. 297194)
hall SetBinError (63 , 1. 225703)
hall SetBinError (64 , 1. 143678)
hall SetBinError (65 , 1. 072383)
hall SetBinError (66 , 1. 005081)
h_b SetBinError (67 , 0. 9442939)
h_b SetBinError (68 , 0. 8864416)
h_b SetBinError (69 , 0. 8561526)
h_b SetBinError (70 , 0. 7995743)
hall SetBinError (71 , 0. 7518081)
h_b SetBinError (72 , 0. 7131542)
hall SetBinError (73 , 0. 6942791)
hall SetBinError (74 , 0. 6403258)
h_b SetBinError (75 , 0. 6161222)
hall SetBinError (76 , 0. 5804843)
h_b SetBinError (77 , 0. 5281453)
h_b SetBinError (78 , 0. 4842986)
hall SetBinError (79 , 0. 4777586)
h_b SetBinError (80 , 0. 4632721)
hall SetBinError (81 , 0. 4279742)
h_b SetBinError (82 , 0. 3996778)
hall SetBinError (83 , 0. 3658907)
hall SetBinError (84 , 0. 3339237)
hall SetBinError (85 , 0. 3370495)
hall SetBinError (86 , 0. 3026235)
h_b SetBinError (87 , 0. 3043511)
hall SetBinError (88 , 0. 2766776)
hall SetBinError (89 , 0. 270287)
hall SetBinError (90 , 0. 2459093)
hall SetBinError (91 , 0. 2305015)
hall SetBinError (92 , 0. 2180326)
hall SetBinError (93 , 0. 2115227)
hall SetBinError (94 , 0. 1987427)
hall SetBinError (95 , 0. 1753853)
h_b SetBinError (96 , 0. 1553018)
hall SetBinError (97 , 0. 171353)
hall SetBinError (98 , 0. 1436078)
hall SetBinError (99 , 0. 1399091)
hall SetBinError (100 , 0. 137388)
hall SetBinError (101 , 0. 1268034)
hall SetBinError (102 , 0. 1386543)
hall SetBinError (103 , 0. 1197137)
hall SetBinError (104 , 0. 1090163)
hall SetBinError (105 , 0. 1057613)
hall SetBinError (106 , 0. 1057613)
hall SetBinError (107 , 0. 08149459)
hall SetBinError (108 , 0. 08567648)
hall SetBinError (109 , 0. 097148)
hall SetBinError (110 , 0. 05912239)
hall SetBinError (111 , 0. 06200808)
hall SetBinError (112 , 0. 06476533)
hall SetBinError (113 , 0. 06740989)
hall SetBinError (114 , 0. 05288067)
hall SetBinError (115 , 0. 04946534)
hall SetBinError (116 , 0. 06200808)
hall SetBinError (117 , 0. 03739228)
hall SetBinError (118 , 0. 05608842)
hall SetBinError (119 , 0. 03739228)
hall SetBinError (120 , 0. 01869614)
hall SetBinError (121 , 0. 03238267)
hall SetBinError (122 , 0. 03238267)
hall SetBinError (123 , 0. 04180584)
hall SetBinError (126 , 0. 03238267)
hall SetBinError (128 , 0. 02644034)
hall SetBinError (129 , 0. 01869614)
hall SetBinError (130 , 0. 01869614)
hall SetBinError (131 , 0. 02644034)
hall SetBinError (134 , 0. 01869614)
hall SetBinError (140 , 0. 01869614)
hall SetBinError (145 , 0. 01869614)
h_b SetBinError (25 , 0. 045796)
h_b SetBinError (26 , 0. 1281743)
h_b SetBinError (27 , 0. 2220044)
h_b SetBinError (28 , 0. 306069)
h_b SetBinError (29 , 0. 348772)
h_b SetBinError (30 , 0. 3586542)
h_b SetBinError (31 , 0. 3729868)
h_b SetBinError (32 , 0. 3673209)
h_b SetBinError (33 , 0. 3601131)
h_b SetBinError (34 , 0. 3442325)
h_b SetBinError (35 , 0. 3183838)
h_b SetBinError (36 , 0. 3066395)
h_b SetBinError (37 , 0. 283541)
h_b SetBinError (38 , 0. 2610774)
h_b SetBinError (39 , 0. 2473267)
h_b SetBinError (40 , 0. 2408829)
h_b SetBinError (41 , 0. 2164235)
h_b SetBinError (42 , 0. 2030921)
h_b SetBinError (43 , 0. 1969761)
h_b SetBinError (44 , 0. 174386)
h_b SetBinError (45 , 0. 1518882)
h_b SetBinError (46 , 0. 148396)
h_b SetBinError (47 , 0. 1268034)
h_b SetBinError (48 , 0. 130873)
h_b SetBinError (49 , 0. 1225988)
h_b SetBinError (50 , 0. 1090163)
h_b SetBinError (51 , 0. 1040957)
h_b SetBinError (52 , 0. 0934807)
h_b SetBinError (53 , 0. 08567648)
h_b SetBinError (54 , 0. 09159201)
h_b SetBinError (55 , 0. 07240984)
h_b SetBinError (56 , 0. 08149459)
h_b SetBinError (57 , 0. 07240984)
h_b SetBinError (58 , 0. 06200808)
h_b SetBinError (59 , 0. 05912239)
h_b SetBinError (60 , 0. 05608842)
h_b SetBinError (61 , 0. 04946534)
h_b SetBinError (62 , 0. 03238267)
h_b SetBinError (63 , 0. 045796)
h_b SetBinError (64 , 0. 05912239)
h_b SetBinError (65 , 0. 04180584)
h_b SetBinError (66 , 0. 045796)
Draw_HFJetTruth_InvMass_DrawCrossSection SetBorderMode (0)
Draw_HFJetTruth_InvMass_DrawCrossSection SetBorderSize (2)
leg SetBorderSize (0)
Draw_HFJetTruth_InvMass_DrawCrossSection SetBottomMargin (0. 16)
hall SetEntries (3386403)
h_b SetEntries (5185)
Draw_HFJetTruth_InvMass_DrawCrossSection SetFillColor (0)
leg SetFillStyle (1001)
Draw_HFJetTruth_InvMass_DrawCrossSection SetFrameBorderMode (0)
Draw_HFJetTruth_InvMass_DrawCrossSection SetLeftMargin (0. 16)
h_b SetLineColor (ci)
leg SetLineColor (1)
leg SetLineStyle (1)
hall SetLineWidth (2)
leg SetLineWidth (1)
Draw_HFJetTruth_InvMass_DrawCrossSection SetLogy ()
h_b SetMarkerColor (ci)
entry SetMarkerColor (1)
hall SetMarkerSize (1. 2)
entry SetMarkerSize (1)
hall SetMarkerStyle (20)
entry SetMarkerStyle (21)
gStyle SetOptFit (1)
gStyle SetOptStat (0)
gStyle SetOptTitle (0)
Draw_HFJetTruth_InvMass_DrawCrossSection SetRightMargin (0. 05)
Draw_HFJetTruth_InvMass_DrawCrossSection SetSelected (Draw_HFJetTruth_InvMass_DrawCrossSection)
entry SetTextFont (42)
Draw_HFJetTruth_InvMass_DrawCrossSection SetTickx (1)
Draw_HFJetTruth_InvMass_DrawCrossSection SetTicky (1)
Draw_HFJetTruth_InvMass_DrawCrossSection SetTopMargin (0. 05)
Variable Documentation
ci = TColor::GetColor("#0000ff")
Definition at line 377 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
TColor* color
Definition at line 378 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
entry =leg->AddEntry("NULL","#splitline{#it{#bf{sPHENIX}} fast simulation, p+p #sqrt{s} = 200 GeV}{|#eta_{1,2}|<0.6, |#Delta#phi_{1,2}|>2#pi/3, p_{T,1}>15 GeV/c, p_{T,2}>10 GeV/c}","h")
Definition at line 411 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
TH1F* h_b = new TH1F("h_b","",200,0,200)
Definition at line 266 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
Referenced by CrossSection2RAA(), CrossSection2RAA_Proposal(), CrossSection2v2(), Draw_HFJetTruth_DrawCrossSection_PR(), Draw_HFJetTruth_InvMass_DrawCrossSection_PR(), and DrawCrossSection().
TH1F* hall = new TH1F("hall","",200,0,200)
Definition at line 22 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.
Referenced by CrossSection2RAA(), CrossSection2v2(), Draw_HFJetTruth_DrawCrossSection_PR(), Draw_HFJetTruth_InvMass_DrawCrossSection_PR(), and DrawCrossSection().
TLegend* leg = new TLegend(0.45,0.6,0.99,0.95,NULL,"brNDC")
Definition at line 404 of file 200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.rootDraw_HFJetTruth_InvMass_DrawCrossSection.C.