Analysis Software: BbcVertexFastSimReco Class Reference
BbcVertexFastSimReco Class Reference
simple truth vertex smearing algorithm
#include <coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexFastSimReco.h>
Public Member Functions
BbcVertexFastSimReco (const std::string &name="BbcVertexFastSimReco")
virtual ~BbcVertexFastSimReco ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_t_smearing (const float t_smear)
void set_z_smearing (const float z_smear)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
Private Attributes
float m_T_Smear
float m_Z_Smear
gsl_rng * RandomGenerator
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
simple truth vertex smearing algorithm
Definition at line 25 of file BbcVertexFastSimReco.h.
Constructor & Destructor Documentation
BbcVertexFastSimReco::BbcVertexFastSimReco (const std::string & name = "BbcVertexFastSimReco")
Definition at line 33 of file BbcVertexFastSimReco.cc.
References RandomGenerator.
BbcVertexFastSimReco::~BbcVertexFastSimReco () virtual
Definition at line 41 of file BbcVertexFastSimReco.cc.
References RandomGenerator.
Member Function Documentation
int BbcVertexFastSimReco::CreateNodes (PHCompositeNode * topNode) private
Definition at line 136 of file BbcVertexFastSimReco.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int BbcVertexFastSimReco::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 131 of file BbcVertexFastSimReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int BbcVertexFastSimReco::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 46 of file BbcVertexFastSimReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int BbcVertexFastSimReco::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 51 of file BbcVertexFastSimReco.cc.
References CreateNodes(), m_T_Smear, m_Z_Smear, PHWHERE, RandomGenerator, TauVsDIS_MachineLearning_Differentiation::seed, and Fun4AllBase::Verbosity().
int BbcVertexFastSimReco::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 74 of file BbcVertexFastSimReco.cc.
References Fun4AllReturnCodes::EVENT_OK, PHG4VtxPoint::get_t(), PHG4VtxPoint::get_z(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), BbcVertexMap::insert(), m_T_Smear, m_Z_Smear, PHWHERE, RandomGenerator, BbcVertex::set_t(), BbcVertex::set_t_err(), BbcVertex::set_z(), BbcVertex::set_z_err(), and Fun4AllBase::Verbosity().
void BbcVertexFastSimReco::set_t_smearing (const float t_smear) inline
Definition at line 36 of file BbcVertexFastSimReco.h.
References m_T_Smear.
Referenced by Bbc_Reco().
void BbcVertexFastSimReco::set_z_smearing (const float z_smear) inline
Definition at line 37 of file BbcVertexFastSimReco.h.
References m_Z_Smear.
Referenced by Bbc_Reco().
Member Data Documentation
float BbcVertexFastSimReco::m_T_Smear private
Definition at line 42 of file BbcVertexFastSimReco.h.
Referenced by InitRun(), process_event(), and set_t_smearing().
float BbcVertexFastSimReco::m_Z_Smear private
Definition at line 43 of file BbcVertexFastSimReco.h.
Referenced by InitRun(), process_event(), and set_z_smearing().
gsl_rng* BbcVertexFastSimReco::RandomGenerator private
Definition at line 46 of file BbcVertexFastSimReco.h.
Referenced by BbcVertexFastSimReco(), InitRun(), process_event(), and ~BbcVertexFastSimReco().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexFastSimReco.h
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexFastSimReco.cc