Analysis Software: AssocInfoContainer Class Reference
AssocInfoContainer Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/AssocInfoContainer.h>
Public Types
typedef std::multimap
< TrkrDefs::cluskey, unsigned
int > ClusterTrackMap
Public Member Functions
AssocInfoContainer ()
virtual ~AssocInfoContainer ()
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
void SetClusterTrackAssoc (const TrkrDefs::cluskey &cluster_id, const unsigned int &track_id)
std::vector< unsigned int > GetTracksFromCluster (const TrkrDefs::cluskey &cluster_id) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
ClusterTrackMap _map_cluster_id_track_id
Detailed Description
Definition at line 13 of file AssocInfoContainer.h.
Member Typedef Documentation
typedef std::multimap<TrkrDefs::cluskey, unsigned int> AssocInfoContainer::ClusterTrackMap
Definition at line 16 of file AssocInfoContainer.h.
Constructor & Destructor Documentation
AssocInfoContainer::AssocInfoContainer ()
Definition at line 5 of file AssocInfoContainer.cc.
AssocInfoContainer::~AssocInfoContainer () virtual
Definition at line 10 of file AssocInfoContainer.cc.
References Reset().
Member Function Documentation
std::vector<unsigned int> AssocInfoContainer::GetTracksFromCluster (const TrkrDefs::cluskey & cluster_id) const inline
Definition at line 29 of file AssocInfoContainer.h.
References _map_cluster_id_track_id.
Referenced by PHGenFitTrkProp::check_track_exists().
void AssocInfoContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 17 of file AssocInfoContainer.cc.
References _map_cluster_id_track_id.
void AssocInfoContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 12 of file AssocInfoContainer.cc.
References _map_cluster_id_track_id.
Referenced by ~AssocInfoContainer().
void AssocInfoContainer::SetClusterTrackAssoc (const TrkrDefs::cluskey & cluster_id, const unsigned int & track_id) inline
Definition at line 24 of file AssocInfoContainer.h.
References _map_cluster_id_track_id.
Referenced by PHHoughSeeding::export_output(), PHGenFitTrkProp::OutputPHGenFitTrack(), PHTruthTrackSeeding::Process(), and TpcPrototypeGenFitTrkFinder::process_event().
Member Data Documentation
ClusterTrackMap AssocInfoContainer::_map_cluster_id_track_id private
Definition at line 41 of file AssocInfoContainer.h.
Referenced by GetTracksFromCluster(), identify(), Reset(), and SetClusterTrackAssoc().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/AssocInfoContainer.h
coresoftware/blob/master/offline/packages/trackreco/AssocInfoContainer.cc