Analysis Software: BEmcRecCEMC Class Reference
BEmcRecCEMC Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcRecCEMC.h>
Public Member Functions
BEmcRecCEMC ()
~BEmcRecCEMC ()
void CorrectEnergy (float energy, float x, float y, float *ecorr)
void CorrectPosition (float energy, float x, float y, float *xcorr, float *ycorr)
void CorrectECore (float ecore, float x, float y, float *ecorecorr)
void Tower2Global (float E, float xC, float yC, float &xA, float &yA, float &zA)
Public Member Functions inherited from BEmcRec
BEmcRec ()
virtual ~BEmcRec ()
void SetVertex (float *vv)
void SetGeometry (int nx, int ny, float txsz, float tysz)
void SetConf (int nx, int ny)
bool SetTowerGeometry (int ix, int iy, float xx, float yy, float zz)
bool GetTowerGeometry (int ix, int iy, TowerGeom &geom)
void PrintTowerGeometry (const char *fname)
void SetPlaneGeometry ()
void SetCylindricalGeometry ()
bool isCylindrical () const
int GetNx () const
int GetNy () const
float GetModSizex () const
float GetModSizey () const
float GetVx () const
float GetVy () const
float GetVz () const
void SetPeakThreshold (float Thresh)
float GetPeakThreshold ()
float GetTowerThreshold ()
void SetModules (std::vector< EmcModule > const *modules)
std::vector< EmcModule > * GetModules ()
std::vector< EmcCluster > * GetClusters ()
int iTowerDist (int ix1, int ix2)
float fTowerDist (float x1, float x2)
int FindClusters ()
void GlobalToSector (float, float, float, float *, float *, float *)
void SectorToGlobal (float xsec, float ysec, float zsec, float *px, float *py, float *pz)
void SectorToGlobalErr (float dxsec, float dysec, float dzsec, float *pdx, float *pdy, float *pdz)
void TowersToSector (float, float, float &, float &)
Converts coordinates in units of towers into cm's (Local coord. system)
void TowersToSector (int, int, float &, float &)
Returns coordinates of the tower centers in cm's (Local coord. system)
void SectorToTowers (float, float, int &, int &)
Converts Local Sector coordinates in cm into integer tower numbers.
void Gamma (int, EmcModule *, float *, float *, float *, float *, float *, float *, float *, float *, int &ndf)
void Momenta (int, EmcModule *, float *, float *, float *, float *, float *, float *)
int ShiftX (int ishift, int nh, EmcModule *phit0, EmcModule *phit1)
EmcModule ShiftX (int ish, EmcModule &ehit)
void SetTowerThreshold (float Thresh)
void SetProfileParameters (int, float, float, float)
void SetChi2Limit (int lim)
int GetTowerID (int iy, int iz, int nn, int *iyy, int *izz, float *ee)
float GetProb (std::vector< EmcModule > HitList, float &chi2, int &ndf)
float ClusterChisq (int, EmcModule *, float, float, float, int &ndf)
float Chi2Correct (float chi2, int ndf)
void TwoGamma (int, EmcModule *, float *, float *, float *, float *, float *, float *, float *)
float Chi2Limit (int ndf)
float PredictEnergy (float, float, float)
void CalculateErrors (float e, float x, float y, float *pde, float *pdx, float *pdy, float *pdz)
void getTowerPos (int ix, int iy, float &x, float &y)
Additional Inherited Members
Static Public Member Functions inherited from BEmcRec
static int HitNCompare (const void *, const void *)
static int HitACompare (const void *, const void *)
static void CopyVector (int *, int *, int)
static void CopyVector (EmcModule *, EmcModule *, int)
static void ZeroVector (int *, int)
static void ZeroVector (float *, int)
static void ZeroVector (EmcModule *, int)
static void c3to5 (float, float, float, float, float, float, float *, float *, float *, float *, float *, float *)
Protected Attributes inherited from BEmcRec
bool bCYL
int fNx
int fNy
std::map< int, TowerGeom > fTowerGeom
float fModSizex
float fModSizey
float fVx
float fVy
float fVz
std::vector< EmcModule > * fModules
std::vector< EmcCluster > * fClusters
float fgTowerThresh
float fgMinPeakEnergy
float fSin4T
float fSinTx
float fSinTy
float fPpar1
float fPpar2
float fPpar3
float fPpar4
float fPshiftx
float fPshifty
Static Protected Attributes inherited from BEmcRec
static float fgChi2Level1 []
static float fgChi2Level2 []
static float fgChi2Level []
static float const fgMinShowerEnergy = 0.1
static int const fgMaxLen = 10000
static float fgEpar00 = 0.005
static float fgEpar0 = 0.0014
static float fgEpar1 = 0.03
static float fgEpar2 = -0.03
static float fgEpar3 = 0.
static float fgEpar4 = 4.0
Detailed Description
Definition at line 6 of file BEmcRecCEMC.h.
Constructor & Destructor Documentation
BEmcRecCEMC::BEmcRecCEMC () inline
Definition at line 9 of file BEmcRecCEMC.h.
BEmcRecCEMC::~BEmcRecCEMC () inline
Definition at line 10 of file BEmcRecCEMC.h.
Member Function Documentation
void BEmcRecCEMC::CorrectECore (float ecore, float x, float y, float * ecorecorr) virtual
Implements BEmcRec.
Definition at line 40 of file BEmcRecCEMC.cc.
void BEmcRecCEMC::CorrectEnergy (float energy, float x, float y, float * ecorr) virtual
Implements BEmcRec.
Definition at line 15 of file BEmcRecCEMC.cc.
void BEmcRecCEMC::CorrectPosition (float energy, float x, float y, float * xcorr, float * ycorr) virtual
Implements BEmcRec.
Definition at line 51 of file BEmcRecCEMC.cc.
References EmcCluster::ABS(), BEmcRec::fSinTx, BEmcRec::fSinTy, BEmcRec::GetModSizex(), EmcCluster::lowint(), printf(), BEmcRec::SetProfileParameters(), t, x, x0, and y.
void BEmcRecCEMC::Tower2Global (float E, float xC, float yC, float & xA, float & yA, float & zA) virtual
Implements BEmcRec.
Definition at line 7 of file BEmcRecCEMC.cc.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcRecCEMC.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcRecCEMC.cc