Analysis Software: CaloCalibration Class Reference
CaloCalibration Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/CaloCalibration.h>
Public Types
enum FitMethodType { kPowerLawExp, kPowerLawDoubleExp, kPowerLawDoubleExpWithGlobalFitConstraint, kPeakSample }
Public Member Functions
CaloCalibration (const std::string &name)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
std::string get_calib_tower_node_prefix () const
void set_calib_tower_node_prefix (const std::string &calibTowerNodePrefix)
std::string get_raw_tower_node_prefix () const
void set_raw_tower_node_prefix (const std::string &rawTowerNodePrefix)
const PHParameters & GetCalibrationParameters () const
Get the parameters for readonly.
PHParameters & GetCalibrationParameters ()
void SetCalibrationParameters (const PHParameters &calib_params)
CaloCalibration (const std::string &name)
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void CreateNodeTree (PHCompositeNode *topNode)
std::string get_calib_tower_node_prefix () const
void set_calib_tower_node_prefix (const std::string &calibTowerNodePrefix)
std::string get_raw_tower_node_prefix () const
void set_raw_tower_node_prefix (const std::string &rawTowerNodePrefix)
const PHParameters & GetCalibrationParameters () const
Get the parameters for readonly.
PHParameters & GetCalibrationParameters ()
void SetCalibrationParameters (const PHParameters &calib_params)
CaloCalibration (const std::string &name)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void CreateNodeTree (PHCompositeNode *topNode)
std::string get_calib_tower_node_prefix () const
void set_calib_tower_node_prefix (const std::string &calibTowerNodePrefix)
std::string get_raw_tower_node_prefix () const
void set_raw_tower_node_prefix (const std::string &rawTowerNodePrefix)
const PHParameters & GetCalibrationParameters () const
Get the parameters for readonly.
PHParameters & GetCalibrationParameters ()
void SetCalibrationParameters (const PHParameters &calib_params)
void SetFitType (FitMethodType t)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters (PHParameters &param)
load the default parameter to param
void SetDefaultParameters (PHParameters &param)
load the default parameter to param
void SetDefaultParameters (PHParameters &param)
load the default parameter to param
Private Attributes
RawTowerContainer * _calib_towers
RawTowerContainer * _raw_towers
std::string detector
std::string RawTowerNodeName
std::string CaliTowerNodeName
std::string _calib_tower_node_prefix
std::string _raw_tower_node_prefix
PHParameters _calib_params
FitMethodType _fit_type
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file CaloCalibration.h.
Member Enumeration Documentation
enum CaloCalibration::FitMethodType
Enumerator:
kPowerLawExp
single power-low-exp fit, PROTOTYPE4_FEM::SampleFit_PowerLawExp()
kPowerLawDoubleExp
power-low-double-exp fit, PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp
kPowerLawDoubleExpWithGlobalFitConstraint
power-low-double-exp fit, PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp, and constraining all tower take identical shape
kPeakSample
just use the peak sample, PROTOTYPE4_FEM::SampleFit_PeakSample()
Definition at line 63 of file CaloCalibration.h.
Constructor & Destructor Documentation
CaloCalibration::CaloCalibration (const std::string & name)
Definition at line 36 of file CaloCalibration.cc.
References _calib_params, and SetDefaultParameters().
CaloCalibration::CaloCalibration (const std::string & name)
CaloCalibration::CaloCalibration (const std::string & name)
Member Function Documentation
void CaloCalibration::CreateNodeTree (PHCompositeNode * topNode)
Definition at line 156 of file CaloCalibration.cc.
References _calib_params, _calib_tower_node_prefix, _calib_towers, _raw_tower_node_prefix, _raw_towers, assert, CaliTowerNodeName, detector, PHNodeIterator::findFirst(), RawTowerContainer::getCalorimeterID(), Fun4AllBase::Name(), RawTowerNodeName, and PHParameters::SaveToNodeTree().
Referenced by InitRun().
void CaloCalibration::CreateNodeTree (PHCompositeNode * topNode)
void CaloCalibration::CreateNodeTree (PHCompositeNode * topNode)
int CaloCalibration::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 224 of file CaloCalibration.cc.
References Fun4AllReturnCodes::EVENT_OK.
std::string CaloCalibration::get_calib_tower_node_prefix () const inline
Definition at line 29 of file CaloCalibration.h.
References _calib_tower_node_prefix.
std::string CaloCalibration::get_calib_tower_node_prefix () const inline
Definition at line 29 of file CaloCalibration.h.
References _calib_tower_node_prefix.
std::string CaloCalibration::get_calib_tower_node_prefix () const inline
Definition at line 33 of file CaloCalibration.h.
References _calib_tower_node_prefix.
std::string CaloCalibration::get_raw_tower_node_prefix () const inline
Definition at line 39 of file CaloCalibration.h.
References _raw_tower_node_prefix.
std::string CaloCalibration::get_raw_tower_node_prefix () const inline
Definition at line 39 of file CaloCalibration.h.
References _raw_tower_node_prefix.
std::string CaloCalibration::get_raw_tower_node_prefix () const inline
Definition at line 43 of file CaloCalibration.h.
References _raw_tower_node_prefix.
const PHParameters& CaloCalibration::GetCalibrationParameters () const inline
Get the parameters for readonly.
Definition at line 50 of file CaloCalibration.h.
References _calib_params.
const PHParameters& CaloCalibration::GetCalibrationParameters () const inline
Get the parameters for readonly.
Definition at line 50 of file CaloCalibration.h.
References _calib_params.
Referenced by Fun4All_TestBeam().
PHParameters& CaloCalibration::GetCalibrationParameters () inline
Get the parameters for update. Useful fields are listed in SetDefaultParameters();
Definition at line 54 of file CaloCalibration.h.
References _calib_params.
PHParameters& CaloCalibration::GetCalibrationParameters () inline
Get the parameters for update. Useful fields are listed in SetDefaultParameters();
Definition at line 54 of file CaloCalibration.h.
References _calib_params.
const PHParameters& CaloCalibration::GetCalibrationParameters () const inline
Get the parameters for readonly.
Definition at line 54 of file CaloCalibration.h.
References _calib_params.
PHParameters& CaloCalibration::GetCalibrationParameters () inline
Get the parameters for update. Useful fields are listed in SetDefaultParameters();
Definition at line 58 of file CaloCalibration.h.
References _calib_params.
int CaloCalibration::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 54 of file CaloCalibration.cc.
References Fun4AllReturnCodes::EVENT_OK.
int CaloCalibration::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 54 of file CaloCalibration.cc.
References _calib_params, CreateNodeTree(), Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Name(), PHParameters::Print(), and Fun4AllBase::Verbosity().
int CaloCalibration::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int CaloCalibration::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int CaloCalibration::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int CaloCalibration::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 69 of file CaloCalibration.cc.
References _calib_params, _calib_towers, _raw_towers, RawTowerContainer::AddTower(), assert, Fun4AllReturnCodes::EVENT_OK, RawTower_Prototype2::get_column(), PHParameters::get_double_param(), RawTower_Prototype2::get_energy(), PHParameters::get_int_param(), RawTower_Prototype2::get_row(), RawTower_Prototype2::get_signal_samples(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTowers(), i, Fun4AllBase::Name(), RawTower_Prototype2::NSAMPLES, PROTOTYPE2_FEM::SampleFit_PowerLawExp(), RawTower_Prototype2::set_energy(), RawTower_Prototype2::set_signal_samples(), RawTower_Prototype2::set_time(), and Fun4AllBase::Verbosity().
int CaloCalibration::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
void CaloCalibration::set_calib_tower_node_prefix (const std::string & calibTowerNodePrefix) inline
Definition at line 34 of file CaloCalibration.h.
References _calib_tower_node_prefix.
Referenced by Fun4All_TestBeam().
void CaloCalibration::set_calib_tower_node_prefix (const std::string & calibTowerNodePrefix) inline
Definition at line 34 of file CaloCalibration.h.
References _calib_tower_node_prefix.
void CaloCalibration::set_calib_tower_node_prefix (const std::string & calibTowerNodePrefix) inline
Definition at line 38 of file CaloCalibration.h.
References _calib_tower_node_prefix.
void CaloCalibration::set_raw_tower_node_prefix (const std::string & rawTowerNodePrefix) inline
Definition at line 44 of file CaloCalibration.h.
References _raw_tower_node_prefix.
Referenced by Fun4All_TestBeam().
void CaloCalibration::set_raw_tower_node_prefix (const std::string & rawTowerNodePrefix) inline
Definition at line 44 of file CaloCalibration.h.
References _raw_tower_node_prefix.
void CaloCalibration::set_raw_tower_node_prefix (const std::string & rawTowerNodePrefix) inline
Definition at line 48 of file CaloCalibration.h.
References _raw_tower_node_prefix.
void CaloCalibration::SetCalibrationParameters (const PHParameters & calib_params) inline
Overwrite the parameter. Useful fields are listed in SetDefaultParameters();
Definition at line 58 of file CaloCalibration.h.
References _calib_params.
void CaloCalibration::SetCalibrationParameters (const PHParameters & calib_params) inline
Overwrite the parameter. Useful fields are listed in SetDefaultParameters();
Definition at line 58 of file CaloCalibration.h.
References _calib_params.
void CaloCalibration::SetCalibrationParameters (const PHParameters & calib_params) inline
Overwrite the parameter. Useful fields are listed in SetDefaultParameters();
Definition at line 62 of file CaloCalibration.h.
References _calib_params.
void CaloCalibration::SetDefaultParameters (PHParameters & param) private
load the default parameter to param
Definition at line 215 of file CaloCalibration.cc.
References PHParameters::set_double_param(), and PHParameters::set_int_param().
Referenced by CaloCalibration().
void CaloCalibration::SetDefaultParameters (PHParameters & param) private
load the default parameter to param
void CaloCalibration::SetDefaultParameters (PHParameters & param) private
load the default parameter to param
void CaloCalibration::SetFitType (FitMethodType t) inline
Definition at line 80 of file CaloCalibration.h.
References _fit_type, and t.
Referenced by Fun4All_TestBeam().
Member Data Documentation
PHParameters CaloCalibration::_calib_params private
Definition at line 74 of file CaloCalibration.h.
Referenced by CaloCalibration(), CreateNodeTree(), GetCalibrationParameters(), InitRun(), process_event(), and SetCalibrationParameters().
std::string CaloCalibration::_calib_tower_node_prefix private
Definition at line 71 of file CaloCalibration.h.
Referenced by CreateNodeTree(), get_calib_tower_node_prefix(), and set_calib_tower_node_prefix().
RawTowerContainer * CaloCalibration::_calib_towers private
Definition at line 64 of file CaloCalibration.h.
Referenced by CreateNodeTree(), and process_event().
FitMethodType CaloCalibration::_fit_type private
Definition at line 95 of file CaloCalibration.h.
Referenced by SetFitType().
std::string CaloCalibration::_raw_tower_node_prefix private
Definition at line 72 of file CaloCalibration.h.
Referenced by CreateNodeTree(), get_raw_tower_node_prefix(), and set_raw_tower_node_prefix().
RawTowerContainer * CaloCalibration::_raw_towers private
Definition at line 65 of file CaloCalibration.h.
Referenced by CreateNodeTree(), and process_event().
std::string CaloCalibration::CaliTowerNodeName private
Definition at line 69 of file CaloCalibration.h.
Referenced by CreateNodeTree().
std::string CaloCalibration::detector private
Definition at line 67 of file CaloCalibration.h.
Referenced by CreateNodeTree().
std::string CaloCalibration::RawTowerNodeName private
Definition at line 68 of file CaloCalibration.h.
Referenced by CreateNodeTree().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/CaloCalibration.h
prototype/blob/master/offline/packages/Prototype4/CaloCalibration.h
prototype/blob/master/offline/packages/Prototype3/CaloCalibration.h
prototype/blob/master/offline/packages/Prototype2/CaloCalibration.cc
prototype/blob/master/offline/packages/Prototype3/CaloCalibration.cc
prototype/blob/master/offline/packages/Prototype4/CaloCalibration.cc