Analysis Software: PHG4CellDefs::EtaPhiBinning Namespace Reference
PHG4CellDefs::EtaPhiBinning Namespace Reference
Functions
keytype genkey (const unsigned short layer, const unsigned short etabin, const unsigned short phibin)
unsigned short int get_etabin (const PHG4CellDefs::keytype key)
unsigned short int get_phibin (const PHG4CellDefs::keytype key)
Function Documentation
PHG4CellDefs::keytype PHG4CellDefs::EtaPhiBinning::genkey (const unsigned short layer, const unsigned short etabin, const unsigned short phibin)
Definition at line 47 of file PHG4CellDefs.cc.
References PHG4CellDefs::etaphibinning, and generic_16bit_genkey().
Referenced by PHG4CylinderCellReco::process_event().
unsigned short int PHG4CellDefs::EtaPhiBinning::get_etabin (const PHG4CellDefs::keytype key)
Definition at line 54 of file PHG4CellDefs.cc.
References PHG4CellDefs::etaphibinning, and generic_lower_16bit_key().
Referenced by PHG4CylinderCellReco::process_event(), and DumpPHG4CellContainer::process_Node().
unsigned short int PHG4CellDefs::EtaPhiBinning::get_phibin (const PHG4CellDefs::keytype key)
Definition at line 61 of file PHG4CellDefs.cc.
References PHG4CellDefs::etaphibinning, and generic_upper_16bit_key().
Referenced by PHG4CylinderCellReco::process_event(), and DumpPHG4CellContainer::process_Node().