Analysis Software: online_distribution/blob/master/newbasic/CframeV1.C File Reference
CframeV1.C File Reference
#include "CframeV1.h"
Functions
VALUE_ret makeFrameHdrV1 (PHDWORD *frame_ptr, UINT maxFrameLen, UINT dataType, UINT frameType, UINT sourceId)
VALUE_ret getFrameDataLengthV1 (FRAME_ptr frame_ptr)
VALUE_ret orFrameStatusV1 (FRAME_ptr frame_ptr, UINT statusBits)
VALUE_ret adjustFrameHistoryLengthV1 (FRAME_ptr frame_ptr, UINT newDwords)
VALUE_ret adjustFrameErrorLengthV1 (FRAME_ptr frame_ptr, UINT newDwords)
Function Documentation
VALUE_ret adjustFrameErrorLengthV1 (FRAME_ptr frame_ptr, UINT newDwords)
Definition at line 124 of file CframeV1.C.
References ERROR_LENGTH_MASK, ERROR_LENGTH_OFFSET_IN_DWORD, ERROR_LENGTH_OFFSET_OF_DWORD, FORMAT_ERR_ERROR_OVERFLOW, getFrameErrorLengthV1(), maxSwordValue, setBitsMACRO, setFrameError(), setFrameSuccess(), and valueFailure.
VALUE_ret adjustFrameHistoryLengthV1 (FRAME_ptr frame_ptr, UINT newDwords)
Definition at line 98 of file CframeV1.C.
References FORMAT_ERR_HISTORY_OVERFLOW, getFrameHistoryLengthV1(), HISTORY_LENGTH_MASK, HISTORY_LENGTH_OFFSET_IN_DWORD, HISTORY_LENGTH_OFFSET_OF_DWORD, maxSwordValue, setBitsMACRO, setFrameError(), setFrameSuccess(), and valueFailure.
VALUE_ret getFrameDataLengthV1 (FRAME_ptr frame_ptr)
Definition at line 50 of file CframeV1.C.
References FORMAT_ERR_INVALID_HEADER, getFrameErrorLengthV1(), getFrameHdrLength(), getFrameHistoryLengthV1(), getFrameLength(), getFramePaddingV1(), setFrameError(), setFrameSuccess(), and valueFailure.
Referenced by adjustFrameDataLengthV1().
VALUE_ret makeFrameHdrV1 (PHDWORD * frame_ptr, UINT maxFrameLen, UINT dataType, UINT frameType, UINT sourceId)
Definition at line 30 of file CframeV1.C.
References currentFrameHdrLength, currentFrameHdrVersion, currentFrameMark, dwordClear, setDataType(), setFrameAlignLength(), setFrameHdrLength(), setFrameHdrVersion(), setFrameLength(), setFrameMark(), setFrameType(), setSourceId(), V1_ALIGN_LENGTH, V1_FRAMEHDR_LENGTH, and valueFailure.
VALUE_ret orFrameStatusV1 (FRAME_ptr frame_ptr, UINT statusBits)
Definition at line 71 of file CframeV1.C.
References FORMAT_ERR_INVALID_DATA, getBitsMACRO, setBitsMACRO, setUserError(), STATUS_MASK, STATUS_NUM_BITS, STATUS_OFFSET_IN_DWORD, STATUS_OFFSET_OF_DWORD, and valueFailure.