Analysis Software: Leptoquarks Class Reference
Leptoquarks Class Reference
#include <analysis/blob/master/EICAnalysis/Leptoquarks.h>
Public Member Functions
Leptoquarks (std::string filename)
int Init (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
void set_beam_energies (float beam_electron, float beam_proton)
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void UpdateFinalStateParticle (HepMC::GenParticle *&)
Private Attributes
bool _verbose
int _ievent
int _total_pass
std::string _foutname
TFile * _fout_root
TNtuple * _tree_event
float _ebeam_E
float _pbeam_E
int _embedding_id
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file Leptoquarks.h.
Constructor & Destructor Documentation
Leptoquarks::Leptoquarks (std::string filename)
Definition at line 24 of file Leptoquarks.C.
Member Function Documentation
int Leptoquarks::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 189 of file Leptoquarks.C.
References _fout_root, and _tree_event.
int Leptoquarks::get_embedding_id () const inline
The embedding ID for the HepMC subevent to be analyzed. embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 44 of file Leptoquarks.h.
References _embedding_id.
int Leptoquarks::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 37 of file Leptoquarks.C.
References _fout_root, _foutname, _ievent, and _tree_event.
int Leptoquarks::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 51 of file Leptoquarks.C.
References _ievent, _tree_event, Fun4AllReturnCodes::ABORTRUN, TruthTrackerHepMC::FindDaughterParticle(), TruthTrackerHepMC::FindDecayParticles(), TruthTrackerHepMC::FindMissingPt(), TruthTrackerHepMC::FindParticle(), PHWHERE, and TruthTrackerHepMC::set_hepmc_geneventmap().
void Leptoquarks::set_beam_energies (float beam_electron, float beam_proton) inline
Definition at line 33 of file Leptoquarks.h.
References _ebeam_E, and _pbeam_E.
Referenced by Fun4All_EICAnalysis_Leptoquarks().
void Leptoquarks::set_embedding_id (int id) inline
The embedding ID for the HepMC subevent to be analyzed. embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 51 of file Leptoquarks.h.
References _embedding_id.
void Leptoquarks::UpdateFinalStateParticle (HepMC::GenParticle *& particle) private
Check if this is the final state particle or not- update pointer if needed
Definition at line 200 of file Leptoquarks.C.
Member Data Documentation
float Leptoquarks::_ebeam_E private
Definition at line 66 of file Leptoquarks.h.
Referenced by set_beam_energies().
int Leptoquarks::_embedding_id private
The embedding ID for the HepMC subevent to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 72 of file Leptoquarks.h.
Referenced by get_embedding_id(), and set_embedding_id().
TFile* Leptoquarks::_fout_root private
Definition at line 60 of file Leptoquarks.h.
Referenced by End(), and Init().
std::string Leptoquarks::_foutname private
Definition at line 59 of file Leptoquarks.h.
Referenced by Init().
int Leptoquarks::_ievent private
Definition at line 56 of file Leptoquarks.h.
Referenced by Init(), and process_event().
float Leptoquarks::_pbeam_E private
Definition at line 67 of file Leptoquarks.h.
Referenced by set_beam_energies().
int Leptoquarks::_total_pass private
Definition at line 57 of file Leptoquarks.h.
TNtuple* Leptoquarks::_tree_event private
Definition at line 63 of file Leptoquarks.h.
Referenced by End(), Init(), and process_event().
bool Leptoquarks::_verbose private
Definition at line 54 of file Leptoquarks.h.
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/Leptoquarks.h
analysis/blob/master/EICAnalysis/Leptoquarks.C