Analysis Software: RawTower_Prototype3 Class Reference
RawTower_Prototype3 Class Reference
#include <prototype/blob/master/offline/packages/Prototype3/RawTower_Prototype3.h>
Public Types
enum { NSAMPLES = PROTOTYPE3_FEM::NSAMPLES }
typedef float signal_type
Public Types inherited from RawTower
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Public Member Functions
RawTower_Prototype3 ()
RawTower_Prototype3 (RawTowerDefs::keytype id)
RawTower_Prototype3 (const unsigned int icol, const unsigned int irow)
RawTower_Prototype3 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual ~RawTower_Prototype3 ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
void set_id (RawTowerDefs::keytype id)
RawTowerDefs::keytype get_id () const
int get_bineta () const
int get_binphi () const
int get_column () const
int get_row () const
double get_energy () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e)
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t)
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_signal_samples (int i, signal_type sig)
signal_type get_signal_samples (int i) const
void set_HBD_channel_number (int i)
int get_HBD_channel_number () const
double get_energy_power_law_exp (int verbosity=0)
Public Member Functions inherited from RawTower
virtual ~RawTower ()
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType g4cellid, const float ecell)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int id)
virtual ShowerConstIterator find_g4shower (int id) const
virtual void add_eshower (const int g4showerid, const float eshower)
virtual void clear_g4showers ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid
double energy
float time
signal_type signal_samples [NSAMPLES]
int HBD_channel
Additional Inherited Members
Protected Member Functions inherited from RawTower
RawTower ()
Detailed Description
Definition at line 14 of file RawTower_Prototype3.h.
Member Typedef Documentation
typedef float RawTower_Prototype3::signal_type
Definition at line 47 of file RawTower_Prototype3.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
NSAMPLES
Definition at line 43 of file RawTower_Prototype3.h.
Constructor & Destructor Documentation
RawTower_Prototype3::RawTower_Prototype3 ()
Definition at line 15 of file RawTower_Prototype3.cc.
References NSAMPLES, and signal_samples.
RawTower_Prototype3::RawTower_Prototype3 (RawTowerDefs::keytype id)
Definition at line 25 of file RawTower_Prototype3.cc.
References NSAMPLES, and signal_samples.
RawTower_Prototype3::RawTower_Prototype3 (const unsigned int icol, const unsigned int irow)
Definition at line 34 of file RawTower_Prototype3.cc.
References RawTowerDefs::encode_towerid(), RawTowerDefs::NONE, NSAMPLES, signal_samples, and towerid.
RawTower_Prototype3::RawTower_Prototype3 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 45 of file RawTower_Prototype3.cc.
References RawTowerDefs::encode_towerid(), NSAMPLES, signal_samples, and towerid.
virtual RawTower_Prototype3::~RawTower_Prototype3 () inline virtual
Definition at line 23 of file RawTower_Prototype3.h.
Member Function Documentation
int RawTower_Prototype3::get_bineta () const inline virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Prototype3.h.
References RawTowerDefs::decode_index1(), and towerid.
Referenced by identify().
int RawTower_Prototype3::get_binphi () const inline virtual
Reimplemented from RawTower.
Definition at line 32 of file RawTower_Prototype3.h.
References RawTowerDefs::decode_index2(), and towerid.
Referenced by identify().
int RawTower_Prototype3::get_column () const inline virtual
Reimplemented from RawTower.
Definition at line 33 of file RawTower_Prototype3.h.
References RawTowerDefs::decode_index1(), and towerid.
double RawTower_Prototype3::get_energy () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 35 of file RawTower_Prototype3.h.
References energy.
Referenced by identify(), isValid(), and Prototype3DSTReader::process_event().
double RawTower_Prototype3::get_energy_power_law_exp (int verbosity = 0)
Definition at line 88 of file RawTower_Prototype3.cc.
References i, NSAMPLES, PROTOTYPE3_FEM::SampleFit_PowerLawExp(), and signal_samples.
int RawTower_Prototype3::get_HBD_channel_number () const inline
Definition at line 52 of file RawTower_Prototype3.h.
References HBD_channel.
RawTowerDefs::keytype RawTower_Prototype3::get_id () const inline virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Prototype3.h.
References towerid.
int RawTower_Prototype3::get_row () const inline virtual
Reimplemented from RawTower.
Definition at line 34 of file RawTower_Prototype3.h.
References RawTowerDefs::decode_index2(), and towerid.
RawTower_Prototype3::signal_type RawTower_Prototype3::get_signal_samples (int i) const
Definition at line 81 of file RawTower_Prototype3.cc.
References assert, i, NSAMPLES, and signal_samples.
Referenced by EventInfoSummary::process_event().
float RawTower_Prototype3::get_time () const inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 37 of file RawTower_Prototype3.h.
References time.
void RawTower_Prototype3::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
Definition at line 66 of file RawTower_Prototype3.cc.
References get_bineta(), get_binphi(), and get_energy().
int RawTower_Prototype3::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 64 of file RawTower_Prototype3.cc.
References get_energy().
void RawTower_Prototype3::Reset () virtual
Clear Event.
Reimplemented from RawTower.
Definition at line 57 of file RawTower_Prototype3.cc.
References energy, NSAMPLES, signal_samples, and time.
void RawTower_Prototype3::set_energy (const double) inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 36 of file RawTower_Prototype3.h.
References energy.
void RawTower_Prototype3::set_HBD_channel_number (int i) inline
Definition at line 51 of file RawTower_Prototype3.h.
References HBD_channel, and i.
void RawTower_Prototype3::set_id (RawTowerDefs::keytype id) inline virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Prototype3.h.
References towerid.
void RawTower_Prototype3::set_signal_samples (int i, RawTower_Prototype3::signal_type sig)
Definition at line 72 of file RawTower_Prototype3.cc.
References assert, i, NSAMPLES, and signal_samples.
void RawTower_Prototype3::set_time (const float) inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 38 of file RawTower_Prototype3.h.
References t, and time.
Member Data Documentation
double RawTower_Prototype3::energy protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 63 of file RawTower_Prototype3.h.
Referenced by get_energy(), Reset(), and set_energy().
int RawTower_Prototype3::HBD_channel protected
Definition at line 70 of file RawTower_Prototype3.h.
Referenced by get_HBD_channel_number(), and set_HBD_channel_number().
signal_type RawTower_Prototype3::signal_samples[NSAMPLES] protected
Definition at line 69 of file RawTower_Prototype3.h.
Referenced by get_energy_power_law_exp(), get_signal_samples(), RawTower_Prototype3(), Reset(), and set_signal_samples().
float RawTower_Prototype3::time protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 66 of file RawTower_Prototype3.h.
Referenced by get_time(), Reset(), and set_time().
RawTowerDefs::keytype RawTower_Prototype3::towerid protected
Definition at line 59 of file RawTower_Prototype3.h.
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), RawTower_Prototype3(), and set_id().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype3/RawTower_Prototype3.h
prototype/blob/master/offline/packages/Prototype3/RawTower_Prototype3.cc