Analysis Software: PgPostCalBankIterator::ValPeriod Class Reference
PgPostCalBankIterator::ValPeriod Class Reference
Public Member Functions
ValPeriod (const PHTimeStamp &min=PHTimeStamp(0), const PHTimeStamp &max=PHTimeStamp::PHFarFuture)
time_t start () const
time_t end () const
Private Attributes
PHTimeStamp start_
PHTimeStamp end_
Detailed Description
Definition at line 48 of file PgPostCalBankIterator.h.
Constructor & Destructor Documentation
PgPostCalBankIterator::ValPeriod::ValPeriod (const PHTimeStamp & min = PHTimeStamp(0), const PHTimeStamp & max = PHTimeStamp::PHFarFuture) inline
Definition at line 51 of file PgPostCalBankIterator.h.
Member Function Documentation
time_t PgPostCalBankIterator::ValPeriod::end () const inline
Definition at line 59 of file PgPostCalBankIterator.h.
References end_, and PHTimeStamp::getTics().
Referenced by PgPostCalBankIterator::next().
time_t PgPostCalBankIterator::ValPeriod::start () const inline
Definition at line 58 of file PgPostCalBankIterator.h.
References PHTimeStamp::getTics(), and start_.
Referenced by PgPostCalBankIterator::next().
Member Data Documentation
PHTimeStamp PgPostCalBankIterator::ValPeriod::end_ private
Definition at line 63 of file PgPostCalBankIterator.h.
Referenced by end().
PHTimeStamp PgPostCalBankIterator::ValPeriod::start_ private
Definition at line 62 of file PgPostCalBankIterator.h.
Referenced by start().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostCalBankIterator.h