Analysis Software: TreeMaker Class Reference
TreeMaker Class Reference
#include <analysis/blob/master/TreeMaker/TreeMaker.h>
Public Member Functions
TreeMaker (const std::string &name="TreeMaker.root")
~TreeMaker ()
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
int CreateNode (PHCompositeNode *)
int InitializeTree ()
int InitializeCounters ()
int GetTruthJets (PHCompositeNode *)
int GetRecoJets (PHCompositeNode *)
int GetClusters (PHCompositeNode *)
int CopyAndMakeJets (PHCompositeNode *)
int CopyAndMakeClusters (PHCompositeNode *)
int UseFastJet (PHCompositeNode *)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
TFile * outfile
TTree * tree
std::string foutname
int b_tower_n
int b_tower_layer [10000]
float b_tower_e [10000]
float b_tower_eta [10000]
float b_tower_phi [10000]
float b_tower_total_0
float b_tower_total_1
float b_tower_total_2
int b_jet5_n
float b_jet5_e [200]
float b_jet5_pt [200]
float b_jet5_eta [200]
float b_jet5_phi [200]
int b_jet4_n
float b_jet4_e [200]
float b_jet4_pt [200]
float b_jet4_eta [200]
float b_jet4_phi [200]
int b_jet3_n
float b_jet3_e [200]
float b_jet3_pt [200]
float b_jet3_eta [200]
float b_jet3_phi [200]
int b_jet2_n
float b_jet2_e [200]
float b_jet2_pt [200]
float b_jet2_eta [200]
float b_jet2_phi [200]
int b_modjet2_n
float b_modjet2_e [200]
float b_modjet2_pt [200]
float b_modjet2_eta [200]
float b_modjet2_phi [200]
int b_truthjet5_n
float b_truthjet5_e [200]
float b_truthjet5_pt [200]
float b_truthjet5_eta [200]
float b_truthjet5_phi [200]
int b_truthjet4_n
float b_truthjet4_e [200]
float b_truthjet4_pt [200]
float b_truthjet4_eta [200]
float b_truthjet4_phi [200]
int b_truthjet3_n
float b_truthjet3_e [200]
float b_truthjet3_pt [200]
float b_truthjet3_eta [200]
float b_truthjet3_phi [200]
int b_truthjet2_n
float b_truthjet2_e [200]
float b_truthjet2_pt [200]
float b_truthjet2_eta [200]
float b_truthjet2_phi [200]
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 12 of file TreeMaker.h.
Constructor & Destructor Documentation
TreeMaker::TreeMaker (const std::string & name = "TreeMaker.root")
Definition at line 16 of file TreeMaker.C.
References foutname, and name.
TreeMaker::~TreeMaker ()
Definition at line 23 of file TreeMaker.C.
Member Function Documentation
int TreeMaker::CopyAndMakeClusters (PHCompositeNode * topNode)
Definition at line 22 of file TreeMakerCopyAndMakeClusters.C.
References RawClusterContainer::AddCluster(), energy, RawCluster::get_chi2(), RawCluster::get_ecore(), RawCluster::get_energy(), RawCluster::get_id(), RawCluster::get_phi(), RawCluster::get_prob(), RawCluster::get_r(), RawCluster::get_z(), RawClusterContainer::getClusters(), phi, r, RawCluster::set_chi2(), RawCluster::set_ecore(), RawCluster::set_energy(), RawCluster::set_id(), RawCluster::set_phi(), RawCluster::set_prob(), RawCluster::set_r(), RawCluster::set_z(), RawClusterContainer::size(), verbosity, and z.
Referenced by process_event().
int TreeMaker::CopyAndMakeJets (PHCompositeNode * topNode)
Definition at line 23 of file TreeMakerCopyAndMakeJets.C.
References Jet::begin_comp(), Jet::end_comp(), Jet::get_e(), RawTower::get_energy(), Jet::get_eta(), RawTowerGeom::get_eta(), RawTower::get_key(), Jet::get_phi(), RawTowerGeom::get_phi(), Jet::get_pt(), Jet::get_px(), Jet::get_py(), Jet::get_pz(), RawTowerContainer::getTower(), Jet::set_e(), Jet::set_id(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), JetMap::size(), and verbosity.
Referenced by process_event().
int TreeMaker::CreateNode (PHCompositeNode * topNode)
Definition at line 23 of file TreeMakerCreateNode.C.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int TreeMaker::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 78 of file TreeMaker.C.
References outfile.
int TreeMaker::GetClusters (PHCompositeNode * topNode)
Definition at line 22 of file TreeMakerGetClusters.C.
References energy, RawCluster::get_energy(), RawClusterContainer::getClusters(), and verbosity.
Referenced by process_event().
int TreeMaker::GetRecoJets (PHCompositeNode * topNode)
Definition at line 98 of file TreeMakerGetJets.C.
References b_jet2_e, b_jet2_eta, b_jet2_n, b_jet2_phi, b_jet2_pt, b_jet3_e, b_jet3_eta, b_jet3_n, b_jet3_phi, b_jet3_pt, b_jet4_e, b_jet4_eta, b_jet4_n, b_jet4_phi, b_jet4_pt, b_jet5_e, b_jet5_eta, b_jet5_n, b_jet5_phi, b_jet5_pt, b_modjet2_e, b_modjet2_eta, b_modjet2_n, b_modjet2_phi, b_modjet2_pt, JetMap::begin(), JetMap::end(), Jet::get_e(), Jet::get_eta(), Jet::get_phi(), and Jet::get_pt().
Referenced by process_event().
int TreeMaker::GetTruthJets (PHCompositeNode * topNode)
Definition at line 13 of file TreeMakerGetJets.C.
References b_truthjet2_e, b_truthjet2_eta, b_truthjet2_n, b_truthjet2_phi, b_truthjet2_pt, b_truthjet3_e, b_truthjet3_eta, b_truthjet3_n, b_truthjet3_phi, b_truthjet3_pt, b_truthjet4_e, b_truthjet4_eta, b_truthjet4_n, b_truthjet4_phi, b_truthjet4_pt, b_truthjet5_e, b_truthjet5_eta, b_truthjet5_n, b_truthjet5_phi, b_truthjet5_pt, JetMap::begin(), JetMap::end(), Jet::get_e(), Jet::get_eta(), Jet::get_phi(), and Jet::get_pt().
Referenced by process_event().
int TreeMaker::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 29 of file TreeMaker.C.
References foutname, InitializeTree(), and outfile.
int TreeMaker::InitializeCounters ()
Definition at line 71 of file TreeMakerInitializations.C.
References b_jet2_n, b_jet3_n, b_jet4_n, b_jet5_n, b_modjet2_n, b_tower_n, b_tower_total_0, b_tower_total_1, b_tower_total_2, b_truthjet2_n, b_truthjet3_n, b_truthjet4_n, and b_truthjet5_n.
Referenced by process_event().
int TreeMaker::InitializeTree (void)
Definition at line 6 of file TreeMakerInitializations.C.
References b_jet2_e, b_jet2_eta, b_jet2_n, b_jet2_phi, b_jet2_pt, b_jet3_e, b_jet3_eta, b_jet3_n, b_jet3_phi, b_jet3_pt, b_jet4_e, b_jet4_eta, b_jet4_n, b_jet4_phi, b_jet4_pt, b_jet5_e, b_jet5_eta, b_jet5_n, b_jet5_phi, b_jet5_pt, b_modjet2_e, b_modjet2_eta, b_modjet2_n, b_modjet2_phi, b_modjet2_pt, b_truthjet2_e, b_truthjet2_eta, b_truthjet2_n, b_truthjet2_phi, b_truthjet2_pt, b_truthjet3_e, b_truthjet3_eta, b_truthjet3_n, b_truthjet3_phi, b_truthjet3_pt, b_truthjet4_e, b_truthjet4_eta, b_truthjet4_n, b_truthjet4_phi, b_truthjet4_pt, b_truthjet5_e, b_truthjet5_eta, b_truthjet5_n, b_truthjet5_phi, b_truthjet5_pt, and tree.
Referenced by Init().
int TreeMaker::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 38 of file TreeMaker.C.
References CreateNode().
int TreeMaker::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 48 of file TreeMaker.C.
References CopyAndMakeClusters(), CopyAndMakeJets(), GetClusters(), GetRecoJets(), GetTruthJets(), InitializeCounters(), tree, and UseFastJet().
int TreeMaker::UseFastJet (PHCompositeNode * topNode)
Definition at line 34 of file TreeMakerUseFastJet.C.
References RawCluster::get_energy(), RawCluster::get_phi(), RawCluster::get_r(), RawCluster::get_z(), RawClusterContainer::getClusters(), phi, r, verbosity, and z.
Referenced by process_event().
Member Data Documentation
float TreeMaker::b_jet2_e[200] private
Definition at line 73 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet2_eta[200] private
Definition at line 75 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
int TreeMaker::b_jet2_n private
Definition at line 72 of file TreeMaker.h.
Referenced by GetRecoJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_jet2_phi[200] private
Definition at line 76 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet2_pt[200] private
Definition at line 74 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet3_e[200] private
Definition at line 67 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet3_eta[200] private
Definition at line 69 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
int TreeMaker::b_jet3_n private
Definition at line 66 of file TreeMaker.h.
Referenced by GetRecoJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_jet3_phi[200] private
Definition at line 70 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet3_pt[200] private
Definition at line 68 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet4_e[200] private
Definition at line 61 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet4_eta[200] private
Definition at line 63 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
int TreeMaker::b_jet4_n private
Definition at line 60 of file TreeMaker.h.
Referenced by GetRecoJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_jet4_phi[200] private
Definition at line 64 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet4_pt[200] private
Definition at line 62 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet5_e[200] private
Definition at line 55 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet5_eta[200] private
Definition at line 57 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
int TreeMaker::b_jet5_n private
Definition at line 54 of file TreeMaker.h.
Referenced by GetRecoJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_jet5_phi[200] private
Definition at line 58 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_jet5_pt[200] private
Definition at line 56 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_modjet2_e[200] private
Definition at line 79 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_modjet2_eta[200] private
Definition at line 81 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
int TreeMaker::b_modjet2_n private
Definition at line 78 of file TreeMaker.h.
Referenced by GetRecoJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_modjet2_phi[200] private
Definition at line 82 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_modjet2_pt[200] private
Definition at line 80 of file TreeMaker.h.
Referenced by GetRecoJets(), and InitializeTree().
float TreeMaker::b_tower_e[10000] private
Definition at line 46 of file TreeMaker.h.
float TreeMaker::b_tower_eta[10000] private
Definition at line 47 of file TreeMaker.h.
int TreeMaker::b_tower_layer[10000] private
Definition at line 45 of file TreeMaker.h.
int TreeMaker::b_tower_n private
Definition at line 44 of file TreeMaker.h.
Referenced by InitializeCounters().
float TreeMaker::b_tower_phi[10000] private
Definition at line 48 of file TreeMaker.h.
float TreeMaker::b_tower_total_0 private
Definition at line 50 of file TreeMaker.h.
Referenced by InitializeCounters().
float TreeMaker::b_tower_total_1 private
Definition at line 51 of file TreeMaker.h.
Referenced by InitializeCounters().
float TreeMaker::b_tower_total_2 private
Definition at line 52 of file TreeMaker.h.
Referenced by InitializeCounters().
float TreeMaker::b_truthjet2_e[200] private
Definition at line 103 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet2_eta[200] private
Definition at line 105 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
int TreeMaker::b_truthjet2_n private
Definition at line 102 of file TreeMaker.h.
Referenced by GetTruthJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_truthjet2_phi[200] private
Definition at line 106 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet2_pt[200] private
Definition at line 104 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet3_e[200] private
Definition at line 97 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet3_eta[200] private
Definition at line 99 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
int TreeMaker::b_truthjet3_n private
Definition at line 96 of file TreeMaker.h.
Referenced by GetTruthJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_truthjet3_phi[200] private
Definition at line 100 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet3_pt[200] private
Definition at line 98 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet4_e[200] private
Definition at line 91 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet4_eta[200] private
Definition at line 93 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
int TreeMaker::b_truthjet4_n private
Definition at line 90 of file TreeMaker.h.
Referenced by GetTruthJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_truthjet4_phi[200] private
Definition at line 94 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet4_pt[200] private
Definition at line 92 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet5_e[200] private
Definition at line 85 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet5_eta[200] private
Definition at line 87 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
int TreeMaker::b_truthjet5_n private
Definition at line 84 of file TreeMaker.h.
Referenced by GetTruthJets(), InitializeCounters(), and InitializeTree().
float TreeMaker::b_truthjet5_phi[200] private
Definition at line 88 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
float TreeMaker::b_truthjet5_pt[200] private
Definition at line 86 of file TreeMaker.h.
Referenced by GetTruthJets(), and InitializeTree().
std::string TreeMaker::foutname private
Definition at line 42 of file TreeMaker.h.
Referenced by Init(), and TreeMaker().
TFile* TreeMaker::outfile private
Definition at line 38 of file TreeMaker.h.
Referenced by End(), and Init().
TTree* TreeMaker::tree private
Definition at line 40 of file TreeMaker.h.
Referenced by InitializeTree(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/TreeMaker/TreeMaker.h
analysis/blob/master/TreeMaker/TreeMaker.C
analysis/blob/master/TreeMaker/TreeMakerCopyAndMakeClusters.C
analysis/blob/master/TreeMaker/TreeMakerCopyAndMakeJets.C
analysis/blob/master/TreeMaker/TreeMakerCreateNode.C
analysis/blob/master/TreeMaker/TreeMakerGetClusters.C
analysis/blob/master/TreeMaker/TreeMakerGetJets.C
analysis/blob/master/TreeMaker/TreeMakerInitializations.C
analysis/blob/master/TreeMaker/TreeMakerUseFastJet.C