Analysis Software: online_distribution/blob/master/newbasic/dpipe.cc File Reference
dpipe.cc File Reference
#include <stdlib.h>
#include <signal.h>
#include <dlfcn.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include "fileEventiterator.h"
#include "testEventiterator.h"
#include "listEventiterator.h"
#include "rcdaqEventiterator.h"
#include "ogzBuffer.h"
#include "olzoBuffer.h"
#include "oamlBuffer.h"
#include "oBuffer.h"
#include "dpipe_filter.h"
#include "phenixTypes.h"
#include "oEvent.h"
#include "stdio.h"
#include "EventTypes.h"
Macros
#define RCDAQEVENTITERATOR 1
#define FILEEVENTITERATOR 2
#define TESTEVENTITERATOR 3
#define ETPOOL 4
#define DFILE 5
#define DNULL 6
#define LISTEVENTITERATOR 7
#define OAML 8
Functions
void sig_handler (...)
void exitmsg ()
void evtcountexitmsg ()
void compressionexitmsg ()
void exithelp ()
void dpipe_register (DpipeFilter *T)
void dpipe_unregister (DpipeFilter *T)
int main (int argc, char *argv[])
Variables
Eventiterator * it
char * sharedlib
int load_lib = 0
DpipeFilter * filter = 0
Macro Definition Documentation
#define DFILE 5
Definition at line 32 of file dpipe.cc.
Referenced by main().
#define DNULL 6
Definition at line 33 of file dpipe.cc.
Referenced by main().
#define ETPOOL 4
Definition at line 31 of file dpipe.cc.
Referenced by main().
#define FILEEVENTITERATOR 2
Definition at line 29 of file dpipe.cc.
Referenced by main().
#define LISTEVENTITERATOR 7
Definition at line 34 of file dpipe.cc.
Referenced by main().
#define OAML 8
Definition at line 35 of file dpipe.cc.
Referenced by main().
#define RCDAQEVENTITERATOR 1
Definition at line 28 of file dpipe.cc.
Referenced by main().
#define TESTEVENTITERATOR 3
Definition at line 30 of file dpipe.cc.
Referenced by main().
Function Documentation
void compressionexitmsg ()
Definition at line 61 of file dpipe.cc.
References COUT.
Referenced by main().
void dpipe_register (DpipeFilter * T)
Definition at line 129 of file dpipe.cc.
References filter, and T.
Referenced by DpipeFilter::DpipeFilter().
void dpipe_unregister (DpipeFilter * T)
Definition at line 136 of file dpipe.cc.
Referenced by DpipeFilter::~DpipeFilter().
void evtcountexitmsg ()
Definition at line 54 of file dpipe.cc.
References COUT.
void exithelp ()
Definition at line 68 of file dpipe.cc.
References COUT.
void exitmsg ()
Definition at line 47 of file dpipe.cc.
References COUT.
int main (int argc, char * argv[])
Definition at line 149 of file dpipe.cc.
References oBuffer::addEvent(), c, compressionexitmsg(), COUT, DFILE, DNULL, ETPOOL, evtcountexitmsg(), exithelp(), exitmsg(), fd, FILEEVENTITERATOR, Event::getEvtSequence(), Eventiterator::getNextEvent(), Event::identify(), DpipeFilter::idString(), it, LISTEVENTITERATOR, load_lib, OAML, ob, RCDAQEVENTITERATOR, DpipeFilter::select(), Eventiterator::setVerbosity(), sharedlib, sig_handler(), signal(), and TESTEVENTITERATOR.
void sig_handler (...)
Definition at line 245 of file changehitformat.cc.
References COUT, and it.
Variable Documentation
DpipeFilter* filter = 0
Definition at line 125 of file dpipe.cc.
Referenced by dpipe_register().
Eventiterator* it
Definition at line 119 of file dpipe.cc.
int load_lib = 0
Definition at line 123 of file dpipe.cc.
Referenced by main().
char* sharedlib
Definition at line 122 of file dpipe.cc.
Referenced by main().