Analysis Software: HFMLTriggerOccupancy Class Reference
HFMLTriggerOccupancy Class Reference
#include <analysis/blob/master/HF-Jet/HFMLTrigger/HFMLTriggerOccupancy.h>
Public Member Functions
HFMLTriggerOccupancy (std::string filename)
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
double get_eta_max () const
void set_eta_max (double etaMax)
double get_eta_min () const
void set_eta_min (double etaMin)
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { kNCHip = 9 }
Private Attributes
int _ievent
TFile * _f
std::fstream m_jsonOut
std::string _foutname
double _eta_min
double _eta_max
int _embedding_id
unsigned int _nlayers_maps
SvtxEvalStack * _svtxevalstack
SvtxHitMap * m_hitMap
PHG4CylinderGeomContainer * m_Geoms
PHG4TruthInfoContainer * m_truthInfo
PdbParameterMap * m_Flags
TH1F * m_hNorm
TH1F * m_hNChEta
TH1F * m_hVertexZ
TH2F * m_hitStaveLayer
TH2F * m_hitModuleHalfStave
TH2F * m_hitChipModule
TH3F * m_hitLayerMap
TH3F * m_hitPixelPhiMap
TH3F * m_hitPixelPhiMapHL
TH3F * m_hitPixelZMap
TH1F * m_Multiplicity
TH2F * m_LayerMultiplicity
TH3F * m_LayerChipMultiplicity
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 30 of file HFMLTriggerOccupancy.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
kNCHip
Definition at line 96 of file HFMLTriggerOccupancy.h.
Constructor & Destructor Documentation
HFMLTriggerOccupancy::HFMLTriggerOccupancy (std::string filename)
Definition at line 68 of file HFMLTriggerOccupancy.C.
References _foutname, and filename.
Member Function Documentation
int HFMLTriggerOccupancy::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 429 of file HFMLTriggerOccupancy.C.
References _f, _foutname, and Fun4AllReturnCodes::EVENT_OK.
int HFMLTriggerOccupancy::get_embedding_id () const inline
The embedding ID for the HepMC subevent to be analyzed. embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 69 of file HFMLTriggerOccupancy.h.
References _embedding_id.
double HFMLTriggerOccupancy::get_eta_max () const inline
Definition at line 41 of file HFMLTriggerOccupancy.h.
References _eta_max.
double HFMLTriggerOccupancy::get_eta_min () const inline
Definition at line 53 of file HFMLTriggerOccupancy.h.
References _eta_min.
int HFMLTriggerOccupancy::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 98 of file HFMLTriggerOccupancy.C.
References _f, _foutname, _ievent, Fun4AllReturnCodes::EVENT_OK, i, kNCHip, m_hitChipModule, m_hitLayerMap, m_hitModuleHalfStave, m_hitStaveLayer, m_hNChEta, m_hNorm, m_hVertexZ, m_LayerChipMultiplicity, m_LayerMultiplicity, and m_Multiplicity.
int HFMLTriggerOccupancy::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 157 of file HFMLTriggerOccupancy.C.
References Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, m_Flags, m_Geoms, m_hitMap, m_truthInfo, and PHWHERE.
int HFMLTriggerOccupancy::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 189 of file HFMLTriggerOccupancy.C.
References _ievent, _nlayers_maps, _svtxevalstack, assert, SvtxHitMap::begin(), SvtxHitMap::end(), Fun4AllReturnCodes::EVENT_OK, PHG4Cell::get_chip_index(), PHG4Cell::get_half_stave_index(), SvtxEvalStack::get_hit_eval(), SvtxHit::get_id(), SvtxHit::get_layer(), PHG4Cell::get_module_index(), PHG4Particle::get_pid(), PHG4Cell::get_pixel_index(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Cell::get_stave_index(), PHG4VtxPoint::get_z(), PHG4CylinderGeomContainer::GetLayerGeom(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), kNCHip, m_Geoms, m_hitChipModule, m_hitLayerMap, m_hitMap, m_hitModuleHalfStave, m_hitStaveLayer, m_hNChEta, m_hNorm, m_hVertexZ, m_LayerChipMultiplicity, m_LayerMultiplicity, m_Multiplicity, m_truthInfo, SvtxEvalStack::next_event(), SvtxEvalStack::set_strict(), SvtxEvalStack::set_verbosity(), and Fun4AllBase::Verbosity().
void HFMLTriggerOccupancy::set_embedding_id (int id) inline
The embedding ID for the HepMC subevent to be analyzed. embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 76 of file HFMLTriggerOccupancy.h.
References _embedding_id.
void HFMLTriggerOccupancy::set_eta_max (double etaMax) inline
Definition at line 47 of file HFMLTriggerOccupancy.h.
References _eta_max.
void HFMLTriggerOccupancy::set_eta_min (double etaMin) inline
Definition at line 59 of file HFMLTriggerOccupancy.h.
References _eta_min.
Member Data Documentation
int HFMLTriggerOccupancy::_embedding_id private
The embedding ID for the HepMC subevent to be analyzed. positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 93 of file HFMLTriggerOccupancy.h.
Referenced by get_embedding_id(), and set_embedding_id().
double HFMLTriggerOccupancy::_eta_max private
Definition at line 87 of file HFMLTriggerOccupancy.h.
Referenced by get_eta_max(), and set_eta_max().
double HFMLTriggerOccupancy::_eta_min private
Definition at line 86 of file HFMLTriggerOccupancy.h.
Referenced by get_eta_min(), and set_eta_min().
TFile* HFMLTriggerOccupancy::_f private
Definition at line 81 of file HFMLTriggerOccupancy.h.
Referenced by End(), and Init().
std::string HFMLTriggerOccupancy::_foutname private
Definition at line 84 of file HFMLTriggerOccupancy.h.
Referenced by End(), HFMLTriggerOccupancy(), and Init().
int HFMLTriggerOccupancy::_ievent private
Definition at line 79 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
unsigned int HFMLTriggerOccupancy::_nlayers_maps private
Definition at line 95 of file HFMLTriggerOccupancy.h.
Referenced by process_event().
SvtxEvalStack* HFMLTriggerOccupancy::_svtxevalstack private
Definition at line 99 of file HFMLTriggerOccupancy.h.
Referenced by process_event().
PdbParameterMap* HFMLTriggerOccupancy::m_Flags private
Definition at line 103 of file HFMLTriggerOccupancy.h.
Referenced by InitRun().
PHG4CylinderGeomContainer* HFMLTriggerOccupancy::m_Geoms private
Definition at line 101 of file HFMLTriggerOccupancy.h.
Referenced by InitRun(), and process_event().
TH2F* HFMLTriggerOccupancy::m_hitChipModule private
Definition at line 111 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH3F* HFMLTriggerOccupancy::m_hitLayerMap private
Definition at line 113 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
SvtxHitMap* HFMLTriggerOccupancy::m_hitMap private
Definition at line 100 of file HFMLTriggerOccupancy.h.
Referenced by InitRun(), and process_event().
TH2F* HFMLTriggerOccupancy::m_hitModuleHalfStave private
Definition at line 110 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH3F* HFMLTriggerOccupancy::m_hitPixelPhiMap private
Definition at line 114 of file HFMLTriggerOccupancy.h.
TH3F* HFMLTriggerOccupancy::m_hitPixelPhiMapHL private
Definition at line 115 of file HFMLTriggerOccupancy.h.
TH3F* HFMLTriggerOccupancy::m_hitPixelZMap private
Definition at line 116 of file HFMLTriggerOccupancy.h.
TH2F* HFMLTriggerOccupancy::m_hitStaveLayer private
Definition at line 109 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH1F* HFMLTriggerOccupancy::m_hNChEta private
Definition at line 106 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH1F* HFMLTriggerOccupancy::m_hNorm private
Definition at line 105 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH1F* HFMLTriggerOccupancy::m_hVertexZ private
Definition at line 107 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
std::fstream HFMLTriggerOccupancy::m_jsonOut private
Definition at line 82 of file HFMLTriggerOccupancy.h.
TH3F* HFMLTriggerOccupancy::m_LayerChipMultiplicity private
Definition at line 120 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH2F* HFMLTriggerOccupancy::m_LayerMultiplicity private
Definition at line 119 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
TH1F* HFMLTriggerOccupancy::m_Multiplicity private
Definition at line 118 of file HFMLTriggerOccupancy.h.
Referenced by Init(), and process_event().
PHG4TruthInfoContainer* HFMLTriggerOccupancy::m_truthInfo private
Definition at line 102 of file HFMLTriggerOccupancy.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/HF-Jet/HFMLTrigger/HFMLTriggerOccupancy.h
analysis/blob/master/HF-Jet/HFMLTrigger/HFMLTriggerOccupancy.C