Analysis Software: TruthJetInput Class Reference
TruthJetInput Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/TruthJetInput.h>
Public Member Functions
TruthJetInput (Jet::SRC input)
virtual ~TruthJetInput ()
void add_embedding_flag (const int embed_stream_id)
void identify (std::ostream &os=std::cout)
Jet::SRC get_src ()
std::vector< Jet * > get_input (PHCompositeNode *topNode)
void set_eta_range (float eta_min, float eta_max)
Public Member Functions inherited from JetInput
virtual ~JetInput ()
Private Member Functions
bool use_embed_stream ()
Private Attributes
int _verbosity
Jet::SRC _input
float _eta_min
float _eta_max
std::vector< int > _embed_id
Additional Inherited Members
Protected Member Functions inherited from JetInput
JetInput ()
Detailed Description
Definition at line 13 of file TruthJetInput.h.
Constructor & Destructor Documentation
TruthJetInput::TruthJetInput (Jet::SRC input)
Definition at line 24 of file TruthJetInput.cc.
virtual TruthJetInput::~TruthJetInput () inline virtual
Definition at line 17 of file TruthJetInput.h.
Member Function Documentation
void TruthJetInput::add_embedding_flag (const int embed_stream_id) inline
by default, TruthJetInput process all truth primary particle. However, it can be configured to read only one or more embedded stream via add_embedding_flag() It can be useful for reconstruct truth jet for embedded pythia jets only, etc. Call add_embedding_flag() multiple times to add multiple embed stream
Definition at line 23 of file TruthJetInput.h.
References _embed_id.
Referenced by HIJetReco(), and run_macro().
std::vector< Jet * > TruthJetInput::get_input (PHCompositeNode * topNode) virtual
Reimplemented from JetInput.
Definition at line 46 of file TruthJetInput.cc.
References _embed_id, _eta_max, _eta_min, _verbosity, PHG4Particle::get_e(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4Particle::get_track_id(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), Jet::insert_comp(), PHG4TruthInfoContainer::isEmbeded(), Jet::PARTICLE, PHWHERE, Jet::set_e(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), and use_embed_stream().
Jet::SRC TruthJetInput::get_src () inline virtual
Reimplemented from JetInput.
Definition at line 30 of file TruthJetInput.h.
References _input.
void TruthJetInput::identify (std::ostream & os = std::cout) virtual
Reimplemented from JetInput.
Definition at line 32 of file TruthJetInput.cc.
References _embed_id, it, and use_embed_stream().
void TruthJetInput::set_eta_range (float eta_min, float eta_max) inline
Definition at line 34 of file TruthJetInput.h.
References _eta_max, and _eta_min.
bool TruthJetInput::use_embed_stream () inline private
Definition at line 50 of file TruthJetInput.h.
References _embed_id.
Referenced by get_input(), and identify().
Member Data Documentation
std::vector<int> TruthJetInput::_embed_id private
if empty: process all primary particles if non-empty: only process primary particles in the selected embed stream.
Definition at line 48 of file TruthJetInput.h.
Referenced by add_embedding_flag(), get_input(), identify(), and use_embed_stream().
float TruthJetInput::_eta_max private
Definition at line 44 of file TruthJetInput.h.
Referenced by get_input(), and set_eta_range().
float TruthJetInput::_eta_min private
Definition at line 43 of file TruthJetInput.h.
Referenced by get_input(), and set_eta_range().
Jet::SRC TruthJetInput::_input private
Definition at line 42 of file TruthJetInput.h.
Referenced by get_src().
int TruthJetInput::_verbosity private
Definition at line 41 of file TruthJetInput.h.
Referenced by get_input().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/TruthJetInput.h
coresoftware/blob/master/simulation/g4simulation/g4jets/TruthJetInput.cc