Analysis Software: TrackProjectorPlaneECAL Class Reference
TrackProjectorPlaneECAL Class Reference
#include <analysis/blob/master/EICAnalysis/TrackProjectorPlaneECAL.h>
Public Types
enum PROJECTION_SURFACE { SPHERE, CYLINDER, PLANEXY, PLANE_CYLINDER }
enum PROJECTION_DETECTOR { EEMC, CEMC, FEMC }
Public Member Functions
TrackProjectorPlaneECAL (PHCompositeNode *topNode)
bool get_projected_position (SvtxTrack_FastSim *track, RawCluster *cluster, double arr_pos[3], const PROJECTION_SURFACE surf, const float surface_par)
bool get_projected_momentum (SvtxTrack_FastSim *track, RawCluster *cluster, double arr_mom[3], const PROJECTION_SURFACE surf, const float surface_par)
SvtxTrack_FastSim * get_best_track (SvtxTrackMap *trackmap, RawCluster *cluster)
SvtxTrackState * get_best_state (SvtxTrack_FastSim *track, RawCluster *cluster)
char get_detector ()
SvtxTrackState * project_track (SvtxTrack_FastSim *track, RawCluster *cluster, const PROJECTION_SURFACE surf, const float surface_par)
void set_detector (char c)
char get_detector_from_cluster (RawCluster *cluster)
Private Attributes
PHGenFit::Fitter * _fitter
enum PROJECTION_DETECTOR detector
Detailed Description
Definition at line 29 of file TrackProjectorPlaneECAL.h.
Member Enumeration Documentation
enum TrackProjectorPlaneECAL::PROJECTION_DETECTOR
Enumerator:
EEMC
CEMC
FEMC
Definition at line 34 of file TrackProjectorPlaneECAL.h.
enum TrackProjectorPlaneECAL::PROJECTION_SURFACE
Enumerator:
SPHERE
CYLINDER
PLANEXY
PLANE_CYLINDER
Definition at line 33 of file TrackProjectorPlaneECAL.h.
Constructor & Destructor Documentation
TrackProjectorPlaneECAL::TrackProjectorPlaneECAL (PHCompositeNode * topNode)
Definition at line 38 of file TrackProjectorPlaneECAL.cc.
References _fitter, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), PHWHERE, and PHGenFit::Fitter::set_verbosity().
Member Function Documentation
SvtxTrackState * TrackProjectorPlaneECAL::get_best_state (SvtxTrack_FastSim * track, RawCluster * cluster)
Definition at line 206 of file TrackProjectorPlaneECAL.cc.
References SvtxTrack_v1::begin_states(), SvtxTrack_v1::end_states(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), SvtxTrackState::get_z(), and RawCluster::get_z().
Referenced by DISKinematicsReco::InsertCandidateFromCluster().
SvtxTrack_FastSim * TrackProjectorPlaneECAL::get_best_track (SvtxTrackMap * trackmap, RawCluster * cluster)
Definition at line 109 of file TrackProjectorPlaneECAL.cc.
References SvtxTrackMap::begin(), SvtxTrack_v1::begin_states(), deltaR(), SvtxTrackMap::end(), SvtxTrack_v1::end_states(), SvtxTrackMap::get(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), SvtxTrackState::get_z(), RawCluster::get_z(), and i.
Referenced by ExclusiveReco::AddInvariantMassInformation(), and DISKinematicsReco::InsertCandidateFromCluster().
char TrackProjectorPlaneECAL::get_detector ()
Definition at line 261 of file TrackProjectorPlaneECAL.cc.
References CEMC, EEMC, and FEMC.
char TrackProjectorPlaneECAL::get_detector_from_cluster (RawCluster * cluster)
Definition at line 416 of file TrackProjectorPlaneECAL.cc.
References RawTowerDefs::convert_caloid_to_name(), RawTowerDefs::decode_caloid(), and RawCluster::get_towers().
Referenced by ExclusiveReco::AddInvariantMassInformation(), and DISKinematicsReco::InsertCandidateFromCluster().
bool TrackProjectorPlaneECAL::get_projected_momentum (SvtxTrack_FastSim * track, RawCluster * cluster, double arr_mom[3], const PROJECTION_SURFACE surf, const float surface_par)
Definition at line 81 of file TrackProjectorPlaneECAL.cc.
References project_track().
bool TrackProjectorPlaneECAL::get_projected_position (SvtxTrack_FastSim * track, RawCluster * cluster, double arr_pos[3], const PROJECTION_SURFACE surf, const float surface_par)
Definition at line 58 of file TrackProjectorPlaneECAL.cc.
References project_track().
SvtxTrackState * TrackProjectorPlaneECAL::project_track (SvtxTrack_FastSim * track, RawCluster * cluster, const PROJECTION_SURFACE surf, const float surface_par)
Definition at line 280 of file TrackProjectorPlaneECAL.cc.
References CEMC, CYLINDER, EEMC, SvtxTrack_v1::end_states(), FEMC, SvtxTrackState::get_error(), RawCluster::get_phi(), SvtxTrackState::get_px(), SvtxTrackState::get_py(), SvtxTrackState::get_pz(), SvtxTrackState::get_x(), RawCluster::get_x(), SvtxTrackState::get_y(), RawCluster::get_y(), SvtxTrackState::get_z(), RawCluster::get_z(), i, j, PLANE_CYLINDER, PLANEXY, pos, SvtxTrackState_v1::set_error(), SvtxTrackState_v1::set_px(), SvtxTrackState_v1::set_py(), SvtxTrackState_v1::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrackState_v1::set_y(), SvtxTrackState_v1::set_z(), SvtxTrack_v1::size_states(), and SPHERE.
Referenced by get_projected_momentum(), and get_projected_position().
void TrackProjectorPlaneECAL::set_detector (char c)
Definition at line 395 of file TrackProjectorPlaneECAL.cc.
References CEMC, EEMC, and FEMC.
Referenced by ExclusiveReco::AddInvariantMassInformation(), and DISKinematicsReco::InsertCandidateFromCluster().
Member Data Documentation
PHGenFit::Fitter* TrackProjectorPlaneECAL::_fitter private
Definition at line 55 of file TrackProjectorPlaneECAL.h.
Referenced by TrackProjectorPlaneECAL().
enum PROJECTION_DETECTOR TrackProjectorPlaneECAL::detector private
Definition at line 56 of file TrackProjectorPlaneECAL.h.
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/TrackProjectorPlaneECAL.h
analysis/blob/master/EICAnalysis/TrackProjectorPlaneECAL.cc