Analysis Software: PHG4SectorSubsystem Class Reference
PHG4SectorSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorSubsystem.h>
Public Member Functions
PHG4SectorSubsystem (const std::string &name="Sector")
constructor
virtual ~PHG4SectorSubsystem ()
destructor
int Init (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void SuperDetector (const std::string &name)
PHG4Sector::Sector_Geometry & get_geometry ()
geometry manager PHG4Sector::Sector_Geometry
void set_geometry (const PHG4Sector::Sector_Geometry &g)
geometry manager PHG4Sector::Sector_Geometry
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4SectorDetector * m_Detector
detector geometry
PHG4SteppingAction * m_SteppingAction
particle tracking "stepping" action
PHG4DisplayAction * m_DisplayAction
display attribute setting
std::string superdetector
PHG4Sector::Sector_Geometry geom
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 18 of file PHG4SectorSubsystem.h.
Constructor & Destructor Documentation
PHG4SectorSubsystem::PHG4SectorSubsystem (const std::string & name = "Sector")
constructor
Definition at line 25 of file PHG4SectorSubsystem.cc.
PHG4SectorSubsystem::~PHG4SectorSubsystem () virtual
destructor
Definition at line 35 of file PHG4SectorSubsystem.cc.
References m_DisplayAction.
Member Function Documentation
PHG4Sector::Sector_Geometry& PHG4SectorSubsystem::get_geometry () inline
geometry manager PHG4Sector::Sector_Geometry
Definition at line 57 of file PHG4SectorSubsystem.h.
References geom.
Referenced by AddLayers_MiniTPCDrift(), AerogelSetup(), DIRCSetup(), FGEMSetup(), and make_GEM_station().
PHG4Detector * PHG4SectorSubsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 93 of file PHG4SectorSubsystem.cc.
References m_Detector.
PHG4DisplayAction* PHG4SectorSubsystem::GetDisplayAction () const inline virtual
return pointer to this subsystem display setting
Reimplemented from PHG4Subsystem.
Definition at line 47 of file PHG4SectorSubsystem.h.
References m_DisplayAction.
virtual PHG4SteppingAction* PHG4SectorSubsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 45 of file PHG4SectorSubsystem.h.
References m_SteppingAction.
int PHG4SectorSubsystem::Init (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from SubsysReco.
Definition at line 41 of file PHG4SectorSubsystem.cc.
References PHCompositeNode::addNode(), PHG4Subsystem::CheckOverlap(), PHNodeIterator::findFirst(), geom, PHG4Sector::PHG4SectorConstructor::geom, PHG4Sector::Sector_Geometry::GetNumActiveLayers(), m_Detector, m_DisplayAction, m_SteppingAction, Fun4AllBase::Name(), PHG4SectorDetector::OverlapCheck(), PHG4SectorDetector::SuperDetector(), superdetector, and PHG4Detector::topNode().
int PHG4SectorSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 80 of file PHG4SectorSubsystem.cc.
References m_SteppingAction, and PHG4SteppingAction::SetInterfacePointers().
void PHG4SectorSubsystem::set_geometry (const PHG4Sector::Sector_Geometry & g) inline
geometry manager PHG4Sector::Sector_Geometry
Definition at line 64 of file PHG4SectorSubsystem.h.
References g, and geom.
void PHG4SectorSubsystem::SuperDetector (const std::string & name) inline
Definition at line 50 of file PHG4SectorSubsystem.h.
References name, and superdetector.
Referenced by FGEMSetup(), and make_GEM_station().
Member Data Documentation
PHG4Sector::Sector_Geometry PHG4SectorSubsystem::geom private
Definition at line 84 of file PHG4SectorSubsystem.h.
Referenced by get_geometry(), Init(), and set_geometry().
PHG4SectorDetector* PHG4SectorSubsystem::m_Detector private
detector geometry
defives from PHG4Detector
Definition at line 72 of file PHG4SectorSubsystem.h.
Referenced by GetDetector(), and Init().
PHG4DisplayAction* PHG4SectorSubsystem::m_DisplayAction private
display attribute setting
derives from PHG4DisplayAction
Definition at line 80 of file PHG4SectorSubsystem.h.
Referenced by GetDisplayAction(), Init(), and ~PHG4SectorSubsystem().
PHG4SteppingAction* PHG4SectorSubsystem::m_SteppingAction private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 76 of file PHG4SectorSubsystem.h.
Referenced by GetSteppingAction(), Init(), and process_event().
std::string PHG4SectorSubsystem::superdetector private
Definition at line 82 of file PHG4SectorSubsystem.h.
Referenced by Init(), and SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorSubsystem.cc