Analysis Software: coresoftware/blob/master/generators/hijing/examples/example_6.f File Reference
example_6.f File Reference
Functions/Subroutines
program __example_6.f__
function ran (NSEED)
Function/Subroutine Documentation
program __example_6.f__ ()
Definition at line 8 of file example_6.f.
References c2, HiMain1::eatt(), efrm, go(), hijing(), hijset(), HiParnt::hint1(), HiParnt::hipr1(), i, iap, iat, HiParnt::ihnt2(), HiParnt::ihpr2(), izp, izt, HiMain1::jatt(), HiMain2::katt(), luchge(), min, HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HiMain1::np(), RanSeed::nseed(), HiMain1::nt(), HiMain2::patt(), phi, pi, HiStrng::pt(), ulangl(), ulmass(), and y.
function ran (NSEED)
Definition at line 525 of file example_6.f.
References RanSeed::nseed(), ran(), and rlu().