Analysis Software: tileTree Class Reference
tileTree Class Reference
#include <analysis/blob/master/Prototype2/hcalLab/hcalUtil.h>
Public Member Functions
void updateRootFile ()
Static Public Member Functions
static tileTree * getInstance ()
static void deleteInstance ()
Public Attributes
int rejectCode
Protected Member Functions
tileTree ()
virtual ~tileTree ()
Static Protected Attributes
static tileTree * single = 0
Detailed Description
Definition at line 637 of file hcalUtil.h.
Constructor & Destructor Documentation
tileTree::tileTree () protected
Definition at line 5 of file tileTree.C.
References ACTIVECHANNELS, hLabHelper::adc, hLabHelper::eventseq, hLabHelper::getInstance(), NSAMPLES, hLabHelper::runnumber, and hLabHelper::thcl.
Referenced by getInstance().
virtual tileTree::~tileTree () inline protected virtual
Definition at line 642 of file hcalUtil.h.
Member Function Documentation
static void tileTree::deleteInstance () inline static
Definition at line 648 of file hcalUtil.h.
References single.
static tileTree* tileTree::getInstance () inline static
Definition at line 647 of file hcalUtil.h.
References single, and tileTree().
Referenced by tileHelper::evLoop().
void tileTree::updateRootFile ()
Definition at line 107 of file tileTree.C.
References hLabHelper::getInstance(), and hLabHelper::thcl.
Member Data Documentation
int tileTree::rejectCode
Definition at line 662 of file hcalUtil.h.
tileTree * tileTree::single = 0 static protected
Definition at line 643 of file hcalUtil.h.
Referenced by deleteInstance(), and getInstance().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype2/hcalLab/hcalUtil.h
analysis/blob/master/Prototype2/hcalLab/hcalUtil.C
analysis/blob/master/Prototype2/hcalLab/tileTree.C