Analysis Software: PHG4ScintillatorSlatv1 Class Reference
PHG4ScintillatorSlatv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h>
Public Member Functions
PHG4ScintillatorSlatv1 ()
virtual ~PHG4ScintillatorSlatv1 ()
void identify (std::ostream &os=std::cout) const
void add_edep (const double f, const double e, const double ly)
void add_hit_key (PHG4HitDefs::keytype key)
void set_key (PHG4ScintillatorSlatDefs::keytype i)
void set_light_yield (const double lightYield)
short get_row () const
short get_column () const
PHG4ScintillatorSlatDefs::keytype get_key () const
double get_edep () const
double get_eion () const
double get_light_yield () const
std::pair< std::set
< PHG4HitDefs::keytype >
::const_iterator, std::set
< PHG4HitDefs::keytype >
::const_iterator > get_hit_ids () const
Public Member Functions inherited from PHG4ScintillatorSlat
virtual ~PHG4ScintillatorSlat ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
PHG4ScintillatorSlatDefs::keytype key
double edep
double eion
double light_yield
std::set< PHG4HitDefs::keytype > hit_id
Additional Inherited Members
Protected Member Functions inherited from PHG4ScintillatorSlat
PHG4ScintillatorSlat ()
Detailed Description
Definition at line 16 of file PHG4ScintillatorSlatv1.h.
Constructor & Destructor Documentation
PHG4ScintillatorSlatv1::PHG4ScintillatorSlatv1 ()
Definition at line 7 of file PHG4ScintillatorSlatv1.cc.
virtual PHG4ScintillatorSlatv1::~PHG4ScintillatorSlatv1 () inline virtual
Definition at line 21 of file PHG4ScintillatorSlatv1.h.
Member Function Documentation
void PHG4ScintillatorSlatv1::add_edep (const double f, const double e, const double ly) inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 25 of file PHG4ScintillatorSlatv1.h.
References edep, eion, and light_yield.
void PHG4ScintillatorSlatv1::add_hit_key (PHG4HitDefs::keytype key) inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 26 of file PHG4ScintillatorSlatv1.h.
References hit_id.
short PHG4ScintillatorSlatv1::get_column () const virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 21 of file PHG4ScintillatorSlatv1.cc.
References key.
Referenced by identify().
double PHG4ScintillatorSlatv1::get_edep () const inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 34 of file PHG4ScintillatorSlatv1.h.
References edep.
Referenced by identify().
double PHG4ScintillatorSlatv1::get_eion () const inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 35 of file PHG4ScintillatorSlatv1.h.
References eion.
Referenced by identify().
std::pair<std::set<PHG4HitDefs::keytype>::const_iterator, std::set<PHG4HitDefs::keytype>::const_iterator> PHG4ScintillatorSlatv1::get_hit_ids () const inline virtual
Implements PHG4ScintillatorSlat.
Definition at line 37 of file PHG4ScintillatorSlatv1.h.
References hit_id.
PHG4ScintillatorSlatDefs::keytype PHG4ScintillatorSlatv1::get_key () const inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 33 of file PHG4ScintillatorSlatv1.h.
References key.
double PHG4ScintillatorSlatv1::get_light_yield () const inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 36 of file PHG4ScintillatorSlatv1.h.
References light_yield.
Referenced by identify().
short PHG4ScintillatorSlatv1::get_row () const virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 15 of file PHG4ScintillatorSlatv1.cc.
References key.
Referenced by identify().
void PHG4ScintillatorSlatv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4ScintillatorSlat.
Definition at line 27 of file PHG4ScintillatorSlatv1.cc.
References get_column(), get_edep(), get_eion(), get_light_yield(), and get_row().
void PHG4ScintillatorSlatv1::set_key (PHG4ScintillatorSlatDefs::keytype i) inline virtual
Reimplemented from PHG4ScintillatorSlat.
Definition at line 28 of file PHG4ScintillatorSlatv1.h.
References i, and key.
void PHG4ScintillatorSlatv1::set_light_yield (const double lightYield) inline
Definition at line 29 of file PHG4ScintillatorSlatv1.h.
References light_yield.
Member Data Documentation
double PHG4ScintillatorSlatv1::edep protected
Definition at line 42 of file PHG4ScintillatorSlatv1.h.
Referenced by add_edep(), and get_edep().
double PHG4ScintillatorSlatv1::eion protected
Definition at line 43 of file PHG4ScintillatorSlatv1.h.
Referenced by add_edep(), and get_eion().
std::set<PHG4HitDefs::keytype> PHG4ScintillatorSlatv1::hit_id protected
Definition at line 45 of file PHG4ScintillatorSlatv1.h.
Referenced by add_hit_key(), and get_hit_ids().
PHG4ScintillatorSlatDefs::keytype PHG4ScintillatorSlatv1::key protected
Definition at line 41 of file PHG4ScintillatorSlatv1.h.
Referenced by get_column(), get_key(), get_row(), and set_key().
double PHG4ScintillatorSlatv1::light_yield protected
Definition at line 44 of file PHG4ScintillatorSlatv1.h.
Referenced by add_edep(), get_light_yield(), and set_light_yield().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.cc