Analysis Software: SvtxClusterMap Class Reference
SvtxClusterMap Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxClusterMap.h>
Public Types
typedef std::map< unsigned int,
SvtxCluster * > ClusterMap
typedef std::map< unsigned int,
SvtxCluster * >
::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxCluster * >::iterator Iter
Public Member Functions
virtual ~SvtxClusterMap ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const SvtxCluster * get (unsigned int idkey) const
virtual SvtxCluster * get (unsigned int idkey)
virtual SvtxCluster * insert (const SvtxCluster *cluster)
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
SvtxClusterMap ()
Private Member Functions
ClassDef (SvtxClusterMap, 1)
Detailed Description
Definition at line 10 of file SvtxClusterMap.h.
Member Typedef Documentation
typedef std::map<unsigned int, SvtxCluster*> SvtxClusterMap::ClusterMap
Definition at line 13 of file SvtxClusterMap.h.
typedef std::map<unsigned int, SvtxCluster*>::const_iterator SvtxClusterMap::ConstIter
Definition at line 14 of file SvtxClusterMap.h.
typedef std::map<unsigned int, SvtxCluster*>::iterator SvtxClusterMap::Iter
Definition at line 15 of file SvtxClusterMap.h.
Constructor & Destructor Documentation
virtual SvtxClusterMap::~SvtxClusterMap () inline virtual
Definition at line 17 of file SvtxClusterMap.h.
SvtxClusterMap::SvtxClusterMap () inline protected
Definition at line 46 of file SvtxClusterMap.h.
Member Function Documentation
virtual ConstIter SvtxClusterMap::begin () const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 37 of file SvtxClusterMap.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), AnaMvtxTelescopeHits::process_event(), and DumpSvtxClusterMap::process_Node().
virtual Iter SvtxClusterMap::begin () inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 41 of file SvtxClusterMap.h.
SvtxClusterMap::ClassDef (SvtxClusterMap , 1) private
virtual void SvtxClusterMap::clear () inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 30 of file SvtxClusterMap.h.
virtual PHObject* SvtxClusterMap::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in SvtxClusterMap_v1.
Definition at line 25 of file SvtxClusterMap.h.
virtual size_t SvtxClusterMap::count (unsigned int idkey) const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 29 of file SvtxClusterMap.h.
virtual bool SvtxClusterMap::empty () const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 27 of file SvtxClusterMap.h.
virtual ConstIter SvtxClusterMap::end () const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 39 of file SvtxClusterMap.h.
Referenced by psTOFTimezeroEval::fillOutputNtuples(), SvtxEvaluatorHaiwang::fillOutputNtuples(), psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), AnaMvtxTelescopeHits::process_event(), and DumpSvtxClusterMap::process_Node().
virtual Iter SvtxClusterMap::end () inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 43 of file SvtxClusterMap.h.
virtual size_t SvtxClusterMap::erase (unsigned int idkey) inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 35 of file SvtxClusterMap.h.
virtual ConstIter SvtxClusterMap::find (unsigned int idkey) const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 38 of file SvtxClusterMap.h.
virtual Iter SvtxClusterMap::find (unsigned int idkey) inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 42 of file SvtxClusterMap.h.
virtual const SvtxCluster* SvtxClusterMap::get (unsigned int idkey) const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 32 of file SvtxClusterMap.h.
Referenced by Conversion::dist(), EMCalCalib::eval_photon(), EMCalAna::eval_trk(), AnaSvtxTracksForGenFit::fill_tree(), Conversion::firstLayer(), Conversion::hasSilicon(), BDiJetModule::MakeGenFitTrack(), psTOFTimezeroEval::printOutputInfo(), SvtxEvaluatorHaiwang::printOutputInfo(), BDiJetModule::process_event(), and Conversion::trackDLayer().
virtual SvtxCluster* SvtxClusterMap::get (unsigned int idkey) inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 33 of file SvtxClusterMap.h.
virtual void SvtxClusterMap::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in SvtxClusterMap_v1.
Definition at line 19 of file SvtxClusterMap.h.
References os.
virtual SvtxCluster* SvtxClusterMap::insert (const SvtxCluster * cluster) inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 34 of file SvtxClusterMap.h.
virtual int SvtxClusterMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in SvtxClusterMap_v1.
Definition at line 24 of file SvtxClusterMap.h.
virtual void SvtxClusterMap::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in SvtxClusterMap_v1.
Definition at line 23 of file SvtxClusterMap.h.
virtual size_t SvtxClusterMap::size (void) const inline virtual
Reimplemented in SvtxClusterMap_v1.
Definition at line 28 of file SvtxClusterMap.h.
Referenced by psTOFTimezeroEval::printInputInfo(), SvtxEvaluatorHaiwang::printInputInfo(), AnaMvtxTelescopeHits::process_event(), and DumpSvtxClusterMap::process_Node().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxClusterMap.h