Analysis Software: analysis/blob/master/HF-Jet/TruthGeneration/macros/Draw_HFJetTruth.C File Reference
Draw_HFJetTruth.C File Reference
#include <TFile.h>
#include <TGraph.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
void Draw_HFJetTruth (const TString infile="/sphenix/user/jinhuang/HF-jet/event_gen/200pp_pythia8_CTEQ6L_7GeV/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root", double int_lumi=891093/3.332e-02/1e9, const double dy=0.6 *2)
void DrawCrossSection (double int_lumi, const double dy)
void Draw_HFJetTruth_DrawCrossSection_PR (const TString infile)
void CrossSection2RAA_Proposal (const TString infile)
void CrossSection2RAA (const TString infile, const bool use_AA_jet_trigger=true, const double dy=.7 *2)
void CrossSection2v2 (const TString infile, const bool use_AA_jet_trigger=true, const double ep_resolution=0.7, const double dy=.7 *2)
TGraphErrors * GetRAA (TH1 *h_pp, TH1 *h_AA)
TH1 * CrossSection2RelUncert (const TH1F *h_cross, const double suppression, const double deta, const double pp_quiv_int_lum)
TGraph * CrossSection2v2Uncert (const TH1F *h_cross, const double suppression, const double deta, const double pp_quiv_int_lum, const double ep_resolution=1, const double pt_shift=0)
void Convert2CrossSection (TH1 *h, const double int_lumi, const double dy)
TGraphAsymmErrors * GetFONLL_B ()
TGraphAsymmErrors * GetFONLL_C ()
TGraph * pQCDModel_HuangKangVitev (const double g)
TGraph * GetPHENIX_jet ()
Variables
TFile * _file0 = NULL
TTree * T = NULL
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file Draw_HFJetTruth.C.
Function Documentation
void Convert2CrossSection (TH1 * h, const double int_lumi, const double dy)
Definition at line 790 of file Draw_HFJetTruth.C.
References i.
Referenced by DrawCrossSection().
void CrossSection2RAA (const TString infile, const bool use_AA_jet_trigger = true, const double dy = .7 * 2)
Definition at line 370 of file Draw_HFJetTruth.C.
References assert, CrossSection2RelUncert(), dy, GetRAA(), h_b, hall, leg, pQCDModel_HuangKangVitev(), and SaveCanvas().
Referenced by Draw_HFJetTruth(), and Draw_HFJetTruth_InvMass().
void CrossSection2RAA_Proposal (const TString infile)
Definition at line 265 of file Draw_HFJetTruth.C.
References assert, CrossSection2RelUncert(), GetRAA(), h_b, i, SaveCanvas(), and t.
TH1* CrossSection2RelUncert (const TH1F * h_cross, const double suppression, const double deta, const double pp_quiv_int_lum)
Definition at line 698 of file Draw_HFJetTruth.C.
References assert, and i.
Referenced by CrossSection2RAA(), and CrossSection2RAA_Proposal().
void CrossSection2v2 (const TString infile, const bool use_AA_jet_trigger = true, const double ep_resolution = 0.7, const double dy = .7 * 2)
Definition at line 514 of file Draw_HFJetTruth.C.
References assert, CrossSection2v2Uncert(), dy, h_b, hall, leg, and SaveCanvas().
TGraph* CrossSection2v2Uncert (const TH1F * h_cross, const double suppression, const double deta, const double pp_quiv_int_lum, const double ep_resolution = 1, const double pt_shift = 0)
Definition at line 735 of file Draw_HFJetTruth.C.
References assert, gr, and i.
Referenced by CrossSection2v2().
void Draw_HFJetTruth (const TString infile = "/sphenix/user/jinhuang/HF-jet/event_gen/200pp_pythia8_CTEQ6L_7GeV/200pp_pythia8_CTEQ6L_7GeV_ALL.cfg_eneg_DSTReader.root", double int_lumi = 891093 / 3.332e-02 / 1e9, const double dy = 0.6 * 2)
Definition at line 27 of file Draw_HFJetTruth.C.
References _file0, assert, CrossSection2RAA(), n, SetsPhenixStyle(), T, and t.
void Draw_HFJetTruth_DrawCrossSection_PR (const TString infile)
Definition at line 201 of file Draw_HFJetTruth.C.
References _file0, assert, GetFONLL_B(), GetFONLL_C(), GetPHENIX_jet(), h_b, hall, leg, and SaveCanvas().
void DrawCrossSection (double int_lumi, const double dy)
Definition at line 82 of file Draw_HFJetTruth.C.
References _file0, Convert2CrossSection(), GetFONLL_B(), GetFONLL_C(), GetPHENIX_jet(), h_b, hall, leg, SaveCanvas(), and T.
TGraphAsymmErrors* GetFONLL_B ()
Definition at line 815 of file Draw_HFJetTruth.C.
References gr, i, max, and min.
Referenced by Draw_HFJetTruth_DrawCrossSection_PR(), and DrawCrossSection().
TGraphAsymmErrors* GetFONLL_C ()
Definition at line 896 of file Draw_HFJetTruth.C.
References gr, i, max, and min.
Referenced by Draw_HFJetTruth_DrawCrossSection_PR(), and DrawCrossSection().
TGraph* GetPHENIX_jet ()
Definition at line 1104 of file Draw_HFJetTruth.C.
References gr, and i.
Referenced by Draw_HFJetTruth_DrawCrossSection_PR(), and DrawCrossSection().
TGraphErrors* GetRAA (TH1 * h_pp, TH1 * h_AA)
Definition at line 666 of file Draw_HFJetTruth.C.
References assert, and i.
Referenced by CrossSection2RAA(), and CrossSection2RAA_Proposal().
TGraph* pQCDModel_HuangKangVitev (const double g)
Definition at line 989 of file Draw_HFJetTruth.C.
References assert.
Referenced by CrossSection2RAA().
Variable Documentation
TFile* _file0 = NULL
Definition at line 24 of file Draw_HFJetTruth.C.
TTree* T = NULL
Definition at line 25 of file Draw_HFJetTruth.C.