Analysis Software: tau_commons Namespace Reference
tau_commons Namespace Reference
Functions
TCut select_true_uds ("evtgen_pid!=15 && evtgen_pid!=11")
TCut select_true_tau ("evtgen_pid==15")
TCut select_accept_jet ("jet_ptrans > 5")
TCut select_tau ("tracks_count_r04 == 3 && tracks_chargesum_r04 == -1 && jet_eta < 0.8 && tracks_vertex > 0.03")
Function Documentation
TCut tau_commons::select_accept_jet (" jet_ptrans, 5")
Referenced by likelihood(), test_cuts(), and tree2csv().
TCut tau_commons::select_tau ()
Referenced by test_cuts().
TCut tau_commons::select_true_tau ()
Referenced by cone_energies(), likelihood(), test_cuts(), and tree2csv().
TCut tau_commons::select_true_uds ()
Referenced by cone_energies(), likelihood(), test_cuts(), and tree2csv().