Analysis Software: Poisson Class Reference
Poisson Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/Poisson.h>
Public Member Functions
long double poisson_prob (double mean, int value)
long double exp1 (double mean, int value)
long double exp2 (double mean)
long double fact (int value)
Detailed Description
Definition at line 18 of file Poisson.h.
Member Function Documentation
long double Poisson::exp1 (double mean, int value)
Definition at line 17 of file Poisson.cc.
Referenced by ar3jet().
long double Poisson::exp2 (double mean)
Definition at line 25 of file Poisson.cc.
long double Poisson::fact (int value)
Definition at line 33 of file Poisson.cc.
References i, and value.
Referenced by pyreco(), pysgex(), pytbhg(), and pytbhq().
long double Poisson::poisson_prob (double mean, int value)
Definition at line 9 of file Poisson.cc.
The documentation for this class was generated from the following files:
analysis/blob/master/ParticleID/RICHAnalysis/Poisson.h
analysis/blob/master/ParticleID/RICHAnalysis/Poisson.cc