Analysis Software: HiStrng Class Reference
HiStrng Class Reference
Class definition for HiStrng, which is used to modify the Hijing HISTRNG common.
#include <coresoftware/blob/master/generators/sHijing/HiStrng.h>
Classes
struct HISTRNG
Public Member Functions
HiStrng ()
~HiStrng ()
int & nfp (int i, int j)
float & pp (int i, int j)
int & nft (int i, int j)
float & pt (int i, int j)
void init (void)
int lenI () const
int lenJ () const
Private Attributes
int _dummy
float _realdummy
Static Private Attributes
static const int _lenI = 300
static const int _lenJ = 15
static HISTRNG * _histrng =0
Friends
struct HISTRNG
Detailed Description
Class definition for HiStrng, which is used to modify the Hijing HISTRNG common.
Definition at line 11 of file HiStrng.h.
Constructor & Destructor Documentation
HiStrng::HiStrng () inline
Definition at line 59 of file HiStrng.h.
HiStrng::~HiStrng () inline
Definition at line 66 of file HiStrng.h.
Member Function Documentation
void HiStrng::init (void) inline
Definition at line 54 of file HiStrng.h.
References _histrng, and histrng_address_().
Referenced by nfp(), nft(), pp(), and pt().
int HiStrng::lenI () const inline
Definition at line 24 of file HiStrng.h.
References _lenI.
Referenced by nfp(), nft(), pp(), and pt().
int HiStrng::lenJ () const inline
Definition at line 25 of file HiStrng.h.
References _lenJ.
Referenced by nfp(), nft(), pp(), and pt().
int & HiStrng::nfp (int i, int j) inline
Definition at line 70 of file HiStrng.h.
References _dummy, _histrng, init(), lenI(), lenJ(), and HiStrng::HISTRNG::nfp.
Referenced by __example_2.f__(), fillEvent(), hijcsc(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), jetini(), pygano(), pygvmd(), pyhiremn(), and quench().
int & HiStrng::nft (int i, int j) inline
Definition at line 90 of file HiStrng.h.
References _dummy, _histrng, init(), lenI(), lenJ(), and HiStrng::HISTRNG::nft.
Referenced by __example_2.f__(), fillEvent(), hijcsc(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), jetini(), pyhiremn(), and quench().
float & HiStrng::pp (int i, int j) inline
Definition at line 80 of file HiStrng.h.
References _histrng, _realdummy, init(), lenI(), lenJ(), and HiStrng::HISTRNG::pp.
Referenced by __example_2.f__(), hijcsc(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), jetini(), pyqqbh(), pystbh(), and quench().
float & HiStrng::pt (int i, int j) inline
Definition at line 100 of file HiStrng.h.
References _histrng, _realdummy, init(), lenI(), lenJ(), and HiStrng::HISTRNG::pt.
Referenced by __example_2.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), dokinematics(), getqvec(), hijcsc(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), hiptdi(), jetini(), lucell(), luptdi(), lushow(), pycell(), pydisg(), pydocu(), pygaga(), pyhimult(), pyhiremn(), pyhithia(), pymign(), pymirm(), pymult(), pyptdi(), pyqqbh(), pyremn(), pyscat(), pyshow(), pystbh(), and quench().
Friends And Related Function Documentation
friend struct HISTRNG friend
Definition at line 33 of file HiStrng.h.
Member Data Documentation
int HiStrng::_dummy private
Definition at line 44 of file HiStrng.h.
Referenced by nfp(), and nft().
HiStrng::HISTRNG * HiStrng::_histrng =0 static private
Definition at line 47 of file HiStrng.h.
Referenced by init(), nfp(), nft(), pp(), and pt().
const int HiStrng::_lenI = 300 static private
Definition at line 30 of file HiStrng.h.
Referenced by lenI().
const int HiStrng::_lenJ = 15 static private
Definition at line 31 of file HiStrng.h.
Referenced by lenJ().
float HiStrng::_realdummy private
Definition at line 45 of file HiStrng.h.
Referenced by pp(), and pt().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HiStrng.h