Analysis Software: CopyAndSubtractJets Class Reference
CopyAndSubtractJets Class Reference
Creates subtractd copy of a jet collection.
#include <coresoftware/blob/master/offline/packages/jetbackground/CopyAndSubtractJets.h>
Public Member Functions
CopyAndSubtractJets (const std::string &name="CopyAndSubtractJets")
virtual ~CopyAndSubtractJets ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetFlowModulation (bool use_flow_modulation)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNode (PHCompositeNode *topNode)
Private Attributes
bool _use_flow_modulation
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Creates subtractd copy of a jet collection.
Makes a copy of a jet collection with a new name and then updates the kinematics of the jets in that collection based on a given UE background (intended use is to create the set of jets used as seeds in the second part of UE determination procedure)
Definition at line 26 of file CopyAndSubtractJets.h.
Constructor & Destructor Documentation
CopyAndSubtractJets::CopyAndSubtractJets (const std::string & name = "CopyAndSubtractJets")
Definition at line 33 of file CopyAndSubtractJets.cc.
virtual CopyAndSubtractJets::~CopyAndSubtractJets () inline virtual
Definition at line 30 of file CopyAndSubtractJets.h.
Member Function Documentation
int CopyAndSubtractJets::CreateNode (PHCompositeNode * topNode) private
Definition at line 204 of file CopyAndSubtractJets.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int CopyAndSubtractJets::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 199 of file CopyAndSubtractJets.cc.
References Fun4AllReturnCodes::EVENT_OK.
int CopyAndSubtractJets::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 39 of file CopyAndSubtractJets.cc.
References CreateNode(), and Fun4AllReturnCodes::EVENT_OK.
int CopyAndSubtractJets::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 46 of file CopyAndSubtractJets.cc.
References _use_flow_modulation, Jet::begin_comp(), Jet::end_comp(), Fun4AllReturnCodes::EVENT_OK, Jet::get_e(), RawTower::get_energy(), Jet::get_eta(), RawTowerGeom::get_eta(), RawTower::get_key(), Jet::get_phi(), RawTowerGeom::get_phi(), Jet::get_pt(), Jet::get_px(), Jet::get_py(), Jet::get_pz(), TowerBackground::get_UE(), RawTowerContainer::getTower(), Jet::set_e(), Jet::set_id(), Jet::set_px(), Jet::set_py(), Jet::set_pz(), and Fun4AllBase::Verbosity().
void CopyAndSubtractJets::SetFlowModulation (bool use_flow_modulation) inline
Definition at line 36 of file CopyAndSubtractJets.h.
References _use_flow_modulation.
Referenced by HIJetReco().
Member Data Documentation
bool CopyAndSubtractJets::_use_flow_modulation private
Definition at line 41 of file CopyAndSubtractJets.h.
Referenced by process_event(), and SetFlowModulation().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/jetbackground/CopyAndSubtractJets.h
coresoftware/blob/master/offline/packages/jetbackground/CopyAndSubtractJets.cc