Analysis Software: analysis/blob/master/PhotonConversion/ana/observHister.C File Reference
observHister.C File Reference
#include <iostream>
#include "TFile.h"
#include "Scalar.h"
#include "TTree.h"
#include "TChain.h"
#include "TLegend.h"
#include "math.h"
#include "TH1.h"
#include "TH2.h"
#include "TEfficiency.h"
#include "TLine.h"
#include "TGraphAsymmErrors.h"
Functions
TChain * handleFile (string name, string extension, string treename, unsigned int filecount)
void matchPlot (TChain *ttree, TFile *out_file)
void makeVtxR (TChain *ttree, TFile *out_file)
void makepTEff (TChain *ttree, TFile *out_file)
void testCuts (TChain *ttree, TFile *out_file)
void makeRefitDist (TChain *ttree, TFile *out_file)
void observHister ()
Function Documentation
TChain* handleFile (string name, string extension, string treename, unsigned int filecount)
Definition at line 16 of file observHister.C.
References i, and s.
void makepTEff (TChain * ttree, TFile * out_file)
Definition at line 79 of file observHister.C.
void makeRefitDist (TChain * ttree, TFile * out_file)
Definition at line 175 of file observHister.C.
void makeVtxR (TChain * ttree, TFile * out_file)
Definition at line 49 of file observHister.C.
References i.
Referenced by photonEff2().
void matchPlot (TChain * ttree, TFile * out_file)
Definition at line 30 of file observHister.C.
Referenced by observHister().
void observHister ()
Definition at line 205 of file observHister.C.
References matchPlot().
void testCuts (TChain * ttree, TFile * out_file)
Definition at line 110 of file observHister.C.