Analysis Software: PHG4FullProjSpacalCellReco::LightCollectionModel Class Reference
PHG4FullProjSpacalCellReco::LightCollectionModel Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h>
Public Member Functions
LightCollectionModel ()
virtual ~LightCollectionModel ()
void load_data_file (const std::string &input_file, const std::string &histogram_light_guide_model, const std::string &histogram_fiber_model)
input data file
bool use_light_guide_model () const
Whether use light collection model.
bool use_fiber_model () const
Whether use Light Transmission Efficiency model for the fiber.
double get_light_guide_efficiency (const double x_fraction, const double y_fraction)
get Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
double get_fiber_transmission (const double z_distance)
get Light Transmission Efficiency for the fiber as function of z position (cm) in the fiber. Z=0 is at the middle of the fiber
Private Attributes
TH2 * data_grid_light_guide_efficiency
2-D data grid for Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
TH1 * data_grid_fiber_trans
1-D data grid for the light transmission efficiency in the fiber as function of distance to location in the fiber. Z=0 is at the middle of the fiber
TH2 * data_grid_light_guide_efficiency_verify
TH1 * data_grid_fiber_trans_verify
Detailed Description
Definition at line 43 of file PHG4FullProjSpacalCellReco.h.
Constructor & Destructor Documentation
PHG4FullProjSpacalCellReco::LightCollectionModel::LightCollectionModel ()
Definition at line 539 of file PHG4FullProjSpacalCellReco.cc.
References data_grid_fiber_trans_verify, data_grid_light_guide_efficiency_verify, Fun4AllServer::instance(), and Fun4AllServer::registerHisto().
PHG4FullProjSpacalCellReco::LightCollectionModel::~LightCollectionModel () virtual
Definition at line 560 of file PHG4FullProjSpacalCellReco.cc.
Member Function Documentation
double PHG4FullProjSpacalCellReco::LightCollectionModel::get_fiber_transmission (const double z_distance)
get Light Transmission Efficiency for the fiber as function of z position (cm) in the fiber. Z=0 is at the middle of the fiber
Definition at line 612 of file PHG4FullProjSpacalCellReco.cc.
References assert.
Referenced by PHG4FullProjSpacalCellReco::process_event().
double PHG4FullProjSpacalCellReco::LightCollectionModel::get_light_guide_efficiency (const double x_fraction, const double y_fraction)
get Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
Definition at line 591 of file PHG4FullProjSpacalCellReco.cc.
References assert.
Referenced by PHG4FullProjSpacalCellReco::process_event().
void PHG4FullProjSpacalCellReco::LightCollectionModel::load_data_file (const std::string & input_file, const std::string & histogram_light_guide_model, const std::string & histogram_fiber_model)
input data file
Definition at line 567 of file PHG4FullProjSpacalCellReco.cc.
References assert.
Referenced by CEMC_Cells(), Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
bool PHG4FullProjSpacalCellReco::LightCollectionModel::use_fiber_model () const inline
Whether use Light Transmission Efficiency model for the fiber.
Definition at line 56 of file PHG4FullProjSpacalCellReco.h.
References data_grid_fiber_trans.
Referenced by PHG4FullProjSpacalCellReco::process_event().
bool PHG4FullProjSpacalCellReco::LightCollectionModel::use_light_guide_model () const inline
Whether use light collection model.
Definition at line 53 of file PHG4FullProjSpacalCellReco.h.
References data_grid_light_guide_efficiency.
Member Data Documentation
TH1* PHG4FullProjSpacalCellReco::LightCollectionModel::data_grid_fiber_trans private
1-D data grid for the light transmission efficiency in the fiber as function of distance to location in the fiber. Z=0 is at the middle of the fiber
Definition at line 69 of file PHG4FullProjSpacalCellReco.h.
Referenced by use_fiber_model().
TH1* PHG4FullProjSpacalCellReco::LightCollectionModel::data_grid_fiber_trans_verify private
Definition at line 72 of file PHG4FullProjSpacalCellReco.h.
Referenced by LightCollectionModel().
TH2* PHG4FullProjSpacalCellReco::LightCollectionModel::data_grid_light_guide_efficiency private
2-D data grid for Light Collection Efficiency for the light guide as function of x,y position in fraction of tower width
Definition at line 66 of file PHG4FullProjSpacalCellReco.h.
Referenced by use_light_guide_model().
TH2* PHG4FullProjSpacalCellReco::LightCollectionModel::data_grid_light_guide_efficiency_verify private
Definition at line 71 of file PHG4FullProjSpacalCellReco.h.
Referenced by LightCollectionModel().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc