Analysis Software: FitNewton::GaussianIntegralGradHessian Class Reference
FitNewton::GaussianIntegralGradHessian Class Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/FitNewton/GaussianIntegralGradHessian.h>
Public Member Functions
GaussianIntegralGradHessian ()
~GaussianIntegralGradHessian ()
bool calcValGradHessian (const Eigen::VectorXd &x, double &val, Eigen::VectorXd &grad, Eigen::MatrixXd &hessian)
FunctionGradHessian * Clone () const
Public Member Functions inherited from FitNewton::FunctionGradHessian
FunctionGradHessian (unsigned int nparams=1, unsigned int nfixedparams=1)
virtual ~FunctionGradHessian ()
virtual bool calcValGrad (const Eigen::VectorXd &x, double &val, Eigen::VectorXd &grad)
unsigned int nPars ()
unsigned int nFixedPars ()
std::vector< double > getFixedPars ()
void setFixedPar (unsigned int coor, double val)
virtual void computeCovariance (const double &val, const Eigen::MatrixXd &hessian)
virtual void rescaleMove (const Eigen::VectorXd &pars, Eigen::VectorXd &move)
Additional Inherited Members
Protected Attributes inherited from FitNewton::FunctionGradHessian
unsigned int npars
unsigned int nfixedpars
std::vector< double > fixedpars
Detailed Description
Definition at line 10 of file GaussianIntegralGradHessian.h.
Constructor & Destructor Documentation
FitNewton::GaussianIntegralGradHessian::GaussianIntegralGradHessian ()
Definition at line 11 of file GaussianIntegralGradHessian.cpp.
Referenced by Clone().
FitNewton::GaussianIntegralGradHessian::~GaussianIntegralGradHessian ()
Definition at line 17 of file GaussianIntegralGradHessian.cpp.
Member Function Documentation
bool FitNewton::GaussianIntegralGradHessian::calcValGradHessian (const Eigen::VectorXd & x, double & val, Eigen::VectorXd & grad, Eigen::MatrixXd & hessian) virtual
Implements FitNewton::FunctionGradHessian.
Definition at line 32 of file GaussianIntegralGradHessian.cpp.
References FitNewton::FunctionGradHessian::fixedpars, temp1, temp2, and x.
FunctionGradHessian * FitNewton::GaussianIntegralGradHessian::Clone () const virtual
Implements FitNewton::FunctionGradHessian.
Definition at line 23 of file GaussianIntegralGradHessian.cpp.
References FitNewton::FunctionGradHessian::fixedpars, GaussianIntegralGradHessian(), and FitNewton::FunctionGradHessian::setFixedPar().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/HelixHough/FitNewton/GaussianIntegralGradHessian.h
coresoftware/blob/master/offline/packages/HelixHough/FitNewton/GaussianIntegralGradHessian.cpp