Analysis Software: PHG4Sector::PHG4SectorConstructor Class Reference
PHG4Sector::PHG4SectorConstructor Class Reference
Generalized detector which use sectors of flat panels to cover full azimuthal acceptance.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorConstructor.h>
Public Member Functions
PHG4SectorConstructor (const std::string &name, PHG4Subsystem *subsys)
virtual ~PHG4SectorConstructor ()
void Construct_Sectors (G4LogicalVolume *WorldLog)
void OverlapCheck (bool check)
Public Attributes
std::string name_base
Sector_Geometry geom
Protected Types
typedef std::map< G4String,
G4LogicalVolume * > map_log_vol_t
typedef std::pair< G4String,
G4int > phy_vol_idx_t
typedef std::map
< phy_vol_idx_t, G4PVPlacement * > map_phy_vol_t
Protected Member Functions
G4VSolid * Construct_Sectors_Plane (const std::string &name, const double start_z, const double thickness, G4VSolid *SecConeBoundary_Det)
G4LogicalVolume * RegisterLogicalVolume (G4LogicalVolume *)
G4PVPlacement * RegisterPhysicalVolume (G4PVPlacement *v, const bool active=false)
Protected Attributes
bool overlapcheck_sector
map_log_vol_t map_log_vol
map_phy_vol_t map_phy_vol
map_phy_vol_t map_active_phy_vol
all physics volume
Private Attributes
PHG4SectorDisplayAction * m_DisplayAction
Detailed Description
Generalized detector which use sectors of flat panels to cover full azimuthal acceptance.
Definition at line 363 of file PHG4SectorConstructor.h.
Member Typedef Documentation
typedef std::map<G4String, G4LogicalVolume *> PHG4Sector::PHG4SectorConstructor::map_log_vol_t protected
Definition at line 403 of file PHG4SectorConstructor.h.
typedef std::map<phy_vol_idx_t, G4PVPlacement *> PHG4Sector::PHG4SectorConstructor::map_phy_vol_t protected
Definition at line 410 of file PHG4SectorConstructor.h.
typedef std::pair<G4String, G4int> PHG4Sector::PHG4SectorConstructor::phy_vol_idx_t protected
Definition at line 409 of file PHG4SectorConstructor.h.
Constructor & Destructor Documentation
PHG4SectorConstructor::PHG4SectorConstructor (const std::string & name, PHG4Subsystem * subsys)
Definition at line 42 of file PHG4SectorConstructor.cc.
virtual PHG4Sector::PHG4SectorConstructor::~PHG4SectorConstructor () inline virtual
Definition at line 367 of file PHG4SectorConstructor.h.
Member Function Documentation
void PHG4SectorConstructor::Construct_Sectors (G4LogicalVolume * WorldLog)
Definition at line 49 of file PHG4SectorConstructor.cc.
References PHG4Sector::Layer::active, PHG4SectorDisplayAction::AddVolume(), Construct_Sectors_Plane(), PHG4Sector::Layer::depth, geom, PHG4Sector::Sector_Geometry::get_material(), PHG4Sector::Sector_Geometry::get_max_polar_angle(), PHG4Sector::Sector_Geometry::get_max_polar_edge(), PHG4Sector::Sector_Geometry::get_max_R(), PHG4Sector::Sector_Geometry::get_min_polar_angle(), PHG4Sector::Sector_Geometry::get_min_polar_edge(), PHG4Sector::Sector_Geometry::get_N_Sector(), PHG4Sector::Sector_Geometry::get_normal_polar_angle(), PHG4Sector::Sector_Geometry::get_normal_start(), PHG4Sector::Sector_Geometry::get_total_thickness(), it, PHG4Sector::Sector_Geometry::kConeEdge, PHG4Sector::Sector_Geometry::kFlatEdge, PHG4Sector::Sector_Geometry::layer_list, m_DisplayAction, map_active_phy_vol, map_log_vol, map_phy_vol, PHG4Sector::Layer::material, TauVsDIS_MachineLearning_Differentiation::msg, PHG4Sector::Layer::name, name_base, overlapcheck_sector, PHG4Sector::Layer::percentage_filled, pi, RegisterLogicalVolume(), RegisterPhysicalVolume(), s, PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), and t.
Referenced by PHG4SectorDetector::ConstructMe().
G4VSolid * PHG4SectorConstructor::Construct_Sectors_Plane (const std::string & name, const double start_z, const double thickness, G4VSolid * SecConeBoundary_Det) protected
Definition at line 223 of file PHG4SectorConstructor.cc.
References assert, geom, PHG4Sector::Sector_Geometry::get_max_R(), and pi.
Referenced by Construct_Sectors().
void PHG4Sector::PHG4SectorConstructor::OverlapCheck (bool check) inline
Definition at line 373 of file PHG4SectorConstructor.h.
References overlapcheck_sector.
G4LogicalVolume * PHG4SectorConstructor::RegisterLogicalVolume (G4LogicalVolume * v) protected
Definition at line 273 of file PHG4SectorConstructor.cc.
References map_log_vol, and v.
Referenced by Construct_Sectors().
G4PVPlacement * PHG4SectorConstructor::RegisterPhysicalVolume (G4PVPlacement * v, const bool active = false) protected
Definition at line 294 of file PHG4SectorConstructor.cc.
References map_active_phy_vol, map_phy_vol, and v.
Referenced by Construct_Sectors().
Member Data Documentation
Sector_Geometry PHG4Sector::PHG4SectorConstructor::geom
Definition at line 394 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors(), Construct_Sectors_Plane(), and PHG4SectorSubsystem::Init().
PHG4SectorDisplayAction* PHG4Sector::PHG4SectorConstructor::m_DisplayAction private
Definition at line 397 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors().
map_phy_vol_t PHG4Sector::PHG4SectorConstructor::map_active_phy_vol protected
all physics volume
Definition at line 412 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors(), PHG4SectorDetector::IsInSectorActive(), and RegisterPhysicalVolume().
map_log_vol_t PHG4Sector::PHG4SectorConstructor::map_log_vol protected
Definition at line 404 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors(), PHG4SectorDetector::ConstructMe(), and RegisterLogicalVolume().
map_phy_vol_t PHG4Sector::PHG4SectorConstructor::map_phy_vol protected
Definition at line 411 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors(), and RegisterPhysicalVolume().
std::string PHG4Sector::PHG4SectorConstructor::name_base
Definition at line 392 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors(), and PHG4SectorDetector::ConstructMe().
bool PHG4Sector::PHG4SectorConstructor::overlapcheck_sector protected
Definition at line 379 of file PHG4SectorConstructor.h.
Referenced by Construct_Sectors(), and OverlapCheck().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc