Analysis Software: TPCFEETestRecov1::PadPlaneData Class Reference
TPCFEETestRecov1::PadPlaneData Class Reference
buffer for full event data
#include <coresoftware/blob/master/offline/packages/tpcdaq/TPCFEETestRecov1.h>
Classes
struct SampleID
Public Member Functions
PadPlaneData ()
void Reset ()
std::vector< int > & getPad (const int pad_x, const int pad_y)
int getSample (const SampleID &id)
void Clustering (int zero_suppression, bool verbosity=false)
3-D Graph clustering based on PHMakeGroups()
const std::vector< std::vector
< std::vector< int > > > & getData () const
const std::multimap< int,
SampleID > & getGroups () const
Static Public Member Functions
static bool IsValidPad (const int pad_x, const int pad_y)
Private Attributes
std::vector< std::vector
< std::vector< int > > > m_data
full event data in index order of m_data[pady][padx][sample]
std::multimap< int, SampleID > m_groups
Detailed Description
buffer for full event data
Definition at line 91 of file TPCFEETestRecov1.h.
Constructor & Destructor Documentation
TPCFEETestRecov1::PadPlaneData::PadPlaneData ()
Definition at line 521 of file TPCFEETestRecov1.cc.
Member Function Documentation
void TPCFEETestRecov1::PadPlaneData::Clustering (int zero_suppression, bool verbosity = false)
3-D Graph clustering based on PHMakeGroups()
Definition at line 588 of file TPCFEETestRecov1.cc.
References TPCFEETestRecov1::PadPlaneData::SampleID::adjust(), assert, G, i, it, TPCDaqDefs::FEEv1::kMaxPadX, TPCDaqDefs::FEEv1::kMaxPadY, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, TPCFEETestRecov1::PadPlaneData::SampleID::pady, and v.
Referenced by TPCFEETestRecov1::Clustering().
const std::vector<std::vector<std::vector<int> > >& TPCFEETestRecov1::PadPlaneData::getData () const inline
Definition at line 120 of file TPCFEETestRecov1.h.
References m_data.
const std::multimap<int, SampleID>& TPCFEETestRecov1::PadPlaneData::getGroups () const inline
Definition at line 125 of file TPCFEETestRecov1.h.
References m_groups.
Referenced by TPCFEETestRecov1::Clustering().
vector< int > & TPCFEETestRecov1::PadPlaneData::getPad (const int pad_x, const int pad_y)
Definition at line 547 of file TPCFEETestRecov1.cc.
References assert, TPCDaqDefs::FEEv1::kMaxPadX, and TPCDaqDefs::FEEv1::kMaxPadY.
Referenced by TPCFEETestRecov1::Clustering(), and TPCFEETestRecov1::process_event().
int TPCFEETestRecov1::PadPlaneData::getSample (const SampleID & id)
bool TPCFEETestRecov1::PadPlaneData::IsValidPad (const int pad_x, const int pad_y) static
Definition at line 539 of file TPCFEETestRecov1.cc.
References TPCDaqDefs::FEEv1::kMaxPadX, and TPCDaqDefs::FEEv1::kMaxPadY.
Referenced by TPCFEETestRecov1::Clustering(), and TPCFEETestRecov1::process_event().
void TPCFEETestRecov1::PadPlaneData::Reset ()
Definition at line 526 of file TPCFEETestRecov1.cc.
Referenced by TPCFEETestRecov1::ResetEvent().
Member Data Documentation
std::vector<std::vector<std::vector<int> > > TPCFEETestRecov1::PadPlaneData::m_data private
full event data in index order of m_data[pady][padx][sample]
Definition at line 132 of file TPCFEETestRecov1.h.
Referenced by getData().
std::multimap<int, SampleID> TPCFEETestRecov1::PadPlaneData::m_groups private
Definition at line 134 of file TPCFEETestRecov1.h.
Referenced by getGroups().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpcdaq/TPCFEETestRecov1.h
coresoftware/blob/master/offline/packages/tpcdaq/TPCFEETestRecov1.cc