Analysis Software: coresoftware/blob/master/offline/packages/HelixHough/helix_hough/circlegen/circlegen.cpp File Reference
circlegen.cpp File Reference
#include <math.h>
#include "TFile.h"
#include "TTree.h"
#include "TRandom3.h"
#include <sstream>
#include <iostream>
#include <vector>
Functions
bool intersect_circles (bool hel, double startx, double starty, double rad_det, double rad_trk, double cx, double cy, double &x, double &y)
void print_usage ()
int main (int argc, char **argv)
Function Documentation
bool intersect_circles (bool hel, double startx, double starty, double rad_det, double rad_trk, double cx, double cy, double & x, double & y)
Definition at line 27 of file circlegen.cpp.
References d, SVM_v1::h, r2, ux, and uy.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 83 of file circlegen.cpp.
References d, dx, dy, dzdl, filename, i, intersect_circles(), j, k, nevents(), phi, print_usage(), s, tanphi, temp1, temp2, ux, uy, v, x, y, and z.
void print_usage ()
Definition at line 77 of file circlegen.cpp.
Referenced by main().