Analysis Software: tutorials/blob/master/PHG4DSTReader/Example.C File Reference
Example.C File Reference
See the main function Example()
#include <TFile.h>
#include <TPad.h>
#include <TString.h>
#include <TSystem.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include <calobase/RawTower.h>
#include <calobase/RawTowerv1.h>
#include <g4main/PHG4HitEval.h>
#include <g4main/PHG4Particlev1.h>
#include <g4main/PHG4Particlev2.h>
#include <g4main/PHG4VtxPointv1.h>
Functions
void CheckItOut ()
First, checkout what is in there.
void AcessGeant4Particles ()
Access information for the truth Geant4 particles.
void WhereIsTheHits ()
void PlotCalorimeterSamplingFraction ()
void AccessCalorimeterTowers ()
void Example (const TString infile="https://www.phenix.bnl.gov/phenix/WWW/sPHENIX/tutorial/G4sPHENIX.root_DSTReader.root")
Variables
TFile * _file0 = NULL
TTree * T = NULL
Detailed Description
See the main function Example()
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file Example.C.
Function Documentation
void AccessCalorimeterTowers ()
Definition at line 118 of file Example.C.
References T.
Referenced by Example().
void AcessGeant4Particles ()
Access information for the truth Geant4 particles.
Definition at line 54 of file Example.C.
References T.
Referenced by Example().
void CheckItOut ()
First, checkout what is in there.
Definition at line 34 of file Example.C.
References T.
Referenced by Example().
void Example (const TString infile = "https://www.phenix.bnl.gov/phenix/WWW/sPHENIX/tutorial/G4sPHENIX.root_DSTReader.root")
Definition at line 148 of file Example.C.
References _file0, AccessCalorimeterTowers(), AcessGeant4Particles(), assert, CheckItOut(), PlotCalorimeterSamplingFraction(), T, and WhereIsTheHits().
void PlotCalorimeterSamplingFraction ()
Definition at line 94 of file Example.C.
References T.
Referenced by Example().
void WhereIsTheHits ()
X-Y distribution for the hits note, as long as we load libg4eval.so, the compiled functions can be used in T->Draw. Example, I will use PHG4Hit::get_avg_x(), https://www.phenix.bnl.gov/WWW/sPHENIX/doxygen/html/d3/d9e/classPHG4Hit.html#a99663034e71d3f324eb878eb0e3b36ba
Definition at line 76 of file Example.C.
References T.
Referenced by Example().
Variable Documentation
TFile* _file0 = NULL
Definition at line 30 of file Example.C.
TTree* T = NULL
Definition at line 31 of file Example.C.