Analysis Software: PHG4HitDefs Namespace Reference
PHG4HitDefs Namespace Reference
Typedefs
typedef unsigned long long keytype
Functions
int get_volume_id (const std::string &nodename)
Variables
static const unsigned int keybits = 32
static const unsigned int hit_idbits = sizeof(keytype)*8-keybits
Typedef Documentation
typedef unsigned long long PHG4HitDefs::keytype
Definition at line 10 of file PHG4HitDefs.h.
Function Documentation
int PHG4HitDefs::get_volume_id (const std::string & nodename)
convert PHG4HitContainer node names in to ID number for the container. used in indexing volume ID in PHG4Shower
Definition at line 8 of file PHG4HitDefs.cc.
Referenced by CaloTruthEval::get_node_pointers(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
Variable Documentation
const unsigned int PHG4HitDefs::hit_idbits = sizeof(keytype)*8-keybits static
Definition at line 12 of file PHG4HitDefs.h.
Referenced by PHG4HitContainer::AddHit(), PHG4HitContainer::genkey(), PHG4Hitv1::get_detid(), PHG4HitContainer::getHits(), PHG4HitContainer::getmaxkey(), and PHG4HcalCellReco::process_event().
const unsigned int PHG4HitDefs::keybits = 32 static
Definition at line 11 of file PHG4HitDefs.h.
Referenced by PHG4HitContainer::genkey(), and PHG4HitContainer::getHits().