Analysis Software: analysis/blob/master/Prototype3/EMCal/macros/DrawEMCalTower.C File Reference
DrawEMCalTower.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <TLatex.h>
#include <TGraphErrors.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawEMCalTower (const TString infile="/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2017/sim/MuonCalib//1k_Muon_DSTReader.root")
void EMCDistribution_Fast (TString gain="LG", bool log_scale=false)
void EMCDistribution (TString gain="LG", bool log_scale=false)
void EMCDistribution_SUM (TString sTOWER="TOWER_CEMC")
void EMCDistributionVSBeam_SUM (TString sTOWER="TOWER_CEMC", const double z_shift=0, const int n_div=1)
TGraphErrors * FitProfile (const TH2 *h2)
Variables
TFile * _file0 = NULL
TTree * T = NULL
TString cuts = ""
Function Documentation
void DrawEMCalTower (const TString infile = "/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2017/sim/MuonCalib//1k_Muon_DSTReader.root")
Definition at line 28 of file DrawEMCalTower.C.
References _file0, assert, cuts, EMCDistribution_Fast(), event_sel, n, SetOKStyle(), T, and t.
void EMCDistribution (TString gain = "LG", bool log_scale = false)
Definition at line 179 of file DrawEMCalTower.C.
References _file0, cuts, gain, SVM_v1::h, SaveCanvas(), T, t, and QAHistManagerDef::useLogBins().
void EMCDistribution_Fast (TString gain = "LG", bool log_scale = false)
Definition at line 101 of file DrawEMCalTower.C.
References _file0, cuts, gain, SVM_v1::h, h2, SaveCanvas(), T, t, and QAHistManagerDef::useLogBins().
void EMCDistribution_SUM (TString sTOWER = "TOWER_CEMC")
Definition at line 249 of file DrawEMCalTower.C.
References _file0, cuts, SVM_v1::h, SaveCanvas(), T, and t.
void EMCDistributionVSBeam_SUM (TString sTOWER = "TOWER_CEMC", const double z_shift = 0, const int n_div = 1)
Definition at line 345 of file DrawEMCalTower.C.
References _file0, cuts, FitProfile(), SVM_v1::h, SaveCanvas(), T, and t.
TGraphErrors* FitProfile (const TH2 * h2)
Definition at line 447 of file DrawEMCalTower.C.
References f2(), h1, i, n, x, and y.
Variable Documentation
TFile* _file0 = NULL
Definition at line 23 of file DrawEMCalTower.C.
TString cuts = ""
Definition at line 25 of file DrawEMCalTower.C.
TTree* T = NULL
Definition at line 24 of file DrawEMCalTower.C.