Analysis Software: analysis/blob/master/EICAnalysis/macros/diskinematics_fun4all/G4_FastSim_Reco_EIC.C File Reference
G4_FastSim_Reco_EIC.C File Reference
Functions
void FastSim_Reco_EIC (int verbosity=0)
Function Documentation
void FastSim_Reco_EIC (int verbosity = 0)
Definition at line 3 of file G4_FastSim_Reco_EIC.C.
References E, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_do_evt_display(), PHG4TrackFastSim::set_fit_alg_name(), PHG4TrackFastSim::set_pat_rec_hit_finding_eff(), PHG4TrackFastSim::set_primary_assumption_pid(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), PHG4TrackFastSim::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.
Referenced by Fun4All_EICAnalysis_DISReco(), and Fun4All_EICAnalysis_TrackEval().