Analysis Software: analysis/blob/master/Prototype2/EMCal/macros/DrawPrototype2EMCalTower_Resolution.C File Reference
DrawPrototype2EMCalTower_Resolution.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <TLatex.h>
#include <TGraphErrors.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawPrototype2EMCalTower_Resolution (const TString base="/gpfs/mnt/gpfs02/sphenix/user/jinhuang/Prototype_2016/Production_0417_CEMC_MIP_set2_v3/", TString cut="col1_row2_5x5_Valid_HODO_center_col1_row2")
vector< double > GetOnePlot (const TString base, const int run, TString cut)
Function Documentation
void DrawPrototype2EMCalTower_Resolution (const TString base = "/gpfs/mnt/gpfs02/sphenix/user/jinhuang/Prototype_2016/Production_0417_CEMC_MIP_set2_v3/", TString cut = "col1_row2_5x5_Valid_HODO_center_col1_row2")
Definition at line 24 of file DrawPrototype2EMCalTower_Resolution.C.
References E, Es, GetOnePlot(), i, N, runs, SaveCanvas(), SetOKStyle(), t, and v.
vector<double> GetOnePlot (const TString base, const int run, TString cut)
Definition at line 142 of file DrawPrototype2EMCalTower_Resolution.C.
References assert, SVM_v1::h, and v.