Analysis Software: macros/blob/master/macros/g4simulations/G4_DSTReader_EICDetector.C File Reference
G4_DSTReader_EICDetector.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4eval/PHG4DSTReader.h>
#include <string>
Functions
void G4DSTreader_EICDetectorInit ()
void G4DSTreader_EICDetector (const char *outputFile="G4sPHENIXCells.root", int absorberactive=1, bool do_svtx=true, bool do_cemc=true, bool do_hcalin=true, bool do_magnet=true, bool do_hcalout=true, bool do_cemc_twr=true, bool do_hcalin_twr=true, bool do_hcalout_twr=true, bool do_FHCAL=true, bool do_FHCAL_twr=true, bool do_FEMC=true, bool do_FEMC_twr=true, bool do_EEMC=true, bool do_EEMC_twr=true)
Function Documentation
void G4DSTreader_EICDetector (const char * outputFile = "G4sPHENIXCells.root", int absorberactive = 1, bool do_svtx = true, bool do_cemc = true, bool do_hcalin = true, bool do_magnet = true, bool do_hcalout = true, bool do_cemc_twr = true, bool do_hcalin_twr = true, bool do_hcalout_twr = true, bool do_FHCAL = true, bool do_FHCAL_twr = true, bool do_FEMC = true, bool do_FEMC_twr = true, bool do_EEMC = true, bool do_EEMC_twr = true)
debug output on screen?
save raw g4 hits
Definition at line 22 of file G4_DSTReader_EICDetector.C.
References PHG4DSTReader::AddNode(), PHG4DSTReader::AddTower(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHG4DSTReader::set_tower_zero_sup(), and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), and Fun4All_G4_EICDetector_RICH().
void G4DSTreader_EICDetectorInit ()
Definition at line 20 of file G4_DSTReader_EICDetector.C.