Analysis Software: analysis/blob/master/EMCal-analysis/macro/DrawEcal_Likelihood.C File Reference
DrawEcal_Likelihood.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawEcal_Likelihood (TString base_dir="../..//sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString pid="e-", TString kine_config="eta0_8GeV", int eval_mode=1)
void EP_LL_Distribution (TString infile)
void Edep_LL_Distribution (TString infile)
void Edep_Distribution (TString infile)
void ShowerShape_Checks (TString infile, TCut good_track_cut)
void Edep_Checks (TString infile, TCut good_track_cut)
void Ep_Checks (TString infile, TCut good_track_cut)
TGraphErrors * Distribution2Efficiency (TH1F *hCEMC3_Max)
Variables
TFile * _file0 = NULL
TTree * T = NULL
TString cuts = ""
Function Documentation
TGraphErrors* Distribution2Efficiency (TH1F * hCEMC3_Max)
Definition at line 518 of file DrawEcal_Likelihood.C.
References A, assert, i, n, and z.
void DrawEcal_Likelihood (TString base_dir = "../..//sPHENIX_work/production_analysis_cemc2x2/emcstudies/pidstudies/spacal2d/fieldmap/", TString pid = "e-", TString kine_config = "eta0_8GeV", int eval_mode = 1)
Definition at line 26 of file DrawEcal_Likelihood.C.
References _file0, assert, cuts, Edep_Checks(), Edep_Distribution(), Edep_LL_Distribution(), Ep_Checks(), EP_LL_Distribution(), event_sel, n, pid, SetOKStyle(), T, and t.
void Edep_Checks (TString infile, TCut good_track_cut)
Definition at line 367 of file DrawEcal_Likelihood.C.
References _file0, cuts, Distribution2Efficiency(), SaveCanvas(), and T.
Referenced by DrawEcal_Likelihood(), and DrawEcal_pDST().
void Edep_Distribution (TString infile)
Definition at line 251 of file DrawEcal_Likelihood.C.
References _file0, cuts, SaveCanvas(), and T.
Referenced by DrawEcal_Likelihood().
void Edep_LL_Distribution (TString infile)
Definition at line 192 of file DrawEcal_Likelihood.C.
References _file0, cuts, Distribution2Efficiency(), SaveCanvas(), and T.
Referenced by DrawEcal_Likelihood().
void Ep_Checks (TString infile, TCut good_track_cut)
Definition at line 471 of file DrawEcal_Likelihood.C.
References _file0, cuts, Distribution2Efficiency(), SaveCanvas(), and T.
Referenced by DrawEcal_Likelihood().
void EP_LL_Distribution (TString infile)
Definition at line 133 of file DrawEcal_Likelihood.C.
References _file0, cuts, Distribution2Efficiency(), SaveCanvas(), and T.
Referenced by DrawEcal_Likelihood().
void ShowerShape_Checks (TString infile, TCut good_track_cut)
Definition at line 292 of file DrawEcal_Likelihood.C.
References _file0, cuts, r, SaveCanvas(), and T.
Variable Documentation
TFile* _file0 = NULL
Definition at line 21 of file DrawEcal_Likelihood.C.
TString cuts = ""
Definition at line 23 of file DrawEcal_Likelihood.C.
TTree* T = NULL
Definition at line 22 of file DrawEcal_Likelihood.C.