Analysis Software: PHG4Prototype2HcalCellReco Class Reference
PHG4Prototype2HcalCellReco Class Reference
#include <prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4Prototype2HcalCellReco.h>
Public Member Functions
PHG4Prototype2HcalCellReco (const std::string &name="Prototype2HcalCELLRECO")
virtual ~PHG4Prototype2HcalCellReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
void SetDefaultParameters ()
void Detector (const std::string &d)
void checkenergy (const int i=1)
void set_timing_window (const double tmi, const double tma)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Private Member Functions
int CheckEnergy (PHCompositeNode *topNode)
Private Attributes
std::string m_Detector
std::string m_HitNodeName
std::string m_CellNodeName
int m_CheckEnergyConservationFlag
double m_Tmin
double m_Tmax
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 13 of file PHG4Prototype2HcalCellReco.h.
Constructor & Destructor Documentation
PHG4Prototype2HcalCellReco::PHG4Prototype2HcalCellReco (const std::string & name = "Prototype2HcalCELLRECO")
Definition at line 42 of file PHG4Prototype2HcalCellReco.cc.
References PHParameterInterface::InitializeParameters().
virtual PHG4Prototype2HcalCellReco::~PHG4Prototype2HcalCellReco () inline virtual
Definition at line 18 of file PHG4Prototype2HcalCellReco.h.
Member Function Documentation
void PHG4Prototype2HcalCellReco::checkenergy (const int i = 1) inline
Definition at line 28 of file PHG4Prototype2HcalCellReco.h.
References i, and m_CheckEnergyConservationFlag.
int PHG4Prototype2HcalCellReco::CheckEnergy (PHCompositeNode * topNode) private
Definition at line 200 of file PHG4Prototype2HcalCellReco.cc.
References PHG4HitContainer::getHits(), m_CellNodeName, m_HitNodeName, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void PHG4Prototype2HcalCellReco::Detector (const std::string & d) inline
Definition at line 27 of file PHG4Prototype2HcalCellReco.h.
References d, and m_Detector.
Referenced by Fun4All_G4_Prototype2(), Fun4All_G4_Prototype3(), and Fun4All_G4_Prototype4().
int PHG4Prototype2HcalCellReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 52 of file PHG4Prototype2HcalCellReco.cc.
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHParameterInterface::get_double_param(), Fun4AllServer::instance(), m_CellNodeName, m_Detector, m_HitNodeName, m_Tmax, m_Tmin, PHWHERE, Fun4AllServer::Print(), PHParameterInterface::PutOnParNode(), PHParameterInterface::SaveToNodeTree(), and PHParameterInterface::UpdateParametersWithMacro().
int PHG4Prototype2HcalCellReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 118 of file PHG4Prototype2HcalCellReco.cc.
References PHG4ScintillatorSlatContainer::AddScintillatorSlat(), CheckEnergy(), COLUMNDIM, Fun4AllReturnCodes::EVENT_OK, PHG4ScintillatorSlatDefs::genkey(), PHG4HitContainer::getHits(), PHG4HitContainer::getLayers(), m_CellNodeName, m_CheckEnergyConservationFlag, m_HitNodeName, m_Tmax, m_Tmin, Fun4AllBase::Name(), ROWDIM, slatarray, and Fun4AllBase::Verbosity().
void PHG4Prototype2HcalCellReco::set_timing_window (const double tmi, const double tma)
Definition at line 244 of file PHG4Prototype2HcalCellReco.cc.
References PHParameterInterface::set_double_param().
void PHG4Prototype2HcalCellReco::SetDefaultParameters () virtual
Implements PHParameterInterface.
Definition at line 237 of file PHG4Prototype2HcalCellReco.cc.
References PHParameterInterface::set_default_double_param().
Member Data Documentation
std::string PHG4Prototype2HcalCellReco::m_CellNodeName private
Definition at line 35 of file PHG4Prototype2HcalCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
int PHG4Prototype2HcalCellReco::m_CheckEnergyConservationFlag private
Definition at line 36 of file PHG4Prototype2HcalCellReco.h.
Referenced by checkenergy(), and process_event().
std::string PHG4Prototype2HcalCellReco::m_Detector private
Definition at line 33 of file PHG4Prototype2HcalCellReco.h.
Referenced by Detector(), and InitRun().
std::string PHG4Prototype2HcalCellReco::m_HitNodeName private
Definition at line 34 of file PHG4Prototype2HcalCellReco.h.
Referenced by CheckEnergy(), InitRun(), and process_event().
double PHG4Prototype2HcalCellReco::m_Tmax private
Definition at line 39 of file PHG4Prototype2HcalCellReco.h.
Referenced by InitRun(), and process_event().
double PHG4Prototype2HcalCellReco::m_Tmin private
Definition at line 38 of file PHG4Prototype2HcalCellReco.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4Prototype2HcalCellReco.h
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4Prototype2HcalCellReco.cc