Analysis Software: G4HitTTree Class Reference
G4HitTTree Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4histos/G4HitTTree.h>
Public Member Functions
G4HitTTree (const std::string &name="HITTTREE")
virtual ~G4HitTTree ()
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
Called at the end of all processing.
void Detector (const std::string &det)
void BlackHoleName (const std::string &bh)
void SaveHits (const int i=1)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
std::string _detector
std::string _outnodename
std::string _hitnodename
std::string _absorbernodename
std::string _blackholenodename
int savehits
int evtno
Fun4AllHistoManager * hm
TH1 * etot_hist
TH2 * eion_etot_hist
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file G4HitTTree.h.
Constructor & Destructor Documentation
G4HitTTree::G4HitTTree (const std::string & name = "HITTTREE")
Definition at line 27 of file G4HitTTree.cc.
References BlackHoleName().
virtual G4HitTTree::~G4HitTTree () inline virtual
Definition at line 17 of file G4HitTTree.h.
Member Function Documentation
void G4HitTTree::BlackHoleName (const std::string & bh)
Definition at line 138 of file G4HitTTree.cc.
References _blackholenodename.
Referenced by G4HitTTree().
void G4HitTTree::Detector (const std::string & det)
Definition at line 130 of file G4HitTTree.cc.
References _absorbernodename, _detector, _hitnodename, and _outnodename.
Referenced by G4TTree(), and MyHitTTree().
int G4HitTTree::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 123 of file G4HitTTree.cc.
References Fun4AllHistoManager::dumpHistos(), and hm.
int G4HitTTree::Init (PHCompositeNode * topNode) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 38 of file G4HitTTree.cc.
References _detector, _outnodename, PHCompositeNode::addNode(), eion_etot_hist, etot_hist, evtno, PHNodeIterator::findFirst(), hm, and Fun4AllHistoManager::registerHisto().
int G4HitTTree::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 62 of file G4HitTTree.cc.
References _absorbernodename, _blackholenodename, _hitnodename, _outnodename, G4RootHitContainer::AddHit(), eion_etot_hist, etot_hist, evtno, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4HitContainer::getHits(), savehits, G4RootHitContainer::set_eion(), G4RootHitContainer::set_etotal(), G4RootHitContainer::set_event(), and G4RootHitContainer::set_leakage().
void G4HitTTree::SaveHits (const int i = 1) inline
Definition at line 30 of file G4HitTTree.h.
References i, and savehits.
Member Data Documentation
std::string G4HitTTree::_absorbernodename protected
Definition at line 36 of file G4HitTTree.h.
Referenced by Detector(), and process_event().
std::string G4HitTTree::_blackholenodename protected
Definition at line 37 of file G4HitTTree.h.
Referenced by BlackHoleName(), and process_event().
std::string G4HitTTree::_detector protected
Definition at line 33 of file G4HitTTree.h.
Referenced by Detector(), and Init().
std::string G4HitTTree::_hitnodename protected
Definition at line 35 of file G4HitTTree.h.
Referenced by Detector(), and process_event().
std::string G4HitTTree::_outnodename protected
Definition at line 34 of file G4HitTTree.h.
Referenced by Detector(), Init(), and process_event().
TH2* G4HitTTree::eion_etot_hist protected
Definition at line 42 of file G4HitTTree.h.
Referenced by Init(), and process_event().
TH1* G4HitTTree::etot_hist protected
Definition at line 41 of file G4HitTTree.h.
Referenced by Init(), and process_event().
int G4HitTTree::evtno protected
Definition at line 39 of file G4HitTTree.h.
Referenced by Init(), and process_event().
Fun4AllHistoManager* G4HitTTree::hm protected
Definition at line 40 of file G4HitTTree.h.
Referenced by End(), and Init().
int G4HitTTree::savehits protected
Definition at line 38 of file G4HitTTree.h.
Referenced by process_event(), and SaveHits().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4histos/G4HitTTree.h
coresoftware/blob/master/simulation/g4simulation/g4histos/G4HitTTree.cc