Analysis Software: analysis/blob/master/TPC/DAMAlgorithm/Fe55_main.dev20190528.cpp File Reference
Fe55_main.dev20190528.cpp File Reference
#include "../Bias.cpp"
#include <assert.h>
#include <time.h>
#include <TRandom.h>
#include "TMinuit.h"
Classes
class rPad
class Co
class OneHit
class Hits
class Qhit
class Ohit
class SimX
class Fe55
Functions
int Fe55_main (const char *dir, const char *outName="Fe_50V")
double G2DI (double *v, double *par)
int PeakRange (TH1D *hist, double *maxpos, double *Rmin, double *Rmax)
Variables
const double CteX = 0.9999999
const double CteY = 0.9999999
Function Documentation
int Fe55_main (const char * dir, const char * outName = "Fe_50V")
Definition at line 3782 of file Fe55_main.dev20190528.cpp.
References Co::doCTE, Co::doFit, Fe55::Flag, i, KeyList, Nkey, Fe55::Plot_FFT(), Fe55::PlotBase(), Fe55::PlotCTE(), Fe55::PlotHits(), Fe55::PlotProfiles(), Fe55::PlotSpectra(), Fe55::PlotXfit(), Fe55::PlotXlines(), printf(), and Vval.
double G2DI (double * v, double * par)
Definition at line 147 of file Fe55_main.dev20190528.cpp.
References x, and y.
Referenced by Fe55::Fe55(), and Ohit::Ohit().
int PeakRange (TH1D * hist, double * maxpos, double * Rmin, double * Rmax)
Definition at line 779 of file Fe55_main.dev20190528.cpp.
Variable Documentation
const double CteX = 0.9999999
Definition at line 21 of file Fe55_main.dev20190528.cpp.
Referenced by Ohit::Cluster(), and Fe55::PlotXlines().
const double CteY = 0.9999999
Definition at line 22 of file Fe55_main.dev20190528.cpp.
Referenced by Ohit::Cluster(), and Fe55::PlotXlines().