Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/Fun4All_G4_EICDetector_LQ_analysis_nf.C File Reference
Fun4All_G4_EICDetector_LQ_analysis_nf.C File Reference
Functions
int Fun4All_G4_EICDetector_LQ_analysis_nf (string fileindex="1", string n="10", string ebeam="20", string pbeam="250",)
Function Documentation
int Fun4All_G4_EICDetector_LQ_analysis_nf (string fileindex = "1", string n = "10", string ebeam = "20", string pbeam = "250")
Definition at line 1 of file Fun4All_G4_EICDetector_LQ_analysis_nf.C.
References Fun4AllServer::End(), Fun4AllInputManager::fileopen(), G4_Lepto(), HIJetReco(), recoConsts::instance(), Fun4AllServer::instance(), Jet_Eval(), Jet_FwdEval(), Jet_FwdReco(), Jet_Reco(), n, nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), and Fun4AllBase::Verbosity().