Analysis Software: CaloRawClusterEval Class Reference
CaloRawClusterEval Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/CaloRawClusterEval.h>
Public Member Functions
CaloRawClusterEval (PHCompositeNode *topNode, const std::string &caloname)
example caloname: CEMC, HCALIN, HCALOUT
virtual ~CaloRawClusterEval ()
int get_caloid ()
get the hash id for this calorimeter volume
void next_event (PHCompositeNode *topNode)
reinitialize the eval for a new event
void do_caching (bool do_cache)
activate or deactivate the memory caching inside the evaluation module
void set_strict (bool strict)
unsigned int get_errors ()
get a count of the errors discovered thus far
void set_verbosity (int verbosity)
adjust the messaging from the evalutaion module
CaloTruthEval * get_truth_eval ()
get a copy of the lower level truth eval and its memory cache
CaloRawTowerEval * get_rawtower_eval ()
get a copy of the lower level tower eval and its memory cache
bool has_reduced_node_pointers ()
has the eval initialized correctly for reduced sim DST nodes?
std::set< PHG4Shower * > all_truth_primary_showers (RawCluster *cluster)
what primary showers contributed energy to this cluster?
PHG4Shower * max_truth_primary_shower_by_energy (RawCluster *cluster)
which primary shower contributed the most energy to this cluster?
std::set< RawCluster * > all_clusters_from (PHG4Shower *primary)
what clusters did this primary truth shower contribute energy to?
RawCluster * best_cluster_from (PHG4Shower *primary)
which cluster did this primary truth shower contribute the most energy to?
float get_energy_contribution (RawCluster *cluster, PHG4Shower *primary)
how much energy did this primary truth shower contribute to this cluster
std::set< PHG4Particle * > all_truth_primary_particles (RawCluster *cluster)
what particles contributed energy to this cluster?
PHG4Particle * max_truth_primary_particle_by_energy (RawCluster *cluster)
which particle contributed the most energy to this cluster?
std::set< RawCluster * > all_clusters_from (PHG4Particle *primary)
what clusters did this primary truth particle contribute energy to?
RawCluster * best_cluster_from (PHG4Particle *primary)
which cluster did this primary truth particle contribute the most energy to?
float get_energy_contribution (RawCluster *cluster, PHG4Particle *primary)
how much energy did this primary truth particle contribute to this cluster
bool has_full_node_pointers ()
has the eval initialized correctly for full sim DST nodes?
std::set< PHG4Hit * > all_truth_hits (RawCluster *cluster)
what truth hits contributed energy to this tower?
Private Member Functions
void get_node_pointers (PHCompositeNode *topNode)
Private Attributes
std::string _caloname
CaloRawTowerEval _towereval
RawClusterContainer * _clusters
RawTowerContainer * _towers
bool _strict
int _verbosity
unsigned int _errors
bool _do_cache
std::map< RawCluster
*, std::set< PHG4Shower * > > _cache_all_truth_primary_showers
std::map< RawCluster
*, PHG4Shower * > _cache_max_truth_primary_shower_by_energy
std::map< PHG4Shower
*, std::set< RawCluster * > > _cache_all_clusters_from_primary_shower
std::map< PHG4Shower
*, RawCluster * > _cache_best_cluster_from_primary_shower
std::map< std::pair
< RawCluster *, PHG4Shower * >
, float > _cache_get_energy_contribution_primary_shower
std::map< RawCluster
*, std::set< PHG4Particle * > > _cache_all_truth_primary_particles
std::map< RawCluster
*, PHG4Particle * > _cache_max_truth_primary_particle_by_energy
std::map< PHG4Particle
*, std::set< RawCluster * > > _cache_all_clusters_from_primary_particle
std::map< PHG4Particle
*, RawCluster * > _cache_best_cluster_from_primary_particle
std::map< std::pair
< RawCluster *, PHG4Particle * >
, float > _cache_get_energy_contribution_primary_particle
std::map< RawCluster
*, std::set< PHG4Hit * > > _cache_all_truth_hits
Detailed Description
Definition at line 20 of file CaloRawClusterEval.h.
Constructor & Destructor Documentation
CaloRawClusterEval::CaloRawClusterEval (PHCompositeNode * topNode, const std::string & caloname)
example caloname: CEMC, HCALIN, HCALOUT
Definition at line 23 of file CaloRawClusterEval.cc.
References get_node_pointers().
CaloRawClusterEval::~CaloRawClusterEval () virtual
Definition at line 47 of file CaloRawClusterEval.cc.
References _errors, and _verbosity.
Member Function Documentation
std::set< RawCluster * > CaloRawClusterEval::all_clusters_from (PHG4Shower * primary)
what clusters did this primary truth shower contribute energy to?
Definition at line 234 of file CaloRawClusterEval.cc.
References _cache_all_clusters_from_primary_shower, _clusters, _do_cache, _errors, _strict, all_truth_primary_showers(), assert, CaloTruthEval::get_primary_shower(), get_truth_eval(), RawClusterContainer::getClusters(), has_reduced_node_pointers(), and CaloTruthEval::is_primary().
Referenced by all_clusters_from(), best_cluster_from(), and CaloEvaluator::printOutputInfo().
std::set< RawCluster * > CaloRawClusterEval::all_clusters_from (PHG4Particle * primary)
what clusters did this primary truth particle contribute energy to?
Definition at line 567 of file CaloRawClusterEval.cc.
References _cache_all_clusters_from_primary_particle, _do_cache, _errors, _strict, all_clusters_from(), assert, CaloTruthEval::get_primary_particle(), CaloTruthEval::get_primary_shower(), get_truth_eval(), has_reduced_node_pointers(), and CaloTruthEval::is_primary().
std::set< PHG4Hit * > CaloRawClusterEval::all_truth_hits (RawCluster * cluster)
what truth hits contributed energy to this tower?
Definition at line 746 of file CaloRawClusterEval.cc.
References _cache_all_truth_hits, _do_cache, _errors, _strict, _towers, CaloRawTowerEval::all_truth_hits(), assert, get_rawtower_eval(), RawCluster::get_towers(), RawTowerContainer::getTower(), and has_full_node_pointers().
Referenced by JetRecoEval::all_truth_hits().
std::set< PHG4Particle * > CaloRawClusterEval::all_truth_primary_particles (RawCluster * cluster)
what particles contributed energy to this cluster?
Definition at line 462 of file CaloRawClusterEval.cc.
References _cache_all_truth_primary_particles, _do_cache, _errors, _strict, all_truth_primary_showers(), assert, CaloTruthEval::get_primary_particle(), get_truth_eval(), and has_reduced_node_pointers().
Referenced by JetRecoEval::all_truth_particles().
std::set< PHG4Shower * > CaloRawClusterEval::all_truth_primary_showers (RawCluster * cluster)
what primary showers contributed energy to this cluster?
Definition at line 96 of file CaloRawClusterEval.cc.
References _cache_all_truth_primary_showers, _do_cache, _errors, _strict, _towereval, _towers, CaloRawTowerEval::all_truth_primary_showers(), assert, RawCluster::get_towers(), RawTowerContainer::getTower(), and has_reduced_node_pointers().
Referenced by all_clusters_from(), all_truth_primary_particles(), JetRecoEval::all_truth_showers(), and max_truth_primary_shower_by_energy().
RawCluster * CaloRawClusterEval::best_cluster_from (PHG4Shower * primary)
which cluster did this primary truth shower contribute the most energy to?
Definition at line 314 of file CaloRawClusterEval.cc.
References _cache_best_cluster_from_primary_shower, _do_cache, _errors, _strict, all_clusters_from(), assert, energy, get_energy_contribution(), CaloTruthEval::get_primary_shower(), get_truth_eval(), and has_reduced_node_pointers().
Referenced by best_cluster_from(), CaloEvaluator::fillOutputNtuples(), STACalorimeterCharacterization::process_event(), and QAG4SimulationCalorimeter::process_event_Cluster().
RawCluster * CaloRawClusterEval::best_cluster_from (PHG4Particle * primary)
which cluster did this primary truth particle contribute the most energy to?
Definition at line 620 of file CaloRawClusterEval.cc.
References _cache_best_cluster_from_primary_particle, _do_cache, _errors, _strict, assert, best_cluster_from(), CaloTruthEval::get_primary_particle(), CaloTruthEval::get_primary_shower(), get_truth_eval(), and has_reduced_node_pointers().
void CaloRawClusterEval::do_caching (bool do_cache) inline
activate or deactivate the memory caching inside the evaluation module
Definition at line 34 of file CaloRawClusterEval.h.
References _do_cache, _towereval, and CaloRawTowerEval::do_caching().
Referenced by CaloEvalStack::do_caching().
int CaloRawClusterEval::get_caloid () inline
get the hash id for this calorimeter volume
Definition at line 28 of file CaloRawClusterEval.h.
References CaloTruthEval::get_caloid(), and get_truth_eval().
float CaloRawClusterEval::get_energy_contribution (RawCluster * cluster, PHG4Shower * primary)
how much energy did this primary truth shower contribute to this cluster
Definition at line 389 of file CaloRawClusterEval.cc.
References _cache_get_energy_contribution_primary_shower, _do_cache, _errors, _strict, _towers, assert, energy, CaloRawTowerEval::get_energy_contribution(), CaloTruthEval::get_primary_shower(), get_rawtower_eval(), RawCluster::get_towers(), get_truth_eval(), RawTowerContainer::getTower(), and has_reduced_node_pointers().
Referenced by best_cluster_from(), CaloEvaluator::fillOutputNtuples(), get_energy_contribution(), JetRecoEval::get_energy_contribution(), max_truth_primary_shower_by_energy(), and CaloEvaluator::printOutputInfo().
float CaloRawClusterEval::get_energy_contribution (RawCluster * cluster, PHG4Particle * primary)
how much energy did this primary truth particle contribute to this cluster
Definition at line 672 of file CaloRawClusterEval.cc.
References _cache_get_energy_contribution_primary_particle, _do_cache, _errors, _strict, assert, energy, get_energy_contribution(), CaloTruthEval::get_primary_particle(), CaloTruthEval::get_primary_shower(), get_truth_eval(), and has_reduced_node_pointers().
unsigned int CaloRawClusterEval::get_errors () inline
get a count of the errors discovered thus far
Definition at line 49 of file CaloRawClusterEval.h.
References _errors, _towereval, and CaloRawTowerEval::get_errors().
Referenced by CaloEvalStack::get_errors().
void CaloRawClusterEval::get_node_pointers (PHCompositeNode * topNode) private
Definition at line 821 of file CaloRawClusterEval.cc.
References _caloname, _clusters, and _towers.
Referenced by CaloRawClusterEval(), and next_event().
CaloRawTowerEval* CaloRawClusterEval::get_rawtower_eval () inline
get a copy of the lower level tower eval and its memory cache
Definition at line 62 of file CaloRawClusterEval.h.
References _towereval.
Referenced by all_truth_hits(), get_energy_contribution(), CaloEvalStack::get_rawtower_eval(), has_full_node_pointers(), and has_reduced_node_pointers().
CaloTruthEval* CaloRawClusterEval::get_truth_eval () inline
get a copy of the lower level truth eval and its memory cache
Definition at line 59 of file CaloRawClusterEval.h.
References _towereval, and CaloRawTowerEval::get_truth_eval().
Referenced by all_clusters_from(), all_truth_primary_particles(), best_cluster_from(), get_caloid(), get_energy_contribution(), CaloEvalStack::get_truth_eval(), and max_truth_primary_particle_by_energy().
bool CaloRawClusterEval::has_full_node_pointers ()
has the eval initialized correctly for full sim DST nodes?
Definition at line 729 of file CaloRawClusterEval.cc.
References _clusters, _strict, _towers, assert, and get_rawtower_eval().
Referenced by all_truth_hits().
bool CaloRawClusterEval::has_reduced_node_pointers ()
has the eval initialized correctly for reduced sim DST nodes?
Definition at line 79 of file CaloRawClusterEval.cc.
References _clusters, _strict, _towers, assert, and get_rawtower_eval().
Referenced by all_clusters_from(), all_truth_primary_particles(), all_truth_primary_showers(), best_cluster_from(), get_energy_contribution(), max_truth_primary_particle_by_energy(), and max_truth_primary_shower_by_energy().
PHG4Particle * CaloRawClusterEval::max_truth_primary_particle_by_energy (RawCluster * cluster)
which particle contributed the most energy to this cluster?
Definition at line 526 of file CaloRawClusterEval.cc.
References _cache_max_truth_primary_particle_by_energy, _do_cache, _errors, _strict, assert, CaloTruthEval::get_primary_particle(), get_truth_eval(), has_reduced_node_pointers(), and max_truth_primary_shower_by_energy().
Referenced by CaloEvaluator::fillOutputNtuples(), and DISKinematicsReco::InsertCandidateFromCluster().
PHG4Shower * CaloRawClusterEval::max_truth_primary_shower_by_energy (RawCluster * cluster)
which primary shower contributed the most energy to this cluster?
Definition at line 171 of file CaloRawClusterEval.cc.
References _cache_max_truth_primary_shower_by_energy, _do_cache, _errors, _strict, all_truth_primary_showers(), assert, get_energy_contribution(), and has_reduced_node_pointers().
Referenced by max_truth_primary_particle_by_energy().
void CaloRawClusterEval::next_event (PHCompositeNode * topNode)
reinitialize the eval for a new event
Definition at line 58 of file CaloRawClusterEval.cc.
References _cache_all_clusters_from_primary_particle, _cache_all_clusters_from_primary_shower, _cache_all_truth_hits, _cache_all_truth_primary_particles, _cache_all_truth_primary_showers, _cache_best_cluster_from_primary_particle, _cache_best_cluster_from_primary_shower, _cache_get_energy_contribution_primary_particle, _cache_get_energy_contribution_primary_shower, _cache_max_truth_primary_particle_by_energy, _cache_max_truth_primary_shower_by_energy, _towereval, get_node_pointers(), and CaloRawTowerEval::next_event().
Referenced by CaloEvalStack::next_event().
void CaloRawClusterEval::set_strict (bool strict) inline
strict mode will assert when an error is detected non-strict mode will notice and report at the End()
Definition at line 42 of file CaloRawClusterEval.h.
References _strict, _towereval, and CaloRawTowerEval::set_strict().
Referenced by CaloEvalStack::set_strict().
void CaloRawClusterEval::set_verbosity (int verbosity) inline
adjust the messaging from the evalutaion module
Definition at line 52 of file CaloRawClusterEval.h.
References _towereval, _verbosity, CaloRawTowerEval::set_verbosity(), and verbosity.
Referenced by STACalorimeterCharacterization::process_event(), and CaloEvalStack::set_verbosity().
Member Data Documentation
std::map<PHG4Particle*, std::set<RawCluster*> > CaloRawClusterEval::_cache_all_clusters_from_primary_particle private
Definition at line 132 of file CaloRawClusterEval.h.
Referenced by all_clusters_from(), and next_event().
std::map<PHG4Shower*, std::set<RawCluster*> > CaloRawClusterEval::_cache_all_clusters_from_primary_shower private
Definition at line 126 of file CaloRawClusterEval.h.
Referenced by all_clusters_from(), and next_event().
std::map<RawCluster*, std::set<PHG4Hit*> > CaloRawClusterEval::_cache_all_truth_hits private
Definition at line 136 of file CaloRawClusterEval.h.
Referenced by all_truth_hits(), and next_event().
std::map<RawCluster*, std::set<PHG4Particle*> > CaloRawClusterEval::_cache_all_truth_primary_particles private
Definition at line 130 of file CaloRawClusterEval.h.
Referenced by all_truth_primary_particles(), and next_event().
std::map<RawCluster*, std::set<PHG4Shower*> > CaloRawClusterEval::_cache_all_truth_primary_showers private
Definition at line 124 of file CaloRawClusterEval.h.
Referenced by all_truth_primary_showers(), and next_event().
std::map<PHG4Particle*, RawCluster*> CaloRawClusterEval::_cache_best_cluster_from_primary_particle private
Definition at line 133 of file CaloRawClusterEval.h.
Referenced by best_cluster_from(), and next_event().
std::map<PHG4Shower*, RawCluster*> CaloRawClusterEval::_cache_best_cluster_from_primary_shower private
Definition at line 127 of file CaloRawClusterEval.h.
Referenced by best_cluster_from(), and next_event().
std::map<std::pair<RawCluster*, PHG4Particle*>, float> CaloRawClusterEval::_cache_get_energy_contribution_primary_particle private
Definition at line 134 of file CaloRawClusterEval.h.
Referenced by get_energy_contribution(), and next_event().
std::map<std::pair<RawCluster*, PHG4Shower*>, float> CaloRawClusterEval::_cache_get_energy_contribution_primary_shower private
Definition at line 128 of file CaloRawClusterEval.h.
Referenced by get_energy_contribution(), and next_event().
std::map<RawCluster*, PHG4Particle*> CaloRawClusterEval::_cache_max_truth_primary_particle_by_energy private
Definition at line 131 of file CaloRawClusterEval.h.
Referenced by max_truth_primary_particle_by_energy(), and next_event().
std::map<RawCluster*, PHG4Shower*> CaloRawClusterEval::_cache_max_truth_primary_shower_by_energy private
Definition at line 125 of file CaloRawClusterEval.h.
Referenced by max_truth_primary_shower_by_energy(), and next_event().
std::string CaloRawClusterEval::_caloname private
Definition at line 114 of file CaloRawClusterEval.h.
Referenced by get_node_pointers().
RawClusterContainer* CaloRawClusterEval::_clusters private
Definition at line 116 of file CaloRawClusterEval.h.
Referenced by all_clusters_from(), get_node_pointers(), has_full_node_pointers(), and has_reduced_node_pointers().
bool CaloRawClusterEval::_do_cache private
Definition at line 123 of file CaloRawClusterEval.h.
Referenced by all_clusters_from(), all_truth_hits(), all_truth_primary_particles(), all_truth_primary_showers(), best_cluster_from(), do_caching(), get_energy_contribution(), max_truth_primary_particle_by_energy(), and max_truth_primary_shower_by_energy().
unsigned int CaloRawClusterEval::_errors private
Definition at line 121 of file CaloRawClusterEval.h.
Referenced by all_clusters_from(), all_truth_hits(), all_truth_primary_particles(), all_truth_primary_showers(), best_cluster_from(), get_energy_contribution(), get_errors(), max_truth_primary_particle_by_energy(), max_truth_primary_shower_by_energy(), and ~CaloRawClusterEval().
bool CaloRawClusterEval::_strict private
Definition at line 119 of file CaloRawClusterEval.h.
Referenced by all_clusters_from(), all_truth_hits(), all_truth_primary_particles(), all_truth_primary_showers(), best_cluster_from(), get_energy_contribution(), has_full_node_pointers(), has_reduced_node_pointers(), max_truth_primary_particle_by_energy(), max_truth_primary_shower_by_energy(), and set_strict().
CaloRawTowerEval CaloRawClusterEval::_towereval private
Definition at line 115 of file CaloRawClusterEval.h.
Referenced by all_truth_primary_showers(), do_caching(), get_errors(), get_rawtower_eval(), get_truth_eval(), next_event(), set_strict(), and set_verbosity().
RawTowerContainer* CaloRawClusterEval::_towers private
Definition at line 117 of file CaloRawClusterEval.h.
Referenced by all_truth_hits(), all_truth_primary_showers(), get_energy_contribution(), get_node_pointers(), has_full_node_pointers(), and has_reduced_node_pointers().
int CaloRawClusterEval::_verbosity private
Definition at line 120 of file CaloRawClusterEval.h.
Referenced by set_verbosity(), and ~CaloRawClusterEval().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloRawClusterEval.h
coresoftware/blob/master/simulation/g4simulation/g4eval/CaloRawClusterEval.cc