Analysis Software: PHG4TpcElectronDrift Class Reference
PHG4TpcElectronDrift Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h>
Public Member Functions
PHG4TpcElectronDrift (const std::string &name="PHG4TpcElectronDrift")
virtual ~PHG4TpcElectronDrift ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void SetDefaultParameters ()
void Detector (const std::string &d)
std::string Detector () const
void set_seed (const unsigned int iseed)
void MapToPadPlane (const double x, const double y, const double z, PHG4HitContainer::ConstIterator hiter, TNtuple *ntpad, TNtuple *nthit)
void registerPadPlane (PHG4TpcPadPlane *padplane)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Private Attributes
TrkrHitSetContainer * hitsetcontainer
TrkrHitSetContainer * temp_hitsetcontainer
TrkrHitTruthAssoc * hittruthassoc
PHG4TpcPadPlane * padplane
TH1 * dlong
TH1 * dtrans
TNtuple * nt
TNtuple * nthit
TNtuple * ntpad
std::string detector
std::string hitnodename
std::string seggeonodename
unsigned int seed
double diffusion_trans
double added_smear_sigma_trans
double diffusion_long
double added_smear_sigma_long
double drift_velocity
double tpc_length
double electrons_per_gev
double min_active_radius
double max_active_radius
double min_time
double max_time
gsl_rng * RandomGenerator
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 26 of file PHG4TpcElectronDrift.h.
Constructor & Destructor Documentation
PHG4TpcElectronDrift::PHG4TpcElectronDrift (const std::string & name = "PHG4TpcElectronDrift")
Definition at line 59 of file PHG4TpcElectronDrift.cc.
References PHParameterInterface::InitializeParameters(), RandomGenerator, and set_seed().
PHG4TpcElectronDrift::~PHG4TpcElectronDrift () virtual
Definition at line 85 of file PHG4TpcElectronDrift.cc.
References padplane, RandomGenerator, and temp_hitsetcontainer.
Member Function Documentation
void PHG4TpcElectronDrift::Detector (const std::string & d) inline
Definition at line 38 of file PHG4TpcElectronDrift.h.
References d.
Referenced by Fun4All_G4_TPC(), and Tracking_Cells().
std::string PHG4TpcElectronDrift::Detector () const inline
Definition at line 39 of file PHG4TpcElectronDrift.h.
References detector.
Referenced by registerPadPlane().
int PHG4TpcElectronDrift::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 473 of file PHG4TpcElectronDrift.cc.
References Fun4AllReturnCodes::EVENT_OK, nt, nthit, ntpad, and Fun4AllBase::Verbosity().
int PHG4TpcElectronDrift::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 92 of file PHG4TpcElectronDrift.cc.
References Fun4AllReturnCodes::EVENT_OK, SubsysReco::Init(), and padplane.
int PHG4TpcElectronDrift::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 99 of file PHG4TpcElectronDrift.cc.
References Fun4AllReturnCodes::ABORTRUN, added_smear_sigma_long, added_smear_sigma_trans, PHCompositeNode::addNode(), assert, PHParametersContainer::CreateAndFillFrom(), PHG4TpcPadPlane::CreateReadoutGeometry(), detector, diffusion_long, diffusion_trans, dlong, drift_velocity, dtrans, electrons_per_gev, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHParameterInterface::get_double_param(), PHParameters::get_double_param(), PHParametersContainer::GetParameters(), hitnodename, hitsetcontainer, hittruthassoc, PHG4TpcPadPlane::InitRun(), Fun4AllServer::instance(), max_active_radius, max_time, min_active_radius, min_time, Fun4AllBase::Name(), nt, nthit, ntpad, padplane, PHWHERE, PdbParameterMapContainer::print(), PHParametersContainer::Print(), PHParameterInterface::PutOnParNode(), Fun4AllServer::registerHisto(), PHParameterInterface::SaveToNodeTree(), seggeonodename, tpc_length, PHParameterInterface::UpdateParametersWithMacro(), and Fun4AllBase::Verbosity().
void PHG4TpcElectronDrift::MapToPadPlane (const double x, const double y, const double z, PHG4HitContainer::ConstIterator hiter, TNtuple * ntpad, TNtuple * nthit)
Definition at line 466 of file PHG4TpcElectronDrift.cc.
References hittruthassoc, PHG4TpcPadPlane::MapToPadPlane(), padplane, and temp_hitsetcontainer.
Referenced by process_event().
int PHG4TpcElectronDrift::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 245 of file PHG4TpcElectronDrift.cc.
References added_smear_sigma_long, added_smear_sigma_trans, TrkrHit::addEnergy(), diffusion_long, diffusion_trans, drift_velocity, electrons_per_gev, Fun4AllReturnCodes::EVENT_OK, TrkrHitTruthAssoc::findOrAddAssoc(), TrkrHitSetContainer::findOrAddHitSet(), TrkrHit::getAdc(), TrkrHit::getEnergy(), PHG4HitContainer::getHits(), TrkrHitSet::getHits(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), TpcDefs::getPad(), TpcDefs::getSectorId(), TpcDefs::getSide(), TpcDefs::getTBin(), hitnodename, hitsetcontainer, hittruthassoc, i, TrkrHitTruthAssoc::identify(), M_PI, MapToPadPlane(), max_active_radius, max_time, nt, nthit, ntpad, RandomGenerator, TrkrHitSetContainer::Reset(), temp_hitsetcontainer, tpc_length, TrkrDefs::tpcId, and Fun4AllBase::Verbosity().
void PHG4TpcElectronDrift::registerPadPlane (PHG4TpcPadPlane * padplane)
Definition at line 523 of file PHG4TpcElectronDrift.cc.
References Detector(), PHG4TpcPadPlane::Detector(), padplane, and PHG4TpcPadPlane::UpdateInternalParameters().
Referenced by Fun4All_G4_TPC(), and Tracking_Cells().
void PHG4TpcElectronDrift::set_seed (const unsigned int iseed)
Definition at line 487 of file PHG4TpcElectronDrift.cc.
References RandomGenerator, and seed.
Referenced by PHG4TpcElectronDrift().
void PHG4TpcElectronDrift::SetDefaultParameters () virtual
Implements PHParameterInterface.
Definition at line 493 of file PHG4TpcElectronDrift.cc.
References CF4_dEdx, CF4_NTotal, Ne_dEdx, Ne_NTotal, and PHParameterInterface::set_default_double_param().
Member Data Documentation
double PHG4TpcElectronDrift::added_smear_sigma_long private
Definition at line 61 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
double PHG4TpcElectronDrift::added_smear_sigma_trans private
Definition at line 59 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
std::string PHG4TpcElectronDrift::detector private
Definition at line 54 of file PHG4TpcElectronDrift.h.
Referenced by Detector(), and InitRun().
double PHG4TpcElectronDrift::diffusion_long private
Definition at line 60 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
double PHG4TpcElectronDrift::diffusion_trans private
Definition at line 58 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
TH1* PHG4TpcElectronDrift::dlong private
Definition at line 49 of file PHG4TpcElectronDrift.h.
Referenced by InitRun().
double PHG4TpcElectronDrift::drift_velocity private
Definition at line 62 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
TH1* PHG4TpcElectronDrift::dtrans private
Definition at line 50 of file PHG4TpcElectronDrift.h.
Referenced by InitRun().
double PHG4TpcElectronDrift::electrons_per_gev private
Definition at line 64 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
std::string PHG4TpcElectronDrift::hitnodename private
Definition at line 55 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
TrkrHitSetContainer* PHG4TpcElectronDrift::hitsetcontainer private
Definition at line 45 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
TrkrHitTruthAssoc* PHG4TpcElectronDrift::hittruthassoc private
Definition at line 47 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), MapToPadPlane(), and process_event().
double PHG4TpcElectronDrift::max_active_radius private
Definition at line 66 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
double PHG4TpcElectronDrift::max_time private
Definition at line 68 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
double PHG4TpcElectronDrift::min_active_radius private
Definition at line 65 of file PHG4TpcElectronDrift.h.
Referenced by InitRun().
double PHG4TpcElectronDrift::min_time private
Definition at line 67 of file PHG4TpcElectronDrift.h.
Referenced by InitRun().
TNtuple* PHG4TpcElectronDrift::nt private
Definition at line 51 of file PHG4TpcElectronDrift.h.
Referenced by End(), InitRun(), and process_event().
TNtuple* PHG4TpcElectronDrift::nthit private
Definition at line 52 of file PHG4TpcElectronDrift.h.
Referenced by End(), InitRun(), and process_event().
TNtuple* PHG4TpcElectronDrift::ntpad private
Definition at line 53 of file PHG4TpcElectronDrift.h.
Referenced by End(), InitRun(), and process_event().
PHG4TpcPadPlane* PHG4TpcElectronDrift::padplane private
Definition at line 48 of file PHG4TpcElectronDrift.h.
Referenced by Init(), InitRun(), MapToPadPlane(), registerPadPlane(), and ~PHG4TpcElectronDrift().
gsl_rng* PHG4TpcElectronDrift::RandomGenerator private
Definition at line 71 of file PHG4TpcElectronDrift.h.
Referenced by PHG4TpcElectronDrift(), process_event(), set_seed(), and ~PHG4TpcElectronDrift().
unsigned int PHG4TpcElectronDrift::seed private
Definition at line 57 of file PHG4TpcElectronDrift.h.
Referenced by set_seed().
std::string PHG4TpcElectronDrift::seggeonodename private
Definition at line 56 of file PHG4TpcElectronDrift.h.
Referenced by InitRun().
TrkrHitSetContainer* PHG4TpcElectronDrift::temp_hitsetcontainer private
Definition at line 46 of file PHG4TpcElectronDrift.h.
Referenced by MapToPadPlane(), process_event(), and ~PHG4TpcElectronDrift().
double PHG4TpcElectronDrift::tpc_length private
Definition at line 63 of file PHG4TpcElectronDrift.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc