Analysis Software: online_distribution/blob/master/newbasic/Cpacket.h File Reference
Cpacket.h File Reference
#include "phenixOnline.h"
#include "packetPublic.h"
#include "packetHdr.h"
#include "formatError.h"
Functions
INLINE_P LOGIC_ret currentPacket (PACKET_ptr)
INLINE_P VALUE_ret getPacketLength (PACKET_ptr)
INLINE_P VALUE_ret getPacketHdrLength (PACKET_ptr)
INLINE_P VALUE_ret getPacketHdrVersion (PACKET_ptr)
INLINE_P LOGIC_ret setPacketHdrVersion (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketHdrLength (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketLength (PACKET_ptr, PHDWORD)
PTR_ret findPacketEnd (PACKET_ptr)
PTR_ret findPacketDataStart (PACKET_ptr)
VALUE_ret extendPacketDataBlock (const PACKET_ptr, UINT, int)
VALUE_ret extendPacketDebugBlock (const PACKET_ptr, UINT, int)
VALUE_ret extendPacketErrorBlock (const PACKET_ptr, UINT, int)
VALUE_ret extendPacketLength (const PACKET_ptr, UINT, int)
LOGIC_ret removePacketPadding (PACKET_ptr)
INLINE_P void endianSwapError (PACKETERROR *outError, PACKETERROR *inError)
VALUE_ret makePacketHdr (const PACKET_ptr, UINT)
VALUE_ret getPacketDataLength (const PACKET_ptr)
VALUE_ret getPacketDebugLength (const PACKET_ptr)
VALUE_ret getPacketErrorLength (const PACKET_ptr)
VALUE_ret getPacketNumErrors (const PACKET_ptr)
VALUE_ret getPacketPadding (const PACKET_ptr)
VALUE_ret getPacketId (const PACKET_ptr)
VALUE_ret getPacketStatus (PACKET_ptr)
VALUE_ret getPacketStructure (const PACKET_ptr)
VALUE_ret getPacketEndianism (const PACKET_ptr)
VALUE_ret getPacketDataDescrLength (const PACKET_ptr)
LOGIC_ret setPacketDebugLength (PACKET_ptr, UINT)
LOGIC_ret setPacketNumErrors (PACKET_ptr, UINT)
LOGIC_ret setPacketEndianism (PACKET_ptr, UINT)
LOGIC_ret setPacketId (PACKET_ptr, UINT)
LOGIC_ret setPacketPadding (PACKET_ptr, UINT)
LOGIC_ret setPacketStructure (PACKET_ptr, UINT)
LOGIC_ret setPacketStatus (PACKET_ptr, UINT)
LOGIC_ret setPacketErrorLength (PACKET_ptr, UINT)
LOGIC_ret setPacketDataDescrLength (PACKET_ptr, UINT)
VALUE_ret orPacketStatus (PACKET_ptr, UINT)
LOGIC_ret validPacketHdr (PACKET_ptr)
LOGIC_ret emptyPacket (PACKET_ptr)
PTR_ret findPacketDataDescr (PACKET_ptr)
PTR_ret findPacketDataEnd (PACKET_ptr)
PTR_ret findPacketDebugStart (PACKET_ptr)
PTR_ret findPacketErrorStart (PACKET_ptr)
VALUE_ret adjustPacketDataLength (PACKET_ptr, int)
VALUE_ret adjustPacketErrorLength (PACKET_ptr, int)
VALUE_ret adjustPacketDebugLength (PACKET_ptr, int)
Function Documentation
VALUE_ret adjustPacketDataLength (PACKET_ptr , int)
Definition at line 563 of file Cpacket.C.
References adjustPacketDataLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by extendPacketDataBlock().
VALUE_ret adjustPacketDebugLength (PACKET_ptr , int)
Definition at line 572 of file Cpacket.C.
References adjustPacketDebugLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by extendPacketDebugBlock().
VALUE_ret adjustPacketErrorLength (PACKET_ptr , int)
Definition at line 581 of file Cpacket.C.
References adjustPacketErrorLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by extendPacketErrorBlock().
INLINE_D LOGIC_ret currentPacket (PACKET_ptr packet_ptr)
Definition at line 255 of file Cpacket.h.
References currentPacketHdrVersion, and getPacketHdrVersion().
LOGIC_ret emptyPacket (PACKET_ptr)
Definition at line 554 of file Cpacket.C.
References emptyPacketV, getPacketHdrVersion(), logicFailure, and valueFailure.
Referenced by startUnstructDataWrite(), and storePacketHits().
INLINE_D void endianSwapError (PACKETERROR * outError, PACKETERROR * inError)
Definition at line 261 of file Cpacket.h.
References endianSwapErrorV1().
VALUE_ret extendPacketDataBlock (const PACKET_ptr , UINT , int)
Definition at line 67 of file Cpacket.C.
References adjustPacketDataLength(), extendPacketLength(), and valueFailure.
Referenced by startUnstructDataWrite(), and storePacketHits().
VALUE_ret extendPacketDebugBlock (const PACKET_ptr , UINT , int)
Definition at line 90 of file Cpacket.C.
References adjustPacketDebugLength(), extendPacketLength(), and valueFailure.
Referenced by reservePacketDebugData().
VALUE_ret extendPacketErrorBlock (const PACKET_ptr , UINT , int)
Definition at line 113 of file Cpacket.C.
References adjustPacketErrorLength(), extendPacketLength(), and valueFailure.
Referenced by appendPacketError().
VALUE_ret extendPacketLength (const PACKET_ptr , UINT , int)
Definition at line 136 of file Cpacket.C.
References FORMAT_ERR_BUFFER_OVERFLOW, getPacketLength(), packetQuantum, removePacketPadding(), setPacketError(), setPacketLength(), setPacketPadding(), and valueFailure.
Referenced by extendPacketDataBlock(), extendPacketDebugBlock(), and extendPacketErrorBlock().
PTR_ret findPacketDataDescr (PACKET_ptr)
Definition at line 535 of file Cpacket.C.
References findPacketDataDescrV, getPacketHdrVersion(), ptrFailure, and valueFailure.
Referenced by getUnstructPacketDataPadding(), getUnstructPacketHitFormat(), getUnstructPacketWordSize(), makeUnstructPacketDataDescr(), setUnstructPacketDataPadding(), setUnstructPacketHitFormat(), and setUnstructPacketWordSize().
PTR_ret findPacketDataEnd (PACKET_ptr)
Definition at line 508 of file Cpacket.C.
References findPacketDataEndV, getPacketHdrVersion(), ptrFailure, and valueFailure.
PTR_ret findPacketDataStart (PACKET_ptr)
Definition at line 53 of file Cpacket.C.
References getPacketDataDescrLength(), getPacketHdrLength(), ptrFailure, and validPacketHdr().
Referenced by Packet_fvtx_dcm0::calculate_parity(), Packet_id2evt::decode(), Packet_id4evt::decode(), Packet_iddigitizerv2::decode(), Packet_gl1psum::decode(), Packet_gl1_evclocks::decode(), Packet_idcstr::decode(), Packet_cdevir::decode(), Packet_idcdevdescr::decode(), Packet_starscaler::decode(), Packet_cdevwcm::decode(), Packet_cdevmadch::decode(), Packet_cdevbpm::decode(), Packet_cdevdvm::decode(), Packet_cdevpoltarget::decode(), Packet_hbd_fpgashort::decode(), Packet_hbd_fpga::decode(), Packet_cdevbuckets::decode(), Packet_cdevring::decode(), Packet_fvtx_dcm0::decode(), Packet_cdevringnopol::decode(), Packet_gl1p::decode(), Packet_id4scaler::decode(), Packet_cdevpolarimeter::decode(), Packet_gl1::decode(), Packet_fvtx_dcm0::decode_misc(), Packet_gl1p::demangle(), Packet_gl1::demangle(), Packet_gl1_evclocks::dump(), Packet_idcdevdescr::dump(), Packet_gl1p::dump(), Packet_id4scaler::dump(), Packet_gl1::dump(), dumpPacket(), fetchPacketHits(), Packet_w1::gdump(), Packet_w2::gdump(), Packet_w4::gdump(), Packet_gl1_evclocks::iValue(), Packet_id4scaler::iValue(), Packet_id4scaler::lValue(), Packet_A::standardIntArray(), startUnstructDataWrite(), and storePacketHits().
PTR_ret findPacketDebugStart (PACKET_ptr)
Definition at line 517 of file Cpacket.C.
References findPacketDebugStartV, getPacketHdrVersion(), ptrFailure, and valueFailure.
Referenced by Packet_A::dumpDebugBlock(), and reservePacketDebugData().
PTR_ret findPacketEnd (PACKET_ptr)
Definition at line 35 of file Cpacket.C.
References getPacketLength(), logicFailure, ptrFailure, setPacketError(), setPacketSuccess(), validPacketHdr(), and valueFailure.
Referenced by findNextFramePacket(), finishUnstructDataWrite(), makeEmptyPacket(), and makeUnstructPacket().
PTR_ret findPacketErrorStart (PACKET_ptr)
Definition at line 526 of file Cpacket.C.
References findPacketErrorStartV, getPacketHdrVersion(), ptrFailure, and valueFailure.
Referenced by appendPacketError(), and Packet_A::dumpErrorBlock().
VALUE_ret getPacketDataDescrLength (const PACKET_ptr)
Definition at line 412 of file Cpacket.C.
References getPacketDataDescrLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by findPacketDataStart(), and Packet_A::fullIdentify().
VALUE_ret getPacketDataLength (const PACKET_ptr)
Definition at line 339 of file Cpacket.C.
References getPacketDataLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by Packet_A::getDataLength(), and getUnstructPacketDataLengthBytes().
VALUE_ret getPacketDebugLength (const PACKET_ptr)
Definition at line 359 of file Cpacket.C.
References getPacketDebugLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by dumpPacket(), Packet_A::fullIdentify(), Packet_A::getDebugLength(), and getPacketV1DataLength().
VALUE_ret getPacketEndianism (const PACKET_ptr)
Definition at line 394 of file Cpacket.C.
References getPacketEndianismV, getPacketHdrVersion(), and valueFailure.
Referenced by dumpPacket(), and Packet_A::fullIdentify().
VALUE_ret getPacketErrorLength (const PACKET_ptr)
Definition at line 349 of file Cpacket.C.
References getPacketErrorLengthV, getPacketHdrVersion(), and valueFailure.
Referenced by appendPacketError(), dumpPacket(), Packet_A::fullIdentify(), Packet_A::getErrorLength(), getPacketV1DataLength(), and reservePacketDebugData().
INLINE_D VALUE_ret getPacketHdrLength (PACKET_ptr packet_ptr)
Definition at line 171 of file Cpacket.h.
References getBitsMACRO, PACKET_HDR_LENGTH_MASK, PACKET_HDR_LENGTH_OFFSET_IN_DWORD, and PACKET_HDR_LENGTH_OFFSET_OF_DWORD.
Referenced by dumpPacket(), emptyPacketV1(), findPacketDataStart(), findPacketV1DataStart(), Packet_A::fullIdentify(), getPacketV1DataLength(), and validPacketV1Hdr().
INLINE_D VALUE_ret getPacketHdrVersion (PACKET_ptr packet_ptr)
Definition at line 191 of file Cpacket.h.
References FORMAT_ERR_INVALID_PACKET_HDRVERSION, getBitsMACRO, numPacketVersions, PACKET_HDR_VERSION_MASK, PACKET_HDR_VERSION_OFFSET_IN_DWORD, PACKET_HDR_VERSION_OFFSET_OF_DWORD, setPacketError(), and valueFailure.
Referenced by adjustPacketDataLength(), adjustPacketDebugLength(), adjustPacketErrorLength(), currentPacket(), dumpPacket(), emptyPacket(), findPacketDataDescr(), findPacketDataEnd(), findPacketDebugStart(), findPacketErrorStart(), Packet_A::fullIdentify(), getPacketDataDescrLength(), getPacketDataLength(), getPacketDebugLength(), getPacketEndianism(), getPacketErrorLength(), getPacketId(), getPacketNumErrors(), getPacketPadding(), getPacketStatus(), getPacketStructure(), orPacketStatus(), setPacketDataDescrLength(), setPacketDebugLenth(), setPacketEndianism(), setPacketErrorLength(), setPacketId(), setPacketPadding(), setPacketStatus(), setPacketStructure(), and validPacketHdr().
VALUE_ret getPacketId (const PACKET_ptr)
Definition at line 377 of file Cpacket.C.
References getPacketHdrVersion(), getPacketIdV, and valueFailure.
Referenced by A_Event::createMap(), dumpPacket(), findFramePacketId(), findNextFramePacketId(), Packet_A::fullIdentify(), and Packet_A::getIdentifier().
INLINE_D VALUE_ret getPacketLength (PACKET_ptr packet_ptr)
Definition at line 180 of file Cpacket.h.
References getWordMACRO, PACKET_LENGTH_OFFSET_OF_DWORD, and valueFailure.
Referenced by dumpPacket(), emptyPacketV1(), extendPacketLength(), findPacketEnd(), findPacketV1DebugStart(), findPacketV1ErrorStart(), Packet_A::fullIdentify(), Packet_A::getLength(), getPacketV1DataLength(), removePacketPadding(), startUnstructDataWrite(), and storePacketHits().
VALUE_ret getPacketNumErrors (const PACKET_ptr)
Definition at line 368 of file Cpacket.C.
References getPacketHdrVersion(), getPacketNumErrorsV, and valueFailure.
VALUE_ret getPacketPadding (const PACKET_ptr)
Definition at line 403 of file Cpacket.C.
References getPacketHdrVersion(), getPacketPaddingV, and valueFailure.
Referenced by dumpPacket(), Packet_A::fullIdentify(), getPacketV1DataLength(), Packet_A::getPadding(), and removePacketPadding().
VALUE_ret getPacketStatus (PACKET_ptr)
Definition at line 321 of file Cpacket.C.
References getPacketHdrVersion(), getPacketStatusV, and valueFailure.
Referenced by dumpPacket(), and Packet_A::fullIdentify().
VALUE_ret getPacketStructure (const PACKET_ptr)
Definition at line 386 of file Cpacket.C.
References getPacketHdrVersion(), getPacketStructureV, and valueFailure.
Referenced by X_Event::change_hf(), dumpPacket(), fetchPacketHits(), A_Event::getPacketList(), getPacketV1DataLength(), Packet_A::getStructure(), A_Event::makePacket(), startUnstructDataWrite(), and storePacketHits().
VALUE_ret makePacketHdr (const PACKET_ptr , UINT)
Definition at line 311 of file Cpacket.C.
References currentPacketHdrVersion, makePacketHdrV, and valueFailure.
Referenced by makeEmptyPacket(), and makeUnstructPacket().
VALUE_ret orPacketStatus (PACKET_ptr , UINT)
Definition at line 330 of file Cpacket.C.
References getPacketHdrVersion(), orPacketStatusV, and valueFailure.
LOGIC_ret removePacketPadding (PACKET_ptr)
Definition at line 183 of file Cpacket.C.
References FORMAT_ERR_HDR_INCONSISTENCY, getPacketLength(), getPacketPadding(), logicFailure, logicSuccess, packetV1HdrLength, setPacketError(), setPacketLength(), and setPacketPadding().
Referenced by extendPacketLength().
LOGIC_ret setPacketDataDescrLength (PACKET_ptr , UINT)
Definition at line 499 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketDataDescrLengthV, and valueFailure.
Referenced by makeUnstructPacketDataDescr().
LOGIC_ret setPacketDebugLength (PACKET_ptr , UINT)
LOGIC_ret setPacketEndianism (PACKET_ptr , UINT)
Definition at line 463 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketEndianismV, and valueFailure.
Referenced by makePacketV1Hdr().
LOGIC_ret setPacketErrorLength (PACKET_ptr , UINT)
Definition at line 490 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketErrorLengthV, and valueFailure.
INLINE_D LOGIC_ret setPacketHdrLength (PACKET_ptr packet_ptr, UINT hdrLength)
Definition at line 239 of file Cpacket.h.
References FALSE, FORMAT_ERR_INVALID_HDRLENGTH, PACKET_HDR_LENGTH_MASK, PACKET_HDR_LENGTH_OFFSET_IN_DWORD, PACKET_HDR_LENGTH_OFFSET_OF_DWORD, setBitsMACRO, setPacketError(), and TRUE.
Referenced by makePacketV1Hdr().
INLINE_D LOGIC_ret setPacketHdrVersion (PACKET_ptr packet_ptr, UINT hdrVersion)
Definition at line 207 of file Cpacket.h.
References FORMAT_ERR_INVALID_PACKET_HDRVERSION, numPacketVersions, PACKET_HDR_VERSION_MASK, PACKET_HDR_VERSION_OFFSET_IN_DWORD, PACKET_HDR_VERSION_OFFSET_OF_DWORD, setBitsMACRO, setPacketError(), TRUE, and valueFailure.
Referenced by makePacketV1Hdr().
LOGIC_ret setPacketId (PACKET_ptr , UINT)
Definition at line 445 of file Cpacket.C.
References getPacketHdrVersion(), setPacketIdV, and valueFailure.
Referenced by X_Event::change_id(), makeEmptyPacket(), and makeUnstructPacket().
INLINE_D LOGIC_ret setPacketLength (PACKET_ptr packet_ptr, PHDWORD length)
Definition at line 223 of file Cpacket.h.
References FALSE, FORMAT_ERR_LENGTH_OVERFLOW, PACKET_LENGTH_OFFSET_OF_DWORD, setPacketError(), setWordMACRO, and TRUE.
Referenced by extendPacketLength(), makePacketV1Hdr(), and removePacketPadding().
LOGIC_ret setPacketNumErrors (PACKET_ptr , UINT)
LOGIC_ret setPacketPadding (PACKET_ptr , UINT)
Definition at line 472 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketPaddingV, and valueFailure.
Referenced by extendPacketLength(), and removePacketPadding().
LOGIC_ret setPacketStatus (PACKET_ptr , UINT)
Definition at line 481 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketStatusV, and valueFailure.
LOGIC_ret setPacketStructure (PACKET_ptr , UINT)
Definition at line 454 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, setPacketStructureV, and valueFailure.
Referenced by makeUnstructPacket(), and setPacketUnstructured().
LOGIC_ret validPacketHdr (PACKET_ptr)
Definition at line 545 of file Cpacket.C.
References getPacketHdrVersion(), logicFailure, NUM_PACKET_VERSIONS, and validPacketHdrV.
Referenced by dumpPacket(), fetchPacketHits(), findFramePacketIndex(), findPacketDataStart(), findPacketEnd(), isLastFramePacket(), and storePacketHits().