Analysis Software: CaloTriggerSim Class Reference
CaloTriggerSim Class Reference
simple trigger emulation
#include <coresoftware/blob/master/offline/packages/trigger/CaloTriggerSim.h>
Public Member Functions
CaloTriggerSim (const std::string &name="CaloTriggerSim")
virtual ~CaloTriggerSim ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
void set_truncation (const int emulate_truncation)
double truncate_8bit (const double raw_E) const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNode (PHCompositeNode *topNode)
void FillNode (PHCompositeNode *topNode)
Private Attributes
int m_EmulateTruncationFlag
int m_EMCAL_1x1_NETA
int m_EMCAL_1x1_NPHI
int m_EMCAL_2x2_NETA
int m_EMCAL_2x2_NPHI
int m_EMCAL_4x4_NETA
int m_EMCAL_4x4_NPHI
float m_EMCAL_2x2_BEST_E
float m_EMCAL_2x2_BEST_PHI
float m_EMCAL_2x2_BEST_ETA
float m_EMCAL_4x4_BEST_E
float m_EMCAL_4x4_BEST_PHI
float m_EMCAL_4x4_BEST_ETA
float m_EMCAL_4x4_BEST2_E
float m_EMCAL_4x4_BEST2_PHI
float m_EMCAL_4x4_BEST2_ETA
float m_FULLCALO_PHI_START
float m_FULLCALO_PHI_END
int m_FULLCALO_0p1x0p1_NETA
int m_FULLCALO_0p1x0p1_NPHI
int m_FULLCALO_0p2x0p2_NETA
int m_FULLCALO_0p2x0p2_NPHI
int m_FULLCALO_0p4x0p4_NETA
int m_FULLCALO_0p4x0p4_NPHI
int m_FULLCALO_0p6x0p6_NETA
int m_FULLCALO_0p6x0p6_NPHI
int m_FULLCALO_0p8x0p8_NETA
int m_FULLCALO_0p8x0p8_NPHI
int m_FULLCALO_1p0x1p0_NETA
int m_FULLCALO_1p0x1p0_NPHI
float m_FULLCALO_0p2x0p2_BEST_E
float m_FULLCALO_0p2x0p2_BEST_PHI
float m_FULLCALO_0p2x0p2_BEST_ETA
float m_FULLCALO_0p4x0p4_BEST_E
float m_FULLCALO_0p4x0p4_BEST_PHI
float m_FULLCALO_0p4x0p4_BEST_ETA
float m_FULLCALO_0p6x0p6_BEST_E
float m_FULLCALO_0p6x0p6_BEST_PHI
float m_FULLCALO_0p6x0p6_BEST_ETA
float m_FULLCALO_0p8x0p8_BEST_E
float m_FULLCALO_0p8x0p8_BEST_PHI
float m_FULLCALO_0p8x0p8_BEST_ETA
float m_FULLCALO_1p0x1p0_BEST_E
float m_FULLCALO_1p0x1p0_BEST_PHI
float m_FULLCALO_1p0x1p0_BEST_ETA
std::vector< std::vector
< double > > m_EMCAL_1x1_MAP
std::vector< std::vector
< double > > m_EMCAL_2x2_MAP
std::vector< std::vector
< double > > m_EMCAL_4x4_MAP
std::vector< std::vector
< double > > m_FULLCALO_0p1x0p1_MAP
std::vector< std::vector
< double > > m_FULLCALO_0p2x0p2_MAP
std::vector< std::vector
< double > > m_FULLCALO_0p4x0p4_MAP
std::vector< std::vector
< double > > m_FULLCALO_0p6x0p6_MAP
std::vector< std::vector
< double > > m_FULLCALO_0p8x0p8_MAP
std::vector< std::vector
< double > > m_FULLCALO_1p0x1p0_MAP
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
simple trigger emulation
This module constructs calo-based trigger signatures
Definition at line 26 of file CaloTriggerSim.h.
Constructor & Destructor Documentation
CaloTriggerSim::CaloTriggerSim (const std::string & name = "CaloTriggerSim")
Definition at line 36 of file CaloTriggerSim.cc.
virtual CaloTriggerSim::~CaloTriggerSim () inline virtual
Definition at line 30 of file CaloTriggerSim.h.
Member Function Documentation
int CaloTriggerSim::CreateNode (PHCompositeNode * topNode) private
Definition at line 781 of file CaloTriggerSim.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_EmulateTruncationFlag, and PHWHERE.
Referenced by InitRun().
void CaloTriggerSim::FillNode (PHCompositeNode * topNode) private
Definition at line 818 of file CaloTriggerSim.cc.
References m_EMCAL_2x2_BEST_E, m_EMCAL_2x2_BEST_ETA, m_EMCAL_2x2_BEST_PHI, m_EMCAL_4x4_BEST2_E, m_EMCAL_4x4_BEST2_ETA, m_EMCAL_4x4_BEST2_PHI, m_EMCAL_4x4_BEST_E, m_EMCAL_4x4_BEST_ETA, m_EMCAL_4x4_BEST_PHI, m_EmulateTruncationFlag, m_FULLCALO_0p2x0p2_BEST_E, m_FULLCALO_0p2x0p2_BEST_ETA, m_FULLCALO_0p2x0p2_BEST_PHI, m_FULLCALO_0p4x0p4_BEST_E, m_FULLCALO_0p4x0p4_BEST_ETA, m_FULLCALO_0p4x0p4_BEST_PHI, m_FULLCALO_0p6x0p6_BEST_E, m_FULLCALO_0p6x0p6_BEST_ETA, m_FULLCALO_0p6x0p6_BEST_PHI, m_FULLCALO_0p8x0p8_BEST_E, m_FULLCALO_0p8x0p8_BEST_ETA, m_FULLCALO_0p8x0p8_BEST_PHI, m_FULLCALO_1p0x1p0_BEST_E, m_FULLCALO_1p0x1p0_BEST_ETA, m_FULLCALO_1p0x1p0_BEST_PHI, CaloTriggerInfo::set_best2_EMCal_4x4_E(), CaloTriggerInfo::set_best2_EMCal_4x4_eta(), CaloTriggerInfo::set_best2_EMCal_4x4_phi(), CaloTriggerInfo::set_best_EMCal_2x2_E(), CaloTriggerInfo::set_best_EMCal_2x2_eta(), CaloTriggerInfo::set_best_EMCal_2x2_phi(), CaloTriggerInfo::set_best_EMCal_4x4_E(), CaloTriggerInfo::set_best_EMCal_4x4_eta(), CaloTriggerInfo::set_best_EMCal_4x4_phi(), CaloTriggerInfo::set_best_FullCalo_0p2x0p2_E(), CaloTriggerInfo::set_best_FullCalo_0p2x0p2_eta(), CaloTriggerInfo::set_best_FullCalo_0p2x0p2_phi(), CaloTriggerInfo::set_best_FullCalo_0p4x0p4_E(), CaloTriggerInfo::set_best_FullCalo_0p4x0p4_eta(), CaloTriggerInfo::set_best_FullCalo_0p4x0p4_phi(), CaloTriggerInfo::set_best_FullCalo_0p6x0p6_E(), CaloTriggerInfo::set_best_FullCalo_0p6x0p6_eta(), CaloTriggerInfo::set_best_FullCalo_0p6x0p6_phi(), CaloTriggerInfo::set_best_FullCalo_0p8x0p8_E(), CaloTriggerInfo::set_best_FullCalo_0p8x0p8_eta(), CaloTriggerInfo::set_best_FullCalo_0p8x0p8_phi(), CaloTriggerInfo::set_best_FullCalo_1p0x1p0_E(), CaloTriggerInfo::set_best_FullCalo_1p0x1p0_eta(), and CaloTriggerInfo::set_best_FullCalo_1p0x1p0_phi().
Referenced by process_event().
int CaloTriggerSim::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 98 of file CaloTriggerSim.cc.
References CreateNode().
int CaloTriggerSim::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 103 of file CaloTriggerSim.cc.
References Fun4AllReturnCodes::EVENT_OK, FillNode(), RawTower::get_energy(), RawTowerGeom::get_eta(), RawTowerGeomContainer_Cylinderv1::get_etabin(), RawTowerGeomContainer_Cylinderv1::get_etabins(), RawTowerGeomContainer_Cylinderv1::get_etacenter(), RawTower::get_key(), RawTowerGeom::get_phi(), RawTowerGeomContainer_Cylinderv1::get_phibin(), RawTowerGeomContainer_Cylinderv1::get_phibins(), RawTowerGeomContainer_Cylinderv1::get_phicenter(), RawTowerGeomContainerv1::get_tower_geometry(), RawTowerContainer::getTowers(), m_EMCAL_1x1_MAP, m_EMCAL_1x1_NETA, m_EMCAL_1x1_NPHI, m_EMCAL_2x2_BEST_E, m_EMCAL_2x2_BEST_ETA, m_EMCAL_2x2_BEST_PHI, m_EMCAL_2x2_MAP, m_EMCAL_2x2_NETA, m_EMCAL_2x2_NPHI, m_EMCAL_4x4_BEST2_E, m_EMCAL_4x4_BEST2_ETA, m_EMCAL_4x4_BEST2_PHI, m_EMCAL_4x4_BEST_E, m_EMCAL_4x4_BEST_ETA, m_EMCAL_4x4_BEST_PHI, m_EMCAL_4x4_MAP, m_EMCAL_4x4_NETA, m_EMCAL_4x4_NPHI, m_EmulateTruncationFlag, m_FULLCALO_0p1x0p1_MAP, m_FULLCALO_0p1x0p1_NETA, m_FULLCALO_0p1x0p1_NPHI, m_FULLCALO_0p2x0p2_BEST_E, m_FULLCALO_0p2x0p2_BEST_ETA, m_FULLCALO_0p2x0p2_BEST_PHI, m_FULLCALO_0p2x0p2_MAP, m_FULLCALO_0p2x0p2_NETA, m_FULLCALO_0p2x0p2_NPHI, m_FULLCALO_0p4x0p4_BEST_E, m_FULLCALO_0p4x0p4_BEST_ETA, m_FULLCALO_0p4x0p4_BEST_PHI, m_FULLCALO_0p4x0p4_MAP, m_FULLCALO_0p4x0p4_NETA, m_FULLCALO_0p4x0p4_NPHI, m_FULLCALO_0p6x0p6_BEST_E, m_FULLCALO_0p6x0p6_BEST_ETA, m_FULLCALO_0p6x0p6_BEST_PHI, m_FULLCALO_0p6x0p6_MAP, m_FULLCALO_0p6x0p6_NETA, m_FULLCALO_0p6x0p6_NPHI, m_FULLCALO_0p8x0p8_BEST_E, m_FULLCALO_0p8x0p8_BEST_ETA, m_FULLCALO_0p8x0p8_BEST_PHI, m_FULLCALO_0p8x0p8_MAP, m_FULLCALO_0p8x0p8_NETA, m_FULLCALO_0p8x0p8_NPHI, m_FULLCALO_1p0x1p0_BEST_E, m_FULLCALO_1p0x1p0_BEST_ETA, m_FULLCALO_1p0x1p0_BEST_PHI, m_FULLCALO_1p0x1p0_MAP, m_FULLCALO_1p0x1p0_NETA, m_FULLCALO_1p0x1p0_NPHI, m_FULLCALO_PHI_END, m_FULLCALO_PHI_START, M_PI, RawTowerContainer::size(), truncate_8bit(), and Fun4AllBase::Verbosity().
void CaloTriggerSim::set_truncation (const int emulate_truncation) inline
Definition at line 35 of file CaloTriggerSim.h.
References m_EmulateTruncationFlag.
double CaloTriggerSim::truncate_8bit (const double raw_E) const
Definition at line 91 of file CaloTriggerSim.cc.
References min.
Referenced by process_event().
Member Data Documentation
std::vector<std::vector<double> > CaloTriggerSim::m_EMCAL_1x1_MAP private
Definition at line 109 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EMCAL_1x1_NETA private
Definition at line 44 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EMCAL_1x1_NPHI private
Definition at line 45 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_EMCAL_2x2_BEST_E private
Definition at line 53 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_2x2_BEST_ETA private
Definition at line 55 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_2x2_BEST_PHI private
Definition at line 54 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_EMCAL_2x2_MAP private
Definition at line 110 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EMCAL_2x2_NETA private
Definition at line 47 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EMCAL_2x2_NPHI private
Definition at line 48 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_EMCAL_4x4_BEST2_E private
Definition at line 61 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_4x4_BEST2_ETA private
Definition at line 63 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_4x4_BEST2_PHI private
Definition at line 62 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_4x4_BEST_E private
Definition at line 57 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_4x4_BEST_ETA private
Definition at line 59 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_EMCAL_4x4_BEST_PHI private
Definition at line 58 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_EMCAL_4x4_MAP private
Definition at line 111 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EMCAL_4x4_NETA private
Definition at line 50 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EMCAL_4x4_NPHI private
Definition at line 51 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_EmulateTruncationFlag private
Definition at line 42 of file CaloTriggerSim.h.
Referenced by CreateNode(), FillNode(), process_event(), and set_truncation().
std::vector<std::vector<double> > CaloTriggerSim::m_FULLCALO_0p1x0p1_MAP private
Definition at line 112 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p1x0p1_NETA private
Definition at line 70 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p1x0p1_NPHI private
Definition at line 71 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_0p2x0p2_BEST_E private
Definition at line 89 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p2x0p2_BEST_ETA private
Definition at line 91 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p2x0p2_BEST_PHI private
Definition at line 90 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_FULLCALO_0p2x0p2_MAP private
Definition at line 113 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p2x0p2_NETA private
Definition at line 73 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p2x0p2_NPHI private
Definition at line 74 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_0p4x0p4_BEST_E private
Definition at line 93 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p4x0p4_BEST_ETA private
Definition at line 95 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p4x0p4_BEST_PHI private
Definition at line 94 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_FULLCALO_0p4x0p4_MAP private
Definition at line 114 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p4x0p4_NETA private
Definition at line 76 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p4x0p4_NPHI private
Definition at line 77 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_0p6x0p6_BEST_E private
Definition at line 97 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p6x0p6_BEST_ETA private
Definition at line 99 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p6x0p6_BEST_PHI private
Definition at line 98 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_FULLCALO_0p6x0p6_MAP private
Definition at line 115 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p6x0p6_NETA private
Definition at line 79 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p6x0p6_NPHI private
Definition at line 80 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_0p8x0p8_BEST_E private
Definition at line 101 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p8x0p8_BEST_ETA private
Definition at line 103 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_0p8x0p8_BEST_PHI private
Definition at line 102 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_FULLCALO_0p8x0p8_MAP private
Definition at line 116 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p8x0p8_NETA private
Definition at line 82 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_0p8x0p8_NPHI private
Definition at line 83 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_1p0x1p0_BEST_E private
Definition at line 105 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_1p0x1p0_BEST_ETA private
Definition at line 107 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
float CaloTriggerSim::m_FULLCALO_1p0x1p0_BEST_PHI private
Definition at line 106 of file CaloTriggerSim.h.
Referenced by FillNode(), and process_event().
std::vector<std::vector<double> > CaloTriggerSim::m_FULLCALO_1p0x1p0_MAP private
Definition at line 117 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_1p0x1p0_NETA private
Definition at line 85 of file CaloTriggerSim.h.
Referenced by process_event().
int CaloTriggerSim::m_FULLCALO_1p0x1p0_NPHI private
Definition at line 86 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_PHI_END private
Definition at line 67 of file CaloTriggerSim.h.
Referenced by process_event().
float CaloTriggerSim::m_FULLCALO_PHI_START private
Definition at line 66 of file CaloTriggerSim.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trigger/CaloTriggerSim.h
coresoftware/blob/master/offline/packages/trigger/CaloTriggerSim.cc