Analysis Software: PHG4GDMLWriteMaterials Class Reference
PHG4GDMLWriteMaterials Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.hh>
Public Member Functions
void AddIsotope (const G4Isotope *const)
void AddElement (const G4Element *const)
void AddMaterial (const G4Material *const)
virtual void MaterialsWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWriteDefine
G4ThreeVector GetAngles (const G4RotationMatrix &)
void ScaleWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &scl)
void RotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void PositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void FirstrotationWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &rot)
void FirstpositionWrite (xercesc::DOMElement *element, const G4String &name, const G4ThreeVector &pos)
void AddPosition (const G4String &name, const G4ThreeVector &pos)
virtual void DefineWrite (xercesc::DOMElement *)
Public Member Functions inherited from PHG4GDMLWrite
G4Transform3D Write (const G4String &filename, const G4LogicalVolume *const topLog, const G4String &schemaPath, const G4int depth, G4bool storeReferences=true)
void AddModule (const G4VPhysicalVolume *const topVol)
void AddModule (const G4int depth)
void AddAuxiliary (PHG4GDMLAuxStructType myaux)
virtual void SolidsWrite (xercesc::DOMElement *)=0
virtual void StructureWrite (xercesc::DOMElement *)=0
virtual G4Transform3D TraverseVolumeTree (const G4LogicalVolume *const, const G4int)=0
virtual void SurfacesWrite ()=0
virtual void SetupWrite (xercesc::DOMElement *, const G4LogicalVolume *const)=0
virtual void ExtensionWrite (xercesc::DOMElement *)
virtual void UserinfoWrite (xercesc::DOMElement *)
virtual void AddExtension (xercesc::DOMElement *, const G4LogicalVolume *const)
G4String GenerateName (const G4String &, const void *const)
Protected Member Functions
PHG4GDMLWriteMaterials ()
virtual ~PHG4GDMLWriteMaterials ()
void AtomWrite (xercesc::DOMElement *, const G4double &)
void DWrite (xercesc::DOMElement *, const G4double &)
void PWrite (xercesc::DOMElement *, const G4double &)
void TWrite (xercesc::DOMElement *, const G4double &)
void MEEWrite (xercesc::DOMElement *, const G4double &)
void IsotopeWrite (const G4Isotope *const)
void ElementWrite (const G4Element *const)
void MaterialWrite (const G4Material *const)
void PropertyWrite (xercesc::DOMElement *, const G4Material *const)
void PropertyVectorWrite (const G4String &, const G4PhysicsOrderedFreeVector *const)
Protected Member Functions inherited from PHG4GDMLWriteDefine
PHG4GDMLWriteDefine ()
virtual ~PHG4GDMLWriteDefine ()
void Scale_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Rotation_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
void Position_vectorWrite (xercesc::DOMElement *, const G4String &, const G4String &, const G4ThreeVector &)
Protected Member Functions inherited from PHG4GDMLWrite
PHG4GDMLWrite ()
virtual ~PHG4GDMLWrite ()
VolumeMapType & VolumeMap ()
xercesc::DOMAttr * NewAttribute (const G4String &, const G4String &)
xercesc::DOMAttr * NewAttribute (const G4String &, const G4double &)
xercesc::DOMElement * NewElement (const G4String &)
G4String Modularize (const G4VPhysicalVolume *const topvol, const G4int depth)
void AddAuxInfo (PHG4GDMLAuxListType *auxInfoList, xercesc::DOMElement *element)
G4bool FileExists (const G4String &) const
PhysVolumeMapType & PvolumeMap ()
DepthMapType & DepthMap ()
Protected Attributes
std::vector< const G4Isotope * > isotopeList
std::vector< const G4Element * > elementList
std::vector< const G4Material * > materialList
xercesc::DOMElement * materialsElement
Protected Attributes inherited from PHG4GDMLWriteDefine
xercesc::DOMElement * defineElement
Protected Attributes inherited from PHG4GDMLWrite
G4String SchemaLocation
xercesc::DOMDocument * doc
xercesc::DOMElement * extElement
xercesc::DOMElement * userinfoElement
XMLCh tempStr [10000]
PHG4GDMLAuxListType auxList
Additional Inherited Members
Static Public Member Functions inherited from PHG4GDMLWrite
static void SetAddPointerToName (G4bool)
Static Protected Attributes inherited from PHG4GDMLWriteDefine
static const G4double kRelativePrecision = DBL_EPSILON
static const G4double kAngularPrecision = DBL_EPSILON
static const G4double kLinearPrecision = DBL_EPSILON
Detailed Description
Definition at line 53 of file PHG4GDMLWriteMaterials.hh.
Constructor & Destructor Documentation
PHG4GDMLWriteMaterials::PHG4GDMLWriteMaterials () protected
Definition at line 46 of file PHG4GDMLWriteMaterials.cc.
PHG4GDMLWriteMaterials::~PHG4GDMLWriteMaterials () protected virtual
Definition at line 51 of file PHG4GDMLWriteMaterials.cc.
Member Function Documentation
void PHG4GDMLWriteMaterials::AddElement (const G4Element * const elementPtr)
Definition at line 297 of file PHG4GDMLWriteMaterials.cc.
References elementList, ElementWrite(), and i.
Referenced by MaterialWrite().
void PHG4GDMLWriteMaterials::AddIsotope (const G4Isotope * const isotopePtr)
Definition at line 287 of file PHG4GDMLWriteMaterials.cc.
References i, isotopeList, and IsotopeWrite().
Referenced by ElementWrite().
void PHG4GDMLWriteMaterials::AddMaterial (const G4Material * const materialPtr)
Definition at line 307 of file PHG4GDMLWriteMaterials.cc.
References i, materialList, and MaterialWrite().
Referenced by PHG4GDMLWriteStructure::TraverseVolumeTree().
void PHG4GDMLWriteMaterials::AtomWrite (xercesc::DOMElement * element, const G4double & a) protected
Definition at line 56 of file PHG4GDMLWriteMaterials.cc.
References g, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by ElementWrite(), IsotopeWrite(), and MaterialWrite().
void PHG4GDMLWriteMaterials::DWrite (xercesc::DOMElement * element, const G4double & d) protected
Definition at line 65 of file PHG4GDMLWriteMaterials.cc.
References g, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by MaterialWrite().
void PHG4GDMLWriteMaterials::ElementWrite (const G4Element * const elementPtr) protected
Definition at line 113 of file PHG4GDMLWriteMaterials.cc.
References AddIsotope(), AtomWrite(), PHG4GDMLWrite::GenerateName(), i, materialsElement, name, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddElement().
void PHG4GDMLWriteMaterials::IsotopeWrite (const G4Isotope * const isotopePtr) protected
Definition at line 101 of file PHG4GDMLWriteMaterials.cc.
References AtomWrite(), PHG4GDMLWrite::GenerateName(), materialsElement, name, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by AddIsotope().
void PHG4GDMLWriteMaterials::MaterialsWrite (xercesc::DOMElement * element) virtual
Implements PHG4GDMLWrite.
Definition at line 275 of file PHG4GDMLWriteMaterials.cc.
References elementList, isotopeList, materialList, materialsElement, and PHG4GDMLWrite::NewElement().
void PHG4GDMLWriteMaterials::MaterialWrite (const G4Material * const materialPtr) protected
Definition at line 148 of file PHG4GDMLWriteMaterials.cc.
References AddElement(), AtomWrite(), DWrite(), PHG4GDMLWrite::GenerateName(), i, materialsElement, MEEWrite(), name, PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), PropertyWrite(), PWrite(), and TWrite().
Referenced by AddMaterial().
void PHG4GDMLWriteMaterials::MEEWrite (xercesc::DOMElement * element, const G4double & MEE) protected
Definition at line 92 of file PHG4GDMLWriteMaterials.cc.
References PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by MaterialWrite().
void PHG4GDMLWriteMaterials::PropertyVectorWrite (const G4String & key, const G4PhysicsOrderedFreeVector * const pvec) protected
Definition at line 211 of file PHG4GDMLWriteMaterials.cc.
References PHG4GDMLWriteDefine::defineElement, PHG4GDMLWrite::GenerateName(), i, PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by PropertyWrite().
void PHG4GDMLWriteMaterials::PropertyWrite (xercesc::DOMElement * matElement, const G4Material * const mat) protected
Definition at line 229 of file PHG4GDMLWriteMaterials.cc.
References PHG4GDMLWriteDefine::defineElement, PHG4GDMLWrite::GenerateName(), PHG4GDMLWrite::NewAttribute(), PHG4GDMLWrite::NewElement(), and PropertyVectorWrite().
Referenced by MaterialWrite().
void PHG4GDMLWriteMaterials::PWrite (xercesc::DOMElement * element, const G4double & P) protected
Definition at line 74 of file PHG4GDMLWriteMaterials.cc.
References PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by MaterialWrite().
void PHG4GDMLWriteMaterials::TWrite (xercesc::DOMElement * element, const G4double & T) protected
Definition at line 83 of file PHG4GDMLWriteMaterials.cc.
References PHG4GDMLWrite::NewAttribute(), and PHG4GDMLWrite::NewElement().
Referenced by MaterialWrite().
Member Data Documentation
std::vector<const G4Element*> PHG4GDMLWriteMaterials::elementList protected
Definition at line 83 of file PHG4GDMLWriteMaterials.hh.
Referenced by AddElement(), and MaterialsWrite().
std::vector<const G4Isotope*> PHG4GDMLWriteMaterials::isotopeList protected
Definition at line 82 of file PHG4GDMLWriteMaterials.hh.
Referenced by AddIsotope(), and MaterialsWrite().
std::vector<const G4Material*> PHG4GDMLWriteMaterials::materialList protected
Definition at line 84 of file PHG4GDMLWriteMaterials.hh.
Referenced by AddMaterial(), and MaterialsWrite().
xercesc::DOMElement* PHG4GDMLWriteMaterials::materialsElement protected
Definition at line 85 of file PHG4GDMLWriteMaterials.hh.
Referenced by ElementWrite(), IsotopeWrite(), MaterialsWrite(), and MaterialWrite().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.hh
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.cc