Analysis Software: ePHENIXRICH::RICH_Geometry Class Reference
ePHENIXRICH::RICH_Geometry Class Reference
This class provides geometry and material parameters to construct the ePHENIX RICH detector in ePHENIXRICHConstruction.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h>
Public Member Functions
RICH_Geometry ()
void SetDefault ()
void CreateOpticalSurfaces ()
Get Parameters
Group of functions to get parameters.
double get_R_max () const
double get_cone_size_z () const
double get_R_frontwindow () const
double get_half_angle_HBD () const
double get_RZ_Seg1_HBD () const
double get_RZ_Seg2_HBD () const
double get_R_Tip_HBD () const
double get_Z_Tip_HBD () const
double get_Rotation_HBD () const
double get_R_beam_pipe () const
double get_frontwindow_DisplaceRatio () const
double get_min_eta () const
double get_R_mirror_ref () const
double get_dR_backwindow () const
double get_dR_frontwindow () const
double get_dR_frontwindow_shrink () const
double get_dR_mirror () const
double get_dR_mirror_spt () const
G4String get_RICH_gas_mat () const
G4String get_RICH_Gas_Window_mat () const
G4String get_RICH_Mirror_mat () const
G4OpticalSurface * get_RICH_Mirror_OpticalSurface () const
int get_N_RICH_Sector () const
double get_z_shift () const
double get_R_shift () const
int get_n_GEM_layers () const
double get_HBD_thickness () const
G4OpticalSurface * get_RICH_Photocathode_OpticalSurface () const
Set Parameters
Group of functions to set parameters.
void set_R_beam_pipe (double beamPipe)
void set_frontwindow_DisplaceRatio (double frontwindowDisplaceRatio)
void set_min_eta (double minEta)
void set_R_mirror_ref (double mirrorRef)
void set_dR_backwindow (double rBackwindow)
void set_dR_frontwindow (double rFrontwindow)
void set_dR_frontwindow_shrink (double rFrontwindowShrink)
void set_dR_mirror (double rMirror)
void set_dR_mirror_spt (double rMirrorSpt)
void set_RICH_gas_mat (G4String richGasMat)
void set_RICH_Gas_Window_mat (G4String richGasWindowMat)
void set_RICH_Mirror_mat (G4String richMirrorMat)
void set_N_RICH_Sector (int richSector)
void set_z_shift (double shift)
void set_R_shift (double shift)
void set_n_GEM_layers (int gemLayers)
void set_HBD_thickness (double hbdThickness)
Static Public Member Functions
static double Unit_cm ()
Private Attributes
int N_RICH_Sector
double min_eta
double R_beam_pipe
double z_shift
double R_shift
double frontwindow_DisplaceRatio
double dR_frontwindow_shrink
double R_mirror_ref
double dR_mirror
double dR_mirror_spt
double dR_backwindow
double dR_frontwindow
int n_GEM_layers
double HBD_thickness
G4String RICH_gas_mat
G4String RICH_Mirror_mat
G4String RICH_Gas_Window_mat
G4OpticalSurface * RICH_Mirror_OpticalSurface
G4OpticalSurface * RICH_Photocathode_OpticalSurface
Detailed Description
This class provides geometry and material parameters to construct the ePHENIX RICH detector in ePHENIXRICHConstruction.
See Also
ePHENIXRICH::RICH_Geometry
ePHENIXRICH::ePHENIXRICHConstruction
PHG4RICHDetector
PHG4RICHSteppingAction
PHG4RICHSubsystem
Note: use GEANT units!
Definition at line 47 of file ePHENIXRICHConstruction.h.
Constructor & Destructor Documentation
ePHENIXRICH::RICH_Geometry::RICH_Geometry () inline
Default constructor.
Definition at line 53 of file ePHENIXRICHConstruction.h.
References CreateOpticalSurfaces(), and SetDefault().
Member Function Documentation
void RICH_Geometry::CreateOpticalSurfaces ()
Create optical surfaces (mirror, photocathode) to properly propagate optical photons in the RICH.
Definition at line 442 of file ePHENIXRICHConstruction.cc.
References RICH_Mirror_OpticalSurface, and RICH_Photocathode_OpticalSurface.
Referenced by RICH_Geometry().
double ePHENIXRICH::RICH_Geometry::get_cone_size_z () const inline
Definition at line 87 of file ePHENIXRICHConstruction.h.
References get_R_max(), and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_dR_backwindow () const inline
Definition at line 138 of file ePHENIXRICHConstruction.h.
References dR_backwindow.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_dR_frontwindow () const inline
Definition at line 144 of file ePHENIXRICHConstruction.h.
References dR_frontwindow.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), and ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_dR_frontwindow_shrink () const inline
Definition at line 150 of file ePHENIXRICHConstruction.h.
References dR_frontwindow_shrink.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD().
double ePHENIXRICH::RICH_Geometry::get_dR_mirror () const inline
Definition at line 156 of file ePHENIXRICHConstruction.h.
References dR_mirror.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_dR_mirror_spt () const inline
Definition at line 162 of file ePHENIXRICHConstruction.h.
References dR_mirror_spt.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_frontwindow_DisplaceRatio () const inline
Definition at line 120 of file ePHENIXRICHConstruction.h.
References frontwindow_DisplaceRatio.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double RICH_Geometry::get_half_angle_HBD () const
Definition at line 489 of file ePHENIXRICHConstruction.cc.
References N_RICH_Sector, pi, R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), and ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD_Layers().
double ePHENIXRICH::RICH_Geometry::get_HBD_thickness () const inline
Definition at line 214 of file ePHENIXRICHConstruction.h.
References HBD_thickness.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD().
double ePHENIXRICH::RICH_Geometry::get_min_eta () const inline
Definition at line 126 of file ePHENIXRICHConstruction.h.
References min_eta.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
int ePHENIXRICH::RICH_Geometry::get_n_GEM_layers () const inline
Definition at line 208 of file ePHENIXRICHConstruction.h.
References n_GEM_layers.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD().
int ePHENIXRICH::RICH_Geometry::get_N_RICH_Sector () const inline
Definition at line 191 of file ePHENIXRICHConstruction.h.
References N_RICH_Sector.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_R_beam_pipe () const inline
Definition at line 114 of file ePHENIXRICHConstruction.h.
References R_beam_pipe.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double RICH_Geometry::get_R_frontwindow () const
Definition at line 484 of file ePHENIXRICHConstruction.cc.
References dR_frontwindow_shrink, frontwindow_DisplaceRatio, R_mirror_ref, R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_R_max () const inline
Definition at line 81 of file ePHENIXRICHConstruction.h.
References dR_backwindow, dR_mirror, dR_mirror_spt, and R_mirror_ref.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH(), and get_cone_size_z().
double ePHENIXRICH::RICH_Geometry::get_R_mirror_ref () const inline
Definition at line 132 of file ePHENIXRICHConstruction.h.
References R_mirror_ref.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double ePHENIXRICH::RICH_Geometry::get_R_shift () const inline
Definition at line 203 of file ePHENIXRICHConstruction.h.
References R_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double RICH_Geometry::get_R_Tip_HBD () const
Definition at line 505 of file ePHENIXRICHConstruction.cc.
References get_Rotation_HBD(), get_RZ_Seg1_HBD(), R_mirror_ref, R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD().
G4String ePHENIXRICH::RICH_Geometry::get_RICH_gas_mat () const inline
Definition at line 168 of file ePHENIXRICHConstruction.h.
References RICH_gas_mat.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), and ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
G4String ePHENIXRICH::RICH_Geometry::get_RICH_Gas_Window_mat () const inline
Definition at line 174 of file ePHENIXRICHConstruction.h.
References RICH_Gas_Window_mat.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
G4String ePHENIXRICH::RICH_Geometry::get_RICH_Mirror_mat () const inline
Definition at line 180 of file ePHENIXRICHConstruction.h.
References RICH_Mirror_mat.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
G4OpticalSurface* ePHENIXRICH::RICH_Geometry::get_RICH_Mirror_OpticalSurface () const inline
Definition at line 186 of file ePHENIXRICHConstruction.h.
References RICH_Mirror_OpticalSurface.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
G4OpticalSurface* ePHENIXRICH::RICH_Geometry::get_RICH_Photocathode_OpticalSurface () const inline
Definition at line 220 of file ePHENIXRICHConstruction.h.
References RICH_Photocathode_OpticalSurface.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD().
double RICH_Geometry::get_Rotation_HBD () const
Definition at line 519 of file ePHENIXRICHConstruction.cc.
References R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), get_R_Tip_HBD(), and get_Z_Tip_HBD().
double RICH_Geometry::get_RZ_Seg1_HBD () const
Definition at line 495 of file ePHENIXRICHConstruction.cc.
References R_mirror_ref, R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD_Layers(), get_R_Tip_HBD(), and get_Z_Tip_HBD().
double RICH_Geometry::get_RZ_Seg2_HBD () const
Definition at line 500 of file ePHENIXRICHConstruction.cc.
References min_eta, R_mirror_ref, R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD(), and ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD_Layers().
double ePHENIXRICH::RICH_Geometry::get_z_shift () const inline
Definition at line 197 of file ePHENIXRICHConstruction.h.
References z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_RICH().
double RICH_Geometry::get_Z_Tip_HBD () const
Definition at line 512 of file ePHENIXRICHConstruction.cc.
References get_Rotation_HBD(), get_RZ_Seg1_HBD(), R_mirror_ref, R_shift, and z_shift.
Referenced by ePHENIXRICH::ePHENIXRICHConstruction::Construct_HBD().
void ePHENIXRICH::RICH_Geometry::set_dR_backwindow (double rBackwindow) inline
Definition at line 255 of file ePHENIXRICHConstruction.h.
References dR_backwindow.
void ePHENIXRICH::RICH_Geometry::set_dR_frontwindow (double rFrontwindow) inline
Definition at line 261 of file ePHENIXRICHConstruction.h.
References dR_frontwindow.
void ePHENIXRICH::RICH_Geometry::set_dR_frontwindow_shrink (double rFrontwindowShrink) inline
Definition at line 267 of file ePHENIXRICHConstruction.h.
References dR_frontwindow_shrink.
void ePHENIXRICH::RICH_Geometry::set_dR_mirror (double rMirror) inline
Definition at line 273 of file ePHENIXRICHConstruction.h.
References dR_mirror.
void ePHENIXRICH::RICH_Geometry::set_dR_mirror_spt (double rMirrorSpt) inline
Definition at line 279 of file ePHENIXRICHConstruction.h.
References dR_mirror_spt.
void ePHENIXRICH::RICH_Geometry::set_frontwindow_DisplaceRatio (double frontwindowDisplaceRatio) inline
Definition at line 237 of file ePHENIXRICHConstruction.h.
References frontwindow_DisplaceRatio.
void ePHENIXRICH::RICH_Geometry::set_HBD_thickness (double hbdThickness) inline
Definition at line 327 of file ePHENIXRICHConstruction.h.
References HBD_thickness.
void ePHENIXRICH::RICH_Geometry::set_min_eta (double minEta) inline
Definition at line 243 of file ePHENIXRICHConstruction.h.
References min_eta.
Referenced by RICHSetup().
void ePHENIXRICH::RICH_Geometry::set_n_GEM_layers (int gemLayers) inline
Definition at line 321 of file ePHENIXRICHConstruction.h.
References n_GEM_layers.
void ePHENIXRICH::RICH_Geometry::set_N_RICH_Sector (int richSector) inline
Definition at line 303 of file ePHENIXRICHConstruction.h.
References N_RICH_Sector.
Referenced by RICHSetup().
void ePHENIXRICH::RICH_Geometry::set_R_beam_pipe (double beamPipe) inline
Definition at line 231 of file ePHENIXRICHConstruction.h.
References R_beam_pipe.
void ePHENIXRICH::RICH_Geometry::set_R_mirror_ref (double mirrorRef) inline
Definition at line 249 of file ePHENIXRICHConstruction.h.
References R_mirror_ref.
Referenced by RICHSetup().
void ePHENIXRICH::RICH_Geometry::set_R_shift (double shift) inline
Definition at line 315 of file ePHENIXRICHConstruction.h.
References R_shift.
Referenced by RICHSetup().
void ePHENIXRICH::RICH_Geometry::set_RICH_gas_mat (G4String richGasMat) inline
Definition at line 285 of file ePHENIXRICHConstruction.h.
References RICH_gas_mat.
void ePHENIXRICH::RICH_Geometry::set_RICH_Gas_Window_mat (G4String richGasWindowMat) inline
Definition at line 291 of file ePHENIXRICHConstruction.h.
References RICH_Gas_Window_mat.
void ePHENIXRICH::RICH_Geometry::set_RICH_Mirror_mat (G4String richMirrorMat) inline
Definition at line 297 of file ePHENIXRICHConstruction.h.
References RICH_Mirror_mat.
void ePHENIXRICH::RICH_Geometry::set_z_shift (double shift) inline
Definition at line 309 of file ePHENIXRICHConstruction.h.
References z_shift.
Referenced by RICHSetup().
void RICH_Geometry::SetDefault ()
Set default parameters for the RICH geometry.
Definition at line 419 of file ePHENIXRICHConstruction.cc.
References dR_backwindow, dR_frontwindow, dR_frontwindow_shrink, dR_mirror, dR_mirror_spt, frontwindow_DisplaceRatio, HBD_thickness, min_eta, n_GEM_layers, N_RICH_Sector, R_beam_pipe, R_mirror_ref, R_shift, RICH_gas_mat, RICH_Gas_Window_mat, RICH_Mirror_mat, and z_shift.
Referenced by RICH_Geometry().
static double ePHENIXRICH::RICH_Geometry::Unit_cm () inline static
Unit.
Definition at line 75 of file ePHENIXRICHConstruction.h.
Referenced by RICHSetup().
Member Data Documentation
double ePHENIXRICH::RICH_Geometry::dR_backwindow private
Definition at line 347 of file ePHENIXRICHConstruction.h.
Referenced by get_dR_backwindow(), get_R_max(), set_dR_backwindow(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::dR_frontwindow private
Definition at line 348 of file ePHENIXRICHConstruction.h.
Referenced by get_dR_frontwindow(), set_dR_frontwindow(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::dR_frontwindow_shrink private
Definition at line 342 of file ePHENIXRICHConstruction.h.
Referenced by get_dR_frontwindow_shrink(), get_R_frontwindow(), set_dR_frontwindow_shrink(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::dR_mirror private
Definition at line 345 of file ePHENIXRICHConstruction.h.
Referenced by get_dR_mirror(), get_R_max(), set_dR_mirror(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::dR_mirror_spt private
Definition at line 346 of file ePHENIXRICHConstruction.h.
Referenced by get_dR_mirror_spt(), get_R_max(), set_dR_mirror_spt(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::frontwindow_DisplaceRatio private
Definition at line 341 of file ePHENIXRICHConstruction.h.
Referenced by get_frontwindow_DisplaceRatio(), get_R_frontwindow(), set_frontwindow_DisplaceRatio(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::HBD_thickness private
Definition at line 351 of file ePHENIXRICHConstruction.h.
Referenced by get_HBD_thickness(), set_HBD_thickness(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::min_eta private
Definition at line 336 of file ePHENIXRICHConstruction.h.
Referenced by get_min_eta(), get_RZ_Seg2_HBD(), set_min_eta(), and SetDefault().
int ePHENIXRICH::RICH_Geometry::n_GEM_layers private
Definition at line 350 of file ePHENIXRICHConstruction.h.
Referenced by get_n_GEM_layers(), set_n_GEM_layers(), and SetDefault().
int ePHENIXRICH::RICH_Geometry::N_RICH_Sector private
Definition at line 334 of file ePHENIXRICHConstruction.h.
Referenced by get_half_angle_HBD(), get_N_RICH_Sector(), set_N_RICH_Sector(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::R_beam_pipe private
Definition at line 337 of file ePHENIXRICHConstruction.h.
Referenced by get_R_beam_pipe(), set_R_beam_pipe(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::R_mirror_ref private
Definition at line 343 of file ePHENIXRICHConstruction.h.
Referenced by get_R_frontwindow(), get_R_max(), get_R_mirror_ref(), get_R_Tip_HBD(), get_RZ_Seg1_HBD(), get_RZ_Seg2_HBD(), get_Z_Tip_HBD(), set_R_mirror_ref(), and SetDefault().
double ePHENIXRICH::RICH_Geometry::R_shift private
Definition at line 340 of file ePHENIXRICHConstruction.h.
Referenced by get_half_angle_HBD(), get_R_frontwindow(), get_R_shift(), get_R_Tip_HBD(), get_Rotation_HBD(), get_RZ_Seg1_HBD(), get_RZ_Seg2_HBD(), get_Z_Tip_HBD(), set_R_shift(), and SetDefault().
G4String ePHENIXRICH::RICH_Geometry::RICH_gas_mat private
Definition at line 353 of file ePHENIXRICHConstruction.h.
Referenced by get_RICH_gas_mat(), set_RICH_gas_mat(), and SetDefault().
G4String ePHENIXRICH::RICH_Geometry::RICH_Gas_Window_mat private
Definition at line 355 of file ePHENIXRICHConstruction.h.
Referenced by get_RICH_Gas_Window_mat(), set_RICH_Gas_Window_mat(), and SetDefault().
G4String ePHENIXRICH::RICH_Geometry::RICH_Mirror_mat private
Definition at line 354 of file ePHENIXRICHConstruction.h.
Referenced by get_RICH_Mirror_mat(), set_RICH_Mirror_mat(), and SetDefault().
G4OpticalSurface* ePHENIXRICH::RICH_Geometry::RICH_Mirror_OpticalSurface private
Definition at line 357 of file ePHENIXRICHConstruction.h.
Referenced by CreateOpticalSurfaces(), and get_RICH_Mirror_OpticalSurface().
G4OpticalSurface* ePHENIXRICH::RICH_Geometry::RICH_Photocathode_OpticalSurface private
Definition at line 358 of file ePHENIXRICHConstruction.h.
Referenced by CreateOpticalSurfaces(), and get_RICH_Photocathode_OpticalSurface().
double ePHENIXRICH::RICH_Geometry::z_shift private
Definition at line 339 of file ePHENIXRICHConstruction.h.
Referenced by get_cone_size_z(), get_half_angle_HBD(), get_R_frontwindow(), get_R_Tip_HBD(), get_Rotation_HBD(), get_RZ_Seg1_HBD(), get_RZ_Seg2_HBD(), get_z_shift(), get_Z_Tip_HBD(), set_z_shift(), and SetDefault().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc