Analysis Software: prototype/blob/master/macros/prototype3/Fun4All_TestBeam.C File Reference
Fun4All_TestBeam.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <phool/recoConsts.h>
#include <prototype3/CaloCalibration.h>
#include <prototype3/CaloUnpackPRDF.h>
#include <prototype3/EventInfoSummary.h>
#include <prototype3/GenericUnpackPRDF.h>
#include <prototype3/PROTOTYPE3_FEM.h>
#include <prototype3/Prototype3DSTReader.h>
#include <prototype3/RunInfoUnpackPRDF.h>
#include <prototype3/TempInfoUnpackPRDF.h>
Functions
void Fun4All_TestBeam (int nEvents=1000, const char *input_file="/sphenix/data/data01/t1044-2016a/fnal/beam/beam_00003310-0000.prdf", const char *output_file="beam_00003310.root")
Function Documentation
void Fun4All_TestBeam (int nEvents = 1000, const char * input_file = "/sphenix/data/data01/t1044-2016a/fnal/beam/beam_00003310-0000.prdf", const char * output_file = "beam_00003310.root")
Definition at line 24 of file Fun4All_TestBeam.C.
References GenericUnpackPRDF::add_channel(), RunInfoUnpackPRDF::add_channel(), Prototype3DSTReader::AddEventInfo(), Prototype3DSTReader::AddRunInfo(), Prototype3DSTReader::AddTower(), Fun4AllServer::End(), Fun4AllInputManager::fileopen(), CaloCalibration::GetCalibrationParameters(), i, in, recoConsts::instance(), Fun4AllServer::instance(), nEvents, PROTOTYPE3_FEM::PACKET_ID, PHParameters::ReadFromFile(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), CaloCalibration::set_calib_tower_node_prefix(), PHParameters::set_double_param(), PHParameters::set_int_param(), PHParameters::set_name(), CaloCalibration::set_raw_tower_node_prefix(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.