Analysis Software: PHSartreGenTrigger Class Reference
PHSartreGenTrigger Class Reference
#include <coresoftware/blob/master/generators/PHSartre/PHSartreGenTrigger.h>
Public Member Functions
virtual ~PHSartreGenTrigger ()
virtual bool Apply (Event *event)
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
int Verbosity () const
void Verbosity (int v)
Protected Member Functions
PHSartreGenTrigger (const std::string &name="PHSartreGenTrigger")
constructor
Private Attributes
int m_Verbosity
std::string m_Name
Detailed Description
Definition at line 10 of file PHSartreGenTrigger.h.
Constructor & Destructor Documentation
PHSartreGenTrigger::PHSartreGenTrigger (const std::string & name = "PHSartreGenTrigger") protected
constructor
Definition at line 8 of file PHSartreGenTrigger.cc.
PHSartreGenTrigger::~PHSartreGenTrigger () virtual
Definition at line 15 of file PHSartreGenTrigger.cc.
Member Function Documentation
virtual bool PHSartreGenTrigger::Apply (Event * event) inline virtual
Reimplemented in PHSartreParticleTrigger.
Definition at line 19 of file PHSartreGenTrigger.h.
std::vector< int > PHSartreGenTrigger::convertToInts (std::string s)
Definition at line 17 of file PHSartreGenTrigger.cc.
References i.
Referenced by PHSartreParticleTrigger::AddParticles().
virtual std::string PHSartreGenTrigger::GetName () inline virtual
Definition at line 25 of file PHSartreGenTrigger.h.
References m_Name.
Referenced by PHSartre::register_trigger().
int PHSartreGenTrigger::Verbosity () const inline
Definition at line 28 of file PHSartreGenTrigger.h.
References m_Verbosity.
Referenced by PHSartreParticleTrigger::Apply(), and PHSartreParticleTrigger::~PHSartreParticleTrigger().
void PHSartreGenTrigger::Verbosity (int v) inline
Definition at line 29 of file PHSartreGenTrigger.h.
References m_Verbosity, and v.
Member Data Documentation
std::string PHSartreGenTrigger::m_Name private
Definition at line 34 of file PHSartreGenTrigger.h.
Referenced by GetName().
int PHSartreGenTrigger::m_Verbosity private
Definition at line 33 of file PHSartreGenTrigger.h.
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/PHSartre/PHSartreGenTrigger.h
coresoftware/blob/master/generators/PHSartre/PHSartreGenTrigger.cc