Analysis Software: online_distribution/blob/master/newbasic/dlist.cc File Reference
dlist.cc File Reference
#include <stdlib.h>
#include <signal.h>
#include <string>
#include "fileEventiterator.h"
#include "rcdaqEventiterator.h"
#include "testEventiterator.h"
#include "oncsEventiterator.h"
#include <stdio.h>
Macros
#define RCDAQEVENTITERATOR 1
#define FILEEVENTITERATOR 2
#define TESTEVENTITERATOR 3
#define ONCSEVENTITERATOR 4
Functions
void sig_handler (...)
void exitmsg ()
void evtcountexitmsg ()
void exithelp ()
int main (int argc, char *argv[])
Variables
Eventiterator * it
Macro Definition Documentation
#define FILEEVENTITERATOR 2
Definition at line 20 of file dlist.cc.
Referenced by main().
#define ONCSEVENTITERATOR 4
Definition at line 22 of file dlist.cc.
Referenced by main().
#define RCDAQEVENTITERATOR 1
Definition at line 19 of file dlist.cc.
Referenced by main().
#define TESTEVENTITERATOR 3
Definition at line 21 of file dlist.cc.
Referenced by main().
Function Documentation
void evtcountexitmsg ()
Definition at line 42 of file dlist.cc.
References COUT.
void exithelp ()
Definition at line 51 of file dlist.cc.
References COUT.
void exitmsg ()
Definition at line 35 of file dlist.cc.
References COUT.
int main (int argc, char * argv[])
Definition at line 112 of file dlist.cc.
References c, COUT, evtcountexitmsg(), exithelp(), exitmsg(), FILEEVENTITERATOR, Packet::fullIdentify(), Event::getEvtSequence(), Event::getEvtType(), Eventiterator::getNextEvent(), Event::getPacketList(), i, Event::identify(), Packet::identify(), it, ONCSEVENTITERATOR, RCDAQEVENTITERATOR, Eventiterator::setVerbosity(), sig_handler(), signal(), and TESTEVENTITERATOR.
void sig_handler (...)
Definition at line 245 of file changehitformat.cc.
Variable Documentation
Eventiterator* it
Definition at line 32 of file dlist.cc.