Analysis Software: PHG4SectorDisplayAction Class Reference
PHG4SectorDisplayAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorDisplayAction.h>
Public Member Functions
PHG4SectorDisplayAction (const std::string &name)
virtual ~PHG4SectorDisplayAction ()
void ApplyDisplayAction (G4VPhysicalVolume *physvol)
ApplyDisplayAction method.
void AddVolume (G4LogicalVolume *logvol, const std::string &mat)
Public Member Functions inherited from PHG4DisplayAction
PHG4DisplayAction ()=delete
constructor
PHG4DisplayAction (const std::string &name)
virtual ~PHG4DisplayAction ()
destructor
virtual void SetName (const std::string &name)
virtual std::string GetName () const
virtual void Print (const std::string &what="ALL")
Private Attributes
std::map< G4LogicalVolume
*, std::string > m_LogicalVolumeMap
std::vector< G4VisAttributes * > m_VisAttVec
Additional Inherited Members
Public Types inherited from PHG4DisplayAction
enum CheckReturnCodes { ABORT = -1, FAILED = 0, ACCEPT = 1 }
Protected Member Functions inherited from PHG4DisplayAction
int FindVolumes (G4VPhysicalVolume *physvol)
find FindVolume method
virtual int CheckVolume (G4VPhysicalVolume *physvol)
find CheckVolume method
virtual void ApplyVisAttributes (G4VPhysicalVolume *physvol)
ApplyVisAttributes method.
Detailed Description
Definition at line 16 of file PHG4SectorDisplayAction.h.
Constructor & Destructor Documentation
PHG4SectorDisplayAction::PHG4SectorDisplayAction (const std::string & name)
Definition at line 19 of file PHG4SectorDisplayAction.cc.
PHG4SectorDisplayAction::~PHG4SectorDisplayAction () virtual
Definition at line 24 of file PHG4SectorDisplayAction.cc.
References it, and m_VisAttVec.
Member Function Documentation
void PHG4SectorDisplayAction::AddVolume (G4LogicalVolume * logvol, const std::string & mat) inline
Definition at line 24 of file PHG4SectorDisplayAction.h.
References m_LogicalVolumeMap.
Referenced by PHG4Sector::PHG4SectorConstructor::Construct_Sectors(), and PHG4SectorDetector::ConstructMe().
void PHG4SectorDisplayAction::ApplyDisplayAction (G4VPhysicalVolume * physvol) virtual
ApplyDisplayAction method.
pure virtual - has to be implemented by derived class creates and set VisAttributes for volumes
Parameters
[in] physvol starting volume in hierarchy (typically world volume)
Implements PHG4DisplayAction.
Definition at line 33 of file PHG4SectorDisplayAction.cc.
References it, m_LogicalVolumeMap, m_VisAttVec, and PHG4Utils::SetColour().
Member Data Documentation
std::map<G4LogicalVolume *, std::string> PHG4SectorDisplayAction::m_LogicalVolumeMap private
Definition at line 27 of file PHG4SectorDisplayAction.h.
Referenced by AddVolume(), and ApplyDisplayAction().
std::vector<G4VisAttributes *> PHG4SectorDisplayAction::m_VisAttVec private
Definition at line 28 of file PHG4SectorDisplayAction.h.
Referenced by ApplyDisplayAction(), and ~PHG4SectorDisplayAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorDisplayAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4SectorDisplayAction.cc