Analysis Software: PHG4CellDefs::SizeBinning Namespace Reference
PHG4CellDefs::SizeBinning Namespace Reference
Functions
keytype genkey (const unsigned short layer, const unsigned short zbin, const unsigned short iphibin)
unsigned short int get_zbin (const PHG4CellDefs::keytype key)
unsigned short int get_phibin (const PHG4CellDefs::keytype key)
Function Documentation
PHG4CellDefs::keytype PHG4CellDefs::SizeBinning::genkey (const unsigned short layer, const unsigned short zbin, const unsigned short iphibin)
Definition at line 26 of file PHG4CellDefs.cc.
References generic_16bit_genkey(), and PHG4CellDefs::sizebinning.
Referenced by PHG4CylinderCellContainer::AddCylinderCell(), PHG4TpcPadPlaneSimple::MapToPadPlane(), PHG4TpcPadPlaneReadout::MapToPadPlane(), and PHG4CylinderCellReco::process_event().
unsigned short int PHG4CellDefs::SizeBinning::get_phibin (const PHG4CellDefs::keytype key)
Definition at line 33 of file PHG4CellDefs.cc.
References generic_lower_16bit_key(), and PHG4CellDefs::sizebinning.
Referenced by RawTowerBuilder::process_event(), TPCIntegratedCharge::process_event(), PHG4CylinderCellReco::process_event(), TPCDataStreamEmulator::process_event(), CaloAna::process_g4cells(), and DumpPHG4CellContainer::process_Node().
unsigned short int PHG4CellDefs::SizeBinning::get_zbin (const PHG4CellDefs::keytype key)
Definition at line 40 of file PHG4CellDefs.cc.
References generic_upper_16bit_key(), and PHG4CellDefs::sizebinning.
Referenced by RawTowerBuilder::process_event(), TPCIntegratedCharge::process_event(), PHG4CylinderCellReco::process_event(), TPCDataStreamEmulator::process_event(), CaloAna::process_g4cells(), and DumpPHG4CellContainer::process_Node().