Analysis Software: PHPy8JetTrigger Class Reference
PHPy8JetTrigger Class Reference
#include <coresoftware/blob/master/generators/PHPythia8/PHPy8JetTrigger.h>
Public Member Functions
PHPy8JetTrigger (const std::string &name="PHPy8JetTrigger")
virtual ~PHPy8JetTrigger ()
bool Apply (Pythia8::Pythia *pythia)
void SetEtaHighLow (double etaHigh, double etaLow)
void SetMinJetPt (double minPt)
void SetJetR (double R)
void SetMinLeadingZ (double minZ)
void SetMinNumConstituents (int nconst)
void PrintConfig ()
Public Member Functions inherited from PHPy8GenTrigger
virtual ~PHPy8GenTrigger ()
virtual std::string GetName ()
std::vector< int > convertToInts (std::string s)
int Verbosity () const
void Verbosity (int v)
Private Attributes
double _theEtaHigh
double _theEtaLow
double _minPt
double _minZ
double _R
int _nconst
Additional Inherited Members
Protected Member Functions inherited from PHPy8GenTrigger
PHPy8GenTrigger (const std::string &name="PHPy8GenTrigger")
constructor
Detailed Description
Definition at line 13 of file PHPy8JetTrigger.h.
Constructor & Destructor Documentation
PHPy8JetTrigger::PHPy8JetTrigger (const std::string & name = "PHPy8JetTrigger")
Definition at line 21 of file PHPy8JetTrigger.cc.
PHPy8JetTrigger::~PHPy8JetTrigger () virtual
Definition at line 32 of file PHPy8JetTrigger.cc.
References PrintConfig(), and PHPy8GenTrigger::Verbosity().
Member Function Documentation
bool PHPy8JetTrigger::Apply (Pythia8::Pythia * pythia) virtual
Reimplemented from PHPy8GenTrigger.
Definition at line 37 of file PHPy8JetTrigger.cc.
References _minPt, _minZ, _nconst, _R, _theEtaHigh, _theEtaLow, i, j, and PHPy8GenTrigger::Verbosity().
void PHPy8JetTrigger::PrintConfig ()
Definition at line 173 of file PHPy8JetTrigger.cc.
References _minPt, _R, _theEtaHigh, and _theEtaLow.
Referenced by ~PHPy8JetTrigger().
void PHPy8JetTrigger::SetEtaHighLow (double etaHigh, double etaLow)
Definition at line 142 of file PHPy8JetTrigger.cc.
References _theEtaHigh, _theEtaLow, and boost::swap().
Referenced by Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and generate_hepmc_bjet().
void PHPy8JetTrigger::SetJetR (double R)
Definition at line 163 of file PHPy8JetTrigger.cc.
References _R.
Referenced by Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and generate_hepmc_bjet().
void PHPy8JetTrigger::SetMinJetPt (double minPt)
Definition at line 153 of file PHPy8JetTrigger.cc.
References _minPt.
Referenced by Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and generate_hepmc_bjet().
void PHPy8JetTrigger::SetMinLeadingZ (double minZ)
Definition at line 158 of file PHPy8JetTrigger.cc.
References _minZ.
void PHPy8JetTrigger::SetMinNumConstituents (int nconst)
Definition at line 168 of file PHPy8JetTrigger.cc.
References _nconst.
Member Data Documentation
double PHPy8JetTrigger::_minPt private
Definition at line 32 of file PHPy8JetTrigger.h.
Referenced by Apply(), PrintConfig(), and SetMinJetPt().
double PHPy8JetTrigger::_minZ private
Definition at line 33 of file PHPy8JetTrigger.h.
Referenced by Apply(), and SetMinLeadingZ().
int PHPy8JetTrigger::_nconst private
Definition at line 35 of file PHPy8JetTrigger.h.
Referenced by Apply(), and SetMinNumConstituents().
double PHPy8JetTrigger::_R private
Definition at line 34 of file PHPy8JetTrigger.h.
Referenced by Apply(), PrintConfig(), and SetJetR().
double PHPy8JetTrigger::_theEtaHigh private
Definition at line 30 of file PHPy8JetTrigger.h.
Referenced by Apply(), PrintConfig(), and SetEtaHighLow().
double PHPy8JetTrigger::_theEtaLow private
Definition at line 31 of file PHPy8JetTrigger.h.
Referenced by Apply(), PrintConfig(), and SetEtaHighLow().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/PHPythia8/PHPy8JetTrigger.h
coresoftware/blob/master/generators/PHPythia8/PHPy8JetTrigger.cc