Analysis Software: pmonstate Class Reference
pmonstate Class Reference
#include <online_distribution/blob/master/pmonitor/pmonstate.h>
Public Member Functions
pmonstate ()
virtual ~pmonstate ()
virtual int streamOpened () const
virtual int setETOpened (const char *name)
virtual int setFileOpened (const char *name)
virtual int setRCDAQOpened (const char *name)
virtual int setTestOpened ()
virtual int clearOpened ()
virtual int isRunning () const
virtual int setRunning ()
virtual int clearRunning ()
virtual int isBroken () const
virtual int getNoevt () const
virtual int setNoevt (const int n)
virtual int clearNoevt ()
virtual int incrementNoevt ()
virtual int getloopStatus ()
virtual void setloopStatus (const int s)
virtual int setIdentifyFlag (const int n=-1)
virtual int isIdentifyFlag ()
virtual char * name () const
Private Attributes
int stream
int initstatus
int eventloopexitstatus
int running
int number_of_events
char * Name
int idflag
Eventiterator * it
Friends
std::ostream & operator<< (std::ostream &os, pmonstate &c)
Detailed Description
Definition at line 16 of file pmonstate.h.
Constructor & Destructor Documentation
pmonstate::pmonstate () inline
Definition at line 57 of file pmonstate.h.
References eventloopexitstatus, idflag, initstatus, MSG_SEV_INFORMATIONAL, MSG_SOURCE_ET, MSG_TYPE_ONLINE, Name, number_of_events, pinit(), running, and stream.
virtual pmonstate::~pmonstate () inline virtual
Definition at line 73 of file pmonstate.h.
References Name.
Member Function Documentation
virtual int pmonstate::clearNoevt () inline virtual
Definition at line 160 of file pmonstate.h.
References number_of_events.
Referenced by pprocess(), and prun().
virtual int pmonstate::clearOpened () inline virtual
Definition at line 116 of file pmonstate.h.
References Name, and stream.
Referenced by pclose().
virtual int pmonstate::clearRunning () inline virtual
Definition at line 137 of file pmonstate.h.
References running.
Referenced by pprocess(), and prun().
virtual int pmonstate::getloopStatus () inline virtual
Definition at line 172 of file pmonstate.h.
References eventloopexitstatus.
Referenced by pexitstatus().
virtual int pmonstate::getNoevt () const inline virtual
Definition at line 149 of file pmonstate.h.
References number_of_events.
virtual int pmonstate::incrementNoevt () inline virtual
Definition at line 166 of file pmonstate.h.
References number_of_events.
Referenced by pprocess(), and prun().
virtual int pmonstate::isBroken () const inline virtual
Definition at line 143 of file pmonstate.h.
References initstatus.
virtual int pmonstate::isIdentifyFlag () inline virtual
Definition at line 188 of file pmonstate.h.
References i, and idflag.
Referenced by pprocess(), and prun().
virtual int pmonstate::isRunning () const inline virtual
Definition at line 125 of file pmonstate.h.
References running.
Referenced by pclose(), pstart(), and pstop().
virtual char* pmonstate::name () const inline virtual
Definition at line 198 of file pmonstate.h.
References Name.
virtual int pmonstate::setETOpened (const char * name) inline virtual
Definition at line 84 of file pmonstate.h.
References ETSTREAM, Name, and stream.
virtual int pmonstate::setFileOpened (const char * name) inline virtual
Definition at line 92 of file pmonstate.h.
References FILESTREAM, Name, and stream.
Referenced by pfileopen(), plistopen(), and poncsopen().
virtual int pmonstate::setIdentifyFlag (const int n = -1) inline virtual
Definition at line 182 of file pmonstate.h.
References idflag, and n.
Referenced by pclearidentify(), and pidentify().
virtual void pmonstate::setloopStatus (const int s) inline virtual
Definition at line 177 of file pmonstate.h.
References eventloopexitstatus, and s.
Referenced by pprocess(), and prun().
virtual int pmonstate::setNoevt (const int n) inline virtual
Definition at line 154 of file pmonstate.h.
References n, and number_of_events.
virtual int pmonstate::setRCDAQOpened (const char * name) inline virtual
Definition at line 100 of file pmonstate.h.
References Name, RCDAQSTREAM, and stream.
Referenced by rcdaqopen().
virtual int pmonstate::setRunning () inline virtual
Definition at line 131 of file pmonstate.h.
References running.
Referenced by pprocess(), and prun().
virtual int pmonstate::setTestOpened () inline virtual
Definition at line 108 of file pmonstate.h.
References Name, stream, and TESTSTREAM.
Referenced by ptestopen().
virtual int pmonstate::streamOpened () const inline virtual
Definition at line 79 of file pmonstate.h.
References stream.
Referenced by pclose(), pfileopen(), plistopen(), poncsopen(), prun(), pstart(), ptestopen(), and rcdaqopen().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, pmonstate & c) friend
Definition at line 19 of file pmonstate.h.
Member Data Documentation
int pmonstate::eventloopexitstatus private
Definition at line 48 of file pmonstate.h.
Referenced by getloopStatus(), pmonstate(), and setloopStatus().
int pmonstate::idflag private
Definition at line 52 of file pmonstate.h.
Referenced by isIdentifyFlag(), pmonstate(), and setIdentifyFlag().
int pmonstate::initstatus private
Definition at line 47 of file pmonstate.h.
Referenced by isBroken(), and pmonstate().
Eventiterator* pmonstate::it private
Definition at line 54 of file pmonstate.h.
char* pmonstate::Name private
Definition at line 51 of file pmonstate.h.
Referenced by clearOpened(), name(), pmonstate(), setETOpened(), setFileOpened(), setRCDAQOpened(), setTestOpened(), and ~pmonstate().
int pmonstate::number_of_events private
Definition at line 50 of file pmonstate.h.
Referenced by clearNoevt(), getNoevt(), incrementNoevt(), pmonstate(), and setNoevt().
int pmonstate::running private
Definition at line 49 of file pmonstate.h.
Referenced by clearRunning(), isRunning(), pmonstate(), and setRunning().
int pmonstate::stream private
Definition at line 41 of file pmonstate.h.
Referenced by clearOpened(), pmonstate(), setETOpened(), setFileOpened(), setRCDAQOpened(), setTestOpened(), and streamOpened().
The documentation for this class was generated from the following file:
online_distribution/blob/master/pmonitor/pmonstate.h