Analysis Software: RawTowerDeadTowerInterp Class Reference
RawTowerDeadTowerInterp Class Reference
RawTowerDeadTowerInterp recovers the energy in the known dead towers with interpolation between alive towers near-by.
#include <coresoftware/blob/master/offline/packages/CaloReco/RawTowerDeadTowerInterp.h>
Public Member Functions
RawTowerDeadTowerInterp (const std::string &name="RawTowerDeadTowerInterp")
virtual ~RawTowerDeadTowerInterp ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void detector (const std::string &d)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
void CreateNodes (PHCompositeNode *topNode)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
RawTowerContainer * m_calibTowers
RawTowerGeomContainer * m_geometry
RawTowerDeadMap * m_deadTowerMap
std::string m_detector
std::string _calib_tower_node_prefix
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
RawTowerDeadTowerInterp recovers the energy in the known dead towers with interpolation between alive towers near-by.
Definition at line 14 of file RawTowerDeadTowerInterp.h.
Constructor & Destructor Documentation
RawTowerDeadTowerInterp::RawTowerDeadTowerInterp (const std::string & name = "RawTowerDeadTowerInterp")
Definition at line 31 of file RawTowerDeadTowerInterp.cc.
virtual RawTowerDeadTowerInterp::~RawTowerDeadTowerInterp () inline virtual
Definition at line 18 of file RawTowerDeadTowerInterp.h.
Member Function Documentation
void RawTowerDeadTowerInterp::CreateNodes (PHCompositeNode * topNode) protected
Definition at line 236 of file RawTowerDeadTowerInterp.cc.
References _calib_tower_node_prefix, PHNodeIterator::findFirst(), RawTowerDeadMap::identify(), RawTowerGeomContainer::identify(), m_calibTowers, m_deadTowerMap, m_detector, m_geometry, Fun4AllBase::Name(), and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerDeadTowerInterp::detector (const std::string & d) inline
Definition at line 27 of file RawTowerDeadTowerInterp.h.
References d, and m_detector.
int RawTowerDeadTowerInterp::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 231 of file RawTowerDeadTowerInterp.cc.
References Fun4AllReturnCodes::EVENT_OK.
int RawTowerDeadTowerInterp::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 41 of file RawTowerDeadTowerInterp.cc.
References Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_detector, and Fun4AllBase::Name().
int RawTowerDeadTowerInterp::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 68 of file RawTowerDeadTowerInterp.cc.
References RawTowerContainer::AddTower(), assert, Fun4AllReturnCodes::EVENT_OK, RawTowerGeom::get_bineta(), RawTowerGeom::get_binphi(), RawTower::get_energy(), RawTowerGeomContainer::get_etabins(), RawTower::get_id(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_tower_geometry(), RawTowerDeadMap::getDeadTowers(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTowerDeadMap::isDeadTower(), m_calibTowers, m_deadTowerMap, m_detector, m_geometry, Fun4AllBase::Name(), RawTower::set_energy(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Member Data Documentation
std::string RawTowerDeadTowerInterp::_calib_tower_node_prefix protected
Definition at line 42 of file RawTowerDeadTowerInterp.h.
Referenced by CreateNodes().
RawTowerContainer* RawTowerDeadTowerInterp::m_calibTowers protected
Definition at line 36 of file RawTowerDeadTowerInterp.h.
Referenced by CreateNodes(), and process_event().
RawTowerDeadMap* RawTowerDeadTowerInterp::m_deadTowerMap protected
Definition at line 38 of file RawTowerDeadTowerInterp.h.
Referenced by CreateNodes(), and process_event().
std::string RawTowerDeadTowerInterp::m_detector protected
Definition at line 40 of file RawTowerDeadTowerInterp.h.
Referenced by CreateNodes(), detector(), InitRun(), and process_event().
RawTowerGeomContainer* RawTowerDeadTowerInterp::m_geometry protected
Definition at line 37 of file RawTowerDeadTowerInterp.h.
Referenced by CreateNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/RawTowerDeadTowerInterp.h
coresoftware/blob/master/offline/packages/CaloReco/RawTowerDeadTowerInterp.cc