Analysis Software: RawTowerBuilderByHitIndex Class Reference
RawTowerBuilderByHitIndex Class Reference
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k indeces of these hits.
#include <coresoftware/blob/master/simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.h>
Public Member Functions
RawTowerBuilderByHitIndex (const std::string &name="RawTowerBuilderByHitIndex")
virtual ~RawTowerBuilderByHitIndex ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void Detector (const std::string &d)
void GeometryTableFile (const std::string &d)
void EminCut (const double e)
std::string get_sim_tower_node_prefix () const
void set_sim_tower_node_prefix (const std::string &simTowerNodePrefix)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void CreateNodes (PHCompositeNode *topNode)
bool ReadGeometryFromTable ()
Private Attributes
RawTowerContainer * m_Towers
RawTowerGeomContainer * m_Geoms
std::string m_Detector
std::string m_SimTowerNodePrefix
std::string m_MappingTowerFile
RawTowerDefs::CalorimeterId m_CaloId
double m_GlobalPlaceInX
double m_GlobalPlaceInY
double m_GlobalPlaceInZ
double m_RotInX
double m_RotInY
double m_RotInZ
double m_Emin
std::map< std::string, double > m_GlobalParameterMap
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
SubsysReco module creating calorimeter tower objects (RawTowerv1) from hits (PHG4Hit) using j,k indeces of these hits.
Definition at line 20 of file RawTowerBuilderByHitIndex.h.
Constructor & Destructor Documentation
RawTowerBuilderByHitIndex::RawTowerBuilderByHitIndex (const std::string & name = "RawTowerBuilderByHitIndex")
Definition at line 41 of file RawTowerBuilderByHitIndex.cc.
virtual RawTowerBuilderByHitIndex::~RawTowerBuilderByHitIndex () inline virtual
Definition at line 24 of file RawTowerBuilderByHitIndex.h.
Member Function Documentation
void RawTowerBuilderByHitIndex::CreateNodes (PHCompositeNode * topNode) private
Create nodes for output.
Name of output node for RawTowerContainer: "TOWER_" + detector;
Definition at line 170 of file RawTowerBuilderByHitIndex.cc.
References PHCompositeNode::addNode(), RawTowerDefs::convert_name_to_caloid(), PHNodeIterator::findFirst(), m_Detector, m_Geoms, m_SimTowerNodePrefix, m_Towers, and PHWHERE.
Referenced by InitRun().
void RawTowerBuilderByHitIndex::Detector (const std::string & d)
Name of the detector node the G4Hits should be taken from.
Definition at line 164 of file RawTowerBuilderByHitIndex.cc.
References RawTowerDefs::convert_name_to_caloid(), d, m_CaloId, and m_Detector.
Referenced by EEMC_Towers(), FEMC_Towers(), and FHCAL_Towers().
void RawTowerBuilderByHitIndex::EminCut (const double e) inline
Define minimum tower energy. After processing an event, towers with lower energy are will be deleted.
Definition at line 46 of file RawTowerBuilderByHitIndex.h.
References m_Emin.
int RawTowerBuilderByHitIndex::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 159 of file RawTowerBuilderByHitIndex.cc.
References Fun4AllReturnCodes::EVENT_OK.
void RawTowerBuilderByHitIndex::GeometryTableFile (const std::string & d) inline
Specifiy text-file with table for tower mapping
Definition at line 38 of file RawTowerBuilderByHitIndex.h.
References d, and m_MappingTowerFile.
Referenced by EEMC_Towers(), FEMC_Towers(), and FHCAL_Towers().
std::string RawTowerBuilderByHitIndex::get_sim_tower_node_prefix () const inline
Get prefix for tower collection to identify simulated towers before digitization.
Definition at line 52 of file RawTowerBuilderByHitIndex.h.
References m_SimTowerNodePrefix.
int RawTowerBuilderByHitIndex::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 58 of file RawTowerBuilderByHitIndex.cc.
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and ReadGeometryFromTable().
int RawTowerBuilderByHitIndex::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 94 of file RawTowerBuilderByHitIndex.cc.
References RawTowerContainer::AddTower(), RawTowerContainer::compress(), RawTowerDefs::encode_towerid(), Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_edep(), PHG4Hit::get_index_j(), PHG4Hit::get_index_k(), PHG4Hit::get_light_yield(), PHG4Hit::get_shower_id(), PHG4HitContainer::getHits(), RawTowerContainer::getTotalEdep(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), RawTowerContainer::identify(), m_CaloId, m_Detector, m_Emin, m_Towers, and Fun4AllBase::Verbosity().
bool RawTowerBuilderByHitIndex::ReadGeometryFromTable () private
Read geometry information from table stored in text-file
Definition at line 223 of file RawTowerBuilderByHitIndex.cc.
References RawTowerGeomContainer::add_tower_geometry(), RawTowerDefs::encode_towerid(), RawTowerGeomContainer::get_tower_geometries(), it, m_CaloId, m_Geoms, m_GlobalParameterMap, m_GlobalPlaceInX, m_GlobalPlaceInY, m_GlobalPlaceInZ, m_MappingTowerFile, m_RotInX, m_RotInY, m_RotInZ, RawTowerGeom::set_center_x(), RawTowerGeom::set_center_y(), RawTowerGeom::set_center_z(), RawTowerGeom::set_size_x(), RawTowerGeom::set_size_y(), RawTowerGeom::set_size_z(), RawTowerGeom::set_tower_type(), and Fun4AllBase::Verbosity().
Referenced by InitRun().
void RawTowerBuilderByHitIndex::set_sim_tower_node_prefix (const std::string & simTowerNodePrefix) inline
Set prefix for tower collection to identify simulated towers before digitization.
Definition at line 61 of file RawTowerBuilderByHitIndex.h.
References m_SimTowerNodePrefix.
Referenced by EEMC_Towers(), FEMC_Towers(), and FHCAL_Towers().
Member Data Documentation
RawTowerDefs::CalorimeterId RawTowerBuilderByHitIndex::m_CaloId private
Definition at line 85 of file RawTowerBuilderByHitIndex.h.
Referenced by Detector(), process_event(), and ReadGeometryFromTable().
std::string RawTowerBuilderByHitIndex::m_Detector private
Definition at line 80 of file RawTowerBuilderByHitIndex.h.
Referenced by CreateNodes(), Detector(), and process_event().
double RawTowerBuilderByHitIndex::m_Emin private
Definition at line 95 of file RawTowerBuilderByHitIndex.h.
Referenced by EminCut(), and process_event().
RawTowerGeomContainer* RawTowerBuilderByHitIndex::m_Geoms private
Definition at line 78 of file RawTowerBuilderByHitIndex.h.
Referenced by CreateNodes(), and ReadGeometryFromTable().
std::map<std::string, double> RawTowerBuilderByHitIndex::m_GlobalParameterMap private
Definition at line 97 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndex::m_GlobalPlaceInX private
Definition at line 87 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndex::m_GlobalPlaceInY private
Definition at line 88 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndex::m_GlobalPlaceInZ private
Definition at line 89 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
std::string RawTowerBuilderByHitIndex::m_MappingTowerFile private
Definition at line 83 of file RawTowerBuilderByHitIndex.h.
Referenced by GeometryTableFile(), and ReadGeometryFromTable().
double RawTowerBuilderByHitIndex::m_RotInX private
Definition at line 91 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndex::m_RotInY private
Definition at line 92 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
double RawTowerBuilderByHitIndex::m_RotInZ private
Definition at line 93 of file RawTowerBuilderByHitIndex.h.
Referenced by ReadGeometryFromTable().
std::string RawTowerBuilderByHitIndex::m_SimTowerNodePrefix private
Definition at line 81 of file RawTowerBuilderByHitIndex.h.
Referenced by CreateNodes(), get_sim_tower_node_prefix(), and set_sim_tower_node_prefix().
RawTowerContainer* RawTowerBuilderByHitIndex::m_Towers private
Definition at line 77 of file RawTowerBuilderByHitIndex.h.
Referenced by CreateNodes(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.h
coresoftware/blob/master/simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc