Analysis Software: PHG4TpcPadPlaneSimple Class Reference
PHG4TpcPadPlaneSimple Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneSimple.h>
Public Member Functions
PHG4TpcPadPlaneSimple (const std::string &name="PHG4TpcPadPlaneSimple")
virtual ~PHG4TpcPadPlaneSimple ()
void MapToPadPlane (PHG4CellContainer *g4cells, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter)
void SetDefaultParameters ()
void UpdateInternalParameters ()
Public Member Functions inherited from PHG4TpcPadPlane
PHG4TpcPadPlane (const std::string &name="PHG4TpcPadPlane")
virtual ~PHG4TpcPadPlane ()
int process_event (PHCompositeNode *) final
int InitRun (PHCompositeNode *topNode)
virtual int CreateReadoutGeometry (PHCompositeNode *topNode, PHG4CylinderCellGeomContainer *seggeo)
virtual void MapToPadPlane (PHG4CellContainer *g4cells, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter, TNtuple *ntpad, TNtuple *nthit)
virtual void MapToPadPlane (TrkrHitSetContainer *hitsetcontainer, TrkrHitTruthAssoc *hittruthassoc, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter, TNtuple *ntpad, TNtuple *nthit)
void Detector (const std::string &name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Protected Attributes
double max_active_radius
double min_active_radius
double rbinwidth
double phibinwidth
double tbinwidth
Protected Attributes inherited from PHG4TpcPadPlane
std::string detector
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 8 of file PHG4TpcPadPlaneSimple.h.
Constructor & Destructor Documentation
PHG4TpcPadPlaneSimple::PHG4TpcPadPlaneSimple (const std::string & name = "PHG4TpcPadPlaneSimple")
Definition at line 11 of file PHG4TpcPadPlaneSimple.cc.
References PHParameterInterface::InitializeParameters().
virtual PHG4TpcPadPlaneSimple::~PHG4TpcPadPlaneSimple () inline virtual
Definition at line 12 of file PHG4TpcPadPlaneSimple.h.
Member Function Documentation
void PHG4TpcPadPlaneSimple::MapToPadPlane (PHG4CellContainer * g4cells, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter)
Definition at line 23 of file PHG4TpcPadPlaneSimple.cc.
References PHG4Cell::add_edep(), PHG4CellContainer::AddCell(), PHG4CellContainer::findCell(), PHG4CellDefs::SizeBinning::genkey(), M_PI, min_active_radius, phi, phibinwidth, rbinwidth, and tbinwidth.
void PHG4TpcPadPlaneSimple::SetDefaultParameters () virtual
Implements PHParameterInterface.
Definition at line 48 of file PHG4TpcPadPlaneSimple.cc.
References PHParameterInterface::set_default_double_param(), and PHParameterInterface::set_default_int_param().
void PHG4TpcPadPlaneSimple::UpdateInternalParameters () virtual
Reimplemented from PHG4TpcPadPlane.
Definition at line 59 of file PHG4TpcPadPlaneSimple.cc.
References PHParameterInterface::get_double_param(), PHParameterInterface::get_int_param(), M_PI, max_active_radius, min_active_radius, phibinwidth, rbinwidth, and tbinwidth.
Member Data Documentation
double PHG4TpcPadPlaneSimple::max_active_radius protected
Definition at line 20 of file PHG4TpcPadPlaneSimple.h.
Referenced by UpdateInternalParameters().
double PHG4TpcPadPlaneSimple::min_active_radius protected
Definition at line 21 of file PHG4TpcPadPlaneSimple.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
double PHG4TpcPadPlaneSimple::phibinwidth protected
Definition at line 23 of file PHG4TpcPadPlaneSimple.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
double PHG4TpcPadPlaneSimple::rbinwidth protected
Definition at line 22 of file PHG4TpcPadPlaneSimple.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
double PHG4TpcPadPlaneSimple::tbinwidth protected
Definition at line 24 of file PHG4TpcPadPlaneSimple.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneSimple.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneSimple.cc