Analysis Software: prdfoStream Class Reference
prdfoStream Class Reference
#include <analysis/blob/master/TPC/groot/prdfoStream.h>
Classes
struct buffer_ptr
Public Member Functions
prdfoStream (const char *filename, const int bufferlength=4 *1024 *1024)
virtual ~prdfoStream ()
int addEvent (Event *)
int is_defunct () const
Protected Member Functions
int addEoB ()
unsigned int writeout ()
int prepare_next (const int iseq, const int irun=0)
Static Protected Member Functions
static unsigned int writen (int fd, char *ptr, const unsigned int nbytes)
Protected Attributes
std::string _filename
int has_buffer
int buffer_sequence
buffer_ptr bptr
int * data_ptr
int current_index
int max_length
int max_size
int left
int has_end
int fd
int defunct
Detailed Description
Definition at line 9 of file prdfoStream.h.
Constructor & Destructor Documentation
prdfoStream::prdfoStream (const char * filename, const int bufferlength = 4*1024*1024)
Definition at line 13 of file prdfoStream.cc.
References fd, and filename.
prdfoStream::~prdfoStream () virtual
Definition at line 47 of file prdfoStream.cc.
References fd.
Member Function Documentation
int prdfoStream::addEoB () protected
Definition at line 108 of file prdfoStream.cc.
int prdfoStream::addEvent (Event * evt)
Definition at line 80 of file prdfoStream.cc.
References Event::Copy(), EOBLENGTH, Event::getEvtLength(), and Event::getRunNumber().
Referenced by process_event().
int prdfoStream::is_defunct () const inline
Definition at line 21 of file prdfoStream.h.
References defunct.
Referenced by prdfopen().
int prdfoStream::prepare_next (const int iseq, const int irun = 0) protected
Definition at line 57 of file prdfoStream.cc.
References BUFFERHEADERLENGTH, and EOBLENGTH.
unsigned int prdfoStream::writen (int fd, char * ptr, const unsigned int nbytes) static protected
Definition at line 135 of file prdfoStream.cc.
References write().
unsigned int prdfoStream::writeout () protected
Definition at line 120 of file prdfoStream.cc.
References BUFFERHEADERLENGTH, and fd.
Member Data Documentation
std::string prdfoStream::_filename protected
Definition at line 36 of file prdfoStream.h.
buffer_ptr prdfoStream::bptr protected
Definition at line 50 of file prdfoStream.h.
int prdfoStream::buffer_sequence protected
Definition at line 48 of file prdfoStream.h.
int prdfoStream::current_index protected
Definition at line 52 of file prdfoStream.h.
int* prdfoStream::data_ptr protected
Definition at line 51 of file prdfoStream.h.
int prdfoStream::defunct protected
Definition at line 59 of file prdfoStream.h.
Referenced by is_defunct().
int prdfoStream::fd protected
Definition at line 58 of file prdfoStream.h.
int prdfoStream::has_buffer protected
Definition at line 47 of file prdfoStream.h.
int prdfoStream::has_end protected
Definition at line 56 of file prdfoStream.h.
int prdfoStream::left protected
Definition at line 55 of file prdfoStream.h.
int prdfoStream::max_length protected
Definition at line 53 of file prdfoStream.h.
int prdfoStream::max_size protected
Definition at line 54 of file prdfoStream.h.
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/groot/prdfoStream.h
analysis/blob/master/TPC/groot/prdfoStream.cc