Analysis Software: Eventiterator Class Reference
Eventiterator Class Reference abstract
#include <online_distribution/blob/master/newbasic/Eventiterator.h>
Public Member Functions
virtual ~Eventiterator ()
The virtual destructor.
virtual const char * getIdTag () const =0
virtual void identify (std::ostream &os=std::cout) const =0
virtual Event * getNextEvent ()=0
virtual int * getNextEventData ()
virtual int releaseEventData ()
virtual void setBlockingMode (const int mode)
virtual int getBlockingMode () const
virtual void setSelectMode (const int mode)
virtual int getSelectMode () const
virtual void setSelectWords (const int i1, const int i2, const int i3, const int i4)
virtual void getSelectWords (int val[]) const
virtual const char * getCurrentFileName () const
virtual int setVerbosity (const int v)
virtual int getVerbosity () const
Detailed Description
The Eventiterator creates and returns pointers to Event objects. This is the virtual base class of a variety of different iterators.
Definition at line 13 of file Eventiterator.h.
Constructor & Destructor Documentation
virtual Eventiterator::~Eventiterator () inline virtual
The virtual destructor.
Definition at line 19 of file Eventiterator.h.
Member Function Documentation
virtual int Eventiterator::getBlockingMode () const inline virtual
Definition at line 42 of file Eventiterator.h.
virtual const char* Eventiterator::getCurrentFileName () const inline virtual
Reimplemented in listEventiterator, and fileEventiterator.
Definition at line 50 of file Eventiterator.h.
virtual const char* Eventiterator::getIdTag () const pure virtual
Implemented in listEventiterator, fileEventiterator, rcdaqEventiterator, testEventiterator, and oncsEventiterator.
virtual Event* Eventiterator::getNextEvent () pure virtual
this member function returns a pointer to the Event object, or NULL if there no events left.
Implemented in listEventiterator, fileEventiterator, testEventiterator, rcdaqEventiterator, and oncsEventiterator.
Referenced by hLabHelper::evDisplay(), hcalHelper::evLoop(), tileHelper::evLoop(), hcal::GetNextEvent(), listEventiterator::getNextEvent(), main(), pprocess(), prun(), Fun4AllPrdfInputManager::PushBackEvents(), and Fun4AllPrdfInputManager::run().
virtual int* Eventiterator::getNextEventData () inline virtual
the next member functions do nothing for most iterators
except the etEventiterator. It's still easier to give the parent class the interfaces
Definition at line 38 of file Eventiterator.h.
virtual int Eventiterator::getSelectMode () const inline virtual
Definition at line 45 of file Eventiterator.h.
virtual void Eventiterator::getSelectWords (int val[]) const inline virtual
Definition at line 48 of file Eventiterator.h.
virtual int Eventiterator::getVerbosity () const inline virtual
Reimplemented in fileEventiterator.
Definition at line 53 of file Eventiterator.h.
virtual void Eventiterator::identify (std::ostream & os = std::cout) const pure virtual
Implemented in listEventiterator, fileEventiterator, rcdaqEventiterator, testEventiterator, and oncsEventiterator.
Referenced by PHG4CylinderGeom_Spacalv3::Print(), DumpRawTowerGeomContainer::process_Node(), and pstatus().
virtual int Eventiterator::releaseEventData () inline virtual
Definition at line 39 of file Eventiterator.h.
virtual void Eventiterator::setBlockingMode (const int mode) inline virtual
Definition at line 41 of file Eventiterator.h.
virtual void Eventiterator::setSelectMode (const int mode) inline virtual
Definition at line 44 of file Eventiterator.h.
virtual void Eventiterator::setSelectWords (const int i1, const int i2, const int i3, const int i4) inline virtual
Definition at line 47 of file Eventiterator.h.
virtual int Eventiterator::setVerbosity (const int v) inline virtual
Reimplemented in fileEventiterator.
Definition at line 52 of file Eventiterator.h.
Referenced by main().
The documentation for this class was generated from the following file:
online_distribution/blob/master/newbasic/Eventiterator.h