Analysis Software: TrkrHitTruthAssoc Class Reference
TrkrHitTruthAssoc Class Reference
Association object for PHG4Cells contributiong to TrkrHits.
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitTruthAssoc.h>
Public Types
typedef std::multimap
< TrkrDefs::hitsetkey,
std::pair< TrkrDefs::hitkey,
PHG4HitDefs::keytype > > MMap
typedefs for convenience
typedef MMap::iterator Iterator
typedef MMap::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
TrkrHitTruthAssoc ()
ctor
virtual ~TrkrHitTruthAssoc ()
dtor
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
void addAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey)
Add an association between hit and cell.
void findOrAddAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey)
Add an association between hit and cell if it does not already exist.
void removeAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey)
void getG4Hits (const TrkrDefs::hitsetkey hitsetkey, const unsigned int hidx, MMap &temp_map)
Get cell keys associated with desired hit.
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (TrkrHitTruthAssoc, 1)
Private Attributes
MMap m_map
Detailed Description
Association object for PHG4Cells contributiong to TrkrHits.
Association object holding a multimap of PHG4Cells associated with a given TrkrHit
Definition at line 25 of file TrkrHitTruthAssoc.h.
Member Typedef Documentation
typedef MMap::const_iterator TrkrHitTruthAssoc::ConstIterator
Definition at line 31 of file TrkrHitTruthAssoc.h.
typedef std::pair<ConstIterator, ConstIterator> TrkrHitTruthAssoc::ConstRange
Definition at line 33 of file TrkrHitTruthAssoc.h.
typedef MMap::iterator TrkrHitTruthAssoc::Iterator
Definition at line 30 of file TrkrHitTruthAssoc.h.
typedef std::multimap< TrkrDefs::hitsetkey, std::pair<TrkrDefs::hitkey, PHG4HitDefs::keytype> > TrkrHitTruthAssoc::MMap
typedefs for convenience
Definition at line 29 of file TrkrHitTruthAssoc.h.
typedef std::pair<Iterator, Iterator> TrkrHitTruthAssoc::Range
Definition at line 32 of file TrkrHitTruthAssoc.h.
Constructor & Destructor Documentation
TrkrHitTruthAssoc::TrkrHitTruthAssoc ()
ctor
Definition at line 15 of file TrkrHitTruthAssoc.cc.
TrkrHitTruthAssoc::~TrkrHitTruthAssoc () virtual
dtor
Definition at line 20 of file TrkrHitTruthAssoc.cc.
Member Function Documentation
void TrkrHitTruthAssoc::addAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey)
Add an association between hit and cell.
Parameters
[in] hset TrkrHitSet key
[in] hidx TrkrHit index in TrkrHitSet
[in] ckey Key for assocuated g4hit
Definition at line 51 of file TrkrHitTruthAssoc.cc.
References m_map.
Referenced by PHG4MvtxHitReco::process_event(), and PHG4InttHitReco::process_event().
TrkrHitTruthAssoc::ClassDef (TrkrHitTruthAssoc , 1) private
void TrkrHitTruthAssoc::findOrAddAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey, const PHG4HitDefs::keytype g4hitkey)
Add an association between hit and cell if it does not already exist.
Parameters
[in] hset TrkrHitSet key
[in] hidx TrkrHit index in TrkrHitSet
[in] ckey Key for assocuated g4hit
Definition at line 59 of file TrkrHitTruthAssoc.cc.
References m_map.
Referenced by PHG4TpcElectronDrift::process_event().
void TrkrHitTruthAssoc::getG4Hits (const TrkrDefs::hitsetkey hitsetkey, const unsigned int hidx, MMap & temp_map)
Get cell keys associated with desired hit.
Parameters
[in] hset TrkrHitSet key
[in] hidx TrkrHit index in TrkrHitSet
Definition at line 108 of file TrkrHitTruthAssoc.cc.
References m_map.
Referenced by SvtxHitEval::all_truth_hits(), SvtxClusterEval::all_truth_hits(), TrkrEvaluator::fillOutputNtuples(), and PHTruthTrackSeeding::Process().
void TrkrHitTruthAssoc::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 31 of file TrkrHitTruthAssoc.cc.
References entry, TrkrDefs::getLayer(), and m_map.
Referenced by PHG4MvtxHitReco::process_event(), PHG4InttHitReco::process_event(), and PHG4TpcElectronDrift::process_event().
void TrkrHitTruthAssoc::removeAssoc (const TrkrDefs::hitsetkey hitsetkey, const TrkrDefs::hitkey hitkey)
Definition at line 84 of file TrkrHitTruthAssoc.cc.
References m_map.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells().
void TrkrHitTruthAssoc::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 25 of file TrkrHitTruthAssoc.cc.
References m_map.
Member Data Documentation
MMap TrkrHitTruthAssoc::m_map private
Definition at line 69 of file TrkrHitTruthAssoc.h.
Referenced by addAssoc(), findOrAddAssoc(), getG4Hits(), identify(), removeAssoc(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitTruthAssoc.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitTruthAssoc.cc