Analysis Software: QAG4SimulationCalorimeter Class Reference
QAG4SimulationCalorimeter Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeter.h>
Public Types
enum enu_flags { kProcessG4Hit = 1 << 1, kProcessTower = 1 << 2, kProcessCluster = 1 << 3, kDefaultFlag = kProcessG4Hit | kProcessTower | kProcessCluster }
Public Member Functions
QAG4SimulationCalorimeter (const std::string &calo_name, enu_flags flags=kDefaultFlag)
virtual ~QAG4SimulationCalorimeter ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
uint32_t get_flags () const
void set_flags (enu_flags flags)
void set_flag (enu_flags flag)
bool flag (enu_flags flag)
void reset_flag (enu_flags flag)
std::string get_histo_prefix ()
common prefix for QA histograms
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int Init_G4Hit (PHCompositeNode *topNode)
int process_event_G4Hit (PHCompositeNode *topNode)
int Init_Tower (PHCompositeNode *topNode)
int process_event_Tower (PHCompositeNode *topNode)
int Init_Cluster (PHCompositeNode *topNode)
int process_event_Cluster (PHCompositeNode *topNode)
Private Attributes
std::shared_ptr< CaloEvalStack > _caloevalstack
std::string _calo_name
uint32_t _flags
PHG4HitContainer * _calo_hit_container
PHG4HitContainer * _calo_abs_hit_container
PHG4TruthInfoContainer * _truth_container
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 21 of file QAG4SimulationCalorimeter.h.
Member Enumeration Documentation
enum QAG4SimulationCalorimeter::enu_flags
Enumerator:
kProcessG4Hit
kProcessTower
kProcessCluster
kDefaultFlag
Definition at line 24 of file QAG4SimulationCalorimeter.h.
Constructor & Destructor Documentation
QAG4SimulationCalorimeter::QAG4SimulationCalorimeter (const std::string & calo_name, QAG4SimulationCalorimeter::enu_flags flags = kDefaultFlag)
Definition at line 46 of file QAG4SimulationCalorimeter.cc.
virtual QAG4SimulationCalorimeter::~QAG4SimulationCalorimeter () inline virtual
Definition at line 35 of file QAG4SimulationCalorimeter.h.
Member Function Documentation
bool QAG4SimulationCalorimeter::flag (enu_flags flag) inline
Definition at line 60 of file QAG4SimulationCalorimeter.h.
References _flags.
Referenced by Init(), InitRun(), and process_event().
uint32_t QAG4SimulationCalorimeter::get_flags () const inline
Definition at line 42 of file QAG4SimulationCalorimeter.h.
References _flags.
string QAG4SimulationCalorimeter::get_histo_prefix ()
common prefix for QA histograms
Definition at line 198 of file QAG4SimulationCalorimeter.cc.
References _calo_name.
Referenced by Init(), Init_Cluster(), Init_G4Hit(), Init_Tower(), process_event(), process_event_Cluster(), process_event_G4Hit(), and process_event_Tower().
int QAG4SimulationCalorimeter::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 113 of file QAG4SimulationCalorimeter.cc.
References _calo_name, assert, Fun4AllReturnCodes::EVENT_OK, flag(), get_histo_prefix(), QAHistManagerDef::getHistoManager(), SVM_v1::h, i, Init_Cluster(), Init_G4Hit(), Init_Tower(), kProcessCluster, kProcessG4Hit, kProcessTower, Fun4AllHistoManager::registerHisto(), and Fun4AllBase::Verbosity().
int QAG4SimulationCalorimeter::Init_Cluster (PHCompositeNode * topNode) private
Definition at line 603 of file QAG4SimulationCalorimeter.cc.
References _calo_name, assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), and Fun4AllHistoManager::registerHisto().
Referenced by Init().
int QAG4SimulationCalorimeter::Init_G4Hit (PHCompositeNode * topNode) private
Definition at line 203 of file QAG4SimulationCalorimeter.cc.
References _calo_name, assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), SVM_v1::h, Fun4AllHistoManager::registerHisto(), and QAHistManagerDef::useLogBins().
Referenced by Init().
int QAG4SimulationCalorimeter::Init_Tower (PHCompositeNode * topNode) private
Definition at line 433 of file QAG4SimulationCalorimeter.cc.
References _calo_name, assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), SVM_v1::h, Fun4AllHistoManager::registerHisto(), and QAHistManagerDef::useLogBins().
Referenced by Init().
int QAG4SimulationCalorimeter::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 57 of file QAG4SimulationCalorimeter.cc.
References _calo_abs_hit_container, _calo_hit_container, _calo_name, _caloevalstack, _truth_container, assert, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), flag(), kProcessCluster, kProcessG4Hit, and Fun4AllBase::Verbosity().
int QAG4SimulationCalorimeter::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 154 of file QAG4SimulationCalorimeter.cc.
References _caloevalstack, assert, Fun4AllReturnCodes::EVENT_OK, flag(), get_histo_prefix(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), kProcessCluster, kProcessG4Hit, kProcessTower, process_event_Cluster(), process_event_G4Hit(), process_event_Tower(), and Fun4AllBase::Verbosity().
int QAG4SimulationCalorimeter::process_event_Cluster (PHCompositeNode * topNode) private
Definition at line 621 of file QAG4SimulationCalorimeter.cc.
References _calo_name, _caloevalstack, _truth_container, Fun4AllReturnCodes::ABORTRUN, assert, CaloRawClusterEval::best_cluster_from(), Fun4AllReturnCodes::EVENT_OK, RawCluster::get_energy(), get_histo_prefix(), RawCluster::get_position(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), PHG4TruthInfoContainer::GetMap(), PHG4TruthInfoContainer::GetPrimaryVtx(), SVM_v1::h, PHWHERE, RawClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int QAG4SimulationCalorimeter::process_event_G4Hit (PHCompositeNode * topNode) private
Definition at line 251 of file QAG4SimulationCalorimeter.cc.
References _calo_abs_hit_container, _calo_hit_container, _calo_name, _truth_container, assert, Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_avg_t(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), PHG4Particle::get_e(), PHG4Hit::get_edep(), get_histo_prefix(), PHG4Hit::get_light_yield(), PHG4Particle::get_pid(), PHG4VtxPoint::get_t(), PHG4Hit::get_trkid(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), PHG4HitContainer::getHits(), PHG4TruthInfoContainer::GetMap(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), PHG4TruthInfoContainer::GetPrimaryVtx(), SVM_v1::h, PHG4Hit::identify(), PHG4VtxPoint::identify(), PHG4HitContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int QAG4SimulationCalorimeter::process_event_Tower (PHCompositeNode * topNode) private
Definition at line 487 of file QAG4SimulationCalorimeter.cc.
References _calo_name, Fun4AllReturnCodes::ABORTRUN, assert, energy, Fun4AllReturnCodes::EVENT_OK, RawTower::get_energy(), RawTowerGeomContainer::get_etabins(), get_histo_prefix(), RawTowerGeomContainer::get_phibins(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), RawTowerContainer::getTower(), SVM_v1::h, PHWHERE, RawTowerContainer::size(), RawTowerGeomContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
void QAG4SimulationCalorimeter::reset_flag (enu_flags flag) inline
Definition at line 66 of file QAG4SimulationCalorimeter.h.
References _flags.
void QAG4SimulationCalorimeter::set_flag (enu_flags flag) inline
Definition at line 54 of file QAG4SimulationCalorimeter.h.
References _flags.
void QAG4SimulationCalorimeter::set_flags (enu_flags flags) inline
Definition at line 48 of file QAG4SimulationCalorimeter.h.
References _flags.
Member Data Documentation
PHG4HitContainer* QAG4SimulationCalorimeter::_calo_abs_hit_container private
Definition at line 94 of file QAG4SimulationCalorimeter.h.
Referenced by InitRun(), and process_event_G4Hit().
PHG4HitContainer* QAG4SimulationCalorimeter::_calo_hit_container private
Definition at line 93 of file QAG4SimulationCalorimeter.h.
Referenced by InitRun(), and process_event_G4Hit().
std::string QAG4SimulationCalorimeter::_calo_name private
Definition at line 90 of file QAG4SimulationCalorimeter.h.
Referenced by get_histo_prefix(), Init(), Init_Cluster(), Init_G4Hit(), Init_Tower(), InitRun(), process_event_Cluster(), process_event_G4Hit(), and process_event_Tower().
std::shared_ptr<CaloEvalStack> QAG4SimulationCalorimeter::_caloevalstack private
Definition at line 87 of file QAG4SimulationCalorimeter.h.
Referenced by InitRun(), process_event(), and process_event_Cluster().
uint32_t QAG4SimulationCalorimeter::_flags private
Definition at line 91 of file QAG4SimulationCalorimeter.h.
Referenced by flag(), get_flags(), reset_flag(), set_flag(), and set_flags().
PHG4TruthInfoContainer* QAG4SimulationCalorimeter::_truth_container private
Definition at line 95 of file QAG4SimulationCalorimeter.h.
Referenced by InitRun(), process_event_Cluster(), and process_event_G4Hit().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeter.h
coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeter.cc