Analysis Software: PHG4RICHDetector Class Reference
PHG4RICHDetector Class Reference
This class creates the ePHENIX RICH volumes for Geant4 within Fun4All via ePHENIXRICH::ePHENIXRICHConstruction based on the geometry information in ePHENIXRICH::RICH_Geometry.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4RICHDetector.h>
Public Member Functions
PHG4RICHDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dname, const ePHENIXRICH::RICH_Geometry &g)
PHG4RICHDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dname)
virtual ~PHG4RICHDetector (void)
virtual void ConstructMe (G4LogicalVolume *world)
virtual G4UserSteppingAction * GetSteppingAction ()
virtual void OverlapCheck (const bool chk=true)
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual std::string GetName () const
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Public Member Functions inherited from ePHENIXRICH::ePHENIXRICHConstruction
virtual ~ePHENIXRICHConstruction ()
ePHENIXRICHConstruction (PHG4Subsystem *subsys)
ePHENIXRICHConstruction (PHG4Subsystem *subsys, const RICH_Geometry &g)
G4LogicalVolume * Construct_RICH (G4LogicalVolume *)
G4LogicalVolume * Construct_HBD (G4LogicalVolume *RICHSecLog)
G4LogicalVolume * Construct_HBD_Layers (G4LogicalVolume *RICHHBDLog, const G4String name, const G4String material, const double start_z, const double thickness)
int is_in_sector (G4VPhysicalVolume *) const
PHG4RICHDisplayAction * GetDisplayAction ()
Private Attributes
G4Region * _region
Additional Inherited Members
Public Attributes inherited from ePHENIXRICH::ePHENIXRICHConstruction
RICH_Geometry geom
Protected Types inherited from ePHENIXRICH::ePHENIXRICHConstruction
typedef std::map< G4String,
G4LogicalVolume * > map_log_vol_t
typedef std::pair< G4String,
G4int > phy_vol_idx_t
typedef std::map
< phy_vol_idx_t, G4PVPlacement * > map_phy_vol_t
Protected Member Functions inherited from ePHENIXRICH::ePHENIXRICHConstruction
G4LogicalVolume * RegisterLogicalVolume (G4LogicalVolume *)
G4PVPlacement * RegisterPhysicalVolume (G4PVPlacement *)
Protected Attributes inherited from ePHENIXRICH::ePHENIXRICHConstruction
map_log_vol_t map_log_vol
PHG4RICHDisplayAction * m_DisplayAction
map_phy_vol_t map_phy_vol
bool overlapcheck_rich
std::set< G4VPhysicalVolume * > sector_vec
Detailed Description
This class creates the ePHENIX RICH volumes for Geant4 within Fun4All via ePHENIXRICH::ePHENIXRICHConstruction based on the geometry information in ePHENIXRICH::RICH_Geometry.
See Also
ePHENIXRICH::RICH_Geometry
ePHENIXRICH::ePHENIXRICHConstruction
PHG4RICHDetector
PHG4RICHSteppingAction
PHG4RICHSubsystem
Definition at line 40 of file PHG4RICHDetector.h.
Constructor & Destructor Documentation
PHG4RICHDetector::PHG4RICHDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dname, const ePHENIXRICH::RICH_Geometry & g)
Definition at line 28 of file PHG4RICHDetector.cc.
PHG4RICHDetector::PHG4RICHDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dname)
Definition at line 35 of file PHG4RICHDetector.cc.
virtual PHG4RICHDetector::~PHG4RICHDetector (void) inline virtual
Definition at line 47 of file PHG4RICHDetector.h.
Member Function Documentation
void PHG4RICHDetector::ConstructMe (G4LogicalVolume * world) virtual
Implements PHG4Detector.
Definition at line 42 of file PHG4RICHDetector.cc.
References _region, and ePHENIXRICH::ePHENIXRICHConstruction::map_log_vol.
virtual G4UserSteppingAction* PHG4RICHDetector::GetSteppingAction (void) inline virtual
Reimplemented from PHG4Detector.
Definition at line 55 of file PHG4RICHDetector.h.
References _region.
Referenced by PHG4RICHSubsystem::process_event().
virtual void PHG4RICHDetector::OverlapCheck (const bool chk = true) inline virtual
Reimplemented from ePHENIXRICH::ePHENIXRICHConstruction.
Definition at line 63 of file PHG4RICHDetector.h.
References PHG4Detector::OverlapCheck().
Referenced by PHG4RICHSubsystem::Init().
Member Data Documentation
G4Region* PHG4RICHDetector::_region private
Definition at line 70 of file PHG4RICHDetector.h.
Referenced by ConstructMe(), and GetSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4RICHDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4RICHDetector.cc