Analysis Software: JetEvaluator Class Reference
JetEvaluator Class Reference
Compares reconstructed jets to truth jets.
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/JetEvaluator.h>
Public Member Functions
JetEvaluator (const std::string &name="JETEVALUATOR", const std::string &recojetname="AntiKt_Tower_r0.3", const std::string &truthjetname="AntiKt_Truth_r0.3", const std::string &filename="g4eval_jets.root")
virtual ~JetEvaluator ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_strict (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
std::string _recojetname
std::string _truthjetname
unsigned long _ievent
JetEvalStack * _jetevalstack
bool _strict
bool _do_recojet_eval
bool _do_truthjet_eval
TNtuple * _ntp_recojet
TNtuple * _ntp_truthjet
std::string _filename
TFile * _tfile
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Compares reconstructed jets to truth jets.
Plan: This module will trace the jet constituents to the greatest contributor Monte Carlo jet and then test one against the other.
Definition at line 27 of file JetEvaluator.h.
Constructor & Destructor Documentation
JetEvaluator::JetEvaluator (const std::string & name = "JETEVALUATOR", const std::string & recojetname = "AntiKt_Tower_r0.3", const std::string & truthjetname = "AntiKt_Truth_r0.3", const std::string & filename = "g4eval_jets.root")
Definition at line 26 of file JetEvaluator.cc.
virtual JetEvaluator::~JetEvaluator () inline virtual
Definition at line 34 of file JetEvaluator.h.
Member Function Documentation
int JetEvaluator::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 100 of file JetEvaluator.cc.
References _do_recojet_eval, _do_truthjet_eval, _filename, _ievent, _jetevalstack, _ntp_recojet, _ntp_truthjet, _tfile, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
void JetEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 135 of file JetEvaluator.cc.
References _do_recojet_eval, _do_truthjet_eval, _ievent, _jetevalstack, _ntp_recojet, _ntp_truthjet, _recojetname, _truthjetname, JetMap::begin(), JetRecoEval::best_jet_from(), JetMap::end(), Jet::get_e(), JetRecoEval::get_energy_contribution(), Jet::get_eta(), Jet::get_id(), Jet::get_phi(), Jet::get_pt(), JetEvalStack::get_reco_eval(), JetRecoEval::max_truth_jet_by_energy(), phi, PHWHERE, Jet::size_comp(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int JetEvaluator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 45 of file JetEvaluator.cc.
References _do_recojet_eval, _do_truthjet_eval, _filename, _ievent, _ntp_recojet, _ntp_truthjet, _tfile, and Fun4AllReturnCodes::EVENT_OK.
void JetEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 123 of file JetEvaluator.cc.
Referenced by process_event().
void JetEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 129 of file JetEvaluator.cc.
Referenced by process_event().
int JetEvaluator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 64 of file JetEvaluator.cc.
References _ievent, _jetevalstack, _recojetname, _strict, _truthjetname, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), JetEvalStack::next_event(), printInputInfo(), printOutputInfo(), JetEvalStack::set_strict(), JetEvalStack::set_verbosity(), and Fun4AllBase::Verbosity().
void JetEvaluator::set_strict (bool b) inline
Definition at line 40 of file JetEvaluator.h.
References _strict.
Member Data Documentation
bool JetEvaluator::_do_recojet_eval private
Definition at line 55 of file JetEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
bool JetEvaluator::_do_truthjet_eval private
Definition at line 56 of file JetEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
std::string JetEvaluator::_filename private
Definition at line 62 of file JetEvaluator.h.
Referenced by End(), and Init().
unsigned long JetEvaluator::_ievent private
Definition at line 46 of file JetEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), and process_event().
JetEvalStack* JetEvaluator::_jetevalstack private
Definition at line 48 of file JetEvaluator.h.
Referenced by End(), fillOutputNtuples(), and process_event().
TNtuple* JetEvaluator::_ntp_recojet private
Definition at line 58 of file JetEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* JetEvaluator::_ntp_truthjet private
Definition at line 59 of file JetEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
std::string JetEvaluator::_recojetname private
Definition at line 43 of file JetEvaluator.h.
Referenced by fillOutputNtuples(), and process_event().
bool JetEvaluator::_strict private
Definition at line 53 of file JetEvaluator.h.
Referenced by process_event(), and set_strict().
TFile* JetEvaluator::_tfile private
Definition at line 63 of file JetEvaluator.h.
Referenced by End(), and Init().
std::string JetEvaluator::_truthjetname private
Definition at line 44 of file JetEvaluator.h.
Referenced by fillOutputNtuples(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/JetEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/JetEvaluator.cc