Analysis Software: FitNewton::FunctionGradHessian Class Reference
FitNewton::FunctionGradHessian Class Reference abstract
#include <coresoftware/blob/master/offline/packages/HelixHough/FitNewton/FunctionGradHessian.h>
Public Member Functions
FunctionGradHessian (unsigned int nparams=1, unsigned int nfixedparams=1)
virtual ~FunctionGradHessian ()
virtual bool calcValGradHessian (const Eigen::VectorXd &x, double &val, Eigen::VectorXd &grad, Eigen::MatrixXd &hessian)=0
virtual bool calcValGrad (const Eigen::VectorXd &x, double &val, Eigen::VectorXd &grad)
unsigned int nPars ()
unsigned int nFixedPars ()
std::vector< double > getFixedPars ()
void setFixedPar (unsigned int coor, double val)
virtual FunctionGradHessian * Clone () const =0
virtual void computeCovariance (const double &val, const Eigen::MatrixXd &hessian)
virtual void rescaleMove (const Eigen::VectorXd &pars, Eigen::VectorXd &move)
Protected Attributes
unsigned int npars
unsigned int nfixedpars
std::vector< double > fixedpars
Detailed Description
Definition at line 9 of file FunctionGradHessian.h.
Constructor & Destructor Documentation
FitNewton::FunctionGradHessian::FunctionGradHessian (unsigned int nparams = 1, unsigned int nfixedparams = 1) inline
Definition at line 12 of file FunctionGradHessian.h.
References fixedpars, and nfixedpars.
virtual FitNewton::FunctionGradHessian::~FunctionGradHessian () inline virtual
Definition at line 17 of file FunctionGradHessian.h.
Member Function Documentation
virtual bool FitNewton::FunctionGradHessian::calcValGrad (const Eigen::VectorXd & x, double & val, Eigen::VectorXd & grad) inline virtual
Reimplemented in FitNewton::ChiSquareGradHessian, and FitNewton::SquareGradient.
Definition at line 21 of file FunctionGradHessian.h.
References calcValGradHessian().
Referenced by FitNewton::ChiSquareGradHessian::calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGradHessian(), and FitNewton::ChiSquareGradHessian::calcValGradThread1().
virtual bool FitNewton::FunctionGradHessian::calcValGradHessian (const Eigen::VectorXd & x, double & val, Eigen::VectorXd & grad, Eigen::MatrixXd & hessian) pure virtual
Implemented in FitNewton::GaussianRegGradHessian, VertexFitFunc, FitNewton::ChiSquareGradHessian, HelixDCAFunc, FitNewton::SquareGradient, FitNewton::GaussianGradHessian, and FitNewton::GaussianIntegralGradHessian.
Referenced by calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGradHessianThread1(), FitNewton::GaussianRegGradHessian::calcValGradHessianThread1(), and FitNewton::NewtonMinimizerGradHessian::findSaddlePoint().
virtual FunctionGradHessian* FitNewton::FunctionGradHessian::Clone () const pure virtual
Implemented in FitNewton::GaussianRegGradHessian, VertexFitFunc, FitNewton::ChiSquareGradHessian, FitNewton::SquareGradient, HelixDCAFunc, FitNewton::GaussianGradHessian, and FitNewton::GaussianIntegralGradHessian.
Referenced by FitNewton::ChiSquareGradHessian::calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGradHessian(), FitNewton::ChiSquareGradHessian::calcValGradHessianThread1(), FitNewton::GaussianRegGradHessian::calcValGradHessianThread1(), and FitNewton::ChiSquareGradHessian::calcValGradThread1().
virtual void FitNewton::FunctionGradHessian::computeCovariance (const double & val, const Eigen::MatrixXd & hessian) inline virtual
Reimplemented in FitNewton::GaussianRegGradHessian, and FitNewton::ChiSquareGradHessian.
Definition at line 36 of file FunctionGradHessian.h.
Referenced by FitNewton::NewtonMinimizerGradHessian::findSaddlePoint().
std::vector<double> FitNewton::FunctionGradHessian::getFixedPars () inline
Definition at line 29 of file FunctionGradHessian.h.
References fixedpars.
Referenced by FitNewton::SquareGradient::SquareGradient().
unsigned int FitNewton::FunctionGradHessian::nFixedPars () inline
Definition at line 28 of file FunctionGradHessian.h.
References nfixedpars.
unsigned int FitNewton::FunctionGradHessian::nPars () inline
Definition at line 27 of file FunctionGradHessian.h.
References npars.
Referenced by FitNewton::NewtonMinimizerGradHessian::setFunction().
virtual void FitNewton::FunctionGradHessian::rescaleMove (const Eigen::VectorXd & pars, Eigen::VectorXd & move) inline virtual
Definition at line 38 of file FunctionGradHessian.h.
Referenced by FitNewton::NewtonMinimizerGradHessian::findSaddlePoint().
void FitNewton::FunctionGradHessian::setFixedPar (unsigned int coor, double val) inline
Definition at line 31 of file FunctionGradHessian.h.
References fixedpars.
Referenced by FitNewton::ChiSquareGradHessian::calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGradHessian(), VertexFitFunc::calcValGradHessian(), FitNewton::ChiSquareGradHessian::calcValGradHessianThread1(), FitNewton::GaussianRegGradHessian::calcValGradHessianThread1(), FitNewton::ChiSquareGradHessian::calcValGradThread1(), FitNewton::GaussianGradHessian::Clone(), FitNewton::GaussianIntegralGradHessian::Clone(), and main().
Member Data Documentation
std::vector<double> FitNewton::FunctionGradHessian::fixedpars protected
Definition at line 46 of file FunctionGradHessian.h.
Referenced by FitNewton::GaussianGradHessian::calcValGradHessian(), FitNewton::GaussianIntegralGradHessian::calcValGradHessian(), HelixDCAFunc::calcValGradHessian(), VertexFitFunc::calcValGradHessian(), FitNewton::GaussianGradHessian::Clone(), FitNewton::GaussianIntegralGradHessian::Clone(), FunctionGradHessian(), getFixedPars(), setFixedPar(), and FitNewton::SquareGradient::SquareGradient().
unsigned int FitNewton::FunctionGradHessian::nfixedpars protected
Definition at line 44 of file FunctionGradHessian.h.
Referenced by FunctionGradHessian(), and nFixedPars().
unsigned int FitNewton::FunctionGradHessian::npars protected
Definition at line 43 of file FunctionGradHessian.h.
Referenced by FitNewton::SquareGradient::calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGrad(), FitNewton::ChiSquareGradHessian::calcValGradHessian(), FitNewton::GaussianRegGradHessian::calcValGradHessian(), FitNewton::ChiSquareGradHessian::calcValGradHessianThread1(), FitNewton::GaussianRegGradHessian::calcValGradHessianThread1(), FitNewton::ChiSquareGradHessian::calcValGradThread1(), FitNewton::ChiSquareGradHessian::computeCovariance(), FitNewton::GaussianRegGradHessian::computeCovariance(), and nPars().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/HelixHough/FitNewton/FunctionGradHessian.h