Analysis Software: MomentumEvaluator Class Reference
MomentumEvaluator Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/MomentumEvaluator.h>
Public Member Functions
MomentumEvaluator (const std::string &fname, float pt_s=0.1, float pz_s=0.2, unsigned int n_l=62, unsigned int n_i=2, unsigned int n_r=50, float i_z=10., float o_z=80.)
~MomentumEvaluator ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
TNtuple * ntp_true
TNtuple * ntp_reco
float pt_search_scale
float pz_search_scale
unsigned int event_counter
std::string file_name
unsigned int n_inner_layers
unsigned int n_required_layers
float inner_z_length
float outer_z_length
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 11 of file MomentumEvaluator.h.
Constructor & Destructor Documentation
MomentumEvaluator::MomentumEvaluator (const std::string & fname, float pt_s = 0.1, float pz_s = 0.2, unsigned int n_l = 62, unsigned int n_i = 2, unsigned int n_r = 50, float i_z = 10., float o_z = 80.)
Definition at line 359 of file MomentumEvaluator.cc.
MomentumEvaluator::~MomentumEvaluator ()
Definition at line 372 of file MomentumEvaluator.cc.
References ntp_reco, and ntp_true.
Member Function Documentation
int MomentumEvaluator::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 598 of file MomentumEvaluator.cc.
References Fun4AllReturnCodes::EVENT_OK, file_name, ntp_reco, and ntp_true.
int MomentumEvaluator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 384 of file MomentumEvaluator.cc.
References event_counter, Fun4AllReturnCodes::EVENT_OK, ntp_reco, and ntp_true.
int MomentumEvaluator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 402 of file MomentumEvaluator.cc.
References RecursiveMomentumContainer::append_list(), SvtxTrackMap::begin(), RecursiveMomentumContainer::begin(), TrivialTrack::dcax, TrivialTrack::dcay, TrivialTrack::dcaz, SvtxTrackMap::end(), event_counter, Fun4AllReturnCodes::EVENT_OK, PHG4Hit::get_layer(), PHG4Particle::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), SvtxTrack::get_x(), SvtxTrack::get_y(), PHG4Hit::get_z(), SvtxTrack::get_z(), PHG4TruthInfoContainer::GetMap(), PHG4TruthInfoContainer::GetPrimaryVertexIndex(), PHG4TruthInfoContainer::GetPrimaryVtx(), PHG4TruthInfoContainer::GetVtx(), i, inner_z_length, RecursiveMomentumContainer::insert(), n_inner_layers, n_required_layers, RecursiveMomentumContainer::next(), ntp_reco, ntp_true, outer_z_length, pt_search_scale, TrivialTrack::px, TrivialTrack::py, TrivialTrack::pz, pz_search_scale, and TrivialTrack::quality.
Member Data Documentation
unsigned int MomentumEvaluator::event_counter private
Definition at line 26 of file MomentumEvaluator.h.
Referenced by Init(), and process_event().
std::string MomentumEvaluator::file_name private
Definition at line 27 of file MomentumEvaluator.h.
Referenced by End().
float MomentumEvaluator::inner_z_length private
Definition at line 30 of file MomentumEvaluator.h.
Referenced by process_event().
unsigned int MomentumEvaluator::n_inner_layers private
Definition at line 28 of file MomentumEvaluator.h.
Referenced by process_event().
unsigned int MomentumEvaluator::n_required_layers private
Definition at line 29 of file MomentumEvaluator.h.
Referenced by process_event().
TNtuple* MomentumEvaluator::ntp_reco private
Definition at line 23 of file MomentumEvaluator.h.
Referenced by End(), Init(), process_event(), and ~MomentumEvaluator().
TNtuple* MomentumEvaluator::ntp_true private
Definition at line 22 of file MomentumEvaluator.h.
Referenced by End(), Init(), process_event(), and ~MomentumEvaluator().
float MomentumEvaluator::outer_z_length private
Definition at line 31 of file MomentumEvaluator.h.
Referenced by process_event().
float MomentumEvaluator::pt_search_scale private
Definition at line 24 of file MomentumEvaluator.h.
Referenced by process_event().
float MomentumEvaluator::pz_search_scale private
Definition at line 25 of file MomentumEvaluator.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/MomentumEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/MomentumEvaluator.cc