Analysis Software: analysis/blob/master/Prototype2/EMCal/macros/DrawPrototype2EMCalTower_ResolutionRecalib.C File Reference
DrawPrototype2EMCalTower_ResolutionRecalib.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <TLatex.h>
#include <TGraphErrors.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawPrototype2EMCalTower_ResolutionRecalib (const TString base="/phenix/u/jinhuang/tmp/miliped_work/Production_0414/calirbated_")
vector< double > RecalibratorMakeOnePlot (const TString base, const int run, const double E)
Variables
bool mask = true
Function Documentation
void DrawPrototype2EMCalTower_ResolutionRecalib (const TString base = "/phenix/u/jinhuang/tmp/miliped_work/Production_0414/calirbated_")
Definition at line 26 of file DrawPrototype2EMCalTower_ResolutionRecalib.C.
References assert, E, Es, i, leg, mask, N, RecalibratorMakeOnePlot(), runs, SaveCanvas(), SetOKStyle(), t, and v.
vector<double> RecalibratorMakeOnePlot (const TString base, const int run, const double E)
Definition at line 220 of file DrawPrototype2EMCalTower_ResolutionRecalib.C.
References assert, E, SVM_v1::h, in, line, mask, and v.
Referenced by DrawPrototype2EMCalTower_ResolutionRecalib().
Variable Documentation
bool mask = true
Definition at line 23 of file DrawPrototype2EMCalTower_ResolutionRecalib.C.
Referenced by DrawPrototype2EMCalTower_ResolutionRecalib(), oncsSub_idmvtxv0::print_stuff(), oncsSub_idmvtxv1::print_stuff(), RecalibratorMakeOnePlot(), simpleRandom::rnd(), and SvtxSimPerformanceCheckReco::set_inner_layer_mask().