Analysis Software: MvtxClusterizer Class Reference
MvtxClusterizer Class Reference
Clusterizer for the MVTX.
#include <coresoftware/blob/master/offline/packages/mvtx/MvtxClusterizer.h>
Public Types
typedef std::pair< unsigned
int, unsigned int > pixel
Public Member Functions
MvtxClusterizer (const std::string &name="MvtxClusterizer")
virtual ~MvtxClusterizer ()
int Init (PHCompositeNode *topNode)
module initialization
int InitRun (PHCompositeNode *topNode)
run initialization
int process_event (PHCompositeNode *topNode)
event processing
int End (PHCompositeNode *topNode)
end of process
void SetZClustering (const bool make_z_clustering)
option to turn off z-dimension clustering
bool GetZClustering () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
bool are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > &lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > &rhs)
void ClusterMvtx (PHCompositeNode *topNode)
void PrintClusters (PHCompositeNode *topNode)
Private Attributes
TrkrHitSetContainer * m_hits
TrkrClusterContainer * m_clusterlist
TrkrClusterHitAssoc * m_clusterhitassoc
bool m_makeZClustering
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Clusterizer for the MVTX.
Definition at line 25 of file MvtxClusterizer.h.
Member Typedef Documentation
typedef std::pair<unsigned int, unsigned int> MvtxClusterizer::pixel
Definition at line 28 of file MvtxClusterizer.h.
Constructor & Destructor Documentation
MvtxClusterizer::MvtxClusterizer (const std::string & name = "MvtxClusterizer")
Definition at line 79 of file MvtxClusterizer.cc.
virtual MvtxClusterizer::~MvtxClusterizer () inline virtual
Definition at line 31 of file MvtxClusterizer.h.
Member Function Documentation
bool MvtxClusterizer::are_adjacent (const std::pair< TrkrDefs::hitkey, TrkrHit * > & lhs, const std::pair< TrkrDefs::hitkey, TrkrHit * > & rhs) private
Definition at line 52 of file MvtxClusterizer.cc.
References MvtxDefs::getCol(), and MvtxDefs::getRow().
Referenced by ClusterMvtx().
void MvtxClusterizer::ClusterMvtx (PHCompositeNode * topNode) private
Definition at line 197 of file MvtxClusterizer.cc.
References TrkrClusterHitAssoc::addAssoc(), are_adjacent(), col, CylinderGeom_Mvtx::find_sensor_center(), TrkrClusterContainer::findOrAddCluster(), G, MvtxDefs::genClusKey(), CylinderGeom_Mvtx::get_local_coords_from_pixel(), CylinderGeom_Mvtx::get_pixel_number_from_xbin_zbin(), CylinderGeom_Mvtx::get_pixel_thickness(), CylinderGeom_Mvtx::get_pixel_x(), CylinderGeom_Mvtx::get_pixel_z(), CylinderGeom_Mvtx::get_stave_phi_tilt(), CylinderGeom_Mvtx::get_world_from_local_coords(), MvtxDefs::getChipId(), MvtxDefs::getCol(), TrkrHitSet::getHits(), TrkrHitSet::getHitSetKey(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), MvtxDefs::getRow(), MvtxDefs::getStaveId(), i, TrkrClusterHitAssoc::identify(), TrkrHitSet::identify(), j, m_clusterhitassoc, m_clusterlist, m_hits, TrkrDefs::mvtxId, phibins, and Fun4AllBase::Verbosity().
Referenced by process_event().
int MvtxClusterizer::End (PHCompositeNode * topNode) inline virtual
end of process
Reimplemented from SubsysReco.
Definition at line 43 of file MvtxClusterizer.h.
bool MvtxClusterizer::GetZClustering () const inline
Definition at line 50 of file MvtxClusterizer.h.
References m_makeZClustering.
int MvtxClusterizer::Init (PHCompositeNode * topNode) inline virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 34 of file MvtxClusterizer.h.
int MvtxClusterizer::InitRun (PHCompositeNode * topNode) virtual
run initialization
Reimplemented from SubsysReco.
Definition at line 88 of file MvtxClusterizer.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), m_makeZClustering, PHWHERE, and Fun4AllBase::Verbosity().
void MvtxClusterizer::PrintClusters (PHCompositeNode * topNode) private
Definition at line 465 of file MvtxClusterizer.cc.
References TrkrClusterContainer::identify(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int MvtxClusterizer::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 163 of file MvtxClusterizer.cc.
References Fun4AllReturnCodes::ABORTRUN, ClusterMvtx(), Fun4AllReturnCodes::EVENT_OK, m_clusterhitassoc, m_clusterlist, m_hits, PHWHERE, and PrintClusters().
void MvtxClusterizer::SetZClustering (const bool make_z_clustering) inline
option to turn off z-dimension clustering
Definition at line 46 of file MvtxClusterizer.h.
References m_makeZClustering.
Member Data Documentation
TrkrClusterHitAssoc* MvtxClusterizer::m_clusterhitassoc private
Definition at line 66 of file MvtxClusterizer.h.
Referenced by ClusterMvtx(), and process_event().
TrkrClusterContainer* MvtxClusterizer::m_clusterlist private
Definition at line 65 of file MvtxClusterizer.h.
Referenced by ClusterMvtx(), and process_event().
TrkrHitSetContainer* MvtxClusterizer::m_hits private
Definition at line 64 of file MvtxClusterizer.h.
Referenced by ClusterMvtx(), and process_event().
bool MvtxClusterizer::m_makeZClustering private
Definition at line 69 of file MvtxClusterizer.h.
Referenced by GetZClustering(), InitRun(), and SetZClustering().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mvtx/MvtxClusterizer.h
coresoftware/blob/master/offline/packages/mvtx/MvtxClusterizer.cc