Analysis Software: analysis/blob/master/TPC/groot/FillBlobHist.h File Reference
FillBlobHist.h File Reference
Functions
void FillBlobHist ()
int line_circle (double m, double b, double r, double &Xi1, double &Yi1, double &Xi2, double &Yi2)
int line_circle (double X1, double Y1, double X2, double Y2, double r, double &Xi1, double &Yi1, double &Xi2, double &Yi2)
Function Documentation
void FillBlobHist ()
Definition at line 47 of file FillBlobHist.C.
References BH_5Efficiency, BH_5Residual, BH_5Residual_PC, BH_5Residual_vsPhi, BH_5Residual_vsPhi_PC, BH_Efficiency_, BH_PhiTic, BH_PhivsR, BH_Q, BH_QvsSize, BH_Residual_, BH_Residual_PC_, BH_Residual_vsPhi_, BH_Residual_vsPhi_PC_, BH_Size, BH_Tdiff, BH_Tmax, i, groot::instance(), j, k, line_circle(), max, min, name, Nphi, Nr, AZigzag::PCenter(), groot::theBlobs, groot::theHistograms, groot::theZigzags, and groot::ZigzagMap2.
Referenced by process_event().
int line_circle (double m, double b, double r, double & Xi1, double & Yi1, double & Xi2, double & Yi2)
Definition at line 318 of file FillBlobHist.C.
References line_circle().
Referenced by FillBlobHist(), and line_circle().
int line_circle (double X1, double Y1, double X2, double Y2, double r, double & Xi1, double & Yi1, double & Xi2, double & Yi2)
Definition at line 324 of file FillBlobHist.C.
References dx, dy, and sign().