Analysis Software: PgPostBankWrapperManager Class Reference
PgPostBankWrapperManager Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankWrapperManager.h>
Public Member Functions
void clear ()
bool commit ()
void print () const
bool registerWrapper (PgPostBankWrapper *wrapper)
bool unregisterWrapper (PgPostBankWrapper *wrapper)
Static Public Member Functions
static PgPostBankWrapperManager & instance ()
Private Types
typedef std::vector
< PgPostBankWrapper * > WVECTOR
Private Member Functions
PgPostBankWrapperManager ()
Private Attributes
WVECTOR fWrappers
Detailed Description
Definition at line 10 of file PgPostBankWrapperManager.h.
Member Typedef Documentation
typedef std::vector<PgPostBankWrapper*> PgPostBankWrapperManager::WVECTOR private
Definition at line 28 of file PgPostBankWrapperManager.h.
Constructor & Destructor Documentation
PgPostBankWrapperManager::PgPostBankWrapperManager () inline private
Definition at line 26 of file PgPostBankWrapperManager.h.
Member Function Documentation
void PgPostBankWrapperManager::clear ()
Definition at line 23 of file PgPostBankWrapperManager.cc.
References fWrappers.
Referenced by PgPostApplication::abort(), commit(), and PgPostApplication::commit().
bool PgPostBankWrapperManager::commit ()
Definition at line 31 of file PgPostBankWrapperManager.cc.
References clear(), fWrappers, and it.
Referenced by PgPostApplication::commit().
PgPostBankWrapperManager & PgPostBankWrapperManager::instance () static
Definition at line 16 of file PgPostBankWrapperManager.cc.
Referenced by PgPostApplication::abort(), PgPostApplication::commit(), PgPostBankWrapper::PgPostBankWrapper(), and PgPostBankWrapper::~PgPostBankWrapper().
void PgPostBankWrapperManager::print () const
Definition at line 45 of file PgPostBankWrapperManager.cc.
References fWrappers, PgPostBankWrapper::getBankID(), PdbBankID::getInternalValue(), PgPostBankWrapper::getTableName(), i, it, and PHWHERE.
bool PgPostBankWrapperManager::registerWrapper (PgPostBankWrapper * wrapper)
Definition at line 70 of file PgPostBankWrapperManager.cc.
References fWrappers, it, and PHWHERE.
Referenced by PgPostBankWrapper::PgPostBankWrapper().
bool PgPostBankWrapperManager::unregisterWrapper (PgPostBankWrapper * wrapper)
Definition at line 93 of file PgPostBankWrapperManager.cc.
References fWrappers, it, and PHWHERE.
Referenced by PgPostBankWrapper::~PgPostBankWrapper().
Member Data Documentation
WVECTOR PgPostBankWrapperManager::fWrappers private
Definition at line 30 of file PgPostBankWrapperManager.h.
Referenced by clear(), commit(), print(), registerWrapper(), and unregisterWrapper().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankWrapperManager.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankWrapperManager.cc