Analysis Software: TrkrHitSetContainer Class Reference
TrkrHitSetContainer Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainer.h>
Public Types
typedef std::map
< TrkrDefs::hitsetkey,
TrkrHitSet * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
TrkrHitSetContainer ()
ctor
virtual ~TrkrHitSetContainer ()
dtor
void Reset ()
PHObject functions.
void identify (std::ostream &os=std::cout) const
ConstIterator addHitSet (TrkrHitSet *newHit)
Add a TrkrHitSet to the container.
ConstIterator addHitSetSpecifyKey (const TrkrDefs::hitsetkey key, TrkrHitSet *newHit)
void removeHitSet (TrkrDefs::hitsetkey key)
preferred removal method, key is currently the hit id
void removeHitSet (TrkrHitSet *hit)
inefficent, use key where possible instead
Iterator findOrAddHitSet (TrkrDefs::hitsetkey key)
find or add HitSet
ConstRange getHitSets (const TrkrDefs::TrkrId trackerid) const
return all HitSets matching a given detid
ConstRange getHitSets (const TrkrDefs::TrkrId trackerid, const char layer) const
return all HitSets matching a given detid, layer
ConstRange getHitSets (void) const
return all HitSets
TrkrHitSet * findHitSet (TrkrDefs::hitsetkey key)
return a given HitSet based on its key
unsigned int size (void) const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map m_hitmap
Detailed Description
Container for TrkrHitSet objects
Definition at line 17 of file TrkrHitSetContainer.h.
Member Typedef Documentation
typedef Map::const_iterator TrkrHitSetContainer::ConstIterator
Definition at line 22 of file TrkrHitSetContainer.h.
typedef std::pair<ConstIterator, ConstIterator> TrkrHitSetContainer::ConstRange
Definition at line 24 of file TrkrHitSetContainer.h.
typedef Map::iterator TrkrHitSetContainer::Iterator
Definition at line 21 of file TrkrHitSetContainer.h.
typedef std::map<TrkrDefs::hitsetkey, TrkrHitSet *> TrkrHitSetContainer::Map
Definition at line 20 of file TrkrHitSetContainer.h.
typedef std::pair<Iterator, Iterator> TrkrHitSetContainer::Range
Definition at line 23 of file TrkrHitSetContainer.h.
Constructor & Destructor Documentation
TrkrHitSetContainer::TrkrHitSetContainer ()
ctor
Definition at line 14 of file TrkrHitSetContainer.cc.
TrkrHitSetContainer::~TrkrHitSetContainer () virtual
dtor
Definition at line 18 of file TrkrHitSetContainer.cc.
References Reset().
Member Function Documentation
TrkrHitSetContainer::ConstIterator TrkrHitSetContainer::addHitSet (TrkrHitSet * newHit)
Add a TrkrHitSet to the container.
Definition at line 47 of file TrkrHitSetContainer.cc.
References addHitSetSpecifyKey(), and TrkrHitSet::getHitSetKey().
TrkrHitSetContainer::ConstIterator TrkrHitSetContainer::addHitSetSpecifyKey (const TrkrDefs::hitsetkey key, TrkrHitSet * newHit)
Definition at line 53 of file TrkrHitSetContainer.cc.
References m_hitmap.
Referenced by addHitSet().
TrkrHitSet * TrkrHitSetContainer::findHitSet (TrkrDefs::hitsetkey key)
return a given HitSet based on its key
Definition at line 128 of file TrkrHitSetContainer.cc.
References it, and m_hitmap.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells().
TrkrHitSetContainer::Iterator TrkrHitSetContainer::findOrAddHitSet (TrkrDefs::hitsetkey key)
find or add HitSet
Definition at line 113 of file TrkrHitSetContainer.cc.
References it, and m_hitmap.
Referenced by PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4MvtxHitReco::process_event(), PHG4InttHitReco::process_event(), and PHG4TpcElectronDrift::process_event().
TrkrHitSetContainer::ConstRange TrkrHitSetContainer::getHitSets (const TrkrDefs::TrkrId trackerid) const
return all HitSets matching a given detid
Definition at line 68 of file TrkrHitSetContainer.cc.
References TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and m_hitmap.
Referenced by SvtxHitEval::all_hits_from(), SvtxHitEval::all_truth_hits(), InttClusterizer::ClusterLadderCells(), MvtxClusterizer::ClusterMvtx(), PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4InttDigitizer::DigitizeLadderCells(), PHG4MvtxDigitizer::DigitizeMvtxLadderCells(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), SvtxEvaluator::printOutputInfo(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), PHG4TpcElectronDrift::process_event(), TPCMLDataInterface::process_event(), AnaMvtxTestBeam2019::process_event(), and DumpTrkrHitSetContainer::process_Node().
TrkrHitSetContainer::ConstRange TrkrHitSetContainer::getHitSets (const TrkrDefs::TrkrId trackerid, const char layer) const
return all HitSets matching a given detid, layer
Definition at line 86 of file TrkrHitSetContainer.cc.
References TrkrDefs::getHitSetKeyHi(), TrkrDefs::getHitSetKeyLo(), and m_hitmap.
TrkrHitSetContainer::ConstRange TrkrHitSetContainer::getHitSets (void) const
return all HitSets
Definition at line 107 of file TrkrHitSetContainer.cc.
References m_hitmap.
void TrkrHitSetContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 33 of file TrkrHitSetContainer.cc.
References TrkrDefs::getLayer(), m_hitmap, and size().
Referenced by PHG4InttHitReco::process_event().
void TrkrHitSetContainer::removeHitSet (TrkrDefs::hitsetkey key) inline
preferred removal method, key is currently the hit id
Definition at line 40 of file TrkrHitSetContainer.h.
References m_hitmap.
void TrkrHitSetContainer::removeHitSet (TrkrHitSet * hit) inline
inefficent, use key where possible instead
Definition at line 46 of file TrkrHitSetContainer.h.
References m_hitmap.
void TrkrHitSetContainer::Reset () virtual
PHObject functions.
Reimplemented from PHObject.
Definition at line 23 of file TrkrHitSetContainer.cc.
References m_hitmap.
Referenced by PHG4TpcElectronDrift::process_event(), and ~TrkrHitSetContainer().
unsigned int TrkrHitSetContainer::size (void) const inline
Definition at line 78 of file TrkrHitSetContainer.h.
References m_hitmap.
Referenced by identify(), AnaMvtxTestBeam2019::process_event(), and DumpTrkrHitSetContainer::process_Node().
Member Data Documentation
Map TrkrHitSetContainer::m_hitmap protected
Definition at line 84 of file TrkrHitSetContainer.h.
Referenced by addHitSetSpecifyKey(), findHitSet(), findOrAddHitSet(), getHitSets(), identify(), removeHitSet(), Reset(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainer.h
coresoftware/blob/master/offline/packages/trackbase/TrkrHitSetContainer.cc