Analysis Software: SvtxVertexMap_v1 Class Reference
SvtxVertexMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap_v1.h>
Public Member Functions
SvtxVertexMap_v1 ()
SvtxVertexMap_v1 (const SvtxVertexMap_v1 &vertexmap)
SvtxVertexMap_v1 & operator= (const SvtxVertexMap_v1 &vertexmap)
virtual ~SvtxVertexMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const SvtxVertex * get (unsigned int idkey) const
SvtxVertex * get (unsigned int idkey)
SvtxVertex * insert (SvtxVertex *vertex)
Add vertex to container. Note the container takes ownership.
SvtxVertex * insert_clone (const SvtxVertex *vertex)
legacy interface. Add vertex to container. Note the container does not take ownership
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SvtxVertexMap
virtual ~SvtxVertexMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (SvtxVertexMap_v1, 1)
Private Attributes
std::map< unsigned int,
SvtxVertex * > _map
Additional Inherited Members
Public Types inherited from SvtxVertexMap
typedef std::map< unsigned int,
SvtxVertex * > VertexMap
typedef std::map< unsigned int,
SvtxVertex * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxVertex * >::iterator Iter
Protected Member Functions inherited from SvtxVertexMap
SvtxVertexMap ()
Detailed Description
Definition at line 13 of file SvtxVertexMap_v1.h.
Constructor & Destructor Documentation
SvtxVertexMap_v1::SvtxVertexMap_v1 ()
Definition at line 12 of file SvtxVertexMap_v1.cc.
Referenced by CloneMe().
SvtxVertexMap_v1::SvtxVertexMap_v1 (const SvtxVertexMap_v1 & vertexmap)
Definition at line 17 of file SvtxVertexMap_v1.cc.
References _map, begin(), end(), and SvtxVertex::get_id().
SvtxVertexMap_v1::~SvtxVertexMap_v1 () virtual
Definition at line 42 of file SvtxVertexMap_v1.cc.
References Reset().
Member Function Documentation
ConstIter SvtxVertexMap_v1::begin () const inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 44 of file SvtxVertexMap_v1.h.
References _map.
Referenced by operator=(), and SvtxVertexMap_v1().
Iter SvtxVertexMap_v1::begin () inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 48 of file SvtxVertexMap_v1.h.
References _map.
SvtxVertexMap_v1::ClassDef (SvtxVertexMap_v1 , 1) private
void SvtxVertexMap_v1::clear () inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 29 of file SvtxVertexMap_v1.h.
References Reset().
PHObject* SvtxVertexMap_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxVertexMap.
Definition at line 24 of file SvtxVertexMap_v1.h.
References SvtxVertexMap_v1().
size_t SvtxVertexMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 28 of file SvtxVertexMap_v1.h.
References _map.
bool SvtxVertexMap_v1::empty () const inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 26 of file SvtxVertexMap_v1.h.
References _map.
ConstIter SvtxVertexMap_v1::end () const inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 46 of file SvtxVertexMap_v1.h.
References _map.
Referenced by operator=(), and SvtxVertexMap_v1().
Iter SvtxVertexMap_v1::end () inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 50 of file SvtxVertexMap_v1.h.
References _map.
size_t SvtxVertexMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 38 of file SvtxVertexMap_v1.h.
References _map.
ConstIter SvtxVertexMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 45 of file SvtxVertexMap_v1.h.
References _map.
Iter SvtxVertexMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 49 of file SvtxVertexMap_v1.h.
References _map.
const SvtxVertex * SvtxVertexMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SvtxVertexMap.
Definition at line 65 of file SvtxVertexMap_v1.cc.
References _map.
SvtxVertex * SvtxVertexMap_v1::get (unsigned int idkey) virtual
Reimplemented from SvtxVertexMap.
Definition at line 72 of file SvtxVertexMap_v1.cc.
References _map.
void SvtxVertexMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxVertexMap.
Definition at line 59 of file SvtxVertexMap_v1.cc.
References _map.
SvtxVertex * SvtxVertexMap_v1::insert (SvtxVertex * vertex) virtual
Add vertex to container. Note the container takes ownership.
Reimplemented from SvtxVertexMap.
Definition at line 79 of file SvtxVertexMap_v1.cc.
References _map, and index.
Referenced by insert_clone().
SvtxVertex * SvtxVertexMap_v1::insert_clone (const SvtxVertex * vertex) virtual
legacy interface. Add vertex to container. Note the container does not take ownership
Reimplemented from SvtxVertexMap.
Definition at line 88 of file SvtxVertexMap_v1.cc.
References SvtxVertex::CloneMe(), and insert().
int SvtxVertexMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxVertexMap.
Definition at line 23 of file SvtxVertexMap_v1.h.
SvtxVertexMap_v1 & SvtxVertexMap_v1::operator= (const SvtxVertexMap_v1 & vertexmap)
Definition at line 29 of file SvtxVertexMap_v1.cc.
References _map, begin(), end(), SvtxVertex::get_id(), and Reset().
void SvtxVertexMap_v1::Reset () virtual
Clear Event.
Reimplemented from SvtxVertexMap.
Definition at line 47 of file SvtxVertexMap_v1.cc.
References _map.
Referenced by clear(), operator=(), and ~SvtxVertexMap_v1().
size_t SvtxVertexMap_v1::size (void) const inline virtual
Reimplemented from SvtxVertexMap.
Definition at line 27 of file SvtxVertexMap_v1.h.
References _map.
Member Data Documentation
std::map<unsigned int, SvtxVertex*> SvtxVertexMap_v1::_map private
Definition at line 53 of file SvtxVertexMap_v1.h.
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and SvtxVertexMap_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxVertexMap_v1.cc