Analysis Software: EmcCluster Class Reference
EmcCluster Class Reference
#include <coresoftware/blob/master/offline/packages/CaloReco/BEmcCluster.h>
Public Member Functions
EmcCluster ()
Constructor (zero Hit List)
EmcCluster (BEmcRec *sector)
EmcCluster (const std::vector< EmcModule > &hlist, BEmcRec *sector)
Constructor (inputs Hit List)
virtual ~EmcCluster ()
void ReInitialize (const std::vector< EmcModule > &hlist)
Reinitializes EmcCluster supplying new Hit List.
int GetNofHits ()
Returns number of EmcModules in EmcCluster.
void GetHits (EmcModule *phit, int n)
Returns n EmcModules (sorted) with the maximum energy.
std::vector< EmcModule > GetHitList ()
Returns EmcCluster fHitList.
EmcModule GetMaxTower ()
Returns the EmcModule with the maximum energy.
EmcModule GetImpactTower ()
Returns the EmcModule corresponding to the reconstructed impact tower.
float GetTowerEnergy (int ich)
Returns the energy of the ich-tower (numbering from 0)
float GetTowerEnergy (int ix, int iy)
Returns the energy of the tower ix,iy (numbering from 0)
float GetTowerToF (int ich)
Returns the ToF of the ich-tower (numbering from 0)
int GetTowerDeadMap (int ich)
Returns the Dead Map of the ich-tower (numbering from 0)
int GetTowerWarnMap (int ich)
Returns the Warning Map of the ich-tower (numbering from 0)
float GetTowerADC (int ich)
float GetTowerTAC (int ich)
int GetNDead ()
Returns the number of dead channels around MaxTower.
int GetDeadMap ()
int GetWarnMap ()
float GetE4 ()
Returns the energy in 2x2 towers around the cluster Center of Gravity.
float GetE9 ()
Returns the energy in 3x3 towers around the cluster Center of Gravity.
float GetE9 (int ich)
Returns the energy in 3x3 towers around the tower ich.
float GetECore ()
Returns the cluster energy taking into account towers with E>Ethresh.
float GetECoreCorrected ()
Ecore corrected for energy leak sidewise core towers.
float GetTotalEnergy ()
Returns the EmcCluster total energy.
void GetMoments (float *pxcg, float *pycg, float *pxx, float *pxy, float *pyy)
Returns EmcCluster 1-st (pxcg,pycg) and 2-d momenta (pxx,pxy,pyy)
void GetCorrPos (float *pxc, float *pyc)
Returns the EmcCluster corrected position in Sector (SM) frame.
void GetGlobalPos (float &xg, float &yg, float &zg)
Returns the EmcCluster position in PHENIX global coord system.
void GetErrors (float *pde, float *pdx, float *pdy, float *pdz)
Returns the errors for the reconstructed energy and position.
void GetChar (float *pe, float *pxcg, float *pysg, float *pxc, float *pyc, float *pxg, float *pyg, float *pzg, float *pxx, float *pxy, float *pyy, float *pde, float *pdx, float *pdy, float *pdz)
Substitutes a number of functions above (to save CPU time)
int GetPeaks (std::vector< EmcPeakarea > *PkList, std::vector< EmcModule > *ppeaks)
Splits the EmcCluster onto peakarea's; also returns peak tower array corresponding to peakarea array.
float GetProb (float &chi2, int &ndf)
Static Public Member Functions
static int max (int a, int b)
static float max (float a, float b)
static double max (double a, double b)
static int min (int a, int b)
static float min (float a, float b)
static double min (double a, double b)
static int ABS (int x)
static float ABS (float x)
static double ABS (double x)
static int lowint (float x)
Protected Attributes
std::vector< EmcModule > fHitList
BEmcRec * fOwner
Static Protected Attributes
static int const fgMaxNofPeaks = 1000
static int const fgPeakIter = 6
static float const fgEmin = 0.002
static float const fgChisq = 3.
static float const fgXABSURD = -999999.
static float const fgYABSURD = -999999.
Detailed Description
The 1-st level of the EMCal clustering: cluster is a set of contiguous towers.
Only used internally by clustering routines.
Definition at line 54 of file BEmcCluster.h.
Constructor & Destructor Documentation
EmcCluster::EmcCluster () inline
Constructor (zero Hit List)
Definition at line 58 of file BEmcCluster.h.
EmcCluster::EmcCluster (BEmcRec * sector) inline
Definition at line 62 of file BEmcCluster.h.
EmcCluster::EmcCluster (const std::vector< EmcModule > & hlist, BEmcRec * sector) inline
Constructor (inputs Hit List)
Definition at line 69 of file BEmcCluster.h.
virtual EmcCluster::~EmcCluster () inline virtual
Definition at line 76 of file BEmcCluster.h.
Member Function Documentation
static int EmcCluster::ABS (int x) inline static
Definition at line 193 of file BEmcCluster.h.
Referenced by BEmcRecCEMC::CorrectPosition(), BEmcRecEEMC::CorrectPosition(), BEmcRecFEMC::CorrectPosition(), BEmcRec::Gamma(), EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), GetPeaks(), BEmcRec::PredictEnergy(), and BEmcRec::TwoGamma().
static float EmcCluster::ABS (float x) inline static
Definition at line 197 of file BEmcCluster.h.
static double EmcCluster::ABS (double x) inline static
Definition at line 201 of file BEmcCluster.h.
void EmcCluster::GetChar (float * pe, float * pxcg, float * pysg, float * pxc, float * pyc, float * pxg, float * pyg, float * pzg, float * pxx, float * pxy, float * pyy, float * pde, float * pdx, float * pdy, float * pdz)
Substitutes a number of functions above (to save CPU time)
Definition at line 532 of file BEmcCluster.cc.
References BEmcRec::CalculateErrors(), BEmcRec::CorrectPosition(), fOwner, GetMoments(), GetTotalEnergy(), and BEmcRec::SectorToGlobal().
void EmcCluster::GetCorrPos (float * pxc, float * pyc)
Returns the EmcCluster corrected position in Sector (SM) frame.
Definition at line 62 of file BEmcCluster.cc.
References BEmcRec::CorrectPosition(), fOwner, GetMoments(), GetTotalEnergy(), x, and y.
Referenced by GetErrors(), GetGlobalPos(), and GetImpactTower().
int EmcCluster::GetDeadMap ()
Definition at line 225 of file BEmcCluster.cc.
References EmcModule::deadmap, and GetMaxTower().
float EmcCluster::GetE4 ()
Returns the energy in 2x2 towers around the cluster Center of Gravity.
Definition at line 307 of file BEmcCluster.cc.
References fOwner, BEmcRec::GetModSizex(), BEmcRec::GetModSizey(), GetMoments(), and GetTowerEnergy().
float EmcCluster::GetE9 ()
Returns the energy in 3x3 towers around the cluster Center of Gravity.
Definition at line 334 of file BEmcCluster.cc.
References fHitList, fOwner, GetMoments(), and BEmcRec::GetNx().
float EmcCluster::GetE9 (int ich)
Returns the energy in 3x3 towers around the tower ich.
Definition at line 356 of file BEmcCluster.cc.
References fHitList, fOwner, BEmcRec::GetNx(), and BEmcRec::iTowerDist().
float EmcCluster::GetECore ()
Returns the cluster energy taking into account towers with E>Ethresh.
Definition at line 274 of file BEmcCluster.cc.
References dx, dy, energy, fHitList, fOwner, BEmcRec::fTowerDist(), GetMoments(), BEmcRec::GetNx(), GetTotalEnergy(), BEmcRec::PredictEnergy(), and BEmcRec::SetProfileParameters().
Referenced by EmcPeakarea::GetChar(), and GetECoreCorrected().
float EmcCluster::GetECoreCorrected ()
Ecore corrected for energy leak sidewise core towers.
Definition at line 262 of file BEmcCluster.cc.
References BEmcRec::CorrectECore(), fOwner, GetECore(), GetMoments(), x, and y.
void EmcCluster::GetErrors (float * pde, float * pdx, float * pdy, float * pdz)
Returns the errors for the reconstructed energy and position.
Definition at line 514 of file BEmcCluster.cc.
References BEmcRec::CalculateErrors(), fOwner, GetCorrPos(), GetTotalEnergy(), x, and y.
void EmcCluster::GetGlobalPos (float & xg, float & yg, float & zg)
Returns the EmcCluster position in PHENIX global coord system.
Definition at line 76 of file BEmcCluster.cc.
References fOwner, GetCorrPos(), GetTotalEnergy(), and BEmcRec::Tower2Global().
std::vector<EmcModule> EmcCluster::GetHitList () inline
Returns EmcCluster fHitList.
Definition at line 95 of file BEmcCluster.h.
References fHitList.
void EmcCluster::GetHits (EmcModule * phit, int n)
Returns n EmcModules (sorted) with the maximum energy.
Definition at line 444 of file BEmcCluster.cc.
References fHitList, fOwner, BEmcRec::HitACompare(), i, min(), and BEmcRec::ZeroVector().
EmcModule EmcCluster::GetImpactTower ()
Returns the EmcModule corresponding to the reconstructed impact tower.
!!!! memset(&ht, 0, sizeof(EmcModule)); // MV 2002/03/12 bugfix
Definition at line 382 of file BEmcCluster.cc.
References EmcModule::adc, EmcModule::amp, EmcModule::deadmap, fOwner, GetCorrPos(), BEmcRec::GetModSizex(), BEmcRec::GetModSizey(), BEmcRec::GetNx(), BEmcRec::GetNy(), GetTowerADC(), GetTowerDeadMap(), GetTowerEnergy(), GetTowerTAC(), GetTowerToF(), GetTowerWarnMap(), EmcModule::ich, lowint(), printf(), EmcModule::tac, EmcModule::tof, EmcModule::warnmap, x, and y.
EmcModule EmcCluster::GetMaxTower ()
Returns the EmcModule with the maximum energy.
!!!! memset(&ht, 0, sizeof(EmcModule)); // MV 2002/03/12 bugfix
Definition at line 416 of file BEmcCluster.cc.
References EmcModule::amp, fHitList, EmcModule::ich, and EmcModule::tof.
Referenced by GetDeadMap(), GetNDead(), GetPeaks(), and GetWarnMap().
void EmcCluster::GetMoments (float * pxcg, float * pycg, float * pxx, float * pxy, float * pyy)
Returns EmcCluster 1-st (pxcg,pycg) and 2-d momenta (pxx,pxy,pyy)
Definition at line 469 of file BEmcCluster.cc.
References EmcModule::amp, fgXABSURD, fgYABSURD, fHitList, fOwner, EmcModule::ich, BEmcRec::Momenta(), x, and y.
Referenced by GetChar(), EmcPeakarea::GetChar(), EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), GetCorrPos(), GetE4(), GetE9(), GetECore(), and GetECoreCorrected().
int EmcCluster::GetNDead ()
Returns the number of dead channels around MaxTower.
Definition at line 204 of file BEmcCluster.cc.
References EmcModule::deadmap, and GetMaxTower().
int EmcCluster::GetNofHits () inline
Returns number of EmcModules in EmcCluster.
Definition at line 87 of file BEmcCluster.h.
References fHitList.
int EmcCluster::GetPeaks (std::vector< EmcPeakarea > * PkList, std::vector< EmcModule > * ppeaks)
Splits the EmcCluster onto peakarea's; also returns peak tower array corresponding to peakarea array.
Definition at line 551 of file BEmcCluster.cc.
References ABS(), EmcModule::adc, EmcModule::amp, EmcModule::deadmap, dx, dy, fgEmin, fgMaxNofPeaks, fgPeakIter, fHitList, fOwner, BEmcRec::fTowerDist(), GetMaxTower(), BEmcRec::GetNx(), BEmcRec::GetPeakThreshold(), BEmcRec::HitNCompare(), i, EmcModule::ich, in, BEmcRec::iTowerDist(), BEmcRec::PredictEnergy(), printf(), ratio, ReInitialize(), BEmcRec::SetProfileParameters(), EmcModule::tac, EmcModule::tof, EmcModule::warnmap, and BEmcRec::ZeroVector().
float EmcCluster::GetProb (float & chi2, int & ndf)
Definition at line 525 of file BEmcCluster.cc.
References fHitList, fOwner, and BEmcRec::GetProb().
float EmcCluster::GetTotalEnergy ()
Returns the EmcCluster total energy.
Definition at line 245 of file BEmcCluster.cc.
References fHitList.
Referenced by GetChar(), EmcPeakarea::GetChar(), EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), GetCorrPos(), GetECore(), GetErrors(), and GetGlobalPos().
float EmcCluster::GetTowerADC (int ich)
Definition at line 170 of file BEmcCluster.cc.
References fHitList.
Referenced by GetImpactTower().
int EmcCluster::GetTowerDeadMap (int ich)
Returns the Dead Map of the ich-tower (numbering from 0)
Definition at line 138 of file BEmcCluster.cc.
References fHitList.
Referenced by GetImpactTower().
float EmcCluster::GetTowerEnergy (int ich)
Returns the energy of the ich-tower (numbering from 0)
Definition at line 87 of file BEmcCluster.cc.
References fHitList.
Referenced by EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), GetE4(), and GetImpactTower().
float EmcCluster::GetTowerEnergy (int ix, int iy)
Returns the energy of the tower ix,iy (numbering from 0)
Definition at line 103 of file BEmcCluster.cc.
References fHitList, fOwner, and BEmcRec::GetNx().
float EmcCluster::GetTowerTAC (int ich)
Definition at line 186 of file BEmcCluster.cc.
References fHitList.
Referenced by GetImpactTower().
float EmcCluster::GetTowerToF (int ich)
Returns the ToF of the ich-tower (numbering from 0)
Definition at line 122 of file BEmcCluster.cc.
References fHitList.
Referenced by GetImpactTower().
int EmcCluster::GetTowerWarnMap (int ich)
Returns the Warning Map of the ich-tower (numbering from 0)
Definition at line 154 of file BEmcCluster.cc.
References fHitList.
Referenced by GetImpactTower().
int EmcCluster::GetWarnMap ()
Definition at line 235 of file BEmcCluster.cc.
References GetMaxTower(), and EmcModule::warnmap.
static int EmcCluster::lowint (float x) inline static
Definition at line 206 of file BEmcCluster.h.
Referenced by BEmcRecCEMC::CorrectPosition(), BEmcRecFEMC::CorrectPosition(), BEmcRecEEMC::CorrectPosition(), and GetImpactTower().
static int EmcCluster::max (int a, int b) inline static
Definition at line 167 of file BEmcCluster.h.
Referenced by BEmcRec::SetTowerThreshold().
static float EmcCluster::max (float a, float b) inline static
Definition at line 171 of file BEmcCluster.h.
static double EmcCluster::max (double a, double b) inline static
Definition at line 175 of file BEmcCluster.h.
static int EmcCluster::min (int a, int b) inline static
Definition at line 180 of file BEmcCluster.h.
Referenced by BEmcRec::Chi2Limit(), and GetHits().
static float EmcCluster::min (float a, float b) inline static
Definition at line 184 of file BEmcCluster.h.
static double EmcCluster::min (double a, double b) inline static
Definition at line 188 of file BEmcCluster.h.
void EmcCluster::ReInitialize (const std::vector< EmcModule > & hlist) inline
Reinitializes EmcCluster supplying new Hit List.
Definition at line 82 of file BEmcCluster.h.
References fHitList.
Referenced by BEmcRec::FindClusters(), and GetPeaks().
Member Data Documentation
float const EmcCluster::fgChisq = 3. static protected
Definition at line 160 of file BEmcCluster.h.
Referenced by EmcPeakarea::GetCGmin(), EmcPeakarea::GetChar(), and EmcPeakarea::GetChi2().
float const EmcCluster::fgEmin = 0.002 static protected
Definition at line 159 of file BEmcCluster.h.
Referenced by GetPeaks().
int const EmcCluster::fgMaxNofPeaks = 1000 static protected
Definition at line 157 of file BEmcCluster.h.
Referenced by GetPeaks().
int const EmcCluster::fgPeakIter = 6 static protected
Definition at line 158 of file BEmcCluster.h.
Referenced by GetPeaks().
float const EmcCluster::fgXABSURD = -999999. static protected
Definition at line 161 of file BEmcCluster.h.
Referenced by EmcPeakarea::GetCGmin(), and GetMoments().
float const EmcCluster::fgYABSURD = -999999. static protected
Definition at line 162 of file BEmcCluster.h.
Referenced by EmcPeakarea::GetCGmin(), and GetMoments().
std::vector<EmcModule> EmcCluster::fHitList protected
Definition at line 152 of file BEmcCluster.h.
Referenced by EmcPeakarea::GetCGmin(), EmcPeakarea::GetChar(), EmcPeakarea::GetChi2(), GetE9(), GetECore(), GetHitList(), GetHits(), GetMaxTower(), GetMoments(), GetNofHits(), GetPeaks(), GetProb(), GetTotalEnergy(), GetTowerADC(), GetTowerDeadMap(), GetTowerEnergy(), GetTowerTAC(), GetTowerToF(), GetTowerWarnMap(), and ReInitialize().
BEmcRec* EmcCluster::fOwner protected
Definition at line 154 of file BEmcCluster.h.
Referenced by EmcPeakarea::GetCGmin(), GetChar(), EmcPeakarea::GetChar(), EmcPeakarea::GetChi2(), EmcPeakarea::GetChi2New(), EmcPeakarea::GetCLNew(), GetCorrPos(), GetE4(), GetE9(), GetECore(), GetECoreCorrected(), GetErrors(), GetGlobalPos(), GetHits(), GetImpactTower(), GetMoments(), GetPeaks(), GetProb(), and GetTowerEnergy().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloReco/BEmcCluster.h
coresoftware/blob/master/offline/packages/CaloReco/BEmcCluster.cc