Analysis Software: FROG Class Reference
FROG Class Reference
#include <coresoftware/blob/master/offline/framework/frog/FROG.h>
Public Member Functions
FROG ()
virtual ~FROG ()
const char * location (const std::string &logical_name)
bool localSearch (const std::string &lname)
bool dCacheSearch (const std::string &lname)
bool PGSearch (const std::string &lname)
void Verbosity (const int i)
int Verbosity () const
Private Member Functions
bool GetConnection ()
void Disconnect ()
Private Attributes
std::string pfn
int m_Verbosity
odbc::Connection * m_OdbcConnection
Detailed Description
Definition at line 12 of file FROG.h.
Constructor & Destructor Documentation
FROG::FROG ()
Definition at line 22 of file FROG.cc.
virtual FROG::~FROG () inline virtual
Definition at line 16 of file FROG.h.
Member Function Documentation
bool FROG::dCacheSearch (const std::string & lname)
Definition at line 181 of file FROG.cc.
References GetConnection(), m_OdbcConnection, pfn, and Verbosity().
Referenced by location().
void FROG::Disconnect () private
Definition at line 153 of file FROG.cc.
References m_OdbcConnection.
Referenced by location().
bool FROG::GetConnection () private
Definition at line 127 of file FROG.cc.
References m_OdbcConnection, and PHWHERE.
Referenced by dCacheSearch(), and PGSearch().
bool FROG::localSearch (const std::string & lname)
Definition at line 117 of file FROG.cc.
References pfn.
Referenced by location().
const char * FROG::location (const std::string & logical_name)
Definition at line 29 of file FROG.cc.
References dCacheSearch(), Disconnect(), localSearch(), pfn, PGSearch(), and Verbosity().
Referenced by Fun4AllDstInputManager::fileopen(), Fun4AllPrdfInputManager::fileopen(), Fun4AllOscarInputManager::fileopen(), Fun4AllHepMCInputManager::fileopen(), and pfileopen().
bool FROG::PGSearch (const std::string & lname)
Definition at line 159 of file FROG.cc.
References GetConnection(), m_OdbcConnection, and pfn.
Referenced by location().
void FROG::Verbosity (const int i) inline
Definition at line 22 of file FROG.h.
References i, and m_Verbosity.
int FROG::Verbosity () const inline
Definition at line 23 of file FROG.h.
References m_Verbosity.
Referenced by dCacheSearch(), and location().
Member Data Documentation
odbc::Connection* FROG::m_OdbcConnection private
Definition at line 30 of file FROG.h.
Referenced by dCacheSearch(), Disconnect(), GetConnection(), and PGSearch().
int FROG::m_Verbosity private
Definition at line 29 of file FROG.h.
Referenced by Verbosity().
std::string FROG::pfn private
Definition at line 28 of file FROG.h.
Referenced by dCacheSearch(), localSearch(), location(), and PGSearch().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/frog/FROG.h
coresoftware/blob/master/offline/framework/frog/FROG.cc