Analysis Software: analysis/blob/master/EMCal-analysis/macro/DrawEcal_pDST.C File Reference
DrawEcal_pDST.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawEcal_pDST (const TString infile="../../sPHENIX_work/production_analysis_cemc2x2//emcstudies/pidstudies/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-ALL.root_Ana.root.lst_EMCalLikelihood.root")
void MakeRadiusCut (TString infile, const double R_CEMC, const double R_HCALIN, TCut good_track_cut)
void Edep_Checks (TString infile, const double R_CEMC, const double R_HCALIN, TCut good_track_cut)
void TrackProjection_Checks (TString infile, TCut good_track_cut)
void UpsilonPair_Checks (TString infile)
TGraphErrors * Distribution2Efficiency (TH1F *hCEMC3_Max)
void TrackProjection_Checks_Comparison ()
void Logs ()
Variables
TFile * _file0 = NULL
TTree * T = NULL
TString cuts = ""
Function Documentation
TGraphErrors* Distribution2Efficiency (TH1F * hCEMC3_Max)
Definition at line 630 of file DrawEcal_pDST.C.
References A, assert, i, n, and z.
void DrawEcal_pDST (const TString infile = "../../sPHENIX_work/production_analysis_cemc2x2//emcstudies/pidstudies/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-ALL.root_Ana.root.lst_EMCalLikelihood.root")
Definition at line 26 of file DrawEcal_pDST.C.
References _file0, assert, cuts, Edep_Checks(), event_sel, n, SetOKStyle(), T, t, and TrackProjection_Checks().
void Edep_Checks (TString infile, const double R_CEMC, const double R_HCALIN, TCut good_track_cut)
Definition at line 342 of file DrawEcal_pDST.C.
References _file0, cuts, MakeRadiusCut(), SaveCanvas(), and T.
void Logs ()
Definition at line 736 of file DrawEcal_pDST.C.
void MakeRadiusCut (TString infile, const double R_CEMC, const double R_HCALIN, TCut good_track_cut)
Definition at line 158 of file DrawEcal_pDST.C.
References _file0, assert, cuts, Distribution2Efficiency(), SaveCanvas(), and T.
Referenced by Edep_Checks().
void TrackProjection_Checks (TString infile, TCut good_track_cut)
Definition at line 428 of file DrawEcal_pDST.C.
References _file0, cuts, SaveCanvas(), and T.
Referenced by DrawEcal_pDST().
void TrackProjection_Checks_Comparison ()
Definition at line 669 of file DrawEcal_pDST.C.
References assert, Draw(), SaveCanvas(), SetOKStyle(), and text().
void UpsilonPair_Checks (TString infile)
Definition at line 587 of file DrawEcal_pDST.C.
References _file0, cuts, SaveCanvas(), and T.
Variable Documentation
TFile* _file0 = NULL
Definition at line 21 of file DrawEcal_pDST.C.
TString cuts = ""
Definition at line 23 of file DrawEcal_pDST.C.
TTree* T = NULL
Definition at line 22 of file DrawEcal_pDST.C.