Analysis Software: analysis/blob/master/Prototype3/EMCal/macros/DrawPrototype3ShowerCalib_Sum.C File Reference
DrawPrototype3ShowerCalib_Sum.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <TLatex.h>
#include <TGraphErrors.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Classes
class lin_res
Functions
void DrawPrototype3ShowerCalib_Sum ()
double GetMu2Pi (const double E)
void RejectionCompare (const double E=4)
TGraphErrors * GetSimRejCurve (const TString physics_lst, const TString energy, const TString particle)
void LineShapeCompare (const double E=4, const TString physics_lst="QGSP_BERT_HP")
void LineShapeCompare_Electron (const double E=4, const TString physics_lst="QGSP_BERT_HP")
TGraphErrors * FitProfile (const TH2 *h2)
TGraphErrors * Distribution2Efficiency (TH1F *hCEMC3_Max)
TGraphErrors * GetTGraphRatio (TGraphErrors *input, TGraphErrors *baseline)
Variables
TCut event_sel
TString cuts
TFile * _file0 = NULL
TTree * T = NULL
Function Documentation
TGraphErrors* Distribution2Efficiency (TH1F * hCEMC3_Max)
Definition at line 515 of file DrawPrototype3ShowerCalib_Sum.C.
References A, assert, i, n, and z.
void DrawPrototype3ShowerCalib_Sum ()
Definition at line 40 of file DrawPrototype3ShowerCalib_Sum.C.
References RejectionCompare(), and SetOKStyle().
TGraphErrors* FitProfile (const TH2 * h2)
Definition at line 452 of file DrawPrototype3ShowerCalib_Sum.C.
References f2(), h1, i, n, x, and y.
double GetMu2Pi (const double E)
Definition at line 76 of file DrawPrototype3ShowerCalib_Sum.C.
References assert.
TGraphErrors* GetSimRejCurve (const TString physics_lst, const TString energy, const TString particle)
Definition at line 274 of file DrawPrototype3ShowerCalib_Sum.C.
References assert, Distribution2Efficiency(), and filename.
TGraphErrors* GetTGraphRatio (TGraphErrors * input, TGraphErrors * baseline)
Definition at line 554 of file DrawPrototype3ShowerCalib_Sum.C.
References assert, and i.
void LineShapeCompare (const double E = 4, const TString physics_lst = "QGSP_BERT_HP")
Definition at line 295 of file DrawPrototype3ShowerCalib_Sum.C.
References assert, E, energy, GetMu2Pi(), SaveCanvas(), and t.
void LineShapeCompare_Electron (const double E = 4, const TString physics_lst = "QGSP_BERT_HP")
Definition at line 394 of file DrawPrototype3ShowerCalib_Sum.C.
References assert, E, energy, SaveCanvas(), and t.
void RejectionCompare (const double E = 4)
Definition at line 103 of file DrawPrototype3ShowerCalib_Sum.C.
References assert, Distribution2Efficiency(), E, energy, GetMu2Pi(), GetSimRejCurve(), GetTGraphRatio(), i, leg, SaveCanvas(), and t.
Variable Documentation
TFile* _file0 = NULL
Definition at line 27 of file DrawPrototype3ShowerCalib_Sum.C.
TString cuts
Definition at line 26 of file DrawPrototype3ShowerCalib_Sum.C.
TCut event_sel
Definition at line 25 of file DrawPrototype3ShowerCalib_Sum.C.
TTree* T = NULL
Definition at line 28 of file DrawPrototype3ShowerCalib_Sum.C.