Analysis Software: TrkrEvaluator Class Reference
TrkrEvaluator Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4eval/TrkrEvaluator.h>
Public Member Functions
TrkrEvaluator (const std::string &name="TRKREVALUATOR", const std::string &filename="g4eval.root", const std::string &trackmapname="SvtxTrackMap", unsigned int nlayers_maps=3, unsigned int nlayers_intt=4, unsigned int nlayers_tpc=48)
virtual ~TrkrEvaluator ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void scan_for_embedded (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
float line_circle_intersection (float x[], float y[], float z[], float radius)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
unsigned int _ievent
bool _do_vertex_eval
bool _do_cluster_eval
bool _do_gtrack_eval
bool _do_track_eval
bool _do_track_match
bool _scan_for_embedded
unsigned int _nlayers_maps
unsigned int _nlayers_intt
unsigned int _nlayers_tpc
TNtuple * _ntp_vertex
TNtuple * _ntp_cluster
TNtuple * _ntp_gtrack
TNtuple * _ntp_track
std::string _filename
std::string _trackmapname
TFile * _tfile
PHTimer * _timer
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 14 of file TrkrEvaluator.h.
Constructor & Destructor Documentation
TrkrEvaluator::TrkrEvaluator (const std::string & name = "TRKREVALUATOR", const std::string & filename = "g4eval.root", const std::string & trackmapname = "SvtxTrackMap", unsigned int nlayers_maps = 3, unsigned int nlayers_intt = 4, unsigned int nlayers_tpc = 48)
Definition at line 50 of file TrkrEvaluator.cc.
virtual TrkrEvaluator::~TrkrEvaluator () inline virtual
Definition at line 23 of file TrkrEvaluator.h.
Member Function Documentation
int TrkrEvaluator::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 159 of file TrkrEvaluator.cc.
References _filename, _ievent, _ntp_cluster, _ntp_gtrack, _ntp_track, _ntp_vertex, _tfile, Fun4AllReturnCodes::EVENT_OK, and Fun4AllBase::Verbosity().
void TrkrEvaluator::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 187 of file TrkrEvaluator.cc.
References _do_track_match, _ievent, _nlayers_intt, _nlayers_maps, _nlayers_tpc, _ntp_cluster, _ntp_gtrack, _ntp_track, _ntp_vertex, _scan_for_embedded, _timer, _trackmapname, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrack::CEMC, SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), PHG4HitContainer::findHit(), SvtxTrackMap::get(), PHTimer::get_accumulated_time(), PHG4Hit::get_avg_t(), PHG4Hit::get_avg_x(), PHG4Hit::get_avg_y(), PHG4Hit::get_avg_z(), SvtxTrack::get_cal_cluster_e(), SvtxTrack::get_cal_deta(), SvtxTrack::get_cal_dphi(), SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_charge(), SvtxTrack::get_chisq(), SvtxTrack::get_dca2d(), SvtxTrack::get_dca2d_error(), SvtxTrack::get_dca3d_xy(), SvtxTrack::get_dca3d_xy_error(), SvtxTrack::get_dca3d_z(), SvtxTrack::get_dca3d_z_error(), PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4VtxPoint::get_id(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), PHG4Particle::get_parent_id(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Hit::get_px(), SvtxTrack::get_px(), PHG4Particle::get_py(), PHG4Hit::get_py(), SvtxTrack::get_py(), PHG4Particle::get_pz(), PHG4Hit::get_pz(), SvtxTrack::get_pz(), SvtxTrack::get_quality(), PHG4CylinderCellGeom::get_radius(), PHG4VtxPoint::get_t(), PHG4CylinderCellGeom::get_thickness(), PHG4Particle::get_track_id(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_x(), PHG4Hit::get_x(), SvtxVertex::get_x(), SvtxTrack::get_x(), PHG4VtxPoint::get_y(), PHG4Hit::get_y(), SvtxVertex::get_y(), SvtxTrack::get_y(), PHG4VtxPoint::get_z(), PHG4Hit::get_z(), SvtxVertex::get_z(), SvtxTrack::get_z(), TrkrCluster::getAdc(), TrkrClusterContainer::getClusters(), TrkrCluster::getError(), TrkrHitTruthAssoc::getG4Hits(), PHG4HitContainer::getHits(), TrkrClusterHitAssoc::getHits(), TrkrDefs::getHitSetKeyFromClusKey(), TrkrHitSetContainer::getHitSets(), TrkrDefs::getLayer(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), TrkrCluster::getPhiError(), TrkrCluster::getPhiSize(), TrkrCluster::getPosition(), TrkrDefs::getTrkrId(), TrkrCluster::getZSize(), gpos, gr, SvtxTrack::HCALIN, SvtxTrack::HCALOUT, i, TrkrDefs::inttId, it, line_circle_intersection(), nparticles, phi, PHWHERE, pos, SvtxTrack::PRES, r, PHTimer::restart(), set(), SvtxTrackMap::size(), SvtxTrack::size_clusters(), SvtxVertex::size_tracks(), PHTimer::stop(), boost::swap(), t, TrkrDefs::tpcId, v, Fun4AllBase::Verbosity(), x, y, and z.
Referenced by process_event().
int TrkrEvaluator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 77 of file TrkrEvaluator.cc.
References _do_cluster_eval, _do_gtrack_eval, _do_track_eval, _do_vertex_eval, _filename, _ievent, _ntp_cluster, _ntp_gtrack, _ntp_track, _ntp_vertex, _scan_for_embedded, _tfile, _timer, Fun4AllReturnCodes::EVENT_OK, PHWHERE, and PHTimer::stop().
int TrkrEvaluator::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 137 of file TrkrEvaluator.cc.
References Fun4AllReturnCodes::EVENT_OK.
float TrkrEvaluator::line_circle_intersection (float x[], float y[], float z[], float radius) private
Definition at line 1829 of file TrkrEvaluator.cc.
References A, C, PHWHERE, and t.
Referenced by fillOutputNtuples().
void TrkrEvaluator::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
void TrkrEvaluator::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
int TrkrEvaluator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 142 of file TrkrEvaluator.cc.
References _ievent, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), and Fun4AllBase::Verbosity().
void TrkrEvaluator::scan_for_embedded (bool b)
Definition at line 182 of file TrkrEvaluator.cc.
References _scan_for_embedded.
Member Data Documentation
bool TrkrEvaluator::_do_cluster_eval private
Definition at line 39 of file TrkrEvaluator.h.
Referenced by Init().
bool TrkrEvaluator::_do_gtrack_eval private
Definition at line 40 of file TrkrEvaluator.h.
Referenced by Init().
bool TrkrEvaluator::_do_track_eval private
Definition at line 41 of file TrkrEvaluator.h.
Referenced by Init().
bool TrkrEvaluator::_do_track_match private
Definition at line 42 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples().
bool TrkrEvaluator::_do_vertex_eval private
Definition at line 38 of file TrkrEvaluator.h.
Referenced by Init().
std::string TrkrEvaluator::_filename private
Definition at line 56 of file TrkrEvaluator.h.
Referenced by End(), and Init().
unsigned int TrkrEvaluator::_ievent private
Definition at line 33 of file TrkrEvaluator.h.
Referenced by End(), fillOutputNtuples(), Init(), and process_event().
unsigned int TrkrEvaluator::_nlayers_intt private
Definition at line 47 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples().
unsigned int TrkrEvaluator::_nlayers_maps private
Definition at line 46 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples().
unsigned int TrkrEvaluator::_nlayers_tpc private
Definition at line 48 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples().
TNtuple* TrkrEvaluator::_ntp_cluster private
Definition at line 51 of file TrkrEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrEvaluator::_ntp_gtrack private
Definition at line 52 of file TrkrEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrEvaluator::_ntp_track private
Definition at line 53 of file TrkrEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* TrkrEvaluator::_ntp_vertex private
Definition at line 50 of file TrkrEvaluator.h.
Referenced by End(), fillOutputNtuples(), and Init().
bool TrkrEvaluator::_scan_for_embedded private
Definition at line 43 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples(), Init(), and scan_for_embedded().
TFile* TrkrEvaluator::_tfile private
Definition at line 59 of file TrkrEvaluator.h.
Referenced by End(), and Init().
PHTimer* TrkrEvaluator::_timer private
Definition at line 61 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples(), and Init().
std::string TrkrEvaluator::_trackmapname private
Definition at line 57 of file TrkrEvaluator.h.
Referenced by fillOutputNtuples().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4eval/TrkrEvaluator.h
coresoftware/blob/master/simulation/g4simulation/g4eval/TrkrEvaluator.cc