Analysis Software: TPCDataStreamEmulator Class Reference
TPCDataStreamEmulator Class Reference
TPCDataStreamEmulator.
#include <coresoftware/blob/master/offline/packages/tpcdaq/TPCDataStreamEmulator.h>
Public Member Functions
TPCDataStreamEmulator (unsigned int minLayer, unsigned int m_maxLayer, const std::string &outputfilenamebase="TPCDataStreamEmulator")
virtual ~TPCDataStreamEmulator ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void maxLayer (int maxLayer)
void minLayer (int minLayer)
void outputFileNameBase (const std::string &outputFileNameBase)
void saveDataStreamFile (bool saveDataStreamFile)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
Fun4AllHistoManager * getHistoManager ()
int writeWavelet (int layer, int side, int phibin, int hittime, const std::vector< unsigned int > &wavelet)
Private Attributes
bool m_saveDataStreamFile
std::string m_outputFileNameBase
int m_minLayer
int m_maxLayer
int m_evtCounter
double m_vertexZAcceptanceCut
double m_etaAcceptanceCut
TH1 * m_hDataSize
TH1 * m_hWavelet
TH1 * m_hNChEta
TH2 * m_hLayerWaveletSize
TH2 * m_hLayerHit
TH2 * m_hLayerZBinHit
TH2 * m_hLayerZBinADC
TH2 * m_hLayerDataSize
TH2 * m_hLayerSumHit
TH2 * m_hLayerSumDataSize
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
TPCDataStreamEmulator.
Definition at line 26 of file TPCDataStreamEmulator.h.
Constructor & Destructor Documentation
TPCDataStreamEmulator::TPCDataStreamEmulator (unsigned int minLayer, unsigned int m_maxLayer, const std::string & outputfilenamebase = "TPCDataStreamEmulator")
Definition at line 61 of file TPCDataStreamEmulator.cc.
TPCDataStreamEmulator::~TPCDataStreamEmulator () virtual
Definition at line 86 of file TPCDataStreamEmulator.cc.
Member Function Documentation
int TPCDataStreamEmulator::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 95 of file TPCDataStreamEmulator.cc.
References assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllHistoManager::getHisto(), getHistoManager(), i, m_outputFileNameBase, Fun4AllHistoManager::nHistos(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Fun4AllHistoManager * TPCDataStreamEmulator::getHistoManager () private
Definition at line 574 of file TPCDataStreamEmulator.cc.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), InitRun(), and process_event().
int TPCDataStreamEmulator::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 90 of file TPCDataStreamEmulator.cc.
References Fun4AllReturnCodes::EVENT_OK.
int TPCDataStreamEmulator::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 114 of file TPCDataStreamEmulator.cc.
References assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHG4CylinderCellGeom::get_zbins(), getHistoManager(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), SVM_v1::h, i, m_hDataSize, m_hLayerDataSize, m_hLayerHit, m_hLayerSumDataSize, m_hLayerSumHit, m_hLayerWaveletSize, m_hLayerZBinADC, m_hLayerZBinHit, m_hNChEta, m_hWavelet, m_maxLayer, m_minLayer, m_outputFileNameBase, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void TPCDataStreamEmulator::maxLayer (int maxLayer) inline
Definition at line 40 of file TPCDataStreamEmulator.h.
void TPCDataStreamEmulator::minLayer (int minLayer) inline
Definition at line 45 of file TPCDataStreamEmulator.h.
References m_minLayer.
void TPCDataStreamEmulator::outputFileNameBase (const std::string & outputFileNameBase) inline
Definition at line 50 of file TPCDataStreamEmulator.h.
References m_outputFileNameBase.
int TPCDataStreamEmulator::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 237 of file TPCDataStreamEmulator.cc.
References Fun4AllReturnCodes::ABORTRUN, assert, SvtxHitMap::begin(), data, SvtxHitMap::end(), Fun4AllReturnCodes::EVENT_OK, PHG4CellContainer::findCell(), SvtxHit::get_adc(), SvtxHit::get_cellid(), PHG4Cell::get_cellid(), SvtxHit::get_layer(), PHG4CellDefs::SizeBinning::get_phibin(), PHG4CylinderCellGeom::get_phibins(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), PHG4CylinderCellGeom::get_radius(), PHG4CellDefs::SizeBinning::get_zbin(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), Fun4AllHistoManager::getHisto(), getHistoManager(), PHG4HitContainer::getHits(), PHG4CylinderCellGeomContainer::GetLayerCellGeom(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), m_etaAcceptanceCut, m_evtCounter, m_hDataSize, m_hLayerDataSize, m_hLayerHit, m_hLayerSumDataSize, m_hLayerSumHit, m_hLayerZBinADC, m_hLayerZBinHit, m_hNChEta, m_hWavelet, m_maxLayer, m_minLayer, m_vertexZAcceptanceCut, r, PHHepMCGenEventMap::size(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, Fun4AllBase::VERBOSITY_MORE, and writeWavelet().
void TPCDataStreamEmulator::saveDataStreamFile (bool saveDataStreamFile) inline
Definition at line 55 of file TPCDataStreamEmulator.h.
References m_saveDataStreamFile.
int TPCDataStreamEmulator::writeWavelet (int layer, int side, int phibin, int hittime, const std::vector< unsigned int > & wavelet) private
Definition at line 558 of file TPCDataStreamEmulator.cc.
References assert, and m_hLayerWaveletSize.
Referenced by process_event().
Member Data Documentation
double TPCDataStreamEmulator::m_etaAcceptanceCut private
Definition at line 76 of file TPCDataStreamEmulator.h.
Referenced by process_event().
int TPCDataStreamEmulator::m_evtCounter private
Definition at line 73 of file TPCDataStreamEmulator.h.
Referenced by process_event().
TH1* TPCDataStreamEmulator::m_hDataSize private
Definition at line 79 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH2* TPCDataStreamEmulator::m_hLayerDataSize private
Definition at line 86 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH2* TPCDataStreamEmulator::m_hLayerHit private
Definition at line 83 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH2* TPCDataStreamEmulator::m_hLayerSumDataSize private
Definition at line 88 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH2* TPCDataStreamEmulator::m_hLayerSumHit private
Definition at line 87 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH2* TPCDataStreamEmulator::m_hLayerWaveletSize private
Definition at line 82 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and writeWavelet().
TH2* TPCDataStreamEmulator::m_hLayerZBinADC private
Definition at line 85 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH2* TPCDataStreamEmulator::m_hLayerZBinHit private
Definition at line 84 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH1* TPCDataStreamEmulator::m_hNChEta private
Definition at line 81 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
TH1* TPCDataStreamEmulator::m_hWavelet private
Definition at line 80 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
int TPCDataStreamEmulator::m_maxLayer private
Definition at line 71 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), and process_event().
int TPCDataStreamEmulator::m_minLayer private
Definition at line 70 of file TPCDataStreamEmulator.h.
Referenced by InitRun(), minLayer(), and process_event().
std::string TPCDataStreamEmulator::m_outputFileNameBase private
Definition at line 68 of file TPCDataStreamEmulator.h.
Referenced by End(), InitRun(), and outputFileNameBase().
bool TPCDataStreamEmulator::m_saveDataStreamFile private
Definition at line 66 of file TPCDataStreamEmulator.h.
Referenced by saveDataStreamFile().
double TPCDataStreamEmulator::m_vertexZAcceptanceCut private
Definition at line 75 of file TPCDataStreamEmulator.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/tpcdaq/TPCDataStreamEmulator.h
coresoftware/blob/master/offline/packages/tpcdaq/TPCDataStreamEmulator.cc