Analysis Software: PHGenIntegralv1 Class Reference
PHGenIntegralv1 Class Reference
PHGenIntegralv1.
#include <coresoftware/blob/master/generators/phhepmc/PHGenIntegralv1.h>
Public Member Functions
PHGenIntegralv1 ()
PHGenIntegralv1 (const std::string &description)
virtual ~PHGenIntegralv1 ()
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int Integrate () const
virtual int Integrate (PHObject *)
For integral objects, e.g. integrated luminosity counter, integrate with another object from another run.
virtual void CopyFrom (const PHObject *obj)
Double_t get_Integrated_Lumi () const
Integrated luminosity in pb^-1.
void set_Integrated_Lumi (Double_t integratedLumi)
Integrated luminosity in pb^-1.
ULong64_t get_N_Generator_Accepted_Event () const
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
void set_N_Generator_Accepted_Event (ULong64_t nGeneratorAcceptedEvent)
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
ULong64_t get_N_Processed_Event () const
Number of processed events in the Fun4All cycles.
void set_N_Processed_Event (ULong64_t nProcessedEvent)
Number of processed events in the Fun4All cycles.
Double_t get_Sum_Of_Weight () const
void set_Sum_Of_Weight (Double_t sumOfWeight)
const std::string & get_Description () const
description on the source
void set_Description (const std::string &description)
description on the source
Public Member Functions inherited from PHGenIntegral
PHGenIntegral ()
virtual ~PHGenIntegral ()
virtual Double_t get_CrossSection_Processed_Event () const
cross sections for the processed events in pb
virtual Double_t get_CrossSection_Generator_Accepted_Event () const
cross sections for the events accepted by the event generator in pb
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
Private Attributes
ULong64_t m_NProcessedEvent
Number of processed events in the Fun4All cycles.
ULong64_t m_NGeneratorAcceptedEvent
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Double_t m_IntegratedLumi
Integrated luminosity in pb^-1.
Double_t m_SumOfWeight
std::string m_Description
description on the source
Detailed Description
PHGenIntegralv1.
Definition at line 22 of file PHGenIntegralv1.h.
Constructor & Destructor Documentation
PHGenIntegralv1::PHGenIntegralv1 ()
Definition at line 20 of file PHGenIntegralv1.cc.
Referenced by CloneMe().
PHGenIntegralv1::PHGenIntegralv1 (const std::string & description) explicit
Definition at line 28 of file PHGenIntegralv1.cc.
virtual PHGenIntegralv1::~PHGenIntegralv1 () inline virtual
Definition at line 27 of file PHGenIntegralv1.h.
Member Function Documentation
virtual PHObject* PHGenIntegralv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 29 of file PHGenIntegralv1.h.
References PHGenIntegralv1().
void PHGenIntegralv1::CopyFrom (const PHObject * obj) virtual
Reimplemented from PHObject.
Definition at line 84 of file PHGenIntegralv1.cc.
References PHGenIntegral::get_Description(), PHGenIntegral::get_Integrated_Lumi(), PHGenIntegral::get_N_Generator_Accepted_Event(), PHGenIntegral::get_N_Processed_Event(), PHGenIntegral::get_Sum_Of_Weight(), PHObject::identify(), m_Description, m_IntegratedLumi, m_NGeneratorAcceptedEvent, m_NProcessedEvent, and m_SumOfWeight.
const std::string& PHGenIntegralv1::get_Description () const inline virtual
description on the source
Reimplemented from PHGenIntegral.
Definition at line 92 of file PHGenIntegralv1.h.
References m_Description.
Referenced by identify().
Double_t PHGenIntegralv1::get_Integrated_Lumi () const inline virtual
Integrated luminosity in pb^-1.
Reimplemented from PHGenIntegral.
Definition at line 40 of file PHGenIntegralv1.h.
References m_IntegratedLumi.
Referenced by identify().
ULong64_t PHGenIntegralv1::get_N_Generator_Accepted_Event () const inline virtual
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Reimplemented from PHGenIntegral.
Definition at line 52 of file PHGenIntegralv1.h.
References m_NGeneratorAcceptedEvent.
Referenced by identify().
ULong64_t PHGenIntegralv1::get_N_Processed_Event () const inline virtual
Number of processed events in the Fun4All cycles.
Reimplemented from PHGenIntegral.
Definition at line 64 of file PHGenIntegralv1.h.
References m_NProcessedEvent.
Referenced by identify().
Double_t PHGenIntegralv1::get_Sum_Of_Weight () const inline virtual
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Reimplemented from PHGenIntegral.
Definition at line 78 of file PHGenIntegralv1.h.
References m_SumOfWeight.
Referenced by identify().
void PHGenIntegralv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 36 of file PHGenIntegralv1.cc.
References PHGenIntegral::get_CrossSection_Generator_Accepted_Event(), PHGenIntegral::get_CrossSection_Processed_Event(), get_Description(), get_Integrated_Lumi(), get_N_Generator_Accepted_Event(), get_N_Processed_Event(), and get_Sum_Of_Weight().
virtual int PHGenIntegralv1::Integrate () const inline virtual
Reimplemented from PHObject.
Definition at line 34 of file PHGenIntegralv1.h.
int PHGenIntegralv1::Integrate (PHObject * incoming_object) virtual
For integral objects, e.g. integrated luminosity counter, integrate with another object from another run.
Reimplemented from PHObject.
Definition at line 54 of file PHGenIntegralv1.cc.
References PHGenIntegral::get_Description(), PHGenIntegral::get_Integrated_Lumi(), PHGenIntegral::get_N_Generator_Accepted_Event(), PHGenIntegral::get_N_Processed_Event(), PHGenIntegral::get_Sum_Of_Weight(), PHObject::identify(), m_Description, m_IntegratedLumi, m_NGeneratorAcceptedEvent, m_NProcessedEvent, and m_SumOfWeight.
virtual int PHGenIntegralv1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 30 of file PHGenIntegralv1.h.
void PHGenIntegralv1::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 45 of file PHGenIntegralv1.cc.
References m_Description, m_IntegratedLumi, m_NGeneratorAcceptedEvent, m_NProcessedEvent, and m_SumOfWeight.
void PHGenIntegralv1::set_Description (const std::string & description) inline virtual
description on the source
Reimplemented from PHGenIntegral.
Definition at line 98 of file PHGenIntegralv1.h.
References description, and m_Description.
void PHGenIntegralv1::set_Integrated_Lumi (Double_t integratedLumi) inline virtual
Integrated luminosity in pb^-1.
Reimplemented from PHGenIntegral.
Definition at line 46 of file PHGenIntegralv1.h.
References m_IntegratedLumi.
void PHGenIntegralv1::set_N_Generator_Accepted_Event (ULong64_t nGeneratorAcceptedEvent) inline virtual
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Reimplemented from PHGenIntegral.
Definition at line 58 of file PHGenIntegralv1.h.
References m_NGeneratorAcceptedEvent.
void PHGenIntegralv1::set_N_Processed_Event (ULong64_t nProcessedEvent) inline virtual
Number of processed events in the Fun4All cycles.
Reimplemented from PHGenIntegral.
Definition at line 70 of file PHGenIntegralv1.h.
References m_NProcessedEvent.
void PHGenIntegralv1::set_Sum_Of_Weight (Double_t sumOfWeight) inline virtual
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Reimplemented from PHGenIntegral.
Definition at line 86 of file PHGenIntegralv1.h.
References m_SumOfWeight.
Member Data Documentation
std::string PHGenIntegralv1::m_Description private
description on the source
Definition at line 119 of file PHGenIntegralv1.h.
Referenced by CopyFrom(), get_Description(), Integrate(), Reset(), and set_Description().
Double_t PHGenIntegralv1::m_IntegratedLumi private
Integrated luminosity in pb^-1.
Definition at line 111 of file PHGenIntegralv1.h.
Referenced by CopyFrom(), get_Integrated_Lumi(), Integrate(), Reset(), and set_Integrated_Lumi().
ULong64_t PHGenIntegralv1::m_NGeneratorAcceptedEvent private
Number of accepted events in the event generator. This can be higher than m_NProcessedEvent depending on trigger on the event generator.
Definition at line 108 of file PHGenIntegralv1.h.
Referenced by CopyFrom(), get_N_Generator_Accepted_Event(), Integrate(), Reset(), and set_N_Generator_Accepted_Event().
ULong64_t PHGenIntegralv1::m_NProcessedEvent private
Number of processed events in the Fun4All cycles.
Definition at line 105 of file PHGenIntegralv1.h.
Referenced by CopyFrom(), get_N_Processed_Event(), Integrate(), Reset(), and set_N_Processed_Event().
Double_t PHGenIntegralv1::m_SumOfWeight private
Sum of weight assigned to the events by the generators. Event weight is normally 1 and thus equal to number of the generated event and is uninteresting. However, there are several cases where one may have nontrivial event weights, e.g. using user hooks in Pythia8 generators to reweight the phase space
Definition at line 116 of file PHGenIntegralv1.h.
Referenced by CopyFrom(), get_Sum_Of_Weight(), Integrate(), Reset(), and set_Sum_Of_Weight().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/PHGenIntegralv1.h
coresoftware/blob/master/generators/phhepmc/PHGenIntegralv1.cc