Analysis Software: online_distribution/blob/master/pmonitor/pmonitor.cc File Reference
pmonitor.cc File Reference
#include <Event/testEventiterator.h>
#include <Event/fileEventiterator.h>
#include <Event/listEventiterator.h>
#include <Event/oncsEventiterator.h>
#include <Event/rcdaqEventiterator.h>
#include <string>
#include <iostream>
#include <sstream>
#include <unistd.h>
#include "pmonitor.h"
#include "pmonstate.h"
#include <TThread.h>
#include <TGClient.h>
#include <pMutex.h>
#include <pthread.h>
Classes
struct threadargument
Functions
int pstatus ()
int pexitstatus ()
int ptestopen ()
int pfileopen (const char *filename)
int poncsopen (const char *filename)
int rcdaqopen (const char *ip)
int plistopen (const char *filename)
int pidentify (const int n)
int pidentify ()
int pclearidentify ()
void pprocess (void *ptr)
int pstart (const int nevents)
int pstart ()
void prun ()
void prun (const int nevents)
int pstop ()
int pclose ()
int plock ()
int prelease ()
int pwait ()
void phelp ()
void update_process (void *ptr)
void pupdate (TVirtualPad *pad, const unsigned int refresh)
void pend_update (TVirtualPad *pad)
Variables
static Eventiterator * theIterator = 0
int stopcondition
int displaystopcondition
static pmonstate theState
static TThread * main_thread = 0
static pMutex TM
static pMutex runningTM
pthread_mutex_t pmonmutex
int totalevents
int mylock = 0
unsigned int stop_display = 0
pMutex mondisplay_started
static TThread * mon_thread = 0
unsigned int refreshinterval = 5
unsigned int stop_update = 0
TVirtualPad * pad_to_stop = 0
Function Documentation
int pclearidentify ()
Definition at line 227 of file pmonitor.cc.
References pmonstate::setIdentifyFlag().
int pclose ()
Definition at line 382 of file pmonitor.cc.
References pmonstate::clearOpened(), pmonstate::isRunning(), pmonstate::streamOpened(), and theIterator.
Referenced by pprocess(), and prun().
void pend_update (TVirtualPad * pad)
Definition at line 679 of file pmonitor.cc.
References pad_to_stop, and stop_update.
int pexitstatus ()
Definition at line 57 of file pmonitor.cc.
References pmonstate::getloopStatus().
int pfileopen (const char * filename)
Definition at line 83 of file pmonitor.cc.
References FROG::location(), pmonstate::setFileOpened(), pmonstate::streamOpened(), and theIterator.
void phelp ()
Definition at line 550 of file pmonitor.cc.
int pidentify (const int n)
Definition at line 201 of file pmonitor.cc.
References pmonstate::setIdentifyFlag().
int pidentify ()
Definition at line 221 of file pmonitor.cc.
References pmonstate::setIdentifyFlag().
int plistopen (const char * filename)
Definition at line 179 of file pmonitor.cc.
References pmonstate::setFileOpened(), pmonstate::streamOpened(), and theIterator.
int plock ()
Definition at line 406 of file pmonitor.cc.
References mylock, and pmonmutex.
int poncsopen (const char * filename)
Definition at line 113 of file pmonitor.cc.
References pmonstate::setFileOpened(), pmonstate::streamOpened(), and theIterator.
Referenced by groot100().
void pprocess (void * ptr)
Definition at line 238 of file pmonitor.cc.
References pmonstate::clearNoevt(), pmonstate::clearRunning(), Eventiterator::getNextEvent(), Event::identify(), pmonstate::incrementNoevt(), pmonstate::isIdentifyFlag(), pMutex::Lock(), nevents(), pclose(), process_event(), pMutex::Release(), return(), pmonstate::setloopStatus(), pmonstate::setRunning(), stopcondition, and totalevents.
Referenced by pstart().
int prelease ()
Definition at line 422 of file pmonitor.cc.
References mylock, and pmonmutex.
void prun ()
Definition at line 319 of file pmonitor.cc.
References prun().
Referenced by groot100(), prun(), and pypole().
void prun (const int nevents)
Definition at line 324 of file pmonitor.cc.
References pmonstate::clearNoevt(), pmonstate::clearRunning(), Eventiterator::getNextEvent(), Event::identify(), pmonstate::incrementNoevt(), pmonstate::isIdentifyFlag(), pclose(), process_event(), return(), pmonstate::setloopStatus(), pmonstate::setRunning(), stopcondition, and pmonstate::streamOpened().
int pstart (const int nevents)
Definition at line 292 of file pmonitor.cc.
References pmonstate::isRunning(), main_thread, nevents(), pprocess(), pmonstate::streamOpened(), and totalevents.
Referenced by pstart().
int pstart ()
Definition at line 314 of file pmonitor.cc.
References pstart().
int pstatus ()
Definition at line 44 of file pmonitor.cc.
References Eventiterator::identify(), and theState.
int pstop ()
Definition at line 366 of file pmonitor.cc.
References pmonstate::isRunning(), and stopcondition.
int ptestopen ()
Definition at line 65 of file pmonitor.cc.
References pmonstate::setTestOpened(), and pmonstate::streamOpened().
void pupdate (TVirtualPad * pad, const unsigned int refresh)
Definition at line 657 of file pmonitor.cc.
References mon_thread, pad_to_stop, threadargument::refreshinterval, stop_update, threadargument::thePad, and update_process().
int pwait ()
Definition at line 437 of file pmonitor.cc.
References pMutex::Lock(), and pMutex::Release().
int rcdaqopen (const char * ip)
Definition at line 137 of file pmonitor.cc.
References pmonstate::setRCDAQOpened(), pmonstate::streamOpened(), and theIterator.
void update_process (void * ptr)
Definition at line 599 of file pmonitor.cc.
References i, pad_to_stop, threadargument::refreshinterval, s, stop_update, threadargument::thePad, and x.
Referenced by pupdate().
Variable Documentation
int displaystopcondition
Definition at line 30 of file pmonitor.cc.
TThread* main_thread = 0 static
Definition at line 34 of file pmonitor.cc.
Referenced by pstart().
TThread* mon_thread = 0 static
Definition at line 590 of file pmonitor.cc.
Referenced by pupdate().
pMutex mondisplay_started
Definition at line 588 of file pmonitor.cc.
int mylock = 0
Definition at line 405 of file pmonitor.cc.
Referenced by plock(), and prelease().
TVirtualPad* pad_to_stop = 0
Definition at line 597 of file pmonitor.cc.
Referenced by pend_update(), pupdate(), and update_process().
pthread_mutex_t pmonmutex
Definition at line 42 of file pmonitor.cc.
Referenced by plock(), and prelease().
unsigned int refreshinterval = 5
Definition at line 592 of file pmonitor.cc.
pMutex runningTM static
Definition at line 38 of file pmonitor.cc.
unsigned int stop_display = 0
Definition at line 580 of file pmonitor.cc.
unsigned int stop_update = 0
Definition at line 596 of file pmonitor.cc.
Referenced by pend_update(), pupdate(), and update_process().
int stopcondition
Definition at line 29 of file pmonitor.cc.
Referenced by pprocess(), prun(), and pstop().
Eventiterator* theIterator = 0 static
Definition at line 26 of file pmonitor.cc.
Referenced by pclose(), pfileopen(), plistopen(), poncsopen(), and rcdaqopen().
pmonstate theState static
Definition at line 32 of file pmonitor.cc.
Referenced by pstatus().
pMutex TM static
Definition at line 37 of file pmonitor.cc.
int totalevents
Definition at line 237 of file pmonitor.cc.
Referenced by pprocess(), and pstart().