Analysis Software: TPCR2Map Class Reference
TPCR2Map Class Reference
#include <prototype/blob/master/offline/packages/tpc2019/ChanMap.h>
Public Member Functions
int GetRpos (int card, int chan)
int Getphipos (int card, int chan)
double GetRposReal (int card, int chan, double offset)
double GetphiposReal (int card, int chan, double offset)
double GetXpos (int card, int chan, double roffset, double phioffset)
double GetYpos (int card, int chan, double roffset, double phioffset)
Private Attributes
int ChanMap [2048][4]
Detailed Description
Definition at line 16 of file ChanMap.h.
Member Function Documentation
int TPCR2Map::Getphipos (int card, int chan) inline
Definition at line 2083 of file ChanMap.h.
References ChanMap.
Referenced by GetphiposReal(), and TpcPrototypeUnpacker::process_event().
double TPCR2Map::GetphiposReal (int card, int chan, double offset) inline
Definition at line 2091 of file ChanMap.h.
References Getphipos(), M_PI, and offset.
Referenced by GetXpos(), and GetYpos().
int TPCR2Map::GetRpos (int card, int chan) inline
Definition at line 2079 of file ChanMap.h.
References ChanMap.
Referenced by GetRposReal(), and TpcPrototypeUnpacker::process_event().
double TPCR2Map::GetRposReal (int card, int chan, double offset) inline
Definition at line 2087 of file ChanMap.h.
References GetRpos(), and offset.
Referenced by GetXpos(), and GetYpos().
double TPCR2Map::GetXpos (int card, int chan, double roffset, double phioffset) inline
Definition at line 2095 of file ChanMap.h.
References GetphiposReal(), and GetRposReal().
double TPCR2Map::GetYpos (int card, int chan, double roffset, double phioffset) inline
Definition at line 2100 of file ChanMap.h.
References GetphiposReal(), and GetRposReal().
Member Data Documentation
int TPCR2Map::ChanMap[2048][4] private
Definition at line 27 of file ChanMap.h.
Referenced by Getphipos(), and GetRpos().
The documentation for this class was generated from the following file:
prototype/blob/master/offline/packages/tpc2019/ChanMap.h