Analysis Software: TPCDaqDefs::FEEv1 Namespace Reference
TPCDaqDefs::FEEv1 Namespace Reference
TPC v1 FEE test stand decoder.
Classes
class SampleFit_PowerLawDoubleExp_PDFMaker
Functions
bool SampleFit_PowerLawDoubleExp (const std::vector< double > &samples,double &peak,double &peak_sample,double &pedestal,std::map< int, double > &parameters_io,const int verbosity=0)
Power law double exp fit.
double SignalShape_PowerLawExp (double *x, double *par)
double SignalShape_PowerLawDoubleExp (double *x, double *par)
pair< int, int > SAMPAChan2PadXY (uint32_t fee_channel)
Variables
static const unsigned int kPACKET_ID = 1024
static const unsigned int kPACKET_LENGTH = 137
static const unsigned int kN_CHANNELS = 256
static const unsigned int kSAMPLE_LENGTH = 128
static const unsigned int kMaxPadX = 50
static const unsigned int kMaxPadY = 12
Detailed Description
TPC v1 FEE test stand decoder.
Function Documentation
std::pair< int, int > TPCDaqDefs::FEEv1::SAMPAChan2PadXY (uint32_t fee_channel)
Definition at line 317 of file TPCDaqDefs.cc.
Referenced by TPCFEETestRecov1::process_event().
bool TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp (const std::vector< double > & samples, double & peak, double & peak_sample, double & pedestal, std::map< int, double > & parameters_io, const int verbosity)
Power law double exp fit.
Parameters
peak_sample peak amplitude.
pedestal peak sample position. Fixed to the input value if NOT NAN
parameters_io pedestal
verbosity IO for fullset of parameters. If a parameter exist and not an NAN, the fit parameter will be fixed to that value. The order of the parameters are ("Amplitude 1", "Sample Start", "Power", "Peak Time 1", "Pedestal", "Amplitude 2", "Peak Time 2")
Definition at line 68 of file TPCDaqDefs.cc.
References f2(), gpulse, i, max, min, pedestal(), SignalShape_PowerLawDoubleExp(), and SignalShape_PowerLawExp().
Referenced by TPCFEETestRecov1::Clustering(), and TpcPrototypeUnpacker::Clustering().
double TPCDaqDefs::FEEv1::SignalShape_PowerLawDoubleExp (double * x, double * par)
Definition at line 298 of file TPCDaqDefs.cc.
References pedestal(), and signal().
Referenced by PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), and SampleFit_PowerLawDoubleExp().
double TPCDaqDefs::FEEv1::SignalShape_PowerLawExp (double * x, double * par)
Definition at line 286 of file TPCDaqDefs.cc.
References pedestal(), and signal().
Referenced by PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp(), SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), PROTOTYPE3_FEM::SampleFit_PowerLawExp(), PROTOTYPE2_FEM::SampleFit_PowerLawExp(), and PROTOTYPE4_FEM::SampleFit_PowerLawExp().
Variable Documentation
const unsigned int TPCDaqDefs::FEEv1::kMaxPadX = 50 static
Definition at line 23 of file TPCDaqDefs.h.
Referenced by TPCFEETestRecov1::PadPlaneData::Clustering(), TpcPrototypeUnpacker::PadPlaneData::Clustering(), TpcPrototypeUnpacker::exportDSTCluster(), TPCFEETestRecov1::PadPlaneData::getPad(), TpcPrototypeUnpacker::PadPlaneData::getPad(), TPCFEETestRecov1::PadPlaneData::IsValidPad(), and TpcPrototypeUnpacker::PadPlaneData::IsValidPad().
const unsigned int TPCDaqDefs::FEEv1::kMaxPadY = 12 static
Definition at line 24 of file TPCDaqDefs.h.
Referenced by TPCFEETestRecov1::PadPlaneData::Clustering(), TpcPrototypeUnpacker::PadPlaneData::Clustering(), TpcPrototypeUnpacker::Clustering(), TPCFEETestRecov1::PadPlaneData::getPad(), TpcPrototypeUnpacker::PadPlaneData::getPad(), TPCFEETestRecov1::PadPlaneData::IsValidPad(), and TpcPrototypeUnpacker::PadPlaneData::IsValidPad().
const unsigned int TPCDaqDefs::FEEv1::kN_CHANNELS = 256 static
Definition at line 20 of file TPCDaqDefs.h.
Referenced by TPCFEETestRecov1::process_event(), and TpcPrototypeUnpacker::process_event().
const unsigned int TPCDaqDefs::FEEv1::kPACKET_ID = 1024 static
Definition at line 18 of file TPCDaqDefs.h.
Referenced by TPCFEETestRecov1::process_event(), and TpcPrototypeUnpacker::process_event().
const unsigned int TPCDaqDefs::FEEv1::kPACKET_LENGTH = 137 static
Definition at line 19 of file TPCDaqDefs.h.
Referenced by TPCFEETestRecov1::process_event().
const unsigned int TPCDaqDefs::FEEv1::kSAMPLE_LENGTH = 128 static
Definition at line 21 of file TPCDaqDefs.h.
Referenced by TPCFEETestRecov1::PadPlaneData::Clustering(), TpcPrototypeUnpacker::PadPlaneData::Clustering(), TPCFEETestRecov1::Clustering(), TpcPrototypeUnpacker::Clustering(), TPCFEETestRecov1::InitRun(), TpcPrototypeUnpacker::InitRun(), TPCFEETestRecov1::process_event(), and TpcPrototypeUnpacker::process_event().