Analysis Software: PHG4FPbScSteppingAction Class Reference
PHG4FPbScSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FPbScSteppingAction.h>
Public Member Functions
PHG4FPbScSteppingAction (PHG4FPbScDetector *)
virtual ~PHG4FPbScSteppingAction ()
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action. This defines processing of a single step in a given volume
virtual void SetInterfacePointers (PHCompositeNode *)
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4FPbScDetector * detector_
PHG4HitContainer * hits_
Detailed Description
Definition at line 13 of file PHG4FPbScSteppingAction.h.
Constructor & Destructor Documentation
PHG4FPbScSteppingAction::PHG4FPbScSteppingAction (PHG4FPbScDetector * detector)
Definition at line 31 of file PHG4FPbScSteppingAction.cc.
virtual PHG4FPbScSteppingAction::~PHG4FPbScSteppingAction () inline virtual
Definition at line 17 of file PHG4FPbScSteppingAction.h.
Member Function Documentation
void PHG4FPbScSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
Reimplemented from PHG4SteppingAction.
Definition at line 137 of file PHG4FPbScSteppingAction.cc.
References detector_, PHG4Detector::GetName(), and hits_.
bool PHG4FPbScSteppingAction::UserSteppingAction (const G4Step * step, bool was_used) virtual
stepping action. This defines processing of a single step in a given volume
returns true if hits associated to this step was processed by this detector
Parameters
step pointer to the geant 4 step class
was_used,: true if the hit was already used by a previously registered subsystem
Implements PHG4SteppingAction.
Definition at line 38 of file PHG4FPbScSteppingAction.cc.
References PHG4FPbScDetector::computeIndex(), detector_, PHG4HitContainer::findOrAddHit(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), PHG4FPbScDetector::getScintillatorLayer(), hits_, PHG4FPbScDetector::isInScintillator(), it, PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and PHG4TrackUserInfoV1::SetWanted().
Member Data Documentation
PHG4FPbScDetector* PHG4FPbScSteppingAction::detector_ private
Definition at line 24 of file PHG4FPbScSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer* PHG4FPbScSteppingAction::hits_ private
Definition at line 25 of file PHG4FPbScSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FPbScSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FPbScSteppingAction.cc