Analysis Software: PgPostBankManager Class Reference
PgPostBankManager Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankManager.h>
Public Member Functions
virtual ~PgPostBankManager ()
virtual PdbCalBankIterator * getIterator ()
Get an iterator to loop over banks.
virtual PdbCalBank * createBank (const std::string &, PdbBankID, const std::string &, PHTimeStamp &, PHTimeStamp &, const std::string &)
PdbCalBank * createBank (const int, const std::string &, PdbBankID, const std::string &, const std::string &, const time_t duration=60)
PdbCalBank * createBank (const int, const int, const std::string &, PdbBankID, const std::string &, const std::string &)
PdbCalBank * fetchBank (const std::string &, PdbBankID, const std::string &, const int)
PdbCalBank * fetchClosestBank (const std::string &, PdbBankID, const std::string &, const int)
PdbCalBank * fetchBank (const std::string &, PdbBankID, const std::string &, const PHTimeStamp &)
PdbCalBank * fetchClosestBank (const std::string &, PdbBankID, const std::string &, PHTimeStamp &)
PdbApplication * getApplication ()
void fillCalibObject (PdbCalBank *, const std::string &, PHTimeStamp &)
void GetUsedBankRids (std::map< std::string, std::set< int > > &usedbanks) const
void ClearUsedBankRids ()
void SetMaxInsertTime (const PHTimeStamp &tMax)
Static Public Member Functions
static PgPostBankManager * instance ()
static int Register ()
Static Public Member Functions inherited from PdbBankManager
static PdbBankManager * instance ()
Protected Member Functions
PgPostBankManager ()
Protected Member Functions inherited from PdbBankManager
PdbBankManager ()
virtual ~PdbBankManager ()
Private Member Functions
std::string getRealName (const std::string &)
Private Attributes
std::map< std::string,
std::set< int > > BankRid
PHTimeStamp tMaxInsertTime
Static Private Attributes
static PgPostBankManager * mySpecificCopy = 0
Additional Inherited Members
Static Protected Attributes inherited from PdbBankManager
static PdbBankManager * __instance = nullptr
Detailed Description
Definition at line 20 of file PgPostBankManager.h.
Constructor & Destructor Documentation
PgPostBankManager::~PgPostBankManager () virtual
Definition at line 73 of file PgPostBankManager.cc.
PgPostBankManager::PgPostBankManager () protected
Definition at line 65 of file PgPostBankManager.cc.
References PHWHERE.
Member Function Documentation
void PgPostBankManager::ClearUsedBankRids () inline virtual
Reimplemented from PdbBankManager.
Definition at line 64 of file PgPostBankManager.h.
References BankRid.
PdbCalBank * PgPostBankManager::createBank (const std::string & className, PdbBankID bankID, const std::string & descr, PHTimeStamp & tStart, PHTimeStamp & tStop, const std::string & tablename) virtual
Implements PdbBankManager.
Definition at line 151 of file PgPostBankManager.cc.
References b1, PdbCalBank::CloneMe(), PdbClassMap< T >::end(), PdbClassMap< T >::find(), PdbBankID::getInternalValue(), PdbClassMap< T >::instance(), PHWHERE, PgPostBankWrapper::setBankID(), PgPostBankWrapper::setDescription(), PgPostBankWrapper::setEndValTime(), PgPostBankWrapper::setInsertTime(), PgPostBankWrapper::setStartValTime(), PgPostBankWrapper::setTableName(), and PgPostBankWrapper::setUserName().
PdbCalBank * PgPostBankManager::createBank (const int runNumber, const std::string & className, PdbBankID bankID, const std::string & description, const std::string & bankName, const time_t duration = 60) virtual
Implements PdbBankManager.
Definition at line 125 of file PgPostBankManager.cc.
References RunToTime::getBeginTime(), and RunToTime::instance().
PdbCalBank * PgPostBankManager::createBank (const int beginRunNumber, const int endRunNumber, const std::string & className, PdbBankID bankID, const std::string & description, const std::string & bankName) virtual
Implements PdbBankManager.
Definition at line 85 of file PgPostBankManager.cc.
References RunToTime::getBeginTime(), RunToTime::getEndTime(), RunToTime::instance(), and PHWHERE.
PdbCalBank * PgPostBankManager::fetchBank (const std::string & className, PdbBankID bankID, const std::string & bankName, const int runNumber) virtual
Implements PdbBankManager.
Definition at line 180 of file PgPostBankManager.cc.
References RunToTime::getBeginTime(), and RunToTime::instance().
PdbCalBank * PgPostBankManager::fetchBank (const std::string & className, PdbBankID bankID, const std::string & bankName, const PHTimeStamp & searchTime) virtual
Implements PdbBankManager.
Definition at line 237 of file PgPostBankManager.cc.
References PgPostApplication::getConnection(), PdbBankID::getInternalValue(), PHTimeStamp::getTics(), PgPostApplication::instance(), PHWHERE, PgPostBankWrapper::printHeader(), PgPostBankWrapper::setBankID(), PgPostBankWrapper::setDescription(), PgPostBankWrapper::setEndValTime(), PgPostBankWrapper::setInsertTime(), PgPostBankWrapper::setStartValTime(), PgPostBankWrapper::setTableName(), PgPostBankWrapper::setUserName(), and t2.
PdbCalBank * PgPostBankManager::fetchClosestBank (const std::string & className, PdbBankID bankID, const std::string & bankName, const int runNumber) virtual
Implements PdbBankManager.
Definition at line 195 of file PgPostBankManager.cc.
References RunToTime::getBeginTime(), and RunToTime::instance().
PdbCalBank * PgPostBankManager::fetchClosestBank (const std::string & className, PdbBankID bankID, const std::string & bankName, PHTimeStamp & searchTime) virtual
Implements PdbBankManager.
Definition at line 316 of file PgPostBankManager.cc.
References PHWHERE.
void PgPostBankManager::fillCalibObject (PdbCalBank * , const std::string & , PHTimeStamp &) inline virtual
Implements PdbBankManager.
Definition at line 61 of file PgPostBankManager.h.
PdbApplication * PgPostBankManager::getApplication () virtual
Implements PdbBankManager.
Definition at line 419 of file PgPostBankManager.cc.
References PgPostApplication::instance().
Referenced by PgPostCalBankIterator::PgPostCalBankIterator().
PdbCalBankIterator * PgPostBankManager::getIterator () virtual
Get an iterator to loop over banks.
Implements PdbBankManager.
Definition at line 79 of file PgPostBankManager.cc.
string PgPostBankManager::getRealName (const std::string & searchName) private
Definition at line 425 of file PgPostBankManager.cc.
void PgPostBankManager::GetUsedBankRids (std::map< std::string, std::set< int > > & usedbanks) const virtual
Reimplemented from PdbBankManager.
Definition at line 433 of file PgPostBankManager.cc.
PgPostBankManager * PgPostBankManager::instance () static
Definition at line 52 of file PgPostBankManager.cc.
int PgPostBankManager::Register () static
Definition at line 57 of file PgPostBankManager.cc.
void PgPostBankManager::SetMaxInsertTime (const PHTimeStamp & tMax) virtual
Reimplemented from PdbBankManager.
Definition at line 449 of file PgPostBankManager.cc.
References PHTimeStamp::getTics().
Member Data Documentation
std::map<std::string, std::set<int> > PgPostBankManager::BankRid private
Definition at line 69 of file PgPostBankManager.h.
Referenced by ClearUsedBankRids().
PgPostBankManager * PgPostBankManager::mySpecificCopy = 0 static private
Definition at line 68 of file PgPostBankManager.h.
PHTimeStamp PgPostBankManager::tMaxInsertTime private
Definition at line 71 of file PgPostBankManager.h.
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankManager.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankManager.cc