Analysis Software: PidInfoContainer Class Reference
PidInfoContainer Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/PidInfoContainer.h>
Public Types
typedef std::map< int, PidInfo * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PidInfoContainer ()
virtual ~PidInfoContainer ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
ConstIterator AddPidInfo (PidInfo *pidinfo)
PidInfo * getPidInfo (const int trackid)
ConstRange getPidInfos (void) const
return all pid infos
Range getPidInfos (void)
unsigned int size () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map _pidinfos
Detailed Description
Definition at line 11 of file PidInfoContainer.h.
Member Typedef Documentation
typedef Map::const_iterator PidInfoContainer::ConstIterator
Definition at line 18 of file PidInfoContainer.h.
typedef std::pair<ConstIterator, ConstIterator> PidInfoContainer::ConstRange
Definition at line 20 of file PidInfoContainer.h.
typedef Map::iterator PidInfoContainer::Iterator
Definition at line 17 of file PidInfoContainer.h.
typedef std::map<int, PidInfo *> PidInfoContainer::Map
Definition at line 16 of file PidInfoContainer.h.
typedef std::pair<Iterator, Iterator> PidInfoContainer::Range
Definition at line 19 of file PidInfoContainer.h.
Constructor & Destructor Documentation
PidInfoContainer::PidInfoContainer () inline
Definition at line 22 of file PidInfoContainer.h.
virtual PidInfoContainer::~PidInfoContainer () inline virtual
Definition at line 23 of file PidInfoContainer.h.
Member Function Documentation
PidInfoContainer::ConstIterator PidInfoContainer::AddPidInfo (PidInfo * pidinfo)
Definition at line 22 of file PidInfoContainer.cc.
References PidInfo::get_track_id().
Referenced by FastPid_RICH::process_event(), and RICHParticleID::process_event().
PidInfo * PidInfoContainer::getPidInfo (const int trackid)
Definition at line 30 of file PidInfoContainer.cc.
References it.
Referenced by FastPid_RICH::process_event(), and RICHParticleID::process_event().
PidInfoContainer::ConstRange PidInfoContainer::getPidInfos (void) const
return all pid infos
Definition at line 10 of file PidInfoContainer.cc.
PidInfoContainer::Range PidInfoContainer::getPidInfos (void)
Definition at line 16 of file PidInfoContainer.cc.
void PidInfoContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 57 of file PidInfoContainer.cc.
int PidInfoContainer::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 41 of file PidInfoContainer.cc.
void PidInfoContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 47 of file PidInfoContainer.cc.
unsigned int PidInfoContainer::size (void) const inline
Definition at line 34 of file PidInfoContainer.h.
References _pidinfos.
Member Data Documentation
Map PidInfoContainer::_pidinfos protected
Definition at line 37 of file PidInfoContainer.h.
Referenced by size().
The documentation for this class was generated from the following files:
analysis/blob/master/ParticleID/RICHAnalysis/PidInfoContainer.h
analysis/blob/master/ParticleID/RICHAnalysis/PidInfoContainer.cc