Analysis Software: PHG4BlockDetector Class Reference
PHG4BlockDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockDetector.h>
Public Member Functions
PHG4BlockDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam, const int lyr=0)
constructor
virtual ~PHG4BlockDetector (void)
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
volume accessors
bool IsInBlock (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Attributes
PHParameters * m_Params
G4VPhysicalVolume * m_BlockPhysi
PHG4BlockDisplayAction * m_DisplayAction
int m_Layer
std::string m_SuperDetector
Detailed Description
Definition at line 17 of file PHG4BlockDetector.h.
Constructor & Destructor Documentation
PHG4BlockDetector::PHG4BlockDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam, const int lyr = 0)
constructor
Definition at line 34 of file PHG4BlockDetector.cc.
virtual PHG4BlockDetector::~PHG4BlockDetector (void) inline virtual
destructor
Definition at line 24 of file PHG4BlockDetector.h.
Member Function Documentation
void PHG4BlockDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 54 of file PHG4BlockDetector.cc.
References PHParameters::get_double_param(), PHParameters::get_string_param(), PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), m_BlockPhysi, m_DisplayAction, m_Params, PHG4Detector::OverlapCheck(), PHG4Subsystem::SetLogicalVolume(), and PHG4BlockDisplayAction::SetMyVolume().
int PHG4BlockDetector::get_Layer () const inline
Definition at line 38 of file PHG4BlockDetector.h.
References m_Layer.
Referenced by PHG4BlockSteppingAction::UserSteppingAction().
bool PHG4BlockDetector::IsInBlock (G4VPhysicalVolume * volume) const
Definition at line 44 of file PHG4BlockDetector.cc.
References m_BlockPhysi.
Referenced by PHG4BlockSteppingAction::UserSteppingAction().
void PHG4BlockDetector::SuperDetector (const std::string & name) inline
Definition at line 36 of file PHG4BlockDetector.h.
References m_SuperDetector, and name.
Referenced by PHG4BlockSubsystem::InitRunSubsystem(), and PHG4BlockSteppingAction::SetInterfacePointers().
const std::string PHG4BlockDetector::SuperDetector () const inline
Definition at line 37 of file PHG4BlockDetector.h.
References m_SuperDetector.
Member Data Documentation
G4VPhysicalVolume* PHG4BlockDetector::m_BlockPhysi private
Definition at line 43 of file PHG4BlockDetector.h.
Referenced by ConstructMe(), and IsInBlock().
PHG4BlockDisplayAction* PHG4BlockDetector::m_DisplayAction private
Definition at line 44 of file PHG4BlockDetector.h.
Referenced by ConstructMe().
int PHG4BlockDetector::m_Layer private
Definition at line 46 of file PHG4BlockDetector.h.
Referenced by get_Layer().
PHParameters* PHG4BlockDetector::m_Params private
Definition at line 41 of file PHG4BlockDetector.h.
Referenced by ConstructMe().
std::string PHG4BlockDetector::m_SuperDetector private
Definition at line 47 of file PHG4BlockDetector.h.
Referenced by SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockDetector.cc