Analysis Software: prototype/blob/master/macros/tpc2019/Fun4All_TestBeam_TPC.C File Reference
Fun4All_TestBeam_TPC.C File Reference
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <fun4allraw/Fun4AllPrdfInputManager.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4eval/PHG4DSTReader.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4eval/TrkrEvaluator.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4TruthSubsystem.h>
#include <g4tpc/PHG4TpcDigitizer.h>
#include <g4tpc/PHG4TpcElectronDrift.h>
#include <g4tpc/PHG4TpcPadPlane.h>
#include <g4tpc/PHG4TpcPadPlaneReadout.h>
#include <g4tpc/PHG4TpcSubsystem.h>
#include <phgeom/PHGeomFileImport.h>
#include <phool/recoConsts.h>
#include <tpc2019/TpcPrototypeClusterizer.h>
#include <tpc2019/TpcPrototypeGenFitTrkFinder.h>
#include <tpc2019/TpcPrototypeGenFitTrkFitter.h>
#include <tpc2019/TpcPrototypeUnpacker.h>
#include <trackreco/PHGenFitTrkFitter.h>
#include <trackreco/PHGenFitTrkProp.h>
#include <trackreco/PHHoughSeeding.h>
#include <trackreco/PHInitVertexing.h>
#include <trackreco/PHTrackSeeding.h>
#include <trackreco/PHTruthTrackSeeding.h>
#include <trackreco/PHTruthVertexing.h>
Functions
int Fun4All_TestBeam_TPC (int nEvents=10, int nSkip=0, const string &input_file="data/tpc_beam/tpc_beam_00000274-0000.evt", bool eventDisp=false, int verbosity=0)
void RunLoadTest ()
Variables
int n_tpc_layer_inner = 0
int tpc_layer_rphi_count_inner = 1152
int n_tpc_layer_mid = 16
int n_tpc_layer_outer = 0
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
Function Documentation
int Fun4All_TestBeam_TPC (int nEvents = 10, int nSkip = 0, const string & input_file = "data/tpc_beam/tpc_beam_00000274-0000.evt", bool eventDisp = false, int verbosity = 0)
Definition at line 64 of file Fun4All_TestBeam_TPC.C.
References Fun4AllServer::End(), Fun4AllInputManager::fileopen(), in, recoConsts::instance(), Fun4AllServer::instance(), nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), TpcPrototypeUnpacker::registerPadPlane(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), TpcPrototypeGenFitTrkFinder::set_do_eval(), TpcPrototypeGenFitTrkFitter::set_do_eval(), TpcPrototypeGenFitTrkFinder::set_do_evt_display(), TpcPrototypeGenFitTrkFitter::set_do_evt_display(), PHParameterInterface::set_double_param(), TpcPrototypeGenFitTrkFinder::set_eval_filename(), TpcPrototypeGenFitTrkFitter::set_eval_filename(), PHParameterInterface::set_int_param(), PHFlag::set_IntFlag(), TpcPrototypeUnpacker::setNPostSample(), TpcPrototypeUnpacker::setNPreSample(), Fun4AllServer::skip(), verbosity, and Fun4AllBase::Verbosity().
void RunLoadTest ()
Definition at line 173 of file Fun4All_TestBeam_TPC.C.
Variable Documentation
int n_gas_layer = n_tpc_layer_inner + n_tpc_layer_mid + n_tpc_layer_outer
Definition at line 60 of file Fun4All_TestBeam_TPC.C.
int n_tpc_layer_inner = 0
Definition at line 56 of file Fun4All_TestBeam_TPC.C.
int n_tpc_layer_mid = 16
Definition at line 58 of file Fun4All_TestBeam_TPC.C.
int n_tpc_layer_outer = 0
Definition at line 59 of file Fun4All_TestBeam_TPC.C.
int tpc_layer_rphi_count_inner = 1152
Definition at line 57 of file Fun4All_TestBeam_TPC.C.