Analysis Software: TpcPrototypeGenFitTrkFinder Class Reference
TpcPrototypeGenFitTrkFinder Class Reference
find tracks
#include <prototype/blob/master/offline/packages/tpc2019/TpcPrototypeGenFitTrkFinder.h>
Public Member Functions
TpcPrototypeGenFitTrkFinder (const std::string &name="TpcPrototypeGenFitTrkFinder", int layers=16)
Default constructor.
~TpcPrototypeGenFitTrkFinder ()
dtor
int Init (PHCompositeNode *)
Initialization, called for initialization.
int InitRun (PHCompositeNode *)
Initialization Run, called for initialization of a run.
int process_event (PHCompositeNode *)
Process Event, called for each event.
int End (PHCompositeNode *)
End, write and close files.
void set_eval_filename (const std::string &file)
std::string get_eval_filename () const
void fill_eval_tree (PHCompositeNode *)
void init_eval_tree ()
void reset_eval_variables ()
bool is_do_eval () const
void set_do_eval (bool doEval)
bool is_do_evt_display () const
void set_do_evt_display (bool doEvtDisplay)
const std::string & get_track_fitting_alg_name () const
void set_track_fitting_alg_name (const std::string &trackFittingAlgName)
int get_primary_pid_guess () const
void set_primary_pid_guess (int primaryPidGuess)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
typedef std::vector< const
TrkrCluster * > tracklet_t
Private Member Functions
int GetNodes (PHCompositeNode *)
Get all the nodes.
int CreateNodes (PHCompositeNode *)
Create New nodes.
double getChi2Ndf (const tracklet_t &tracklet)
Private Attributes
int _event
Event counter.
PHGenFit::Fitter * _fitter
std::string _track_fitting_alg_name
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
int nLayer
unsigned int minLayer
unsigned int maxTracklet
int _primary_pid_guess
double rphiWindow
double ZWindow
TrkrClusterContainer * _clustermap
Input Node pointers.
SvtxTrackMap * _trackmap
AssocInfoContainer * _assoc_container
SvtxVertexMap * _vertexmap
bool _do_eval
std::string _eval_outname
eval output filename
TTree * _eval_tree
int _tca_ntrack
TClonesArray * _tca_trackmap
TTree * _cluster_eval_tree
float _cluster_eval_tree_x
float _cluster_eval_tree_y
float _cluster_eval_tree_z
float _cluster_eval_tree_gx
float _cluster_eval_tree_gy
float _cluster_eval_tree_gz
bool _do_evt_display
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
find tracks
Definition at line 32 of file TpcPrototypeGenFitTrkFinder.h.
Member Typedef Documentation
typedef std::vector<const TrkrCluster*> TpcPrototypeGenFitTrkFinder::tracklet_t private
Definition at line 118 of file TpcPrototypeGenFitTrkFinder.h.
Constructor & Destructor Documentation
TpcPrototypeGenFitTrkFinder::TpcPrototypeGenFitTrkFinder (const std::string & name = "TpcPrototypeGenFitTrkFinder", int layers = 16)
Default constructor.
Definition at line 85 of file TpcPrototypeGenFitTrkFinder.cc.
References _cluster_eval_tree, _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _event, Fun4AllBase::Verbosity(), and WILD_FLOAT.
TpcPrototypeGenFitTrkFinder::~TpcPrototypeGenFitTrkFinder ()
dtor
Definition at line 529 of file TpcPrototypeGenFitTrkFinder.cc.
References _fitter.
Member Function Documentation
int TpcPrototypeGenFitTrkFinder::CreateNodes (PHCompositeNode * topNode) private
Create New nodes.
Definition at line 600 of file TpcPrototypeGenFitTrkFinder.cc.
References _assoc_container, _trackmap, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by InitRun().
int TpcPrototypeGenFitTrkFinder::End (PHCompositeNode * topNode) virtual
End, write and close files.
Reimplemented from SubsysReco.
Definition at line 494 of file TpcPrototypeGenFitTrkFinder.cc.
References _cluster_eval_tree, _do_eval, _do_evt_display, _eval_outname, _eval_tree, _fitter, PHTFileServer::cd(), PHGenFit::Fitter::displayEvent(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHGenFit::Fitter::getEventDisplay(), PHWHERE, and Fun4AllBase::Verbosity().
void TpcPrototypeGenFitTrkFinder::fill_eval_tree (PHCompositeNode * topNode)
Make sure to reset all the TTree variables before trying to set them.
Definition at line 537 of file TpcPrototypeGenFitTrkFinder.cc.
References _eval_tree, _tca_ntrack, _trackmap, SvtxTrackMap::begin(), SvtxTrackMap::end(), i, and reset_eval_variables().
Referenced by process_event().
std::string TpcPrototypeGenFitTrkFinder::get_eval_filename () const inline
Definition at line 59 of file TpcPrototypeGenFitTrkFinder.h.
References _eval_outname.
int TpcPrototypeGenFitTrkFinder::get_primary_pid_guess () const inline
Definition at line 98 of file TpcPrototypeGenFitTrkFinder.h.
References _primary_pid_guess.
const std::string& TpcPrototypeGenFitTrkFinder::get_track_fitting_alg_name () const inline
Definition at line 88 of file TpcPrototypeGenFitTrkFinder.h.
References _track_fitting_alg_name.
double TpcPrototypeGenFitTrkFinder::getChi2Ndf (const tracklet_t & tracklet) private
Definition at line 402 of file TpcPrototypeGenFitTrkFinder.cc.
References _clustermap, _fitter, _primary_pid_guess, assert, TrkrDefs::getLayer(), i, j, LogWarning, minLayer, n, pos, PHGenFit::Fitter::processTrack(), and Fun4AllBase::Verbosity().
Referenced by process_event().
int TpcPrototypeGenFitTrkFinder::GetNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 652 of file TpcPrototypeGenFitTrkFinder.cc.
References _clustermap, _event, _trackmap, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
int TpcPrototypeGenFitTrkFinder::Init (PHCompositeNode * topNode) virtual
Initialization, called for initialization.
Reimplemented from SubsysReco.
Definition at line 122 of file TpcPrototypeGenFitTrkFinder.cc.
References Fun4AllReturnCodes::EVENT_OK.
void TpcPrototypeGenFitTrkFinder::init_eval_tree ()
create TTree
Definition at line 559 of file TpcPrototypeGenFitTrkFinder.cc.
References _cluster_eval_tree, _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _eval_tree, _tca_ntrack, and _tca_trackmap.
Referenced by InitRun().
int TpcPrototypeGenFitTrkFinder::InitRun (PHCompositeNode * topNode) virtual
Initialization Run, called for initialization of a run.
Reimplemented from SubsysReco.
Definition at line 132 of file TpcPrototypeGenFitTrkFinder.cc.
References _do_eval, _do_evt_display, _eval_outname, _fitter, _track_fitting_alg_name, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), init_eval_tree(), PHTFileServer::open(), PHWHERE, PHGenFit::Fitter::set_verbosity(), and Fun4AllBase::Verbosity().
bool TpcPrototypeGenFitTrkFinder::is_do_eval () const inline
Definition at line 68 of file TpcPrototypeGenFitTrkFinder.h.
References _do_eval.
bool TpcPrototypeGenFitTrkFinder::is_do_evt_display () const inline
Definition at line 78 of file TpcPrototypeGenFitTrkFinder.h.
References _do_evt_display.
int TpcPrototypeGenFitTrkFinder::process_event (PHCompositeNode * topNode) virtual
Process Event, called for each event.
Reimplemented from SubsysReco.
Definition at line 161 of file TpcPrototypeGenFitTrkFinder.cc.
References _assoc_container, _clustermap, _do_eval, _do_evt_display, _event, _trackmap, assert, Fun4AllReturnCodes::EVENT_OK, fill_eval_tree(), SvtxTrack_v1::get_id(), getChi2Ndf(), TrkrClusterContainer::getClusters(), GetNodes(), TrkrCluster::getPosition(), SvtxTrackMap::insert(), SvtxTrack_v1::insert_cluster_key(), maxTracklet, n, nLayer, PHWHERE, pos, rphiWindow, SvtxTrack_v1::set_id(), SvtxTrack_v1::set_px(), SvtxTrack_v1::set_py(), SvtxTrack_v1::set_pz(), SvtxTrack_v1::set_x(), SvtxTrack_v1::set_y(), SvtxTrack_v1::set_z(), AssocInfoContainer::SetClusterTrackAssoc(), SvtxTrackMap::size(), TrkrDefs::tpcId, Fun4AllBase::Verbosity(), and ZWindow.
void TpcPrototypeGenFitTrkFinder::reset_eval_variables ()
Definition at line 587 of file TpcPrototypeGenFitTrkFinder.cc.
References _cluster_eval_tree_gx, _cluster_eval_tree_gy, _cluster_eval_tree_gz, _cluster_eval_tree_x, _cluster_eval_tree_y, _cluster_eval_tree_z, _tca_ntrack, _tca_trackmap, and WILD_FLOAT.
Referenced by fill_eval_tree().
void TpcPrototypeGenFitTrkFinder::set_do_eval (bool doEval) inline
Definition at line 73 of file TpcPrototypeGenFitTrkFinder.h.
References _do_eval.
Referenced by Fun4All_G4_TPC(), and Fun4All_TestBeam_TPC().
void TpcPrototypeGenFitTrkFinder::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 83 of file TpcPrototypeGenFitTrkFinder.h.
References _do_evt_display.
Referenced by Fun4All_G4_TPC(), and Fun4All_TestBeam_TPC().
void TpcPrototypeGenFitTrkFinder::set_eval_filename (const std::string & file) inline
For evalution Change eval output filename
Definition at line 55 of file TpcPrototypeGenFitTrkFinder.h.
References _eval_outname, and file.
Referenced by Fun4All_TestBeam_TPC().
void TpcPrototypeGenFitTrkFinder::set_primary_pid_guess (int primaryPidGuess) inline
Definition at line 103 of file TpcPrototypeGenFitTrkFinder.h.
References _primary_pid_guess.
void TpcPrototypeGenFitTrkFinder::set_track_fitting_alg_name (const std::string & trackFittingAlgName) inline
Definition at line 93 of file TpcPrototypeGenFitTrkFinder.h.
References _track_fitting_alg_name.
Member Data Documentation
AssocInfoContainer* TpcPrototypeGenFitTrkFinder::_assoc_container private
Definition at line 138 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by CreateNodes(), and process_event().
TTree* TpcPrototypeGenFitTrkFinder::_cluster_eval_tree private
Definition at line 152 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by End(), init_eval_tree(), and TpcPrototypeGenFitTrkFinder().
float TpcPrototypeGenFitTrkFinder::_cluster_eval_tree_gx private
Definition at line 156 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFinder().
float TpcPrototypeGenFitTrkFinder::_cluster_eval_tree_gy private
Definition at line 157 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFinder().
float TpcPrototypeGenFitTrkFinder::_cluster_eval_tree_gz private
Definition at line 158 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFinder().
float TpcPrototypeGenFitTrkFinder::_cluster_eval_tree_x private
Definition at line 153 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFinder().
float TpcPrototypeGenFitTrkFinder::_cluster_eval_tree_y private
Definition at line 154 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFinder().
float TpcPrototypeGenFitTrkFinder::_cluster_eval_tree_z private
Definition at line 155 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), reset_eval_variables(), and TpcPrototypeGenFitTrkFinder().
TrkrClusterContainer* TpcPrototypeGenFitTrkFinder::_clustermap private
Input Node pointers.
Definition at line 136 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by getChi2Ndf(), GetNodes(), and process_event().
bool TpcPrototypeGenFitTrkFinder::_do_eval private
Evaluation switch eval out
Definition at line 143 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by End(), InitRun(), is_do_eval(), process_event(), and set_do_eval().
bool TpcPrototypeGenFitTrkFinder::_do_evt_display private
Definition at line 160 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by End(), InitRun(), is_do_evt_display(), process_event(), and set_do_evt_display().
std::string TpcPrototypeGenFitTrkFinder::_eval_outname private
eval output filename
Definition at line 146 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by End(), get_eval_filename(), InitRun(), and set_eval_filename().
TTree* TpcPrototypeGenFitTrkFinder::_eval_tree private
Definition at line 148 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by End(), fill_eval_tree(), and init_eval_tree().
int TpcPrototypeGenFitTrkFinder::_event private
Event counter.
Definition at line 110 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by GetNodes(), process_event(), and TpcPrototypeGenFitTrkFinder().
PHGenFit::Fitter* TpcPrototypeGenFitTrkFinder::_fitter private
Definition at line 122 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by End(), getChi2Ndf(), InitRun(), and ~TpcPrototypeGenFitTrkFinder().
int TpcPrototypeGenFitTrkFinder::_primary_pid_guess private
Definition at line 130 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by get_primary_pid_guess(), getChi2Ndf(), and set_primary_pid_guess().
int TpcPrototypeGenFitTrkFinder::_tca_ntrack private
Definition at line 149 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by fill_eval_tree(), init_eval_tree(), and reset_eval_variables().
TClonesArray* TpcPrototypeGenFitTrkFinder::_tca_trackmap private
Definition at line 150 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by init_eval_tree(), and reset_eval_variables().
std::string TpcPrototypeGenFitTrkFinder::_track_fitting_alg_name private
KalmanFitterRefTrack, KalmanFitter, DafSimple, DafRef.
Definition at line 125 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by get_track_fitting_alg_name(), InitRun(), and set_track_fitting_alg_name().
SvtxTrackMap* TpcPrototypeGenFitTrkFinder::_trackmap private
Definition at line 137 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by CreateNodes(), fill_eval_tree(), GetNodes(), and process_event().
SvtxVertexMap* TpcPrototypeGenFitTrkFinder::_vertexmap private
Definition at line 139 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by CreateNodes(), and GetNodes().
unsigned int TpcPrototypeGenFitTrkFinder::maxTracklet private
Definition at line 129 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by process_event().
unsigned int TpcPrototypeGenFitTrkFinder::minLayer private
Definition at line 128 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by getChi2Ndf().
int TpcPrototypeGenFitTrkFinder::nLayer private
Definition at line 127 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by process_event().
double TpcPrototypeGenFitTrkFinder::rphiWindow private
Definition at line 131 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by process_event().
double TpcPrototypeGenFitTrkFinder::ZWindow private
Definition at line 132 of file TpcPrototypeGenFitTrkFinder.h.
Referenced by process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeGenFitTrkFinder.h
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeGenFitTrkFinder.cc