Analysis Software: analysis/blob/master/Prototype2/hcalLab/hcalUtil.h File Reference
hcalUtil.h File Reference
#include <list>
#include <algorithm>
#include <TROOT.h>
#include <TFile.h>
#include <TTree.h>
#include <TGMsgBox.h>
#include <TCanvas.h>
#include <TGraph.h>
#include <TString.h>
#include <TText.h>
#include <TApplication.h>
#include <TStyle.h>
#include <TSystem.h>
#include <TGClient.h>
#include <TGWindow.h>
#include <TH1.h>
#include <TH1F.h>
#include <TH1D.h>
#include <TProfile.h>
#include <TF1.h>
#include <TH2.h>
#include <TH3.h>
#include <TMath.h>
#include <TSpectrum.h>
#include "TVirtualFitter.h"
#include <TSystemDirectory.h>
#include <TSystemFile.h>
#include <hcalControls.h>
Classes
struct rootfile
struct prdffile
class hLabHelper
class hcalHelper
class hcal
class stack
class tower
class hcalTree
class tileHelper
struct tileHelper::eventtilesummary
struct tileHelper::runtilesummary
class tileLightYield
class tileTree
class hcalUtil
Functions
Double_t erfunc (Double_t *x, Double_t *par)
Double_t erf_g (Double_t *x, Double_t *par)
Double_t powerFun (Double_t *x, Double_t *par)
Double_t power_g (Double_t *x, Double_t *par)
Double_t ps (Double_t *adc, Double_t *par)
Double_t sipmPeaks (Double_t *x, Double_t *par)
Int_t sipmCalib (TString &hName, int mode=0)
Double_t AsymToX (Double_t asym)
Double_t signalShape (Double_t *x, Double_t *par)
Function Documentation
Double_t AsymToX (Double_t asym)
Definition at line 303 of file hcalUtil.C.
Referenced by tileHelper::collectTileSummary().
Double_t erf_g (Double_t * x, Double_t * par)
Definition at line 346 of file hcalUtil.C.
References g.
Double_t erfunc (Double_t * x, Double_t * par)
Definition at line 339 of file hcalUtil.C.
Referenced by hcalUtil::shapeFit().
Double_t power_g (Double_t * x, Double_t * par)
Definition at line 360 of file hcalUtil.C.
References g.
Referenced by hcalUtil::twrMipFit(), and hcalUtil::twrTimeFit().
Double_t powerFun (Double_t * x, Double_t * par)
Definition at line 352 of file hcalUtil.C.
Referenced by hcalUtil::twrMipFit(), and hcalUtil::twrTimeFit().
Double_t ps (Double_t * adc, Double_t * par)
Definition at line 102 of file hcalUtil.C.
References g, n, norm, sum(), and x.
Referenced by ReadLikelihoodD::GetMvaValue__().
Double_t signalShape (Double_t * x, Double_t * par)
Definition at line 70 of file evDisplay.C.
References pedestal(), and signal().
Referenced by tileHelper::eventtilesummary::eventtilesummary(), fitShape(), hLabHelper::fitShape(), G__hcalUtilDict__0_1608(), hLabHelper::hLabHelper(), hLabHelper::initPRDFRun(), stack::stack(), and tower::tower().
Int_t sipmCalib (TString & hName, int mode = 0)
Double_t sipmPeaks (Double_t * x, Double_t * par)
Definition at line 133 of file hcalUtil.C.
References calibMode(), calibPeaks(), norm, and spCalib().
Referenced by sipmCalib().