Analysis Software: coresoftware/blob/master/generators/sHijing/Hijing.cxx File Reference
Hijing.cxx File Reference
#include "HiParnt.h"
#include "RanSeed.h"
#include "HiMain1.h"
#include "HiMain2.h"
#include "HijJet1.h"
#include "HijJet2.h"
#include "HijJet4.h"
#include "HiStrng.h"
#include "HijCrdn.h"
#include <HepMC/GenEvent.h>
#include <HepMC/GenVertex.h>
#include <HepMC/GenParticle.h>
#include <HepMC/IO_AsciiParticles.h>
#include <HepMC/IO_GenEvent.h>
#include <CLHEP/Random/RandomEngine.h>
#include <CLHEP/Random/MTwistEngine.h>
#include <CLHEP/Random/RandFlat.h>
#include <CLHEP/Vector/LorentzVector.h>
#include <CLHEP/Geometry/Point3D.h>
#include <boost/property_tree/ptree.hpp>
#include <boost/property_tree/xml_parser.hpp>
#include <boost/foreach.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/algorithm/string.hpp>
#include <iostream>
#include <cstdlib>
#include <string>
#include <memory>
#include <vector>
#include <numeric>
#include <cmath>
#include <random>
#include <cfortran.h>
Macros
#define f2cFortran
#define gFortran
#define HIJING(FRAME, BMIN0, BMAX0) CCALLSFSUB3(HIJING,hijing,STRING,FLOAT,FLOAT,FRAME,BMIN0,BMAX0)
#define HIJSET(EFRM, FRAME, PROJ, TARG, IAP, IZP, IAT, IZT)
Typedefs
typedef HepGeom::Point3D< double > HepPoint3D
typedef
HepMC::GenEvent::particle_iterator piter
Functions
void hijfst_control (int, vector< string >, vector< float >, vector< int >, vector< float >, vector< float >, vector< float >)
float atl_ran (int *)
int fillEvent (HepMC::GenEvent *evt)
int main (int argc, char **argv)
Variables
CLHEP::HepRandomEngine * engine
HiParnt m_hiparnt
RanSeed m_ranseed
HiMain1 m_himain1
HiMain2 m_himain2
HijJet1 m_hijjet1
HijJet2 m_hijjet2
HijJet4 m_hijjet4
HiStrng m_histrng
HijCrdn m_hijcrdn
float efrm
std::string m_frame
std::string m_proj
std::string m_targ
int iap
int iat
int izp
int izt
int spec
double m_vertexOffsetCut = 1.0E-7
bool keepSpectators
Macro Definition Documentation
#define f2cFortran
Definition at line 44 of file Hijing.cxx.
#define gFortran
Definition at line 45 of file Hijing.cxx.
#define HIJING (FRAME, BMIN0, BMAX0) CCALLSFSUB3(HIJING,hijing,STRING,FLOAT,FLOAT,FRAME,BMIN0,BMAX0)
Definition at line 49 of file Hijing.cxx.
Referenced by main().
#define HIJSET (EFRM, FRAME, PROJ, TARG, IAP, IZP, IAT, IZT)
Value:
CCALLSFSUB8(HIJSET,hijset,FLOAT,STRING,STRING,STRING,INT,INT,INT,INT, \
              EFRM,FRAME,PROJ,TARG,IAP,IZP,IAT,IZT)
Definition at line 53 of file Hijing.cxx.
Referenced by main().
Typedef Documentation
typedef HepGeom::Point3D< double > HepPoint3D
Definition at line 72 of file Hijing.cxx.
typedef HepMC::GenEvent::particle_iterator piter
Definition at line 73 of file Hijing.cxx.
Function Documentation
float atl_ran (int *)
Definition at line 66 of file Hijing.cxx.
References engine.
Referenced by ar3jet(), aran9(), arorie(), attflv(), attrad(), hijcsc(), hijels(), hijflv(), hijfrg(), hijhrd(), hijing(), hijini(), hijsft(), hiptdi(), hirnd(), hirnd2(), and quench().
int fillEvent (HepMC::GenEvent * evt)
Definition at line 222 of file Hijing.cxx.
References efrm, HiParnt::hint1(), i, iap, HiParnt::ihnt2(), HiParnt::ihpr2(), HiMain2::katt(), keepSpectators, m_frame, m_hijcrdn, m_himain1, m_himain2, m_hiparnt, m_histrng, m_proj, m_targ, m_vertexOffsetCut, N, HiMain1::n0(), HiMain1::n01(), HiMain1::n10(), HiMain1::n11(), HiMain1::natt(), HiStrng::nfp(), HiStrng::nft(), HiMain1::np(), HiMain1::nt(), HiMain2::patt(), v1, HiMain2::vatt(), x, y, HijCrdn::yp(), HijCrdn::yt(), and z.
Referenced by main().
void hijfst_control (int , vector< string > , vector< float > , vector< int > , vector< float > , vector< float > , vector< float >)
Definition at line 47 of file hijfst.cc.
References algo_info_vec, algo_info::algorithm, algorithms, enablep, and i.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 105 of file Hijing.cxx.
References engine, fillEvent(), hijfst_control(), HIJING, HIJSET, HiParnt::hipr1(), HiMain1::ierrstat(), HiParnt::ihpr2(), it, N, v, and value.
Variable Documentation
float efrm
Definition at line 92 of file Hijing.cxx.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), fillEvent(), and hijset().
CLHEP::HepRandomEngine* engine
Definition at line 63 of file Hijing.cxx.
int iap
Definition at line 96 of file Hijing.cxx.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), fillEvent(), hijset(), and pyreco().
int iat
Definition at line 97 of file Hijing.cxx.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), and hijset().
int izp
Definition at line 98 of file Hijing.cxx.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), and hijset().
int izt
Definition at line 99 of file Hijing.cxx.
Referenced by __example_1.f__(), __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_5.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), BEmcProfile::GetTowerEnergy(), and hijset().
bool keepSpectators
Definition at line 102 of file Hijing.cxx.
Referenced by fillEvent().
std::string m_frame
Definition at line 93 of file Hijing.cxx.
Referenced by fillEvent().
HijCrdn m_hijcrdn
Definition at line 90 of file Hijing.cxx.
Referenced by fillEvent().
HijJet1 m_hijjet1
Definition at line 86 of file Hijing.cxx.
HijJet2 m_hijjet2
Definition at line 87 of file Hijing.cxx.
HijJet4 m_hijjet4
Definition at line 88 of file Hijing.cxx.
HiMain1 m_himain1
Definition at line 84 of file Hijing.cxx.
Referenced by fillEvent().
HiMain2 m_himain2
Definition at line 85 of file Hijing.cxx.
Referenced by fillEvent().
HiParnt m_hiparnt
Definition at line 78 of file Hijing.cxx.
Referenced by fillEvent().
HiStrng m_histrng
Definition at line 89 of file Hijing.cxx.
Referenced by fillEvent().
std::string m_proj
Definition at line 94 of file Hijing.cxx.
Referenced by fillEvent().
RanSeed m_ranseed
Definition at line 81 of file Hijing.cxx.
std::string m_targ
Definition at line 95 of file Hijing.cxx.
Referenced by fillEvent().
double m_vertexOffsetCut = 1.0E-7
Definition at line 101 of file Hijing.cxx.
Referenced by fillEvent().
int spec
Definition at line 100 of file Hijing.cxx.