Analysis Software: analysis/blob/master/Prototype4/EMCal/macros/DrawPrototype4EMCalTower.C File Reference
DrawPrototype4EMCalTower.C File Reference
#include <TFile.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Functions
void DrawPrototype4EMCalTower (const TString infile="data/beam_00001214.root_DSTReader.root", bool plot_all=false, const double momentum=-16)
void EMC_HodoScope_Calibration (TString Cherenkov_Choice)
void EMCDistribution_HCalCalibration ()
void EMCDistribution_ShowShape (TString CherenkovSignal="C2_Inner", const double che_cut=2000)
void EMCDistribution_SUM (TString sTOWER="Energy_Sum_col1_row2_5x5", TString CherenkovSignal="C2_Inner")
void EMCDistribution_SUM_RawADC (TString sTOWER="Energy_Sum_col1_row2_5x5", TString CherenkovSignal="C2_Inner")
void EMCDistribution_Fast (TString gain="CALIB", bool full_gain=false)
void EMCDistribution_PeakSample_Fast (bool full_gain=false)
void EMCDistribution (TString gain="CALIB", bool log_scale=false)
void EMCDistribution_ADC (bool log_scale=true)
Variables
TFile * _file0 = NULL
TTree * T = NULL
TString cuts = ""
double beam_momentum_selection = -16
Function Documentation
void DrawPrototype4EMCalTower (const TString infile = "data/beam_00001214.root_DSTReader.root", bool plot_all = false, const double momentum = -16)
Definition at line 30 of file DrawPrototype4EMCalTower.C.
References _file0, assert, beam_momentum_selection, cuts, EMC_HodoScope_Calibration(), EMCDistribution_ADC(), EMCDistribution_Fast(), EMCDistribution_HCalCalibration(), EMCDistribution_ShowShape(), EMCDistribution_SUM(), EMCDistribution_SUM_RawADC(), event_sel, n, SetOKStyle(), T, and t.
void EMC_HodoScope_Calibration (TString Cherenkov_Choice)
Definition at line 293 of file DrawPrototype4EMCalTower.C.
References _file0, beam_momentum_selection, cuts, SaveCanvas(), T, and t.
Referenced by DrawPrototype4EMCalTower().
void EMCDistribution (TString gain = "CALIB", bool log_scale = false)
Definition at line 1073 of file DrawPrototype4EMCalTower.C.
References _file0, cuts, gain, SVM_v1::h, SaveCanvas(), T, t, and QAHistManagerDef::useLogBins().
void EMCDistribution_ADC (bool log_scale = true)
Definition at line 1142 of file DrawPrototype4EMCalTower.C.
References _file0, cuts, gain, SVM_v1::h, SaveCanvas(), T, and t.
void EMCDistribution_Fast (TString gain = "CALIB", bool full_gain = false)
Definition at line 869 of file DrawPrototype4EMCalTower.C.
References _file0, cuts, fit(), gain, SVM_v1::h, h2, SaveCanvas(), T, and t.
void EMCDistribution_HCalCalibration ()
Definition at line 383 of file DrawPrototype4EMCalTower.C.
References _file0, assert, beam_momentum_selection, cuts, SaveCanvas(), T, and t.
void EMCDistribution_PeakSample_Fast (bool full_gain = false)
Definition at line 980 of file DrawPrototype4EMCalTower.C.
References _file0, cuts, fit(), gain, SVM_v1::h, h2, SaveCanvas(), T, t, and QAHistManagerDef::useLogBins().
void EMCDistribution_ShowShape (TString CherenkovSignal = "C2_Inner", const double che_cut = 2000)
Definition at line 484 of file DrawPrototype4EMCalTower.C.
References _file0, cuts, SaveCanvas(), T, and t.
void EMCDistribution_SUM (TString sTOWER = "Energy_Sum_col1_row2_5x5", TString CherenkovSignal = "C2_Inner")
Definition at line 581 of file DrawPrototype4EMCalTower.C.
References _file0, c2, cuts, SVM_v1::h, SaveCanvas(), T, and t.
void EMCDistribution_SUM_RawADC (TString sTOWER = "Energy_Sum_col1_row2_5x5", TString CherenkovSignal = "C2_Inner")
Definition at line 725 of file DrawPrototype4EMCalTower.C.
References _file0, c2, cuts, SVM_v1::h, SaveCanvas(), T, and t.
Variable Documentation
TFile* _file0 = NULL
Definition at line 25 of file DrawPrototype4EMCalTower.C.
double beam_momentum_selection = -16
Definition at line 28 of file DrawPrototype4EMCalTower.C.
TString cuts = ""
Definition at line 27 of file DrawPrototype4EMCalTower.C.
TTree* T = NULL
Definition at line 26 of file DrawPrototype4EMCalTower.C.