Analysis Software: PHG4TruthEventAction Class Reference
PHG4TruthEventAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthEventAction.h>
Public Member Functions
PHG4TruthEventAction ()
constructor
virtual ~PHG4TruthEventAction ()
destuctor
void BeginOfEventAction (const G4Event *)
void EndOfEventAction (const G4Event *)
int ResetEvent (PHCompositeNode *)
void SetInterfacePointers (PHCompositeNode *)
get relevant nodes from top node passed as argument
void AddTrackidToWritelist (const int trackid)
add id into track list
Public Member Functions inherited from PHG4EventAction
PHG4EventAction (void)
virtual ~PHG4EventAction ()
Private Member Functions
void SearchNode (PHCompositeNode *topNode)
void PruneShowers ()
void ProcessShowers ()
Private Attributes
std::set< int > m_WriteSet
set of track ids to be written out
PHG4TruthInfoContainer * m_TruthInfoContainer
pointer to truth information container
int m_LowerKeyPrevExist
int m_UpperKeyPrevExist
std::map< int, PHG4HitContainer * > m_HitContainerMap
Detailed Description
Definition at line 16 of file PHG4TruthEventAction.h.
Constructor & Destructor Documentation
PHG4TruthEventAction::PHG4TruthEventAction ()
constructor
Definition at line 40 of file PHG4TruthEventAction.cc.
virtual PHG4TruthEventAction::~PHG4TruthEventAction () inline virtual
destuctor
Definition at line 23 of file PHG4TruthEventAction.h.
Member Function Documentation
void PHG4TruthEventAction::AddTrackidToWritelist (const int trackid)
add id into track list
Definition at line 218 of file PHG4TruthEventAction.cc.
References m_WriteSet.
Referenced by PHG4TruthTrackingAction::PostUserTrackingAction().
void PHG4TruthEventAction::BeginOfEventAction (const G4Event * evt) virtual
Reimplemented from PHG4EventAction.
Definition at line 48 of file PHG4TruthEventAction.cc.
References PHG4TruthInfoContainer::GetMap(), m_LowerKeyPrevExist, m_TruthInfoContainer, and m_UpperKeyPrevExist.
void PHG4TruthEventAction::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from PHG4EventAction.
Definition at line 66 of file PHG4TruthEventAction.cc.
References PHG4TruthInfoContainer::AddEmbededTrkId(), PHG4TruthInfoContainer::AddEmbededVtxId(), PHG4TruthInfoContainer::delete_particle(), PHG4TruthInfoContainer::delete_vtx(), PHG4UserPrimaryParticleInformation::get_embed(), PHG4Particle::get_parent_id(), PHG4UserPrimaryParticleInformation::get_user_track_id(), PHG4UserPrimaryParticleInformation::get_user_vtx_id(), PHG4Particle::get_vtx_id(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtxRange(), m_LowerKeyPrevExist, m_TruthInfoContainer, m_UpperKeyPrevExist, m_WriteSet, ProcessShowers(), and PruneShowers().
void PHG4TruthEventAction::ProcessShowers () private
Definition at line 371 of file PHG4TruthEventAction.cc.
References PHG4Shower::begin_g4hit_id(), PHG4Shower::end_g4hit_id(), entry, PHG4HitContainer::findHit(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_light_yield(), PHG4Particle::get_pid(), PHG4Hit::get_trkid(), PHG4Particle::get_vtx_id(), PHG4Hit::get_x(), PHG4Hit::get_y(), PHG4Hit::get_z(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetShowerRange(), PHG4TruthInfoContainer::GetVtx(), i, j, m_HitContainerMap, m_TruthInfoContainer, PHWHERE, PHG4Shower::set_covar(), PHG4Shower::set_edep(), PHG4Shower::set_eh_ratio(), PHG4Shower::set_eion(), PHG4Shower::set_light_yield(), PHG4Shower::set_nhits(), PHG4Shower::set_x(), PHG4Shower::set_y(), PHG4Shower::set_z(), and X.
Referenced by EndOfEventAction().
void PHG4TruthEventAction::PruneShowers () private
Definition at line 277 of file PHG4TruthEventAction.cc.
References PHG4Shower::begin_g4hit_id(), PHG4Shower::begin_g4particle_id(), PHG4TruthInfoContainer::delete_shower(), PHG4Shower::empty_g4hit_id(), PHG4Shower::empty_g4particle_id(), PHG4Shower::end_g4hit_id(), PHG4Shower::end_g4particle_id(), PHG4Shower::get_edep(), PHG4TruthInfoContainer::GetParticle(), PHG4TruthInfoContainer::GetShowerRange(), m_HitContainerMap, m_TruthInfoContainer, PHG4Shower::remove_g4hit_volume(), and PHG4Shower::remove_g4particle_id().
Referenced by EndOfEventAction().
int PHG4TruthEventAction::ResetEvent (PHCompositeNode *) virtual
Reimplemented from PHG4EventAction.
Definition at line 271 of file PHG4TruthEventAction.cc.
References m_WriteSet.
Referenced by PHG4TruthSubsystem::ResetEvent().
void PHG4TruthEventAction::SearchNode (PHCompositeNode * topNode) private
Definition at line 238 of file PHG4TruthEventAction.cc.
References PHDataNode< T >::getData(), PHNodeIterator::ls(), and m_HitContainerMap.
Referenced by SetInterfacePointers().
void PHG4TruthEventAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
get relevant nodes from top node passed as argument
Reimplemented from PHG4EventAction.
Definition at line 224 of file PHG4TruthEventAction.cc.
References m_TruthInfoContainer, and SearchNode().
Referenced by PHG4TruthSubsystem::process_event().
Member Data Documentation
std::map<int, PHG4HitContainer*> PHG4TruthEventAction::m_HitContainerMap private
Definition at line 51 of file PHG4TruthEventAction.h.
Referenced by ProcessShowers(), PruneShowers(), and SearchNode().
int PHG4TruthEventAction::m_LowerKeyPrevExist private
Definition at line 48 of file PHG4TruthEventAction.h.
Referenced by BeginOfEventAction(), and EndOfEventAction().
PHG4TruthInfoContainer* PHG4TruthEventAction::m_TruthInfoContainer private
pointer to truth information container
Definition at line 46 of file PHG4TruthEventAction.h.
Referenced by BeginOfEventAction(), EndOfEventAction(), ProcessShowers(), PruneShowers(), and SetInterfacePointers().
int PHG4TruthEventAction::m_UpperKeyPrevExist private
Definition at line 49 of file PHG4TruthEventAction.h.
Referenced by BeginOfEventAction(), and EndOfEventAction().
std::set<int> PHG4TruthEventAction::m_WriteSet private
set of track ids to be written out
Definition at line 43 of file PHG4TruthEventAction.h.
Referenced by AddTrackidToWritelist(), EndOfEventAction(), and ResetEvent().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthEventAction.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthEventAction.cc