Analysis Software: Fun4AllDstInputManager Class Reference
Fun4AllDstInputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstInputManager.h>
Public Member Functions
Fun4AllDstInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
virtual ~Fun4AllDstInputManager ()
int fileopen (const std::string &filenam)
int fileclose ()
int run (const int nevents=0)
int GetSyncObject (SyncObject **mastersync)
int SyncIt (const SyncObject *mastersync)
int BranchSelect (const std::string &branch, const int iflag)
int setBranches ()
virtual int setSyncBranches (PHNodeIOManager *IManager)
void Print (const std::string &what="ALL") const
int PushBackEvents (const int i)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int skip (const int nevt)
virtual int NoSyncPushBackEvents (const int)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int ReadNextEventSyncObject ()
void ReadRunTTree (const int i)
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Private Attributes
int m_ReadRunTTree
int events_total
int events_thisfile
int events_skipped_during_sync
std::string fullfilename
std::string RunNode
std::map< const std::string, int > branchread
std::string syncbranchname
PHCompositeNode * dstNode
PHCompositeNode * runNode
PHCompositeNode * runNodeCopy
PHCompositeNode * runNodeSum
PHNodeIOManager * IManager
SyncObject * syncobject
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 15 of file Fun4AllDstInputManager.h.
Constructor & Destructor Documentation
Fun4AllDstInputManager::Fun4AllDstInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP")
Definition at line 31 of file Fun4AllDstInputManager.cc.
Fun4AllDstInputManager::~Fun4AllDstInputManager () virtual
Definition at line 48 of file Fun4AllDstInputManager.cc.
References IManager, and runNodeSum.
Member Function Documentation
int Fun4AllDstInputManager::BranchSelect (const std::string & branch, const int iflag) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 493 of file Fun4AllDstInputManager.cc.
References branchread, and Fun4AllBase::Verbosity().
int Fun4AllDstInputManager::fileclose () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 214 of file Fun4AllDstInputManager.cc.
References IManager, Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), and Fun4AllInputManager::UpdateFileList().
Referenced by fileopen(), ReadNextEventSyncObject(), run(), and SyncIt().
int Fun4AllDstInputManager::fileopen (const std::string & filenam) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 55 of file Fun4AllDstInputManager.cc.
References Fun4AllInputManager::AddToFileOpened(), dstNode, events_thisfile, fileclose(), Fun4AllInputManager::FileName(), PHNodeIterator::forEach(), fullfilename, RunHeader::get_RunNumber(), PHNode::getName(), Fun4AllServer::getNode(), IManager, Fun4AllInputManager::InputNode(), Fun4AllServer::instance(), PHNodeIOManager::isFunctional(), Fun4AllInputManager::IsOpen(), FROG::location(), m_ReadRunTTree, Fun4AllBase::Name(), PHReadOnly, PHRunTree, PHWHERE, PHNodeIOManager::print(), PHNodeIOManager::read(), PHNodeIntegrate::RunNode(), RunNode, runNode, runNodeCopy, runNodeSum, PHNodeIntegrate::RunSumNode(), setBranches(), Fun4AllInputManager::SetRunNumber(), Fun4AllInputManager::TopNodeName(), and Fun4AllBase::Verbosity().
int Fun4AllDstInputManager::GetSyncObject (SyncObject ** mastersync) virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllNoSyncDstInputManager.
Definition at line 228 of file Fun4AllDstInputManager.cc.
References assert, SyncObject::CloneMe(), Fun4AllReturnCodes::SYNC_OK, and syncobject.
void Fun4AllDstInputManager::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from Fun4AllInputManager.
Definition at line 569 of file Fun4AllDstInputManager.cc.
References branchread, IManager, Fun4AllBase::Name(), PHNodeIOManager::print(), and Fun4AllInputManager::Print().
int Fun4AllDstInputManager::PushBackEvents (const int i) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 605 of file Fun4AllDstInputManager.cc.
References PHIOManager::getEventNumber(), i, IManager, Fun4AllBase::Name(), PHWHERE, and PHIOManager::setEventNumber().
Referenced by Fun4AllNoSyncDstInputManager::NoSyncPushBackEvents(), and SyncIt().
int Fun4AllDstInputManager::ReadNextEventSyncObject () protected
Definition at line 399 of file Fun4AllDstInputManager.cc.
References dstNode, fileclose(), PHNodeIOManager::GetBranchMap(), PHIOManager::getEventNumber(), IManager, Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), PHWHERE, pos, PHNodeIOManager::read(), PHNodeIOManager::readSpecific(), PHIOManager::setEventNumber(), Fun4AllReturnCodes::SYNC_FAIL, syncbranchname, and Fun4AllBase::Verbosity().
Referenced by SyncIt().
void Fun4AllDstInputManager::ReadRunTTree (const int i) inline protected
Definition at line 33 of file Fun4AllDstInputManager.h.
References i, and m_ReadRunTTree.
Referenced by Fun4AllNoSyncDstInputManager::NoRunTTree().
int Fun4AllDstInputManager::run (const int nevents = 0) virtual
Reimplemented from Fun4AllInputManager.
Definition at line 156 of file Fun4AllDstInputManager.cc.
References dstNode, Fun4AllReturnCodes::EVENT_OK, events_thisfile, events_total, fileclose(), Fun4AllInputManager::FileListEmpty(), IManager, Fun4AllInputManager::IsOpen(), Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), PHNodeIOManager::read(), Fun4AllInputManager::RejectEvent(), syncobject, and Fun4AllBase::Verbosity().
int Fun4AllDstInputManager::setBranches () virtual
Reimplemented from Fun4AllInputManager.
Definition at line 530 of file Fun4AllDstInputManager.cc.
References branchread, IManager, Fun4AllBase::Name(), PHWHERE, PHNodeIOManager::selectObjectToRead(), setSyncBranches(), and Fun4AllBase::Verbosity().
Referenced by fileopen().
int Fun4AllDstInputManager::setSyncBranches (PHNodeIOManager * IManager) virtual
Reimplemented in Fun4AllNoSyncDstInputManager.
Definition at line 559 of file Fun4AllDstInputManager.cc.
References i, syncdefs::NUM_SYNC_VARS, PHNodeIOManager::selectObjectToRead(), and syncdefs::SYNCVARS.
Referenced by setBranches().
int Fun4AllDstInputManager::SyncIt (const SyncObject * mastersync) virtual
Reimplemented from Fun4AllInputManager.
Reimplemented in Fun4AllNoSyncDstInputManager.
Definition at line 249 of file Fun4AllDstInputManager.cc.
References SyncObject::Different(), dstNode, SyncObject::EventCounter(), SyncObject::EventNumber(), events_skipped_during_sync, fileclose(), SyncObject::identify(), IManager, Fun4AllBase::Name(), PHWHERE, PushBackEvents(), PHNodeIOManager::read(), ReadNextEventSyncObject(), SyncObject::RunNumber(), SyncObject::SegmentNumber(), Fun4AllReturnCodes::SYNC_FAIL, Fun4AllReturnCodes::SYNC_OK, syncobject, and Fun4AllBase::Verbosity().
Member Data Documentation
std::map<const std::string, int> Fun4AllDstInputManager::branchread private
Definition at line 42 of file Fun4AllDstInputManager.h.
Referenced by BranchSelect(), Print(), and setBranches().
PHCompositeNode* Fun4AllDstInputManager::dstNode private
Definition at line 44 of file Fun4AllDstInputManager.h.
Referenced by fileopen(), ReadNextEventSyncObject(), run(), and SyncIt().
int Fun4AllDstInputManager::events_skipped_during_sync private
Definition at line 39 of file Fun4AllDstInputManager.h.
Referenced by SyncIt().
int Fun4AllDstInputManager::events_thisfile private
Definition at line 38 of file Fun4AllDstInputManager.h.
Referenced by fileopen(), and run().
int Fun4AllDstInputManager::events_total private
Definition at line 37 of file Fun4AllDstInputManager.h.
Referenced by run().
std::string Fun4AllDstInputManager::fullfilename private
Definition at line 40 of file Fun4AllDstInputManager.h.
Referenced by fileopen().
PHNodeIOManager* Fun4AllDstInputManager::IManager private
Definition at line 48 of file Fun4AllDstInputManager.h.
Referenced by fileclose(), fileopen(), Print(), PushBackEvents(), ReadNextEventSyncObject(), run(), setBranches(), SyncIt(), and ~Fun4AllDstInputManager().
int Fun4AllDstInputManager::m_ReadRunTTree private
Definition at line 36 of file Fun4AllDstInputManager.h.
Referenced by fileopen(), and ReadRunTTree().
std::string Fun4AllDstInputManager::RunNode private
Definition at line 41 of file Fun4AllDstInputManager.h.
Referenced by fileopen().
PHCompositeNode* Fun4AllDstInputManager::runNode private
Definition at line 45 of file Fun4AllDstInputManager.h.
Referenced by fileopen().
PHCompositeNode* Fun4AllDstInputManager::runNodeCopy private
Definition at line 46 of file Fun4AllDstInputManager.h.
Referenced by fileopen().
PHCompositeNode* Fun4AllDstInputManager::runNodeSum private
Definition at line 47 of file Fun4AllDstInputManager.h.
Referenced by fileopen(), and ~Fun4AllDstInputManager().
std::string Fun4AllDstInputManager::syncbranchname private
Definition at line 43 of file Fun4AllDstInputManager.h.
Referenced by ReadNextEventSyncObject().
SyncObject* Fun4AllDstInputManager::syncobject private
Definition at line 49 of file Fun4AllDstInputManager.h.
Referenced by GetSyncObject(), run(), and SyncIt().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstInputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllDstInputManager.cc