Analysis Software: TrackProjectorPid Class Reference
TrackProjectorPid Class Reference
#include <analysis/blob/master/ParticleID/RICHAnalysis/TrackProjectorPid.h>
Public Types
enum PROJECTION_SURFACE { SPHERE, CYLINDER, PLANEXY }
Public Member Functions
TrackProjectorPid (PHCompositeNode *topNode)
bool get_projected_position (SvtxTrack *track, double arr_pos[3], const PROJECTION_SURFACE surf, const float surface_par)
bool get_projected_momentum (SvtxTrack *track, double arr_mom[3], const PROJECTION_SURFACE surf, const float surface_par)
SvtxTrackState * project_track (SvtxTrack *track, const PROJECTION_SURFACE surf, const float surface_par)
bool is_in_RICH (double momv[3])
Private Attributes
PHGenFit::Fitter * _fitter
Detailed Description
Class to project tracks to RICH volumes. Based on clas coresoftware/simulation/g4simulation/g4hough/PHG4GenFitTrackProjection
Definition at line 26 of file TrackProjectorPid.h.
Member Enumeration Documentation
enum TrackProjectorPid::PROJECTION_SURFACE
Enumerator:
SPHERE
CYLINDER
PLANEXY
Definition at line 30 of file TrackProjectorPid.h.
Constructor & Destructor Documentation
TrackProjectorPid::TrackProjectorPid (PHCompositeNode * topNode)
Definition at line 27 of file TrackProjectorPid.cc.
References _fitter, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), PHWHERE, and PHGenFit::Fitter::set_verbosity().
Member Function Documentation
bool TrackProjectorPid::get_projected_momentum (SvtxTrack * track, double arr_mom[3], const PROJECTION_SURFACE surf, const float surface_par)
Definition at line 70 of file TrackProjectorPid.cc.
References project_track().
Referenced by RICHEvaluator::process_event(), and RICHParticleID::process_event().
bool TrackProjectorPid::get_projected_position (SvtxTrack * track, double arr_pos[3], const PROJECTION_SURFACE surf, const float surface_par)
Definition at line 47 of file TrackProjectorPid.cc.
References project_track().
Referenced by RICHEvaluator::process_event(), and RICHParticleID::process_event().
bool TrackProjectorPid::is_in_RICH (double momv[3])
Definition at line 170 of file TrackProjectorPid.cc.
Referenced by RICHEvaluator::process_event(), and RICHParticleID::process_event().
SvtxTrackState * TrackProjectorPid::project_track (SvtxTrack * track, const PROJECTION_SURFACE surf, const float surface_par)
Definition at line 93 of file TrackProjectorPid.cc.
References CYLINDER, SvtxTrack::end_states(), SvtxTrackState::get_error(), SvtxTrackState::get_px(), SvtxTrackState::get_py(), SvtxTrackState::get_pz(), SvtxTrackState::get_x(), SvtxTrackState::get_y(), SvtxTrackState::get_z(), i, j, PLANEXY, pos, SvtxTrackState_v1::set_error(), SvtxTrackState_v1::set_px(), SvtxTrackState_v1::set_py(), SvtxTrackState_v1::set_pz(), SvtxTrackState_v1::set_x(), SvtxTrackState_v1::set_y(), SvtxTrackState_v1::set_z(), and SPHERE.
Referenced by get_projected_momentum(), get_projected_position(), and FastPid_RICH::process_event().
Member Data Documentation
PHGenFit::Fitter* TrackProjectorPid::_fitter private
Definition at line 44 of file TrackProjectorPid.h.
Referenced by TrackProjectorPid().
The documentation for this class was generated from the following files:
analysis/blob/master/ParticleID/RICHAnalysis/TrackProjectorPid.h
analysis/blob/master/ParticleID/RICHAnalysis/TrackProjectorPid.cc