Analysis Software: hcalHelper Class Reference
hcalHelper Class Reference
#include <analysis/blob/master/Prototype2/hcalLab/hcalUtil.h>
Public Member Functions
void setCTriggerOn (Bool_t ON=kTRUE)
void setCTriggerGRange (Int_t gain=1)
void setDisplayMode (Int_t mode=3)
void setRunKind (TString rK="beam")
Int_t evLoop (int run, int evToProcess=0, int fToProcess=1)
Int_t collectRaw ()
void updateCalibration ()
void hcalTrigger ()
void hcalPattern (Int_t nx, Int_t ny, Int_t run, Int_t mod=0)
void hcalImpact ()
void fitHCalSignal ()
void hcalDisplay ()
void dofixes ()
Int_t reject ()
Static Public Member Functions
static hcalHelper * getInstance ()
static void deleteInstance ()
Public Attributes
hcal * t1044
Double_t trThresholdBin
Double_t twrThreshold
Double_t stckSumThreshold
Int_t runnumber
Int_t eventseq
Int_t eventsread
Int_t displayMode
Int_t triggerOn
Int_t triggerGain
Int_t rejectRaw
Int_t eventReject
Int_t eventTrigger
Int_t channels
Int_t samples
Int_t parameters
Double_t uSum
Double_t cSum
Double_t YF
Double_t YU
Double_t YC
Double_t XU
Double_t XC
Double_t sumFU
Double_t sumFC
Double_t muxU
Double_t muxC
Double_t muxFU
Double_t muxFC
Int_t muxUCh
Int_t muxCCh
Int_t muxUFiber
Int_t muxCFiber
Int_t ** adc
Int_t * activeCh
TH2 * rdata
Protected Member Functions
hcalHelper ()
virtual ~hcalHelper ()
Static Protected Attributes
static hcalHelper * single = 0
Detailed Description
Definition at line 194 of file hcalUtil.h.
Constructor & Destructor Documentation
hcalHelper::hcalHelper () protected
Definition at line 3 of file hcalHelper.C.
References activeCh, ACTIVECHANNELS, adc, hcal::alive, CALSTACKS, channels, CHTOTAL, counters, detchannels, displayMode, EMC, emcCh, eventseq, eventsread, stack::gains, hLabHelper::getInstance(), hcalInnerCh, hcalOuterCh, HINNER, HODO, hodoCh, HOUTER, NSAMPLES, rdata, samples, hcal::setCalibration(), stack::stackId, hcal::stacks, t1044, stack::twrsInStack, and stack::updateMap().
Referenced by getInstance().
virtual hcalHelper::~hcalHelper () inline protected virtual
Definition at line 198 of file hcalUtil.h.
Member Function Documentation
Int_t hcalHelper::collectRaw ()
Definition at line 228 of file hcalHelper.C.
References adc, tower::adcChannel, CALSTACKS, stack::fitTime, stack::gains, max, ovrflow, tower::rawAmpl, tower::rawPed, tower::rawTime, rdata, rejectRaw, hcal::stacks, t1044, stack::towers, stack::twrsInStack, and undflow.
Referenced by evLoop().
static void hcalHelper::deleteInstance () inline static
Definition at line 202 of file hcalUtil.h.
References single.
void hcalHelper::dofixes ()
Definition at line 265 of file hcalHelper.C.
int hcalHelper::evLoop (int run, int evToProcess = 0, int fToProcess = 1)
Definition at line 75 of file hcalHelper.C.
References activeCh, ACTIVECHANNELS, adc, tower::adcChannel, hcal::alive, CALOR, CALSTACKS, hcal::clean(), collectRaw(), hcal::collectTrPrimitives(), displayMode, hcal::displayRaw(), hcal::displaySummary(), eventReject, eventseq, eventsread, eventTrigger, stack::gains, Event::getEvtSequence(), Event::getEvtType(), hLabHelper::getInstance(), hcalTree::getInstance(), Eventiterator::getNextEvent(), Event::getPacket(), hcal::getStackTiming(), tower::graph, it, Packet_hbd_fpgashort::iValue(), NSAMPLES, ovrflow, hLabHelper::prdfName, hLabHelper::runnumber, runnumber, tower::satFlag, Packet_hbd_fpgashort::setNumSamples(), stack::stackKind, hcal::stacks, t1044, stack::towers, triggerOn, stack::twrsInStack, undflow, and hcal::update().
Referenced by runHelper().
void hcalHelper::fitHCalSignal ()
Definition at line 260 of file hcalHelper.C.
static hcalHelper* hcalHelper::getInstance () inline static
Definition at line 201 of file hcalUtil.h.
References hcalHelper(), and single.
Referenced by tower::display(), stack::displayADCSum(), stack::displayEvent(), stack::displayStackSummary(), hcal::displaySummary(), stack::displayTowerSummary(), stack::getStackTime(), hcalTree::hcalTree(), runHelper(), and setRunKind().
void hcalHelper::hcalDisplay ()
Definition at line 262 of file hcalHelper.C.
void hcalHelper::hcalImpact ()
Definition at line 258 of file hcalHelper.C.
void hcalHelper::hcalPattern (Int_t nx, Int_t ny, Int_t run, Int_t mod = 0)
Definition at line 223 of file hcalHelper.C.
void hcalHelper::hcalTrigger ()
Int_t hcalHelper::reject ()
Definition at line 275 of file hcalHelper.C.
void hcalHelper::setCTriggerGRange (Int_t gain = 1)
Definition at line 209 of file hcalHelper.C.
References gain, TRGAINRANGE, and triggerGain.
void hcalHelper::setCTriggerOn (Bool_t ON = kTRUE)
Definition at line 202 of file hcalHelper.C.
References ON, and triggerOn.
void hcalHelper::setDisplayMode (Int_t mode = 3)
Definition at line 195 of file hcalHelper.C.
References displayMode.
void hcalHelper::setRunKind (TString rK = "beam")
Definition at line 56 of file hcalHelper.C.
References hcal::alive, EMC, hLabHelper::getInstance(), getInstance(), HODO, SCINT, hcal::stacks, and t1044.
Referenced by runHelper().
void hcalHelper::updateCalibration ()
Definition at line 216 of file hcalHelper.C.
Member Data Documentation
Int_t* hcalHelper::activeCh
Definition at line 246 of file hcalUtil.h.
Referenced by evLoop(), and hcalHelper().
Int_t** hcalHelper::adc
Definition at line 245 of file hcalUtil.h.
Referenced by collectRaw(), evLoop(), stack::getStackTime(), hcalHelper(), and hcalTree::hcalTree().
Int_t hcalHelper::channels
Definition at line 235 of file hcalUtil.h.
Referenced by hcalHelper().
Double_t hcalHelper::cSum
Definition at line 239 of file hcalUtil.h.
Int_t hcalHelper::displayMode
Definition at line 229 of file hcalUtil.h.
Referenced by evLoop(), hcalHelper(), and setDisplayMode().
Int_t hcalHelper::eventReject
Definition at line 233 of file hcalUtil.h.
Referenced by evLoop(), and hcalTree::hcalTree().
Int_t hcalHelper::eventseq
Definition at line 227 of file hcalUtil.h.
Referenced by evLoop(), hcalHelper(), and hcalTree::hcalTree().
Int_t hcalHelper::eventsread
Definition at line 228 of file hcalUtil.h.
Referenced by evLoop(), and hcalHelper().
Int_t hcalHelper::eventTrigger
Definition at line 234 of file hcalUtil.h.
Referenced by evLoop(), and hcalTree::hcalTree().
Double_t hcalHelper::muxC
Definition at line 242 of file hcalUtil.h.
Int_t hcalHelper::muxCCh
Definition at line 243 of file hcalUtil.h.
Int_t hcalHelper::muxCFiber
Definition at line 243 of file hcalUtil.h.
Double_t hcalHelper::muxFC
Definition at line 242 of file hcalUtil.h.
Double_t hcalHelper::muxFU
Definition at line 242 of file hcalUtil.h.
Double_t hcalHelper::muxU
Definition at line 242 of file hcalUtil.h.
Int_t hcalHelper::muxUCh
Definition at line 243 of file hcalUtil.h.
Int_t hcalHelper::muxUFiber
Definition at line 243 of file hcalUtil.h.
Int_t hcalHelper::parameters
Definition at line 237 of file hcalUtil.h.
TH2* hcalHelper::rdata
Definition at line 248 of file hcalUtil.h.
Referenced by collectRaw(), and hcalHelper().
Int_t hcalHelper::rejectRaw
Definition at line 232 of file hcalUtil.h.
Referenced by collectRaw().
Int_t hcalHelper::runnumber
Definition at line 226 of file hcalUtil.h.
Referenced by tower::display(), stack::displayADCSum(), stack::displayEvent(), stack::displayStackSummary(), hcal::displaySummary(), stack::displayTowerSummary(), evLoop(), and hcalTree::hcalTree().
Int_t hcalHelper::samples
Definition at line 236 of file hcalUtil.h.
Referenced by hcalHelper().
hcalHelper * hcalHelper::single = 0 static protected
Definition at line 197 of file hcalUtil.h.
Referenced by deleteInstance(), and getInstance().
Double_t hcalHelper::stckSumThreshold
Definition at line 224 of file hcalUtil.h.
Double_t hcalHelper::sumFC
Definition at line 241 of file hcalUtil.h.
Double_t hcalHelper::sumFU
Definition at line 241 of file hcalUtil.h.
hcal* hcalHelper::t1044
Definition at line 205 of file hcalUtil.h.
Referenced by collectRaw(), evLoop(), hcalHelper(), hcalTree::hcalTree(), and setRunKind().
Int_t hcalHelper::triggerGain
Definition at line 231 of file hcalUtil.h.
Referenced by setCTriggerGRange().
Int_t hcalHelper::triggerOn
Definition at line 230 of file hcalUtil.h.
Referenced by evLoop(), and setCTriggerOn().
Double_t hcalHelper::trThresholdBin
Definition at line 222 of file hcalUtil.h.
Double_t hcalHelper::twrThreshold
Definition at line 223 of file hcalUtil.h.
Double_t hcalHelper::uSum
Definition at line 239 of file hcalUtil.h.
Double_t hcalHelper::XC
Definition at line 240 of file hcalUtil.h.
Double_t hcalHelper::XU
Definition at line 240 of file hcalUtil.h.
Double_t hcalHelper::YC
Definition at line 240 of file hcalUtil.h.
Double_t hcalHelper::YF
Definition at line 240 of file hcalUtil.h.
Double_t hcalHelper::YU
Definition at line 240 of file hcalUtil.h.
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype2/hcalLab/hcalUtil.h
analysis/blob/master/Prototype2/hcalLab/hcalHelper.C
analysis/blob/master/Prototype2/hcalLab/hcalUtil.C