Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_FHCAL.C File Reference
G4_FHCAL.C File Reference
Functions
void FHCALInit ()
void FHCAL_Cells (int verbosity=0)
void FHCALSetup (PHG4Reco *g4Reco, const int absorberactive=0)
void FHCAL_Towers (int verbosity=0)
void FHCAL_Clusters (int verbosity=0)
void FHCAL_Eval (std::string outputfile, int verbosity=0)
Function Documentation
void FHCAL_Cells (int verbosity = 0)
Definition at line 8 of file G4_FHCAL.C.
References PHG4ForwardCalCellReco::Detector(), Fun4AllServer::instance(), and Fun4AllServer::registerSubsystem().
void FHCAL_Clusters (int verbosity = 0)
Definition at line 109 of file G4_FHCAL.C.
References RawClusterBuilderFwd::Detector(), Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), RawClusterBuilderFwd::set_threshold_energy(), verbosity, and Fun4AllBase::Verbosity().
void FHCAL_Eval (std::string outputfile, int verbosity = 0)
Definition at line 124 of file G4_FHCAL.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void FHCAL_Towers (int verbosity = 0)
Definition at line 49 of file G4_FHCAL.C.
References RawTowerCalibration::Detector(), RawTowerDigitizer::Detector(), RawTowerBuilderByHitIndex::Detector(), RawTowerBuilderByHitIndex::GeometryTableFile(), Fun4AllServer::instance(), RawTowerDigitizer::kNo_digitization, RawTowerCalibration::kSimple_linear_calibration, Fun4AllServer::registerSubsystem(), RawTowerCalibration::set_calib_algorithm(), RawTowerCalibration::set_calib_const_GeV_ADC(), RawTowerDigitizer::set_digi_algorithm(), RawTowerCalibration::set_pedstal_ADC(), RawTowerBuilderByHitIndex::set_sim_tower_node_prefix(), verbosity, and Fun4AllBase::Verbosity().
void FHCALInit ()
Definition at line 4 of file G4_FHCAL.C.
void FHCALSetup (PHG4Reco * g4Reco, const int absorberactive = 0)
Use dedicated FHCAL module
Definition at line 22 of file G4_FHCAL.C.
References Fun4AllServer::instance(), overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4ForwardHcalSubsystem::SetAbsorberActive(), and PHG4ForwardHcalSubsystem::SetTowerMappingFile().