Analysis Software: online_distribution/blob/master/newbasic/Event.h File Reference
Event.h File Reference
#include "packet.h"
#include <ctime>
Classes
class Event
Functions
const char * get_evt_mnemonic (const int)
Function Documentation
const char* get_evt_mnemonic (const int)
Definition at line 4 of file evt_mnemonic.cc.
Referenced by oncsEvent::identify(), A_Event::identify(), and A_Event::updateFramelist().