Analysis Software: online_distribution/blob/master/newbasic/formatError.h File Reference
formatError.h File Reference
#include "phenixOnline.h"
Macros
#define FORMAT_ERROR_SUBTYPE_FRAME 1
#define FORMAT_ERROR_SUBTYPE_PACKET 2
#define FORMAT_ERROR_SUBTYPE_USER 3
Typedefs
typedef UINT ERRORVALUE
Enumerations
enum formatErrorCodes {
FORAMT_ERR_SUCCESS = 0, FORMAT_ERR_INVALID_HEADER, FORMAT_ERR_INVALID_HDRVERSION, FORMAT_ERR_INVALID_PACKET_HDRVERSION,
FORMAT_ERR_INVALID_DATA, FORMAT_ERR_HISTORY_OVERFLOW, FORMAT_ERR_ERROR_OVERFLOW, FORMAT_ERR_BUFFER_OVERFLOW,
FORMAT_ERR_INVALID_MODIFY, FORMAT_ERR_INVALID_FRAMEMARK, FORMAT_ERR_LENGTH_OVERFLOW, FORMAT_ERR_INVALID_HDRLENGTH,
FORMAT_ERR_INVALID_APPEND, FORMAT_ERR_WRONG_STRUCTURE, FORMAT_ERR_HDR_INCONSISTENCY, FORMAT_ERR_DATA_INCONSISTENCY,
FORMAT_ERR_NONEMPTY_PACKET
}
Functions
void setFrameError (ERRORVALUE, PHDWORD *, PHDWORD)
void setPacketError (ERRORVALUE, PHDWORD *, PHDWORD)
void setUserError (ERRORVALUE, PHDWORD)
void setFrameSuccess ()
void setPacketSuccess ()
ERRORVALUE formatGetError (UINT *, PHDWORD **, PHDWORD *)
ERRORVALUE formatGetErrorNumber ()
PHDWORD * formatGetErrorPointer ()
PHDWORD formatGetErrorAdditionalData ()
Variables
CONSTANT UINT errorTypeFrame = FORMAT_ERROR_SUBTYPE_FRAME
CONSTANT UINT errorTypePacket = FORMAT_ERROR_SUBTYPE_PACKET
CONSTANT UINT errorTypeUser = FORMAT_ERROR_SUBTYPE_USER
Macro Definition Documentation
#define FORMAT_ERROR_SUBTYPE_FRAME 1
Definition at line 39 of file formatError.h.
#define FORMAT_ERROR_SUBTYPE_PACKET 2
Definition at line 40 of file formatError.h.
#define FORMAT_ERROR_SUBTYPE_USER 3
Definition at line 41 of file formatError.h.
Typedef Documentation
typedef UINT ERRORVALUE
Definition at line 37 of file formatError.h.
Enumeration Type Documentation
enum formatErrorCodes
Enumerator:
FORAMT_ERR_SUCCESS
FORMAT_ERR_INVALID_HEADER
FORMAT_ERR_INVALID_HDRVERSION
FORMAT_ERR_INVALID_PACKET_HDRVERSION
FORMAT_ERR_INVALID_DATA
FORMAT_ERR_HISTORY_OVERFLOW
FORMAT_ERR_ERROR_OVERFLOW
FORMAT_ERR_BUFFER_OVERFLOW
FORMAT_ERR_INVALID_MODIFY
FORMAT_ERR_INVALID_FRAMEMARK
FORMAT_ERR_LENGTH_OVERFLOW
FORMAT_ERR_INVALID_HDRLENGTH
FORMAT_ERR_INVALID_APPEND
FORMAT_ERR_WRONG_STRUCTURE
FORMAT_ERR_HDR_INCONSISTENCY
FORMAT_ERR_DATA_INCONSISTENCY
FORMAT_ERR_NONEMPTY_PACKET
Definition at line 71 of file formatError.h.
Function Documentation
ERRORVALUE formatGetError (UINT * , PHDWORD ** , PHDWORD *)
Definition at line 93 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, formatError::frameOrPacket_ptr, and formatError::subType.
PHDWORD formatGetErrorAdditionalData ()
Definition at line 114 of file formatError.C.
References formatError::additionalData, and formatError::errorNumber.
ERRORVALUE formatGetErrorNumber ()
Definition at line 86 of file formatError.C.
References formatError::errorNumber.
PHDWORD* formatGetErrorPointer ()
Definition at line 104 of file formatError.C.
References formatError::errorNumber, and formatError::frameOrPacket_ptr.
void setFrameError (ERRORVALUE , PHDWORD * , PHDWORD)
Definition at line 43 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, errorTypeFrame, formatError::frameOrPacket_ptr, and formatError::subType.
Referenced by adjustFrameErrorLengthV1(), adjustFrameHistoryLengthV1(), adjustFrameLength(), checkFrameHdrVersion(), getFrameDataLengthV1(), getFrameHdrLength(), getFrameHdrVersion(), getFrameLength(), and validFrameHdrV1().
void setFrameSuccess ()
Definition at line 72 of file formatError.C.
References formatError::errorNumber.
Referenced by adjustFrameErrorLengthV1(), adjustFrameHistoryLengthV1(), checkFrameHdrVersion(), findFrameEnd(), getFrameDataLengthV1(), and validFrameHdrV1().
void setPacketError (ERRORVALUE , PHDWORD * , PHDWORD)
Definition at line 53 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, errorTypePacket, formatError::frameOrPacket_ptr, and formatError::subType.
Referenced by extendPacketLength(), findPacketEnd(), getPacketHdrVersion(), getUnstructPacketDataLengthWords(), removePacketPadding(), reservePacketDebugData(), setPacketHdrLength(), setPacketHdrVersion(), setPacketLength(), storePacketHits(), and validPacketV1Hdr().
void setPacketSuccess ()
Definition at line 79 of file formatError.C.
References formatError::errorNumber.
Referenced by appendEmptyFramePacket(), findPacketEnd(), and validPacketV1Hdr().
void setUserError (ERRORVALUE , PHDWORD)
Definition at line 63 of file formatError.C.
References formatError::additionalData, formatError::errorNumber, errorTypeUser, and formatError::subType.
Referenced by appendEmptyFramePacket(), orFrameStatusV1(), orPacketV1Status(), and startUnstructDataWrite().
Variable Documentation
CONSTANT UINT errorTypeFrame = FORMAT_ERROR_SUBTYPE_FRAME
Definition at line 43 of file formatError.h.
Referenced by setFrameError().
CONSTANT UINT errorTypePacket = FORMAT_ERROR_SUBTYPE_PACKET
Definition at line 44 of file formatError.h.
Referenced by setPacketError().
CONSTANT UINT errorTypeUser = FORMAT_ERROR_SUBTYPE_USER
Definition at line 45 of file formatError.h.
Referenced by setUserError().