Analysis Software: PHTrackPropagating Class Reference
PHTrackPropagating Class Reference abstract
Base class for track seeding.
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackPropagating.h>
Public Member Functions
PHTrackPropagating (const std::string &name="PHTrackPropagating")
virtual ~PHTrackPropagating ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int Setup (PHCompositeNode *topNode)
virtual int Process ()=0
virtual int End ()=0
void set_track_map_name (const std::string &map_name)
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Base class for track seeding.
Definition at line 28 of file PHTrackPropagating.h.
Constructor & Destructor Documentation
PHTrackPropagating::PHTrackPropagating (const std::string & name = "PHTrackPropagating")
Definition at line 20 of file PHTrackPropagating.cc.
virtual PHTrackPropagating::~PHTrackPropagating () inline virtual
Definition at line 32 of file PHTrackPropagating.h.
Member Function Documentation
int PHTrackPropagating::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 40 of file PHTrackPropagating.cc.
References End(), and Fun4AllReturnCodes::EVENT_OK.
virtual int PHTrackPropagating::End () protected pure virtual
Implemented in PHGenFitTrkProp.
Referenced by End().
int PHTrackPropagating::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 54 of file PHTrackPropagating.cc.
References _assoc_container, _cluster_map, _track_map, _vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHTrackPropagating::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 30 of file PHTrackPropagating.cc.
References Setup().
virtual int PHTrackPropagating::Process () protected pure virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implemented in PHGenFitTrkProp.
Referenced by process_event().
int PHTrackPropagating::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 35 of file PHTrackPropagating.cc.
References Process().
void PHTrackPropagating::set_track_map_name (const std::string & map_name) inline protected
Definition at line 50 of file PHTrackPropagating.h.
References _track_map_name.
int PHTrackPropagating::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented in PHGenFitTrkProp.
Definition at line 46 of file PHTrackPropagating.cc.
References Fun4AllReturnCodes::EVENT_OK, and GetNodes().
Referenced by InitRun(), and PHGenFitTrkProp::Setup().
Member Data Documentation
AssocInfoContainer* PHTrackPropagating::_assoc_container protected
Definition at line 56 of file PHTrackPropagating.h.
Referenced by PHGenFitTrkProp::check_track_exists(), GetNodes(), and PHGenFitTrkProp::OutputPHGenFitTrack().
TrkrClusterContainer* PHTrackPropagating::_cluster_map protected
Definition at line 53 of file PHTrackPropagating.h.
Referenced by PHGenFitTrkProp::BuildLayerZPhiHitMap(), PHGenFitTrkProp::check_track_exists(), GetNodes(), PHGenFitTrkProp::SvtxTrackToPHGenFitTracks(), and PHGenFitTrkProp::TrackPropPatRec().
SvtxTrackMap* PHTrackPropagating::_track_map protected
Definition at line 55 of file PHTrackPropagating.h.
Referenced by GetNodes(), PHGenFitTrkProp::KalmanTrkProp(), and PHGenFitTrkProp::OutputPHGenFitTrack().
std::string PHTrackPropagating::_track_map_name protected
Definition at line 58 of file PHTrackPropagating.h.
Referenced by set_track_map_name().
SvtxVertexMap* PHTrackPropagating::_vertex_map protected
Definition at line 54 of file PHTrackPropagating.h.
Referenced by GetNodes(), and PHGenFitTrkProp::Process().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackPropagating.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackPropagating.cc