Analysis Software: BbcVertexv1 Class Reference
BbcVertexv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexv1.h>
Public Member Functions
BbcVertexv1 ()
virtual ~BbcVertexv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
float get_t () const
void set_t (float t)
float get_t_err () const
void set_t_err (float t_err)
float get_z () const
void set_z (float z)
float get_z_err () const
void set_z_err (float z_err)
Public Member Functions inherited from BbcVertex
virtual ~BbcVertex ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (BbcVertexv1, 1)
Private Attributes
unsigned int _id
float _t
float _t_err
float _z
float _z_err
Additional Inherited Members
Protected Member Functions inherited from BbcVertex
BbcVertex ()
Detailed Description
Definition at line 8 of file BbcVertexv1.h.
Constructor & Destructor Documentation
BbcVertexv1::BbcVertexv1 ()
Definition at line 7 of file BbcVertexv1.cc.
Referenced by CloneMe(), and Reset().
BbcVertexv1::~BbcVertexv1 () virtual
Definition at line 16 of file BbcVertexv1.cc.
Member Function Documentation
BbcVertexv1::ClassDef (BbcVertexv1 , 1) private
PHObject* BbcVertexv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from BbcVertex.
Definition at line 19 of file BbcVertexv1.h.
References BbcVertexv1().
unsigned int BbcVertexv1::get_id () const inline virtual
Reimplemented from BbcVertex.
Definition at line 23 of file BbcVertexv1.h.
References _id.
Referenced by identify().
float BbcVertexv1::get_t () const inline virtual
Reimplemented from BbcVertex.
Definition at line 26 of file BbcVertexv1.h.
References _t.
Referenced by identify().
float BbcVertexv1::get_t_err () const inline virtual
Reimplemented from BbcVertex.
Definition at line 29 of file BbcVertexv1.h.
References _t_err.
Referenced by identify().
float BbcVertexv1::get_z () const inline virtual
Reimplemented from BbcVertex.
Definition at line 32 of file BbcVertexv1.h.
References _z.
Referenced by identify().
float BbcVertexv1::get_z_err () const inline virtual
Reimplemented from BbcVertex.
Definition at line 35 of file BbcVertexv1.h.
References _z_err.
Referenced by identify().
void BbcVertexv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from BbcVertex.
Definition at line 18 of file BbcVertexv1.cc.
References get_id(), get_t(), get_t_err(), get_z(), and get_z_err().
int BbcVertexv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from BbcVertex.
Definition at line 29 of file BbcVertexv1.cc.
References _id, _t, _t_err, _z, and _z_err.
void BbcVertexv1::Reset () inline virtual
Clear Event.
Reimplemented from BbcVertex.
Definition at line 17 of file BbcVertexv1.h.
References BbcVertexv1().
void BbcVertexv1::set_id (unsigned int id) inline virtual
Reimplemented from BbcVertex.
Definition at line 24 of file BbcVertexv1.h.
References _id.
void BbcVertexv1::set_t (float t) inline virtual
Reimplemented from BbcVertex.
Definition at line 27 of file BbcVertexv1.h.
References _t, and t.
void BbcVertexv1::set_t_err (float t_err) inline virtual
Reimplemented from BbcVertex.
Definition at line 30 of file BbcVertexv1.h.
References _t_err.
void BbcVertexv1::set_z (float z) inline virtual
Reimplemented from BbcVertex.
Definition at line 33 of file BbcVertexv1.h.
References _z, and z.
void BbcVertexv1::set_z_err (float z_err) inline virtual
Reimplemented from BbcVertex.
Definition at line 36 of file BbcVertexv1.h.
References _z_err.
Member Data Documentation
unsigned int BbcVertexv1::_id private
Definition at line 39 of file BbcVertexv1.h.
Referenced by get_id(), isValid(), and set_id().
float BbcVertexv1::_t private
Definition at line 40 of file BbcVertexv1.h.
Referenced by get_t(), isValid(), and set_t().
float BbcVertexv1::_t_err private
Definition at line 41 of file BbcVertexv1.h.
Referenced by get_t_err(), isValid(), and set_t_err().
float BbcVertexv1::_z private
Definition at line 42 of file BbcVertexv1.h.
Referenced by get_z(), isValid(), and set_z().
float BbcVertexv1::_z_err private
Definition at line 43 of file BbcVertexv1.h.
Referenced by get_z_err(), isValid(), and set_z_err().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexv1.h
coresoftware/blob/master/simulation/g4simulation/g4bbc/BbcVertexv1.cc