Analysis Software: PHG4CylinderCellGeom Class Reference
PHG4CylinderCellGeom Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeom.h>
Public Member Functions
PHG4CylinderCellGeom ()
virtual ~PHG4CylinderCellGeom ()
void identify (std::ostream &os=std::cout) const
int get_layer () const
double get_radius () const
double get_thickness () const
int get_binning () const
int get_zbins () const
int get_phibins () const
double get_zmin () const
double get_phistep () const
double get_phimin () const
double get_zstep () const
int get_etabins () const
double get_etastep () const
double get_etamin () const
virtual std::pair< double, double > get_zbounds (const int ibin) const
virtual std::pair< double, double > get_phibounds (const int ibin) const
virtual std::pair< double, double > get_etabounds (const int ibin) const
virtual double get_etacenter (const int ibin) const
virtual double get_zcenter (const int ibin) const
virtual double get_phicenter (const int ibin) const
virtual int get_etabin (const double eta) const
virtual int get_zbin (const double z) const
virtual int get_phibin (const double phi) const
void set_layer (const int i)
void set_binning (const int i)
void set_radius (const double r)
void set_thickness (const double t)
void set_zbins (const int i)
void set_zmin (const double z)
void set_zstep (const double z)
void set_phibins (const int i)
void set_phistep (const double phi)
void set_phimin (const double phi)
void set_etabins (const int i)
void set_etamin (const double z)
void set_etastep (const double z)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
void check_binning_method (const int i) const
void check_binning_method_eta (const std::string &src="") const
void check_binning_method_phi (const std::string &src="") const
std::string methodname (const int i) const
Protected Attributes
int layer
int binning
double radius
int nzbins
double zmin
double zstep
int nphibins
double phimin
double phistep
double thickness
Detailed Description
Definition at line 12 of file PHG4CylinderCellGeom.h.
Constructor & Destructor Documentation
PHG4CylinderCellGeom::PHG4CylinderCellGeom ()
Definition at line 10 of file PHG4CylinderCellGeom.cc.
virtual PHG4CylinderCellGeom::~PHG4CylinderCellGeom () inline virtual
Definition at line 17 of file PHG4CylinderCellGeom.h.
Member Function Documentation
void PHG4CylinderCellGeom::check_binning_method (const int i) const protected
Definition at line 332 of file PHG4CylinderCellGeom.cc.
References binning, and methodname().
Referenced by get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), get_zmin(), get_zstep(), set_zbins(), set_zmin(), and set_zstep().
void PHG4CylinderCellGeom::check_binning_method_eta (const std::string & src = "") const protected
Definition at line 345 of file PHG4CylinderCellGeom.cc.
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), and PHG4CylinderCellDefs::spacalbinning.
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_etamin(), get_etastep(), set_etabins(), set_etamin(), and set_etastep().
void PHG4CylinderCellGeom::check_binning_method_phi (const std::string & src = "") const protected
Definition at line 365 of file PHG4CylinderCellGeom.cc.
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, methodname(), PHG4CylinderCellDefs::sizebinning, and PHG4CylinderCellDefs::spacalbinning.
Referenced by get_phibin(), get_phibins(), get_phicenter(), get_phimin(), get_phistep(), set_phibins(), set_phimin(), and set_phistep().
int PHG4CylinderCellGeom::get_binning () const inline
Definition at line 23 of file PHG4CylinderCellGeom.h.
References binning.
Referenced by RawTowerBuilder::CreateNodes().
int PHG4CylinderCellGeom::get_etabin (const double eta) const virtual
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 246 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), nzbins, zmin, and zstep.
Referenced by PHG4CylinderCellReco::process_event().
int PHG4CylinderCellGeom::get_etabins () const
Definition at line 110 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and nzbins.
Referenced by RawTowerBuilder::CreateNodes().
pair< double, double > PHG4CylinderCellGeom::get_etabounds (const int ibin) const virtual
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 203 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), nzbins, PHWHERE, zmin, and zstep.
Referenced by RawTowerBuilder::CreateNodes().
double PHG4CylinderCellGeom::get_etacenter (const int ibin) const virtual
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 283 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), nzbins, PHWHERE, zmin, and zstep.
Referenced by PHG4CylinderCellReco::process_event(), and G4CellNtuple::process_event().
double PHG4CylinderCellGeom::get_etamin () const
Definition at line 123 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and zmin.
Referenced by RawTowerBuilder::CreateNodes().
double PHG4CylinderCellGeom::get_etastep () const
Definition at line 117 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), and zstep.
Referenced by RawTowerBuilder::CreateNodes(), and PHG4CylinderCellReco::process_event().
int PHG4CylinderCellGeom::get_layer () const inline
Definition at line 20 of file PHG4CylinderCellGeom.h.
References layer.
Referenced by PHG4CylinderCellGeomContainer::AddLayerCellGeom(), RawTowerBuilder::CreateNodes(), PHInitZVertexing::initialize_geometry(), PHPatternReco::initialize_geometry(), PHHoughSeeding::InitializeGeometry(), PHGenFitTrkProp::InitializeGeometry(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_zbins(), and PHG4TpcPadPlaneReadout::populate_zigzag_phibins().
int PHG4CylinderCellGeom::get_phibin (const double phi) const virtual
Definition at line 258 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), M_PI, nphibins, phi, phimin, and phistep.
Referenced by PHG4TpcPadPlaneReadout::populate_rectangular_phibins(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), and PHG4CylinderCellReco::process_event().
int PHG4CylinderCellGeom::get_phibins () const
Definition at line 68 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and nphibins.
Referenced by RawTowerBuilder::CreateNodes(), PHG4TpcDigitizer::DigitizeCylinderCells(), TpcPrototypeUnpacker::exportDSTCluster(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_rectangular_phibins(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), TPCIntegratedCharge::process_event(), TPCDataStreamEmulator::process_event(), and TPCMLDataInterface::process_event().
pair< double, double > PHG4CylinderCellGeom::get_phibounds (const int ibin) const virtual
Definition at line 219 of file PHG4CylinderCellGeom.cc.
References nphibins, phimin, phistep, and PHWHERE.
Referenced by RawTowerBuilder::CreateNodes().
double PHG4CylinderCellGeom::get_phicenter (const int ibin) const virtual
Definition at line 296 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), nphibins, phimin, phistep, and PHWHERE.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), SvtxEvaluator::fillOutputNtuples(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_rectangular_phibins(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), PHG4CylinderCellReco::process_event(), and G4CellNtuple::process_event().
double PHG4CylinderCellGeom::get_phimin () const
Definition at line 82 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and phimin.
Referenced by RawTowerBuilder::CreateNodes().
double PHG4CylinderCellGeom::get_phistep () const
Definition at line 75 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), and phistep.
Referenced by RawTowerBuilder::CreateNodes(), PHG4TpcPadPlaneReadout::populate_rectangular_phibins(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), and PHG4CylinderCellReco::process_event().
double PHG4CylinderCellGeom::get_radius () const inline
Definition at line 21 of file PHG4CylinderCellGeom.h.
References radius.
Referenced by RawTowerBuilder::CreateNodes(), TpcPrototypeUnpacker::exportDSTCluster(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHInitZVertexing::initialize_geometry(), PHPatternReco::initialize_geometry(), PHHoughSeeding::InitializeGeometry(), PHGenFitTrkProp::InitializeGeometry(), PHG4TpcPadPlaneReadout::populate_rectangular_phibins(), PHG4TpcPadPlaneReadout::populate_zigzag_phibins(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), TPCDataStreamEmulator::process_event(), and TPCMLDataInterface::process_event().
double PHG4CylinderCellGeom::get_thickness () const inline
Definition at line 22 of file PHG4CylinderCellGeom.h.
References thickness.
Referenced by RawTowerBuilder::CreateNodes(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), PHPatternReco::initialize_geometry(), PHInitZVertexing::initialize_geometry(), PHHoughSeeding::InitializeGeometry(), and PHGenFitTrkProp::InitializeGeometry().
int PHG4CylinderCellGeom::get_zbin (const double z) const virtual
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 233 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by PHG4TpcPadPlaneReadout::populate_zbins(), and PHG4CylinderCellReco::process_event().
int PHG4CylinderCellGeom::get_zbins () const
Definition at line 40 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, and PHG4CylinderCellDefs::sizebinning.
Referenced by RawTowerBuilder::CreateNodes(), PHG4TpcDigitizer::DigitizeCylinderCells(), TpcPrototypeUnpacker::exportDSTCluster(), TPCDataStreamEmulator::InitRun(), TPCMLDataInterface::InitRun(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_zbins(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), TPCIntegratedCharge::process_event(), TPCDataStreamEmulator::process_event(), and TPCMLDataInterface::process_event().
pair< double, double > PHG4CylinderCellGeom::get_zbounds (const int ibin) const virtual
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 189 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, PHWHERE, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by RawTowerBuilder::CreateNodes().
double PHG4CylinderCellGeom::get_zcenter (const int ibin) const virtual
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 271 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), nzbins, PHWHERE, PHG4CylinderCellDefs::sizebinning, zmin, and zstep.
Referenced by RawTowerBuilder::CreateNodes(), TpcPrototypeUnpacker::exportDSTCluster(), SvtxEvaluator::fillOutputNtuples(), PHG4TpcPadPlaneReadout::MapToPadPlane(), PHG4TpcPadPlaneReadout::populate_zbins(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), PHG4CylinderCellReco::process_event(), TPCDataStreamEmulator::process_event(), and TPCMLDataInterface::process_event().
double PHG4CylinderCellGeom::get_zmin () const
Definition at line 47 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zmin.
double PHG4CylinderCellGeom::get_zstep () const
Definition at line 54 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, and zstep.
Referenced by PHG4TpcPadPlaneReadout::populate_zbins(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), and PHG4CylinderCellReco::process_event().
void PHG4CylinderCellGeom::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in PHG4CylinderCellGeom_Spacalv1.
Definition at line 151 of file PHG4CylinderCellGeom.cc.
References binning, PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, layer, nphibins, nzbins, phimin, phistep, radius, PHG4CylinderCellDefs::sizebinning, PHG4CylinderCellDefs::spacalbinning, thickness, zmin, and zstep.
Referenced by RawTowerBuilder::CreateNodes(), PHG4CylinderCellGeom_Spacalv1::identify(), PHInitZVertexing::initialize_geometry(), and PHG4CylinderCellReco::InitRun().
string PHG4CylinderCellGeom::methodname (const int i) const protected
Definition at line 309 of file PHG4CylinderCellGeom.cc.
References PHG4CylinderCellDefs::etaphibinning, PHG4CylinderCellDefs::etaslatbinning, PHG4CylinderCellDefs::sizebinning, and PHG4CylinderCellDefs::spacalbinning.
Referenced by check_binning_method(), check_binning_method_eta(), and check_binning_method_phi().
void PHG4CylinderCellGeom::set_binning (const int i) inline
Definition at line 46 of file PHG4CylinderCellGeom.h.
References binning, and i.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_etabins (const int i)
Definition at line 144 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), i, and nzbins.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_etamin (const double z)
Definition at line 130 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), z, and zmin.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_etastep (const double z)
Definition at line 137 of file PHG4CylinderCellGeom.cc.
References check_binning_method_eta(), z, and zstep.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_layer (const int i) inline
Definition at line 45 of file PHG4CylinderCellGeom.h.
References i, and layer.
Referenced by PHG4CylinderCellGeomContainer::AddLayerCellGeom(), PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_phibins (const int i)
Definition at line 89 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), i, and nphibins.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_phimin (const double phi)
Definition at line 103 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), phimin, and r.
Referenced by PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_phistep (const double phi)
Definition at line 96 of file PHG4CylinderCellGeom.cc.
References check_binning_method_phi(), phistep, and r.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_radius (const double r) inline
Definition at line 47 of file PHG4CylinderCellGeom.h.
References r, and radius.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_thickness (const double t) inline
Definition at line 48 of file PHG4CylinderCellGeom.h.
References t, and thickness.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
void PHG4CylinderCellGeom::set_zbins (const int i)
Definition at line 26 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), i, nzbins, and PHG4CylinderCellDefs::sizebinning.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), and PHG4CylinderCellReco::InitRun().
void PHG4CylinderCellGeom::set_zmin (const double z)
Definition at line 33 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, z, and zmin.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), and PHG4CylinderCellReco::InitRun().
void PHG4CylinderCellGeom::set_zstep (const double z)
Definition at line 61 of file PHG4CylinderCellGeom.cc.
References check_binning_method(), PHG4CylinderCellDefs::sizebinning, z, and zstep.
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), and PHG4CylinderCellReco::InitRun().
Member Data Documentation
int PHG4CylinderCellGeom::binning protected
Definition at line 65 of file PHG4CylinderCellGeom.h.
Referenced by check_binning_method(), check_binning_method_eta(), check_binning_method_phi(), get_binning(), identify(), and set_binning().
int PHG4CylinderCellGeom::layer protected
Definition at line 64 of file PHG4CylinderCellGeom.h.
Referenced by get_layer(), identify(), and set_layer().
int PHG4CylinderCellGeom::nphibins protected
Definition at line 70 of file PHG4CylinderCellGeom.h.
Referenced by get_phibin(), get_phibins(), get_phibounds(), get_phicenter(), identify(), and set_phibins().
int PHG4CylinderCellGeom::nzbins protected
Definition at line 67 of file PHG4CylinderCellGeom.h.
Referenced by get_etabin(), get_etabins(), get_etabounds(), get_etacenter(), get_zbin(), get_zbins(), get_zbounds(), get_zcenter(), identify(), set_etabins(), and set_zbins().
double PHG4CylinderCellGeom::phimin protected
Definition at line 71 of file PHG4CylinderCellGeom.h.
Referenced by get_phibin(), get_phibounds(), get_phicenter(), get_phimin(), identify(), and set_phimin().
double PHG4CylinderCellGeom::phistep protected
Definition at line 72 of file PHG4CylinderCellGeom.h.
Referenced by get_phibin(), get_phibounds(), get_phicenter(), get_phistep(), identify(), and set_phistep().
double PHG4CylinderCellGeom::radius protected
Definition at line 66 of file PHG4CylinderCellGeom.h.
Referenced by get_radius(), identify(), and set_radius().
double PHG4CylinderCellGeom::thickness protected
Definition at line 73 of file PHG4CylinderCellGeom.h.
Referenced by get_thickness(), identify(), and set_thickness().
double PHG4CylinderCellGeom::zmin protected
Definition at line 68 of file PHG4CylinderCellGeom.h.
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etamin(), get_zbin(), get_zbounds(), get_zcenter(), get_zmin(), identify(), set_etamin(), and set_zmin().
double PHG4CylinderCellGeom::zstep protected
Definition at line 69 of file PHG4CylinderCellGeom.h.
Referenced by get_etabin(), get_etabounds(), get_etacenter(), get_etastep(), get_zbin(), get_zbounds(), get_zcenter(), get_zstep(), identify(), set_etastep(), and set_zstep().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeom.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeom.cc