Analysis Software: RawTowerGeomv3 Class Reference
RawTowerGeomv3 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv3.h>
Public Member Functions
RawTowerGeomv3 ()
RawTowerGeomv3 (RawTowerDefs::keytype id)
virtual ~RawTowerGeomv3 ()
void identify (std::ostream &os=std::cout) const
void set_id (RawTowerDefs::keytype key)
RawTowerDefs::keytype get_id () const
int get_bineta () const
int get_binphi () const
int get_column () const
int get_row () const
void set_center_x (double x)
void set_center_y (double y)
void set_center_z (double z)
void set_size_x (double dx)
void set_size_y (double dy)
void set_size_z (double dz)
double get_center_x () const
double get_center_y () const
double get_center_z () const
double get_size_x () const
double get_size_y () const
double get_size_z () const
double get_volume () const
double get_center_radius () const
double get_eta () const
double get_phi () const
void set_tower_type (int tt)
int get_tower_type () const
Public Member Functions inherited from RawTowerGeom
virtual ~RawTowerGeom ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype _towerid
double _center_x
double _center_y
double _center_z
double _size_x
double _size_y
double _size_z
int _tower_type
Additional Inherited Members
Protected Member Functions inherited from RawTowerGeom
RawTowerGeom ()
Detailed Description
Definition at line 10 of file RawTowerGeomv3.h.
Constructor & Destructor Documentation
RawTowerGeomv3::RawTowerGeomv3 ()
Definition at line 8 of file RawTowerGeomv3.cc.
RawTowerGeomv3::RawTowerGeomv3 (RawTowerDefs::keytype id)
Definition at line 20 of file RawTowerGeomv3.cc.
virtual RawTowerGeomv3::~RawTowerGeomv3 () inline virtual
Definition at line 15 of file RawTowerGeomv3.h.
Member Function Documentation
int RawTowerGeomv3::get_bineta () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 22 of file RawTowerGeomv3.h.
References _towerid, and RawTowerDefs::decode_index1().
int RawTowerGeomv3::get_binphi () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 23 of file RawTowerGeomv3.h.
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv3::get_center_radius () const virtual
Reimplemented from RawTowerGeom.
Definition at line 32 of file RawTowerGeomv3.cc.
References _center_x, and _center_y.
double RawTowerGeomv3::get_center_x () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 59 of file RawTowerGeomv3.h.
References _center_x.
Referenced by identify().
double RawTowerGeomv3::get_center_y () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 60 of file RawTowerGeomv3.h.
References _center_y.
Referenced by identify().
double RawTowerGeomv3::get_center_z () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 61 of file RawTowerGeomv3.h.
References _center_z.
Referenced by identify().
int RawTowerGeomv3::get_column () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv3.h.
References _towerid, and RawTowerDefs::decode_index1().
double RawTowerGeomv3::get_eta () const virtual
Reimplemented from RawTowerGeom.
Definition at line 38 of file RawTowerGeomv3.cc.
References _center_x, _center_y, and _center_z.
RawTowerDefs::keytype RawTowerGeomv3::get_id () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 20 of file RawTowerGeomv3.h.
References _towerid.
double RawTowerGeomv3::get_phi () const virtual
Reimplemented from RawTowerGeom.
Definition at line 49 of file RawTowerGeomv3.cc.
References _center_x, and _center_y.
int RawTowerGeomv3::get_row () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 25 of file RawTowerGeomv3.h.
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv3::get_size_x () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 63 of file RawTowerGeomv3.h.
References _size_x.
Referenced by identify().
double RawTowerGeomv3::get_size_y () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 64 of file RawTowerGeomv3.h.
References _size_y.
Referenced by identify().
double RawTowerGeomv3::get_size_z () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 65 of file RawTowerGeomv3.h.
References _size_z.
Referenced by identify().
int RawTowerGeomv3::get_tower_type () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 77 of file RawTowerGeomv3.h.
References _tower_type.
double RawTowerGeomv3::get_volume () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 66 of file RawTowerGeomv3.h.
References _size_x, _size_y, and _size_z.
void RawTowerGeomv3::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeom.
Definition at line 54 of file RawTowerGeomv3.cc.
References _tower_type, get_center_x(), get_center_y(), get_center_z(), get_size_x(), get_size_y(), and get_size_z().
void RawTowerGeomv3::set_center_x (double x) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 27 of file RawTowerGeomv3.h.
References _center_x, and x.
void RawTowerGeomv3::set_center_y (double y) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 32 of file RawTowerGeomv3.h.
References _center_y, and y.
void RawTowerGeomv3::set_center_z (double z) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 37 of file RawTowerGeomv3.h.
References _center_z, and z.
void RawTowerGeomv3::set_id (RawTowerDefs::keytype key) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 19 of file RawTowerGeomv3.h.
References _towerid.
void RawTowerGeomv3::set_size_x (double dx) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 43 of file RawTowerGeomv3.h.
References _size_x, and dx.
void RawTowerGeomv3::set_size_y (double dy) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 48 of file RawTowerGeomv3.h.
References _size_y, and dy.
void RawTowerGeomv3::set_size_z (double dz) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 53 of file RawTowerGeomv3.h.
References _size_z.
void RawTowerGeomv3::set_tower_type (int tt) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 72 of file RawTowerGeomv3.h.
References _tower_type.
Member Data Documentation
double RawTowerGeomv3::_center_x protected
Definition at line 82 of file RawTowerGeomv3.h.
Referenced by get_center_radius(), get_center_x(), get_eta(), get_phi(), and set_center_x().
double RawTowerGeomv3::_center_y protected
Definition at line 83 of file RawTowerGeomv3.h.
Referenced by get_center_radius(), get_center_y(), get_eta(), get_phi(), and set_center_y().
double RawTowerGeomv3::_center_z protected
Definition at line 84 of file RawTowerGeomv3.h.
Referenced by get_center_z(), get_eta(), and set_center_z().
double RawTowerGeomv3::_size_x protected
Definition at line 86 of file RawTowerGeomv3.h.
Referenced by get_size_x(), get_volume(), and set_size_x().
double RawTowerGeomv3::_size_y protected
Definition at line 87 of file RawTowerGeomv3.h.
Referenced by get_size_y(), get_volume(), and set_size_y().
double RawTowerGeomv3::_size_z protected
Definition at line 88 of file RawTowerGeomv3.h.
Referenced by get_size_z(), get_volume(), and set_size_z().
int RawTowerGeomv3::_tower_type protected
Definition at line 90 of file RawTowerGeomv3.h.
Referenced by get_tower_type(), identify(), and set_tower_type().
RawTowerDefs::keytype RawTowerGeomv3::_towerid protected
Definition at line 80 of file RawTowerGeomv3.h.
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv3.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv3.cc