Analysis Software: macros/blob/master/macros/g4simulations/Fun4All_G4_sPHENIX.C File Reference
Fun4All_G4_sPHENIX.C File Reference
#include <phool/PHRandomSeed.h>
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/PHG4ParticleGeneratorVectorMeson.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/HepMCNodeReader.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <phool/recoConsts.h>
#include <phpythia6/PHPythia6.h>
#include <phpythia8/PHPythia8.h>
#include <phhepmc/Fun4AllHepMCPileupInputManager.h>
#include <phhepmc/Fun4AllHepMCInputManager.h>
#include "G4Setup_sPHENIX.C"
#include "G4_Bbc.C"
#include "G4_Global.C"
#include "G4_CaloTrigger.C"
#include "G4_Jets.C"
#include "G4_HIJetReco.C"
#include "G4_TopoClusterReco.C"
#include "G4_DSTReader.C"
#include "DisplayOn.C"
Functions
int Fun4All_G4_sPHENIX (const int nEvents=1, const char *inputFile="/sphenix/data/data02/review_2017-08-02/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root", const char *outputFile="G4sPHENIX.root", const char *embed_input_file="/sphenix/data/data02/review_2017-08-02/sHijing/fm_0-4.list")
void RunFFALoadTest ()
Function Documentation
int Fun4All_G4_sPHENIX (const int nEvents = 1, const char * inputFile = "/sphenix/data/data02/review_2017-08-02/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root", const char * outputFile = "G4sPHENIX.root", const char * embed_input_file = "/sphenix/data/data02/review_2017-08-02/sHijing/fm_0-4.list")
forward flux return plug door. Out of acceptance and off by default.
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 42 of file Fun4All_G4_sPHENIX.C.
References PHG4ParticleGeneratorVectorMeson::add_decay_particles(), PHG4SimpleEventGenerator::add_particles(), Fun4AllInputManager::AddFile(), Fun4AllInputManager::AddListFile(), assert, Bbc_Reco(), BbcInit(), CaloTrigger_Sim(), CEMC_Cells(), CEMC_Clusters(), CEMC_Eval(), CEMC_Towers(), DisplayOn(), DstCompress(), PHG4ParticleGeneratorBase::Embed(), Fun4AllServer::End(), FEMC_Cells(), FEMC_Clusters(), FEMC_Eval(), FEMC_Towers(), Fun4AllInputManager::fileopen(), Fun4AllServer::fileopen(), G4DSTreader(), G4Init(), G4Setup(), PHParameterInterface::get_double_param(), Fun4AllServer::getSubsysReco(), Global_FastSim(), Global_Reco(), HCALInner_Cells(), HCALInner_Clusters(), HCALInner_Eval(), HCALInner_Towers(), HCALOuter_Cells(), HCALOuter_Clusters(), HCALOuter_Eval(), HCALOuter_Towers(), HIJetReco(), i, in, recoConsts::instance(), Fun4AllServer::instance(), Jet_Eval(), Jet_Reco(), kAll, Fun4AllBase::Name(), nEvents, particles, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), Fun4AllHepMCPileupInputManager::set_collision_rate(), PHPythia6::set_config_file(), PHPythia8::set_config_file(), PHG4ParticleGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_eta_range(), PHG4SimpleEventGenerator::set_existing_vertex_offset_vector(), PHG4ParticleGeneratorVectorMeson::set_mass(), PHG4ParticleGeneratorBase::set_mom(), PHG4ParticleGenerator::set_mom_range(), PHG4ParticleGeneratorBase::set_name(), PHG4ParticleGenerator::set_phi_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4ParticleGeneratorVectorMeson::set_pt_range(), PHG4SimpleEventGenerator::set_pt_range(), PHG4ParticleGeneratorVectorMeson::set_rapidity_range(), PHG4ParticleGeneratorBase::set_reuse_existing_vertex(), PHPythia6::set_reuse_vertex(), PHPythia8::set_reuse_vertex(), Fun4AllHepMCPileupInputManager::set_time_window(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4ParticleGeneratorBase::set_vtx(), PHG4ParticleGeneratorVectorMeson::set_width(), PHG4ParticleGenerator::set_z_range(), ShowerCompress(), TopoClusterReco(), Tracking_Cells(), Tracking_Clus(), Tracking_Eval(), Tracking_Reco(), PHG4SimpleEventGenerator::Uniform, PHRandomSeed::Verbosity(), and Fun4AllBase::Verbosity().
void RunFFALoadTest ()
Definition at line 641 of file Fun4All_G4_sPHENIX.C.