Analysis Software: PHG4ScoringManager Class Reference
PHG4ScoringManager Class Reference
PHG4ScoringManager is the connection between Fun4All to G4ScoringManager Track primitive score like flux or energy deposition integrated over events and save to histograms More on G4ScoringManager see Manual http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/BackupVersions/V9.6/html/ch04s08.html And talk http://geant4.slac.stanford.edu/JLAB2012/Scoring1.pdf.
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ScoringManager.h>
Public Member Functions
PHG4ScoringManager ()
virtual ~PHG4ScoringManager ()
int InitRun (PHCompositeNode *topNode)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
void setOutputFileName (const std::string &outputfilename)
Output result to a ROOT file with this name.
void G4Command (const std::string &cmd)
Run this Geant4 command after initialization of G4ScoringManager in the InitRun() stage You can call this command multiple times to stage multiple commands to run.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
Fun4AllHistoManager * getHistoManager ()
void makeScoringHistograms ()
based on G4VScoreWriter::DumpAllQuantitiesToFile()
Private Attributes
std::vector< std::string > m_commands
std::string m_outputFileName
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
PHG4ScoringManager is the connection between Fun4All to G4ScoringManager Track primitive score like flux or energy deposition integrated over events and save to histograms More on G4ScoringManager see Manual http://geant4-userdoc.web.cern.ch/geant4-userdoc/UsersGuides/ForApplicationDeveloper/BackupVersions/V9.6/html/ch04s08.html And talk http://geant4.slac.stanford.edu/JLAB2012/Scoring1.pdf.
Definition at line 31 of file PHG4ScoringManager.h.
Constructor & Destructor Documentation
PHG4ScoringManager::PHG4ScoringManager ()
Definition at line 59 of file PHG4ScoringManager.cc.
virtual PHG4ScoringManager::~PHG4ScoringManager () inline virtual
Definition at line 36 of file PHG4ScoringManager.h.
Member Function Documentation
int PHG4ScoringManager::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 201 of file PHG4ScoringManager.cc.
References assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), Fun4AllHistoManager::getHisto(), getHistoManager(), i, m_outputFileName, makeScoringHistograms(), and Fun4AllHistoManager::nHistos().
void PHG4ScoringManager::G4Command (const std::string & cmd)
Run this Geant4 command after initialization of G4ScoringManager in the InitRun() stage You can call this command multiple times to stage multiple commands to run.
Example
PHG4ScoringManager * g4score = new PHG4ScoringManager();
g4score->G4Command("/score/create/cylinderMesh cyl_score");
g4score->G4Command("/score/mesh/cylinderSize 100. 400. cm");
g4score->G4Command("/score/mesh/nBin 100 800 8");
g4score->G4Command("/score/quantity/eDep cyl_edep");
g4score->G4Command("/score/quantity/cellFlux cyl_flux");
g4score->G4Command("/score/close");
Definition at line 120 of file PHG4ScoringManager.cc.
References m_commands.
Fun4AllHistoManager * PHG4ScoringManager::getHistoManager () private
Definition at line 392 of file PHG4ScoringManager.cc.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), Fun4AllServer::registerHistoManager(), and Fun4AllBase::Verbosity().
Referenced by End(), InitRun(), makeScoringHistograms(), and process_event().
int PHG4ScoringManager::InitRun (PHCompositeNode * topNode) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 64 of file PHG4ScoringManager.cc.
References Fun4AllReturnCodes::ABORTRUN, assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), getHistoManager(), SVM_v1::h, i, m_commands, m_outputFileName, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void PHG4ScoringManager::makeScoringHistograms () private
based on G4VScoreWriter::DumpAllQuantitiesToFile()
Definition at line 221 of file PHG4ScoringManager.cc.
References assert, data, getHistoManager(), SVM_v1::h, M_PI, Fun4AllHistoManager::registerHisto(), value, Fun4AllBase::Verbosity(), x, y, and z.
Referenced by End().
int PHG4ScoringManager::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 128 of file PHG4ScoringManager.cc.
References assert, Fun4AllReturnCodes::EVENT_OK, PHHepMCGenEvent::get_collision_vertex(), PHHepMCGenEventMap::get_map(), PHG4Particle::get_pid(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), Fun4AllHistoManager::getHisto(), getHistoManager(), PHG4InEvent::GetParticles(), and PHHepMCGenEventMap::size().
void PHG4ScoringManager::setOutputFileName (const std::string & outputfilename) inline
Output result to a ROOT file with this name.
Definition at line 48 of file PHG4ScoringManager.h.
References m_outputFileName.
Member Data Documentation
std::vector<std::string> PHG4ScoringManager::m_commands private
Definition at line 72 of file PHG4ScoringManager.h.
Referenced by G4Command(), and InitRun().
std::string PHG4ScoringManager::m_outputFileName private
Definition at line 74 of file PHG4ScoringManager.h.
Referenced by End(), InitRun(), and setOutputFileName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ScoringManager.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4ScoringManager.cc