Analysis Software: Fun4AllOutputManager Class Reference
Fun4AllOutputManager Class Reference
#include <coresoftware/blob/master/offline/framework/fun4all/Fun4AllOutputManager.h>
Public Member Functions
virtual ~Fun4AllOutputManager ()
destructor
virtual void Print (const std::string &what="ALL") const
print method (dump event selector)
virtual int AddNode (const std::string &)
add a node in outputmanager
virtual int StripNode (const std::string &)
not write a node in outputmanager
virtual int StripRunNode (const std::string &)
not write a runwise node in outputmanager
virtual int AddEventSelector (const std::string &recomodule)
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
virtual int outfileopen (const std::string &)
opens output file
int WriteGeneric (PHCompositeNode *startNode)
Common method, called before calling virtual Write.
virtual int Write (PHCompositeNode *)
write starting from given node
virtual int WriteNode (PHCompositeNode *)
write specified node
virtual std::vector
< std::string > * EventSelector ()
retrieves pointer to vector of event selector module names
virtual std::vector< unsigned > * RecoModuleIndex ()
retrieves pointer to vector of event selector module ids
virtual int DoNotWriteEvent (std::vector< int > *retcodes) const
decides if event is to be written or not
virtual size_t EventsWritten () const
get number of Events
virtual void IncrementEvents (const unsigned int i)
increment number of events
virtual std::string OutFileName () const
get output file name
void OutFileName (const std::string &name)
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
Fun4AllOutputManager (const std::string &myname)
Fun4AllOutputManager (const std::string &myname, const std::string &outfname)
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Private Attributes
unsigned int m_NEvents
Number of Events.
std::string m_OutFileName
output file name
std::vector< std::string > m_EventSelectorsVector
vector of event selectors modules
std::vector< unsigned > m_RecoModuleIndexVector
vector of associated module indexes
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Definition at line 14 of file Fun4AllOutputManager.h.
Constructor & Destructor Documentation
virtual Fun4AllOutputManager::~Fun4AllOutputManager () inline virtual
destructor
Definition at line 18 of file Fun4AllOutputManager.h.
Fun4AllOutputManager::Fun4AllOutputManager (const std::string & myname) protected
constructor. is protected since we do not want the class to be created in root macros
Definition at line 9 of file Fun4AllOutputManager.cc.
Fun4AllOutputManager::Fun4AllOutputManager (const std::string & myname, const std::string & outfname) protected
Definition at line 15 of file Fun4AllOutputManager.cc.
Member Function Documentation
int Fun4AllOutputManager::AddEventSelector (const std::string & recomodule) virtual
add an event selector to the outputmanager. event will get written only if all event selectors process_event method return EVENT_OK
Definition at line 23 of file Fun4AllOutputManager.cc.
References m_EventSelectorsVector.
Referenced by MakeTree().
virtual int Fun4AllOutputManager::AddNode (const std::string &) inline virtual
add a node in outputmanager
Reimplemented in Fun4AllDstOutputManager.
Definition at line 26 of file Fun4AllOutputManager.h.
Referenced by G4TTree(), MakeTree(), and MyHitTTree().
int Fun4AllOutputManager::DoNotWriteEvent (std::vector< int > * retcodes) const virtual
decides if event is to be written or not
Definition at line 68 of file Fun4AllOutputManager.cc.
References index, and m_RecoModuleIndexVector.
virtual std::vector<std::string>* Fun4AllOutputManager::EventSelector () inline virtual
retrieves pointer to vector of event selector module names
Definition at line 72 of file Fun4AllOutputManager.h.
References m_EventSelectorsVector.
Referenced by Fun4AllServer::UpdateEventSelector().
virtual size_t Fun4AllOutputManager::EventsWritten () const inline virtual
get number of Events
Definition at line 87 of file Fun4AllOutputManager.h.
References m_NEvents.
Referenced by Print().
virtual void Fun4AllOutputManager::IncrementEvents (const unsigned int i) inline virtual
increment number of events
Definition at line 89 of file Fun4AllOutputManager.h.
References i, and m_NEvents.
Referenced by Fun4AllHepMCOutputManager::Write().
virtual std::string Fun4AllOutputManager::OutFileName () const inline virtual
get output file name
Definition at line 91 of file Fun4AllOutputManager.h.
References m_OutFileName.
Referenced by Fun4AllPrdfOutputManager::InitPrdfManager(), Fun4AllPrdfOutputManager::outfileopen(), Fun4AllDstOutputManager::Print(), Fun4AllEventOutputManager::SetOutfileName(), and Fun4AllDstOutputManager::WriteNode().
void Fun4AllOutputManager::OutFileName (const std::string & name) inline
Definition at line 92 of file Fun4AllOutputManager.h.
References m_OutFileName, and name.
virtual int Fun4AllOutputManager::outfileopen (const std::string &) inline virtual
opens output file
Reimplemented in Fun4AllPrdfOutputManager, Fun4AllHepMCOutputManager, Fun4AllDstOutputManager, and Fun4AllEventOutputManager.
Definition at line 51 of file Fun4AllOutputManager.h.
void Fun4AllOutputManager::Print (const std::string & what = "ALL") const virtual
print method (dump event selector)
Reimplemented from Fun4AllBase.
Reimplemented in Fun4AllHepMCOutputManager, Fun4AllDstOutputManager, and Fun4AllEventOutputManager.
Definition at line 48 of file Fun4AllOutputManager.cc.
References EventsWritten(), m_EventSelectorsVector, m_RecoModuleIndexVector, and Fun4AllBase::Name().
Referenced by Fun4AllEventOutputManager::Print(), Fun4AllDstOutputManager::Print(), Fun4AllHepMCOutputManager::Print(), and Fun4AllServer::Print().
virtual std::vector<unsigned>* Fun4AllOutputManager::RecoModuleIndex () inline virtual
retrieves pointer to vector of event selector module ids
Definition at line 78 of file Fun4AllOutputManager.h.
References m_RecoModuleIndexVector.
Referenced by Fun4AllServer::UpdateEventSelector().
virtual int Fun4AllOutputManager::StripNode (const std::string &) inline virtual
not write a node in outputmanager
Reimplemented in Fun4AllDstOutputManager.
Definition at line 32 of file Fun4AllOutputManager.h.
virtual int Fun4AllOutputManager::StripRunNode (const std::string &) inline virtual
not write a runwise node in outputmanager
Reimplemented in Fun4AllDstOutputManager.
Definition at line 38 of file Fun4AllOutputManager.h.
virtual int Fun4AllOutputManager::Write (PHCompositeNode *) inline virtual
write starting from given node
Reimplemented in Fun4AllPrdfOutputManager, Fun4AllHepMCOutputManager, Fun4AllDstOutputManager, and Fun4AllEventOutputManager.
Definition at line 60 of file Fun4AllOutputManager.h.
Referenced by WriteGeneric().
int Fun4AllOutputManager::WriteGeneric (PHCompositeNode * startNode)
Common method, called before calling virtual Write.
Definition at line 40 of file Fun4AllOutputManager.cc.
References m_NEvents, and Write().
virtual int Fun4AllOutputManager::WriteNode (PHCompositeNode *) inline virtual
write specified node
Reimplemented in Fun4AllDstOutputManager.
Definition at line 66 of file Fun4AllOutputManager.h.
Member Data Documentation
std::vector<std::string> Fun4AllOutputManager::m_EventSelectorsVector private
vector of event selectors modules
Definition at line 110 of file Fun4AllOutputManager.h.
Referenced by AddEventSelector(), EventSelector(), and Print().
unsigned int Fun4AllOutputManager::m_NEvents private
Number of Events.
Definition at line 104 of file Fun4AllOutputManager.h.
Referenced by EventsWritten(), IncrementEvents(), and WriteGeneric().
std::string Fun4AllOutputManager::m_OutFileName private
output file name
Definition at line 107 of file Fun4AllOutputManager.h.
Referenced by OutFileName().
std::vector<unsigned> Fun4AllOutputManager::m_RecoModuleIndexVector private
vector of associated module indexes
Definition at line 113 of file Fun4AllOutputManager.h.
Referenced by DoNotWriteEvent(), Print(), and RecoModuleIndex().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/Fun4AllOutputManager.h
coresoftware/blob/master/offline/framework/fun4all/Fun4AllOutputManager.cc