Analysis Software: AnaMvtxTelescopeHits Class Reference
AnaMvtxTelescopeHits Class Reference
#include <analysis/blob/master/MvtxTelescope/AnaMvtxTelescopeHits/AnaMvtxTelescopeHits.h>
Public Member Functions
AnaMvtxTelescopeHits (const std::string &name="AnaMvtxTelescopeHits", const std::string &ofName="out.root")
int Init (PHCompositeNode *)
int InitRun (PHCompositeNode *)
int process_event (PHCompositeNode *)
int End (PHCompositeNode *)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int GetNodes (PHCompositeNode *)
double CalcSlope (double x0, double y0, double x1, double y1)
Get all nodes.
double CalcIntecept (double x0, double y0, double m)
double CalcProjection (double x, double m, double b)
Private Attributes
SvtxClusterMap * _clustermap
std::string _foutname
TFile * _f
TH1D * hlayer
TH1D * hsize_phi [4]
TH1D * hsize_z [4]
TH2D * hphiz [4]
TH1D * hdphi [4]
TH1D * hdz [4]
int _ievent
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 44 of file AnaMvtxTelescopeHits.h.
Constructor & Destructor Documentation
AnaMvtxTelescopeHits::AnaMvtxTelescopeHits (const std::string & name = "AnaMvtxTelescopeHits", const std::string & ofName = "out.root")
Definition at line 95 of file AnaMvtxTelescopeHits.C.
References hdphi, hdz, hlayer, hphiz, hsize_phi, and hsize_z.
Member Function Documentation
double AnaMvtxTelescopeHits::CalcIntecept (double x0, double y0, double m) private
Definition at line 422 of file AnaMvtxTelescopeHits.C.
Referenced by process_event().
double AnaMvtxTelescopeHits::CalcProjection (double x, double m, double b) private
Definition at line 431 of file AnaMvtxTelescopeHits.C.
Referenced by process_event().
double AnaMvtxTelescopeHits::CalcSlope (double x0, double y0, double x1, double y1) private
Get all nodes.
Definition at line 413 of file AnaMvtxTelescopeHits.C.
References x0.
Referenced by process_event().
int AnaMvtxTelescopeHits::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 383 of file AnaMvtxTelescopeHits.C.
References _f.
int AnaMvtxTelescopeHits::GetNodes (PHCompositeNode * topNode) private
Definition at line 394 of file AnaMvtxTelescopeHits.C.
References _clustermap, _ievent, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by process_event().
int AnaMvtxTelescopeHits::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 114 of file AnaMvtxTelescopeHits.C.
References _f, _foutname, hdphi, hdz, hlayer, hphiz, hsize_phi, and hsize_z.
int AnaMvtxTelescopeHits::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 153 of file AnaMvtxTelescopeHits.C.
References _ievent.
int AnaMvtxTelescopeHits::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 175 of file AnaMvtxTelescopeHits.C.
References _clustermap, _ievent, SvtxClusterMap::begin(), CalcIntecept(), CalcProjection(), CalcSlope(), SvtxClusterMap::end(), Fun4AllReturnCodes::EVENT_OK, SvtxCluster::get_layer(), SvtxCluster::get_phi_size(), SvtxCluster::get_x(), SvtxCluster::get_y(), SvtxCluster::get_z(), SvtxCluster::get_z_size(), GetNodes(), hdphi, hdz, hlayer, hphiz, hsize_phi, hsize_z, phi, r, SvtxClusterMap::size(), verbosity, Fun4AllBase::VERBOSITY_MORE, and z.
Member Data Documentation
SvtxClusterMap* AnaMvtxTelescopeHits::_clustermap private
Definition at line 77 of file AnaMvtxTelescopeHits.h.
Referenced by GetNodes(), and process_event().
TFile* AnaMvtxTelescopeHits::_f private
Definition at line 84 of file AnaMvtxTelescopeHits.h.
Referenced by End(), and Init().
std::string AnaMvtxTelescopeHits::_foutname private
Definition at line 83 of file AnaMvtxTelescopeHits.h.
Referenced by Init().
int AnaMvtxTelescopeHits::_ievent private
Definition at line 95 of file AnaMvtxTelescopeHits.h.
Referenced by GetNodes(), InitRun(), and process_event().
TH1D* AnaMvtxTelescopeHits::hdphi[4] private
Definition at line 90 of file AnaMvtxTelescopeHits.h.
Referenced by AnaMvtxTelescopeHits(), Init(), and process_event().
TH1D* AnaMvtxTelescopeHits::hdz[4] private
Definition at line 91 of file AnaMvtxTelescopeHits.h.
Referenced by AnaMvtxTelescopeHits(), Init(), and process_event().
TH1D* AnaMvtxTelescopeHits::hlayer private
Definition at line 86 of file AnaMvtxTelescopeHits.h.
Referenced by AnaMvtxTelescopeHits(), Init(), and process_event().
TH2D* AnaMvtxTelescopeHits::hphiz[4] private
Definition at line 89 of file AnaMvtxTelescopeHits.h.
Referenced by AnaMvtxTelescopeHits(), Init(), and process_event().
TH1D* AnaMvtxTelescopeHits::hsize_phi[4] private
Definition at line 87 of file AnaMvtxTelescopeHits.h.
Referenced by AnaMvtxTelescopeHits(), Init(), and process_event().
TH1D* AnaMvtxTelescopeHits::hsize_z[4] private
Definition at line 88 of file AnaMvtxTelescopeHits.h.
Referenced by AnaMvtxTelescopeHits(), Init(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/MvtxTelescope/AnaMvtxTelescopeHits/AnaMvtxTelescopeHits.h
analysis/blob/master/MvtxTelescope/AnaMvtxTelescopeHits/AnaMvtxTelescopeHits.C