Analysis Software: PHG4FCalSteppingAction Class Reference
PHG4FCalSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FCalSteppingAction.h>
Public Member Functions
PHG4FCalSteppingAction (PHG4FCalDetector *)
virtual ~PHG4FCalSteppingAction ()
virtual void UserSteppingAction (const G4Step *)
virtual void SetInterfacePointers (PHCompositeNode *)
Private Attributes
PHG4FCalDetector * detector_
PHG4HitContainer * hits_
PHG4Hit * hit
Detailed Description
Definition at line 14 of file PHG4FCalSteppingAction.h.
Constructor & Destructor Documentation
PHG4FCalSteppingAction::PHG4FCalSteppingAction (PHG4FCalDetector * detector)
Definition at line 31 of file PHG4FCalSteppingAction.cc.
virtual PHG4FCalSteppingAction::~PHG4FCalSteppingAction () inline virtual
Definition at line 18 of file PHG4FCalSteppingAction.h.
Member Function Documentation
void PHG4FCalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
Definition at line 112 of file PHG4FCalSteppingAction.cc.
References hits_.
void PHG4FCalSteppingAction::UserSteppingAction (const G4Step * aStep) virtual
Definition at line 38 of file PHG4FCalSteppingAction.cc.
References PHG4FCalDetector::computeIndex(), detector_, PHG4HitContainer::findOrAddHit(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), PHG4FCalDetector::getScintillatorLayer(), hit, hits_, PHG4FCalDetector::isInScintillator(), it, PHG4Hit::set_edep(), PHG4Hit::set_shower_id(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), and PHG4TrackUserInfoV1::SetWanted().
Member Data Documentation
PHG4FCalDetector* PHG4FCalSteppingAction::detector_ private
Definition at line 25 of file PHG4FCalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Hit* PHG4FCalSteppingAction::hit private
Definition at line 27 of file PHG4FCalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4FCalSteppingAction::hits_ private
Definition at line 26 of file PHG4FCalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FCalSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4FCalSteppingAction.cc