Analysis Software: online_distribution/blob/master/newbasic/CpacketV1.C File Reference
CpacketV1.C File Reference
#include "phenixOnline.h"
#include "Cpacket.h"
#include "CpacketV1.h"
Functions
VALUE_ret makePacketV1Hdr (PHDWORD *packet_ptr, UINT maxPacketLength)
PTR_ret findPacketV1DebugStart (PACKET_ptr packet_ptr)
PTR_ret findPacketV1ErrorStart (PACKET_ptr packet_ptr)
PTR_ret findPacketV1DataStart (PACKET_ptr packet_ptr)
PTR_ret findPacketV1DataEnd (PACKET_ptr packet_ptr)
LOGIC_ret validPacketV1Hdr (PACKET_ptr packet_ptr)
Function Documentation
PTR_ret findPacketV1DataEnd (PACKET_ptr packet_ptr)
Definition at line 71 of file CpacketV1.C.
References findPacketV1DebugStart().
PTR_ret findPacketV1DataStart (PACKET_ptr packet_ptr)
Definition at line 66 of file CpacketV1.C.
References getPacketHdrLength().
PTR_ret findPacketV1DebugStart (PACKET_ptr packet_ptr)
Definition at line 51 of file CpacketV1.C.
References getPacketLength(), getPacketV1DebugLength(), and getPacketV1ErrorLength().
Referenced by findPacketV1DataEnd().
PTR_ret findPacketV1ErrorStart (PACKET_ptr packet_ptr)
Definition at line 60 of file CpacketV1.C.
References getPacketLength(), and getPacketV1ErrorLength().
VALUE_ret makePacketV1Hdr (PHDWORD * packet_ptr, UINT maxPacketLength)
Definition at line 30 of file CpacketV1.C.
References dwordClear, n, packetV1HdrLength, packetV1HdrVersion, setPacketEndianism(), setPacketHdrLength(), setPacketHdrVersion(), setPacketLength(), and valueFailure.
LOGIC_ret validPacketV1Hdr (PACKET_ptr packet_ptr)
Definition at line 82 of file CpacketV1.C.
References FALSE, FORMAT_ERR_INVALID_HEADER, getPacketHdrLength(), packetV1HdrLength, setPacketError(), setPacketSuccess(), and TRUE.