Analysis Software: online_distribution/blob/master/newbasic/CframeV1.h File Reference
CframeV1.h File Reference
#include "phenixOnline.h"
#include "formatError.h"
#include "framePublic.h"
#include "frameV1Public.h"
#include "frameHdrV1.h"
#include "Cframe.h"
Functions
VALUE_ret makeFrameHdrV1 (PHDWORD *, UINT, UINT, UINT, UINT)
VALUE_ret getFrameDataLengthV1 (FRAME_ptr)
VALUE_ret adjustFrameHistoryLengthV1 (FRAME_ptr, UINT)
VALUE_ret adjustFrameErrorLengthV1 (FRAME_ptr, UINT)
VALUE_ret orFrameStatusV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret validFrameHdrV1 (FRAME_ptr)
INLINE_P LOGIC_ret emptyFrameV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameErrorLengthV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameHistoryLengthV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameAlignLengthV1 (FRAME_ptr)
INLINE_P VALUE_ret getFramePaddingV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameSourceIdV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameTypeV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameDataTypeV1 (FRAME_ptr)
INLINE_P VALUE_ret getFrameStatusV1 (FRAME_ptr)
INLINE_P VALUE_ret adjustFrameDataLengthV1 (FRAME_ptr, UINT)
INLINE_P VALUE_ret setFramePaddingV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setDataTypeV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameTypeV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setSourceIdV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameHistoryLengthV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameErrorLengthV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameAlignLengthV1 (FRAME_ptr, UINT)
INLINE_P LOGIC_ret setFrameStatusV1 (FRAME_ptr, UINT)
INLINE_P PTR_ret findFrameAlignBlockV1 (FRAME_ptr)
INLINE_P PTR_ret findFrameErrorStartV1 (FRAME_ptr)
INLINE_P PTR_ret findFrameHistoryStartV1 (FRAME_ptr)
INLINE_P VALUE_ret getAlignBlockV1 (FRAME_ptr, PHDWORD *, UINT)
INLINE_P LOGIC_ret setAlignBlockV1 (FRAME_ptr, PHDWORD *, UINT)
INLINE_P VALUE_ret getHistoryEntryV1 (FRAME_ptr, UINT)
INLINE_P VALUE_ret getHistoryStageV1 (FRAME_ptr, UINT)
INLINE_P VALUE_ret getHistorySourceIndexV1 (FRAME_ptr, UINT)
INLINE_P VALUE_ret getHistoryStatusV1 (FRAME_ptr, UINT)
INLINE_P VALUE_ret getStageFromHistoryEntryV1 (PHDWORD)
INLINE_P VALUE_ret getSourceIndexFromHistoryEntryV1 (PHDWORD)
INLINE_P VALUE_ret getStatusFromHistoryEntryV1 (PHDWORD)
INLINE_P PTR_ret findNextErrorV1 (FRAME_ptr, FRAME_ptr)
Function Documentation
INLINE_D UINT adjustFrameDataLengthV1 (FRAME_ptr frame_ptr, UINT newDwords)
Definition at line 263 of file CframeV1.h.
References getFrameDataLengthV1(), and valueFailure.
VALUE_ret adjustFrameErrorLengthV1 (FRAME_ptr , UINT)
Definition at line 124 of file CframeV1.C.
References ERROR_LENGTH_MASK, ERROR_LENGTH_OFFSET_IN_DWORD, ERROR_LENGTH_OFFSET_OF_DWORD, FORMAT_ERR_ERROR_OVERFLOW, getFrameErrorLengthV1(), maxSwordValue, setBitsMACRO, setFrameError(), setFrameSuccess(), and valueFailure.
VALUE_ret adjustFrameHistoryLengthV1 (FRAME_ptr , UINT)
Definition at line 98 of file CframeV1.C.
References FORMAT_ERR_HISTORY_OVERFLOW, getFrameHistoryLengthV1(), HISTORY_LENGTH_MASK, HISTORY_LENGTH_OFFSET_IN_DWORD, HISTORY_LENGTH_OFFSET_OF_DWORD, maxSwordValue, setBitsMACRO, setFrameError(), setFrameSuccess(), and valueFailure.
INLINE_D LOGIC_ret emptyFrameV1 (FRAME_ptr frame_ptr)
Definition at line 138 of file CframeV1.h.
References getFrameHdrLength(), and getFrameLength().
INLINE_D PTR_ret findFrameAlignBlockV1 (FRAME_ptr frame_ptr)
Definition at line 238 of file CframeV1.h.
References ALIGN_OFFSET_OF_DWORD.
INLINE_D PTR_ret findFrameErrorStartV1 (FRAME_ptr frame_ptr)
Definition at line 218 of file CframeV1.h.
References getFrameErrorLengthV1(), getFrameLength(), and getFramePadding().
INLINE_D PTR_ret findFrameHistoryStartV1 (FRAME_ptr frame_ptr)
Definition at line 228 of file CframeV1.h.
References getFrameErrorLengthV1(), getFrameHistoryLengthV1(), getFrameLength(), and getFramePadding().
INLINE_D PTR_ret findNextErrorV1 (FRAME_ptr frame_ptr, FRAME_ptr thisError)
Definition at line 429 of file CframeV1.h.
References findFrameEnd(), findFrameErrorStart(), and ptrFailure.
INLINE_D VALUE_ret getAlignBlockV1 (FRAME_ptr frame_ptr, PHDWORD * alignDestination, UINT maxNumDwords)
Definition at line 370 of file CframeV1.h.
References ALIGN_OFFSET_OF_DWORD, dwordCopy, getFrameAlignLength(), and valueFailure.
INLINE_D VALUE_ret getFrameAlignLengthV1 (FRAME_ptr frame_ptr)
Definition at line 207 of file CframeV1.h.
References ALIGN_LENGTH_MASK, ALIGN_LENGTH_OFFSET_IN_DWORD, ALIGN_LENGTH_OFFSET_OF_DWORD, and getBitsMACRO.
VALUE_ret getFrameDataLengthV1 (FRAME_ptr)
Definition at line 50 of file CframeV1.C.
References FORMAT_ERR_INVALID_HEADER, getFrameErrorLengthV1(), getFrameHdrLength(), getFrameHistoryLengthV1(), getFrameLength(), getFramePaddingV1(), setFrameError(), setFrameSuccess(), and valueFailure.
Referenced by adjustFrameDataLengthV1().
INLINE_D VALUE_ret getFrameDataTypeV1 (FRAME_ptr frame_ptr)
Definition at line 162 of file CframeV1.h.
References DATA_TYPE_MASK, DATA_TYPE_OFFSET_IN_DWORD, DATA_TYPE_OFFSET_OF_DWORD, and getBitsMACRO.
INLINE_D VALUE_ret getFrameErrorLengthV1 (FRAME_ptr frame_ptr)
Definition at line 189 of file CframeV1.h.
References ERROR_LENGTH_MASK, ERROR_LENGTH_OFFSET_IN_DWORD, ERROR_LENGTH_OFFSET_OF_DWORD, and getBitsMACRO.
Referenced by adjustFrameErrorLengthV1(), findFrameErrorStartV1(), findFrameHistoryStartV1(), and getFrameDataLengthV1().
INLINE_D VALUE_ret getFrameHistoryLengthV1 (FRAME_ptr frame_ptr)
Definition at line 198 of file CframeV1.h.
References getBitsMACRO, HISTORY_LENGTH_MASK, HISTORY_LENGTH_OFFSET_IN_DWORD, and HISTORY_LENGTH_OFFSET_OF_DWORD.
Referenced by adjustFrameHistoryLengthV1(), findFrameHistoryStartV1(), and getFrameDataLengthV1().
INLINE_D VALUE_ret getFramePaddingV1 (FRAME_ptr frame_ptr)
Definition at line 144 of file CframeV1.h.
References getBitsMACRO, PADDING_MASK, PADDING_OFFSET_IN_DWORD, and PADDING_OFFSET_OF_DWORD.
Referenced by getFrameDataLengthV1().
INLINE_D VALUE_ret getFrameSourceIdV1 (FRAME_ptr frame_ptr)
Definition at line 153 of file CframeV1.h.
References getBitsMACRO, SOURCE_ID_MASK, SOURCE_ID_OFFSET_IN_DWORD, and SOURCE_ID_OFFSET_OF_DWORD.
INLINE_D VALUE_ret getFrameStatusV1 (FRAME_ptr frame_ptr)
Definition at line 180 of file CframeV1.h.
References getBitsMACRO, STATUS_MASK, STATUS_OFFSET_IN_DWORD, and STATUS_OFFSET_OF_DWORD.
INLINE_D VALUE_ret getFrameTypeV1 (FRAME_ptr frame_ptr)
Definition at line 171 of file CframeV1.h.
References FRAME_TYPE_MASK, FRAME_TYPE_OFFSET_IN_DWORD, FRAME_TYPE_OFFSET_OF_DWORD, and getBitsMACRO.
INLINE_D VALUE_ret getHistoryEntryV1 (FRAME_ptr frame_ptr, UINT index)
Definition at line 392 of file CframeV1.h.
References findFrameHistoryStart(), getFrameHistoryLength(), and valueFailure.
Referenced by getHistorySourceIndexV1(), getHistoryStageV1(), and getHistoryStatusV1().
INLINE_D VALUE_ret getHistorySourceIndexV1 (FRAME_ptr frame_ptr, UINT index)
Definition at line 419 of file CframeV1.h.
References getHistoryEntryV1(), and getSourceIndexFromHistoryEntryV1().
INLINE_D VALUE_ret getHistoryStageV1 (FRAME_ptr frame_ptr, UINT index)
Definition at line 414 of file CframeV1.h.
References getHistoryEntryV1(), and getStageFromHistoryEntryV1().
INLINE_D VALUE_ret getHistoryStatusV1 (FRAME_ptr frame_ptr, UINT index)
Definition at line 424 of file CframeV1.h.
References getHistoryEntryV1(), and getStatusFromHistoryEntryV1().
INLINE_D VALUE_ret getSourceIndexFromHistoryEntryV1 (PHDWORD historyEntry)
Definition at line 404 of file CframeV1.h.
Referenced by getHistorySourceIndexV1().
INLINE_D VALUE_ret getStageFromHistoryEntryV1 (PHDWORD historyEntry)
Definition at line 399 of file CframeV1.h.
Referenced by getHistoryStageV1().
INLINE_D VALUE_ret getStatusFromHistoryEntryV1 (PHDWORD historyEntry)
Definition at line 409 of file CframeV1.h.
Referenced by getHistoryStatusV1().
VALUE_ret makeFrameHdrV1 (PHDWORD * , UINT , UINT , UINT , UINT)
Definition at line 30 of file CframeV1.C.
References currentFrameHdrLength, currentFrameHdrVersion, currentFrameMark, dwordClear, setDataType(), setFrameAlignLength(), setFrameHdrLength(), setFrameHdrVersion(), setFrameLength(), setFrameMark(), setFrameType(), setSourceId(), V1_ALIGN_LENGTH, V1_FRAMEHDR_LENGTH, and valueFailure.
VALUE_ret orFrameStatusV1 (FRAME_ptr , UINT)
Definition at line 71 of file CframeV1.C.
References FORMAT_ERR_INVALID_DATA, getBitsMACRO, setBitsMACRO, setUserError(), STATUS_MASK, STATUS_NUM_BITS, STATUS_OFFSET_IN_DWORD, STATUS_OFFSET_OF_DWORD, and valueFailure.
INLINE_D LOGIC_ret setAlignBlockV1 (FRAME_ptr frame_ptr, PHDWORD * alignSource, UINT numDwords)
Definition at line 380 of file CframeV1.h.
References ALIGN_OFFSET_OF_DWORD, dwordCopy, FALSE, getFrameAlignLength(), and TRUE.
INLINE_D LOGIC_ret setDataTypeV1 (FRAME_ptr frame_ptr, UINT dataType)
Definition at line 273 of file CframeV1.h.
References DATA_TYPE_MASK, DATA_TYPE_OFFSET_IN_DWORD, DATA_TYPE_OFFSET_OF_DWORD, FALSE, maxByteValue, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setFrameAlignLengthV1 (FRAME_ptr frame_ptr, UINT alignLength)
Definition at line 343 of file CframeV1.h.
References ALIGN_LENGTH_MASK, ALIGN_LENGTH_OFFSET_IN_DWORD, ALIGN_LENGTH_OFFSET_OF_DWORD, FALSE, maxByteValue, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setFrameErrorLengthV1 (FRAME_ptr frame_ptr, UINT errorLength)
Definition at line 329 of file CframeV1.h.
References ERROR_LENGTH_MASK, ERROR_LENGTH_OFFSET_IN_DWORD, ERROR_LENGTH_OFFSET_OF_DWORD, FALSE, maxSwordValue, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setFrameHistoryLengthV1 (FRAME_ptr frame_ptr, UINT historyLength)
Definition at line 315 of file CframeV1.h.
References FALSE, HISTORY_LENGTH_MASK, HISTORY_LENGTH_OFFSET_IN_DWORD, HISTORY_LENGTH_OFFSET_OF_DWORD, maxSwordValue, setBitsMACRO, and TRUE.
INLINE_D VALUE_ret setFramePaddingV1 (FRAME_ptr frame_ptr, UINT numPadDwords)
Definition at line 243 of file CframeV1.h.
References PADDING_MASK, PADDING_OFFSET_IN_DWORD, PADDING_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setFrameStatusV1 (FRAME_ptr frame_ptr, UINT status)
Definition at line 356 of file CframeV1.h.
References FALSE, maxSwordValue, setBitsMACRO, STATUS_MASK, STATUS_OFFSET_IN_DWORD, STATUS_OFFSET_OF_DWORD, and TRUE.
INLINE_D LOGIC_ret setFrameTypeV1 (FRAME_ptr frame_ptr, UINT frameType)
Definition at line 287 of file CframeV1.h.
References FALSE, FRAME_TYPE_MASK, FRAME_TYPE_OFFSET_IN_DWORD, FRAME_TYPE_OFFSET_OF_DWORD, maxByteValue, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setSourceIdV1 (FRAME_ptr frame_ptr, UINT sourceId)
Definition at line 301 of file CframeV1.h.
References FALSE, maxSwordValue, setBitsMACRO, SOURCE_ID_MASK, SOURCE_ID_OFFSET_IN_DWORD, SOURCE_ID_OFFSET_OF_DWORD, and TRUE.
INLINE_D LOGIC_ret validFrameHdrV1 (FRAME_ptr frame_ptr)
Definition at line 123 of file CframeV1.h.
References FALSE, FORMAT_ERR_INVALID_HEADER, getFrameHdrLength(), setFrameError(), setFrameSuccess(), TRUE, and V1_FRAMEHDR_LENGTH.