Analysis Software: Jetv1 Class Reference
Jetv1 Class Reference
Jetv1.
#include <coresoftware/blob/master/simulation/g4simulation/g4jets/Jetv1.h>
Public Member Functions
Jetv1 ()
virtual ~Jetv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
float get_px () const
void set_px (float px)
float get_py () const
void set_py (float py)
float get_pz () const
void set_pz (float pz)
float get_e () const
void set_e (float e)
float get_p () const
float get_pt () const
float get_et () const
float get_eta () const
float get_phi () const
float get_mass () const
float get_mass2 () const
bool has_property (Jet::PROPERTY prop_id) const
float get_property (Jet::PROPERTY prop_id) const
void set_property (Jet::PROPERTY prop_id, float value)
void print_property (std::ostream &os) const
bool empty_comp () const
size_t size_comp () const
size_t count_comp (SRC source) const
void clear_comp ()
void insert_comp (SRC source, unsigned int compid)
size_t erase_comp (SRC source)
void erase_comp (Iter iter)
void erase_comp (Iter first, Iter last)
ConstIter begin_comp () const
ConstIter lower_bound_comp (SRC source) const
ConstIter upper_bound_comp (SRC source) const
ConstIter find (SRC source) const
ConstIter end_comp () const
Iter begin_comp ()
Iter lower_bound_comp (SRC source)
Iter upper_bound_comp (SRC source)
Iter find (SRC source)
Iter end_comp ()
Public Member Functions inherited from Jet
Jet ()
virtual ~Jet ()
ClassDef (Jet, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Types
typedef std::map
< Jet::PROPERTY, float > typ_property_map
Private Member Functions
ClassDef (Jetv1, 1)
Private Attributes
unsigned int _id
unique identifier within container
float _mom [3]
jet momentum vector (px,py,pz)
float _e
jet energy
typ_comp_ids _comp_ids
source id -> component id
typ_property_map _property_map
map that contains extra properties
Additional Inherited Members
Public Types inherited from Jet
enum ALGO { NONE = 0, ANTIKT = 1, KT = 2, CAMBRIDGE = 3 }
enum SRC {
VOID = 0, PARTICLE = 1, TRACK = 2, CEMC_TOWER = 3,
CEMC_CLUSTER = 4, HCALIN_TOWER = 5, HCALIN_CLUSTER = 6, HCALOUT_TOWER = 7,
HCALOUT_CLUSTER = 8, FEMC_TOWER = 9, FEMC_CLUSTER = 10, FHCAL_TOWER = 11,
FHCAL_CLUSTER = 12, CEMC_TOWER_RETOWER = 13, CEMC_TOWER_SUB1 = 14, HCALIN_TOWER_SUB1 = 15,
HCALOUT_TOWER_SUB1 = 16, CEMC_TOWER_SUB1CS = 17, HCALIN_TOWER_SUB1CS = 18, HCALOUT_TOWER_SUB1CS = 19,
HEPMC_IMPORT = 20
}
enum PROPERTY { prop_JetCharge = 1, prop_BFrac = 2, prop_SeedD = 3, prop_SeedItr = 4 }
typedef std::multimap
< Jet::SRC, unsigned int > typ_comp_ids
typedef
typ_comp_ids::const_iterator ConstIter
typedef typ_comp_ids::iterator Iter
Detailed Description
Jetv1.
Definition at line 24 of file Jetv1.h.
Member Typedef Documentation
typedef std::map<Jet::PROPERTY, float> Jetv1::typ_property_map private
Definition at line 116 of file Jetv1.h.
Constructor & Destructor Documentation
Jetv1::Jetv1 ()
Definition at line 18 of file Jetv1.cc.
References _mom, and i.
Referenced by CloneMe().
virtual Jetv1::~Jetv1 () inline virtual
Definition at line 28 of file Jetv1.h.
Member Function Documentation
ConstIter Jetv1::begin_comp () const inline virtual
Reimplemented from Jet.
Definition at line 91 of file Jetv1.h.
References _comp_ids.
Referenced by identify().
Iter Jetv1::begin_comp () inline virtual
Reimplemented from Jet.
Definition at line 97 of file Jetv1.h.
References _comp_ids.
Jetv1::ClassDef (Jetv1 , 1) private
void Jetv1::clear_comp () inline virtual
Reimplemented from Jet.
Definition at line 77 of file Jetv1.h.
References _comp_ids.
PHObject * Jetv1::CloneMe () const virtual
Virtual copy constructor.
Reimplemented from Jet.
Definition at line 65 of file Jetv1.cc.
References Jetv1().
size_t Jetv1::count_comp (SRC source) const inline virtual
Reimplemented from Jet.
Definition at line 75 of file Jetv1.h.
References _comp_ids.
bool Jetv1::empty_comp () const inline virtual
Reimplemented from Jet.
Definition at line 73 of file Jetv1.h.
References _comp_ids.
ConstIter Jetv1::end_comp () const inline virtual
Reimplemented from Jet.
Definition at line 95 of file Jetv1.h.
References _comp_ids.
Referenced by identify().
Iter Jetv1::end_comp () inline virtual
Reimplemented from Jet.
Definition at line 101 of file Jetv1.h.
References _comp_ids.
size_t Jetv1::erase_comp (SRC source) inline virtual
Reimplemented from Jet.
Definition at line 79 of file Jetv1.h.
References _comp_ids.
void Jetv1::erase_comp (Iter iter) inline virtual
Reimplemented from Jet.
Definition at line 80 of file Jetv1.h.
References _comp_ids.
void Jetv1::erase_comp (Iter first, Iter last) inline virtual
Reimplemented from Jet.
Definition at line 85 of file Jetv1.h.
References _comp_ids.
ConstIter Jetv1::find (SRC source) const inline virtual
Reimplemented from Jet.
Definition at line 94 of file Jetv1.h.
References _comp_ids.
Iter Jetv1::find (SRC source) inline virtual
Reimplemented from Jet.
Definition at line 100 of file Jetv1.h.
References _comp_ids.
float Jetv1::get_e () const inline virtual
Reimplemented from Jet.
Definition at line 51 of file Jetv1.h.
References _e.
Referenced by get_et(), get_mass2(), and identify().
float Jetv1::get_et () const virtual
Reimplemented from Jet.
Definition at line 81 of file Jetv1.cc.
References get_e(), get_p(), and get_pt().
float Jetv1::get_eta () const virtual
Reimplemented from Jet.
Definition at line 86 of file Jetv1.cc.
References get_pt(), and get_pz().
unsigned int Jetv1::get_id () const inline virtual
Reimplemented from Jet.
Definition at line 39 of file Jetv1.h.
References _id.
Referenced by identify().
float Jetv1::get_mass () const virtual
Reimplemented from Jet.
Definition at line 96 of file Jetv1.cc.
References get_mass2().
float Jetv1::get_mass2 () const virtual
Reimplemented from Jet.
Definition at line 106 of file Jetv1.cc.
References get_e(), get_px(), get_py(), and get_pz().
Referenced by get_mass().
float Jetv1::get_p () const virtual
Reimplemented from Jet.
Definition at line 71 of file Jetv1.cc.
References get_px(), get_py(), and get_pz().
Referenced by get_et().
float Jetv1::get_phi () const virtual
Reimplemented from Jet.
Definition at line 91 of file Jetv1.cc.
References get_px(), and get_py().
float Jetv1::get_property (Jet::PROPERTY prop_id) const virtual
Reimplemented from Jet.
Definition at line 121 of file Jetv1.cc.
References _property_map.
float Jetv1::get_pt () const virtual
Reimplemented from Jet.
Definition at line 76 of file Jetv1.cc.
References get_px(), and get_py().
Referenced by get_et(), and get_eta().
float Jetv1::get_px () const inline virtual
Reimplemented from Jet.
Definition at line 42 of file Jetv1.h.
References _mom.
Referenced by get_mass2(), get_p(), get_phi(), get_pt(), and identify().
float Jetv1::get_py () const inline virtual
Reimplemented from Jet.
Definition at line 45 of file Jetv1.h.
References _mom.
Referenced by get_mass2(), get_p(), get_phi(), get_pt(), and identify().
float Jetv1::get_pz () const inline virtual
Reimplemented from Jet.
Definition at line 48 of file Jetv1.h.
References _mom.
Referenced by get_eta(), get_mass2(), get_p(), and identify().
bool Jetv1::has_property (Jet::PROPERTY prop_id) const virtual
Reimplemented from Jet.
Definition at line 112 of file Jetv1.cc.
References _property_map.
void Jetv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from Jet.
Definition at line 28 of file Jetv1.cc.
References begin_comp(), end_comp(), get_e(), get_id(), get_px(), get_py(), get_pz(), and print_property().
void Jetv1::insert_comp (SRC source, unsigned int compid) inline virtual
Reimplemented from Jet.
Definition at line 78 of file Jetv1.h.
References _comp_ids.
int Jetv1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from Jet.
Definition at line 53 of file Jetv1.cc.
References _comp_ids, _e, _id, _mom, and i.
ConstIter Jetv1::lower_bound_comp (SRC source) const inline virtual
Reimplemented from Jet.
Definition at line 92 of file Jetv1.h.
References _comp_ids.
Iter Jetv1::lower_bound_comp (SRC source) inline virtual
Reimplemented from Jet.
Definition at line 98 of file Jetv1.h.
References _comp_ids.
void Jetv1::print_property (std::ostream & os) const virtual
Reimplemented from Jet.
Definition at line 135 of file Jetv1.cc.
References _property_map, Jet::prop_BFrac, and Jet::prop_JetCharge.
Referenced by identify().
void Jetv1::Reset () virtual
Clear Event.
Reimplemented from Jet.
Definition at line 44 of file Jetv1.cc.
References _comp_ids, _e, _id, _mom, _property_map, and i.
void Jetv1::set_e (float e) inline virtual
Reimplemented from Jet.
Definition at line 52 of file Jetv1.h.
References _e.
void Jetv1::set_id (unsigned int id) inline virtual
Reimplemented from Jet.
Definition at line 40 of file Jetv1.h.
References _id.
void Jetv1::set_property (Jet::PROPERTY prop_id, float value) virtual
Reimplemented from Jet.
Definition at line 130 of file Jetv1.cc.
References _property_map, and value.
void Jetv1::set_px (float px) inline virtual
Reimplemented from Jet.
Definition at line 43 of file Jetv1.h.
References _mom.
void Jetv1::set_py (float py) inline virtual
Reimplemented from Jet.
Definition at line 46 of file Jetv1.h.
References _mom.
void Jetv1::set_pz (float pz) inline virtual
Reimplemented from Jet.
Definition at line 49 of file Jetv1.h.
References _mom.
size_t Jetv1::size_comp () const inline virtual
Reimplemented from Jet.
Definition at line 74 of file Jetv1.h.
References _comp_ids.
ConstIter Jetv1::upper_bound_comp (SRC source) const inline virtual
Reimplemented from Jet.
Definition at line 93 of file Jetv1.h.
References _comp_ids.
Iter Jetv1::upper_bound_comp (SRC source) inline virtual
Reimplemented from Jet.
Definition at line 99 of file Jetv1.h.
References _comp_ids.
Member Data Documentation
typ_comp_ids Jetv1::_comp_ids private
source id -> component id
Definition at line 114 of file Jetv1.h.
Referenced by begin_comp(), clear_comp(), count_comp(), empty_comp(), end_comp(), erase_comp(), find(), insert_comp(), isValid(), lower_bound_comp(), Reset(), size_comp(), and upper_bound_comp().
float Jetv1::_e private
jet energy
Definition at line 111 of file Jetv1.h.
Referenced by get_e(), isValid(), Reset(), and set_e().
unsigned int Jetv1::_id private
unique identifier within container
Definition at line 105 of file Jetv1.h.
Referenced by get_id(), isValid(), Reset(), and set_id().
float Jetv1::_mom[3] private
jet momentum vector (px,py,pz)
Definition at line 108 of file Jetv1.h.
Referenced by get_px(), get_py(), get_pz(), isValid(), Jetv1(), Reset(), set_px(), set_py(), and set_pz().
typ_property_map Jetv1::_property_map private
map that contains extra properties
Definition at line 118 of file Jetv1.h.
Referenced by get_property(), has_property(), print_property(), Reset(), and set_property().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4jets/Jetv1.h
coresoftware/blob/master/simulation/g4simulation/g4jets/Jetv1.cc