Analysis Software: macros/blob/master/macros/g4simulations/G4_FwdJets.C File Reference
G4_FwdJets.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4jets/FastJetAlgo.h>
#include <g4jets/JetReco.h>
#include <g4jets/TowerJetInput.h>
#include <g4eval/JetEvaluator.h>
Functions
void Jet_FwdRecoInit ()
void Jet_FwdReco (int verbosity=0)
void Jet_FwdEval (std::string outfilename="g4fwdjets_eval.root", int verbosity=0)
Function Documentation
void Jet_FwdEval (std::string outfilename = "g4fwdjets_eval.root", int verbosity = 0)
Definition at line 57 of file G4_FwdJets.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), and Fun4All_G4_fsPHENIX_pi0().
void Jet_FwdReco (int verbosity = 0)
Definition at line 14 of file G4_FwdJets.C.
References JetReco::add_algo(), JetReco::add_input(), Jet::ANTIKT, Jet::CEMC_TOWER, Jet::FEMC_TOWER, Jet::FHCAL_TOWER, Jet::HCALIN_TOWER, Jet::HCALOUT_TOWER, Fun4AllServer::instance(), Jet::PARTICLE, Fun4AllServer::registerSubsystem(), JetReco::set_algo_node(), JetReco::set_input_node(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ_analysis(), Fun4All_G4_EICDetector_LQ_analysis_nf(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), and Fun4All_G4_fsPHENIX_pi0().
void Jet_FwdRecoInit ()
Definition at line 12 of file G4_FwdJets.C.