Analysis Software: EMCalLikelihood Class Reference
EMCalLikelihood Class Reference
EMCalLikelihood.
#include <analysis/blob/master/EMCal-analysis/EMCalAna/EMCalLikelihood.h>
Public Member Functions
EMCalLikelihood (const std::string &filename)
virtual ~EMCalLikelihood ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Fun4AllHistoManager * get_HistoManager ()
void ApplyEMCalGanging (EMCalTrk *trk)
void UpdateEnergyDeposition (EMCalTrk *trk)
void UpdateEnergyDepositionLikelihood (EMCalTrk *trk)
TH2 * get_h2_Edep_Distribution_e () const
void set_h2_Edep_Distribution_e (TH2 *h2EdepDistributionE)
TH2 * get_h2_Edep_Distribution_pi () const
void set_h2_Edep_Distribution_pi (TH2 *h2EdepDistributionPi)
double get_center_cemc_ieta () const
void set_center_cemc_ieta (double centerCemcIeta)
double get_center_cemc_iphi () const
void set_center_cemc_iphi (double centerCemcIphi)
double get_center_hcalin_ieta () const
void set_center_hcalin_ieta (double centerHcalinIeta)
double get_center_hcalin_iphi () const
void set_center_hcalin_iphi (double centerHcalinIphi)
double get_width_cemc_ieta () const
void set_width_cemc_ieta (double widthCemcIeta)
double get_width_cemc_iphi () const
void set_width_cemc_iphi (double widthCemcIphi)
double get_width_hcalin_ieta () const
void set_width_hcalin_ieta (double widthHcalinIeta)
double get_width_hcalin_iphi () const
void set_width_hcalin_iphi (double widthHcalinIphi)
void do_ganging (unsigned int eta, unsigned int phi)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
std::string _filename
int _ievent
EMCalTrk * _trk
double center_cemc_iphi
double center_cemc_ieta
double center_hcalin_iphi
double center_hcalin_ieta
double width_cemc_iphi
double width_cemc_ieta
double width_hcalin_iphi
double width_hcalin_ieta
TH2 * h2_Edep_Distribution_e
TH2 * h2_Edep_Distribution_pi
TH1 * h1_ep_Distribution_e
TH1 * h1_ep_Distribution_pi
bool _do_ganging
std::pair< unsigned int,
unsigned int > _ganging_size
eta and phi ganging
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
EMCalLikelihood.
Definition at line 31 of file EMCalLikelihood.h.
Constructor & Destructor Documentation
EMCalLikelihood::EMCalLikelihood (const std::string & filename)
Definition at line 50 of file EMCalLikelihood.C.
EMCalLikelihood::~EMCalLikelihood () virtual
Definition at line 63 of file EMCalLikelihood.C.
Member Function Documentation
void EMCalLikelihood::ApplyEMCalGanging (EMCalTrk * trk)
Definition at line 262 of file EMCalLikelihood.C.
References _ganging_size, assert, EMCalTrk::cemc_energy, EMCalTrk::cemc_ieta, EMCalTrk::cemc_iphi, get_HistoManager(), Fun4AllHistoManager::getHisto(), EMCalTrk::gpx, EMCalTrk::gpy, EMCalTrk::gpz, EMCalTrk::gvx, EMCalTrk::gvy, EMCalTrk::gvz, and EMCalTrk::Max_N_Tower.
Referenced by process_event().
void EMCalLikelihood::do_ganging (unsigned int eta, unsigned int phi) inline
Definition at line 179 of file EMCalLikelihood.h.
References _do_ganging, _ganging_size, and phi.
Referenced by Fun4All_EMCalLikelihood().
int EMCalLikelihood::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 103 of file EMCalLikelihood.C.
References _filename, assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, and Fun4AllHistoManager::nHistos().
double EMCalLikelihood::get_center_cemc_ieta () const inline
Definition at line 84 of file EMCalLikelihood.h.
References center_cemc_ieta.
double EMCalLikelihood::get_center_cemc_iphi () const inline
Definition at line 96 of file EMCalLikelihood.h.
References center_cemc_iphi.
double EMCalLikelihood::get_center_hcalin_ieta () const inline
Definition at line 108 of file EMCalLikelihood.h.
References center_hcalin_ieta.
double EMCalLikelihood::get_center_hcalin_iphi () const inline
Definition at line 120 of file EMCalLikelihood.h.
References center_hcalin_iphi.
TH2* EMCalLikelihood::get_h2_Edep_Distribution_e () const inline
Definition at line 60 of file EMCalLikelihood.h.
References h2_Edep_Distribution_e.
TH2* EMCalLikelihood::get_h2_Edep_Distribution_pi () const inline
Definition at line 72 of file EMCalLikelihood.h.
References h2_Edep_Distribution_pi.
Fun4AllHistoManager * EMCalLikelihood::get_HistoManager ()
Definition at line 241 of file EMCalLikelihood.C.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by ApplyEMCalGanging(), End(), and Init().
double EMCalLikelihood::get_width_cemc_ieta () const inline
Definition at line 132 of file EMCalLikelihood.h.
References width_cemc_ieta.
double EMCalLikelihood::get_width_cemc_iphi () const inline
Definition at line 144 of file EMCalLikelihood.h.
References width_cemc_iphi.
double EMCalLikelihood::get_width_hcalin_ieta () const inline
Definition at line 156 of file EMCalLikelihood.h.
References width_hcalin_ieta.
double EMCalLikelihood::get_width_hcalin_iphi () const inline
Definition at line 168 of file EMCalLikelihood.h.
References width_hcalin_iphi.
int EMCalLikelihood::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 118 of file EMCalLikelihood.C.
References _filename, assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), h1_ep_Distribution_e, h1_ep_Distribution_pi, h2_Edep_Distribution_e, h2_Edep_Distribution_pi, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), x, and y.
int EMCalLikelihood::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 69 of file EMCalLikelihood.C.
References _ievent, _trk, Fun4AllReturnCodes::ABORTRUN, assert, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), Fun4AllBase::Name(), and PHWHERE.
int EMCalLikelihood::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 220 of file EMCalLikelihood.C.
References _do_ganging, _ievent, _trk, ApplyEMCalGanging(), Fun4AllReturnCodes::EVENT_OK, h2_Edep_Distribution_e, h2_Edep_Distribution_pi, UpdateEnergyDeposition(), and UpdateEnergyDepositionLikelihood().
void EMCalLikelihood::set_center_cemc_ieta (double centerCemcIeta) inline
Definition at line 90 of file EMCalLikelihood.h.
References center_cemc_ieta.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_center_cemc_iphi (double centerCemcIphi) inline
Definition at line 102 of file EMCalLikelihood.h.
References center_cemc_iphi.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_center_hcalin_ieta (double centerHcalinIeta) inline
Definition at line 114 of file EMCalLikelihood.h.
References center_hcalin_ieta.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_center_hcalin_iphi (double centerHcalinIphi) inline
Definition at line 126 of file EMCalLikelihood.h.
References center_hcalin_iphi.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_h2_Edep_Distribution_e (TH2 * h2EdepDistributionE) inline
Definition at line 66 of file EMCalLikelihood.h.
References h2_Edep_Distribution_e.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_h2_Edep_Distribution_pi (TH2 * h2EdepDistributionPi) inline
Definition at line 78 of file EMCalLikelihood.h.
References h2_Edep_Distribution_pi.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_width_cemc_ieta (double widthCemcIeta) inline
Definition at line 138 of file EMCalLikelihood.h.
References width_cemc_ieta.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_width_cemc_iphi (double widthCemcIphi) inline
Definition at line 150 of file EMCalLikelihood.h.
References width_cemc_iphi.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_width_hcalin_ieta (double widthHcalinIeta) inline
Definition at line 162 of file EMCalLikelihood.h.
References width_hcalin_ieta.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::set_width_hcalin_iphi (double widthHcalinIphi) inline
Definition at line 174 of file EMCalLikelihood.h.
References width_hcalin_iphi.
Referenced by Fun4All_EMCalLikelihood().
void EMCalLikelihood::UpdateEnergyDeposition (EMCalTrk * trk)
Definition at line 356 of file EMCalLikelihood.C.
References assert, EMCalTrk::cemc_energy, EMCalTrk::cemc_ieta, EMCalTrk::cemc_iphi, EMCalTrk::cemc_radius, EMCalTrk::cemc_sum_energy, EMCalTrk::cemc_sum_n_tower, center_cemc_ieta, center_cemc_iphi, center_hcalin_ieta, center_hcalin_iphi, EMCalTrk::hcalin_energy, EMCalTrk::hcalin_ieta, EMCalTrk::hcalin_iphi, EMCalTrk::hcalin_radius, EMCalTrk::hcalin_sum_energy, EMCalTrk::hcalin_sum_n_tower, EMCalTrk::Max_N_Tower, width_cemc_ieta, width_cemc_iphi, width_hcalin_ieta, and width_hcalin_iphi.
Referenced by process_event().
void EMCalLikelihood::UpdateEnergyDepositionLikelihood (EMCalTrk * trk)
Definition at line 404 of file EMCalLikelihood.C.
References assert, EMCalTrk::get_ep(), h1_ep_Distribution_e, h1_ep_Distribution_pi, h2_Edep_Distribution_e, h2_Edep_Distribution_pi, EMCalTrk::hcalin_sum_energy, EMCalTrk::ll_edep_e, EMCalTrk::ll_edep_h, EMCalTrk::ll_ep_e, EMCalTrk::ll_ep_h, and Fun4AllBase::Name().
Referenced by process_event().
Member Data Documentation
bool EMCalLikelihood::_do_ganging private
Definition at line 208 of file EMCalLikelihood.h.
Referenced by do_ganging(), and process_event().
std::string EMCalLikelihood::_filename private
Definition at line 187 of file EMCalLikelihood.h.
Referenced by End(), and Init().
std::pair<unsigned int, unsigned int> EMCalLikelihood::_ganging_size private
eta and phi ganging
Definition at line 211 of file EMCalLikelihood.h.
Referenced by ApplyEMCalGanging(), and do_ganging().
int EMCalLikelihood::_ievent private
Definition at line 189 of file EMCalLikelihood.h.
Referenced by InitRun(), and process_event().
EMCalTrk* EMCalLikelihood::_trk private
Definition at line 191 of file EMCalLikelihood.h.
Referenced by InitRun(), and process_event().
double EMCalLikelihood::center_cemc_ieta private
Definition at line 194 of file EMCalLikelihood.h.
Referenced by get_center_cemc_ieta(), set_center_cemc_ieta(), and UpdateEnergyDeposition().
double EMCalLikelihood::center_cemc_iphi private
Definition at line 193 of file EMCalLikelihood.h.
Referenced by get_center_cemc_iphi(), set_center_cemc_iphi(), and UpdateEnergyDeposition().
double EMCalLikelihood::center_hcalin_ieta private
Definition at line 196 of file EMCalLikelihood.h.
Referenced by get_center_hcalin_ieta(), set_center_hcalin_ieta(), and UpdateEnergyDeposition().
double EMCalLikelihood::center_hcalin_iphi private
Definition at line 195 of file EMCalLikelihood.h.
Referenced by get_center_hcalin_iphi(), set_center_hcalin_iphi(), and UpdateEnergyDeposition().
TH1* EMCalLikelihood::h1_ep_Distribution_e private
Definition at line 205 of file EMCalLikelihood.h.
Referenced by Init(), and UpdateEnergyDepositionLikelihood().
TH1* EMCalLikelihood::h1_ep_Distribution_pi private
Definition at line 206 of file EMCalLikelihood.h.
Referenced by Init(), and UpdateEnergyDepositionLikelihood().
TH2* EMCalLikelihood::h2_Edep_Distribution_e private
Definition at line 203 of file EMCalLikelihood.h.
Referenced by get_h2_Edep_Distribution_e(), Init(), process_event(), set_h2_Edep_Distribution_e(), and UpdateEnergyDepositionLikelihood().
TH2* EMCalLikelihood::h2_Edep_Distribution_pi private
Definition at line 204 of file EMCalLikelihood.h.
Referenced by get_h2_Edep_Distribution_pi(), Init(), process_event(), set_h2_Edep_Distribution_pi(), and UpdateEnergyDepositionLikelihood().
double EMCalLikelihood::width_cemc_ieta private
Definition at line 199 of file EMCalLikelihood.h.
Referenced by get_width_cemc_ieta(), set_width_cemc_ieta(), and UpdateEnergyDeposition().
double EMCalLikelihood::width_cemc_iphi private
Definition at line 198 of file EMCalLikelihood.h.
Referenced by get_width_cemc_iphi(), set_width_cemc_iphi(), and UpdateEnergyDeposition().
double EMCalLikelihood::width_hcalin_ieta private
Definition at line 201 of file EMCalLikelihood.h.
Referenced by get_width_hcalin_ieta(), set_width_hcalin_ieta(), and UpdateEnergyDeposition().
double EMCalLikelihood::width_hcalin_iphi private
Definition at line 200 of file EMCalLikelihood.h.
Referenced by get_width_hcalin_iphi(), set_width_hcalin_iphi(), and UpdateEnergyDeposition().
The documentation for this class was generated from the following files:
analysis/blob/master/EMCal-analysis/EMCalAna/EMCalLikelihood.h
analysis/blob/master/EMCal-analysis/EMCalAna/EMCalLikelihood.C