Analysis Software: Fun4AllHepMCPileupInputManager Class Reference
Fun4AllHepMCPileupInputManager Class Reference
#include <coresoftware/blob/master/generators/phhepmc/Fun4AllHepMCPileupInputManager.h>
Public Member Functions
Fun4AllHepMCPileupInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
virtual ~Fun4AllHepMCPileupInputManager ()
int run (const int nevents=0)
void set_time_window (double past_nsec, double future_nsec)
past times are negative, future times are positive
void set_collision_rate (double Hz)
collision rate in Hz
void set_time_between_crossings (double nsec)
time between bunch crossing in ns
Public Member Functions inherited from Fun4AllHepMCInputManager
Fun4AllHepMCInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
virtual ~Fun4AllHepMCInputManager ()
virtual int fileopen (const std::string &filenam)
virtual int fileclose ()
void ReadOscar (const int i=1)
virtual void Print (const std::string &what="ALL") const
virtual int PushBackEvents (const int i)
int SyncIt (const SyncObject *)
int GetSyncObject (SyncObject **)
int NoSyncPushBackEvents (const int nevt)
HepMC::GenEvent * ConvertFromOscar ()
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
Public Member Functions inherited from Fun4AllInputManager
virtual ~Fun4AllInputManager ()
virtual int ReadInRunNode (PHCompositeNode *)
std::string FileName () const
void FileName (const std::string &fn)
virtual int BranchSelect (const std::string &, const int)
virtual int setBranches ()
virtual int skip (const int nevt)
int AddFile (const std::string &filename)
int AddListFile (const std::string &filename, const int do_it=0)
int registerSubsystem (SubsysReco *subsystem)
virtual int RejectEvent ()
void Repeat (const int i=-1)
virtual void setSyncManager (Fun4AllSyncManager *master)
int ResetFileList ()
virtual int ResetEvent ()
virtual void SetRunNumber (const int runno)
virtual int RunNumber () const
void AddToFileOpened (const std::string &filename)
std::pair< std::list
< std::string >
::const_iterator, std::list
< std::string >
::const_iterator > FileOpenListBeginEnd ()
std::string InputNode ()
void InputNode (const std::string &innode)
std::string TopNodeName () const
bool FileListEmpty () const
virtual int IsOpen () const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
double _min_integration_time
past times are negative, future times are positive
double _max_integration_time
double _collision_rate
collision rate in Hz
double _time_between_crossings
time between bunch crossing in ns
double _ave_coll_per_crossing
int _min_crossing
int _max_crossing
bool _first_run
gsl_rng * RandomGenerator
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from Fun4AllInputManager
Fun4AllInputManager (const std::string &name="DUMMY", const std::string &nodename="DST", const std::string &topnodename="TOP")
void UpdateFileList ()
int OpenNextFile ()
void IsOpen (const int i)
Fun4AllSyncManager * MySyncManager ()
Protected Attributes inherited from Fun4AllHepMCInputManager
int events_total
int events_thisfile
int readoscar
std::string filename
std::string topNodeName
PHCompositeNode * topNode
HepMC::IO_GenEvent * ascii_in
HepMC::GenEvent * evt
HepMC::GenEvent * save_evt
std::ifstream * filestream
std::istream * unzipstream
std::ifstream theOscarFile
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
boost::iostreams::filtering_streambuf
< boost::iostreams::input > zinbuffer
Detailed Description
Generate pile up collisions based on beam parameter If set_embedding_id(i) with a negative number or 0, the pile up event will be inserted with increasing positive embedding_id. This is the default operation mode. If set_embedding_id(i) with a positive number, the pile up event will be inserted with increasing positive embedding_id. This would be a strange way to use pile up.
Definition at line 15 of file Fun4AllHepMCPileupInputManager.h.
Constructor & Destructor Documentation
Fun4AllHepMCPileupInputManager::Fun4AllHepMCPileupInputManager (const std::string & name = "DUMMY", const std::string & nodename = "DST", const std::string & topnodename = "TOP")
repeatedly read the input file
If set_embedding_id(i) with a negative number or 0, the pile up event will be inserted with increasing positive embedding_id. This is the default operation mode.
setup default beam diamond to ~Run14 level
Definition at line 25 of file Fun4AllHepMCPileupInputManager.cc.
References PHHepMCGenHelper::Gaus, Fun4AllHepMCInputManager::hepmc_helper, RandomGenerator, Fun4AllInputManager::Repeat(), TauVsDIS_MachineLearning_Differentiation::seed, PHHepMCGenHelper::set_embedding_id(), PHHepMCGenHelper::set_vertex_distribution_function(), PHHepMCGenHelper::set_vertex_distribution_mean(), and PHHepMCGenHelper::set_vertex_distribution_width().
Fun4AllHepMCPileupInputManager::~Fun4AllHepMCPileupInputManager () virtual
Definition at line 58 of file Fun4AllHepMCPileupInputManager.cc.
References RandomGenerator.
Member Function Documentation
int Fun4AllHepMCPileupInputManager::run (const int nevents = 0) virtual
If set_embedding_id(i) with a positive number, the pile up event will be inserted with increasing positive embedding_id. This would be a strange way to use pile up.
If set_embedding_id(i) with a negative number or 0, the pile up event will be inserted with increasing positive embedding_id. This is the default operation mode.
Reimplemented from Fun4AllHepMCInputManager.
Definition at line 63 of file Fun4AllHepMCPileupInputManager.cc.
References _ave_coll_per_crossing, _collision_rate, _first_run, _max_crossing, _max_integration_time, _min_crossing, _min_integration_time, _time_between_crossings, PHHepMCGenEvent::addEvent(), Fun4AllHepMCInputManager::ascii_in, assert, Fun4AllHepMCInputManager::ConvertFromOscar(), Fun4AllSyncManager::CurrentEvent(), Fun4AllReturnCodes::EVENT_OK, Fun4AllHepMCInputManager::events_thisfile, Fun4AllHepMCInputManager::events_total, Fun4AllHepMCInputManager::evt, Fun4AllHepMCInputManager::fileclose(), Fun4AllInputManager::FileListEmpty(), genevent(), PHHepMCGenHelper::get_embedding_id(), PHHepMCGenHelper::get_geneventmap(), Fun4AllHepMCInputManager::hepmc_helper, PHHepMCGenEventMap::insert_active_event(), PHHepMCGenEventMap::insert_background_event(), Fun4AllInputManager::IsOpen(), PHHepMCGenHelper::move_vertex(), PHHepMCGenEvent::moveVertex(), Fun4AllInputManager::MySyncManager(), Fun4AllBase::Name(), Fun4AllInputManager::OpenNextFile(), RandomGenerator, Fun4AllHepMCInputManager::readoscar, Fun4AllInputManager::RejectEvent(), Fun4AllInputManager::ResetEvent(), Fun4AllHepMCInputManager::save_evt, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
void Fun4AllHepMCPileupInputManager::set_collision_rate (double Hz) inline
collision rate in Hz
Definition at line 33 of file Fun4AllHepMCPileupInputManager.h.
References _collision_rate.
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), and Fun4All_G4_sPHENIX_truthphotonjet().
void Fun4AllHepMCPileupInputManager::set_time_between_crossings (double nsec) inline
time between bunch crossing in ns
Definition at line 35 of file Fun4AllHepMCPileupInputManager.h.
References _time_between_crossings.
void Fun4AllHepMCPileupInputManager::set_time_window (double past_nsec, double future_nsec) inline
past times are negative, future times are positive
Definition at line 26 of file Fun4AllHepMCPileupInputManager.h.
References _max_integration_time, and _min_integration_time.
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), and Fun4All_G4_sPHENIX_truthphotonjet().
Member Data Documentation
double Fun4AllHepMCPileupInputManager::_ave_coll_per_crossing private
Definition at line 47 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run().
double Fun4AllHepMCPileupInputManager::_collision_rate private
collision rate in Hz
Definition at line 42 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run(), and set_collision_rate().
bool Fun4AllHepMCPileupInputManager::_first_run private
Definition at line 51 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run().
int Fun4AllHepMCPileupInputManager::_max_crossing private
Definition at line 49 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run().
double Fun4AllHepMCPileupInputManager::_max_integration_time private
Definition at line 40 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run(), and set_time_window().
int Fun4AllHepMCPileupInputManager::_min_crossing private
Definition at line 48 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run().
double Fun4AllHepMCPileupInputManager::_min_integration_time private
past times are negative, future times are positive
Definition at line 39 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run(), and set_time_window().
double Fun4AllHepMCPileupInputManager::_time_between_crossings private
time between bunch crossing in ns
Definition at line 44 of file Fun4AllHepMCPileupInputManager.h.
Referenced by run(), and set_time_between_crossings().
gsl_rng* Fun4AllHepMCPileupInputManager::RandomGenerator private
Definition at line 54 of file Fun4AllHepMCPileupInputManager.h.
Referenced by Fun4AllHepMCPileupInputManager(), run(), and ~Fun4AllHepMCPileupInputManager().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/phhepmc/Fun4AllHepMCPileupInputManager.h
coresoftware/blob/master/generators/phhepmc/Fun4AllHepMCPileupInputManager.cc