Analysis Software: oncsSub_id4evt Class Reference
oncsSub_id4evt Class Reference
#include <online_distribution/blob/master/newbasic/oncsSub_id4evt.h>
Public Member Functions
oncsSub_id4evt (subevtdata_ptr)
Public Member Functions inherited from oncsSubevent_w4
oncsSubevent_w4 (subevtdata_ptr)
virtual void dump (OSTREAM &os=COUT)
virtual void gdump (const int how=EVT_HEXADECIMAL, OSTREAM &os=COUT) const
Public Member Functions inherited from oncsSubevent
oncsSubevent (subevtdata_ptr data)
virtual ~oncsSubevent ()
virtual int getLength () const
virtual int getIdentifier () const
get the packet identifier
virtual int getHitFormat () const
get the hit format; in case of unformatted get the encoding scheme.
virtual int getPadding () const
get the number of padding units in the packet data.
virtual int getDataLength () const
get what the name says...
virtual int getStructure () const
get the structure of the packet data; unformatted, hitlist, etc.
virtual int getDebugLength () const
get the length of the debug block
virtual int getErrorLength () const
virtual void identify (OSTREAM &=COUT) const
int iValue (const int)
iValue returns the value of a given channel as an int.
int iValue (const int, const char *)
int iValue (const int, const int)
int iValue (const int, const int, const char *)
int iValue (const int channel, const int iy, const int iz)
int iValue (const int channel, const int iy, const int iz, const char *what)
virtual float rValue (const int)
virtual float rValue (const int, const char *)
virtual float rValue (const int, const int)
virtual int getArraylength (const char *)
virtual int fillIntArray (int[], const int, int *, const char *what="")
virtual int fillFloatArray (float[], const int, int *, const char *what="")
fillFloatArray fills an array of floats
virtual int * getIntArray (int *, const char *what="")
virtual float * getFloatArray (int *, const char *what="")
getFloatArray creates and returns an array of floats
virtual int is_pointer_type () const
find out what type (pointer- or data based) packet object we have
virtual int convert ()
convert from pointer- to data based object, if it is already data-based, do nothing.
int setInternalParameter (const int p1=0, const int p2=0, const char *what="")
Public Member Functions inherited from Packet
virtual ~Packet ()
the virtual destructor
virtual double dValue (const int channel)
virtual double dValue (const int channel, const char *what)
virtual double dValue (const int channel, const int iy)
virtual long long lValue (const int channel)
virtual long long lValue (const int channel, const char *what)
virtual long long lValue (const int channel, const int iy)
virtual void * pValue (const int chan)
virtual void * pValue (const int chan, const char *what)
virtual void * pValue (const int chan, const int iy)
virtual void identify (std::ostream &os=std::cout) const =0
see below for comments
virtual void fullIdentify (std::ostream &os=std::cout) const
write an indepth identification message to the supplied OSTREAM.
virtual void dump (std::ostream &os=std::cout)=0
virtual void gdump (const int how=EVT_HEXADECIMAL, std::ostream &os=std::cout) const =0
virtual int getCheckSumStatus () const
virtual int copyMe (int[], const int maxlength) const
Protected Member Functions
int * decode (int *)
Additional Inherited Members
Protected Attributes inherited from oncsSubevent
subevtdata_ptr SubeventHdr
int data1_length
int data2_length
int data3_length
int data4_length
int * decoded_data1
int * decoded_data2
int * decoded_data3
int * decoded_data4
int is_data_type
Detailed Description
Definition at line 7 of file oncsSub_id4evt.h.
Constructor & Destructor Documentation
oncsSub_id4evt::oncsSub_id4evt (subevtdata_ptr data)
Definition at line 3 of file oncsSub_id4evt.cc.
Member Function Documentation
int * oncsSub_id4evt::decode (int * nwout) protected virtual
Reimplemented from oncsSubevent_w4.
Definition at line 6 of file oncsSub_id4evt.cc.
References subevt_data::data, decode_id4evt(), dlength, oncsSubevent::getLength(), oncsSubevent::getPadding(), i, k, MAX_OUTLENGTH, and oncsSubevent::SubeventHdr.
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsSub_id4evt.h
online_distribution/blob/master/newbasic/oncsSub_id4evt.cc