Analysis Software: PHGenFit::SpacepointMeasurement Class Reference
PHGenFit::SpacepointMeasurement Class Reference
#include <coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h>
Public Member Functions
SpacepointMeasurement (const TVector3 &pos, const double resolution)
SpacepointMeasurement (const TVector3 &pos, const TMatrixDSym &cov)
void init (const TVector3 &pos, const TMatrixDSym &cov)
~SpacepointMeasurement ()
dtor
Public Member Functions inherited from PHGenFit::Measurement
Measurement ()
ctor
~Measurement ()
dtor
genfit::AbsMeasurement * getMeasurement ()
unsigned int get_cluster_ID () const
void set_cluster_ID (unsigned int clusterId)
TrkrDefs::cluskey get_cluster_key () const
void set_cluster_key (TrkrDefs::cluskey clusterkey)
Additional Inherited Members
Protected Attributes inherited from PHGenFit::Measurement
genfit::AbsMeasurement * _measurement
unsigned int _clusterID
TrkrDefs::cluskey _clusterkey
Detailed Description
Definition at line 18 of file SpacepointMeasurement.h.
Constructor & Destructor Documentation
PHGenFit::SpacepointMeasurement::SpacepointMeasurement (const TVector3 & pos, const double resolution)
Ctor
Parameters
pos measurement position
resolution standard dev for diagnal elements of the cov, other elements are zero
Definition at line 39 of file SpacepointMeasurement.cc.
References init().
PHGenFit::SpacepointMeasurement::SpacepointMeasurement (const TVector3 & pos, const TMatrixDSym & cov)
Ctor
Parameters
pos measurement position
covariance matrix
Definition at line 54 of file SpacepointMeasurement.cc.
References init().
PHGenFit::SpacepointMeasurement::~SpacepointMeasurement ()
dtor
Definition at line 59 of file SpacepointMeasurement.cc.
Member Function Documentation
void PHGenFit::SpacepointMeasurement::init (const TVector3 & pos, const TMatrixDSym & cov)
Definition at line 19 of file SpacepointMeasurement.cc.
References PHGenFit::Measurement::_measurement, i, and j.
Referenced by SpacepointMeasurement().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc