Analysis Software: RawTower_Prototype2 Class Reference
RawTower_Prototype2 Class Reference
#include <prototype/blob/master/offline/packages/Prototype2/RawTower_Prototype2.h>
Public Types
enum { NSAMPLES = PROTOTYPE2_FEM::NSAMPLES }
typedef float signal_type
Public Types inherited from RawTower
typedef unsigned long long CellKeyType
key type for cell map which should be consistent with CellKeyType
typedef std::map< CellKeyType,
float > CellMap
typedef CellMap::iterator CellIterator
typedef CellMap::const_iterator CellConstIterator
typedef std::pair
< CellIterator, CellIterator > CellRange
typedef std::pair
< CellConstIterator,
CellConstIterator > CellConstRange
typedef std::map< int, float > ShowerMap
typedef ShowerMap::iterator ShowerIterator
typedef ShowerMap::const_iterator ShowerConstIterator
typedef std::pair
< ShowerIterator,
ShowerIterator > ShowerRange
typedef std::pair
< ShowerConstIterator,
ShowerConstIterator > ShowerConstRange
Public Member Functions
RawTower_Prototype2 ()
RawTower_Prototype2 (const RawTower &tower)
RawTower_Prototype2 (RawTowerDefs::keytype id)
RawTower_Prototype2 (const unsigned int icol, const unsigned int irow)
RawTower_Prototype2 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
virtual ~RawTower_Prototype2 ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
void set_id (RawTowerDefs::keytype id)
RawTowerDefs::keytype get_id () const
int get_bineta () const
int get_binphi () const
int get_column () const
int get_row () const
double get_energy () const
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
void set_energy (const double e)
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
float get_time () const
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_time (const float t)
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
void set_signal_samples (int i, signal_type sig)
signal_type get_signal_samples (int i) const
void set_HBD_channel_number (int i)
int get_HBD_channel_number () const
double get_energy_power_law_exp (int verbosity=0)
Public Member Functions inherited from RawTower
virtual ~RawTower ()
virtual void set_key (RawTowerDefs::keytype id)
virtual RawTowerDefs::keytype get_key () const
virtual bool empty_g4cells () const
virtual size_t size_g4cells () const
virtual CellConstRange get_g4cells () const
virtual CellIterator find_g4cell (CellKeyType id)
virtual CellConstIterator find_g4cell (CellKeyType id) const
virtual void add_ecell (const CellKeyType g4cellid, const float ecell)
virtual void clear_g4cells ()
virtual bool empty_g4showers () const
virtual size_t size_g4showers () const
virtual ShowerConstRange get_g4showers () const
virtual ShowerIterator find_g4shower (int id)
virtual ShowerConstIterator find_g4shower (int id) const
virtual void add_eshower (const int g4showerid, const float eshower)
virtual void clear_g4showers ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype towerid
double energy
float time
signal_type signal_samples [NSAMPLES]
int HBD_channel
Additional Inherited Members
Protected Member Functions inherited from RawTower
RawTower ()
Detailed Description
Definition at line 13 of file RawTower_Prototype2.h.
Member Typedef Documentation
typedef float RawTower_Prototype2::signal_type
Definition at line 46 of file RawTower_Prototype2.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
NSAMPLES
Definition at line 42 of file RawTower_Prototype2.h.
Constructor & Destructor Documentation
RawTower_Prototype2::RawTower_Prototype2 ()
Definition at line 16 of file RawTower_Prototype2.cc.
References NSAMPLES, and signal_samples.
RawTower_Prototype2::RawTower_Prototype2 (const RawTower & tower)
Definition at line 26 of file RawTower_Prototype2.cc.
References energy, RawTower::get_energy(), RawTower::get_id(), RawTower::get_time(), HBD_channel, NSAMPLES, signal_samples, time, and towerid.
RawTower_Prototype2::RawTower_Prototype2 (RawTowerDefs::keytype id)
Definition at line 35 of file RawTower_Prototype2.cc.
References NSAMPLES, and signal_samples.
RawTower_Prototype2::RawTower_Prototype2 (const unsigned int icol, const unsigned int irow)
Definition at line 44 of file RawTower_Prototype2.cc.
References RawTowerDefs::encode_towerid(), RawTowerDefs::NONE, NSAMPLES, signal_samples, and towerid.
RawTower_Prototype2::RawTower_Prototype2 (const RawTowerDefs::CalorimeterId caloid, const unsigned int ieta, const unsigned int iphi)
Definition at line 55 of file RawTower_Prototype2.cc.
References RawTowerDefs::encode_towerid(), NSAMPLES, signal_samples, and towerid.
virtual RawTower_Prototype2::~RawTower_Prototype2 () inline virtual
Definition at line 22 of file RawTower_Prototype2.h.
Member Function Documentation
int RawTower_Prototype2::get_bineta () const inline virtual
Reimplemented from RawTower.
Definition at line 30 of file RawTower_Prototype2.h.
References RawTowerDefs::decode_index1(), and towerid.
Referenced by identify().
int RawTower_Prototype2::get_binphi () const inline virtual
Reimplemented from RawTower.
Definition at line 31 of file RawTower_Prototype2.h.
References RawTowerDefs::decode_index2(), and towerid.
Referenced by identify().
int RawTower_Prototype2::get_column () const inline virtual
Reimplemented from RawTower.
Definition at line 32 of file RawTower_Prototype2.h.
References RawTowerDefs::decode_index1(), and towerid.
Referenced by CaloCalibration::process_event().
double RawTower_Prototype2::get_energy () const inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 34 of file RawTower_Prototype2.h.
References energy.
Referenced by identify(), isValid(), CaloCalibration::process_event(), and Prototype2DSTReader::process_event().
double RawTower_Prototype2::get_energy_power_law_exp (int verbosity = 0)
Definition at line 98 of file RawTower_Prototype2.cc.
References i, NSAMPLES, PROTOTYPE2_FEM::SampleFit_PowerLawExp(), and signal_samples.
int RawTower_Prototype2::get_HBD_channel_number () const inline
Definition at line 51 of file RawTower_Prototype2.h.
References HBD_channel.
RawTowerDefs::keytype RawTower_Prototype2::get_id () const inline virtual
Reimplemented from RawTower.
Definition at line 29 of file RawTower_Prototype2.h.
References towerid.
int RawTower_Prototype2::get_row () const inline virtual
Reimplemented from RawTower.
Definition at line 33 of file RawTower_Prototype2.h.
References RawTowerDefs::decode_index2(), and towerid.
Referenced by CaloCalibration::process_event().
RawTower_Prototype2::signal_type RawTower_Prototype2::get_signal_samples (int i) const
Definition at line 91 of file RawTower_Prototype2.cc.
References assert, i, NSAMPLES, and signal_samples.
Referenced by CaloCalibration::process_event(), and CaloUnpackPRDF::process_event().
float RawTower_Prototype2::get_time () const inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 36 of file RawTower_Prototype2.h.
References time.
void RawTower_Prototype2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTower.
Definition at line 76 of file RawTower_Prototype2.cc.
References get_bineta(), get_binphi(), and get_energy().
Referenced by CaloUnpackPRDF::process_event().
int RawTower_Prototype2::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from RawTower.
Definition at line 74 of file RawTower_Prototype2.cc.
References get_energy().
void RawTower_Prototype2::Reset () virtual
Clear Event.
Reimplemented from RawTower.
Definition at line 67 of file RawTower_Prototype2.cc.
References energy, NSAMPLES, signal_samples, and time.
void RawTower_Prototype2::set_energy (const double) inline virtual
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Reimplemented from RawTower.
Definition at line 35 of file RawTower_Prototype2.h.
References energy.
Referenced by GenericUnpackPRDF::process_event(), CaloCalibration::process_event(), and CaloUnpackPRDF::process_event().
void RawTower_Prototype2::set_HBD_channel_number (int i) inline
Definition at line 50 of file RawTower_Prototype2.h.
References HBD_channel, and i.
Referenced by GenericUnpackPRDF::process_event(), and CaloUnpackPRDF::process_event().
void RawTower_Prototype2::set_id (RawTowerDefs::keytype id) inline virtual
Reimplemented from RawTower.
Definition at line 28 of file RawTower_Prototype2.h.
References towerid.
void RawTower_Prototype2::set_signal_samples (int i, RawTower_Prototype2::signal_type sig)
Definition at line 82 of file RawTower_Prototype2.cc.
References assert, i, NSAMPLES, and signal_samples.
Referenced by GenericUnpackPRDF::process_event(), CaloCalibration::process_event(), and CaloUnpackPRDF::process_event().
void RawTower_Prototype2::set_time (const float) inline virtual
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Reimplemented from RawTower.
Definition at line 37 of file RawTower_Prototype2.h.
References t, and time.
Referenced by CaloCalibration::process_event().
Member Data Documentation
double RawTower_Prototype2::energy protected
energy assigned to the tower. Depending on stage of process and DST node name, it could be energy deposition, light yield or calibrated energies
Definition at line 62 of file RawTower_Prototype2.h.
Referenced by get_energy(), RawTower_Prototype2(), Reset(), and set_energy().
int RawTower_Prototype2::HBD_channel protected
Definition at line 69 of file RawTower_Prototype2.h.
Referenced by get_HBD_channel_number(), RawTower_Prototype2(), and set_HBD_channel_number().
signal_type RawTower_Prototype2::signal_samples[NSAMPLES] protected
Definition at line 68 of file RawTower_Prototype2.h.
Referenced by get_energy_power_law_exp(), get_signal_samples(), RawTower_Prototype2(), Reset(), and set_signal_samples().
float RawTower_Prototype2::time protected
Time stamp assigned to the tower. Depending on the tower maker, it could be rise time or peak time.
Definition at line 65 of file RawTower_Prototype2.h.
Referenced by get_time(), RawTower_Prototype2(), Reset(), and set_time().
RawTowerDefs::keytype RawTower_Prototype2::towerid protected
Definition at line 58 of file RawTower_Prototype2.h.
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), RawTower_Prototype2(), and set_id().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/RawTower_Prototype2.h
prototype/blob/master/offline/packages/Prototype2/RawTower_Prototype2.cc