Analysis Software: analysis/blob/master/MvtxTelescope/macros/DisplayOn.C File Reference
DisplayOn.C File Reference
Functions
PHG4Reco * DisplayOn (const char *mac="vis.mac")
void displaycmd ()
Function Documentation
void displaycmd ()
Definition at line 20 of file DisplayOn.C.
PHG4Reco* DisplayOn (const char * mac = "vis.mac")
Definition at line 9 of file DisplayOn.C.
References PHG4Reco::ApplyCommand(), g4, Fun4AllServer::getSubsysReco(), PHG4Reco::InitRun(), Fun4AllServer::instance(), and Fun4AllServer::topNode().