Analysis Software: PHG4GDMLUtility Class Reference
PHG4GDMLUtility Class Reference
PHG4GDMLUtility is utility class that drive the PHG4GDMLWriteStructure.
#include <coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLUtility.hh>
Public Member Functions
virtual ~PHG4GDMLUtility ()
Static Public Member Functions
static void Dump_GDML (const std::string &filename, G4VPhysicalVolume *vol, PHCompositeNode *topNode=nullptr)
save the current Geant4 geometry to GDML file. Reading PHG4GDMLConfig from topNode
static constexpr const char * get_PHG4GDML_Schema ()
static PHG4GDMLConfig * GetOrMakeConfigNode (PHCompositeNode *topNode, bool build_new=true)
Get or make the parameter node PHG4GDMLConfig from DST nodes. If not found, make a new one.
static constexpr const char * getDSTNodeName ()
Private Member Functions
PHG4GDMLUtility ()
Detailed Description
PHG4GDMLUtility is utility class that drive the PHG4GDMLWriteStructure.
Definition at line 23 of file PHG4GDMLUtility.hh.
Constructor & Destructor Documentation
virtual PHG4GDMLUtility::~PHG4GDMLUtility () inline virtual
Definition at line 26 of file PHG4GDMLUtility.hh.
PHG4GDMLUtility::PHG4GDMLUtility () inline private
Definition at line 45 of file PHG4GDMLUtility.hh.
Member Function Documentation
void PHG4GDMLUtility::Dump_GDML (const std::string & filename, G4VPhysicalVolume * vol, PHCompositeNode * topNode = nullptr) static
save the current Geant4 geometry to GDML file. Reading PHG4GDMLConfig from topNode
Definition at line 32 of file PHG4GDMLUtility.cc.
References assert, Fun4AllServer::instance(), Fun4AllServer::topNode(), and PHG4GDMLWrite::Write().
Referenced by PHG4Reco::Dump_GDML().
static constexpr const char* PHG4GDMLUtility::get_PHG4GDML_Schema () inline static
Definition at line 31 of file PHG4GDMLUtility.hh.
static constexpr const char* PHG4GDMLUtility::getDSTNodeName () inline static
Definition at line 39 of file PHG4GDMLUtility.hh.
PHG4GDMLConfig * PHG4GDMLUtility::GetOrMakeConfigNode (PHCompositeNode * topNode, bool build_new = true) static
Get or make the parameter node PHG4GDMLConfig from DST nodes. If not found, make a new one.
Definition at line 53 of file PHG4GDMLUtility.cc.
References PHNodeIterator::findFirst().
Referenced by PHG4SpacalDetector::PHG4SpacalDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLUtility.hh
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLUtility.cc