Analysis Software: online_distribution/blob/master/newbasic/Cframe.C File Reference
Cframe.C File Reference
#include "phenixOnline.h"
#include "frameHdr.h"
#include "Cframe.h"
#include "CframeV1.h"
#include <stdlib.h>
Typedefs
typedef LOGIC_ret CHECKFUNCTION (FRAME_ptr)
typedef VALUE_ret ACCESSFUNCTION (FRAME_ptr)
typedef PTR_ret PTRACCESSFUNCTION (FRAME_ptr)
typedef VALUE_ret MODIFYFUNCTION (FRAME_ptr, UINT)
typedef LOGIC_ret LOGICALMODIFYFUNCTION (FRAME_ptr, UINT)
typedef VALUE_ret VARRAYCOPYFUNCTION (FRAME_ptr, PHDWORD *, UINT)
typedef LOGIC_ret LARRAYCOPYFUNCTION (FRAME_ptr, PHDWORD *, UINT)
typedef VALUE_ret MAKEHDRFUNCTION (FRAME_ptr, UINT, UINT, UINT, UINT)
typedef VALUE_ret PARAMACCESSFUNCTION (FRAME_ptr, UINT)
typedef PTR_ret FINDNEXTFUNCTION (FRAME_ptr, FRAME_ptr)
typedef ACCESSFUNCTION * ACCESSFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef PTRACCESSFUNCTION * PTRACCESSFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef CHECKFUNCTION * CHECKFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef MODIFYFUNCTION * MODIFYFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef LOGICALMODIFYFUNCTION * LOGICALMODIFYFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef VARRAYCOPYFUNCTION * VARRAYCOPYFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef LARRAYCOPYFUNCTION * LARRAYCOPYFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef MAKEHDRFUNCTION * MAKEHDRFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef PARAMACCESSFUNCTION * PARAMACCESSFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
typedef FINDNEXTFUNCTION * FINDNEXTFUNCTIONPTR_arr [NUM_FRAME_VERSIONS]
Functions
PTR_ret findFrameDataStart (FRAME_ptr frame_ptr)
PTR_ret findFrameDataEnd (FRAME_ptr frame_ptr)
VALUE_ret checkFrameHdrVersion (FRAME_ptr frame_ptr)
PTR_ret findFrameEnd (FRAME_ptr frame_ptr)
VALUE_ret checkFrameEndianism (FRAME_ptr frame_ptr)
VALUE_ret adjustFrameLength (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT addDwords, LOGIC_ret pad)
VALUE_ret removeFramePadding (FRAME_ptr frame_ptr)
VALUE_ret getFrameStatus (FRAME_ptr frame_ptr)
VALUE_ret getFrameType (FRAME_ptr frame_ptr)
VALUE_ret getFrameSourceId (FRAME_ptr frame_ptr)
VALUE_ret getFrameDataType (FRAME_ptr frame_ptr)
VALUE_ret getFrameDataLength (FRAME_ptr frame_ptr)
VALUE_ret getFrameHistoryLength (FRAME_ptr frame_ptr)
VALUE_ret getFrameErrorLength (FRAME_ptr frame_ptr)
VALUE_ret getFrameAlignLength (FRAME_ptr frame_ptr)
PTR_ret findFrameAlignBlock (FRAME_ptr frame_ptr)
PTR_ret findFrameHistoryStart (FRAME_ptr frame_ptr)
PTR_ret findFrameErrorStart (FRAME_ptr frame_ptr)
VALUE_ret orFrameStatus (FRAME_ptr frame_ptr, UINT statusBits)
VALUE_ret getFramePadding (FRAME_ptr frame_ptr)
VALUE_ret makeFrameHdr (FRAME_ptr frame_ptr, UINT maxFrameLen, UINT dataType, UINT frameType, UINT sourceId)
VALUE_ret adjustFrameDataLength (FRAME_ptr frame_ptr, UINT newDwords)
VALUE_ret adjustFrameHistoryLength (FRAME_ptr frame_ptr, UINT newDwords)
VALUE_ret adjustFrameErrorLength (FRAME_ptr frame_ptr, UINT newDwords)
VALUE_ret setFramePadding (FRAME_ptr frame_ptr, UINT padDwords)
LOGIC_ret setDataType (FRAME_ptr frame_ptr, UINT dataType)
LOGIC_ret setFrameType (FRAME_ptr frame_ptr, UINT frameType)
LOGIC_ret setSourceId (FRAME_ptr frame_ptr, UINT sourceId)
LOGIC_ret setFrameHistoryLength (FRAME_ptr frame_ptr, UINT historyLength)
LOGIC_ret setFrameErrorLength (FRAME_ptr frame_ptr, UINT errorLength)
LOGIC_ret setFrameAlignLength (FRAME_ptr frame_ptr, UINT alignLength)
LOGIC_ret setFrameStatus (FRAME_ptr frame_ptr, UINT status)
VALUE_ret getAlignBlock (FRAME_ptr frame_ptr, PHDWORD *alignDestination, UINT maxNumDwords)
LOGIC_ret setAlignBlock (FRAME_ptr frame_ptr, PHDWORD *alignSource, UINT numDwords)
VALUE_ret getHistoryEntry (FRAME_ptr frame_ptr, UINT index)
VALUE_ret getHistoryStage (FRAME_ptr frame_ptr, UINT index)
VALUE_ret getHistorySourceIndex (FRAME_ptr frame_ptr, UINT index)
VALUE_ret getHistoryStatus (FRAME_ptr frame_ptr, UINT index)
PTR_ret findNextError (FRAME_ptr frame_ptr, FRAME_ptr thisError)
Variables
ACCESSFUNCTIONPTR_arr CONSTANT getFrameSourceIdV = {0, &getFrameSourceIdV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameTypeV = {0, &getFrameTypeV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameStatusV = {0, &getFrameStatusV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameDataTypeV = {0, &getFrameDataTypeV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFramePaddingV = {0, &getFramePaddingV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameHistoryLengthV = {0, &getFrameHistoryLengthV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameErrorLengthV = {0, &getFrameErrorLengthV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameDataLengthV = {0, &getFrameDataLengthV1}
ACCESSFUNCTIONPTR_arr CONSTANT getFrameAlignLengthV = {0, &getFrameAlignLengthV1}
PTRACCESSFUNCTIONPTR_arr CONSTANT findFrameErrorStartV = {0, &findFrameErrorStartV1}
PTRACCESSFUNCTIONPTR_arr CONSTANT findFrameAlignBlockV = {0, &findFrameAlignBlockV1}
PTRACCESSFUNCTIONPTR_arr CONSTANT findFrameHistoryStartV = {0, &findFrameHistoryStartV1}
CHECKFUNCTIONPTR_arr CONSTANT validFrameHdrV = {0, &validFrameHdrV1}
CHECKFUNCTIONPTR_arr CONSTANT emptyFrameV = {0, &emptyFrameV1}
MODIFYFUNCTIONPTR_arr CONSTANT orFrameStatusV = {0, &orFrameStatusV1}
MODIFYFUNCTIONPTR_arr CONSTANT setFramePaddingV = {0, &setFramePaddingV1}
MODIFYFUNCTIONPTR_arr CONSTANT adjustFrameDataLengthV = {0, &adjustFrameDataLengthV1}
MODIFYFUNCTIONPTR_arr CONSTANT adjustFrameHistoryLengthV = {0, &adjustFrameHistoryLengthV1}
MODIFYFUNCTIONPTR_arr CONSTANT adjustFrameErrorLengthV = {0, &adjustFrameErrorLengthV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setDataTypeV = {0, &setDataTypeV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setFrameTypeV = {0, &setFrameTypeV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setSourceIdV = {0, &setSourceIdV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setFrameHistoryLengthV = {0, &setFrameHistoryLengthV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setFrameErrorLengthV = {0, &setFrameErrorLengthV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setFrameAlignLengthV = {0, &setFrameAlignLengthV1}
LOGICALMODIFYFUNCTIONPTR_arr
CONSTANT setFrameStatusV = {0, &setFrameStatusV1}
VARRAYCOPYFUNCTIONPTR_arr CONSTANT getAlignBlockV = {0, &getAlignBlockV1}
LARRAYCOPYFUNCTIONPTR_arr CONSTANT setAlignBlockV = {0, &setAlignBlockV1}
MAKEHDRFUNCTIONPTR_arr CONSTANT makeFrameHdrV = {0, &makeFrameHdrV1}
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistoryEntryV = {0, &getHistoryEntryV1}
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistoryStageV = {0, &getHistoryStageV1}
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistorySourceIndexV = {0, &getHistorySourceIndexV1}
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistoryStatusV = {0, &getHistoryStatusV1}
FINDNEXTFUNCTIONPTR_arr CONSTANT findNextErrorV = {0, &findNextErrorV1}
Typedef Documentation
typedef VALUE_ret ACCESSFUNCTION(FRAME_ptr)
Definition at line 205 of file Cframe.C.
typedef ACCESSFUNCTION* ACCESSFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 215 of file Cframe.C.
typedef LOGIC_ret CHECKFUNCTION(FRAME_ptr)
Definition at line 204 of file Cframe.C.
typedef CHECKFUNCTION* CHECKFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 217 of file Cframe.C.
typedef PTR_ret FINDNEXTFUNCTION(FRAME_ptr, FRAME_ptr)
Definition at line 213 of file Cframe.C.
typedef FINDNEXTFUNCTION* FINDNEXTFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 224 of file Cframe.C.
typedef LOGIC_ret LARRAYCOPYFUNCTION(FRAME_ptr, PHDWORD *, UINT)
Definition at line 210 of file Cframe.C.
typedef LARRAYCOPYFUNCTION* LARRAYCOPYFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 221 of file Cframe.C.
typedef LOGIC_ret LOGICALMODIFYFUNCTION(FRAME_ptr, UINT)
Definition at line 208 of file Cframe.C.
typedef LOGICALMODIFYFUNCTION* LOGICALMODIFYFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 219 of file Cframe.C.
typedef VALUE_ret MAKEHDRFUNCTION(FRAME_ptr, UINT, UINT, UINT, UINT)
Definition at line 211 of file Cframe.C.
typedef MAKEHDRFUNCTION* MAKEHDRFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 222 of file Cframe.C.
typedef VALUE_ret MODIFYFUNCTION(FRAME_ptr, UINT)
Definition at line 207 of file Cframe.C.
typedef MODIFYFUNCTION* MODIFYFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 218 of file Cframe.C.
typedef VALUE_ret PARAMACCESSFUNCTION(FRAME_ptr, UINT)
Definition at line 212 of file Cframe.C.
typedef PARAMACCESSFUNCTION* PARAMACCESSFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 223 of file Cframe.C.
typedef PTR_ret PTRACCESSFUNCTION(FRAME_ptr)
Definition at line 206 of file Cframe.C.
typedef PTRACCESSFUNCTION* PTRACCESSFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 216 of file Cframe.C.
typedef VALUE_ret VARRAYCOPYFUNCTION(FRAME_ptr, PHDWORD *, UINT)
Definition at line 209 of file Cframe.C.
typedef VARRAYCOPYFUNCTION* VARRAYCOPYFUNCTIONPTR_arr[NUM_FRAME_VERSIONS]
Definition at line 220 of file Cframe.C.
Function Documentation
VALUE_ret adjustFrameDataLength (FRAME_ptr frame_ptr, UINT newDwords)
Definition at line 414 of file Cframe.C.
References adjustFrameDataLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by extendFrameData(), and extendFrameDataNopad().
VALUE_ret adjustFrameErrorLength (FRAME_ptr frame_ptr, UINT newDwords)
Definition at line 433 of file Cframe.C.
References adjustFrameErrorLengthV, getFrameHdrVersion(), and valueFailure.
VALUE_ret adjustFrameHistoryLength (FRAME_ptr frame_ptr, UINT newDwords)
Definition at line 424 of file Cframe.C.
References adjustFrameHistoryLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by extendFrameHistory(), and extendFrameHistoryNopad().
VALUE_ret adjustFrameLength (FRAME_ptr frame_ptr, UINT maxFrameLength, UINT addDwords, LOGIC_ret pad)
Definition at line 122 of file Cframe.C.
References currentFrameQuantum, dwordClear, FORMAT_ERR_BUFFER_OVERFLOW, FORMAT_ERR_LENGTH_OVERFLOW, getFrameLength(), maxDwordValue, removeFramePadding(), setFrameError(), setFrameLength(), setFramePadding(), validFrameHdr(), and valueFailure.
Referenced by oEvent::addPacket(), oEvent::addUnstructPacketData(), extendFrameData(), extendFrameDataNopad(), extendFrameHistory(), and extendFrameHistoryNopad().
VALUE_ret checkFrameEndianism (FRAME_ptr frame_ptr)
Definition at line 107 of file Cframe.C.
References dwordByteSwap(), maxFrameHdrLength, validFrameHdr(), and valueFailure.
Referenced by main().
VALUE_ret checkFrameHdrVersion (FRAME_ptr frame_ptr)
Definition at line 64 of file Cframe.C.
References FORMAT_ERR_INVALID_FRAMEMARK, frameHdrLengthV, frameMarkV, getFrameHdrLength(), getFrameHdrVersion(), getFrameMark(), setFrameError(), setFrameSuccess(), and valueFailure.
Referenced by validFrameHdr().
PTR_ret findFrameAlignBlock (FRAME_ptr frame_ptr)
Definition at line 355 of file Cframe.C.
References findFrameAlignBlockV, getFrameHdrVersion(), ptrFailure, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
PTR_ret findFrameDataEnd (FRAME_ptr frame_ptr)
Definition at line 49 of file Cframe.C.
References findFrameDataStart(), getFrameDataLength(), ptrFailure, and valueFailure.
Referenced by oEvent::addPacket(), oEvent::addUnstructPacketData(), and findNextFramePacket().
PTR_ret findFrameDataStart (FRAME_ptr frame_ptr)
Definition at line 40 of file Cframe.C.
References getFrameHdrLength(), ptrFailure, and validFrameHdr().
Referenced by appendEmptyFramePacket(), dumpFrame(), findFrameDataEnd(), findFramePacketId(), findFramePacketIndex(), findNextFramePacket(), and storeFrameData().
PTR_ret findFrameEnd (FRAME_ptr frame_ptr)
Definition at line 87 of file Cframe.C.
References getFrameLength(), ptrFailure, setFrameSuccess(), validFrameHdr(), and valueFailure.
Referenced by fakeFrame(), and findNextErrorV1().
PTR_ret findFrameErrorStart (FRAME_ptr frame_ptr)
Definition at line 375 of file Cframe.C.
References findFrameErrorStartV, getFrameHdrVersion(), ptrFailure, and valueFailure.
Referenced by A_Event::dumpErrorBlock(), findNextErrorV1(), and A_Event::listError().
PTR_ret findFrameHistoryStart (FRAME_ptr frame_ptr)
Definition at line 365 of file Cframe.C.
References findFrameHistoryStartV, getFrameHdrVersion(), ptrFailure, and valueFailure.
Referenced by getHistoryEntryV1(), A_Event::listHistory(), and storeFrameHistory().
PTR_ret findNextError (FRAME_ptr frame_ptr, FRAME_ptr thisError)
Definition at line 568 of file Cframe.C.
References findNextErrorV, getFrameHdrVersion(), ptrFailure, and valueFailure.
VALUE_ret getAlignBlock (FRAME_ptr frame_ptr, PHDWORD * alignDestination, UINT maxNumDwords)
Definition at line 514 of file Cframe.C.
References getAlignBlockV, getFrameHdrVersion(), and valueFailure.
VALUE_ret getFrameAlignLength (FRAME_ptr frame_ptr)
Definition at line 345 of file Cframe.C.
References getFrameAlignLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), getAlignBlockV1(), A_Event::getFrameValue(), and setAlignBlockV1().
VALUE_ret getFrameDataLength (FRAME_ptr frame_ptr)
Definition at line 315 of file Cframe.C.
References getFrameDataLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by dumpFrame(), fakeFrame(), and findFrameDataEnd().
VALUE_ret getFrameDataType (FRAME_ptr frame_ptr)
Definition at line 305 of file Cframe.C.
References getFrameDataTypeV, getFrameHdrVersion(), and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getFrameErrorLength (FRAME_ptr frame_ptr)
Definition at line 335 of file Cframe.C.
References getFrameErrorLengthV, getFrameHdrVersion(), and valueFailure.
Referenced by A_Event::dumpErrorBlock(), A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::listError().
VALUE_ret getFrameHistoryLength (FRAME_ptr frame_ptr)
Definition at line 325 of file Cframe.C.
References getFrameHdrVersion(), getFrameHistoryLengthV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), getHistoryEntryV1(), A_Event::listHistory(), and storeFrameHistory().
VALUE_ret getFramePadding (FRAME_ptr frame_ptr)
Definition at line 395 of file Cframe.C.
References getFrameHdrVersion(), getFramePaddingV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), findFrameErrorStartV1(), findFrameHistoryStartV1(), and removeFramePadding().
VALUE_ret getFrameSourceId (FRAME_ptr frame_ptr)
Definition at line 295 of file Cframe.C.
References getFrameHdrVersion(), getFrameSourceIdV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getFrameStatus (FRAME_ptr frame_ptr)
Definition at line 276 of file Cframe.C.
References getFrameHdrVersion(), getFrameStatusV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getFrameType (FRAME_ptr frame_ptr)
Definition at line 285 of file Cframe.C.
References getFrameHdrVersion(), getFrameTypeV, and valueFailure.
Referenced by A_Event::dumpFrame(), dumpFrameHdr(), and A_Event::getFrameValue().
VALUE_ret getHistoryEntry (FRAME_ptr frame_ptr, UINT index)
Definition at line 532 of file Cframe.C.
References getFrameHdrVersion(), getHistoryEntryV, index, and valueFailure.
VALUE_ret getHistorySourceIndex (FRAME_ptr frame_ptr, UINT index)
Definition at line 550 of file Cframe.C.
References getFrameHdrVersion(), getHistorySourceIndexV, index, and valueFailure.
VALUE_ret getHistoryStage (FRAME_ptr frame_ptr, UINT index)
Definition at line 541 of file Cframe.C.
References getFrameHdrVersion(), getHistoryStageV, index, and valueFailure.
VALUE_ret getHistoryStatus (FRAME_ptr frame_ptr, UINT index)
Definition at line 559 of file Cframe.C.
References getFrameHdrVersion(), getHistoryStatusV, index, and valueFailure.
VALUE_ret makeFrameHdr (FRAME_ptr frame_ptr, UINT maxFrameLen, UINT dataType, UINT frameType, UINT sourceId)
Definition at line 407 of file Cframe.C.
References currentFrameHdrVersion, and makeFrameHdrV.
Referenced by oEvent::addPacket(), oEvent::addUnstructPacketData(), and fakeFrame().
VALUE_ret orFrameStatus (FRAME_ptr frame_ptr, UINT statusBits)
Definition at line 385 of file Cframe.C.
References getFrameHdrVersion(), orFrameStatusV, and valueFailure.
VALUE_ret removeFramePadding (FRAME_ptr frame_ptr)
Definition at line 186 of file Cframe.C.
References getFrameLength(), getFramePadding(), setFrameLength(), and setFramePadding().
Referenced by adjustFrameLength(), storeFrameData(), and storeFrameHistory().
LOGIC_ret setAlignBlock (FRAME_ptr frame_ptr, PHDWORD * alignSource, UINT numDwords)
Definition at line 523 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setAlignBlockV, and valueFailure.
Referenced by fakeFrame().
LOGIC_ret setDataType (FRAME_ptr frame_ptr, UINT dataType)
Definition at line 451 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setDataTypeV, and valueFailure.
Referenced by makeFrameHdrV1().
LOGIC_ret setFrameAlignLength (FRAME_ptr frame_ptr, UINT alignLength)
Definition at line 496 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameAlignLengthV, and valueFailure.
Referenced by makeFrameHdrV1().
LOGIC_ret setFrameErrorLength (FRAME_ptr frame_ptr, UINT errorLength)
Definition at line 487 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameErrorLengthV, and valueFailure.
LOGIC_ret setFrameHistoryLength (FRAME_ptr frame_ptr, UINT historyLength)
Definition at line 478 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameHistoryLengthV, and valueFailure.
VALUE_ret setFramePadding (FRAME_ptr frame_ptr, UINT padDwords)
Definition at line 442 of file Cframe.C.
References getFrameHdrVersion(), setFramePaddingV, and valueFailure.
Referenced by adjustFrameLength(), and removeFramePadding().
LOGIC_ret setFrameStatus (FRAME_ptr frame_ptr, UINT status)
Definition at line 505 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameStatusV, and valueFailure.
LOGIC_ret setFrameType (FRAME_ptr frame_ptr, UINT frameType)
Definition at line 460 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setFrameTypeV, and valueFailure.
Referenced by makeFrameHdrV1().
LOGIC_ret setSourceId (FRAME_ptr frame_ptr, UINT sourceId)
Definition at line 469 of file Cframe.C.
References FALSE, getFrameHdrVersion(), setSourceIdV, and valueFailure.
Referenced by makeFrameHdrV1(), and TruthConversionEval::process_event().
Variable Documentation
MODIFYFUNCTIONPTR_arr CONSTANT adjustFrameDataLengthV = {0, &adjustFrameDataLengthV1}
Definition at line 253 of file Cframe.C.
Referenced by adjustFrameDataLength().
MODIFYFUNCTIONPTR_arr CONSTANT adjustFrameErrorLengthV = {0, &adjustFrameErrorLengthV1}
Definition at line 255 of file Cframe.C.
Referenced by adjustFrameErrorLength().
MODIFYFUNCTIONPTR_arr CONSTANT adjustFrameHistoryLengthV = {0, &adjustFrameHistoryLengthV1}
Definition at line 254 of file Cframe.C.
Referenced by adjustFrameHistoryLength().
CHECKFUNCTIONPTR_arr CONSTANT emptyFrameV = {0, &emptyFrameV1}
Definition at line 249 of file Cframe.C.
PTRACCESSFUNCTIONPTR_arr CONSTANT findFrameAlignBlockV = {0, &findFrameAlignBlockV1}
Definition at line 245 of file Cframe.C.
Referenced by findFrameAlignBlock().
PTRACCESSFUNCTIONPTR_arr CONSTANT findFrameErrorStartV = {0, &findFrameErrorStartV1}
Definition at line 244 of file Cframe.C.
Referenced by findFrameErrorStart().
PTRACCESSFUNCTIONPTR_arr CONSTANT findFrameHistoryStartV = {0, &findFrameHistoryStartV1}
Definition at line 246 of file Cframe.C.
Referenced by findFrameHistoryStart().
FINDNEXTFUNCTIONPTR_arr CONSTANT findNextErrorV = {0, &findNextErrorV1}
Definition at line 274 of file Cframe.C.
Referenced by findNextError().
VARRAYCOPYFUNCTIONPTR_arr CONSTANT getAlignBlockV = {0, &getAlignBlockV1}
Definition at line 265 of file Cframe.C.
Referenced by getAlignBlock().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameAlignLengthV = {0, &getFrameAlignLengthV1}
Definition at line 242 of file Cframe.C.
Referenced by getFrameAlignLength().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameDataLengthV = {0, &getFrameDataLengthV1}
Definition at line 241 of file Cframe.C.
Referenced by getFrameDataLength().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameDataTypeV = {0, &getFrameDataTypeV1}
Definition at line 237 of file Cframe.C.
Referenced by getFrameDataType().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameErrorLengthV = {0, &getFrameErrorLengthV1}
Definition at line 240 of file Cframe.C.
Referenced by getFrameErrorLength().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameHistoryLengthV = {0, &getFrameHistoryLengthV1}
Definition at line 239 of file Cframe.C.
Referenced by getFrameHistoryLength().
ACCESSFUNCTIONPTR_arr CONSTANT getFramePaddingV = {0, &getFramePaddingV1}
Definition at line 238 of file Cframe.C.
Referenced by getFramePadding().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameSourceIdV = {0, &getFrameSourceIdV1}
Definition at line 234 of file Cframe.C.
Referenced by getFrameSourceId().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameStatusV = {0, &getFrameStatusV1}
Definition at line 236 of file Cframe.C.
Referenced by getFrameStatus().
ACCESSFUNCTIONPTR_arr CONSTANT getFrameTypeV = {0, &getFrameTypeV1}
Definition at line 235 of file Cframe.C.
Referenced by getFrameType().
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistoryEntryV = {0, &getHistoryEntryV1}
Definition at line 270 of file Cframe.C.
Referenced by getHistoryEntry().
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistorySourceIndexV = {0, &getHistorySourceIndexV1}
Definition at line 272 of file Cframe.C.
Referenced by getHistorySourceIndex().
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistoryStageV = {0, &getHistoryStageV1}
Definition at line 271 of file Cframe.C.
Referenced by getHistoryStage().
PARAMACCESSFUNCTIONPTR_arr CONSTANT getHistoryStatusV = {0, &getHistoryStatusV1}
Definition at line 273 of file Cframe.C.
Referenced by getHistoryStatus().
MAKEHDRFUNCTIONPTR_arr CONSTANT makeFrameHdrV = {0, &makeFrameHdrV1}
Definition at line 268 of file Cframe.C.
Referenced by makeFrameHdr().
MODIFYFUNCTIONPTR_arr CONSTANT orFrameStatusV = {0, &orFrameStatusV1}
Definition at line 251 of file Cframe.C.
Referenced by orFrameStatus().
LARRAYCOPYFUNCTIONPTR_arr CONSTANT setAlignBlockV = {0, &setAlignBlockV1}
Definition at line 266 of file Cframe.C.
Referenced by setAlignBlock().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setDataTypeV = {0, &setDataTypeV1}
Definition at line 257 of file Cframe.C.
Referenced by setDataType().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setFrameAlignLengthV = {0, &setFrameAlignLengthV1}
Definition at line 262 of file Cframe.C.
Referenced by setFrameAlignLength().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setFrameErrorLengthV = {0, &setFrameErrorLengthV1}
Definition at line 261 of file Cframe.C.
Referenced by setFrameErrorLength().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setFrameHistoryLengthV = {0, &setFrameHistoryLengthV1}
Definition at line 260 of file Cframe.C.
Referenced by setFrameHistoryLength().
MODIFYFUNCTIONPTR_arr CONSTANT setFramePaddingV = {0, &setFramePaddingV1}
Definition at line 252 of file Cframe.C.
Referenced by setFramePadding().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setFrameStatusV = {0, &setFrameStatusV1}
Definition at line 263 of file Cframe.C.
Referenced by setFrameStatus().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setFrameTypeV = {0, &setFrameTypeV1}
Definition at line 258 of file Cframe.C.
Referenced by setFrameType().
LOGICALMODIFYFUNCTIONPTR_arr CONSTANT setSourceIdV = {0, &setSourceIdV1}
Definition at line 259 of file Cframe.C.
Referenced by setSourceId().
CHECKFUNCTIONPTR_arr CONSTANT validFrameHdrV = {0, &validFrameHdrV1}
Definition at line 248 of file Cframe.C.