Analysis Software: PHDataNode< T > Class Template Reference
PHDataNode< T > Class Template Reference
#include <coresoftware/blob/master/offline/framework/phool/PHDataNode.h>
Classes
union tobjcast
Public Member Functions
PHDataNode (T *, const std::string &)
PHDataNode (T *, const std::string &, const std::string &)
virtual ~PHDataNode ()
T * getData ()
void setData (T *d)
virtual void prune ()
virtual void forgetMe (PHNode *)
virtual void print (const std::string &)
virtual bool write (PHIOManager *, const std::string &="")
Public Member Functions inherited from PHNode
PHNode (const std::string &)
PHNode (const std::string &, const std::string &)
virtual ~PHNode ()
PHNode * getParent () const
bool isPersistent () const
void makePersistent ()
const std::string getObjectType () const
const std::string getType () const
const std::string getName () const
const std::string getClass () const
void setParent (PHNode *p)
void setName (const std::string &n)
void setObjectType (const std::string &type)
virtual void setResetFlag (const bool b)
virtual bool getResetFlag () const
void makeTransient ()
Protected Member Functions
PHDataNode ()=delete
Protected Attributes
tobjcast data
Protected Attributes inherited from PHNode
PHNode * parent
bool persistent
std::string type
std::string objecttype
std::string name
bool reset_able
std::string objectclass
Detailed Description
template<class T>
class PHDataNode< T >
Definition at line 13 of file PHDataNode.h.
Constructor & Destructor Documentation
template<class T> PHDataNode< T >::PHDataNode (T * d, const std::string & name)
Definition at line 41 of file PHDataNode.h.
References PHDataNode< T >::setData(), and PHNode::type.
template<class T> PHDataNode< T >::PHDataNode (T * d, const std::string & name, const std::string & objtype)
Definition at line 50 of file PHDataNode.h.
References PHDataNode< T >::setData(), and PHNode::type.
template<class T > PHDataNode< T >::~PHDataNode () virtual
Definition at line 60 of file PHDataNode.h.
References data.
template<class T> PHDataNode< T >::PHDataNode () protected delete
Member Function Documentation
template<class T> virtual void PHDataNode< T >::forgetMe (PHNode *) inline virtual
Implements PHNode.
Definition at line 24 of file PHDataNode.h.
template<class T> T* PHDataNode< T >::getData () inline
Definition at line 21 of file PHDataNode.h.
Referenced by JetReco::FillJetNode(), findNode::getClass(), PHIODataNode< T >::operator*(), DumpCaloTriggerInfo::process_Node(), DumpTowerBackground::process_Node(), DumpPHG4InEvent::process_Node(), DumpPHG4CylinderGeomContainer::process_Node(), DumpPHG4CylinderCellGeomContainer::process_Node(), DumpSyncObject::process_Node(), DumpSvtxVertexMap::process_Node(), DumpTrkrClusterContainer::process_Node(), DumpSvtxHitMap::process_Node(), DumpSvtxClusterMap::process_Node(), DumpRunHeader::process_Node(), DumpTrkrHitSetContainer::process_Node(), DumpRawTowerGeom::process_Node(), DumpRawTowerContainer::process_Node(), DumpRawClusterContainer::process_Node(), DumpPHG4TruthInfoContainer::process_Node(), DumpPHG4ScintillatorSlatContainer::process_Node(), DumpPHG4HitContainer::process_Node(), DumpJetMap::process_Node(), DumpPdbParameterMap::process_Node(), DumpGlobalVertexMap::process_Node(), DumpSvtxTrackMap::process_Node(), DumpPHG4CellContainer::process_Node(), DumpRawTowerGeomContainer::process_Node(), DumpPHG4BlockCellGeomContainer::process_Node(), DumpBbcVertexMap::process_Node(), DumpPdbParameterMapContainer::process_Node(), DumpVariableArray::process_Node(), DumpPHG4CylinderCellContainer::process_Node(), DumpPHG4BlockGeomContainer::process_Node(), PHNodeIOManager::reconstructNodeTree(), PHG4DstCompressReco::SearchG4HitNodes(), PHG4TruthEventAction::SearchNode(), and PHRawOManager::write().
template<class T > void PHDataNode< T >::print (const std::string & path) virtual
Implements PHNode.
Definition at line 73 of file PHDataNode.h.
References name.
template<class T> virtual void PHDataNode< T >::prune () inline virtual
Implements PHNode.
Definition at line 23 of file PHDataNode.h.
template<class T> void PHDataNode< T >::setData (T * d) inline
Definition at line 22 of file PHDataNode.h.
Referenced by PHDataNode< T >::PHDataNode(), Fun4AllPrdfInputManager::ResetEvent(), and Fun4AllPrdfInputManager::run().
template<class T> virtual bool PHDataNode< T >::write (PHIOManager * , const std::string & = "") inline virtual
Implements PHNode.
Reimplemented in PHIODataNode< T >, and PHRawDataNode.
Definition at line 26 of file PHDataNode.h.
Member Data Documentation
template<class T> tobjcast PHDataNode< T >::data protected
Definition at line 36 of file PHDataNode.h.
Referenced by PHDataNode< PHDWORD >::getData(), PHNodeIOManager::reconstructNodeTree(), and PHDataNode< PHDWORD >::setData().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/framework/phool/PHDataNode.h