Analysis Software: PHG4InttDetector Class Reference
PHG4InttDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttDetector.h>
Public Member Functions
PHG4InttDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParametersContainer *parameters, const std::string &dnam, const std::pair< std::vector< std::pair< int, int >>::const_iterator, std::vector< std::pair< int, int >>::const_iterator > &layer_b_e)
constructor
virtual ~PHG4InttDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
void Detector (const std::string &name)
const std::string Detector () const
std::map< G4VPhysicalVolume
*, std::tuple< int, int, int,
int > >::const_iterator get_ActiveVolumeTuple (G4VPhysicalVolume *physvol) const
std::map< G4LogicalVolume
*, std::tuple< int, int >
>::const_iterator get_PassiveVolumeTuple (G4LogicalVolume *logvol) const
volume accessors
int IsInIntt (G4VPhysicalVolume *) const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
void AddGeometryNode ()
int ConstructIntt (G4LogicalVolume *sandwich)
Private Attributes
PHG4InttDisplayAction * m_DisplayAction
PHParametersContainer * m_ParamsContainer
std::string m_DetectorType
std::string m_SuperDetector
int m_IsSupportActive
int m_IsEndcapActive
double m_PosZ [8][2]
double m_SensorRadius [8]
double m_StripOffsetX [8]
std::set< G4LogicalVolume * > m_ActiveLogVols
std::map< int, int > m_IsActiveMap
std::map< int, int > m_IsAbsorberActiveMap
std::pair< std::vector
< std::pair< int, int >
>::const_iterator,
std::vector< std::pair< int,
int > >::const_iterator > m_LayerBeginEndIteratorPair
std::map< G4VPhysicalVolume
*, std::tuple< int, int, int,
int > > m_ActiveVolumeTuple
std::map< G4LogicalVolume
*, std::tuple< int, int > > m_PassiveVolumeTuple
Detailed Description
Definition at line 22 of file PHG4InttDetector.h.
Constructor & Destructor Documentation
PHG4InttDetector::PHG4InttDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParametersContainer * parameters, const std::string & dnam, const std::pair< std::vector< std::pair< int, int >>::const_iterator, std::vector< std::pair< int, int >>::const_iterator > & layer_b_e)
constructor
Definition at line 59 of file PHG4InttDetector.cc.
References PHParameters::get_int_param(), PHParametersContainer::GetParameters(), m_IsAbsorberActiveMap, m_IsActiveMap, m_IsEndcapActive, m_IsSupportActive, m_LayerBeginEndIteratorPair, m_ParamsContainer, m_PosZ, m_SensorRadius, m_StripOffsetX, and PHG4InttDefs::SUPPORTPARAMS.
virtual PHG4InttDetector::~PHG4InttDetector () inline virtual
destructor
Definition at line 29 of file PHG4InttDetector.h.
Member Function Documentation
void PHG4InttDetector::AddGeometryNode () private
Definition at line 1561 of file PHG4InttDetector.cc.
References PHG4CylinderGeomContainer::AddLayerGeom(), PHCompositeNode::addNode(), PHNodeIterator::findFirst(), PHParameters::get_double_param(), PHParameters::get_int_param(), PHParametersContainer::GetParameters(), PHG4CylinderGeomContainer::identify(), m_DetectorType, m_IsActiveMap, m_LayerBeginEndIteratorPair, m_ParamsContainer, m_PosZ, m_SensorRadius, m_SuperDetector, PHG4Detector::topNode(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
int PHG4InttDetector::ConstructIntt (G4LogicalVolume * sandwich) private
Definition at line 122 of file PHG4InttDetector.cc.
References PHG4InttDisplayAction::AddVolume(), assert, double(), PHG4InttDefs::FPHX, PHParameters::get_double_param(), PHParameters::get_int_param(), PHParametersContainer::GetParameters(), PHG4InttDefs::HDI_COPPER, PHG4InttDefs::HDI_KAPTON, PHG4InttDefs::HDIEXT_COPPER, PHG4InttDefs::HDIEXT_KAPTON, i, PHG4InttDefs::INTT_INNER_SKIN, PHG4InttDefs::INTT_OUTER_SKIN, j, laddertype, m_ActiveLogVols, m_ActiveVolumeTuple, m_DisplayAction, m_IsAbsorberActiveMap, m_IsActiveMap, m_IsEndcapActive, m_IsSupportActive, m_LayerBeginEndIteratorPair, m_ParamsContainer, m_PassiveVolumeTuple, M_PI, m_PosZ, m_SensorRadius, m_StripOffsetX, offsetphi, PHG4Detector::OverlapCheck(), PHG4InttDefs::PGS, PHG4InttDefs::PGSEXT, phi, PHWHERE, PHG4InttDefs::SEGMENTATION_PHI, PHG4InttDefs::SEGMENTATION_Z, PHG4InttDefs::SI_INACTIVE, PHG4InttDefs::STAVE_CURVE, PHG4InttDefs::STAVE_STRAIGHT_COOLER, PHG4InttDefs::STAVE_STRAIGHT_INNER, PHG4InttDefs::STAVE_STRAIGHT_OUTER, PHG4InttDefs::STAVEEXT_CURVE, PHG4InttDefs::STAVEEXT_STRAIGHT_COOLER, PHG4InttDefs::STAVEEXT_STRAIGHT_INNER, PHG4InttDefs::STAVEEXT_STRAIGHT_OUTER, PHG4InttDefs::SUPPORT_DETID, PHG4InttDefs::SUPPORT_RAIL, PHG4InttDefs::SUPPORTPARAMS, and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void PHG4InttDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 104 of file PHG4InttDetector.cc.
References AddGeometryNode(), ConstructIntt(), m_LayerBeginEndIteratorPair, and PHG4Detector::Verbosity().
void PHG4InttDetector::Detector (const std::string & name) inline
Definition at line 46 of file PHG4InttDetector.h.
References m_DetectorType, and name.
const std::string PHG4InttDetector::Detector () const inline
Definition at line 50 of file PHG4InttDetector.h.
References m_DetectorType.
map< G4VPhysicalVolume *, std::tuple< int, int, int, int > >::const_iterator PHG4InttDetector::get_ActiveVolumeTuple (G4VPhysicalVolume * physvol) const
Definition at line 1622 of file PHG4InttDetector.cc.
References m_ActiveVolumeTuple, and PHWHERE.
Referenced by PHG4InttSteppingAction::UserSteppingAction().
map< G4LogicalVolume *, std::tuple< int, int > >::const_iterator PHG4InttDetector::get_PassiveVolumeTuple (G4LogicalVolume * logvol) const
Definition at line 1634 of file PHG4InttDetector.cc.
References m_PassiveVolumeTuple, and PHWHERE.
Referenced by PHG4InttSteppingAction::UserSteppingAction().
int PHG4InttDetector::IsInIntt (G4VPhysicalVolume * volume) const
Definition at line 83 of file PHG4InttDetector.cc.
References m_ActiveLogVols, and m_PassiveVolumeTuple.
Referenced by PHG4InttSteppingAction::UserSteppingAction().
void PHG4InttDetector::SuperDetector (const std::string & name) inline
Definition at line 38 of file PHG4InttDetector.h.
References m_SuperDetector, and name.
Referenced by PHG4InttSteppingAction::SetInterfacePointers().
const std::string PHG4InttDetector::SuperDetector () const inline
Definition at line 42 of file PHG4InttDetector.h.
References m_SuperDetector.
Member Data Documentation
std::set<G4LogicalVolume *> PHG4InttDetector::m_ActiveLogVols private
Definition at line 75 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), and IsInIntt().
std::map<G4VPhysicalVolume *, std::tuple<int, int, int, int> > PHG4InttDetector::m_ActiveVolumeTuple private
Definition at line 79 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), and get_ActiveVolumeTuple().
std::string PHG4InttDetector::m_DetectorType private
Definition at line 65 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), and Detector().
PHG4InttDisplayAction* PHG4InttDetector::m_DisplayAction private
Definition at line 62 of file PHG4InttDetector.h.
Referenced by ConstructIntt().
std::map<int, int> PHG4InttDetector::m_IsAbsorberActiveMap private
Definition at line 77 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), and PHG4InttDetector().
std::map<int, int> PHG4InttDetector::m_IsActiveMap private
Definition at line 76 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), ConstructIntt(), and PHG4InttDetector().
int PHG4InttDetector::m_IsEndcapActive private
Definition at line 69 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), and PHG4InttDetector().
int PHG4InttDetector::m_IsSupportActive private
Definition at line 68 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), and PHG4InttDetector().
std::pair<std::vector<std::pair<int, int> >::const_iterator, std::vector<std::pair<int, int> >::const_iterator> PHG4InttDetector::m_LayerBeginEndIteratorPair private
Definition at line 78 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), ConstructIntt(), ConstructMe(), and PHG4InttDetector().
PHParametersContainer* PHG4InttDetector::m_ParamsContainer private
Definition at line 63 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), ConstructIntt(), and PHG4InttDetector().
std::map<G4LogicalVolume *, std::tuple<int, int> > PHG4InttDetector::m_PassiveVolumeTuple private
Definition at line 80 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), get_PassiveVolumeTuple(), and IsInIntt().
double PHG4InttDetector::m_PosZ[8][2] private
Definition at line 71 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), ConstructIntt(), and PHG4InttDetector().
double PHG4InttDetector::m_SensorRadius[8] private
Definition at line 72 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), ConstructIntt(), and PHG4InttDetector().
double PHG4InttDetector::m_StripOffsetX[8] private
Definition at line 73 of file PHG4InttDetector.h.
Referenced by ConstructIntt(), and PHG4InttDetector().
std::string PHG4InttDetector::m_SuperDetector private
Definition at line 66 of file PHG4InttDetector.h.
Referenced by AddGeometryNode(), and SuperDetector().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttDetector.h
coresoftware/blob/master/simulation/g4simulation/g4intt/PHG4InttDetector.cc