Analysis Software: component
component
Typedefs
typedef std::multimap
< Jet::SRC, unsigned int > Jet::typ_comp_ids
typedef
typ_comp_ids::const_iterator Jet::ConstIter
typedef typ_comp_ids::iterator Jet::Iter
Functions
virtual bool Jet::empty_comp () const
virtual size_t Jet::size_comp () const
virtual size_t Jet::count_comp (Jet::SRC source) const
virtual void Jet::clear_comp ()
virtual void Jet::insert_comp (Jet::SRC source, unsigned int compid)
virtual size_t Jet::erase_comp (Jet::SRC source)
virtual void Jet::erase_comp (Iter iter)
virtual void Jet::erase_comp (Iter first, Iter last)
virtual ConstIter Jet::begin_comp () const
virtual ConstIter Jet::lower_bound_comp (Jet::SRC source) const
virtual ConstIter Jet::upper_bound_comp (Jet::SRC source) const
virtual ConstIter Jet::find (Jet::SRC source) const
virtual ConstIter Jet::end_comp () const
virtual Iter Jet::begin_comp ()
virtual Iter Jet::lower_bound_comp (Jet::SRC source)
virtual Iter Jet::upper_bound_comp (Jet::SRC source)
virtual Iter Jet::find (Jet::SRC source)
virtual Iter Jet::end_comp ()
Jet::ClassDef (Jet, 1)
Detailed Description
clustered component methods (multimap interface based) source type id –> unique id within that storage
Typedef Documentation
typedef typ_comp_ids::const_iterator Jet::ConstIter
Definition at line 116 of file Jet.h.
typedef typ_comp_ids::iterator Jet::Iter
Definition at line 117 of file Jet.h.
typedef std::multimap<Jet::SRC, unsigned int> Jet::typ_comp_ids
Definition at line 115 of file Jet.h.
Function Documentation
virtual ConstIter Jet::begin_comp () const inline virtual
Reimplemented in Jetv1.
Definition at line 129 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetTruthEval::all_truth_particles(), JetRecoEval::all_truth_showers(), TreeMaker::CopyAndMakeJets(), JetRecoEval::get_energy_contribution(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), JetTruthEval::get_truth_jet(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), and PhotonJet::process_event().
virtual Iter Jet::begin_comp () inline virtual
Reimplemented in Jetv1.
Definition at line 135 of file Jet.h.
Jet::ClassDef (Jet , 1)
virtual void Jet::clear_comp () inline virtual
Reimplemented in Jetv1.
Definition at line 123 of file Jet.h.
virtual size_t Jet::count_comp (Jet::SRC source) const inline virtual
Reimplemented in Jetv1.
Definition at line 121 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation().
virtual bool Jet::empty_comp () const inline virtual
Reimplemented in Jetv1.
Definition at line 119 of file Jet.h.
virtual ConstIter Jet::end_comp () const inline virtual
Reimplemented in Jetv1.
Definition at line 133 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetTruthEval::all_truth_particles(), JetRecoEval::all_truth_showers(), TreeMaker::CopyAndMakeJets(), JetRecoEval::get_energy_contribution(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), JetTruthEval::get_truth_jet(), CopyAndSubtractJets::process_event(), DetermineTowerBackground::process_event(), and PhotonJet::process_event().
virtual Iter Jet::end_comp () inline virtual
Reimplemented in Jetv1.
Definition at line 139 of file Jet.h.
virtual size_t Jet::erase_comp (Jet::SRC source) inline virtual
Reimplemented in Jetv1.
Definition at line 125 of file Jet.h.
virtual void Jet::erase_comp (Iter iter) inline virtual
Reimplemented in Jetv1.
Definition at line 126 of file Jet.h.
virtual void Jet::erase_comp (Iter first, Iter last) inline virtual
Reimplemented in Jetv1.
Definition at line 127 of file Jet.h.
virtual ConstIter Jet::find (Jet::SRC source) const inline virtual
Reimplemented in Jetv1.
Definition at line 132 of file Jet.h.
virtual Iter Jet::find (Jet::SRC source) inline virtual
Reimplemented in Jetv1.
Definition at line 138 of file Jet.h.
virtual void Jet::insert_comp (Jet::SRC source, unsigned int compid) inline virtual
Reimplemented in Jetv1.
Definition at line 124 of file Jet.h.
Referenced by TrackJetInput::get_input(), TowerJetInput::get_input(), ClusterJetInput::get_input(), TruthJetInput::get_input(), FastJetAlgo::get_jets(), FastJetAlgoSub::get_jets(), and JetHepMCLoader::process_event().
virtual ConstIter Jet::lower_bound_comp (Jet::SRC source) const inline virtual
Reimplemented in Jetv1.
Definition at line 130 of file Jet.h.
Referenced by JetRecoEval::get_energy_contribution().
virtual Iter Jet::lower_bound_comp (Jet::SRC source) inline virtual
Reimplemented in Jetv1.
Definition at line 136 of file Jet.h.
virtual size_t Jet::size_comp () const inline virtual
Reimplemented in Jetv1.
Definition at line 120 of file Jet.h.
Referenced by LeptoquarksReco::AddJetInformation(), JetEvaluator::fillOutputNtuples(), JetEnergies::fillOutputNtuples(), MyJetAnalysis::process_event(), BDiJetModule::process_event(), QAG4SimulationJet::process_Spectrum(), and SoftLeptonTaggingTruth::process_Spectrum().
virtual ConstIter Jet::upper_bound_comp (Jet::SRC source) const inline virtual
Reimplemented in Jetv1.
Definition at line 131 of file Jet.h.
Referenced by JetRecoEval::get_energy_contribution().
virtual Iter Jet::upper_bound_comp (Jet::SRC source) inline virtual
Reimplemented in Jetv1.
Definition at line 137 of file Jet.h.