Analysis Software: gzbuffer Class Reference
gzbuffer Class Reference
#include <online_distribution/blob/master/newbasic/gzbuffer.h>
Public Member Functions
gzbuffer (PHDWORD *array, const int length)
~gzbuffer ()
Event * getEvent ()
Public Member Functions inherited from prdfBuffer
prdfBuffer ()
prdfBuffer (PHDWORD *array, const int length)
~prdfBuffer ()
Event * getEvent ()
int * getEventData ()
int isGood () const
int buffer_swap ()
int frame_swap (PHDWORD *fp, const int eventlength)
Public Member Functions inherited from buffer
buffer ()
virtual ~buffer ()
Protected Attributes
PHDWORD * bufferarray
buffer * theBuffer
Protected Attributes inherited from prdfBuffer
buffer_ptr bptr
PHDWORD * data_ptr
int buffer_size
int max_length
int current_index
int is_good
Additional Inherited Members
Static Public Member Functions inherited from buffer
static int makeBuffer (PHDWORD *bp, const int allocatedsize, buffer **bptr)
static int i4swap (const int in)
static unsigned int u4swap (const unsigned int in)
static int i22swap (const int in)
static short i2swap (const short in)
Detailed Description
Definition at line 7 of file gzbuffer.h.
Constructor & Destructor Documentation
gzbuffer::gzbuffer (PHDWORD * array, const int length)
Definition at line 5 of file gzbuffer.cc.
References bufferarray, BUFFERHEADERLENGTH, COUT, GZBUFFERMARKER, i, buffer::i4swap(), prdfBuffer::is_good, prdfBuffer::prdfBuffer(), theBuffer, and buffer::u4swap().
gzbuffer::~gzbuffer ()
Definition at line 51 of file gzbuffer.cc.
References bufferarray, and theBuffer.
Member Function Documentation
Event * gzbuffer::getEvent () virtual
Implements buffer.
Definition at line 44 of file gzbuffer.cc.
References buffer::getEvent(), and theBuffer.
Member Data Documentation
PHDWORD* gzbuffer::bufferarray protected
Definition at line 24 of file gzbuffer.h.
Referenced by gzbuffer(), and ~gzbuffer().
buffer* gzbuffer::theBuffer protected
Definition at line 25 of file gzbuffer.h.
Referenced by getEvent(), gzbuffer(), and ~gzbuffer().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/gzbuffer.h
online_distribution/blob/master/newbasic/gzbuffer.cc