Analysis Software: RawTowerGeomv2 Class Reference
RawTowerGeomv2 Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv2.h>
Public Member Functions
RawTowerGeomv2 ()
RawTowerGeomv2 (RawTowerDefs::keytype id)
virtual ~RawTowerGeomv2 ()
void identify (std::ostream &os=std::cout) const
void set_id (RawTowerDefs::keytype key)
RawTowerDefs::keytype get_id () const
int get_bineta () const
int get_binphi () const
int get_column () const
int get_row () const
void set_center_x (double x)
void set_center_y (double y)
void set_center_z (double z)
void set_size_x (double dx)
void set_size_y (double dy)
void set_size_z (double dz)
double get_center_x () const
double get_center_y () const
double get_center_z () const
double get_size_x () const
double get_size_y () const
double get_size_z () const
double get_volume () const
double get_center_radius () const
double get_eta () const
double get_phi () const
Public Member Functions inherited from RawTowerGeom
virtual ~RawTowerGeom ()
virtual void set_tower_type (int)
virtual int get_tower_type () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
RawTowerDefs::keytype _towerid
double _center_x
double _center_y
double _center_z
double _size_x
double _size_y
double _size_z
Additional Inherited Members
Protected Member Functions inherited from RawTowerGeom
RawTowerGeom ()
Detailed Description
Definition at line 10 of file RawTowerGeomv2.h.
Constructor & Destructor Documentation
RawTowerGeomv2::RawTowerGeomv2 ()
Definition at line 8 of file RawTowerGeomv2.cc.
RawTowerGeomv2::RawTowerGeomv2 (RawTowerDefs::keytype id)
Definition at line 18 of file RawTowerGeomv2.cc.
virtual RawTowerGeomv2::~RawTowerGeomv2 () inline virtual
Definition at line 15 of file RawTowerGeomv2.h.
Member Function Documentation
int RawTowerGeomv2::get_bineta () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 22 of file RawTowerGeomv2.h.
References _towerid, and RawTowerDefs::decode_index1().
int RawTowerGeomv2::get_binphi () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 23 of file RawTowerGeomv2.h.
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv2::get_center_radius () const virtual
Reimplemented from RawTowerGeom.
Definition at line 29 of file RawTowerGeomv2.cc.
References _center_x, and _center_y.
double RawTowerGeomv2::get_center_x () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 59 of file RawTowerGeomv2.h.
References _center_x.
Referenced by identify().
double RawTowerGeomv2::get_center_y () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 60 of file RawTowerGeomv2.h.
References _center_y.
Referenced by identify().
double RawTowerGeomv2::get_center_z () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 61 of file RawTowerGeomv2.h.
References _center_z.
Referenced by identify().
int RawTowerGeomv2::get_column () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 24 of file RawTowerGeomv2.h.
References _towerid, and RawTowerDefs::decode_index1().
double RawTowerGeomv2::get_eta () const virtual
Reimplemented from RawTowerGeom.
Definition at line 35 of file RawTowerGeomv2.cc.
References _center_x, _center_y, and _center_z.
RawTowerDefs::keytype RawTowerGeomv2::get_id () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 20 of file RawTowerGeomv2.h.
References _towerid.
double RawTowerGeomv2::get_phi () const virtual
Reimplemented from RawTowerGeom.
Definition at line 47 of file RawTowerGeomv2.cc.
References _center_x, and _center_y.
int RawTowerGeomv2::get_row () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 25 of file RawTowerGeomv2.h.
References _towerid, and RawTowerDefs::decode_index2().
double RawTowerGeomv2::get_size_x () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 63 of file RawTowerGeomv2.h.
References _size_x.
Referenced by identify().
double RawTowerGeomv2::get_size_y () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 64 of file RawTowerGeomv2.h.
References _size_y.
Referenced by identify().
double RawTowerGeomv2::get_size_z () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 65 of file RawTowerGeomv2.h.
References _size_z.
Referenced by identify().
double RawTowerGeomv2::get_volume () const inline virtual
Reimplemented from RawTowerGeom.
Definition at line 66 of file RawTowerGeomv2.h.
References _size_x, _size_y, and _size_z.
void RawTowerGeomv2::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from RawTowerGeom.
Definition at line 52 of file RawTowerGeomv2.cc.
References get_center_x(), get_center_y(), get_center_z(), get_size_x(), get_size_y(), and get_size_z().
void RawTowerGeomv2::set_center_x (double x) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 27 of file RawTowerGeomv2.h.
References _center_x, and x.
void RawTowerGeomv2::set_center_y (double y) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 32 of file RawTowerGeomv2.h.
References _center_y, and y.
void RawTowerGeomv2::set_center_z (double z) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 37 of file RawTowerGeomv2.h.
References _center_z, and z.
void RawTowerGeomv2::set_id (RawTowerDefs::keytype key) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 19 of file RawTowerGeomv2.h.
References _towerid.
void RawTowerGeomv2::set_size_x (double dx) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 43 of file RawTowerGeomv2.h.
References _size_x, and dx.
void RawTowerGeomv2::set_size_y (double dy) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 48 of file RawTowerGeomv2.h.
References _size_y, and dy.
void RawTowerGeomv2::set_size_z (double dz) inline virtual
Reimplemented from RawTowerGeom.
Definition at line 53 of file RawTowerGeomv2.h.
References _size_z.
Member Data Documentation
double RawTowerGeomv2::_center_x protected
Definition at line 75 of file RawTowerGeomv2.h.
Referenced by get_center_radius(), get_center_x(), get_eta(), get_phi(), and set_center_x().
double RawTowerGeomv2::_center_y protected
Definition at line 76 of file RawTowerGeomv2.h.
Referenced by get_center_radius(), get_center_y(), get_eta(), get_phi(), and set_center_y().
double RawTowerGeomv2::_center_z protected
Definition at line 77 of file RawTowerGeomv2.h.
Referenced by get_center_z(), get_eta(), and set_center_z().
double RawTowerGeomv2::_size_x protected
Definition at line 79 of file RawTowerGeomv2.h.
Referenced by get_size_x(), get_volume(), and set_size_x().
double RawTowerGeomv2::_size_y protected
Definition at line 80 of file RawTowerGeomv2.h.
Referenced by get_size_y(), get_volume(), and set_size_y().
double RawTowerGeomv2::_size_z protected
Definition at line 81 of file RawTowerGeomv2.h.
Referenced by get_size_z(), get_volume(), and set_size_z().
RawTowerDefs::keytype RawTowerGeomv2::_towerid protected
Definition at line 73 of file RawTowerGeomv2.h.
Referenced by get_bineta(), get_binphi(), get_column(), get_id(), get_row(), and set_id().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv2.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomv2.cc