Analysis Software: X_Event Class Reference
X_Event Class Reference
Public Member Functions
X_Event (PHDWORD *)
X_Event (int *)
~X_Event ()
int change_hf (const int oldhf, const int newhf)
X_Event (PHDWORD *)
X_Event (int *)
~X_Event ()
int change_id (const int oldid, const int newid)
Public Member Functions inherited from A_Event
A_Event (PHDWORD *)
A_Event (int *)
virtual ~A_Event ()
virtual unsigned int getEvtLength ()
virtual int getEvtType ()
virtual int getEvtSequence ()
virtual int getRunNumber ()
virtual void identify (std::ostream &os=std::cout) const
virtual void listFrame (const int id=0, OSTREAM &os=COUT) const
virtual void listHistory (const int id=0, OSTREAM &os=COUT) const
virtual void listError (const int id=0, OSTREAM &os=COUT) const
unsigned int getFrameEntry (const char *what, const int id=0, const int index=0) const
virtual Packet * getPacket (const int)
virtual Packet * getPacket (const int, const int hitFormat)
virtual int getPacketList (Packet *[], const int)
virtual int existPacket (const int)
virtual int Copy (int *, const unsigned int, int *, const char *what="")
int getErrorCode ()
unsigned int getTagWord (const int i=0) const
virtual int is_pointer_type () const
virtual int convert ()
virtual int getDate ()
virtual time_t getTime () const
Public Member Functions inherited from Event
virtual ~Event ()
virtual void listFrame (const int id=0, std::ostream &os=std::cout) const
virtual void listHistory (const int id=0, std::ostream &os=std::cout) const
virtual void listError (const int id=0, std::ostream &os=std::cout) const
Additional Inherited Members
Static Public Member Functions inherited from A_Event
static void dumpFrame (PHDWORD *fp, OSTREAM &os=COUT)
static void dumpErrorBlock (PHDWORD *fp, OSTREAM &os=COUT)
static void dumpBlock (PHDWORD *p, UINT len, OSTREAM &os=COUT, const int how=EVT_HEXADECIMAL)
static Packet * makePacket (PHDWORD *pp, const int hitformat=0)
Protected Member Functions inherited from A_Event
virtual int updateFramelist ()
virtual unsigned int getFrameValue (const char *what, PHDWORD *fp, const unsigned int index=0) const
virtual int createMap ()
Protected Attributes inherited from A_Event
int is_data_type
evtdata_ptr EventData
PHDWORD ** framelist
int NumberFrames
int hasMap
int errorcode
std::map< int, PHDWORD * > pmap
Detailed Description
Definition at line 42 of file changehitformat.cc.
Constructor & Destructor Documentation
X_Event::X_Event (PHDWORD * data)
Definition at line 58 of file changehitformat.cc.
X_Event::X_Event (int * data)
Definition at line 62 of file changehitformat.cc.
X_Event::~X_Event ()
Definition at line 66 of file changehitformat.cc.
X_Event::X_Event (PHDWORD *)
X_Event::X_Event (int *)
X_Event::~X_Event ()
Member Function Documentation
int X_Event::change_hf (const int oldhf, const int newhf)
Definition at line 69 of file changehitformat.cc.
References findFramePacketIndex(), findNextFramePacket(), A_Event::framelist, getPacketStructure(), getUnstructPacketHitFormat(), i, ptrFailure, setUnstructPacketHitFormat(), and Unstructured.
Referenced by main().
int X_Event::change_id (const int oldid, const int newid)
Definition at line 70 of file changeid.cc.
References findFramePacketId(), A_Event::framelist, i, ptrFailure, and setPacketId().
Referenced by main().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/changehitformat.cc
online_distribution/blob/master/newbasic/changeid.cc