Analysis Software: PHG4mRICHSteppingAction Class Reference
PHG4mRICHSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4mRICHSteppingAction.h>
Public Member Functions
PHG4mRICHSteppingAction (PHG4mRICHDetector *detector, PHParameters *params)
constructor
virtual ~PHG4mRICHSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Member Functions
int GetModuleID (G4VPhysicalVolume *volume)
Private Attributes
PHG4mRICHDetector * detector_
pointer to the detector
int IsBlackHole
std::string detectorname
std::string superdetector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
int savetrackid
int savepoststepstatus
Detailed Description
Definition at line 19 of file PHG4mRICHSteppingAction.h.
Constructor & Destructor Documentation
PHG4mRICHSteppingAction::PHG4mRICHSteppingAction (PHG4mRICHDetector * detector, PHParameters * params)
constructor
Definition at line 62 of file PHG4mRICHSteppingAction.cc.
PHG4mRICHSteppingAction::~PHG4mRICHSteppingAction () virtual
destroctor
Definition at line 80 of file PHG4mRICHSteppingAction.cc.
References hit.
Member Function Documentation
int PHG4mRICHSteppingAction::GetModuleID (G4VPhysicalVolume * volume) private
Definition at line 303 of file PHG4mRICHSteppingAction.cc.
References PHWHERE.
void PHG4mRICHSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 273 of file PHG4mRICHSteppingAction.cc.
References absorberhits_, detectorname, hits_, superdetector, and PHG4SteppingAction::Verbosity().
bool PHG4mRICHSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 85 of file PHG4mRICHSteppingAction.cc.
References absorberhits_, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_x(), PHG4HitContainer::GetID(), PHG4SteppingAction::GetName(), hit, hits_, PHG4mRICHDetector::INACTIVE, IsBlackHole, PHG4mRICHDetector::IsInmRICH(), PHG4Hit::Reset(), savehitcontainer, savepoststepstatus, saveshower, savetrackid, PHG4mRICHDetector::SENSOR, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4mRICHSteppingAction::absorberhits_ private
Definition at line 50 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4mRICHDetector* PHG4mRICHSteppingAction::detector_ private
pointer to the detector
Definition at line 39 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
std::string PHG4mRICHSteppingAction::detectorname private
Definition at line 45 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers().
PHG4Hit* PHG4mRICHSteppingAction::hit private
Definition at line 51 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4mRICHSteppingAction().
PHG4HitContainer* PHG4mRICHSteppingAction::hits_ private
pointer to hit container
Definition at line 49 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4mRICHSteppingAction::IsBlackHole private
Definition at line 43 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4mRICHSteppingAction::savehitcontainer private
Definition at line 52 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4mRICHSteppingAction::savepoststepstatus private
Definition at line 55 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4mRICHSteppingAction::saveshower private
Definition at line 53 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4mRICHSteppingAction::savetrackid private
Definition at line 54 of file PHG4mRICHSteppingAction.h.
Referenced by UserSteppingAction().
std::string PHG4mRICHSteppingAction::superdetector private
Definition at line 46 of file PHG4mRICHSteppingAction.h.
Referenced by SetInterfacePointers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4mRICHSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4mRICHSteppingAction.cc