Analysis Software: PH3DVertexing Class Reference
PH3DVertexing Class Reference abstract
Base class for track seeding.
#include <coresoftware/blob/master/offline/packages/trackreco/PH3DVertexing.h>
Public Member Functions
PH3DVertexing (const std::string &name="PH3DVertexing")
virtual ~PH3DVertexing ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
virtual const std::set
< unsigned int > & get_seeding_layers () const =0
virtual void set_seeding_layers (const unsigned int a[], const unsigned int n)=0
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int Setup (PHCompositeNode *topNode)
virtual int Process ()=0
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
Private Member Functions
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Base class for track seeding.
Definition at line 31 of file PH3DVertexing.h.
Constructor & Destructor Documentation
PH3DVertexing::PH3DVertexing (const std::string & name = "PH3DVertexing")
Definition at line 20 of file PH3DVertexing.cc.
virtual PH3DVertexing::~PH3DVertexing () inline virtual
Definition at line 35 of file PH3DVertexing.h.
Member Function Documentation
virtual const std::set<unsigned int>& PH3DVertexing::get_seeding_layers () const pure virtual
int PH3DVertexing::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 47 of file PH3DVertexing.cc.
References _assoc_container, _cluster_map, _track_map, _vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PH3DVertexing::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 29 of file PH3DVertexing.cc.
References Setup().
virtual int PH3DVertexing::Process () protected pure virtual
process event interface for trackers, called in process_event. implemented in derived classes
Referenced by process_event().
int PH3DVertexing::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 34 of file PH3DVertexing.cc.
References Process().
virtual void PH3DVertexing::set_seeding_layers (const unsigned int a[], const unsigned int n) pure virtual
int PH3DVertexing::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Definition at line 39 of file PH3DVertexing.cc.
References Fun4AllReturnCodes::EVENT_OK, and GetNodes().
Referenced by InitRun().
Member Data Documentation
AssocInfoContainer* PH3DVertexing::_assoc_container protected
Definition at line 58 of file PH3DVertexing.h.
Referenced by GetNodes().
TrkrClusterContainer* PH3DVertexing::_cluster_map protected
Definition at line 54 of file PH3DVertexing.h.
Referenced by GetNodes().
SvtxTrackMap* PH3DVertexing::_track_map protected
Definition at line 57 of file PH3DVertexing.h.
Referenced by GetNodes().
SvtxVertexMap* PH3DVertexing::_vertex_map protected
Definition at line 56 of file PH3DVertexing.h.
Referenced by GetNodes().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PH3DVertexing.h
coresoftware/blob/master/offline/packages/trackreco/PH3DVertexing.cc