Analysis Software: tutorials/blob/master/MyOwnTTree/macro/RunBoth.C File Reference
RunBoth.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <phool/recoConsts.h>
#include <mytree/AnalyzeSimpleTree.h>
#include <mytree/MakeSimpleTree.h>
Functions
void RunBoth ()
Function Documentation
void RunBoth ()
Definition at line 17 of file RunBoth.C.
References Fun4AllServer::dumpHistos(), Fun4AllServer::End(), in, recoConsts::instance(), Fun4AllServer::instance(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), Fun4AllServer::run(), and PHFlag::set_IntFlag().