Analysis Software: Dumper Class Reference
Dumper Class Reference
#include <coresoftware/blob/master/offline/packages/NodeDump/Dumper.h>
Public Member Functions
Dumper (const std::string &name="DUMPER")
virtual ~Dumper ()
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int process_event (PHCompositeNode *topNode)
void SetOutDir (const std::string &outdir)
void SetPrecision (const int digits)
int AddIgnore (const std::string &name)
int Select (const std::string &name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHNodeDump * nodedump
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 11 of file Dumper.h.
Constructor & Destructor Documentation
Dumper::Dumper (const std::string & name = "DUMPER")
Definition at line 14 of file Dumper.cc.
References nodedump.
Dumper::~Dumper () virtual
Definition at line 21 of file Dumper.cc.
References nodedump.
Member Function Documentation
int Dumper::AddIgnore (const std::string & name)
Definition at line 72 of file Dumper.cc.
References PHNodeDump::AddIgnore(), and nodedump.
int Dumper::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 41 of file Dumper.cc.
References PHNodeIterator::cd(), PHNodeDump::CloseOutputFiles(), PHNodeIterator::forEach(), and nodedump.
int Dumper::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 27 of file Dumper.cc.
References PHNodeIterator::cd(), PHNodeIterator::findFirst(), PHNodeIterator::forEach(), PHNodeDump::GetGlobalVars(), and nodedump.
int Dumper::Select (const std::string & name)
Definition at line 77 of file Dumper.cc.
References nodedump, and PHNodeDump::Select().
void Dumper::SetOutDir (const std::string & outdir)
Definition at line 60 of file Dumper.cc.
References nodedump, and PHNodeDump::SetOutDir().
Referenced by run_dump().
void Dumper::SetPrecision (const int digits)
Definition at line 66 of file Dumper.cc.
References nodedump, and PHNodeDump::SetPrecision().
Member Data Documentation
PHNodeDump* Dumper::nodedump private
Definition at line 24 of file Dumper.h.
Referenced by AddIgnore(), Dumper(), End(), process_event(), Select(), SetOutDir(), SetPrecision(), and ~Dumper().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/NodeDump/Dumper.h
coresoftware/blob/master/offline/packages/NodeDump/Dumper.cc