Analysis Software: RawTowerGeomContainer Class Reference
RawTowerGeomContainer Class Reference
base class to describe calorimeter geometries
#include <coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer.h>
Public Types
typedef std::map
< RawTowerDefs::keytype,
RawTowerGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
virtual ~RawTowerGeomContainer ()
default constructor for ROOT IO
virtual void identify (std::ostream &os=std::cout) const
virtual void set_calorimeter_id (RawTowerDefs::CalorimeterId)
8-bit calorimeter ID
virtual RawTowerDefs::CalorimeterId get_calorimeter_id () const
virtual ConstIterator add_tower_geometry (RawTowerGeom *geo)
go through all towers
virtual RawTowerGeom * get_tower_geometry (RawTowerDefs::keytype key)
virtual ConstRange get_tower_geometries (void) const
return all tower geometries
virtual Range get_tower_geometries (void)
virtual unsigned int size () const
virtual double get_radius () const
virtual double get_thickness () const
virtual int get_phibins () const
virtual int get_etabins () const
virtual std::pair< double, double > get_phibounds (const int ibin) const
virtual std::pair< double, double > get_etabounds (const int ibin) const
virtual double get_etacenter (const int ibin) const
virtual double get_phicenter (const int ibin) const
virtual int get_etabin (const double eta) const
virtual int get_phibin (const double phi) const
virtual void set_radius (const double r)
virtual void set_thickness (const double t)
virtual void set_phibins (const int i)
virtual void set_etabins (const int i)
virtual void set_etabounds (const int ibin, const std::pair< double, double > &bounds)
virtual void set_phibounds (const int ibin, const std::pair< double, double > &bounds)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
RawTowerGeomContainer ()
this class is not for use. Base class only
Detailed Description
base class to describe calorimeter geometries
Definition at line 24 of file RawTowerGeomContainer.h.
Member Typedef Documentation
typedef Map::const_iterator RawTowerGeomContainer::ConstIterator
Definition at line 29 of file RawTowerGeomContainer.h.
typedef std::pair<ConstIterator, ConstIterator> RawTowerGeomContainer::ConstRange
Definition at line 31 of file RawTowerGeomContainer.h.
typedef Map::iterator RawTowerGeomContainer::Iterator
Definition at line 28 of file RawTowerGeomContainer.h.
typedef std::map<RawTowerDefs::keytype, RawTowerGeom *> RawTowerGeomContainer::Map
Definition at line 27 of file RawTowerGeomContainer.h.
typedef std::pair<Iterator, Iterator> RawTowerGeomContainer::Range
Definition at line 30 of file RawTowerGeomContainer.h.
Constructor & Destructor Documentation
virtual RawTowerGeomContainer::~RawTowerGeomContainer () inline virtual
default constructor for ROOT IO
Definition at line 34 of file RawTowerGeomContainer.h.
RawTowerGeomContainer::RawTowerGeomContainer () inline protected
this class is not for use. Base class only
Definition at line 155 of file RawTowerGeomContainer.h.
Member Function Documentation
virtual ConstIterator RawTowerGeomContainer::add_tower_geometry (RawTowerGeom * geo) inline virtual
go through all towers
Reimplemented in RawTowerGeomContainerv1.
Definition at line 47 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual RawTowerDefs::CalorimeterId RawTowerGeomContainer::get_calorimeter_id () const inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 40 of file RawTowerGeomContainer.h.
References RawTowerDefs::NONE, and PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplateEEMC::Cell2Abs(), RawClusterBuilderTemplateFEMC::Cell2Abs(), and DumpRawTowerGeomContainer::process_Node().
virtual ConstRange RawTowerGeomContainer::get_tower_geometries (void) const inline virtual
return all tower geometries
Reimplemented in RawTowerGeomContainerv1.
Definition at line 59 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplateEEMC::InitRun(), RawClusterBuilderTemplateFEMC::InitRun(), RawClusterBuilderTemplate::InitRun(), PHG4TrackFastSim::InitRun(), RawTowerDigitizer::process_event(), DumpRawTowerGeomContainer::process_Node(), and RawTowerBuilderByHitIndex::ReadGeometryFromTable().
virtual Range RawTowerGeomContainer::get_tower_geometries (void) inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 64 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
virtual RawTowerGeom* RawTowerGeomContainer::get_tower_geometry (RawTowerDefs::keytype key) inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 52 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by DISKinematicsReco::AddGlobalCalorimeterInformation(), RawClusterBuilderTemplateEEMC::Cell2Abs(), RawClusterBuilderTemplateFEMC::Cell2Abs(), RawClusterBuilderFwd::CorrectPhi(), RawTowerBuilder::CreateNodes(), EpFinderEval::fill_tree(), CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), TrackProjectionTools::getE33Forward(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderGraph::process_event(), RawClusterBuilderFwd::process_event(), RawTowerDeadTowerInterp::process_event(), RawClusterBuilderTopo::process_event(), RawTowerCalibration::process_event(), ClusterIso::process_event(), and DetermineTowerBackground::process_event().
void RawTowerGeomContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in RawTowerGeomContainer_Cylinderv1, and RawTowerGeomContainerv1.
Definition at line 7 of file RawTowerGeomContainer.cc.
Referenced by RawTowerDeadTowerInterp::CreateNodes(), RawTowerBuilder::CreateNodes(), RawTowerCalibration::CreateNodes(), RawTowerCombiner::CreateNodes(), RawTowerDigitizer::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), HcalRawTowerBuilder::InitRun(), and DumpRawTowerGeomContainer::process_Node().
virtual void RawTowerGeomContainer::set_calorimeter_id (RawTowerDefs::CalorimeterId) inline virtual
8-bit calorimeter ID
Reimplemented in RawTowerGeomContainerv1.
Definition at line 39 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
virtual unsigned int RawTowerGeomContainer::size (void) const inline virtual
Reimplemented in RawTowerGeomContainerv1.
Definition at line 70 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by QAG4SimulationCalorimeter::process_event_Tower(), and DumpRawTowerGeomContainer::process_Node().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer.h
coresoftware/blob/master/offline/packages/CaloBase/RawTowerGeomContainer.cc