Analysis Software: PHG4SpacalPrototype4SteppingAction Class Reference
PHG4SpacalPrototype4SteppingAction Class Reference
#include <prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4SpacalPrototype4SteppingAction.h>
Public Member Functions
PHG4SpacalPrototype4SteppingAction (PHG4SpacalPrototype4Detector *)
constructor
virtual ~PHG4SpacalPrototype4SteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
double get_zmin ()
double get_zmax ()
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4SpacalPrototype4Detector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
PHG4HitContainer * savehitcontainer
PHG4Shower * saveshower
Detailed Description
Definition at line 25 of file PHG4SpacalPrototype4SteppingAction.h.
Constructor & Destructor Documentation
PHG4SpacalPrototype4SteppingAction::PHG4SpacalPrototype4SteppingAction (PHG4SpacalPrototype4Detector * detector) explicit
constructor
Definition at line 47 of file PHG4SpacalPrototype4SteppingAction.cc.
virtual PHG4SpacalPrototype4SteppingAction::~PHG4SpacalPrototype4SteppingAction () inline virtual
destroctor
Definition at line 32 of file PHG4SpacalPrototype4SteppingAction.h.
Member Function Documentation
double PHG4SpacalPrototype4SteppingAction::get_zmax ()
Definition at line 354 of file PHG4SpacalPrototype4SteppingAction.cc.
References detector_, PHG4SpacalPrototype4Detector::get_geom(), and PHG4CylinderGeomv1::get_zmax().
double PHG4SpacalPrototype4SteppingAction::get_zmin ()
Definition at line 345 of file PHG4SpacalPrototype4SteppingAction.cc.
References detector_, PHG4SpacalPrototype4Detector::get_geom(), and PHG4CylinderGeomv1::get_zmin().
void PHG4SpacalPrototype4SteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 309 of file PHG4SpacalPrototype4SteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4SpacalPrototype4Detector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4SpacalPrototype4SteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 59 of file PHG4SpacalPrototype4SteppingAction.cc.
References PHG4SpacalPrototype4Detector::ABSORBER, absorberhits_, PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), detector_, PHG4SpacalPrototype4Detector::FIBER_CLADING, PHG4SpacalPrototype4Detector::FIBER_CORE, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Hit::get_light_yield(), PHG4HitContainer::GetID(), PHG4Detector::GetName(), PHG4SteppingAction::GetVisibleEnergyDeposition(), hit, hits_, PHG4SpacalPrototype4Detector::INACTIVE, PHG4SpacalPrototype4Detector::IsInCylinderActive(), PHG4Hit::Reset(), savehitcontainer, saveshower, PHG4CylinderGeom_Spacalv3::scint_id_coder::scint_ID, PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_light_yield(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::StoreLocalCoordinate(), and PHG4SteppingAction::Verbosity().
Member Data Documentation
PHG4HitContainer* PHG4SpacalPrototype4SteppingAction::absorberhits_ private
Definition at line 56 of file PHG4SpacalPrototype4SteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4SpacalPrototype4Detector* PHG4SpacalPrototype4SteppingAction::detector_ private
pointer to the detector
Definition at line 52 of file PHG4SpacalPrototype4SteppingAction.h.
Referenced by get_zmax(), get_zmin(), SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4SpacalPrototype4SteppingAction::hit private
Definition at line 57 of file PHG4SpacalPrototype4SteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4SpacalPrototype4SteppingAction::hits_ private
pointer to hit container
Definition at line 55 of file PHG4SpacalPrototype4SteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HitContainer* PHG4SpacalPrototype4SteppingAction::savehitcontainer private
Definition at line 58 of file PHG4SpacalPrototype4SteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4SpacalPrototype4SteppingAction::saveshower private
Definition at line 59 of file PHG4SpacalPrototype4SteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4SpacalPrototype4SteppingAction.h
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4SpacalPrototype4SteppingAction.cc