Analysis Software: online_distribution/blob/master/newbasic/CpacketV1.h File Reference
CpacketV1.h File Reference
#include "phenixOnline.h"
#include "packetPublic.h"
#include "packetV1Public.h"
#include "packetHdrV1.h"
#include "formatError.h"
#include "dataBlock.h"
Functions
VALUE_ret makePacketV1Hdr (PACKET_ptr, UINT)
PTR_ret findPacketV1DataStart (PACKET_ptr)
PTR_ret findPacketV1DataEnd (PACKET_ptr)
PTR_ret findPacketV1DebugStart (PACKET_ptr)
PTR_ret findPacketV1ErrorStart (PACKET_ptr)
INLINE_P PTR_ret findPacketV1DataDescr (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1DataLength (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1DebugLength (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1ErrorLength (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1Padding (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1NumErrors (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1Id (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1Structure (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1Endianism (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1Status (PACKET_ptr)
INLINE_P VALUE_ret getPacketV1DataDescrLength (PACKET_ptr)
INLINE_P VALUE_ret orPacketV1Status (PACKET_ptr, UINT)
INLINE_P VALUE_ret adjustPacketV1DataLength (PACKET_ptr, int)
INLINE_P VALUE_ret adjustPacketV1DebugLength (PACKET_ptr, int)
INLINE_P VALUE_ret adjustPacketV1ErrorLength (PACKET_ptr, int)
LOGIC_ret validPacketV1Hdr (PACKET_ptr)
INLINE_P LOGIC_ret emptyPacketV1 (PACKET_ptr)
INLINE_P LOGIC_ret setPacketV1Id (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1Endianism (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1Structure (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1Padding (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1Status (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1ErrorLength (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1DebugLength (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1NumErrors (PACKET_ptr, UINT)
INLINE_P LOGIC_ret setPacketV1DataDescrLength (PACKET_ptr, UINT)
Function Documentation
INLINE_D VALUE_ret adjustPacketV1DataLength (PACKET_ptr packet_ptr, int addDwords)
Definition at line 188 of file CpacketV1.h.
References getPacketV1DataLength().
INLINE_D VALUE_ret adjustPacketV1DebugLength (PACKET_ptr packet_ptr, int addLength)
Definition at line 193 of file CpacketV1.h.
References getPacketV1DebugLength(), setPacketV1DebugLength(), and valueFailure.
INLINE_D VALUE_ret adjustPacketV1ErrorLength (PACKET_ptr packet_ptr, int addLength)
Definition at line 205 of file CpacketV1.h.
References getPacketV1ErrorLength(), setPacketV1ErrorLength(), and valueFailure.
INLINE_D LOGIC_ret emptyPacketV1 (PACKET_ptr packet_ptr)
Definition at line 83 of file CpacketV1.h.
References getPacketHdrLength(), and getPacketLength().
INLINE_D PTR_ret findPacketV1DataDescr (PACKET_ptr packet_ptr)
Definition at line 277 of file CpacketV1.h.
References DATADESCR_OFFSET_OF_DWORD.
PTR_ret findPacketV1DataEnd (PACKET_ptr)
Definition at line 71 of file CpacketV1.C.
References findPacketV1DebugStart().
PTR_ret findPacketV1DataStart (PACKET_ptr)
Definition at line 66 of file CpacketV1.C.
References getPacketHdrLength().
PTR_ret findPacketV1DebugStart (PACKET_ptr)
Definition at line 51 of file CpacketV1.C.
References getPacketLength(), getPacketV1DebugLength(), and getPacketV1ErrorLength().
Referenced by findPacketV1DataEnd().
PTR_ret findPacketV1ErrorStart (PACKET_ptr)
Definition at line 60 of file CpacketV1.C.
References getPacketLength(), and getPacketV1ErrorLength().
INLINE_D VALUE_ret getPacketV1DataDescrLength (PACKET_ptr packet_ptr)
Definition at line 155 of file CpacketV1.h.
References DESCR_LENGTH_MASK, DESCR_LENGTH_OFFSET_IN_DWORD, DESCR_LENGTH_OFFSET_OF_DWORD, and getBitsMACRO.
INLINE_D VALUE_ret getPacketV1DataLength (PACKET_ptr packet_ptr)
Definition at line 88 of file CpacketV1.h.
References getPacketDebugLength(), getPacketErrorLength(), getPacketHdrLength(), getPacketLength(), getPacketPadding(), getPacketStructure(), getUnstructPacketWordSize(), and Unstructured.
Referenced by adjustPacketV1DataLength().
INLINE_D VALUE_ret getPacketV1DebugLength (PACKET_ptr packet_ptr)
Definition at line 113 of file CpacketV1.h.
References DEBUG_LENGTH_MASK, DEBUG_LENGTH_OFFSET_IN_DWORD, DEBUG_LENGTH_OFFSET_OF_DWORD, and getBitsMACRO.
Referenced by adjustPacketV1DebugLength(), and findPacketV1DebugStart().
INLINE_D VALUE_ret getPacketV1Endianism (PACKET_ptr packet_ptr)
Definition at line 161 of file CpacketV1.h.
References ENDIANISM_MASK, ENDIANISM_OFFSET_IN_DWORD, ENDIANISM_OFFSET_OF_DWORD, and getBitsMACRO.
INLINE_D VALUE_ret getPacketV1ErrorLength (PACKET_ptr packet_ptr)
Definition at line 119 of file CpacketV1.h.
References getBitsMACRO, PACKET_ERROR_LENGTH_MASK, PACKET_ERROR_LENGTH_OFFSET_IN_DWORD, and PACKET_ERROR_LENGTH_OFFSET_OF_DWORD.
Referenced by adjustPacketV1ErrorLength(), findPacketV1DebugStart(), findPacketV1ErrorStart(), and getPacketV1NumErrors().
INLINE_D VALUE_ret getPacketV1Id (PACKET_ptr packet_ptr)
Definition at line 138 of file CpacketV1.h.
References getWordMACRO, and ID_OFFSET_OF_DWORD.
INLINE_D VALUE_ret getPacketV1NumErrors (PACKET_ptr packet_ptr)
Definition at line 132 of file CpacketV1.h.
References calcNumErrorsV1(), and getPacketV1ErrorLength().
INLINE_D VALUE_ret getPacketV1Padding (PACKET_ptr packet_ptr)
Definition at line 126 of file CpacketV1.h.
References getBitsMACRO, PACKET_PADDING_MASK, PACKET_PADDING_OFFSET_IN_DWORD, and PACKET_PADDING_OFFSET_OF_DWORD.
INLINE_D VALUE_ret getPacketV1Status (PACKET_ptr packet_ptr)
Definition at line 149 of file CpacketV1.h.
References getBitsMACRO, PACKET_STATUS_MASK, PACKET_STATUS_OFFSET_IN_DWORD, and PACKET_STATUS_OFFSET_OF_DWORD.
INLINE_D VALUE_ret getPacketV1Structure (PACKET_ptr packet_ptr)
Definition at line 143 of file CpacketV1.h.
References getBitsMACRO, STRUCTURE_MASK, STRUCTURE_OFFSET_IN_DWORD, and STRUCTURE_OFFSET_OF_DWORD.
VALUE_ret makePacketV1Hdr (PACKET_ptr , UINT)
INLINE_D VALUE_ret orPacketV1Status (PACKET_ptr packet_ptr, UINT inBits)
Definition at line 167 of file CpacketV1.h.
References FORMAT_ERR_INVALID_DATA, getBitsMACRO, PACKET_STATUS_MASK, PACKET_STATUS_NUM_BITS, PACKET_STATUS_OFFSET_IN_DWORD, PACKET_STATUS_OFFSET_OF_DWORD, setBitsMACRO, setUserError(), and valueFailure.
INLINE_D LOGIC_ret setPacketV1DataDescrLength (PACKET_ptr packet_ptr, UINT inLength)
Definition at line 266 of file CpacketV1.h.
References DESCR_LENGTH_MASK, DESCR_LENGTH_OFFSET_IN_DWORD, DESCR_LENGTH_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setPacketV1DebugLength (PACKET_ptr packet_ptr, UINT inLength)
Definition at line 259 of file CpacketV1.h.
References DEBUG_LENGTH_MASK, DEBUG_LENGTH_OFFSET_IN_DWORD, DEBUG_LENGTH_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
Referenced by adjustPacketV1DebugLength().
INLINE_D LOGIC_ret setPacketV1Endianism (PACKET_ptr packet_ptr, UINT inEndianism)
Definition at line 223 of file CpacketV1.h.
References ENDIANISM_MASK, ENDIANISM_OFFSET_IN_DWORD, ENDIANISM_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setPacketV1ErrorLength (PACKET_ptr packet_ptr, UINT inLength)
Definition at line 252 of file CpacketV1.h.
References PACKET_ERROR_LENGTH_MASK, PACKET_ERROR_LENGTH_OFFSET_IN_DWORD, PACKET_ERROR_LENGTH_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
Referenced by adjustPacketV1ErrorLength().
INLINE_D LOGIC_ret setPacketV1Id (PACKET_ptr packet_ptr, UINT inId)
Definition at line 217 of file CpacketV1.h.
References ID_OFFSET_OF_DWORD, setWordMACRO, and TRUE.
INLINE_P LOGIC_ret setPacketV1NumErrors (PACKET_ptr , UINT)
INLINE_D LOGIC_ret setPacketV1Padding (PACKET_ptr packet_ptr, UINT inPadding)
Definition at line 238 of file CpacketV1.h.
References PACKET_PADDING_MASK, PACKET_PADDING_OFFSET_IN_DWORD, PACKET_PADDING_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setPacketV1Status (PACKET_ptr packet_ptr, UINT inStatus)
Definition at line 245 of file CpacketV1.h.
References PACKET_STATUS_MASK, PACKET_STATUS_OFFSET_IN_DWORD, PACKET_STATUS_OFFSET_OF_DWORD, setBitsMACRO, and TRUE.
INLINE_D LOGIC_ret setPacketV1Structure (PACKET_ptr packet_ptr, UINT inStruct)
Definition at line 231 of file CpacketV1.h.
References setBitsMACRO, STRUCTURE_MASK, STRUCTURE_OFFSET_IN_DWORD, STRUCTURE_OFFSET_OF_DWORD, and TRUE.
LOGIC_ret validPacketV1Hdr (PACKET_ptr)
Definition at line 82 of file CpacketV1.C.
References FALSE, FORMAT_ERR_INVALID_HEADER, getPacketHdrLength(), packetV1HdrLength, setPacketError(), setPacketSuccess(), and TRUE.