Analysis Software: HelixHoughFuncs Class Reference
HelixHoughFuncs Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs.h>
Public Member Functions
virtual ~HelixHoughFuncs ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual void set_current_zoom (unsigned int cur_zoom)
virtual void set_hough_space (HelixHoughSpace *hough_space)
virtual void calculate_dzdl_range (float *hitpos3d, std::vector< float > &z0_range, std::vector< float > &kappa_phi_d_ranges, float *dzdl_range)
virtual void calculate_phi_range (float *hitpos2d, std::vector< float > &kappa_d_ranges, float *phi_r_range, float *phi_l_range)
virtual void calculate_phi_range (float *hitpos2d, std::vector< float > &kappa_d_ranges, int helicity, float *phi_range, float *phi_next_range)
virtual void calculate_phi_range (float *hitpos2d, std::vector< float > &kappa_d_ranges, int helicity, float *phi_range, float *phi_prev_range, float *phi_next_range)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
HelixHoughFuncs ()
ClassDef (HelixHoughFuncs, 1)
Detailed Description
Definition at line 13 of file HelixHoughFuncs.h.
Constructor & Destructor Documentation
virtual HelixHoughFuncs::~HelixHoughFuncs () inline virtual
Definition at line 16 of file HelixHoughFuncs.h.
HelixHoughFuncs::HelixHoughFuncs () inline protected
Definition at line 42 of file HelixHoughFuncs.h.
Member Function Documentation
virtual void HelixHoughFuncs::calculate_dzdl_range (float * hitpos3d, std::vector< float > & z0_range, std::vector< float > & kappa_phi_d_ranges, float * dzdl_range) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 30 of file HelixHoughFuncs.h.
Referenced by PHInitZVertexing::vote_z(), PHPatternReco::vote_z(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual void HelixHoughFuncs::calculate_phi_range (float * hitpos2d, std::vector< float > & kappa_d_ranges, float * phi_r_range, float * phi_l_range) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 31 of file HelixHoughFuncs.h.
Referenced by PHInitZVertexing::vote_xy(), and PHPatternReco::vote_xy().
virtual void HelixHoughFuncs::calculate_phi_range (float * hitpos2d, std::vector< float > & kappa_d_ranges, int helicity, float * phi_range, float * phi_next_range) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 32 of file HelixHoughFuncs.h.
virtual void HelixHoughFuncs::calculate_phi_range (float * hitpos2d, std::vector< float > & kappa_d_ranges, int helicity, float * phi_range, float * phi_prev_range, float * phi_next_range) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 33 of file HelixHoughFuncs.h.
HelixHoughFuncs::ClassDef (HelixHoughFuncs , 1) protected
virtual PHObject* HelixHoughFuncs::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 25 of file HelixHoughFuncs.h.
virtual void HelixHoughFuncs::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 20 of file HelixHoughFuncs.h.
References os.
virtual int HelixHoughFuncs::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 24 of file HelixHoughFuncs.h.
virtual void HelixHoughFuncs::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in HelixHoughFuncs_v1.
Definition at line 23 of file HelixHoughFuncs.h.
virtual void HelixHoughFuncs::set_current_zoom (unsigned int cur_zoom) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 28 of file HelixHoughFuncs.h.
Referenced by PHInitZVertexing::vote_xy(), PHPatternReco::vote_xy(), PHPatternReco::vote_z(), PHInitZVertexing::vote_z(), PHPatternReco::vote_z_init(), and PHInitZVertexing::vote_z_init().
virtual void HelixHoughFuncs::set_hough_space (HelixHoughSpace * hough_space) inline virtual
Reimplemented in HelixHoughFuncs_v1.
Definition at line 29 of file HelixHoughFuncs.h.
Referenced by PHPatternReco::Init(), and PHInitZVertexing::Setup().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/trackreco/HelixHoughFuncs.h