Analysis Software: online_distribution/blob/master/newbasic/prdfsplit.cc File Reference
prdfsplit.cc File Reference
#include "buffer.h"
#include <cstdio>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <csignal>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
Functions
void exitmsg ()
int check_buffermarker (const int bm)
int main (int argc, char *argv[])
Function Documentation
int check_buffermarker (const int bm)
Definition at line 28 of file prdfsplit.cc.
References BUFFERMARKER, GZBUFFERMARKER, buffer::i4swap(), and LZO1XBUFFERMARKER.
Referenced by main().
void exitmsg ()
Definition at line 17 of file prdfsplit.cc.
int main (int argc, char * argv[])
Definition at line 50 of file prdfsplit.cc.
References check_buffermarker(), fd, i, buffer::i4swap(), and write().