Analysis Software: PROTOTYPE3_FEM Namespace Reference
PROTOTYPE3_FEM Namespace Reference
Functions
int GetHBDCh (const std::string &caloname, int i_column, int i_row)
FEM mapping of channel -> calorimeter col and rows.
bool SampleFit_PowerLawExp (const std::vector< double > &samples, double &peak, double &peak_sample, double &pedstal, const int verbosity=0)
Abhisek's power-law + exp fit.
double SignalShape_PowerLawExp (double *x, double *par)
Variables
const int PACKET_ID = 21101
const int NSAMPLES = 24
const int NCH_IHCAL_ROWS = 4
const int NCH_IHCAL_COLUMNS = 4
const int NCH_OHCAL_ROWS = 4
const int NCH_OHCAL_COLUMNS = 4
const int NCH_EMCAL_ROWS = 8
const int NCH_EMCAL_COLUMNS = 8
const int SATURATED_ADC_ERROR = 100
const int DEAD_CHANNEL_ERROR = 300
const int PACKET_EMCAL_HIGHETA_FLAG = 905
Function Documentation
int PROTOTYPE3_FEM::GetHBDCh (const std::string & caloname, int i_column, int i_row)
FEM mapping of channel -> calorimeter col and rows.
Definition at line 25 of file PROTOTYPE3_FEM.cc.
References assert, PROTOTYPE2_FEM::NCH_EMCAL_COLUMNS, and PROTOTYPE2_FEM::NCH_EMCAL_ROWS.
bool PROTOTYPE3_FEM::SampleFit_PowerLawExp (const std::vector< double > & samples, double & peak, double & peak_sample, double & pedstal, const int verbosity = 0)
Abhisek's power-law + exp fit.
Definition at line 117 of file PROTOTYPE3_FEM.cc.
References assert, gpulse, i, NSAMPLES, pedestal(), and TPCDaqDefs::FEEv1::SignalShape_PowerLawExp().
Referenced by RawTower_Prototype3::get_energy_power_law_exp().
double PROTOTYPE3_FEM::SignalShape_PowerLawExp (double * x, double * par)
Definition at line 212 of file PROTOTYPE3_FEM.cc.
References pedestal(), and signal().
Variable Documentation
const int PROTOTYPE3_FEM::DEAD_CHANNEL_ERROR = 300
Error assigned to dead channels
Definition at line 33 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NCH_EMCAL_COLUMNS = 8
Definition at line 27 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NCH_EMCAL_ROWS = 8
Number of EMCAL towers
Definition at line 26 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NCH_IHCAL_COLUMNS = 4
Definition at line 19 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NCH_IHCAL_ROWS = 4
Number of Inner HCAL towers
Definition at line 18 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NCH_OHCAL_COLUMNS = 4
Definition at line 23 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NCH_OHCAL_ROWS = 4
Number of Outer HCAL towers
Definition at line 22 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::NSAMPLES = 24
Number of ADC Samples per tower
Definition at line 15 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::PACKET_EMCAL_HIGHETA_FLAG = 905
special treatment for EMCal tagging packet See also https://wiki.bnl.gov/sPHENIX/index.php/2017_calorimeter_beam_test#What_is_new_in_the_data_structures_in_2017 Result stored in RUN_INFO node under variable EMCAL_Is_HighEta
Definition at line 53 of file PROTOTYPE3_FEM.h.
const int PROTOTYPE3_FEM::PACKET_ID = 21101
Packet ID
Definition at line 12 of file PROTOTYPE3_FEM.h.
Referenced by Fun4All_TestBeam().
const int PROTOTYPE3_FEM::SATURATED_ADC_ERROR = 100
Error assigned to saturated ADCs
Definition at line 30 of file PROTOTYPE3_FEM.h.