Analysis Software: coresoftware/blob/master/generators/JETSCAPE/readerTest.cc File Reference
readerTest.cc File Reference
#include <iostream>
#include <fstream>
#include <memory>
#include <chrono>
#include <thread>
#include "gzstream.h"
#include "PartonShower.h"
#include "JetScapeLogger.h"
#include "JetScapeReader.h"
#include "JetScapeBanner.h"
#include "fjcore.hh"
#include <GTL/dfs.h>
Functions
void Show ()
void AnalyzeGraph (shared_ptr< PartonShower > mS)
ostream & operator<< (ostream &ostr, const fjcore::PseudoJet &jet)
overloaded jet info output
int main (int argc, char **argv)
Function Documentation
void AnalyzeGraph (shared_ptr< PartonShower > mS)
Definition at line 142 of file readerTest.cc.
References dfs().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 53 of file readerTest.cc.
References AnalyzeGraph(), i, k, and Show().
ostream & operator<< (ostream & ostr, const fjcore::PseudoJet & jet)
overloaded jet info output
Definition at line 197 of file readerTest.cc.
void Show ()