Analysis Software: PHG4InEventCompress Class Reference
PHG4InEventCompress Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4InEventCompress.h>
Public Member Functions
PHG4InEventCompress (const std::string &name="PHG4InEventCompress")
virtual ~PHG4InEventCompress ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Attributes
VariableArray * vtxarray
VariableArray * particlearray
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 13 of file PHG4InEventCompress.h.
Constructor & Destructor Documentation
PHG4InEventCompress::PHG4InEventCompress (const std::string & name = "PHG4InEventCompress")
Definition at line 28 of file PHG4InEventCompress.cc.
virtual PHG4InEventCompress::~PHG4InEventCompress () inline virtual
Definition at line 17 of file PHG4InEventCompress.h.
Member Function Documentation
int PHG4InEventCompress::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 110 of file PHG4InEventCompress.cc.
References Fun4AllReturnCodes::EVENT_OK.
int PHG4InEventCompress::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 35 of file PHG4InEventCompress.cc.
References PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), varids::G4PARTICLEV1, varids::G4VTXV1, particlearray, and vtxarray.
int PHG4InEventCompress::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 55 of file PHG4InEventCompress.cc.
References Fun4AllReturnCodes::EVENT_OK, VariableArrayUtils::FloatToShortBits(), PHG4InEvent::GetParticles(), PHG4InEvent::GetVertices(), particlearray, VariableArray::set_val(), and vtxarray.
Member Data Documentation
VariableArray* PHG4InEventCompress::particlearray protected
Definition at line 24 of file PHG4InEventCompress.h.
Referenced by InitRun(), and process_event().
VariableArray* PHG4InEventCompress::vtxarray protected
Definition at line 23 of file PHG4InEventCompress.h.
Referenced by InitRun(), and process_event().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4InEventCompress.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4InEventCompress.cc