Analysis Software: macros/blob/master/macros/g4simulations/G4_CaloTrigger.C File Reference
G4_CaloTrigger.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <calotrigger/CaloTriggerSim.h>
Functions
void CaloTriggerInit ()
void CaloTrigger_Sim (int verbosity=0)
Function Documentation
void CaloTrigger_Sim (int verbosity = 0)
Definition at line 10 of file G4_CaloTrigger.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), and Fun4All_G4_sPHENIX_truthphotonjet().
void CaloTriggerInit ()
Definition at line 8 of file G4_CaloTrigger.C.