Analysis Software: PHG4MvtxHitReco Class Reference
PHG4MvtxHitReco Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h>
Public Member Functions
PHG4MvtxHitReco (const std::string &name="PHG4MvtxRECO")
virtual ~PHG4MvtxHitReco ()
int InitRun (PHCompositeNode *topNode)
module initialization
int process_event (PHCompositeNode *topNode)
event processing
void Detector (const std::string &d)
double get_timing_window_min (const int i)
double get_timing_window_max (const int i)
void set_timing_window (const int detid, const double tmin, const double tmax)
void SetDefaultParameters ()
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterContainerInterface
PHParameterContainerInterface (const std::string &name)
virtual ~PHParameterContainerInterface ()
void set_name (const std::string &name)
void set_double_param (const int id, const std::string &name, const double dval)
double get_double_param (const int id, const std::string &name) const
void set_int_param (const int id, const std::string &name, const int ival)
int get_int_param (const int id, const std::string &name) const
void set_string_param (const int id, const std::string &name, const std::string &sval)
std::string get_string_param (const int id, const std::string &name) const
void UpdateParametersWithMacro ()
void CreateInitialize (const int detid)
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
int ExistDetid (const int detid) const
Protected Attributes
std::string detector
std::string hitnodename
std::string geonodename
std::map< int, std::pair
< double, double > > tmin_max
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterContainerInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
const PHParametersContainer * GetParamsContainer ()
PHParametersContainer * GetParamsContainerModify ()
const PHParameters * GetDefaultParameters ()
Detailed Description
Definition at line 14 of file PHG4MvtxHitReco.h.
Constructor & Destructor Documentation
PHG4MvtxHitReco::PHG4MvtxHitReco (const std::string & name = "PHG4MvtxRECO") explicit
Definition at line 45 of file PHG4MvtxHitReco.cc.
References SetDefaultParameters(), and Fun4AllBase::Verbosity().
virtual PHG4MvtxHitReco::~PHG4MvtxHitReco () inline virtual
Definition at line 19 of file PHG4MvtxHitReco.h.
Member Function Documentation
void PHG4MvtxHitReco::Detector (const std::string & d) inline
Definition at line 27 of file PHG4MvtxHitReco.h.
References d.
double PHG4MvtxHitReco::get_timing_window_max (const int i) inline
Definition at line 30 of file PHG4MvtxHitReco.h.
References i, and tmin_max.
double PHG4MvtxHitReco::get_timing_window_min (const int i) inline
Definition at line 29 of file PHG4MvtxHitReco.h.
References i, and tmin_max.
int PHG4MvtxHitReco::InitRun (PHCompositeNode * topNode) virtual
module initialization
Reimplemented from SubsysReco.
Definition at line 55 of file PHG4MvtxHitReco.cc.
References PHCompositeNode::addNode(), detector, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), geonodename, hitnodename, PHG4CylinderGeomContainer::identify(), PHWHERE, and Fun4AllBase::Verbosity().
int PHG4MvtxHitReco::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 124 of file PHG4MvtxHitReco.cc.
References TrkrHitTruthAssoc::addAssoc(), TrkrHit::addEnergy(), PHG4Utils::circle_rectangle_intersection(), double(), Fun4AllReturnCodes::EVENT_OK, TrkrHitSetContainer::findOrAddHitSet(), MvtxDefs::genHitKey(), MvtxDefs::genHitSetKey(), geonodename, CylinderGeom_Mvtx::get_layer(), CylinderGeom_Mvtx::get_local_coords_from_pixel(), CylinderGeom_Mvtx::get_local_from_world_coords(), CylinderGeom_Mvtx::get_NX(), CylinderGeom_Mvtx::get_NZ(), CylinderGeom_Mvtx::get_pixel_from_local_coords(), CylinderGeom_Mvtx::get_pixel_number_from_xbin_zbin(), CylinderGeom_Mvtx::get_pixel_x(), CylinderGeom_Mvtx::get_pixel_X_from_pixel_number(), CylinderGeom_Mvtx::get_pixel_z(), CylinderGeom_Mvtx::get_pixel_Z_from_pixel_number(), CylinderGeom_Mvtx::get_world_from_local_coords(), PHG4HitContainer::getHits(), PHG4CylinderGeomContainer::GetLayerGeom(), PHG4HitContainer::getLayers(), hitnodename, i, CylinderGeom_Mvtx::identify(), TrkrHitTruthAssoc::identify(), M_PI, PHWHERE, PHG4Hit::prop_chip_index, PHG4Hit::prop_eion, PHG4Hit::prop_half_stave_index, PHG4Hit::prop_module_index, PHG4Hit::prop_stave_index, tmin_max, Fun4AllBase::Verbosity(), x2, z1, and z2.
void PHG4MvtxHitReco::set_timing_window (const int detid, const double tmin, const double tmax)
Definition at line 551 of file PHG4MvtxHitReco.cc.
References it, and tmin_max.
Referenced by Tracking_Cells().
void PHG4MvtxHitReco::SetDefaultParameters () virtual
Implements PHParameterContainerInterface.
Definition at line 564 of file PHG4MvtxHitReco.cc.
References tmin_max.
Referenced by PHG4MvtxHitReco().
Member Data Documentation
std::string PHG4MvtxHitReco::detector protected
Definition at line 36 of file PHG4MvtxHitReco.h.
Referenced by InitRun().
std::string PHG4MvtxHitReco::geonodename protected
Definition at line 38 of file PHG4MvtxHitReco.h.
Referenced by InitRun(), and process_event().
std::string PHG4MvtxHitReco::hitnodename protected
Definition at line 37 of file PHG4MvtxHitReco.h.
Referenced by InitRun(), and process_event().
std::map<int, std::pair<double, double> > PHG4MvtxHitReco::tmin_max protected
Definition at line 39 of file PHG4MvtxHitReco.h.
Referenced by get_timing_window_max(), get_timing_window_min(), process_event(), set_timing_window(), and SetDefaultParameters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc