Analysis Software: for cylindrical calorimeter only as implemented in RawTowerGeomContainer_Cylinderv1
for cylindrical calorimeter only as implemented in RawTowerGeomContainer_Cylinderv1
Functions
virtual double RawTowerGeomContainer::get_radius () const
virtual double RawTowerGeomContainer::get_thickness () const
virtual int RawTowerGeomContainer::get_phibins () const
virtual int RawTowerGeomContainer::get_etabins () const
virtual std::pair< double, double > RawTowerGeomContainer::get_phibounds (const int ibin) const
virtual std::pair< double, double > RawTowerGeomContainer::get_etabounds (const int ibin) const
virtual double RawTowerGeomContainer::get_etacenter (const int ibin) const
virtual double RawTowerGeomContainer::get_phicenter (const int ibin) const
virtual int RawTowerGeomContainer::get_etabin (const double eta) const
virtual int RawTowerGeomContainer::get_phibin (const double phi) const
virtual void RawTowerGeomContainer::set_radius (const double r)
virtual void RawTowerGeomContainer::set_thickness (const double t)
virtual void RawTowerGeomContainer::set_phibins (const int i)
virtual void RawTowerGeomContainer::set_etabins (const int i)
virtual void RawTowerGeomContainer::set_etabounds (const int ibin, const std::pair< double, double > &bounds)
virtual void RawTowerGeomContainer::set_phibounds (const int ibin, const std::pair< double, double > &bounds)
Detailed Description
Note these: concept do not apply to generic calorimeters, like forward calorimeters
Function Documentation
virtual int RawTowerGeomContainer::get_etabin (const double eta) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 129 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), RawClusterBuilderTopo::process_event(), DetermineTowerBackground::process_event(), and PHGenFitTrackProjection::process_event().
virtual int RawTowerGeomContainer::get_etabins () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 100 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplate::Cell2Abs(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), RawClusterDeadAreaMask::process_event(), RawClusterBuilderTemplate::process_event(), RawTowerDeadTowerInterp::process_event(), DetermineTowerBackground::process_event(), PHGenFitTrackProjection::process_event(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), and EMCalCalib::process_event_Tower().
virtual std::pair<double, double> RawTowerGeomContainer::get_etabounds (const int ibin) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 113 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), and DetermineTowerBackground::process_event().
virtual double RawTowerGeomContainer::get_etacenter (const int ibin) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 118 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplate::Cell2Abs(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), HcalRawTowerBuilder::InitRun(), RecoInfoExport::process_event(), G4TowerNtuple::process_event(), TowerTiming::process_event(), DetermineTowerBackground::process_event(), and CaloAna::process_towers().
virtual int RawTowerGeomContainer::get_phibin (const double phi) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 134 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), RawClusterBuilderTopo::process_event(), DetermineTowerBackground::process_event(), and PHGenFitTrackProjection::process_event().
virtual int RawTowerGeomContainer::get_phibins () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 93 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplate::Cell2Abs(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), TrackProjectionTools::getE33Barrel(), Prototype2RawTowerBuilder::InitRun(), HcalRawTowerBuilder::InitRun(), RawClusterBuilderGraph::process_event(), RawClusterDeadAreaMask::process_event(), RawClusterPositionCorrection::process_event(), RawClusterBuilderTemplate::process_event(), RawTowerDeadTowerInterp::process_event(), DetermineTowerBackground::process_event(), PHGenFitTrackProjection::process_event(), QAG4SimulationCalorimeter::process_event_Tower(), EMCalAna::process_event_Tower(), and EMCalCalib::process_event_Tower().
virtual std::pair<double, double> RawTowerGeomContainer::get_phibounds (const int ibin) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 108 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), and DetermineTowerBackground::process_event().
virtual double RawTowerGeomContainer::get_phicenter (const int ibin) const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 123 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawClusterBuilderTemplate::Cell2Abs(), RawClusterBuilderTemplate::CorrectPhi(), RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), EMCalCalib::eval_photon_proj(), EMCalAna::eval_trk_proj(), QAG4SimulationCalorimeterSum::eval_trk_proj(), HcalRawTowerBuilder::InitRun(), RecoInfoExport::process_event(), G4TowerNtuple::process_event(), TowerTiming::process_event(), DetermineTowerBackground::process_event(), and CaloAna::process_towers().
virtual double RawTowerGeomContainer::get_radius () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 83 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerCombiner::CreateNodes(), PHGenFitTrackProjection::InitRun(), PHG4TrackFastSim::InitRun(), and RawClusterBuilderTemplate::process_event().
virtual double RawTowerGeomContainer::get_thickness () const inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 88 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
virtual void RawTowerGeomContainer::set_etabins (const int i) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 145 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_etabounds (const int ibin, const std::pair< double, double > & bounds) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 148 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_phibins (const int i) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 142 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), Prototype2RawTowerBuilder::InitRun(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_phibounds (const int ibin, const std::pair< double, double > & bounds) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 149 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), RawTowerCombiner::CreateNodes(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_radius (const double r) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 140 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), and HcalRawTowerBuilder::InitRun().
virtual void RawTowerGeomContainer::set_thickness (const double t) inline virtual
Reimplemented in RawTowerGeomContainer_Cylinderv1.
Definition at line 141 of file RawTowerGeomContainer.h.
References PHOOL_VIRTUAL_WARN.
Referenced by RawTowerBuilder::CreateNodes(), and HcalRawTowerBuilder::InitRun().