Analysis Software: PdbCalBank Class Reference
PdbCalBank Class Reference abstract
#include <coresoftware/blob/master/offline/database/pdbcal/base/PdbCalBank.h>
Public Member Functions
PdbCalBank ()
virtual ~PdbCalBank ()
virtual PHObject * CloneMe () const =0
Virtual copy constructor.
virtual void printHeader () const =0
virtual void print ()=0
virtual void printEntry (size_t)=0
virtual size_t getLength ()=0
virtual PdbCalChan & getEntry (size_t)=0
virtual void setLength (size_t val)=0
virtual PdbBankID getBankID () const =0
virtual PHTimeStamp getInsertTime () const =0
virtual PHTimeStamp getStartValTime () const =0
virtual PHTimeStamp getEndValTime () const =0
virtual std::string getDescription () const =0
virtual std::string getUserName () const =0
virtual void setBankID (const PdbBankID &)=0
virtual void setInsertTime (const PHTimeStamp &)=0
virtual void setStartValTime (const PHTimeStamp &)=0
virtual void setEndValTime (const PHTimeStamp &)=0
virtual void setDescription (const std::string &)=0
virtual void setUserName (const std::string &)=0
virtual int isValid (const PHTimeStamp &) const =0
ClassDef (PdbCalBank, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Detailed Description
Definition at line 20 of file PdbCalBank.h.
Constructor & Destructor Documentation
PdbCalBank::PdbCalBank () inline
Definition at line 23 of file PdbCalBank.h.
virtual PdbCalBank::~PdbCalBank () inline virtual
Definition at line 24 of file PdbCalBank.h.
Member Function Documentation
PdbCalBank::ClassDef (PdbCalBank , 1)
virtual PHObject* PdbCalBank::CloneMe () const pure virtual
Virtual copy constructor.
Reimplemented from PHObject.
Implemented in PgPostBankWrapper.
Referenced by PgPostBankManager::createBank().
virtual PdbBankID PdbCalBank::getBankID () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual std::string PdbCalBank::getDescription () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual PHTimeStamp PdbCalBank::getEndValTime () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual PdbCalChan& PdbCalBank::getEntry (size_t) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
Referenced by PgPostBankWrapper::getEntry(), and PgPostBankBackupStorage::getEntry().
virtual PHTimeStamp PdbCalBank::getInsertTime () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual size_t PdbCalBank::getLength () pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
Referenced by PgPostBankWrapper::getLength(), PgPostBankBackupStorage::getLength(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
virtual PHTimeStamp PdbCalBank::getStartValTime () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual std::string PdbCalBank::getUserName () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual int PdbCalBank::isValid (const PHTimeStamp &) const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::print () pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
Referenced by PgPostBankWrapper::print(), and PgPostBankBackupStorage::Print().
virtual void PdbCalBank::printEntry (size_t) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
Referenced by PgPostBankWrapper::printEntry().
virtual void PdbCalBank::printHeader () const pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::setBankID (const PdbBankID &) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::setDescription (const std::string &) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::setEndValTime (const PHTimeStamp &) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::setInsertTime (const PHTimeStamp &) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::setLength (size_t val) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
Referenced by PgPostBankWrapper::setLength(), PHParametersContainer::WriteToDB(), and PHParameters::WriteToDB().
virtual void PdbCalBank::setStartValTime (const PHTimeStamp &) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
virtual void PdbCalBank::setUserName (const std::string &) pure virtual
Implemented in PgPostBankWrapper, and PgPostCalBank.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/database/pdbcal/base/PdbCalBank.h