Analysis Software: RawClusterContainer Class Reference
RawClusterContainer Class Reference
#include <coresoftware/blob/master/offline/packages/CaloBase/RawClusterContainer.h>
Public Types
typedef std::map
< RawClusterDefs::keytype,
RawCluster * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
RawClusterContainer ()
virtual ~RawClusterContainer ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
ConstIterator AddCluster (RawCluster *clus)
RawCluster * getCluster (const RawClusterDefs::keytype id)
const RawCluster * getCluster (const RawClusterDefs::keytype id) const
ConstRange getClusters (void) const
return all clusters
Range getClusters (void)
const Map & getClustersMap () const
Map & getClustersMap ()
unsigned int size () const
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map _clusters
Detailed Description
Definition at line 14 of file RawClusterContainer.h.
Member Typedef Documentation
typedef Map::const_iterator RawClusterContainer::ConstIterator
Definition at line 19 of file RawClusterContainer.h.
typedef std::pair<ConstIterator, ConstIterator> RawClusterContainer::ConstRange
Definition at line 21 of file RawClusterContainer.h.
typedef Map::iterator RawClusterContainer::Iterator
Definition at line 18 of file RawClusterContainer.h.
typedef std::map<RawClusterDefs::keytype, RawCluster *> RawClusterContainer::Map
Definition at line 17 of file RawClusterContainer.h.
typedef std::pair<Iterator, Iterator> RawClusterContainer::Range
Definition at line 20 of file RawClusterContainer.h.
Constructor & Destructor Documentation
RawClusterContainer::RawClusterContainer () inline
Definition at line 23 of file RawClusterContainer.h.
virtual RawClusterContainer::~RawClusterContainer () inline virtual
Definition at line 24 of file RawClusterContainer.h.
Member Function Documentation
RawClusterContainer::ConstIterator RawClusterContainer::AddCluster (RawCluster * clus)
Definition at line 23 of file RawClusterContainer.cc.
References RawCluster::set_id().
Referenced by TreeMaker::CopyAndMakeClusters(), VtxTest::numUnique(), RawClusterBuilderGraph::process_event(), RawClusterPositionCorrection::process_event(), RawClusterBuilderTemplateEEMC::process_event(), RawClusterBuilderTemplateFEMC::process_event(), RawClusterBuilderFwd::process_event(), RawClusterBuilderTemplate::process_event(), and RawClusterBuilderTopo::process_event().
RawCluster * RawClusterContainer::getCluster (const RawClusterDefs::keytype id)
Definition at line 39 of file RawClusterContainer.cc.
References it.
Referenced by ExclusiveReco::AddInvariantMassInformation(), JetRecoEval::all_truth_hits(), JetRecoEval::all_truth_particles(), JetRecoEval::all_truth_showers(), DISKinematicsReco::CollectEmCandidatesFromCluster(), JetRecoEval::get_energy_contribution(), TrackProjectionTools::getCluster(), PJTranslator::process_event(), RecoConversionEval::process_event(), VtxTest::processBackground(), TruthConversionEval::processTrackBackground(), TruthConversionEval::recordConversion(), and PHFlowJetMaker::run_particle_flow().
const RawCluster * RawClusterContainer::getCluster (const RawClusterDefs::keytype id) const
Definition at line 50 of file RawClusterContainer.cc.
References it.
RawClusterContainer::ConstRange RawClusterContainer::getClusters (void) const
return all clusters
Definition at line 11 of file RawClusterContainer.cc.
Referenced by CaloRawClusterEval::all_clusters_from(), PhotonJet::ConeSum(), TreeMaker::CopyAndMakeClusters(), ClusterJetInput::get_input(), STACalorimeterCharacterization::get_ordered_clusters(), TreeMaker::GetClusters(), AnaTutorial::getEMCalClusters(), CaloAna::process_clusters(), RawClusterDeadAreaMask::process_event(), RawClusterPositionCorrection::process_event(), RawClusterBuilderTopo::process_event(), ClusterIso::process_event(), Photons::process_event(), DumpRawClusterContainer::process_Node(), and TreeMaker::UseFastJet().
RawClusterContainer::Range RawClusterContainer::getClusters (void)
Definition at line 17 of file RawClusterContainer.cc.
const Map& RawClusterContainer::getClustersMap () const inline
Definition at line 37 of file RawClusterContainer.h.
References _clusters.
Referenced by CaloEvaluator::fillOutputNtuples(), RawClusterBuilderGraph::process_event(), RawClusterDeadAreaMask::process_event(), RawClusterBuilderFwd::process_event(), and PHGenFitTrackProjection::process_event().
Map& RawClusterContainer::getClustersMap () inline
Definition at line 38 of file RawClusterContainer.h.
References _clusters.
double RawClusterContainer::getTotalEdep () const
Definition at line 80 of file RawClusterContainer.cc.
Referenced by RawClusterBuilderGraph::process_event(), RawClusterBuilderFwd::process_event(), and RawClusterBuilderTemplate::process_event().
void RawClusterContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 74 of file RawClusterContainer.cc.
int RawClusterContainer::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 60 of file RawClusterContainer.cc.
void RawClusterContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 65 of file RawClusterContainer.cc.
Referenced by TruthConversionEval::process_event().
unsigned int RawClusterContainer::size (void) const inline
Definition at line 40 of file RawClusterContainer.h.
References _clusters.
Referenced by ExclusiveReco::AddInvariantMassInformation(), DISKinematicsReco::CollectEmCandidatesFromCluster(), TreeMaker::CopyAndMakeClusters(), TrackProjectionTools::getCluster(), RawClusterDeadAreaMask::process_event(), ClusterIso::process_event(), PJTranslator::process_event(), QAG4SimulationCalorimeter::process_event_Cluster(), DumpRawClusterContainer::process_Node(), and PHFlowJetMaker::run_particle_flow().
Member Data Documentation
Map RawClusterContainer::_clusters protected
Definition at line 44 of file RawClusterContainer.h.
Referenced by getClustersMap(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/CaloBase/RawClusterContainer.h
coresoftware/blob/master/offline/packages/CaloBase/RawClusterContainer.cc