Analysis Software: EventHeaderv1 Class Reference
EventHeaderv1 Class Reference
simple event header with ID and time
#include <coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv1.h>
Public Member Functions
EventHeaderv1 ()
ctor
virtual ~EventHeaderv1 ()
dtor
PHObject * CloneMe () const
Virtual copy constructor.
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
int isValid () const
isValid returns non zero if object contains valid data
int get_RunNumber () const
get Run Number
void set_RunNumber (const int run)
set Run Number
int get_EvtSequence () const
get Event Number
void set_EvtSequence (const int evtno)
set Event Number
int get_EvtType () const
get Event Type (Data,rejected,EOR,BOR,...)
void set_EvtType (const int ival)
set Event Type (Data,rejected,EOR,BOR,...)
time_t get_TimeStamp () const
get ATP TimeStamp (unix time, convert with ctime() to date string
void set_TimeStamp (const time_t evttime)
set ATP TimeStamp
Public Member Functions inherited from EventHeader
virtual ~EventHeader ()
dtor
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int RunNumber
int EvtSequence
int EvtType
time_t TimeStamp
Detailed Description
simple event header with ID and time
Definition at line 14 of file EventHeaderv1.h.
Constructor & Destructor Documentation
EventHeaderv1::EventHeaderv1 ()
ctor
Definition at line 7 of file EventHeaderv1.cc.
Referenced by CloneMe().
virtual EventHeaderv1::~EventHeaderv1 () inline virtual
dtor
Definition at line 21 of file EventHeaderv1.h.
Member Function Documentation
PHObject* EventHeaderv1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from PHObject.
Definition at line 23 of file EventHeaderv1.h.
References EventHeaderv1().
int EventHeaderv1::get_EvtSequence () const inline virtual
get Event Number
Reimplemented from EventHeader.
Definition at line 42 of file EventHeaderv1.h.
References EvtSequence.
int EventHeaderv1::get_EvtType () const inline virtual
get Event Type (Data,rejected,EOR,BOR,...)
Reimplemented from EventHeader.
Definition at line 47 of file EventHeaderv1.h.
References EvtType.
int EventHeaderv1::get_RunNumber () const inline virtual
get Run Number
Reimplemented from EventHeader.
Definition at line 37 of file EventHeaderv1.h.
References RunNumber.
time_t EventHeaderv1::get_TimeStamp () const inline virtual
get ATP TimeStamp (unix time, convert with ctime() to date string
Reimplemented from EventHeader.
Definition at line 52 of file EventHeaderv1.h.
References TimeStamp.
void EventHeaderv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from EventHeader.
Definition at line 22 of file EventHeaderv1.cc.
Referenced by RunInfoUnpackPRDF::process_event().
int EventHeaderv1::isValid () const virtual
isValid returns non zero if object contains valid data
Reimplemented from EventHeader.
Definition at line 34 of file EventHeaderv1.cc.
void EventHeaderv1::Reset () virtual
Clear Event.
Reimplemented from EventHeader.
Definition at line 13 of file EventHeaderv1.cc.
void EventHeaderv1::set_EvtSequence (const int evtno) inline virtual
set Event Number
Reimplemented from EventHeader.
Definition at line 44 of file EventHeaderv1.h.
References EvtSequence.
Referenced by RunInfoUnpackPRDF::process_event().
void EventHeaderv1::set_EvtType (const int ival) inline virtual
set Event Type (Data,rejected,EOR,BOR,...)
Reimplemented from EventHeader.
Definition at line 49 of file EventHeaderv1.h.
References EvtType.
Referenced by RunInfoUnpackPRDF::process_event().
void EventHeaderv1::set_RunNumber (const int run) inline virtual
set Run Number
Reimplemented from EventHeader.
Definition at line 39 of file EventHeaderv1.h.
References RunNumber.
Referenced by RunInfoUnpackPRDF::process_event().
void EventHeaderv1::set_TimeStamp (const time_t evttime) inline virtual
set ATP TimeStamp
Reimplemented from EventHeader.
Definition at line 54 of file EventHeaderv1.h.
References TimeStamp.
Referenced by RunInfoUnpackPRDF::process_event().
Member Data Documentation
int EventHeaderv1::EvtSequence protected
Definition at line 59 of file EventHeaderv1.h.
Referenced by get_EvtSequence(), and set_EvtSequence().
int EventHeaderv1::EvtType protected
Definition at line 60 of file EventHeaderv1.h.
Referenced by get_EvtType(), and set_EvtType().
int EventHeaderv1::RunNumber protected
Definition at line 58 of file EventHeaderv1.h.
Referenced by get_RunNumber(), and set_RunNumber().
time_t EventHeaderv1::TimeStamp protected
Definition at line 61 of file EventHeaderv1.h.
Referenced by get_TimeStamp(), and set_TimeStamp().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv1.h
coresoftware/blob/master/offline/framework/ffaobjects/EventHeaderv1.cc