Analysis Software: Prototype2DSTReader Class Reference
Prototype2DSTReader Class Reference
Prototype2DSTReader save information from DST to an evaluator, which could include hit. particle, vertex, towers and jet (to be activated)
#include <prototype/blob/master/offline/packages/Prototype2/Prototype2DSTReader.h>
Classes
struct record
Public Member Functions
Prototype2DSTReader (const std::string &filename)
virtual ~Prototype2DSTReader ()
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
void AddTower (const std::string &name)
void AddTowerTemperature (const std::string &name)
void AddRunInfo (const std::string &name)
double get_tower_zero_sup ()
zero suppression for all calorimeters
void set_tower_zero_sup (double b)
zero suppression for all calorimeters
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Types
typedef std::shared_ptr
< TClonesArray > arr_ptr
typedef std::vector< record > records_t
typedef RawTower_Prototype2 RawTower_type
typedef RawTower_Temperature RawTowerT_type
Protected Member Functions
void build_tree ()
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::vector< std::string > _tower_postfix
std::vector< std::string > _towertemp_postfix
tower temperature
std::vector< std::string > _runinfo_list
int nblocks
records_t _records
int _event
std::string _out_file_name
TTree * _T
double _tower_zero_sup
zero suppression for all calorimeters
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Prototype2DSTReader save information from DST to an evaluator, which could include hit. particle, vertex, towers and jet (to be activated)
Definition at line 31 of file Prototype2DSTReader.h.
Member Typedef Documentation
typedef std::shared_ptr<TClonesArray> Prototype2DSTReader::arr_ptr protected
Definition at line 71 of file Prototype2DSTReader.h.
typedef RawTower_Prototype2 Prototype2DSTReader::RawTower_type protected
Definition at line 96 of file Prototype2DSTReader.h.
typedef RawTower_Temperature Prototype2DSTReader::RawTowerT_type protected
Definition at line 98 of file Prototype2DSTReader.h.
typedef std::vector<record> Prototype2DSTReader::records_t protected
Definition at line 93 of file Prototype2DSTReader.h.
Constructor & Destructor Documentation
Prototype2DSTReader::Prototype2DSTReader (const std::string & filename)
Definition at line 41 of file Prototype2DSTReader.cc.
Prototype2DSTReader::~Prototype2DSTReader () virtual
Definition at line 53 of file Prototype2DSTReader.cc.
References _records, and _T.
Member Function Documentation
void Prototype2DSTReader::AddRunInfo (const std::string & name) inline
Definition at line 53 of file Prototype2DSTReader.h.
References _runinfo_list.
Referenced by Fun4All_TestBeam().
void Prototype2DSTReader::AddTower (const std::string & name) inline
Definition at line 46 of file Prototype2DSTReader.h.
References _tower_postfix.
Referenced by Fun4All_TestBeam().
void Prototype2DSTReader::AddTowerTemperature (const std::string & name) inline
Definition at line 48 of file Prototype2DSTReader.h.
References _towertemp_postfix.
Referenced by Fun4All_TestBeam().
void Prototype2DSTReader::build_tree () protected
Definition at line 148 of file Prototype2DSTReader.cc.
References Prototype2DSTReader::record::_arr_ptr, Prototype2DSTReader::record::_cnt, Prototype2DSTReader::record::_dvalue, Prototype2DSTReader::record::_name, _out_file_name, _records, _T, Prototype2DSTReader::record::_type, BUFFER_SIZE, PHTFileServer::get(), it, nblocks, PHTFileServer::open(), Prototype2DSTReader::record::typ_runinfo, Prototype2DSTReader::record::typ_tower, and Prototype2DSTReader::record::typ_towertemp.
Referenced by Init().
int Prototype2DSTReader::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 371 of file Prototype2DSTReader.cc.
References _out_file_name, _records, _T, PHTFileServer::cd(), and PHTFileServer::get().
double Prototype2DSTReader::get_tower_zero_sup () inline
zero suppression for all calorimeters
Definition at line 56 of file Prototype2DSTReader.h.
References _tower_zero_sup.
int Prototype2DSTReader::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 65 of file Prototype2DSTReader.cc.
References Prototype2DSTReader::record::_arr, Prototype2DSTReader::record::_arr_ptr, Prototype2DSTReader::record::_cnt, Prototype2DSTReader::record::_dvalue, Prototype2DSTReader::record::_name, _records, _runinfo_list, _tower_postfix, _tower_zero_sup, _towertemp_postfix, Prototype2DSTReader::record::_type, build_tree(), it, nblocks, Prototype2DSTReader::record::typ_runinfo, Prototype2DSTReader::record::typ_tower, and Prototype2DSTReader::record::typ_towertemp.
int Prototype2DSTReader::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 199 of file Prototype2DSTReader.cc.
References Prototype2DSTReader::record::_arr, Prototype2DSTReader::record::_arr_ptr, Prototype2DSTReader::record::_cnt, Prototype2DSTReader::record::_dvalue, _event, Prototype2DSTReader::record::_name, _records, _T, _tower_zero_sup, Prototype2DSTReader::record::_type, assert, PHParameters::FillFrom(), PHParameters::get_double_param(), RawTower_Prototype2::get_energy(), RawTower_Temperature::get_nr_entries(), RawTower_Temperature::get_temperature_from_entry(), RawTowerContainer::getTowers(), it, RawTowerContainer::size(), Prototype2DSTReader::record::typ_hit, Prototype2DSTReader::record::typ_part, Prototype2DSTReader::record::typ_runinfo, Prototype2DSTReader::record::typ_tower, Prototype2DSTReader::record::typ_towertemp, Prototype2DSTReader::record::typ_vertex, and Fun4AllBase::Verbosity().
void Prototype2DSTReader::set_tower_zero_sup (double b) inline
zero suppression for all calorimeters
Definition at line 59 of file Prototype2DSTReader.h.
References _tower_zero_sup.
Member Data Documentation
int Prototype2DSTReader::_event protected
Definition at line 101 of file Prototype2DSTReader.h.
Referenced by process_event().
std::string Prototype2DSTReader::_out_file_name protected
Definition at line 103 of file Prototype2DSTReader.h.
Referenced by build_tree(), and End().
records_t Prototype2DSTReader::_records protected
Definition at line 94 of file Prototype2DSTReader.h.
Referenced by build_tree(), End(), Init(), process_event(), and ~Prototype2DSTReader().
std::vector<std::string> Prototype2DSTReader::_runinfo_list protected
Definition at line 65 of file Prototype2DSTReader.h.
Referenced by AddRunInfo(), and Init().
TTree* Prototype2DSTReader::_T protected
Definition at line 106 of file Prototype2DSTReader.h.
Referenced by build_tree(), End(), process_event(), and ~Prototype2DSTReader().
std::vector<std::string> Prototype2DSTReader::_tower_postfix protected
Definition at line 62 of file Prototype2DSTReader.h.
Referenced by AddTower(), and Init().
double Prototype2DSTReader::_tower_zero_sup protected
zero suppression for all calorimeters
Definition at line 109 of file Prototype2DSTReader.h.
Referenced by get_tower_zero_sup(), Init(), process_event(), and set_tower_zero_sup().
std::vector<std::string> Prototype2DSTReader::_towertemp_postfix protected
tower temperature
Definition at line 64 of file Prototype2DSTReader.h.
Referenced by AddTowerTemperature(), and Init().
int Prototype2DSTReader::nblocks protected
Definition at line 67 of file Prototype2DSTReader.h.
Referenced by build_tree(), and Init().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype2/Prototype2DSTReader.h
prototype/blob/master/offline/packages/Prototype2/Prototype2DSTReader.cc