Analysis Software: analysis/blob/master/EICAnalysis/macros/scattered-electron_analysis/prob_EMC_e_pi_plotMacro.C File Reference
prob_EMC_e_pi_plotMacro.C File Reference
#include <iostream>
#include <cstdlib>
#include "TFile.h"
#include "TTree.h"
#include "TCanvas.h"
Functions
TTree * loadTree (TString FILE_NAME="", TString TREE_NAME="", const TString DIR_PATH="/sphenix/user/gregtom3/data/Summer2018/ECAL_probability_studies/")
TH1F * fillHist (TH1F *THE_HIST, TTree *THE_TREE)
void histToPNG (TH1F *h_p, TH1F *h_e, char *title, char *saveFileName)
void prob_EMC_e_pi_plotMacro (const TString DIR_PATH="/sphenix/user/gregtom3/data/Summer2018/ECAL_probability_studies/")
Function Documentation
TH1F* fillHist (TH1F * THE_HIST, TTree * THE_TREE)
Definition at line 19 of file prob_EMC_e_pi_plotMacro.C.
References i.
void histToPNG (TH1F * h_p, TH1F * h_e, char * title, char * saveFileName)
Definition at line 49 of file prob_EMC_e_pi_plotMacro.C.
Referenced by prob_EMC_e_pi_plotMacro().
TTree* loadTree (TString FILE_NAME = "", TString TREE_NAME = "", const TString DIR_PATH = "/sphenix/user/gregtom3/data/Summer2018/ECAL_probability_studies/")
Definition at line 8 of file prob_EMC_e_pi_plotMacro.C.
References t.
Referenced by prob_EMC_e_pi_plotMacro().
void prob_EMC_e_pi_plotMacro (const TString DIR_PATH = "/sphenix/user/gregtom3/data/Summer2018/ECAL_probability_studies/")
Definition at line 77 of file prob_EMC_e_pi_plotMacro.C.
References fillHist(), histToPNG(), loadTree(), and SetsPhenixStyle().