Analysis Software: Prototype3DSTReader Class Reference
Prototype3DSTReader Class Reference
Prototype3DSTReader save information from DST to an evaluator, which could include hit. particle, vertex, towers and jet (to be activated)
#include <prototype/blob/master/offline/packages/Prototype3/Prototype3DSTReader.h>
Classes
struct record
Public Member Functions
Prototype3DSTReader (const std::string &filename)
virtual ~Prototype3DSTReader ()
int Init (PHCompositeNode *)
full initialization
int process_event (PHCompositeNode *)
event processing method
int End (PHCompositeNode *)
end of run method
void AddTower (const std::string &name)
void AddTowerTemperature (const std::string &name)
void AddRunInfo (const std::string &name)
void AddEventInfo (const std::string &name)
double get_tower_zero_sup ()
zero suppression for all calorimeters
void set_tower_zero_sup (double b)
zero suppression for all calorimeters
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Types
typedef std::shared_ptr
< TClonesArray > arr_ptr
typedef std::vector< record > records_t
typedef RawTower_Prototype3 RawTower_type
typedef RawTower_Temperature RawTowerT_type
Protected Member Functions
void build_tree ()
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
std::vector< std::string > _tower_postfix
std::vector< std::string > _towertemp_postfix
tower temperature
std::vector< std::string > _runinfo_list
std::vector< std::string > _eventinfo_list
int nblocks
records_t _records
int _event
std::string _out_file_name
TTree * _T
double _tower_zero_sup
zero suppression for all calorimeters
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Prototype3DSTReader save information from DST to an evaluator, which could include hit. particle, vertex, towers and jet (to be activated)
Definition at line 33 of file Prototype3DSTReader.h.
Member Typedef Documentation
typedef std::shared_ptr<TClonesArray> Prototype3DSTReader::arr_ptr protected
Definition at line 81 of file Prototype3DSTReader.h.
typedef RawTower_Prototype3 Prototype3DSTReader::RawTower_type protected
Definition at line 107 of file Prototype3DSTReader.h.
typedef RawTower_Temperature Prototype3DSTReader::RawTowerT_type protected
Definition at line 109 of file Prototype3DSTReader.h.
typedef std::vector<record> Prototype3DSTReader::records_t protected
Definition at line 104 of file Prototype3DSTReader.h.
Constructor & Destructor Documentation
Prototype3DSTReader::Prototype3DSTReader (const std::string & filename)
Definition at line 40 of file Prototype3DSTReader.cc.
Prototype3DSTReader::~Prototype3DSTReader () virtual
Definition at line 52 of file Prototype3DSTReader.cc.
References _records, and _T.
Member Function Documentation
void Prototype3DSTReader::AddEventInfo (const std::string & name) inline
Definition at line 56 of file Prototype3DSTReader.h.
References _eventinfo_list.
Referenced by Fun4All_TestBeam().
void Prototype3DSTReader::AddRunInfo (const std::string & name) inline
Definition at line 55 of file Prototype3DSTReader.h.
References _runinfo_list.
Referenced by Fun4All_TestBeam().
void Prototype3DSTReader::AddTower (const std::string & name) inline
Definition at line 48 of file Prototype3DSTReader.h.
References _tower_postfix.
Referenced by Fun4All_TestBeam().
void Prototype3DSTReader::AddTowerTemperature (const std::string & name) inline
Definition at line 50 of file Prototype3DSTReader.h.
References _towertemp_postfix.
void Prototype3DSTReader::build_tree () protected
Definition at line 164 of file Prototype3DSTReader.cc.
References Prototype3DSTReader::record::_arr_ptr, Prototype3DSTReader::record::_cnt, Prototype3DSTReader::record::_dvalue, Prototype3DSTReader::record::_name, _out_file_name, _records, _T, Prototype3DSTReader::record::_type, BUFFER_SIZE, PHTFileServer::get(), it, nblocks, PHTFileServer::open(), Prototype3DSTReader::record::typ_eventinfo, Prototype3DSTReader::record::typ_runinfo, Prototype3DSTReader::record::typ_tower, and Prototype3DSTReader::record::typ_towertemp.
Referenced by Init().
int Prototype3DSTReader::End (PHCompositeNode *) virtual
end of run method
Reimplemented from SubsysReco.
Definition at line 407 of file Prototype3DSTReader.cc.
References _out_file_name, _records, _T, PHTFileServer::cd(), and PHTFileServer::get().
double Prototype3DSTReader::get_tower_zero_sup () inline
zero suppression for all calorimeters
Definition at line 62 of file Prototype3DSTReader.h.
References _tower_zero_sup.
int Prototype3DSTReader::Init (PHCompositeNode *) virtual
full initialization
Reimplemented from SubsysReco.
Definition at line 64 of file Prototype3DSTReader.cc.
References Prototype3DSTReader::record::_arr, Prototype3DSTReader::record::_arr_ptr, Prototype3DSTReader::record::_cnt, Prototype3DSTReader::record::_dvalue, _eventinfo_list, Prototype3DSTReader::record::_name, _records, _runinfo_list, _tower_postfix, _tower_zero_sup, _towertemp_postfix, Prototype3DSTReader::record::_type, build_tree(), it, nblocks, Prototype3DSTReader::record::typ_eventinfo, Prototype3DSTReader::record::typ_runinfo, Prototype3DSTReader::record::typ_tower, and Prototype3DSTReader::record::typ_towertemp.
int Prototype3DSTReader::process_event (PHCompositeNode * topNode) virtual
event processing method
Reimplemented from SubsysReco.
Definition at line 222 of file Prototype3DSTReader.cc.
References Prototype3DSTReader::record::_arr, Prototype3DSTReader::record::_arr_ptr, Prototype3DSTReader::record::_cnt, Prototype3DSTReader::record::_dvalue, _event, Prototype3DSTReader::record::_name, _records, _T, _tower_zero_sup, Prototype3DSTReader::record::_type, assert, PHParameters::FillFrom(), PHParameters::get_double_param(), RawTower_Prototype3::get_energy(), RawTower_Temperature::get_nr_entries(), RawTower_Temperature::get_temperature_from_entry(), RawTowerContainer::getTowers(), it, RawTowerContainer::size(), Prototype3DSTReader::record::typ_eventinfo, Prototype3DSTReader::record::typ_hit, Prototype3DSTReader::record::typ_part, Prototype3DSTReader::record::typ_runinfo, Prototype3DSTReader::record::typ_tower, Prototype3DSTReader::record::typ_towertemp, Prototype3DSTReader::record::typ_vertex, and Fun4AllBase::Verbosity().
void Prototype3DSTReader::set_tower_zero_sup (double b) inline
zero suppression for all calorimeters
Definition at line 65 of file Prototype3DSTReader.h.
References _tower_zero_sup.
Member Data Documentation
int Prototype3DSTReader::_event protected
Definition at line 112 of file Prototype3DSTReader.h.
Referenced by process_event().
std::vector<std::string> Prototype3DSTReader::_eventinfo_list protected
Definition at line 75 of file Prototype3DSTReader.h.
Referenced by AddEventInfo(), and Init().
std::string Prototype3DSTReader::_out_file_name protected
Definition at line 114 of file Prototype3DSTReader.h.
Referenced by build_tree(), and End().
records_t Prototype3DSTReader::_records protected
Definition at line 105 of file Prototype3DSTReader.h.
Referenced by build_tree(), End(), Init(), process_event(), and ~Prototype3DSTReader().
std::vector<std::string> Prototype3DSTReader::_runinfo_list protected
Definition at line 74 of file Prototype3DSTReader.h.
Referenced by AddRunInfo(), and Init().
TTree* Prototype3DSTReader::_T protected
Definition at line 117 of file Prototype3DSTReader.h.
Referenced by build_tree(), End(), process_event(), and ~Prototype3DSTReader().
std::vector<std::string> Prototype3DSTReader::_tower_postfix protected
Definition at line 69 of file Prototype3DSTReader.h.
Referenced by AddTower(), and Init().
double Prototype3DSTReader::_tower_zero_sup protected
zero suppression for all calorimeters
Definition at line 120 of file Prototype3DSTReader.h.
Referenced by get_tower_zero_sup(), Init(), process_event(), and set_tower_zero_sup().
std::vector<std::string> Prototype3DSTReader::_towertemp_postfix protected
tower temperature
Definition at line 71 of file Prototype3DSTReader.h.
Referenced by AddTowerTemperature(), and Init().
int Prototype3DSTReader::nblocks protected
Definition at line 77 of file Prototype3DSTReader.h.
Referenced by build_tree(), and Init().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/Prototype3/Prototype3DSTReader.h
prototype/blob/master/offline/packages/Prototype3/Prototype3DSTReader.cc