Analysis Software: PHG4Hitv1 Class Reference
PHG4Hitv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hitv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
PHG4Hitv1 ()
PHG4Hitv1 (const PHG4Hit *g4hit)
virtual ~PHG4Hitv1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
float get_x (const int i) const
float get_y (const int i) const
float get_z (const int i) const
float get_t (const int i) const
float get_edep () const
PHG4HitDefs::keytype get_hit_id () const
int get_detid () const
int get_shower_id () const
int get_trkid () const
void set_x (const int i, const float f)
void set_y (const int i, const float f)
void set_z (const int i, const float f)
void set_t (const int i, const float f)
void set_edep (const float f)
void set_hit_id (const PHG4HitDefs::keytype i)
void set_shower_id (const int i)
void set_trkid (const int i)
virtual void print () const
bool has_property (const PROPERTY prop_id) const
float get_property_float (const PROPERTY prop_id) const
int get_property_int (const PROPERTY prop_id) const
unsigned int get_property_uint (const PROPERTY prop_id) const
void set_property (const PROPERTY prop_id, const float value)
void set_property (const PROPERTY prop_id, const int value)
void set_property (const PROPERTY prop_id, const unsigned int value)
virtual float get_px (const int i) const
virtual float get_py (const int i) const
virtual float get_pz (const int i) const
virtual float get_local_x (const int i) const
virtual float get_local_y (const int i) const
virtual float get_local_z (const int i) const
virtual float get_eion () const
virtual float get_light_yield () const
virtual float get_path_length () const
virtual unsigned int get_layer () const
virtual int get_scint_id () const
virtual int get_row () const
virtual int get_strip_z_index () const
virtual int get_strip_y_index () const
virtual int get_ladder_z_index () const
virtual int get_ladder_phi_index () const
virtual int get_index_i () const
virtual int get_index_j () const
virtual int get_index_k () const
virtual int get_index_l () const
virtual int get_hit_type () const
virtual void set_px (const int i, const float f)
virtual void set_py (const int i, const float f)
virtual void set_pz (const int i, const float f)
virtual void set_local_x (const int i, const float f)
virtual void set_local_y (const int i, const float f)
virtual void set_local_z (const int i, const float f)
virtual void set_eion (const float f)
virtual void set_light_yield (const float f)
virtual void set_path_length (const float f)
virtual void set_layer (const unsigned int i)
virtual void set_scint_id (const int i)
virtual void set_row (const int i)
virtual void set_strip_z_index (const int i)
virtual void set_strip_y_index (const int i)
virtual void set_ladder_z_index (const int i)
virtual void set_ladder_phi_index (const int i)
virtual void set_index_i (const int i)
virtual void set_index_j (const int i)
virtual void set_index_k (const int i)
virtual void set_index_l (const int i)
virtual void set_hit_type (const int i)
Public Member Functions inherited from PHG4Hit
PHG4Hit ()
virtual ~PHG4Hit ()
virtual void CopyFrom (const PHObject *phobj)
virtual float get_avg_x () const
virtual float get_avg_y () const
virtual float get_avg_z () const
virtual float get_avg_t () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Protected Attributes
float x [2]
float y [2]
float z [2]
float t [2]
PHG4HitDefs::keytype hitid
int trackid
int showerid
float edep
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Hit
enum PROPERTY {
prop_eion = 1, prop_light_yield = 2, prop_px_0 = 10, prop_px_1 = 11,
prop_py_0 = 12, prop_py_1 = 13, prop_pz_0 = 14, prop_pz_1 = 15,
prop_path_length = 16, prop_local_x_0 = 20, prop_local_x_1 = 21, prop_local_y_0 = 22,
prop_local_y_1 = 23, prop_local_z_0 = 24, prop_local_z_1 = 25, prop_layer = 101,
prop_scint_id = 102, prop_row = 103, prop_strip_z_index = 110, prop_strip_y_index = 111,
prop_ladder_z_index = 112, prop_ladder_phi_index = 113, prop_stave_index = 114, prop_half_stave_index = 115,
prop_module_index = 116, prop_chip_index = 117, prop_local_pos_x_0 = 118, prop_local_pos_y_0 = 119,
prop_local_pos_z_0 = 120, prop_index_i = 121, prop_index_j = 122, prop_index_k = 123,
prop_index_l = 124, prop_hit_type = 125, prop_local_pos_x_1 = 128, prop_local_pos_y_1 = 126,
prop_local_pos_z_1 = 127, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Static Public Member Functions inherited from PHG4Hit
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 17 of file PHG4Hitv1.h.
Member Typedef Documentation
typedef uint8_t PHG4Hitv1::prop_id_t protected
storage types for additional property
Definition at line 115 of file PHG4Hitv1.h.
typedef std::map<prop_id_t, prop_storage_t> PHG4Hitv1::prop_map_t protected
Definition at line 117 of file PHG4Hitv1.h.
typedef uint32_t PHG4Hitv1::prop_storage_t protected
Definition at line 116 of file PHG4Hitv1.h.
Constructor & Destructor Documentation
PHG4Hitv1::PHG4Hitv1 ()
Definition at line 14 of file PHG4Hitv1.cc.
References i, set_t(), set_x(), set_y(), and set_z().
PHG4Hitv1::PHG4Hitv1 (const PHG4Hit * g4hit) explicit
Definition at line 29 of file PHG4Hitv1.cc.
References PHG4Hit::CopyFrom().
virtual PHG4Hitv1::~PHG4Hitv1 () inline virtual
Definition at line 22 of file PHG4Hitv1.h.
Member Function Documentation
int PHG4Hitv1::get_detid () const virtual
Reimplemented from PHG4Hit.
Definition at line 51 of file PHG4Hitv1.cc.
References PHG4HitDefs::hit_idbits, and hitid.
float PHG4Hitv1::get_edep () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 31 of file PHG4Hitv1.h.
References edep.
virtual float PHG4Hitv1::get_eion () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 62 of file PHG4Hitv1.h.
References get_property_float(), and PHG4Hit::prop_eion.
PHG4HitDefs::keytype PHG4Hitv1::get_hit_id () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 32 of file PHG4Hitv1.h.
References hitid.
virtual int PHG4Hitv1::get_hit_type () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 76 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_hit_type.
virtual int PHG4Hitv1::get_index_i () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 72 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_i.
virtual int PHG4Hitv1::get_index_j () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 73 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_j.
virtual int PHG4Hitv1::get_index_k () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 74 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_k.
virtual int PHG4Hitv1::get_index_l () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 75 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_index_l.
virtual int PHG4Hitv1::get_ladder_phi_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 71 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_ladder_phi_index.
virtual int PHG4Hitv1::get_ladder_z_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 70 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_ladder_z_index.
virtual unsigned int PHG4Hitv1::get_layer () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 65 of file PHG4Hitv1.h.
References get_property_uint(), and PHG4Hit::prop_layer.
virtual float PHG4Hitv1::get_light_yield () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 63 of file PHG4Hitv1.h.
References get_property_float(), and PHG4Hit::prop_light_yield.
float PHG4Hitv1::get_local_x (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 301 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_local_x_0, and PHG4Hit::prop_local_x_1.
float PHG4Hitv1::get_local_y (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 316 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_local_y_0, and PHG4Hit::prop_local_y_1.
float PHG4Hitv1::get_local_z (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 331 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_local_z_0, and PHG4Hit::prop_local_z_1.
virtual float PHG4Hitv1::get_path_length () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 64 of file PHG4Hitv1.h.
References get_property_float(), and PHG4Hit::prop_path_length.
float PHG4Hitv1::get_property_float (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 97 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hitv1::u_property::fdata, PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), i, PHWHERE, prop_map, and PHG4Hit::type_float.
Referenced by get_eion(), get_light_yield(), get_local_x(), get_local_y(), get_local_z(), get_path_length(), get_px(), get_py(), get_pz(), identify(), and print().
int PHG4Hitv1::get_property_int (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 115 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), i, PHG4Hitv1::u_property::idata, PHWHERE, prop_map, and PHG4Hit::type_int.
Referenced by get_hit_type(), get_index_i(), get_index_j(), get_index_k(), get_index_l(), get_ladder_phi_index(), get_ladder_z_index(), get_row(), get_scint_id(), get_strip_y_index(), get_strip_z_index(), identify(), and print().
unsigned int PHG4Hitv1::get_property_nocheck (const PROPERTY prop_id) const protected virtual
Reimplemented from PHG4Hit.
Definition at line 193 of file PHG4Hitv1.cc.
References prop_map.
unsigned int PHG4Hitv1::get_property_uint (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 133 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), i, PHWHERE, prop_map, PHG4Hit::type_uint, and PHG4Hitv1::u_property::uidata.
Referenced by get_layer(), identify(), and print().
float PHG4Hitv1::get_px (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 204 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_px_0, and PHG4Hit::prop_px_1.
float PHG4Hitv1::get_py (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 219 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_py_0, and PHG4Hit::prop_py_1.
float PHG4Hitv1::get_pz (const int i) const virtual
Reimplemented from PHG4Hit.
Definition at line 234 of file PHG4Hitv1.cc.
References get_property_float(), PHG4Hit::prop_pz_0, and PHG4Hit::prop_pz_1.
virtual int PHG4Hitv1::get_row () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 67 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_row.
virtual int PHG4Hitv1::get_scint_id () const inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 66 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_scint_id.
int PHG4Hitv1::get_shower_id () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 34 of file PHG4Hitv1.h.
References showerid.
virtual int PHG4Hitv1::get_strip_y_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 69 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_strip_y_index.
virtual int PHG4Hitv1::get_strip_z_index () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 68 of file PHG4Hitv1.h.
References get_property_int(), and PHG4Hit::prop_strip_z_index.
float PHG4Hitv1::get_t (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 30 of file PHG4Hitv1.h.
References i, and t.
Referenced by identify().
int PHG4Hitv1::get_trkid () const inline virtual
Reimplemented from PHG4Hit.
Definition at line 35 of file PHG4Hitv1.h.
References trackid.
float PHG4Hitv1::get_x (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 27 of file PHG4Hitv1.h.
References i, and x.
Referenced by identify().
float PHG4Hitv1::get_y (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 28 of file PHG4Hitv1.h.
References i, and y.
Referenced by identify().
float PHG4Hitv1::get_z (const int i) const inline virtual
Reimplemented from PHG4Hit.
Definition at line 29 of file PHG4Hitv1.h.
References i, and z.
Referenced by identify().
bool PHG4Hitv1::has_property (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Hit.
Definition at line 90 of file PHG4Hitv1.cc.
References i, and prop_map.
void PHG4Hitv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Hit.
Definition at line 397 of file PHG4Hitv1.cc.
References edep, get_property_float(), PHG4Hit::get_property_info(), get_property_int(), get_property_uint(), get_t(), get_x(), get_y(), get_z(), hitid, i, prop_map, showerid, trackid, PHG4Hit::type_float, PHG4Hit::type_int, and PHG4Hit::type_uint.
void PHG4Hitv1::print () const virtual
Reimplemented from PHG4Hit.
Definition at line 60 of file PHG4Hitv1.cc.
References edep, get_property_float(), PHG4Hit::get_property_info(), get_property_int(), get_property_uint(), hitid, i, prop_map, t, trackid, PHG4Hit::type_float, PHG4Hit::type_int, PHG4Hit::type_uint, x, y, and z.
void PHG4Hitv1::Reset () virtual
Clear Event.
Reimplemented from PHG4Hit.
Definition at line 35 of file PHG4Hitv1.cc.
References edep, hitid, i, prop_map, set_t(), set_x(), set_y(), set_z(), and trackid.
void PHG4Hitv1::set_edep (const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 41 of file PHG4Hitv1.h.
References edep.
virtual void PHG4Hitv1::set_eion (const float f) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 84 of file PHG4Hitv1.h.
References PHG4Hit::prop_eion, and set_property().
void PHG4Hitv1::set_hit_id (const PHG4HitDefs::keytype i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 42 of file PHG4Hitv1.h.
References hitid, and i.
virtual void PHG4Hitv1::set_hit_type (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 98 of file PHG4Hitv1.h.
References PHG4Hit::prop_hit_type, and set_property().
virtual void PHG4Hitv1::set_index_i (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 94 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_i, and set_property().
virtual void PHG4Hitv1::set_index_j (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 95 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_j, and set_property().
virtual void PHG4Hitv1::set_index_k (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 96 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_k, and set_property().
virtual void PHG4Hitv1::set_index_l (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 97 of file PHG4Hitv1.h.
References PHG4Hit::prop_index_l, and set_property().
virtual void PHG4Hitv1::set_ladder_phi_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 93 of file PHG4Hitv1.h.
References PHG4Hit::prop_ladder_phi_index, and set_property().
virtual void PHG4Hitv1::set_ladder_z_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 92 of file PHG4Hitv1.h.
References PHG4Hit::prop_ladder_z_index, and set_property().
virtual void PHG4Hitv1::set_layer (const unsigned int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 87 of file PHG4Hitv1.h.
References PHG4Hit::prop_layer, and set_property().
virtual void PHG4Hitv1::set_light_yield (const float f) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 85 of file PHG4Hitv1.h.
References PHG4Hit::prop_light_yield, and set_property().
void PHG4Hitv1::set_local_x (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 346 of file PHG4Hitv1.cc.
References PHG4Hit::prop_local_x_0, PHG4Hit::prop_local_x_1, and set_property().
void PHG4Hitv1::set_local_y (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 363 of file PHG4Hitv1.cc.
References PHG4Hit::prop_local_y_0, PHG4Hit::prop_local_y_1, and set_property().
void PHG4Hitv1::set_local_z (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 380 of file PHG4Hitv1.cc.
References PHG4Hit::prop_local_z_0, PHG4Hit::prop_local_z_1, and set_property().
virtual void PHG4Hitv1::set_path_length (const float f) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 86 of file PHG4Hitv1.h.
References PHG4Hit::prop_path_length, and set_property().
void PHG4Hitv1::set_property (const PROPERTY prop_id, const float value) virtual
Reimplemented from PHG4Hit.
Definition at line 151 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Hit::type_float.
Referenced by set_eion(), set_hit_type(), set_index_i(), set_index_j(), set_index_k(), set_index_l(), set_ladder_phi_index(), set_ladder_z_index(), set_layer(), set_light_yield(), set_local_x(), set_local_y(), set_local_z(), set_path_length(), set_px(), set_py(), set_pz(), set_row(), set_scint_id(), set_strip_y_index(), and set_strip_z_index().
void PHG4Hitv1::set_property (const PROPERTY prop_id, const int value) virtual
Reimplemented from PHG4Hit.
Definition at line 165 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Hit::type_int.
void PHG4Hitv1::set_property (const PROPERTY prop_id, const unsigned int value) virtual
Reimplemented from PHG4Hit.
Definition at line 179 of file PHG4Hitv1.cc.
References PHG4Hit::check_property(), PHG4Hit::get_property_info(), PHG4Hit::get_property_type(), PHG4Hitv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Hit::type_uint.
void PHG4Hitv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline protected virtual
Reimplemented from PHG4Hit.
Definition at line 102 of file PHG4Hitv1.h.
References prop_map.
void PHG4Hitv1::set_px (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 249 of file PHG4Hitv1.cc.
References PHG4Hit::prop_px_0, PHG4Hit::prop_px_1, and set_property().
void PHG4Hitv1::set_py (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 266 of file PHG4Hitv1.cc.
References PHG4Hit::prop_py_0, PHG4Hit::prop_py_1, and set_property().
void PHG4Hitv1::set_pz (const int i, const float f) virtual
Reimplemented from PHG4Hit.
Definition at line 283 of file PHG4Hitv1.cc.
References PHG4Hit::prop_pz_0, PHG4Hit::prop_pz_1, and set_property().
virtual void PHG4Hitv1::set_row (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 89 of file PHG4Hitv1.h.
References PHG4Hit::prop_row, and set_property().
virtual void PHG4Hitv1::set_scint_id (const int i) inline virtual
Reimplemented from PHG4Hit.
Reimplemented in PHG4HitEval.
Definition at line 88 of file PHG4Hitv1.h.
References PHG4Hit::prop_scint_id, and set_property().
void PHG4Hitv1::set_shower_id (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 43 of file PHG4Hitv1.h.
References i, and showerid.
virtual void PHG4Hitv1::set_strip_y_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 91 of file PHG4Hitv1.h.
References PHG4Hit::prop_strip_y_index, and set_property().
virtual void PHG4Hitv1::set_strip_z_index (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 90 of file PHG4Hitv1.h.
References PHG4Hit::prop_strip_z_index, and set_property().
void PHG4Hitv1::set_t (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 40 of file PHG4Hitv1.h.
References i, and t.
Referenced by PHG4Hitv1(), and Reset().
void PHG4Hitv1::set_trkid (const int i) inline virtual
Reimplemented from PHG4Hit.
Definition at line 44 of file PHG4Hitv1.h.
References i, and trackid.
void PHG4Hitv1::set_x (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 37 of file PHG4Hitv1.h.
References i, and x.
Referenced by PHG4Hitv1(), and Reset().
void PHG4Hitv1::set_y (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 38 of file PHG4Hitv1.h.
References i, and y.
Referenced by PHG4Hitv1(), and Reset().
void PHG4Hitv1::set_z (const int i, const float f) inline virtual
Reimplemented from PHG4Hit.
Definition at line 39 of file PHG4Hitv1.h.
References i, and z.
Referenced by PHG4Hitv1(), and Reset().
Member Data Documentation
float PHG4Hitv1::edep protected
Definition at line 112 of file PHG4Hitv1.h.
Referenced by get_edep(), identify(), print(), Reset(), and set_edep().
PHG4HitDefs::keytype PHG4Hitv1::hitid protected
Definition at line 109 of file PHG4Hitv1.h.
Referenced by get_detid(), get_hit_id(), identify(), print(), Reset(), and set_hit_id().
prop_map_t PHG4Hitv1::prop_map protected
container for additional property
Definition at line 134 of file PHG4Hitv1.h.
Referenced by get_property_float(), get_property_int(), get_property_nocheck(), get_property_uint(), has_property(), identify(), print(), Reset(), set_property(), and set_property_nocheck().
int PHG4Hitv1::showerid protected
Definition at line 111 of file PHG4Hitv1.h.
Referenced by get_shower_id(), identify(), and set_shower_id().
float PHG4Hitv1::t[2] protected
Definition at line 108 of file PHG4Hitv1.h.
Referenced by get_t(), print(), and set_t().
int PHG4Hitv1::trackid protected
Definition at line 110 of file PHG4Hitv1.h.
Referenced by get_trkid(), identify(), print(), Reset(), and set_trkid().
float PHG4Hitv1::x[2] protected
Definition at line 105 of file PHG4Hitv1.h.
Referenced by get_x(), print(), and set_x().
float PHG4Hitv1::y[2] protected
Definition at line 106 of file PHG4Hitv1.h.
Referenced by get_y(), print(), and set_y().
float PHG4Hitv1::z[2] protected
Definition at line 107 of file PHG4Hitv1.h.
Referenced by get_z(), print(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hitv1.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4Hitv1.cc