Analysis Software: RecursiveMomentumContainer Class Reference
RecursiveMomentumContainer Class Reference
Public Member Functions
RecursiveMomentumContainer (float PX_LO, float PX_HI, float PY_LO, float PY_HI, float PZ_LO, float PZ_HI, int MLEV, int LEV=0)
virtual ~RecursiveMomentumContainer ()
virtual bool insert (TrivialTrack &track)
virtual TrivialTrack * begin ()
virtual TrivialTrack * next ()
virtual void append_list (vector< TrivialTrack * > &track_list, float PX_LO, float PX_HI, float PY_LO, float PY_HI, float PZ_LO, float PZ_HI)
Protected Attributes
float px_lo
float px_hi
float py_lo
float py_hi
float pz_lo
float pz_hi
int level
int maxlevel
unsigned int x_pos
unsigned int y_pos
unsigned int z_pos
RecursiveMomentumContainer * containers [2][2][2]
Detailed Description
Definition at line 46 of file MomentumEvaluator.cc.
Constructor & Destructor Documentation
RecursiveMomentumContainer::RecursiveMomentumContainer (float PX_LO, float PX_HI, float PY_LO, float PY_HI, float PZ_LO, float PZ_HI, int MLEV, int LEV = 0) inline
Definition at line 61 of file MomentumEvaluator.cc.
References i, j, and k.
virtual RecursiveMomentumContainer::~RecursiveMomentumContainer () inline virtual
Definition at line 85 of file MomentumEvaluator.cc.
References i, j, and k.
Member Function Documentation
virtual void RecursiveMomentumContainer::append_list (vector< TrivialTrack * > & track_list, float PX_LO, float PX_HI, float PY_LO, float PY_HI, float PZ_LO, float PZ_HI) inline virtual
Reimplemented in RecursiveMomentumContainerEnd.
Definition at line 235 of file MomentumEvaluator.cc.
References i, j, and k.
Referenced by MomentumEvaluator::process_event().
virtual TrivialTrack* RecursiveMomentumContainer::begin () inline virtual
Reimplemented in RecursiveMomentumContainerEnd.
Definition at line 104 of file MomentumEvaluator.cc.
Referenced by MomentumEvaluator::process_event().
bool RecursiveMomentumContainer::insert (TrivialTrack & track) virtual
Reimplemented in RecursiveMomentumContainerEnd.
Definition at line 313 of file MomentumEvaluator.cc.
References TrivialTrack::px, TrivialTrack::py, and TrivialTrack::pz.
Referenced by MomentumEvaluator::process_event().
virtual TrivialTrack* RecursiveMomentumContainer::next () inline virtual
Reimplemented in RecursiveMomentumContainerEnd.
Definition at line 149 of file MomentumEvaluator.cc.
Referenced by MomentumEvaluator::process_event().
Member Data Documentation
RecursiveMomentumContainer* RecursiveMomentumContainer::containers[2][2][2] protected
Definition at line 58 of file MomentumEvaluator.cc.
int RecursiveMomentumContainer::level protected
Definition at line 53 of file MomentumEvaluator.cc.
int RecursiveMomentumContainer::maxlevel protected
Definition at line 54 of file MomentumEvaluator.cc.
float RecursiveMomentumContainer::px_hi protected
Definition at line 49 of file MomentumEvaluator.cc.
float RecursiveMomentumContainer::px_lo protected
Definition at line 49 of file MomentumEvaluator.cc.
float RecursiveMomentumContainer::py_hi protected
Definition at line 50 of file MomentumEvaluator.cc.
float RecursiveMomentumContainer::py_lo protected
Definition at line 50 of file MomentumEvaluator.cc.
float RecursiveMomentumContainer::pz_hi protected
Definition at line 51 of file MomentumEvaluator.cc.
float RecursiveMomentumContainer::pz_lo protected
Definition at line 51 of file MomentumEvaluator.cc.
unsigned int RecursiveMomentumContainer::x_pos protected
Definition at line 56 of file MomentumEvaluator.cc.
unsigned int RecursiveMomentumContainer::y_pos protected
Definition at line 56 of file MomentumEvaluator.cc.
unsigned int RecursiveMomentumContainer::z_pos protected
Definition at line 56 of file MomentumEvaluator.cc.
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4eval/MomentumEvaluator.cc