Analysis Software: coresoftware/blob/master/offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTracker.cpp File Reference
sPHENIXTracker.cpp File Reference
#include "sPHENIXTracker.h"
#include "CylinderKalman.h"
#include "Pincushion.h"
#include "SimpleTrack3D.h"
#include "vector_math_inline.h"
#include <Eigen/Core>
#include <Eigen/Dense>
#include <Eigen/LU>
#include <algorithm>
#include <cfloat>
#include <cmath>
#include <cstddef>
#include <sys/time.h>
#include <iostream>
#include <utility>
#include <xmmintrin.h>
Classes
class hit_triplet
class hitTriplet
struct TempComb
Functions
static void xyTangent (SimpleHit3D &hit1, SimpleHit3D &hit2, float kappa, float hel, float &ux_out, float &uy_out, float &ux_in, float &uy_in)
static float cosScatter (SimpleHit3D &hit1, SimpleHit3D &hit2, SimpleHit3D &hit3, float kappa, float hel)
static float dzdsSimple (SimpleHit3D &hit1, SimpleHit3D &hit2, float k)
static void triplet_rejection (vector< SimpleTrack3D > &input, vector< float > &chi2s, vector< bool > &usetrack)
static double sign (double x)
Function Documentation
static float cosScatter (SimpleHit3D & hit1, SimpleHit3D & hit2, SimpleHit3D & hit3, float kappa, float hel) static
Definition at line 355 of file sPHENIXTracker.cpp.
References temp1, temp2, and xyTangent().
static float dzdsSimple (SimpleHit3D & hit1, SimpleHit3D & hit2, float k) static
Definition at line 371 of file sPHENIXTracker.cpp.
References SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), s, temp1, temp2, x, and y.
static double sign (double x) inline static
Definition at line 1751 of file sPHENIXTracker.cpp.
References double().
Referenced by sPHENIXTracker::projectToLayer().
static void triplet_rejection (vector< SimpleTrack3D > & input, vector< float > & chi2s, vector< bool > & usetrack) static
Definition at line 1183 of file sPHENIXTracker.cpp.
References h1, h2, i, and pos.
static void xyTangent (SimpleHit3D & hit1, SimpleHit3D & hit2, float kappa, float hel, float & ux_out, float & uy_out, float & ux_in, float & uy_in) static
Definition at line 329 of file sPHENIXTracker.cpp.
References SimpleHit3D::get_x(), SimpleHit3D::get_y(), norm, x, and y.
Referenced by cosScatter().