Analysis Software: HijCrdn Class Reference
HijCrdn Class Reference
Class definition for HijCrdn, which is used to modify the Hijing HIJCRDN common.
#include <coresoftware/blob/master/generators/sHijing/HijCrdn.h>
Classes
struct HIJCRDN
Public Member Functions
HijCrdn ()
~HijCrdn ()
float & yp (int i, int j)
float & yt (int i, int j)
void init (void)
int lenI () const
int lenJ () const
Private Attributes
float _realdummy
Static Private Attributes
static const int _lenI = 3
static const int _lenJ = 300
static HIJCRDN * _hijcrdn =0
Friends
struct HIJCRDN
Detailed Description
Class definition for HijCrdn, which is used to modify the Hijing HIJCRDN common.
Definition at line 11 of file HijCrdn.h.
Constructor & Destructor Documentation
HijCrdn::HijCrdn () inline
Definition at line 55 of file HijCrdn.h.
HijCrdn::~HijCrdn () inline
Definition at line 62 of file HijCrdn.h.
Member Function Documentation
void HijCrdn::init (void) inline
Definition at line 50 of file HijCrdn.h.
References _hijcrdn, and hijcrdn_address_().
Referenced by yp(), and yt().
int HijCrdn::lenI () const inline
Definition at line 22 of file HijCrdn.h.
References _lenI.
Referenced by yp(), and yt().
int HijCrdn::lenJ () const inline
Definition at line 23 of file HijCrdn.h.
References _lenJ.
Referenced by yp(), and yt().
float & HijCrdn::yp (int i, int j) inline
Definition at line 66 of file HijCrdn.h.
References _hijcrdn, _realdummy, init(), lenI(), lenJ(), and HijCrdn::HIJCRDN::yp.
Referenced by fillEvent(), hijcsc(), hijhrd(), hijing(), hijset(), hijsft(), jetini(), pyhistfu(), and quench().
float & HijCrdn::yt (int i, int j) inline
Definition at line 76 of file HijCrdn.h.
References _hijcrdn, _realdummy, init(), lenI(), lenJ(), and HijCrdn::HIJCRDN::yt.
Referenced by fillEvent(), hijcsc(), hijhrd(), hijing(), hijset(), hijsft(), jetini(), pyhistfu(), and quench().
Friends And Related Function Documentation
friend struct HIJCRDN friend
Definition at line 31 of file HijCrdn.h.
Member Data Documentation
HijCrdn::HIJCRDN * HijCrdn::_hijcrdn =0 static private
Definition at line 43 of file HijCrdn.h.
Referenced by init(), yp(), and yt().
const int HijCrdn::_lenI = 3 static private
Definition at line 28 of file HijCrdn.h.
Referenced by lenI().
const int HijCrdn::_lenJ = 300 static private
Definition at line 29 of file HijCrdn.h.
Referenced by lenJ().
float HijCrdn::_realdummy private
Definition at line 41 of file HijCrdn.h.
Referenced by yp(), and yt().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HijCrdn.h