Analysis Software: PROTOTYPE4_FEM Namespace Reference
PROTOTYPE4_FEM Namespace Reference
Functions
int GetChannelNumber (const std::string &caloname, int i_column, int i_row)
FEM mapping of channel -> calorimeter col and rows.
bool SampleFit_PowerLawExp (const std::vector< double > &samples, double &peak, double &peak_sample, double &pedstal, const int verbosity=0)
Abhisek's power-law + exp fit.
bool SampleFit_PowerLawDoubleExp (const std::vector< double > &samples, double &peak, double &peak_sample, double &pedestal, std::map< int, double > &parameters_io, const int verbosity=0)
Power law double exp fit.
bool SampleFit_PeakSample (const std::vector< double > &samples, double &peak, double &peak_sample, double &pedestal, const int verbosity=0)
Just return the max sample...
double SignalShape_PowerLawExp (double *x, double *par)
double SignalShape_PowerLawDoubleExp (double *x, double *par)
Variables
const int PACKET_ID = 21351
const int NSAMPLES = 31
const int ADC_DATA_MASK = (1 << 14) - 1
Mask to obtain ADC from DWord data.
const int NCH_IHCAL_ROWS = 4
const int NCH_IHCAL_COLUMNS = 4
const int NCH_OHCAL_ROWS = 4
const int NCH_OHCAL_COLUMNS = 4
const int NCH_EMCAL_ROWS = 8
const int NCH_EMCAL_COLUMNS = 8
const int SATURATED_ADC_ERROR = 100
const int DEAD_CHANNEL_ERROR = 300
const int PACKET_EMCAL_HIGHETA_FLAG = 905
Function Documentation
int PROTOTYPE4_FEM::GetChannelNumber (const std::string & caloname, int i_column, int i_row)
FEM mapping of channel -> calorimeter col and rows.
Definition at line 29 of file PROTOTYPE4_FEM.cc.
References assert, PROTOTYPE2_FEM::NCH_EMCAL_COLUMNS, PROTOTYPE2_FEM::NCH_EMCAL_ROWS, PROTOTYPE2_FEM::NCH_IHCAL_COLUMNS, PROTOTYPE2_FEM::NCH_IHCAL_ROWS, PROTOTYPE2_FEM::NCH_OHCAL_COLUMNS, and PROTOTYPE2_FEM::NCH_OHCAL_ROWS.
bool PROTOTYPE4_FEM::SampleFit_PeakSample (const std::vector< double > & samples, double & peak, double & peak_sample, double & pedestal, const int verbosity = 0)
Just return the max sample...
Parameters
peak_sample peak amplitude.
pedestal peak sample position. Fixed to the input value if NOT NAN
verbosity pedestal
Definition at line 525 of file PROTOTYPE4_FEM.cc.
References assert, NSAMPLES, and pedestal().
Referenced by RawTower_Prototype4::get_energy_peak_sample().
bool PROTOTYPE4_FEM::SampleFit_PowerLawDoubleExp (const std::vector< double > & samples, double & peak, double & peak_sample, double & pedestal, std::map< int, double > & parameters_io, const int verbosity = 0)
Power law double exp fit.
Parameters
peak_sample peak amplitude.
pedestal peak sample position. Fixed to the input value if NOT NAN
parameters_io pedestal
verbosity IO for fullset of parameters. If a parameter exist and not an NAN, the fit parameter will be fixed to that value. The order of the parameters are ("Amplitude 1", "Sample Start", "Power", "Peak Time 1", "Pedestal", "Amplitude 2", "Peak Time 2")
Definition at line 282 of file PROTOTYPE4_FEM.cc.
References assert, f2(), gpulse, i, max, min, NSAMPLES, pedestal(), TPCDaqDefs::FEEv1::SignalShape_PowerLawDoubleExp(), and TPCDaqDefs::FEEv1::SignalShape_PowerLawExp().
Referenced by TPCFEETestRecov1::Clustering(), TpcPrototypeUnpacker::Clustering(), and RawTower_Prototype4::get_energy_power_law_double_exp().
bool PROTOTYPE4_FEM::SampleFit_PowerLawExp (const std::vector< double > & samples, double & peak, double & peak_sample, double & pedstal, const int verbosity = 0)
Abhisek's power-law + exp fit.
Definition at line 159 of file PROTOTYPE4_FEM.cc.
References assert, gpulse, i, NSAMPLES, pedestal(), and TPCDaqDefs::FEEv1::SignalShape_PowerLawExp().
Referenced by RawTower_Prototype4::get_energy_power_law_exp().
double PROTOTYPE4_FEM::SignalShape_PowerLawDoubleExp (double * x, double * par)
Definition at line 499 of file PROTOTYPE4_FEM.cc.
References pedestal(), and signal().
Referenced by SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), and TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp().
double PROTOTYPE4_FEM::SignalShape_PowerLawExp (double * x, double * par)
Definition at line 268 of file PROTOTYPE4_FEM.cc.
References pedestal(), and signal().
Referenced by SampleFit_PowerLawDoubleExp(), TPCDaqDefs::FEEv1::SampleFit_PowerLawDoubleExp(), TpcPrototypeDefs::FEEv2::SampleFit_PowerLawDoubleExp(), PROTOTYPE3_FEM::SampleFit_PowerLawExp(), PROTOTYPE2_FEM::SampleFit_PowerLawExp(), and SampleFit_PowerLawExp().
Variable Documentation
const int PROTOTYPE4_FEM::ADC_DATA_MASK = (1 << 14) - 1
Mask to obtain ADC from DWord data.
Definition at line 19 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::DEAD_CHANNEL_ERROR = 300
Error assigned to dead channels
Definition at line 37 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NCH_EMCAL_COLUMNS = 8
Definition at line 31 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NCH_EMCAL_ROWS = 8
Number of EMCAL towers
Definition at line 30 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NCH_IHCAL_COLUMNS = 4
Definition at line 23 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NCH_IHCAL_ROWS = 4
Number of Inner HCAL towers
Definition at line 22 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NCH_OHCAL_COLUMNS = 4
Definition at line 27 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NCH_OHCAL_ROWS = 4
Number of Outer HCAL towers
Definition at line 26 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::NSAMPLES = 31
Number of ADC Samples per tower
Definition at line 16 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::PACKET_EMCAL_HIGHETA_FLAG = 905
special treatment for EMCal tagging packet See also https://wiki.bnl.gov/sPHENIX/index.php/2017_calorimeter_beam_test#What_is_new_in_the_data_structures_in_2017 Result stored in RUN_INFO node under variable EMCAL_Is_HighEta
Definition at line 82 of file PROTOTYPE4_FEM.h.
const int PROTOTYPE4_FEM::PACKET_ID = 21351
Packet ID
Definition at line 13 of file PROTOTYPE4_FEM.h.
Referenced by Fun4All_TestBeam().
const int PROTOTYPE4_FEM::SATURATED_ADC_ERROR = 100
Error assigned to saturated ADCs
Definition at line 34 of file PROTOTYPE4_FEM.h.