Analysis Software: PHG4Cellv1 Class Reference
PHG4Cellv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cellv1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
PHG4Cellv1 ()
PHG4Cellv1 (const PHG4CellDefs::keytype g4cellid)
virtual ~PHG4Cellv1 ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
void set_cellid (const PHG4CellDefs::keytype i)
PHG4CellDefs::keytype get_cellid () const
bool has_binning (const PHG4CellDefs::CellBinning binning) const
short int get_detid () const
void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep)
void add_shower_edep (const int g4showerid, const float edep)
EdepConstRange get_g4hits ()
ShowerEdepConstRange get_g4showers ()
void add_edep (const float f)
double get_edep () const
void add_eion (const float f)
double get_eion () const
void add_light_yield (const float f)
float get_light_yield () const
void set_chip_index (const int i)
int get_chip_index () const
void set_half_stave_index (const int i)
int get_half_stave_index () const
void set_ladder_phi_index (const int i)
int get_ladder_phi_index () const
void set_ladder_z_index (const int i)
int get_ladder_z_index () const
void set_module_index (const int i)
int get_module_index () const
void set_phibin (const int i)
int get_phibin () const
void set_pixel_index (const int i)
int get_pixel_index () const
void set_stave_index (const int i)
int get_stave_index () const
void set_zbin (const int i)
int get_zbin () const
void print () const
bool has_property (const PROPERTY prop_id) const
float get_property_float (const PROPERTY prop_id) const
int get_property_int (const PROPERTY prop_id) const
unsigned int get_property_uint (const PROPERTY prop_id) const
void add_property (const PROPERTY prop_id, const float value)
void add_property (const PROPERTY prop_id, const int value)
void add_property (const PROPERTY prop_id, const unsigned int value)
void set_property (const PROPERTY prop_id, const float value)
void set_property (const PROPERTY prop_id, const int value)
void set_property (const PROPERTY prop_id, const unsigned int value)
Public Member Functions inherited from PHG4Cell
virtual ~PHG4Cell ()
virtual void CopyFrom (const PHObject *phobj)
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const float edep, const float light_yield)
virtual void add_edep (const PHG4HitDefs::keytype g4hitid, const int tbin, const float edep)
short int get_layer () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Protected Member Functions inherited from PHG4Cell
PHG4Cell ()
Protected Attributes
PHG4CellDefs::keytype cellid
EdepMap hitedeps
ShowerEdepMap showeredeps
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PHG4Cell
enum PROPERTY {
prop_stave_index = 1, prop_half_stave_index = 2, prop_module_index = 3, prop_chip_index = 4,
prop_pixel_index = 5, prop_phibin = 6, prop_zbin = 7, prop_ladder_z_index = 8,
prop_ladder_phi_index = 9, prop_edep = 21, prop_eion = 22, prop_light_yield = 23,
prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
typedef std::map
< PHG4HitDefs::keytype, float > EdepMap
typedef EdepMap::iterator EdepIterator
typedef EdepMap::const_iterator EdepConstIterator
typedef std::pair
< EdepIterator, EdepIterator > EdepRange
typedef std::pair
< EdepConstIterator,
EdepConstIterator > EdepConstRange
typedef std::map< int, float > ShowerEdepMap
typedef ShowerEdepMap::iterator ShowerEdepIterator
typedef
ShowerEdepMap::const_iterator ShowerEdepConstIterator
typedef std::pair
< ShowerEdepIterator,
ShowerEdepIterator > ShowerEdepRange
typedef std::pair
< ShowerEdepConstIterator,
ShowerEdepConstIterator > ShowerEdepConstRange
typedef std::pair< unsigned
short, std::map< int, int > > tpccompress
typedef std::map< unsigned
short, tpccompress > tpctod
Static Public Member Functions inherited from PHG4Cell
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 22 of file PHG4Cellv1.h.
Member Typedef Documentation
typedef uint8_t PHG4Cellv1::prop_id_t protected
storage types for additional property
Definition at line 112 of file PHG4Cellv1.h.
typedef std::map<prop_id_t, prop_storage_t> PHG4Cellv1::prop_map_t protected
Definition at line 114 of file PHG4Cellv1.h.
typedef uint32_t PHG4Cellv1::prop_storage_t protected
Definition at line 113 of file PHG4Cellv1.h.
Constructor & Destructor Documentation
PHG4Cellv1::PHG4Cellv1 ()
Definition at line 15 of file PHG4Cellv1.cc.
PHG4Cellv1::PHG4Cellv1 (const PHG4CellDefs::keytype g4cellid)
Definition at line 19 of file PHG4Cellv1.cc.
PHG4Cellv1::~PHG4Cellv1 () virtual
Definition at line 23 of file PHG4Cellv1.cc.
References hitedeps, prop_map, and showeredeps.
Member Function Documentation
void PHG4Cellv1::add_edep (const PHG4HitDefs::keytype g4hitid, const float edep) virtual
Reimplemented from PHG4Cell.
Definition at line 32 of file PHG4Cellv1.cc.
References hitedeps.
void PHG4Cellv1::add_edep (const float f) inline virtual
Reimplemented from PHG4Cell.
Definition at line 50 of file PHG4Cellv1.h.
References add_property(), and PHG4Cell::prop_edep.
void PHG4Cellv1::add_eion (const float f) inline virtual
Reimplemented from PHG4Cell.
Definition at line 53 of file PHG4Cellv1.h.
References add_property(), and PHG4Cell::prop_eion.
void PHG4Cellv1::add_light_yield (const float f) inline virtual
Reimplemented from PHG4Cell.
Definition at line 56 of file PHG4Cellv1.h.
References add_property(), and PHG4Cell::prop_light_yield.
void PHG4Cellv1::add_property (const PROPERTY prop_id, const float value)
Definition at line 119 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), get_property_float(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, PHG4Cell::type_float, and value.
Referenced by add_edep(), add_eion(), and add_light_yield().
void PHG4Cellv1::add_property (const PROPERTY prop_id, const int value)
Definition at line 138 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), get_property_int(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, PHG4Cell::type_int, and value.
void PHG4Cellv1::add_property (const PROPERTY prop_id, const unsigned int value)
Definition at line 157 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), get_property_uint(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, PHG4Cell::type_uint, and value.
void PHG4Cellv1::add_shower_edep (const int g4showerid, const float edep) virtual
Reimplemented from PHG4Cell.
Definition at line 39 of file PHG4Cellv1.cc.
References showeredeps.
PHG4CellDefs::keytype PHG4Cellv1::get_cellid () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 34 of file PHG4Cellv1.h.
References cellid.
int PHG4Cellv1::get_chip_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 60 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_chip_index.
short int PHG4Cellv1::get_detid () const virtual
Reimplemented from PHG4Cell.
Definition at line 52 of file PHG4Cellv1.cc.
References cellid, and PHG4CellDefs::get_detid().
double PHG4Cellv1::get_edep () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 51 of file PHG4Cellv1.h.
References get_property_float(), and PHG4Cell::prop_edep.
double PHG4Cellv1::get_eion () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 54 of file PHG4Cellv1.h.
References get_property_float(), and PHG4Cell::prop_eion.
EdepConstRange PHG4Cellv1::get_g4hits () inline virtual
Reimplemented from PHG4Cell.
Definition at line 41 of file PHG4Cellv1.h.
References hitedeps.
ShowerEdepConstRange PHG4Cellv1::get_g4showers () inline virtual
Reimplemented from PHG4Cell.
Definition at line 45 of file PHG4Cellv1.h.
References showeredeps.
int PHG4Cellv1::get_half_stave_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 63 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_half_stave_index.
int PHG4Cellv1::get_ladder_phi_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 66 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_ladder_phi_index.
int PHG4Cellv1::get_ladder_z_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 69 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_ladder_z_index.
float PHG4Cellv1::get_light_yield () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 57 of file PHG4Cellv1.h.
References get_property_float(), and PHG4Cell::prop_light_yield.
int PHG4Cellv1::get_module_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 72 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_module_index.
int PHG4Cellv1::get_phibin () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 75 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_phibin.
int PHG4Cellv1::get_pixel_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 78 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_pixel_index.
float PHG4Cellv1::get_property_float (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Cell.
Definition at line 65 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cellv1::u_property::fdata, PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), i, PHWHERE, prop_map, and PHG4Cell::type_float.
Referenced by add_property(), get_edep(), get_eion(), get_light_yield(), and identify().
int PHG4Cellv1::get_property_int (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Cell.
Definition at line 83 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), i, PHG4Cellv1::u_property::idata, PHWHERE, prop_map, and PHG4Cell::type_int.
Referenced by add_property(), get_chip_index(), get_half_stave_index(), get_ladder_phi_index(), get_ladder_z_index(), get_module_index(), get_phibin(), get_pixel_index(), get_stave_index(), get_zbin(), and identify().
unsigned int PHG4Cellv1::get_property_nocheck (const PROPERTY prop_id) const protected virtual
Reimplemented from PHG4Cell.
Definition at line 218 of file PHG4Cellv1.cc.
References prop_map.
unsigned int PHG4Cellv1::get_property_uint (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Cell.
Definition at line 101 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), i, PHWHERE, prop_map, PHG4Cell::type_uint, and PHG4Cellv1::u_property::uidata.
Referenced by add_property(), and identify().
int PHG4Cellv1::get_stave_index () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 81 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_stave_index.
int PHG4Cellv1::get_zbin () const inline virtual
Reimplemented from PHG4Cell.
Definition at line 86 of file PHG4Cellv1.h.
References get_property_int(), and PHG4Cell::prop_zbin.
bool PHG4Cellv1::has_binning (const PHG4CellDefs::CellBinning binning) const virtual
Reimplemented from PHG4Cell.
Definition at line 46 of file PHG4Cellv1.cc.
References cellid, and PHG4CellDefs::has_binning().
bool PHG4Cellv1::has_property (const PROPERTY prop_id) const virtual
Reimplemented from PHG4Cell.
Definition at line 58 of file PHG4Cellv1.cc.
References i, and prop_map.
void PHG4Cellv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4Cell.
Definition at line 243 of file PHG4Cellv1.cc.
References cellid, get_property_float(), PHG4Cell::get_property_info(), get_property_int(), get_property_uint(), hitedeps, i, prop_map, showeredeps, PHG4Cell::type_float, PHG4Cell::type_int, and PHG4Cell::type_uint.
Referenced by print().
void PHG4Cellv1::print () const virtual
Reimplemented from PHG4Cell.
Definition at line 229 of file PHG4Cellv1.cc.
References identify().
void PHG4Cellv1::Reset () virtual
Clear Event.
Reimplemented from PHG4Cell.
Definition at line 235 of file PHG4Cellv1.cc.
References hitedeps, prop_map, and showeredeps.
void PHG4Cellv1::set_cellid (const PHG4CellDefs::keytype i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 32 of file PHG4Cellv1.h.
References cellid, and i.
void PHG4Cellv1::set_chip_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 59 of file PHG4Cellv1.h.
References PHG4Cell::prop_chip_index, and set_property().
void PHG4Cellv1::set_half_stave_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 62 of file PHG4Cellv1.h.
References PHG4Cell::prop_half_stave_index, and set_property().
void PHG4Cellv1::set_ladder_phi_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 65 of file PHG4Cellv1.h.
References PHG4Cell::prop_ladder_phi_index, and set_property().
void PHG4Cellv1::set_ladder_z_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 68 of file PHG4Cellv1.h.
References PHG4Cell::prop_ladder_z_index, and set_property().
void PHG4Cellv1::set_module_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 71 of file PHG4Cellv1.h.
References PHG4Cell::prop_module_index, and set_property().
void PHG4Cellv1::set_phibin (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 74 of file PHG4Cellv1.h.
References PHG4Cell::prop_phibin, and set_property().
void PHG4Cellv1::set_pixel_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 77 of file PHG4Cellv1.h.
References PHG4Cell::prop_pixel_index, and set_property().
void PHG4Cellv1::set_property (const PROPERTY prop_id, const float value) virtual
Reimplemented from PHG4Cell.
Definition at line 176 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Cell::type_float.
Referenced by set_chip_index(), set_half_stave_index(), set_ladder_phi_index(), set_ladder_z_index(), set_module_index(), set_phibin(), set_pixel_index(), set_stave_index(), and set_zbin().
void PHG4Cellv1::set_property (const PROPERTY prop_id, const int value) virtual
Reimplemented from PHG4Cell.
Definition at line 190 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Cell::type_int.
void PHG4Cellv1::set_property (const PROPERTY prop_id, const unsigned int value) virtual
Reimplemented from PHG4Cell.
Definition at line 204 of file PHG4Cellv1.cc.
References PHG4Cell::check_property(), PHG4Cell::get_property_info(), PHG4Cell::get_property_type(), PHG4Cellv1::u_property::get_storage(), PHWHERE, prop_map, and PHG4Cell::type_uint.
void PHG4Cellv1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline protected virtual
Reimplemented from PHG4Cell.
Definition at line 104 of file PHG4Cellv1.h.
References prop_map.
void PHG4Cellv1::set_stave_index (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 80 of file PHG4Cellv1.h.
References PHG4Cell::prop_stave_index, and set_property().
void PHG4Cellv1::set_zbin (const int i) inline virtual
Reimplemented from PHG4Cell.
Definition at line 85 of file PHG4Cellv1.h.
References PHG4Cell::prop_zbin, and set_property().
Member Data Documentation
PHG4CellDefs::keytype PHG4Cellv1::cellid protected
Definition at line 106 of file PHG4Cellv1.h.
Referenced by get_cellid(), get_detid(), has_binning(), identify(), and set_cellid().
EdepMap PHG4Cellv1::hitedeps protected
Definition at line 107 of file PHG4Cellv1.h.
Referenced by add_edep(), get_g4hits(), identify(), Reset(), and ~PHG4Cellv1().
prop_map_t PHG4Cellv1::prop_map protected
container for additional property
Definition at line 131 of file PHG4Cellv1.h.
Referenced by add_property(), get_property_float(), get_property_int(), get_property_nocheck(), get_property_uint(), has_property(), identify(), Reset(), set_property(), set_property_nocheck(), and ~PHG4Cellv1().
ShowerEdepMap PHG4Cellv1::showeredeps protected
Definition at line 108 of file PHG4Cellv1.h.
Referenced by add_shower_edep(), get_g4showers(), identify(), Reset(), and ~PHG4Cellv1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cellv1.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4Cellv1.cc