Analysis Software: Proto2ShowerCalib Class Reference
Proto2ShowerCalib Class Reference
#include <analysis/blob/master/Prototype2/EMCal/ShowerCalib/Proto2ShowerCalib.h>
Classes
class Eval_Cluster
class Eval_Run
class HCAL_shower
class Time_Samples
Public Member Functions
Proto2ShowerCalib (const std::string &filename="cemc_ana.root")
virtual ~Proto2ShowerCalib ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int LoadRecalibMap (const std::string &file)
void is_sim (bool b)
Proto2ShowerCalib (const std::string &filename="ana.root")
virtual ~Proto2ShowerCalib ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
int LoadRecalibMap (const std::string &file)
void set_sim (const bool b)
void fill_time_samples (const bool)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { n_size = 8 }
enum { n_size_emcal = 8, n_size_hcalin = 4, n_size_hcalout = 4 }
Private Member Functions
Fun4AllHistoManager * get_HistoManager ()
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
Fun4AllHistoManager * get_HistoManager ()
Private Attributes
bool _is_sim
std::string _filename
unsigned long _ievent
fstream fdata
Eval_Run _eval_run
Eval_Cluster _eval_3x3_raw
Eval_Cluster _eval_5x5_raw
Eval_Cluster _eval_3x3_prod
Eval_Cluster _eval_5x5_prod
Eval_Cluster _eval_3x3_temp
Eval_Cluster _eval_5x5_temp
Eval_Cluster _eval_3x3_recalib
Eval_Cluster _eval_5x5_recalib
std::map< std::pair< int, int >
, double > _recalib_const
HCAL_shower _shower
Time_Samples _time_samples
bool _fill_time_samples
std::map< std::pair< int, int >
, double > _emcal_recalib_const
std::map< std::pair< int, int >
, double > _hcalin_recalib_const
std::map< std::pair< int, int >
, double > _hcalout_recalib_const
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file Proto2ShowerCalib.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
n_size
Definition at line 163 of file Proto2ShowerCalib.h.
anonymous enum private
Enumerator:
n_size_emcal
n_size_hcalin
n_size_hcalout
Definition at line 169 of file Proto2ShowerCalib.h.
Constructor & Destructor Documentation
Proto2ShowerCalib::Proto2ShowerCalib (const std::string & filename = "cemc_ana.root")
Definition at line 47 of file Proto2ShowerCalib.C.
References _eval_3x3_prod, _eval_3x3_raw, _eval_3x3_recalib, _eval_3x3_temp, _eval_5x5_prod, _eval_5x5_raw, _eval_5x5_recalib, _eval_5x5_temp, _eval_run, _recalib_const, col, n_size, Proto2ShowerCalib::Eval_Run::reset(), Proto2ShowerCalib::Eval_Cluster::reset(), and verbosity.
Proto2ShowerCalib::~Proto2ShowerCalib () virtual
Definition at line 72 of file Proto2ShowerCalib.C.
Proto2ShowerCalib::Proto2ShowerCalib (const std::string & filename = "ana.root")
virtual Proto2ShowerCalib::~Proto2ShowerCalib () virtual
Member Function Documentation
int Proto2ShowerCalib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 119 of file Proto2ShowerCalib.C.
References _filename, assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, fdata, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, and Fun4AllHistoManager::nHistos().
int Proto2ShowerCalib::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
void Proto2ShowerCalib::fill_time_samples (const bool b)
Definition at line 68 of file Proto2ShowerCalib.C.
References _fill_time_samples.
pair< int, int > Proto2ShowerCalib::find_max (RawTowerContainer * towers, int cluster_size) private
Definition at line 643 of file Proto2ShowerCalib.C.
References assert, col, energy, RawTower::get_energy(), RawTowerContainer::getTower(), max, n_size, and t.
Referenced by process_event().
Fun4AllHistoManager * Proto2ShowerCalib::get_HistoManager () private
Definition at line 77 of file Proto2ShowerCalib.C.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), Init(), and process_event().
Fun4AllHistoManager* Proto2ShowerCalib::get_HistoManager () private
int Proto2ShowerCalib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 138 of file Proto2ShowerCalib.C.
References _eval_3x3_prod, _eval_3x3_raw, _eval_3x3_recalib, _eval_3x3_temp, _eval_5x5_prod, _eval_5x5_raw, _eval_5x5_recalib, _eval_5x5_temp, _eval_run, _filename, _ievent, assert, Fun4AllReturnCodes::EVENT_OK, fdata, PHTFileServer::get(), get_HistoManager(), hNormalization, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), and T.
int Proto2ShowerCalib::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
int Proto2ShowerCalib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
int Proto2ShowerCalib::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 98 of file Proto2ShowerCalib.C.
References _ievent, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and verbosity.
void Proto2ShowerCalib::is_sim (bool b) inline
Definition at line 45 of file Proto2ShowerCalib.h.
References _is_sim.
int Proto2ShowerCalib::LoadRecalibMap (const std::string & file)
Definition at line 680 of file Proto2ShowerCalib.C.
References _recalib_const, assert, col, line, and verbosity.
Referenced by Fun4All_TestBeam_ShowerCalib().
int Proto2ShowerCalib::LoadRecalibMap (const std::string & file)
int Proto2ShowerCalib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
int Proto2ShowerCalib::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 202 of file Proto2ShowerCalib.C.
References _eval_3x3_prod, _eval_3x3_raw, _eval_3x3_recalib, _eval_3x3_temp, _eval_5x5_prod, _eval_5x5_raw, _eval_5x5_recalib, _eval_5x5_temp, _eval_run, _is_sim, _recalib_const, TemperatureCorrection::Apply(), assert, Proto2ShowerCalib::Eval_Cluster::average_col, Proto2ShowerCalib::Eval_Cluster::average_row, Proto2ShowerCalib::Eval_Run::beam_mom, Proto2ShowerCalib::Eval_Run::C2_sum, col, Proto2ShowerCalib::Eval_Run::EoP, Proto2ShowerCalib::Eval_Run::event, Fun4AllReturnCodes::EVENT_OK, fdata, PHParameters::FillFrom(), find_max(), RawTower::get_bineta(), RawTower::get_binphi(), RawTower::get_column(), PHParameters::get_double_param(), RawTower::get_energy(), EventHeader::get_EvtSequence(), get_HistoManager(), RawTower::get_id(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), RawTower::get_row(), EventHeader::get_RunNumber(), RawTower_Temperature::get_temperature_from_time(), EventHeader::get_TimeStamp(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), findNode::getClass(), Fun4AllHistoManager::getHisto(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), PHG4TruthInfoContainer::GetVtx(), Proto2ShowerCalib::Eval_Run::good_data, Proto2ShowerCalib::Eval_Run::good_e, Proto2ShowerCalib::Eval_Run::good_temp, hNormalization, Proto2ShowerCalib::Eval_Run::hodo_h, Proto2ShowerCalib::Eval_Run::hodo_v, it, Proto2ShowerCalib::Eval_Cluster::max_col, Proto2ShowerCalib::Eval_Cluster::max_row, Proto2ShowerCalib::Eval_Run::reset(), Proto2ShowerCalib::Eval_Cluster::reset(), Proto2ShowerCalib::Eval_Cluster::reweight_clus_pol(), Proto2ShowerCalib::Eval_Run::run, Proto2ShowerCalib::Eval_Cluster::sum_E, Proto2ShowerCalib::Eval_Run::sum_energy_T, T, Proto2ShowerCalib::Eval_Run::trigger_veto_pass, Proto2ShowerCalib::Eval_Run::truth_y, Proto2ShowerCalib::Eval_Run::truth_z, v, Proto2ShowerCalib::Eval_Run::valid_hodo_h, Proto2ShowerCalib::Eval_Run::valid_hodo_v, and verbosity.
void Proto2ShowerCalib::set_sim (const bool b) inline
Definition at line 161 of file Proto2ShowerCalib.h.
References _is_sim.
Member Data Documentation
std::map<std::pair<int, int>, double> Proto2ShowerCalib::_emcal_recalib_const private
Definition at line 193 of file Proto2ShowerCalib.h.
Eval_Cluster Proto2ShowerCalib::_eval_3x3_prod private
Definition at line 187 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_3x3_raw private
Definition at line 184 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_3x3_recalib private
Definition at line 193 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_3x3_temp private
Definition at line 190 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_5x5_prod private
Definition at line 188 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_5x5_raw private
Definition at line 185 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_5x5_recalib private
Definition at line 194 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Cluster Proto2ShowerCalib::_eval_5x5_temp private
Definition at line 191 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
Eval_Run Proto2ShowerCalib::_eval_run private
Definition at line 182 of file Proto2ShowerCalib.h.
Referenced by Init(), process_event(), and Proto2ShowerCalib().
std::string Proto2ShowerCalib::_filename private
Definition at line 176 of file Proto2ShowerCalib.h.
Referenced by End(), and Init().
bool Proto2ShowerCalib::_fill_time_samples private
Definition at line 192 of file Proto2ShowerCalib.h.
Referenced by fill_time_samples().
std::map<std::pair<int, int>, double> Proto2ShowerCalib::_hcalin_recalib_const private
Definition at line 194 of file Proto2ShowerCalib.h.
std::map<std::pair<int, int>, double> Proto2ShowerCalib::_hcalout_recalib_const private
Definition at line 195 of file Proto2ShowerCalib.h.
unsigned long Proto2ShowerCalib::_ievent private
Definition at line 178 of file Proto2ShowerCalib.h.
Referenced by Init(), and InitRun().
bool Proto2ShowerCalib::_is_sim private
Definition at line 168 of file Proto2ShowerCalib.h.
Referenced by is_sim(), process_event(), and set_sim().
std::map<std::pair<int, int>, double> Proto2ShowerCalib::_recalib_const private
Definition at line 196 of file Proto2ShowerCalib.h.
Referenced by LoadRecalibMap(), process_event(), and Proto2ShowerCalib().
HCAL_shower Proto2ShowerCalib::_shower private
Definition at line 187 of file Proto2ShowerCalib.h.
Time_Samples Proto2ShowerCalib::_time_samples private
Definition at line 189 of file Proto2ShowerCalib.h.
fstream Proto2ShowerCalib::fdata private
Definition at line 180 of file Proto2ShowerCalib.h.
Referenced by End(), Init(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype2/EMCal/ShowerCalib/Proto2ShowerCalib.h
analysis/blob/master/Prototype2/HCAL/ShowerCalib/Proto2ShowerCalib.h
analysis/blob/master/Prototype2/EMCal/ShowerCalib/Proto2ShowerCalib.C
analysis/blob/master/Prototype2/HCAL/ShowerCalib/Proto2ShowerCalib.C