Analysis Software: analysis/blob/master/EIC-IR/macros_fun4all/G4Setup_EICIR.C File Reference
G4Setup_EICIR.C File Reference
Functions
void G4Init (bool do_magnet=true, bool do_pipe=true, bool do_ExtendedIR=true)
int G4Setup (const int absorberactive=0, const string &field="1.5", const EDecayType decayType=TPythia6Decayer::kAll, const bool do_magnet=true, const bool do_pipe=true, const bool do_ExtendedIR=true, const float magfield_rescale=1.0)
Variables
double no_overlapp = 0.0001
bool overlapcheck = false
Function Documentation
void G4Init (bool do_magnet = true, bool do_pipe = true, bool do_ExtendedIR = true)
Definition at line 5 of file G4Setup_EICIR.C.
References IRInit(), MagnetInit(), and PipeInit().
int G4Setup (const int absorberactive = 0, const string & field = "1.5", const EDecayType decayType = TPythia6Decayer::kAll, const bool do_magnet = true, const bool do_pipe = true, const bool do_ExtendedIR = true, const float magfield_rescale = 1.0)
Definition at line 32 of file G4Setup_EICIR.C.
References i, Fun4AllServer::instance(), IRSetup(), kAll, Magnet(), overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), Pipe(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4Reco::set_field(), PHG4Reco::set_field_map(), PHG4Reco::set_field_rescale(), PHG4Reco::set_force_decay(), PHG4DetectorSubsystem::set_int_param(), PHG4Reco::set_rapidity_coverage(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4Reco::SetWorldMaterial(), and PHG4DetectorSubsystem::SuperDetector().
Variable Documentation
double no_overlapp = 0.0001
Definition at line 2 of file G4Setup_EICIR.C.
bool overlapcheck = false
Definition at line 3 of file G4Setup_EICIR.C.