Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_Svtx.C File Reference
G4_Svtx.C File Reference
Functions
void SvtxInit (int verbosity=0)
double Svtx (PHG4Reco *g4Reco, double radius, const int absorberactive=0, int verbosity=0)
void Svtx_Cells (int verbosity=0)
void Svtx_Reco (int verbosity=0)
void G4_Svtx_Reco ()
void Svtx_Eval (std::string outputfile, int verbosity=0)
Variables
int Min_si_layer = 0
int Max_si_layer = 6
Function Documentation
void G4_Svtx_Reco ()
Definition at line 314 of file G4_Svtx.C.
References Svtx_Reco().
double Svtx (PHG4Reco * g4Reco, double radius, const int absorberactive = 0, int verbosity = 0)
Definition at line 12 of file G4_Svtx.C.
References Max_si_layer, Min_si_layer, no_overlapp, PHG4Reco::registerSubsystem(), PHG4DetectorSubsystem::set_double_param(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4DetectorSubsystem::SetActive(), PHG4DetectorSubsystem::SuperDetector(), and verbosity.
void Svtx_Cells (int verbosity = 0)
Definition at line 120 of file G4_Svtx.C.
References PHG4CylinderCellReco::cellsize(), PHG4CylinderCellReco::Detector(), i, Fun4AllServer::instance(), Max_si_layer, Min_si_layer, Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
void Svtx_Eval (std::string outputfile, int verbosity = 0)
Definition at line 324 of file G4_Svtx.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), verbosity, and Fun4AllBase::Verbosity().
Referenced by ConfigureDetectors(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), Jin_BJet(), and Wrapper().
void Svtx_Reco (int verbosity = 0)
Definition at line 165 of file G4_Svtx.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and verbosity.
void SvtxInit (int verbosity = 0)
Definition at line 6 of file G4_Svtx.C.
References Max_si_layer, and Min_si_layer.
Variable Documentation
int Max_si_layer = 6
Definition at line 4 of file G4_Svtx.C.
int Min_si_layer = 0
Definition at line 3 of file G4_Svtx.C.
Referenced by Get_Min_si_layer(), Svtx(), Svtx_Cells(), Svtx_Reco(), and SvtxInit().