Analysis Software: PidCandidatev1 Class Reference
PidCandidatev1 Class Reference
#include <analysis/blob/master/EICAnalysis/PidCandidatev1.h>
Classes
union u_property
convert between 32bit inputs and storage type prop_storage_t
Public Member Functions
PidCandidatev1 ()
PidCandidatev1 (const PidCandidate &tc)
virtual ~PidCandidatev1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
void set_candidate_id (const int i)
int get_candidate_id () const
virtual void print () const
bool has_property (const PROPERTY prop_id) const
float get_property_float (const PROPERTY prop_id) const
int get_property_int (const PROPERTY prop_id) const
unsigned int get_property_uint (const PROPERTY prop_id) const
void set_property (const PROPERTY prop_id, const float value)
void set_property (const PROPERTY prop_id, const int value)
void set_property (const PROPERTY prop_id, const unsigned int value)
Public Member Functions inherited from PidCandidate
PidCandidate ()
virtual ~PidCandidate ()
virtual void Copy (PidCandidate const &tc)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Types
typedef uint8_t prop_id_t
storage types for additional property
typedef uint32_t prop_storage_t
typedef std::map< prop_id_t,
prop_storage_t > prop_map_t
Protected Member Functions
unsigned int get_property_nocheck (const PROPERTY prop_id) const
void set_property_nocheck (const PROPERTY prop_id, const unsigned int ui)
Protected Attributes
int _candidateid
prop_map_t prop_map
container for additional property
Additional Inherited Members
Public Types inherited from PidCandidate
enum PROPERTY {
evtgen_pid = 1, evtgen_ptotal = 2, evtgen_etotal = 3, evtgen_theta = 4,
evtgen_phi = 5, evtgen_eta = 6, evtgen_charge = 7, evtgen_decay_prong = 8,
evtgen_decay_hcharged = 9, evtgen_decay_lcharged = 10, jet_id = 101, jet_eta = 102,
jet_phi = 103, jet_etotal = 104, jet_etrans = 105, jet_ptotal = 106,
jet_ptrans = 107, jet_minv = 108, jet_mtrans = 109, jet_ncomp = 110,
jet_ncomp_above_0p1 = 111, jet_ncomp_above_1 = 112, jet_ncomp_above_10 = 113, jet_ncomp_emcal = 115,
jetshape_radius = 121, jetshape_rms = 122, jetshape_r90 = 123, jetshape_econe_r01 = 131,
jetshape_econe_r02 = 132, jetshape_econe_r03 = 133, jetshape_econe_r04 = 134, jetshape_econe_r05 = 135,
jetshape_emcal_radius = 161, jetshape_emcal_rms = 162, jetshape_emcal_r90 = 163, jetshape_emcal_econe_r01 = 171,
jetshape_emcal_econe_r02 = 172, jetshape_emcal_econe_r03 = 173, jetshape_emcal_econe_r04 = 174, jetshape_emcal_econe_r05 = 175,
tracks_count_r02 = 210, tracks_count_r04 = 211, tracks_count_R = 212, tracks_rmax_r02 = 215,
tracks_rmax_r04 = 216, tracks_rmax_R = 217, tracks_chargesum_r02 = 220, tracks_chargesum_r04 = 221,
tracks_chargesum_R = 222, tracks_vertex = 223, em_cluster_id = 301, em_cluster_prob = 302,
em_cluster_posx = 303, em_cluster_posy = 304, em_cluster_posz = 305, em_cluster_e = 306,
em_cluster_ecore = 307, em_cluster_et_iso = 308, em_cluster_theta = 309, em_cluster_phi = 310,
em_cluster_eta = 311, em_cluster_pt = 312, em_cluster_ntower = 313, em_cluster_caloid = 314,
em_track_id = 350, em_track_quality = 351, em_track_theta = 352, em_track_phi = 353,
em_track_eta = 354, em_track_ptotal = 355, em_track_ptrans = 356, em_track_charge = 357,
em_track_dca = 358, em_track_section = 359, em_track_e3x3_cemc = 360, em_track_e3x3_femc = 361,
em_track_e3x3_eemc = 362, em_track_e3x3_ihcal = 363, em_track_e3x3_ohcal = 364, em_track_e3x3_fhcal = 365,
em_track_e3x3_ehcal = 366, em_track_cluster_dr = 367, em_track_theta2cluster = 368, em_track_eta2cluster = 369,
em_track_phi2cluster = 370, em_track_p2cluster = 371, em_track_x2cluster = 372, em_track_y2cluster = 373,
em_track_z2cluster = 374, em_pid_prob_electron = 391, em_pid_prob_pion = 392, em_pid_prob_kaon = 393,
em_pid_prob_proton = 394, em_evtgen_pid = 401, em_evtgen_ptotal = 402, em_evtgen_etotal = 403,
em_evtgen_theta = 404, em_evtgen_phi = 405, em_evtgen_eta = 406, em_evtgen_charge = 407,
em_evtgen_is_scattered_lepton = 408, em_reco_x_e = 410, em_reco_y_e = 411, em_reco_q2_e = 412,
em_reco_w_e = 413, prop_MAX_NUMBER = UCHAR_MAX
}
enum PROPERTY_TYPE { type_int = 1, type_uint = 2, type_float = 3, type_unknown = -1 }
Static Public Member Functions inherited from PidCandidate
static std::pair< const
std::string, PROPERTY_TYPE > get_property_info (PROPERTY prop_id)
static bool check_property (const PROPERTY prop_id, const PROPERTY_TYPE prop_type)
static std::string get_property_type (const PROPERTY_TYPE prop_type)
Detailed Description
Definition at line 14 of file PidCandidatev1.h.
Member Typedef Documentation
typedef uint8_t PidCandidatev1::prop_id_t protected
storage types for additional property
Definition at line 44 of file PidCandidatev1.h.
typedef std::map<prop_id_t, prop_storage_t> PidCandidatev1::prop_map_t protected
Definition at line 46 of file PidCandidatev1.h.
typedef uint32_t PidCandidatev1::prop_storage_t protected
Definition at line 45 of file PidCandidatev1.h.
Constructor & Destructor Documentation
PidCandidatev1::PidCandidatev1 ()
PidCandidatev1::PidCandidatev1 (const PidCandidate & tc) explicit
Definition at line 16 of file PidCandidatev1.C.
virtual PidCandidatev1::~PidCandidatev1 () inline virtual
Definition at line 19 of file PidCandidatev1.h.
Member Function Documentation
int PidCandidatev1::get_candidate_id () const inline
Definition at line 26 of file PidCandidatev1.h.
References _candidateid.
Referenced by DISKinematicsReco::CollectEmCandidatesFromTruth(), and DISKinematicsReco::InsertCandidateFromCluster().
float PidCandidatev1::get_property_float (const PROPERTY prop_id) const virtual
Reimplemented from PidCandidate.
Definition at line 62 of file PidCandidatev1.C.
References PidCandidatev1::u_property::fdata, i, and PHWHERE.
int PidCandidatev1::get_property_int (const PROPERTY prop_id) const virtual
Reimplemented from PidCandidate.
Definition at line 80 of file PidCandidatev1.C.
References i, PidCandidatev1::u_property::idata, and PHWHERE.
unsigned int PidCandidatev1::get_property_nocheck (const PROPERTY prop_id) const protected virtual
Reimplemented from PidCandidate.
Definition at line 158 of file PidCandidatev1.C.
unsigned int PidCandidatev1::get_property_uint (const PROPERTY prop_id) const virtual
Reimplemented from PidCandidate.
Definition at line 98 of file PidCandidatev1.C.
References i, PHWHERE, and PidCandidatev1::u_property::uidata.
bool PidCandidatev1::has_property (const PROPERTY prop_id) const virtual
Reimplemented from PidCandidate.
Definition at line 55 of file PidCandidatev1.C.
References i.
void PidCandidatev1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PidCandidate.
Definition at line 169 of file PidCandidatev1.C.
References i.
void PidCandidatev1::print () const virtual
Reimplemented from PidCandidate.
Definition at line 28 of file PidCandidatev1.C.
References i.
void PidCandidatev1::Reset () virtual
Clear Event.
Reimplemented from PidCandidate.
Definition at line 22 of file PidCandidatev1.C.
void PidCandidatev1::set_candidate_id (const int i) inline
Definition at line 25 of file PidCandidatev1.h.
References _candidateid, and i.
Referenced by DISKinematicsReco::CollectEmCandidatesFromTruth(), DISKinematicsReco::InsertCandidateFromCluster(), and LeptoquarksReco::process_event().
void PidCandidatev1::set_property (const PROPERTY prop_id, const float value) virtual
Reimplemented from PidCandidate.
Definition at line 116 of file PidCandidatev1.C.
References PidCandidatev1::u_property::get_storage(), and PHWHERE.
Referenced by DISKinematicsReco::CollectEmCandidatesFromTruth(), DISKinematicsReco::InsertCandidateFromCluster(), and LeptoquarksReco::process_event().
void PidCandidatev1::set_property (const PROPERTY prop_id, const int value) virtual
Reimplemented from PidCandidate.
Definition at line 130 of file PidCandidatev1.C.
References PidCandidatev1::u_property::get_storage(), and PHWHERE.
void PidCandidatev1::set_property (const PROPERTY prop_id, const unsigned int value) virtual
Reimplemented from PidCandidate.
Definition at line 144 of file PidCandidatev1.C.
References PidCandidatev1::u_property::get_storage(), and PHWHERE.
void PidCandidatev1::set_property_nocheck (const PROPERTY prop_id, const unsigned int ui) inline protected virtual
Reimplemented from PidCandidate.
Definition at line 40 of file PidCandidatev1.h.
References prop_map.
Member Data Documentation
int PidCandidatev1::_candidateid protected
Definition at line 41 of file PidCandidatev1.h.
Referenced by get_candidate_id(), and set_candidate_id().
prop_map_t PidCandidatev1::prop_map protected
container for additional property
Definition at line 63 of file PidCandidatev1.h.
Referenced by set_property_nocheck().
The documentation for this class was generated from the following files:
analysis/blob/master/EICAnalysis/PidCandidatev1.h
analysis/blob/master/EICAnalysis/PidCandidatev1.C