Analysis Software: ReadCuts Class Reference
ReadCuts Class Reference
Public Member Functions
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const override
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const override
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const
ReadCuts (std::vector< std::string > &theInputVars)
virtual ~ReadCuts ()
double GetMvaValue (const std::vector< double > &inputValues) const
Public Member Functions inherited from IClassifierReader
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
bool IsStatusClean () const
Private Member Functions
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
void Clear ()
size_t GetNvar () const
char GetType (int ivar) const
bool IsNormalised () const
double NormVariable (double x, double xmin, double xmax) const
void Initialize ()
double GetMvaValue__ (const std::vector< double > &inputValues) const
Private Attributes
const char * fClassName
const size_t fNvars
double fVmin [10]
double fVmax [10]
char fType [10]
const bool fIsNormalised
Additional Inherited Members
Protected Attributes inherited from IClassifierReader
bool fStatusIsClean
Detailed Description
Definition at line 113 of file aback_Cuts.class.C.
Constructor & Destructor Documentation
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 118 of file aback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 187 of file aback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 102 of file aback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 159 of file aback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 93 of file aback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 145 of file aback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 106 of file eback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 167 of file eback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 106 of file hback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 167 of file hback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 101 of file pairback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 156 of file pairback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 93 of file trackback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 145 of file trackback_Cuts.class.C.
References Clear().
ReadCuts::ReadCuts (std::vector< std::string > & theInputVars) inline
Definition at line 98 of file vtxback_Cuts.class.C.
References fClassName, fNvars, IClassifierReader::fStatusIsClean, fType, fVmax, fVmin, and Initialize().
virtual ReadCuts::~ReadCuts () inline virtual
Definition at line 147 of file vtxback_Cuts.class.C.
References Clear().
Member Function Documentation
void ReadCuts::Clear () private
void ReadCuts::Clear () private
void ReadCuts::Clear () private
void ReadCuts::Clear () private
void ReadCuts::Clear () private
void ReadCuts::Clear () private
void ReadCuts::Clear () private
void ReadCuts::Clear () private
Referenced by ~ReadCuts().
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const override virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const virtual
Implements IClassifierReader.
double ReadCuts::GetMvaValue (const std::vector< double > & inputValues) const inline override virtual
Implements IClassifierReader.
Definition at line 226 of file aback_Cuts.class.C.
References fClassName, GetMvaValue__(), and IClassifierReader::IsStatusClean().
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
double ReadCuts::GetMvaValue__ (const std::vector< double > & inputValues) const private
Referenced by GetMvaValue().
size_t ReadCuts::GetNvar () const inline private
Definition at line 163 of file aback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 163 of file trackback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 165 of file vtxback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 174 of file pairback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 177 of file aback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 185 of file hback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 185 of file eback_Cuts.class.C.
References fNvars.
size_t ReadCuts::GetNvar () const inline private
Definition at line 205 of file aback_Cuts.class.C.
References fNvars.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 164 of file aback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 164 of file trackback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 166 of file vtxback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 175 of file pairback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 178 of file aback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 186 of file eback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 186 of file hback_Cuts.class.C.
References fType.
char ReadCuts::GetType (int ivar) const inline private
Definition at line 206 of file aback_Cuts.class.C.
References fType.
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
void ReadCuts::Initialize () private
Referenced by ReadCuts().
bool ReadCuts::IsNormalised () const inline private
Definition at line 168 of file trackback_Cuts.class.C.
References fIsNormalised.
bool ReadCuts::IsNormalised () const inline private
Definition at line 168 of file aback_Cuts.class.C.
References fIsNormalised.
bool ReadCuts::IsNormalised () const inline private
Definition at line 170 of file vtxback_Cuts.class.C.
References fIsNormalised.
bool ReadCuts::IsNormalised () const inline private
Definition at line 179 of file pairback_Cuts.class.C.
References fIsNormalised.
bool ReadCuts::IsNormalised () const inline private
Definition at line 190 of file eback_Cuts.class.C.
References fIsNormalised.
bool ReadCuts::IsNormalised () const inline private
Definition at line 190 of file hback_Cuts.class.C.
References fIsNormalised.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 171 of file aback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 171 of file trackback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 173 of file vtxback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 182 of file pairback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 183 of file aback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 193 of file eback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 193 of file hback_Cuts.class.C.
double ReadCuts::NormVariable (double x, double xmin, double xmax) const inline private
Definition at line 211 of file aback_Cuts.class.C.
Member Data Documentation
const char * ReadCuts::fClassName private
Definition at line 202 of file aback_Cuts.class.C.
Referenced by GetMvaValue(), and ReadCuts().
const bool ReadCuts::fIsNormalised private
Definition at line 167 of file aback_Cuts.class.C.
Referenced by IsNormalised().
const size_t ReadCuts::fNvars private
Definition at line 204 of file aback_Cuts.class.C.
Referenced by GetNvar(), and ReadCuts().
char ReadCuts::fType private
Definition at line 217 of file aback_Cuts.class.C.
Referenced by GetType(), and ReadCuts().
double ReadCuts::fVmax private
Definition at line 210 of file aback_Cuts.class.C.
Referenced by ReadCuts().
double ReadCuts::fVmin private
Definition at line 209 of file aback_Cuts.class.C.
Referenced by ReadCuts().
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/Training/default/weights/aback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/training/default/weights/aback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/aback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/eback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/pairback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/trackback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/vtxback_Cuts.class.C