Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_fun4all/G4_FGEM_fsPHENIX.C File Reference
G4_FGEM_fsPHENIX.C File Reference
Functions
void FGEM_Init ()
void FGEMSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.45)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8)
void FGEM_FastSim_Reco (int verbosity=0)
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
Definition at line 175 of file G4_FGEM_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::AddLayer(), assert, d, PHG4SectorSubsystem::get_geometry(), s, and PHG4Sector::Sector_Geometry::Unit_cm().
void FGEM_FastSim_Reco (int verbosity = 0)
Definition at line 253 of file G4_FGEM_fsPHENIX.C.
References E, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_do_evt_display(), PHG4TrackFastSim::set_fit_alg_name(), PHG4TrackFastSim::set_pat_rec_hit_finding_eff(), PHG4TrackFastSim::set_primary_assumption_pid(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), PHG4TrackFastSim::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.
void FGEM_Init ()
Definition at line 14 of file G4_FGEM_fsPHENIX.C.
void FGEMSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.45)
Definition at line 20 of file G4_FGEM_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), make_GEM_station(), name, overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), and PHG4Sector::Sector_Geometry::Unit_cm().
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8)
Definition at line 204 of file G4_FGEM_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, and PHG4Sector::Sector_Geometry::Unit_cm().