Analysis Software: PHG4CylinderDisplayAction Class Reference
PHG4CylinderDisplayAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h>
Public Member Functions
PHG4CylinderDisplayAction (const std::string &name, PHParameters *parameters)
virtual ~PHG4CylinderDisplayAction ()
void ApplyDisplayAction (G4VPhysicalVolume *physvol)
ApplyDisplayAction method.
void SetMyVolume (G4LogicalVolume *vol)
void SetColor (const double red, const double green, const double blue, const double alpha=1.)
Public Member Functions inherited from PHG4DisplayAction
PHG4DisplayAction ()=delete
constructor
PHG4DisplayAction (const std::string &name)
virtual ~PHG4DisplayAction ()
destructor
virtual void SetName (const std::string &name)
virtual std::string GetName () const
virtual void Print (const std::string &what="ALL")
Private Attributes
PHParameters * m_Params
G4LogicalVolume * m_MyVolume
G4VisAttributes * m_VisAtt
G4Colour * m_Colour
Additional Inherited Members
Public Types inherited from PHG4DisplayAction
enum CheckReturnCodes { ABORT = -1, FAILED = 0, ACCEPT = 1 }
Protected Member Functions inherited from PHG4DisplayAction
int FindVolumes (G4VPhysicalVolume *physvol)
find FindVolume method
virtual int CheckVolume (G4VPhysicalVolume *physvol)
find CheckVolume method
virtual void ApplyVisAttributes (G4VPhysicalVolume *physvol)
ApplyVisAttributes method.
Detailed Description
Definition at line 16 of file PHG4CylinderDisplayAction.h.
Constructor & Destructor Documentation
PHG4CylinderDisplayAction::PHG4CylinderDisplayAction (const std::string & name, PHParameters * parameters)
Definition at line 18 of file PHG4CylinderDisplayAction.cc.
PHG4CylinderDisplayAction::~PHG4CylinderDisplayAction () virtual
Definition at line 27 of file PHG4CylinderDisplayAction.cc.
References m_Colour, and m_VisAtt.
Member Function Documentation
void PHG4CylinderDisplayAction::ApplyDisplayAction (G4VPhysicalVolume * physvol) virtual
ApplyDisplayAction method.
pure virtual - has to be implemented by derived class creates and set VisAttributes for volumes
Parameters
[in] physvol starting volume in hierarchy (typically world volume)
Implements PHG4DisplayAction.
Definition at line 33 of file PHG4CylinderDisplayAction.cc.
References PHParameters::get_int_param(), PHParameters::get_string_param(), m_Colour, m_MyVolume, m_Params, m_VisAtt, and PHG4Utils::SetColour().
void PHG4CylinderDisplayAction::SetColor (const double red, const double green, const double blue, const double alpha = 1.)
Definition at line 67 of file PHG4CylinderDisplayAction.cc.
References m_Colour.
Referenced by PHG4CylinderSubsystem::InitRunSubsystem().
void PHG4CylinderDisplayAction::SetMyVolume (G4LogicalVolume * vol) inline
Definition at line 24 of file PHG4CylinderDisplayAction.h.
References m_MyVolume.
Referenced by PHG4CylinderDetector::ConstructMe().
Member Data Documentation
G4Colour* PHG4CylinderDisplayAction::m_Colour private
Definition at line 31 of file PHG4CylinderDisplayAction.h.
Referenced by ApplyDisplayAction(), SetColor(), and ~PHG4CylinderDisplayAction().
G4LogicalVolume* PHG4CylinderDisplayAction::m_MyVolume private
Definition at line 29 of file PHG4CylinderDisplayAction.h.
Referenced by ApplyDisplayAction(), and SetMyVolume().
PHParameters* PHG4CylinderDisplayAction::m_Params private
Definition at line 28 of file PHG4CylinderDisplayAction.h.
Referenced by ApplyDisplayAction().
G4VisAttributes* PHG4CylinderDisplayAction::m_VisAtt private
Definition at line 30 of file PHG4CylinderDisplayAction.h.
Referenced by ApplyDisplayAction(), and ~PHG4CylinderDisplayAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.cc