Analysis Software: PHG4Prototype2InnerHcalSteppingAction Class Reference
PHG4Prototype2InnerHcalSteppingAction Class Reference
#include <prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4Prototype2InnerHcalSteppingAction.h>
Public Member Functions
PHG4Prototype2InnerHcalSteppingAction (PHG4Prototype2InnerHcalDetector *, const PHParameters *parameters)
constructor
virtual ~PHG4Prototype2InnerHcalSteppingAction ()
dtor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
double GetLightCorrection (const double r) const
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4Prototype2InnerHcalDetector * m_Detector
pointer to the detector
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4HitContainer * m_AbsorberHitContainer
PHG4Hit * m_Hit
const PHParameters * m_Params
PHG4HitContainer * m_SaveHitContainer
PHG4Shower * m_SaveShower
int m_AbsorberTruthFlag
int m_IsActiveFlag
int m_IsBlackHoleFlag
int m_LightScintModelFlag
double m_LightBalanceInnerCorr
double m_LightBalanceInnerRadius
double m_LightBalanceOuterCorr
double m_LightBalanceOuterRadius
Detailed Description
Definition at line 16 of file PHG4Prototype2InnerHcalSteppingAction.h.
Constructor & Destructor Documentation
PHG4Prototype2InnerHcalSteppingAction::PHG4Prototype2InnerHcalSteppingAction (PHG4Prototype2InnerHcalDetector * detector, const PHParameters * parameters)
constructor
Definition at line 46 of file PHG4Prototype2InnerHcalSteppingAction.cc.
PHG4Prototype2InnerHcalSteppingAction::~PHG4Prototype2InnerHcalSteppingAction () virtual
dtor
Definition at line 66 of file PHG4Prototype2InnerHcalSteppingAction.cc.
References m_Hit.
Member Function Documentation
double PHG4Prototype2InnerHcalSteppingAction::GetLightCorrection (const double r) const virtual
Reimplemented from PHG4SteppingAction.
Definition at line 347 of file PHG4Prototype2InnerHcalSteppingAction.cc.
References m_LightBalanceInnerCorr, m_LightBalanceInnerRadius, m_LightBalanceOuterCorr, m_LightBalanceOuterRadius, and value.
Referenced by UserSteppingAction().
void PHG4Prototype2InnerHcalSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 313 of file PHG4Prototype2InnerHcalSteppingAction.cc.
References PHG4Detector::GetName(), m_AbsorberHitContainer, m_Detector, m_HitContainer, PHG4Prototype2InnerHcalDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4Prototype2InnerHcalSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 76 of file PHG4Prototype2InnerHcalSteppingAction.cc.
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4Prototype2InnerHcalDetector::get_Layer(), PHG4Hit::get_light_yield(), PHG4Prototype2InnerHcalDetector::get_scinti_row_id(), PHG4Prototype2InnerHcalDetector::get_steel_plate_id(), PHG4HitContainer::GetID(), GetLightCorrection(), PHG4SteppingAction::GetVisibleEnergyDeposition(), PHG4Prototype2InnerHcalDetector::IsInPrototype2InnerHcal(), m_AbsorberHitContainer, m_AbsorberTruthFlag, m_Detector, m_Hit, m_HitContainer, m_IsActiveFlag, m_IsBlackHoleFlag, m_LightBalanceInnerCorr, m_LightBalanceInnerRadius, m_LightBalanceOuterCorr, m_LightBalanceOuterRadius, m_LightScintModelFlag, m_SaveHitContainer, m_SaveShower, r, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_hit_type(), PHG4Hit::set_light_yield(), PHG4Hit::set_row(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4Prototype2InnerHcalSteppingAction::m_AbsorberHitContainer private
Definition at line 39 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4Prototype2InnerHcalSteppingAction::m_AbsorberTruthFlag private
Definition at line 47 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Prototype2InnerHcalDetector* PHG4Prototype2InnerHcalSteppingAction::m_Detector private
pointer to the detector
Definition at line 35 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4Prototype2InnerHcalSteppingAction::m_Hit private
Definition at line 40 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4Prototype2InnerHcalSteppingAction().
PHG4HitContainer* PHG4Prototype2InnerHcalSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 38 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
int PHG4Prototype2InnerHcalSteppingAction::m_IsActiveFlag private
Definition at line 48 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
int PHG4Prototype2InnerHcalSteppingAction::m_IsBlackHoleFlag private
Definition at line 49 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
double PHG4Prototype2InnerHcalSteppingAction::m_LightBalanceInnerCorr private
Definition at line 52 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4Prototype2InnerHcalSteppingAction::m_LightBalanceInnerRadius private
Definition at line 53 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4Prototype2InnerHcalSteppingAction::m_LightBalanceOuterCorr private
Definition at line 54 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
double PHG4Prototype2InnerHcalSteppingAction::m_LightBalanceOuterRadius private
Definition at line 55 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by GetLightCorrection(), and UserSteppingAction().
int PHG4Prototype2InnerHcalSteppingAction::m_LightScintModelFlag private
Definition at line 50 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
const PHParameters* PHG4Prototype2InnerHcalSteppingAction::m_Params private
Definition at line 41 of file PHG4Prototype2InnerHcalSteppingAction.h.
PHG4HitContainer* PHG4Prototype2InnerHcalSteppingAction::m_SaveHitContainer private
Definition at line 42 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
PHG4Shower* PHG4Prototype2InnerHcalSteppingAction::m_SaveShower private
Definition at line 43 of file PHG4Prototype2InnerHcalSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4Prototype2InnerHcalSteppingAction.h
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4Prototype2InnerHcalSteppingAction.cc