Analysis Software: SVReco Class Reference
SVReco Class Reference
Find secondary vertex from track pairs and refit SvtxTracks with PHGenFit.
#include <analysis/blob/master/PhotonConversion/truthconversion/SVReco.h>
Public Member Functions
SVReco (const std::string &name="SVReco")
default ctor with hardcoded settings
~SVReco ()
dtor
int InitEvent (PHCompositeNode *)
Initialization, called for initialization at each event.
int InitRun (PHCompositeNode *)
Initialization Run, called for initialization of a run.
genfit::GFRaveVertex * findSecondaryVertex (SvtxTrack *track1, SvtxTrack *track2)
SvtxVertex * GFRVVtxToSvtxVertex (genfit::GFRaveVertex *rave_vtx) const
PHGenFit::Track * refitTrack (SvtxVertex *vtx, SvtxTrack *svtxtrk)
PHGenFit::Track * refitTrack (genfit::GFRaveVertex *vtx, SvtxTrack *svtxtrk)
PHGenFit::Track * getPHGFTrack (SvtxTrack *svtxtrk)
void reset_eval_variables ()
void set_do_eval (bool doEval)
void set_use_ladder_geom (bool useLadderGeom)
changes how genfit tracks are calculated and vtx fit
void set_do_evt_display (bool doEvtDisplay)
void set_reverse_mag_field (bool reverseMagField)
void set_mag_field_re_scaling_factor (float magFieldReScalingFactor)
void set_vertexing_method (const std::string &vertexingMethod)
string name for the rave hueristic
void set_mag_field_file_name (const std::string &magFieldFileName)
const std::string & get_track_fitting_alg_name () const
void set_track_fitting_alg_name (const std::string &trackFittingAlgName)
void set_primary_pid_guess (int primaryPidGuess)
used for building the tracks
void set_cut_min_pT (double cutMinPT)
void set_cut_dca (double cutDCA)
void set_cut_chi2ndf (double cutChi2Ndf)
void set_cut_ncluster (bool cutNcluster)
void set_n_maps_layer (unsigned int n)
void set_n_intt_layer (unsigned int n)
Private Member Functions
int GetNodes (PHCompositeNode *)
Get all the nodes.
int CreateNodes (PHCompositeNode *)
Create New nodes.
PHGenFit::Track * MakeGenFitTrack (const SvtxTrack *intrack)
Uses the tracking clusters exclusively to make a GFTrack.
PHGenFit::Track * MakeGenFitTrack (const SvtxTrack *intrack, const SvtxVertex *invertex)
Uses the tracking clusters and a vertex to fit/refit the track.
PHGenFit::Track * MakeGenFitTrack (const SvtxTrack *intrack, const genfit::GFRaveVertex *invertex)
Uses the tracking clusters and a vertex to fit/refit the track.
std::shared_ptr< SvtxTrack > MakeSvtxTrack (const SvtxTrack *svtx_track, const PHGenFit::Track *phgf_track, const SvtxVertex *vertex)
Uses the vertex to remake the track.
void FillVertexMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const std::vector< genfit::Track * > &gf_tracks)
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
void printGenFitTrackKinematics (PHGenFit::Track *track)
void FillSVMap (const std::vector< genfit::GFRaveVertex * > &rave_vertices, const std::vector< genfit::Track * > &gf_tracks)
int GetSVMass_mom (const genfit::GFRaveVertex *rave_vtx, float &vtx_mass, float &vtx_px, float &vtx_py, float &vtx_pz, int &ntrk_good_pv)
Private Attributes
std::string _mag_field_file_name
std::vector< PHGenFit::Track * > _main_rf_phgf_tracks
created by InitEvent to associate genfit to Svtx
float _mag_field_re_scaling_factor
rescale mag field, modify the original mag field read in
bool _reverse_mag_field
Switch to reverse Magnetic field.
PHGenFit::Fitter * _fitter
std::string _track_fitting_alg_name
unsigned int _n_maps_layer
unsigned int _n_intt_layer
int _primary_pid_guess
bool _cut_Ncluster
double _cut_min_pT
double _cut_dca
double _cut_chi2_ndf
bool _use_ladder_geom
genfit::GFRaveVertexFactory * _vertex_finder
https://rave.hepforge.org/trac/wiki/RaveMethods
std::string _vertexing_method
TrkrClusterContainer * _clustermap
Input Node pointers.
SvtxTrackMap * _trackmap
SvtxVertexMap * _vertexmap
PHG4CylinderGeomContainer * _geom_container_intt
PHG4CylinderGeomContainer * _geom_container_maps
bool _do_eval
switch eval out
int _verbosity
float gf_prim_vtx [3]
float gf_prim_vtx_err [3]
int gf_prim_vtx_ntrk
float rv_prim_vtx [3]
float rv_prim_vtx_err [3]
int rv_prim_vtx_ntrk
int rv_sv_njets
int rv_sv_jet_id [10]
int rv_sv_jet_prop [10][2]
float rv_sv_jet_pT [10]
float rv_sv_jet_px [10]
float rv_sv_jet_py [10]
float rv_sv_jet_pz [10]
int rv_sv_pT00_nvtx [10]
float rv_sv_pT00_vtx_x [10][30]
float rv_sv_pT00_vtx_y [10][30]
float rv_sv_pT00_vtx_z [10][30]
float rv_sv_pT00_vtx_ex [10][30]
float rv_sv_pT00_vtx_ey [10][30]
float rv_sv_pT00_vtx_ez [10][30]
int rv_sv_pT00_vtx_ntrk [10][30]
int rv_sv_pT00_vtx_ntrk_good [10][30]
int rv_sv_pT00_vtx_ntrk_good_pv [10][30]
float rv_sv_pT00_vtx_mass [10][30]
float rv_sv_pT00_vtx_mass_corr [10][30]
float rv_sv_pT00_vtx_pT [10][30]
float rv_sv_pT00_vtx_jet_theta [10][30]
float rv_sv_pT00_vtx_chi2 [10][30]
float rv_sv_pT00_vtx_ndf [10][30]
int rv_sv_pT05_nvtx [10]
float rv_sv_pT05_vtx_x [10][30]
float rv_sv_pT05_vtx_y [10][30]
float rv_sv_pT05_vtx_z [10][30]
float rv_sv_pT05_vtx_ex [10][30]
float rv_sv_pT05_vtx_ey [10][30]
float rv_sv_pT05_vtx_ez [10][30]
int rv_sv_pT05_vtx_ntrk [10][30]
int rv_sv_pT05_vtx_ntrk_good [10][30]
int rv_sv_pT05_vtx_ntrk_good_pv [10][30]
float rv_sv_pT05_vtx_mass [10][30]
float rv_sv_pT05_vtx_mass_corr [10][30]
float rv_sv_pT05_vtx_pT [10][30]
float rv_sv_pT05_vtx_jet_theta [10][30]
float rv_sv_pT05_vtx_chi2 [10][30]
float rv_sv_pT05_vtx_ndf [10][30]
int rv_sv_pT10_nvtx [10]
float rv_sv_pT10_vtx_x [10][30]
float rv_sv_pT10_vtx_y [10][30]
float rv_sv_pT10_vtx_z [10][30]
float rv_sv_pT10_vtx_ex [10][30]
float rv_sv_pT10_vtx_ey [10][30]
float rv_sv_pT10_vtx_ez [10][30]
int rv_sv_pT10_vtx_ntrk [10][30]
int rv_sv_pT10_vtx_ntrk_good [10][30]
int rv_sv_pT10_vtx_ntrk_good_pv [10][30]
float rv_sv_pT10_vtx_mass [10][30]
float rv_sv_pT10_vtx_mass_corr [10][30]
float rv_sv_pT10_vtx_pT [10][30]
float rv_sv_pT10_vtx_jet_theta [10][30]
float rv_sv_pT10_vtx_chi2 [10][30]
float rv_sv_pT10_vtx_ndf [10][30]
int rv_sv_pT15_nvtx [10]
float rv_sv_pT15_vtx_x [10][30]
float rv_sv_pT15_vtx_y [10][30]
float rv_sv_pT15_vtx_z [10][30]
float rv_sv_pT15_vtx_ex [10][30]
float rv_sv_pT15_vtx_ey [10][30]
float rv_sv_pT15_vtx_ez [10][30]
int rv_sv_pT15_vtx_ntrk [10][30]
int rv_sv_pT15_vtx_ntrk_good [10][30]
int rv_sv_pT15_vtx_ntrk_good_pv [10][30]
float rv_sv_pT15_vtx_mass [10][30]
float rv_sv_pT15_vtx_mass_corr [10][30]
float rv_sv_pT15_vtx_pT [10][30]
float rv_sv_pT15_vtx_jet_theta [10][30]
float rv_sv_pT15_vtx_chi2 [10][30]
float rv_sv_pT15_vtx_ndf [10][30]
bool _do_evt_display
std::map< unsigned int,
unsigned int > _svtxtrk_gftrk_map
std::map< unsigned int, float > _svtxtrk_wt_map
std::map< unsigned int, float > _svtxtrk_pt_map
std::vector< unsigned int > _svtxtrk_id
Detailed Description
Find secondary vertex from track pairs and refit SvtxTracks with PHGenFit.
Definition at line 35 of file SVReco.h.
Constructor & Destructor Documentation
SVReco::SVReco (const std::string & name = "SVReco")
default ctor with hardcoded settings
Definition at line 92 of file SVReco.C.
SVReco::~SVReco ()
dtor
Definition at line 256 of file SVReco.C.
References _fitter, _main_rf_phgf_tracks, _vertex_finder, i, and PHWHERE.
Member Function Documentation
int SVReco::CreateNodes (PHCompositeNode * topNode) private
Create New nodes.
Definition at line 350 of file SVReco.C.
References Fun4AllReturnCodes::EVENT_OK.
Referenced by InitRun().
void SVReco::FillSVMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const std::vector< genfit::Track * > & gf_tracks) private
Definition at line 931 of file SVReco.C.
void SVReco::FillVertexMap (const std::vector< genfit::GFRaveVertex * > & rave_vertices, const std::vector< genfit::Track * > & gf_tracks) private
Fill SvtxVertexMap from GFRaveVertexes and Tracks.
Definition at line 820 of file SVReco.C.
References _svtxtrk_wt_map, and rv_prim_vtx_ntrk.
genfit::GFRaveVertex * SVReco::findSecondaryVertex (SvtxTrack * track1, SvtxTrack * track2)
Returns
a vertex for each track pair
Definition at line 210 of file SVReco.C.
References _main_rf_phgf_tracks, _svtxtrk_gftrk_map, _vertex_finder, SvtxTrack::get_id(), PHGenFit::Track::getGenFitTrack(), and PHWHERE.
Referenced by Conversion::getSecondaryVertex(), VtxTest::numUnique(), RecoConversionEval::process_event(), VtxTest::process_event(), VtxTest::processBackground(), and TruthConversionEval::processTrackBackground().
const std::string& SVReco::get_track_fitting_alg_name () const inline
Definition at line 91 of file SVReco.h.
References _track_fitting_alg_name.
int SVReco::GetNodes (PHCompositeNode * topNode) private
Get all the nodes.
Definition at line 359 of file SVReco.C.
References _clustermap, _geom_container_intt, _geom_container_maps, _trackmap, _vertex_finder, _vertexmap, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by InitEvent().
PHGenFit::Track * SVReco::getPHGFTrack (SvtxTrack * svtxtrk)
Definition at line 177 of file SVReco.C.
References _main_rf_phgf_tracks, _svtxtrk_gftrk_map, and SvtxTrack::get_id().
Referenced by Conversion::getPHGFTracks().
int SVReco::GetSVMass_mom (const genfit::GFRaveVertex * rave_vtx, float & vtx_mass, float & vtx_px, float & vtx_py, float & vtx_pz, int & ntrk_good_pv) private
Definition at line 883 of file SVReco.C.
References _svtxtrk_wt_map.
SvtxVertex * SVReco::GFRVVtxToSvtxVertex (genfit::GFRaveVertex * rave_vtx) const
Returns
a new SvtxVertex from the rave_vtx ownership is returned
Definition at line 792 of file SVReco.C.
References _main_rf_phgf_tracks, i, SvtxVertex::insert_track(), j, SvtxVertex::set_chisq(), SvtxVertex::set_error(), SvtxVertex::set_ndof(), and SvtxVertex::set_position().
int SVReco::InitEvent (PHCompositeNode * topNode)
Initialization, called for initialization at each event.
stands for Refit_GenFit_Tracks
Definition at line 119 of file SVReco.C.
References _cut_chi2_ndf, _cut_dca, _cut_min_pT, _cut_Ncluster, _main_rf_phgf_tracks, _n_intt_layer, _n_maps_layer, _svtxtrk_gftrk_map, _svtxtrk_id, _svtxtrk_wt_map, _trackmap, SvtxTrackMap::begin(), SvtxTrack::begin_cluster_keys(), SvtxTrackMap::end(), SvtxTrack::end_cluster_keys(), Fun4AllReturnCodes::EVENT_OK, SvtxTrack::get_chisq(), SvtxTrack::get_dca3d_xy(), SvtxTrack::get_dca3d_z(), SvtxTrack::get_id(), SvtxTrack::get_ndf(), SvtxTrack::get_pt(), TrkrDefs::getLayer(), GetNodes(), and MakeGenFitTrack().
Referenced by RecoConversionEval::doNodePointers(), VtxTest::process_event(), and TruthConversionEval::process_event().
int SVReco::InitRun (PHCompositeNode * topNode)
Initialization Run, called for initialization of a run.
Definition at line 183 of file SVReco.C.
References _do_evt_display, _fitter, _track_fitting_alg_name, _verbosity, _vertex_finder, _vertexing_method, Fun4AllReturnCodes::ABORTRUN, CreateNodes(), Fun4AllReturnCodes::EVENT_OK, PHFieldUtility::GetFieldMapNode(), PHGenFit::Fitter::getInstance(), PHGeomUtility::GetTGeoManager(), and PHWHERE.
Referenced by RecoConversionEval::InitRun(), VtxTest::InitRun(), and TruthConversionEval::InitRun().
PHGenFit::Track * SVReco::MakeGenFitTrack (const SvtxTrack * intrack) private
Uses the tracking clusters exclusively to make a GFTrack.
Returns
ownership.
Definition at line 405 of file SVReco.C.
References _clustermap, _fitter, _geom_container_intt, _geom_container_maps, _primary_pid_guess, _use_ladder_geom, _verbosity, PHGenFit::Track::addMeasurements(), SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), CylinderGeomIntt::find_segment_center(), CylinderGeom_Mvtx::find_sensor_center(), TrkrClusterContainer::findCluster(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), CylinderGeom_Mvtx::get_stave_phi_tilt(), CylinderGeomIntt::get_strip_phi_tilt(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), MvtxDefs::getChipId(), PHGenFit::Track::getGenFitTrack(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), TrkrCluster::getPhiError(), TrkrCluster::getPosition(), MvtxDefs::getStaveId(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), i, TrkrDefs::inttId, j, LogError, LogWarning, TrkrDefs::mvtxId, n, PHWHERE, pos, PHGenFit::Fitter::processTrack(), x, and y.
Referenced by InitEvent(), and refitTrack().
PHGenFit::Track * SVReco::MakeGenFitTrack (const SvtxTrack * intrack, const SvtxVertex * invertex) private
Uses the tracking clusters and a vertex to fit/refit the track.
Returns
ownership.
Definition at line 489 of file SVReco.C.
References _clustermap, _fitter, _geom_container_intt, _geom_container_maps, _primary_pid_guess, _use_ladder_geom, _verbosity, PHGenFit::Track::addMeasurements(), SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), CylinderGeomIntt::find_segment_center(), CylinderGeom_Mvtx::find_sensor_center(), TrkrClusterContainer::findCluster(), SvtxVertex::get_error(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), CylinderGeom_Mvtx::get_stave_phi_tilt(), CylinderGeomIntt::get_strip_phi_tilt(), SvtxVertex::get_x(), SvtxTrack::get_x(), SvtxVertex::get_y(), SvtxTrack::get_y(), SvtxVertex::get_z(), SvtxTrack::get_z(), MvtxDefs::getChipId(), PHGenFit::Track::getGenFitTrack(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), TrkrCluster::getPhiError(), TrkrCluster::getPosition(), MvtxDefs::getStaveId(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), i, TrkrDefs::inttId, j, LogError, LogWarning, TrkrDefs::mvtxId, n, PHWHERE, pos, PHGenFit::Fitter::processTrack(), SvtxVertex::size_tracks(), x, and y.
PHGenFit::Track * SVReco::MakeGenFitTrack (const SvtxTrack * intrack, const genfit::GFRaveVertex * invertex) private
Uses the tracking clusters and a vertex to fit/refit the track.
Returns
ownership.
Definition at line 598 of file SVReco.C.
References _clustermap, _fitter, _geom_container_intt, _geom_container_maps, _primary_pid_guess, _use_ladder_geom, _verbosity, PHGenFit::Track::addMeasurements(), SvtxTrack::begin_cluster_keys(), SvtxTrack::end_cluster_keys(), CylinderGeomIntt::find_segment_center(), CylinderGeom_Mvtx::find_sensor_center(), TrkrClusterContainer::findCluster(), SvtxTrack::get_error(), SvtxTrack::get_id(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), CylinderGeom_Mvtx::get_stave_phi_tilt(), CylinderGeomIntt::get_strip_phi_tilt(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), MvtxDefs::getChipId(), PHGenFit::Track::getGenFitTrack(), InttDefs::getLadderPhiId(), InttDefs::getLadderZId(), TrkrDefs::getLayer(), PHG4CylinderGeomContainer::GetLayerGeom(), TrkrCluster::getPhiError(), TrkrCluster::getPosition(), MvtxDefs::getStaveId(), TrkrDefs::getTrkrId(), TrkrCluster::getZError(), i, TrkrDefs::inttId, j, LogError, LogWarning, TrkrDefs::mvtxId, n, PHWHERE, pos, PHGenFit::Fitter::processTrack(), x, and y.
std::shared_ptr< SvtxTrack > SVReco::MakeSvtxTrack (const SvtxTrack * svtx_track, const PHGenFit::Track * phgf_track, const SvtxVertex * vertex) private
Uses the vertex to remake the track.
From PHG4TrackKalmanFitter
1/p, u'/z', v'/z', u, v u is defined as momentum X beam line at POCA of the beam line v is alone the beam line so u is the dca2d direction
dca3d_xy, dca3d_z
Definition at line 982 of file SVReco.C.
References _verbosity, PHGenFit::Track::extrapolateToLine(), PHGenFit::Track::extrapolateToPoint(), PHGenFit::Track::get_charge(), PHGenFit::Track::get_chi2(), SvtxVertex::get_error(), PHGenFit::Track::get_ndf(), SvtxVertex::get_x(), SvtxVertex::get_y(), SvtxVertex::get_z(), PHGenFit::Track::getGenFitTrack(), i, j, LogWarning, PHWHERE, pos, SvtxTrack_v1::set_dca2d(), and v.
void SVReco::printGenFitTrackKinematics (PHGenFit::Track * track) private
Definition at line 277 of file SVReco.C.
References _verbosity, PHGenFit::Track::extrapolateToPoint(), and LogWarning.
PHGenFit::Track * SVReco::refitTrack (SvtxVertex * vtx, SvtxTrack * svtxtrk)
Definition at line 938 of file SVReco.C.
References MakeGenFitTrack().
Referenced by RecoConversionEval::refitTracks(), Conversion::refitTracks(), and Conversion::refitTracksTruthVtx().
PHGenFit::Track * SVReco::refitTrack (genfit::GFRaveVertex * vtx, SvtxTrack * svtxtrk)
Definition at line 951 of file SVReco.C.
References MakeGenFitTrack().
void SVReco::reset_eval_variables ()
Definition at line 298 of file SVReco.C.
References gf_prim_vtx, gf_prim_vtx_err, gf_prim_vtx_ntrk, i, rv_prim_vtx, rv_prim_vtx_err, rv_prim_vtx_ntrk, rv_sv_jet_id, rv_sv_jet_prop, rv_sv_jet_pT, rv_sv_jet_px, rv_sv_jet_py, rv_sv_jet_pz, rv_sv_njets, rv_sv_pT00_nvtx, rv_sv_pT00_vtx_chi2, rv_sv_pT00_vtx_ex, rv_sv_pT00_vtx_ey, rv_sv_pT00_vtx_ez, rv_sv_pT00_vtx_jet_theta, rv_sv_pT00_vtx_mass, rv_sv_pT00_vtx_mass_corr, rv_sv_pT00_vtx_ndf, rv_sv_pT00_vtx_ntrk, rv_sv_pT00_vtx_ntrk_good, rv_sv_pT00_vtx_ntrk_good_pv, rv_sv_pT00_vtx_pT, rv_sv_pT00_vtx_x, rv_sv_pT00_vtx_y, rv_sv_pT00_vtx_z, rv_sv_pT05_nvtx, rv_sv_pT05_vtx_chi2, rv_sv_pT05_vtx_ex, rv_sv_pT05_vtx_ey, rv_sv_pT05_vtx_ez, rv_sv_pT05_vtx_jet_theta, rv_sv_pT05_vtx_mass, rv_sv_pT05_vtx_mass_corr, rv_sv_pT05_vtx_ndf, rv_sv_pT05_vtx_ntrk, rv_sv_pT05_vtx_ntrk_good, rv_sv_pT05_vtx_ntrk_good_pv, rv_sv_pT05_vtx_pT, rv_sv_pT05_vtx_x, rv_sv_pT05_vtx_y, rv_sv_pT05_vtx_z, rv_sv_pT10_nvtx, rv_sv_pT10_vtx_chi2, rv_sv_pT10_vtx_ex, rv_sv_pT10_vtx_ey, rv_sv_pT10_vtx_ez, rv_sv_pT10_vtx_jet_theta, rv_sv_pT10_vtx_mass, rv_sv_pT10_vtx_mass_corr, rv_sv_pT10_vtx_ndf, rv_sv_pT10_vtx_ntrk, rv_sv_pT10_vtx_ntrk_good, rv_sv_pT10_vtx_ntrk_good_pv, rv_sv_pT10_vtx_pT, rv_sv_pT10_vtx_x, rv_sv_pT10_vtx_y, rv_sv_pT10_vtx_z, rv_sv_pT15_nvtx, rv_sv_pT15_vtx_chi2, rv_sv_pT15_vtx_ex, rv_sv_pT15_vtx_ey, rv_sv_pT15_vtx_ez, rv_sv_pT15_vtx_jet_theta, rv_sv_pT15_vtx_mass, rv_sv_pT15_vtx_mass_corr, rv_sv_pT15_vtx_ndf, rv_sv_pT15_vtx_ntrk, rv_sv_pT15_vtx_ntrk_good, rv_sv_pT15_vtx_ntrk_good_pv, rv_sv_pT15_vtx_pT, rv_sv_pT15_vtx_x, rv_sv_pT15_vtx_y, and rv_sv_pT15_vtx_z.
void SVReco::set_cut_chi2ndf (double cutChi2Ndf) inline
Definition at line 111 of file SVReco.h.
References _cut_chi2_ndf.
void SVReco::set_cut_dca (double cutDCA) inline
Definition at line 107 of file SVReco.h.
References _cut_dca.
void SVReco::set_cut_min_pT (double cutMinPT) inline
Definition at line 103 of file SVReco.h.
References _cut_min_pT.
void SVReco::set_cut_ncluster (bool cutNcluster) inline
Definition at line 115 of file SVReco.h.
References _cut_Ncluster.
void SVReco::set_do_eval (bool doEval) inline
Definition at line 63 of file SVReco.h.
References _do_eval.
void SVReco::set_do_evt_display (bool doEvtDisplay) inline
Definition at line 71 of file SVReco.h.
References _do_evt_display.
void SVReco::set_mag_field_file_name (const std::string & magFieldFileName) inline
Definition at line 87 of file SVReco.h.
References _mag_field_file_name.
void SVReco::set_mag_field_re_scaling_factor (float magFieldReScalingFactor) inline
Definition at line 79 of file SVReco.h.
References _mag_field_re_scaling_factor.
void SVReco::set_n_intt_layer (unsigned int n) inline
Definition at line 123 of file SVReco.h.
References _n_intt_layer, and n.
void SVReco::set_n_maps_layer (unsigned int n) inline
Definition at line 119 of file SVReco.h.
References _n_maps_layer, and n.
void SVReco::set_primary_pid_guess (int primaryPidGuess) inline
used for building the tracks
Definition at line 99 of file SVReco.h.
References _primary_pid_guess.
void SVReco::set_reverse_mag_field (bool reverseMagField) inline
Definition at line 75 of file SVReco.h.
References _reverse_mag_field.
void SVReco::set_track_fitting_alg_name (const std::string & trackFittingAlgName) inline
Definition at line 95 of file SVReco.h.
References _track_fitting_alg_name.
void SVReco::set_use_ladder_geom (bool useLadderGeom) inline
changes how genfit tracks are calculated and vtx fit
Definition at line 67 of file SVReco.h.
References _use_ladder_geom.
void SVReco::set_vertexing_method (const std::string & vertexingMethod) inline
string name for the rave hueristic
Definition at line 83 of file SVReco.h.
References _vertexing_method.
Member Data Documentation
TrkrClusterContainer* SVReco::_clustermap private
Input Node pointers.
Definition at line 196 of file SVReco.h.
Referenced by GetNodes(), and MakeGenFitTrack().
double SVReco::_cut_chi2_ndf private
Definition at line 187 of file SVReco.h.
Referenced by InitEvent(), and set_cut_chi2ndf().
double SVReco::_cut_dca private
Definition at line 186 of file SVReco.h.
Referenced by InitEvent(), and set_cut_dca().
double SVReco::_cut_min_pT private
Definition at line 185 of file SVReco.h.
Referenced by InitEvent(), and set_cut_min_pT().
bool SVReco::_cut_Ncluster private
Definition at line 184 of file SVReco.h.
Referenced by InitEvent(), and set_cut_ncluster().
bool SVReco::_do_eval private
switch eval out
Definition at line 203 of file SVReco.h.
Referenced by set_do_eval().
bool SVReco::_do_evt_display private
Definition at line 292 of file SVReco.h.
Referenced by InitRun(), and set_do_evt_display().
PHGenFit::Fitter* SVReco::_fitter private
Definition at line 177 of file SVReco.h.
Referenced by InitRun(), MakeGenFitTrack(), and ~SVReco().
PHG4CylinderGeomContainer* SVReco::_geom_container_intt private
Definition at line 199 of file SVReco.h.
Referenced by GetNodes(), and MakeGenFitTrack().
PHG4CylinderGeomContainer* SVReco::_geom_container_maps private
Definition at line 200 of file SVReco.h.
Referenced by GetNodes(), and MakeGenFitTrack().
std::string SVReco::_mag_field_file_name private
Definition at line 166 of file SVReco.h.
Referenced by set_mag_field_file_name().
float SVReco::_mag_field_re_scaling_factor private
rescale mag field, modify the original mag field read in
Definition at line 172 of file SVReco.h.
Referenced by set_mag_field_re_scaling_factor().
std::vector<PHGenFit::Track*> SVReco::_main_rf_phgf_tracks private
created by InitEvent to associate genfit to Svtx
Definition at line 169 of file SVReco.h.
Referenced by findSecondaryVertex(), getPHGFTrack(), GFRVVtxToSvtxVertex(), InitEvent(), and ~SVReco().
unsigned int SVReco::_n_intt_layer private
Definition at line 181 of file SVReco.h.
Referenced by InitEvent(), and set_n_intt_layer().
unsigned int SVReco::_n_maps_layer private
Definition at line 180 of file SVReco.h.
Referenced by InitEvent(), and set_n_maps_layer().
int SVReco::_primary_pid_guess private
Definition at line 183 of file SVReco.h.
Referenced by MakeGenFitTrack(), and set_primary_pid_guess().
bool SVReco::_reverse_mag_field private
Switch to reverse Magnetic field.
Definition at line 175 of file SVReco.h.
Referenced by set_reverse_mag_field().
std::map<unsigned int, unsigned int> SVReco::_svtxtrk_gftrk_map private
Definition at line 294 of file SVReco.h.
Referenced by findSecondaryVertex(), getPHGFTrack(), and InitEvent().
std::vector<unsigned int> SVReco::_svtxtrk_id private
Definition at line 297 of file SVReco.h.
Referenced by InitEvent().
std::map<unsigned int, float> SVReco::_svtxtrk_pt_map private
Definition at line 296 of file SVReco.h.
std::map<unsigned int, float> SVReco::_svtxtrk_wt_map private
Definition at line 295 of file SVReco.h.
Referenced by FillVertexMap(), GetSVMass_mom(), and InitEvent().
std::string SVReco::_track_fitting_alg_name private
Definition at line 178 of file SVReco.h.
Referenced by get_track_fitting_alg_name(), InitRun(), and set_track_fitting_alg_name().
SvtxTrackMap* SVReco::_trackmap private
Definition at line 197 of file SVReco.h.
Referenced by GetNodes(), and InitEvent().
bool SVReco::_use_ladder_geom private
Definition at line 189 of file SVReco.h.
Referenced by MakeGenFitTrack(), and set_use_ladder_geom().
int SVReco::_verbosity private
Definition at line 205 of file SVReco.h.
Referenced by InitRun(), MakeGenFitTrack(), MakeSvtxTrack(), and printGenFitTrackKinematics().
genfit::GFRaveVertexFactory* SVReco::_vertex_finder private
https://rave.hepforge.org/trac/wiki/RaveMethods
Definition at line 192 of file SVReco.h.
Referenced by findSecondaryVertex(), GetNodes(), InitRun(), and ~SVReco().
std::string SVReco::_vertexing_method private
Definition at line 193 of file SVReco.h.
Referenced by InitRun(), and set_vertexing_method().
SvtxVertexMap* SVReco::_vertexmap private
Definition at line 198 of file SVReco.h.
Referenced by GetNodes().
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/truthconversion/SVReco.h
analysis/blob/master/PhotonConversion/truthconversion/SVReco.C