Analysis Software: analysis/blob/master/Prototype2/EMCal/macros/DrawPrototype2ShowerCalib.C File Reference
DrawPrototype2ShowerCalib.C File Reference
#include <cmath>
#include <TFile.h>
#include <TString.h>
#include <TLine.h>
#include <TTree.h>
#include <TLatex.h>
#include <TGraphErrors.h>
#include <cassert>
#include "SaveCanvas.C"
#include "SetOKStyle.C"
Classes
class lin_res
Functions
void DrawPrototype2ShowerCalib (const TString infile="/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2017/sim/EMCalOnly_0Tilt_FlatLightCollection/Prototype_e-_ALL_SegA_ALL_EMCalCalib.root")
void PositionDependenceData (TString sTOWER="clus_5x5_prod.sum_E", const double z_shift=0, const int n_div=1)
void PositionDependenceSim (TString sTOWER="clus_5x5_prod.sum_E", const double z_shift=0, const int n_div=1)
void LineShapeData (TCut c2_h="abs(info.C2_sum)<100", TCut c2_e="(info.C2_sum)>500 && (info.C2_sum)<1300")
void LineShapeSim ()
void HodoscopeCheck ()
void SimPositionCheck (const double shift_z=0)
void Get_Res_linear_Summmary ()
void Get_Res_linear_Summmary_Sim ()
vector< double > GetBeamMom ()
lin_res GetResolution (TString cluster_name, vector< double > beam_mom, Color_t col)
TGraphErrors * FitProfile (const TH2 *h2)
Variables
TCut event_sel
TString cuts
TFile * _file0 = NULL
TTree * T = NULL
Function Documentation
void DrawPrototype2ShowerCalib (const TString infile = "/phenix/u/jinhuang/links/sPHENIX_work/Prototype_2017/sim/EMCalOnly_0Tilt_FlatLightCollection/Prototype_e-_ALL_SegA_ALL_EMCalCalib.root")
Definition at line 40 of file DrawPrototype2ShowerCalib.C.
References _file0, assert, cuts, event_sel, Get_Res_linear_Summmary_Sim(), n, PositionDependenceSim(), SetOKStyle(), T, and t.
TGraphErrors* FitProfile (const TH2 * h2)
Definition at line 971 of file DrawPrototype2ShowerCalib.C.
References f2(), h1, i, n, x, and y.
void Get_Res_linear_Summmary ()
Definition at line 608 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, lin_res::f_res, GetBeamMom(), GetResolution(), leg, lin_res::linearity, lin_res::name, lin_res::resolution, and SaveCanvas().
Referenced by DrawPrototype3ShowerCalib(), and DrawPrototype4ShowerCalib().
void Get_Res_linear_Summmary_Sim ()
Definition at line 733 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, lin_res::f_res, GetBeamMom(), GetResolution(), leg, lin_res::linearity, lin_res::name, lin_res::resolution, and SaveCanvas().
Referenced by DrawPrototype2ShowerCalib(), and DrawPrototype3ShowerCalib().
vector<double> GetBeamMom ()
Definition at line 835 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, SaveCanvas(), T, and t.
Referenced by Get_Res_linear_Summmary(), and Get_Res_linear_Summmary_Sim().
lin_res GetResolution (TString cluster_name, vector< double > beam_mom, Color_t col)
Definition at line 874 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, lin_res::f_res, SVM_v1::h, i, lin_res::linearity, lin_res::name, lin_res::resolution, SaveCanvas(), and T.
void HodoscopeCheck ()
Definition at line 523 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, SaveCanvas(), T, and t.
Referenced by DrawPrototype3ShowerCalib(), and DrawPrototype4ShowerCalib().
void LineShapeData (TCut c2_h = "abs(info.C2_sum)<100", TCut c2_e = "(info.C2_sum)>500 && (info.C2_sum)<1300")
Definition at line 408 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, SaveCanvas(), T, and t.
void LineShapeSim ()
Definition at line 495 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, SaveCanvas(), T, and t.
void PositionDependenceData (TString sTOWER = "clus_5x5_prod.sum_E", const double z_shift = 0, const int n_div = 1)
Definition at line 208 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, FitProfile(), SVM_v1::h, SaveCanvas(), T, and t.
Referenced by DrawPrototype3ShowerCalib(), and DrawPrototype4ShowerCalib().
void PositionDependenceSim (TString sTOWER = "clus_5x5_prod.sum_E", const double z_shift = 0, const int n_div = 1)
Definition at line 308 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, FitProfile(), SVM_v1::h, SaveCanvas(), T, and t.
Referenced by DrawPrototype2ShowerCalib().
void SimPositionCheck (const double shift_z = 0)
Definition at line 565 of file DrawPrototype2ShowerCalib.C.
References _file0, cuts, SaveCanvas(), T, and t.
Variable Documentation
TFile* _file0 = NULL
Definition at line 27 of file DrawPrototype2ShowerCalib.C.
TString cuts
Definition at line 26 of file DrawPrototype2ShowerCalib.C.
TCut event_sel
Definition at line 25 of file DrawPrototype2ShowerCalib.C.
Referenced by Draw_PHG4DSTReader(), DrawEcal_Likelihood(), DrawEcal_pDST(), DrawEMCalTower(), DrawPrototype2EMCalTower(), DrawPrototype2MIPAnalysis(), DrawPrototype2ShowerCalib(), DrawPrototype3EMCalTower(), DrawPrototype3ShowerCalib(), DrawPrototype4EMCalTower(), DrawPrototype4ShowerCalib(), and FillEnergy().
TTree* T = NULL
Definition at line 28 of file DrawPrototype2ShowerCalib.C.