Analysis Software: analysis/blob/master/Prototype2/hcalLab/fitter.C File Reference
fitter.C File Reference
#include "TCanvas.h"
#include "TH1.h"
#include "TF1.h"
#include "TRandom.h"
#include "TSpectrum.h"
#include "TVirtualFitter.h"
Functions
Double_t fpeaks (Double_t *x, Double_t *par)
void peaks (Int_t np=10)
Variables
Int_t npeaks = 30
Function Documentation
Double_t fpeaks (Double_t * x, Double_t * par)
Definition at line 9 of file fitter.C.
References norm, and npeaks.
Referenced by peaks().
void peaks (Int_t np = 10)
Definition at line 19 of file fitter.C.
References fit(), fpeaks(), SVM_v1::h, h2, npeaks, printf(), and s.
Referenced by sipmCalib(), and spmcalib().
Variable Documentation
Int_t npeaks = 30
Definition at line 8 of file fitter.C.
Referenced by fpeaks(), peaks(), sccalib(), sipmpeaks(), and spmcalib().