Analysis Software: GlobalVertexReco Class Reference
GlobalVertexReco Class Reference
simple truth vertex smearing algorithm
#include <coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexReco.h>
Public Member Functions
GlobalVertexReco (const std::string &name="GlobalVertexReco")
virtual ~GlobalVertexReco ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_x_defaults (float xdefault, float xerr)
void set_y_defaults (float ydefault, float yerr)
void set_t_defaults (float tdefault, float terr)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
Private Attributes
float _xdefault
float _xerr
float _ydefault
float _yerr
float _tdefault
float _terr
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
simple truth vertex smearing algorithm
Definition at line 23 of file GlobalVertexReco.h.
Constructor & Destructor Documentation
GlobalVertexReco::GlobalVertexReco (const std::string & name = "GlobalVertexReco")
Definition at line 34 of file GlobalVertexReco.cc.
GlobalVertexReco::~GlobalVertexReco () virtual
Definition at line 45 of file GlobalVertexReco.cc.
Member Function Documentation
int GlobalVertexReco::CreateNodes (PHCompositeNode * topNode) private
Definition at line 253 of file GlobalVertexReco.cc.
References Fun4AllReturnCodes::ABORTRUN, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), and PHWHERE.
Referenced by InitRun().
int GlobalVertexReco::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 248 of file GlobalVertexReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int GlobalVertexReco::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 47 of file GlobalVertexReco.cc.
References Fun4AllReturnCodes::EVENT_OK.
int GlobalVertexReco::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 52 of file GlobalVertexReco.cc.
References CreateNodes(), and Fun4AllBase::Verbosity().
int GlobalVertexReco::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 63 of file GlobalVertexReco.cc.
References _tdefault, _terr, _xdefault, _xerr, _ydefault, _yerr, GlobalVertex::BBC, SvtxVertexMap::begin(), SvtxVertexMap::end(), Fun4AllReturnCodes::EVENT_OK, SvtxVertex::get_chisq(), SvtxVertex::get_error(), BbcVertex::get_id(), SvtxVertex::get_id(), SvtxVertex::get_ndof(), SvtxVertex::get_position(), BbcVertex::get_t(), BbcVertex::get_t_err(), BbcVertex::get_z(), SvtxVertex::get_z(), BbcVertex::get_z_err(), i, GlobalVertex::identify(), GlobalVertexMap::insert(), GlobalVertex::insert_vtxids(), j, PHWHERE, GlobalVertex::set_chisq(), GlobalVertex::set_error(), GlobalVertex::set_ndof(), GlobalVertex::set_position(), GlobalVertex::set_t(), GlobalVertex::set_t_err(), GlobalVertex::set_x(), GlobalVertex::set_y(), GlobalVertex::set_z(), GlobalVertex::SVTX, and Fun4AllBase::Verbosity().
void GlobalVertexReco::set_t_defaults (float tdefault, float terr) inline
Definition at line 44 of file GlobalVertexReco.h.
References _tdefault, and _terr.
void GlobalVertexReco::set_x_defaults (float xdefault, float xerr) inline
Definition at line 34 of file GlobalVertexReco.h.
References _xdefault, and _xerr.
void GlobalVertexReco::set_y_defaults (float ydefault, float yerr) inline
Definition at line 39 of file GlobalVertexReco.h.
References _ydefault, and _yerr.
Member Data Documentation
float GlobalVertexReco::_tdefault private
Definition at line 55 of file GlobalVertexReco.h.
Referenced by process_event(), and set_t_defaults().
float GlobalVertexReco::_terr private
Definition at line 55 of file GlobalVertexReco.h.
Referenced by process_event(), and set_t_defaults().
float GlobalVertexReco::_xdefault private
Definition at line 53 of file GlobalVertexReco.h.
Referenced by process_event(), and set_x_defaults().
float GlobalVertexReco::_xerr private
Definition at line 53 of file GlobalVertexReco.h.
Referenced by process_event(), and set_x_defaults().
float GlobalVertexReco::_ydefault private
Definition at line 54 of file GlobalVertexReco.h.
Referenced by process_event(), and set_y_defaults().
float GlobalVertexReco::_yerr private
Definition at line 54 of file GlobalVertexReco.h.
Referenced by process_event(), and set_y_defaults().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexReco.h
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexReco.cc