Analysis Software: PHG4EventActionClearZeroEdep Class Reference
PHG4EventActionClearZeroEdep Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4EventActionClearZeroEdep.h>
Public Member Functions
PHG4EventActionClearZeroEdep (PHCompositeNode *topNode, const std::string &name)
constructor
void AddNode (const std::string &name)
virtual ~PHG4EventActionClearZeroEdep ()
destuctor
void EndOfEventAction (const G4Event *)
Public Member Functions inherited from PHG4EventAction
PHG4EventAction (void)
virtual ~PHG4EventAction ()
virtual void BeginOfEventAction (const G4Event *)
virtual void SetInterfacePointers (PHCompositeNode *)
get relevant nodes from top node passed as argument
virtual int ResetEvent (PHCompositeNode *)
Private Attributes
std::set< std::string > nodename_set
PHCompositeNode * topNode
Detailed Description
Definition at line 14 of file PHG4EventActionClearZeroEdep.h.
Constructor & Destructor Documentation
PHG4EventActionClearZeroEdep::PHG4EventActionClearZeroEdep (PHCompositeNode * topNode, const std::string & name)
constructor
Definition at line 11 of file PHG4EventActionClearZeroEdep.cc.
References AddNode().
virtual PHG4EventActionClearZeroEdep::~PHG4EventActionClearZeroEdep () inline virtual
destuctor
Definition at line 25 of file PHG4EventActionClearZeroEdep.h.
Member Function Documentation
void PHG4EventActionClearZeroEdep::AddNode (const std::string & name)
Definition at line 19 of file PHG4EventActionClearZeroEdep.cc.
References nodename_set.
Referenced by PHG4mRICHSubsystem::InitRunSubsystem(), and PHG4EventActionClearZeroEdep().
void PHG4EventActionClearZeroEdep::EndOfEventAction (const G4Event * evt) virtual
Reimplemented from PHG4EventAction.
Definition at line 25 of file PHG4EventActionClearZeroEdep.cc.
References nodename_set, PHG4HitContainer::RemoveZeroEDep(), and topNode.
Member Data Documentation
std::set<std::string> PHG4EventActionClearZeroEdep::nodename_set private
Definition at line 32 of file PHG4EventActionClearZeroEdep.h.
Referenced by AddNode(), and EndOfEventAction().
PHCompositeNode* PHG4EventActionClearZeroEdep::topNode private
Definition at line 33 of file PHG4EventActionClearZeroEdep.h.
Referenced by EndOfEventAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4EventActionClearZeroEdep.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4EventActionClearZeroEdep.cc