Analysis Software: PHPythia8 Class Reference
PHPythia8 Class Reference
#include <coresoftware/blob/master/generators/PHPythia8/PHPythia8.h>
Public Member Functions
PHPythia8 (const std::string &name="PHPythia8")
virtual ~PHPythia8 ()
int Init (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int ResetEvent (PHCompositeNode *topNode)
Clean up after each event.
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_config_file (const char *cfg_file)
void print_config () const
void register_trigger (PHPy8GenTrigger *theTrigger)
set event selection criteria
void set_trigger_OR ()
void set_trigger_AND ()
void process_string (std::string s)
pass commands directly to PYTHIA8
void beam_vertex_parameters (double beamX, double beamY, double beamZ, double beamXsigma, double beamYsigma, double beamZsigma)
void set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t)
toss a new vertex according to a Uniform or Gaus distribution
void set_vertex_distribution_mean (const double x, const double y, const double z, const double t)
set the mean value of the vertex distribution, use PHENIX units of cm, ns
void set_vertex_distribution_width (const double x, const double y, const double z, const double t)
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
void set_reuse_vertex (int src_embedding_id)
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
int get_embedding_id () const
void set_embedding_id (int id)
void save_integrated_luminosity (const bool b)
whether to store the integrated luminosity and other event statistics to the TOP/RUN/PHGenIntegral node
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int InitRun (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
int read_config (const char *cfg_file=0)
int create_node_tree (PHCompositeNode *topNode)
double percent_diff (const double a, const double b)
Private Attributes
int _eventcount
std::vector< PHPy8GenTrigger * > _registeredTriggers
bool _triggersOR
bool _triggersAND
Pythia8::Pythia * _pythia
std::string _configFile
std::vector< std::string > _commands
HepMC::Pythia8ToHepMC * _pythiaToHepMC
PHHepMCGenHelper hepmc_helper
helper for insert HepMC event to DST node and add vertex smearing
bool _save_integrated_luminosity
whether to store the integrated luminosity and other event statistics to the TOP/RUN/PHGenIntegral node
PHGenIntegral * _integral_node
pointer to data node saving the integrated luminosity
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 26 of file PHPythia8.h.
Constructor & Destructor Documentation
PHPythia8::PHPythia8 (const std::string & name = "PHPythia8")
Definition at line 40 of file PHPythia8.cc.
References _pythia, _pythiaToHepMC, hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
PHPythia8::~PHPythia8 () virtual
Definition at line 72 of file PHPythia8.cc.
References _pythia, and _pythiaToHepMC.
Member Function Documentation
void PHPythia8::beam_vertex_parameters (double beamX, double beamY, double beamZ, double beamXsigma, double beamYsigma, double beamZsigma) inline
Definition at line 59 of file PHPythia8.h.
References set_vertex_distribution_mean(), and set_vertex_distribution_width().
Referenced by Fun4All_G4_sPHENIX().
int PHPythia8::create_node_tree (PHCompositeNode * topNode) private
Definition at line 273 of file PHPythia8.cc.
References _integral_node, Fun4AllReturnCodes::ABORTRUN, assert, PHHepMCGenHelper::create_node_tree(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHHepMCGenHelper::get_embedding_id(), hepmc_helper, PHObject::identify(), and PHWHERE.
Referenced by Init().
int PHPythia8::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 120 of file PHPythia8.cc.
References _eventcount, _integral_node, _pythia, Fun4AllReturnCodes::EVENT_OK, PHObject::identify(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
int PHPythia8::get_embedding_id () const inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 98 of file PHPythia8.h.
References PHHepMCGenHelper::get_embedding_id(), and hepmc_helper.
int PHPythia8::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 78 of file PHPythia8.cc.
References _commands, _configFile, _eventcount, _pythia, create_node_tree(), Fun4AllReturnCodes::EVENT_OK, j, PHWHERE, read_config(), and TauVsDIS_MachineLearning_Differentiation::seed.
double PHPythia8::percent_diff (const double a, const double b) inline private
Definition at line 111 of file PHPythia8.h.
void PHPythia8::print_config () const
Definition at line 173 of file PHPythia8.cc.
References _pythia.
Referenced by Fun4All_G4_sPHENIX().
int PHPythia8::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 178 of file PHPythia8.cc.
References _eventcount, _integral_node, _pythia, _pythiaToHepMC, _registeredTriggers, _triggersAND, _triggersOR, Fun4AllReturnCodes::ABORTRUN, Fun4AllReturnCodes::EVENT_OK, genevent(), hepmc_helper, PHHepMCGenHelper::insert_event(), PHGenIntegral::set_Integrated_Lumi(), PHGenIntegral::set_N_Generator_Accepted_Event(), PHGenIntegral::set_N_Processed_Event(), PHGenIntegral::set_Sum_Of_Weight(), Fun4AllBase::Verbosity(), Fun4AllBase::VERBOSITY_A_LOT, Fun4AllBase::VERBOSITY_EVEN_MORE, Fun4AllBase::VERBOSITY_MORE, and Fun4AllBase::VERBOSITY_SOME.
void PHPythia8::process_string (std::string s) inline
pass commands directly to PYTHIA8
Definition at line 58 of file PHPythia8.h.
References _commands.
int PHPythia8::read_config (const char * cfg_file = 0) private
Definition at line 153 of file PHPythia8.cc.
References _configFile, _pythia, Fun4AllReturnCodes::EVENT_OK, Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_SOME.
Referenced by Init().
void PHPythia8::register_trigger (PHPy8GenTrigger * theTrigger)
set event selection criteria
Definition at line 314 of file PHPythia8.cc.
References _registeredTriggers, PHPy8GenTrigger::GetName(), Fun4AllBase::Verbosity(), and Fun4AllBase::VERBOSITY_MORE.
Referenced by Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_single_particle(), and generate_hepmc_bjet().
int PHPythia8::ResetEvent (PHCompositeNode *) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 309 of file PHPythia8.cc.
References Fun4AllReturnCodes::EVENT_OK.
void PHPythia8::save_integrated_luminosity (const bool b) inline
whether to store the integrated luminosity and other event statistics to the TOP/RUN/PHGenIntegral node
Definition at line 106 of file PHPythia8.h.
References _save_integrated_luminosity.
void PHPythia8::set_config_file (const char * cfg_file) inline
Definition at line 37 of file PHPythia8.h.
References _configFile.
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_EICAnalysis_DVCS(), Fun4All_G4_EICDetector(), Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), Fun4All_G4_fsPHENIX_pi0(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_AnaGenFit(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), Fun4All_G4_sPHENIX_truthphotonjet(), Fun4All_Generator_Display(), Fun4All_MCEventGen(), Fun4All_single_particle(), generate_hepmc_bjet(), and Jin_BJet().
void PHPythia8::set_embedding_id (int id) inline
embedding ID for the event positive ID is the embedded event of interest, e.g. jetty event from pythia negative IDs are backgrounds, .e.g out of time pile up collisions Usually, ID = 0 means the primary Au+Au collision background
Definition at line 104 of file PHPythia8.h.
References hepmc_helper, and PHHepMCGenHelper::set_embedding_id().
void PHPythia8::set_reuse_vertex (int src_embedding_id) inline
reuse vertex from another PHHepMCGenEvent with embedding_id = src_embedding_id Additional smearing and shift possible with set_vertex_distribution_*()
Definition at line 89 of file PHPythia8.h.
References hepmc_helper, and PHHepMCGenHelper::set_reuse_vertex().
Referenced by Fun4All_AnaTutorial(), Fun4All_AnaTutorial_Jets(), Fun4All_G4_sPHENIX(), Fun4All_G4_sPHENIX_photonjet(), Fun4All_G4_sPHENIX_photons(), and Fun4All_G4_sPHENIX_truthphotonjet().
void PHPythia8::set_trigger_AND () inline
Definition at line 51 of file PHPythia8.h.
References _triggersAND, and _triggersOR.
void PHPythia8::set_trigger_OR () inline
Definition at line 46 of file PHPythia8.h.
References _triggersAND, and _triggersOR.
void PHPythia8::set_vertex_distribution_function (PHHepMCGenHelper::VTXFUNC x, PHHepMCGenHelper::VTXFUNC y, PHHepMCGenHelper::VTXFUNC z, PHHepMCGenHelper::VTXFUNC t) inline
toss a new vertex according to a Uniform or Gaus distribution
Definition at line 71 of file PHPythia8.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_function().
void PHPythia8::set_vertex_distribution_mean (const double x, const double y, const double z, const double t) inline
set the mean value of the vertex distribution, use PHENIX units of cm, ns
Definition at line 77 of file PHPythia8.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_mean().
Referenced by beam_vertex_parameters().
void PHPythia8::set_vertex_distribution_width (const double x, const double y, const double z, const double t) inline
set the width of the vertex distribution function about the mean, use PHENIX units of cm, ns
Definition at line 83 of file PHPythia8.h.
References hepmc_helper, and PHHepMCGenHelper::set_vertex_distribution_width().
Referenced by beam_vertex_parameters().
Member Data Documentation
std::vector<std::string> PHPythia8::_commands private
Definition at line 123 of file PHPythia8.h.
Referenced by Init(), and process_string().
std::string PHPythia8::_configFile private
Definition at line 122 of file PHPythia8.h.
Referenced by Init(), read_config(), and set_config_file().
int PHPythia8::_eventcount private
Definition at line 112 of file PHPythia8.h.
Referenced by End(), Init(), and process_event().
PHGenIntegral* PHPythia8::_integral_node private
pointer to data node saving the integrated luminosity
Definition at line 135 of file PHPythia8.h.
Referenced by create_node_tree(), End(), and process_event().
Pythia8::Pythia* PHPythia8::_pythia private
Definition at line 120 of file PHPythia8.h.
Referenced by End(), Init(), PHPythia8(), print_config(), process_event(), read_config(), and ~PHPythia8().
HepMC::Pythia8ToHepMC* PHPythia8::_pythiaToHepMC private
Definition at line 126 of file PHPythia8.h.
Referenced by PHPythia8(), process_event(), and ~PHPythia8().
std::vector<PHPy8GenTrigger *> PHPythia8::_registeredTriggers private
Definition at line 115 of file PHPythia8.h.
Referenced by process_event(), and register_trigger().
bool PHPythia8::_save_integrated_luminosity private
whether to store the integrated luminosity and other event statistics to the TOP/RUN/PHGenIntegral node
Definition at line 132 of file PHPythia8.h.
Referenced by save_integrated_luminosity().
bool PHPythia8::_triggersAND private
Definition at line 117 of file PHPythia8.h.
Referenced by process_event(), set_trigger_AND(), and set_trigger_OR().
bool PHPythia8::_triggersOR private
Definition at line 116 of file PHPythia8.h.
Referenced by process_event(), set_trigger_AND(), and set_trigger_OR().
PHHepMCGenHelper PHPythia8::hepmc_helper private
helper for insert HepMC event to DST node and add vertex smearing
Definition at line 129 of file PHPythia8.h.
Referenced by create_node_tree(), get_embedding_id(), PHPythia8(), process_event(), set_embedding_id(), set_reuse_vertex(), set_vertex_distribution_function(), set_vertex_distribution_mean(), and set_vertex_distribution_width().
The documentation for this class was generated from the following files:
coresoftware/blob/master/generators/PHPythia8/PHPythia8.h
coresoftware/blob/master/generators/PHPythia8/PHPythia8.cc