Analysis Software: CellularAutomaton_v1 Class Reference
CellularAutomaton_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/CellularAutomaton_v1.h>
Public Member Functions
CellularAutomaton_v1 (std::vector< SimpleTrack3D > &input_tracks, std::vector< float > &radius, std::vector< float > &material)
virtual ~CellularAutomaton_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
int isValid () const
CellularAutomaton * Clone () const
void set_hough_space (HelixHoughSpace *hough_space)
void set_mag_field (float mag_field)
void set_pt_rescale (float pt_rescale)
void set_n_layers (unsigned int n_layers)
void set_required_layers (unsigned int req_layers)
void set_ca_chi2 (float chi2_cut)
void set_ca_chi2_layer (float chi2_layer_cut)
void set_ca_phi_cut (float phi_cut)
void set_ca_z_cut (float z_cut)
void set_ca_dcaxy_cut (float dcaxy_cut)
void set_propagate_forward (bool fwd)
void set_remove_hits (bool remove)
void set_remove_inner_hits (bool remove_inner)
void set_require_inner_hits (bool require_inner)
void set_triplet_mode (bool mod)
void set_seeding_mode (bool mod)
void set_hits_map (std::map< unsigned int, SimpleHit3D > &hits_map)
void set_verbose (int v)
int run (std::vector< SimpleTrack3D > &output_tracks, std::vector< HelixKalmanState > &output_track_states, std::map< unsigned int, bool > &hits_used)
Public Member Functions inherited from CellularAutomaton
virtual ~CellularAutomaton ()
Private Member Functions
void set_detector_radii (std::vector< float > &radii)
void set_detector_materials (std::vector< float > &materials)
void set_input_tracks (std::vector< SimpleTrack3D > &input_tracks)
void set_cylinder_kalman ()
int init ()
int process_tracks ()
int process_single_track (SimpleTrack3D &track)
int process_single_triplet (SimpleTrack3D &track)
int get_ca_tracks (std::vector< SimpleTrack3D > &output_tracks, std::vector< HelixKalmanState > &output_track_states)
int calculate_kappa_tangents (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float dx1, float dy1, float dz1, float dx2, float dy2, float dz2, float dx3, float dy3, float dz3, float &kappa, float &dkappa, float &ux_mid, float &uy_mid, float &ux_end, float &uy_end, float &dzdl_1, float &dzdl_2, float &ddzdl_1, float &ddzdl_2)
int calculate_kappa_tangents (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float dx1, float dy1, float dz1, float dx2, float dy2, float dz2, float dx3, float dy3, float dz3, float &kappa, float &dkappa, float &ux_mid, float &uy_mid, float &ux_end, float &uy_end, float &dzdl_1, float &dzdl_2, float &ddzdl_1, float &ddzdl_2, float ca_sin_ang_cut, float inv_cos_ang_diff, float cur_kappa, float cur_dkappa, float cur_ux, float cur_uy, float cur_chi2, float &chi2)
float kappa_to_pt (float kappa)
float shift_phi_range (float phi)
Private Attributes
HelixHoughSpace * _hough_space
HelixKalmanFilter * _kalman
std::vector< SimpleTrack3D > in_tracks
std::vector< SimpleTrack3D > ca_tracks
std::vector< HelixKalmanState > ca_track_states
std::vector< unsigned int > temp_combo
std::set< std::vector
< unsigned int > > combos
std::vector< std::vector
< SimpleHit3D > > layer_sorted
unsigned int nlayers
unsigned int rlayers
unsigned int allowed_missing_inner_hits
float ca_cos_ang_cut
float ca_chi2_cut
float ca_chi2_layer_cut
float ca_phi_cut
float ca_z_cut
float ca_dcaxy_cut
float fast_chi2_cut_max
float fast_chi2_cut_par0
float fast_chi2_cut_par1
float _pt_rescale
float _mag_field
std::vector< float > _detector_radii
std::vector< float > _detector_scatter
std::vector< float > _detector_materials
std::vector< float > _integrated_scatter
std::map< unsigned int, bool > _hits_used
std::map< unsigned int,
SimpleHit3D > _hits_map
double CAtime
double KALtime
bool forward
bool remove_hits
bool remove_inner_hits
bool require_inner_hits
bool triplet_mode
bool seeding_mode
int verbose
Additional Inherited Members
Protected Member Functions inherited from CellularAutomaton
CellularAutomaton ()
Detailed Description
Definition at line 40 of file CellularAutomaton_v1.h.
Constructor & Destructor Documentation
CellularAutomaton_v1::CellularAutomaton_v1 (std::vector< SimpleTrack3D > & input_tracks, std::vector< float > & radius, std::vector< float > & material)
Definition at line 32 of file CellularAutomaton_v1.cc.
References set_detector_materials(), set_detector_radii(), and set_input_tracks().
Referenced by Clone().
virtual CellularAutomaton_v1::~CellularAutomaton_v1 () inline virtual
Definition at line 46 of file CellularAutomaton_v1.h.
Member Function Documentation
int CellularAutomaton_v1::calculate_kappa_tangents (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float dx1, float dy1, float dz1, float dx2, float dy2, float dz2, float dx3, float dy3, float dz3, float & kappa, float & dkappa, float & ux_mid, float & uy_mid, float & ux_end, float & uy_end, float & dzdl_1, float & dzdl_2, float & ddzdl_1, float & ddzdl_2) private virtual
Reimplemented from CellularAutomaton.
Definition at line 1539 of file CellularAutomaton_v1.cc.
References dz2, num, x2, z1, and z2.
Referenced by process_single_track(), and process_single_triplet().
int CellularAutomaton_v1::calculate_kappa_tangents (float x1, float y1, float z1, float x2, float y2, float z2, float x3, float y3, float z3, float dx1, float dy1, float dz1, float dx2, float dy2, float dz2, float dx3, float dy3, float dz3, float & kappa, float & dkappa, float & ux_mid, float & uy_mid, float & ux_end, float & uy_end, float & dzdl_1, float & dzdl_2, float & ddzdl_1, float & ddzdl_2, float ca_sin_ang_cut, float inv_cos_ang_diff, float cur_kappa, float cur_dkappa, float cur_ux, float cur_uy, float cur_chi2, float & chi2) private virtual
Reimplemented from CellularAutomaton.
Definition at line 1610 of file CellularAutomaton_v1.cc.
References dz2, num, x2, z1, and z2.
CellularAutomaton* CellularAutomaton_v1::Clone () const inline virtual
Reimplemented from CellularAutomaton.
Definition at line 52 of file CellularAutomaton_v1.h.
References CellularAutomaton_v1().
int CellularAutomaton_v1::get_ca_tracks (std::vector< SimpleTrack3D > & output_tracks, std::vector< HelixKalmanState > & output_track_states) private virtual
Reimplemented from CellularAutomaton.
Definition at line 244 of file CellularAutomaton_v1.cc.
References ca_track_states, ca_tracks, and i.
Referenced by run().
void CellularAutomaton_v1::identify (std::ostream & os = std::cout) const inline virtual
Reimplemented from CellularAutomaton.
Definition at line 49 of file CellularAutomaton_v1.h.
int CellularAutomaton_v1::init (void) private virtual
Reimplemented from CellularAutomaton.
Definition at line 145 of file CellularAutomaton_v1.cc.
References _detector_materials, _detector_radii, _hough_space, ca_track_states, ca_tracks, combos, layer_sorted, nlayers, PHWHERE, set_cylinder_kalman(), and temp_combo.
Referenced by run().
int CellularAutomaton_v1::isValid () const inline virtual
Reimplemented from CellularAutomaton.
Definition at line 51 of file CellularAutomaton_v1.h.
float CellularAutomaton_v1::kappa_to_pt (float kappa) private
Definition at line 1696 of file CellularAutomaton_v1.cc.
References _mag_field, and _pt_rescale.
Referenced by process_single_track().
int CellularAutomaton_v1::process_single_track (SimpleTrack3D & track) private virtual
Reimplemented from CellularAutomaton.
Definition at line 1026 of file CellularAutomaton_v1.cc.
References _hits_used, _kalman, HelixKalmanFilter::addHit(), HelixKalmanState::C, ca_chi2_cut, ca_chi2_layer_cut, ca_cos_ang_cut, ca_track_states, ca_tracks, calculate_kappa_tangents(), CAtime, HelixKalmanState::chi2, TrackSegment::chi2, combos, HelixKalmanState::d, SimpleTrack3D::d, TrackSegment::dkappa, double(), dz2, HelixKalmanState::dzdl, SimpleTrack3D::dzdl, fast_chi2_cut_max, fast_chi2_cut_par0, fast_chi2_cut_par1, SimpleTrack3D::fit_track(), forward, SimpleHit3D::get_layer(), SVM_v1::h, SimpleTrack3D::hits, TrackSegment::hits, i, it, j, k, KALtime, HelixKalmanState::kappa, SimpleTrack3D::kappa, TrackSegment::kappa, kappa_to_pt(), layer_sorted, M_PI, min, n, TrackSegment::n_hits, nfits(), nlayers, HelixKalmanState::nu, HelixKalmanState::phi, SimpleTrack3D::phi, HelixKalmanState::position, remove_hits, remove_inner_hits, require_inner_hits, rlayers, boost::swap(), t1, t2, temp_combo, TrackSegment::ux, TrackSegment::uy, verbose, x2, x3, HelixKalmanState::x_int, y3, HelixKalmanState::y_int, HelixKalmanState::z0, SimpleTrack3D::z0, z1, z2, and HelixKalmanState::z_int.
Referenced by process_tracks().
int CellularAutomaton_v1::process_single_triplet (SimpleTrack3D & track) private virtual
Reimplemented from CellularAutomaton.
Definition at line 297 of file CellularAutomaton_v1.cc.
References _hits_map, _hits_used, _hough_space, _kalman, HelixKalmanFilter::addHit(), allowed_missing_inner_hits, HelixKalmanState::C, ca_chi2_cut, ca_chi2_layer_cut, ca_cos_ang_cut, ca_phi_cut, ca_track_states, ca_tracks, ca_z_cut, calculate_kappa_tangents(), HelixKalmanState::chi2, TrackSegment::chi2, combos, HelixKalmanState::d, SimpleTrack3D::d, TrackSegment::dkappa, dz2, HelixKalmanState::dzdl, SimpleTrack3D::dzdl, SimpleTrack3D::fit_track(), forward, SimpleHit3D::get_id(), HelixHoughSpace::get_kappa_max(), SimpleHit3D::get_layer(), SimpleHit3D::get_size(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), SVM_v1::h, SimpleTrack3D::hits, TrackSegment::hits, i, it, j, k, HelixKalmanState::kappa, SimpleTrack3D::kappa, TrackSegment::kappa, layer_sorted, M_PI, min, n, TrackSegment::n_hits, nfits(), nlayers, HelixKalmanState::nu, HelixKalmanState::phi, SimpleTrack3D::phi, HelixKalmanState::position, remove_hits, remove_inner_hits, seeding_mode, shift_phi_range(), boost::swap(), temp_combo, TrackSegment::ux, TrackSegment::uy, verbose, x2, x3, HelixKalmanState::x_int, y3, HelixKalmanState::y_int, HelixKalmanState::z0, SimpleTrack3D::z0, z1, z2, and HelixKalmanState::z_int.
Referenced by process_tracks().
int CellularAutomaton_v1::process_tracks () private virtual
Reimplemented from CellularAutomaton.
Definition at line 262 of file CellularAutomaton_v1.cc.
References i, in_tracks, process_single_track(), process_single_triplet(), triplet_mode, and verbose.
Referenced by run().
void CellularAutomaton_v1::Reset () virtual
Reimplemented from CellularAutomaton.
Definition at line 78 of file CellularAutomaton_v1.cc.
References _detector_materials, _detector_radii, _detector_scatter, _hough_space, _integrated_scatter, _kalman, ca_track_states, ca_tracks, in_tracks, and temp_combo.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
int CellularAutomaton_v1::run (std::vector< SimpleTrack3D > & output_tracks, std::vector< HelixKalmanState > & output_track_states, std::map< unsigned int, bool > & hits_used) virtual
Reimplemented from CellularAutomaton.
Definition at line 96 of file CellularAutomaton_v1.cc.
References _hits_used, ca_track_states, ca_tracks, get_ca_tracks(), i, in_tracks, init(), layer_sorted, PHWHERE, process_tracks(), remove_hits, and verbose.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_ca_chi2 (float chi2_cut) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 59 of file CellularAutomaton_v1.h.
References ca_chi2_cut.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_ca_chi2_layer (float chi2_layer_cut) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 60 of file CellularAutomaton_v1.h.
References ca_chi2_layer_cut.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_ca_dcaxy_cut (float dcaxy_cut) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 63 of file CellularAutomaton_v1.h.
References ca_dcaxy_cut.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_ca_phi_cut (float phi_cut) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 61 of file CellularAutomaton_v1.h.
References ca_phi_cut.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_ca_z_cut (float z_cut) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 62 of file CellularAutomaton_v1.h.
References ca_z_cut.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_cylinder_kalman () private virtual
Reimplemented from CellularAutomaton.
Definition at line 225 of file CellularAutomaton_v1.cc.
References _detector_materials, _detector_radii, _kalman, and _mag_field.
Referenced by init().
void CellularAutomaton_v1::set_detector_materials (std::vector< float > & materials) private
Definition at line 209 of file CellularAutomaton_v1.cc.
References _detector_materials, _detector_scatter, _integrated_scatter, and i.
Referenced by CellularAutomaton_v1().
void CellularAutomaton_v1::set_detector_radii (std::vector< float > & radii) private virtual
Reimplemented from CellularAutomaton.
Definition at line 202 of file CellularAutomaton_v1.cc.
References _detector_radii, and i.
Referenced by CellularAutomaton_v1().
void CellularAutomaton_v1::set_hits_map (std::map< unsigned int, SimpleHit3D > & hits_map) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 70 of file CellularAutomaton_v1.h.
References _hits_map.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_hough_space (HelixHoughSpace * hough_space) virtual
Reimplemented from CellularAutomaton.
Definition at line 188 of file CellularAutomaton_v1.cc.
References _hough_space, assert, and HelixHoughSpace::CloneMe().
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_input_tracks (std::vector< SimpleTrack3D > & input_tracks) private virtual
Reimplemented from CellularAutomaton.
Definition at line 230 of file CellularAutomaton_v1.cc.
References in_tracks.
Referenced by CellularAutomaton_v1().
void CellularAutomaton_v1::set_mag_field (float mag_field) virtual
Reimplemented from CellularAutomaton.
Definition at line 194 of file CellularAutomaton_v1.cc.
References _mag_field.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_n_layers (unsigned int n_layers) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 57 of file CellularAutomaton_v1.h.
References nlayers.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_propagate_forward (bool fwd) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 64 of file CellularAutomaton_v1.h.
References forward.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_pt_rescale (float pt_rescale) virtual
Reimplemented from CellularAutomaton.
Definition at line 198 of file CellularAutomaton_v1.cc.
References _pt_rescale.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_remove_hits (bool remove) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 65 of file CellularAutomaton_v1.h.
References remove_hits.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_remove_inner_hits (bool remove_inner) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 66 of file CellularAutomaton_v1.h.
References remove_inner_hits.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_require_inner_hits (bool require_inner) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 67 of file CellularAutomaton_v1.h.
References require_inner_hits.
void CellularAutomaton_v1::set_required_layers (unsigned int req_layers) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 58 of file CellularAutomaton_v1.h.
References rlayers.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_seeding_mode (bool mod) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 69 of file CellularAutomaton_v1.h.
References seeding_mode.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_triplet_mode (bool mod) inline virtual
Reimplemented from CellularAutomaton.
Definition at line 68 of file CellularAutomaton_v1.h.
References triplet_mode.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init(), and PHPatternReco::cellular_automaton_zvtx_init().
void CellularAutomaton_v1::set_verbose (int v) inline
Definition at line 71 of file CellularAutomaton_v1.h.
References v, and verbose.
Referenced by PHInitZVertexing::cellular_automaton_zvtx_init().
float CellularAutomaton_v1::shift_phi_range (float phi) private virtual
Reimplemented from CellularAutomaton.
Definition at line 1700 of file CellularAutomaton_v1.cc.
References M_PI.
Referenced by process_single_triplet().
Member Data Documentation
std::vector<float> CellularAutomaton_v1::_detector_materials private
Definition at line 143 of file CellularAutomaton_v1.h.
Referenced by init(), Reset(), set_cylinder_kalman(), and set_detector_materials().
std::vector<float> CellularAutomaton_v1::_detector_radii private
Definition at line 141 of file CellularAutomaton_v1.h.
Referenced by init(), Reset(), set_cylinder_kalman(), and set_detector_radii().
std::vector<float> CellularAutomaton_v1::_detector_scatter private
Definition at line 142 of file CellularAutomaton_v1.h.
Referenced by Reset(), and set_detector_materials().
std::map<unsigned int, SimpleHit3D> CellularAutomaton_v1::_hits_map private
Definition at line 147 of file CellularAutomaton_v1.h.
Referenced by process_single_triplet(), and set_hits_map().
std::map<unsigned int, bool> CellularAutomaton_v1::_hits_used private
Definition at line 146 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), and run().
HelixHoughSpace* CellularAutomaton_v1::_hough_space private
Definition at line 112 of file CellularAutomaton_v1.h.
Referenced by init(), process_single_triplet(), Reset(), and set_hough_space().
std::vector<float> CellularAutomaton_v1::_integrated_scatter private
Definition at line 144 of file CellularAutomaton_v1.h.
Referenced by Reset(), and set_detector_materials().
HelixKalmanFilter* CellularAutomaton_v1::_kalman private
Definition at line 113 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), Reset(), and set_cylinder_kalman().
float CellularAutomaton_v1::_mag_field private
Definition at line 139 of file CellularAutomaton_v1.h.
Referenced by kappa_to_pt(), set_cylinder_kalman(), and set_mag_field().
float CellularAutomaton_v1::_pt_rescale private
Definition at line 138 of file CellularAutomaton_v1.h.
Referenced by kappa_to_pt(), and set_pt_rescale().
unsigned int CellularAutomaton_v1::allowed_missing_inner_hits private
Definition at line 124 of file CellularAutomaton_v1.h.
Referenced by process_single_triplet().
float CellularAutomaton_v1::ca_chi2_cut private
Definition at line 127 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), and set_ca_chi2().
float CellularAutomaton_v1::ca_chi2_layer_cut private
Definition at line 128 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), and set_ca_chi2_layer().
float CellularAutomaton_v1::ca_cos_ang_cut private
Definition at line 126 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), and process_single_triplet().
float CellularAutomaton_v1::ca_dcaxy_cut private
Definition at line 131 of file CellularAutomaton_v1.h.
Referenced by set_ca_dcaxy_cut().
float CellularAutomaton_v1::ca_phi_cut private
Definition at line 129 of file CellularAutomaton_v1.h.
Referenced by process_single_triplet(), and set_ca_phi_cut().
std::vector<HelixKalmanState> CellularAutomaton_v1::ca_track_states private
Definition at line 116 of file CellularAutomaton_v1.h.
Referenced by get_ca_tracks(), init(), process_single_track(), process_single_triplet(), Reset(), and run().
std::vector<SimpleTrack3D> CellularAutomaton_v1::ca_tracks private
Definition at line 115 of file CellularAutomaton_v1.h.
Referenced by get_ca_tracks(), init(), process_single_track(), process_single_triplet(), Reset(), and run().
float CellularAutomaton_v1::ca_z_cut private
Definition at line 130 of file CellularAutomaton_v1.h.
Referenced by process_single_triplet(), and set_ca_z_cut().
double CellularAutomaton_v1::CAtime private
Definition at line 149 of file CellularAutomaton_v1.h.
Referenced by process_single_track().
std::set<std::vector<unsigned int> > CellularAutomaton_v1::combos private
Definition at line 119 of file CellularAutomaton_v1.h.
Referenced by init(), process_single_track(), and process_single_triplet().
float CellularAutomaton_v1::fast_chi2_cut_max private
Definition at line 133 of file CellularAutomaton_v1.h.
Referenced by process_single_track().
float CellularAutomaton_v1::fast_chi2_cut_par0 private
Definition at line 134 of file CellularAutomaton_v1.h.
Referenced by process_single_track().
float CellularAutomaton_v1::fast_chi2_cut_par1 private
Definition at line 135 of file CellularAutomaton_v1.h.
Referenced by process_single_track().
bool CellularAutomaton_v1::forward private
Definition at line 151 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), and set_propagate_forward().
std::vector<SimpleTrack3D> CellularAutomaton_v1::in_tracks private
Definition at line 114 of file CellularAutomaton_v1.h.
Referenced by process_tracks(), Reset(), run(), and set_input_tracks().
double CellularAutomaton_v1::KALtime private
Definition at line 150 of file CellularAutomaton_v1.h.
Referenced by process_single_track().
std::vector<std::vector<SimpleHit3D> > CellularAutomaton_v1::layer_sorted private
Definition at line 120 of file CellularAutomaton_v1.h.
Referenced by init(), process_single_track(), process_single_triplet(), and run().
unsigned int CellularAutomaton_v1::nlayers private
Definition at line 122 of file CellularAutomaton_v1.h.
Referenced by init(), process_single_track(), process_single_triplet(), and set_n_layers().
bool CellularAutomaton_v1::remove_hits private
Definition at line 152 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), run(), and set_remove_hits().
bool CellularAutomaton_v1::remove_inner_hits private
Definition at line 153 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), and set_remove_inner_hits().
bool CellularAutomaton_v1::require_inner_hits private
Definition at line 154 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), and set_require_inner_hits().
unsigned int CellularAutomaton_v1::rlayers private
Definition at line 123 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), and set_required_layers().
bool CellularAutomaton_v1::seeding_mode private
Definition at line 156 of file CellularAutomaton_v1.h.
Referenced by process_single_triplet(), and set_seeding_mode().
std::vector<unsigned int> CellularAutomaton_v1::temp_combo private
Definition at line 118 of file CellularAutomaton_v1.h.
Referenced by init(), process_single_track(), process_single_triplet(), and Reset().
bool CellularAutomaton_v1::triplet_mode private
Definition at line 155 of file CellularAutomaton_v1.h.
Referenced by process_tracks(), and set_triplet_mode().
int CellularAutomaton_v1::verbose private
Definition at line 157 of file CellularAutomaton_v1.h.
Referenced by process_single_track(), process_single_triplet(), process_tracks(), run(), and set_verbose().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/CellularAutomaton_v1.h
coresoftware/blob/master/offline/packages/trackreco/CellularAutomaton_v1.cc