Analysis Software: analysis/blob/master/Test/W-Shashlik/Fun4All_G4_W.C File Reference
Fun4All_G4_W.C File Reference
Functions
int Fun4All_G4_W (const int nEvents=100, const double momentum=5, const char *outfile="test.root")
void G4Cmd (const char *cmd)
PHG4ParticleGun * get_gun (const char *name="PGUN")
Function Documentation
int Fun4All_G4_W (const int nEvents = 100, const double momentum = 5, const char * outfile = "test.root")
Definition at line 2 of file Fun4All_G4_W.C.
References PHG4SimpleEventGenerator::add_particles(), PHG4DSTReader::AddNode(), PHG4DetectorSubsystem::BlackHole(), cemc, PHG4ParticleGeneratorBase::Embed(), Fun4AllServer::End(), PHG4Reco::GetWorldSizeZ(), in, Fun4AllServer::instance(), QAG4SimulationCalorimeter::kProcessG4Hit, Max_cemc_layer, nEvents, no_overlapp, overlapcheck, PHG4DetectorSubsystem::OverlapCheck(), Fun4AllServer::registerInputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), QAHistManagerDef::saveQARootFile(), PHG4DetectorSubsystem::set_double_param(), PHG4SimpleEventGenerator::set_eta_range(), PHG4Reco::set_field(), PHG4Reco::set_field_rescale(), PHG4DetectorSubsystem::set_int_param(), PHG4DSTReader::set_load_active_particle(), PHG4DSTReader::set_load_all_particle(), PHG4SimpleEventGenerator::set_p_range(), PHG4SimpleEventGenerator::set_phi_range(), PHG4DSTReader::set_save_particle(), PHG4DSTReader::set_save_vertex(), PHG4DetectorSubsystem::set_string_param(), PHG4SimpleEventGenerator::set_vertex_distribution_function(), PHG4SimpleEventGenerator::set_vertex_distribution_mean(), PHG4SimpleEventGenerator::set_vertex_distribution_width(), PHG4SimpleEventGenerator::set_vertex_size_function(), PHG4SimpleEventGenerator::set_vertex_size_parameters(), PHG4DetectorSubsystem::SetActive(), PHG4Reco::SetPhysicsList(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), PHG4DetectorSubsystem::SuperDetector(), PHG4SimpleEventGenerator::Uniform, and Fun4AllBase::Verbosity().
void G4Cmd (const char * cmd)
Definition at line 282 of file Fun4All_G4_W.C.
References PHG4Reco::ApplyCommand(), g4, Fun4AllServer::getSubsysReco(), and Fun4AllServer::instance().
PHG4ParticleGun* get_gun (const char * name = "PGUN")
Definition at line 290 of file Fun4All_G4_W.C.
References Fun4AllServer::getSubsysReco(), Fun4AllServer::instance(), and name.