Analysis Software: PHRawOManager Class Reference
PHRawOManager Class Reference
#include <coresoftware/blob/master/offline/framework/phoolraw/PHRawOManager.h>
Public Member Functions
PHRawOManager ()
PHRawOManager (const std::string &, const int run=0, const int bufl=100000, const int evtl=-1, const int complvl=3)
virtual ~PHRawOManager ()
bool setFile (const std::string &, const int setRun, const int setBufl, const int setEvtl, const int complvl)
virtual void closeFile ()
virtual bool write (PHCompositeNode *)
bool write (PHRawDataNode *)
virtual void print () const
Public Member Functions inherited from PHIOManager
virtual ~PHIOManager ()
std::string getFilename () const
size_t getEventNumber () const
void setEventNumber (const size_t evno)
Private Attributes
int filedesc
PHDWORD * memBuffer
oBuffer * fileBuffer
int runNumber
int bufferSize
int eventLength
int compressionLevel
Additional Inherited Members
Protected Member Functions inherited from PHIOManager
PHIOManager ()
Protected Attributes inherited from PHIOManager
std::string filename
size_t eventNumber
Detailed Description
Definition at line 42 of file PHRawOManager.h.
Constructor & Destructor Documentation
PHRawOManager::PHRawOManager ()
Definition at line 45 of file PHRawOManager.cc.
PHRawOManager::PHRawOManager (const std::string & newFile, const int run = 0, const int bufl = 100000, const int evtl = -1, const int complvl = 3)
Definition at line 29 of file PHRawOManager.cc.
References compressionLevel, fileBuffer, filedesc, PHIOManager::filename, memBuffer, and setFile().
PHRawOManager::~PHRawOManager () virtual
Definition at line 56 of file PHRawOManager.cc.
References closeFile().
Member Function Documentation
void PHRawOManager::closeFile () virtual
Implements PHIOManager.
Definition at line 61 of file PHRawOManager.cc.
References fileBuffer, filedesc, and memBuffer.
Referenced by setFile(), and ~PHRawOManager().
void PHRawOManager::print () const virtual
Implements PHIOManager.
Definition at line 174 of file PHRawOManager.cc.
References bufferSize, eventLength, PHIOManager::eventNumber, PHIOManager::filename, and runNumber.
bool PHRawOManager::setFile (const std::string & setFile, const int setRun, const int setBufl, const int setEvtl, const int complvl)
Definition at line 80 of file PHRawOManager.cc.
References bufferSize, closeFile(), compressionLevel, eventLength, fileBuffer, filedesc, PHIOManager::filename, memBuffer, PHError, PHMessage(), PHWarning, and runNumber.
Referenced by PHRawOManager().
bool PHRawOManager::write (PHCompositeNode * topNode) virtual
Implements PHIOManager.
Definition at line 140 of file PHRawOManager.cc.
References DATAEVENT, eventLength, PHIOManager::eventNumber, fileBuffer, filedesc, oBuffer::nextEvent(), and PHCompositeNode::write().
Referenced by PHRawDataNode::write(), and Fun4AllPrdfOutputManager::Write().
bool PHRawOManager::write (PHRawDataNode * node)
Definition at line 158 of file PHRawOManager.cc.
References oBuffer::addUnstructPacketData(), fileBuffer, filedesc, PHDataNode< T >::getData(), PHRawDataNode::getHitFormat(), PHRawDataNode::getID(), PHRawDataNode::getLength(), PHRawDataNode::getWordLength(), PHError, and PHMessage().
Member Data Documentation
int PHRawOManager::bufferSize private
Definition at line 61 of file PHRawOManager.h.
Referenced by print(), and setFile().
int PHRawOManager::compressionLevel private
Definition at line 63 of file PHRawOManager.h.
Referenced by PHRawOManager(), and setFile().
int PHRawOManager::eventLength private
Definition at line 62 of file PHRawOManager.h.
Referenced by print(), setFile(), and write().
oBuffer* PHRawOManager::fileBuffer private
Definition at line 59 of file PHRawOManager.h.
Referenced by closeFile(), PHRawOManager(), setFile(), and write().
int PHRawOManager::filedesc private
Definition at line 57 of file PHRawOManager.h.
Referenced by closeFile(), PHRawOManager(), setFile(), and write().
PHDWORD* PHRawOManager::memBuffer private
Definition at line 58 of file PHRawOManager.h.
Referenced by closeFile(), PHRawOManager(), and setFile().
int PHRawOManager::runNumber private
Definition at line 60 of file PHRawOManager.h.
Referenced by print(), and setFile().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/phoolraw/PHRawOManager.h
coresoftware/blob/master/offline/framework/phoolraw/PHRawOManager.cc