Analysis Software: PHG4ScintillatorSlatContainer Class Reference
PHG4ScintillatorSlatContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.h>
Public Types
typedef std::map
< PHG4ScintillatorSlatDefs::keytype,
PHG4ScintillatorSlat * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
typedef std::set< int >
::const_iterator LayerIter
typedef std::pair< LayerIter,
LayerIter > LayerRange
Public Member Functions
PHG4ScintillatorSlatContainer ()
virtual ~PHG4ScintillatorSlatContainer ()
void Reset ()
Clear Event.
void identify (std::ostream &os=std::cout) const
ConstIterator AddScintillatorSlat (const PHG4ScintillatorSlatDefs::keytype key, PHG4ScintillatorSlat *newscintillatorSlat)
void RemoveScintillatorSlat (PHG4ScintillatorSlatDefs::keytype key)
preferred removal method, key is currently the slat id
void RemoveScintillatorSlat (PHG4ScintillatorSlat *slat)
inefficent, use key where possible instead
ConstRange getScintillatorSlats (const short icolumn) const
return all scintillatorSlats matching a given detid
ConstRange getScintillatorSlats (void) const
return all hist
PHG4ScintillatorSlat * findScintillatorSlat (PHG4ScintillatorSlatDefs::keytype key)
unsigned int size (void) const
double getTotalEdep () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
Map slatmap
Detailed Description
Definition at line 17 of file PHG4ScintillatorSlatContainer.h.
Member Typedef Documentation
typedef Map::const_iterator PHG4ScintillatorSlatContainer::ConstIterator
Definition at line 23 of file PHG4ScintillatorSlatContainer.h.
typedef std::pair<ConstIterator, ConstIterator> PHG4ScintillatorSlatContainer::ConstRange
Definition at line 25 of file PHG4ScintillatorSlatContainer.h.
typedef Map::iterator PHG4ScintillatorSlatContainer::Iterator
Definition at line 22 of file PHG4ScintillatorSlatContainer.h.
typedef std::set<int>::const_iterator PHG4ScintillatorSlatContainer::LayerIter
Definition at line 26 of file PHG4ScintillatorSlatContainer.h.
typedef std::pair<LayerIter, LayerIter> PHG4ScintillatorSlatContainer::LayerRange
Definition at line 27 of file PHG4ScintillatorSlatContainer.h.
typedef std::map<PHG4ScintillatorSlatDefs::keytype,PHG4ScintillatorSlat *> PHG4ScintillatorSlatContainer::Map
Definition at line 21 of file PHG4ScintillatorSlatContainer.h.
typedef std::pair<Iterator, Iterator> PHG4ScintillatorSlatContainer::Range
Definition at line 24 of file PHG4ScintillatorSlatContainer.h.
Constructor & Destructor Documentation
PHG4ScintillatorSlatContainer::PHG4ScintillatorSlatContainer ()
Definition at line 10 of file PHG4ScintillatorSlatContainer.cc.
virtual PHG4ScintillatorSlatContainer::~PHG4ScintillatorSlatContainer () inline virtual
Definition at line 31 of file PHG4ScintillatorSlatContainer.h.
Member Function Documentation
PHG4ScintillatorSlatContainer::ConstIterator PHG4ScintillatorSlatContainer::AddScintillatorSlat (const PHG4ScintillatorSlatDefs::keytype key, PHG4ScintillatorSlat * newscintillatorSlat)
Definition at line 39 of file PHG4ScintillatorSlatContainer.cc.
References PHG4ScintillatorSlat::set_key().
Referenced by PHG4Prototype2HcalCellReco::process_event().
PHG4ScintillatorSlat * PHG4ScintillatorSlatContainer::findScintillatorSlat (PHG4ScintillatorSlatDefs::keytype key)
Definition at line 77 of file PHG4ScintillatorSlatContainer.cc.
References it.
PHG4ScintillatorSlatContainer::ConstRange PHG4ScintillatorSlatContainer::getScintillatorSlats (const short icolumn) const
return all scintillatorSlats matching a given detid
Definition at line 53 of file PHG4ScintillatorSlatContainer.cc.
References PHG4ScintillatorSlatDefs::columnbits.
Referenced by Prototype2RawTowerBuilder::process_event(), HCalib::process_event(), and DumpPHG4ScintillatorSlatContainer::process_Node().
PHG4ScintillatorSlatContainer::ConstRange PHG4ScintillatorSlatContainer::getScintillatorSlats (void) const
return all hist
Definition at line 72 of file PHG4ScintillatorSlatContainer.cc.
double PHG4ScintillatorSlatContainer::getTotalEdep () const
Definition at line 90 of file PHG4ScintillatorSlatContainer.cc.
Referenced by Prototype2RawTowerBuilder::process_event().
void PHG4ScintillatorSlatContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 26 of file PHG4ScintillatorSlatContainer.cc.
void PHG4ScintillatorSlatContainer::RemoveScintillatorSlat (PHG4ScintillatorSlatDefs::keytype key) inline
preferred removal method, key is currently the slat id
Definition at line 40 of file PHG4ScintillatorSlatContainer.h.
References slatmap.
void PHG4ScintillatorSlatContainer::RemoveScintillatorSlat (PHG4ScintillatorSlat * slat) inline
inefficent, use key where possible instead
Definition at line 45 of file PHG4ScintillatorSlatContainer.h.
References slatmap.
void PHG4ScintillatorSlatContainer::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 15 of file PHG4ScintillatorSlatContainer.cc.
unsigned int PHG4ScintillatorSlatContainer::size (void) const inline
Definition at line 71 of file PHG4ScintillatorSlatContainer.h.
References slatmap.
Referenced by DumpPHG4ScintillatorSlatContainer::process_Node().
Member Data Documentation
Map PHG4ScintillatorSlatContainer::slatmap protected
Definition at line 77 of file PHG4ScintillatorSlatContainer.h.
Referenced by RemoveScintillatorSlat(), and size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.cc