Analysis Software: PHTFileServer Class Reference
PHTFileServer Class Reference
TFile clean handling. It allow independant classes to access the same TFile and write ntuple to it. TFiles get written only when as many write request are achieved as open request. It get closed when the server is deleted.
#include <coresoftware/blob/master/offline/framework/fun4all/PHTFileServer.h>
Classes
class SafeTFile
local class to store TFile and counter
Public Member Functions
virtual ~PHTFileServer ()
destructor. All non close TFiles are closed, with a warning.
void open (const std::string &filename, const std::string &type="RECREATE")
open a SafeTFile. If filename is not found in the map, create a new TFile and append to the map; increment counter otherwise
bool flush (const std::string &filename)
flush TFile matching filename
bool cd (const std::string &filename)
change to directory of TFile matching filename
bool write (const std::string &filename)
if TFile is found in map and counter is 0, close the TFile, decrement counter otherwise
void close (void)
close all TFiles
Static Public Member Functions
static PHTFileServer & get (void)
return reference to class singleton
Private Member Functions
PHTFileServer (void)
constructor
Detailed Description
TFile clean handling. It allow independant classes to access the same TFile and write ntuple to it. TFiles get written only when as many write request are achieved as open request. It get closed when the server is deleted.
Definition at line 28 of file PHTFileServer.h.
Constructor & Destructor Documentation
PHTFileServer::~PHTFileServer (void) virtual
destructor. All non close TFiles are closed, with a warning.
Definition at line 25 of file PHTFileServer.cc.
PHTFileServer::PHTFileServer (void) inline private
constructor
Definition at line 64 of file PHTFileServer.h.
Member Function Documentation
bool PHTFileServer::cd (const std::string & filename)
change to directory of TFile matching filename
Definition at line 76 of file PHTFileServer.cc.
Referenced by TPCIntegratedCharge::End(), PHAna::End(), AnaSvtxTracksForGenFit::End(), Proto4ShowerCalib::End(), TPCDataStreamEmulator::End(), Proto3ShowerCalib::End(), Proto2ShowerCalib::End(), FastTrackingEval::End(), PHG4TrackFastSimEval::End(), EpFinderEval::End(), TPCMLDataInterface::End(), Proto4SampleFrac::End(), Proto4TowerCalib::End(), Prototype2DSTReader::End(), EMCalLikelihood::End(), PHG4ScoringManager::End(), Prototype3DSTReader::End(), Prototype4DSTReader::End(), TPCFEETestRecov1::End(), MyJetAnalysis::End(), ExampleAnalysisModule::End(), PHG4DSTReader::End(), TpcPrototypeUnpacker::End(), TpcPrototypeGenFitTrkFinder::End(), EMCalAna::End(), EMCalCalib::End(), GenFitTrackProp::End(), AnaMvtxTestBeam2019::End(), PHGenFitTrkFitter::End(), TpcPrototypeGenFitTrkFitter::End(), EMCalCalib_TestBeam::End(), and Proto4ShowerCalib::process_event().
void PHTFileServer::close (void)
close all TFiles
Definition at line 133 of file PHTFileServer.cc.
Referenced by AnaMvtxTestBeam2019::End().
bool PHTFileServer::flush (const std::string & filename)
flush TFile matching filename
Definition at line 59 of file PHTFileServer.cc.
Referenced by compressevent(), converttohepmc(), dokinematics(), genevent(), init(), and Proto4ShowerCalib::process_event().
static PHTFileServer& PHTFileServer::get (void) inline static
return reference to class singleton
Definition at line 32 of file PHTFileServer.h.
Referenced by Prototype2DSTReader::build_tree(), Prototype3DSTReader::build_tree(), Prototype4DSTReader::build_tree(), PHG4DSTReader::build_tree(), TPCIntegratedCharge::End(), PHAna::End(), AnaSvtxTracksForGenFit::End(), Proto4ShowerCalib::End(), TPCDataStreamEmulator::End(), Proto3ShowerCalib::End(), Proto2ShowerCalib::End(), PHG4TrackFastSimEval::End(), FastTrackingEval::End(), EpFinderEval::End(), TPCMLDataInterface::End(), Proto4SampleFrac::End(), Proto4TowerCalib::End(), Prototype2DSTReader::End(), EMCalLikelihood::End(), PHG4ScoringManager::End(), Prototype3DSTReader::End(), Prototype4DSTReader::End(), TPCFEETestRecov1::End(), MyJetAnalysis::End(), ExampleAnalysisModule::End(), PHG4DSTReader::End(), TpcPrototypeUnpacker::End(), TpcPrototypeGenFitTrkFinder::End(), GenFitTrackProp::End(), AnaMvtxTestBeam2019::End(), EMCalCalib::End(), EMCalAna::End(), PHGenFitTrkFitter::End(), TpcPrototypeGenFitTrkFitter::End(), EMCalCalib_TestBeam::End(), PHAna::Init(), AnaSvtxTracksForGenFit::Init(), Proto4ShowerCalib::Init(), EpFinderEval::Init(), Proto3ShowerCalib::Init(), Proto2ShowerCalib::Init(), Proto4TowerCalib::Init(), FastTrackingEval::Init(), PHG4TrackFastSimEval::Init(), Proto4SampleFrac::Init(), ExampleAnalysisModule::Init(), EMCalLikelihood::Init(), MyJetAnalysis::Init(), GenFitTrackProp::Init(), EMCalAna::Init(), EMCalCalib::Init(), EMCalCalib_TestBeam::Init(), TPCIntegratedCharge::InitRun(), TPCDataStreamEmulator::InitRun(), PHG4ScoringManager::InitRun(), TPCMLDataInterface::InitRun(), TPCFEETestRecov1::InitRun(), TpcPrototypeGenFitTrkFinder::InitRun(), TpcPrototypeUnpacker::InitRun(), PHGenFitTrkFitter::InitRun(), TpcPrototypeGenFitTrkFitter::InitRun(), and Proto4ShowerCalib::process_event().
void PHTFileServer::open (const std::string & filename, const std::string & type = "RECREATE")
open a SafeTFile. If filename is not found in the map, create a new TFile and append to the map; increment counter otherwise
Definition at line 31 of file PHTFileServer.cc.
References file.
Referenced by Prototype2DSTReader::build_tree(), Prototype3DSTReader::build_tree(), Prototype4DSTReader::build_tree(), PHG4DSTReader::build_tree(), AnaMvtxTestBeam2019::End(), PHAna::Init(), AnaSvtxTracksForGenFit::Init(), Proto4ShowerCalib::Init(), Proto2ShowerCalib::Init(), Proto3ShowerCalib::Init(), EpFinderEval::Init(), Proto4SampleFrac::Init(), PHG4TrackFastSimEval::Init(), Proto4TowerCalib::Init(), FastTrackingEval::Init(), ExampleAnalysisModule::Init(), EMCalLikelihood::Init(), MyJetAnalysis::Init(), GenFitTrackProp::Init(), EMCalCalib::Init(), EMCalAna::Init(), EMCalCalib_TestBeam::Init(), TPCIntegratedCharge::InitRun(), TPCDataStreamEmulator::InitRun(), PHG4ScoringManager::InitRun(), TPCMLDataInterface::InitRun(), TPCFEETestRecov1::InitRun(), TpcPrototypeGenFitTrkFinder::InitRun(), TpcPrototypeUnpacker::InitRun(), PHGenFitTrkFitter::InitRun(), and TpcPrototypeGenFitTrkFitter::InitRun().
bool PHTFileServer::write (const std::string & filename)
if TFile is found in map and counter is 0, close the TFile, decrement counter otherwise
Definition at line 93 of file PHTFileServer.cc.
Referenced by AnaMvtxTestBeam2019::End().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/framework/fun4all/PHTFileServer.h
coresoftware/blob/master/offline/framework/fun4all/PHTFileServer.cc