var dir_f54f933ac0dce6e26514dda2d6324e6b =
[
    [ "calculate_g1.C", "d5/d82/calculate__g1_8C.html", "d5/d82/calculate__g1_8C" ],
    [ "calculate_g1_projection_per_bin.C", "d5/d9d/calculate__g1__projection__per__bin_8C.html", "d5/d9d/calculate__g1__projection__per__bin_8C" ],
    [ "create_pythia_dummy.C", "d5/de3/create__pythia__dummy_8C.html", "d5/de3/create__pythia__dummy_8C" ],
    [ "eic_sphenix.C", "da/da1/eic__sphenix_8C.html", "da/da1/eic__sphenix_8C" ],
    [ "eic_sphenix_fill_xq2.C", "d9/d6c/eic__sphenix__fill__xq2_8C.html", "d9/d6c/eic__sphenix__fill__xq2_8C" ],
    [ "eic_sphenix_geomacceptance.h", "d3/d62/eic__sphenix__geomacceptance_8h.html", "d3/d62/eic__sphenix__geomacceptance_8h" ],
    [ "eic_sphenix_sidis_countbins.C", "d1/d78/eic__sphenix__sidis__countbins_8C.html", "d1/d78/eic__sphenix__sidis__countbins_8C" ],
    [ "eic_sphenix_test_smearing.C", "da/d53/eic__sphenix__test__smearing_8C.html", "da/d53/eic__sphenix__test__smearing_8C" ],
    [ "eic_sphenix_withmRICH.C", "d3/d1f/eic__sphenix__withmRICH_8C.html", "d3/d1f/eic__sphenix__withmRICH_8C" ],
    [ "eic_unsmeared_eta_p.C", "d0/d50/eic__unsmeared__eta__p_8C.html", "d0/d50/eic__unsmeared__eta__p_8C" ],
    [ "eicsmear_check_calorimeter.C", "dd/d3a/eicsmear__check__calorimeter_8C.html", "dd/d3a/eicsmear__check__calorimeter_8C" ],
    [ "eicsmear_check_tracking.C", "d9/d43/eicsmear__check__tracking_8C.html", "d9/d43/eicsmear__check__tracking_8C" ],
    [ "eicsmear_dvmp_plot.C", "d2/dea/eicsmear__dvmp__plot_8C.html", "d2/dea/eicsmear__dvmp__plot_8C" ],
    [ "eicsmear_dvmp_plot2.C", "dd/de7/eicsmear__dvmp__plot2_8C.html", "dd/de7/eicsmear__dvmp__plot2_8C" ],
    [ "eicsmear_dvmp_tree.C", "d0/d58/eicsmear__dvmp__tree_8C.html", "d0/d58/eicsmear__dvmp__tree_8C" ],
    [ "hera_dis_countbins.C", "d8/df8/hera__dis__countbins_8C.html", "d8/df8/hera__dis__countbins_8C" ],
    [ "hera_dis_fillbins.C", "d0/d7d/hera__dis__fillbins_8C.html", "d0/d7d/hera__dis__fillbins_8C" ],
    [ "plot_dis_acceptance.C", "de/d71/plot__dis__acceptance_8C.html", "de/d71/plot__dis__acceptance_8C" ],
    [ "plot_g1_projection.C", "d3/d2b/plot__g1__projection_8C.html", "d3/d2b/plot__g1__projection_8C" ],
    [ "plot_momentum_vs_eta.C", "dc/d64/plot__momentum__vs__eta_8C.html", "dc/d64/plot__momentum__vs__eta_8C" ],
    [ "plot_sidis_proj_uncertainty.C", "de/d90/plot__sidis__proj__uncertainty_8C.html", "de/d90/plot__sidis__proj__uncertainty_8C" ],
    [ "run_eic_sphenix.C", "dd/dfd/run__eic__sphenix_8C.html", "dd/dfd/run__eic__sphenix_8C" ]
];