Analysis Software: PHG4UserPrimaryParticleInformation Class Reference
PHG4UserPrimaryParticleInformation Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4UserPrimaryParticleInformation.h>
Public Member Functions
PHG4UserPrimaryParticleInformation (const int emb)
void Print () const
int get_embed () const
void set_user_track_id (int val)
int get_user_track_id () const
void set_user_vtx_id (int val)
int get_user_vtx_id () const
void set_user_barcode (int bcd)
int get_user_barcode () const
Private Attributes
int embed
int usertrackid
int uservtxid
int barcode
Detailed Description
Definition at line 9 of file PHG4UserPrimaryParticleInformation.h.
Constructor & Destructor Documentation
PHG4UserPrimaryParticleInformation::PHG4UserPrimaryParticleInformation (const int emb) inline
Definition at line 12 of file PHG4UserPrimaryParticleInformation.h.
Member Function Documentation
int PHG4UserPrimaryParticleInformation::get_embed () const inline
Definition at line 24 of file PHG4UserPrimaryParticleInformation.h.
References embed.
Referenced by PHG4TruthEventAction::EndOfEventAction().
int PHG4UserPrimaryParticleInformation::get_user_barcode () const inline
Definition at line 33 of file PHG4UserPrimaryParticleInformation.h.
References barcode.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
int PHG4UserPrimaryParticleInformation::get_user_track_id () const inline
Definition at line 27 of file PHG4UserPrimaryParticleInformation.h.
References usertrackid.
Referenced by PHG4TruthEventAction::EndOfEventAction().
int PHG4UserPrimaryParticleInformation::get_user_vtx_id () const inline
Definition at line 30 of file PHG4UserPrimaryParticleInformation.h.
References uservtxid.
Referenced by PHG4TruthEventAction::EndOfEventAction().
void PHG4UserPrimaryParticleInformation::Print () const inline
Definition at line 18 of file PHG4UserPrimaryParticleInformation.h.
References embed, usertrackid, and uservtxid.
void PHG4UserPrimaryParticleInformation::set_user_barcode (int bcd) inline
Definition at line 32 of file PHG4UserPrimaryParticleInformation.h.
References barcode.
Referenced by PHG4PrimaryGeneratorAction::GeneratePrimaries().
void PHG4UserPrimaryParticleInformation::set_user_track_id (int val) inline
Definition at line 26 of file PHG4UserPrimaryParticleInformation.h.
References usertrackid.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
void PHG4UserPrimaryParticleInformation::set_user_vtx_id (int val) inline
Definition at line 29 of file PHG4UserPrimaryParticleInformation.h.
References uservtxid.
Referenced by PHG4TruthTrackingAction::PreUserTrackingAction().
Member Data Documentation
int PHG4UserPrimaryParticleInformation::barcode private
Definition at line 39 of file PHG4UserPrimaryParticleInformation.h.
Referenced by get_user_barcode(), and set_user_barcode().
int PHG4UserPrimaryParticleInformation::embed private
Definition at line 36 of file PHG4UserPrimaryParticleInformation.h.
Referenced by get_embed(), and Print().
int PHG4UserPrimaryParticleInformation::usertrackid private
Definition at line 37 of file PHG4UserPrimaryParticleInformation.h.
Referenced by get_user_track_id(), Print(), and set_user_track_id().
int PHG4UserPrimaryParticleInformation::uservtxid private
Definition at line 38 of file PHG4UserPrimaryParticleInformation.h.
Referenced by get_user_vtx_id(), Print(), and set_user_vtx_id().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4UserPrimaryParticleInformation.h