Analysis Software: online_distribution/blob/master/newbasic/decoding_routines.cc File Reference
decoding_routines.cc File Reference
#include "decoding_routines.h"
#include <mizar.h>
Functions
int decode_id4evt (int iarr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_id2evt (int iarr[], short *SubeventData, int dlength, int nlen, int *olength)
int decode_idhammond (int iarr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_idhammondset (int iarr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_idtecfem (int iarr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_idmiznhc (int parr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_idsam (int iarr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_iddcfem (int iarr[], int *SubeventData, int dlength, int nlen, int *olength)
int decode_bbc_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mvd_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_dch_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pc_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tec_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_rich_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tof_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbsc_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbsc_dcm32 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbgl_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muta_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mutc_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muid_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_zdc_dcm0 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_rich_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mvd_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_bbc_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_ntczdc_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_big_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tof_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muid_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_ert_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbgl_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbsc_ll1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_gl1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_gl1p (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_bbc_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mvd_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_dch_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pc_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tec_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_rich_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tof_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbsc_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbgl_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muta_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mutc_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muid_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_zdc_dcm1 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_bbc_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mvd_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_dch_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pc_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pc_dcm3 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tec_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_rich_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_tof_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbsc_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbgl_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muta_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mutc_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_muid_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_zdc_dcm2 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_pbsc_dcms (int iarr[], int *packetData, int dlength, int nlen, int *olength)
int decode_mutc_dcm3 (int iarr[], int *packetData, int dlength, int nlen, int *olength)
Function Documentation
int decode_bbc_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 423 of file decoding_routines.cc.
References decode_id4evt().
int decode_bbc_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 885 of file decoding_routines.cc.
References decode_id4evt().
int decode_bbc_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1042 of file decoding_routines.cc.
References decode_id4evt().
int decode_bbc_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 793 of file decoding_routines.cc.
References decode_id4evt().
int decode_big_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 811 of file decoding_routines.cc.
References decode_id4evt().
int decode_dch_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 443 of file decoding_routines.cc.
References decode_id4evt().
int decode_dch_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 905 of file decoding_routines.cc.
References decode_id4evt().
int decode_dch_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1062 of file decoding_routines.cc.
References decode_id4evt().
int decode_ert_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 838 of file decoding_routines.cc.
References decode_id4evt().
int decode_gl1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 865 of file decoding_routines.cc.
References decode_id4evt().
Referenced by Packet_gl1::decode().
int decode_gl1p (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 875 of file decoding_routines.cc.
References decode_id4evt().
Referenced by Packet_gl1p::decode().
int decode_id2evt (int iarr[], short * SubeventData, int dlength, int nlen, int * olength)
Definition at line 51 of file decoding_routines.cc.
References dlength, and i.
Referenced by oncsSub_id2evt::decode(), and Packet_id2evt::decode().
int decode_id4evt (int iarr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 9 of file decoding_routines.cc.
References dlength, and i.
Referenced by oncsSub_id4evt::decode(), Packet_id4evt::decode(), decode_bbc_dcm0(), decode_bbc_dcm1(), decode_bbc_dcm2(), decode_bbc_ll1(), decode_big_ll1(), decode_dch_dcm0(), decode_dch_dcm1(), decode_dch_dcm2(), decode_ert_ll1(), decode_gl1(), decode_gl1p(), decode_idsam(), decode_muid_dcm0(), decode_muid_dcm1(), decode_muid_dcm2(), decode_muid_ll1(), decode_muta_dcm0(), decode_muta_dcm1(), decode_muta_dcm2(), decode_mvd_dcm0(), decode_mvd_dcm1(), decode_mvd_dcm2(), decode_mvd_ll1(), decode_ntczdc_ll1(), decode_pbgl_dcm0(), decode_pbgl_dcm1(), decode_pbgl_dcm2(), decode_pbgl_ll1(), decode_pbsc_dcm1(), decode_pbsc_dcm2(), decode_pbsc_ll1(), decode_pc_dcm0(), decode_pc_dcm1(), decode_pc_dcm2(), decode_pc_dcm3(), decode_rich_dcm0(), decode_rich_dcm1(), decode_rich_dcm2(), decode_rich_ll1(), decode_tec_dcm1(), decode_tec_dcm2(), decode_tof_dcm0(), decode_tof_dcm1(), decode_tof_dcm2(), decode_tof_ll1(), decode_zdc_dcm0(), decode_zdc_dcm1(), and decode_zdc_dcm2().
int decode_iddcfem (int iarr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 350 of file decoding_routines.cc.
References dlength, i, and j.
int decode_idhammond (int iarr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 87 of file decoding_routines.cc.
References dlength, h1, h2, i, and k.
int decode_idhammondset (int iarr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 149 of file decoding_routines.cc.
References dlength, and i.
int decode_idmiznhc (int parr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 252 of file decoding_routines.cc.
References sdm_c_blockdef::array, miz_irdgdef::board_adr, miz_irdgdef::byte_err, miz_irdgdef::c1_cell, miz_irdgdef::c2_cell, miz_irdgdef::conv1_high, sdm_c_blockdef::conv1_info, miz_irdgdef::conv1_low, miz_irdgdef::conv2_high, sdm_c_blockdef::conv2_info, miz_irdgdef::conv2_low, i, index, miz_irdgdef::out, sdm_c_blockdef::sdmlength, miz_irdgdef::ser_ret, miz_irdgdef::tac, miz_irdgdef::words, and miz_irdgdef::write_cell.
int decode_idsam (int iarr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 325 of file decoding_routines.cc.
References decode_id4evt(), and i.
int decode_idtecfem (int iarr[], int * SubeventData, int dlength, int nlen, int * olength)
Definition at line 185 of file decoding_routines.cc.
References dlength, i, and j.
int decode_muid_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 756 of file decoding_routines.cc.
References decode_id4evt().
int decode_muid_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1024 of file decoding_routines.cc.
References decode_id4evt().
int decode_muid_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1185 of file decoding_routines.cc.
References decode_id4evt().
int decode_muid_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 829 of file decoding_routines.cc.
References decode_id4evt().
int decode_muta_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 699 of file decoding_routines.cc.
References decode_id4evt().
int decode_muta_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 975 of file decoding_routines.cc.
References decode_id4evt().
int decode_muta_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1141 of file decoding_routines.cc.
References decode_id4evt().
int decode_mutc_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 712 of file decoding_routines.cc.
References COUT, ENDL, i, and j.
int decode_mutc_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 987 of file decoding_routines.cc.
References COUT, ENDL, i, and j.
int decode_mutc_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1151 of file decoding_routines.cc.
References COUT, ENDL, i, and j.
int decode_mutc_dcm3 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1272 of file decoding_routines.cc.
References COUT, ENDL, i, and j.
int decode_mvd_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 433 of file decoding_routines.cc.
References decode_id4evt().
int decode_mvd_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 895 of file decoding_routines.cc.
References decode_id4evt().
int decode_mvd_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1052 of file decoding_routines.cc.
References decode_id4evt().
int decode_mvd_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 784 of file decoding_routines.cc.
References decode_id4evt().
int decode_ntczdc_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 802 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbgl_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 689 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbgl_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 965 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbgl_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1131 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbgl_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 847 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbsc_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 563 of file decoding_routines.cc.
References channel(), COUT, ENDL, and i.
int decode_pbsc_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 955 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbsc_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1121 of file decoding_routines.cc.
References decode_id4evt().
int decode_pbsc_dcm32 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 632 of file decoding_routines.cc.
References COUT, ENDL, i, and j.
int decode_pbsc_dcms (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1204 of file decoding_routines.cc.
References COUT, ENDL, i, and j.
int decode_pbsc_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 856 of file decoding_routines.cc.
References decode_id4evt().
int decode_pc_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 453 of file decoding_routines.cc.
References decode_id4evt().
int decode_pc_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 915 of file decoding_routines.cc.
References decode_id4evt().
int decode_pc_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1072 of file decoding_routines.cc.
References decode_id4evt().
int decode_pc_dcm3 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1081 of file decoding_routines.cc.
References decode_id4evt().
int decode_rich_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 543 of file decoding_routines.cc.
References decode_id4evt().
int decode_rich_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 935 of file decoding_routines.cc.
References decode_id4evt().
int decode_rich_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1101 of file decoding_routines.cc.
References decode_id4evt().
int decode_rich_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 775 of file decoding_routines.cc.
References decode_id4evt().
int decode_tec_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 463 of file decoding_routines.cc.
References channel(), i, and j.
int decode_tec_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 925 of file decoding_routines.cc.
References decode_id4evt().
int decode_tec_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1091 of file decoding_routines.cc.
References decode_id4evt().
int decode_tof_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 553 of file decoding_routines.cc.
References decode_id4evt().
int decode_tof_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 945 of file decoding_routines.cc.
References decode_id4evt().
int decode_tof_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1111 of file decoding_routines.cc.
References decode_id4evt().
int decode_tof_ll1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 820 of file decoding_routines.cc.
References decode_id4evt().
int decode_zdc_dcm0 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 765 of file decoding_routines.cc.
References decode_id4evt().
int decode_zdc_dcm1 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1033 of file decoding_routines.cc.
References decode_id4evt().
int decode_zdc_dcm2 (int iarr[], int * packetData, int dlength, int nlen, int * olength)
Definition at line 1194 of file decoding_routines.cc.
References decode_id4evt().