Analysis Software: HiParnt Class Reference
HiParnt Class Reference
Class definition for HiParnt, which is used to modify the Hijing HIPARNT common.
#include <coresoftware/blob/master/generators/sHijing/HiParnt.h>
Classes
struct HIPARNT
Public Member Functions
HiParnt ()
~HiParnt ()
float & hipr1 (int n)
int & ihpr2 (int n)
float & hint1 (int n)
int & ihnt2 (int n)
void init (void)
int lenHipr1 () const
int lenIhpr2 () const
int lenHint1 () const
int lenIhnt2 () const
Private Attributes
int _dummy
float _realdummy
Static Private Attributes
static const int _lenHipr1 = 100
static const int _lenIhpr2 = 50
static const int _lenHint1 = 100
static const int _lenIhnt2 = 50
static HIPARNT * _hiparnt =0
Friends
struct HIPARNT
Detailed Description
Class definition for HiParnt, which is used to modify the Hijing HIPARNT common.
Definition at line 12 of file HiParnt.h.
Constructor & Destructor Documentation
HiParnt::HiParnt () inline
Definition at line 62 of file HiParnt.h.
HiParnt::~HiParnt () inline
Definition at line 68 of file HiParnt.h.
Member Function Documentation
float & HiParnt::hint1 (int n) inline
Definition at line 88 of file HiParnt.h.
References _hiparnt, _realdummy, HiParnt::HIPARNT::hint1, init(), and lenHint1().
Referenced by __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), ar3jet(), arorie(), attrad(), crsjet(), fgp1(), fgp2(), fhin(), fillEvent(), fjet(), fjetrig(), flap(), fnjet(), fnkick(), fnkick2(), fnstru(), fnstrum(), fnstrus(), ftot(), ftotjet(), ftotrig(), g(), ghvq(), gphoton(), hiboost(), hijcrs(), hijcsc(), hijels(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), hijwds(), hiptdi(), jetini(), omg0(), parton(), profile(), pyhiremn(), pyhistfu(), quench(), wdsax1(), and wdsax2().
float & HiParnt::hipr1 (int n) inline
Definition at line 72 of file HiParnt.h.
References _hiparnt, _realdummy, HiParnt::HIPARNT::hipr1, init(), and lenHipr1().
Referenced by __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), ar3jet(), arorie(), attrad(), crsjet(), fgp1(), fgp2(), fhin(), fjet(), fjetrig(), flap(), fnjet(), fnkick(), fnkick2(), fnstru(), fnstrum(), fnstrus(), ftot(), ftotjet(), ftotrig(), g(), ghvq(), gphoton(), hiboost(), hijcrs(), hijcsc(), hijels(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), hijwds(), hiptdi(), jetini(), main(), omg0(), parton(), profile(), pyhiremn(), pyhistfu(), quench(), wdsax1(), and wdsax2().
int & HiParnt::ihnt2 (int n) inline
Definition at line 97 of file HiParnt.h.
References _dummy, _hiparnt, HiParnt::HIPARNT::ihnt2, init(), and lenIhnt2().
Referenced by __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), ar3jet(), arorie(), attrad(), crsjet(), fgp1(), fgp2(), fhin(), fillEvent(), fjet(), fjetrig(), flap(), fnjet(), fnkick(), fnkick2(), fnstru(), fnstrum(), fnstrus(), ftot(), ftotjet(), ftotrig(), g(), ghvq(), gphoton(), hiboost(), hijcrs(), hijcsc(), hijels(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), hijwds(), hiptdi(), jetini(), omg0(), parton(), profile(), pyhiremn(), pyhistfu(), quench(), wdsax1(), and wdsax2().
int & HiParnt::ihpr2 (int n) inline
Definition at line 80 of file HiParnt.h.
References _dummy, _hiparnt, HiParnt::HIPARNT::ihpr2, init(), and lenIhpr2().
Referenced by __example_2.f__(), __example_3.f__(), __example_4.f__(), __example_6.f__(), __example_7.f__(), __example_8.f__(), ar3jet(), arorie(), attrad(), crsjet(), fgp1(), fgp2(), fhin(), fillEvent(), fjet(), fjetrig(), flap(), fnjet(), fnkick(), fnkick2(), fnstru(), fnstrum(), fnstrus(), ftot(), ftotjet(), ftotrig(), g(), ghvq(), gphoton(), hiboost(), hijcrs(), hijcsc(), hijels(), hijfrg(), hijhrd(), hijing(), hijini(), hijset(), hijsft(), hijwds(), hiptdi(), jetini(), main(), omg0(), parton(), profile(), pyhiremn(), pyhistfu(), quench(), wdsax1(), and wdsax2().
void HiParnt::init (void) inline
Definition at line 58 of file HiParnt.h.
References _hiparnt, and hiparnt_address_().
Referenced by hint1(), hipr1(), ihnt2(), and ihpr2().
int HiParnt::lenHint1 () const inline
Definition at line 27 of file HiParnt.h.
References _lenHint1.
Referenced by hint1().
int HiParnt::lenHipr1 () const inline
Definition at line 25 of file HiParnt.h.
References _lenHipr1.
Referenced by hipr1().
int HiParnt::lenIhnt2 () const inline
Definition at line 28 of file HiParnt.h.
References _lenIhnt2.
Referenced by ihnt2().
int HiParnt::lenIhpr2 () const inline
Definition at line 26 of file HiParnt.h.
References _lenIhpr2.
Referenced by ihpr2().
Friends And Related Function Documentation
friend struct HIPARNT friend
Definition at line 38 of file HiParnt.h.
Member Data Documentation
int HiParnt::_dummy private
Definition at line 49 of file HiParnt.h.
Referenced by ihnt2(), and ihpr2().
HiParnt::HIPARNT * HiParnt::_hiparnt =0 static private
Definition at line 51 of file HiParnt.h.
Referenced by hint1(), hipr1(), ihnt2(), ihpr2(), and init().
const int HiParnt::_lenHint1 = 100 static private
Definition at line 35 of file HiParnt.h.
Referenced by lenHint1().
const int HiParnt::_lenHipr1 = 100 static private
Definition at line 33 of file HiParnt.h.
Referenced by lenHipr1().
const int HiParnt::_lenIhnt2 = 50 static private
Definition at line 36 of file HiParnt.h.
Referenced by lenIhnt2().
const int HiParnt::_lenIhpr2 = 50 static private
Definition at line 34 of file HiParnt.h.
Referenced by lenIhpr2().
float HiParnt::_realdummy private
Definition at line 50 of file HiParnt.h.
Referenced by hint1(), and hipr1().
The documentation for this class was generated from the following file:
coresoftware/blob/master/generators/sHijing/HiParnt.h