Analysis Software: PHG4ForwardEcalDetector Class Reference
PHG4ForwardEcalDetector Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h>
Classes
struct towerposition
Public Member Functions
PHG4ForwardEcalDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, PHParameters *parameters, const std::string &dnam)
constructor
virtual ~PHG4ForwardEcalDetector ()
destructor
virtual void ConstructMe (G4LogicalVolume *world)
construct
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual G4UserSteppingAction * GetSteppingAction ()
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual void Print (const std::string &what="ALL") const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
volume accessors
PHG4ForwardEcalDisplayAction * m_DisplayAction
PHParameters * m_Params
PHG4GDMLConfig * m_GdmlConfig
registry for volumes that should not be exported, i.e. fibers
double m_TowerDx [7]
double m_TowerDy [7]
double m_TowerDz [7]
double m_XRot
double m_YRot
double m_ZRot
double m_PlaceX
double m_PlaceY
double m_PlaceZ
double m_RMin [2]
double m_RMax [2]
double m_dZ
int m_ActiveFlag
int m_AbsorberActiveFlag
int m_Layer
std::string m_SuperDetector
std::string m_TowerLogicNamePrefix
std::map< std::string,
towerposition > m_TowerPositionMap
std::map< std::string, double > m_GlobalParameterMap
std::set< G4LogicalVolume * > m_AbsorberLogicalVolSet
std::set< G4LogicalVolume * > m_ScintiLogicalVolSet
int IsInForwardEcal (G4VPhysicalVolume *) const
void SetTowerDimensions (double dx, double dy, double dz, int type)
void SetPlace (double place_in_x, double place_in_y, double place_in_z)
void SetPlaceX (double place_x)
void SetPlaceY (double place_y)
void SetPlaceZ (double place_z)
double GetPlaceX () const
double GetPlaceY () const
double GetPlaceZ () const
void SetXRot (double rot_in_x)
void SetYRot (double rot_in_y)
void SetZRot (double rot_in_z)
double GetXRot () const
double GetYRot () const
double GetZRot () const
double GetRMin (int i) const
double GetRMax (int i) const
void SetRMin (int i, double val)
void SetRMax (int i, double val)
double GetdZ () const
void SetdZ (double val)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int get_Layer () const
PHG4ForwardEcalDisplayAction * GetDisplayAction ()
G4LogicalVolume * ConstructTower (int type)
G4LogicalVolume * ConstructTowerType2 ()
G4LogicalVolume * ConstructTowerType3_4_5_6 (int type)
int PlaceTower (G4LogicalVolume *envelope, G4LogicalVolume *tower[6])
int ParseParametersFromTable ()
const std::string TowerLogicNamePrefix () const
PHParameters * GetParams () const
void AbsorberLogicalVolSetInsert (G4LogicalVolume *logvol)
void ScintiLogicalVolSetInsert (G4LogicalVolume *logvol)
std::map< std::string, double >
::const_iterator FindIter (const std::string &name)
std::map< std::string, double >
::const_iterator EndIter ()
void InsertParam (const std::string &parname, double parval)
Detailed Description
Definition at line 28 of file PHG4ForwardEcalDetector.h.
Constructor & Destructor Documentation
PHG4ForwardEcalDetector::PHG4ForwardEcalDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, PHParameters * parameters, const std::string & dnam)
constructor
Definition at line 44 of file PHG4ForwardEcalDetector.cc.
References assert, i, m_GdmlConfig, m_RMax, m_RMin, m_TowerDx, m_TowerDy, and m_TowerDz.
virtual PHG4ForwardEcalDetector::~PHG4ForwardEcalDetector () inline virtual
destructor
Definition at line 35 of file PHG4ForwardEcalDetector.h.
Member Function Documentation
void PHG4ForwardEcalDetector::AbsorberLogicalVolSetInsert (G4LogicalVolume * logvol) inline protected
Definition at line 154 of file PHG4ForwardEcalDetector.h.
References m_AbsorberLogicalVolSet.
Referenced by PHG4EICForwardEcalDetector::ConstructTower().
void PHG4ForwardEcalDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Reimplemented in PHG4EICForwardEcalDetector.
Definition at line 103 of file PHG4ForwardEcalDetector.cc.
References PHG4ForwardEcalDisplayAction::AddVolume(), ConstructTower(), GetDisplayAction(), i, m_dZ, M_PI, m_PlaceX, m_PlaceY, m_PlaceZ, m_RMax, m_RMin, m_TowerLogicNamePrefix, m_TowerPositionMap, m_XRot, m_YRot, m_ZRot, PHG4Detector::OverlapCheck(), ParseParametersFromTable(), PlaceTower(), and PHG4Detector::Verbosity().
G4LogicalVolume * PHG4ForwardEcalDetector::ConstructTower (int type) private
Definition at line 165 of file PHG4ForwardEcalDetector.cc.
References PHG4ForwardEcalDisplayAction::AddVolume(), assert, ConstructTowerType2(), ConstructTowerType3_4_5_6(), GetDisplayAction(), m_TowerDx, m_TowerDy, m_TowerDz, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), PHNode::type, and PHG4Detector::Verbosity().
Referenced by ConstructMe().
G4LogicalVolume * PHG4ForwardEcalDetector::ConstructTowerType2 () private
Definition at line 256 of file PHG4ForwardEcalDetector.cc.
References PHG4ForwardEcalDisplayAction::AddVolume(), GetDisplayAction(), i, m_AbsorberLogicalVolSet, m_ScintiLogicalVolSet, m_TowerDx, m_TowerDy, m_TowerDz, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructTower().
G4LogicalVolume * PHG4ForwardEcalDetector::ConstructTowerType3_4_5_6 (int type) private
Definition at line 348 of file PHG4ForwardEcalDetector.cc.
References PHG4ForwardEcalDisplayAction::AddVolume(), GetDisplayAction(), i, j, m_AbsorberLogicalVolSet, m_ScintiLogicalVolSet, m_TowerDx, m_TowerDy, m_TowerDz, m_TowerLogicNamePrefix, PHG4Detector::OverlapCheck(), twopi, PHNode::type, and PHG4Detector::Verbosity().
Referenced by ConstructTower().
std::map<std::string, double>::const_iterator PHG4ForwardEcalDetector::EndIter () inline protected
Definition at line 163 of file PHG4ForwardEcalDetector.h.
References m_GlobalParameterMap.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
std::map<std::string, double>::const_iterator PHG4ForwardEcalDetector::FindIter (const std::string & name) inline protected
Definition at line 162 of file PHG4ForwardEcalDetector.h.
References m_GlobalParameterMap.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
int PHG4ForwardEcalDetector::get_Layer () const inline
Definition at line 96 of file PHG4ForwardEcalDetector.h.
References m_Layer.
Referenced by PHG4ForwardEcalSteppingAction::UserSteppingAction().
PHG4ForwardEcalDisplayAction* PHG4ForwardEcalDetector::GetDisplayAction () inline
Definition at line 98 of file PHG4ForwardEcalDetector.h.
References m_DisplayAction.
Referenced by PHG4EICForwardEcalDetector::ConstructMe(), ConstructMe(), PHG4EICForwardEcalDetector::ConstructTower(), ConstructTower(), ConstructTowerType2(), and ConstructTowerType3_4_5_6().
double PHG4ForwardEcalDetector::GetdZ () const inline
Definition at line 89 of file PHG4ForwardEcalDetector.h.
References m_dZ.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
PHParameters* PHG4ForwardEcalDetector::GetParams () const inline protected
Definition at line 153 of file PHG4ForwardEcalDetector.h.
References m_Params.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
double PHG4ForwardEcalDetector::GetPlaceX () const inline
Definition at line 55 of file PHG4ForwardEcalDetector.h.
References m_PlaceX.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetPlaceY () const inline
Definition at line 56 of file PHG4ForwardEcalDetector.h.
References m_PlaceY.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetPlaceZ () const inline
Definition at line 57 of file PHG4ForwardEcalDetector.h.
References m_PlaceZ.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetRMax (int i) const inline
Definition at line 72 of file PHG4ForwardEcalDetector.h.
References assert, i, and m_RMax.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetRMin (int i) const inline
Definition at line 67 of file PHG4ForwardEcalDetector.h.
References assert, i, and m_RMin.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetXRot () const inline
Definition at line 63 of file PHG4ForwardEcalDetector.h.
References m_XRot.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetYRot () const inline
Definition at line 64 of file PHG4ForwardEcalDetector.h.
References m_YRot.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
double PHG4ForwardEcalDetector::GetZRot () const inline
Definition at line 65 of file PHG4ForwardEcalDetector.h.
References m_ZRot.
Referenced by PHG4EICForwardEcalDetector::ConstructMe().
void PHG4ForwardEcalDetector::InsertParam (const std::string & parname, double parval) inline protected
Definition at line 164 of file PHG4ForwardEcalDetector.h.
References m_GlobalParameterMap.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
int PHG4ForwardEcalDetector::IsInForwardEcal (G4VPhysicalVolume * volume) const
Definition at line 82 of file PHG4ForwardEcalDetector.cc.
References m_AbsorberActiveFlag, m_AbsorberLogicalVolSet, m_ActiveFlag, and m_ScintiLogicalVolSet.
Referenced by PHG4ForwardEcalSteppingAction::UserSteppingAction().
int PHG4ForwardEcalDetector::ParseParametersFromTable () private
Definition at line 513 of file PHG4ForwardEcalDetector.cc.
References PHParameters::get_string_param(), i, index, m_dZ, m_GlobalParameterMap, m_Params, m_PlaceX, m_PlaceY, m_PlaceZ, m_RMax, m_RMin, m_TowerDx, m_TowerDy, m_TowerDz, m_TowerLogicNamePrefix, m_TowerPositionMap, m_XRot, m_YRot, m_ZRot, PHNode::type, PHG4ForwardEcalDetector::towerposition::type, PHG4Detector::Verbosity(), PHG4ForwardEcalDetector::towerposition::x, PHG4ForwardEcalDetector::towerposition::y, and PHG4ForwardEcalDetector::towerposition::z.
Referenced by ConstructMe().
int PHG4ForwardEcalDetector::PlaceTower (G4LogicalVolume * envelope, G4LogicalVolume * tower[6]) private
Definition at line 484 of file PHG4ForwardEcalDetector.cc.
References assert, PHG4GDMLConfig::exclude_physical_vol(), m_GdmlConfig, m_TowerPositionMap, PHG4Detector::OverlapCheck(), and PHG4Detector::Verbosity().
Referenced by ConstructMe().
void PHG4ForwardEcalDetector::ScintiLogicalVolSetInsert (G4LogicalVolume * logvol) inline protected
Definition at line 158 of file PHG4ForwardEcalDetector.h.
References m_ScintiLogicalVolSet.
Referenced by PHG4EICForwardEcalDetector::ConstructTower().
void PHG4ForwardEcalDetector::SetdZ (double val) inline
Definition at line 91 of file PHG4ForwardEcalDetector.h.
References m_dZ.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetPlace (double place_in_x, double place_in_y, double place_in_z) inline
Definition at line 45 of file PHG4ForwardEcalDetector.h.
References m_PlaceX, m_PlaceY, and m_PlaceZ.
void PHG4ForwardEcalDetector::SetPlaceX (double place_x) inline
Definition at line 51 of file PHG4ForwardEcalDetector.h.
References m_PlaceX.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetPlaceY (double place_y) inline
Definition at line 52 of file PHG4ForwardEcalDetector.h.
References m_PlaceY.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetPlaceZ (double place_z) inline
Definition at line 53 of file PHG4ForwardEcalDetector.h.
References m_PlaceZ.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetRMax (int i, double val) inline
Definition at line 83 of file PHG4ForwardEcalDetector.h.
References assert, i, and m_RMax.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetRMin (int i, double val) inline
Definition at line 78 of file PHG4ForwardEcalDetector.h.
References assert, i, and m_RMin.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetTowerDimensions (double dx, double dy, double dz, int type)
Definition at line 665 of file PHG4ForwardEcalDetector.cc.
References assert, dx, dy, m_TowerDx, m_TowerDy, m_TowerDz, and PHNode::type.
void PHG4ForwardEcalDetector::SetXRot (double rot_in_x) inline
Definition at line 59 of file PHG4ForwardEcalDetector.h.
References m_XRot.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetYRot (double rot_in_y) inline
Definition at line 60 of file PHG4ForwardEcalDetector.h.
References m_YRot.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SetZRot (double rot_in_z) inline
Definition at line 61 of file PHG4ForwardEcalDetector.h.
References m_ZRot.
Referenced by PHG4EICForwardEcalDetector::ParseParametersFromTable().
void PHG4ForwardEcalDetector::SuperDetector (const std::string & name) inline
Definition at line 93 of file PHG4ForwardEcalDetector.h.
References m_SuperDetector, and name.
Referenced by PHG4ForwardEcalSubsystem::InitRunSubsystem(), and PHG4ForwardEcalSteppingAction::SetInterfacePointers().
const std::string PHG4ForwardEcalDetector::SuperDetector () const inline
Definition at line 94 of file PHG4ForwardEcalDetector.h.
References m_SuperDetector.
const std::string PHG4ForwardEcalDetector::TowerLogicNamePrefix () const inline protected
Definition at line 152 of file PHG4ForwardEcalDetector.h.
References m_TowerLogicNamePrefix.
Referenced by PHG4EICForwardEcalDetector::ConstructMe(), PHG4EICForwardEcalDetector::ConstructTower(), and PHG4EICForwardEcalDetector::ParseParametersFromTable().
Member Data Documentation
int PHG4ForwardEcalDetector::m_AbsorberActiveFlag private
Definition at line 139 of file PHG4ForwardEcalDetector.h.
Referenced by IsInForwardEcal().
std::set<G4LogicalVolume *> PHG4ForwardEcalDetector::m_AbsorberLogicalVolSet private
Definition at line 148 of file PHG4ForwardEcalDetector.h.
Referenced by AbsorberLogicalVolSetInsert(), ConstructTowerType2(), ConstructTowerType3_4_5_6(), and IsInForwardEcal().
int PHG4ForwardEcalDetector::m_ActiveFlag private
Definition at line 138 of file PHG4ForwardEcalDetector.h.
Referenced by IsInForwardEcal().
PHG4ForwardEcalDisplayAction* PHG4ForwardEcalDetector::m_DisplayAction private
Definition at line 115 of file PHG4ForwardEcalDetector.h.
Referenced by GetDisplayAction().
double PHG4ForwardEcalDetector::m_dZ private
Definition at line 136 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetdZ(), ParseParametersFromTable(), and SetdZ().
PHG4GDMLConfig* PHG4ForwardEcalDetector::m_GdmlConfig private
registry for volumes that should not be exported, i.e. fibers
Definition at line 118 of file PHG4ForwardEcalDetector.h.
Referenced by PHG4ForwardEcalDetector(), and PlaceTower().
std::map<std::string, double> PHG4ForwardEcalDetector::m_GlobalParameterMap private
Definition at line 146 of file PHG4ForwardEcalDetector.h.
Referenced by EndIter(), FindIter(), InsertParam(), and ParseParametersFromTable().
int PHG4ForwardEcalDetector::m_Layer private
Definition at line 140 of file PHG4ForwardEcalDetector.h.
Referenced by get_Layer().
PHParameters* PHG4ForwardEcalDetector::m_Params private
Definition at line 116 of file PHG4ForwardEcalDetector.h.
Referenced by GetParams(), and ParseParametersFromTable().
double PHG4ForwardEcalDetector::m_PlaceX private
Definition at line 129 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetPlaceX(), ParseParametersFromTable(), SetPlace(), and SetPlaceX().
double PHG4ForwardEcalDetector::m_PlaceY private
Definition at line 130 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetPlaceY(), ParseParametersFromTable(), SetPlace(), and SetPlaceY().
double PHG4ForwardEcalDetector::m_PlaceZ private
Definition at line 131 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetPlaceZ(), ParseParametersFromTable(), SetPlace(), and SetPlaceZ().
double PHG4ForwardEcalDetector::m_RMax[2] private
Definition at line 134 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetRMax(), ParseParametersFromTable(), PHG4ForwardEcalDetector(), and SetRMax().
double PHG4ForwardEcalDetector::m_RMin[2] private
Definition at line 133 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetRMin(), ParseParametersFromTable(), PHG4ForwardEcalDetector(), and SetRMin().
std::set<G4LogicalVolume *> PHG4ForwardEcalDetector::m_ScintiLogicalVolSet private
Definition at line 149 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructTowerType2(), ConstructTowerType3_4_5_6(), IsInForwardEcal(), and ScintiLogicalVolSetInsert().
std::string PHG4ForwardEcalDetector::m_SuperDetector private
Definition at line 142 of file PHG4ForwardEcalDetector.h.
Referenced by SuperDetector().
double PHG4ForwardEcalDetector::m_TowerDx[7] private
Definition at line 121 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructTower(), ConstructTowerType2(), ConstructTowerType3_4_5_6(), ParseParametersFromTable(), PHG4ForwardEcalDetector(), and SetTowerDimensions().
double PHG4ForwardEcalDetector::m_TowerDy[7] private
Definition at line 122 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructTower(), ConstructTowerType2(), ConstructTowerType3_4_5_6(), ParseParametersFromTable(), PHG4ForwardEcalDetector(), and SetTowerDimensions().
double PHG4ForwardEcalDetector::m_TowerDz[7] private
Definition at line 123 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructTower(), ConstructTowerType2(), ConstructTowerType3_4_5_6(), ParseParametersFromTable(), PHG4ForwardEcalDetector(), and SetTowerDimensions().
std::string PHG4ForwardEcalDetector::m_TowerLogicNamePrefix private
Definition at line 143 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), ConstructTower(), ConstructTowerType2(), ConstructTowerType3_4_5_6(), ParseParametersFromTable(), and TowerLogicNamePrefix().
std::map<std::string, towerposition> PHG4ForwardEcalDetector::m_TowerPositionMap private
Definition at line 145 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), ParseParametersFromTable(), and PlaceTower().
double PHG4ForwardEcalDetector::m_XRot private
Definition at line 125 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetXRot(), ParseParametersFromTable(), and SetXRot().
double PHG4ForwardEcalDetector::m_YRot private
Definition at line 126 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetYRot(), ParseParametersFromTable(), and SetYRot().
double PHG4ForwardEcalDetector::m_ZRot private
Definition at line 127 of file PHG4ForwardEcalDetector.h.
Referenced by ConstructMe(), GetZRot(), ParseParametersFromTable(), and SetZRot().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc