Analysis Software: G4RootRawTower Class Reference
G4RootRawTower Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4histos/G4RootRawTower.h>
Public Member Functions
G4RootRawTower ()
G4RootRawTower (const float ieta, const float iphi, const float e)
virtual ~G4RootRawTower ()
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
void identify (std::ostream &os=std::cout) const
float get_eta () const
float get_phi () const
float get_energy () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
float eta
float phi
float energy
Detailed Description
Definition at line 8 of file G4RootRawTower.h.
Constructor & Destructor Documentation
G4RootRawTower::G4RootRawTower ()
Definition at line 8 of file G4RootRawTower.cc.
G4RootRawTower::G4RootRawTower (const float ieta, const float iphi, const float e)
Definition at line 15 of file G4RootRawTower.cc.
virtual G4RootRawTower::~G4RootRawTower () inline virtual
Definition at line 13 of file G4RootRawTower.h.
Member Function Documentation
float G4RootRawTower::get_energy () const inline
Definition at line 21 of file G4RootRawTower.h.
References energy.
Referenced by identify(), and isValid().
float G4RootRawTower::get_eta () const inline
Definition at line 19 of file G4RootRawTower.h.
References eta.
float G4RootRawTower::get_phi () const inline
Definition at line 20 of file G4RootRawTower.h.
References phi.
void G4RootRawTower::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 34 of file G4RootRawTower.cc.
References eta, get_energy(), and phi.
int G4RootRawTower::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 29 of file G4RootRawTower.cc.
References get_energy().
void G4RootRawTower::Reset () virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 22 of file G4RootRawTower.cc.
References energy, eta, and phi.
Member Data Documentation
float G4RootRawTower::energy protected
Definition at line 26 of file G4RootRawTower.h.
Referenced by get_energy(), and Reset().
float G4RootRawTower::eta protected
Definition at line 24 of file G4RootRawTower.h.
Referenced by get_eta(), identify(), and Reset().
float G4RootRawTower::phi protected
Definition at line 25 of file G4RootRawTower.h.
Referenced by get_phi(), identify(), and Reset().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4histos/G4RootRawTower.h
coresoftware/blob/master/simulation/g4simulation/g4histos/G4RootRawTower.cc