Analysis Software: analysis/blob/master/EICMCAnalysis/analysis_eicsmear/calculate_g1.C File Reference
calculate_g1.C File Reference
Functions
double get_parametrization_F2 (double x, double Q2)
double get_parametrization_R (double x, double Q2)
double get_depolarization_factor (double x, double Q2, double y, double mlepton=0.000511)
double get_beam_polarization ()
double get_g1_value (double x_val, double Q2_val, double y_val, double mlepton=0.000511)
double get_g1_sigma (double x_val, double Q2_val, double y_val, double N_val, double mlepton=0.000511)
double get_A1_sigma (double x_val, double Q2_val, double y_val, double N_val, double mlepton=0.000511)
void calculate_g1 (double x_val, double Q2_val, double y_val, double N_val, double mlepton=0.000511)
Function Documentation
void calculate_g1 (double x_val, double Q2_val, double y_val, double N_val, double mlepton = 0.000511)
Printing values on screen
Definition at line 185 of file calculate_g1.C.
References F2, get_depolarization_factor(), get_g1_sigma(), get_g1_value(), get_parametrization_F2(), and get_parametrization_R().
double get_A1_sigma (double x_val, double Q2_val, double y_val, double N_val, double mlepton = 0.000511)
Caluclate A1 statistical uncertainty
Definition at line 163 of file calculate_g1.C.
References F1, F2, get_g1_sigma(), get_parametrization_F2(), and get_parametrization_R().
Referenced by calculate_g1_projection_per_bin().
double get_beam_polarization ()
Calculate beam polarization
Definition at line 101 of file calculate_g1.C.
Referenced by get_g1_sigma().
double get_depolarization_factor (double x, double Q2, double y, double mlepton = 0.000511)
Calculate depolarization factor D(x,Q2,y,m_lepton)
Definition at line 73 of file calculate_g1.C.
References get_parametrization_R(), and y.
Referenced by calculate_g1(), get_g1_sigma(), and get_g1_value().
double get_g1_sigma (double x_val, double Q2_val, double y_val, double N_val, double mlepton = 0.000511)
Caluclate g1 statistical uncertainty
Definition at line 142 of file calculate_g1.C.
References F2, get_beam_polarization(), get_depolarization_factor(), get_parametrization_F2(), and get_parametrization_R().
Referenced by calculate_g1(), calculate_g1_projection_per_bin(), and get_A1_sigma().
double get_g1_value (double x_val, double Q2_val, double y_val, double mlepton = 0.000511)
Calculate value of g1
Definition at line 114 of file calculate_g1.C.
References F2, get_depolarization_factor(), get_parametrization_F2(), and get_parametrization_R().
Referenced by calculate_g1().
double get_parametrization_F2 (double x, double Q2)
Parametrization for F2(x,Q2)
Definition at line 4 of file calculate_g1.C.
References A, b1, C, and c2.
Referenced by calculate_g1(), get_A1_sigma(), get_g1_sigma(), and get_g1_value().
double get_parametrization_R (double x, double Q2)
Parametrization for R(x,Q2)
Definition at line 44 of file calculate_g1.C.
Referenced by calculate_g1(), get_A1_sigma(), get_depolarization_factor(), get_g1_sigma(), and get_g1_value().