Analysis Software: PHG4HcalPrototypeSteppingAction Class Reference
PHG4HcalPrototypeSteppingAction Class Reference
#include <prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4HcalPrototypeSteppingAction.h>
Public Member Functions
PHG4HcalPrototypeSteppingAction (PHG4HcalPrototypeDetector *)
constructor
virtual ~PHG4HcalPrototypeSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4HcalPrototypeDetector * detector_
pointer to the detector
PHG4HitContainer * hits_
pointer to hit container
PHG4HitContainer * absorberhits_
PHG4Hit * hit
Detailed Description
Definition at line 17 of file PHG4HcalPrototypeSteppingAction.h.
Constructor & Destructor Documentation
PHG4HcalPrototypeSteppingAction::PHG4HcalPrototypeSteppingAction (PHG4HcalPrototypeDetector * detector)
constructor
Definition at line 38 of file PHG4HcalPrototypeSteppingAction.cc.
virtual PHG4HcalPrototypeSteppingAction::~PHG4HcalPrototypeSteppingAction () inline virtual
destroctor
Definition at line 26 of file PHG4HcalPrototypeSteppingAction.h.
Member Function Documentation
void PHG4HcalPrototypeSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 258 of file PHG4HcalPrototypeSteppingAction.cc.
References absorberhits_, detector_, PHG4Detector::GetName(), hits_, PHG4HcalPrototypeDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
Referenced by PHG4HcalPrototypeSubsystem::process_event().
bool PHG4HcalPrototypeSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 48 of file PHG4HcalPrototypeSteppingAction.cc.
References absorberhits_, PHG4HitContainer::AddHit(), detector_, PHG4Hit::get_edep(), PHG4Hit::get_eion(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), hit, hits_, PHG4HcalPrototypeDetector::IsActive(), PHG4HcalPrototypeDetector::IsBlackHole(), PHG4Hit::set_edep(), PHG4Hit::set_eion(), PHG4Hit::set_layer(), PHG4Hit::set_scint_id(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), and PHG4Hit::set_z().
Member Data Documentation
PHG4HitContainer* PHG4HcalPrototypeSteppingAction::absorberhits_ private
Definition at line 42 of file PHG4HcalPrototypeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4HcalPrototypeDetector* PHG4HcalPrototypeSteppingAction::detector_ private
pointer to the detector
Definition at line 38 of file PHG4HcalPrototypeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4HcalPrototypeSteppingAction::hit private
Definition at line 43 of file PHG4HcalPrototypeSteppingAction.h.
Referenced by UserSteppingAction().
PHG4HitContainer* PHG4HcalPrototypeSteppingAction::hits_ private
pointer to hit container
Definition at line 41 of file PHG4HcalPrototypeSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
The documentation for this class was generated from the following files:
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4HcalPrototypeSteppingAction.h
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4HcalPrototypeSteppingAction.cc