Analysis Software: BinEntryPair5D Class Reference
BinEntryPair5D Class Reference
#include <coresoftware/blob/master/offline/packages/HelixHough/helix_hough/HelixHough.h>
Public Member Functions
BinEntryPair5D (unsigned int b=0, unsigned int e=0, bool is=false)
~BinEntryPair5D ()
bool operator< (const BinEntryPair5D &other) const
void bin5D (unsigned int nbins2, unsigned int nbins3, unsigned int nbins4, unsigned int nbins5, unsigned int &bin1, unsigned int &bin2, unsigned int &bin3, unsigned int &bin4, unsigned int &bin5) const
Static Public Member Functions
static unsigned int linearBin (unsigned int nbins2, unsigned int nbins3, unsigned int nbins4, unsigned int nbins5, unsigned int bin1, unsigned int bin2, unsigned int bin3, unsigned int bin4, unsigned int bin5)
Public Attributes
unsigned int bin
unsigned int entry
bool is_seed
Detailed Description
Definition at line 78 of file HelixHough.h.
Constructor & Destructor Documentation
BinEntryPair5D::BinEntryPair5D (unsigned int b = 0, unsigned int e = 0, bool is = false) inline
Definition at line 81 of file HelixHough.h.
BinEntryPair5D::~BinEntryPair5D () inline
Definition at line 82 of file HelixHough.h.
Member Function Documentation
void BinEntryPair5D::bin5D (unsigned int nbins2, unsigned int nbins3, unsigned int nbins4, unsigned int nbins5, unsigned int & bin1, unsigned int & bin2, unsigned int & bin3, unsigned int & bin4, unsigned int & bin5) const inline
Definition at line 94 of file HelixHough.h.
References bin, temp1, and temp2.
Referenced by setRange(), and HelixHough::setRange().
static unsigned int BinEntryPair5D::linearBin (unsigned int nbins2, unsigned int nbins3, unsigned int nbins4, unsigned int nbins5, unsigned int bin1, unsigned int bin2, unsigned int bin3, unsigned int bin4, unsigned int bin5) inline static
Definition at line 89 of file HelixHough.h.
Referenced by HelixHough::fillBins(), HelixHough::findSeededHelices(), and HelixHough::makeClusters().
bool BinEntryPair5D::operator< (const BinEntryPair5D & other) const inline
Definition at line 84 of file HelixHough.h.
References bin.
Member Data Documentation
unsigned int BinEntryPair5D::bin
Definition at line 111 of file HelixHough.h.
Referenced by bin5D(), operator<(), and HelixHough::splitIntoBins().
unsigned int BinEntryPair5D::entry
Definition at line 112 of file HelixHough.h.
bool BinEntryPair5D::is_seed
Definition at line 113 of file HelixHough.h.
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/packages/HelixHough/helix_hough/HelixHough.h