Analysis Software: IClassifierReader Class Reference
IClassifierReader Class Reference abstract
Public Member Functions
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
IClassifierReader ()
virtual ~IClassifierReader ()
virtual double GetMvaValue (const std::vector< double > &inputValues) const =0
bool IsStatusClean () const
Protected Attributes
bool fStatusIsClean
Detailed Description
Definition at line 92 of file aback_Cuts.class.C.
Constructor & Destructor Documentation
IClassifierReader::IClassifierReader () inline
Definition at line 97 of file aback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 98 of file aback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 68 of file aback_LikelihoodD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 69 of file aback_LikelihoodD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 81 of file aback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 82 of file aback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 64 of file aback_LikelihoodD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 65 of file aback_LikelihoodD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 72 of file aback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 73 of file aback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 65 of file aback_LikelihoodD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 66 of file aback_LikelihoodD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 85 of file eback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 86 of file eback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 66 of file eback_Fisher.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 67 of file eback_Fisher.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 65 of file eback_LD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 66 of file eback_LD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 65 of file eback_LikelihoodD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 66 of file eback_LikelihoodD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 80 of file eback_PDEFoam.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 81 of file eback_PDEFoam.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 85 of file hback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 86 of file hback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 66 of file hback_Fisher.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 67 of file hback_Fisher.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 65 of file hback_LD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 66 of file hback_LD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 65 of file hback_LikelihoodD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 66 of file hback_LikelihoodD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 80 of file hback_PDEFoam.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 81 of file hback_PDEFoam.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 80 of file pairback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 81 of file pairback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 68 of file pairCuts_LikelihoodD.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 69 of file pairCuts_LikelihoodD.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 72 of file trackback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 73 of file trackback_Cuts.class.C.
IClassifierReader::IClassifierReader () inline
Definition at line 77 of file vtxback_Cuts.class.C.
virtual IClassifierReader::~IClassifierReader () inline virtual
Definition at line 78 of file vtxback_Cuts.class.C.
Member Function Documentation
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
virtual double IClassifierReader::GetMvaValue (const std::vector< double > & inputValues) const pure virtual
Implemented in ReadCuts, ReadCuts, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadFisher, ReadFisher, ReadLD, ReadLD, ReadCuts, ReadLikelihoodD, ReadLikelihoodD, ReadLikelihoodD, ReadCuts, ReadCuts, ReadCuts, and ReadLikelihoodD.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 71 of file aback_LikelihoodD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 72 of file eback_LD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 72 of file eback_LikelihoodD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 72 of file aback_LikelihoodD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 72 of file hback_LD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 72 of file hback_LikelihoodD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 73 of file eback_Fisher.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 73 of file hback_Fisher.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 75 of file pairCuts_LikelihoodD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 75 of file aback_LikelihoodD.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 79 of file trackback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 79 of file aback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 84 of file vtxback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 87 of file hback_PDEFoam.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 87 of file pairback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 87 of file eback_PDEFoam.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 88 of file aback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 92 of file hback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 92 of file eback_Cuts.class.C.
References fStatusIsClean.
bool IClassifierReader::IsStatusClean () const inline
Definition at line 104 of file aback_Cuts.class.C.
References fStatusIsClean.
Referenced by ReadLD::GetMvaValue(), ReadFisher::GetMvaValue(), ReadLikelihoodD::GetMvaValue(), and ReadCuts::GetMvaValue().
Member Data Documentation
bool IClassifierReader::fStatusIsClean protected
Definition at line 108 of file aback_Cuts.class.C.
Referenced by ReadLD::Initialize(), ReadFisher::Initialize(), IsStatusClean(), ReadCuts::ReadCuts(), ReadFisher::ReadFisher(), ReadLD::ReadLD(), and ReadLikelihoodD::ReadLikelihoodD().
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/Training/default/weights/aback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/default/weights/aback_LikelihoodD.class.C
analysis/blob/master/PhotonConversion/Training/training/default/weights/aback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/training/default/weights/aback_LikelihoodD.class.C
analysis/blob/master/PhotonConversion/Training/weights/aback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/aback_LikelihoodD.class.C
analysis/blob/master/PhotonConversion/Training/weights/eback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/eback_Fisher.class.C
analysis/blob/master/PhotonConversion/Training/weights/eback_LD.class.C
analysis/blob/master/PhotonConversion/Training/weights/eback_LikelihoodD.class.C
analysis/blob/master/PhotonConversion/Training/weights/eback_PDEFoam.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_Fisher.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_LD.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_LikelihoodD.class.C
analysis/blob/master/PhotonConversion/Training/weights/hback_PDEFoam.class.C
analysis/blob/master/PhotonConversion/Training/weights/pairback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/pairCuts_LikelihoodD.class.C
analysis/blob/master/PhotonConversion/Training/weights/trackback_Cuts.class.C
analysis/blob/master/PhotonConversion/Training/weights/vtxback_Cuts.class.C