Analysis Software: PdbBankID Class Reference
PdbBankID Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/base/PdbBankID.h>
Public Member Functions
PdbBankID (const int val=0)
virtual ~PdbBankID ()
void print () const
int getInternalValue () const
void setInternalValue (const int val)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
int bankID
Friends
int operator== (const PdbBankID &, const PdbBankID &)
Detailed Description
Definition at line 19 of file PdbBankID.h.
Constructor & Destructor Documentation
PdbBankID::PdbBankID (const int val = 0)
Definition at line 14 of file PdbBankID.cc.
References bankID.
virtual PdbBankID::~PdbBankID () inline virtual
Definition at line 22 of file PdbBankID.h.
Member Function Documentation
int PdbBankID::getInternalValue () const inline
Definition at line 26 of file PdbBankID.h.
References bankID.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), PgPostCalBankIterator::init(), PgPostBankWrapperManager::print(), PgPostCalBankIterator::print(), PHParameters::ReadFromFile(), PgPostBankBackupStorage::set_obj_info(), PHParametersContainer::WriteToFile(), PdbParameterMapContainer::WriteToFile(), and PHParameters::WriteToFile().
void PdbBankID::print () const
Definition at line 19 of file PdbBankID.cc.
References bankID.
Referenced by PgPostBankWrapper::printHeader().
void PdbBankID::setInternalValue (const int val) inline
Definition at line 27 of file PdbBankID.h.
References bankID.
Friends And Related Function Documentation
int operator== (const PdbBankID & a, const PdbBankID & b) friend
Definition at line 24 of file PdbBankID.cc.
Member Data Documentation
int PdbBankID::bankID private
Definition at line 32 of file PdbBankID.h.
Referenced by getInternalValue(), operator==(), PdbBankID(), print(), and setInternalValue().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/base/PdbBankID.h
coresoftware/blob/master/offline/database/pdbcal/base/PdbBankID.cc