Analysis Software: TpcPrototypeUnpacker::PadPlaneData Class Reference
TpcPrototypeUnpacker::PadPlaneData Class Reference
buffer for full event data
#include <prototype/blob/master/offline/packages/tpc2019/TpcPrototypeUnpacker.h>
Classes
struct SampleID
Public Member Functions
PadPlaneData ()
void Reset ()
std::vector< int > & getPad (const int pad_x, const int pad_y)
int getSample (const SampleID &id)
void Clustering (int zero_suppression, bool verbosity=false)
3-D Graph clustering based on PHMakeGroups()
const std::vector< std::vector
< std::vector< int > > > & getData () const
const std::multimap< int,
SampleID > & getGroups () const
Static Public Member Functions
static bool IsValidPad (const int pad_x, const int pad_y)
Private Attributes
std::vector< std::vector
< std::vector< int > > > m_data
full event data in index order of m_data[pady][padx][sample]
std::multimap< int, SampleID > m_groups
Detailed Description
buffer for full event data
Definition at line 97 of file TpcPrototypeUnpacker.h.
Constructor & Destructor Documentation
TpcPrototypeUnpacker::PadPlaneData::PadPlaneData ()
Definition at line 907 of file TpcPrototypeUnpacker.cc.
Member Function Documentation
void TpcPrototypeUnpacker::PadPlaneData::Clustering (int zero_suppression, bool verbosity = false)
3-D Graph clustering based on PHMakeGroups()
Definition at line 974 of file TpcPrototypeUnpacker.cc.
References TpcPrototypeUnpacker::PadPlaneData::SampleID::adjust(), assert, G, i, it, TPCDaqDefs::FEEv1::kMaxPadX, TPCDaqDefs::FEEv1::kMaxPadY, TPCDaqDefs::FEEv1::kSAMPLE_LENGTH, TpcPrototypeUnpacker::PadPlaneData::SampleID::pady, and v.
Referenced by TpcPrototypeUnpacker::Clustering().
const std::vector<std::vector<std::vector<int> > >& TpcPrototypeUnpacker::PadPlaneData::getData () const inline
Definition at line 126 of file TpcPrototypeUnpacker.h.
References m_data.
const std::multimap<int, SampleID>& TpcPrototypeUnpacker::PadPlaneData::getGroups () const inline
Definition at line 131 of file TpcPrototypeUnpacker.h.
References m_groups.
Referenced by TpcPrototypeUnpacker::Clustering().
vector< int > & TpcPrototypeUnpacker::PadPlaneData::getPad (const int pad_x, const int pad_y)
Definition at line 933 of file TpcPrototypeUnpacker.cc.
References assert, TPCDaqDefs::FEEv1::kMaxPadX, and TPCDaqDefs::FEEv1::kMaxPadY.
Referenced by TpcPrototypeUnpacker::Clustering(), and TpcPrototypeUnpacker::process_event().
int TpcPrototypeUnpacker::PadPlaneData::getSample (const SampleID & id)
bool TpcPrototypeUnpacker::PadPlaneData::IsValidPad (const int pad_x, const int pad_y) static
Definition at line 925 of file TpcPrototypeUnpacker.cc.
References TPCDaqDefs::FEEv1::kMaxPadX, and TPCDaqDefs::FEEv1::kMaxPadY.
Referenced by TpcPrototypeUnpacker::Clustering().
void TpcPrototypeUnpacker::PadPlaneData::Reset ()
Definition at line 912 of file TpcPrototypeUnpacker.cc.
Referenced by TpcPrototypeUnpacker::ResetEvent().
Member Data Documentation
std::vector<std::vector<std::vector<int> > > TpcPrototypeUnpacker::PadPlaneData::m_data private
full event data in index order of m_data[pady][padx][sample]
Definition at line 138 of file TpcPrototypeUnpacker.h.
Referenced by getData().
std::multimap<int, SampleID> TpcPrototypeUnpacker::PadPlaneData::m_groups private
Definition at line 140 of file TpcPrototypeUnpacker.h.
Referenced by getGroups().
The documentation for this class was generated from the following files:
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeUnpacker.h
prototype/blob/master/offline/packages/tpc2019/TpcPrototypeUnpacker.cc