Analysis Software: ExampleAnalysisModule Class Reference
ExampleAnalysisModule Class Reference
you get started
#include <analysis/blob/master/Prototype3/tutorial/ExampleAnalysisModule/ExampleAnalysisModule.h>
Classes
class Eval_Cluster
class Eval_Run
Public Member Functions
ExampleAnalysisModule (const std::string &filename="ExampleAnalysis.root")
constructor
virtual ~ExampleAnalysisModule ()
destructor
int Init (PHCompositeNode *topNode)
Standard function called at initialization.
int InitRun (PHCompositeNode *topNode)
Standard function called when a new run is processed.
int process_event (PHCompositeNode *topNode)
Standard function called at each event.
int End (PHCompositeNode *topNode)
Standard function called at the end of processing. Save your stuff here.
void is_sim (bool b)
Is processing simulation files?
ExampleAnalysisModule (const std::string &filename="ExampleAnalysis.root")
constructor
virtual ~ExampleAnalysisModule ()
destructor
int Init (PHCompositeNode *topNode)
Standard function called at initialization.
int InitRun (PHCompositeNode *topNode)
Standard function called when a new run is processed.
int process_event (PHCompositeNode *topNode)
Standard function called at each event.
int End (PHCompositeNode *topNode)
Standard function called at the end of processing. Save your stuff here.
void is_sim (bool b)
Is processing simulation files?
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { n_size = 8 }
enum { n_size = 8 }
Private Member Functions
Fun4AllHistoManager * get_HistoManager ()
get manager of histograms
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
Fun4AllHistoManager * get_HistoManager ()
get manager of histograms
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
Private Attributes
bool _is_sim
is processing simulation files?
std::string _filename
output root file name
unsigned long _ievent
simple event counter
Eval_Run _eval_run
run infomation. To be copied to output TTree T
Eval_Cluster _eval_5x5_CEMC
clusters of max 5x5 EMCal cluster. To be copied to output TTree T
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
you get started
Definition at line 23 of file ExampleAnalysisModule.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
n_size
Definition at line 200 of file ExampleAnalysisModule.h.
anonymous enum private
Enumerator:
n_size
Definition at line 189 of file ExampleAnalysisModule.h.
Constructor & Destructor Documentation
ExampleAnalysisModule::ExampleAnalysisModule (const std::string & filename = "ExampleAnalysis.root")
constructor
Definition at line 47 of file ExampleAnalysisModule.C.
References _eval_5x5_CEMC, _eval_run, ExampleAnalysisModule::Eval_Run::reset(), ExampleAnalysisModule::Eval_Cluster::reset(), and verbosity.
ExampleAnalysisModule::~ExampleAnalysisModule () virtual
destructor
Definition at line 58 of file ExampleAnalysisModule.C.
ExampleAnalysisModule::ExampleAnalysisModule (const std::string & filename = "ExampleAnalysis.root")
constructor
virtual ExampleAnalysisModule::~ExampleAnalysisModule () virtual
destructor
Member Function Documentation
int ExampleAnalysisModule::End (PHCompositeNode * topNode) virtual
Standard function called at the end of processing. Save your stuff here.
Reimplemented from SubsysReco.
int ExampleAnalysisModule::End (PHCompositeNode * topNode) virtual
Standard function called at the end of processing. Save your stuff here.
Reimplemented from SubsysReco.
Definition at line 105 of file ExampleAnalysisModule.C.
References _filename, assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, and Fun4AllHistoManager::nHistos().
std::pair<int, int> ExampleAnalysisModule::find_max (RawTowerContainer * towers, int cluster_size) private
pair< int, int > ExampleAnalysisModule::find_max (RawTowerContainer * towers, int cluster_size) private
Definition at line 538 of file ExampleAnalysisModule.C.
References assert, col, energy, RawTower::get_energy(), RawTowerContainer::getTower(), max, n_size, and t.
Referenced by process_event().
Fun4AllHistoManager* ExampleAnalysisModule::get_HistoManager () private
get manager of histograms
Fun4AllHistoManager * ExampleAnalysisModule::get_HistoManager () private
get manager of histograms
Definition at line 63 of file ExampleAnalysisModule.C.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), Init(), and process_event().
int ExampleAnalysisModule::Init (PHCompositeNode * topNode) virtual
Standard function called at initialization.
Reimplemented from SubsysReco.
int ExampleAnalysisModule::Init (PHCompositeNode * topNode) virtual
Standard function called at initialization.
Histogram of Cherenkov counters
Envent nomalization
Reimplemented from SubsysReco.
Definition at line 122 of file ExampleAnalysisModule.C.
References _eval_5x5_CEMC, _eval_run, _filename, _ievent, assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), hNormalization, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), and T.
int ExampleAnalysisModule::InitRun (PHCompositeNode * topNode) virtual
Standard function called when a new run is processed.
Reimplemented from SubsysReco.
int ExampleAnalysisModule::InitRun (PHCompositeNode * topNode) virtual
Standard function called when a new run is processed.
Reimplemented from SubsysReco.
Definition at line 84 of file ExampleAnalysisModule.C.
References _ievent, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and verbosity.
void ExampleAnalysisModule::is_sim (bool b) inline
Is processing simulation files?
Definition at line 46 of file ExampleAnalysisModule.h.
References _is_sim.
void ExampleAnalysisModule::is_sim (bool b) inline
Is processing simulation files?
Definition at line 53 of file ExampleAnalysisModule.h.
References _is_sim.
int ExampleAnalysisModule::process_event (PHCompositeNode * topNode) virtual
Standard function called at each event.
Reimplemented from SubsysReco.
int ExampleAnalysisModule::process_event (PHCompositeNode * topNode) virtual
Standard function called at each event.
Reimplemented from SubsysReco.
Definition at line 179 of file ExampleAnalysisModule.C.
References _eval_5x5_CEMC, _eval_run, _is_sim, assert, ExampleAnalysisModule::Eval_Cluster::average_col, ExampleAnalysisModule::Eval_Cluster::average_row, ExampleAnalysisModule::Eval_Run::beam_2CH_mm, ExampleAnalysisModule::Eval_Run::beam_2CV_mm, ExampleAnalysisModule::Eval_Run::beam_mom, ExampleAnalysisModule::Eval_Run::C1, ExampleAnalysisModule::Eval_Run::C2_sum, col, ExampleAnalysisModule::Eval_Run::event, Fun4AllReturnCodes::EVENT_OK, PHParameters::FillFrom(), find_max(), RawTower::get_bineta(), RawTower::get_binphi(), PHParameters::get_double_param(), RawTower::get_energy(), EventHeader::get_EvtSequence(), get_HistoManager(), RawTower::get_id(), PHG4Particle::get_px(), PHG4Particle::get_py(), PHG4Particle::get_pz(), EventHeader::get_RunNumber(), PHG4Particle::get_vtx_id(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), findNode::getClass(), Fun4AllHistoManager::getHisto(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTower(), RawTowerContainer::getTowers(), PHG4TruthInfoContainer::GetVtx(), ExampleAnalysisModule::Eval_Run::good_anti_e, ExampleAnalysisModule::Eval_Run::good_e, hNormalization, ExampleAnalysisModule::Eval_Run::hodo_h, ExampleAnalysisModule::Eval_Run::hodo_v, it, ExampleAnalysisModule::Eval_Cluster::max_col, ExampleAnalysisModule::Eval_Cluster::max_row, ExampleAnalysisModule::Eval_Run::reset(), ExampleAnalysisModule::Eval_Cluster::reset(), ExampleAnalysisModule::Eval_Cluster::reweight_clus_pol(), ExampleAnalysisModule::Eval_Run::run, ExampleAnalysisModule::Eval_Cluster::sum_E, ExampleAnalysisModule::Eval_Run::sum_E_CEMC, ExampleAnalysisModule::Eval_Run::sum_E_HCAL_IN, ExampleAnalysisModule::Eval_Run::sum_E_HCAL_OUT, T, ExampleAnalysisModule::Eval_Run::trigger_veto_pass, ExampleAnalysisModule::Eval_Run::truth_y, ExampleAnalysisModule::Eval_Run::truth_z, v, ExampleAnalysisModule::Eval_Run::valid_hodo_h, ExampleAnalysisModule::Eval_Run::valid_hodo_v, and verbosity.
Member Data Documentation
Eval_Cluster ExampleAnalysisModule::_eval_5x5_CEMC private
clusters of max 5x5 EMCal cluster. To be copied to output TTree T
Definition at line 225 of file ExampleAnalysisModule.h.
Referenced by ExampleAnalysisModule(), Init(), and process_event().
Eval_Run ExampleAnalysisModule::_eval_run private
run infomation. To be copied to output TTree T
Definition at line 222 of file ExampleAnalysisModule.h.
Referenced by ExampleAnalysisModule(), Init(), and process_event().
std::string ExampleAnalysisModule::_filename private
output root file name
Definition at line 216 of file ExampleAnalysisModule.h.
Referenced by End(), and Init().
unsigned long ExampleAnalysisModule::_ievent private
simple event counter
Definition at line 219 of file ExampleAnalysisModule.h.
Referenced by Init(), and InitRun().
bool ExampleAnalysisModule::_is_sim private
is processing simulation files?
Definition at line 206 of file ExampleAnalysisModule.h.
Referenced by is_sim(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype3/tutorial/ExampleAnalysisModule/ExampleAnalysisModule.h
analysis/blob/master/Prototype4/tutorial/ExampleAnalysisModule/ExampleAnalysisModule.h
analysis/blob/master/Prototype3/tutorial/ExampleAnalysisModule/ExampleAnalysisModule.C
analysis/blob/master/Prototype4/tutorial/ExampleAnalysisModule/ExampleAnalysisModule.C