Analysis Software: SvtxCluster_v1 Class Reference
SvtxCluster_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxCluster_v1.h>
Public Member Functions
SvtxCluster_v1 ()
virtual ~SvtxCluster_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
unsigned int get_id () const
void set_id (unsigned int id)
unsigned int get_layer () const
void set_layer (unsigned int layer)
float get_x () const
void set_x (float x)
float get_y () const
void set_y (float y)
float get_z () const
void set_z (float z)
float get_position (int coor) const
void set_position (int coor, float xi)
float get_e () const
void set_e (float e)
unsigned int get_adc () const
void set_adc (unsigned int adc)
float get_size (unsigned int i, unsigned int j) const
void set_size (unsigned int i, unsigned int j, float value)
float get_error (unsigned int i, unsigned int j) const
void set_error (unsigned int i, unsigned int j, float value)
void clear_hits ()
bool empty_hits ()
size_t size_hits ()
void insert_hit (unsigned int hit_id)
size_t erase_hit (unsigned int hit_id)
ConstHitIter begin_hits () const
ConstHitIter find_hit (unsigned int hitid) const
ConstHitIter end_hits () const
HitIter begin_hits ()
HitIter find_hit (unsigned int hitid)
HitIter end_hits ()
float get_phi_size () const
float get_z_size () const
float get_rphi_error () const
float get_phi_error () const
float get_z_error () const
Public Member Functions inherited from SvtxCluster
virtual ~SvtxCluster ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
unsigned int covar_index (unsigned int i, unsigned int j) const
ClassDef (SvtxCluster_v1, 1)
Private Attributes
unsigned int _id
unsigned int _layer
float _pos [3]
float _e
unsigned int _adc
float _size [6]
float _err [6]
std::set< unsigned int > _hit_ids
Additional Inherited Members
Public Types inherited from SvtxCluster
typedef std::set< unsigned int > HitSet
typedef std::set< unsigned int >
::const_iterator ConstHitIter
typedef std::set< unsigned int >
::iterator HitIter
Protected Member Functions inherited from SvtxCluster
SvtxCluster ()
ClassDef (SvtxCluster, 1)
Detailed Description
Definition at line 12 of file SvtxCluster_v1.h.
Constructor & Destructor Documentation
SvtxCluster_v1::SvtxCluster_v1 ()
Definition at line 13 of file SvtxCluster_v1.cc.
References _pos, i, j, set_error(), and set_size().
Referenced by CloneMe(), and Reset().
virtual SvtxCluster_v1::~SvtxCluster_v1 () inline virtual
Definition at line 16 of file SvtxCluster_v1.h.
Member Function Documentation
ConstHitIter SvtxCluster_v1::begin_hits () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 65 of file SvtxCluster_v1.h.
References _hit_ids.
Referenced by identify().
HitIter SvtxCluster_v1::begin_hits () inline virtual
Reimplemented from SvtxCluster.
Definition at line 68 of file SvtxCluster_v1.h.
References _hit_ids.
SvtxCluster_v1::ClassDef (SvtxCluster_v1 , 1) private
void SvtxCluster_v1::clear_hits () inline virtual
Reimplemented from SvtxCluster.
Definition at line 60 of file SvtxCluster_v1.h.
References _hit_ids.
PHObject* SvtxCluster_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxCluster.
Definition at line 23 of file SvtxCluster_v1.h.
References SvtxCluster_v1().
unsigned int SvtxCluster_v1::covar_index (unsigned int i, unsigned int j) const private
Definition at line 214 of file SvtxCluster_v1.cc.
References boost::swap().
Referenced by get_error(), get_size(), set_error(), and set_size().
bool SvtxCluster_v1::empty_hits () inline virtual
Reimplemented from SvtxCluster.
Definition at line 61 of file SvtxCluster_v1.h.
References _hit_ids.
ConstHitIter SvtxCluster_v1::end_hits () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 67 of file SvtxCluster_v1.h.
References _hit_ids.
Referenced by identify().
HitIter SvtxCluster_v1::end_hits () inline virtual
Reimplemented from SvtxCluster.
Definition at line 70 of file SvtxCluster_v1.h.
References _hit_ids.
size_t SvtxCluster_v1::erase_hit (unsigned int hit_id) inline virtual
Reimplemented from SvtxCluster.
Definition at line 64 of file SvtxCluster_v1.h.
References _hit_ids.
ConstHitIter SvtxCluster_v1::find_hit (unsigned int hitid) const inline virtual
Reimplemented from SvtxCluster.
Definition at line 66 of file SvtxCluster_v1.h.
References _hit_ids.
HitIter SvtxCluster_v1::find_hit (unsigned int hitid) inline virtual
Reimplemented from SvtxCluster.
Definition at line 69 of file SvtxCluster_v1.h.
References _hit_ids.
unsigned int SvtxCluster_v1::get_adc () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 48 of file SvtxCluster_v1.h.
References _adc.
Referenced by identify().
float SvtxCluster_v1::get_e () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 45 of file SvtxCluster_v1.h.
References _e.
Referenced by identify().
float SvtxCluster_v1::get_error (unsigned int i, unsigned int j) const virtual
Reimplemented from SvtxCluster.
Definition at line 126 of file SvtxCluster_v1.cc.
References _err, and covar_index().
Referenced by get_rphi_error(), get_z_error(), identify(), and isValid().
unsigned int SvtxCluster_v1::get_id () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 27 of file SvtxCluster_v1.h.
References _id.
Referenced by identify().
unsigned int SvtxCluster_v1::get_layer () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 30 of file SvtxCluster_v1.h.
References _layer.
Referenced by identify().
float SvtxCluster_v1::get_phi_error () const virtual
Reimplemented from SvtxCluster.
Definition at line 169 of file SvtxCluster_v1.cc.
References _pos, and get_rphi_error().
float SvtxCluster_v1::get_phi_size () const virtual
Reimplemented from SvtxCluster.
Definition at line 131 of file SvtxCluster_v1.cc.
References _pos, get_size(), i, j, and phi.
Referenced by identify().
float SvtxCluster_v1::get_position (int coor) const inline virtual
Reimplemented from SvtxCluster.
Definition at line 42 of file SvtxCluster_v1.h.
References _pos.
Referenced by identify().
float SvtxCluster_v1::get_rphi_error () const virtual
Reimplemented from SvtxCluster.
Definition at line 176 of file SvtxCluster_v1.cc.
References _pos, get_error(), i, j, and phi.
Referenced by get_phi_error().
float SvtxCluster_v1::get_size (unsigned int i, unsigned int j) const virtual
Reimplemented from SvtxCluster.
Definition at line 115 of file SvtxCluster_v1.cc.
References _size, and covar_index().
Referenced by get_phi_size(), get_z_size(), identify(), and isValid().
float SvtxCluster_v1::get_x () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 33 of file SvtxCluster_v1.h.
References _pos.
float SvtxCluster_v1::get_y () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 36 of file SvtxCluster_v1.h.
References _pos.
float SvtxCluster_v1::get_z () const inline virtual
Reimplemented from SvtxCluster.
Definition at line 39 of file SvtxCluster_v1.h.
References _pos.
float SvtxCluster_v1::get_z_error () const virtual
Reimplemented from SvtxCluster.
Definition at line 209 of file SvtxCluster_v1.cc.
References get_error().
float SvtxCluster_v1::get_z_size () const virtual
Reimplemented from SvtxCluster.
Definition at line 164 of file SvtxCluster_v1.cc.
References get_size().
Referenced by identify().
void SvtxCluster_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxCluster.
Definition at line 35 of file SvtxCluster_v1.cc.
References begin_hits(), end_hits(), get_adc(), get_e(), get_error(), get_id(), get_layer(), get_phi_size(), get_position(), get_size(), and get_z_size().
void SvtxCluster_v1::insert_hit (unsigned int hit_id) inline virtual
Reimplemented from SvtxCluster.
Definition at line 63 of file SvtxCluster_v1.h.
References _hit_ids.
int SvtxCluster_v1::isValid () const virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxCluster.
Definition at line 86 of file SvtxCluster_v1.cc.
References _adc, _e, _hit_ids, _id, _layer, _pos, get_error(), get_size(), i, and j.
void SvtxCluster_v1::Reset () inline virtual
Clear Event.
Reimplemented from SvtxCluster.
Definition at line 21 of file SvtxCluster_v1.h.
References SvtxCluster_v1().
void SvtxCluster_v1::set_adc (unsigned int adc) inline virtual
Reimplemented from SvtxCluster.
Definition at line 49 of file SvtxCluster_v1.h.
References _adc.
void SvtxCluster_v1::set_e (float e) inline virtual
Reimplemented from SvtxCluster.
Definition at line 46 of file SvtxCluster_v1.h.
References _e.
void SvtxCluster_v1::set_error (unsigned int i, unsigned int j, float value) virtual
Reimplemented from SvtxCluster.
Definition at line 120 of file SvtxCluster_v1.cc.
References _err, covar_index(), and value.
Referenced by SvtxCluster_v1().
void SvtxCluster_v1::set_id (unsigned int id) inline virtual
Reimplemented from SvtxCluster.
Definition at line 28 of file SvtxCluster_v1.h.
References _id.
void SvtxCluster_v1::set_layer (unsigned int layer) inline virtual
Reimplemented from SvtxCluster.
Definition at line 31 of file SvtxCluster_v1.h.
References _layer.
void SvtxCluster_v1::set_position (int coor, float xi) inline virtual
Reimplemented from SvtxCluster.
Definition at line 43 of file SvtxCluster_v1.h.
References _pos.
void SvtxCluster_v1::set_size (unsigned int i, unsigned int j, float value) virtual
Reimplemented from SvtxCluster.
Definition at line 109 of file SvtxCluster_v1.cc.
References _size, covar_index(), and value.
Referenced by SvtxCluster_v1().
void SvtxCluster_v1::set_x (float x) inline virtual
Reimplemented from SvtxCluster.
Definition at line 34 of file SvtxCluster_v1.h.
References _pos, and x.
void SvtxCluster_v1::set_y (float y) inline virtual
Reimplemented from SvtxCluster.
Definition at line 37 of file SvtxCluster_v1.h.
References _pos, and y.
void SvtxCluster_v1::set_z (float z) inline virtual
Reimplemented from SvtxCluster.
Definition at line 40 of file SvtxCluster_v1.h.
References _pos, and z.
size_t SvtxCluster_v1::size_hits () inline virtual
Reimplemented from SvtxCluster.
Definition at line 62 of file SvtxCluster_v1.h.
References _hit_ids.
Member Data Documentation
unsigned int SvtxCluster_v1::_adc private
Definition at line 88 of file SvtxCluster_v1.h.
Referenced by get_adc(), isValid(), and set_adc().
float SvtxCluster_v1::_e private
Definition at line 87 of file SvtxCluster_v1.h.
Referenced by get_e(), isValid(), and set_e().
float SvtxCluster_v1::_err[6] private
Definition at line 90 of file SvtxCluster_v1.h.
Referenced by get_error(), and set_error().
std::set<unsigned int> SvtxCluster_v1::_hit_ids private
Definition at line 91 of file SvtxCluster_v1.h.
Referenced by begin_hits(), clear_hits(), empty_hits(), end_hits(), erase_hit(), find_hit(), insert_hit(), isValid(), and size_hits().
unsigned int SvtxCluster_v1::_id private
Definition at line 84 of file SvtxCluster_v1.h.
Referenced by get_id(), isValid(), and set_id().
unsigned int SvtxCluster_v1::_layer private
Definition at line 85 of file SvtxCluster_v1.h.
Referenced by get_layer(), isValid(), and set_layer().
float SvtxCluster_v1::_pos[3] private
Definition at line 86 of file SvtxCluster_v1.h.
Referenced by get_phi_error(), get_phi_size(), get_position(), get_rphi_error(), get_x(), get_y(), get_z(), isValid(), set_position(), set_x(), set_y(), set_z(), and SvtxCluster_v1().
float SvtxCluster_v1::_size[6] private
Definition at line 89 of file SvtxCluster_v1.h.
Referenced by get_size(), and set_size().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxCluster_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxCluster_v1.cc