Analysis Software: Conversion Class Reference
Conversion Class Reference
#include <analysis/blob/master/PhotonConversion/truthconversion/Conversion.h>
Public Member Functions
Conversion ()
Conversion (SvtxTrackEval *trackeval, int verbosity=0)
Conversion (PHG4VtxPoint *vtx, int verbosity=0)
Conversion (PHG4VtxPoint *vtx, SvtxTrackEval *trackeval, int verbosity=0)
~Conversion ()
void setElectron (PHG4Particle *e)
void setTrackEval (SvtxTrackEval *trackeval)
void setVtx (PHG4VtxPoint *vtx)
PHG4VtxPoint * getVtx () const
bool isComplete () const
true if both electrons and photon are set
bool hasPair () const
check if both electrons are initialized
bool setParent (PHG4Particle *parent)
sets the photon
PHG4Particle * e1 =NULL
PHG4Particle * e2 =NULL
PHG4Particle * photon =NULL
PHG4Particle * primaryPhoton =NULL
PHG4VtxPoint * vtx =NULL
SvtxVertex * truthSvtxVtx =NULL
SvtxTrack * reco1 =NULL
SvtxTrack * reco2 =NULL
SvtxTrackEval * trackeval =NULL
SvtxClusterMap * _svtxClusterMap =NULL
genfit::GFRaveVertex * recoVertex =NULL
TLorentzVector * recoPhoton =NULL
std::pair< PHGenFit::Track
*, PHGenFit::Track * > _refit_phgf_tracks
std::pair< unsigned, unsigned > pairTruthReco1
std::pair< unsigned, unsigned > pairTruthReco2
int embedID =0
int verbosity
int sourceId
static const int _kNSiliconLayer =7
hardcoded
static const float _kElectronRestM =.0005109989461
void setPrimaryPhoton (PHG4Particle *parent, PHG4TruthInfoContainer *truthinfo)
callslink setParent} photon is set with
int recoCount () const
PHG4Particle * getElectron ()
calls setElectron() then returns e1
PHG4Particle * getElectron () const
PHG4Particle * getPositron ()
calls setElectron() if true returns e2 else returns e1
PHG4Particle * getPositron () const
PHG4Particle * getPhoton () const
PHG4Particle * getPrimaryPhoton () const
int getEmbed () const
void setEmbed (int embedID)
void setSourceId (int source)
int getSourceId () const
genfit::GFRaveVertex * getRecoVtx () const
float trackDEta () const
float trackDPhi () const
float minTrackpT ()
std::pair< float, float > getTrackpTs ()
std::pair< float, float > getTrackEtas ()
std::pair< float, float > getTrackPhis ()
std::pair< SvtxTrack
*, SvtxTrack * > getRecoTracks () const
SvtxTrack * getRecoTrack (unsigned truthID) const
void setClusterMap (SvtxClusterMap *cmap)
int setVerbosity (int v)
int get_cluster_id ()
int get_cluster_id () const
int get_cluster_id (SvtxTrackEval *trackeval)
std::pair< int, int > get_cluster_ids ()
int setRecoTracks (SvtxTrackEval *trackeval)
int setRecoTracks ()
void setRecoTrack (int truthID, SvtxTrack *recoTrack)
bool setElectron ()
int trackDLayer (SvtxClusterMap *cmap, SvtxHitMap *hitmap)
int trackDLayer (TrkrClusterContainer *)
int firstLayer (SvtxClusterMap *cmap, SvtxHitMap *hitmap)
int firstLayer (TrkrClusterContainer *)
bool hasSilicon (SvtxClusterMap *)
double approachDistance () const
double dist (PHG4VtxPoint *vtx, SvtxClusterMap *cmap)
double dist (TVector3 *vtx, SvtxClusterMap *cmap)
double dist (TVector3 *vtx, TrkrClusterContainer *cmap)
float minDca ()
float vtxTrackRPhi (TVector3 vertpos)
float vtxTrackRZ (TVector3 vertpos)
TLorentzVector * setRecoPhoton ()
constructs a tlv for a photon by adding the tlvs for the reco tracks
TLorentzVector * getRecoPhoton ()
TLorentzVector * getRefitRecoPhoton ()
Uses the _refit_phgf_tracks to set recoPhoton. Will delete any existing recoPhoton.
PHG4Particle * getTruthPhoton (PHG4TruthInfoContainer *)
std::pair< PHGenFit::Track
*, PHGenFit::Track * > refitTracks (SVReco *vertexer, SvtxVertex *recoVtx)
Uses recoVertex and.
std::pair< PHGenFit::Track
*, PHGenFit::Track * > refitTracks (SVReco *vertexer)
Uses recoVertex and.
std::pair< PHGenFit::Track
*, PHGenFit::Track * > refitTracksTruthVtx (SVReco *vertexer)
Uses the truth vertex and SVReco to improve the fit of reco1 and reco2.
std::pair< PHGenFit::Track
*, PHGenFit::Track * > refitTracksTruthVtx (SVReco *vertexer, SvtxVertex *seedVtx)
Uses the truth vertex and SVReco to improve the fit of reco1 and reco2. Uses.
genfit::GFRaveVertex * getSecondaryVertex (SVReco *vertexer)
std::pair< PHGenFit::Track
*, PHGenFit::Track * > getPHGFTracks (SVReco *vertexer)
get the PHGF version of reco1 and reco2. If not possible
std::pair< TLorentzVector
*, TLorentzVector * > getRecoTlvs ()
std::pair< TLorentzVector
*, TLorentzVector * > getRefitRecoTlvs ()
std::pair< PHG4Particle
*, PHG4Particle * > getParticlesMissingTrack ()
genfit::GFRaveVertex * correctSecondaryVertex (VtxRegressor *regressor)
Uses the specified TMVA method to update and.
void printTruth ()
print the truth info calls e1->identify(), e2->identify(), vtx->identify(), photon->identify()
void printReco ()
print the reco info calls reco1->identify(), reco2->identify(), recoVertex->identify(), recoPhoton->print()
void PrintPhotonRecoInfo ()
print the info relating to photon reconstruction
void PrintPhotonRecoInfo (TLorentzVector *tlv_photon, TLorentzVector *tlv_electron, TLorentzVector *tlv_positron, float mass)
static float trackDEta (SvtxTrack *reco1, SvtxTrack *reco2)
static float trackDPhi (SvtxTrack *reco1, SvtxTrack *reco2)
static int trackDLayer (TrkrClusterContainer *, SvtxTrack *, SvtxTrack *)
static double approachDistance (SvtxTrack *, SvtxTrack *)
static float vtxTrackRPhi (TVector3 vertpos, SvtxTrack *, SvtxTrack *)
static float vtxTrackRZ (TVector3 vertpos, SvtxTrack *, SvtxTrack *)
static TLorentzVector * getRecoPhoton (SvtxTrack *reco1, SvtxTrack *reco2)
static genfit::GFRaveVertex * correctSecondaryVertex (VtxRegressor *regressor, genfit::GFRaveVertex *, SvtxTrack *reco1, SvtxTrack *reco2)
static double InTwoPi (double phi)
static double DeltaPhi (double phi1, double phi2)
static float vtxTrackRZ (TVector3 recoVertPos, SvtxTrack *track)
helper function
static float vtxTrackRPhi (TVector3 recoVertPos, SvtxTrack *track)
helper function
void PHG4VtxPointToSvtxVertex ()
void PHG4VtxPointToSvtxVertex (SvtxVertex *seedVtx)
Detailed Description
Definition at line 37 of file Conversion.h.
Constructor & Destructor Documentation
Conversion::Conversion () inline
Definition at line 40 of file Conversion.h.
References verbosity.
Conversion::Conversion (SvtxTrackEval * trackeval, int verbosity = 0)
Definition at line 20 of file Conversion.cc.
References _refit_phgf_tracks, pairTruthReco1, pairTruthReco2, trackeval, and verbosity.
Conversion::Conversion (PHG4VtxPoint * vtx, int verbosity = 0)
Definition at line 30 of file Conversion.cc.
References _refit_phgf_tracks, pairTruthReco1, pairTruthReco2, verbosity, and vtx.
Conversion::Conversion (PHG4VtxPoint * vtx, SvtxTrackEval * trackeval, int verbosity = 0)
Definition at line 41 of file Conversion.cc.
References _refit_phgf_tracks, pairTruthReco1, pairTruthReco2, trackeval, verbosity, and vtx.
Conversion::~Conversion ()
Definition at line 53 of file Conversion.cc.
References _refit_phgf_tracks, recoPhoton, recoVertex, and truthSvtxVtx.
Member Function Documentation
double Conversion::approachDistance () const
distance between two closest points on the reco tracks
Returns
-1 if tracks are not set
Definition at line 623 of file Conversion.cc.
References c, d, SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), reco1, reco2, recoCount(), and v.
Referenced by TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
double Conversion::approachDistance (SvtxTrack * reco1, SvtxTrack * reco2) static
Definition at line 666 of file Conversion.cc.
References c, d, SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_y(), SvtxTrack::get_z(), and v.
genfit::GFRaveVertex * Conversion::correctSecondaryVertex (VtxRegressor * regressor)
Uses the specified TMVA method to update and.
Returns
recoVertex
Definition at line 781 of file Conversion.cc.
References i, reco1, reco2, recoCount(), recoVertex, VtxRegressor::regress(), and tracks().
Referenced by TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
genfit::GFRaveVertex * Conversion::correctSecondaryVertex (VtxRegressor * regressor, genfit::GFRaveVertex * recoVertex, SvtxTrack * reco1, SvtxTrack * reco2) static
Definition at line 806 of file Conversion.cc.
References i, recoVertex, VtxRegressor::regress(), and tracks().
static double Conversion::DeltaPhi (double phi1, double phi2) inline static
Returns the difference between two angles in 0 to pi.
Definition at line 250 of file Conversion.h.
References InTwoPi().
Referenced by trackDPhi().
double Conversion::dist (PHG4VtxPoint * vtx, SvtxClusterMap * cmap)
Returns
distance in xyz space between the vertex and the closest track hit
Definition at line 535 of file Conversion.cc.
References SvtxTrack::begin_clusters(), c2, SvtxClusterMap::get(), PHG4VtxPoint::get_x(), SvtxCluster::get_x(), PHG4VtxPoint::get_y(), SvtxCluster::get_y(), PHG4VtxPoint::get_z(), SvtxCluster::get_z(), r1, r2, reco1, and reco2.
Referenced by pyhimult(), and pymult().
double Conversion::dist (TVector3 * vtx, SvtxClusterMap * cmap)
Definition at line 547 of file Conversion.cc.
References SvtxTrack::begin_clusters(), c2, SvtxClusterMap::get(), SvtxCluster::get_x(), SvtxCluster::get_y(), SvtxCluster::get_z(), r1, r2, reco1, and reco2.
double Conversion::dist (TVector3 * vtx, TrkrClusterContainer * cmap)
Definition at line 559 of file Conversion.cc.
References SvtxTrack::begin_cluster_keys(), c2, TrkrClusterContainer::findCluster(), TrkrCluster::getX(), TrkrCluster::getY(), TrkrCluster::getZ(), r1, r2, reco1, and reco2.
int Conversion::firstLayer (SvtxClusterMap * cmap, SvtxHitMap * hitmap)
Returns
the first layer the associated reco clusters hit
Definition at line 488 of file Conversion.cc.
References SvtxTrack::begin_clusters(), SvtxCluster::begin_hits(), c2, SvtxHitMap::get(), SvtxClusterMap::get(), SvtxHit::get_layer(), SvtxCluster::get_layer(), h1, h2, reco1, reco2, and recoCount().
Referenced by TruthConversionEval::recordConversion().
int Conversion::firstLayer (TrkrClusterContainer * clusterMap)
Definition at line 511 of file Conversion.cc.
References SvtxTrack::begin_cluster_keys(), c2, TrkrClusterContainer::findCluster(), TrkrCluster::getClusKey(), TrkrDefs::getLayer(), reco1, reco2, and recoCount().
int Conversion::get_cluster_id ()
Finds the cluster associated with reco1 if the trackeval was not previously set it needs to be set now if reco1 not set will attempt to set
Returns
-1 if no cluster is found
Definition at line 339 of file Conversion.cc.
References assert, SvtxTrackEval::best_track_from(), e1, SvtxTrack::get_cal_cluster_id(), reco1, and trackeval.
int Conversion::get_cluster_id () const
Finds the cluster associated with reco1
Returns
-1 if no cluster is found
Definition at line 350 of file Conversion.cc.
References SvtxTrack::get_cal_cluster_id(), and reco1.
int Conversion::get_cluster_id (SvtxTrackEval * trackeval)
Finds the cluster associated with reco1 if reco1 not set will attempt to set
Returns
-1 if no cluster is found
Definition at line 357 of file Conversion.cc.
References SvtxTrackEval::best_track_from(), e1, SvtxTrack::get_cal_cluster_id(), reco1, and trackeval.
std::pair< int, int > Conversion::get_cluster_ids ()
Returns
the cluster ID for both tracks if both are set. *If one is set pair.first will be the id. *the unset tracks get -1 as the cluster id
Definition at line 370 of file Conversion.cc.
References SvtxTrack::get_cal_cluster_id(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::recordConversion().
PHG4Particle * Conversion::getElectron ()
calls setElectron() then returns e1
Definition at line 118 of file Conversion.cc.
References e1, and setElectron().
PHG4Particle* Conversion::getElectron () const inline
Returns
e1
Definition at line 94 of file Conversion.h.
References e1.
int Conversion::getEmbed () const inline
Definition at line 101 of file Conversion.h.
References embedID.
std::pair<PHG4Particle*,PHG4Particle*> Conversion::getParticlesMissingTrack ()
Returns
the truth particle(s) that are missing reco tracks fill NULL if the particles have a reco track in the case that only one is missing a track it will be the first value of the pair
std::pair< PHGenFit::Track *, PHGenFit::Track * > Conversion::getPHGFTracks (SVReco * vertexer)
get the PHGF version of reco1 and reco2. If not possible
Returns
NULL for that track.
Definition at line 831 of file Conversion.cc.
References SVReco::getPHGFTrack(), r, reco1, and reco2.
PHG4Particle* Conversion::getPhoton () const inline
Definition at line 99 of file Conversion.h.
References photon.
PHG4Particle * Conversion::getPositron ()
calls setElectron() if true returns e2 else returns e1
Definition at line 123 of file Conversion.cc.
References e1, e2, and setElectron().
PHG4Particle* Conversion::getPositron () const inline
Returns
e2
Definition at line 98 of file Conversion.h.
References e2.
PHG4Particle* Conversion::getPrimaryPhoton () const inline
Definition at line 100 of file Conversion.h.
References primaryPhoton.
TLorentzVector * Conversion::getRecoPhoton ()
Returns
the constructed tlv does not return ownserhip
Definition at line 262 of file Conversion.cc.
References setRecoPhoton().
Referenced by TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
TLorentzVector * Conversion::getRecoPhoton (SvtxTrack * reco1, SvtxTrack * reco2) static
Returns
the addition of respective tlvs,
ownership
Definition at line 266 of file Conversion.cc.
References _kElectronRestM, SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), and SvtxTrack::get_pz().
std::pair< TLorentzVector *, TLorentzVector * > Conversion::getRecoTlvs ()
Definition at line 285 of file Conversion.cc.
References _kElectronRestM, SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), r, reco1, reco2, and recoCount().
SvtxTrack * Conversion::getRecoTrack (unsigned truthID) const
Returns
the reco track associated with the
Parameters
truthID
Definition at line 231 of file Conversion.cc.
References SvtxTrack::get_id(), pairTruthReco1, pairTruthReco2, reco1, and reco2.
Referenced by PrintPhotonRecoInfo().
std::pair<SvtxTrack*,SvtxTrack*> Conversion::getRecoTracks () const inline
Definition at line 128 of file Conversion.h.
References reco1, and reco2.
genfit::GFRaveVertex* Conversion::getRecoVtx () const inline
Definition at line 106 of file Conversion.h.
References recoVertex.
TLorentzVector * Conversion::getRefitRecoPhoton ()
Uses the _refit_phgf_tracks to set recoPhoton. Will delete any existing recoPhoton.
Returns
NULL if either _refit_phgf_tracks are NULL.
Definition at line 275 of file Conversion.cc.
References getRefitRecoTlvs(), and recoPhoton.
Referenced by TruthConversionEval::recordConversion().
std::pair< TLorentzVector *, TLorentzVector * > Conversion::getRefitRecoTlvs ()
Definition at line 318 of file Conversion.cc.
References _kElectronRestM, _refit_phgf_tracks, and r.
Referenced by getRefitRecoPhoton().
genfit::GFRaveVertex * Conversion::getSecondaryVertex (SVReco * vertexer)
Returns
the secondary vertex fit with reco1 and reco2
Definition at line 772 of file Conversion.cc.
References SVReco::findSecondaryVertex(), reco1, reco2, recoCount(), and recoVertex.
Referenced by TruthConversionEval::recordConversion(), and refitTracks().
int Conversion::getSourceId () const inline
Definition at line 105 of file Conversion.h.
References sourceId.
std::pair< float, float > Conversion::getTrackEtas ()
Definition at line 737 of file Conversion.cc.
References SvtxTrack::get_eta(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::recordConversion().
std::pair< float, float > Conversion::getTrackPhis ()
Definition at line 751 of file Conversion.cc.
References SvtxTrack::get_phi(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::recordConversion().
std::pair< float, float > Conversion::getTrackpTs ()
Definition at line 723 of file Conversion.cc.
References SvtxTrack::get_pt(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::recordConversion().
PHG4Particle * Conversion::getTruthPhoton (PHG4TruthInfoContainer * truthinfo)
Returns
NULL if not valid conversion else return photon
Definition at line 334 of file Conversion.cc.
References photon.
PHG4VtxPoint* Conversion::getVtx () const inline
Definition at line 51 of file Conversion.h.
References vtx.
Referenced by TruthConversionEval::recordConversion().
bool Conversion::hasPair () const inline
check if both electrons are initialized
Definition at line 63 of file Conversion.h.
References e1, and e2.
Referenced by setElectron().
bool Conversion::hasSilicon (SvtxClusterMap * svtxClusterMap)
Returns
true if there are any silicon hits for the conversion. Is deprecated.
Definition at line 390 of file Conversion.cc.
References _kNSiliconLayer, SvtxTrack::begin_clusters(), c2, SvtxClusterMap::get(), SvtxCluster::get_layer(), reco1, reco2, and recoCount().
static double Conversion::InTwoPi (double phi) inline static
Returns the equivalent angle in the range 0 to 2pi.
Definition at line 239 of file Conversion.h.
References phi.
Referenced by DeltaPhi().
bool Conversion::isComplete () const inline
true if both electrons and photon are set
Definition at line 53 of file Conversion.h.
References e1, e2, and photon.
float Conversion::minDca ()
Returns
dca of the reco track with the lower dca
Definition at line 465 of file Conversion.cc.
References SvtxTrack::get_dca(), reco1, and reco2.
Referenced by TruthConversionEval::recordConversion().
float Conversion::minTrackpT ()
Returns
the minimun reco track pT
Definition at line 701 of file Conversion.cc.
References SvtxTrack::get_pt(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::recordConversion().
void Conversion::PHG4VtxPointToSvtxVertex () private
Initializes truthSvtxVtx with x,y,x,t from the PHG4VtxPoint. *Chisq and ndof are set to 1. *The tracks are set with reco1 and reco2. *The errors are set to a randomish positive-definite matrix
Definition at line 884 of file Conversion.cc.
References d, g, SvtxTrack::get_id(), PHG4VtxPoint::get_t(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), SVM_v1::h, i, SvtxVertex::insert_track(), reco1, reco2, recoCount(), SvtxVertex::set_chisq(), SvtxVertex::set_error(), SvtxVertex::set_ndof(), SvtxVertex::set_t0(), SvtxVertex::set_x(), SvtxVertex::set_y(), SvtxVertex::set_z(), truthSvtxVtx, and vtx.
Referenced by refitTracksTruthVtx().
void Conversion::PHG4VtxPointToSvtxVertex (SvtxVertex * seedVtx) private
Initializes truthSvtxVtx with x,y,x,t from the PHG4VtxPoint. *Chisq and ndof are set to 1. *The tracks are set with reco1 and reco2. *The errors are set to the errors of the seedVtx. The primary vtx is suggested.
Definition at line 921 of file Conversion.cc.
References SvtxVertex::get_error(), SvtxTrack::get_id(), PHG4VtxPoint::get_t(), PHG4VtxPoint::get_x(), PHG4VtxPoint::get_y(), PHG4VtxPoint::get_z(), i, SvtxVertex::insert_track(), j, reco1, reco2, recoCount(), SvtxVertex::set_chisq(), SvtxVertex::set_error(), SvtxVertex::set_ndof(), SvtxVertex::set_t0(), SvtxVertex::set_x(), SvtxVertex::set_y(), SvtxVertex::set_z(), truthSvtxVtx, and vtx.
void Conversion::PrintPhotonRecoInfo ()
print the info relating to photon reconstruction
Definition at line 586 of file Conversion.cc.
References e1, e2, PHG4Particle::get_track_id(), getRecoTrack(), PHG4Particle::identify(), photon, and recoPhoton.
Referenced by TruthConversionEval::recordConversion().
void Conversion::PrintPhotonRecoInfo (TLorentzVector * tlv_photon, TLorentzVector * tlv_electron, TLorentzVector * tlv_positron, float mass)
Definition at line 597 of file Conversion.cc.
References SvtxTrack::identify(), reco1, reco2, and recoPhoton.
void Conversion::printReco ()
print the reco info calls reco1->identify(), reco2->identify(), recoVertex->identify(), recoPhoton->print()
Definition at line 578 of file Conversion.cc.
References PHG4VtxPoint::identify(), SvtxTrack::identify(), PHG4Particle::identify(), photon, reco1, reco2, and vtx.
void Conversion::printTruth ()
print the truth info calls e1->identify(), e2->identify(), vtx->identify(), photon->identify()
Definition at line 571 of file Conversion.cc.
References e1, e2, PHG4Particle::identify(), recoPhoton, recoVertex, and vtx.
int Conversion::recoCount () const inline
Returns
the number of matched reco tracks
Definition at line 79 of file Conversion.h.
References r, reco1, and reco2.
Referenced by approachDistance(), correctSecondaryVertex(), firstLayer(), get_cluster_ids(), getRecoTlvs(), getSecondaryVertex(), getTrackEtas(), getTrackPhis(), getTrackpTs(), hasSilicon(), minTrackpT(), PHG4VtxPointToSvtxVertex(), TruthConversionEval::recordConversion(), trackDEta(), trackDLayer(), and trackDPhi().
std::pair< PHGenFit::Track *, PHGenFit::Track * > Conversion::refitTracks (SVReco * vertexer, SvtxVertex * recoVtx)
Uses recoVertex and.
Parameters
vertexer to make _refit_phgf_tracks. Sets recoVertex to
recoVtx
Definition at line 870 of file Conversion.cc.
References _refit_phgf_tracks, reco1, reco2, and SVReco::refitTrack().
std::pair< PHGenFit::Track *, PHGenFit::Track * > Conversion::refitTracks (SVReco * vertexer)
Uses recoVertex and.
Parameters
vertexer to make _refit_phgf_tracks. If recoVertex is not set call getSecondaryVertex(SVReco* vertexer).
Definition at line 855 of file Conversion.cc.
References _refit_phgf_tracks, getSecondaryVertex(), reco1, reco2, recoVertex, and SVReco::refitTrack().
std::pair< PHGenFit::Track *, PHGenFit::Track * > Conversion::refitTracksTruthVtx (SVReco * vertexer)
Uses the truth vertex and SVReco to improve the fit of reco1 and reco2.
Definition at line 847 of file Conversion.cc.
References _refit_phgf_tracks, PHG4VtxPointToSvtxVertex(), reco1, reco2, SVReco::refitTrack(), and truthSvtxVtx.
std::pair< PHGenFit::Track *, PHGenFit::Track * > Conversion::refitTracksTruthVtx (SVReco * vertexer, SvtxVertex * seedVtx)
Uses the truth vertex and SVReco to improve the fit of reco1 and reco2. Uses.
Parameters
seedVtx to set the uncertainies on the truth vertex.
Definition at line 838 of file Conversion.cc.
References _refit_phgf_tracks, PHG4VtxPointToSvtxVertex(), reco1, reco2, SVReco::refitTrack(), and truthSvtxVtx.
void Conversion::setClusterMap (SvtxClusterMap * cmap) inline
set the reco maps used for trackDEta, trackDLayer,hasSilicon *Note that all use of SvtxClusterMap is now deprecated
Definition at line 135 of file Conversion.h.
References _svtxClusterMap.
void Conversion::setElectron (PHG4Particle * e)
sets the daughters of the conversion use this to set the electron and positron initializes both points but does not determine charge
Definition at line 67 of file Conversion.cc.
References e1, e2, PHG4Particle::get_track_id(), pairTruthReco1, pairTruthReco2, and verbosity.
bool Conversion::setElectron ()
Sets the negative charge to e1
Returns
false otherwise will print warnings if something is wrong with the Conversion
Definition at line 86 of file Conversion.cc.
References e1, e2, PHG4Particle::get_pid(), hasPair(), and verbosity.
Referenced by getElectron(), getPositron(), setRecoTrack(), and setRecoTracks().
void Conversion::setEmbed (int embedID) inline
Definition at line 103 of file Conversion.h.
References embedID.
bool Conversion::setParent (PHG4Particle * parent)
sets the photon
Returns
true if there are no errors
Definition at line 132 of file Conversion.cc.
References photon, and r.
Referenced by setPrimaryPhoton().
void Conversion::setPrimaryPhoton (PHG4Particle * parent, PHG4TruthInfoContainer * truthinfo)
callslink setParent} photon is set with
Parameters
parent and the primaryPhoton is set with the primary particle associated with
parent
Definition at line 142 of file Conversion.cc.
References PHG4Particle::get_primary_id(), PHG4Particle::get_track_id(), PHG4TruthInfoContainer::GetParticle(), photon, primaryPhoton, and setParent().
TLorentzVector * Conversion::setRecoPhoton ()
constructs a tlv for a photon by adding the tlvs for the reco tracks
Definition at line 249 of file Conversion.cc.
References _kElectronRestM, SvtxTrack::get_p(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), reco1, reco2, and recoPhoton.
Referenced by getRecoPhoton(), and setRecoTracks().
void Conversion::setRecoTrack (int truthID, SvtxTrack * recoTrack)
call setElectron() then setRecoTrakcs then set the reco track for the truth particle that corresponds to
Parameters
truthID if it does not already have a reco track
Definition at line 152 of file Conversion.cc.
References e1, e2, SvtxTrack::get_id(), PHG4Particle::get_track_id(), pairTruthReco1, pairTruthReco2, reco1, reco2, setElectron(), and setRecoTracks().
int Conversion::setRecoTracks (SvtxTrackEval * trackeval)
match the truth particles to reco tracks if the trackeval was not previously set it needs to be set now
Returns
the number of matched tracks [0,2]
Definition at line 170 of file Conversion.cc.
References SvtxTrackEval::best_track_from(), e1, e2, SvtxTrack::get_id(), PHG4Particle::get_track_id(), pairTruthReco1, pairTruthReco2, r, reco1, reco2, setElectron(), setRecoPhoton(), and trackeval.
int Conversion::setRecoTracks ()
Definition at line 201 of file Conversion.cc.
References assert, SvtxTrackEval::best_track_from(), e1, e2, SvtxTrack::get_id(), PHG4Particle::get_track_id(), pairTruthReco1, pairTruthReco2, r, reco1, reco2, setRecoPhoton(), and trackeval.
Referenced by setRecoTrack().
void Conversion::setSourceId (int source) inline
Definition at line 104 of file Conversion.h.
References sourceId.
void Conversion::setTrackEval (SvtxTrackEval * trackeval) inline
Definition at line 49 of file Conversion.h.
References trackeval.
int Conversion::setVerbosity (int v) inline
Definition at line 138 of file Conversion.h.
References v, and verbosity.
void Conversion::setVtx (PHG4VtxPoint * vtx) inline
Definition at line 50 of file Conversion.h.
References vtx.
float Conversion::trackDEta () const
Finds the delta eta of the reco tracks.
Returns
-1 if reco tracks are not set
Definition at line 658 of file Conversion.cc.
References SvtxTrack::get_eta(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
float Conversion::trackDEta (SvtxTrack * reco1, SvtxTrack * reco2) static
Definition at line 697 of file Conversion.cc.
References SvtxTrack::get_eta().
int Conversion::trackDLayer (SvtxClusterMap * cmap, SvtxHitMap * hitmap)
Return the difference in layers of the first hits of the reco track
Returns
-1 if reco tracks are not set
Definition at line 452 of file Conversion.cc.
References SvtxTrack::begin_clusters(), SvtxCluster::begin_hits(), c2, SvtxHitMap::get(), SvtxClusterMap::get(), SvtxHit::get_layer(), h1, h2, reco1, reco2, and recoCount().
Referenced by TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
int Conversion::trackDLayer (TrkrClusterContainer * clusterMap)
Definition at line 470 of file Conversion.cc.
References SvtxTrack::begin_cluster_keys(), c2, TrkrClusterContainer::findCluster(), TrkrCluster::getClusKey(), TrkrDefs::getLayer(), reco1, reco2, and recoCount().
int Conversion::trackDLayer (TrkrClusterContainer * clusterMap, SvtxTrack * reco1, SvtxTrack * reco2) static
Definition at line 480 of file Conversion.cc.
References SvtxTrack::begin_cluster_keys(), c2, TrkrClusterContainer::findCluster(), TrkrCluster::getClusKey(), and TrkrDefs::getLayer().
float Conversion::trackDPhi () const inline
Finds the delta phi of the reco tracks.
Returns
-1 if reco tracks are not set
Definition at line 113 of file Conversion.h.
References DeltaPhi(), SvtxTrack::get_phi(), reco1, reco2, and recoCount().
Referenced by TruthConversionEval::processTrackBackground(), and TruthConversionEval::recordConversion().
static float Conversion::trackDPhi (SvtxTrack * reco1, SvtxTrack * reco2) inline static
Definition at line 120 of file Conversion.h.
References DeltaPhi(), and SvtxTrack::get_phi().
float Conversion::vtxTrackRPhi (TVector3 vertpos)
Returns
the RPhi distance between the reco vtx and further track
Definition at line 429 of file Conversion.cc.
References reco1, and reco2.
Referenced by TruthConversionEval::processTrackBackground(), TruthConversionEval::recordConversion(), and vtxTrackRPhi().
float Conversion::vtxTrackRPhi (TVector3 vertpos, SvtxTrack * reco1, SvtxTrack * reco2) static
Definition at line 435 of file Conversion.cc.
References vtxTrackRPhi().
float Conversion::vtxTrackRPhi (TVector3 recoVertPos, SvtxTrack * track) static private
helper function
Definition at line 446 of file Conversion.cc.
References SvtxTrack::get_phi(), SvtxTrack::get_x(), and SvtxTrack::get_y().
float Conversion::vtxTrackRZ (TVector3 vertpos)
Returns
the RZ distance between the reco vtx and further track
Definition at line 418 of file Conversion.cc.
References reco1, and reco2.
Referenced by TruthConversionEval::processTrackBackground(), TruthConversionEval::recordConversion(), and vtxTrackRZ().
float Conversion::vtxTrackRZ (TVector3 vertpos, SvtxTrack * reco1, SvtxTrack * reco2) static
Definition at line 423 of file Conversion.cc.
References vtxTrackRZ().
float Conversion::vtxTrackRZ (TVector3 recoVertPos, SvtxTrack * track) static private
helper function
Definition at line 440 of file Conversion.cc.
References SvtxTrack::get_x(), SvtxTrack::get_y(), and SvtxTrack::get_z().
Member Data Documentation
const float Conversion::_kElectronRestM =.0005109989461 static private
Definition at line 286 of file Conversion.h.
Referenced by getRecoPhoton(), getRecoTlvs(), getRefitRecoTlvs(), and setRecoPhoton().
const int Conversion::_kNSiliconLayer =7 static private
hardcoded
Definition at line 282 of file Conversion.h.
Referenced by hasSilicon().
std::pair<PHGenFit::Track*,PHGenFit::Track*> Conversion::_refit_phgf_tracks private
Definition at line 278 of file Conversion.h.
Referenced by Conversion(), getRefitRecoTlvs(), refitTracks(), refitTracksTruthVtx(), and ~Conversion().
SvtxClusterMap* Conversion::_svtxClusterMap =NULL private
Definition at line 275 of file Conversion.h.
Referenced by setClusterMap().
PHG4Particle* Conversion::e1 =NULL private
Definition at line 266 of file Conversion.h.
Referenced by get_cluster_id(), getElectron(), getPositron(), hasPair(), isComplete(), PrintPhotonRecoInfo(), printTruth(), setElectron(), setRecoTrack(), and setRecoTracks().
PHG4Particle* Conversion::e2 =NULL private
Definition at line 267 of file Conversion.h.
Referenced by getPositron(), hasPair(), isComplete(), PrintPhotonRecoInfo(), printTruth(), setElectron(), setRecoTrack(), and setRecoTracks().
int Conversion::embedID =0 private
Definition at line 283 of file Conversion.h.
Referenced by getEmbed(), and setEmbed().
std::pair<unsigned,unsigned> Conversion::pairTruthReco1 private
Definition at line 279 of file Conversion.h.
Referenced by Conversion(), getRecoTrack(), setElectron(), setRecoTrack(), and setRecoTracks().
std::pair<unsigned,unsigned> Conversion::pairTruthReco2 private
Definition at line 280 of file Conversion.h.
Referenced by Conversion(), getRecoTrack(), setElectron(), setRecoTrack(), and setRecoTracks().
PHG4Particle* Conversion::photon =NULL private
Definition at line 268 of file Conversion.h.
Referenced by getPhoton(), getTruthPhoton(), isComplete(), PrintPhotonRecoInfo(), printReco(), setParent(), and setPrimaryPhoton().
PHG4Particle* Conversion::primaryPhoton =NULL private
Definition at line 269 of file Conversion.h.
Referenced by getPrimaryPhoton(), and setPrimaryPhoton().
SvtxTrack* Conversion::reco1 =NULL private
Definition at line 272 of file Conversion.h.
Referenced by approachDistance(), correctSecondaryVertex(), dist(), firstLayer(), get_cluster_id(), get_cluster_ids(), getPHGFTracks(), getRecoTlvs(), getRecoTrack(), getRecoTracks(), getSecondaryVertex(), getTrackEtas(), getTrackPhis(), getTrackpTs(), hasSilicon(), minDca(), minTrackpT(), PHG4VtxPointToSvtxVertex(), PrintPhotonRecoInfo(), printReco(), recoCount(), refitTracks(), refitTracksTruthVtx(), setRecoPhoton(), setRecoTrack(), setRecoTracks(), trackDEta(), trackDLayer(), trackDPhi(), vtxTrackRPhi(), and vtxTrackRZ().
SvtxTrack* Conversion::reco2 =NULL private
Definition at line 273 of file Conversion.h.
Referenced by approachDistance(), correctSecondaryVertex(), dist(), firstLayer(), get_cluster_ids(), getPHGFTracks(), getRecoTlvs(), getRecoTrack(), getRecoTracks(), getSecondaryVertex(), getTrackEtas(), getTrackPhis(), getTrackpTs(), hasSilicon(), minDca(), minTrackpT(), PHG4VtxPointToSvtxVertex(), PrintPhotonRecoInfo(), printReco(), recoCount(), refitTracks(), refitTracksTruthVtx(), setRecoPhoton(), setRecoTrack(), setRecoTracks(), trackDEta(), trackDLayer(), trackDPhi(), vtxTrackRPhi(), and vtxTrackRZ().
TLorentzVector* Conversion::recoPhoton =NULL private
Definition at line 277 of file Conversion.h.
Referenced by getRefitRecoPhoton(), PrintPhotonRecoInfo(), printTruth(), setRecoPhoton(), and ~Conversion().
genfit::GFRaveVertex* Conversion::recoVertex =NULL private
Definition at line 276 of file Conversion.h.
Referenced by correctSecondaryVertex(), getRecoVtx(), getSecondaryVertex(), printTruth(), refitTracks(), and ~Conversion().
int Conversion::sourceId private
Definition at line 285 of file Conversion.h.
Referenced by getSourceId(), and setSourceId().
SvtxTrackEval* Conversion::trackeval =NULL private
Definition at line 274 of file Conversion.h.
Referenced by Conversion(), get_cluster_id(), setRecoTracks(), and setTrackEval().
SvtxVertex* Conversion::truthSvtxVtx =NULL private
Definition at line 271 of file Conversion.h.
Referenced by PHG4VtxPointToSvtxVertex(), refitTracksTruthVtx(), and ~Conversion().
int Conversion::verbosity private
Definition at line 284 of file Conversion.h.
Referenced by Conversion(), setElectron(), and setVerbosity().
PHG4VtxPoint* Conversion::vtx =NULL private
Definition at line 270 of file Conversion.h.
Referenced by Conversion(), getVtx(), PHG4VtxPointToSvtxVertex(), printReco(), printTruth(), and setVtx().
The documentation for this class was generated from the following files:
analysis/blob/master/PhotonConversion/truthconversion/Conversion.h
analysis/blob/master/PhotonConversion/truthconversion/Conversion.cc