Analysis Software: AZigzag Class Reference
AZigzag Class Reference
#include <analysis/blob/master/TPC/groot/AZigzag.h>
Public Member Functions
AZigzag (CheveronPad_t paddef)
virtual ~AZigzag ()
virtual void Draw (double MAX)
int color (int)
void Clear ()
virtual void Report ()
void SetQ (double Q)
void SetT (double T)
void AddQ (double Q)
double Q ()
double T ()
double MAXQ ()
double MAXT ()
int MyID ()
void SetMyID (int ID)
double XCenter ()
double YCenter ()
double ZCenter ()
double RCenter ()
double PCenter ()
double NumSigma ()
bool IsHit ()
void DetermineQ (double Mintime=-2.0, double Maxtime=30.0)
bool IsIsolated ()
Static Public Member Functions
static int NCreated ()
static void WriteCalibration ()
static void ReadCalibration ()
static void DetermineCommonMode ()
static void ApplyCalibration ()
Public Attributes
CheveronPad_t fPads
int MyHybrid
int MyChannel
int MyWaveIndex
int iR
int iPhi
double myR
double myPhi
AZigzag * PreLogical
AZigzag * PostLogical
AZigzag * PreWaveform
AZigzag * PostWaveform
double xinit
double yinit
double rinit
double phinit
double t
double q
double maxq
double maxt
int myID
Static Public Attributes
static TRandom Randy
static bool FastQ = false
static bool UseSigma = true
static double SigmaCut =4
static double PulseCut =100
static std::string CommonModeMethod ="median"
static std::vector< int > Raw [Nsrs]
static std::vector< double > Cal [Nsrs]
static double Pedestals [Nsrs] = {0}
static double Sigmas [Nsrs] = {0}
static double Gains [Nsrs] = {0}
static std::vector< double > CommonMode [Nhybrid]
static TH1D * commy [Nhybrid] = {0}
static TH1D * Pulse =0
static TF1 * blue =0
static int nextID =0
Detailed Description
Definition at line 18 of file AZigzag.h.
Constructor & Destructor Documentation
AZigzag::AZigzag (CheveronPad_t paddef)
Definition at line 50 of file AZigzag.C.
References maxR, and minR.
virtual AZigzag::~AZigzag () inline virtual
Definition at line 22 of file AZigzag.h.
Member Function Documentation
void AZigzag::AddQ (double Q) inline
Definition at line 42 of file AZigzag.h.
References Q(), and q.
void AZigzag::ApplyCalibration () static
Definition at line 328 of file AZigzag.C.
References i, groot::instance(), j, MyHybrid, Nsrs, and groot::ZigzagMap.
Referenced by process_event().
void AZigzag::Clear (void) inline
Definition at line 36 of file AZigzag.h.
References q.
int AZigzag::color (int)
Definition at line 104 of file AZigzag.C.
void AZigzag::DetermineCommonMode () static
Definition at line 167 of file AZigzag.C.
References i, index, groot::instance(), j, k, name, Nhybrid, and groot::theZigzags.
Referenced by process_event().
void AZigzag::DetermineQ (double Mintime = -2.0, double Maxtime = 30.0)
Definition at line 346 of file AZigzag.C.
References i, max, min, and t.
void AZigzag::Draw (double MAX) virtual
Definition at line 74 of file AZigzag.C.
References N.
bool AZigzag::IsHit () inline
Definition at line 71 of file AZigzag.h.
References NumSigma(), PulseCut, q, SigmaCut, and UseSigma.
Referenced by FindBlobs().
bool AZigzag::IsIsolated ()
double AZigzag::MAXQ () inline
Definition at line 47 of file AZigzag.h.
References maxq.
double AZigzag::MAXT () inline
Definition at line 48 of file AZigzag.h.
References maxt.
int AZigzag::MyID () inline
Definition at line 49 of file AZigzag.h.
References myID.
static int AZigzag::NCreated () inline static
Definition at line 51 of file AZigzag.h.
References nextID.
double AZigzag::NumSigma () inline
Definition at line 70 of file AZigzag.h.
References Gains, myID, q, and Sigmas.
Referenced by IsHit().
double AZigzag::PCenter ()
Definition at line 435 of file AZigzag.C.
Referenced by FillBlobHist(), ABlob::GetPHI(), and NoiseSimulator().
double AZigzag::Q () inline
Definition at line 45 of file AZigzag.h.
References q.
Referenced by AddQ(), FindBlobs(), and SetQ().
double AZigzag::RCenter ()
Definition at line 433 of file AZigzag.C.
void AZigzag::ReadCalibration () static
Definition at line 130 of file AZigzag.C.
References file, i, and Nsrs.
Referenced by groot::groot().
void AZigzag::Report () virtual
Definition at line 415 of file AZigzag.C.
void AZigzag::SetMyID (int ID) inline
Definition at line 50 of file AZigzag.h.
References myID.
Referenced by groot::CreateZigzags().
void AZigzag::SetQ (double Q) inline
Definition at line 40 of file AZigzag.h.
References Q(), and q.
void AZigzag::SetT (double T) inline
Definition at line 41 of file AZigzag.h.
References T(), and t.
double AZigzag::T () inline
Definition at line 46 of file AZigzag.h.
References t.
Referenced by FindBlobs(), and SetT().
void AZigzag::WriteCalibration () static
Definition at line 107 of file AZigzag.C.
References file, i, and Nsrs.
double AZigzag::XCenter ()
Definition at line 427 of file AZigzag.C.
Referenced by FillHoughHist().
double AZigzag::YCenter ()
Definition at line 429 of file AZigzag.C.
Referenced by FillHoughHist().
double AZigzag::ZCenter ()
Definition at line 431 of file AZigzag.C.
Member Data Documentation
TF1 * AZigzag::blue =0 static
Definition at line 123 of file AZigzag.h.
std::vector< double > AZigzag::Cal static
Definition at line 107 of file AZigzag.h.
Referenced by groot::ClearTheDetector(), and FillCalHist().
std::vector< double > AZigzag::CommonMode static
Definition at line 113 of file AZigzag.h.
string AZigzag::CommonModeMethod ="median" static
Definition at line 103 of file AZigzag.h.
TH1D * AZigzag::commy = {0} static
Definition at line 121 of file AZigzag.h.
bool AZigzag::FastQ = false static
Definition at line 99 of file AZigzag.h.
CheveronPad_t AZigzag::fPads
Definition at line 30 of file AZigzag.h.
double AZigzag::Gains = {0} static
Definition at line 112 of file AZigzag.h.
Referenced by FitPedestals(), and NumSigma().
int AZigzag::iPhi
Definition at line 58 of file AZigzag.h.
int AZigzag::iR
Definition at line 57 of file AZigzag.h.
double AZigzag::maxq
Definition at line 133 of file AZigzag.h.
Referenced by MAXQ().
double AZigzag::maxt
Definition at line 134 of file AZigzag.h.
Referenced by MAXT().
int AZigzag::MyChannel
Definition at line 55 of file AZigzag.h.
Referenced by groot::CreateZigzags().
int AZigzag::MyHybrid
Definition at line 54 of file AZigzag.h.
Referenced by ApplyCalibration(), and groot::CreateZigzags().
int AZigzag::myID
Definition at line 137 of file AZigzag.h.
Referenced by MyID(), NumSigma(), and SetMyID().
double AZigzag::myPhi
Definition at line 66 of file AZigzag.h.
double AZigzag::myR
Definition at line 66 of file AZigzag.h.
int AZigzag::MyWaveIndex
Definition at line 56 of file AZigzag.h.
Referenced by groot::CreateZigzags().
int AZigzag::nextID =0 static
Definition at line 136 of file AZigzag.h.
Referenced by NCreated().
double AZigzag::Pedestals = {0} static
Definition at line 110 of file AZigzag.h.
Referenced by FitPedestals().
double AZigzag::phinit
Definition at line 129 of file AZigzag.h.
AZigzag* AZigzag::PostLogical
Definition at line 83 of file AZigzag.h.
AZigzag* AZigzag::PostWaveform
Definition at line 85 of file AZigzag.h.
AZigzag* AZigzag::PreLogical
Definition at line 82 of file AZigzag.h.
AZigzag* AZigzag::PreWaveform
Definition at line 84 of file AZigzag.h.
TH1D * AZigzag::Pulse =0 static
Definition at line 122 of file AZigzag.h.
double AZigzag::PulseCut =100 static
Definition at line 102 of file AZigzag.h.
Referenced by IsHit().
double AZigzag::q
Definition at line 132 of file AZigzag.h.
Referenced by AddQ(), Clear(), IsHit(), NumSigma(), Q(), and SetQ().
TRandom AZigzag::Randy static
Definition at line 96 of file AZigzag.h.
std::vector< int > AZigzag::Raw static
Definition at line 106 of file AZigzag.h.
Referenced by groot::ClearTheDetector(), FillCalHist(), FillRawHist(), and process_event().
double AZigzag::rinit
Definition at line 128 of file AZigzag.h.
double AZigzag::SigmaCut =4 static
Definition at line 101 of file AZigzag.h.
Referenced by IsHit().
double AZigzag::Sigmas = {0} static
Definition at line 111 of file AZigzag.h.
Referenced by FitPedestals(), and NumSigma().
double AZigzag::t
Definition at line 131 of file AZigzag.h.
Referenced by SetT(), and T().
bool AZigzag::UseSigma = true static
Definition at line 100 of file AZigzag.h.
Referenced by IsHit().
double AZigzag::xinit
Definition at line 126 of file AZigzag.h.
double AZigzag::yinit
Definition at line 127 of file AZigzag.h.
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/groot/AZigzag.h
analysis/blob/master/TPC/groot/AZigzag.C