Analysis Software: SvtxTrackMap_v1 Class Reference
SvtxTrackMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v1.h>
Public Member Functions
SvtxTrackMap_v1 ()
SvtxTrackMap_v1 (const SvtxTrackMap_v1 &trackmap)
SvtxTrackMap_v1 & operator= (const SvtxTrackMap_v1 &trackmap)
virtual ~SvtxTrackMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const SvtxTrack * get (unsigned int idkey) const
SvtxTrack * get (unsigned int idkey)
SvtxTrack * insert (const SvtxTrack *track)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SvtxTrackMap
virtual ~SvtxTrackMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (SvtxTrackMap_v1, 1)
Private Attributes
TrackMap _map
Additional Inherited Members
Public Types inherited from SvtxTrackMap
typedef std::map< unsigned int,
SvtxTrack * > TrackMap
typedef std::map< unsigned int,
SvtxTrack * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxTrack * >::iterator Iter
Protected Member Functions inherited from SvtxTrackMap
SvtxTrackMap ()
Detailed Description
Definition at line 12 of file SvtxTrackMap_v1.h.
Constructor & Destructor Documentation
SvtxTrackMap_v1::SvtxTrackMap_v1 ()
Definition at line 15 of file SvtxTrackMap_v1.cc.
Referenced by CloneMe().
SvtxTrackMap_v1::SvtxTrackMap_v1 (const SvtxTrackMap_v1 & trackmap)
Definition at line 20 of file SvtxTrackMap_v1.cc.
References _map, begin(), end(), and SvtxTrack::get_id().
SvtxTrackMap_v1::~SvtxTrackMap_v1 () virtual
Definition at line 45 of file SvtxTrackMap_v1.cc.
References Reset().
Member Function Documentation
ConstIter SvtxTrackMap_v1::begin () const inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 39 of file SvtxTrackMap_v1.h.
References _map.
Referenced by operator=(), and SvtxTrackMap_v1().
Iter SvtxTrackMap_v1::begin () inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 43 of file SvtxTrackMap_v1.h.
References _map.
SvtxTrackMap_v1::ClassDef (SvtxTrackMap_v1 , 1) private
void SvtxTrackMap_v1::clear () inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 28 of file SvtxTrackMap_v1.h.
References Reset().
PHObject* SvtxTrackMap_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxTrackMap.
Definition at line 23 of file SvtxTrackMap_v1.h.
References SvtxTrackMap_v1().
size_t SvtxTrackMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 27 of file SvtxTrackMap_v1.h.
References _map.
bool SvtxTrackMap_v1::empty () const inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 25 of file SvtxTrackMap_v1.h.
References _map.
ConstIter SvtxTrackMap_v1::end () const inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 41 of file SvtxTrackMap_v1.h.
References _map.
Referenced by operator=(), and SvtxTrackMap_v1().
Iter SvtxTrackMap_v1::end () inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 45 of file SvtxTrackMap_v1.h.
References _map.
size_t SvtxTrackMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 33 of file SvtxTrackMap_v1.h.
References _map.
ConstIter SvtxTrackMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 40 of file SvtxTrackMap_v1.h.
References _map.
Iter SvtxTrackMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 44 of file SvtxTrackMap_v1.h.
References _map.
const SvtxTrack * SvtxTrackMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SvtxTrackMap.
Definition at line 68 of file SvtxTrackMap_v1.cc.
References _map.
SvtxTrack * SvtxTrackMap_v1::get (unsigned int idkey) virtual
Reimplemented from SvtxTrackMap.
Definition at line 75 of file SvtxTrackMap_v1.cc.
References _map.
void SvtxTrackMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxTrackMap.
Definition at line 62 of file SvtxTrackMap_v1.cc.
References _map.
SvtxTrack * SvtxTrackMap_v1::insert (const SvtxTrack * track) virtual
Reimplemented from SvtxTrackMap.
Definition at line 82 of file SvtxTrackMap_v1.cc.
References _map, SvtxTrack::CloneMe(), and index.
int SvtxTrackMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxTrackMap.
Definition at line 22 of file SvtxTrackMap_v1.h.
SvtxTrackMap_v1 & SvtxTrackMap_v1::operator= (const SvtxTrackMap_v1 & trackmap)
Definition at line 32 of file SvtxTrackMap_v1.cc.
References _map, begin(), end(), SvtxTrack::get_id(), and Reset().
void SvtxTrackMap_v1::Reset () virtual
Clear Event.
Reimplemented from SvtxTrackMap.
Definition at line 50 of file SvtxTrackMap_v1.cc.
References _map.
Referenced by clear(), operator=(), and ~SvtxTrackMap_v1().
size_t SvtxTrackMap_v1::size (void) const inline virtual
Reimplemented from SvtxTrackMap.
Definition at line 26 of file SvtxTrackMap_v1.h.
References _map.
Member Data Documentation
TrackMap SvtxTrackMap_v1::_map private
Definition at line 48 of file SvtxTrackMap_v1.h.
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and SvtxTrackMap_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxTrackMap_v1.cc