Analysis Software: FieldMapsLaplace Class Reference
FieldMapsLaplace Class Reference
#include <analysis/blob/master/TPC/SCDCorrections/FieldMapsLaplace.h>
Public Member Functions
virtual void ComputeE ()
Public Member Functions inherited from FieldMaps
FieldMaps ()
virtual ~FieldMaps ()
void ReadFile ()
void SetDebugLevel (int n)
void TPCDimensions (float irad, float orad, float hzet)
void TPCGridSize (int nr, int np, int nz)
void OutputFileName (std::string a)
void LSFileName (std::string a)
void MirrorZ ()
void Make (int n=-1)
Additional Inherited Members
Protected Member Functions inherited from FieldMaps
void InitMaps ()
void SaveMaps ()
float ReadCharge (float rprime, float phiprime, float zprime, float dr, float dphi, float dz)
Protected Attributes inherited from FieldMaps
int fDebug
int fRadialBin
TH3F * fEr
TH3F * fEp
TH3F * fEz
TH3F * fRho
float fInnerRadius
float fOutterRadius
float fHalfLength
int fNRadialSteps
int fNAzimuthalSteps
int fNLongitudinalSteps
std::string fFileNameRoot
std::string fLSNameRoot
bool fMirrorZ
Detailed Description
Definition at line 12 of file FieldMapsLaplace.h.
Member Function Documentation
void FieldMapsLaplace::ComputeE () virtual
Implements FieldMaps.
Definition at line 12 of file FieldMapsLaplace.cxx.
References LaplaceSolution::Er(), LaplaceSolution::Ez(), FieldMaps::fDebug, FieldMaps::fEp, FieldMaps::fEr, FieldMaps::fEz, FieldMaps::fHalfLength, FieldMaps::fInnerRadius, FieldMaps::fLSNameRoot, FieldMaps::fMirrorZ, FieldMaps::fNAzimuthalSteps, FieldMaps::fNLongitudinalSteps, FieldMaps::fNRadialSteps, FieldMaps::fOutterRadius, FieldMaps::fRadialBin, phi, printf(), r, FieldMaps::ReadCharge(), TwoPi, and z.
The documentation for this class was generated from the following files:
analysis/blob/master/TPC/SCDCorrections/FieldMapsLaplace.h
analysis/blob/master/TPC/SCDCorrections/FieldMapsLaplace.cxx