Analysis Software: analysis/blob/master/EMCal-analysis/macro/DrawEcal_BlockCalibration.C File Reference
DrawEcal_BlockCalibration.C File Reference
#include <TFile.h>
#include <TGraphAsymmErrors.h>
#include <TGraphErrors.h>
#include <TLatex.h>
#include <TLine.h>
#include <TString.h>
#include <TTree.h>
#include <cassert>
#include <cmath>
#include "SaveCanvas.C"
#include "sPhenixStyle.C"
Functions
void DrawEcal_BlockCalibration (const TString infile="/phenix/u/jinhuang/links/sPHENIX_work/prod_analysis/EMCal_photon_calib/EMCalAna.root")
Detailed Description
Author
Jin Huang jhuan.nosp@m.g@bn.nosp@m.l.gov
Version
Revision:
Date
Date:
Definition in file DrawEcal_BlockCalibration.C.
Function Documentation
void DrawEcal_BlockCalibration (const TString infile = "/phenix/u/jinhuang/links/sPHENIX_work/prod_analysis/EMCal_photon_calib/EMCalAna.root")
Definition at line 25 of file DrawEcal_BlockCalibration.C.
References assert, leg, phi, SaveCanvas(), PHParameters::set_double_param(), PHParameters::set_int_param(), PHParameters::set_string_param(), SetsPhenixStyle(), and PHParameters::WriteToFile().