Analysis Software: PHG4GDMLDetector Class Reference
PHG4GDMLDetector Class Reference
PHG4GDMLDetector is a generic detector built from a GDML import.
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4GDMLDetector.h>
Public Member Functions
PHG4GDMLDetector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &dnam, PHParameters *parameters)
virtual ~PHG4GDMLDetector ()
void ConstructMe (G4LogicalVolume *world)
construct
G4UserSteppingAction * GetSteppingAction ()
void Print (const std::string &what="ALL") const
Public Member Functions inherited from PHG4Detector
PHG4Detector ()=delete
constructor
PHG4Detector (PHG4Subsystem *subsys, PHCompositeNode *Node, const std::string &nam)
virtual ~PHG4Detector (void)
destructor
virtual void Construct (G4LogicalVolume *world) final
construct method
virtual void Verbosity (const int v)
virtual int Verbosity () const
virtual std::string GetName () const
virtual void OverlapCheck (const bool chk)
virtual bool OverlapCheck () const
virtual int DisplayVolume (G4VSolid *volume, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual int DisplayVolume (G4LogicalVolume *checksolid, G4LogicalVolume *logvol, G4RotationMatrix *rotm=nullptr)
virtual PHCompositeNode * topNode ()
virtual PHG4Subsystem * GetMySubsystem ()
Private Member Functions
void SetDisplayProperty (G4AssemblyVolume *av)
void SetDisplayProperty (G4LogicalVolume *lv)
Private Attributes
std::string m_GDMPath
std::string m_TopVolName
G4double m_placeX
G4double m_placeY
G4double m_placeZ
G4double m_rotationX
G4double m_rotationY
G4double m_rotationZ
Detailed Description
PHG4GDMLDetector is a generic detector built from a GDML import.
Definition at line 32 of file PHG4GDMLDetector.h.
Constructor & Destructor Documentation
PHG4GDMLDetector::PHG4GDMLDetector (PHG4Subsystem * subsys, PHCompositeNode * Node, const std::string & dnam, PHParameters * parameters)
Definition at line 41 of file PHG4GDMLDetector.cc.
PHG4GDMLDetector::~PHG4GDMLDetector () virtual
Definition at line 54 of file PHG4GDMLDetector.cc.
Member Function Documentation
void PHG4GDMLDetector::ConstructMe (G4LogicalVolume * world) virtual
construct
Implements PHG4Detector.
Definition at line 71 of file PHG4GDMLDetector.cc.
References PHG4Detector::GetMySubsystem(), PHG4Detector::GetName(), m_GDMPath, m_placeX, m_placeY, m_placeZ, m_rotationX, m_rotationY, m_rotationZ, m_TopVolName, PHG4Detector::OverlapCheck(), Print(), SetDisplayProperty(), PHG4Subsystem::SetLogicalVolume(), and PHG4Detector::Verbosity().
G4UserSteppingAction* PHG4GDMLDetector::GetSteppingAction (void) inline virtual
Reimplemented from PHG4Detector.
Definition at line 42 of file PHG4GDMLDetector.h.
void PHG4GDMLDetector::Print (const std::string & what = "ALL") const virtual
Reimplemented from PHG4Detector.
Definition at line 60 of file PHG4GDMLDetector.cc.
References PHG4Detector::GetName(), m_GDMPath, m_placeX, m_placeY, m_placeZ, m_rotationX, m_rotationY, m_rotationZ, and m_TopVolName.
Referenced by ConstructMe(), and PHG4GDMLSubsystem::Print().
void PHG4GDMLDetector::SetDisplayProperty (G4AssemblyVolume * av) private
Definition at line 119 of file PHG4GDMLDetector.cc.
References i, and it.
Referenced by ConstructMe(), and SetDisplayProperty().
void PHG4GDMLDetector::SetDisplayProperty (G4LogicalVolume * lv) private
Definition at line 137 of file PHG4GDMLDetector.cc.
References i, PHG4Utils::SetColour(), SetDisplayProperty(), and PHG4Detector::Verbosity().
Member Data Documentation
std::string PHG4GDMLDetector::m_GDMPath private
Definition at line 53 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
G4double PHG4GDMLDetector::m_placeX private
Definition at line 56 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
G4double PHG4GDMLDetector::m_placeY private
Definition at line 57 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
G4double PHG4GDMLDetector::m_placeZ private
Definition at line 58 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
G4double PHG4GDMLDetector::m_rotationX private
Definition at line 60 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
G4double PHG4GDMLDetector::m_rotationY private
Definition at line 61 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
G4double PHG4GDMLDetector::m_rotationZ private
Definition at line 62 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
std::string PHG4GDMLDetector::m_TopVolName private
Definition at line 54 of file PHG4GDMLDetector.h.
Referenced by ConstructMe(), and Print().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4GDMLDetector.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc