Analysis Software: PHG4TpcPadPlaneReadout Class Reference
PHG4TpcPadPlaneReadout Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h>
Public Member Functions
PHG4TpcPadPlaneReadout (const std::string &name="PHG4TpcPadPlaneReadout")
virtual ~PHG4TpcPadPlaneReadout ()
int CreateReadoutGeometry (PHCompositeNode *topNode, PHG4CylinderCellGeomContainer *seggeo)
void MapToPadPlane (PHG4CellContainer *g4cells, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter, TNtuple *ntpad, TNtuple *nthit)
void MapToPadPlane (TrkrHitSetContainer *hitsetcontainer, TrkrHitTruthAssoc *hittruthassoc, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter, TNtuple *ntpad, TNtuple *nthit)
void populate_rectangular_phibins (const unsigned int layernum, const double phi, const double cloud_sig_rp, std::vector< int > &pad_phibin, std::vector< double > &pad_phibin_share)
void populate_zigzag_phibins (const unsigned int layernum, const double phi, const double cloud_sig_rp, std::vector< int > &pad_phibin, std::vector< double > &pad_phibin_share)
void populate_zbins (const double z, const double cloud_sig_zz[2], std::vector< int > &adc_zbin, std::vector< double > &adc_zbin_share)
void SetDefaultParameters ()
void UpdateInternalParameters ()
Public Member Functions inherited from PHG4TpcPadPlane
PHG4TpcPadPlane (const std::string &name="PHG4TpcPadPlane")
virtual ~PHG4TpcPadPlane ()
int process_event (PHCompositeNode *) final
int InitRun (PHCompositeNode *topNode)
void Detector (const std::string &name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Public Member Functions inherited from PHParameterInterface
PHParameterInterface (const std::string &name)
virtual ~PHParameterInterface ()
void set_paramname (const std::string &name)
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UpdateParametersWithMacro ()
void SaveToNodeTree (PHCompositeNode *runNode, const std::string &nodename)
void PutOnParNode (PHCompositeNode *parNode, const std::string &nodename)
Protected Attributes
std::string seggeonodename
TF1 * fcharge
TF1 * fpad [10]
PHG4CylinderCellGeomContainer * GeomContainer
PHG4CylinderCellGeom * LayerGeom
double rad_gem
double output_radius
double neffelectrons_threshold
int MinLayer [3]
int MaxLayer [3]
double MinRadius [3]
double MaxRadius [3]
double Thickness [3]
double MinZ
double MaxZ
double sigmaT
double sigmaL [2]
double PhiBinWidth [3]
double ZBinWidth
double tpc_drift_velocity
double tpc_adc_clock
int NZBins
int NPhiBins [3]
int NTpcLayers [3]
int tpc_region
int zigzag_pads
int hit
std::vector< int > adc_zbin
std::vector< int > pad_phibin
std::vector< double > pad_phibin_share
std::vector< double > adc_zbin_share
Protected Attributes inherited from PHG4TpcPadPlane
std::string detector
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from PHParameterInterface
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
void InitializeParameters ()
Detailed Description
Definition at line 20 of file PHG4TpcPadPlaneReadout.h.
Constructor & Destructor Documentation
PHG4TpcPadPlaneReadout::PHG4TpcPadPlaneReadout (const std::string & name = "PHG4TpcPadPlaneReadout")
Definition at line 38 of file PHG4TpcPadPlaneReadout.cc.
References fcharge, fpad, and PHParameterInterface::InitializeParameters().
PHG4TpcPadPlaneReadout::~PHG4TpcPadPlaneReadout () virtual
Definition at line 80 of file PHG4TpcPadPlaneReadout.cc.
References fcharge, and fpad.
Member Function Documentation
int PHG4TpcPadPlaneReadout::CreateReadoutGeometry (PHCompositeNode * topNode, PHG4CylinderCellGeomContainer * seggeo) virtual
Reimplemented from PHG4TpcPadPlane.
Definition at line 89 of file PHG4TpcPadPlaneReadout.cc.
References PHG4CylinderCellGeomContainer::AddLayerCellGeom(), double(), GeomContainer, MinLayer, MinRadius, MinZ, NPhiBins, NTpcLayers, NZBins, PhiBinWidth, PHG4CylinderCellGeom::set_binning(), PHG4CylinderCellGeom::set_layer(), PHG4CylinderCellGeom::set_phibins(), PHG4CylinderCellGeom::set_phistep(), PHG4CylinderCellGeom::set_radius(), PHG4CylinderCellGeom::set_thickness(), PHG4CylinderCellGeom::set_zbins(), PHG4CylinderCellGeom::set_zmin(), PHG4CylinderCellGeom::set_zstep(), PHG4CellDefs::sizebinning, Thickness, Fun4AllBase::Verbosity(), and ZBinWidth.
void PHG4TpcPadPlaneReadout::MapToPadPlane (PHG4CellContainer * g4cells, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter, TNtuple * ntpad, TNtuple * nthit) virtual
Reimplemented from PHG4TpcPadPlane.
Definition at line 134 of file PHG4TpcPadPlaneReadout.cc.
References adc_zbin, adc_zbin_share, PHG4Cell::add_edep(), PHG4CellContainer::AddCell(), PHG4CellContainer::findCell(), PHG4CellDefs::SizeBinning::genkey(), GeomContainer, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), hit, PHG4Cell::identify(), LayerGeom, M_PI, neffelectrons_threshold, pad_phibin, pad_phibin_share, phi, populate_rectangular_phibins(), populate_zbins(), populate_zigzag_phibins(), rad_gem, sigmaL, sigmaT, Fun4AllBase::Verbosity(), and zigzag_pads.
void PHG4TpcPadPlaneReadout::MapToPadPlane (TrkrHitSetContainer * hitsetcontainer, TrkrHitTruthAssoc * hittruthassoc, const double x_gem, const double y_gem, const double t_gem, PHG4HitContainer::ConstIterator hiter, TNtuple * ntpad, TNtuple * nthit) virtual
Reimplemented from PHG4TpcPadPlane.
Definition at line 308 of file PHG4TpcPadPlaneReadout.cc.
References adc_zbin, adc_zbin_share, TrkrHit::addEnergy(), TrkrHitSetContainer::findOrAddHitSet(), TpcDefs::genHitKey(), TpcDefs::genHitSetKey(), GeomContainer, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), hit, LayerGeom, M_PI, neffelectrons_threshold, pad_phibin, pad_phibin_share, phi, populate_rectangular_phibins(), populate_zbins(), populate_zigzag_phibins(), rad_gem, sigmaL, sigmaT, Fun4AllBase::Verbosity(), and zigzag_pads.
void PHG4TpcPadPlaneReadout::populate_rectangular_phibins (const unsigned int layernum, const double phi, const double cloud_sig_rp, std::vector< int > & pad_phibin, std::vector< double > & pad_phibin_share)
Definition at line 502 of file PHG4TpcPadPlaneReadout.cc.
References PHG4CylinderCellGeom::get_phibin(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_radius(), and LayerGeom.
Referenced by MapToPadPlane().
void PHG4TpcPadPlaneReadout::populate_zbins (const double z, const double cloud_sig_zz[2], std::vector< int > & adc_zbin, std::vector< double > & adc_zbin_share)
Definition at line 635 of file PHG4TpcPadPlaneReadout.cc.
References PHG4CylinderCellGeom::get_layer(), PHG4CylinderCellGeom::get_zbin(), PHG4CylinderCellGeom::get_zbins(), PHG4CylinderCellGeom::get_zcenter(), PHG4CylinderCellGeom::get_zstep(), index, LayerGeom, NZBins, and Fun4AllBase::Verbosity().
Referenced by MapToPadPlane().
void PHG4TpcPadPlaneReadout::populate_zigzag_phibins (const unsigned int layernum, const double phi, const double cloud_sig_rp, std::vector< int > & pad_phibin, std::vector< double > & pad_phibin_share)
Definition at line 542 of file PHG4TpcPadPlaneReadout.cc.
References double(), fcharge, fpad, PHG4CylinderCellGeom::get_layer(), PHG4CylinderCellGeom::get_phibin(), PHG4CylinderCellGeom::get_phibins(), PHG4CylinderCellGeom::get_phicenter(), PHG4CylinderCellGeom::get_phistep(), PHG4CylinderCellGeom::get_radius(), i, LayerGeom, output_radius, rad_gem, Fun4AllBase::Verbosity(), and x.
Referenced by MapToPadPlane().
void PHG4TpcPadPlaneReadout::SetDefaultParameters () virtual
Implements PHParameterInterface.
Definition at line 748 of file PHG4TpcPadPlaneReadout.cc.
References PHParameterInterface::set_default_double_param(), and PHParameterInterface::set_default_int_param().
void PHG4TpcPadPlaneReadout::UpdateInternalParameters () virtual
Reimplemented from PHG4TpcPadPlane.
Definition at line 782 of file PHG4TpcPadPlaneReadout.cc.
References double(), PHParameterInterface::get_double_param(), PHParameterInterface::get_int_param(), M_PI, MaxRadius, MaxZ, MinLayer, MinRadius, MinZ, neffelectrons_threshold, NPhiBins, NTpcLayers, NZBins, PhiBinWidth, sigmaL, sigmaT, Thickness, tpc_adc_clock, tpc_drift_velocity, ZBinWidth, and zigzag_pads.
Member Data Documentation
std::vector<int> PHG4TpcPadPlaneReadout::adc_zbin protected
Definition at line 75 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane().
std::vector<double> PHG4TpcPadPlaneReadout::adc_zbin_share protected
Definition at line 78 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane().
TF1* PHG4TpcPadPlaneReadout::fcharge protected
Definition at line 42 of file PHG4TpcPadPlaneReadout.h.
Referenced by PHG4TpcPadPlaneReadout(), populate_zigzag_phibins(), and ~PHG4TpcPadPlaneReadout().
TF1* PHG4TpcPadPlaneReadout::fpad[10] protected
Definition at line 43 of file PHG4TpcPadPlaneReadout.h.
Referenced by PHG4TpcPadPlaneReadout(), populate_zigzag_phibins(), and ~PHG4TpcPadPlaneReadout().
PHG4CylinderCellGeomContainer* PHG4TpcPadPlaneReadout::GeomContainer protected
Definition at line 45 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and MapToPadPlane().
int PHG4TpcPadPlaneReadout::hit protected
Definition at line 73 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane().
PHG4CylinderCellGeom* PHG4TpcPadPlaneReadout::LayerGeom protected
Definition at line 46 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane(), populate_rectangular_phibins(), populate_zbins(), and populate_zigzag_phibins().
int PHG4TpcPadPlaneReadout::MaxLayer[3] protected
Definition at line 54 of file PHG4TpcPadPlaneReadout.h.
double PHG4TpcPadPlaneReadout::MaxRadius[3] protected
Definition at line 56 of file PHG4TpcPadPlaneReadout.h.
Referenced by UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::MaxZ protected
Definition at line 59 of file PHG4TpcPadPlaneReadout.h.
Referenced by UpdateInternalParameters().
int PHG4TpcPadPlaneReadout::MinLayer[3] protected
Definition at line 53 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::MinRadius[3] protected
Definition at line 55 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::MinZ protected
Definition at line 58 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::neffelectrons_threshold protected
Definition at line 51 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
int PHG4TpcPadPlaneReadout::NPhiBins[3] protected
Definition at line 68 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
int PHG4TpcPadPlaneReadout::NTpcLayers[3] protected
Definition at line 70 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
int PHG4TpcPadPlaneReadout::NZBins protected
Definition at line 67 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), populate_zbins(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::output_radius protected
Definition at line 49 of file PHG4TpcPadPlaneReadout.h.
Referenced by populate_zigzag_phibins().
std::vector<int> PHG4TpcPadPlaneReadout::pad_phibin protected
Definition at line 76 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane().
std::vector<double> PHG4TpcPadPlaneReadout::pad_phibin_share protected
Definition at line 77 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane().
double PHG4TpcPadPlaneReadout::PhiBinWidth[3] protected
Definition at line 62 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::rad_gem protected
Definition at line 48 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane(), and populate_zigzag_phibins().
std::string PHG4TpcPadPlaneReadout::seggeonodename protected
Definition at line 40 of file PHG4TpcPadPlaneReadout.h.
double PHG4TpcPadPlaneReadout::sigmaL[2] protected
Definition at line 61 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::sigmaT protected
Definition at line 60 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::Thickness[3] protected
Definition at line 57 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::tpc_adc_clock protected
Definition at line 65 of file PHG4TpcPadPlaneReadout.h.
Referenced by UpdateInternalParameters().
double PHG4TpcPadPlaneReadout::tpc_drift_velocity protected
Definition at line 64 of file PHG4TpcPadPlaneReadout.h.
Referenced by UpdateInternalParameters().
int PHG4TpcPadPlaneReadout::tpc_region protected
Definition at line 71 of file PHG4TpcPadPlaneReadout.h.
double PHG4TpcPadPlaneReadout::ZBinWidth protected
Definition at line 63 of file PHG4TpcPadPlaneReadout.h.
Referenced by CreateReadoutGeometry(), and UpdateInternalParameters().
int PHG4TpcPadPlaneReadout::zigzag_pads protected
Definition at line 72 of file PHG4TpcPadPlaneReadout.h.
Referenced by MapToPadPlane(), and UpdateInternalParameters().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
coresoftware/blob/master/simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc