Analysis Software: analysis/blob/master/TPC/groot/FillHoughHist.h File Reference
FillHoughHist.h File Reference
Macros
#define Med_inverseSlope -0.0018
#define Med_Offset 426.526
#define MAD_inverseSlope 0.0091081
#define MAD_Offset 426.528
#define HFACTOR 5.0
Functions
void FillHoughHist ()
double inverseSlope (double x1, double y1, double x2, double y2)
double intercept (double x1, double y1, double x2, double y2)
Macro Definition Documentation
#define HFACTOR 5.0
Definition at line 13 of file FillHoughHist.h.
Referenced by FillHoughHist().
#define MAD_inverseSlope 0.0091081
Definition at line 11 of file FillHoughHist.h.
Referenced by FillHoughHist().
#define MAD_Offset 426.528
Definition at line 12 of file FillHoughHist.h.
Referenced by FillHoughHist().
#define Med_inverseSlope -0.0018
Definition at line 9 of file FillHoughHist.h.
Referenced by FillHoughHist().
#define Med_Offset 426.526
Definition at line 10 of file FillHoughHist.h.
Referenced by FillHoughHist().
Function Documentation
void FillHoughHist ()
Definition at line 18 of file FillHoughHist.C.
References C, c, d, HFACTOR, HoughHistABS, HoughHistMC, i, groot::instance(), intercept(), inverseSlope(), j, k, k1, MAD_inverseSlope, MAD_Offset, Med_inverseSlope, Med_Offset, Nphi, Nr, offset, groot::theBlobs, x2, AZigzag::XCenter(), AZigzag::YCenter(), and groot::ZigzagMap2.
double intercept (double x1, double y1, double x2, double y2)
Definition at line 123 of file FillHoughHist.C.
References c, and x2.
Referenced by FillHoughHist().
double inverseSlope (double x1, double y1, double x2, double y2)
Definition at line 117 of file FillHoughHist.C.
Referenced by FillHoughHist().