Analysis Software: PHG4CylinderCellGeomContainer Class Reference
PHG4CylinderCellGeomContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeomContainer.h>
Public Types
typedef std::map< int,
PHG4CylinderCellGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4CylinderCellGeomContainer ()
virtual ~PHG4CylinderCellGeomContainer ()
void identify (std::ostream &os=std::cout) const
int AddLayerCellGeom (const int i, PHG4CylinderCellGeom *mygeom)
int AddLayerCellGeom (PHG4CylinderCellGeom *mygeom)
PHG4CylinderCellGeom * GetLayerCellGeom (const int i)
PHG4CylinderCellGeom * GetFirstLayerCellGeom ()
int get_NLayers () const
std::pair< std::map< int,
PHG4CylinderCellGeom * >
::const_iterator, std::map
< int, PHG4CylinderCellGeom * >
::const_iterator > get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
std::map< int,
PHG4CylinderCellGeom * > layergeoms
Detailed Description
Definition at line 14 of file PHG4CylinderCellGeomContainer.h.
Member Typedef Documentation
typedef Map::const_iterator PHG4CylinderCellGeomContainer::ConstIterator
Definition at line 19 of file PHG4CylinderCellGeomContainer.h.
typedef std::pair<ConstIterator, ConstIterator> PHG4CylinderCellGeomContainer::ConstRange
Definition at line 21 of file PHG4CylinderCellGeomContainer.h.
typedef Map::iterator PHG4CylinderCellGeomContainer::Iterator
Definition at line 18 of file PHG4CylinderCellGeomContainer.h.
typedef std::map<int, PHG4CylinderCellGeom*> PHG4CylinderCellGeomContainer::Map
Definition at line 17 of file PHG4CylinderCellGeomContainer.h.
typedef std::pair<Iterator, Iterator> PHG4CylinderCellGeomContainer::Range
Definition at line 20 of file PHG4CylinderCellGeomContainer.h.
Constructor & Destructor Documentation
PHG4CylinderCellGeomContainer::PHG4CylinderCellGeomContainer () inline
Definition at line 23 of file PHG4CylinderCellGeomContainer.h.
PHG4CylinderCellGeomContainer::~PHG4CylinderCellGeomContainer () virtual
Definition at line 8 of file PHG4CylinderCellGeomContainer.cc.
Member Function Documentation
int PHG4CylinderCellGeomContainer::AddLayerCellGeom (const int i, PHG4CylinderCellGeom * mygeom)
Definition at line 31 of file PHG4CylinderCellGeomContainer.cc.
References i, and PHG4CylinderCellGeom::set_layer().
Referenced by PHG4TpcPadPlaneReadout::CreateReadoutGeometry(), PHG4CylinderCellReco::InitRun(), and PHG4FullProjSpacalCellReco::InitRun().
int PHG4CylinderCellGeomContainer::AddLayerCellGeom (PHG4CylinderCellGeom * mygeom)
Definition at line 44 of file PHG4CylinderCellGeomContainer.cc.
References PHG4CylinderCellGeom::get_layer().
std::pair<std::map<int,PHG4CylinderCellGeom *>::const_iterator, std::map<int,PHG4CylinderCellGeom *>::const_iterator> PHG4CylinderCellGeomContainer::get_begin_end () const inline
Definition at line 33 of file PHG4CylinderCellGeomContainer.h.
References layergeoms.
Referenced by PHG4TpcDigitizer::CalculateCylinderCellADCScale(), RawTowerBuilder::CreateNodes(), PHPatternReco::initialize_geometry(), PHInitZVertexing::initialize_geometry(), PHHoughSeeding::InitializeGeometry(), PHGenFitTrkProp::InitializeGeometry(), PHG4TpcPadPlaneReadout::MapToPadPlane(), and DumpPHG4CylinderCellGeomContainer::process_Node().
int PHG4CylinderCellGeomContainer::get_NLayers () const inline
Definition at line 32 of file PHG4CylinderCellGeomContainer.h.
References layergeoms.
Referenced by RawTowerBuilder::CreateNodes(), RawTowerBuilder::InitRun(), and DumpPHG4CylinderCellGeomContainer::process_Node().
PHG4CylinderCellGeom * PHG4CylinderCellGeomContainer::GetFirstLayerCellGeom ()
Definition at line 69 of file PHG4CylinderCellGeomContainer.cc.
Referenced by PHG4FullProjSpacalCellReco::process_event(), and EMCalAna::process_event_SF().
PHG4CylinderCellGeom * PHG4CylinderCellGeomContainer::GetLayerCellGeom (const int i)
Definition at line 57 of file PHG4CylinderCellGeomContainer.cc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), TpcPrototypeUnpacker::exportDSTCluster(), TrkrEvaluator::fillOutputNtuples(), SvtxEvaluator::fillOutputNtuples(), TPCDataStreamEmulator::InitRun(), TPCMLDataInterface::InitRun(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), TPCIntegratedCharge::process_event(), PHG4CylinderCellReco::process_event(), G4CellNtuple::process_event(), TPCDataStreamEmulator::process_event(), and TPCMLDataInterface::process_event().
void PHG4CylinderCellGeomContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 19 of file PHG4CylinderCellGeomContainer.cc.
Member Data Documentation
std::map<int,PHG4CylinderCellGeom *> PHG4CylinderCellGeomContainer::layergeoms protected
Definition at line 36 of file PHG4CylinderCellGeomContainer.h.
Referenced by get_begin_end(), and get_NLayers().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeomContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4CylinderCellGeomContainer.cc