Analysis Software: PHG4VtxPointv1 Class Reference
PHG4VtxPointv1 Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPointv1.h>
Public Member Functions
PHG4VtxPointv1 ()
PHG4VtxPointv1 (const PHG4VtxPoint *vtx)
PHG4VtxPointv1 (const double x, const double y, const double z, const double t, const int id_value=INT_MIN)
virtual ~PHG4VtxPointv1 ()
void set_x (const double r)
void set_y (const double r)
void set_z (const double r)
void set_t (const double r)
void set_id (const int i)
double get_x () const
double get_y () const
double get_z () const
double get_t () const
int get_id () const
void identify (std::ostream &os=std::cout) const
Public Member Functions inherited from PHG4VtxPoint
virtual ~PHG4VtxPoint ()
bool operator== (const PHG4VtxPoint &) const
comparison of vertex value only, not on the id, per algorithm requirement in PHG4TruthInfoContainer::AddPrimaryVertex
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
double vx
double vy
double vz
double t0
int id
id tag for this vertex
Additional Inherited Members
Protected Member Functions inherited from PHG4VtxPoint
PHG4VtxPoint ()
Detailed Description
Definition at line 12 of file PHG4VtxPointv1.h.
Constructor & Destructor Documentation
PHG4VtxPointv1::PHG4VtxPointv1 () inline
Definition at line 15 of file PHG4VtxPointv1.h.
PHG4VtxPointv1::PHG4VtxPointv1 (const PHG4VtxPoint * vtx) inline
Definition at line 23 of file PHG4VtxPointv1.h.
PHG4VtxPointv1::PHG4VtxPointv1 (const double x, const double y, const double z, const double t, const int id_value = INT_MIN) inline
Definition at line 31 of file PHG4VtxPointv1.h.
virtual PHG4VtxPointv1::~PHG4VtxPointv1 () inline virtual
Definition at line 39 of file PHG4VtxPointv1.h.
Member Function Documentation
int PHG4VtxPointv1::get_id () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 51 of file PHG4VtxPointv1.h.
References id.
double PHG4VtxPointv1::get_t () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 50 of file PHG4VtxPointv1.h.
References t0.
double PHG4VtxPointv1::get_x () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 47 of file PHG4VtxPointv1.h.
References vx.
double PHG4VtxPointv1::get_y () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 48 of file PHG4VtxPointv1.h.
References vy.
double PHG4VtxPointv1::get_z () const inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 49 of file PHG4VtxPointv1.h.
References vz.
void PHG4VtxPointv1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4VtxPoint.
Definition at line 6 of file PHG4VtxPointv1.cc.
void PHG4VtxPointv1::set_id (const int i) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 45 of file PHG4VtxPointv1.h.
References i.
Referenced by PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_t (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 44 of file PHG4VtxPointv1.h.
References r, and t0.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_x (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 41 of file PHG4VtxPointv1.h.
References r, and vx.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_y (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 42 of file PHG4VtxPointv1.h.
References r, and vy.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
void PHG4VtxPointv1::set_z (const double r) inline virtual
Reimplemented from PHG4VtxPoint.
Definition at line 43 of file PHG4VtxPointv1.h.
References r, and vz.
Referenced by PHG4InEventReadBack::process_event(), and PHG4DSTReader::process_event().
Member Data Documentation
int PHG4VtxPointv1::id protected
id tag for this vertex
Definition at line 63 of file PHG4VtxPointv1.h.
Referenced by get_id().
double PHG4VtxPointv1::t0 protected
Definition at line 60 of file PHG4VtxPointv1.h.
Referenced by get_t(), and set_t().
double PHG4VtxPointv1::vx protected
Definition at line 57 of file PHG4VtxPointv1.h.
Referenced by get_x(), and set_x().
double PHG4VtxPointv1::vy protected
Definition at line 58 of file PHG4VtxPointv1.h.
Referenced by get_y(), and set_y().
double PHG4VtxPointv1::vz protected
Definition at line 59 of file PHG4VtxPointv1.h.
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPointv1.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4VtxPointv1.cc