Analysis Software: hcalUtil Class Reference
hcalUtil Class Reference
#include <analysis/blob/master/Prototype2/hcalLab/hcalUtil.h>
Public Member Functions
Float_t xPeak (TF1 *f, Float_t x1, Float_t x2)
Float_t width (TF1 *f, Float_t x1, Float_t x2, Float_t peak)
bool shapeFit (TH1D *proj, Double_t *pE, Float_t &maxE, Double_t *pG, bool fine, bool MIP)
bool emcFit (TH1D *proj, bool fine, bool sing, Double_t *pE, Float_t &maxE, Double_t *pG, bool MIP)
bool emcFit (TH1D *proj, bool sing, Double_t *pE, Float_t &maxE, Double_t *pG)
bool emcFit (TH1D *proj, bool sing, Double_t *pE, Float_t &maxE, Double_t *pG, Float_t minx, Float_t maxx)
bool twrMipFit (TH1D *proj, Double_t *pE, Float_t &maxE, Double_t *pG)
bool twrTimeFit (TH1D *proj, Double_t *pE, Float_t &maxE, Double_t *pG)
Static Public Member Functions
static hcalUtil * getInstance ()
static void deleteInstance ()
Protected Member Functions
hcalUtil ()
virtual ~hcalUtil ()
Static Protected Attributes
static hcalUtil * single = 0
Detailed Description
Definition at line 667 of file hcalUtil.h.
Constructor & Destructor Documentation
hcalUtil::hcalUtil () protected
Definition at line 374 of file hcalUtil.C.
References s.
Referenced by getInstance().
virtual hcalUtil::~hcalUtil () inline protected virtual
Definition at line 670 of file hcalUtil.h.
Member Function Documentation
static void hcalUtil::deleteInstance () inline static
Definition at line 675 of file hcalUtil.h.
References single.
Referenced by G__hcalUtilDict_478_0_3(), and G__setup_memfunchcalUtil().
bool hcalUtil::emcFit (TH1D * proj, bool fine, bool sing, Double_t * pE, Float_t & maxE, Double_t * pG, bool MIP)
bool hcalUtil::emcFit (TH1D * proj, bool sing, Double_t * pE, Float_t & maxE, Double_t * pG)
bool hcalUtil::emcFit (TH1D * proj, bool sing, Double_t * pE, Float_t & maxE, Double_t * pG, Float_t minx, Float_t maxx)
static hcalUtil* hcalUtil::getInstance () inline static
Definition at line 674 of file hcalUtil.h.
References hcalUtil(), and single.
Referenced by G__hcalUtilDict_478_0_2(), and G__setup_memfunchcalUtil().
bool hcalUtil::shapeFit (TH1D * proj, Double_t * pE, Float_t & maxE, Double_t * pG, bool fine, bool MIP)
Definition at line 450 of file hcalUtil.C.
References erfunc(), and x.
bool hcalUtil::twrMipFit (TH1D * proj, Double_t * pE, Float_t & maxE, Double_t * pG)
Definition at line 645 of file hcalUtil.C.
References b1, power_g(), powerFun(), and x.
bool hcalUtil::twrTimeFit (TH1D * proj, Double_t * pE, Float_t & maxE, Double_t * pG)
Definition at line 709 of file hcalUtil.C.
References b1, power_g(), powerFun(), and x.
float hcalUtil::width (TF1 * f, Float_t x1, Float_t x2, Float_t peak)
Definition at line 409 of file hcalUtil.C.
References x2.
Referenced by pyslha().
float hcalUtil::xPeak (TF1 * f, Float_t x1, Float_t x2)
Definition at line 387 of file hcalUtil.C.
References dx, x, x2, and y.
Member Data Documentation
hcalUtil * hcalUtil::single = 0 static protected
Definition at line 671 of file hcalUtil.h.
Referenced by deleteInstance(), and getInstance().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype2/hcalLab/hcalUtil.h
analysis/blob/master/Prototype2/hcalLab/hcalUtil.C