Analysis Software: analysis/blob/master/TPC/SCDCorrections/simRho.cc File Reference
simRho.cc File Reference
#include <iostream>
#include <fstream>
#include "sHelix.h"
#include "sChargeMap.h"
#include "TStyle.h"
#include "TCanvas.h"
#include "TMath.h"
#include "TRandom3.h"
#include "TFile.h"
#include "TH1D.h"
#include "TH2D.h"
#include "TH3D.h"
Functions
int main ()
Variables
const int npid = 12+1
int apid [npid]
int acha [npid] = {-1,-1,+1,+1,+1,+1,+1,+1,+1,-1,-1,-1}
TString spid [npid]
TH1F * hpid = new TH1F("hpid","hpid",npid,-0.5,npid-0.5)
TH1F * hrpass = new TH1F("hrpass","hrpass; r [cm]",100,-15,+15)
TH1F * hzpass = new TH1F("hzpass","hzpass; z [cm]",100,-15,+15)
TH1F * hpidpass = new TH1F("hpidpass","hpidpass",npid,-0.5,npid-0.5)
TH1F * hptpass = new TH1F("hptpass","hptpass; pt [GeV]",100,0,10)
TH1F * hetapass = new TH1F("hetapass","hetapass; eta",100,-3,+3)
TH1F * hlengthpass =new TH1F("hlengthpass","hlengthpass; length [cm]",100,0,150)
TH1F * hbxing = new TH1F("hbxing","hbxing",150,-0.5,300-0.5)
TH3F * tracking = new TH3F("tracking","Generated tracks: tracking;xi;yi;zi",120,-100,+100,120,-100,+100,120,-100,+100)
Function Documentation
int main ()
Definition at line 49 of file simRho.cc.
References acha, apid, sHelix::breakIntoPieces(), Data, sChargeMap::Fill(), sHelix::findFirstInterceptTo(), hbxing, hetapass, hlengthpass, hpid, hpidpass, hptpass, hrpass, hzpass, i, n, npid, pi, pid, sChargeMap::Propagate(), sHelix::s(), sChargeMap::SaveIonMap(), sChargeMap::ScreenShot(), spid, t, t1, t2, tracking, TwoPi, x, y, and z.
Variable Documentation
int acha[npid] = {-1,-1,+1,+1,+1,+1,+1,+1,+1,-1,-1,-1}
Definition at line 24 of file simRho.cc.
Referenced by main().
int apid[npid]
Initial value:
=     {11, 13,
                      211,
                      321,
                      411, 431,
                      511,
                      2212,
                      3222, 3112, 3312, 3334,
                      0}
Definition at line 16 of file simRho.cc.
Referenced by main().
TH1F* hbxing = new TH1F("hbxing","hbxing",150,-0.5,300-0.5)
Definition at line 46 of file simRho.cc.
Referenced by main().
TH1F* hetapass = new TH1F("hetapass","hetapass; eta",100,-3,+3)
Definition at line 44 of file simRho.cc.
Referenced by main().
TH1F* hlengthpass =new TH1F("hlengthpass","hlengthpass; length [cm]",100,0,150)
Definition at line 45 of file simRho.cc.
Referenced by main().
TH1F* hpid = new TH1F("hpid","hpid",npid,-0.5,npid-0.5)
Definition at line 39 of file simRho.cc.
Referenced by main().
TH1F* hpidpass = new TH1F("hpidpass","hpidpass",npid,-0.5,npid-0.5)
Definition at line 42 of file simRho.cc.
Referenced by main().
TH1F* hptpass = new TH1F("hptpass","hptpass; pt [GeV]",100,0,10)
Definition at line 43 of file simRho.cc.
Referenced by main().
TH1F* hrpass = new TH1F("hrpass","hrpass; r [cm]",100,-15,+15)
Definition at line 40 of file simRho.cc.
Referenced by main().
TH1F* hzpass = new TH1F("hzpass","hzpass; z [cm]",100,-15,+15)
Definition at line 41 of file simRho.cc.
Referenced by main().
const int npid = 12+1
Definition at line 15 of file simRho.cc.
Referenced by main().
TString spid[npid]
Initial value:
= {"e^{-}",
                      "#mu^{-}",
                      "#pi^{+}",
                      "K^{+}",
                      "D^{+}",
                      "D^{+}_{s}",
                      "B^{+}",
                      "p",
                      "#Sigma^{+}",
                      "#Sigma^{-}",
                      "#Xi^{-}",
                      "#Omega^{-}",
                      "Neutral"}
Definition at line 25 of file simRho.cc.
Referenced by main().
TH3F* tracking = new TH3F("tracking","Generated tracks: tracking;xi;yi;zi",120,-100,+100,120,-100,+100,120,-100,+100)
Definition at line 47 of file simRho.cc.
Referenced by main().