Analysis Software: PHG4GDMLConfig Class Reference
PHG4GDMLConfig Class Reference
PHG4GDMLConfig.
#include <coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLConfig.hh>
Public Member Functions
PHG4GDMLConfig ()
virtual ~PHG4GDMLConfig ()
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual void identify (std::ostream &os=std::cout) const
void exclude_physical_vol (const G4VPhysicalVolume *vol)
void exclude_logical_vol (const G4LogicalVolume *vol)
const std::set< const
G4VPhysicalVolume * > & get_excluded_physical_vol () const
const std::set< const
G4LogicalVolume * > & get_excluded_logical_vol () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Attributes
std::set< const
G4VPhysicalVolume * > excluded_physical_vol
std::set< const G4LogicalVolume * > excluded_logical_vol
Detailed Description
PHG4GDMLConfig.
Definition at line 25 of file PHG4GDMLConfig.hh.
Constructor & Destructor Documentation
PHG4GDMLConfig::PHG4GDMLConfig () inline
Definition at line 28 of file PHG4GDMLConfig.hh.
virtual PHG4GDMLConfig::~PHG4GDMLConfig () inline virtual
Definition at line 29 of file PHG4GDMLConfig.hh.
Member Function Documentation
void PHG4GDMLConfig::exclude_logical_vol (const G4LogicalVolume * vol) inline
Definition at line 44 of file PHG4GDMLConfig.hh.
References excluded_logical_vol.
void PHG4GDMLConfig::exclude_physical_vol (const G4VPhysicalVolume * vol) inline
Definition at line 43 of file PHG4GDMLConfig.hh.
References excluded_physical_vol.
Referenced by PHG4FullProjTiltedSpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_AzimuthalSeg(), PHG4SpacalDetector::Construct_AzimuthalSeg(), PHG4FullProjSpacalDetector::Construct_Fibers(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers(), PHG4FullProjSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4FullProjTiltedSpacalDetector::Construct_Fibers_SameLengthFiberPerTower(), PHG4SpacalDetector::ConstructMe(), and PHG4ForwardEcalDetector::PlaceTower().
const std::set<const G4LogicalVolume *>& PHG4GDMLConfig::get_excluded_logical_vol () const inline
Definition at line 46 of file PHG4GDMLConfig.hh.
References excluded_logical_vol.
Referenced by PHG4GDMLWriteStructure::TraverseVolumeTree().
const std::set<const G4VPhysicalVolume *>& PHG4GDMLConfig::get_excluded_physical_vol () const inline
Definition at line 45 of file PHG4GDMLConfig.hh.
References excluded_physical_vol.
Referenced by PHG4GDMLWriteStructure::TraverseVolumeTree().
virtual void PHG4GDMLConfig::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 37 of file PHG4GDMLConfig.hh.
References excluded_logical_vol, and excluded_physical_vol.
virtual int PHG4GDMLConfig::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Definition at line 36 of file PHG4GDMLConfig.hh.
virtual void PHG4GDMLConfig::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Definition at line 31 of file PHG4GDMLConfig.hh.
References excluded_logical_vol, and excluded_physical_vol.
Member Data Documentation
std::set<const G4LogicalVolume *> PHG4GDMLConfig::excluded_logical_vol private
Definition at line 50 of file PHG4GDMLConfig.hh.
Referenced by exclude_logical_vol(), get_excluded_logical_vol(), identify(), and Reset().
std::set<const G4VPhysicalVolume *> PHG4GDMLConfig::excluded_physical_vol private
Definition at line 49 of file PHG4GDMLConfig.hh.
Referenced by exclude_physical_vol(), get_excluded_physical_vol(), identify(), and Reset().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4gdml/PHG4GDMLConfig.hh