Analysis Software: PHG4SpacalPrototype4Subsystem Class Reference
PHG4SpacalPrototype4Subsystem Class Reference
#include <prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4SpacalPrototype4Subsystem.h>
Public Member Functions
PHG4SpacalPrototype4Subsystem (const std::string &name="CEMC")
constructor
virtual ~PHG4SpacalPrototype4Subsystem (void)
destructor
int InitRunSubsystem (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual PHG4Detector * GetDetector (void) const
accessors (reimplemented)
PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
void Print (const std::string &what="ALL") const
Public Member Functions inherited from PHG4DetectorSubsystem
virtual ~PHG4DetectorSubsystem ()
int Init (PHCompositeNode *) final
int InitRun (PHCompositeNode *) final
virtual int InitSubsystem (PHCompositeNode *)
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
PHParameters * GetParams () const
void set_double_param (const std::string &name, const double dval)
double get_double_param (const std::string &name) const
void set_int_param (const std::string &name, const int ival)
int get_int_param (const std::string &name) const
void set_string_param (const std::string &name, const std::string &sval)
std::string get_string_param (const std::string &name) const
void UseDB (const int i=1)
int ReadDB () const
FILE_TYPE get_filetype () const
void UseCalibFiles (const FILE_TYPE ftyp)
int SaveParamsToDB ()
int ReadParamsFromDB (const std::string &name, const int issuper)
int SaveParamsToFile (const FILE_TYPE ftyp)
int ReadParamsFromFile (const std::string &name, const FILE_TYPE ftyp, const int issuper)
void SetCalibrationFileDir (const std::string &calibdir)
void UpdateParametersWithMacro ()
void SetActive (const int i=1)
void SetAbsorberActive (const int i=1)
void SetAbsorberTruth (const int i=1)
void BlackHole (const int i=1)
void SuperDetector (const std::string &name)
const std::string SuperDetector () const
int GetLayer () const
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual int process_after_geant (PHCompositeNode *)
event processing
virtual PHG4EventAction * GetEventAction (void) const
return pointer to this subsystem event action
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
void SetDefaultParameters ()
load the default parameter to param
Private Attributes
PHG4SpacalPrototype4Detector * detector_
detector geometry
PHG4SteppingAction * steppingAction_
particle tracking "stepping" action
Additional Inherited Members
Public Types inherited from PHG4DetectorSubsystem
enum FILE_TYPE { none = 0, xml = 1, root = 2 }
Protected Member Functions inherited from PHG4DetectorSubsystem
PHG4DetectorSubsystem (const std::string &name="GenericSubsystem", const int lyr=0)
void InitializeParameters ()
void set_default_double_param (const std::string &name, const double dval)
void set_default_int_param (const std::string &name, const int ival)
void set_default_string_param (const std::string &name, const std::string &sval)
int BeginRunExecuted () const
Detailed Description
Definition at line 15 of file PHG4SpacalPrototype4Subsystem.h.
Constructor & Destructor Documentation
PHG4SpacalPrototype4Subsystem::PHG4SpacalPrototype4Subsystem (const std::string & name = "CEMC") explicit
constructor
Definition at line 26 of file PHG4SpacalPrototype4Subsystem.cc.
References PHG4DetectorSubsystem::InitializeParameters().
virtual PHG4SpacalPrototype4Subsystem::~PHG4SpacalPrototype4Subsystem (void) inline virtual
destructor
Definition at line 22 of file PHG4SpacalPrototype4Subsystem.h.
Member Function Documentation
PHG4Detector * PHG4SpacalPrototype4Subsystem::GetDetector (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 113 of file PHG4SpacalPrototype4Subsystem.cc.
References detector_.
PHG4SteppingAction* PHG4SpacalPrototype4Subsystem::GetSteppingAction (void) const inline virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 41 of file PHG4SpacalPrototype4Subsystem.h.
References steppingAction_.
int PHG4SpacalPrototype4Subsystem::InitRunSubsystem (PHCompositeNode * topNode) virtual
init
creates the detector_ object and place it on the node tree, under "DETECTORS" node (or whatever) reates the stepping action and place it on the node tree, under "ACTIONS" node creates relevant hit nodes that will be populated by the stepping action and stored in the output DST
Reimplemented from PHG4DetectorSubsystem.
Definition at line 35 of file PHG4SpacalPrototype4Subsystem.cc.
References PHG4HitContainer::AddLayer(), PHCompositeNode::addNode(), PHG4DetectorSubsystem::CheckOverlap(), detector_, PHNodeIterator::findFirst(), PHG4DetectorSubsystem::get_int_param(), PHG4DetectorSubsystem::GetParams(), Fun4AllBase::Name(), PHG4Detector::OverlapCheck(), PHG4SpacalPrototype4Detector::SetAbsorberActive(), PHG4SpacalPrototype4Detector::SetActive(), steppingAction_, PHG4DetectorSubsystem::SuperDetector(), PHG4SpacalPrototype4Detector::SuperDetector(), PHG4Detector::topNode(), PHG4SteppingAction::Verbosity(), and Fun4AllBase::Verbosity().
void PHG4SpacalPrototype4Subsystem::Print (const std::string & what = "ALL") const virtual
Print out some info about this module.
Parameters
what can be used to specify what to print exactly.
Reimplemented from SubsysReco.
Definition at line 118 of file PHG4SpacalPrototype4Subsystem.cc.
References PHG4DetectorSubsystem::BeginRunExecuted(), detector_, PHG4DetectorSubsystem::GetParams(), Fun4AllBase::Name(), PHParameters::Print(), and PHG4SpacalPrototype4Detector::Print().
int PHG4SpacalPrototype4Subsystem::process_event (PHCompositeNode * topNode) virtual
event processing
get all relevant nodes from top nodes (namely hit list) and pass that to the stepping action
Reimplemented from SubsysReco.
Definition at line 100 of file PHG4SpacalPrototype4Subsystem.cc.
References PHG4SteppingAction::SetInterfacePointers(), and steppingAction_.
void PHG4SpacalPrototype4Subsystem::SetDefaultParameters () private virtual
load the default parameter to param
Implements PHG4DetectorSubsystem.
Definition at line 137 of file PHG4SpacalPrototype4Subsystem.cc.
References PHG4DetectorSubsystem::set_default_double_param(), and PHG4DetectorSubsystem::set_default_int_param().
Member Data Documentation
PHG4SpacalPrototype4Detector* PHG4SpacalPrototype4Subsystem::detector_ private
detector geometry
derives from PHG4Detector
Definition at line 52 of file PHG4SpacalPrototype4Subsystem.h.
Referenced by GetDetector(), InitRunSubsystem(), and Print().
PHG4SteppingAction* PHG4SpacalPrototype4Subsystem::steppingAction_ private
particle tracking "stepping" action
derives from PHG4SteppingActions
Definition at line 56 of file PHG4SpacalPrototype4Subsystem.h.
Referenced by GetSteppingAction(), InitRunSubsystem(), and process_event().
The documentation for this class was generated from the following files:
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4SpacalPrototype4Subsystem.h
prototype/blob/master/simulation/g4simulation/g4caloprototype/PHG4SpacalPrototype4Subsystem.cc