Analysis Software: PdbClassMap< T > Class Template Reference
PdbClassMap< T > Class Template Reference
#include <coresoftware/blob/master/offline/database/pdbcal/base/PdbClassMap.h>
Public Member Functions
virtual ~PdbClassMap ()
T *& operator[] (const char *className)
std::map< const char *, T
*, strless< const char * >
>::iterator find (const char *className)
std::map< const char *, T
*, strless< const char * >
>::iterator end ()
void erase (const char *className)
Static Public Member Functions
static PdbClassMap * instance ()
Protected Member Functions
PdbClassMap ()
Private Attributes
std::map< const char *, T
*, strless< const char * > > _map
Static Private Attributes
static PdbClassMap * _instance = 0
Detailed Description
template<typename T>
class PdbClassMap< T >
Definition at line 27 of file PdbClassMap.h.
Constructor & Destructor Documentation
template<typename T > PdbClassMap< T >::~PdbClassMap () virtual
Definition at line 65 of file PdbClassMap.h.
template<typename T > PdbClassMap< T >::PdbClassMap () protected
Definition at line 48 of file PdbClassMap.h.
Member Function Documentation
template<typename T> std::map<const char*, T*, strless<const char*> >::iterator PdbClassMap< T >::end () inline
Definition at line 36 of file PdbClassMap.h.
References PdbClassMap< T >::_map.
Referenced by PgPostBankManager::createBank(), PgPostBankBackupStorage::createBank(), PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
template<typename T > void PdbClassMap< T >::erase (const char * className)
Definition at line 53 of file PdbClassMap.h.
template<typename T> std::map<const char*, T*, strless<const char*> >::iterator PdbClassMap< T >::find (const char * className) inline
Definition at line 35 of file PdbClassMap.h.
References PdbClassMap< T >::_map.
Referenced by PgPostBankManager::createBank(), PgPostBankBackupStorage::createBank(), PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
template<typename T > PdbClassMap< T > * PdbClassMap< T >::instance () static
Definition at line 75 of file PdbClassMap.h.
Referenced by PgPostBankManager::createBank(), PgPostBankBackupStorage::createBank(), PgPostBankBackupStorage::set_obj_info(), and PgPostBankBackupManager::SQLResultSet2BackupStorage().
template<typename T> T*& PdbClassMap< T >::operator[] (const char * className) inline
Definition at line 34 of file PdbClassMap.h.
References PdbClassMap< T >::_map.
Member Data Documentation
template<typename T> PdbClassMap< T > * PdbClassMap< T >::_instance = 0 static private
Definition at line 43 of file PdbClassMap.h.
template<typename T> std::map<const char*, T*, strless<const char*> > PdbClassMap< T >::_map private
Definition at line 44 of file PdbClassMap.h.
Referenced by PdbClassMap< T >::end(), PdbClassMap< T >::find(), and PdbClassMap< T >::operator[]().
The documentation for this class was generated from the following file:
coresoftware/blob/master/offline/database/pdbcal/base/PdbClassMap.h