Analysis Software: SvtxHitMap_v1 Class Reference
SvtxHitMap_v1 Class Reference
#include <coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHitMap_v1.h>
Public Member Functions
SvtxHitMap_v1 ()
SvtxHitMap_v1 (const SvtxHitMap_v1 &hitmap)
SvtxHitMap_v1 & operator= (const SvtxHitMap_v1 &hitmap)
virtual ~SvtxHitMap_v1 ()
void identify (std::ostream &os=std::cout) const
void Reset ()
Clear Event.
int isValid () const
isValid returns non zero if object contains vailid data
PHObject * CloneMe () const
Virtual copy constructor.
bool empty () const
size_t size () const
size_t count (unsigned int idkey) const
void clear ()
const SvtxHit * get (unsigned int idkey) const
SvtxHit * get (unsigned int idkey)
SvtxHit * insert (const SvtxHit *hit)
size_t erase (unsigned int idkey)
ConstIter begin () const
ConstIter find (unsigned int idkey) const
ConstIter end () const
Iter begin ()
Iter find (unsigned int idkey)
Iter end ()
Public Member Functions inherited from SvtxHitMap
virtual ~SvtxHitMap ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (SvtxHitMap_v1, 1)
Private Attributes
HitMap _map
Additional Inherited Members
Public Types inherited from SvtxHitMap
typedef std::map< unsigned int,
SvtxHit * > HitMap
typedef std::map< unsigned int,
SvtxHit * >::const_iterator ConstIter
typedef std::map< unsigned int,
SvtxHit * >::iterator Iter
Protected Member Functions inherited from SvtxHitMap
SvtxHitMap ()
Detailed Description
Definition at line 12 of file SvtxHitMap_v1.h.
Constructor & Destructor Documentation
SvtxHitMap_v1::SvtxHitMap_v1 ()
Definition at line 14 of file SvtxHitMap_v1.cc.
Referenced by CloneMe().
SvtxHitMap_v1::SvtxHitMap_v1 (const SvtxHitMap_v1 & hitmap)
Definition at line 19 of file SvtxHitMap_v1.cc.
References _map, begin(), end(), and SvtxHit::get_id().
SvtxHitMap_v1::~SvtxHitMap_v1 () virtual
Definition at line 44 of file SvtxHitMap_v1.cc.
References Reset().
Member Function Documentation
ConstIter SvtxHitMap_v1::begin () const inline virtual
Reimplemented from SvtxHitMap.
Definition at line 39 of file SvtxHitMap_v1.h.
References _map.
Referenced by operator=(), and SvtxHitMap_v1().
Iter SvtxHitMap_v1::begin () inline virtual
Reimplemented from SvtxHitMap.
Definition at line 43 of file SvtxHitMap_v1.h.
References _map.
SvtxHitMap_v1::ClassDef (SvtxHitMap_v1 , 1) private
void SvtxHitMap_v1::clear () inline virtual
Reimplemented from SvtxHitMap.
Definition at line 28 of file SvtxHitMap_v1.h.
References Reset().
PHObject* SvtxHitMap_v1::CloneMe () const inline virtual
Virtual copy constructor.
Reimplemented from SvtxHitMap.
Definition at line 23 of file SvtxHitMap_v1.h.
References SvtxHitMap_v1().
size_t SvtxHitMap_v1::count (unsigned int idkey) const inline virtual
Reimplemented from SvtxHitMap.
Definition at line 27 of file SvtxHitMap_v1.h.
References _map.
bool SvtxHitMap_v1::empty () const inline virtual
Reimplemented from SvtxHitMap.
Definition at line 25 of file SvtxHitMap_v1.h.
References _map.
ConstIter SvtxHitMap_v1::end () const inline virtual
Reimplemented from SvtxHitMap.
Definition at line 41 of file SvtxHitMap_v1.h.
References _map.
Referenced by operator=(), and SvtxHitMap_v1().
Iter SvtxHitMap_v1::end () inline virtual
Reimplemented from SvtxHitMap.
Definition at line 45 of file SvtxHitMap_v1.h.
References _map.
size_t SvtxHitMap_v1::erase (unsigned int idkey) inline virtual
Reimplemented from SvtxHitMap.
Definition at line 33 of file SvtxHitMap_v1.h.
References _map.
ConstIter SvtxHitMap_v1::find (unsigned int idkey) const inline virtual
Reimplemented from SvtxHitMap.
Definition at line 40 of file SvtxHitMap_v1.h.
References _map.
Iter SvtxHitMap_v1::find (unsigned int idkey) inline virtual
Reimplemented from SvtxHitMap.
Definition at line 44 of file SvtxHitMap_v1.h.
References _map.
const SvtxHit * SvtxHitMap_v1::get (unsigned int idkey) const virtual
Reimplemented from SvtxHitMap.
Definition at line 67 of file SvtxHitMap_v1.cc.
References _map.
SvtxHit * SvtxHitMap_v1::get (unsigned int idkey) virtual
Reimplemented from SvtxHitMap.
Definition at line 74 of file SvtxHitMap_v1.cc.
References _map.
void SvtxHitMap_v1::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from SvtxHitMap.
Definition at line 61 of file SvtxHitMap_v1.cc.
References _map.
SvtxHit * SvtxHitMap_v1::insert (const SvtxHit * hit) virtual
Reimplemented from SvtxHitMap.
Definition at line 81 of file SvtxHitMap_v1.cc.
References _map, SvtxHit::CloneMe(), and index.
int SvtxHitMap_v1::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from SvtxHitMap.
Definition at line 22 of file SvtxHitMap_v1.h.
SvtxHitMap_v1 & SvtxHitMap_v1::operator= (const SvtxHitMap_v1 & hitmap)
Definition at line 31 of file SvtxHitMap_v1.cc.
References _map, begin(), end(), SvtxHit::get_id(), and Reset().
void SvtxHitMap_v1::Reset () virtual
Clear Event.
Reimplemented from SvtxHitMap.
Definition at line 49 of file SvtxHitMap_v1.cc.
References _map.
Referenced by clear(), operator=(), and ~SvtxHitMap_v1().
size_t SvtxHitMap_v1::size (void) const inline virtual
Reimplemented from SvtxHitMap.
Definition at line 26 of file SvtxHitMap_v1.h.
References _map.
Member Data Documentation
HitMap SvtxHitMap_v1::_map private
Definition at line 48 of file SvtxHitMap_v1.h.
Referenced by begin(), count(), empty(), end(), erase(), find(), get(), identify(), insert(), operator=(), Reset(), size(), and SvtxHitMap_v1().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHitMap_v1.h
coresoftware/blob/master/offline/packages/trackbase_historic/SvtxHitMap_v1.cc