Analysis Software: macros/blob/master/macros/g4simulations/G4_FGEM_fsPHENIX.C File Reference
G4_FGEM_fsPHENIX.C File Reference
#include <fun4all/Fun4AllServer.h>
#include <g4detectors/PHG4SectorSubsystem.h>
#include <g4eval/SvtxEvaluator.h>
#include <g4main/PHG4Reco.h>
#include <g4trackfastsim/PHG4TrackFastSim.h>
#include <g4trackfastsim/PHG4TrackFastSimEval.h>
#include "GlobalVariables.C"
Functions
int make_GEM_station (string name, PHG4Reco *g4Reco, double zpos, double etamin, double etamax, const int N_Sector=8)
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem *gem)
Add drift layers to mini TPC.
void FGEM_Init ()
void FGEMSetup (PHG4Reco *g4Reco, const int N_Sector=8, const double min_eta=1.45)
void FGEM_FastSim_Reco (int verbosity=0)
void FGEM_FastSim_Eval (std::string outputfile, int verbosity=0)
Function Documentation
void AddLayers_MiniTPCDrift (PHG4SectorSubsystem * gem)
Add drift layers to mini TPC.
Definition at line 175 of file G4_FGEM_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::AddLayer(), assert, d, PHG4SectorSubsystem::get_geometry(), s, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by FGEMSetup(), and make_GEM_station().
void FGEM_FastSim_Eval (std::string outputfile, int verbosity = 0)
Definition at line 355 of file G4_FGEM_fsPHENIX.C.
References Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), and PHG4TrackFastSimEval::set_filename().
Referenced by Fun4All_G4_fsPHENIX(), and Fun4All_G4_fsPHENIX_FastSim().
void FGEM_FastSim_Reco (int verbosity = 0)
Definition at line 249 of file G4_FGEM_fsPHENIX.C.
References PHG4TrackFastSim::add_phg4hits(), PHG4TrackFastSim::add_state_name(), PHG4TrackFastSim::Cylinder, E, Fun4AllServer::instance(), Fun4AllServer::registerSubsystem(), PHG4TrackFastSim::set_sub_top_node_name(), PHG4TrackFastSim::set_trackmap_out_name(), PHG4TrackFastSim::set_use_vertex_in_fitting(), PHG4TrackFastSim::set_vertex_xy_resolution(), PHG4TrackFastSim::set_vertex_z_resolution(), verbosity, PHG4TrackFastSim::Verbosity(), and PHG4TrackFastSim::Vertical_Plane.
Referenced by Fun4All_G4_EICDetector_LQ(), Fun4All_G4_EICDetector_LQ_reference(), Fun4All_G4_EICDetector_RICH(), Fun4All_G4_fsPHENIX(), Fun4All_G4_fsPHENIX_FastSim(), and Fun4All_G4_fsPHENIX_pi0().
void FGEM_Init ()
Definition at line 29 of file G4_FGEM_fsPHENIX.C.
Referenced by G4Init(), and TrackingInit().
void FGEMSetup (PHG4Reco * g4Reco, const int N_Sector = 8, const double min_eta = 1.45)
Definition at line 33 of file G4_FGEM_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), make_GEM_station(), name, overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by G4Setup(), and Tracking().
int make_GEM_station (string name, PHG4Reco * g4Reco, double zpos, double etamin, double etamax, const int N_Sector = 8)
Definition at line 202 of file G4_FGEM_fsPHENIX.C.
References PHG4Sector::Sector_Geometry::AddLayers_HBD_GEM(), AddLayers_MiniTPCDrift(), PHG4Sector::Sector_Geometry::eta_to_polar_angle(), PHG4Sector::Sector_Geometry::FlatEdge(), PHG4SectorSubsystem::get_geometry(), overlapcheck, PHG4Subsystem::OverlapCheck(), PHG4Reco::registerSubsystem(), PHG4Sector::Sector_Geometry::set_material(), PHG4Sector::Sector_Geometry::set_max_polar_angle(), PHG4Sector::Sector_Geometry::set_max_polar_edge(), PHG4Sector::Sector_Geometry::set_min_polar_angle(), PHG4Sector::Sector_Geometry::set_min_polar_edge(), PHG4Sector::Sector_Geometry::set_N_Sector(), PHG4Sector::Sector_Geometry::set_normal_polar_angle(), PHG4Sector::Sector_Geometry::set_normal_start(), PHG4SectorSubsystem::SuperDetector(), t, and PHG4Sector::Sector_Geometry::Unit_cm().
Referenced by EGEMSetup(), and FGEMSetup().