Analysis Software: PHG4BlockGeomContainer Class Reference
PHG4BlockGeomContainer Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockGeomContainer.h>
Public Types
typedef std::map< int,
PHG4BlockGeom * > Map
typedef Map::iterator Iterator
typedef Map::const_iterator ConstIterator
typedef std::pair< Iterator,
Iterator > Range
typedef std::pair
< ConstIterator, ConstIterator > ConstRange
Public Member Functions
PHG4BlockGeomContainer ()
virtual ~PHG4BlockGeomContainer ()
void identify (std::ostream &os=std::cout) const
int AddLayerGeom (const int i, PHG4BlockGeom *mygeom)
int AddLayerGeom (PHG4BlockGeom *mygeom)
PHG4BlockGeom * GetLayerGeom (const int i)
int get_NLayers () const
std::pair< std::map< int,
PHG4BlockGeom * >
::const_iterator, std::map
< int, PHG4BlockGeom * >
::const_iterator > get_begin_end () const
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
std::map< int, PHG4BlockGeom * > _layergeoms
float _magfield
Detailed Description
Definition at line 14 of file PHG4BlockGeomContainer.h.
Member Typedef Documentation
typedef Map::const_iterator PHG4BlockGeomContainer::ConstIterator
Definition at line 19 of file PHG4BlockGeomContainer.h.
typedef std::pair<ConstIterator, ConstIterator> PHG4BlockGeomContainer::ConstRange
Definition at line 21 of file PHG4BlockGeomContainer.h.
typedef Map::iterator PHG4BlockGeomContainer::Iterator
Definition at line 18 of file PHG4BlockGeomContainer.h.
typedef std::map<int,PHG4BlockGeom *> PHG4BlockGeomContainer::Map
Definition at line 17 of file PHG4BlockGeomContainer.h.
typedef std::pair<Iterator, Iterator> PHG4BlockGeomContainer::Range
Definition at line 20 of file PHG4BlockGeomContainer.h.
Constructor & Destructor Documentation
PHG4BlockGeomContainer::PHG4BlockGeomContainer ()
Definition at line 9 of file PHG4BlockGeomContainer.cc.
PHG4BlockGeomContainer::~PHG4BlockGeomContainer () virtual
Definition at line 13 of file PHG4BlockGeomContainer.cc.
References _layergeoms.
Member Function Documentation
int PHG4BlockGeomContainer::AddLayerGeom (const int i, PHG4BlockGeom * mygeom)
Definition at line 37 of file PHG4BlockGeomContainer.cc.
References _layergeoms, i, and PHG4BlockGeom::set_layer().
Referenced by PHG4BlockSubsystem::InitRunSubsystem().
int PHG4BlockGeomContainer::AddLayerGeom (PHG4BlockGeom * mygeom)
Definition at line 50 of file PHG4BlockGeomContainer.cc.
References _layergeoms, and PHG4BlockGeom::get_layer().
std::pair<std::map<int,PHG4BlockGeom *>::const_iterator, std::map<int,PHG4BlockGeom *>::const_iterator> PHG4BlockGeomContainer::get_begin_end () const inline
Definition at line 32 of file PHG4BlockGeomContainer.h.
References _layergeoms.
Referenced by PHG4BlockCellReco::InitRun(), and DumpPHG4BlockGeomContainer::process_Node().
int PHG4BlockGeomContainer::get_NLayers () const inline
Definition at line 31 of file PHG4BlockGeomContainer.h.
References _layergeoms.
Referenced by DumpPHG4BlockGeomContainer::process_Node().
PHG4BlockGeom * PHG4BlockGeomContainer::GetLayerGeom (const int i)
Definition at line 63 of file PHG4BlockGeomContainer.cc.
References _layergeoms.
void PHG4BlockGeomContainer::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Definition at line 24 of file PHG4BlockGeomContainer.cc.
References _layergeoms, and _magfield.
Referenced by PHG4BlockCellReco::InitRun().
Member Data Documentation
std::map<int,PHG4BlockGeom *> PHG4BlockGeomContainer::_layergeoms protected
Definition at line 35 of file PHG4BlockGeomContainer.h.
Referenced by AddLayerGeom(), get_begin_end(), get_NLayers(), GetLayerGeom(), identify(), and ~PHG4BlockGeomContainer().
float PHG4BlockGeomContainer::_magfield protected
Definition at line 36 of file PHG4BlockGeomContainer.h.
Referenced by identify().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockGeomContainer.h
coresoftware/blob/master/simulation/g4simulation/g4detectors/PHG4BlockGeomContainer.cc