Analysis Software: PgPostBankWrapper Class Reference
PgPostBankWrapper Class Reference
#include <coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankWrapper.h>
Public Member Functions
PgPostBankWrapper ()
PgPostBankWrapper (PdbCalBank *b)
virtual ~PgPostBankWrapper ()
virtual PHObject * CloneMe () const
Virtual copy constructor.
void printHeader () const
void print ()
void printEntry (size_t s)
size_t getLength ()
PdbCalChan & getEntry (size_t pos)
void setLength (size_t len)
virtual bool commit ()
PdbBankID getBankID () const
PHTimeStamp getInsertTime () const
PHTimeStamp getStartValTime () const
PHTimeStamp getEndValTime () const
std::string getDescription () const
std::string getUserName () const
std::string getTableName () const
void setBankID (const PdbBankID &val)
void setInsertTime (const PHTimeStamp &val)
void setStartValTime (const PHTimeStamp &val)
void setEndValTime (const PHTimeStamp &val)
void setDescription (const std::string &val)
void setUserName (const std::string &val)
void setTableName (const std::string &val)
PdbCalBank * getBank ()
virtual int isValid (const PHTimeStamp &) const
Public Member Functions inherited from PgPostCalBank
PgPostCalBank ()
virtual ~PgPostCalBank ()
ClassDef (PgPostCalBank, 2)
Public Member Functions inherited from PdbCalBank
PdbCalBank ()
virtual ~PdbCalBank ()
ClassDef (PdbCalBank, 1)
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Private Member Functions
ClassDef (PgPostBankWrapper, 1)
Private Attributes
PdbBankID bankID
PHTimeStamp insertTime
PHTimeStamp startValTime
PHTimeStamp endValTime
std::string description
std::string userName
std::string tableName
PdbCalBank * bank
Detailed Description
Definition at line 19 of file PgPostBankWrapper.h.
Constructor & Destructor Documentation
PgPostBankWrapper::PgPostBankWrapper ()
Definition at line 22 of file PgPostBankWrapper.cc.
Referenced by CloneMe().
PgPostBankWrapper::PgPostBankWrapper (PdbCalBank * b)
Definition at line 27 of file PgPostBankWrapper.cc.
References bank, PgPostBankWrapperManager::instance(), and PgPostBankWrapperManager::registerWrapper().
PgPostBankWrapper::~PgPostBankWrapper () virtual
Definition at line 33 of file PgPostBankWrapper.cc.
References bank, PgPostBankWrapperManager::instance(), and PgPostBankWrapperManager::unregisterWrapper().
Member Function Documentation
PgPostBankWrapper::ClassDef (PgPostBankWrapper , 1) private
virtual PHObject* PgPostBankWrapper::CloneMe () const inline virtual
Virtual copy constructor.
Implements PdbCalBank.
Definition at line 25 of file PgPostBankWrapper.h.
References PgPostBankWrapper().
bool PgPostBankWrapper::commit () virtual
Definition at line 49 of file PgPostBankWrapper.cc.
References bank, PgPostApplication::getConnection(), PgPostApplication::instance(), PHWHERE, and tableName.
Referenced by PgPostApplication::commit().
PdbCalBank* PgPostBankWrapper::getBank () inline
Definition at line 52 of file PgPostBankWrapper.h.
References bank.
PdbBankID PgPostBankWrapper::getBankID () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 36 of file PgPostBankWrapper.h.
References bankID.
Referenced by PgPostBankWrapperManager::print().
std::string PgPostBankWrapper::getDescription () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 40 of file PgPostBankWrapper.h.
References description.
PHTimeStamp PgPostBankWrapper::getEndValTime () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 39 of file PgPostBankWrapper.h.
References endValTime.
PdbCalChan& PgPostBankWrapper::getEntry (size_t pos) inline virtual
Implements PgPostCalBank.
Definition at line 32 of file PgPostBankWrapper.h.
References bank, and PdbCalBank::getEntry().
PHTimeStamp PgPostBankWrapper::getInsertTime () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 37 of file PgPostBankWrapper.h.
References insertTime.
size_t PgPostBankWrapper::getLength () inline virtual
Implements PgPostCalBank.
Definition at line 31 of file PgPostBankWrapper.h.
References bank, and PdbCalBank::getLength().
PHTimeStamp PgPostBankWrapper::getStartValTime () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 38 of file PgPostBankWrapper.h.
References startValTime.
std::string PgPostBankWrapper::getTableName () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 42 of file PgPostBankWrapper.h.
References tableName.
Referenced by PgPostBankWrapperManager::print().
std::string PgPostBankWrapper::getUserName () const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 41 of file PgPostBankWrapper.h.
References userName.
virtual int PgPostBankWrapper::isValid (const PHTimeStamp &) const inline virtual
Reimplemented from PgPostCalBank.
Definition at line 53 of file PgPostBankWrapper.h.
void PgPostBankWrapper::print () inline virtual
Implements PgPostCalBank.
Definition at line 28 of file PgPostBankWrapper.h.
References bank, and PdbCalBank::print().
void PgPostBankWrapper::printEntry (size_t s) inline virtual
Implements PgPostCalBank.
Definition at line 29 of file PgPostBankWrapper.h.
References bank, and PdbCalBank::printEntry().
void PgPostBankWrapper::printHeader () const virtual
Reimplemented from PgPostCalBank.
Definition at line 39 of file PgPostBankWrapper.cc.
References bankID, description, endValTime, insertTime, PdbBankID::print(), startValTime, and userName.
Referenced by PgPostBankManager::fetchBank().
void PgPostBankWrapper::setBankID (const PdbBankID & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 44 of file PgPostBankWrapper.h.
References bankID.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
void PgPostBankWrapper::setDescription (const std::string & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 48 of file PgPostBankWrapper.h.
References description.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
void PgPostBankWrapper::setEndValTime (const PHTimeStamp & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 47 of file PgPostBankWrapper.h.
References endValTime.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
void PgPostBankWrapper::setInsertTime (const PHTimeStamp & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 45 of file PgPostBankWrapper.h.
References insertTime.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
void PgPostBankWrapper::setLength (size_t len) inline virtual
Implements PgPostCalBank.
Definition at line 33 of file PgPostBankWrapper.h.
References bank, and PdbCalBank::setLength().
void PgPostBankWrapper::setStartValTime (const PHTimeStamp & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 46 of file PgPostBankWrapper.h.
References startValTime.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
void PgPostBankWrapper::setTableName (const std::string & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 50 of file PgPostBankWrapper.h.
References tableName.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
void PgPostBankWrapper::setUserName (const std::string & val) inline virtual
Reimplemented from PgPostCalBank.
Definition at line 49 of file PgPostBankWrapper.h.
References userName.
Referenced by PgPostBankManager::createBank(), PgPostBankManager::fetchBank(), and PgPostCalBankIterator::next().
Member Data Documentation
PdbCalBank* PgPostBankWrapper::bank private
Definition at line 64 of file PgPostBankWrapper.h.
Referenced by commit(), getBank(), getEntry(), getLength(), PgPostBankWrapper(), print(), printEntry(), setLength(), and ~PgPostBankWrapper().
PdbBankID PgPostBankWrapper::bankID private
Definition at line 56 of file PgPostBankWrapper.h.
Referenced by getBankID(), printHeader(), and setBankID().
std::string PgPostBankWrapper::description private
Definition at line 60 of file PgPostBankWrapper.h.
Referenced by getDescription(), printHeader(), and setDescription().
PHTimeStamp PgPostBankWrapper::endValTime private
Definition at line 59 of file PgPostBankWrapper.h.
Referenced by getEndValTime(), printHeader(), and setEndValTime().
PHTimeStamp PgPostBankWrapper::insertTime private
Definition at line 57 of file PgPostBankWrapper.h.
Referenced by getInsertTime(), printHeader(), and setInsertTime().
PHTimeStamp PgPostBankWrapper::startValTime private
Definition at line 58 of file PgPostBankWrapper.h.
Referenced by getStartValTime(), printHeader(), and setStartValTime().
std::string PgPostBankWrapper::tableName private
Definition at line 62 of file PgPostBankWrapper.h.
Referenced by commit(), getTableName(), and setTableName().
std::string PgPostBankWrapper::userName private
Definition at line 61 of file PgPostBankWrapper.h.
Referenced by getUserName(), printHeader(), and setUserName().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankWrapper.h
coresoftware/blob/master/offline/database/pdbcal/pg/PgPostBankWrapper.cc