Analysis Software: analysis/blob/master/EICAnalysis/macros/leptoquarks_analysis/likelihood.C File Reference
likelihood.C File Reference
#include "tau_commons.h"
Functions
double Average (vector< double > v)
int likelihood ()
Function Documentation
double Average (vector< double > v)
Compare reconstructed observables between tau jets and quark jets
Written by nils..nosp@m.feeg.nosp@m.e@sto.nosp@m.nybr.nosp@m.ook.e.nosp@m.du & sean..nosp@m.jeff.nosp@m.as@st.nosp@m.onyb.nosp@m.rook..nosp@m.edu
Definition at line 11 of file likelihood.C.
References i, and sum().
int likelihood ()
Definition at line 20 of file likelihood.C.
References Average(), file, filename, g, i, SVM_v1::id_e, j, k, n, phi, pid, TauVsDIS_MachineLearning_Differentiation::seed, tau_commons::select_accept_jet(), tau_commons::select_true_tau(), tau_commons::select_true_uds(), and t.
Referenced by likelihood_topology().