Analysis Software: PHG4PhenixTrackingAction Class Reference
PHG4PhenixTrackingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4PhenixTrackingAction.h>
Public Member Functions
PHG4PhenixTrackingAction (void)
virtual ~PHG4PhenixTrackingAction ()
void AddAction (PHG4TrackingAction *action)
register an action. This is called in PHG4Reco::Init based on which actions are found on the tree
virtual void PreUserTrackingAction (const G4Track *)
virtual void PostUserTrackingAction (const G4Track *)
void Verbosity (int val)
Get/Set verbosity level.
int Verbosity () const
Private Types
typedef std::list
< PHG4TrackingAction * > ActionList
list of subsystem specific Event actions
Private Attributes
ActionList actions_
int verbosity_
Detailed Description
Definition at line 15 of file PHG4PhenixTrackingAction.h.
Member Typedef Documentation
typedef std::list<PHG4TrackingAction*> PHG4PhenixTrackingAction::ActionList private
list of subsystem specific Event actions
Definition at line 36 of file PHG4PhenixTrackingAction.h.
Constructor & Destructor Documentation
PHG4PhenixTrackingAction::PHG4PhenixTrackingAction (void) inline
Definition at line 18 of file PHG4PhenixTrackingAction.h.
PHG4PhenixTrackingAction::~PHG4PhenixTrackingAction () virtual
Definition at line 6 of file PHG4PhenixTrackingAction.cc.
References actions_.
Member Function Documentation
void PHG4PhenixTrackingAction::AddAction (PHG4TrackingAction * action) inline
register an action. This is called in PHG4Reco::Init based on which actions are found on the tree
Definition at line 23 of file PHG4PhenixTrackingAction.h.
References actions_.
Referenced by PHG4Reco::InitRun().
void PHG4PhenixTrackingAction::PostUserTrackingAction (const G4Track * track) virtual
Definition at line 34 of file PHG4PhenixTrackingAction.cc.
References actions_, and Verbosity().
void PHG4PhenixTrackingAction::PreUserTrackingAction (const G4Track * track) virtual
Definition at line 16 of file PHG4PhenixTrackingAction.cc.
References actions_, and Verbosity().
void PHG4PhenixTrackingAction::Verbosity (int val) inline
Get/Set verbosity level.
Definition at line 30 of file PHG4PhenixTrackingAction.h.
References verbosity_.
int PHG4PhenixTrackingAction::Verbosity () const inline
Definition at line 31 of file PHG4PhenixTrackingAction.h.
References verbosity_.
Referenced by PostUserTrackingAction(), and PreUserTrackingAction().
Member Data Documentation
ActionList PHG4PhenixTrackingAction::actions_ private
Definition at line 37 of file PHG4PhenixTrackingAction.h.
Referenced by AddAction(), PostUserTrackingAction(), PreUserTrackingAction(), and ~PHG4PhenixTrackingAction().
int PHG4PhenixTrackingAction::verbosity_ private
Definition at line 38 of file PHG4PhenixTrackingAction.h.
Referenced by Verbosity().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4PhenixTrackingAction.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4PhenixTrackingAction.cc