Analysis Software: JetEnergies Class Reference
JetEnergies Class Reference
Compares reconstructed jets to truth jets.
#include <analysis/blob/master/ForwardCalo/Flux_Return_Study/JetEnergies.h>
Public Member Functions
JetEnergies (const std::string &name="JETENERGIES", const std::string &recojetname="AntiKt_Tower_r0.3", const std::string &truthjetname="AntiKt_Truth_r0.3", const std::string &filename="g4eval_jets.root")
virtual ~JetEnergies ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_strict (bool b)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Member Functions
float GetTotalEnergy (PHG4HitContainer *hit_object)
void printInputInfo (PHCompositeNode *topNode)
print out the input object information (debugging upstream components)
void fillOutputNtuples (PHCompositeNode *topNode)
dump the evaluator information into ntuple for external analysis
void printOutputInfo (PHCompositeNode *topNode)
print out the ancestry information for detailed diagnosis
Private Attributes
std::string _recojetname
std::string _truthjetname
unsigned long _ievent
JetEvalStack * _jetevalstack
bool _strict
unsigned int _errors
bool _do_recojet_eval
bool _do_truthjet_eval
TNtuple * _ntp_recojet
TNtuple * _ntp_truthjet
std::string _filename
TFile * _tfile
PHG4HitContainer * _FluxReturn_plus_hit_container
PHG4HitContainer * _FluxReturn_minus_hit_container
PHG4HitContainer * _BH_1_hit_container
PHG4HitContainer * _BH_Forward_hit_container
PHG4HitContainer * _BH_Negative_hit_container
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Compares reconstructed jets to truth jets.
author Michael P. McCumber author David Kapukchyan
is from the old JetEvaluator.h file Plan: This module will trace the jet constituents to the greatest contributor Monte Carlo jet and then test one against the other.
Definition at line 36 of file JetEnergies.h.
Constructor & Destructor Documentation
JetEnergies::JetEnergies (const std::string & name = "JETENERGIES", const std::string & recojetname = "AntiKt_Tower_r0.3", const std::string & truthjetname = "AntiKt_Truth_r0.3", const std::string & filename = "g4eval_jets.root")
Definition at line 26 of file JetEnergies.C.
References verbosity.
virtual JetEnergies::~JetEnergies () inline virtual
Definition at line 44 of file JetEnergies.h.
Member Function Documentation
int JetEnergies::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 132 of file JetEnergies.C.
References _do_recojet_eval, _do_truthjet_eval, _filename, _ievent, _jetevalstack, _ntp_recojet, _ntp_truthjet, _tfile, Fun4AllReturnCodes::EVENT_OK, and verbosity.
void JetEnergies::fillOutputNtuples (PHCompositeNode * topNode) private
dump the evaluator information into ntuple for external analysis
Definition at line 164 of file JetEnergies.C.
References _BH_1_hit_container, _BH_Forward_hit_container, _BH_Negative_hit_container, _do_recojet_eval, _do_truthjet_eval, _FluxReturn_minus_hit_container, _FluxReturn_plus_hit_container, _ievent, _jetevalstack, _ntp_recojet, _ntp_truthjet, _recojetname, _truthjetname, JetMap::begin(), JetRecoEval::best_jet_from(), JetMap::end(), Jet::get_e(), JetRecoEval::get_energy_contribution(), Jet::get_eta(), Jet::get_id(), Jet::get_phi(), Jet::get_pt(), JetEvalStack::get_reco_eval(), GetTotalEnergy(), JetRecoEval::max_truth_jet_by_energy(), phi, PHWHERE, Jet::size_comp(), and verbosity.
Referenced by process_event().
float JetEnergies::GetTotalEnergy (PHG4HitContainer * hit_object) private
Definition at line 317 of file JetEnergies.C.
References assert, PHG4Hit::get_edep(), and PHG4HitContainer::getHits().
Referenced by fillOutputNtuples().
int JetEnergies::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 52 of file JetEnergies.C.
References _do_recojet_eval, _do_truthjet_eval, _filename, _ievent, _ntp_recojet, _ntp_truthjet, _tfile, and Fun4AllReturnCodes::EVENT_OK.
int JetEnergies::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 73 of file JetEnergies.C.
References _BH_1_hit_container, _BH_Forward_hit_container, _BH_Negative_hit_container, _FluxReturn_minus_hit_container, _FluxReturn_plus_hit_container, and Fun4AllReturnCodes::EVENT_OK.
void JetEnergies::printInputInfo (PHCompositeNode * topNode) private
print out the input object information (debugging upstream components)
Definition at line 154 of file JetEnergies.C.
Referenced by process_event().
void JetEnergies::printOutputInfo (PHCompositeNode * topNode) private
print out the ancestry information for detailed diagnosis
Definition at line 159 of file JetEnergies.C.
Referenced by process_event().
int JetEnergies::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 97 of file JetEnergies.C.
References _ievent, _jetevalstack, _recojetname, _strict, _truthjetname, Fun4AllReturnCodes::EVENT_OK, fillOutputNtuples(), JetEvalStack::next_event(), printInputInfo(), printOutputInfo(), JetEvalStack::set_strict(), JetEvalStack::set_verbosity(), and verbosity.
void JetEnergies::set_strict (bool b) inline
Definition at line 51 of file JetEnergies.h.
References _strict.
Member Data Documentation
PHG4HitContainer* JetEnergies::_BH_1_hit_container private
Definition at line 83 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and InitRun().
PHG4HitContainer* JetEnergies::_BH_Forward_hit_container private
Definition at line 84 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and InitRun().
PHG4HitContainer* JetEnergies::_BH_Negative_hit_container private
Definition at line 85 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and InitRun().
bool JetEnergies::_do_recojet_eval private
Definition at line 70 of file JetEnergies.h.
Referenced by End(), fillOutputNtuples(), and Init().
bool JetEnergies::_do_truthjet_eval private
Definition at line 71 of file JetEnergies.h.
Referenced by End(), fillOutputNtuples(), and Init().
unsigned int JetEnergies::_errors private
Definition at line 68 of file JetEnergies.h.
std::string JetEnergies::_filename private
Definition at line 77 of file JetEnergies.h.
Referenced by End(), and Init().
PHG4HitContainer* JetEnergies::_FluxReturn_minus_hit_container private
Definition at line 82 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and InitRun().
PHG4HitContainer* JetEnergies::_FluxReturn_plus_hit_container private
Definition at line 81 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and InitRun().
unsigned long JetEnergies::_ievent private
Definition at line 60 of file JetEnergies.h.
Referenced by End(), fillOutputNtuples(), Init(), and process_event().
JetEvalStack* JetEnergies::_jetevalstack private
Definition at line 62 of file JetEnergies.h.
Referenced by End(), fillOutputNtuples(), and process_event().
TNtuple* JetEnergies::_ntp_recojet private
Definition at line 73 of file JetEnergies.h.
Referenced by End(), fillOutputNtuples(), and Init().
TNtuple* JetEnergies::_ntp_truthjet private
Definition at line 74 of file JetEnergies.h.
Referenced by End(), fillOutputNtuples(), and Init().
std::string JetEnergies::_recojetname private
Definition at line 57 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and process_event().
bool JetEnergies::_strict private
Definition at line 67 of file JetEnergies.h.
Referenced by process_event(), and set_strict().
TFile* JetEnergies::_tfile private
Definition at line 78 of file JetEnergies.h.
Referenced by End(), and Init().
std::string JetEnergies::_truthjetname private
Definition at line 58 of file JetEnergies.h.
Referenced by fillOutputNtuples(), and process_event().
The documentation for this class was generated from the following files:
analysis/blob/master/ForwardCalo/Flux_Return_Study/JetEnergies.h
analysis/blob/master/ForwardCalo/Flux_Return_Study/JetEnergies.C