Analysis Software: TpcDefs Namespace Reference
TpcDefs Namespace Reference
Utility functions for TPC.
Functions
static const unsigned int
kBitShiftSectorId __attribute__ ((unused)) = 16
uint8_t getSectorId (TrkrDefs::hitsetkey key)
Get the sector id from hitsetkey.
uint8_t getSectorId (TrkrDefs::cluskey key)
Get the sector id from cluskey.
uint8_t getSide (TrkrDefs::hitsetkey key)
Get the side from hitsetkey.
uint8_t getSide (TrkrDefs::cluskey key)
Get the side id from cluskey.
uint16_t getPad (TrkrDefs::hitkey key)
Get the pad index from hitkey.
uint16_t getTBin (TrkrDefs::hitkey key)
Get the time bin from hitkey.
TrkrDefs::hitkey genHitKey (const uint16_t pad, const uint16_t tbin)
Generate a hitkey from a pad index and time bin.
TrkrDefs::hitsetkey genHitSetKey (const uint8_t lyr, const uint8_t sector, const uint8_t side)
Generate a hitsetkey for the tpc.
TrkrDefs::cluskey genClusKey (const uint8_t lyr, const uint8_t sector, const uint8_t side, const uint32_t clusid)
Generate a cluster key from indeces.
TrkrDefs::cluskey genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
Generate a cluster key using a hitsetkey and cluster id.
Detailed Description
Utility functions for TPC.
Contains the functions for manipulating the various keys used by the tpc for hits, hit sets, and clusters
Function Documentation
static const uint16_t MAXTBIN TpcDefs::__attribute__ ((unused)) = 16 static
TrkrDefs::cluskey TpcDefs::genClusKey (const uint8_t lyr, const uint8_t sector, const uint8_t side, const uint32_t clusid)
Generate a cluster key from indeces.
Parameters
[in] lyr Layer index
[in] sector Sector index
[in] side Side index
[in] clusid Cluster id
[out] cluskey
Definition at line 74 of file TpcDefs.cc.
References InttDefs::genHitSetKey().
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), TpcClusterizer::process_event(), and TpcPrototypeClusterizer::process_event().
TrkrDefs::cluskey TpcDefs::genClusKey (const TrkrDefs::hitsetkey hskey, const uint32_t clusid)
Generate a cluster key using a hitsetkey and cluster id.
Parameters
[in] hskey hitsetkey
[in] clusid Cluster id
[out] cluskey
Definition at line 83 of file TpcDefs.cc.
TrkrDefs::hitkey TpcDefs::genHitKey (const uint16_t pad, const uint16_t tbin)
Generate a hitkey from a pad index and time bin.
Parameters
[in] pad Pad index
[in] tbin Time bin
[out] hitkey
Definition at line 54 of file TpcDefs.cc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), PHG4TpcPadPlaneReadout::MapToPadPlane(), TpcPrototypeClusterizer::process_event(), and TpcClusterizer::process_event().
TrkrDefs::hitsetkey TpcDefs::genHitSetKey (const uint8_t lyr, const uint8_t sector, const uint8_t side)
Generate a hitsetkey for the tpc.
Parameters
[in] lyr Layer index
[in] sector Sector index
[in] side Side index
[out] hitsetkey Generate a hitsetkey for the tpc. The tracker id is known implicitly and used in the function.
Definition at line 63 of file TpcDefs.cc.
References TrkrDefs::genHitSetKey(), and TrkrDefs::tpcId.
Referenced by TpcPrototypeUnpacker::exportDSTCluster(), and PHG4TpcPadPlaneReadout::MapToPadPlane().
uint16_t TpcDefs::getPad (TrkrDefs::hitkey key)
Get the pad index from hitkey.
Parameters
[in] hitkey
[out] pad index
Definition at line 40 of file TpcDefs.cc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), SvtxEvaluator::fillOutputNtuples(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), PHG4TpcElectronDrift::process_event(), and TPCMLDataInterface::process_event().
uint8_t TpcDefs::getSectorId (TrkrDefs::hitsetkey key)
Get the sector id from hitsetkey.
Parameters
[in] hitsetkey
[out] sector id
Definition at line 12 of file TpcDefs.cc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), getSectorId(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), and PHG4TpcElectronDrift::process_event().
uint8_t TpcDefs::getSectorId (TrkrDefs::cluskey key)
Get the sector id from cluskey.
Parameters
[in] cluskey
[out] sector id
Definition at line 19 of file TpcDefs.cc.
References getSectorId().
uint8_t TpcDefs::getSide (TrkrDefs::hitsetkey key)
Get the side from hitsetkey.
Parameters
[in] hitsetkey
[out] side
Definition at line 26 of file TpcDefs.cc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), getSide(), TpcClusterizer::process_event(), TpcPrototypeClusterizer::process_event(), and PHG4TpcElectronDrift::process_event().
uint8_t TpcDefs::getSide (TrkrDefs::cluskey key)
Get the side id from cluskey.
Parameters
[in] cluskey
[out] side id
Definition at line 33 of file TpcDefs.cc.
References getSide().
uint16_t TpcDefs::getTBin (TrkrDefs::hitkey key)
Get the time bin from hitkey.
Parameters
[in] hitkey
[out] time bin
Definition at line 47 of file TpcDefs.cc.
Referenced by PHG4TpcDigitizer::DigitizeCylinderCells(), SvtxEvaluator::fillOutputNtuples(), TpcPrototypeClusterizer::process_event(), TpcClusterizer::process_event(), PHG4TpcElectronDrift::process_event(), and TPCMLDataInterface::process_event().