Analysis Software: oncsBuffer Class Reference
oncsBuffer Class Reference
#include <online_distribution/blob/master/newbasic/oncsBuffer.h>
Classes
struct buffer_ptr
Public Member Functions
oncsBuffer (PHDWORD *array, const PHDWORD length)
Event * getEvent ()
int buffer_swap ()
int * getEventData ()
int isGood () const
Public Member Functions inherited from buffer
buffer ()
virtual ~buffer ()
Static Public Member Functions
static int i4swap (const int in)
static int i22swap (const int in)
static short i2swap (const short in)
Static Public Member Functions inherited from buffer
static int makeBuffer (PHDWORD *bp, const int allocatedsize, buffer **bptr)
static int i4swap (const int in)
static unsigned int u4swap (const unsigned int in)
static int i22swap (const int in)
static short i2swap (const short in)
Protected Attributes
int * data_ptr
int buffer_size
int max_length
int current_index
buffer_ptr bptr
Detailed Description
Definition at line 17 of file oncsBuffer.h.
Constructor & Destructor Documentation
oncsBuffer::oncsBuffer (PHDWORD * array, const PHDWORD length)
Definition at line 6 of file oncsBuffer.cc.
References bptr, buffer_size, buffer_swap(), COUT, current_index, oncsBuffer::buffer_ptr::data, data_ptr, i4swap(), oncsBuffer::buffer_ptr::ID, max_length, ONCSBUFFERID, and PRDFBUFFERID.
Member Function Documentation
int oncsBuffer::buffer_swap ()
Definition at line 31 of file oncsBuffer.cc.
References bptr, BUFFERHEADERLENGTH, oncsBuffer::buffer_ptr::Bufseq, COUT, subevt_data::data, oncsevt_data::data, oncsBuffer::buffer_ptr::data, oncsevt_data::evt_length, oncsevt_data::evt_type, EVTHEADERLENGTH, i, i22swap(), i2swap(), i4swap(), oncsBuffer::buffer_ptr::ID, oncsBuffer::buffer_ptr::Length, Length, subevt_data::reserved, oncsBuffer::buffer_ptr::Runnr, SEVTHEADERLENGTH, subevt_data::sub_decoding, subevt_data::sub_id, subevt_data::sub_length, subevt_data::sub_padding, and subevt_data::sub_type.
Referenced by oncsBuffer().
Event * oncsBuffer::getEvent () virtual
Implements buffer.
Definition at line 166 of file oncsBuffer.cc.
References bptr, buffer_size, current_index, oncsBuffer::buffer_ptr::data, and Event::getEvtLength().
Referenced by oncsEventiterator::getNextEvent().
int* oncsBuffer::getEventData () inline virtual
Implements buffer.
Definition at line 33 of file oncsBuffer.h.
int oncsBuffer::i22swap (const int in) static
Definition at line 132 of file oncsBuffer.cc.
References c, i, and in.
Referenced by buffer_swap().
short oncsBuffer::i2swap (const short in) static
Definition at line 149 of file oncsBuffer.cc.
References c, i, and in.
Referenced by buffer_swap().
int oncsBuffer::i4swap (const int in) static
Definition at line 116 of file oncsBuffer.cc.
References c, i, and in.
Referenced by buffer_swap(), oncsBuffer(), and oncsEventiterator::read_next_buffer().
int oncsBuffer::isGood () const inline virtual
Implements buffer.
Definition at line 34 of file oncsBuffer.h.
Member Data Documentation
buffer_ptr oncsBuffer::bptr protected
Definition at line 54 of file oncsBuffer.h.
Referenced by buffer_swap(), getEvent(), and oncsBuffer().
int oncsBuffer::buffer_size protected
Definition at line 51 of file oncsBuffer.h.
Referenced by getEvent(), and oncsBuffer().
int oncsBuffer::current_index protected
Definition at line 53 of file oncsBuffer.h.
Referenced by getEvent(), and oncsBuffer().
int* oncsBuffer::data_ptr protected
Definition at line 50 of file oncsBuffer.h.
Referenced by oncsBuffer().
int oncsBuffer::max_length protected
Definition at line 52 of file oncsBuffer.h.
Referenced by oncsBuffer().
The documentation for this class was generated from the following files:
online_distribution/blob/master/newbasic/oncsBuffer.h
online_distribution/blob/master/newbasic/oncsBuffer.cc