Analysis Software: PHInitZVertexing Class Reference
PHInitZVertexing Class Reference
#include <coresoftware/blob/master/offline/packages/trackreco/PHInitZVertexing.h>
Public Member Functions
PHInitZVertexing (unsigned int nlayers=7, unsigned int min_nlayers=7, const std::string &name="PHInitZVertexing")
virtual ~PHInitZVertexing ()
void set_file_name (const std::string &fname)
void set_mag_field (float mag_field)
float get_mag_field () const
void set_min_pT (float pt)
void set_max_kappa (float kappa_max)
void set_min_d (float d_min)
void set_max_d (float d_max)
void set_min_dzdl (float dzdl_min)
void set_max_dzdl (float dzdl_max)
void set_min_z0 (float z0_min)
void set_max_z0 (float z0_max)
float get_max_kappa () const
float get_min_z0 () const
float get_max_z0 () const
void set_material (int layer, float value)
radiation length per layer, sequential layer indexes required here
void setCutOnDCA (bool cod)
turn on DCA limitation
void set_dcaxy_cut (float dcut)
sets an upper limit on X-Y DCA
void set_dcaz_cut (float dzcut)
sets an upper limit on Z DCA
void set_chi2_cut (float chi2_cut)
sets a chi2 cut
void set_ca_z_cut (float z_cut)
void setPtRescaleFactor (float pt_rescale)
void set_ca_phi_cut (float phi_cut)
void set_mult_onebin (float mult)
void set_mult_twobins (float mult)
void set_mult_threebins (float mult)
void set_min_zvtx_tracks (unsigned int min_zvtx_tracks)
const std::vector< int > & get_seeding_layer () const
void set_seeding_layer (const int *seedingLayer, const int n)
void add_zoom (unsigned int n_kappa, unsigned int n_phi, unsigned int n_d, unsigned int n_dzdl, unsigned int n_z0)
void set_nzooms ()
void reset_zooms ()
Public Member Functions inherited from PHInitVertexing
PHInitVertexing (const std::string &name="PHInitVertexing")
virtual ~PHInitVertexing ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
int Setup (PHCompositeNode *topNode)
int Process (PHCompositeNode *topNode)
int End (PHCompositeNode *)
Called at the end of all processing.
Private Member Functions
int create_nodes (PHCompositeNode *topNode)
int initialize_geometry (PHCompositeNode *topNode)
int get_nodes (PHCompositeNode *topNode)
int translate_input (PHCompositeNode *topNode)
void set_nbins (unsigned int izoom)
void initialize_houghbin ()
void vote_z_init (unsigned int zoomlevel)
void find_track_candidates_z_init (unsigned int zoomlevel)
void vote_z (unsigned int zoomlevel)
void find_track_candidates_z (unsigned int zoomlevel)
void vote_xy (unsigned int zoomlevel)
void find_track_candidates_xy (unsigned int zoomlevel)
void prune_z (unsigned int zoomlevel)
void prune_xy (unsigned int zoomlevel)
void reset_hits_used ()
int export_output ()
float kappa_to_pt (float kappa)
convert from inverse curvature to momentum
float pt_to_kappa (float pt)
convert from momentum to inverse curvature
void bins_to_SimpleTrack3D (std::vector< SimpleTrack3D > &temp_tracks, int imap, unsigned int zoomlevel)
int build_triplets_to_SimpleTrack3D (std::vector< SimpleTrack3D > &new_tracks, bool forward)
int cellular_automaton_zvtx_init (std::vector< SimpleTrack3D > &temp_tracks)
int fit_vertex ()
void convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const &input, Eigen::Matrix< float, 6, 6 > &output)
convert the covariance from HelixHough coords to x,y,z,px,py,pz
void shift_coordinate_system (double dx, double dy, double dz)
float shift_phi_range (float phi)
Private Attributes
int _event
PHTimer * _t_output_io
std::vector< int > _seeding_layer
unsigned int _nlayers
number of detector layers
unsigned int _min_nlayers
minimum number of layers to make a track
unsigned int _ca_nlayers
float _ca_chi2
std::vector< float > _radii
radial distance of each layer (cm)
std::vector< float > _material
material at each layer in rad. lengths
std::map< int, float > _user_material
material in user ladder indexes
float _mag_field
in Tesla
bool _use_max_kappa
bool fill_multi_zvtx
float _min_pt
float _max_kappa
float _min_d
float _max_d
float _min_dzdl
float _max_dzdl
float _min_z0
float _max_z0
bool _cut_on_dca
float _dcaxy_cut
float _dcaz_cut
float _pt_rescale
float _ca_phi_cut
float _ca_z_cut
float _z_cut
float _mult_onebin
float _mult_twobins
float _mult_threebins
unsigned int _min_zvtx_tracks
bool _override_min_zvtx_tracks
unsigned int bin
unsigned int ik
unsigned int ip
unsigned int id
unsigned int il
unsigned int iz
unsigned int nkappa
unsigned int nphi
unsigned int nd
unsigned int ndzdl
unsigned int nz0
TrkrDefs::cluskey cluster_key
std::map< int, unsigned int > _layer_ilayer_map
recorded layer indexes to internal sequential indexes
std::vector< SimpleTrack3D > _temp_tracks
std::vector< SimpleTrack3D > _tracks
working array of tracks
std::vector< HelixKalmanState > _track_states
std::vector< double > _track_errors
working array of track chisq
std::vector< Eigen::Matrix
< float, 5, 5 > > _track_covars
working array of track covariances
std::vector< float > _vertex
working array for collision vertex
std::vector< std::vector< float > > _vertex_list
BbcVertexMap * _bbc_vertexes
SvtxTrackMap * _trackmap
VertexFitter _vertex_finder
HelixHoughSpace * _hough_space
HelixHoughFuncs * _hough_funcs
TNtuple * _ntp_zvtx_by_event
TNtuple * _ntp_zvtx_by_track
TH2D * _z0_dzdl
TH2D * _kappa_phi
TH2D * _d_phi
TH3D * _kappa_d_phi
TFile * _ofile
TFile * _ofile2
std::string _fname
int _nlayers_all
int _nclus_mvtx
std::map< int, unsigned int > _layer_ilayer_map_all
std::vector< float > _radii_all
std::vector< std::vector
< unsigned int > > zooms_vec
std::map< unsigned int, bool > hits_used
std::map< unsigned int,
SimpleHit3D > hits_map
std::map< unsigned int,
HelixHoughBin * > bins_map
std::map< unsigned int,
HelixHoughBin * > bins_map_prev
std::map< unsigned int,
HelixHoughBin * > bins_map_cur
std::map< unsigned int,
HelixHoughBin * > bins_map_sel
std::map< unsigned int,
unsigned int > kappa_phi_map
std::map< unsigned int,
unsigned int > d_phi_map
std::map< unsigned int,
unsigned int > kappa_d_phi_map
float hit [50][3]
float hitpos3d [3]
unsigned int nzooms
bool separate_helicity
int helicity
int n_vtx_tracks
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Attributes inherited from PHInitVertexing
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
Detailed Description
Definition at line 43 of file PHInitZVertexing.h.
Constructor & Destructor Documentation
PHInitZVertexing::PHInitZVertexing (unsigned int nlayers = 7, unsigned int min_nlayers = 7, const std::string & name = "PHInitZVertexing")
Definition at line 70 of file PHInitZVertexing.cc.
References _event, and zooms_vec.
PHInitZVertexing::~PHInitZVertexing () virtual
Definition at line 166 of file PHInitZVertexing.cc.
References _hough_funcs, _hough_space, and _t_output_io.
Member Function Documentation
void PHInitZVertexing::add_zoom (unsigned int n_kappa, unsigned int n_phi, unsigned int n_d, unsigned int n_dzdl, unsigned int n_z0)
Definition at line 523 of file PHInitZVertexing.cc.
References zooms_vec.
Referenced by Process().
void PHInitZVertexing::bins_to_SimpleTrack3D (std::vector< SimpleTrack3D > & temp_tracks, int imap, unsigned int zoomlevel) private
Definition at line 1802 of file PHInitZVertexing.cc.
References _tracks, HelixHoughBin::begin_clusters(), bins_map_prev, bins_map_sel, SimpleTrack3D::d, SimpleTrack3D::dzdl, HelixHoughBin::end_clusters(), HelixHoughBin::get_count(), HelixHoughBin::get_dzdl_center(), HelixHoughBin::get_kappa_center(), HelixHoughBin::get_phi_center(), HelixHoughBin::get_z0_center(), hit, SimpleTrack3D::hits, hits_map, it, SimpleTrack3D::kappa, SimpleTrack3D::phi, and SimpleTrack3D::z0.
Referenced by Process().
int PHInitZVertexing::build_triplets_to_SimpleTrack3D (std::vector< SimpleTrack3D > & new_tracks, bool forward) private
Definition at line 1864 of file PHInitZVertexing.cc.
References _ca_phi_cut, _nlayers, _z_cut, SimpleHit3D::get_id(), SimpleHit3D::get_layer(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), hit, SimpleTrack3D::hits, hits_map, hits_used, it, M_PI, shift_phi_range(), and Fun4AllBase::Verbosity().
Referenced by Process().
int PHInitZVertexing::cellular_automaton_zvtx_init (std::vector< SimpleTrack3D > & temp_tracks) private
Definition at line 1986 of file PHInitZVertexing.cc.
References _ca_chi2, _ca_nlayers, _ca_phi_cut, _ca_z_cut, _dcaxy_cut, _hough_space, _mag_field, _material, _pt_rescale, _radii, _track_states, _tracks, Fun4AllReturnCodes::EVENT_OK, hits_map, hits_used, i, CellularAutomaton_v1::Reset(), CellularAutomaton_v1::run(), CellularAutomaton_v1::set_ca_chi2(), CellularAutomaton_v1::set_ca_chi2_layer(), CellularAutomaton_v1::set_ca_dcaxy_cut(), CellularAutomaton_v1::set_ca_phi_cut(), CellularAutomaton_v1::set_ca_z_cut(), CellularAutomaton_v1::set_hits_map(), CellularAutomaton_v1::set_hough_space(), CellularAutomaton_v1::set_mag_field(), CellularAutomaton_v1::set_n_layers(), CellularAutomaton_v1::set_propagate_forward(), CellularAutomaton_v1::set_pt_rescale(), CellularAutomaton_v1::set_remove_hits(), CellularAutomaton_v1::set_remove_inner_hits(), CellularAutomaton_v1::set_required_layers(), CellularAutomaton_v1::set_seeding_mode(), CellularAutomaton_v1::set_triplet_mode(), CellularAutomaton_v1::set_verbose(), and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::convertHelixCovarianceToEuclideanCovariance (float B, float phi, float d, float kappa, float z0, float dzdl, Eigen::Matrix< float, 5, 5 > const & input, Eigen::Matrix< float, 6, 6 > & output) private
convert the covariance from HelixHough coords to x,y,z,px,py,pz
Definition at line 2329 of file PHInitZVertexing.cc.
References d, and dzdl.
int PHInitZVertexing::create_nodes (PHCompositeNode * topNode) private
Definition at line 529 of file PHInitZVertexing.cc.
References _trackmap, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Setup().
int PHInitZVertexing::End (PHCompositeNode *) protected virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 492 of file PHInitZVertexing.cc.
References _d_phi, _fname, _kappa_d_phi, _kappa_phi, _ntp_zvtx_by_event, _ntp_zvtx_by_track, _ofile, _ofile2, _temp_tracks, _z0_dzdl, Fun4AllReturnCodes::EVENT_OK, fill_multi_zvtx, PHWHERE, and Fun4AllBase::Verbosity().
int PHInitZVertexing::export_output () private
Definition at line 818 of file PHInitZVertexing.cc.
References PHInitVertexing::_cluster_map, _mag_field, _track_covars, _track_errors, _trackmap, _tracks, _vertex, _vertex_list, PHInitVertexing::_vertex_map, SvtxTrackMap::clear(), SvtxVertexMap::clear(), col, d, dzdl, Fun4AllReturnCodes::EVENT_OK, SvtxTrack_v1::get_id(), SvtxTrack_v1::get_px(), SvtxTrack_v1::get_py(), SvtxTrack_v1::get_pz(), SvtxTrack_v1::get_quality(), helicity, hits_map, i, SvtxVertex::identify(), SvtxTrackMap::insert(), SvtxVertexMap::insert_clone(), SvtxTrack_v1::insert_cluster_key(), kappa_to_pt(), M_PI, phi, PHWHERE, SvtxTrack_v1::set_charge(), SvtxVertex_v1::set_chisq(), SvtxTrack_v1::set_dca2d(), SvtxVertex_v1::set_error(), SvtxTrack_v1::set_id(), SvtxTrack_v1::set_ndf(), SvtxVertex_v1::set_ndof(), SvtxVertex_v1::set_position(), SvtxTrack_v1::set_px(), SvtxTrack_v1::set_py(), SvtxTrack_v1::set_pz(), SvtxVertex_v1::set_t0(), SvtxTrack_v1::set_x(), SvtxTrack_v1::set_y(), SvtxTrack_v1::set_z(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::find_track_candidates_xy (unsigned int zoomlevel) private
Definition at line 1642 of file PHInitZVertexing.cc.
References _min_nlayers, bin, bins_map_cur, bins_map_prev, HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughBin::get_phi_bin(), HelixHoughBin::get_z0_bin(), ik, il, ip, it, iz, and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::find_track_candidates_z (unsigned int zoomlevel) private
Definition at line 1316 of file PHInitZVertexing.cc.
References _min_nlayers, bin, bins_map_cur, bins_map_sel, HelixHoughBin::get_count(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_z0_bin(), il, it, iz, and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::find_track_candidates_z_init (unsigned int zoomlevel) private
Definition at line 1127 of file PHInitZVertexing.cc.
References _hough_space, _min_nlayers, _z0_dzdl, bin, bins, bins_map, bins_map_sel, HelixHoughSpace::get_bin(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_z0_bins(), i, j, k, and Fun4AllBase::Verbosity().
Referenced by Process().
int PHInitZVertexing::fit_vertex () private
< working array of track chisq
< working array of track covariances
Definition at line 2073 of file PHInitZVertexing.cc.
References _dcaz_cut, _event, _max_z0, _min_z0, _min_zvtx_tracks, _mult_onebin, _mult_twobins, _ntp_zvtx_by_event, _ntp_zvtx_by_track, _track_covars, _track_errors, _track_states, _tracks, _vertex, _vertex_finder, _vertex_list, C, Fun4AllReturnCodes::EVENT_OK, fill_multi_zvtx, VertexFitter::findVertex(), i, iz, j, k, n_vtx_tracks, SimpleTrack3D::set_vertex_id(), and Fun4AllBase::Verbosity().
Referenced by Process().
float PHInitZVertexing::get_mag_field () const inline
Definition at line 55 of file PHInitZVertexing.h.
References _mag_field.
float PHInitZVertexing::get_max_kappa () const inline
Definition at line 70 of file PHInitZVertexing.h.
References _max_kappa.
float PHInitZVertexing::get_max_z0 () const inline
Definition at line 72 of file PHInitZVertexing.h.
References _max_z0.
float PHInitZVertexing::get_min_z0 () const inline
Definition at line 71 of file PHInitZVertexing.h.
References _min_z0.
int PHInitZVertexing::get_nodes (PHCompositeNode * topNode) private
const std::vector<int>& PHInitZVertexing::get_seeding_layer () const inline
Definition at line 127 of file PHInitZVertexing.h.
References _seeding_layer.
int PHInitZVertexing::initialize_geometry (PHCompositeNode * topNode) private
Definition at line 555 of file PHInitZVertexing.cc.
References _layer_ilayer_map, _layer_ilayer_map_all, _material, _nlayers, _nlayers_all, _radii, _radii_all, _seeding_layer, _user_material, Fun4AllReturnCodes::EVENT_OK, PHG4CylinderCellGeomContainer::get_begin_end(), PHG4CylinderCellGeom::get_layer(), PHG4CylinderGeom::get_layer(), PHG4CylinderCellGeom::get_radius(), PHG4CylinderGeom::get_radius(), PHG4CylinderCellGeom::get_thickness(), PHG4CylinderGeom::get_thickness(), findNode::getClass(), PHG4CylinderCellGeom::identify(), PHG4CylinderGeom::identify(), and Fun4AllBase::Verbosity().
Referenced by Setup().
void PHInitZVertexing::initialize_houghbin () private
Definition at line 1004 of file PHInitZVertexing.cc.
References _hough_space, bin, bins, bins_map, HelixHoughSpace::get_bin(), id, HelixHoughBin::identify(), ik, il, HelixHoughBin::init(), ip, iz, nd, ndzdl, nkappa, nphi, nz0, HelixHoughBin::set_hough_space(), HelixHoughBin::set_zoomlevel(), and Fun4AllBase::Verbosity().
Referenced by Process().
float PHInitZVertexing::kappa_to_pt (float kappa) private
convert from inverse curvature to momentum
Definition at line 983 of file PHInitZVertexing.cc.
References _mag_field, and _pt_rescale.
Referenced by export_output().
int PHInitZVertexing::Process (PHCompositeNode * topNode) protected virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implements PHInitVertexing.
Definition at line 287 of file PHInitZVertexing.cc.
References _ca_chi2, _ca_nlayers, _event, _temp_tracks, _track_covars, _track_errors, _track_states, _tracks, _vertex, _vertex_list, add_zoom(), bins_map, bins_map_cur, bins_map_prev, bins_map_sel, bins_to_SimpleTrack3D(), build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), Fun4AllReturnCodes::EVENT_OK, export_output(), find_track_candidates_xy(), find_track_candidates_z(), find_track_candidates_z_init(), fit_vertex(), helicity, hits_map, hits_used, i, initialize_houghbin(), nd, ndzdl, nkappa, nphi, nz0, prune_xy(), prune_z(), reset_hits_used(), reset_zooms(), separate_helicity, set_nbins(), shift_coordinate_system(), translate_input(), Fun4AllBase::Verbosity(), vote_xy(), vote_z(), and vote_z_init().
void PHInitZVertexing::prune_xy (unsigned int zoomlevel) private
Definition at line 1738 of file PHInitZVertexing.cc.
References _nlayers, HelixHoughBin::add_cluster_ID(), bins_map_prev, HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_global_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughBin::get_neighbors_global_bin(), HelixHoughBin::get_phi_bin(), HelixHoughBin::get_z0_bin(), it, set_nbins(), sign(), and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::prune_z (unsigned int zoomlevel) private
Definition at line 1685 of file PHInitZVertexing.cc.
References _nlayers, HelixHoughBin::add_cluster_ID(), bins_map_sel, HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_global_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughBin::get_neighbors_global_bin(), HelixHoughBin::get_phi_bin(), HelixHoughBin::get_z0_bin(), it, set_nbins(), sign(), and Fun4AllBase::Verbosity().
Referenced by Process().
float PHInitZVertexing::pt_to_kappa (float pt) private
convert from momentum to inverse curvature
Definition at line 987 of file PHInitZVertexing.cc.
References _mag_field, and _pt_rescale.
Referenced by Setup().
void PHInitZVertexing::reset_hits_used () private
Definition at line 1794 of file PHInitZVertexing.cc.
References hits_used, and it.
Referenced by Process().
void PHInitZVertexing::reset_zooms () inline
Definition at line 138 of file PHInitZVertexing.h.
References zooms_vec.
Referenced by Process().
void PHInitZVertexing::set_ca_phi_cut (float phi_cut) inline
Definition at line 105 of file PHInitZVertexing.h.
References _ca_phi_cut.
void PHInitZVertexing::set_ca_z_cut (float z_cut) inline
Definition at line 94 of file PHInitZVertexing.h.
References _ca_z_cut.
void PHInitZVertexing::set_chi2_cut (float chi2_cut) inline
sets a chi2 cut
Definition at line 90 of file PHInitZVertexing.h.
References _ca_chi2.
void PHInitZVertexing::set_dcaxy_cut (float dcut) inline
sets an upper limit on X-Y DCA
Definition at line 82 of file PHInitZVertexing.h.
References _dcaxy_cut.
void PHInitZVertexing::set_dcaz_cut (float dzcut) inline
sets an upper limit on Z DCA
Definition at line 86 of file PHInitZVertexing.h.
References _dcaz_cut.
void PHInitZVertexing::set_file_name (const std::string & fname) inline
Definition at line 51 of file PHInitZVertexing.h.
References _fname.
void PHInitZVertexing::set_mag_field (float mag_field) inline
Definition at line 52 of file PHInitZVertexing.h.
References _mag_field.
void PHInitZVertexing::set_material (int layer, float value)
radiation length per layer, sequential layer indexes required here
Definition at line 519 of file PHInitZVertexing.cc.
References _user_material, and value.
void PHInitZVertexing::set_max_d (float d_max) inline
Definition at line 65 of file PHInitZVertexing.h.
References _max_d.
void PHInitZVertexing::set_max_dzdl (float dzdl_max) inline
Definition at line 67 of file PHInitZVertexing.h.
References _max_dzdl.
void PHInitZVertexing::set_max_kappa (float kappa_max)
Definition at line 991 of file PHInitZVertexing.cc.
References _max_kappa, and _use_max_kappa.
void PHInitZVertexing::set_max_z0 (float z0_max) inline
Definition at line 69 of file PHInitZVertexing.h.
References _max_z0.
void PHInitZVertexing::set_min_d (float d_min) inline
Definition at line 64 of file PHInitZVertexing.h.
References _min_d.
void PHInitZVertexing::set_min_dzdl (float dzdl_min) inline
Definition at line 66 of file PHInitZVertexing.h.
References _min_dzdl.
void PHInitZVertexing::set_min_pT (float pt) inline
Definition at line 59 of file PHInitZVertexing.h.
References _min_pt.
void PHInitZVertexing::set_min_z0 (float z0_min) inline
Definition at line 68 of file PHInitZVertexing.h.
References _min_z0.
void PHInitZVertexing::set_min_zvtx_tracks (unsigned int min_zvtx_tracks)
Definition at line 174 of file PHInitZVertexing.cc.
References _min_zvtx_tracks, and _override_min_zvtx_tracks.
Referenced by Tracking_Reco().
void PHInitZVertexing::set_mult_onebin (float mult) inline
Definition at line 110 of file PHInitZVertexing.h.
References _mult_onebin.
void PHInitZVertexing::set_mult_threebins (float mult) inline
Definition at line 120 of file PHInitZVertexing.h.
References _mult_threebins.
void PHInitZVertexing::set_mult_twobins (float mult) inline
Definition at line 115 of file PHInitZVertexing.h.
References _mult_twobins.
void PHInitZVertexing::set_nbins (unsigned int izoom) private
Definition at line 996 of file PHInitZVertexing.cc.
References _hough_space, HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), HelixHoughSpace::get_n_z0_bins(), nd, ndzdl, nkappa, nphi, and nz0.
Referenced by Process(), prune_xy(), prune_z(), vote_xy(), and vote_z().
void PHInitZVertexing::set_nzooms () inline
Definition at line 137 of file PHInitZVertexing.h.
References nzooms, and zooms_vec.
Referenced by Setup().
void PHInitZVertexing::set_seeding_layer (const int * seedingLayer, const int n) inline
Definition at line 131 of file PHInitZVertexing.h.
References _seeding_layer.
Referenced by Tracking_Reco().
void PHInitZVertexing::setCutOnDCA (bool cod) inline
turn on DCA limitation
Definition at line 78 of file PHInitZVertexing.h.
References _cut_on_dca.
void PHInitZVertexing::setPtRescaleFactor (float pt_rescale) inline
adjust the fit pt by a recalibration factor (constant B versus real mag field)
Definition at line 101 of file PHInitZVertexing.h.
References _pt_rescale.
int PHInitZVertexing::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented from PHInitVertexing.
Definition at line 181 of file PHInitZVertexing.cc.
References _cut_on_dca, _d_phi, _dcaxy_cut, _dcaz_cut, _fname, _hough_funcs, _hough_space, _kappa_d_phi, _kappa_phi, _mag_field, _material, _max_d, _max_dzdl, _max_kappa, _max_z0, _min_d, _min_dzdl, _min_nlayers, _min_pt, _min_z0, _nlayers, _ntp_zvtx_by_event, _ntp_zvtx_by_track, _ofile, _ofile2, _pt_rescale, _radii, _t_output_io, _use_max_kappa, _z0_dzdl, Fun4AllReturnCodes::ABORTRUN, HelixHoughSpace::add_one_zoom(), create_nodes(), Fun4AllReturnCodes::EVENT_OK, fill_multi_zvtx, HelixHoughSpace::get_d_max(), HelixHoughSpace::get_d_min(), HelixHoughSpace::get_dzdl_max(), HelixHoughSpace::get_dzdl_min(), HelixHoughSpace::get_kappa_max(), HelixHoughSpace::get_kappa_min(), HelixHoughSpace::get_n_d_bins(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_kappa_bins(), HelixHoughSpace::get_n_phi_bins(), HelixHoughSpace::get_n_z0_bins(), HelixHoughSpace::get_phi_max(), HelixHoughSpace::get_phi_min(), HelixHoughSpace::get_z0_max(), HelixHoughSpace::get_z0_min(), i, initialize_geometry(), M_PI, nzooms, pt_to_kappa(), HelixHoughSpace::set_d_max(), HelixHoughSpace::set_d_min(), HelixHoughSpace::set_dzdl_max(), HelixHoughSpace::set_dzdl_min(), HelixHoughFuncs::set_hough_space(), HelixHoughSpace::set_kappa_max(), HelixHoughSpace::set_kappa_min(), set_nzooms(), HelixHoughSpace::set_phi_max(), HelixHoughSpace::set_phi_min(), HelixHoughSpace::set_z0_max(), HelixHoughSpace::set_z0_min(), PHInitVertexing::Setup(), PHTimer::stop(), Fun4AllBase::Verbosity(), and zooms_vec.
void PHInitZVertexing::shift_coordinate_system (double dx, double dy, double dz) private
Definition at line 2370 of file PHInitZVertexing.cc.
References _tracks, _vertex, dx, dy, SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), hit, hits_map, it, SimpleHit3D::set_x(), SimpleHit3D::set_y(), and SimpleHit3D::set_z().
Referenced by Process().
float PHInitZVertexing::shift_phi_range (float phi) private
Definition at line 2399 of file PHInitZVertexing.cc.
References M_PI.
Referenced by build_triplets_to_SimpleTrack3D().
int PHInitZVertexing::translate_input (PHCompositeNode * topNode) private
Definition at line 720 of file PHInitZVertexing.cc.
References PHInitVertexing::_cluster_map, _layer_ilayer_map, _min_zvtx_tracks, _nclus_mvtx, _nlayers, _override_min_zvtx_tracks, Fun4AllReturnCodes::EVENT_OK, SimpleHit3D::get_id(), TrkrClusterContainer::getClusters(), TrkrCluster::getError(), TrkrDefs::getLayer(), TrkrCluster::getPosition(), hit, hits_map, hits_used, i, it, j, PHWHERE, SimpleHit3D::print(), SimpleHit3D::set_cluskey(), SimpleHit3D::set_error(), SimpleHit3D::set_id(), SimpleHit3D::set_layer(), SimpleHit3D::set_size(), SimpleHit3D::set_x(), SimpleHit3D::set_y(), SimpleHit3D::set_z(), TrkrClusterContainer::size(), and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::vote_xy (unsigned int zoomlevel) private
Definition at line 1354 of file PHInitZVertexing.cc.
References _d_phi, _hough_funcs, _hough_space, _kappa_d_phi, _kappa_phi, HelixHoughBin::add_cluster_ID(), assert, HelixHoughBin::begin_clusters(), bin, bins_map_cur, bins_map_sel, HelixHoughFuncs::calculate_phi_range(), HelixHoughBin::clear_clusters(), HelixHoughBin::CloneMe(), d_phi_map, HelixHoughBin::end_clusters(), HelixHoughSpace::get_bin(), HelixHoughBin::get_count(), HelixHoughBin::get_d_bin(), HelixHoughSpace::get_d_bin_size(), HelixHoughBin::get_d_center(), HelixHoughSpace::get_d_min(), HelixHoughBin::get_dzdl_bin(), HelixHoughBin::get_global_bin(), HelixHoughBin::get_kappa_bin(), HelixHoughSpace::get_kappa_bin_size(), HelixHoughBin::get_kappa_center(), HelixHoughSpace::get_kappa_min(), HelixHoughSpace::get_n_phi_bins(), HelixHoughBin::get_phi_bin(), HelixHoughSpace::get_phi_bin(), HelixHoughSpace::get_phi_bin_size(), HelixHoughBin::get_phi_center(), HelixHoughSpace::get_phi_max(), HelixHoughSpace::get_phi_min(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), HelixHoughBin::get_z0_bin(), helicity, hit, hitpos3d, hits_map, i, id, ik, il, ip, it, iz, kappa_d_phi_map, kappa_phi_map, nd, nkappa, separate_helicity, HelixHoughBin::set_bin(), HelixHoughBin::set_bins(), HelixHoughFuncs::set_current_zoom(), set_nbins(), HelixHoughBin::set_zoomlevel(), and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::vote_z (unsigned int zoomlevel) private
Definition at line 1185 of file PHInitZVertexing.cc.
References _hough_funcs, _hough_space, _z0_dzdl, HelixHoughBin::add_cluster_ID(), assert, bin, bins_map_cur, bins_map_prev, HelixHoughFuncs::calculate_dzdl_range(), HelixHoughBin::clear_clusters(), HelixHoughBin::CloneMe(), HelixHoughSpace::get_bin(), HelixHoughSpace::get_d_bin_size(), HelixHoughBin::get_d_center(), HelixHoughBin::get_dzdl_bin(), HelixHoughSpace::get_dzdl_bin(), HelixHoughSpace::get_dzdl_bin_size(), HelixHoughBin::get_dzdl_center(), HelixHoughBin::get_global_bin(), HelixHoughSpace::get_kappa_bin_size(), HelixHoughBin::get_kappa_center(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_z0_bins(), HelixHoughBin::get_phi_bin(), HelixHoughSpace::get_phi_bin_size(), HelixHoughBin::get_phi_center(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), HelixHoughBin::get_z0_bin(), HelixHoughSpace::get_z0_bin_size(), HelixHoughBin::get_z0_center(), hit, hitpos3d, hits_map, il, it, iz, HelixHoughBin::set_bin(), HelixHoughBin::set_bins(), HelixHoughFuncs::set_current_zoom(), set_nbins(), HelixHoughBin::set_zoomlevel(), and Fun4AllBase::Verbosity().
Referenced by Process().
void PHInitZVertexing::vote_z_init (unsigned int zoomlevel) private
Definition at line 1031 of file PHInitZVertexing.cc.
References _hough_funcs, _hough_space, bin, bins_map, HelixHoughFuncs::calculate_dzdl_range(), HelixHoughSpace::get_bin(), HelixHoughSpace::get_d_max(), HelixHoughSpace::get_d_min(), HelixHoughSpace::get_dzdl_bin(), HelixHoughSpace::get_dzdl_max(), HelixHoughSpace::get_dzdl_min(), HelixHoughSpace::get_kappa_max(), HelixHoughSpace::get_kappa_min(), HelixHoughSpace::get_n_dzdl_bins(), HelixHoughSpace::get_n_z0_bins(), HelixHoughSpace::get_phi_max(), HelixHoughSpace::get_phi_min(), SimpleHit3D::get_x(), SimpleHit3D::get_y(), SimpleHit3D::get_z(), HelixHoughSpace::get_z0_bin_size(), HelixHoughSpace::get_z0_min(), hit, hitpos3d, hits_map, hits_used, il, it, iz, HelixHoughFuncs::set_current_zoom(), and Fun4AllBase::Verbosity().
Referenced by Process().
Member Data Documentation
BbcVertexMap* PHInitZVertexing::_bbc_vertexes private
Definition at line 277 of file PHInitZVertexing.h.
float PHInitZVertexing::_ca_chi2 private
Definition at line 214 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), Process(), and set_chi2_cut().
unsigned int PHInitZVertexing::_ca_nlayers private
Definition at line 212 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), and Process().
float PHInitZVertexing::_ca_phi_cut private
Definition at line 237 of file PHInitZVertexing.h.
Referenced by build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), and set_ca_phi_cut().
float PHInitZVertexing::_ca_z_cut private
Definition at line 238 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), and set_ca_z_cut().
bool PHInitZVertexing::_cut_on_dca private
Definition at line 233 of file PHInitZVertexing.h.
Referenced by setCutOnDCA(), and Setup().
TH2D* PHInitZVertexing::_d_phi private
Definition at line 293 of file PHInitZVertexing.h.
Referenced by End(), Setup(), and vote_xy().
float PHInitZVertexing::_dcaxy_cut private
Definition at line 234 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), set_dcaxy_cut(), and Setup().
float PHInitZVertexing::_dcaz_cut private
Definition at line 235 of file PHInitZVertexing.h.
Referenced by fit_vertex(), set_dcaz_cut(), and Setup().
int PHInitZVertexing::_event private
Definition at line 205 of file PHInitZVertexing.h.
Referenced by fit_vertex(), PHInitZVertexing(), and Process().
std::string PHInitZVertexing::_fname private
Definition at line 298 of file PHInitZVertexing.h.
Referenced by End(), set_file_name(), and Setup().
HelixHoughFuncs* PHInitZVertexing::_hough_funcs private
Definition at line 285 of file PHInitZVertexing.h.
Referenced by Setup(), vote_xy(), vote_z(), vote_z_init(), and ~PHInitZVertexing().
HelixHoughSpace* PHInitZVertexing::_hough_space private
Definition at line 284 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), find_track_candidates_z_init(), initialize_houghbin(), set_nbins(), Setup(), vote_xy(), vote_z(), vote_z_init(), and ~PHInitZVertexing().
TH3D* PHInitZVertexing::_kappa_d_phi private
Definition at line 294 of file PHInitZVertexing.h.
Referenced by End(), Setup(), and vote_xy().
TH2D* PHInitZVertexing::_kappa_phi private
Definition at line 292 of file PHInitZVertexing.h.
Referenced by End(), Setup(), and vote_xy().
std::map<int, unsigned int> PHInitZVertexing::_layer_ilayer_map private
recorded layer indexes to internal sequential indexes
Definition at line 264 of file PHInitZVertexing.h.
Referenced by initialize_geometry(), and translate_input().
std::map<int, unsigned int> PHInitZVertexing::_layer_ilayer_map_all private
Definition at line 301 of file PHInitZVertexing.h.
Referenced by initialize_geometry().
float PHInitZVertexing::_mag_field private
in Tesla
Definition at line 219 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), export_output(), get_mag_field(), kappa_to_pt(), pt_to_kappa(), set_mag_field(), and Setup().
std::vector<float> PHInitZVertexing::_material private
material at each layer in rad. lengths
Definition at line 216 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), initialize_geometry(), and Setup().
float PHInitZVertexing::_max_d private
Definition at line 227 of file PHInitZVertexing.h.
Referenced by set_max_d(), and Setup().
float PHInitZVertexing::_max_dzdl private
Definition at line 229 of file PHInitZVertexing.h.
Referenced by set_max_dzdl(), and Setup().
float PHInitZVertexing::_max_kappa private
Definition at line 225 of file PHInitZVertexing.h.
Referenced by get_max_kappa(), set_max_kappa(), and Setup().
float PHInitZVertexing::_max_z0 private
Definition at line 231 of file PHInitZVertexing.h.
Referenced by fit_vertex(), get_max_z0(), set_max_z0(), and Setup().
float PHInitZVertexing::_min_d private
Definition at line 226 of file PHInitZVertexing.h.
Referenced by set_min_d(), and Setup().
float PHInitZVertexing::_min_dzdl private
Definition at line 228 of file PHInitZVertexing.h.
Referenced by set_min_dzdl(), and Setup().
unsigned int PHInitZVertexing::_min_nlayers private
minimum number of layers to make a track
Definition at line 211 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), find_track_candidates_z_init(), and Setup().
float PHInitZVertexing::_min_pt private
Definition at line 224 of file PHInitZVertexing.h.
Referenced by set_min_pT(), and Setup().
float PHInitZVertexing::_min_z0 private
Definition at line 230 of file PHInitZVertexing.h.
Referenced by fit_vertex(), get_min_z0(), set_min_z0(), and Setup().
unsigned int PHInitZVertexing::_min_zvtx_tracks private
Definition at line 243 of file PHInitZVertexing.h.
Referenced by fit_vertex(), set_min_zvtx_tracks(), and translate_input().
float PHInitZVertexing::_mult_onebin private
Definition at line 240 of file PHInitZVertexing.h.
Referenced by fit_vertex(), and set_mult_onebin().
float PHInitZVertexing::_mult_threebins private
Definition at line 242 of file PHInitZVertexing.h.
Referenced by set_mult_threebins().
float PHInitZVertexing::_mult_twobins private
Definition at line 241 of file PHInitZVertexing.h.
Referenced by fit_vertex(), and set_mult_twobins().
int PHInitZVertexing::_nclus_mvtx private
Definition at line 300 of file PHInitZVertexing.h.
Referenced by translate_input().
unsigned int PHInitZVertexing::_nlayers private
number of detector layers
Definition at line 210 of file PHInitZVertexing.h.
Referenced by build_triplets_to_SimpleTrack3D(), initialize_geometry(), prune_xy(), prune_z(), Setup(), and translate_input().
int PHInitZVertexing::_nlayers_all private
Definition at line 299 of file PHInitZVertexing.h.
Referenced by initialize_geometry().
TNtuple* PHInitZVertexing::_ntp_zvtx_by_event private
Definition at line 289 of file PHInitZVertexing.h.
Referenced by End(), fit_vertex(), and Setup().
TNtuple* PHInitZVertexing::_ntp_zvtx_by_track private
Definition at line 290 of file PHInitZVertexing.h.
Referenced by End(), fit_vertex(), and Setup().
TFile* PHInitZVertexing::_ofile private
Definition at line 295 of file PHInitZVertexing.h.
Referenced by End(), and Setup().
TFile* PHInitZVertexing::_ofile2 private
Definition at line 296 of file PHInitZVertexing.h.
Referenced by End(), and Setup().
bool PHInitZVertexing::_override_min_zvtx_tracks private
Definition at line 244 of file PHInitZVertexing.h.
Referenced by set_min_zvtx_tracks(), and translate_input().
float PHInitZVertexing::_pt_rescale private
Definition at line 236 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), kappa_to_pt(), pt_to_kappa(), setPtRescaleFactor(), and Setup().
std::vector<float> PHInitZVertexing::_radii private
radial distance of each layer (cm)
Definition at line 215 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), initialize_geometry(), and Setup().
std::vector<float> PHInitZVertexing::_radii_all private
Definition at line 302 of file PHInitZVertexing.h.
Referenced by initialize_geometry().
std::vector<int> PHInitZVertexing::_seeding_layer private
Definition at line 208 of file PHInitZVertexing.h.
Referenced by get_seeding_layer(), initialize_geometry(), and set_seeding_layer().
PHTimer* PHInitZVertexing::_t_output_io private
Definition at line 206 of file PHInitZVertexing.h.
Referenced by Setup(), and ~PHInitZVertexing().
std::vector<SimpleTrack3D> PHInitZVertexing::_temp_tracks private
Definition at line 268 of file PHInitZVertexing.h.
Referenced by End(), and Process().
std::vector<Eigen::Matrix<float, 5, 5> > PHInitZVertexing::_track_covars private
working array of track covariances
Definition at line 272 of file PHInitZVertexing.h.
Referenced by export_output(), fit_vertex(), and Process().
std::vector<double> PHInitZVertexing::_track_errors private
working array of track chisq
Definition at line 271 of file PHInitZVertexing.h.
Referenced by export_output(), fit_vertex(), and Process().
std::vector<HelixKalmanState> PHInitZVertexing::_track_states private
Definition at line 270 of file PHInitZVertexing.h.
Referenced by cellular_automaton_zvtx_init(), fit_vertex(), and Process().
SvtxTrackMap* PHInitZVertexing::_trackmap private
Definition at line 278 of file PHInitZVertexing.h.
Referenced by create_nodes(), and export_output().
std::vector<SimpleTrack3D> PHInitZVertexing::_tracks private
working array of tracks
Definition at line 269 of file PHInitZVertexing.h.
Referenced by bins_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), export_output(), fit_vertex(), Process(), and shift_coordinate_system().
bool PHInitZVertexing::_use_max_kappa private
Definition at line 221 of file PHInitZVertexing.h.
Referenced by set_max_kappa(), and Setup().
std::map<int, float> PHInitZVertexing::_user_material private
material in user ladder indexes
Definition at line 217 of file PHInitZVertexing.h.
Referenced by initialize_geometry(), and set_material().
std::vector<float> PHInitZVertexing::_vertex private
working array for collision vertex
Definition at line 273 of file PHInitZVertexing.h.
Referenced by export_output(), fit_vertex(), Process(), and shift_coordinate_system().
VertexFitter PHInitZVertexing::_vertex_finder private
Definition at line 281 of file PHInitZVertexing.h.
Referenced by fit_vertex().
std::vector<std::vector<float> > PHInitZVertexing::_vertex_list private
Definition at line 274 of file PHInitZVertexing.h.
Referenced by export_output(), fit_vertex(), and Process().
TH2D* PHInitZVertexing::_z0_dzdl private
Definition at line 291 of file PHInitZVertexing.h.
Referenced by End(), find_track_candidates_z_init(), Setup(), and vote_z().
float PHInitZVertexing::_z_cut private
Definition at line 239 of file PHInitZVertexing.h.
Referenced by build_triplets_to_SimpleTrack3D().
unsigned int PHInitZVertexing::bin private
Definition at line 246 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), find_track_candidates_z_init(), initialize_houghbin(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, HelixHoughBin* > PHInitZVertexing::bins_map private
Definition at line 307 of file PHInitZVertexing.h.
Referenced by find_track_candidates_z_init(), initialize_houghbin(), Process(), and vote_z_init().
std::map<unsigned int, HelixHoughBin* > PHInitZVertexing::bins_map_cur private
Definition at line 309 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), Process(), vote_xy(), and vote_z().
std::map<unsigned int, HelixHoughBin* > PHInitZVertexing::bins_map_prev private
Definition at line 308 of file PHInitZVertexing.h.
Referenced by bins_to_SimpleTrack3D(), find_track_candidates_xy(), Process(), prune_xy(), and vote_z().
std::map<unsigned int, HelixHoughBin* > PHInitZVertexing::bins_map_sel private
Definition at line 310 of file PHInitZVertexing.h.
Referenced by bins_to_SimpleTrack3D(), find_track_candidates_z(), find_track_candidates_z_init(), Process(), prune_z(), and vote_xy().
TrkrDefs::cluskey PHInitZVertexing::cluster_key private
Definition at line 261 of file PHInitZVertexing.h.
std::map<unsigned int, unsigned int> PHInitZVertexing::d_phi_map private
Definition at line 313 of file PHInitZVertexing.h.
Referenced by vote_xy().
bool PHInitZVertexing::fill_multi_zvtx private
Definition at line 222 of file PHInitZVertexing.h.
Referenced by End(), fit_vertex(), and Setup().
int PHInitZVertexing::helicity private
Definition at line 321 of file PHInitZVertexing.h.
Referenced by export_output(), Process(), and vote_xy().
float PHInitZVertexing::hit[50][3] private
Definition at line 316 of file PHInitZVertexing.h.
Referenced by bins_to_SimpleTrack3D(), build_triplets_to_SimpleTrack3D(), shift_coordinate_system(), translate_input(), vote_xy(), vote_z(), and vote_z_init().
float PHInitZVertexing::hitpos3d[3] private
Definition at line 317 of file PHInitZVertexing.h.
Referenced by vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, SimpleHit3D> PHInitZVertexing::hits_map private
Definition at line 306 of file PHInitZVertexing.h.
Referenced by bins_to_SimpleTrack3D(), build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), export_output(), Process(), shift_coordinate_system(), translate_input(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, bool> PHInitZVertexing::hits_used private
Definition at line 305 of file PHInitZVertexing.h.
Referenced by build_triplets_to_SimpleTrack3D(), cellular_automaton_zvtx_init(), Process(), reset_hits_used(), translate_input(), and vote_z_init().
unsigned int PHInitZVertexing::id private
Definition at line 250 of file PHInitZVertexing.h.
Referenced by initialize_houghbin(), and vote_xy().
unsigned int PHInitZVertexing::ik private
Definition at line 248 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), initialize_houghbin(), and vote_xy().
unsigned int PHInitZVertexing::il private
Definition at line 251 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), initialize_houghbin(), vote_xy(), vote_z(), and vote_z_init().
unsigned int PHInitZVertexing::ip private
Definition at line 249 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), initialize_houghbin(), and vote_xy().
unsigned int PHInitZVertexing::iz private
Definition at line 252 of file PHInitZVertexing.h.
Referenced by find_track_candidates_xy(), find_track_candidates_z(), fit_vertex(), initialize_houghbin(), vote_xy(), vote_z(), and vote_z_init().
std::map<unsigned int, unsigned int> PHInitZVertexing::kappa_d_phi_map private
Definition at line 314 of file PHInitZVertexing.h.
Referenced by vote_xy().
std::map<unsigned int, unsigned int> PHInitZVertexing::kappa_phi_map private
Definition at line 312 of file PHInitZVertexing.h.
Referenced by vote_xy().
int PHInitZVertexing::n_vtx_tracks private
Definition at line 322 of file PHInitZVertexing.h.
Referenced by fit_vertex().
unsigned int PHInitZVertexing::nd private
Definition at line 256 of file PHInitZVertexing.h.
Referenced by initialize_houghbin(), Process(), set_nbins(), and vote_xy().
unsigned int PHInitZVertexing::ndzdl private
Definition at line 257 of file PHInitZVertexing.h.
Referenced by initialize_houghbin(), Process(), and set_nbins().
unsigned int PHInitZVertexing::nkappa private
Definition at line 254 of file PHInitZVertexing.h.
Referenced by initialize_houghbin(), Process(), set_nbins(), and vote_xy().
unsigned int PHInitZVertexing::nphi private
Definition at line 255 of file PHInitZVertexing.h.
Referenced by initialize_houghbin(), Process(), and set_nbins().
unsigned int PHInitZVertexing::nz0 private
Definition at line 258 of file PHInitZVertexing.h.
Referenced by initialize_houghbin(), Process(), and set_nbins().
unsigned int PHInitZVertexing::nzooms private
Definition at line 318 of file PHInitZVertexing.h.
Referenced by set_nzooms(), and Setup().
bool PHInitZVertexing::separate_helicity private
Definition at line 320 of file PHInitZVertexing.h.
Referenced by Process(), and vote_xy().
std::vector<std::vector<unsigned int> > PHInitZVertexing::zooms_vec private
Definition at line 303 of file PHInitZVertexing.h.
Referenced by add_zoom(), PHInitZVertexing(), reset_zooms(), set_nzooms(), and Setup().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHInitZVertexing.h
coresoftware/blob/master/offline/packages/trackreco/PHInitZVertexing.cc