Analysis Software: online_distribution/blob/master/newbasic/packetRoutines.h File Reference
packetRoutines.h File Reference
#include "phenixOnline.h"
#include "packetPublic.h"
Functions
PTR_ret makeEmptyPacket (PACKET_ptr, UINT, UINT)
PTR_ret makeUnstructPacket (PACKET_ptr, UINT, UINT, UINT, UINT)
LOGIC_ret appendPacketError (PACKET_ptr, UINT, ERRORENTRYV1_ptr)
PTR_ret reservePacketDebugData (PACKET_ptr, UINT, UINT)
PTR_ret startUnstructDataWrite (PACKET_ptr, UINT, PHDWORD)
PTR_ret finishUnstructDataWrite (PACKET_ptr, UINT, PHDWORD)
VALUE_ret storePacketHits (PACKET_ptr, UINT, UINT *, BYTE *, UINT, UINT)
VALUE_ret fetchPacketHits (PACKET_ptr, UINT **, BYTE **, UINT *)
Function Documentation
LOGIC_ret appendPacketError (PACKET_ptr , UINT , ERRORENTRYV1_ptr)
Definition at line 120 of file packetRoutines.C.
References dwordCopy, errorEntryV1Length, extendPacketErrorBlock(), findPacketErrorStart(), getPacketErrorLength(), logicFailure, logicSuccess, and valueFailure.
VALUE_ret fetchPacketHits (PACKET_ptr , UINT ** , BYTE ** , UINT *)
Definition at line 320 of file packetRoutines.C.
References byteCopy, findPacketDataStart(), getPacketStructure(), getUnstructPacketDataLengthWords(), getUnstructPacketWordSize(), Unstructured, validPacketHdr(), and valueFailure.
PTR_ret finishUnstructDataWrite (PACKET_ptr , UINT , PHDWORD)
Definition at line 219 of file packetRoutines.C.
References extendUnstructPacketDataBlock(), findPacketEnd(), getUnstructPacketDataLengthWords(), ptrFailure, and valueFailure.
PTR_ret makeEmptyPacket (PACKET_ptr , UINT , UINT)
Definition at line 51 of file packetRoutines.C.
References findPacketEnd(), makePacketHdr(), ptrFailure, setPacketId(), and valueFailure.
Referenced by appendEmptyFramePacket().
PTR_ret makeUnstructPacket (PACKET_ptr , UINT , UINT , UINT , UINT)
Definition at line 96 of file packetRoutines.C.
References findPacketEnd(), makePacketHdr(), makeUnstructPacketDataDescr(), ptrFailure, setPacketId(), setPacketStructure(), Unstructured, and valueFailure.
Referenced by oEvent::addUnstructPacketData(), and fakeFrame().
PTR_ret reservePacketDebugData (PACKET_ptr , UINT , UINT)
Definition at line 146 of file packetRoutines.C.
References extendPacketDebugBlock(), findPacketDebugStart(), FORMAT_ERR_INVALID_APPEND, getPacketErrorLength(), ptrFailure, setPacketError(), and valueFailure.
PTR_ret startUnstructDataWrite (PACKET_ptr , UINT , PHDWORD)
Definition at line 173 of file packetRoutines.C.
References emptyPacket(), extendPacketDataBlock(), extendUnstructPacketDataBlock(), findPacketDataStart(), FORMAT_ERR_INVALID_APPEND, FORMAT_ERR_WRONG_STRUCTURE, getPacketLength(), getPacketStructure(), ptrFailure, setUserError(), Unstructured, and valueFailure.
VALUE_ret storePacketHits (PACKET_ptr , UINT , UINT * , BYTE * , UINT , UINT)
Definition at line 258 of file packetRoutines.C.
References byteClear, byteCopy, emptyPacket(), extendPacketDataBlock(), extendUnstructPacketDataBlock(), findPacketDataStart(), FORMAT_ERR_INVALID_HEADER, FORMAT_ERR_NONEMPTY_PACKET, FORMAT_ERR_WRONG_STRUCTURE, getPacketLength(), getPacketStructure(), getUnstructPacketDataPadding(), getUnstructPacketWordSize(), setPacketError(), Unstructured, validPacketHdr(), and valueFailure.
Referenced by oEvent::addUnstructPacketData(), and fakeFrame().