Analysis Software: PHG4TruthSubsystem Class Reference
PHG4TruthSubsystem Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthSubsystem.h>
Public Member Functions
PHG4TruthSubsystem (const std::string &name="TRUTH")
constructor
virtual ~PHG4TruthSubsystem (void)
destructor
int InitRun (PHCompositeNode *)
init
int process_event (PHCompositeNode *)
event processing
virtual int process_after_geant (PHCompositeNode *)
event processing
int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual PHG4EventAction * GetEventAction (void) const
accessors (reimplemented)
virtual PHG4TrackingAction * GetTrackingAction (void) const
return pointer to this subsystem stepping action
void SetSaveOnlyEmbeded (bool b=true)
only save the G4 truth information that is associated with the embedded particle
Public Member Functions inherited from PHG4Subsystem
PHG4Subsystem (const std::string &name="Generic Subsystem")
constructor
virtual ~PHG4Subsystem (void)
destructor
virtual PHG4Detector * GetDetector (void) const
return pointer to created detector object
virtual PHG4SteppingAction * GetSteppingAction (void) const
return pointer to this subsystem stepping action
virtual PHG4DisplayAction * GetDisplayAction () const
return pointer to this subsystem display setting
void OverlapCheck (const bool chk=true)
bool CheckOverlap () const
void SetMotherSubsystem (PHG4Subsystem *subsys)
PHG4Subsystem * GetMotherSubsystem () const
void SetLogicalVolume (G4LogicalVolume *vol)
G4LogicalVolume * GetLogicalVolume () const
virtual bool CanBeMotherSubsystem () const
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Attributes
PHG4TruthEventAction * m_EventAction
PHG4TruthTrackingAction * m_TrackingAction
bool m_SaveOnlyEmbededFlag
only save the G4 truth information that is associated with the embedded particle
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 16 of file PHG4TruthSubsystem.h.
Constructor & Destructor Documentation
PHG4TruthSubsystem::PHG4TruthSubsystem (const std::string & name = "TRUTH")
constructor
Definition at line 30 of file PHG4TruthSubsystem.cc.
virtual PHG4TruthSubsystem::~PHG4TruthSubsystem (void) inline virtual
destructor
Definition at line 23 of file PHG4TruthSubsystem.h.
Member Function Documentation
PHG4EventAction * PHG4TruthSubsystem::GetEventAction (void) const virtual
accessors (reimplemented)
Reimplemented from PHG4Subsystem.
Definition at line 151 of file PHG4TruthSubsystem.cc.
References m_EventAction.
PHG4TrackingAction * PHG4TruthSubsystem::GetTrackingAction (void) const virtual
return pointer to this subsystem stepping action
Reimplemented from PHG4Subsystem.
Definition at line 159 of file PHG4TruthSubsystem.cc.
References m_TrackingAction.
int PHG4TruthSubsystem::InitRun (PHCompositeNode * topNode) virtual
init
Reimplemented from SubsysReco.
Definition at line 39 of file PHG4TruthSubsystem.cc.
References PHCompositeNode::addNode(), PHNodeIterator::findFirst(), m_EventAction, and m_TrackingAction.
int PHG4TruthSubsystem::process_after_geant (PHCompositeNode * topNode) virtual
event processing
Reimplemented from PHG4Subsystem.
Definition at line 89 of file PHG4TruthSubsystem.cc.
References assert, PHG4TruthInfoContainer::delete_particle(), PHG4TruthInfoContainer::delete_vtx(), PHG4TruthInfoContainer::GetParticleRange(), PHG4TruthInfoContainer::GetVtxRange(), PHG4TruthInfoContainer::isEmbeded(), m_SaveOnlyEmbededFlag, and Fun4AllBase::Verbosity().
int PHG4TruthSubsystem::process_event (PHCompositeNode * topNode) virtual
event processing
Reimplemented from SubsysReco.
Definition at line 62 of file PHG4TruthSubsystem.cc.
References Fun4AllReturnCodes::EVENT_OK, m_EventAction, m_TrackingAction, PHWHERE, PHG4TruthEventAction::SetInterfacePointers(), and PHG4TruthTrackingAction::SetInterfacePointers().
int PHG4TruthSubsystem::ResetEvent (PHCompositeNode * topNode) virtual
Clean up after each event.
Reimplemented from SubsysReco.
Definition at line 143 of file PHG4TruthSubsystem.cc.
References m_EventAction, m_TrackingAction, PHG4TruthEventAction::ResetEvent(), and PHG4TruthTrackingAction::ResetEvent().
void PHG4TruthSubsystem::SetSaveOnlyEmbeded (bool b = true) inline
only save the G4 truth information that is associated with the embedded particle
Definition at line 44 of file PHG4TruthSubsystem.h.
References m_SaveOnlyEmbededFlag.
Member Data Documentation
PHG4TruthEventAction* PHG4TruthSubsystem::m_EventAction private
Definition at line 44 of file PHG4TruthSubsystem.h.
Referenced by GetEventAction(), InitRun(), process_event(), and ResetEvent().
bool PHG4TruthSubsystem::m_SaveOnlyEmbededFlag private
only save the G4 truth information that is associated with the embedded particle
Definition at line 52 of file PHG4TruthSubsystem.h.
Referenced by process_after_geant(), and SetSaveOnlyEmbeded().
PHG4TruthTrackingAction* PHG4TruthSubsystem::m_TrackingAction private
Definition at line 49 of file PHG4TruthSubsystem.h.
Referenced by GetTrackingAction(), InitRun(), process_event(), and ResetEvent().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthSubsystem.h
coresoftware/blob/master/simulation/g4simulation/g4main/PHG4TruthSubsystem.cc