Analysis Software: PHTrackSeeding Class Reference
PHTrackSeeding Class Reference abstract
Base class for track seeding.
#include <coresoftware/blob/master/offline/packages/trackreco/PHTrackSeeding.h>
Public Member Functions
PHTrackSeeding (const std::string &name="PHTrackSeeding")
virtual ~PHTrackSeeding ()
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
int End (PHCompositeNode *topNode)
Called at the end of all processing.
void set_track_map_name (const std::string &map_name)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Init (PHCompositeNode *)
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Protected Member Functions
virtual int Setup (PHCompositeNode *topNode)
virtual int Process (PHCompositeNode *topNode)=0
virtual int End ()=0
Called in SubsysReco::End.
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Protected Member Functions inherited from Fun4AllBase
Fun4AllBase (const std::string &name="NONAME")
Protected Attributes
TrkrClusterContainer * _cluster_map
SvtxVertexMap * _vertex_map
SvtxTrackMap * _track_map
AssocInfoContainer * _assoc_container
std::string _track_map_name
Private Member Functions
int CreateNodes (PHCompositeNode *topNode)
create new node output pointers
int GetNodes (PHCompositeNode *topNode)
fetch node pointers
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Detailed Description
Base class for track seeding.
Definition at line 29 of file PHTrackSeeding.h.
Constructor & Destructor Documentation
PHTrackSeeding::PHTrackSeeding (const std::string & name = "PHTrackSeeding")
Definition at line 26 of file PHTrackSeeding.cc.
virtual PHTrackSeeding::~PHTrackSeeding () inline virtual
Definition at line 33 of file PHTrackSeeding.h.
Member Function Documentation
int PHTrackSeeding::CreateNodes (PHCompositeNode * topNode) private
create new node output pointers
Definition at line 64 of file PHTrackSeeding.cc.
References _assoc_container, _track_map, Fun4AllReturnCodes::ABORTEVENT, PHCompositeNode::addNode(), Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), SvtxTrackMap::identify(), PHWHERE, and Fun4AllBase::Verbosity().
Referenced by Setup().
int PHTrackSeeding::End (PHCompositeNode *) virtual
Called at the end of all processing.
Reimplemented from SubsysReco.
Definition at line 46 of file PHTrackSeeding.cc.
References End().
virtual int PHTrackSeeding::End () protected pure virtual
Called in SubsysReco::End.
Implemented in PHHoughSeeding, and PHTruthTrackSeeding.
Referenced by End().
int PHTrackSeeding::GetNodes (PHCompositeNode * topNode) private
fetch node pointers
Definition at line 116 of file PHTrackSeeding.cc.
References _assoc_container, _cluster_map, _track_map, _vertex_map, Fun4AllReturnCodes::ABORTEVENT, Fun4AllReturnCodes::EVENT_OK, and PHWHERE.
Referenced by Setup().
int PHTrackSeeding::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 36 of file PHTrackSeeding.cc.
References Setup().
virtual int PHTrackSeeding::Process (PHCompositeNode * topNode) protected pure virtual
process event interface for trackers, called in process_event. implemented in derived classes
Implemented in PHHoughSeeding, and PHTruthTrackSeeding.
Referenced by process_event().
int PHTrackSeeding::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 41 of file PHTrackSeeding.cc.
References Process().
void PHTrackSeeding::set_track_map_name (const std::string & map_name) inline
Definition at line 38 of file PHTrackSeeding.h.
References _track_map_name.
int PHTrackSeeding::Setup (PHCompositeNode * topNode) protected virtual
setup interface for trackers, called in InitRun, setup things like pointers to nodes. overrided in derived classes
Reimplemented in PHHoughSeeding, and PHTruthTrackSeeding.
Definition at line 51 of file PHTrackSeeding.cc.
References CreateNodes(), Fun4AllReturnCodes::EVENT_OK, and GetNodes().
Referenced by InitRun(), PHTruthTrackSeeding::Setup(), and PHHoughSeeding::Setup().
Member Data Documentation
AssocInfoContainer* PHTrackSeeding::_assoc_container protected
Definition at line 59 of file PHTrackSeeding.h.
Referenced by CreateNodes(), PHHoughSeeding::export_output(), GetNodes(), and PHTruthTrackSeeding::Process().
TrkrClusterContainer* PHTrackSeeding::_cluster_map protected
Definition at line 56 of file PHTrackSeeding.h.
Referenced by PHHoughSeeding::export_output(), GetNodes(), PHTruthTrackSeeding::Process(), and PHHoughSeeding::translate_input().
SvtxTrackMap* PHTrackSeeding::_track_map protected
Definition at line 58 of file PHTrackSeeding.h.
Referenced by CreateNodes(), PHHoughSeeding::export_output(), GetNodes(), and PHTruthTrackSeeding::Process().
std::string PHTrackSeeding::_track_map_name protected
Definition at line 61 of file PHTrackSeeding.h.
Referenced by set_track_map_name().
SvtxVertexMap* PHTrackSeeding::_vertex_map protected
Definition at line 57 of file PHTrackSeeding.h.
Referenced by PHHoughSeeding::export_output(), GetNodes(), and PHHoughSeeding::vertexing().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/trackreco/PHTrackSeeding.h
coresoftware/blob/master/offline/packages/trackreco/PHTrackSeeding.cc