Analysis Software: CylinderGeom_Mvtx Class Reference
CylinderGeom_Mvtx Class Reference
#include <coresoftware/blob/master/offline/packages/mvtx/CylinderGeom_Mvtx.h>
Public Member Functions
CylinderGeom_Mvtx (int layer, int stave_type, int in_Nstaves, double in_layer_nominal_radius, double in_phistep, double in_phitilt, double in_pixel_x, double in_pixel_z, double in_pixel_thickness)
CylinderGeom_Mvtx ()
default ctor to allow ROOT stream of this class. Implemented using c++11 feature of delegating constructors
virtual ~CylinderGeom_Mvtx ()
void identify (std::ostream &os=std::cout) const
TVector3 get_local_from_world_coords (int stave, int half_stave, int module, int chip, TVector3 world_location)
TVector3 get_world_from_local_coords (int stave, int half_stave, int module, int chip, TVector3 sensor_local)
int get_pixel_from_local_coords (TVector3 sensor_local)
TVector3 get_local_coords_from_pixel (int NXZ)
int get_pixel_X_from_pixel_number (int NXZ)
int get_pixel_Z_from_pixel_number (int NXZ)
int get_pixel_number_from_xbin_zbin (int xbin, int zbin)
double get_pixel_x () const
double get_pixel_z () const
double get_pixel_thickness () const
void set_layer (const int i)
int get_layer () const
double get_radius () const
double get_stave_phi_tilt () const
int get_ladder_phi_index (int stave, int half_stave, int chip)
int get_ladder_z_index (int module, int chip)
void find_sensor_center (int stave_number, int half_stave_number, int module_number, int chip_number, double location[])
int get_N_staves () const
int get_N_half_staves () const
int get_NZ () const
int get_NX () const
Public Member Functions inherited from PHG4CylinderGeom
virtual ~PHG4CylinderGeom ()
virtual double get_thickness () const
virtual double get_zmin () const
virtual double get_zmax () const
virtual int get_nscint () const
virtual double get_tiltangle () const
virtual double get_phi_slat_zero () const
virtual void set_radius (const double r)
virtual void set_thickness (const double t)
virtual void set_zmin (const double z)
virtual void set_zmax (const double z)
virtual void set_nscint (const int i)
virtual void set_tiltangle (const double i)
virtual void set_phi_slat_zero (const double phi)
virtual void find_segment_center (const int segment_z_bin, const int segment_phi_bin, double location[])
virtual void find_strip_center (const int segment_z_bin, const int segment_phi_bin, const int strip_column, const int strip_index, double location[])
virtual void find_strip_index_values (const int segment_z_bin, const double ypos, const double zpos, int &strip_y_index, int &strip_z_index)
virtual void find_strip_center_local_coords (const int segment_z_bin, const int strip_y_index, const int strip_z_index, double location[])
virtual double get_strip_y_spacing () const
virtual double get_strip_z_spacing () const
virtual double get_strip_tilt () const
virtual int get_N_strip_columns () const
virtual int get_N_strips_per_column () const
virtual int get_N_sensors_in_layer () const
virtual void ImportParameters (const PHParameters &param)
load parameters from PHParameters, which interface to Database/XML/ROOT files
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Attributes
int layer
int stave_type
int N_staves
int N_half_staves
double Xsensor
double Zsensor
double layer_radius
double stave_phi_step
double stave_phi_tilt
double loc_sensor_in_chip [3]
double inner_loc_chip_in_module [9][3]
double inner_loc_module_in_halfstave [3]
double inner_loc_halfstave_in_stave [3]
double middle_loc_chip_in_module [14][3]
double middle_loc_module_in_halfstave [4][3]
double middle_loc_halfstave_in_stave [2][3]
double outer_loc_chip_in_module [14][3]
double outer_loc_module_in_halfstave [7][3]
double outer_loc_halfstave_in_stave [2][3]
double pixel_x
double pixel_z
double pixel_thickness
Additional Inherited Members
Protected Member Functions inherited from PHG4CylinderGeom
PHG4CylinderGeom ()
Detailed Description
Definition at line 10 of file CylinderGeom_Mvtx.h.
Constructor & Destructor Documentation
CylinderGeom_Mvtx::CylinderGeom_Mvtx (int layer, int stave_type, int in_Nstaves, double in_layer_nominal_radius, double in_phistep, double in_phitilt, double in_pixel_x, double in_pixel_z, double in_pixel_thickness)
Definition at line 11 of file CylinderGeom_Mvtx.cc.
References i, inner_loc_chip_in_module, inner_loc_halfstave_in_stave, inner_loc_module_in_halfstave, j, loc_sensor_in_chip, middle_loc_chip_in_module, middle_loc_halfstave_in_stave, middle_loc_module_in_halfstave, N_half_staves, outer_loc_chip_in_module, outer_loc_halfstave_in_stave, outer_loc_module_in_halfstave, stave_type, Xsensor, and Zsensor.
CylinderGeom_Mvtx::CylinderGeom_Mvtx () inline
default ctor to allow ROOT stream of this class. Implemented using c++11 feature of delegating constructors
Definition at line 16 of file CylinderGeom_Mvtx.h.
virtual CylinderGeom_Mvtx::~CylinderGeom_Mvtx () inline virtual
Definition at line 30 of file CylinderGeom_Mvtx.h.
Member Function Documentation
void CylinderGeom_Mvtx::find_sensor_center (int stave_number, int half_stave_number, int module_number, int chip_number, double location[])
Definition at line 638 of file CylinderGeom_Mvtx.cc.
References get_world_from_local_coords().
Referenced by MvtxClusterizer::ClusterMvtx(), SVReco::MakeGenFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
int CylinderGeom_Mvtx::get_ladder_phi_index (int stave, int half_stave, int chip)
Definition at line 613 of file CylinderGeom_Mvtx.cc.
References stave_type.
int CylinderGeom_Mvtx::get_ladder_z_index (int module, int chip)
Definition at line 588 of file CylinderGeom_Mvtx.cc.
References stave_type.
int CylinderGeom_Mvtx::get_layer () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 46 of file CylinderGeom_Mvtx.h.
References layer.
Referenced by PHG4MvtxHitReco::process_event().
TVector3 CylinderGeom_Mvtx::get_local_coords_from_pixel (int NXZ)
Definition at line 540 of file CylinderGeom_Mvtx.cc.
References double(), get_NX(), get_NZ(), pixel_x, and pixel_z.
Referenced by MvtxClusterizer::ClusterMvtx(), and PHG4MvtxHitReco::process_event().
TVector3 CylinderGeom_Mvtx::get_local_from_world_coords (int stave, int half_stave, int module, int chip, TVector3 world_location)
Definition at line 197 of file CylinderGeom_Mvtx.cc.
References double(), inner_loc_chip_in_module, inner_loc_halfstave_in_stave, inner_loc_module_in_halfstave, layer_radius, loc_sensor_in_chip, M_PI, middle_loc_chip_in_module, middle_loc_halfstave_in_stave, middle_loc_module_in_halfstave, outer_loc_chip_in_module, outer_loc_halfstave_in_stave, outer_loc_module_in_halfstave, stave_phi_step, stave_phi_tilt, and stave_type.
Referenced by PHG4MvtxHitReco::process_event().
int CylinderGeom_Mvtx::get_N_half_staves () const inline
Definition at line 55 of file CylinderGeom_Mvtx.h.
References N_half_staves.
int CylinderGeom_Mvtx::get_N_staves () const inline
Definition at line 54 of file CylinderGeom_Mvtx.h.
References N_staves.
int CylinderGeom_Mvtx::get_NX () const inline
Definition at line 60 of file CylinderGeom_Mvtx.h.
References pixel_x, and Xsensor.
Referenced by get_local_coords_from_pixel(), get_pixel_from_local_coords(), get_pixel_number_from_xbin_zbin(), get_pixel_X_from_pixel_number(), get_pixel_Z_from_pixel_number(), and PHG4MvtxHitReco::process_event().
int CylinderGeom_Mvtx::get_NZ () const inline
Definition at line 59 of file CylinderGeom_Mvtx.h.
References pixel_z, and Zsensor.
Referenced by get_local_coords_from_pixel(), get_pixel_from_local_coords(), and PHG4MvtxHitReco::process_event().
int CylinderGeom_Mvtx::get_pixel_from_local_coords (TVector3 sensor_local)
Definition at line 505 of file CylinderGeom_Mvtx.cc.
References get_NX(), get_NZ(), pixel_x, and pixel_z.
Referenced by PHG4MvtxHitReco::process_event().
int CylinderGeom_Mvtx::get_pixel_number_from_xbin_zbin (int xbin, int zbin)
Definition at line 475 of file CylinderGeom_Mvtx.cc.
References get_NX().
Referenced by MvtxClusterizer::ClusterMvtx(), and PHG4MvtxHitReco::process_event().
double CylinderGeom_Mvtx::get_pixel_thickness () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 43 of file CylinderGeom_Mvtx.h.
References pixel_thickness.
Referenced by MvtxClusterizer::ClusterMvtx().
double CylinderGeom_Mvtx::get_pixel_x () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 41 of file CylinderGeom_Mvtx.h.
References pixel_x.
Referenced by MvtxClusterizer::ClusterMvtx(), and PHG4MvtxHitReco::process_event().
int CylinderGeom_Mvtx::get_pixel_X_from_pixel_number (int NXZ)
Definition at line 485 of file CylinderGeom_Mvtx.cc.
References get_NX().
Referenced by PHG4MvtxHitReco::process_event().
double CylinderGeom_Mvtx::get_pixel_z () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 42 of file CylinderGeom_Mvtx.h.
References pixel_z.
Referenced by MvtxClusterizer::ClusterMvtx(), and PHG4MvtxHitReco::process_event().
int CylinderGeom_Mvtx::get_pixel_Z_from_pixel_number (int NXZ)
Definition at line 495 of file CylinderGeom_Mvtx.cc.
References get_NX().
Referenced by PHG4MvtxHitReco::process_event().
double CylinderGeom_Mvtx::get_radius () const inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 47 of file CylinderGeom_Mvtx.h.
References layer_radius.
double CylinderGeom_Mvtx::get_stave_phi_tilt () const inline
Definition at line 48 of file CylinderGeom_Mvtx.h.
References stave_phi_tilt.
Referenced by MvtxClusterizer::ClusterMvtx(), SVReco::MakeGenFitTrack(), PHGenFitTrkFitter::ReFitTrack(), and PHGenFitTrkProp::TrkrClusterToPHGenFitMeasurement().
TVector3 CylinderGeom_Mvtx::get_world_from_local_coords (int stave, int half_stave, int module, int chip, TVector3 sensor_local)
Definition at line 329 of file CylinderGeom_Mvtx.cc.
References double(), inner_loc_chip_in_module, inner_loc_halfstave_in_stave, inner_loc_module_in_halfstave, layer_radius, loc_sensor_in_chip, M_PI, middle_loc_chip_in_module, middle_loc_halfstave_in_stave, middle_loc_module_in_halfstave, outer_loc_chip_in_module, outer_loc_halfstave_in_stave, outer_loc_module_in_halfstave, stave_phi_step, stave_phi_tilt, and stave_type.
Referenced by MvtxClusterizer::ClusterMvtx(), find_sensor_center(), and PHG4MvtxHitReco::process_event().
void CylinderGeom_Mvtx::identify (std::ostream & os = std::cout) const virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHG4CylinderGeom.
Definition at line 574 of file CylinderGeom_Mvtx.cc.
References layer, layer_radius, N_half_staves, N_staves, pixel_thickness, pixel_x, pixel_z, and stave_type.
Referenced by PHG4MvtxHitReco::process_event().
void CylinderGeom_Mvtx::set_layer (const int i) inline virtual
Reimplemented from PHG4CylinderGeom.
Definition at line 45 of file CylinderGeom_Mvtx.h.
References i.
Member Data Documentation
double CylinderGeom_Mvtx::inner_loc_chip_in_module[9][3] protected
Definition at line 84 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::inner_loc_halfstave_in_stave[3] protected
Definition at line 86 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::inner_loc_module_in_halfstave[3] protected
Definition at line 85 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
int CylinderGeom_Mvtx::layer protected
Definition at line 63 of file CylinderGeom_Mvtx.h.
Referenced by get_layer(), and identify().
double CylinderGeom_Mvtx::layer_radius protected
Definition at line 72 of file CylinderGeom_Mvtx.h.
Referenced by get_local_from_world_coords(), get_radius(), get_world_from_local_coords(), and identify().
double CylinderGeom_Mvtx::loc_sensor_in_chip[3] protected
Definition at line 80 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::middle_loc_chip_in_module[14][3] protected
Definition at line 90 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::middle_loc_halfstave_in_stave[2][3] protected
Definition at line 92 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::middle_loc_module_in_halfstave[4][3] protected
Definition at line 91 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
int CylinderGeom_Mvtx::N_half_staves protected
Definition at line 66 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_N_half_staves(), and identify().
int CylinderGeom_Mvtx::N_staves protected
Definition at line 65 of file CylinderGeom_Mvtx.h.
Referenced by get_N_staves(), and identify().
double CylinderGeom_Mvtx::outer_loc_chip_in_module[14][3] protected
Definition at line 96 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::outer_loc_halfstave_in_stave[2][3] protected
Definition at line 98 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::outer_loc_module_in_halfstave[7][3] protected
Definition at line 97 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::pixel_thickness protected
Definition at line 102 of file CylinderGeom_Mvtx.h.
Referenced by get_pixel_thickness(), and identify().
double CylinderGeom_Mvtx::pixel_x protected
Definition at line 100 of file CylinderGeom_Mvtx.h.
Referenced by get_local_coords_from_pixel(), get_NX(), get_pixel_from_local_coords(), get_pixel_x(), and identify().
double CylinderGeom_Mvtx::pixel_z protected
Definition at line 101 of file CylinderGeom_Mvtx.h.
Referenced by get_local_coords_from_pixel(), get_NZ(), get_pixel_from_local_coords(), get_pixel_z(), and identify().
double CylinderGeom_Mvtx::stave_phi_step protected
Definition at line 73 of file CylinderGeom_Mvtx.h.
Referenced by get_local_from_world_coords(), and get_world_from_local_coords().
double CylinderGeom_Mvtx::stave_phi_tilt protected
Definition at line 74 of file CylinderGeom_Mvtx.h.
Referenced by get_local_from_world_coords(), get_stave_phi_tilt(), and get_world_from_local_coords().
int CylinderGeom_Mvtx::stave_type protected
Definition at line 64 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), get_ladder_phi_index(), get_ladder_z_index(), get_local_from_world_coords(), get_world_from_local_coords(), and identify().
double CylinderGeom_Mvtx::Xsensor protected
Definition at line 68 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), and get_NX().
double CylinderGeom_Mvtx::Zsensor protected
Definition at line 69 of file CylinderGeom_Mvtx.h.
Referenced by CylinderGeom_Mvtx(), and get_NZ().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/mvtx/CylinderGeom_Mvtx.h
coresoftware/blob/master/offline/packages/mvtx/CylinderGeom_Mvtx.cc