Analysis Software: PHGenFit::Track Class Reference
PHGenFit::Track Class Reference
#include <coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Track.h>
Public Member Functions
Track (genfit::AbsTrackRep *rep, TVector3 seed_pos, TVector3 seed_mom, TMatrixDSym seed_cov, const int v=0)
Default ctor.
Track (const PHGenFit::Track &t)
Copy constructor.
~Track ()
Default dtor.
int addMeasurement (PHGenFit::Measurement *measurement)
Add measurement.
int addMeasurements (std::vector< PHGenFit::Measurement * > &measurements)
int deleteLastMeasurement ()
int updateOneMeasurementKalman (const std::vector< PHGenFit::Measurement * > &measurements, std::map< double, std::shared_ptr< PHGenFit::Track > > &incr_chi2s_new_tracks, const int base_tp_idx=-1, const int direction=1, const float blowup_factor=1., const bool use_fitted_state=false) const
double extrapolateToPlane (genfit::MeasuredStateOnPlane &state, TVector3 O, TVector3 n, const int tr_point_id=0) const
double extrapolateToLine (genfit::MeasuredStateOnPlane &state, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0) const
double extrapolateToCylinder (genfit::MeasuredStateOnPlane &state, double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0, const int direction=1) const
double extrapolateToPoint (genfit::MeasuredStateOnPlane &state, TVector3 P, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToPlane (TVector3 O, TVector3 n, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToLine (TVector3 line_point, TVector3 line_direction, const int tr_point_id=0) const
genfit::MeasuredStateOnPlane * extrapolateToCylinder (double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id=0, const int direction=1) const
genfit::MeasuredStateOnPlane * extrapolateToPoint (TVector3 P, const int tr_point_id=0) const
genfit::Track * getGenFitTrack ()
genfit::Track * getGenFitTrack () const
double get_chi2 () const
double get_ndf () const
double get_charge () const
TVector3 get_mom () const
const std::vector< unsigned int > & get_cluster_IDs () const
void set_cluster_IDs (const std::vector< unsigned int > &clusterIDs)
const std::vector
< TrkrDefs::cluskey > & get_cluster_keys () const
void set_cluster_keys (const std::vector< TrkrDefs::cluskey > &clusterkeys)
void set_vertex_id (const unsigned int vert_id)
unsigned int get_vertex_id ()
int get_verbosity () const
void set_verbosity (int verbosity)
Private Member Functions
Track operator= (Track &trk)=delete
Private Attributes
int verbosity
genfit::Track * _track
std::vector< unsigned int > _clusterIDs
std::vector< TrkrDefs::cluskey > _clusterkeys
unsigned int _vertex_id
Detailed Description
Definition at line 34 of file Track.h.
Constructor & Destructor Documentation
PHGenFit::Track::Track (genfit::AbsTrackRep * rep, TVector3 seed_pos, TVector3 seed_mom, TMatrixDSym seed_cov, const int v = 0)
Default ctor.
Definition at line 62 of file Track.cc.
References _track, v, and verbosity.
PHGenFit::Track::Track (const PHGenFit::Track & t)
Copy constructor.
Definition at line 80 of file Track.cc.
References _clusterIDs, _clusterkeys, _track, get_cluster_IDs(), get_cluster_keys(), getGenFitTrack(), and verbosity.
PHGenFit::Track::~Track ()
Default dtor.
Definition at line 133 of file Track.cc.
References _clusterIDs, _clusterkeys, and _track.
Member Function Documentation
int PHGenFit::Track::addMeasurement (PHGenFit::Measurement * measurement)
Add measurement.
Definition at line 88 of file Track.cc.
References _clusterIDs, _clusterkeys, _track, PHGenFit::Measurement::get_cluster_ID(), PHGenFit::Measurement::get_cluster_key(), and PHGenFit::Measurement::getMeasurement().
int PHGenFit::Track::addMeasurements (std::vector< PHGenFit::Measurement * > & measurements)
Definition at line 102 of file Track.cc.
References _clusterIDs, _clusterkeys, and _track.
Referenced by main(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeGenFitTrack(), and PHG4TrackFastSim::process_event().
int PHGenFit::Track::deleteLastMeasurement ()
Definition at line 123 of file Track.cc.
References _clusterIDs, _clusterkeys, and _track.
double PHGenFit::Track::extrapolateToCylinder (genfit::MeasuredStateOnPlane & state, double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0, const int direction = 1) const
Definition at line 244 of file Track.cc.
References _track, assert, LogError, LogWarning, verbosity, and WILD_DOUBLE.
Referenced by extrapolateToCylinder(), main(), and PHG4TrackFastSim::MakeSvtxTrack().
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToCylinder (double radius, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0, const int direction = 1) const
Definition at line 346 of file Track.cc.
References assert, extrapolateToCylinder(), and WILD_DOUBLE.
double PHGenFit::Track::extrapolateToLine (genfit::MeasuredStateOnPlane & state, TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0) const
Definition at line 197 of file Track.cc.
References _track, and WILD_DOUBLE.
Referenced by extrapolateToLine(), main(), SVReco::MakeSvtxTrack(), and PHG4TrackFastSim::MakeSvtxTrack().
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToLine (TVector3 line_point, TVector3 line_direction, const int tr_point_id = 0) const
Definition at line 231 of file Track.cc.
References extrapolateToLine(), and WILD_DOUBLE.
double PHGenFit::Track::extrapolateToPlane (genfit::MeasuredStateOnPlane & state, TVector3 O, TVector3 n, const int tr_point_id = 0) const
track_point 0 is the first one, and -1 is the last one
Definition at line 148 of file Track.cc.
References _track, and WILD_DOUBLE.
Referenced by extrapolateToPlane(), and PHG4TrackFastSim::MakeSvtxTrack().
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToPlane (TVector3 O, TVector3 n, const int tr_point_id = 0) const
Definition at line 184 of file Track.cc.
References extrapolateToPlane(), and WILD_DOUBLE.
double PHGenFit::Track::extrapolateToPoint (genfit::MeasuredStateOnPlane & state, TVector3 P, const int tr_point_id = 0) const
Definition at line 719 of file Track.cc.
References _track, and WILD_DOUBLE.
Referenced by extrapolateToPoint(), BDiJetModule::MakeGenFitTrack(), SVReco::MakeSvtxTrack(), and SVReco::printGenFitTrackKinematics().
genfit::MeasuredStateOnPlane * PHGenFit::Track::extrapolateToPoint (TVector3 P, const int tr_point_id = 0) const
Definition at line 752 of file Track.cc.
References extrapolateToPoint(), and WILD_DOUBLE.
double PHGenFit::Track::get_charge () const
Definition at line 793 of file Track.cc.
References _track, and verbosity.
Referenced by SVReco::MakeSvtxTrack(), and PHG4TrackFastSim::MakeSvtxTrack().
double PHGenFit::Track::get_chi2 () const
Definition at line 765 of file Track.cc.
References _track.
Referenced by SVReco::MakeSvtxTrack(), and PHG4TrackFastSim::MakeSvtxTrack().
const std::vector<unsigned int>& PHGenFit::Track::get_cluster_IDs () const inline
Definition at line 94 of file Track.h.
References _clusterIDs.
Referenced by Track().
const std::vector<TrkrDefs::cluskey>& PHGenFit::Track::get_cluster_keys () const inline
Definition at line 104 of file Track.h.
References _clusterkeys.
Referenced by Track().
TVector3 PHGenFit::Track::get_mom () const
Definition at line 834 of file Track.cc.
References _track.
double PHGenFit::Track::get_ndf () const
Definition at line 779 of file Track.cc.
References _track.
Referenced by SVReco::MakeSvtxTrack(), and PHG4TrackFastSim::MakeSvtxTrack().
int PHGenFit::Track::get_verbosity () const inline
Definition at line 125 of file Track.h.
References verbosity.
unsigned int PHGenFit::Track::get_vertex_id () inline
Definition at line 118 of file Track.h.
References _vertex_id.
genfit::Track* PHGenFit::Track::getGenFitTrack () inline
Definition at line 81 of file Track.h.
References _track.
Referenced by SVReco::findSecondaryVertex(), SVReco::MakeGenFitTrack(), SVReco::MakeSvtxTrack(), BDiJetModule::process_event(), PHG4TrackFastSim::process_event(), PHGenFit::Fitter::processTrack(), and Track().
genfit::Track* PHGenFit::Track::getGenFitTrack () const inline
Definition at line 83 of file Track.h.
References _track.
Track PHGenFit::Track::operator= (Track & trk) private delete
void PHGenFit::Track::set_cluster_IDs (const std::vector< unsigned int > & clusterIDs) inline
Definition at line 98 of file Track.h.
References _clusterIDs.
void PHGenFit::Track::set_cluster_keys (const std::vector< TrkrDefs::cluskey > & clusterkeys) inline
Definition at line 108 of file Track.h.
References _clusterkeys.
void PHGenFit::Track::set_verbosity (int verbosity) inline
Definition at line 130 of file Track.h.
References verbosity.
void PHGenFit::Track::set_vertex_id (const unsigned int vert_id) inline
Definition at line 113 of file Track.h.
References _vertex_id.
int PHGenFit::Track::updateOneMeasurementKalman (const std::vector< PHGenFit::Measurement * > & measurements, std::map< double, std::shared_ptr< PHGenFit::Track > > & incr_chi2s_new_tracks, const int base_tp_idx = -1, const int direction = 1, const float blowup_factor = 1., const bool use_fitted_state = false) const
A new TrackPoint created in addMeasurement PHGenFit: clusterID also registerd
Get the pointer of the TrackPoint just created
Definition at line 360 of file Track.cc.
References H, it, LogDebug, LogWarning, and verbosity.
Member Data Documentation
std::vector<unsigned int> PHGenFit::Track::_clusterIDs private
Definition at line 148 of file Track.h.
Referenced by addMeasurement(), addMeasurements(), deleteLastMeasurement(), get_cluster_IDs(), set_cluster_IDs(), Track(), and ~Track().
std::vector<TrkrDefs::cluskey> PHGenFit::Track::_clusterkeys private
Definition at line 149 of file Track.h.
Referenced by addMeasurement(), addMeasurements(), deleteLastMeasurement(), get_cluster_keys(), set_cluster_keys(), Track(), and ~Track().
genfit::Track* PHGenFit::Track::_track private
Definition at line 146 of file Track.h.
Referenced by addMeasurement(), addMeasurements(), deleteLastMeasurement(), extrapolateToCylinder(), extrapolateToLine(), extrapolateToPlane(), extrapolateToPoint(), get_charge(), get_chi2(), get_mom(), get_ndf(), getGenFitTrack(), Track(), and ~Track().
unsigned int PHGenFit::Track::_vertex_id private
Definition at line 150 of file Track.h.
Referenced by get_vertex_id(), and set_vertex_id().
int PHGenFit::Track::verbosity private
Definition at line 144 of file Track.h.
Referenced by extrapolateToCylinder(), get_charge(), get_verbosity(), set_verbosity(), Track(), and updateOneMeasurementKalman().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Track.h
coresoftware/blob/master/offline/packages/PHGenFitPkg/PHGenFit/Track.cc