Analysis Software: Proto4TowerCalib Class Reference
Proto4TowerCalib Class Reference
you get started
#include <analysis/blob/master/Prototype4/HCal/TowerCalib/Proto4TowerCalib.h>
Classes
class HCAL_Tower
Public Member Functions
Proto4TowerCalib (const std::string &filename="Proto4TowerCalib.root")
constructor
virtual ~Proto4TowerCalib ()
destructor
int Init (PHCompositeNode *topNode)
Standard function called at initialization.
int InitRun (PHCompositeNode *topNode)
Standard function called when a new run is processed.
int process_event (PHCompositeNode *topNode)
Standard function called at each event.
int End (PHCompositeNode *topNode)
Standard function called at the end of processing. Save your stuff here.
void is_sim (bool b)
Is processing simulation files?
int InitAna ()
int MakeAna ()
int FinishAna ()
void set_det (std::string detector)
void set_colID (int colID)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { n_size = 8 }
Private Member Functions
Fun4AllHistoManager * get_HistoManager ()
get manager of histograms
std::pair< int, int > find_max (RawTowerContainer *towers, int cluster_size)
int getChannelNumber (int column, int row)
bool is_sig (int colID)
int fill_sig (int colID)
int reset_pedestal ()
Private Attributes
bool _is_sim
is processing simulation files?
std::string _filename
output root file name
unsigned long _ievent
simple event counter
HCAL_Tower _tower
hcal infromation. To be copied to output TTree T
TFile * mFile_OutPut
TChain * mChainInPut
unsigned long _mStartEvent
unsigned long _mStopEvent
int _mInPut_flag
std::string _mList
std::string _mDet
int _mCol
float _mPedestal
HCAL_Tower * _mTower
TH1F * h_mHCAL [16]
float hcal_twr [16]
bool _is_sig [16]
Additional Inherited Members
Public Types inherited from Fun4AllBase
enum enu_Verbosity {
VERBOSITY_QUIET = 0, VERBOSITY_SOME = 1, VERBOSITY_MORE = 2, VERBOSITY_EVEN_MORE = 3,
VERBOSITY_A_LOT = 4, VERBOSITY_MAX = INT_MAX - 10
}
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
you get started
Definition at line 24 of file Proto4TowerCalib.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
n_size
Definition at line 165 of file Proto4TowerCalib.h.
Constructor & Destructor Documentation
Proto4TowerCalib::Proto4TowerCalib (const std::string & filename = "Proto4TowerCalib.root")
constructor
Definition at line 48 of file Proto4TowerCalib.C.
References _mCol, _mDet, _mInPut_flag, _mPedestal, _mStartEvent, _mStopEvent, _tower, Proto4TowerCalib::HCAL_Tower::reset(), reset_pedestal(), and Fun4AllBase::Verbosity().
Proto4TowerCalib::~Proto4TowerCalib () virtual
destructor
Definition at line 67 of file Proto4TowerCalib.C.
Member Function Documentation
int Proto4TowerCalib::End (PHCompositeNode * topNode) virtual
Standard function called at the end of processing. Save your stuff here.
Reimplemented from SubsysReco.
Definition at line 111 of file Proto4TowerCalib.C.
References _filename, assert, PHTFileServer::cd(), Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), Fun4AllHistoManager::getHisto(), i, and Fun4AllHistoManager::nHistos().
int Proto4TowerCalib::fill_sig (int colID) private
Definition at line 791 of file Proto4TowerCalib.C.
References getChannelNumber(), h_mHCAL, and hcal_twr.
Referenced by MakeAna().
pair< int, int > Proto4TowerCalib::find_max (RawTowerContainer * towers, int cluster_size) private
Definition at line 574 of file Proto4TowerCalib.C.
References assert, col, energy, RawTower::get_energy(), RawTowerContainer::getTower(), max, n_size, and t.
int Proto4TowerCalib::FinishAna ()
Definition at line 762 of file Proto4TowerCalib.C.
References _filename, h_mHCAL, and mFile_OutPut.
Fun4AllHistoManager * Proto4TowerCalib::get_HistoManager () private
get manager of histograms
Definition at line 72 of file Proto4TowerCalib.C.
References assert, Fun4AllServer::getHistoManager(), Fun4AllServer::instance(), and Fun4AllServer::registerHistoManager().
Referenced by End(), Init(), and process_event().
int Proto4TowerCalib::getChannelNumber (int column, int row) private
Definition at line 610 of file Proto4TowerCalib.C.
References _is_sim.
Referenced by fill_sig(), is_sig(), and process_event().
int Proto4TowerCalib::Init (PHCompositeNode * topNode) virtual
Standard function called at initialization.
Envent nomalization
Reimplemented from SubsysReco.
Definition at line 127 of file Proto4TowerCalib.C.
References _filename, _ievent, _is_sim, _tower, assert, Fun4AllReturnCodes::EVENT_OK, PHTFileServer::get(), get_HistoManager(), hNormalization, PHTFileServer::open(), Fun4AllHistoManager::registerHisto(), and T.
int Proto4TowerCalib::InitAna ()
Definition at line 635 of file Proto4TowerCalib.C.
References _is_sim, _mCol, _mDet, _mInPut_flag, _mList, _mStartEvent, _mStopEvent, _mTower, h_mHCAL, in, and mChainInPut.
int Proto4TowerCalib::InitRun (PHCompositeNode * topNode) virtual
Standard function called when a new run is processed.
Reimplemented from SubsysReco.
Definition at line 91 of file Proto4TowerCalib.C.
References _ievent, Fun4AllReturnCodes::EVENT_OK, PHNodeIterator::findFirst(), PHWHERE, and Fun4AllBase::Verbosity().
bool Proto4TowerCalib::is_sig (int colID) private
Definition at line 776 of file Proto4TowerCalib.C.
References _is_sig, and getChannelNumber().
Referenced by MakeAna().
void Proto4TowerCalib::is_sim (bool b) inline
Is processing simulation files?
Definition at line 46 of file Proto4TowerCalib.h.
References _is_sim.
Referenced by Fun4All_TestBeam_HCAL_TowerCalib(), and TestBeam_HCAL_TowerCalibAna().
int Proto4TowerCalib::MakeAna ()
Definition at line 704 of file Proto4TowerCalib.C.
References _is_sig, _is_sim, _mCol, _mDet, _mPedestal, _mStartEvent, _mStopEvent, _mTower, fill_sig(), h_mHCAL, hcal_twr, Proto4TowerCalib::HCAL_Tower::hcalin_lg_twr_raw, Proto4TowerCalib::HCAL_Tower::hcalin_twr_sim, Proto4TowerCalib::HCAL_Tower::hcalout_hg_twr_raw, Proto4TowerCalib::HCAL_Tower::hcalout_twr_sim, is_sig(), mChainInPut, and reset_pedestal().
int Proto4TowerCalib::process_event (PHCompositeNode * topNode) virtual
Standard function called at each event.
Reimplemented from SubsysReco.
Definition at line 215 of file Proto4TowerCalib.C.
References _is_sim, _tower, assert, col, Fun4AllReturnCodes::EVENT_OK, RawTower::get_bineta(), RawTower::get_binphi(), RawTower::get_energy(), get_HistoManager(), PHG4Particle::get_vtx_id(), getChannelNumber(), findNode::getClass(), Fun4AllHistoManager::getHisto(), PHG4TruthInfoContainer::GetPrimaryParticleRange(), RawTowerContainer::getTowers(), PHG4TruthInfoContainer::GetVtx(), Proto4TowerCalib::HCAL_Tower::hcal_asym_calib, Proto4TowerCalib::HCAL_Tower::hcal_asym_raw, Proto4TowerCalib::HCAL_Tower::hcal_asym_sim, Proto4TowerCalib::HCAL_Tower::hcal_total_calib, Proto4TowerCalib::HCAL_Tower::hcal_total_raw, Proto4TowerCalib::HCAL_Tower::hcal_total_sim, Proto4TowerCalib::HCAL_Tower::hcalin_e_sim, Proto4TowerCalib::HCAL_Tower::hcalin_lg_e_calib, Proto4TowerCalib::HCAL_Tower::hcalin_lg_e_raw, Proto4TowerCalib::HCAL_Tower::hcalin_lg_twr_calib, Proto4TowerCalib::HCAL_Tower::hcalin_lg_twr_raw, Proto4TowerCalib::HCAL_Tower::hcalin_twr_sim, Proto4TowerCalib::HCAL_Tower::hcalout_e_sim, Proto4TowerCalib::HCAL_Tower::hcalout_hg_e_calib, Proto4TowerCalib::HCAL_Tower::hcalout_hg_e_raw, Proto4TowerCalib::HCAL_Tower::hcalout_hg_twr_calib, Proto4TowerCalib::HCAL_Tower::hcalout_hg_twr_raw, Proto4TowerCalib::HCAL_Tower::hcalout_lg_e_calib, Proto4TowerCalib::HCAL_Tower::hcalout_lg_e_raw, Proto4TowerCalib::HCAL_Tower::hcalout_lg_twr_calib, Proto4TowerCalib::HCAL_Tower::hcalout_lg_twr_raw, Proto4TowerCalib::HCAL_Tower::hcalout_twr_sim, hNormalization, it, Proto4TowerCalib::HCAL_Tower::reset(), T, v, and Fun4AllBase::Verbosity().
int Proto4TowerCalib::reset_pedestal () private
Definition at line 803 of file Proto4TowerCalib.C.
References _is_sig, and hcal_twr.
Referenced by MakeAna(), and Proto4TowerCalib().
void Proto4TowerCalib::set_colID (int colID) inline
Definition at line 63 of file Proto4TowerCalib.h.
References _mCol.
void Proto4TowerCalib::set_det (std::string detector) inline
Definition at line 58 of file Proto4TowerCalib.h.
References _mDet.
Member Data Documentation
std::string Proto4TowerCalib::_filename private
output root file name
Definition at line 183 of file Proto4TowerCalib.h.
Referenced by End(), FinishAna(), and Init().
unsigned long Proto4TowerCalib::_ievent private
simple event counter
Definition at line 186 of file Proto4TowerCalib.h.
Referenced by Init(), and InitRun().
bool Proto4TowerCalib::_is_sig[16] private
Definition at line 206 of file Proto4TowerCalib.h.
Referenced by is_sig(), MakeAna(), and reset_pedestal().
bool Proto4TowerCalib::_is_sim private
is processing simulation files?
Definition at line 171 of file Proto4TowerCalib.h.
Referenced by getChannelNumber(), Init(), InitAna(), is_sim(), MakeAna(), and process_event().
int Proto4TowerCalib::_mCol private
Definition at line 199 of file Proto4TowerCalib.h.
Referenced by InitAna(), MakeAna(), Proto4TowerCalib(), and set_colID().
std::string Proto4TowerCalib::_mDet private
Definition at line 198 of file Proto4TowerCalib.h.
Referenced by InitAna(), MakeAna(), Proto4TowerCalib(), and set_det().
int Proto4TowerCalib::_mInPut_flag private
Definition at line 196 of file Proto4TowerCalib.h.
Referenced by InitAna(), and Proto4TowerCalib().
std::string Proto4TowerCalib::_mList private
Definition at line 197 of file Proto4TowerCalib.h.
Referenced by InitAna().
float Proto4TowerCalib::_mPedestal private
Definition at line 200 of file Proto4TowerCalib.h.
Referenced by MakeAna(), and Proto4TowerCalib().
unsigned long Proto4TowerCalib::_mStartEvent private
Definition at line 194 of file Proto4TowerCalib.h.
Referenced by InitAna(), MakeAna(), and Proto4TowerCalib().
unsigned long Proto4TowerCalib::_mStopEvent private
Definition at line 195 of file Proto4TowerCalib.h.
Referenced by InitAna(), MakeAna(), and Proto4TowerCalib().
HCAL_Tower* Proto4TowerCalib::_mTower private
Definition at line 202 of file Proto4TowerCalib.h.
Referenced by InitAna(), and MakeAna().
HCAL_Tower Proto4TowerCalib::_tower private
hcal infromation. To be copied to output TTree T
Definition at line 189 of file Proto4TowerCalib.h.
Referenced by Init(), process_event(), and Proto4TowerCalib().
TH1F* Proto4TowerCalib::h_mHCAL[16] private
Definition at line 204 of file Proto4TowerCalib.h.
Referenced by fill_sig(), FinishAna(), InitAna(), and MakeAna().
float Proto4TowerCalib::hcal_twr[16] private
Definition at line 205 of file Proto4TowerCalib.h.
Referenced by fill_sig(), MakeAna(), and reset_pedestal().
TChain* Proto4TowerCalib::mChainInPut private
Definition at line 193 of file Proto4TowerCalib.h.
Referenced by InitAna(), and MakeAna().
TFile* Proto4TowerCalib::mFile_OutPut private
Definition at line 192 of file Proto4TowerCalib.h.
Referenced by FinishAna().
The documentation for this class was generated from the following files:
analysis/blob/master/Prototype4/HCal/TowerCalib/Proto4TowerCalib.h
analysis/blob/master/Prototype4/HCal/TowerCalib/Proto4TowerCalib.C