Analysis Software: QAG4SimulationCalorimeterSum Class Reference
QAG4SimulationCalorimeterSum Class Reference
#include <coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeterSum.h>
Public Types
enum enu_flags { kProcessCluster = 1 << 2, kProcessTrackProj = 1 << 3, kDefaultFlag = kProcessCluster | kProcessTrackProj }
Public Member Functions
QAG4SimulationCalorimeterSum (enu_flags flags=kDefaultFlag)
virtual ~QAG4SimulationCalorimeterSum ()
int Init (PHCompositeNode *topNode)
int InitRun (PHCompositeNode *topNode)
int process_event (PHCompositeNode *topNode)
uint32_t get_flags () const
void set_flags (enu_flags flags)
void set_flag (enu_flags flag)
bool flag (enu_flags flag)
void reset_flag (enu_flags flag)
std::string get_histo_prefix ()
common prefix for QA histograms
std::string get_calo_name_cemc () const
void set_calo_name_cemc (const std::string &caloNameCemc)
std::string get_calo_name_hcalin () const
void set_calo_name_hcalin (const std::string &caloNameHcalin)
std::string get_calo_name_hcalout () const
void set_calo_name_hcalout (const std::string &caloNameHcalout)
float get_mag_field () const
void set_mag_field (float magField)
Public Member Functions inherited from SubsysReco
virtual ~SubsysReco ()
virtual int End (PHCompositeNode *)
Called at the end of all processing.
virtual int EndRun (const int)
Called at the end of each run.
virtual int Reset (PHCompositeNode *)
Reset.
virtual int ResetEvent (PHCompositeNode *)
Clean up after each event.
virtual void Print (const std::string &what="ALL") const
Public Member Functions inherited from Fun4AllBase
virtual ~Fun4AllBase ()
virtual const std::string Name () const
Returns the name of this module.
virtual void Name (const std::string &name)
Sets the name of this module.
virtual void Verbosity (const int ival)
Sets the verbosity of this module (0 by default=quiet).
virtual void Verbosity (enu_Verbosity ival)
Sets the verbosity of this module (0 by default=quiet).
virtual int Verbosity () const
Gets the verbosity of this module.
Private Types
enum { Max_N_Tower = 11 }
Private Member Functions
int Init_Cluster (PHCompositeNode *topNode)
int process_event_Cluster (PHCompositeNode *topNode)
int Init_TrackProj (PHCompositeNode *topNode)
int process_event_TrackProj (PHCompositeNode *topNode)
PHG4Particle * get_truth_particle ()
fetch the truth particle to be analyzed. By default it is the last primary particle in truth container (therefore works in single particle embedding)
bool eval_trk_proj (const std::string &detector, SvtxTrack *track, PHCompositeNode *topNode)
fetch tower around track and histogram energy distributions
Private Attributes
std::shared_ptr< CaloEvalStack > _caloevalstack_cemc
std::shared_ptr< CaloEvalStack > _caloevalstack_hcalin
std::shared_ptr< CaloEvalStack > _caloevalstack_hcalout
std::shared_ptr< SvtxEvalStack > _svtxevalstack
uint32_t _flags
std::string _calo_name_cemc
std::string _calo_name_hcalin
std::string _calo_name_hcalout
PHG4TruthInfoContainer * _truth_container
float _magField
central magnetic field strength in T
Additional Inherited Members
Protected Member Functions inherited from SubsysReco
SubsysReco (const std::string &name="NONAME")
Detailed Description
Definition at line 23 of file QAG4SimulationCalorimeterSum.h.
Member Enumeration Documentation
anonymous enum private
Enumerator:
Max_N_Tower
max number of tower row/column to process around a track projection
Definition at line 156 of file QAG4SimulationCalorimeterSum.h.
enum QAG4SimulationCalorimeterSum::enu_flags
Enumerator:
kProcessCluster
kProcessTrackProj
kDefaultFlag
Definition at line 26 of file QAG4SimulationCalorimeterSum.h.
Constructor & Destructor Documentation
QAG4SimulationCalorimeterSum::QAG4SimulationCalorimeterSum (QAG4SimulationCalorimeterSum::enu_flags flags = kDefaultFlag)
Definition at line 42 of file QAG4SimulationCalorimeterSum.cc.
virtual QAG4SimulationCalorimeterSum::~QAG4SimulationCalorimeterSum () inline virtual
Definition at line 37 of file QAG4SimulationCalorimeterSum.h.
Member Function Documentation
bool QAG4SimulationCalorimeterSum::eval_trk_proj (const std::string & detector, SvtxTrack * track, PHCompositeNode * topNode) private
fetch tower around track and histogram energy distributions
Definition at line 299 of file QAG4SimulationCalorimeterSum.cc.
References assert, energy, RawTower::get_energy(), RawTowerGeomContainer::get_etabin(), RawTowerGeomContainer::get_etabins(), RawTowerGeomContainer::get_etabounds(), RawTowerGeomContainer::get_etacenter(), get_histo_prefix(), RawTowerGeomContainer::get_phibin(), RawTowerGeomContainer::get_phibins(), RawTowerGeomContainer::get_phibounds(), RawTowerGeomContainer::get_phicenter(), SvtxTrack::get_px(), SvtxTrack::get_py(), SvtxTrack::get_pz(), SvtxTrack::get_x(), SvtxTrack::get_z(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), RawTowerContainer::getTower(), RawTowerGeomContainer::identify(), M_PI, Max_N_Tower, phi, SvtxTrack::size_states(), Fun4AllBase::Verbosity(), x, y, and z.
Referenced by process_event_TrackProj().
bool QAG4SimulationCalorimeterSum::flag (enu_flags flag) inline
Definition at line 62 of file QAG4SimulationCalorimeterSum.h.
References _flags.
Referenced by Init(), InitRun(), and process_event().
std::string QAG4SimulationCalorimeterSum::get_calo_name_cemc () const inline
Definition at line 78 of file QAG4SimulationCalorimeterSum.h.
References _calo_name_cemc.
std::string QAG4SimulationCalorimeterSum::get_calo_name_hcalin () const inline
Definition at line 90 of file QAG4SimulationCalorimeterSum.h.
References _calo_name_hcalin.
std::string QAG4SimulationCalorimeterSum::get_calo_name_hcalout () const inline
Definition at line 102 of file QAG4SimulationCalorimeterSum.h.
References _calo_name_hcalout.
uint32_t QAG4SimulationCalorimeterSum::get_flags () const inline
Definition at line 44 of file QAG4SimulationCalorimeterSum.h.
References _flags.
string QAG4SimulationCalorimeterSum::get_histo_prefix ()
common prefix for QA histograms
Definition at line 196 of file QAG4SimulationCalorimeterSum.cc.
Referenced by eval_trk_proj(), Init(), Init_Cluster(), Init_TrackProj(), process_event(), process_event_Cluster(), and process_event_TrackProj().
float QAG4SimulationCalorimeterSum::get_mag_field () const inline
Definition at line 113 of file QAG4SimulationCalorimeterSum.h.
References _magField.
PHG4Particle * QAG4SimulationCalorimeterSum::get_truth_particle () private
fetch the truth particle to be analyzed. By default it is the last primary particle in truth container (therefore works in single particle embedding)
Definition at line 202 of file QAG4SimulationCalorimeterSum.cc.
References _truth_container, assert, and PHG4TruthInfoContainer::GetMap().
Referenced by process_event_Cluster(), and process_event_TrackProj().
int QAG4SimulationCalorimeterSum::Init (PHCompositeNode *) virtual
Called during initialization. Typically this is where you can book histograms, and e.g. register them to Fun4AllServer (so they can be output to file using Fun4AllServer::dumpHistos() method).
Reimplemented from SubsysReco.
Definition at line 103 of file QAG4SimulationCalorimeterSum.cc.
References _calo_name_cemc, _calo_name_hcalin, _calo_name_hcalout, assert, Fun4AllReturnCodes::EVENT_OK, flag(), get_histo_prefix(), QAHistManagerDef::getHistoManager(), SVM_v1::h, i, Init_Cluster(), Init_TrackProj(), kProcessCluster, kProcessTrackProj, Fun4AllHistoManager::registerHisto(), and Fun4AllBase::Verbosity().
int QAG4SimulationCalorimeterSum::Init_Cluster (PHCompositeNode * topNode) private
Definition at line 473 of file QAG4SimulationCalorimeterSum.cc.
References _calo_name_cemc, _calo_name_hcalin, _calo_name_hcalout, assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), and Fun4AllHistoManager::registerHisto().
Referenced by Init().
int QAG4SimulationCalorimeterSum::Init_TrackProj (PHCompositeNode * topNode) private
Definition at line 213 of file QAG4SimulationCalorimeterSum.cc.
References _calo_name_cemc, _calo_name_hcalin, _calo_name_hcalout, assert, Fun4AllReturnCodes::EVENT_OK, get_histo_prefix(), QAHistManagerDef::getHistoManager(), Max_N_Tower, and Fun4AllHistoManager::registerHisto().
Referenced by Init().
int QAG4SimulationCalorimeterSum::InitRun (PHCompositeNode *) virtual
Called for first event when run number is known. Typically this is where you may want to fetch data from database, because you know the run number.
Reimplemented from SubsysReco.
Definition at line 54 of file QAG4SimulationCalorimeterSum.cc.
References _calo_name_cemc, _calo_name_hcalin, _calo_name_hcalout, _caloevalstack_cemc, _caloevalstack_hcalin, _caloevalstack_hcalout, _svtxevalstack, _truth_container, assert, Fun4AllReturnCodes::EVENT_OK, flag(), kProcessCluster, kProcessTrackProj, and Fun4AllBase::Verbosity().
int QAG4SimulationCalorimeterSum::process_event (PHCompositeNode *) virtual
Called for each event. This is where you do the real work.
Reimplemented from SubsysReco.
Definition at line 146 of file QAG4SimulationCalorimeterSum.cc.
References _caloevalstack_cemc, _caloevalstack_hcalin, _caloevalstack_hcalout, _svtxevalstack, assert, Fun4AllReturnCodes::EVENT_OK, flag(), get_histo_prefix(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), kProcessCluster, kProcessTrackProj, process_event_Cluster(), process_event_TrackProj(), and Fun4AllBase::Verbosity().
int QAG4SimulationCalorimeterSum::process_event_Cluster (PHCompositeNode * topNode) private
Definition at line 508 of file QAG4SimulationCalorimeterSum.cc.
References _calo_name_cemc, _calo_name_hcalin, _calo_name_hcalout, _caloevalstack_cemc, _caloevalstack_hcalin, _caloevalstack_hcalout, assert, Fun4AllReturnCodes::DISCARDEVENT, Fun4AllReturnCodes::EVENT_OK, PHG4Particle::get_e(), RawCluster::get_energy(), get_histo_prefix(), get_truth_particle(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), h2, and Fun4AllBase::Verbosity().
Referenced by process_event().
int QAG4SimulationCalorimeterSum::process_event_TrackProj (PHCompositeNode * topNode) private
Definition at line 252 of file QAG4SimulationCalorimeterSum.cc.
References _calo_name_cemc, _calo_name_hcalin, _calo_name_hcalout, _svtxevalstack, assert, SvtxTrackEval::best_track_from(), SvtxTrack::CEMC, Fun4AllReturnCodes::DISCARDEVENT, eval_trk_proj(), Fun4AllReturnCodes::EVENT_OK, SvtxTrack::get_cal_energy_3x3(), SvtxTrack::get_cal_energy_5x5(), PHG4Particle::get_e(), get_histo_prefix(), get_truth_particle(), Fun4AllHistoManager::getHisto(), QAHistManagerDef::getHistoManager(), SvtxTrack::HCALIN, SvtxTrack::HCALOUT, and Fun4AllBase::Verbosity().
Referenced by process_event().
void QAG4SimulationCalorimeterSum::reset_flag (enu_flags flag) inline
Definition at line 68 of file QAG4SimulationCalorimeterSum.h.
References _flags.
void QAG4SimulationCalorimeterSum::set_calo_name_cemc (const std::string & caloNameCemc) inline
Definition at line 84 of file QAG4SimulationCalorimeterSum.h.
References _calo_name_cemc.
void QAG4SimulationCalorimeterSum::set_calo_name_hcalin (const std::string & caloNameHcalin) inline
Definition at line 96 of file QAG4SimulationCalorimeterSum.h.
References _calo_name_hcalin.
void QAG4SimulationCalorimeterSum::set_calo_name_hcalout (const std::string & caloNameHcalout) inline
Definition at line 108 of file QAG4SimulationCalorimeterSum.h.
References _calo_name_hcalout.
void QAG4SimulationCalorimeterSum::set_flag (enu_flags flag) inline
Definition at line 56 of file QAG4SimulationCalorimeterSum.h.
References _flags.
void QAG4SimulationCalorimeterSum::set_flags (enu_flags flags) inline
Definition at line 50 of file QAG4SimulationCalorimeterSum.h.
References _flags.
void QAG4SimulationCalorimeterSum::set_mag_field (float magField) inline
Definition at line 114 of file QAG4SimulationCalorimeterSum.h.
References _magField.
Member Data Documentation
std::string QAG4SimulationCalorimeterSum::_calo_name_cemc private
Definition at line 138 of file QAG4SimulationCalorimeterSum.h.
Referenced by get_calo_name_cemc(), Init(), Init_Cluster(), Init_TrackProj(), InitRun(), process_event_Cluster(), process_event_TrackProj(), and set_calo_name_cemc().
std::string QAG4SimulationCalorimeterSum::_calo_name_hcalin private
Definition at line 139 of file QAG4SimulationCalorimeterSum.h.
Referenced by get_calo_name_hcalin(), Init(), Init_Cluster(), Init_TrackProj(), InitRun(), process_event_Cluster(), process_event_TrackProj(), and set_calo_name_hcalin().
std::string QAG4SimulationCalorimeterSum::_calo_name_hcalout private
Definition at line 140 of file QAG4SimulationCalorimeterSum.h.
Referenced by get_calo_name_hcalout(), Init(), Init_Cluster(), Init_TrackProj(), InitRun(), process_event_Cluster(), process_event_TrackProj(), and set_calo_name_hcalout().
std::shared_ptr<CaloEvalStack> QAG4SimulationCalorimeterSum::_caloevalstack_cemc private
Definition at line 130 of file QAG4SimulationCalorimeterSum.h.
Referenced by InitRun(), process_event(), and process_event_Cluster().
std::shared_ptr<CaloEvalStack> QAG4SimulationCalorimeterSum::_caloevalstack_hcalin private
Definition at line 131 of file QAG4SimulationCalorimeterSum.h.
Referenced by InitRun(), process_event(), and process_event_Cluster().
std::shared_ptr<CaloEvalStack> QAG4SimulationCalorimeterSum::_caloevalstack_hcalout private
Definition at line 132 of file QAG4SimulationCalorimeterSum.h.
Referenced by InitRun(), process_event(), and process_event_Cluster().
uint32_t QAG4SimulationCalorimeterSum::_flags private
Definition at line 136 of file QAG4SimulationCalorimeterSum.h.
Referenced by flag(), get_flags(), reset_flag(), set_flag(), and set_flags().
float QAG4SimulationCalorimeterSum::_magField private
central magnetic field strength in T
Definition at line 154 of file QAG4SimulationCalorimeterSum.h.
Referenced by get_mag_field(), and set_mag_field().
std::shared_ptr<SvtxEvalStack> QAG4SimulationCalorimeterSum::_svtxevalstack private
Definition at line 133 of file QAG4SimulationCalorimeterSum.h.
Referenced by InitRun(), process_event(), and process_event_TrackProj().
PHG4TruthInfoContainer* QAG4SimulationCalorimeterSum::_truth_container private
Definition at line 142 of file QAG4SimulationCalorimeterSum.h.
Referenced by get_truth_particle(), and InitRun().
The documentation for this class was generated from the following files:
coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeterSum.h
coresoftware/blob/master/offline/QA/modules/QAG4SimulationCalorimeterSum.cc