Analysis Software: analysis/blob/master/ForwardCalo/JetEnergyResolution/fjetResol.C File Reference
fjetResol.C File Reference
#include <TCanvas.h>
#include <TFile.h>
#include <TF1.h>
#include <TGraph.h>
#include <TGraphErrors.h>
#include <TH1.h>
#include <TH2.h>
#include <TLatex.h>
#include <TLegend.h>
#include <TNtuple.h>
#include <TString.h>
#include <TStyle.h>
#include <iostream>
Functions
std::vector< int > searchLeadingJets (TNtuple *T, float cutPT, const char *targetV="gpt")
void fjetResol (const char *path="/gpfs/mnt/gpfs04/sphenix/user/ckim/fjets/Ana/results_1121", const char *var="e", const char *suffix="", bool print=true)
Function Documentation
void fjetResol (const char * path = "/gpfs/mnt/gpfs04/sphenix/user/ckim/fjets/Ana/results_1121", const char * var = "e", const char * suffix = "", bool print = true)
Definition at line 41 of file fjetResol.C.
References c, c2, d, F, h1, h2, i, SVM_v1::id_e, path, phi, print(), searchLeadingJets(), T, x, and y.
std::vector< int > searchLeadingJets (TNtuple * T, float cutPT, const char * targetV = "gpt")
Definition at line 217 of file fjetResol.C.
Referenced by fjetResol().