Analysis Software: online_distribution/blob/master/newbasic/errorBlock.h File Reference
errorBlock.h File Reference
#include "phenixOnline.h"
Classes
struct errorEntryV1
Macros
#define ERROR_ENTRY_V1_LENGTH sizeof(ERRORENTRYV1)/4
Typedefs
typedef struct errorEntryV1 ERRORENTRYV1
typedef struct errorEntryV1 * ERRORENTRYV1_ptr
Enumerations
enum daqErrorCodes { InvalidFrameHeader = 1, InvalidSourceId = 2, InvalidFrameType = 3 }
Functions
VALUE_ret calcNumErrorsV1 (UINT)
void endianSwapErrorV1 (ERRORENTRYV1_ptr, ERRORENTRYV1_ptr)
Variables
CONSTANT UINT errorEntryV1Length = ERROR_ENTRY_V1_LENGTH
Macro Definition Documentation
#define ERROR_ENTRY_V1_LENGTH sizeof(ERRORENTRYV1)/4
Definition at line 48 of file errorBlock.h.
Typedef Documentation
typedef struct errorEntryV1 ERRORENTRYV1
Definition at line 46 of file errorBlock.h.
typedef struct errorEntryV1 * ERRORENTRYV1_ptr
Definition at line 46 of file errorBlock.h.
Enumeration Type Documentation
enum daqErrorCodes
Enumerator:
InvalidFrameHeader
InvalidSourceId
InvalidFrameType
Definition at line 51 of file errorBlock.h.
Function Documentation
VALUE_ret calcNumErrorsV1 (UINT)
Definition at line 18 of file errorBlock.C.
References errorEntryV1Length, and valueFailure.
Referenced by A_Event::dumpErrorBlock(), and getPacketV1NumErrors().
void endianSwapErrorV1 (ERRORENTRYV1_ptr , ERRORENTRYV1_ptr)
Definition at line 26 of file errorBlock.C.
Referenced by endianSwapError().
Variable Documentation
CONSTANT UINT errorEntryV1Length = ERROR_ENTRY_V1_LENGTH
Definition at line 49 of file errorBlock.h.
Referenced by appendPacketError(), and calcNumErrorsV1().