Analysis Software: tutorials/blob/master/IonGun/Fun4All_G4_IonGun.C File Reference
Fun4All_G4_IonGun.C File Reference
#include <fun4all/SubsysReco.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <g4detectors/PHG4BlockSubsystem.h>
#include <g4histos/G4EdepNtuple.h>
#include <g4histos/G4HitNtuple.h>
#include <g4main/PHG4IonGun.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4PrimaryGeneratorAction.h>
#include <g4main/PHG4Reco.h>
#include <g4main/PHG4TruthSubsystem.h>
#include "GlobalVariables.h"
#include "DisplayOn.C"
Functions
void Fun4All_G4_IonGun (int nEvents=10)
PHG4IonGun * getgun ()
Function Documentation
void Fun4All_G4_IonGun (int nEvents = 10)
Definition at line 26 of file Fun4All_G4_IonGun.C.
References G4EdepNtuple::AddNode(), G4HitNtuple::AddNode(), Fun4AllServer::End(), igun, in, Fun4AllServer::instance(), nEvents, Fun4AllServer::registerInputManager(), Fun4AllServer::registerOutputManager(), Fun4AllServer::registerSubsystem(), PHG4Reco::registerSubsystem(), Fun4AllServer::run(), PHG4DetectorSubsystem::set_double_param(), PHG4Reco::set_field(), PHG4DetectorSubsystem::set_int_param(), PHG4DetectorSubsystem::set_string_param(), PHG4IonGun::SetA(), PHG4DetectorSubsystem::SetActive(), PHG4IonGun::SetCharge(), PHG4IonGun::SetMom(), PHG4Reco::SetPhysicsList(), PHG4Reco::SetWorldMaterial(), PHG4Reco::SetWorldShape(), PHG4Reco::SetWorldSizeX(), PHG4Reco::SetWorldSizeY(), PHG4Reco::SetWorldSizeZ(), PHG4IonGun::SetZ(), and PHG4DetectorSubsystem::SuperDetector().
PHG4IonGun* getgun ()
Definition at line 129 of file Fun4All_G4_IonGun.C.
References igun.