Analysis Software: GlobalVertexMap Class Reference
GlobalVertexMap Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexMap.h>
Public Types
typedef std::map< unsigned int,
GlobalVertex * >
::const_iterator ConstIter
typedef std::map< unsigned int,
GlobalVertex * >::iterator Iter
Public Member Functions
virtual ~GlobalVertexMap ()
virtual void identify (std::ostream &os=std::cout) const
virtual void Reset ()
Clear Event.
virtual int isValid () const
isValid returns non zero if object contains vailid data
virtual bool empty () const
virtual size_t size () const
virtual size_t count (unsigned int idkey) const
virtual void clear ()
virtual const GlobalVertex * get (unsigned int idkey) const
virtual GlobalVertex * get (unsigned int idkey)
virtual GlobalVertex * insert (GlobalVertex *vertex)
virtual size_t erase (unsigned int idkey)
virtual ConstIter begin () const
virtual ConstIter find (unsigned int idkey) const
virtual ConstIter end () const
virtual Iter begin ()
virtual Iter find (unsigned int idkey)
virtual Iter end ()
Public Member Functions inherited from PHObject
PHObject ()
ctor
virtual ~PHObject ()
dtor
virtual PHObject * CloneMe () const
Virtual copy constructor.
virtual PHObject * clone () const final
virtual PHObject * Clone (const char *newname="") const final
virtual void Copy (TObject &object) const final
virtual int isValid (const float) const
virtual int isValid (const double) const
virtual int isValid (const int) const
virtual int isValid (const unsigned int) const
virtual int isImplemented (const float f) const
virtual int isImplemented (const double f) const
virtual int isImplemented (const int i) const
virtual int isImplemented (const unsigned int i) const
virtual int Integrate () const
virtual int Integrate (PHObject *obj)
virtual void CopyFrom (const PHObject *obj)
Protected Member Functions
GlobalVertexMap ()
Private Member Functions
ClassDef (GlobalVertexMap, 1)
Detailed Description
Definition at line 13 of file GlobalVertexMap.h.
Member Typedef Documentation
typedef std::map<unsigned int, GlobalVertex*>::const_iterator GlobalVertexMap::ConstIter
Definition at line 16 of file GlobalVertexMap.h.
typedef std::map<unsigned int, GlobalVertex*>::iterator GlobalVertexMap::Iter
Definition at line 17 of file GlobalVertexMap.h.
Constructor & Destructor Documentation
virtual GlobalVertexMap::~GlobalVertexMap () inline virtual
Definition at line 19 of file GlobalVertexMap.h.
GlobalVertexMap::GlobalVertexMap () inline protected
Definition at line 44 of file GlobalVertexMap.h.
Member Function Documentation
virtual ConstIter GlobalVertexMap::begin () const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 35 of file GlobalVertexMap.h.
References end().
Referenced by CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), CaloEvaluator::printOutputInfo(), ClusterIso::process_event(), Forward_pi0s::process_event(), PJTranslator::process_event(), PhotonJet::process_event(), and DumpGlobalVertexMap::process_Node().
virtual Iter GlobalVertexMap::begin () inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 39 of file GlobalVertexMap.h.
References end().
GlobalVertexMap::ClassDef (GlobalVertexMap , 1) private
virtual void GlobalVertexMap::clear () inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 28 of file GlobalVertexMap.h.
virtual size_t GlobalVertexMap::count (unsigned int idkey) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 27 of file GlobalVertexMap.h.
virtual bool GlobalVertexMap::empty () const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 25 of file GlobalVertexMap.h.
Referenced by CaloEvaluator::fillOutputNtuples(), TowerJetInput::get_input(), ClusterJetInput::get_input(), AnaTutorial::getEMCalClusters(), CaloEvaluator::printOutputInfo(), ClusterIso::process_event(), Forward_pi0s::process_event(), PJTranslator::process_event(), and PhotonJet::process_event().
virtual ConstIter GlobalVertexMap::end () const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 37 of file GlobalVertexMap.h.
References end().
Referenced by begin(), end(), find(), and DumpGlobalVertexMap::process_Node().
virtual Iter GlobalVertexMap::end () inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 41 of file GlobalVertexMap.h.
References end().
Referenced by end().
virtual size_t GlobalVertexMap::erase (unsigned int idkey) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 33 of file GlobalVertexMap.h.
virtual ConstIter GlobalVertexMap::find (unsigned int idkey) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 36 of file GlobalVertexMap.h.
References end().
virtual Iter GlobalVertexMap::find (unsigned int idkey) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 40 of file GlobalVertexMap.h.
References end().
virtual const GlobalVertex* GlobalVertexMap::get (unsigned int idkey) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 30 of file GlobalVertexMap.h.
virtual GlobalVertex* GlobalVertexMap::get (unsigned int idkey) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 31 of file GlobalVertexMap.h.
virtual void GlobalVertexMap::identify (std::ostream & os = std::cout) const inline virtual
identify Function from PHObject
Parameters
os Output Stream
Reimplemented from PHObject.
Reimplemented in GlobalVertexMapv1.
Definition at line 21 of file GlobalVertexMap.h.
References os.
virtual GlobalVertex* GlobalVertexMap::insert (GlobalVertex * vertex) inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 32 of file GlobalVertexMap.h.
Referenced by GlobalVertexReco::process_event(), and GlobalVertexFastSimReco::process_event().
virtual int GlobalVertexMap::isValid () const inline virtual
isValid returns non zero if object contains vailid data
Reimplemented from PHObject.
Reimplemented in GlobalVertexMapv1.
Definition at line 23 of file GlobalVertexMap.h.
virtual void GlobalVertexMap::Reset () inline virtual
Clear Event.
Reimplemented from PHObject.
Reimplemented in GlobalVertexMapv1.
Definition at line 22 of file GlobalVertexMap.h.
virtual size_t GlobalVertexMap::size (void) const inline virtual
Reimplemented in GlobalVertexMapv1.
Definition at line 26 of file GlobalVertexMap.h.
Referenced by DumpGlobalVertexMap::process_Node().
The documentation for this class was generated from the following file:
coresoftware/blob/master/simulation/g4simulation/g4vertex/GlobalVertexMap.h