Analysis Software: PHG4MvtxSteppingAction Class Reference
PHG4MvtxSteppingAction Class Reference
#include <coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.h>
Public Member Functions
PHG4MvtxSteppingAction (PHG4MvtxDetector *)
constructor
virtual ~PHG4MvtxSteppingAction ()
destroctor
virtual bool UserSteppingAction (const G4Step *, bool)
stepping action
virtual void SetInterfacePointers (PHCompositeNode *)
reimplemented from base class
Public Member Functions inherited from PHG4SteppingAction
PHG4SteppingAction (const std::string &name, const int i=0)
virtual ~PHG4SteppingAction ()
virtual void Verbosity (const int i)
virtual int Verbosity () const
virtual int Init ()
virtual double GetScintLightYield (const G4Step *step)
get scintillation photon count. It require a custom set SCINTILLATIONYIELD property to work
virtual double GetVisibleEnergyDeposition (const G4Step *step)
get amount of energy that can make scintillation light, in Unit of GeV.
virtual void StoreLocalCoordinate (PHG4Hit *hit, const G4Step *step, const bool do_prepoint, const bool do_postpoint)
Extract local coordinate of the hit and save to PHG4Hit.
virtual void Print (const std::string &what) const
std::string GetName () const
void SetName (const std::string &name)
virtual void SetLightCorrection (const double inner_radius, const double inner_corr, const double outer_radius, const double outer_corr)
virtual double GetLightCorrection (const double r) const
virtual double GetLightCorrection (const double xpos, const double ypos) const
virtual bool ValidCorrection () const
Private Attributes
PHG4MvtxDetector * m_Detector
pointer to the detector
PHG4HitContainer * m_HitContainer
pointer to hit container
PHG4HitContainer * m_AbsorberhitContainer
PHG4Hit * m_Hit
PHG4Shower * m_SaveShower
Detailed Description
Definition at line 15 of file PHG4MvtxSteppingAction.h.
Constructor & Destructor Documentation
PHG4MvtxSteppingAction::PHG4MvtxSteppingAction (PHG4MvtxDetector * detector)
constructor
Definition at line 55 of file PHG4MvtxSteppingAction.cc.
PHG4MvtxSteppingAction::~PHG4MvtxSteppingAction () virtual
destroctor
Definition at line 66 of file PHG4MvtxSteppingAction.cc.
References m_Hit.
Member Function Documentation
void PHG4MvtxSteppingAction::SetInterfacePointers (PHCompositeNode * topNode) virtual
reimplemented from base class
Reimplemented from PHG4SteppingAction.
Definition at line 441 of file PHG4MvtxSteppingAction.cc.
References PHG4Detector::GetName(), m_AbsorberhitContainer, m_Detector, m_HitContainer, PHG4MvtxDetector::SuperDetector(), and PHG4SteppingAction::Verbosity().
bool PHG4MvtxSteppingAction::UserSteppingAction (const G4Step * aStep, bool) virtual
stepping action
Implements PHG4SteppingAction.
Definition at line 76 of file PHG4MvtxSteppingAction.cc.
References PHG4Shower::add_g4hit_id(), PHG4HitContainer::AddHit(), PHG4Hit::get_edep(), PHG4Hit::get_hit_id(), PHG4HitContainer::GetID(), PHG4MvtxDetector::IsActive(), PHG4MvtxDetector::IsBlackHole(), PHG4MvtxDetector::IsInMvtx(), PHG4MvtxDetector::IsSensor(), m_Detector, m_Hit, m_HitContainer, m_SaveShower, PHWHERE, PHG4Hit::print(), PHG4Hit::prop_chip_index, PHG4Hit::prop_half_stave_index, PHG4Hit::prop_module_index, PHG4Hit::prop_stave_index, PHG4Hit::Reset(), PHG4Hit::set_edep(), PHG4Hit::set_layer(), PHG4Hit::set_property(), PHG4Hit::set_px(), PHG4Hit::set_py(), PHG4Hit::set_pz(), PHG4Hit::set_shower_id(), PHG4Hit::set_t(), PHG4Hit::set_trkid(), PHG4Hit::set_x(), PHG4Hit::set_y(), PHG4Hit::set_z(), PHG4SteppingAction::StoreLocalCoordinate(), v1, v2, v3, and PHG4SteppingAction::Verbosity().
Member Data Documentation
PHG4HitContainer* PHG4MvtxSteppingAction::m_AbsorberhitContainer private
Definition at line 36 of file PHG4MvtxSteppingAction.h.
Referenced by SetInterfacePointers().
PHG4MvtxDetector* PHG4MvtxSteppingAction::m_Detector private
pointer to the detector
Definition at line 32 of file PHG4MvtxSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Hit* PHG4MvtxSteppingAction::m_Hit private
Definition at line 37 of file PHG4MvtxSteppingAction.h.
Referenced by UserSteppingAction(), and ~PHG4MvtxSteppingAction().
PHG4HitContainer* PHG4MvtxSteppingAction::m_HitContainer private
pointer to hit container
Definition at line 35 of file PHG4MvtxSteppingAction.h.
Referenced by SetInterfacePointers(), and UserSteppingAction().
PHG4Shower* PHG4MvtxSteppingAction::m_SaveShower private
Definition at line 38 of file PHG4MvtxSteppingAction.h.
Referenced by UserSteppingAction().
The documentation for this class was generated from the following files:
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.h
coresoftware/blob/master/simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc